### ISSUE TITLE
Merge issue labels "adoptme" + "help wanted" and "low hanging fruit" + "good first issue"

### ISSUE THREAD

**Issue by xeraa** [elastic/logstash#10002]
Elasticsearch just renamed their issue labels "adoptme" to "help wanted" and "low hanging fruit" to "good first issue", which is also in line with the [special labels GitHub supports](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/). IMO it would be cool if we could stick to the convention and also keep it in sync across projects :)

In Logstash we have both, but from what I could tell we are mostly using the old format. Could we just combine them? I guess it would be easiest to rename the old issues and switch the label on the others.

PS: If we keep the old names in the label descriptions the autocomplete will still work with the old name as well.

**Comment by xeraa** [comment]
ping @jsvd — Kibana, Beats, and APM are already using the GitHub convention.

**Comment by jsvd** [comment]
All open "adopt me" issues/prs have been relabelled as "help wanted" and all "low hanging fruit" to "good first issue". The old labels have been deleted.
This is a good initiative, thanks for the heads up, Philipp
