### ISSUE TITLE
[Docs] Clarify inability to utilize CPM & local pipeline configuration simultaneously across all CPM docs

### ISSUE THREAD

**Issue by mikeisonthenets** [elastic/logstash#10014]
Request to add a note to https://www.elastic.co/guide/en/logstash/6.x/logstash-centralized-pipeline-management.html that clearly states that it's not possible to specify local pipeline configurations if LS is set-up to use CPM as is included in https://www.elastic.co/guide/en/logstash/6.x/configuring-centralized-pipelines.html

Searching this question via Google and internal `elastic.co` search tends to surface the page under the `Manage Logstash` heading first where this limitation is not articulated. 

I've seen many instances where users were unsure, and I shared that uncertainty until calling in an assist and doing additional digging. 🤓

**Comment by karenzone** [comment]
Fixed with #10028. Thanks for the suggestion
