### ISSUE TITLE
Integration tests from os_spec related to cgroups are failing

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#10022]
Some recent examples from two different branches:

https://logstash-ci.elastic.co/job/elastic+logstash+6.4+multijob-unix-compatibility/os=amazon/40/console
https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=amazon/32/console

**Comment by jsvd** [comment]
@guyboertje please check if this could be related to the recent cgroups fix: https://github.com/elastic/logstash/pull/9999

**Comment by guyboertje** [comment]
It is.

I didn't know that that spec also mocked the same things that the previous cgroups spec did.

I will fix it.
