### ISSUE TITLE
logstash output plugin creation guide is not working

### ISSUE THREAD

**Issue by mjnorman** [elastic/logstash#10042]
Hello all.  I also posted this on the Elastic forums, and don't seem to be getting any info there after several bumps.  I am attempting to follow the official guide [here](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html).

Forum post [here](https://discuss.elastic.co/t/creating-an-output-plugin-guide-not-working/150432).

Ruby versions:
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit...

Windows 10

Steps to reproduce--

Download logstash 6.4.1.zip extract.
Using the bin/logstash-plugin module, I created the output plugin, no issues. Modify the gemspec file to include some test summary/description.
Add `gem "logstash", :github => "elastic/logstash", :branch => "6.4"` to Gemfile as per directions. However this didn't work so I had to change to `logstash-core`, doc out of date?
No other code changes.
Push to github
Move to new directory
git clone mytestplugin
bundle install (no issues)
bundle exec rspec (this reports 0 examples, 0 failures)
Also tried bundle exec rspec spec gives the below error:

```An error occurred while loading ./spec/outputs/mytestseq_spec.rb.
Failure/Error: # encoding: utf-8

RuntimeError:


        you might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command

  no such file to load -- org/apache/logging/log4j/log4j-core/compile/log4j-core-compile-2.6.2 (LoadError)
# ./spec/outputs/mytestseq_spec.rb:1:in `(root)'
# ./spec/outputs/mytestseq_spec.rb:2:in `(root)'
# c:\jruby-9.2.0.0\bin\rspec:23:in `<main>'
# ------------------
# --- Caused by: ---
# LoadError:
#   no such file to load -- org/apache/logging/log4j/log4j-core/compile/log4j-core-compile-2.6.2
#   ./spec/outputs/mytestseq_spec.rb:1:in `(root)'
No examples found.


Finished in 0.011 seconds (files took 1.71 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by AustinTaghaviAmazon** [comment]
Were you ever able to resolve this? I am seeing this now.

**Comment by mjnorman** [comment]
I honestly do not recall.  I moved away from needing to solve this problem.

Michael J Norman
NCO
Comcast

________________________________
