### ISSUE TITLE
How to configure Management and monitoring？

### ISSUE THREAD

**Issue by CyanPhish** [elastic/logstash#10055]
Version: logstash 6.2.4 ,elasticsearch 6.2.4, kibana 6.2.4 and all of them with the xpack.

I want to configure centralized pipeline Management and Monitoring for logstash node. The following is my configuration. 

logstash.yml
> node.name: test
> pipeline.id: main
> xpack.monitoring.enabled: true
> xpack.monitoring.elasticsearch.url: "http://xx.xx.xx.xx:9200"
> xpack.management.enabled: true
> xpack.management.elasticsearch.url: "http://xx.xx.xx.xx:9200"

elasticsearch.yml
> cluster.name: test-elasticsearch
> node.name: test-node
> node.master: true
> node.data: true
> ......
> xpack.security.enaled: false

kibana.yml
> server.port: "5601"
> server.host: "xx.xx.xx.xx"
> xpack.security.enabled: false

There was throwing an error when logstash is startuped.

> [FATAL] [logstash.runner          ] An unexpected error occured! {:error=>#<ArgumentError: You must set the password using the "xpack.management.elasticsearch.password" in logstash.yml>,.......}

but I had setted the security is false already. Anybody help me ? please....

**Comment by remd** [comment]
It looks like `xpack.security.enabled` is a typo in your elasticsearch.yml.
