### ISSUE TITLE
Enhance `GET /` API for Metricbeat monitoring

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#10121]
### Background

Today, when the `xpack.monitoring.*` settings are configured in `logstash.yml`, Logstash performs _internal_ collection of it's own monitoring metrics and ships them to `.monitoring-logstash-*`. The Monitoring UI in Kibana then reads documents from these indices to create visualizations of a user's Logstash instances and pipelines.

In the future, we're aiming to have Metricbeat _externally_ collect Logstash metrics and ship them to `.monitoring-logstash-*` indices. This will mean that Metricbeat has to poll various Logstash HTTP APIs to collect said metrics.

### The Request

Currently the `GET /` API returns much of the Logstash node information that Metricbeat will need in order to build the documents to be indexed into `.monitoring-logstash-*`. However, there are a few additional pieces of information that this API would need to return to complete the picture:

* `status`: Status of node (`green`, etc.)
* `ephemeral_id`: Ephemeral ID of node
* `uuid`: Persistent UUID of node
* `name`: Name of node, could be different from `host`
* `snapshot`: Whether the node is working off a snapshot build

Here is an example JSON document showing **just these additional fields**:

```json
{
  "status": "green",
  "ephemeral_id":"6d69db08-f2a5-411f-81cf-0f395d5de358",
  "uuid":"7565df20-c3aa-4261-81d5-3b0ab8d15c16",
  "name":"Shaunaks-MBP-2",
  "snapshot": false
}
```

**Comment by jsvd** [comment]
> status

Not sure what this currently means we don't have a measure of status in logstash

> "name":"Shaunaks-MBP-2",
>  "snapshot": false

we have these already: 

```
% curl -s localhost:9600 | jq ".build_snapshot"
false
% curl -s localhost:9600 | jq ".name"
"test"
```

**Comment by ycombinator** [comment]
Thanks @jsvd.

>  I've checked and "status" is always "green", should we still generate it?

I think yes. The Monitoring UI is depending on this field and ideally LS should be the source-of-truth for it anyway (as opposed to something external to LS trying to figure out the status from other fields). That way it's part of the contract and LS is free to compute it differently in the future.

**Comment by cachedout** [comment]
@jsvd Is there anything special I need to do in order to display `.build_snapshot`? Here is what I am seeing at the head of the master branch:

```
Mikes-MBP:~ mp$ curl -s localhost:9600 | jq
{
  "host": "Mikes-MBP",
  "version": "8.0.0",
  "http_address": "127.0.0.1:9600",
  "id": "0c656d92-c5f7-4965-80ee-9bef8e1e58ec",
  "name": "Mikes-MBP"
}
```

**Comment by jsvd** [comment]
@cachedout currently the snapshot information is only placed inside artifacts, it's not included when building locally for testing.
So right now we only send this information when it's available, do you think you can work with this constraint (of maybe not being there) or is this now blocked?

**Comment by cachedout** [comment]
@ycombinator Do you know how the snapshot information is used by stack monitoring after it's collected?

**Comment by ycombinator** [comment]
I just grep'd the Kibana Stack Monitoring source code for `snapshot` and no files related to Logstash came up. So I'm fairly certain this field is not being used by the Stack Monitoring UI.

When we build the Metricbeat collector that calls this API, we'll collect this field only if it exists.

**Comment by cachedout** [comment]
@ycombinator Sounds good. The field is now present but the key will be empty unless we detect a build that contains snapshot data.

**Comment by ycombinator** [comment]
There is one more field that is seen in Stack Monitoring data in `.monitoring-logstash-*` indices for docs with `type: logstash_stats`, under the `logstash` field:

```
"pipeline" : {
  "batch_size" : 125,
  "workers" : 8
}
```

Could the `GET /` API return this field too, please?

**Comment by cachedout** [comment]
@ycombinator Most certainly. I am on the case!

**Comment by ycombinator** [comment]
> Most certainly. I am on the case!

@cachedout Did you implement this? I'm running the latest Logstash from `master` and I'm not seeing the `pipeline` field when I call http://localhost:9600/.

**Comment by ycombinator** [comment]
@cachedout I think this issue can be closed now?
