### ISSUE TITLE
Logstash 6.4.3 does not include logstash-input-tcp 5.1.0

### ISSUE THREAD

**Issue by praseodym** [elastic/logstash#10154]
The [Logstash 6.4.3 release notes](https://github.com/elastic/logstash/blob/c52cf9f69c05bc239221763b1f93275b9ce6948c/docs/static/releasenotes.asciidoc#plugins) include the following paragraph:
> Tcp Input
>    Added new configuration option dns_reverse_lookup_enabled to allow users to disable costly DNS reverse lookups

This change was [included in logstash-input-tcp v5.1.0](https://github.com/logstash-plugins/logstash-input-tcp/commit/3cadde60bfd994f3ef457fcd4b98c840db1ca4e0). However, Logstash 6.4.3 only includes v5.0.10 of this plugin:
```
$ tar tf logstash-6.4.3.tar.gz | grep logstash-input-tcp.gemspec
logstash-6.4.3/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-5.0.10-java/logstash-input-tcp.gemspec
```
This version of the plugin [does not support the new `dns_reverse_lookup_enabled` option](https://github.com/logstash-plugins/logstash-input-tcp/commits/v5.0.10), so the Logstash 6.4.3 release notes are not correct.

**Comment by jsvd** [comment]
Thank you for the heads up @praseodym, #10161 should fix this

**Comment by jsvd** [comment]
fixed by https://github.com/elastic/logstash/pull/10161, documentation page should be updated soon.
