### ISSUE TITLE
Change config.field_reference.parser to STRICT

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#10177]

**Comment by yaauie** [comment]
This was done on `master` in #9543:

> ~~~ ruby
>             Setting::String.new("config.field_reference.parser", "STRICT", true, %w(STRICT)),
> ~~~
>-- [logstash-core/lib/logstash/environment.rb:36@master](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/environment.rb#L36)

**Comment by jsvd** [comment]
🤦‍♂️ , closing.
