### ISSUE TITLE
I have two errors with logstash-plugins but can't find a solution after 3 days of unlucky research.

### ISSUE THREAD

**Issue by HikariNTB** [elastic/logstash#10183]
Hi,

last week some workmates sends me this two errors from our ELK machine we are setting up in the office. I can't solve this and need some help as I just begun working with this technology.

Error 1:
_/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:403:in `block in start_input'_

Error 2:
_Error: Permission denied - gzip Exception: Errno::EACCES Stack: org/jruby/RubyFile.java:366:in `initialize'_

The idea is to read gzip, gz, csv, etc. documents but our plugins seems not to be well installed or configured. What should I do? 

Thank you.

**Comment by yaauie** [comment]
General usage questions are much better addressed in the [forum](https://discuss.elastic.co/c/logstash), and do not have a place in the project's Github issues. 

When you open a thread in the forum, please include:
 - a summary of what you are attempting to achieve
 - logstash version, as well as how you installed it (rpm, deb, downloaded tar file or zip file, etc.)
 - platform you are working on (linux distribution, mac, windows; include versions where possible)
 - your pipeline configuration (this is the file that defines your `input`s, `filter`s, and `output`s)
 - full, unedited log messages indicating the errors you are encountering
