### ISSUE TITLE
logstash API TLS support

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/logstash#10197]
It does not appear that TLS is supported in https://www.elastic.co/guide/en/logstash/current/monitoring.html

Is there any plan to support that in the future?

**Comment by yaauie** [comment]
The endpoint is exposed on localhost only by default, and performs no authentication or authorisation; the value-add from TLS would be relatively low until these other things are implemented.

If you have an immediate need, setting up an nginx server as an SSL/TLS terminator is pretty straight-forward (see: [nginx ssl termination docs](https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-http/))

**Comment by jsvd** [comment]
closing as duplicate of https://github.com/elastic/logstash/issues/9476
