### ISSUE TITLE
Can't decompress a *.gz file. Easy to solve guys!

### ISSUE THREAD

**Issue by HikariNTB** [elastic/logstash#10194]
Hi everyone,

I'm trying to read a `*.gz` document with logs. In my `/etc/logstash/conf.d/logstash.conf` I have set this:

```
input {
    file {
        type => "gz"
        path => "/opt/logs/newones/machine004info.log.2018-11-20.gz"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        codec => "gzip_lines"
    }
}

output {
        elasticsearch { hosts => ["http://testing.local:9200"] }
}
```

Afer that, I type: `tail -f logstash-plain.log` and display me this warning:

> [2018-12-04T06:55:43,665][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}

I want to make my ELK read the `.gz` doc and unzip/decompress it. At the moment i see this:

![image](https://user-images.githubusercontent.com/45421464/49441615-5b78dc00-f7c7-11e8-8bc5-b4c6865fd733.png)

Anyway, I thing I have to do something with the `"type"`. What do you thing about it? What sould I do?

**Comment by guyboertje** [comment]
@HikariNTB 

The file input supports gzip file reading in "read" mode. See [docs](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-mode)

The file extension must be either `gz` or `gzip` - `@path.end_with?('.gz','.gzip')`.

You do not need the `codec => "gzip_lines"` setting.

The `type` setting when set in an input is typically used for conditional processing, e.g. if you have a few inputs and you need to enrich events from each "type" separately.

**Comment by HikariNTB** [comment]
Thank you so much. Now everything is working right!

I share with all of you my `/etc/logstash/conf.d/logstash.conf` configuration as for helping others with the same problem:

```
input {
    file {
        path => "/opt/logs/testing/nameofthelog.gz"
        sincedb_path => "/dev/null"
        mode => "read"
        ignore_older => "31 d"
        file_completed_action => "delete"
        start_position => "beginning"
    }
}

output {
        elasticsearch { hosts => ["http://test.local:9200"] }
}
```

**Comment by guyboertje** [comment]
@HikariNTB 
FYI, In read mode (and especially with gzip files), `start_position => "beginning"` is ignored as `read mode` always reads files from the beginning.
