### ISSUE TITLE
Replace _xpack/monitoring/* with _monitoring/* ES API calls

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#10207]
Starting 7.0, the `_xpack/monitoring/*` API endpoints in Elasticsearch will be [deprecated](https://github.com/elastic/elasticsearch/pull/36130) in favor of `monitoring/*` API endpoints. We should update any references to the deprecated endpoints in the Logstash codebase and replace them with the new ones.

**Comment by ycombinator** [comment]
`GET _xpack` is going to stay as-is. However, we might want to separately consider switching the license check to use `GET _license` instead of `GET _xpack` if possible.

**Comment by jsvd** [comment]
fixed in https://github.com/elastic/logstash/pull/10528

**Comment by jsvd** [comment]
created https://github.com/elastic/logstash/issues/11382 to track the license checking path update
