### ISSUE TITLE
jvm.options recognized as java classes

### ISSUE THREAD

**Issue by Dyanngg** [elastic/logstash#10260]
- **Version:** Logstash-6.5.4, installation via downloaded binary
- **Operating System:** OS Sierra 10.12.6
- **Java version:** java version "1.8.0_181"
                          Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
                          Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
- **Config File:** the original `config/logstash-simple.conf`
- **Steps to Reproduce:**
Tried to run the hello world example with
``bin/logstash -e 'input { stdin { } } output { stdout {} }' ``
Got the following error from command line:
`` Error: Could not find or load main class -Xms1g ``
If I comment out -Xms and -Xmx options from config/jvm.options then the next option throws the error
`` Error: Could not find or load main class -XX:+UseParNewGC ``
The closet issue I can find online is [this](https://stackoverflow.com/questions/45490492/error-could-not-find-or-load-main-class-xmx1g) but it seems to be something other than the character misuse error. Running `` bin/logstash -e config/logstash-simple.conf `` throws the same err.

**Comment by yaauie** [comment]
🤔 I can't replicate.

I downloaded and expanded the `tar.gz` distribution, copying the referenced sample config file into place:

> ~~~
> ╭─{ yaauie@castrovel:~/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes }
> ╰─○ wget https://artifacts.elastic.co/downloads/logstash/logstash-6.5.4.tar.gz
> --2019-02-05 18:02:56--  https://artifacts.elastic.co/downloads/logstash/logstash-6.5.4.tar.gz
> Resolving artifacts.elastic.co... 54.235.82.130, 107.21.237.95, 107.21.239.197, ...
> Connecting to artifacts.elastic.co|54.235.82.130|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 160286824 (153M) [application/x-gzip]
> Saving to: ‘logstash-6.5.4.tar.gz’
> 
> logstash-6.5.4.tar.gz                                       100%[=========================================================================================================================================>] 152.86M  3.15MB/s    in 49s
> 
> 2019-02-05 18:03:46 (3.11 MB/s) - ‘logstash-6.5.4.tar.gz’ saved [160286824/160286824]
> 
> [success (50.000s)]
> 
> ╭─{ yaauie@castrovel:~/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes }
> ╰─○ tar -xzf logstash-6.5.4.tar.gz
> tar -xzf logstash-6.5.4.tar.gz  1.65s user 4.87s system 89% cpu 7.269 total
> [success (7.000s)]
> 
> ╭─{ yaauie@castrovel:~/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes }
> ╰─○ cd logstash-6.5.4
> [success]
> 
> ╭─{ yaauie@castrovel:~/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes/logstash-6.5.4 }
> ╰─○ cp config/logstash-sample.conf config/logstash.conf
> [success]
> ~~~

Then, I ensured I was running the referenced version of Java, exactly

> ~~~
> ╭─{ yaauie@castrovel:~/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes/logstash-6.5.4 }
> ╰─○ export JAVA_HOME="$(/usr/libexec/java_home --version 1.8.0p181 --failfast)"
> [success]
> 
> ╭─{ yaauie@castrovel:~/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes/logstash-6.5.4 }
> ╰─○ java -version
> java version "1.8.0_181"
> Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
> [success]
> ~~~

And then ran the referenced command

> ~~~
> ╭─{ yaauie@castrovel:~/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes/logstash-6.5.4 }
> ╰─○ bin/logstash -e 'input { stdin { } } output { stdout {} }'
> Sending Logstash logs to /Users/yaauie/src/elastic/issue-scratch/logstash-10260-jvm-options-as-classes/logstash-6.5.4/logs which is now configured via log4j2.properties
> [2019-02-05T18:22:28,102][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
> [2019-02-05T18:22:28,125][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.5.4"}
> [2019-02-05T18:22:31,458][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
> [2019-02-05T18:22:31,596][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"main", :thread=>"#<Thread:0x108f9a36 run>"}
> The stdin plugin is now waiting for input:
> [2019-02-05T18:22:31,653][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
> [2019-02-05T18:22:32,033][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
> hello
> {
>        "message" => "hello",
>           "host" => "castrovel.local",
>       "@version" => "1",
>     "@timestamp" => 2019-02-05T18:22:41.272Z
> }
> ^C[2019-02-05T18:22:43,294][WARN ][logstash.runner          ] SIGINT received. Shutting down.
> [2019-02-05T18:22:43,506][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x108f9a36 run>"}
> bin/logstash -e 'input { stdin { } } output { stdout {} }'  84.82s user 3.10s system 258% cpu 33.993 total
> [success (34.000s)]
> ~~~

**Comment by kares** [comment]
closing as stale, if the issue persist let us know - maybe share the exact *config/logstash-simple.conf* and *jvm.opts* you're running as smt might have interfered with whitespace/line-endings afte extraction.
