### ISSUE TITLE
illegal_argument_exception 

### ISSUE THREAD

**Issue by 13142025891** [elastic/logstash#10263]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by yaauie** [comment]
@13142025891 I believe that this issue was created in error; its body contains only our verbatim issue template. If you have clear steps to reproduce an error, please follow the directions to create an issue in the proper place.
