### ISSUE TITLE
logstash is storing @timestamp with wrong value

### ISSUE THREAD

**Issue by cgambrel** [elastic/logstash#10280]
When the timestamp is calculated and stored, it is storing the value minus the timezone offset but is still storing as UCT time.  My current timezone is GMT -5.  For example:

The syslog message begins:

<181>Jan 10 14:48:52 ise22 CISE_Failed_Attempts 0000080054 1 0 2019-01-10 14:48:52.169 -05:00  (--Correct--)

The syslog timestamp:

"syslog_timestamp" : "Jan 10 14:48:52" (--Correct--)

"received_at":

"received_at" : "2019-01-10T19:48:52.178Z" (--Correct--)

However the issue is with @timestamp:

"@timestamp" : "2019-01-10T14:48:52.000Z"  (--Incorrect--)

It should be the same as (or in the same timezone) "received_at".  Both should be in UTC.

The @timestamp should actually be:

"@timestamp" : "2019-01-10T19:48:52.000Z"

- Version: logstash 6.5.4
- Operating System: Debian
- Config File (if you have sensitive info, please remove it):
input {
  tcp {
    port => 1468
    type => syslog
  }
  udp {
    port => 5000
    type => syslog
  }
}
filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}
output 
{
    elasticsearch 
    {
        hosts => ["127.0.0.1:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}

- Sample Data:
"""<181>Jan 10 14:48:52 ise22 CISE_Failed_Attempts 0000080054 1 0 2019-01-10 14:48:52.169 -05:00 0008285888 5400 NOTICE Failed-Attempt: Authentication failed, ConfigVersionId=44, Device IP Address=<obfuscated>, Device Port=46000, DestinationIPAddress=<obfuscated>, DestinationPort=1645, RadiusPacketType=AccessRequest, UserName=<obfuscated>, Protocol=Radius, RequestLatency=324, NetworkDeviceName=secure, User-Name=<obfuscated>, NAS-IP-Address=<obfuscated>, NAS-Port=59958, Calling-Station-ID=<obfuscated>, NAS-Port-Type=Virtual, cisco-av-pair=ip:source-ip=<obfuscated>, cisco-av-pair=coa-push=true, OriginalUserName=<obfuscated>, NetworkDeviceProfileName=<obfuscated>, NetworkDeviceProfileId=42152014-8793-4387-8c7e-feb0f43024a4, IsThirdPartyDeviceFlow=false, AcsSessionID=ise22/332661932/416859, AuthenticationIdentityStore=<obfuscated>, AuthenticationMethod=PAP_ASCII, SelectedAccessService=PAP_Only, FailureReason=24408 User authentication against Active Directory failed since user has entered the wrong password, Step=11001, Step=11017, Step=11117, Step=15049, Step=15008, Step=15048, Step=15048, Step=15048, Step=15048, Step=15006, Step=15041, Step=15006, Step=22072, Step=15013, Step=24430, Step=24325, Step=24313, Step=24357, Step=24319, Step=24323, Step=24344, Step=24408, Step=22057, Step=22061, Step=11003, SelectedAuthenticationIdentityStores=<obfuscated>, SelectedAuthenticationIdentityStores=Internal Users, NetworkDeviceGroups=Location#All Locations#Internal_LOC, NetworkDeviceGroups=Device Type#All Device Types#Firewall, NetworkDeviceGroups=Managed_Devices#Managed_Devices#Cisco_IOS, NetworkDeviceGroups=AP#AP, IdentityPolicyMatchedRule=Default3a60a630-1482-43f7-a78a-c570759c04f2, CPMSessionID=ac10c816mtJFE1pgWAVlO_wwAuFU0ns_2UzGnA20WHzyGZhXixU, ISEPolicySetName=Device_Management, AllowedProtocolMatchedRule=Default, IdentitySelectionMatchedRule=Default, AD-User-Candidate-Identities=<obfuscated>, StepData=5= Normalised Radius.RadiusFlowType (4 times), StepData=6= Cisco-VPN3000.CVPN3000/ASA/PIX7x-Client-Type, StepData=7= Radius.NAS-Port-Type, StepData=8= DEVICE.Managed_Devices, StepData=12=ADplusCerts, StepData=13=<obfuscated>, StepData=14=<obfuscated>, StepData=15=<obfuscated>, StepData=16=<obfuscated>, StepData=17=from: <obfuscated> to: <obfuscated>, StepData=18=<obfuscated>, StepData=20=STATUS_WRONG_PASSWORD\,ERROR_INVALID_PASSWORD\,<obfuscated>, StepData=21=TotB_AD, IsMachineIdentity=false, DTLSSupport=Unknown, Model Name=<obfuscated>, Software Version=<obfuscated>, Location=Location#All Locations#Internal_LOC, Device Type=Device Type#All Device Types#Firewall, Network Device Profile=Cisco, Managed_Devices=Managed_Devices#Managed_Devices#Cisco_IOS, AP=AP#AP, Response={RadiusPacketType=AccessReject; AuthenticationResult=Failed; },""",

- Steps to Reproduce:

Send syslog traffic with the above format.

Thanks in advance!

**Comment by yaauie** [comment]
Typically, usage questions are best addressed in the [community forum](https://discuss.elastic.co/c/logstash). I am closing this issue along with a brief analysis, and advise that you open a thread in the forum if it's not enough to get your problem solved.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> -- [ISSUE_TEMPLATE.md](https://github.com/elastic/logstash/edit/master/.github/ISSUE_TEMPLATE.md)

***

The `@timestamp` is being overwritten by your `date` filter, which is configured to read from the `syslog_timestamp` that has been extracted from the message; the value of that field from the example event you posted is the string `Jan 10 14:48:52`, which contains no offset information so you will need to inform the Date Filter Plugin of the timezone context in which to parse the string, using the [`timezone`](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-timezone) directive.

**Comment by cgambrel** [comment]
Thanks yaauie!  That was it.  I appreciate you answering and not just closing.  I will try the community forum next time (Honestly, I thought this was it).  Cheers!
