### ISSUE TITLE
How to have a boolean based field migrated from MongoDB to Elasticsearch using Logstash?

### ISSUE THREAD

**Issue by topgun743** [elastic/logstash#10333]
I have banged my head on so many internet forums but failed to accomplish this.

Here are my sample documents present in MongoDB in _test_ collection:

```
{
    "_id" : ObjectId("59a41f63dba6488b33268377"),
    "EntityID": "abc123"
    "IsRestrictedView" : false
},
{
    "_id" : ObjectId("59a41f63dba6488b33268388"),
    "EntityID" : "abc456",
    "IsRestrictedView" : true
},
{
    "_id" : ObjectId("59a41f63dba6488b33268399"),
    "EntityID" : "abc789",
    "IsRestrictedView" : false
 }
```

Here is content of my Logstash config file:

```
input {
    mongodb {
        uri => 'mongodb://localhost/TestDB'
        placeholder_db_dir => 'E:/logstash-mongodb/'
        placeholder_db_name => 'logstash_sqlite.db'
        collection => 'test'
        batch_size => 5000
        generateId => false
    }
}
filter {
    mutate {
        rename => { "_id" => "mongo_id" }
    }
    mutate {
        convert => {"IsRestrictedView" => "boolean"}
    }
}
output {
    stdout {
        codec => rubydebug
    }
    elasticsearch {
        hosts => ["127.0.0.1:9200"]
        index => "mediasummary"
        doc_as_upsert => true
        document_id => "%{mongo_id}"
    }
}
```

The indexed data in Elasticsearch contains all other fields except "IsRestrictedView".

So
1. How can I get this boolean field correctly into Elasticsearch? 
2. Also the first document is always missing in indexed data. Why so?

A question has been posted in this regard also on Stackoverflow.com
[See post](https://stackoverflow.com/questions/54202732/how-to-have-a-boolean-based-field-migrated-from-mongodb-to-elasticsearch-using-l)

- Logstash Version: 6.5.4
- Windows 10

**Comment by guyboertje** [comment]
Closing this. I am working with @topgun743 on this [in Discuss](https://discuss.elastic.co/t/how-to-have-a-boolean-based-field-migrated-from-mongodb-to-elasticsearch-using-logstash/164589/5).
