### ISSUE TITLE
add_field isn't handled for plugins using the new v0 Plugin API

### ISSUE THREAD

**Issue by w4** [elastic/logstash#10350]
On the current beta version, calls to:

```
LogStash::Util::Decorators.add_fields(@add_field,event,"inputs/#{self.class.name}")
LogStash::Util::Decorators.add_tags(@tags,event,"inputs/#{self.class.name}")
```

([logstash-core/lib/logstash/inputs/base.rb L112](https://github.com/elastic/logstash/blob/ccbfd8a9ae7045661afb7225e55602c72db34c57/logstash-core/lib/logstash/inputs/base.rb#L112))

don't seem to be being made and so add_field handling needs to be done manually by the plugin which is difficult because the event.sprintf API doesn't seem like it's exposed to v0 plugins.

**Comment by w4** [comment]
In fact, `sprintf` is defined in `org.logstash.Event` - I assumed it was still written in Ruby.

Although I'd prefer `add_tag` and `add_field` to be handled outside of the plugin as it previously was,  allowing us to pass round an `Event` rather than a `Map<String, Object>` (as I've asked about in #10351) would mitigate part of this issue (not being able to call sprintf ourselves) and also allow things like [logstash-codec-msgpack](https://github.com/logstash-plugins/logstash-codec-msgpack/blob/848a4977b9cd4051bcffdc67715bc4d5de06404e/lib/logstash/codecs/msgpack.rb#L27-L31) to be ported over without breaking changes.

**Comment by danhermann** [comment]
@w4, thanks again for looking thoroughly at the v0 Java plugin API (and before we've even announced its availability!). What you're seeing there is the fact that v0 Java plugin API is experimental and has not yet reached feature parity with the feature set for Ruby plugins. In the upcoming [beta](https://github.com/elastic/logstash/pull/10232) release of the Java Plugin API, there is feature parity with Ruby plugins including support for the decorator tags which are, coincidentally, implemented outside of the plugin as you suggested. I'm going to close this issue as resolved, but if you are interested, you can look at the decorator implementation in the beta release and drop a comment on that PR if there's something different that you'd like to see.
