### ISSUE TITLE
false warning for elasticsearch output config when using monitoring

### ISSUE THREAD

**Issue by jpcarey** [elastic/logstash#10352]
In 6.5.4, if you have monitoring setup - it produces a false warning for `logstash.outputs.elasticsearch`. I'm not sure why this message is triggered at all, and why it is flagged as `logstash.outputs.elasticsearch` instead of the appropriate monitoring module.

```
[2019-01-11T11:16:28,685][WARN ][logstash.outputs.elasticsearch] ** WARNING ** Detected UNSAFE options in elasticsearch output configuration!
** WARNING ** You have enabled encryption but DISABLED certificate verification.
** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true 
```

```
[2019-01-11T11:16:28,654][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch.
```

**Comment by Pectojin** [comment]
Facing the same issue in 6.6.2. There's no monitoring value for setting validation either which makes you wonder if it's a false warning or a default `false` value that can't be changed.

**Comment by jgrevich** [comment]
I noticed the same issue with a cluster running 6.4.2.

**Comment by davtex** [comment]
Facing same problem in 7.0.1. I assume there are incorrect defaults configured for monitoring exporter.

**Comment by MorrieAtElastic** [comment]
Customer is encountering these messages after upgrading to V7.2.0; he does not recall seeing these errors in the same clusters when they were at 6.7.1. 

Can we get confirmation that they are indeed harmless and can be ignored.

**Comment by fholzer** [comment]
I though it may have been fixed in https://github.com/elastic/logstash/commit/78bc47d1c94146f268ecd5862359cd371203772f
but after installing 7.2 and setting `xpack.monitoring.elasticsearch.ssl.verification_mode: certificate` the warning still shows up.

**Comment by saifat29** [comment]
Having same issue on 7.02

**Comment by rustamxp** [comment]
Have the same issue on 7.3.0

**Comment by geekpete** [comment]
Seems a few related or possibly duplicate issues around this:
https://github.com/elastic/logstash/issues/10524
https://github.com/elastic/logstash/issues/9716
https://github.com/elastic/logstash/issues/9734

possibly related upstream issue:
https://github.com/cheald/manticore/issues/52

**Comment by Erni** [comment]
Facing the same issue in 6.8

**Comment by adoerrES** [comment]
Another user also experiencing the issue in 6.8.

**Comment by mohclips** [comment]
Same on 7.4

**Comment by danlsgiga** [comment]
Same on 7.5

**Comment by maggieghamry** [comment]
Same issue on 7.6

**Comment by rboutin** [comment]
Same issue on 7.6.1

**Comment by rhizoet** [comment]
Always same on latest 7.8.0. Please fix. This makes me and my teammates nervous :laughing:

**Comment by aruandre** [comment]
same on 7.9.3

**Comment by sastorsl** [comment]
And on 7.11.1
