### ISSUE TITLE
public_suffix gem upgrade (1.4.6 -> 3.0.3)

### ISSUE THREAD

**Issue by renshuki** [elastic/logstash#10447]
Hi there,

LS is still running an old version of the public_suffix gem (1.4.6).
To take advantage of new domain patterns and other improvements, it would be worth to update the gem to a more recent version.

Reference:
https://rubygems.org/gems/public_suffix/versions/3.0.3
https://github.com/weppos/publicsuffix-ruby

Thanks.

**Comment by yaauie** [comment]
@renshuki It looks like that dependency is pulled in by the Twitter Input Plugin, so I've opened an issue over there and am closing this one.

https://github.com/logstash-plugins/logstash-input-twitter/issues/61
