### ISSUE TITLE
clarify inter pipelines communication ensure_delivery option

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#10443]
The documentation of the `ensure_delivery` option in the [delivery guarantees](https://www.elastic.co/guide/en/logstash/current/pipeline-to-pipeline.html#delivery-guarantees) is confusing WRT to the back pressure behaviour. 

The confusion and clarification can be seen here https://discuss.elastic.co/t/pipeline-pipeline-communication-question/138106

In short, `ensure_delivery` is really meant for when a destination pipeline becomes unavailable (it is reloading for example)  and not for when the destination pipeline input is blocked where `ensure_delivery` has **no** effect.

/cc @karenzone

**Comment by danhermann** [comment]
Resolved by https://github.com/elastic/logstash/pull/10754.
