### ISSUE TITLE
Add ability to dynamically assign new pipelines to Logstash via CPM

### ISSUE THREAD

**Issue by n0othing** [elastic/logstash#10457]
Today, Logstash Centralized Pipeline Management (CPM) requires users to register pipelines in the `logstash.yml` via the `xpack.management.pipeline.id: [ ]` property. It would be useful if you could dynamically assign pipelines on the fly to any given instance of Logstash (without the need to add said pipelines to `xpack.management.pipeline.id`).

**Comment by waynetaylor** [comment]
+1 to this. The concept of central management is great but then requiring to modify yml files is kind of defeating the purpose.

It's great for existing and works well. But adding new pipelines requires a new deployment or change to your clusters

**Comment by cpmoore** [comment]
Related #10558

**Comment by percygrunwald** [comment]
Very disappointing that this wasn't part of the implementation. It feels like this feature was poorly thought out. I left a comment in #10558 with my feedback on this: https://github.com/elastic/logstash/issues/10558#issuecomment-555160717

**Comment by n0othing** [comment]
This should be possible to do when `7.11` is released [1].

[1] https://github.com/elastic/logstash/issues/12366
