### ISSUE TITLE
LogStash::Json::ParserError: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

### ISSUE THREAD

**Issue by amiya-elear** [elastic/logstash#10465]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:6.6.0
- Operating System:ubuntu 16.04
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:
i am new to logstash i need help on this issue i am not able to understand what the actual problem is .

my logstash config file is 
logstash.config

~~~
input {
tcp {
port => 5001
type => "tomcat"
codec=> "json"
}

tcp {
port => 5000
type => "nginx"
codec=> "json"
}

}

filter {
json {
source => "message"
target => "parsedjson"
}
mutate {
add_field => { "Source_IP" => "%{[_source][SOURCEIP]}" }
}
}

output {

```
if [type] == "tomcat" {
    elasticsearch {
        hosts => "elasticsearch:9200"
        index => "tomcat_index"
    }
} else if [type] == "nginx"{
    elasticsearch {
        hosts => "elasticsearch:9200"
        index => "nginx_index"
    }
} else {
     elasticsearch {
                   hosts => "elasticsearch:9200"
                   index => "default"
          }
     }
```

}
~~~

this is my logstash config file and i am having the same issue. kindly help me o this.
error file:

[2019-02-18T11:28:04,248][WARN ][logstash.filters.json ] Error parsing json {:source=>"message", :raw=>"<30>Feb 18 16:58:04 nginx[2170]: 172.17.0.1 - - [18/Feb/2019:11:28:04 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0" "-"", :exception=>#<LogStash::Json::ParserError: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

thanks in advance

**Comment by yaauie** [comment]
Since this is a general usage question and not a reproducible bug report or a feature request, I am closing this issue.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash).
> Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> 
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

Hopefully the following will help you get on track, but if you need more, please open a thread on the [forum](https://discuss.elastic.co/c/logstash).

***

The warning message indicates that the JSON parser was given input that is not valid JSON, and therefore could not be parsed.

From the warning, it looks like the raw message contains a syslog-style message, and not a JSON body; you will likely need to configure your inputs to use a codec that is appropriate for your inputs.
