### ISSUE TITLE
Documentation needs updating to use HTTP over Lumberjack for LS - LS connection

### ISSUE THREAD

**Issue by hoigau** [elastic/logstash#10487]
In the [latest 6.6 documentation](https://www.elastic.co/guide/en/logstash/6.6/ls-to-ls.html), it is recommending Lumberjack for connecting 2 logstash:

`Use the Lumberjack protocol to connect two Logstash machines.`

while we should be recommendating HTTP output/input pair with `json_batch` as the current recommendation as it also plays nicer with load balancers in general, because each batch is an independent HTTP request that the load balancer is free to route to any of the hosts it sits in front of.

**Comment by rwaight** [comment]
Hi folks, any update on this?  In [the 7.0 documentation](https://www.elastic.co/guide/en/logstash/7.0/ls-to-ls.html), we are still recommending Lumberjack for connecting logstash-to-logstash:
> Use the Lumberjack protocol to connect two Logstash machines.

**Comment by karenzone** [comment]
@rwaight  This work is still on the roadmap, but on hold for the moment.

**Comment by praseodym** [comment]
Previous issue: https://github.com/elastic/logstash/issues/9021

**Comment by AndyHunt66** [comment]
Added a temporary PR to at least point out in the docs that the current page is obsolete/deprecated
https://github.com/elastic/logstash/pull/13168

**Comment by roaksoax** [comment]
We believe this issue is now complete and available in https://www.elastic.co/guide/en/logstash/current/ls-to-ls.html
