### ISSUE TITLE
Update example configs to show ECS fields

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#10490]
The Logstash configurations shown in the section about [working with Filebeat modules](https://www.elastic.co/guide/en/logstash/current/logstash-config-for-filebeat-modules.html) use the old field names generated by Beats. As part of our move to ECS, we need to update the configs for 7.0 and later to use the new field names. The config examples have not been updated for awhile, so some of them use field names that were removed in previous releases, making it a little harder to figure out the correct fields to use.

@karenzone Do you know if there is a good/easy way to convert logstash configs to use the ECS fields? Are we planning some kind of migration tool that could help us here? I started to convert them by hand (because I wanted to remove references to apache2), but quickly learned that it's not a trivial effort.

**Comment by dedemorton** [comment]
@ruflin Do you have any thoughts on how we can automate this? Will there be a migration tool for converting configs to use ECS? I'm assuming we want to have this conversion complete by 7.0, correct?

**Comment by ruflin** [comment]
There is the migration file here which has all the migrated fields inside: https://github.com/elastic/beats/blob/master/dev-tools/ecs-migration.yml But I'm not sure if that would be the right approach here. For the modules we have, should we really recommend to do the processing in LS or instead have docs on how to install the ingest pipeline in Elasticsearch and let Logstash use it?

**Comment by dedemorton** [comment]
@ruflin I've already reworked the docs to show how to use the ingest pipelines, so that part is done. It sounds like there are some use cases, though, where folks might want to switch over to Logstash, but still use the configs, dashboards, and so on in Filebeat.

I'm torn because I realize that maintaining these examples manually is time consuming.

But I hesitate to rip out examples that might be useful, especially since the Logstash Reference is very light on full examples. 

@karenzone WDYT?

**Comment by adoerrES** [comment]
Logstash users would still like to see the filebeat modules examples updated to use ECS fields, if possible.  

Specifically, a few examples have been mentioned as needing updates (for System and auditd modules; the System example being below):

https://www.elastic.co/guide/en/logstash/current/logstash-config-for-filebeat-modules.html#parsing-system

**Comment by karenzone** [comment]
Thanks, @adoerrES. I'm working on this right now. It's nice to know that it's needed.

**Comment by karenzone** [comment]
WIP: #11563

**Comment by dedemorton** [comment]
Closing this old issue because it looks like we removed the examples from the docs at some point.
