### ISSUE TITLE
Test Failure: CI integration test for DLQ 7.x

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#10503]
Jenkins Console

https://logstash-ci.elastic.co/job/elastic+logstash+7.x+multijob-integration-1/23/console

Will create PR to skip it

**Comment by jsvd** [comment]
@guyboertje there seem to be a couple of open issues about this https://github.com/elastic/logstash/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+separate+config+file+behaves+like+it+can+send+1000+documents+to+and+index+from+the+dlq+should+index+all+documents

probably we can close this as follow through in https://github.com/elastic/logstash/issues/10275?

**Comment by guyboertje** [comment]
OK
