### ISSUE TITLE
the logstash cannot find the conf file

### ISSUE THREAD

**Issue by lovexiongmao** [elastic/logstash#10512]
- Version: 6.6.1
- Operating System: centos7.6
- Config File (if you have sensitive info, please remove it):  default（not modified）
- Sample Data:  
- Steps to Reproduce:  
I pull the image from the registry，And i exec the following command below
```
docker run --rm -it -v /home/cyk/elk/logstash-6.6.1/config/:/usr/share/logstash/config/ docker.elastic.co/logstash/logstash:6.6.1
```
then i get the error :  "2019/03/02 14:32:05 error: open /usr/share/logstash/config/logstash.yml: no such file or directory"
so i entry the directory: /usr/share/logstash/config/ of the container to see whether exist this file. 
it does exist! 
what's the problem?

**Comment by amejiarosario** [comment]
@lovexiongmao what was the problem? I'm seeing the same issue
