### ISSUE TITLE
Default Document Type Should be `_doc`

### ISSUE THREAD

**Issue by bliles** [elastic/logstash#10554]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: 6.3.2
- Operating System: Ubuntu 16.04
- Steps to Reproduce:
According to https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html#_schedule_for_removal_of_mapping_types the default document_type mapping should be `_doc` this is to be consistent with the URL pattern in ES 7. However with logstash if you do not specify document_type it defaults to `doc` and your pipeline will fail with the error:
[WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"xxx", :_type=>"doc", :_routing=>nil}, #<LogStash::Event:0x6724eea8>], :response=>{"index"=>{"_index"=>"xxx", "_type"=>"doc", "_id"=>"xxx", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [xxx] as the final mapping would have more than 1 type: [_doc, doc]"}}}}

**Comment by mbniehues** [comment]
+1

Give that https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-document_type indicates the `document_type` option is deprecated and will be removed with the next major version, we need some clarification here.

**Comment by yaauie** [comment]
This does not appear to be an issue with logstash itself, so I am closing the ticket.

> Logstash Plugins are located in a different organization: https://github.com/logstash-plugins.
> For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open
> it in the respective Redis Output repository. 
>
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

***

That said, the current version of the Elasticsearch Output Plugin (10.0.1 as of this writing) defaults to `_doc` when connected to an Elasticsearch cluster with version 7 or greater, so the issue should be resolved in upcoming releases.
