### ISSUE TITLE
Date filter bug with "ä" 

### ISSUE THREAD

**Issue by ChristophMarketsmuellerUnymira** [elastic/logstash#10565]
Hello there is a bug in logstash with the date filter.
I use 
- logstash 6.6.2
- OS: CentOS Linux release 7.6.1810 (Core)

I have dateparsing Errors with the following Example

The Following command
```
echo "15-Mär-2019 18:54:42.585 INFO [pool-1-thread-1][LiferayExpandoServiceImpl:137] Successfully initallized 642 of 642 expando values for friendlyURL mapping" | ./logstash -e 'input { stdin {} }
filter {

   grok {
      patterns_dir => "/etc/logstash/pattern"
      match => [ "message", "%{TOMCATLOG}", "message", "%{CATALINALOG}" ]

   }

   date {
      match => [ "timestamp", "dd-MMM-yyyy HH:mm:ss.SSS", "yyyy-MM-dd HH:mm:ss.SSS" ]
   }
}
'
```
had this output
```{
         "level" => "INFO",
    "@timestamp" => 2019-03-15T18:31:38.141Z,
          "host" => "adm01vm",
    "logmessage" => " Successfully initallized 642 of 642 expando values for friendlyURL mapping",
     "timestamp" => "15-Mär-2019 18:54:42.585",
      "@version" => "1",
        "syslog" => "[pool-1-thread-1]",
       "message" => "15-Mär-2019 18:54:42.585 INFO [pool-1-thread-1][LiferayExpandoServiceImpl:137] Successfully initallized 642 of 642 expando values for friendlyURL mapping",
     "javaclass" => "[LiferayExpandoServiceImpl:137]",
          "tags" => [
        [0] "_dateparsefailure"
    ]
}
```

When I change the "ä" from Mär  to an "Mar" everything is fine
```{
     "timestamp" => "15-Mar-2019 18:54:42.585",
     "javaclass" => "[LiferayExpandoServiceImpl:137]",
         "level" => "INFO",
       "message" => "15-Mar-2019 18:54:42.585 INFO [pool-1-thread-1][LiferayExpandoServiceImpl:137] Successfully initallized 642 of 642 expando values for friendlyURL mapping",
      "@version" => "1",
        "syslog" => "[pool-1-thread-1]",
          "host" => "adm01vm",
    "@timestamp" => 2019-03-15T17:54:42.585Z,
    "logmessage" => " Successfully initallized 642 of 642 expando values for friendlyURL mapping"
}```

**Comment by yaauie** [comment]
This does not appear to be an issue with logstash itself, so I am closing the ticket.

> Logstash Plugins are located in a different organization: https://github.com/logstash-plugins.
> For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open
> it in the respective Redis Output repository. 
>
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

***

That said, the date filter plugin can be configured to parse month names and abbreviations from a specific locale (in this case, I _think_ that `Mär` is an abbreviation for the german _März_, in which case the value `de` can be used). From the docs:

> `locale`:
>  - Value type is string
>  - There is no default value for this setting.
>
> Specify a locale to be used for date parsing using either IETF-BCP47 or POSIX language tag. Simple examples are en,en-US for BCP47 or en_US for POSIX.
>
> The locale is mostly necessary to be set for parsing month names (pattern with MMM) and weekday names (pattern with EEE).
> 
> If not specified, the platform default will be used but for non-english platform default an english parser will also be used as a fallback mechanism.
>
> --[Logstash Documentation -- Date Filter Plugin -- `locale`](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-locale)

***

If you have further issues, I would recommend either asking in our [forum](https://discuss.elastic.co/c/logstash) or opening up an issue on [logstash-plugins/logstash-filter-date](https://github.com/logstash-plugins/logstash-filter-date).
