### ISSUE TITLE
Make GET _node/pipelines/:id and GET _node/stats/pipelines/:id APIs return Elasticsearch output cluster_uuid

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#10602]
### Background

Today, when the `xpack.monitoring.*` settings are configured in `logstash.yml`, Logstash performs _internal_ collection of it's own monitoring metrics and ships them to `.monitoring-logstash-*`. **Note that Logstash ships these metrics to the _production_ Elasticsearch cluster, which then enriches them with it's `cluster_uuid` and forwards them on to the _monitoring_ Elasticsearch cluster for indexing.** The Monitoring UI in Kibana then reads documents from these indices to create visualizations of a user's Logstash instances and pipelines.

In the future, we're aiming to have Metricbeat _externally_ collect Logstash metrics and ship them to `.monitoring-logstash-*` indices. This will mean that Metricbeat has to poll various Logstash HTTP APIs to collect said metrics.

### The Request

This request is a follow up to #10119 and #10120. Once those issues are implemented, the corresponding APIs will return _almost_ all the information needed by Metricbeat. However, there is still one piece of information needed, which is currently being injected into Logstash monitoring data by the production Elasticsearch cluster (see **bolded** sentence in the Background section above): the `cluster_uuid` of the Elasticsearch production cluster.

Taking a step back and looking at this `cluster_uuid` from a conceptual perspective, it really is meant to be the `cluster_uuid` of any Elasticsearch cluster that a Logstash pipeline is sending its data to. That way the Stack Monitoring UI can show this Logstash pipeline (and it's node) as part of the correct stack, which is built on top of the correct Elasticsearch cluster. 

Of course, it's possible that a particular Logstash pipeline is not using the Elasticsearch output at all or is using multiple Elasticsearch outputs. If a Logstash pipeline is using one or more Elasticsearch outputs, would it be possible to return these Elasticsearch clusters' `cluster_uuid`s in the API responses, perhaps as a `cluster_uuids` or `elasticsearch_cluster_uuids` property, as a sibling to the `ephemeral_id` property? If a Logstash pipeline is not using an Elasticsearch output, this property could be omitted or returned as `null`, whatever is easier.

**Comment by ycombinator** [comment]
Since the notion of `cluster_uuid` is specific to Elasticsearch, it might be better to return this field inside an `elasticsearch` plugin or vertex field instead of a pipeline-level field.

**Comment by cachedout** [comment]
This is resolved via https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/857 in conjunction with an update to https://github.com/elastic/logstash/pull/10561

**Comment by cachedout** [comment]
@ycombinator It's a child of the pipeline right now but we can move deeper if you want. Take a look and let me know which you'd prefer.

**Comment by cachedout** [comment]
@ycombinator I just realized this isn't correctly applying to the /stats endpoint. I'm fixing that up now.

**Comment by ycombinator** [comment]
Just a reminder to implement this as a follow up to https://github.com/elastic/logstash/pull/10576, per https://github.com/elastic/logstash/pull/10576#issuecomment-495544345. Thanks!

**Comment by cachedout** [comment]
This should now be fully resolved once https://github.com/elastic/logstash/pull/10576 is merged.

**Comment by cachedout** [comment]
Closed by #10576
