### ISSUE TITLE
Java plugin API produces nullpointerexception during startup

### ISSUE THREAD

**Issue by nterry** [elastic/logstash#10617]
Before I get spammed with 'this already exists, I have looked over #7768 and this appears to be unrelated.

I recently wrote an input plugin for 6.7.0 that correctly starts up when using the Ruby interface. I tried to convert it over to a Java implementation and I get a NPE when starting up. After debugging, I (think) i've found the issue here:

Null gets passed in here:
https://github.com/elastic/logstash/blob/583ec6b62574878c6ed6669271304e1f06ffa8e4/logstash-core/src/main/java/org/logstash/plugins/PluginFactoryExt.java#L191

Which gets passed through here:
https://github.com/elastic/logstash/blob/583ec6b62574878c6ed6669271304e1f06ffa8e4/logstash-core/src/main/java/org/logstash/plugins/PluginFactoryExt.java#L290

Then through here:
https://github.com/elastic/logstash/blob/48ee9987ccda8b9899f4dcc93f76eec2d64a116c/logstash-core/src/main/java/org/logstash/plugins/PluginUtil.java#L40

Then here:
https://github.com/elastic/logstash/blob/80c966b03e653baa9ce77c88065c1cdc0ee73b2d/logstash-core/src/main/java/org/logstash/plugins/ConfigurationImpl.java#L70

Looking at the constructor, the rawSettings is populated with null here:
https://github.com/elastic/logstash/blob/583ec6b62574878c6ed6669271304e1f06ffa8e4/logstash-core/src/main/java/org/logstash/plugins/PluginFactoryExt.java#L307

which is what is passed through the call chain... This will always result in an NPE as it is a literal null that is passed in...

Here is the requested info:

- Version: logstash: 6.7.0, jruby: 9.2.5.0, java: 8
- Operating System: macOS 10.14.4
- Config File n/a
- Sample Data: n/a
- Steps to Reproduce: see above code call stack

**Comment by danhermann** [comment]
@nterry, thank you for your detailed bug report. The `plugin` method you list above with the hard-coded `null` for the final parameter should be invoked only for Ruby plugins and not Java plugins, so something unexpected is definitely happening. Could you provide more detail about your Java input plugin? Was it created within the Logstash codebase or external to it and installed with the `logstash-plugin` utility? Would it be possible to share an outline of the code (the body of the input's `start` method should not be necessary) for your input?

**Comment by nterry** [comment]
Ive been using the path option in the Gemfile. I based my plugin off https://github.com/logstash-plugins/logstash-input-java_input_example and its pretty simple.

**Comment by nterry** [comment]
Also, as this may be relevant, the 6.7.0 interface specifies a Consumer for the start method, but the object supplied by logstash implements QueueWriter, so I get a NoSuchMethodError for the accept() method (if I run with ruby).  As a consequence, I've had to revert to 6.6.2 and use the queuewriter with the ruby interface that instantiates my java class.

**Comment by danhermann** [comment]
@nterry, I've been trying to reproduce the problems you describe locally and the only way I get anything close to them is if I run Logstash with the Ruby execution engine rather than the Java execution engine that is required for Java plugins. Could you confirm that you're [running Logstash with the Java execution engine](https://www.elastic.co/guide/en/logstash/current/java-input-plugin.html#_running_logstash_with_the_java_input_plugin)?

**Comment by nterry** [comment]
Well, In a matter of a few minutes, you managed to solve my issue that I have been bashing my head into my desk over for days... I guess I missed the part where I needed to specify the --java-execution flag... Such a tiny change, yet it makes all the difference. Thanks man!

Is this documented in the https://github.com/logstash-plugins/logstash-input-java_input_example repo somewhere. Maybe add it in bold letters in the README so blind fools like myself can avoid this in the future ;)

**Comment by danhermann** [comment]
@nterry, I'm sorry you got stuck on that, but I'm glad you're past it now. That requirement is documented in the "[Running Logstash with the Java input plugin](https://www.elastic.co/guide/en/logstash/6.7/java-input-plugin.html#_running_logstash_with_the_java_input_plugin)" section of the "[How to write a Java input plugin](https://www.elastic.co/guide/en/logstash/6.7/java-input-plugin.html)" page, but if you missed it, it's probably not prominent enough as you suggest. I'll see what we can do to make that more clear. As a related aside, Java execution becomes the default in the soon-to-be-released 7.0 version of Logstash, so this won't be necessary then. Let me know if you have any other problems with this API.

**Comment by nterry** [comment]
@danhermann Thanks! Any idea when 7.0 will be out?

**Comment by danhermann** [comment]
[Release candidate #1 for 7.0 is already out](https://www.elastic.co/blog/elastic-stack-7-0-0-rc1-released), so barring any major unforeseen problems, I'd expect it to be available around the middle of this month.
