### ISSUE TITLE
Enhance GET _node/stats API for Metricbeat monitoring

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#10610]
### Background

Today, when the `xpack.monitoring.*` settings are configured in `logstash.yml`, Logstash performs _internal_ collection of it's own monitoring metrics and ships them to `.monitoring-logstash-*`. The Monitoring UI in Kibana then reads documents from these indices to create visualizations of a user's Logstash instances and pipelines.

In the future, we're aiming to have Metricbeat _externally_ collect Logstash metrics and ship them to `.monitoring-logstash-*` indices. This will mean that Metricbeat has to poll various Logstash HTTP APIs to collect said metrics.

### The Request

Currently the `GET _node/stats` API returns much of the information that Metricbeat will need in order to build the documents to be indexed into `.monitoring-logstash-*`. However, there is one additional field that this API would need to return to complete the picture:

```json
{
   "queue": {
      "events_count" : 1
   }
}
```

This field shows up today in `.monitoring-logstash-*` documents with `type: logstash_stats`, as the `logstash_stats.queue` field.

**Comment by cachedout** [comment]
Thanks, @ycombinator. This functionality is now present in https://github.com/elastic/logstash/pull/10576

**Comment by cachedout** [comment]
Closed via #10576
