### ISSUE TITLE
How to Use Logstash for GitHub Enterprise apliance 

### ISSUE THREAD

**Issue by vivuu1989** [elastic/logstash#10688]
Hi Experts, Looking for your suggestion on below requirement.

We Have our own GitHub Enterprise which is installed as an appliance.

We need to have a central log system. which will analyze the logs. GitHub appliance will supports syslog-style log streams is supported.

How to configure log-stash for forwarding the logs ?.. Whether the log-stash is inbuilt with GHE, any other separate configuration needed and from log-stash how the logs can be monitored.

Please help me with some more details on the above part....

**Comment by guyboertje** [comment]
https://help.github.com/en/enterprise/2.16/admin/installation/log-forwarding

syslog-ng uses RFC 3164 and after 3.0, RFC 5424 as well.

https://www.elastic.co/blog/brewing-in-beats-syslog-input-in-filebeat parses RFC 3164.

I don't know which protocol GHE uses.

Depending how much extra enrichment or transformation you need to do, you can use `filebeat -> elasticsearch` or `filebeat -> logstash (extra enrichment or transformation) -> elasticsearch`.

Contact GitHub Enterprise Support to see whether they have articles/blogs/docs on using the Elastic Stack for GHE monitoring (in any case, to clarify the RFC format used).

**Comment by roaksoax** [comment]
Closing this issue as the request has been addressed in the above comment.
