### ISSUE TITLE
GPLv3 licensing - error?

### ISSUE THREAD

**Issue by hyandell** [elastic/logstash#10681]
Hi Logstash folk,

I noticed that https://github.com/elastic/logstash/blob/8b6c162c18694e97016134a1dbe9184d553a4190/tools/dependencies-report/src/main/resources/licenseMapping.csv contains a row stating:

> "controls.js:",https://github.com/controlsjs/controls.js,GPL-3.0-only

That seems an odd license given you're an Apache 2.0 licensed project. I didn't find the code within Logstash, but I did notice that JRuby's COPYING file refers to a controls.js file. JRuby stated that was MIT, and it predates the controlsjs github project; perhaps the row in your csv file is a false positive?

I've also asked JRuby about whether their controls.js note is needed anymore as I can't find it in their source: https://github.com/jruby/jruby/issues/5691

**Comment by hyandell** [comment]
Noting that JRuby responded and identified that it was an error on their part. So if the controls.js here refers to JRuby's controls.js note, then it sounds like it can be deleted, removing any licensing concern users might have.

**Comment by jsvd** [comment]
Closing here as we no longer list controls.js as a dependency. Thanks for the report!
