### ISSUE TITLE
Error when running Java codec 

### ISSUE THREAD

**Issue by synapticiel** [elastic/logstash#10680]
I tried to compile a new codec plugin, but failed getting the execution right
Could you help on this ?

[2019-04-11T14:23:35,906][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"codec", :name=>"asc_codec", :path=>"logstash/codecs/asc_codec", :error_message=>"\n\n\tyou might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\nno such file to load -- org/logstash/javaapi/asn-plugin/0.2.0/asn-plugin-0.2.0 (LoadError)", :error_class=>RuntimeError, :error_backtrace=>["uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:356:in `do_require'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:265:in `block in require_jar'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:307:in `require_jar_with_block'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:264:in `require_jar'", "C:/es7/logstash/lib/bootstrap/patches/jar_dependencies.rb:6:in `require_jar'", "C:/es7/logstash/lib/logstash-codec-asc_codec_jars.rb:2:in `<main>'", "org/jruby/RubyKernel.java:984:in `require'", "C:/es7/logstash/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/es7/logstash/logstash-core/lib/logstash/codecs/asc_codec.rb:1:in `<main>'", "org/jruby/RubyKernel.java:984:in `require'", "C:/es7/logstash/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:181:in `legacy_lookup'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:156:in `block in lookup'", "org/jruby/ext/thread/Mutex.java:165:in `synchronize'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:152:in `lookup'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:206:in `lookup_pipeline_plugin'", "C:/es7/logstash/logstash-core/lib/logstash/plugin.rb:137:in `lookup'", "org/logstash/plugins/PluginFactoryExt.java:200:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:308:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:117:in `buildInput'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/java_pipeline.rb:23:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "C:/es7/logstash/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}

Example

# encoding: utf-8
require "logstash/codecs/base"
require "logstash/namespace"
require "logstash-codec-asc_codec_jars"
require "java"

class LogStash::Codecs::AsnCodec < LogStash::Codecs::Base
  config_name "asc_codec"

  def self.javaClass() org.logstash.javaapi.AsnCodec.java_class; end
end

require 'jar_dependencies'
require_jar('org.logstash.javaapi', 'asn-plugin', '0.2.0')

**Comment by synapticiel** [comment]
I followed this guide using version 7.0
https://www.elastic.co/guide/en/logstash/current/java-codec-plugin.html

**Comment by synapticiel** [comment]
@danhermann Thank You for your valuable response
I was able to review my code and recompile it correclty and was sucessfully executed

**Comment by synapticiel** [comment]
The codec is sucessfully executed when using this command

type bpgwcdr02087595.dat | logstash --java-execution -e "input { java_stdin { codec => asn_codec } } "

But when using a logstash config file, with input 

logstash --java-execution -w 1 -f asn1_conf.conf

input {
  file {
    path => "C:/es7/logstash/example_asn/bpgwcdr02087595.dat"
    start_position => "beginning"
    codec => asn_codec
  }
}

filter {
}

output {
  stdout { codec => rubydebug }
}


I am getting this error

[2019-04-24T09:05:57,157][ERROR][logstash.plugins.registry] 

Problems loading a plugin with {:type=>"codec", :name=>"asn_codec", :path=>"logstash/codecs/asn_codec", :error_message=>"\n\n\t

you might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\nno such file to load 

-- org/logstash/javaapi/logstash-codec-asn_codec/0.2.0/logstash-codec-asn_codec-0.2.0 (LoadError)", :

error_class=>RuntimeError, :error_backtrace=>["uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:356:in `do_require'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:265:in `block in require_jar'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:307:in `require_jar_with_block'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jar_dependencies.rb:264:in `require_jar'", "C:/es7/logstash/lib/bootstrap/patches/jar_dependencies.rb:6:in `require_jar'", "C:/es7/logstash/logstash-core/lib/logstash-codec-asn_codec_jars.rb:2:in `<main>'", "org/jruby/RubyKernel.java:984:in `require'", "C:/es7/logstash/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/es7/logstash/logstash-core/lib/logstash/codecs/asn_codec.rb:1:in `<main>'", "org/jruby/RubyKernel.java:984:in `require'", "C:/es7/logstash/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:181:in `legacy_lookup'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:156:in `block in lookup'", "org/jruby/ext/thread/Mutex.java:165:in `synchronize'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:152:in `lookup'", "C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:206:in `lookup_pipeline_plugin'", "C:/es7/logstash/logstash-core/lib/logstash/plugin.rb:137:in `lookup'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:413:in `validate_value'", "C:/es7/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-file-4.1.10/lib/logstash/inputs/file.rb:236:in `validate_value'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:332:in `process_parameter_value'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:351:in `block in validate_check_parameter_values'", "org/jruby/RubyArray.java:1792:in `each'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:345:in `block in validate_check_parameter_values'", "org/jruby/RubyHash.java:1419:in `each'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:344:in `validate_check_parameter_values'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:234:in `validate'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:85:in `config_init'", "C:/es7/logstash/logstash-core/lib/logstash/inputs/base.rb:60:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:255:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:117:in `buildInput'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/java_pipeline.rb:23:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "C:/es7/logstash/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}

[2019-04-24T09:05:57,173][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any codec plugin named 'asn_codec'. Are you sure this is correct? Trying to load the asn_codec codec plugin resulted in this error: Problems loading the requested plugin named asn_codec of type codec. Error: RuntimeError \n\n\tyou might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\n

no such file to load -- org/logstash/javaapi/logstash-codec-asn_codec/0.2.0/logstash-codec-asn_codec-0.2.0 (LoadError)", :backtrace=>

["C:/es7/logstash/logstash-core/lib/logstash/plugins/registry.rb:211:in `lookup_pipeline_plugin'", "C:/es7/logstash/logstash-core/lib/logstash/plugin.rb:137:in `lookup'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:413:in `validate_value'", "C:/es7/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-file-4.1.10/lib/logstash/inputs/file.rb:236:in `validate_value'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:332:in `process_parameter_value'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:351:in `block in validate_check_parameter_values'", "org/jruby/RubyArray.java:1792:in `each'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:345:in `block in validate_check_parameter_values'", "org/jruby/RubyHash.java:1419:in `each'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:344:in `validate_check_parameter_values'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:234:in `validate'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:85:in `config_init'", "C:/es7/logstash/logstash-core/lib/logstash/inputs/base.rb:60:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:255:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:117:in `buildInput'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/java_pipeline.rb:23:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "C:/es7/logstash/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}

**Comment by synapticiel** [comment]
After some changes in package naming, i get an other error when running the same command logstash --java-execution -w 1 -f asn1_conf.conf





{:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"NoMethodError", :message=>"undefined method `new' for class org.logstash.javaapi.AsnCodec:Java::JavaClass", :backtrace=>["C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:413:in `validate_value'", "C:/es7/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-file-4.1.10/lib/logstash/inputs/file.rb:236:in `validate_value'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:332:in `process_parameter_value'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:351:in `block in validate_check_parameter_values'", "org/jruby/RubyArray.java:1792:in `each'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:345:in `block in validate_check_parameter_values'", "org/jruby/RubyHash.java:1419:in `each'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:344:in `validate_check_parameter_values'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:234:in `validate'", "C:/es7/logstash/logstash-core/lib/logstash/config/mixin.rb:85:in `config_init'", "C:/es7/logstash/logstash-core/lib/logstash/inputs/base.rb:60:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:255:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:117:in `buildInput'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/java_pipeline.rb:23:in `initialize'", "C:/es7/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "C:/es7/logstash/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}
[2019-04-24T13:53:31,688][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2019-04-24T13:53:36,641][INFO ][logstash.runner          ] Logstash shut down.

**Comment by danhermann** [comment]
@synapticiel, apologies for your trouble. Java codecs work only with Java plugins such as `java-stdin` and will not work with Ruby plugins such as `file`. This is not properly documented, so I will open a PR to add that to the documentation.

**Comment by synapticiel** [comment]
@danhermann bad news for me :)  i need to convert file input plugin to Java :)

**Comment by danhermann** [comment]
@synapticiel, converting the file input plugin to Java sounds like a fun project! ;)  It is likely to be technically possible to make Java codecs work with Ruby input and outputs though the required conversions back and forth between Java and JRuby datatypes would make it less efficient and performant than using codecs of the same type as the input/output. You are not the first person to mention this, so it is possible that we will end up adding support for mixing codec and input/output types even if there is a performance cost there.

**Comment by danhermann** [comment]
Doc update here: https://github.com/elastic/logstash/pull/10716

**Comment by asherzhi** [comment]
@danhermann my try use https://www.elastic.co/guide/en/logstash/7.1/java-codec-plugin.html, but failed

![image](https://user-images.githubusercontent.com/47183904/61019677-9b431a00-a3cd-11e9-88c0-8d9b7b059574.png)

**Comment by danhermann** [comment]
@asherzhi, it's most likely that you have some mismatch between the specified name and/or version of the codec plugin that you're trying to run but I'll need more info to help you. Please post your Logstash config and the source code of your codec in a post in our [Logstash forums](https://discuss.elastic.co/c/logstash), tag me (`@danhermann`) in that post, and I'll try to help you there.
