### ISSUE TITLE
[Doc] Improve content for JVM heap recommendations

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#10694]
Improve and expand content

**Comment by yuwtennis** [comment]
Dear Elastic team. Thank you for posting this issue. I appreciate your cooperation with this issue.

**Comment by yuwtennis** [comment]
@karenzone Any update with this issue ? Or perhaps is there anything that I could help ?

**Comment by karenzone** [comment]
Recommended sample is here: https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

**Comment by karenzone** [comment]
Opened #11716 to resolve this issue. Your comments are welcomed.

**Comment by karenzone** [comment]
Closed with #11716
