### ISSUE TITLE
Disabling TLS 1.0 and TLS 1.1 impossible in TCP input on logstash

### ISSUE THREAD

**Issue by murangoo** [elastic/logstash#10708]
Hi,

I have the problem to disable TLS 1.0 an TLS 1.1 on logstash TCP input. 
For example, beats input have option:
_tls_min_version | number _

 Is there (or will be in the future) any option to exclude it?

**Comment by murangoo** [comment]
Does anyone have information on this subject?

**Comment by kostasb** [comment]
This feature request is being tracked at: https://github.com/logstash-plugins/logstash-input-tcp/issues/127
