### ISSUE TITLE
logstash on operating system with no sticky bit on /tmp will systematically Failed

### ISSUE THREAD

**Issue by damdr** [elastic/logstash#10714]
Hello 

Logstash on operating system with no sticky bit on /tmp will systematically Failed with this error : 

```bash
[ERROR] 2019-04-24 13:45:17.355 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (ArgumentError) could not find a temporary directory
```

We used AWS EMR for our Big-data workload, we recently experiment an issue only on TASK and CORE instance TYPE with emr-5.20 and above.  (logstash on MASTER instance type works fine)

After several hours of troubleshooting we find **ONE** difference : 

MASTER sticky bit on `/tmp` is set : 

```bash
drwxr-xr-x  2 yarn   yarn      6 Apr 24 09:24 mapred
drwx------  3 hdfs   hdfs     40 Apr 24 09:24 namenode
drwxrwxrwt  2 hadoop hadoop    6 Apr 24 09:24 s3
drwxrwxrwt 47 root   root   4096 Apr 24 11:13 tmp
```

CORE, TASK sticky bit on `/tmp` is not set :

```bash
drwxr-xr-x  2 yarn   yarn      6 Apr 24 09:31 mapred
drwxrwxrwt  2 hadoop hadoop    6 Apr 24 09:31 s3
drwxrwxrwx 13 root   root   4096 Apr 24 14:05 tmp
```

- Version: logstash-6.7.0 and above 
- Operating System: CentOs based OS ( Linux AMAZON ) , i think same issue on other linux distribution
- Config File : N/A
- Sample Data: N/A 
- Steps to Reproduce: 

```bash
$ sudo rpm -i logstash-6.7.0.rpm
$ sudo start logstash
$ tail -f /var/log/logstash-stdout.log
```

I found help [here](https://stackoverflow.com/questions/21117878/ruby-could-not-find-a-temporary-directory) and a try to put some TMP variable as follow in `/etc/default/logstash`.
But same Error. 

```bash 
TEMP="/tmp/tmplogstash"
TMPDIR="/tmp/tmplogstash"
TMP="/tmp/tmplogstash"
```
Does the mastering of the Operating system have to impact the proper functioning of logstash ?

Where can I tell logstash to use another temporary directory?

Fixing the sticky bit on /tmp on TASK and CORE works but will my workload work well?

**Comment by danhermann** [comment]
@damdr, this looks like an expected error when running Logstash with an inaccessible temp directory. You can change the directory that Logstash uses as the temp directory by specifying the `-Djava.io.tmpdir="/my/alternate/tmp/directory"` JVM flag in your `jvm.options` file. I'm going to close this issue, but if you find additional information that may indicate that there's a bug, please provide that information here and we'll re-open it.

**Comment by damdr** [comment]
hello @danhermann  after specifying an temp directory in the `jvm.options` like this : 
```
-Djava.io.tmpdir="/tmp/templogstash"
``` 

with this permissions : 

```bash
ls -al /tmp/templogstash
total 8
drwxrwxrwt  2 logstash logstash 4096 Apr 25 12:50 .
```
i get this error : 

```
[ERROR] 2019-04-25 13:12:28.829 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (GemspecError)
[!] There was an error while loading `logstash-core-plugin-api.gemspec`: load error: psych -- java.lang.RuntimeException: BUG: we can not copy embedded jar to temp directory
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.
```

**Comment by danhermann** [comment]
@damdr, Logstash uses the temp directory to read, write, and execute files. If the owner of the Logstash process doesn't have read, write, and execute permissions on the temp directory, whether the default temp directory or a different one specified via the `java.io.tmpdir` flag, it will produce the error above. It's not immediately obvious to me why the `/tmp/templogstash` directory above is not working for you, but if, as you mentioned in your original post, "fixing the sticky bit on /tmp on TASK and CORE" machines worked for you, I would suggest doing that.
