### ISSUE TITLE
Download link has invalid certificate

### ISSUE THREAD

**Issue by judge2005** [elastic/logstash#10729]
wget https://artifacts.elastic.co/downloads/logstash/logstash-7.0.0.tar.gz
--2019-04-30 09:47:52--  https://artifacts.elastic.co/downloads/logstash/logstash-7.0.0.tar.gz
Resolving artifacts.elastic.co... 146.112.47.0, 146.112.47.2, 146.112.47.30, ...
Connecting to artifacts.elastic.co|146.112.47.0|:443... connected.
ERROR: cannot verify artifacts.elastic.co’s certificate, issued by “/CN=Cisco Umbrella Secondary SubCA nyc-SG/O=Cisco”:
  Unable to locally verify the issuer’s authority.
ERROR: certificate common name “*.opendns.com” doesn’t match requested host name “artifacts.elastic.co”.
To connect to artifacts.elastic.co insecurely, use ‘--no-check-certificate’.

**Comment by kares** [comment]
thanks for the report, believe it all seems to be resolved by now.
