### ISSUE TITLE
Proposed logstash_writer role has insufficient privileges to set up ILM

### ISSUE THREAD

**Issue by kostasb** [elastic/logstash#10722]
The proposed "Configuring Security in Logstash" role and user configurations, when setup in an Elasticsearch output with ILM enabled (or left to auto) will hit a 403.

```
Apr 25 11:09:34 localhost.localdomain logstash[3405]: LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: Got response code '403' contacting Elasticsearch at URL 'http://localhost:9200/logstash'
```

which will cause a FATAL error

> Apr 25 11:09:35 localhost.localdomain logstash[3405]: [2019-04-25T11:09:35,010][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:291:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:278:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:373:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:277:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:285:in `block in Pool'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:341:in `exists?'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:359:in `rollover_alias_exists?'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/ilm.rb:89:in `maybe_create_rollover_alias'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/ilm.rb:11:in `setup_ilm'", "/usr/share/logstash/vendor/bund
Apr 25 11:09:35 localhost.localdomain logstash[3405]: le/jruby/2.5.0/gems/logstash-output-elasticsearch-10.0.1-java/lib/logstash/outputs/elasticsearch/common.rb:51:in `block in setup_after_successful_connection'"]}

Apparently logstash tries to check for the "logstash" alias in order to set it up as part of the ILM process.

Since the indices.names in the proposed logstash_writer role is set to "logstash-*" our user logstash_internal doesn't have the privilege to run `GET /logstash`.

Workarounds:
-either disable ILM in the Logstash ES output
-or set logstash* as the index name to assign the document's proposed privileges

Places for doc update:
https://github.com/elastic/logstash/blob/7.0/docs/static/security/logstash.asciidoc

https://www.elastic.co/guide/en/logstash/7.0/ls-security.html#ls-user-access

**Comment by kostasb** [comment]
We should also consider better logging message instead/on top of the FATAL error, to make it clear that the call that failed was part of setting up the ILM path.

**Comment by VimCommando** [comment]
That is interesting, the [Configuring SSL, TLS and HTTPS to secure Elasticsearch, Kibana, Beats and Logstash](https://www.elastic.co/blog/configuring-ssl-tls-and-https-to-secure-elasticsearch-kibana-beats-and-logstash) blog post looks like it uses the expected form: `"names": [ "logstash*" ],`

We just recently updated this blog post to include the missing ILM policy permissions that were causing other failures.

**Comment by duclm2609** [comment]
I would really appreciate that a human-readable error message is logged instead of a ruby stacktrace.
