### ISSUE TITLE
Lostash multi-pipeline queue behaviour

### ISSUE THREAD

**Issue by burghategaurao** [elastic/logstash#10723]
Could anyone please help us to understand queue behaviour in case of multiple pipeline.
We have more than 500 pipelines. As per Documentation, page capacity is allocated to all pipelines.So if we set queue.page_capacity to 64mb, then for all pipelines 64mb is allocated.
So we need to understand, Is queue is one for all pipelines or Queue is specific to particular pipeline.

If we set queue.max_events to 1000 then will it means that 1000 events will be queued for all pipelines , or Will 1000 events queued for single pipeline.

**Comment by burghategaurao** [comment]
@suyograo @colinsurprenant  Could you please help us to understand this

**Comment by danhermann** [comment]
Please don't open Github issues to ping individuals with questions about Logstash usage. As the issue template notes, usage questions are best addressed in the forums:

>Please post all product and debugging questions on our forum.
>Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
>
>-- Logstash Issue Template

Per the [Logstash multi-pipeline docs](https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html), persistent queue settings are per-pipeline. Please open a thread on the [forum](https://discuss.elastic.co/c/logstash) if you need additional assistance on this.
