### ISSUE TITLE
Not able to add the RunTime dependencies

### ISSUE THREAD

**Issue by prakash1243** [elastic/logstash#10772]
I have created a customized logstash filter plugin and added the run-time dependencies; and when I try to install the plugin with --no-verify, LS throws the below error:

~~~
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    logstash-filter-kins_logs (= 0.2.0) java was resolved to 0.1.0, which depends on
      rubocop (~> 0.44.1) java
~~~

Here is the gemspec file:

~~~
 s.metadata = { "logstash_plugin" => "true", "logstash_group" => "filter" }

  # Gem dependencies
  s.add_runtime_dependency "logstash-core-plugin-api", "~> 2.0"
  s.add_development_dependency 'logstash-devutils'
  s.add_runtime_dependency "rubocop", '~> 0.44.1'
  s.add_runtime_dependency "rubocop-checkstyle_formatter", '~> 0.2'
~~~

 I believe LS would download all the dependencies mentioned in the plugin and add it on the Gemlock. Please let me know if its otherwise. Thanks !

**Comment by prakash1243** [comment]
I figured out the issue; we shouldn't use --local while installing the plugin

**Comment by yaauie** [comment]
also, are you actually using rubocop as a _runtime_ dependency, or is it really a _development_ dependency?

**Comment by prakash1243** [comment]
It is a run-time dependency, since we would have a code-quality check running from a rake file in CI Pipeline which requires rubocop as run-time dependency.
