### ISSUE TITLE
Dropped events are still reported to events.out for the pipeline

### ISSUE THREAD

**Issue by w4** [elastic/logstash#10773]
![image](https://user-images.githubusercontent.com/5258114/57374091-fd935a80-7191-11e9-8bd4-3122dcd0cf2e.png)

When there is a `drop` filter, the events are still reported to `pipelines/[id]/events/out` even if they don't make it through to the output.

Possibly related to #8752

**Comment by roaksoax** [comment]
Hello there!

We believe we have fixed this issue in #13593, and will be available in Logstash 8.0 and 7.17.0. If you believe this issue is not resolved, please re-open or create a new issue.
