### ISSUE TITLE
Fast path for buffered outputs with no filters

### ISSUE THREAD

**Issue by w4** [elastic/logstash#10795]
With a Logstash configuration like this:

```
input {
  java_kinesis {
    kinesis_stream_name => "abc-gzipped"
    codec => java_gzip
  }
}

filter {}

output {
  kinesis {
    kinesis_stream_name => "abc-ungzipped"
  }
}
```

Would it make sense for Logstash to still buffer events to the filter thread rather than the fast path of input -> output, letting the output block the input thread (which would normally have been blocked by the queue)?

I can see the use for low-throughput pipelines where you'd still want to run inputs through the codec while the output is blocking however it seems like a bit of a waste of resources in high-throughput environments to write to the filter queue when (a lot of?) outputs already buffer and the inputs are already threaded.

**Comment by guyboertje** [comment]
@w4 
Logstash does not work quite as you describe.

The current version of LS is 7.x and it uses the java execution engine by default.

As you say the inputs are separately threaded and feed events into a queue. There are two types of queues, memory and persisted. The memory queue is a 1000 (workers * batch size) entry ArrayBlockingQueue but the persistent queue size is bound by disk space. Both queues have a single event writer and a batch size event reader.

At compilation the config is turned into a Directed Acyclic Graph, the filter/output piece of the graph is given to a pipeline worker to execute. If there are no filters configured then there are no filter or conditional branch nodes in the graph.

This not true of the ruby execution engine, a filter function traverses an empty structure - a no op and execution is passed on to the output function.

With the memory queue there is a form of synchrony happening an input thread will block when the the queue is full and the workers are all busy with filtering or outputting.
With the persistent queue the input threads do not block until queue capacity is reached.

The outputs do not (should not in the case of 3rd party plugins) buffer events as such, events are held in a batch object and the output should try to deliver these events downstream (forever).

**Comment by w4** [comment]
Ah right, makes sense. This issue comes out the back of us implementing an intermediate queue between our Logstash instances using logstash-output-kinesis which has an external C++-based process that batches events in the background on top of the Logstash batches (where something like this would be useful) & I'd read something a while ago relating to logstash-output-elasticsearch batching events for the _bulk request and I assumed this was further batching separate to the  `batch_size` events but looking further into this seems my assumptions were incorrect.

Thanks for the detailed explanation @guyboertje
