### ISSUE TITLE
Recursive depth of Logstash - not finding my files?

### ISSUE THREAD

**Issue by sgreszcz** [elastic/logstash#10800]
- Version: 7.0.1
- Operating System: Ubuntu 18.04 LTS
- Config File (if you have sensitive info, please remove it):

```
input {
    file {
        id => "perfmon-in"
        path => "/data/tracelogger/tracelogger_data/*/*/*/*/*/*/*/*/PerfMon*"
        sincedb_path => "/data/elk/logstash/sincedb"
        start_position => "beginning"
        tags => ["perfmon"]
    }
}

filter {
  csv {
    id => "perfmon-filter"
    autodetect_column_names => "true"
    convert => {
      "column1" => "date_time"
    }
  }
}

output {
    if "perfmon" in [tags]{

    	elasticsearch
    	{
		hosts => "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"
		manage_template => false
		index => "perfmon-%{+YYYY.MM.dd}"
		id => "perfmon-out"
	    }
	    stdout { codec => rubydebug }
    }
}
```

- Sample Data:

Doesn't even find the file when trace debugs are on.

- Steps to Reproduce:

I've tried with this path:
```
path => "/data/tracelogger/tracelogger_data/*/*/*/*/*/*/*/*/PerfMon*"
```
and it doesn't work, and it also doesn't work like this:
```
path => "/data/tracelogger/tracelogger_data/**/PerfMon*"
```

But it does work like this (fully described).
```
path => "/data/tracelogger/tracelogger_data/processed/AP4/10.66.132.23/2019-05-17_20-21-30/cm/log/ris/csv/PerfMon*"
```

Discussion here: https://discuss.elastic.co/t/recursive-depth-of-logstash-not-finding-my-files/181602/8

**Comment by axpatito** [comment]
Same issue. Working with logstash "7.1.1".

My configs has many subdirectories, but I get a silent fail on "/some/path/**/*.txt"

**Comment by yaauie** [comment]
I've moved this issue to the Logstash File Input Plugin so it can get the appropriate attention:

https://github.com/logstash-plugins/logstash-input-file/issues/241
