### ISSUE TITLE
Random logstash crashes

### ISSUE THREAD

**Issue by bryantcj52** [elastic/logstash#10801]
After startup, logstash will randomly crash with the following error:

`[2019-05-20T01:02:26,785][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>java.nio.channe
ls.ClosedByInterruptException, :backtrace=>["java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterr
uptibleChannel.java:202)", "sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)", "org.logstash.ackedqueue.
io.FileCheckpointIO.write(FileCheckpointIO.java:79)", "org.logstash.ackedqueue.Page.forceCheckpoint(Page.java:205)
", "org.logstash.ackedqueue.Page.headPageCheckpoint(Page.java:170)", "org.logstash.ackedqueue.Page.checkpoint(Page
.java:159)", "org.logstash.ackedqueue.Queue.ack(Queue.java:643)", "org.logstash.ackedqueue.Batch.close(Batch.java:
37)", "org.logstash.ackedqueue.AckedBatch.close(AckedBatch.java:33)", "org.logstash.ackedqueue.AckedReadBatch.clos
e(AckedReadBatch.java:77)", "org.logstash.execution.QueueReadClientBase.closeBatch(QueueReadClientBase.java:111)",
 "org.logstash.execution.QueueReadClientBase.rubyCloseBatch(QueueReadClientBase.java:130)", "usr.share.logstash.lo
gstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0(/usr/share/logstash/logstash-core/lib/logstash/p
ipeline.rb:342)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_workers$2(/usr/sh
are/logstash/logstash-core/lib/logstash/pipeline.rb:304)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(Compi
ledIRBlockBody.java:136)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)", "org.jruby.runtime.Block.cal
l(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:295)", "org.jruby.RubyProc.call(RubyProc.java:274)", "o
rg.jruby.RubyProc.call(RubyProc.java:270)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.lang.Thread.run(Thread.java:748)"]}
[2019-05-20T01:02:28,825][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
`

Nothing before it or any indication of what is causing it. Sometimes it happens 30 seconds after startup or 3 hours and usually multiple times in a row as systemd will keep starting logstash back up. This is only happening on our production cluster (3 stack servers with ES, logstash, kibana, apm-server) and not stage (single stack server, and much less data consumption).

Logstash version: 6.7.2
CentOS 7
Xms and Xmx was 2gb, increased to 4gb to see if it would help

Using Beats input on all three servers:
```
input {
  beats {
    id => "beatsInput"
    port => 5044
    client_inactivity_timeout => 0
  }
}
```

One of the logstash servers also has the s3 input plugin
```
input {
  s3 {
    bucket => "**"
    region => "**"
    type => "elb-access"
    codec => plain {
      charset => "ISO-8859-1"
    }
  }
}
```

**Comment by danhermann** [comment]
As of the 6.7.0 release, Logstash uses JRuby 9.2 which appears to have different error handling behavior (https://github.com/elastic/logstash/issues/10612) such that certain error conditions that were previously handled within the Logstash event pipeline now propagate up and terminate Logstash. We're actively working on that problem as it is affecting a lot of Logstash use cases.

We think that disabling the timeout on any grok or kv filters that you have in your pipeline might be a workaround for this, but we're still working to establish that, too.

**Comment by bryantcj52** [comment]
Thanks, disabling Grok timeouts seems to have helped.

**Comment by danhermann** [comment]
I'm going to close this issue. We're tracking the fix of the root issue on https://github.com/elastic/logstash/issues/10612 if you're interested in that.

**Comment by zeph** [comment]
+1 on the possibility of being grok the culprit
