### ISSUE TITLE
Document copy semantics of QueueWriter::push method

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#10806]
An intentional part of the design for Java inputs relies on the ability to maintain a single mutable map instance that is repeatedly mutated and presented to `QueueWriter::push` because that significantly reduces allocations and GC pressure for inputs with high event volumes and/or large numbers of common fields. This behavior is not explicitly documented on `QueueWriter` and should be.

**Comment by yaauie** [comment]
Have we tested that sharing a single mutable map is _actually_ more performant here than using optimised singletons via `Collections.singletonMap(K,V)` (overhead is literally one object that has exactly two properties, no underlying hash tables or keysets ([source](https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/Collections.java#l4919))), or guava's `ImmutableMap.of(K,V)` variants, which have similar optimised performance characteristics?

**Comment by danhermann** [comment]
Yes, even for the simplest case in which there is a single key and value, reusing a mutable map outperforms creating a new singleton map in both overall event throughput and GC load. For more complex use cases where events have many fields and nested structures, the performance differential in favor of the reused mutable map increases.
