### ISSUE TITLE
Feature request: support for nanosecond timestamps

### ISSUE THREAD

**Issue by bmerry** [elastic/logstash#10822]
Now that Elasticsearch 7.x [supports nanosecond timestamps](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/release-highlights-7.0.0.html#_support_nanosecond_timestamps), it would be nice if they could pass through logstash as well (in my case I want them just for better sorting). It looks like the Timestamp class is still based on Joda rather than Java 8 so presumably only supports milliseconds.

**Comment by TomGudman** [comment]
This is a feature we all need when you deal with a high throughput of logs. 

Often we check logs on box due to the interleaved effect in Kibana inherent to milliseconds precision only.

I've also discovered that logstash is now the bottleneck for nanoseconds probably because of joda time. Since ES7.x announcement, I guess the whole community believe it's a done deal but it's far from it. 

**Current state**:
- Elasticsearch 7.x  : supports nanoseconds (`date_nanos`)
- Logstash : **status unknown** :(
- Filebeat : work in progress ( [PR](https://github.com/elastic/beats/pull/9818) )
- Kibana : supports nanooseconds

_References_:
- https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-match : Look for: "Maximum precision is milliseconds (SSS). Beyond that, zeroes are appended."

**Comment by TomGudman** [comment]
@bmerry : Can you edit your issue title to add the word nanoseconds? 

Google did not find this issue. I only found this issue via Github issue search. 

If more people :+1: this request then it may get more traction. 

In the mean time, we can only wait that some skilled programmers can improve the situation ;-)

**Comment by TomGudman** [comment]
Thanks @bmerry . Now we just have to wait...

**Comment by weizhu-us** [comment]
We would love to have this.

**Comment by th0ger** [comment]
Any known workarounds? (in logstash, but without the date filter).

**Comment by bmerry** [comment]
I've worked around it by adding an extra field called `timestamp_precise` to the GELF log records (in our Python logging framework, before they reach Logstash), and then using an Elasticsearch pipeline to use that field to overwrite `@timestamp` when available. I couldn't find a way to do this without modifying the source of the logs, because Logstash gobbles up the standard GELF timestamp before any filters have a chance to extract it. You might have better luck if you're extracting timestamps by grokking flat text logs.

Here's the Elasticsearch pipeline:

```
{
  "description": "transfers timestamp_precise to @timestamp if present",
  "processors": [
    {
      "set": {
        "field": "timestamp_coarse",
        "value": "{{@timestamp}}"
      }
    },
    {
      "remove": {
        "field": "@timestamp",
        "if": "ctx.containsKey('timestamp_precise')"
      }
    },
    {
      "rename": {
        "field": "timestamp_precise",
        "target_field": "@timestamp",
        "ignore_missing": true
      }
    }
  ]
}
```

**Comment by juan-domenech** [comment]
I've got nanoseconds working on logs with this precision having @timestamp and @timesamp_nanos fields coexisting at the same time and telling Kibana to use nanos as main timestamp:
https://discuss.elastic.co/t/how-to-index-nanoseconds-precision-events-with-logstash-7-10-and-type-date-nanos/262029

**Comment by bmerry** [comment]
Great to hear that there is now some forward progress here. Any idea whether the workaround can be used with the gelf input plugin, or will the plugin need to be updated?

**Comment by yaauie** [comment]
> Great to hear that there is now some forward progress here. Any idea whether the workaround can be used with the gelf input plugin, or will the plugin need to be updated?
> -- https://github.com/elastic/logstash/issues/10822#issuecomment-955675347

My reading of the code is that on Logstash 8, events created by the Gelf input will maintain the precision of what is available, since it uses the `LogStash::Timestamp::at` API to generate the timestamp from a numeric epoch, and `LogStash::Timestamp` maintains precision up to nanos. This means that no "workaround" will be needed.

**Comment by bmerry** [comment]
Thanks, that's great news.

**Comment by roaksoax** [comment]
Given that Logstash 8.0 does already support nanosecond on timestamps, I'll close this issue.

**Comment by alfonsoveneziano** [comment]
> I've worked around it by adding an extra field called `timestamp_precise` to the GELF log records (in our Python logging framework, before they reach Logstash), and then using an Elasticsearch pipeline to use that field to overwrite `@timestamp` when available. I couldn't find a way to do this without modifying the source of the logs, because Logstash gobbles up the standard GELF timestamp before any filters have a chance to extract it. You might have better luck if you're extracting timestamps by grokking flat text logs.
> 
> Here's the Elasticsearch pipeline:
> 
> ```
> {
>   "description": "transfers timestamp_precise to @timestamp if present",
>   "processors": [
>     {
>       "set": {
>         "field": "timestamp_coarse",
>         "value": "{{@timestamp}}"
>       }
>     },
>     {
>       "remove": {
>         "field": "@timestamp",
>         "if": "ctx.containsKey('timestamp_precise')"
>       }
>     },
>     {
>       "rename": {
>         "field": "timestamp_precise",
>         "target_field": "@timestamp",
>         "ignore_missing": true
>       }
>     }
>   ]
> }
> ```

Hi, sorry for reopening the discussion. I've tried to use the pipeline using a timestamp_precise field that contains the date with nanoseconds precision in text format e.g. "timestamp_precise":"2022-10-28T19:43:57.867631621Z") but it does not work for me.
Could you please help to figure out what is wrong?
Thanks
BRs, alfonso

**Comment by alfonsoveneziano** [comment]
> > I've worked around it by adding an extra field called `timestamp_precise` to the GELF log records (in our Python logging framework, before they reach Logstash), and then using an Elasticsearch pipeline to use that field to overwrite `@timestamp` when available. I couldn't find a way to do this without modifying the source of the logs, because Logstash gobbles up the standard GELF timestamp before any filters have a chance to extract it. You might have better luck if you're extracting timestamps by grokking flat text logs.
> > Here's the Elasticsearch pipeline:
> > ```
> > {
> >   "description": "transfers timestamp_precise to @timestamp if present",
> >   "processors": [
> >     {
> >       "set": {
> >         "field": "timestamp_coarse",
> >         "value": "{{@timestamp}}"
> >       }
> >     },
> >     {
> >       "remove": {
> >         "field": "@timestamp",
> >         "if": "ctx.containsKey('timestamp_precise')"
> >       }
> >     },
> >     {
> >       "rename": {
> >         "field": "timestamp_precise",
> >         "target_field": "@timestamp",
> >         "ignore_missing": true
> >       }
> >     }
> >   ]
> > }
> > ```
> 
> Hi, sorry for reopening the discussion. I've tried to use the pipeline using a timestamp_precise field that contains the date with nanoseconds precision in text format e.g. "timestamp_precise":"2022-10-28T19:43:57.867631621Z") but it does not work for me. Could you please help to figure out what is wrong? Thanks BRs, alfonso

Hi,
I got the same result by adding a pipeline in Elasticsearch:

```
{
        "description": "mypipeline",
        "processors": [
            {
                "date": {
                    "field": "timestamp_nano",
                    "formats": ["ISO8601"],
                    "output_format": "yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSSZ"
                }
            }
        ]
}
```
The timestamp_nano includes a timestamp with nanoseconds precision.
BRs

**Comment by juan-domenech** [comment]
For those waiting (like me) for the Date filter to handle nanosecond precision in 8.x, there are a couple of workarounds:

- Using JSON filter to inject @timestamp into the event https://stackoverflow.com/a/70788618/2834587
- Using Ruby to overwrite @timestamp https://stackoverflow.com/a/73319562/2834587

I hope it helps!
