### ISSUE TITLE
[DOCS] Add brew installation instructions

### ISSUE THREAD

**Issue by debadair** [elastic/logstash#10846]
Update the installation info to:

- Add a brew  installation option to the [install page](https://www.elastic.co/guide/en/logstash/current/installing-logstash.html) and give it the anchor [[brew]]

To use brew to install the stack components, users will first need to “tap” the Elastic Homebrew repo. See https://github.com/elastic/elasticsearch/pull/42915.

**Comment by karenzone** [comment]
Closed with merge of #10874
