### ISSUE TITLE
Cannot install sflow

### ISSUE THREAD

**Issue by davidshirk80** [elastic/logstash#10887]
NOTE - I HAVE TRIED SETTING GEM SOURCE TO HTTP TEMP AND STILL NOTHING!!!
TLS is set to use 1.2 all the way on up to modern. I can hit other https sites just fine.

xxx@xxx:~ sudo /usr/share/logstash/bin/logstash-plugin install logstash-codec-sflow Validating logstash-codec-sflow Unable to download data from https://rubygems.org - Connection reset by peer (https://api.rubygems.org/latest_specs.4.8.gz) ERROR: Installation aborted, verification failed for logstash-codec-sflow xxx@xxx:~ ping api.rubygems.org
PING rubygems.org (151.101.128.70) 56(84) bytes of data.
64 bytes from 151.101.128.70 (151.101.128.70): icmp_seq=1 ttl=55 time=40.2 ms
64 bytes from 151.101.128.70 (151.101.128.70): icmp_seq=2 ttl=55 time=40.1 ms
64 bytes from 151.101.128.70 (151.101.128.70): icmp_seq=3 ttl=55 time=52.6 ms
64 bytes from 151.101.128.70 (151.101.128.70): icmp_seq=4 ttl=55 time=41.1 ms
^C
--- rubygems.org ping statistics ---

I am running Ubuntu 18.04 (and tried disco dingo as well) - elastic stack 7.1 (elasticsearch, kibana, logstash), and on bare metal server. No nat and no firewalls are blocking.

I followed these directions:
https://www.catapultsystems.com/blogs/install-elastiflow-on-ubuntu-18-04

What else would cause my server to have issues with downloading sflow plugin and that plugin only as I can get everything else just fine.

**Comment by davidshirk80** [comment]
xxx@xxx:~# DEBUG=1 bin/plugin install logstash-codec-sflow
bash: bin/plugin: No such file or directory
root@usmlbnetflw:~# DEBUG=1 /usr/share/logstash/bin/logstash-plugin install logstash-codec-sflow
Using GEM_HOME=/usr/share/logstash/vendor/bundle/jruby/2.5.0
Using GEM_PATH=/usr/share/logstash/vendor/bundle/jruby/2.5.0
DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install logstash-codec-sflow
Looking if package named: logstash-codec-sflow exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-codec-sflow/logstash-codec-sflow-7.1.1.zip
Package not found at: https://artifacts.elastic.co/downloads/logstash-plugins/logstash-codec-sflow/logstash-codec-sflow-7.1.1.zip
Validating logstash-codec-sflow
Unable to download data from https://rubygems.org - Connection reset by peer (https://api.rubygems.org/latest_specs.4.8.gz)
ERROR: Installation aborted, verification failed for logstash-codec-sflow

**Comment by davidshirk80** [comment]
As seen above - sflow is not in the current library it seems. Can you please update?

**Comment by davidshirk80** [comment]
Is this even considered an issue, or is sflow codec not supported in the updated logstash?

**Comment by jsvd** [comment]
hi @davidshirk80 , the sflow codec isn't created or maintained by Elastic, you can see the owners here: 
 https://rubygems.org/gems/logstash-codec-sflow/

**Comment by jsvd** [comment]
that said, overall there should be no issue in installing the codec. locally I can install it correctly:

```
/tmp/logstash-7.1.0 % bin/logstash-plugin install logstash-codec-sflow
Validating logstash-codec-sflow
Installing logstash-codec-sflow
Installation successful
/tmp/logstash-7.1.0 % bin/logstash-plugin list --verbose sflow
logstash-codec-sflow (2.0.0)
```

**Comment by davidshirk80** [comment]
root@x:~# service logstash status
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/logstash.service.d
           └─elastiflow.conf
   Active: active (running) since Wed 2019-06-26 16:30:54 UTC; 6s ago
 Main PID: 48945 (java)
    Tasks: 39 (limit: 7372)
   Memory: 704.9M
   CGroup: /system.slice/logstash.service
           └─48945 /usr/bin/java -Xms4g -Xmx4g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby

Jun 26 16:30:54 usmlbnetflw systemd[1]: Started logstash.

root@x:~# find / -name logstash-codec-sflow
root@x:~#

**Comment by davidshirk80** [comment]
And are you on bare metal and what linux flavor?

**Comment by davidshirk80** [comment]
The thing is - logstash when it was installed did not have the sflow codec in it. Ergo when it tries to validate, there is nothing to validate.

**Comment by davidshirk80** [comment]
Closing.....Cisco SFR redirect had been tripped.....that was a total pita to find.......
