### ISSUE TITLE
Docs for monitoring Logstash with Metricbeat

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#10920]
Going forward, the plan is for stack products to be monitored with Metricbeat instead of the products internally monitoring themselves. So far this plan has been implemented for Elasticsearch and Kibana.

For Elasticsearch, see https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html. Note that this page is linked to from https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-monitoring.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/collecting-monitoring-data.html.

For Kibana, see https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html. Note that this page is linked to from https://www.elastic.co/guide/en/kibana/current/configuring-monitoring.html and https://www.elastic.co/guide/en/kibana/current/monitoring-kibana.html.

We will need equivalent documentation pages for Logstash as well, as Metricbeat has gained the ability to monitor Logstash starting from 7.3.0.

**Comment by ycombinator** [comment]
Hi @lcawl, please let me know if I can help with this issue/associated PRs. Thanks!

**Comment by cachedout** [comment]
Ping @lcawl . This is getting quite close to release. Has this been started?

**Comment by 09029516849** [comment]
@

**Comment by ycombinator** [comment]
Hi @karenzone, any ideas when you might be able to update https://www.elastic.co/guide/en/logstash/7.3/configuring-logstash.html to look more like https://www.elastic.co/guide/en/elasticsearch/reference/7.3/configuring-monitoring.html or https://www.elastic.co/guide/en/kibana/7.3/configuring-monitoring.html or https://www.elastic.co/guide/en/beats/filebeat/7.3/monitoring.html? Essentially the Logstash page needs to show that there are now (starting 7.3 onwards) two ways of configuring Monitoring — internal collection and Metricbeat collection. Prior to that only internal collection was supported.

**Comment by karenzone** [comment]
WIP amidst other priorities

**Comment by ycombinator** [comment]
Hey @karenzone, just want to follow up on this again, since it's been a few weeks. I see the WIP PR. Please let me know if I can help move it forward. Thanks!

**Comment by karenzone** [comment]
Thanks, @ycombinator.  Yes, please! Let's sync on status and best path forward, please.  I'll DM you to arrange.

**Comment by karenzone** [comment]
Addressed with #11033
