### ISSUE TITLE
[meta] kv and grok filters timeout handling

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#10976]
### Description

Both the kv and grok filters share a similar strategy for supporting the timeout option to abort long running regex operations. 

The strategy, initially put in place for grok, is to rely on the [Java interrupt status flag](https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html). The basic idea is  to create a watchdog thread which monitor the time spent from the worker thread inside the regex parsing calls (that are ultimately handled by the Java joni regex library). Upon figuring that a worker thread has spent too much time in a regex call, to abort it, it sets that worker thread underlying Java thread interrupt status by using `Thread.interrupt()`. See [kv implementation for example]( https://github.com/logstash-plugins/logstash-filter-kv/blob/4a1ff66266b16608dd4398aa50c12e24cf146d5f/lib/logstash/filters/kv.rb#L670-L673).

### Problem

We have realized that logstash was sometimes randomly crashing with `InterruptedException` and figured these were tied to the grok and kv filters timeout handling and also figured that the timeout was not working at all in other cases.

The problem seems to be related to the direct manipulation of the Java interrupt status flag on the underlying Java thread from a JRuby execution context. JRuby threads + runtime has its own layer to handle the Java interrupt status flag, see the [RubyThread implementation](https://github.com/jruby/jruby/blob/8a269e34ff3d242ec90fb08061f79c2757a5e157/core/src/main/java/org/jruby/RubyThread.java#L723-L732). We can see that the `RubyThread.pollThreadEvents()` method calls `RubyThreads.anyInterrupted()` which is turn call `Thread.interrupted()` which [reads and resets the  interrupt status flag](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#interrupted--) :

> The interrupted status of the thread is cleared by this method. In other words, if this method were to be called twice in succession, the second call would return false 

The problem is that that the JRuby `RubyThread.pollThreadEvents()` methods is invoked in [many places in the JRuby runtime](https://github.com/jruby/jruby/search?q=pollThreadEvents&type=Code) and **it is very hard to predict the behaviour of explicitly setting a Java thread interrupt flag from a JRuby context** because once set in Java from JRuby,  the JRuby runtime will continue to be invoked up until the final joni Java code is executed. 

Also looking at this [JRuby issue](https://github.com/jruby/jruby/issues/5476) we can see that figuring the right interruption semantics between Java and Ruby in not trivial and that these implementation details can change. Relying on such implementation details can become future problems if these implementation details change. 

### Solution

I am not sure. There are possibly two paths; 
- Finding a fix for the current Ruby plugins implementations of grok and kv, maybe look into using the `Timeout` class? 
- Rewriting both plugins in pure Java using the Java plugins API and make sure that setting the Java thread interrupt flag on a thread is never inter winded with JRuby execution  on that same thread?

**Comment by colinsurprenant** [comment]
/cc @headius @kares do you think this is a correct assessment of a strategy of directly using Java `Thread.interrupt()` from JRuby?

I see that this strategy was actually suggested back then (1.7.3) by @headius in https://github.com/jruby/jruby/issues/792 because `Timeout` did not seem to be working correctly with joni - I will have to see what the state of this is.

**Comment by kares** [comment]
will need to look at details, but there's a somehow recent interrupt related change, altough pbly not regexp related (certainly smt where logstash was considered). anyways, there's some support in joni itself for regexp timeouts that isn't used much but could be fine tuned if it would help logstash's case ...

**Comment by colinsurprenant** [comment]
@kares thanks - you probably refer to https://github.com/jruby/jruby/pull/5683 ? 

While ultimately the end goal is about interrupting a long regex call in joni (and obviously all suggestions are welcome) my question is more about the potential dangers of using Java `Thread.interrupt()` from JRuby? My assessment is that it is dangerous and can lead to hard to predict behaviours. Feedback about that would be useful in helping to decide if we should spend more energy in trying to make it work correctly or is it probably better to avoid that?

**Comment by jsvd** [comment]
> Finding a fix for the current Ruby plugins implementations of grok and kv, maybe look into using the Timeout class?

From what I tested I see no current way of interrupting joni from jruby, be it [using interrupt](https://gist.github.com/jsvd/a3556820266838c53dff0ed4466dc214#file-using_interrupt-rb) or [ruby's Timeout](https://gist.github.com/jsvd/a3556820266838c53dff0ed4466dc214#file-using_timeout-rb).

**Comment by colinsurprenant** [comment]
FYI I found some history on joni's interruptibility; https://github.com/jruby/joni/pull/6 and digging further I realize that an option was added to control joni's interruptability from JRuby https://github.com/jruby/jruby/blob/493822c134fe74e9630d2dc49325e291008b3101/core/src/main/java/org/jruby/util/cli/Options.java#L147 and it is off by default. 

@jsvd running your above interrupt example using 
```
jruby -Xregexp.interruptible=true using_interrupt.rb
``` 
actually works - so that solves the mystery of why joni's interruption stopped working at some point.

**Comment by jsvd** [comment]
yep, this makes both java interrupt and ruby's Timeout work again.

**Comment by colinsurprenant** [comment]
pushed kv logstash-plugins/logstash-filter-kv#84 and grok logstash-plugins/logstash-filter-grok#147 modifications

**Comment by untergeek** [comment]
👏 Well done, gentlemen. I know a few sites I've visited had kv timeout issues, and this is a tremendous bit of investigation and correction. Bravo!

**Comment by colinsurprenant** [comment]
Also related and somewhat full-circle logstash-plugins/logstash-filter-grok#130 logstash-plugins/logstash-filter-grok#131

**Comment by colinsurprenant** [comment]
grok v4.1.0 and kv v4.4.0 have been published both using `Timeout.timeout` instead direct Java `Thread.interrupt()` for timeout handling.

**Comment by colinsurprenant** [comment]
For reference, we traced back to **v6.7.0** (where JRuby was updated from 9.1.13.0 to 9.2.6.0) when joni interruptability was disabled by default and resulted in both the kv and grok filters timeout options just not working. This is tracked in #10978

**Comment by colinsurprenant** [comment]
I am closing this issue since a fix was pushed. 

Note that we discovered a substantial performance regression with the current fix as described in #11302
