### ISSUE TITLE
Missing stats in /_node/stats/pipelines after upgrade to 7.3.0

### ISSUE THREAD

**Issue by lukasertl** [elastic/logstash#11021]
My logstash setup runs 20+ pipelines and I use the /_node/stats/pipelines API endpoint to monitor the throughput for each pipeline.

After upgrading from 7.2.0 to 7.3.0 the stats output only has metrics for one pipeline (and the pipeline it shows seems to be randomly chosen after restarts).

The /_node/pipelines API however lists all pipelines configured on the node.

- Version:
7.3.0

- Operating System:
CentOS 7

**Comment by redbaron4** [comment]
I have the same issue. I've asked for help on the [discuss forum](https://discuss.elastic.co/t/logstash-7-3-0-node-stats-api-does-not-list-all-pipelines/195724) too.

Looking at the code, I've found #10576 and #10120 which probably made these changes.
