### ISSUE TITLE
Introduce deprecation logging

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#11049]
Currently logstash doesn't have a unified way for its components to log deprecation notices, we just tend to log them as warnings and they show up in the normal log.

There should be a way for any piece of core and plugins to log a deprecation warning that would end up in a separate log file.
This would be very helpful for development of a new major version, where we could start failing builds if any deprecation logs were generated. It also helps users prepare for a major upgrade, as they'd have a single location to see if they're still using any feature that will stop working after the upgrade.

This issue isn't meant to be an implementation proposal, just a way to alert for this need.

**Comment by andsel** [comment]
it log4j properties could be created a log appender (with additivity flag to false) with a special name (e.g. DEPRECATION_LOG) and then in all the code points where actually it's logged something with the keyword deprecation, grab this from LogManager with getLogger("DEPRECATION_LOG") and use it.

**Comment by andsel** [comment]
I think I've found 3 places where we have such log:
```
lib/logstash/agent.rb:58:      logger.warn("deprecated setting `config.field_reference.parser` set; field reference parsing is strict by default")
lib/logstash/config/mixin.rb:102:        self.logger.warn("You are using a deprecated config setting " +
lib/logstash/patches/clamp.rb:63:          self.class.logger.warn "DEPRECATION WARNING: The flag #{option.switches} has been deprecated, please use \"--#{opts[:new_flag]}=#{opts[:new_value]}\" instead."
```
my  questions is:
- is only this locations that you have in mind?
- does the solution based on special logger name (es `deprecated_log` or something similar) is good for you?

**Comment by jsvd** [comment]
> is only this locations that you have in mind?

It should be a general feature that can be used in core but also plugins.

Although there's a way to mark a config option as deprecated, there's often a need to deprecate a **certain part**  of a setting, e.g.:
`config :modes => ["slow", "fast", "wooahh"]`, and we want to deprecate `"slow"`, a plugin author should be able to trigger a deprecation notice in the plugin's setup method (`#register`).


> does the solution based on special logger name (es deprecated_log or something similar) is good for you?

As long as we document this in the plugin development guide, that should be enough, e.g.

`LogManager.getLogger("DeprecationLogger").warn("Setting \"slow\" will be deprecated in the next major version, use \"fast\" instead")`

**Comment by andsel** [comment]
Instead of give the notice to the plugin developers (probably someone misspells the logger name, and have no deprecation notice and similar problems) we could use the same idea that ES team used. They implemented a special class named `DeprecationLogger` that essentially is a wrapper around a logger, but it carries the task to use correct logger name (in their case they append a `deprecation` to the logger). Also provide a useful method named `deprecate` that simply log at warn level to the deprecation logger and appender. For the plugins we could provide 2 loggers, the normal one and the deprecation so then is also easy to grep into the code to found where these things are used

**Comment by jsvd** [comment]
I'm 100% in favor of that approach :)

**Comment by andsel** [comment]
Closed because the PR https://github.com/elastic/logstash/pull/11260 has been merged
