### ISSUE TITLE
TLD extract feature request to get the parent domain

### ISSUE THREAD

**Issue by mbudge** [elastic/logstash#11079]
Hi, 

Would it be possible to add a TLD extract filter to Logstash, which uses the public suffix list to get the parent domain? If TLD extract fails to get the parent domain (it could be a Punny code domain), it should add the original domain to the target field so users only need to search the target fields to find the relevant logs/documents. 

At the moment if they search for malware.com they won't find connections to foo.malware.com.

The Elastic Common Schema already has a parent/registered domain field for DNS, and I've made a pull request to add the following to ECS. 

source.domain.parent
destination.domain.parent
url.domain.parent

https://github.com/elastic/ecs/pull/531

https://www.elastic.co/guide/en/ecs/current/ecs-dns.html

It would be useful if Logstash could update the public suffix list every 24 hours if the filter is being used. Doing this in a Logstash filter will be useful for users who ingest syslog directly from Beats agents, as they can't use a parsing script to manually get the parent domain with a TLD extract library.

**Comment by yaauie** [comment]
There exists a [TLD Filter Plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-tld.html), but it uses the `public-suffix` gem for parsing. I would advise opening an issue or pull-request for adding the refresh interval on https://github.com/logstash-plugins/logstash-filter-tld

**Comment by mbudge** [comment]
It would be good if the TLD extract filter was a core Logstash plugin which can extract the subdomain, root domain and top level domain. It would need to reload the public suffix list from a file on the server.

https://publicsuffix.org/
