### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by linuxwyn** [elastic/logstash#11090]
[2018-08-21T20:05:36,111][INFO ][logstash.outputs.elasticsearch] retrying
failed action with response code: 429
({"type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of
org.elasticsearch.transport.TransportService$7@85be457 on
EsThreadPoolExecutor[bulk, queue capacity = 200,
org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@538c9d8a[Running,
pool size = 16, active threads = 16, queued tasks = 200, completed tasks =
685]]"})

**Comment by kares** [comment]
you could find details on ES's HTTP 429 on [discussion forums](https://discuss.elastic.co/t/in-which-case-elasticsearch-will-return-429/23483), there's not general advice to give from Logstash's point of view wout knowing details about why ES is unable to keep up ...
