### ISSUE TITLE
Logstash upgrade overwrites customized /etc/default/logstash

### ISSUE THREAD

**Issue by farrp** [elastic/logstash#11151]
- Version: logstash 7.3.1
- Operating System: CentOS 7
- Config File: /etc/default/logstash
- Sample Data:

Contents of /etc/default/logstash before update:
LS_HOME="/usr/share/logstash"
LS_SETTINGS_DIR="/etc/logstash"
LS_PIDFILE="/var/run/logstash.pid"
LS_USER="logstash"
LS_GROUP="logstash"
LS_GC_LOG_FILE="/var/log/logstash/gc.log"
LS_OPEN_FILES="16384"
LS_NICE="19"
SERVICE_NAME="logstash"
SERVICE_DESCRIPTION="logstash"
LS_LOCATION=somewhere
LS_ELASTIC_USER="XXXXXXXXX"
LS_ELASTIC_PASSWD="**********"

Contents of /etc/default/logstash after update:
LS_HOME="/usr/share/logstash"
LS_SETTINGS_DIR="/etc/logstash"
LS_PIDFILE="/var/run/logstash.pid"
LS_USER="logstash"
LS_GROUP="logstash"
LS_GC_LOG_FILE="/var/log/logstash/gc.log"
LS_OPEN_FILES="16384"
LS_NICE="19"
SERVICE_NAME="logstash"
SERVICE_DESCRIPTION="logstash"

- Steps to Reproduce:
1. Add custom entries to /etc/default/logstash
2. Run "yum update logstash"
3. Customizations in /etc/default/logstash are erased with no apparent backup or warning

The upgrade process should warn that the file will be changed and preferably offer the option to keep, overwrite or merge. It should also make a backup of the old file before wiping it out.

**Comment by chrisgacsal** [comment]
@farrp You need to define these parameters in `/etc/logstash/startup.options` file as the `system-install` script is being executed during package install/upgrade: https://github.com/elastic/logstash/blob/533d5c169df4b9afd7398504d65d1510632839f3/pkg/debian/after-install.sh#L11
More on this [here](https://www.elastic.co/guide/en/logstash/current/config-setting-files.html).
