### ISSUE TITLE
Java execution may start inputs before compilation of filters and outputs has completed.

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#11170]
When processing large and complex pipelines, there may be a significant delay between the inputs starting and the compilation of the filters and outputs, which does not happen with the ruby execution.

The issue is that the compilation is done in [separate threads](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/java_pipeline.rb#L250) in the [constructor of the WorkerLoop](https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java#L46), but the main thread does not wait for this to be completed before [starting the inputs](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/java_pipeline.rb#L257)

**Comment by colinsurprenant** [comment]
PR in #11492

**Comment by colinsurprenant** [comment]
Fix merged, will make it for 7.5.2 and 7.6.0.
