### ISSUE TITLE
Produce Docker images for RedHat Universal Base Image

### ISSUE THREAD

**Issue by rwaight** [elastic/logstash#11265]
**Describe the feature:**
This feature request is a request to produce Logstash images based on the [RedHat Universal Base Image (UBI)](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image).

**Describe a specific use case for the feature:**
Producing Logstash images based on the official RHEL UBI would be beneficial for anyone using the official RHEL UBI for the base image of their docker containers.

**Comment by jsvd** [comment]
As described in another issue the goal is to, in addition to the centos based images, build the default (and not the OSS) images based on UBI.
