### ISSUE TITLE
Jenkins job might have some issue

### ISSUE THREAD

**Issue by amitavmohanty01** [elastic/logstash#11292]
For two PRs, there are Jenkins job failures, which seems unrelated to the code change.

https://github.com/elastic/logstash/pull/11280 -> https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/556/console

https://github.com/elastic/logstash/pull/11281 -> https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/546/console

The following error shows up in both.

```Failure/Error: @elasticsearch_service = elasticsearch
21:44:29          
21:44:29          Elasticsearch::Transport::Transport::Errors::BadRequest:
21:44:29            [400] {"error":"no handler found for uri [/_xpack/license] and method [GET]"}
```
The error does not seem to be related to either of the PR's changes. So, the issue is mostly because of some nuance in the Jenkins job or there is some other bug.

**Comment by jsvd** [comment]
this should be solved by #11297 
thanks for the report :)
