### ISSUE TITLE
rake bootstrap produces 'Gem::MissingSpecVersionError: Could not find 'json'' error

### ISSUE THREAD

**Issue by nasica88** [elastic/logstash#11304]
I am trying to build logstash from source, and gradlew seems to work fine.  I can see logstash scripts built in bin directory.   But when I run 'rake bootstrap', it produces the following error.   Pls read the below for details.

**rake aborted!
Gem::MissingSpecVersionError: Could not find 'json' (~> 1) - did find: [json-2.1.0]**

[user607@p607-kvm1 logstash]$ git describe --tags
7.0.0-alpha2-293-g4dcf53cbd

[user607@p607-kvm1 logstash]$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 (Ootpa)

[user607@p607-kvm1 logstash]$ ./gradlew
Downloading https://services.gradle.org/distributions/gradle-4.10-bin.zip
..........................................................................

Welcome to Gradle 4.10!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC3
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10/release-notes.html

> Task :help

Welcome to Gradle 4.10.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 32s
1 actionable task: 1 executed

[user607@p607-kvm1 logstash]$ ls -l bin
total 80
-rwxrwxr-x. 1 user607 user607  152 Nov 12 04:10 benchmark.sh
-rwxrwxr-x. 1 user607 user607  473 Nov 12 04:10 bundle
-rwxrwxr-x. 1 user607 user607  377 Nov 12 04:10 cpdump
-rwxrwxr-x. 1 user607 user607 1025 Nov 12 04:10 dependencies-report
-rwxrwxr-x. 1 user607 user607  155 Nov 12 04:10 ingest-convert.sh
-rwxrwxr-x. 1 user607 user607 2354 Nov 12 04:10 logstash
-rw-rw-r--. 1 user607 user607 2442 Nov 12 04:10 logstash.bat
-rwxrwxr-x. 1 user607 user607  447 Nov 12 04:10 logstash-keystore
-rw-rw-r--. 1 user607 user607  257 Nov 12 04:10 logstash-keystore.bat
-rwxrwxr-x. 1 user607 user607 4919 Nov 12 04:10 logstash.lib.sh
-rwxrwxr-x. 1 user607 user607  448 Nov 12 04:10 logstash-plugin
-rw-rw-r--. 1 user607 user607  260 Nov 12 04:10 logstash-plugin.bat
-rwxrwxr-x. 1 user607 user607 1124 Nov 12 04:10 pqcheck
-rwxrwxr-x. 1 user607 user607 1125 Nov 12 04:10 pqrepair
-rwxrwxr-x. 1 user607 user607  322 Nov 12 04:10 rspec
-rw-rw-r--. 1 user607 user607  848 Nov 12 04:10 rspec.bat
-rwxrwxr-x. 1 user607 user607  666 Nov 12 04:10 ruby
-rw-rw-r--. 1 user607 user607 1436 Nov 12 04:10 setup.bat
-rwxrwxr-x. 1 user607 user607 3547 Nov 12 04:10 system-install

[user607@p607-kvm1 logstash]$ rake bootstrap
rake aborted!
Gem::MissingSpecVersionError: Could not find 'json' (~> 1) - did find: [json-2.1.0]
Checked in 'GEM_PATH=/home/user607/.gem/ruby:/usr/share/gems:/usr/local/share/gems', execute `gem env` for more information
/home/user607/logstash/rakelib/artifacts.rake:2:in `block in <top (required)>'
/home/user607/logstash/rakelib/artifacts.rake:1:in `<top (required)>'
/usr/share/gems/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by kares** [comment]
unfortunately `rake bootstrap` did have this problem, but the gradle build should have worked:
`./gradlew clean build` this will download JRuby and hook it up (no need to use rake explicitly)

you could work-around by installing json < 2 `vendor/jruby/bin/jruby -S gem install json:1.8.6`

also, now with https://github.com/elastic/logstash/pull/11102 merged you should no longer experience the issue
