### ISSUE TITLE
using pipeline.plugin_classloaders (--plugin-classloaders) with custom java plugin

### ISSUE THREAD

**Issue by PeterTruchly** [elastic/logstash#11305]
Trying the dependency isolation using own java plugin created from base (https://github.com/logstash-plugins/logstash-output-java_output_example) repository. Using release version 7.4.2.

- on Windows: loading of plugin fails by
~~~
:error_message=>"String index out of range: -1", 
:error_class=>Java::JavaLang::StringIndexOutOfBoundsException, 
:error_backtrace=>["java.lang.String.substring(java/lang/String.java:1967)", 
                  "org.logstash.plugins.PluginClassLoader.create(org/logstash/plugins/PluginClassLoader.java:35)", 
   ...
~~~
this is caused by path containing '/' being supplied in 1st parameter parameter to PluginClassLoader.create(plugin_paths[0], plugin_paths[1], Logstash.java_class.class_loader)  (registry.rb line 293) and parsed by gemPath.lastIndexOf(File.separator) (PluginClassLoader line 35)

... when going around this by replacing / by \ just for plugin_paths[0], another problem is with org.apache.logging.log4j dependencies - as far as I understood, logger is injected in a context, passed to the plugin -> this dependency is already present at runtime and should not be loaded twice. This expectation is in line with error: 
~~~
:exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: java.lang.LinkageError: loader constraint violation: loader (instance of org/logstash/plugins/PluginClassLoader) previously initiated loading for a different type with name \"org/apache/logging/log4j/Logger\""
~~~

When these dependencies are removed from final gem, the error is:
~~~
:exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger",
~~~

There seems to be no way around this with current implementation.

https://github.com/elastic/logstash/blob/0de53939e952d0ab314c72eaccc083ee4bb465b2/logstash-core/src/main/java/org/logstash/plugins/PluginClassLoader.java#L52

**Comment by robbavey** [comment]
I believe this should be fixed by the changes in #14060. Please reopen if this is not the case
