### ISSUE TITLE
[Monitoring] [Packaging] Bundling Metricbeat

### ISSUE THREAD

**Issue by cachedout** [elastic/logstash#11328]
With the 8.0 release of the stack, [internal collection will be removed from Logstash](https://github.com/elastic/logstash/issues/11169). 

As such, each stack team may consider bundling Metricbeat with their software package so that it's available for users to configure and quickly set up monitoring.

The Elasticsearch team is planning to go ahead with this for Elasticsearch and, according to comment from @jasontedor in a meeting yesterday, they'll likely take the route of bundling Metricbeat and then having it be started automatically by init scripts alongside Elasticsearch. Metricbeat configuration, however, will remain separate and distinct from Elasticsearch.

This issue is being filed in the Logstash repo to discuss with the team whether Logstash wishes to adopt a similar pattern and, if so, any implementation details that may need to be discussed.

cc: @elastic/stack-monitoring 

@jsvd and @roaksoax I have assigned this to both of you in order to kick the discussion off but please feel free to move around as appropriate. Thanks!

**Comment by cachedout** [comment]
Here is a link to the Elasticsearch proposal for this as well: https://github.com/elastic/elasticsearch/issues/49399

**Comment by cachedout** [comment]
There is also interest in teams, such as cloud, in bundling Filebeat as well. Please let me know if you'd be open to that discussion.

**Comment by jsvd** [comment]
No plans at this point to package metricbeat in Logstash.
