### ISSUE TITLE
Migrate jdbc plugins into a integration plugin

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#11339]
Join:
- https://github.com/logstash-plugins/logstash-input-jdbc
- https://github.com/logstash-plugins/logstash-filter-jdbc_streaming
- https://github.com/logstash-plugins/logstash-filter-jdbc_static

**Comment by robbavey** [comment]
[Meta issue](https://github.com/logstash-plugins/logstash-integration-jdbc/issues/2) created

**Comment by jsvd** [comment]
@robbavey we can close this one and link your meta issue in the meta.....meta issue: https://github.com/elastic/logstash/issues/11338
