### ISSUE TITLE
License issue on OSS compiled version.

### ISSUE THREAD

**Issue by arkasai** [elastic/logstash#11344]
As mentioned on the Elastic web-page the OSS version will not contain any Elastic License related code and the compiled code will be under Apache 2.0 license. As I downloaded the current available ZIP file from GitHub and as Docker container I was able to find one single file which still includes the license header for Elastic License. Is it possible to remove that license header and make it complete licensed as Apache 2.0?

File: logstash-core/lib/logstash/config/pipelines_info.rb

- Version: latest version available (older haven't been checked; But file hasn't been touched a while)
- Operating System: n/a
- Config File (if you have sensitive info, please remove it): n/a
- Sample Data: n/a
- Steps to Reproduce: see license header of file "logstash-core/lib/logstash/config/pipelines_info.rb".

Cheers, Wolfgang.

**Comment by jsvd** [comment]
Thank you for the report @arkasai this will be removed immediately. This file was moved from licensed to apache 2.0, but somewhere in the process we messed up by not removing the license header.

**Comment by jsvd** [comment]
fixed in https://github.com/elastic/logstash/commit/ff527a01cd8d1e70eaa8fa6eecc9e992b60154d3, this will be included in the 7.5.1 release, unfortunately just missed the 7.5.0 window.
