### ISSUE TITLE
[Monitoring] Add deprecation warning to shipping monitoring data to the production cluster

### ISSUE THREAD

**Issue by cachedout** [elastic/logstash#11346]
This issue is a request for Logstash to add a deprecation log entry in 7.6 for users who are shipping monitoring data to the production cluster which urges them to switch to using Metricbeat monitoring in order to be prepared for 8.0.

If desired, the warning could link to instructions for doing so which are described here: elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html

cc: @jsvd and @roaksoax 

Refs: https://github.com/elastic/logstash/issues/11169

**Comment by cachedout** [comment]
Hi @jsvd and @roaksoax. Is this something we might be able to get into the 7.6 roadmap for Logstash?

**Comment by andsel** [comment]
PR to update documentation, marking as deprecated the internal collectors #11526

**Comment by andsel** [comment]
PR to solve the issue #11511
