### ISSUE TITLE
Use a forward proxy with centralized management

### ISSUE THREAD

**Issue by fdartayre** [elastic/logstash#11343]
The ES output can be configured with a forward HTTP proxy but neither X-Pack monitoring nor centralized management can be configured with a forward proxy.

For X-Pack monitoring there's already an existing issue (https://github.com/elastic/logstash/issues/9560) and a possible workaround is to use [Metricbeat](https://www.elastic.co/guide/en/logstash/current/monitoring-with-metricbeat.html) to collect and ship the monitoring data. This issue is for centralized management.

**Comment by roaksoax** [comment]
We believe this issue has now been fixed and will be available in the next release of Logstash 7.8. Please refer to the attached PR's for more information. If you feel this issue has not been fixed once the release mentioned is available, please re-open this bug report.
