### ISSUE TITLE
Produce platform specific release artifacts with bundled JDK

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#11350]
Along the lines of what elasticsearch has done: https://github.com/elastic/elasticsearch/pull/38013

> Setting up a jdk is currently a required external step when installing
> elasticsearch. This is particularly problematic for the rpm/deb packages
> as installing a jdk in the same package installation command does not
> guarantee any order, so must be done in separate steps. Additionally,
> JAVA_HOME must be set and often causes problems in selecting a correct
> jdk when, for example, the system java is an older unsupported version.
> 

The goal is to provide tarball/zip/deb/rpm artifacts with java bundled together with Logstash.

We would still provide the platform agnostic artifacts but encourage use of bundled releases.

Having platform specific release artifacts also aligns with the future removal of internal metric collection https://github.com/elastic/logstash/issues/11169

**Comment by roaksoax** [comment]
Closing this issue as it has now been addressed!
