### ISSUE TITLE
Switch license checking from _xpack to _license

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#11382]
License checking should use the `/_license` endpoint instead of `/_xpack`, which is what we do now: https://github.com/elastic/logstash/blob/master/x-pack/lib/license_checker/license_reader.rb#L29

**Comment by kaisecheng** [comment]
`/_license` cannot replace `/_xpack` because `/_xpack` provide extra information to tell if elasticsearch enable "security", "logstash", "monitoring". 
Elasticsearch team has no plan to deprecate `/_xpack`, so Logstash is safe to keep it as is

**Comment by kaisecheng** [comment]
reopen to get feedback from @jsvd

**Comment by jsvd** [comment]
The initial intent was to remove all mentions of xpack (other than file paths) as we move towards 8.0.

Since ES is keeping the xpack endpoint to provide information about which non-oss features exist/are enabled then this issue is not valid anymore.

We may need to reopen it in the past if:
a) the _xpack endpoint feature content is moved to a dedicated telemetry endpoint
b) the license data in the _xpack endpoint is removed and kept only in _license, causing is to have to execute two requests.
