### ISSUE TITLE
Headache problem

### ISSUE THREAD

**Issue by kinbod** [elastic/logstash#11397]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:  7.5.0
- Operating System: centos 7
- Config File (if you have sensitive info, please remove it):
- Sample Data: 
- Steps to Reproduce:
 

when I setup x-pack on elasticsearch and create default users with private password, restart logstash and always printing this log "[logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"http://11.5.0.75:9200/_bulk"} ", I have done my beast to try it , but it is still here......headache

**Comment by kares** [comment]
*400* is a bad request status for ES, so you need to figure out what caused the bad request.
as you probably noticed by now, these kind of questions are best suited for the forum, thanks.
