### ISSUE TITLE
[ERROR][logstash.instrument.periodicpoller.jvm] Unknown garbage collector name {:name=>"ZGC"}

### ISSUE THREAD

**Issue by YaKazama** [elastic/logstash#11464]
- Version: 7.5.1
- Operating System: centos 7
- Config File: logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb
- Sample Data: [ERROR][logstash.instrument.periodicpoller.jvm] Unknown garbage collector name {:name=>"ZGC"}
- Steps to Reproduce: start logstash

When using ZGC, it needs to be modified to the following.

```
 23       YOUNG_GC_NAMES = Set.new(["Copy", "PS Scavenge", "ParNew", "G1 Young Generation", "scavenge", "GPGC New", "ZGC"])
 24       OLD_GC_NAMES = Set.new(["MarkSweepCompact", "PS MarkSweep", "ConcurrentMarkSweep", "G1 Old Generation", "global", "GPGC Old", "ZGC"])
```

For more information: #11463

**Comment by kares** [comment]
feel free to fire up a PR with your suggested resolution for discussion. we do not need the issue twice

**Comment by zdyj3170101136** [comment]
@kares when will this bug fixed? logstash could use zgc
@andsel

**Comment by andsel** [comment]
Hi @zdyj3170101136 ZGC is not yet currently supported by Logstash. If you run Logstash 8.x or 9.x it ships with a tested JDK that's configured with a tested and working GC, specifically G1GC.
