### ISSUE TITLE
Dissect padding does not work with static text

### ISSUE THREAD

**Issue by blookot** [elastic/logstash#11472]
- Version: 7.5.0
- Operating System: Windows 10

Padding (->) in dissect works with another field, but not static text.

The following message: "XXX YYY        ZZZ"
can be dissected with `dissect { mapping => { "message" => "XXX %{fld->} %{fld2}" } }` but not `dissect { mapping => { "message" => "XXX %{fld->} ZZZ" } }`

Example to reproduce attached.

Is there any explanation? I would expect both would work...
Thank you

[logstash-test.txt](https://github.com/elastic/logstash/files/4026249/logstash-test.txt)

**Comment by kaisecheng** [comment]
this issue is fixed in logstash-filter-dissect v1.2.5
