### ISSUE TITLE
Confused Quote Usage in Error Messages

### ISSUE THREAD

**Issue by Kolano** [elastic/logstash#11480]
- Version: 7.5.1
- Operating System: Ubuntu 19.04
- Config File (if you have sensitive info, please remove it): NA
- Sample Data: NA
- Steps to Reproduce: Output a NoMethodError error message
- Discussion Post: https://discuss.elastic.co/t/nomethoderror-undefined-method-deep-merge/214367

There is a larger issue that seems to prevent Logstash from starting up being discussed in the post above, but while that's investigated further there is a clear issue with the quotes used in the NoMethodError error message, with it using a fancy quote on the left side and a normal single quote on the right.

```
[ERROR] 2020-01-09 08:18:37.084 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (NoMethodError) undefined method `deep_merge' for #<Hash:0x6b29771f>
```

I'd expect, given this issue in that error message, that it's likely fancy-quotes are inappropriately mixed in in many places; a general search for such should likely be performed when cleaning up this reported issue.

**Comment by yaauie** [comment]
This the verbatim exception message from jruby, which mirrors the behaviour of the MRI Ruby implementation, and is outside of our control.
