### ISSUE TITLE
Support for AdoptOpenJDK 11

### ISSUE THREAD

**Issue by rwaight** [elastic/logstash#11514]
The [Elastic Support Matrix](https://www.elastic.co/support/matrix#matrix_jvm) shows that Java 11 (Oracle/OpenJDK 11) is supported for Logstash (version 6.7 and newer), but does not mention AdoptOpenJDK 11.  

For Elasticsearch, the support matrix clearly shows AdoptOpenJDK 11 is compatible with multiple versions.  However, the Logstash section does not include AdoptOpenJDK specifically.

This enhancement request is to either: 1) Clarify and document if AdoptOpenJDK 11 is supported for Logstash, or 2) Open the floor to discussion on if AdoptOpenJDK 11 can/will be supported for Logstash.

**Comment by roaksoax** [comment]
This is being tracked in https://github.com/elastic/logstash/issues/11696

**Comment by roaksoax** [comment]
Closing this issue as Logstash now supports AdopOpenJDK 11 starting from 7.8
