### ISSUE TITLE
[7.5.2] Beats: i/o timeouts during bulk publish

### ISSUE THREAD

**Issue by oehlrich9** [elastic/logstash#11540]
The same issue described in https://github.com/elastic/logstash/issues/11517 occurs with beats and logstash in Version 7.5.2.
Is there a roadmap for bugfixes?

**Comment by jsvd** [comment]
[A new version of the beats input](https://github.com/logstash-plugins/logstash-input-beats/blob/master/CHANGELOG.md#606) has been published, which you can receive through `bin/logstash-plugin update logstash-input-beats`. Upcoming versions of Logstash will have this new version as well.

**Comment by inammathe** [comment]
Thanks @jsvd , that worked for me on 7.5.2

**Comment by jsvd** [comment]
thanks for the confirmation, closing here.
