### ISSUE TITLE
Elasticsearch output specifies deprecated types in bulk requests

### ISSUE THREAD

**Issue by fdartayre** [elastic/logstash#11558]
**Version:** Logstash 7.5.2 / logstash-output-elasticsearch 10.2.3

[Starting from Elasticsearch 7.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_document_apis), types should also no longer appear in the body of bulk requests.

Including a type causes a deprecation warning to get logged in Elasticsearch:
```
[2020-01-31T10:58:52,319][WARN ][o.e.d.a.b.BulkRequestParser] [hostname] [types removal] Specifying types in bulk requests is deprecated.
```
Logstash Elasticsearch output plugin shouldn't use types anymore.

**Comment by fdartayre** [comment]
Closing as this is the wrong repository (should be https://github.com/logstash-plugins/logstash-output-elasticsearch)

**Comment by andsel** [comment]
Types was removed conditionally with this commit https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/c93abd1e6255d5ba519e942a85ac708c05d472a7
