### ISSUE TITLE
pipeline.id not logged in Docker container

### ISSUE THREAD

**Issue by SpencerLN** [elastic/logstash#11566]
- Version: 7.5.2
- Operating System: RHEL 7.7
- Config File (if you have sensitive info, please remove it): N/A
- Sample Data: N/A
- Steps to Reproduce: Run Logstash using the latest Docker container from docker.elastic.co. The pipeline.id is not part of the log message.

According to the release notes and per #10521 / #11075 , this should have been added in 7.4.0.

**Comment by roaksoax** [comment]
We believe this issue has already been fixed with the above PRs. As such, I'm closing this issue.
