### ISSUE TITLE
Error Logstash absolute path needed 

### ISSUE THREAD

**Issue by lukelee1987** [elastic/logstash#11571]
Dear all, below are the info and seeking your advise. 

- Version: 7.1.1
- Operating System: Ubuntu 16.04
- Config File: Logstash.yml
- Steps to Reproduce:

[ERROR][logstash.javapipeline    ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<ArgumentError: File paths must be absolute, relative path specified: http://ip/var/log/nginx/access.log>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-file-4.1.10/lib/logstash/inputs/file.rb:269:in `block in register'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-file-4.1.10/lib/logstash/inputs/file.rb:267:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:191:in `block in register_plugins'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:190:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:280:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:244:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:145:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:104:in `block in start'"], :thread=>"#<Thread:0x85bf7c9 run>"}

**Comment by yaauie** [comment]
The file input plugin is for reading files from a local volume and as the error message states, requires an absolute file path (e.g., one starting with `/`, or a drive letter on windows). It does not support tailing files over http (note: exposing your logs from your webserver over http as above may represent a security risk).

I am closing this issue. In future, please use the forums for general debugging questions, or the affected plugin's issue tracker to track issues in plugins, as we use the Logstash issue tracker for issues on Logstash itself.
