### ISSUE TITLE
Translate doesn't substitute if destination = source field

### ISSUE THREAD

**Issue by blookot** [elastic/logstash#11585]
- Version: 7.5.0
- Operating System: Windows 10
- Issue: When doing a filter translate with a different destination than source "field", it works, but when setting the same field name, the substitution is not performed (the original value remains).
- Config File (if you have sensitive info, please remove it):

filter {
	translate {
		field => "[devicehostip]"
		destination => "[devicehostip]"
		dictionary => {
			"127.0.0.1" => "Localhost"
			"83.202.178.93" => "Special IP"
			"83.202.178.92" => "Other one"
		}
		fallback => "Stuff"
	}
}

**Comment by blookot** [comment]
PS substitution is supposed to work, cf https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html#plugins-filters-translate-destination

**Comment by kares** [comment]
might be due `override` being false by default ... did you try setting that to `true` ?

**Comment by blookot** [comment]
Indeed!
didn't see this setting!
thanks a lot @kares
