### ISSUE TITLE
[Meta Issue] moving plugin testing forward

### ISSUE THREAD

**Issue by kares** [elastic/logstash#11609]
The issue is meant to loosely track various aspects to improving testing of plugins.
Goal is to unify testing as much as possible, while also having flexibility when needed.

Let's break this down a bit:

1. all plugins should be tested using docker (even if only unit tests are present)
2. base-line (CI) testing experience should be ~ same and shared among plugins
3. testing should try to match 'production' environment closely
4. plugins should eventually drop testing against old LS versions
    only testing against 6.X stable line and forward

The above requirements are to be accomplished using [logstash-devutils](https://github.com/elastic/logstash-devutils) helper gem and the [.ci](https://github.com/logstash-plugins/.ci) module.

- [x] [deal with devutils upgrade](https://github.com/elastic/logstash/issues/11610) for an easier 2.0 transition
- [x] [upgrade all plugins to dockerized testing](https://github.com/elastic/logstash/issues/11662) (the 'legacy' ways of testing are starting to catch up on us)

**Comment by roaksoax** [comment]
@kares could you please that "upgrade all plugins to dockerized testing" is a list of plugins that need to be upgraded to dockerized testing instead? its difficult to judge progress or what plugins need it and if we make changes plugin, per plugin is better to track it that way.

**Comment by kares** [comment]
@roaksoax we could automatically open an issue for plugins affected (would need to script that). 
but that might simply turn out as 'redundant' work. the way I was planning on approaching this is a mass edit as much as possible (like with the devutils) and only afterwards turn to a manual process.

anyhow, will try to generate a list of affected plugins here and we can decide from there how many would need special care (usually ones that also have functiona/integration tests on top of unit specs).

**Comment by jsvd** [comment]
closing here, thanks for all the work here @kares
