### ISSUE TITLE
No configuration found in the configured sources.

### ISSUE THREAD

**Issue by ztluxi** [elastic/logstash#11643]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by kares** [comment]
this issue has no details

**Comment by roaksoax** [comment]
@ztluxi Thank you for filing an issue against Logstash. However, the issue provides no details whatsoever about what the issue you are experiencing is. Given that there are no details whatsoever, I'm closing this issue.

If you believe this issue should be re-open, please do so and provide details giving context into what issue is the one you are coming across.
