### ISSUE TITLE
Logstash no longer supports a pipeline config split into multiple files.

### ISSUE THREAD

**Issue by robcowart** [elastic/logstash#11695]
https://github.com/elastic/logstash/pull/11456 breaks most of the pipelines currently deployed, and would force a refactoring of over 1000 pipeline config files (literally) and result in significantly less organized and more difficult to maintain pipeline code.

This is a pretty significant change that should have been listed in Breaking Changes. I see that https://github.com/elastic/logstash/issues/11637 has been opened to explore a fix. It would good to see this accelerated.

**Comment by andsel** [comment]
Duplicate issue of #11637
