### ISSUE TITLE
[Plugin submission] Logstash-filter-wurfl plugin

### ISSUE THREAD

**Issue by andreacastello** [elastic/logstash#11707]
Hello, I'm opening a plugin submission request, according to this page instructions: https://www.elastic.co/guide/en/logstash/current/submitting-plugin.html#_contributing_your_source_code_to_logstash_plugins_5

The plugin I wrote adds [WURFL](https://en.wikipedia.org/wiki/WURFL) device data to a Logstash event data.

The plugin is written in Java, you can find the source code [here](https://github.com/WURFL/logstash-filter-wurfl).

**Comment by kares** [comment]
Thanks Andrea, the repository seems non existent.

**Comment by andreacastello** [comment]
Hi Kares, we mede the repo public. Can you try again? Thanks.

**Comment by andreacastello** [comment]
> Thanks Andrea, the repository seems non existent.

Hi Kares, we mede the repo public. Can you try again? Thanks.

**Comment by kares** [comment]
Hello Andrea, appreciate your submission. 
The docs isn't up-to-date, the team paused pushing all plugins users create under the plugins org. 

There simply is only that much the LS owners can handle (e.g. we'd like to make reviews for new plugins as a minimum).
Already some plugins are outdated and these repositories make things slightly more complicated if we need to mass-edit (supported plugins) etc.

We might reconsider the approach in the future, believe that is the reason the docs still mentions the submission - having some notion of (new) plugins even if only in the issue tracker is useful ...

For discovery on GH you can tag your repo with *logstash*, *logstash-plugin*, *wurfl* or whatever it relates to.

**Comment by andreacastello** [comment]
@kares 
Hi Karol, thanks for the answer. The option to keep the plugin in our public repo and list it on your page sounds good to me. I guess the documentation should be provided in markdown format, am I right?

**Comment by andreacastello** [comment]
@kares 

Hi, I'va added to our repository tha documentation for your listing page.
You can find it here: https://github.com/WURFL/logstash-filter-wurfl/blob/master/listing_page/listing_page_doc.asciidoc

I used asciidoc format. Please let me know if it's OK or you need some modification.

**Comment by andreacastello** [comment]
@kares have you any news about this? Thanks

**Comment by andreacastello** [comment]
Hi, any news?

**Comment by andreacastello** [comment]
Hey, @kares Any news about the listing? In logstash plugin page?
Thanks.

**Comment by andreacastello** [comment]
Hello, @kares sorry for being insistent, but I'd need a feedback on the logstash plugin listing on Logstash plugin page. Thanks

**Comment by kares** [comment]
sorry I was out for several weeks and since the process is manual I will need some help from the docs folks.

**Comment by kares** [comment]
@karenzone would need some help looking [at potential content](https://github.com/WURFL/logstash-filter-wurfl/blob/master/listing_page/listing_page_doc.asciidoc) for the 3rd plugins listing page like [this one](https://www.elastic.co/guide/en/logstash/current/plugins-filters-threats_classifier.html)

note-to-self: someone might also need to review the (Java) plugin's repository for some base-line checks ...

**Comment by andreacastello** [comment]
Hi @kares no worries. Thanks for your help.

**Comment by andreacastello** [comment]
Hi @kares any news on this?

**Comment by kares** [comment]
Hey Andrea, please take a look at the [docs](https://www.elastic.co/guide/en/logstash/current/java-input-plugin.html#_package_and_deploy) as I do not see the plugin [released](https://rubygems.org/search?utf8=%E2%9C%93&query=logstash-filter-wurfl) this is needed for users to be able to `bin/logstash-plugin install logstash-filter-wurfl`.

**Comment by andreacastello** [comment]
Hi @kares , thanks for the heads up! I released it now. (version 0.3.2)

**Comment by kares** [comment]
Thanks, I brought this to the team's attention and we realized LS' external plugin listing process isn't formalized.
Thus more work to-do on our end to come up with something for anyone wanting to list a plugin (a kind of "quality-control").

**Comment by andreacastello** [comment]
Thank you for your answer, @kares. Can you please advise on the next steps?  
What should we do to get our plugin listed?

**Comment by karenzone** [comment]
Hi @andreacastello We haven't forgotten your request!  As Kares said, this is a new process for us, and we're working out the details to make sure that it's scalable.  I hope to have an update for you soon. 
cc:/ @roaksoax

**Comment by roaksoax** [comment]
Hi @andreacastello

First let me thank you for submitting your plugin for inclusion to our ecosystem. I also wanted to apologize for the delay, but as we were reviewing submission process, we noticed some information was missing. That said, as we were discussing improvements to our documentation, we noticed a few things were missing in your codebase that need to be addressed before we can add your plugin. These are.

 - [ ] Add missing files (at least the 'logstash-filter-wurlf.gemspec' file). I'd suggest you use our [Plugin Generator](https://www.elastic.co/guide/en/logstash/current/plugin-generator.html) to figure out the desired organization of the codebase and the missing files, but at the very minimum, the gemspec should be available. An example [can be found here](https://github.com/logstash-plugins/logstash-filter-fingerprint/blob/master/logstash-filter-fingerprint.gemspec)

 - [ ] Publish to rubygems.org (requires the above gemspec file). See [our documentation for details](https://www.elastic.co/guide/en/logstash/current/submitting-plugin.html#_publishing_to_rubygems_org_5).

 - [ ] Integrate with Logstash Travis CI. This is OPTIONAL step but HIGHLY recommended. This would give the community confidence that your plugin is being actively tested, as well as give us confidence to list your plugin in the official documentation. If you decide to add this, you'd need to:
     - Enable travis on your account.
     - Import our standard [travis.yaml](https://github.com/logstash-plugins/.ci/blob/1.x/travis/travis.yml) as shown in [this example](https://github.com/logstash-plugins/logstash-filter-fingerprint/blob/master/.travis.yml)
     - Ensure your 'specs' tests are in the spec folder.


/cc @karenzone @jsvd

**Comment by andreacastello** [comment]
Hi @roaksoax 
Thanks for the detailed explaination. I'll try to make the plugin compliant with your requests ASAP. I'll update here, when it'll be ready or if I have any question about it.

**Comment by andreacastello** [comment]
@roaksoax I've added the gemspec file. I've also renamed the repo in order to match the gem file name.

As for the CI, it is more difficult. The unit test are structured to use maven and comply with the standard "Java on Maven" project structure, where tests are placed under /src/test/java folder. But, most of all, the test requires a running WURFL Microservice server which is not available to your CI. So, unless it's really mandatory I'd skip it.
I've added the link to the PR on our repo so that you can review the file

**Comment by andreacastello** [comment]
Here's a list of file generated by logstash plugin generator with an "OK" for each one present in the repo.
Some of the missing files seem not necessary for a Java plugin, but if you thing some of them should be there, tell me.
Thanks

Gemfile **OK**
wurfl_test_spec.rb
spec_helper.rb 
logstash-filter-wurfl_test.gemspec **OK**
docs/index.asciidoc **OK**
LICENSE **OK**
README.md **OK**
CONTRIBUTORS **OK**
Rakefile
filters/wurfl_test.rb -> no ruby test but java test with junit/testNG
DEVELOPER.md 
CHANGELOG.md **OK**

**Comment by roaksoax** [comment]
Thank you for addressing all requests @andreacastello . @karenzone will take over and complete the process to list your plugin now that all my concerns have been resolved.

**Comment by karenzone** [comment]
@andreacastello  Your logstash-filter-wurfl_device_detection plugin is now included in the [list of filter plugins](https://www.elastic.co/guide/en/logstash/7.9/filter-plugins.html) in the Logstash Reference, and it has its own [landing page](https://www.elastic.co/guide/en/logstash/current/plugins-filters-wurfl_device_detection.html). Thanks again for submitting this plugin.
