### ISSUE TITLE
Could we alloc multi global variable for every worker in ruby filter?

### ISSUE THREAD

**Issue by pengtianabc** [elastic/logstash#11718]
- Version: logstash-7.4.2-1
- Operating System: CentOS6.5
- Steps to Reproduce:
1. i want to open a big file to search by fileno offset,  i got a fileno in `register` 
2. i will use and change fileno in `filter`
3. when use multi worker, the fileno will be used by multi worker at same time, so the data i got from fileno will be error. when i change worker to 1, it will be ok.
4. so, i want to share a variable for each worker.

**Comment by kares** [comment]
this is possible but requires handling concurrent (multi-thread) updates to a variable.
also these kind of issues are better asked [at the forum](https://discuss.elastic.co/c/elastic-stack/logstash) or on SO
