### ISSUE TITLE
Using protobufs in Logstash plugin

### ISSUE THREAD

**Issue by adityacs** [elastic/logstash#11722]
We are developing an output plugin and we want to send the output as protobuf encoded messages. It seems like JRuby is not fully supported on protobuf. So, just wanted to understand is there any other way to handle this? 

I am aware that there is logstash-codec-protobuf plugin. However, it uses `protobuf 3.5.0-pre`.

Thanks

**Comment by kares** [comment]
Hello Aditya, the protobuf plugin has an outdated google-protobuf dependency likely due the later versions introducing a C extension.

The codec itself has been created (and maintained) by trivago folks, would suggest you ask them about specific issues you currently run into with the plugin.

IMO, there are several ways you can handle the case that google's protobuf is not using C ext : 
- use pure Ruby protobuf gem (which is tested against JRuby)
- use a Java protobuf library (having your models as Java classes)

Would start with the plugin and see how far it gets, than possibly do a fork if you need changes to meet your needs and from there open a PR pushing the changes upstream.

Also recommend to try using the LS [forums](https://discuss.elastic.co/c/logstash) if you're looking for a general discussion on a topic such as how to approach protobuf.
