### ISSUE TITLE
Release notes generation scripts needs to include plugin versions

### ISSUE THREAD

**Issue by roaksoax** [elastic/logstash#11759]
Release notes generation script should include the plugin versions, specially for those that are being bundled with Logstash (tier 1 plugins)

**Comment by roaksoax** [comment]
@jsvd I think it is important to communicate to our users the version of Logstash plugins being bundled with a given Logstash release, and the release note generation script should give us that information.

**Comment by robbavey** [comment]
@roaksoax The script actually does provide the list of changed plugin versions, but when compiling release notes, that information has not been included in the somewhat "curated" versions of the release notes we provide.

**Comment by jsvd** [comment]
> Release notes generation script should include the plugin versions, specially for those that are being bundled with Logstash (tier 1 plugins)

As Rob mentioned it is easy to obtain this information, I'm just wondering if having a list with 100 lines of:

> logstash-input-file 1.2.3
> logstash-output-redis 3.2.1

Is useful. We can make sure to include a link to the lockfile in Github, so folks can check which dependencies ship with logstash. For example, for 7.6.2: https://github.com/elastic/logstash/blob/v7.6.2/Gemfile.jruby-2.5.lock.release

**Comment by roaksoax** [comment]
Well it si not really a list of 100 of plugins. Its for those that really do end up here:
http://logstash_11721.docs-preview.app.elstc.co/guide/en/logstash/7.7/logstash-7-6-2.html

And the reality of this is that it is really more useful for plugins that are bundled with Logstash.

**Comment by jsvd** [comment]
Ah so it’s only those whose versions were bumped, not all the plugins included with the Logstash? If so I’m +1

**Comment by roaksoax** [comment]
Yes indeed, only for those that have been bumped/have a delta from a previous release.

**Comment by jsvd** [comment]
@roaksoax I've created #11769 to address this and tagged you as reviewer

**Comment by jsvd** [comment]
fixed by https://github.com/elastic/logstash/pull/11769
