### ISSUE TITLE
Logstash docker images contain problematic JRE 11 versions

### ISSUE THREAD

**Issue by dtuck9** [elastic/logstash#11907]
When TLSv1.3 was initially released in Java 11, it contained several bugs preventing proper TLS handshake. The impacted JREs are 11.0.0 through 11.0.4, inclusively. 11.0.5 and up are fixed.

That means that customers using certain logstash docker images may be impacted if/when their corresponding ES cluster starts supporting TLSv1.3.

The impacted logstash docker images are:

- Versions:
    - 7.4.x: 7.4.0 and 7.4.1 (OpenJDK 11.0.4+11-LTS)
    - 7.3.x: 7.3.0, 7.3.1, and 7.3.2 (OpenJDK 11.0.4+11-LTS)
    - 7.2.x: 7.2.0 and 7.2.1 (OpenJDK 11.0.3+7-LTS)

Please consider patching the impacted docker images to incorporate the JRE fixes and other security patches.

**Comment by dtuck9** [comment]
Please also consider pinning the java versions included in the docker images for easier identification of what needs important security patches

**Comment by roaksoax** [comment]
Closing this issue provided that newer Logstash releases (and their docker images) already feature a newer Java version that solves this issue, and the recommended/supported solution is for users to upgrade to a later version.
