### ISSUE TITLE
DEB/RPM artifacts can only be built on Java < 9

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#11951]
This project uses [jordansissel/fpm](https://github.com/jordansissel/fpm) to build DEB and RPM packages.

`fpm` uses `childprocess` and in particular the `0.9.0` version due to an issue. 
the release manager script invokes rake task `rake artifact:all` which is a shell to call other tasks, in particular `rake artifact:deb` or `rake artifact:rpm`. `childprocess` once run in a Java >=9 throws an error due to explicit check to Java class that do not exists anymore since Java 9.

A possible solution is to monkey patch fpm in logstash to do not use childprocess, or file a PR to fpm to use newer versions of this library.
Another could be to move deb/rpm creation into Gradle tools like Elasticsearch does, using  [nebula plugins](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin) which permits the creation of deb/rpm without leveraging the native tool but using java libraries.

**Comment by jsvd** [comment]
If needed, we can in the meantime monkeypatch child process with @yaauie's change https://github.com/enkessler/childprocess/pull/141/files#diff-b89b9509bf2451cc35a7f9e33baebdae

**Comment by yaauie** [comment]
🤯😂  I did not remember contributing that upstream change to childprocess until you linked it just now.

I'll put together an effective monkeypatch pulling it in shortly.
