### ISSUE TITLE
[Docs] Deprecate legacy monitoring

### ISSUE THREAD

**Issue by chrisronline** [elastic/logstash#11979]
Related to https://github.com/elastic/logstash/pull/11511

[In the monitoring docs](https://www.elastic.co/guide/en/logstash/current/configuring-logstash.html), we need to mark legacy collection as officially deprecated in 7.9 to align with the deprecation logs.

**Comment by karenzone** [comment]
@chrisronline I assigned this issue to myself.  Please keep me in the loop for any changes. Thanks!

**Comment by roaksoax** [comment]
We should also remove the internal collection code changes.
