### ISSUE TITLE
env2yaml doesn't support xpack.monitoring.elasticsearch.ssl.verification_mode

### ISSUE THREAD

**Issue by dcode** [elastic/logstash#11996]
- Version: 7.7.1 Docker image
- Operating System: CentOS 8.1.1911 + podman 1.6.4
- Config File (if you have sensitive info, please remove it):
Environment variables:
```
LOG_FORMAT=json
XPACK_MONITORING_ENABLED=true
XPACK_MONITORING_ELASTICSEARCH_USERNAME=logstash_user
XPACK_MONITORING_ELASTICSEARCH_PASSWORD=<logstash_password>
XPACK_MONITORING_ELASTICSEARCH_HOSTS="https://coord.elasticsearch.service.consul:9200"
XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITY=/usr/share/logstash/ca.pem
XPACK_MONITORING_ELASTICSEARCH_SSL_VERIFICATION_MODE=none
```

- Steps to Reproduce:

1. Try to disable SSL certificate verification for monitoring (though `certificate` level verification would be better, similar to Kibana, Beats, and Elasticsearch).
2. Logstash refuses to connect to Elasticsearch to enable monitoring

```json
{"level":"ERROR","loggerName":"logstash.licensechecker.licensereader","timeMillis":1591719183765,"thread":"monitoring-license-manager","logEvent":{"message":"Unable to retrieve license information from license server","message":"Host name 'coord.elasticsearch.service.consul' does not match the certificate subject provided by the peer (CN=es-coord-0)"}}
```

---
Relevant lines are here, where the configuration option is clearly missing.

code:
https://github.com/elastic/logstash/blob/3695580b9268aef05c3f9eeddd45100fe8dd7e36/docker/data/logstash/env2yaml/env2yaml.go#L102-L106
---

Though, looking at this in more detail, even if this bug gets fixed, looks like I'll hit another: https://github.com/elastic/logstash/issues/9716

**Comment by jsvd** [comment]
This will be fixed in 7.9.1 with https://github.com/elastic/logstash/pull/12162
