### ISSUE TITLE
Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"=>\" at line 14, column 10

### ISSUE THREAD

**Issue by bouzouitadhouha** [elastic/logstash#12070]
[Please](url
![log_format](https://user-images.githubusercontent.com/41326222/86237624-0912c380-bb94-11ea-9fdb-333509669598.png)
![logstash_conf](https://user-images.githubusercontent.com/41326222/86237649-116afe80-bb94-11ea-97fc-11b69baff49e.png)
![logstash_cmd](https://user-images.githubusercontent.com/41326222/86237666-18920c80-bb94-11ea-9e26-82bc2cbf45e4.png)

) post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by jsvd** [comment]
you're missing a `}` to close the grok filter, and the date filter has one extra that needs to be deleted :)

**Comment by bouzouitadhouha** [comment]
Thank you it work.

**Comment by bouzouitadhouha** [comment]
But after it work i didn' find any index in kibana
![screen_logstash](https://user-images.githubusercontent.com/41326222/86342421-7d5e6d00-bc4f-11ea-991a-2f65b4304b34.png)
![index](https://user-images.githubusercontent.com/41326222/86342762-f1007a00-bc4f-11ea-9b85-e661d2b0d9e1.png)
![kibana](https://user-images.githubusercontent.com/41326222/86342780-f958b500-bc4f-11ea-94aa-d631b567cdd5.png)

**Comment by bouzouitadhouha** [comment]
@jsvd
