### ISSUE TITLE
Req: make logstash automatically load logstash.conf, without needing -f

### ISSUE THREAD

**Issue by rugabunda** [elastic/logstash#12103]
Make logstash and every other elastic application automatically load their corresponding configuration file without having to add the -f command. Nobody loads an unconfigured application, it doesn't work that way.  Allow -f only for rare special circumstances.

Thanks.

**Comment by kares** [comment]
Hello, sorry about your bad experience but the `config/.yml` files are already read by default if you just run `bin/logstash`.
Also configuration is properly setup when using Docker or having LS installed as a system service.

Adding `config/*.conf` might be confusing on top of having *pipelines.yml* (as well as *logstash.yml*) read by default ...
For consistency configuration is by default yaml only.
