### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#12129]
Logstash v6 can crash with the exception  `no implicit conversion of nil into String` and similarly logstash v5 can crash with `can't convert nil into String`.

This problem is solved in logstash v7 but if you are still using an earlier version read on:

This is indeed a tricky problem to diagnose and we don't have a great way to troubleshoot it. 

### Problem 

When this happen it is usually because of a conditional trying to verify the inclusion of an explicit  `nil` value using the  `in` statement. Here's a snippet that reproduces that problem:

```
 echo '{"type": null}' | bin/logstash -e "input { stdin { codec => json } } filter { if [type] in \"something\" { } }"
```

Note that the `type` field here will have an explicit `nil` value because it was converted from the source `null` JSON value. 

### Solution

The way to prevent that is to guard the `if` to test for a non nil value with something like `if [field] and [field] in ...`. To fix the above example use:

```
echo '{"type": null}' | bin/logstash -e "input { stdin { codec => json } } filter { if [type] and [type] in \"something\" { } }"
```

### Recap 

The typical statement where this occurs is with a  `if [somefield] in "somestring"`  and per the above the way to solve the problem in by using `if [somefield] and [somefield] in "somestring"`

**Comment by karenzone** [comment]
@karenzone Note to self:  Evaluate this issue for inclusion in Troubleshooting section.

**Comment by kares** [comment]
believe this is defunct by now
