### ISSUE TITLE
Config compilation is still running after 1 hour

### ISSUE THREAD

**Issue by packetrevolt** [elastic/logstash#12156]
Version: 7.8.1 (6.5.2 works, every version after is slow)
OS: CentOS 7
Steps to Reproduce: Start the service
Config file: can provide privately, it is too large with too much sensitive info to share here

Config compilation in 6.5.2 using ruby execution would take around 5 minutes.   Every version I have tried that is newer all the way to 7.8.1 will still be compiling config after 1 hour.   Some pipelines will finish compiling and start but others will still be compiling and not start.   Using ruby or java execution in 7.8.1 does not matter with the time taken, both are equally slow.   Config is large at around 16,000 lines in total.

Some pipeline compiles seem to abort (all of the ones with larger configs).   There are no error messages, the pipeline just stops trying to compile and never starts.

**Comment by yaauie** [comment]
The release of 7.9.0 is in-flight and includes some pretty major performance improvements to pipeline compilation under the Java execution engine (#12060, #12038), so there is a good chance you'll see some improvements soon.

You're welcome to compare compilation with a 7.9 [snapshot build](https://github.com/elastic/logstash/tree/7.9#snapshot-builds), or you can send me a copy of the pipeline privately (ry.biesemeyer@elastic.co -- feel free to use the GPG keys attached to my GitHub profile if you need privacy).

**Comment by packetrevolt** [comment]
Email sent with the config files.

Tested with the current 7.9 snapshot build.   Same server, same config.   
7.8.1 = 1+ hours and only 6 of the 14 pipelines actually loaded
7.9 = 55 seconds and all 14 pipelines are loaded

**Comment by yaauie** [comment]
Well I'd say that's an improvement 🙂

I'll take a look at the configs in the morning to see if I can spot anything obvious, but more likely than not waiting for the 7.9 release will be your best bet.
