### ISSUE TITLE
Logstash 7.8.0 High CPU Usage

### ISSUE THREAD

**Issue by voilaviola** [elastic/logstash#12168]
Hello,
I'm using logstash to parse csv files and feed into elasticsearch. The quantity of data is ~2G, but lot of filters are used in the logstash confg file to deal with fields. The config file has more than 3000 lines.
My logstash is configured with the option `exit_after_read => true`, but gets killed before finish processing all csv files. The CPU usage is extremly high (200%), with a low RAM usage (10%).
```
 PID USER    PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 6146 user       20   0 6944168 1,552g      0 S 203,8 10,1  74:00.68 java        
 5064 elastic+  20   0  9,993g 1,553g   7516 S 120,4 10,1  33:49.31 java 
```
My jvm.options file is configured with JVM heap size of 1G : `-Xms1g -Xmx1g`, and logstash.yml sets number of cpu cores to use as 2 : `pipeline.workers: 2`
Do I need to increase the cpu number to avoid logstash been killed ?

- Version: 7.8.0
- Operating System: Ubuntu 18.04, Linux 5.3.0-42-generic
- RAM :
```
              total        used        free      shared  buff/cache   available
Mem:            15G        8,3G        2,7G        1,2G        4,3G        5,5G
Swap:          2,0G        1,0G        976M
```
- CPU:
> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              8
> On-line CPU(s) list: 0-7
> Thread(s) per core:  2
> Core(s) per socket:  4
> Socket(s):           1
> NUMA node(s):        1
> Vendor ID:           GenuineIntel
> CPU family:          6
> Model:               142
> Model name:          Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
> Stepping:            12
> CPU MHz:             1018.158
> CPU max MHz:         4600,0000
> CPU min MHz:         400,0000
> BogoMIPS:            3999.93
> Virtualization:      VT-x
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            256K
> L3 cache:            8192K
> NUMA node0 CPU(s):   0-7

**Comment by andsel** [comment]
Probably you are victim of a pipeline compilation regression introduced with `7.7.0` and fixed with `7.8.1` (https://www.elastic.co/guide/en/logstash/current/logstash-7-8-1.html)

**Comment by voilaviola** [comment]
> Probably you are victim of a pipeline compilation regression introduced with `7.7.0` and fixed with `7.8.1` (https://www.elastic.co/guide/en/logstash/current/logstash-7-8-1.html)

I've upgraded the elk stack to 7.8.1, and got a even higher cpu usage at ~600% :
```
 PID USER    PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
28531 user       20   0 6941500 1,562g  21104 S 567,5 10,2  26:52.24 java        
25127 elastic+  20   0 7471976 1,559g  49968 S  23,2 10,1   2:50.37 java 
```
And logstash got killed with the following error log:
>  [2020-08-10T17:10:18,760][ERROR][logstash.javapipeline    ][main] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"main", :error=>"(EPIPE) Broken pipe - <STDOUT>", :exception=>Java::OrgJrubyExceptions::SystemCallError, :backtrace=>["org.jruby.RubyIO.write(org/jruby/RubyIO.java:1475)", "org.jruby.RubyIO.write(org/jruby/RubyIO.java:1430)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:43)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1809)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:42)", "usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:103)", "org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multi_receive(org/logstash/config/ir/compiler/OutputStrategyExt.java:138)", "org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:289)"], :thread=>"#<Thread:0x2de6cf8a sleep>"}
> [2020-08-10T17:10:19,217][ERROR][logstash.javapipeline    ][main] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"main", :error=>"(EPIPE) Broken pipe - <STDOUT>", :exception=>Java::OrgJrubyExceptions::SystemCallError, :backtrace=>["org.jruby.RubyIO.write(org/jruby/RubyIO.java:1475)", "org.jruby.RubyIO.write(org/jruby/RubyIO.java:1430)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:43)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1809)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:42)", "usr.share.logstash.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:103)", "org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multi_receive(org/logstash/config/ir/compiler/OutputStrategyExt.java:138)", "org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:289)"], :thread=>"#<Thread:0x2de6cf8a sleep>"}
> [2020-08-10T17:10:20,299][DEBUG][logstash.javapipeline    ][main] Pipeline terminated by worker error {:pipeline_id=>"main", :exception=>#<RuntimeError: Worker thread terminated in pipeline.id: main>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:336:in `monitor_inputs_and_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:193:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:134:in `block in start'"], "pipeline.sources"=>["/home/user/tools/my_logstash/conf/logstash_master.conf"], :thread=>"#<Thread:0x2de6cf8a run>"}

**Comment by andsel** [comment]
Your `-Xmx` in `jvm.options` are really low, probably you could check what's happening on the GC side, I would rise up to 4-8 GB the heap

**Comment by voilaviola** [comment]
> Your `-Xmx` in `jvm.options` are really low, probably you could check what's happening on the GC side, I would rise up to 4-8 GB the heap

Sorry for my late reply. I've changed the Xms and Xms to 4G and still got the same result. Thank you for the advice though

**Comment by andsel** [comment]
Ok, the broken pipe happens on the stdout plugin, so it's seems something weird happens. I expect that running your logstash instance with `bin/logstash -e "input {stdin{}} output {stdout {codec => rubydebug}}"` works smoothly. Probably sharing your LS pipeline or logs could give more help understanding what's happening.

**Comment by voilaviola** [comment]
> Ok, the broken pipe happens on the stdout plugin, so it's seems something weird happens. I expect that running your logstash instance with `bin/logstash -e "input {stdin{}} output {stdout {codec => rubydebug}}"` works smoothly. Probably sharing your LS pipeline or logs could give more help understanding what's happening.

The problem gets fixed after reducing the harddisk usage to <95%. I don't know if it's somehow related to the cpu usage, but gladly my cpu usage became normal :)
