### ISSUE TITLE
[Docs] Logstash Split Filter Plugin Description

### ISSUE THREAD

**Issue by woodywalton** [elastic/logstash#12197]
The [Logstash `split` filter plugin detail page](https://www.elastic.co/guide/en/logstash/current/plugins-filters-split.html) should start the description paragraph with the simple sentence used on the [filter plugins overview page](https://www.elastic.co/guide/en/logstash/current/filter-plugins.html):

"Splits multi-line messages into distinct events" 

The existing description paragraph jumps right into the details and doesn't state the main intent of the plugin up front, so it's a little confusing regarding what it does.

**Comment by karenzone** [comment]
Fixed in https://github.com/logstash-plugins/logstash-filter-split/pull/43. Updated docs should appear after plugin docs are generated and merged. Thanks for opening this issue.
