### ISSUE TITLE
PipelinesRegistry reports loading pipelines as running

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#12190]
The PipelinesRegistry defines [running pipelines](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/pipelines_registry.rb#L230-L232) as:

```ruby
    def running_pipelines
      select_pipelines { |state| !state.terminated? }
    end
```

This causes pipelines in the loading state to appear as running, and in some cases (for example when monitoring is enabled), one can end up seeing an error until the pipeline finishes loading, such as:
```
[2020-08-19T11:20:03,946][ERROR][logstash.inputs.metrics  ] Failed to create monitoring event {:message=>"For path: http_address. Map keys: [:jvm, :stats]", :error=>"LogStash::Instrument::MetricStore::MetricNotFound"}
```

**Comment by andsel** [comment]
Probably related to #9126

**Comment by andsel** [comment]
I tried to replicate with the following flow:
- in `/tmp/autoreaload_test` folder I've added the pipeline config with:
```
input {
	java_generator {
		 eps => 0
		 message => "Hello world!"
	}
}

output {}
```

- started Logstash with `/logstash-7.9.2/bin/logstash -f /tmp/autoreload_test --config.reload.automatic` and with the following in `logstah.yml`:
```
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: changeme
```
- in the `Management > Stack Monitoring > Logstash > Nodes > [my node name]` of local Kibana instance I checked the node and the pipeline are monitored

- added a second pipeline with a long initialization: 
```
input { generator {} }filter { ruby { init => 'sleep 10000' code => ''} } output {}
```

What I can observe is Logstash terminating the main pipeline but it's never able to recover the execution, and the worstly it doesn't log any stacktrace or something, it seems hungup.

@jsvd perhaps do you have reproducer of the bug?

**Comment by jsvd** [comment]
Here is my reproducer:

```
❯ grep -v "^#" config/logstash.yml 
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://localhost:9200"]
❯ grep -v "^#" config/pipelines.yml 
- pipeline.id: test
  pipeline.workers: 1
  pipeline.batch.size: 1
  config.string: "input { generator {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
#- pipeline.id: test_2
#  pipeline.workers: 1
#  pipeline.batch.size: 1
#  config.string: "input { generator {} }filter { ruby { init => 'sleep 10000' code => ''} } output {}"
```

Steps:
1. start elasticsearch on localhost
2. start logstash with `bin/logstash -r`
3. wait for startup
4. uncoment the second pipeline

Result:

```
[2020-11-24T14:39:35,539][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:".monitoring-logstash", :test], :non_running_pipelines=>[]}
[2020-11-24T14:39:35,745][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
.........[2020-11-24T14:39:45,603][ERROR][logstash.inputs.metrics  ] Failed to create monitoring event {:message=>"undefined method `[]' for nil:NilClass", :error=>"NoMethodError"}
..........[2020-11-24T14:39:55,635][ERROR][logstash.inputs.metrics  ] Failed to create monitoring event {:message=>"undefined method `[]' for nil:NilClass", :error=>"NoMethodError"}
```
