### ISSUE TITLE
Logstash with logstash-output-loki plugin make Logstash use too much CPU

### ISSUE THREAD

**Issue by acheng-floyd** [elastic/logstash#12206]
Before i want to use Loki, i just collect my log with filebeat and send the logs to redis on clients, then i have a log server installed with logstash, logstash reads the logs from redis and use file output to save logs to a new file, that's working for a long time.
Now i just update my logstash to 7.9.0 version, and install the plugin logstash-output-loki , here is one of my config pipline files :

input {
redis {
data_type => "list"
host => "192.100.1.19"
db => "0"
port => "6379"
password => "xxxx"
key => "floydtest18_cscerror"
type => "floydtest18_cscerror"
}
}
output {
if [type] == "floydtest18_cscerror" {
loki {
url => "http://192.100.1.10:3100/loki/api/v1/push"
}
}
}

I already test the config file is working, and log was saved to loki, but problem is that logstash consume much more CPU than before. As it's seen below
image

If there are more piplines , the logstash will consume all the CPU resources.

image

I googled the problem , and could just find that there's a similar problem when use kafka output plugin, the plugin also caused logstash consume high cpu resource. After they fix the bug of kafka output plugin, the problem's resolved. So i guess if there's something wrong with logstash-output-loki also caused the problem !

here is my logfile after i started my logstash about 2 minutes
[logstash-plain.log](https://github.com/elastic/logstash/files/5127113/logstash-plain.log)

Here is the thread information from VisualVM

![1](https://user-images.githubusercontent.com/62228888/91187040-ed521680-e719-11ea-8926-f9bb0455dc83.png)

![2](https://user-images.githubusercontent.com/62228888/91187198-183c6a80-e71a-11ea-9503-e3ed716efbdc.png)

![3](https://user-images.githubusercontent.com/62228888/91189065-30ad8480-e71c-11ea-827b-20efe840870c.png)

Hope someone can help me to find out , thank you

**Comment by kares** [comment]
seems like a *logstash-output-loki* plugin issue, hopefully this was reported at the plugin repo, not much LS could do about a problematic plugin.
