### ISSUE TITLE
docs: offline plugin management burried, leads to struggles

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#12280]
When installing plugins on an air-gapped machine (e.g., offline), a "pack" file needs to first be prepared on a machine with a route to Rubygems.org, which can then be transferred to the air-gapped machine and installed as documented in our "[Offline Plugin Management](https://www.elastic.co/guide/en/logstash/current/offline-plugins.html)" docs.

Unfortunately, this page is buried in our page hierarchy, accessible only in the nested drill-down menu on the right or by clicking through "next page" links on other plugins sub-topics. This leads users tend to get into the weeds struggling with the normal "network required" commands of the `logstash-plugins` executable when they run them on air-gapped machines. We should add clues to the top of "Working With Plugins" to send people in the right direction.

**Comment by karenzone** [comment]
Closed with #12283
