### ISSUE TITLE
Filter flushes should be relative to @timestamp and configurable

### ISSUE THREAD

**Issue by samuraraujo** [elastic/logstash#1231]
Filters are flushed every 5 seconds. This should be configurable. 

Desirably, it should be associated to the @timestamp read from log events. 

Therefore, it would allow the reprocessing of a batch of logs considering the correct time that the events happened.

**Comment by jordansissel** [comment]
> Filters are flushed every 5 seconds

IMO this is really meaning "Filters are given the opportunity to flush every N seconds". For example, in multiline filter (https://github.com/logstash-plugins/logstash-filter-multiline/blob/master/lib/logstash/filters/multiline.rb#L196) it will only flush events that have a `@timestamp` older than the `max_age` setting.

I think flush-opportunity timing should be configurable, but I also think it should be rare that anyone needs to change it.

**Comment by jordansissel** [comment]
The way the pipeline operates will be changing soon and, as a result, will make filter flushing not necessary anymore. I'm going to close this since in Logstash 5.x and beyond, it is unlikely filters will have a flush feature.
