### ISSUE TITLE
logstash can not start up?

### ISSUE THREAD

**Issue by h812755591** [elastic/logstash#12329]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:6.5.4
- Operating System: windows10 
- Config File (if you have sensitive info, please remove it): input { stdin { } } output { stdout {} }
- Sample Data:
- Steps to Reproduce:
.\logstash.bat  -f logstash_default.conf 
 : Ҳ޷ Active
I do not know why?
![RFF{M{ T`ZL49H5IGT242RV](https://user-images.githubusercontent.com/29937880/95559932-1b31b700-0a4b-11eb-9134-9c9437fdc0d0.png)

**Comment by kares** [comment]
Hey, sorry LS 6.5 is no longer supported. Please try latest LS instead.
