### ISSUE TITLE
s390x support for Logstash

### ISSUE THREAD

**Issue by Prabhav-Thali** [elastic/logstash#12331]
Hello,

Since Logstash [binary](https://www.elastic.co/downloads/logstash) works fine on s390x by explicitly installing jffi dependency. We would like to know if support for s390x can be provided in the existing Jenkins CI.

**Comment by kares** [comment]
Hey, there's no official support for IBM's s390x. However if JRuby's jffi library supports s390 than it should work for most parts.
No plans to have active testing in Jenkins CI against IBM H/W. Esp. given that LS is trying to move to self-packaged binaries, this would mean we package for `arch: s390x`, which is out-of-scope currently.

Could you maybe clarify the description as to what/how LS failed and what you did to install jffi, including the LS version?
I am sure LS eventually updates JRuby (including jffi) and the issue would get resolved but it's hard to tell without details.

**Comment by Prabhav-Thali** [comment]
@kares Thanks for the update!

Encountered below error while starting Logstash(v7.9.1) service using `logstash -e 'input { stdin { } } output { file { path => "op.txt" } }' < test.txt`
**Error:**
`[2020-10-06T02:57:58,182][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (LoadError) Could not load FFI Provider: (NotImplementedError) FFI not available: java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/s390x-Linux/libjffi-1.2.so, /jni/s390x-Linux/libjffi-1.2.so]`

Also, you can refer to [this](https://github.com/linux-on-ibm-z/docs/wiki/Building-Logstash) where we maintain the steps to install Logstash on s390x.

**Comment by Prabhav-Thali** [comment]
@kares any update on this?

**Comment by kares** [comment]
Not really, JFFI would need a package built for the s390x platform.
However there's progress since on doing so using CI, see https://github.com/jnr/jffi/pull/90 so you could add a built target in a PR.

**Comment by Prabhav-Thali** [comment]
We were able to install Logstash `7.16.2` without explicit installation of jffi. As Logstash `7.16.2` has jffi `1.3.6` (which supports Z).
