### ISSUE TITLE
Filter date, format "UNIX" defaults to 1970-01-01

### ISSUE THREAD

**Issue by robin13** [elastic/logstash#1236]
Example date filter which I am currently using:

```
   date {
        match => [ "timestamp", 
            "yyyy-MM-dd HH:mm:ss,SSS",
            "yyyy-MM-dd'T'HH:mm:ss,SSS",
            "dd/MMM/yyyy:HH:mm:ss Z",
            "EEE MMM dd HH:mm:ss 'CET' yyyy",
            "UNIX"
        ]
        target => "@timestamp"
        remove_field  => [ "timestamp" ]
    }
```

This causes great confusion because if the timestamp field does not match any of the date formats, it always matches on UNIX, even if it is obviously not a unix timestamp (does not match regexp /^\d+$/), and so creates events at 1970-01-01.
Would it be possible to confirm that the date _could_ be a Unix timestamp before forcing a failed conversion?

Cheers,
-Robin-

**Comment by incebellipipo** [comment]
Ladies, we have the same problem again.
```
output {                                                      
    elasticsearch {                                           
        hosts => ["localhost:9200"]                           
        index => "%{host}-%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    }                                                         
}                                                             
```
Leads to index called: `host-metadata-beat-1970.01.01`
