### ISSUE TITLE
Possible memory leak in Logstash 6.8.10

### ISSUE THREAD

**Issue by shreyas29** [elastic/logstash#12382]
- Version: Logstash 6.8.10
- Operating System: Ubuntu 16.04
- Config File (if you have sensitive info, please remove it): Not possible to share
- Sample Data: NA
- Steps to Reproduce: NA

We are using Logstash in one of our microservices. The pod is getting OOMError. Below is the top consumers report from Heap dump. We are suspecting something is wrong with JRuby.
![image](https://user-images.githubusercontent.com/16454030/97156890-5b0fd280-179d-11eb-928e-854fae21a9c2.png)

**Comment by kares** [comment]
Thanks for the report, however given the screenshot and the short description we want be able to identify the leak.
We do not even see what the biggest chunk of memory `(l)` stands for. 
Also LS 6.8 is only receiving security updates at this point.
