### ISSUE TITLE
Upgrade jackson databind to 2.9.10.6

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#12383]
Or as an alternative to 2.11.x

This change impacts both core, jrjackson dependency and the beats input plugin.

**Comment by colinsurprenant** [comment]
Done via https://github.com/guyboertje/jrjackson/pull/83 in jrjackson v0.4.13.

**Comment by robbavey** [comment]
Logstash core has been upgraded - https://github.com/elastic/logstash/pull/12385

**Comment by jsvd** [comment]
@colinsurprenant @robbavey <3

@robbavey can you also backport to 7.10 once 7.10.0 is GA? Thanks!
