### ISSUE TITLE
Remove the usage of pleaserun to configure the `services` script

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#12439]
Logstash uses Pleaserun to generate startup scripts and service definitions for various service managers like sysv, systemd, upstart etc.

Pleaserun is unmaintained and sometimes generate scripts that's malformed for certain distributions, see #12453 and https://github.com/jordansissel/pleaserun/issues/146 for more details.

For these reason we should use another solution to generate the services scripts (in deb and rpm distributions)

**Comment by roaksoax** [comment]
@andsel can you please file a different issue for the 'TimeoutStopSec=infinity' ? AS the removal of pleaserun (already in progress) won't address the other issue.

**Comment by andsel** [comment]
Created issue #12453 to handle the fix on `TimeoutStopSec`
