### ISSUE TITLE
Jdbc schedule issue

### ISSUE THREAD

**Issue by 1omercohen** [elastic/logstash#12438]
- Version: 7.9.3
- Operating System:  docker
- logstash, jdbc ,sql-server, elasricsearch

`
input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/mssql-jdbc-8.4.1.jre8.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    jdbc_connection_string => "connection string"
    schedule => "* */1 * * *"
    statement => "EXEC Some Stord Procedure"
  }
}
`
my issue needs to run every hour but is running every 5 minutes? why?

![image](https://user-images.githubusercontent.com/14128432/98928278-48f29b80-24e2-11eb-93f9-949ed3d698bc.png)

**Comment by kares** [comment]
if I understand correctly you want `0 */1 * * *` for every `xx:00` not every 1 minute.
please next time try using the [forums](https://discuss.elastic.co/c/elastic-stack/logstash) or SO for questions about usage instead ...

**Comment by 1omercohen** [comment]
no, you did not understand.
in my file schedule is "* */1 * * *" => it is mean every one hour
but actual is run every 5 minutes.
is a bug in your conversion schedules.
