### ISSUE TITLE
Handle `TimeoutStopSec=infinity` corretly for `Centos-7` systemd init script

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#12453]
Logstash installation scripts, executed when deb or rpm are installed, generate init scripts for various service managers, like sysv/sysytemd/upstrart.
This init script contains the definition `TimeoutStopSec=infinity` ([generated by pleaserun](https://github.com/jordansissel/pleaserun/blob/972cff10fab32703303fd26c4c97d21ce2a1eedf/templates/systemd/default/program.service#L27)) for `systemd` that's not accepted by any systemd's version, so it happens that on `Centos-7` which uses a version before 229, the scripts doesn't wait the termination of Logstash for infinity, but it kills it immediately, after a `service logstash stop`.

More details on jordansissel/pleaserun#146

This issue related to pleaserun, there is a PR #12415 to move away from pleaserun, so we have to be sure that `TimeoutStopSec=infinity` is handled correctly by the new scripts.

**Comment by juan-domenech** [comment]
+1 on this one.
Confirmed that Logstash 7.10 under Centos-7 Systemd shuts down immediately after stop command and might cause data loss (leaving the service as failed).

```
[root@testbox ~]# systemctl stop logstash
[root@testbox ~]# systemctl status logstash
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; disabled; vendor preset: disabled)
   Active: failed (Result: signal) since Tue 2021-01-05 14:29:47 UTC; 1s ago
  Process: 347844 ExecStart=/usr/share/logstash/bin/logstash --path.settings /etc/logstash --log.level trace (code=killed, signal=KILL)
 Main PID: 347844 (code=killed, signal=KILL)
Jan 05 14:29:06 testbox systemd[1]: Started logstash.
Jan 05 14:29:47 testbox systemd[1]: Stopping logstash...
Jan 05 14:29:47 testbox systemd[1]: logstash.service stop-sigterm timed out. Killing.
Jan 05 14:29:47 testbox systemd[1]: logstash.service still around after SIGKILL. Ignoring.
Jan 05 14:29:47 testbox systemd[1]: logstash.service: main process exited, code=killed, status=9/KILL
Jan 05 14:29:47 testbox systemd[1]: Stopped logstash.
Jan 05 14:29:47 testbox systemd[1]: Unit logstash.service entered failed state.
Jan 05 14:29:47 testbox systemd[1]: logstash.service failed.
```

As workaround I'm commenting out `#TimeoutStopSec=infinity` in `/etc/systemd/system/logstash.service` to use default settings.
This gives time to Logstash to shutdown gracefully.
