### ISSUE TITLE
 logsatash同步mysql数据到es 类型字段数据丢失

### ISSUE THREAD

**Issue by xiao-ma-nong** [elastic/logstash#12486]
字段中的数据丢失

es版本 7.6.2

logstash版本 7.6.2

**Comment by kares** [comment]
thanks for the report, please try to open reports in English (doesn't matter if it's bad English) next time.
closing as there seems to be very little info to understand the issue.

**Comment by xiao-ma-nong** [comment]
> thanks for the report, please try to open reports in English (doesn't matter if it's bad English) next time.
> closing as there seems to be very little info to understand the issue.

对，是因为的我多表查询导致，java实体类是用驼峰，mysql数据库是下划线导致的字段名不对应无法更新字段

这个问题已经解决了，非常感谢你的回复
