### ISSUE TITLE
Introduce Validator Support Plugin Mixin

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#12491]
In order to introduce new plugin parameter validators (e.g., `field_reference` -> https://github.com/elastic/logstash/pull/12459), we need to provide a path for using these new validators in plugins without constraining those plugins to only work on the newest Logstash.

I have built a support library, which provides back-ports of newly-introduced validators. Plugin maintainers can rely on the provided adapter(s), and do not need to care whether support for the validator was natively provided by Logstash core or by the adapter.

This is a proposal to adopt the mixin into the logstash_plugins org and to release the associated gem artifact.

https://github.com/yaauie/logstash-mixin-validator_support

**Comment by jsvd** [comment]
Apologies for only raising this now, can you dump a bit of your thoughts on the downsides/benefits of just having plugins be pinned to logstash >= 7.11.0 vs introducing the adapter?

**Comment by yaauie** [comment]
The primary reason for this adapter plugin is the same as the reasoning we had when creating the [deprecation logger][] and [ecs compatibility][] support mixins: they allow us to move forward with the Logstash plugin APIs without fracturing our plugin ecosystem each time we introduce a new feature to Logstash core.

When we pin plugins to certain versions of Logstash, we invariably introduce complexity to maintaining the plugin, since any unrelated fixes will need to be back-ported to multiple branches. And since our small team currently is tasked with maintaining ~250 plugins, I'm very reluctant to add to the cognitive overhead of maintaining each.

By introducing a support adapter, we provide an API by which plugin maintainers can use a new feature without having to care  about pinning or maintaining multiple branches.

[deprecation logger]: https://github.com/logstash-plugins/logstash-mixin-deprecation_logger_support#deprecation-logger-support-mixin
[ecs compatibility]: https://github.com/logstash-plugins/logstash-mixin-ecs_compatibility_support#ecs-compatibility-support-mixin

**Comment by jsvd** [comment]
Thanks for the explanation @yaauie. I agree the added mixin removes potential pain of dealing with backporting fixes.

As for getting the mixin released. I'd suggest creating an empty repo and making your code into a PR so it can be reviewed.

**Comment by yaauie** [comment]
Moving conversation to the PR -> https://github.com/logstash-plugins/logstash-mixin-validator_support/pull/1
