### ISSUE TITLE
Put the new port field in an ECS field

### ISSUE THREAD

**Issue by mbudge** [elastic/logstash#12493]
Hi, 

We just noticed a new "port" field is adding at Logstash. 

This is a new top level field which is confusing for analysts/operators when it's dumped in with network data. 

Very easy for operators to think this is a port for a network connection they are investigating. 

Please can you move port to a more descriptive ECS field?

Thanks

**Comment by yaauie** [comment]
@mbudge Logstash itself doesn't add fields to events -- this is done by plugins as configured in your pipelines. We have an effort in-flight to add ECS-compatibility modes in the plugins we bundle to eliminate _implicit_ collisions with ECS (https://github.com/elastic/logstash/issues/11635), and to make that mode on-by-default in the next major release of Logstash (https://github.com/elastic/logstash/issues/11623).

Would you mind sharing details about your pipeline to help us make sure we address your use-case? Specifically, which input plugin are you using?

**Comment by mbudge** [comment]
@yaauie we think it's the TCP and UDP input plugins which are adding this field.

Thanks

**Comment by yaauie** [comment]
Great. We have those tracked as https://github.com/logstash-plugins/logstash-input-tcp/issues/149 and https://github.com/logstash-plugins/logstash-input-udp/issues/48 so I will close this issue as a duplicate.
