### ISSUE TITLE
add robustness to avoid crashing on unexepected input

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#1250]
this is a followup from issue #1240 - where pre multiline/tv_sec fix shippers were paired with post multiline/tv_sec fix indexers using redis. The indexer was crashing on the tv_sec error because the shipper malformed the event. 

should we add robustness to avoid crashing in such a condition?

**Comment by suyograo** [comment]
related to https://github.com/elasticsearch/logstash/issues/2130#issuecomment-70820578

**Comment by colinsurprenant** [comment]
the global exception handling issue is #2386 - I will keep this one open to make sure this specific concerned is tracked.

**Comment by henriklynggaard** [comment]
Any traction on this. It has been open for a long time?

**Comment by colinsurprenant** [comment]
I am closing this issue and redirecting to #4127. A lot a progress has been made to improve exception handling & reliability and the original issue reported here is not very current anymore.
