### ISSUE TITLE
Drop support for older Operating Systems for 8.0.0

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#12511]
Support for many operating system versions has dropped or will be dropped during 2019-2020 or start of 2021.

The elasticsearch team has gone through the work and compiled a list of versions that will be deprecated starting with 8.0.0 https://github.com/elastic/elasticsearch/issues/51480.

This issue has been created to track the necessary work to deprecate these same operating systems.

**Comment by roaksoax** [comment]
I believe that the support matrix now reflects all the required changes with OS support.Gonna go ahead and close this issue.
