### ISSUE TITLE
Possible memory leak in logstash 7.9.3

### ISSUE THREAD

**Issue by spgreenberg** [elastic/logstash#12555]
Our logstash nodes continue to consume more and more memory over time until they reach a point of alerting in our system. Our only remedy currently is to restart the processes and free memory. It appears there could be a memory leak.

- Version: Logstash 7.9.3
- Java: AdoptOpenJDK build 11.0.9.1+1
- Operating System: Ubuntu 16.04 (xenial)
- Config 

java start:
``` 
/var/vcap/packages/openjdk-11/jre/bin/java -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.compile.invokedynamic=true -Djruby.jit.threshold=0 -Djruby.regexp.interruptible=true -XX:+HeapDumpOnOutOfMemoryError -Xlog:gc*=debug::time -verbose:gc -Djava.security.egd=file:/dev/urandom -Dlog4j2.isThreadContextMapInheritable=true -Xms7416359K -Xmx7416359K -DPID=8 -Djava.io.tmpdir=/var/vcap/sys/tmp/archiver_syslog -cp /var/vcap/packages/logstash/logstash-core/lib/jars/animal-sniffer-annotations-1.14.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/checker-compat-qual-2.0.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/commons-codec-1.14.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/commons-compiler-3.1.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/commons-logging-1.2.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/error_prone_annotations-2.1.3.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/google-java-format-1.1.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/gradle-license-report-0.7.1.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/guava-24.1.1-jre.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/j2objc-annotations-1.1.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/jackson-annotations-2.9.10.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/jackson-core-2.9.10.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/jackson-databind-2.9.10.4.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/jackson-dataformat-cbor-2.9.10.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/janino-3.1.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/javassist-3.26.0-GA.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/jruby-complete-9.2.13.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/jsr305-1.3.9.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/log4j-api-2.13.3.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/log4j-core-2.13.3.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/log4j-jcl-2.13.3.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/log4j-slf4j-impl-2.13.3.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/logstash-core.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.core.commands-3.6.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.core.contenttype-3.4.100.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.core.expressions-3.4.300.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.core.filesystem-1.3.100.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.core.jobs-3.5.100.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.core.resources-3.7.100.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.core.runtime-3.7.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.equinox.app-1.3.100.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.equinox.common-3.6.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.equinox.preferences-3.4.1.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.equinox.registry-3.5.101.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.jdt.core-3.10.0.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.osgi-3.7.1.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/org.eclipse.text-3.5.101.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/reflections-0.9.11.jar:/var/vcap/packages/logstash/logstash-core/lib/jars/slf4j-api-1.7.25.jar org.logstash.Logstash --path.data /var/vcap/store/archiver_syslog --path.config /var/vcap/jobs/archiver_syslog/config/logstash.conf --path.settings /var/vcap/jobs/archiver_syslog/config --pipeline.workers 2 --log.format=json --log.level=info --path.logs /var/vcap/sys/log/archiver_syslog
```

logstash.yml
```
queue.type: persisted
queue.page_capacity: 250mb
queue.max_events: 0
queue.max_bytes: 30gb
queue.checkpoint.acks: 1024
queue.checkpoint.writes: 1024
queue.checkpoint.interval: 1000
```

- Sample Data: 

We have enabled debug garbage collection logging and see the free space declining over time. The below excerpts of logs are from our staging environment with the production environment usage growing more rapidly. The full logs show constant growth between the excerpts.

Total Free Space:

``` 
[2021-01-07T06:03:45.118+0000] Total Free Space: 878728163
[2021-01-07T20:59:50.885+0000] Total Free Space: 878238893
```

We see similar growth in Young GC reporting:

```
[2021-01-07T05:57:53.878+0000] GC(167) Pause Young (Allocation Failure) 514M->381M(7227M) 47.446ms
[2021-01-07T21:05:36.372+0000] GC(318) Pause Young (Allocation Failure) 520M->384M(7227M) 43.155ms
```

The concurrent mark-sweep and Metaspace appear to grow continously:

```
[2021-01-07T05:57:53.879+0000] GC(167)  concurrent mark-sweep generation total 7247488K, used 381639K [0x0000000645a60000, 0x0000000800000000, 0x0000000800000000)
[2021-01-07T21:05:36.372+0000] GC(318)  concurrent mark-sweep generation total 7247488K, used 385485K [0x0000000645a60000, 0x0000000800000000, 0x0000000800000000)
```

```
[2021-01-07T06:03:45.164+0000] GC(168)  Metaspace       used 111888K, capacity 131144K, committed 131192K, reserved 1159168K
[2021-01-07T21:11:41.429+0000] GC(319)  Metaspace       used 111961K, capacity 131210K, committed 131448K, reserved 1159168K
```

We have six different ELK clusters each with two types of logstash nodes in each (archivers and ingestors). All of our logstash instances show constant memory growth over time and require periodic restarting.

We are unsure of what additional information we can collect to help identify a root cause. Please let me know how we can help provide more information.

**Comment by kares** [comment]
> All of our logstash instances show constant memory growth over time and require periodic restarting.

What is the time frame you're seeing for the growth over time, is LS under load when memory 'grows'?
Did you try identifying the leak (by analysing a heap-dump) or is it more of an observation at this point?

Is this new behavior you're seeing after an upgrade to LS 7.9.1, was it behaving fine before?

Also, could you please share your `logstash.conf` to be able to identify what plugins you're using.

**Comment by spgreenberg** [comment]
We are having to restart the LS process about once a week. This is for the logging system on cloud.gov and therefore the load is fairly consistent (2B logs/month). This system handles all of the logs for all applications on the platform.

I apologize for not being clear in my original message when I said: "All of our logstash instances show constant memory growth over time and require periodic restarting." We have (3) r5.large instances that are sending logs to S3. We also have (5) r5.xlarge instances that ingest for the ELK stack. Only the S3 LS nodes are running out of memory. This behavior started after we upgraded to 7.9.1. 

Our logstash.conf is fairly simple (redacted):

```
input {
  tcp {
    add_field => [ "type", "syslog" ]
    host => "<tcp_host>"
    port => "<tcp_port>"
  }
  udp {
    add_field => [ "type", "syslog" ]
    host => "<udp_host>"
    port => "<udp_port>"
  }
  relp {
    add_field => { "_logstash_input" => "relp" }
    host => "<relp_host>"
    port => "<relp_port>"
  }
}
filter {
  # drop empty logs (eg: monit connection healthcheck)
  ruby {
    code => 'event.cancel if event.get("message") == "\u0000"'
  }
}
output {  
        s3 {
          bucket => "<bucket>"
          encoding => "gzip"
          prefix => "%{+yyyy/MM/dd/HH/mm}"
          region => "<region>"
          server_side_encryption => true
          time_file => 5
          validate_credentials_on_root_bucket => false        
        }   
}
```

**Comment by kares** [comment]
> Only the S3 LS nodes are running out of memory. 

and the configuration for the ELK stack LS instances would be the same except `output { elasticsearch }`, right?

**Comment by spgreenberg** [comment]
Yes, that is correct.

**Comment by kares** [comment]
Thanks Steve, had a few ideas to explore but I checked none of them should matter here.
Recently, we've seen an issue with running out of heap using the S3 output - turned out to be an issue with having too many temporary files around being gzip-ed at the same time (due "high" `time_file => 60` and a changing `prefix => `).

If it's a leak we should be able to confirm from a heap dump - esp. one that had been running for a long time and is not releasing several MB of memory over time. Sharing a heap dump might be tricky since there will be sensitive data due the memory snapshot. Maybe you can try opening a dump in a tool such as [MAT](https://www.eclipse.org/mat/) and sharing screenshots from it's "potential leak candidate analysis" + the histogram on largest GC roots.

**Comment by kares** [comment]
closing - we never got any clear confirmation of a leak
