### ISSUE TITLE
Security issue RHSA-2020:5566

### ISSUE THREAD

**Issue by 2ndalpha** [elastic/logstash#12565]
In the latest Docker image `logstash:7.10.1@sha256:c37e21ed82561791d095a7f9f617ea123bc255b32aa9ee61b7713cbd287749c0`
There is a security issue with high severity: [RHSA-2020:5566](https://access.redhat.com/errata/RHSA-2020:5566)

**Comment by yaauie** [comment]
Per guidance, security issues should not be opened in public. I am closing this ticket and have referred the issue to Elastic's internal Security team:

> For security vulnerabilities please only send reports to security@elastic.co.
> See https://www.elastic.co/community/security for more information.
