### ISSUE TITLE
Patch for JRuby bug #6529

### ISSUE THREAD

**Issue by peacand** [elastic/logstash#12577]
Hi,

Is there any way to include a patch in Logstash to include the fix for the issue 6529 in JRuby ? 

==>  [FD leak with orphan Unix Socket](https://github.com/jruby/jruby/issues/6529)

This fix prevents a file descriptor leak when we use Unix Sockets in JRuby. Which is my case with custom Logstash plugins. Without this fix, my plugin is likely to crash after some time due to too may open files on the Logstash process. 

Thank you for your help

**Comment by headius** [comment]
The fix mentioned above has been pushed to relevant JRuby branches and will be in all upcoming releases. Thanks for the report!

**Comment by kares** [comment]
Hey Michael, this seems to be Unix socket specific issue.
The patching would be quite an effort but you could easily to that on your own - replacing `vendor/jruby/lib/jruby.jar` with a [jruby-core-9.2.15.0 SNAPSHOT](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.jruby&a=jruby-core&v=9.2.15.0-SNAPSHOT). Logstash will bundle JRuby 9.2.15.0 in it's next release after 9.2.15.0 is released.

**Comment by peacand** [comment]
Thank you for your help @kares. I've tried that but it does not seem to work. When I replace the `vendor/jruby/lib/jruby.jar`, when I restart Logstash it's still saying `[main] runner - Starting Logstash {"logstash.version"=>"7.9.3", "jruby.version"=>"jruby 9.2.13.0 (2.5.7)`

And the bug is still here. It looks like replacing the Jar is not enough to actually switch the JRuby runtime of Logstash.

**Comment by kares** [comment]
@peacand sorry for the confusion - only the second jar is used when running LS (the vendor/jruby/lib one gets still to be used with the plugin manager). the *logstash-core/lib/jars/jruby-complete-9.2.13.0.jar* is a fat-jar not just "jruby-core" so you would be downloading [jruby-complete](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.jruby&a=jruby-complete&v=9.2.15.0-SNAPSHOT). and if I didn't say so this is :hankey:

**Comment by peacand** [comment]
Thank you for the clarification @kares. With this Jar I get the following error while starting Logstash : 

`[main] Logstash - java.lang.IllegalStateException: Logstash stopped processing becaus                                                                                                                        e of an error: (GemNotFound) Could not find jruby-openssl-0.10.4-java in any of the sources`

Indeed it looks like with the latest jruby 9.2.15 jruby-openssl version is 0.10.5. It looks like there is a version mismatch somewhere. 

I tried to fix the version number in the file Gemfile.lock, I replaced the line `jruby-openssl (0.10.4-java)` with `jruby-openssl (0.10.5-java)`

After that it seems to work.

Is that the right way to do ? Do you think it is safe to keep Logstash running like that ?
