### ISSUE TITLE
Review memory sizing recommendations

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#12622]
Currently we have recommendations on memory sizing in the [performance troubleshooting](https://www.elastic.co/guide/en/logstash/current/performance-troubleshooting.html) and [jvm settings](https://www.elastic.co/guide/en/logstash/current/jvm-settings.html#heap-size).

Namely, we recommend: 
1. The recommended heap size for typical ingestion scenarios should be no less than 4GB and no more than 8GB.
2.  Do not increase the heap size past the amount of physical memory. Some memory must be left to run the OS and other processes. As a general guideline for most installations, don’t exceed 50-75% of physical memory. The more memory you have, the higher percentage you can use.

Let's take an example: in a server with 16GB of RAM, a logstash instance is deployed w/ a beats input to elasticsearch output pipeline w/ PQ. Our guidelines above can lead users to select Xmx:8g (8GB of heap size).
By default the JVM will allocate the same size for direct memory (beats input is a heavy user of direct memory). This may cause to the Operating System to not have memory for itself, or not enough memory to bring PQ mmapped pages to memory.

Like Elasticsearch we should default direct memory to be half of the heap, so in the example above we'd set `-XX:MaxDirectMemorySize=4g`. Until we default direct memory to be half of heap (tracked in https://github.com/elastic/logstash/issues/12621), we should recommend to either not exceed around 30-40% of the total RAM for heap, or to explicitly set -XX:MaxDirectMemorySize in the jvm.options file.

**Comment by andsel** [comment]
The sizing of direct memory is little bit more complicated. As per [discussion](https://github.com/netty/netty/discussions/13514#discussioncomment-6531208) on Netty project, when Logstash executes one of the plugins that leverage Netty, there is another portion of memory allocated by Unsafe that's not accounted in the JVM limit (`MaxDirectMemorySize`) which inherit the same size.
So the suggestion to set `MaxDirectMemorySize` to the half of Java heap size is correct in this case.
