### ISSUE TITLE
Ruby Time.nsec

### ISSUE THREAD

**Issue by sliencestorm-wyw** [elastic/logstash#12627]
I fond a problem in ruby
the code  is  
 t = Time.now()
 puts  t.strftime('%Y-%m-%d %X')+ '.' + (time).to_s + '+0800'
output is
2021-01-31 01:19:24.739830342+0800
739830342 is 9 
but in logstash in put 
  ruby {
                       code =>"
                            t = Time.now()
                            event.set('date', t.strftime('%Y-%m-%d %X')+ '.' +(t.nsec).to_s + '+0800')
                      "
          }
output is like
2021-01-31 09:55:33.8403000+0800
8403000 is 7   not 9  or  6
Is this a bug?  It will cause date_time_parse_exception.
date model is not support  date_nanos
ruby model is not support  date_nanos either?

**Comment by yaauie** [comment]
Remember to left-pad your nanoseconds with zeroes if you're composing timestamps this way ☺️

**Comment by sliencestorm-wyw** [comment]
well
code can write to it
t.strftime('%Y-%m-%d %X')+ '.' + (t.nsec).to_s.rjust(9, '0')  + '+0800'

**Comment by roaksoax** [comment]
This is a test

**Comment by roaksoax** [comment]
This is a test
