### ISSUE TITLE
PluginListing: logstash-output-dynatrace

### ISSUE THREAD

**Issue by dyladan** [elastic/logstash#12947]
Following the directions at https://www.elastic.co/guide/en/logstash/current/plugin-listing.html I am creating this issue to request listing of the `logstash-output-dynatrace` plugin.

This plugin outputs log lines to Dynatrace for correlation and analysis.

The current plugin can be found here: https://github.com/dynatrace-oss/logstash-output-dynatrace

I believe I have met all of the requirements. The plugin has unit tests and we run internal integration tests nightly against every minor logstash version from `7.2.1` to `7.12.0`.

Following the example of other plugins, I added the Travis CI include from `logstash-plugins/.ci:travis/travis.yml@1.x`, but it appears to fail during the `docker-setup.sh`. An example of this can be seen here: https://travis-ci.com/github/dynatrace-oss/logstash-output-dynatrace/jobs/506912569. Is this an issue you've seen before, and if so how can we fix this issue? If this is no longer the recommended way to do testing, we're happy to switch over to github actions and build testing procedures ourselves.

**Comment by dyladan** [comment]
I know it was a holiday weekend, but has anyone seen the same test issue? If it is better for us to create our own test setup please let me know and I will get to work on it

**Comment by dyladan** [comment]
Has anyone had a chance to look at this?

**Comment by andsel** [comment]
Hi @dyladan thank you a lot for your contribution.

Regarding the fail, it's due to the fact that the `Rakefile` doesn't provide a `vendor` task. This task is invoked from `.ci/Dockerfile` https://github.com/logstash-plugins/.ci/blob/b20255c2da0c7fa82e9a247f6366e2da61b47e6c/Dockerfile#L32. 
The straightforward way to solve it is to `require "logstash/devutils/rake"` on top of your `Rakefile`, like in https://github.com/logstash-plugins/logstash-integration-rabbitmq/blob/master/Rakefile for example, or you can redefine the `vendor` as in https://github.com/logstash-plugins/logstash-integration-kafka/blob/0465820dce529b9230842e8222710431264bac2f/Rakefile#L10-L12

**Comment by dyladan** [comment]
Thanks for your help. That worked and the tests are passing now. We've published [`logstash-output-dynatrace@0.1.0`](https://rubygems.org/gems/logstash-output-dynatrace/versions/0.1.0) on RubyGems.

**Comment by dyladan** [comment]
At this point do we need to do anything further to be included in the plugin listing?

**Comment by andsel** [comment]
Hi @dyladan 
we are almost there, if you could add a CHANGELOG.md file that we can link from documentation page would  be great. Bring as an example https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/master/CHANGELOG.md.

I would suggest some error handling around https://github.com/dynatrace-oss/logstash-output-dynatrace/blob/9f2fc7e870b45386e7433d364c4d4e9b232464e9/lib/logstash/outputs/dynatrace.rb#L76-L79 in case the Logstash host experience some network errors, maybe that sending code should decode the error and decide to give some retries, with incremental back of or give up immediately.

**Comment by dyladan** [comment]
Looks like armin handled the changelog and I'm working on error handling today

**Comment by andsel** [comment]
Great, so now I can merge the Logstash documention that links it

**Comment by andsel** [comment]
I'll ping you when published

**Comment by andsel** [comment]
Dynatrace output plugin is listed https://www.elastic.co/guide/en/logstash/master/plugins-outputs-dynatrace.html. 
I think this issue could be closed

**Comment by dyladan** [comment]
Thanks so much!

**Comment by dyladan** [comment]
@andsel we're working on the exponential backoff you suggested and we had some questions about the threading model. In our current iteration, we are using 5 retries max with `2^i` sleep seconds. This means at most we are waiting for about 30 seconds. We are currently just using the `sleep` method to sleep the thread for that amount of time.

We are currently using concurrency mode `:single` which is documented like this:

> When configured as :single a single instance of the Output will be shared among the
> pipeline worker threads. Access to the `#multi_receive/#multi_receive_encoded/#receive` method will be synchronized
> i.e. only one thread will be active at a time making threadsafety much simpler.

According to the [execution model](https://www.elastic.co/guide/en/logstash/current/execution-model.html), there is one worker thread per CPU.

As I understand it this means we would only ever take up a single thread and not exhaust the thread pool correct?

Another issue is the event queue. If a Dynatrace server is unavailable and the batch size is 125 (default) then we will at most remove 125 events from the queue every 30 seconds or so. This will cause the queue to constantly grow and eventually crash the logstash server no? Is there any safeguard against this? If not, what can we do in our output plugin to prevent causing this?

**Comment by andsel** [comment]
> According to the execution model, there is one worker thread per CPU.
