### ISSUE TITLE
logstash 1.3.3 is losing data with raw TCP input

### ISSUE THREAD

**Issue by klesteb** [elastic/logstash#1295]
When using raw TCP for input, I have noticed that you can lose data. This appears to happen when the input queue is overflowed. How is this overflowed, I am not sure because there is no entry in the log file and I am not a Ruby programmer. But I suspect it is when a queue processing thread dies.

Since there is no flow control, the sending program might as well dump the data to /dev/null.

When this happens, it would be nice if the socket was closed, then the client can pause and reconnect.

**Comment by murthym** [comment]
Hi,
I am using logstash 1.3.3 flat jar on solaris and seeing out of memory issues on production environment.

I have gone through this on jira https://logstash.jira.com/browse/LOGSTASH-2168.

I am afraid I cannot upgrade to the higher version other than 1.3.3 which I believe is compatible with the solaris version we are using 

Could you please advice how should I add the patch or import the fix on the flat jar 1.3.3?

We have plans to deploy logstash on other set of production servers and this is based on how stable the version 1.3.3 is. So I need to know if this version really works or I need to move to a different version.

Any information would be really helpful.

Thanks in anticipation.

Regards,
Mohan

**Comment by jordansissel** [comment]
1.3.x is not worked on anymore and does not receive any more bug fixes. Recommend you upgrade.

If you cannot upgrade, backporting that patch is possible, but I don't have any particular advice and I don't know how complex it will be to backport. Good luck! :)
