### ISSUE TITLE
ingest-convert.sh: line 3: java: command not found

### ISSUE THREAD

**Issue by ulab** [elastic/logstash#13022]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)

```
balu@elk-logstash-01:~$ dpkg -l logstash
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  logstash       1:7.13.2-1   amd64        An extensible logging pipeline
```

3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)

systemd, irrelevant.

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

irrelevant.

**JVM** (e.g. `java -version`):

bundled:
```
balu@elk-logstash-01:~$ /usr/share/logstash/jdk/bin/java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

```
balu@elk-logstash-01:~$ uname -a
Linux elk-logstash-01 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux
balu@elk-logstash-01:~$ cat /etc/debian_version
10.10
```

**Description of the problem including expected versus actual behavior**:

When running `ingest-convert.sh`, the bundled `java` interpreter is not found.

I'd suggest to expand the `PATH` environment variable in the script or change the script to use the absolute path to the bundled `java` interpreter.

```
balu@elk-logstash-01:/usr/share/logstash/bin$ diff ingest-convert.sh ingest-convert,balu.sh
2a3,4
> PATH=$PATH:/usr/share/logstash/jdk/bin/
>
```

I am not sure if how this is handled different in other distributions.

**Steps to reproduce**:

```
balu@elk-logstash-01:~$ /usr/share/logstash/bin/ingest-convert.sh
/usr/share/logstash/bin/ingest-convert.sh: line 3: java: command not found
```

**Comment by kares** [comment]
Thanks for the report, the tool [hasn't been maintained for a while](https://github.com/elastic/logstash/issues/12933) and should be removed soon.

> Our recommendation for users looking to convert Beat module's ingest pipelines is to follow the guide [here](https://www.elastic.co/guide/en/logstash/current/use-ingest-pipelines.html).

**Comment by ulab** [comment]
Oh I see. I was actually trying to convert the other way - logstash patterns (for [postfix logs](https://github.com/whyscream/postfix-grok-patterns) to ingest pipelines when I stumbled over the tool and noticed it was not working :)

So I thought I'd report it, but if it gets removed, that's fine by me :).
