### ISSUE TITLE
Document sprintf timestamp timezone behavior

### ISSUE THREAD

**Issue by RubieV** [elastic/logstash#13112]
## Context
Logstash allows for putting dynamic fields in the event data, such as the current time in your specified format.

This format is specified in the [sprintf +FORMAT](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#sprintf), and applied to the @timestamp field. 

## Issue
The locale of the `sprintf` differs from the locale of the `date` filter. This creates inconsistencies in the rollover of indices and other unexpected behavior. 

#### Difference
**sprintf locale**
https://github.com/elastic/logstash/blob/c698aa224b44c7356fbfeb58ebb0c4a66d72dc71/logstash-core/src/main/java/org/logstash/StringInterpolation.java#L81

**date locale**
The [platform default](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-timezone)

## Moving forward
Suggested to make this clear in the [documentation](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#sprintf).

**Comment by SirBouBou** [comment]
Hi, I would like to solve this issue with friends as a first contribution to Logstash if it's not already taken.
