### ISSUE TITLE
version 7.10.2 not available on elasticsearch artifcats

### ISSUE THREAD

**Issue by happysalada** [elastic/logstash#13176]
The following url returns a 404

https://artifacts.elastic.co/downloads/logstash/logstash-7.10.2.tar.gz

not sure why that is.

I'm not sure this is the best place to post this. If it's not and you let me know where I should post this, I would be happy to post it somewhere else.

**Comment by andsel** [comment]
Hi @happysalada, 
starting from version `7.10.0` Logstash ships with embedded JVM, so the name of the package changed a little bit to include the OS and CPU architecture, for example the Linux x86_64 can be found at https://artifacts.elastic.co/downloads/logstash/logstash-7.10.2-linux-x86_64.tar.gz

**Comment by happysalada** [comment]
Thanks a lot!
