### ISSUE TITLE
Logstash 7.14.1: stall on shutdown due to pipeline error when using an external GeoIP DB.

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#13208]
Version: 7.14.1 (and 7.14.0)
Installation source: deb
Run with: systemd

**Plugins installed**: https://gist.github.com/ceeeekay/4d92026033118d4efb44951d194a57d4

**JVM**: bundled 11.0.11+9

**OS version** Ubuntu 18.04.5 LTS

**Description of the problem including expected versus actual behavior**: 
* When using a custom `database` directive for the geoip filter, Logstash produces a pipeline error on shutdown. 
* This is problematic for us as we're using pipeline-to-pipeline communication, and the error prevents the running pipelines from shutting down in the correct order, resulting in a stalled shutdown because of in-flight events.
* If the `database` directive is omitted, and Logstash runs with the packaged GeoIP DBs, this error does not occur.

**Expected behaviour:** Logstash shuts down cleanly regardless of whether the `database` directive is used.

**Steps to reproduce**: 
1. Start Logstash 7.14.1 with a config using the geoip filter, and a `database` directive referencing an external GeoIP DB.
2. Issue a shutdown, and observe the logs.

The following basic config will reproduce the error, but not cause a stall, as there are no sequential pipelines. I've used this for the sake of simplicity. No events need to be in the pipeline - a start/stop will reproduce the error.

```
input {
  beats {
    port => 3001
  }
}
filter {
  geoip {
    source => "message"
    database => "/tmp/GeoLite2-City.mmdb"
  }
}
output {
 file {
   path => "/tmp/main.txt"
 }
}
```

**Provide logs (if relevant)**:
**Startup:**
`[2021-09-07T10:53:20,976][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/tmp/GeoLite2-City.mmdb"}`

**Shutdown:**
`[2021-09-07T10:53:36,407][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/usr/share/logstash/x-pack/lib/filters/geoip/database_manager.rb:294:in `unsubscribe_database_path'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-geoip-7.2.2-java/lib/logstash/filters/geoip.rb:174:in `close'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:97:in `do_close'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:90:in `do_close'", "org/jruby/RubyArray.java:1820:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:473:in `shutdown_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/ls.conf"], :thread=>"#<Thread:0x728674c6 run>"}`

**Comment by kaisecheng** [comment]
@ceeeekay thanks for reporting the bug. A fix will be released in the next cycle, 7.14.3 and 7.15.1
