### ISSUE TITLE
zeromq errors out upon logstash restart

### ISSUE THREAD

**Issue by gurvindersingh** [elastic/logstash#1320]
When restarting logstash when receiving input from zeromq, logstash gives error as 

{:timestamp=>"2014-05-01T00:38:36.503000+0200", :message=>"ZeroMQ error while in recv_string", :error_code=>-1, :level=>:error}

Error repeats for a while before logstash has started up completely, it functions fine afterwards though

**Comment by jordansissel** [comment]
@timbunce https://logstash.jira.com/browse/LOGSTASH-2252 is resolved, though I am not really sure how zeromq problems relate to .gitignore

**Comment by jsvd** [comment]
migrated to https://github.com/logstash-plugins/logstash-input-zeromq/issues/5
