### ISSUE TITLE
Support Nested Hashes in HTTP output mapping

### ISSUE THREAD

**Issue by GABeech** [elastic/logstash#1323]
I would like the ability to have nested hashes when using the mapping function of the HTTP output. 

given: 
`mapping => [ "metric", "test", "tags", [ "name", "Help", "type", "Please"]`

The current json output would be: 

    {
       "metric": "test",
       "tags": "["name","Help","type","Please"]"
    }

What I would expect would be: 

    {
      "Metric": "test",
      "tags": {
        "name": "Help",
        "type": "Please"
      }
    }

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-http/issues/4. Let's continue the discussion there! :)
