### ISSUE TITLE
logstash docker image: support setting "pipeline.ordered" via environment variables

### ISSUE THREAD

**Issue by passing** [elastic/logstash#13293]
the `env2yaml` script is supporting most "pipeline" settings:
https://github.com/elastic/logstash/blob/master/docker/data/logstash/env2yaml/env2yaml.go#L53-L61
https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html
only these 2 are missing
- pipeline.ordered
- pipeline.java_execution

being able to configure `pipeline.workers`, I'd expect to be able to also configure `pipeline.ordered`
not sure about `pipeline.java_execution`, but I guess adding it would do no harm as well..

**Comment by roaksoax** [comment]
Hi @passing 

Thanks for reporting this issue. I've fixed it and will be released as part of 7.16.0. Please note that I've only added pipeline.ordered, given that the java execution is already default and we don't expect users to use "false", as in 8.x the "ruby execution" (which this would have used if set to false), is already deprecated and already removed in 8.x, and I haven't really seen any docker users using it.

Hope this helps!
