### ISSUE TITLE
.ruby-version has wrong jruby version

### ISSUE THREAD

**Issue by jstemen** [elastic/logstash#13388]
**Logstash information**:

The jruby version in the README.md ( 9.2) file doesn't match the jruby version in the .ruby-version (9.1) .  This is an issue with v7.9.3 and likely other versions of the code.

The following commands illustrate the issue:
```
jared@jared-N56JN:~/logstash$ git checkout v7.9.3
HEAD is now at d296f0087 Update patch plugin versions in gemfile lock for 7.9.3 Update Gemfile.jruby-2.5.lock.release to keep jruby-openssl fixed to version 0.10.4, see #12300
jared@jared-N56JN:~/logstash$ grep 9.2 README.md 
* Install JRuby 9.2.x It is recommended to use a Ruby version manager such as [RVM](https://rvm.io/) or [rbenv](https://github.com/sstephenson/rbenv).
jared@jared-N56JN:~/logstash$ cat .ruby-version 
jruby-9.1.12.0
```

**Comment by kares** [comment]
LS embeds JRuby (version taken from the [yml](https://github.com/elastic/logstash/blob/main/versions.yml)), the *.ruby-version* is outdated but unfortunately still required by a build step.
