### ISSUE TITLE
logstash output plugin  does not supports influxdb 2.0 version 

### ISSUE THREAD

**Issue by chenzhigang-cn** [elastic/logstash#13393]
influxdb 2.0 use token ，org  and bucket ，but output plugin  influxdb use db and measurement ,

**Comment by kares** [comment]
thanks for the report - since there's already https://github.com/logstash-plugins/logstash-output-influxdb/issues/96 no need to double open issues against LS as well esp. since core Logstash can not do much about the 3rd party plugin.
