### ISSUE TITLE
[DOCKER] change base images to Ubuntu 20.04

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#13438]
As Centos 8 will be EOL by the end of the year the base image of Logstash's docker images will have to be changed to a different operating system.
Currently Logstash uses centos 7 and while it's a LTS release it is an operating system released in 2014 so it's time to move forward. So we (Elastic) are jointly deciding on adopting Ubuntu 20.04 for the base OS of docker images of products like Logstash, Elasticsearch and Kibana.

**Comment by roaksoax** [comment]
Since Ubuntu 20.04 is the base image, we can now close this issue.
