### ISSUE TITLE
LS_JAVA_OPTS not parsed if jvm.options file is absent

### ISSUE THREAD

**Issue by sidmalik123** [elastic/logstash#13472]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`) 7.12.1
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker) Docker Hub https://hub.docker.com/_/logstash 
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes) Kubernetes

**Description of the problem including expected versus actual behavior**:
Setting the heap size using the `LS_JAVA_OPTS` environment variable doesn't work unless you have a `jvm.options` file. The reason for this is that this parser [returns](https://github.com/elastic/logstash/blob/main/logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java#L77-L78) before parsing the environment variable if there is no `jvm.options` file. So, it never reaches [the point where the environment variable is parsed.](https://github.com/elastic/logstash/blob/main/logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java#L117). I would except the environment variable to still be parsed even if options using the `jvm.options` file haven't been specified.

**Steps to reproduce**:

 1. Set the `LS_JAVA_OPTS` environment variable to `-Xmx<your value>`.
 2. Start Logstash.
 3. `curl localhost:9600/_node/jvm` and then check the value of `heap_max_in_bytes`, this will be set to 500MB irrespective of the value you specified in the environment variable.

**Comment by mandeamit** [comment]
I am having same issue on logstash version 7.16.1

```
[root@logstash]# echo $LS_JAVA_OPTS
-Xmx1g -Xms1g
[root@logstash]# ps -ef|grep logstash|grep -i xms
[root@logstash]# 
```

**Comment by KannappanSomu** [comment]
+1

**Comment by yaauie** [comment]
I can confirm that this is the source of the issue. `JvmOptionsParser#parse` is responsible for injecting args from the environment, and is not called if the `jvm.options` file is not present.

https://github.com/elastic/logstash/blob/0c2645c9c6e181334b85f8414165d4e36c9671a0/logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java#L75-L80
