### ISSUE TITLE
Enhancement: Add array support for host parameter in elasticsearch output

### ISSUE THREAD

**Issue by faxm0dem** [elastic/logstash#1349]
In an environment where multicast discovery is disabled (`discovery.zen.ping.multicast.enabled: false`), it would be more robust to have `host` accept a list of unicast adresses, as it is possible in elasticsearch using `discovery.zen.ping.unicast.hosts: ["host1", "host2", ...]`.

**Comment by fninja** [comment]
just for the sake of clarity: the elasticsearch output plugin shipped with logstash 2 (don't know about 1.5) accepts lists of hosts in json like this:
```
elasticsearch {
hosts => [ 'host1', 'host2', ... 'hostN' ]
[...]
}
```

works nicely, thanks!
