### ISSUE TITLE
The logstash s3 module cannot read data from Kafka. How can I solve it?

### ISSUE THREAD

**Issue by shaojielinux** [elastic/logstash#13524]
The logstash s3 module cannot read data from Kafka. How can I solve it?
Below is my configuration
input {
        kafka {
            bootstrap_servers => "10.88.14.172:9092,10.88.6.9:9092,10.88.10.166:9092
            topics => ["fluent-log"]
            group_id => "k8s2"
            consumer_threads => 4
            decorate_events => true
            auto_offset_reset => "latest"
            codec => "json"
         }
}

output {
  s3{
    access_key_id => ""
    secret_access_key => ""
    region => ""
    bucket => ""
    prefix => "%{[container_name]}/%{+YYYY}/%{+MM}/%{+dd}"
    temporary_directory => "/tmp/logstash_s3"
    encoding => "gzip"
    codec => "plain"
    #以下time_file設定(15分→5分)を追記
    rotation_strategy => "time"
    time_file => 5
  }
}

**Comment by yaauie** [comment]
The Logstash repository is not the place for general debugging. I would advise you to post in the [community forums](https://discuss.elastic.co/c/logstash), and to include relevant logs, perhaps at DEBUG level by adding `log.level: debug` to your `config/logstash.yml`. It may also be helpful to include what version of Logstash you are working with, how it was installed (tarball, package manager, etc), and how the process is being spawned (command-line, or as a managed service).
