### ISSUE TITLE
Contradictory statements about setting LS_JAVA_HOME

### ISSUE THREAD

**Issue by alexander-marquardt** [elastic/logstash#13561]
The [Bundled JDK](https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html#ls-jvm) documentation states the following:

> Use the LS_JAVA_HOME environment variable if you want to use a JDK other than the version that is bundled.  

If I am interpreting this correctly, it means that if `LS_JAVA_HOME`  is not set, that the bundled version will be applied by default (or in other words, it is not necessary to set `LS_JAVA_HOME`)

But later on in [LS_JAVA_HOME and JAVA_HOME](https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html#java-home) we state:

> Logstash uses the Java version set in LS_JAVA_HOME. The LS_JAVA_HOME environment variable **_must be set for Logstash to operate correctly_**. 

Which contradicts what is previously stated. 

CC: @karenzone

Originally mentioned this issue in https://github.com/elastic/logstash/pull/13513,

**Comment by yaauie** [comment]
Facts:

 - Logstash needs Java to run.
 - If `LS_JAVA_HOME` is set, we use the Java it specifies (since ~7.16?); else
 - If `JAVA_HOME` is set, we use it (deprecated, removed in 8.0); else
 - If running from an artifact that bundled Java, we use the bundled Java; else
 - we fall back to using the system Java, as available on the `PATH`; else
 - Logstash fails to launch

**Comment by andsel** [comment]
I think that the sentence 

> Logstash uses the Java version set in LS_JAVA_HOME. The LS_JAVA_HOME environment variable must be set for Logstash to operate correctly.

comes from when Logstash didn't bundle the JDK.

Maybe we could restate it as 
> Logstash by default uses the bundled JDK, if you want to use a different one please define the LS_JAVA_HOME enviroment variable.

**Comment by RobertShan2000** [comment]
I will work on this and submit PR later

**Comment by xyzkpz** [comment]
how to define LS_JAVA_HOME with logstash jdk bundle ??

**Comment by andsel** [comment]
Hi @xyzkpz you just need to value the environment variable, for example
```sh
LS_JAVA_HOME=/path/to/user_jdk bin/logstash -e "input{stdin{}}"
```

**Comment by xyzkpz** [comment]
Thanks @andsel
