### ISSUE TITLE
[WARN ][logstash.filters.elasticsearch] Failed to query elasticsearch for previous event {:index=>"kiosk_search-%{+YYYY.MM.dd}", :error=>"[404] {\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index [kiosk_search-2022.01.07]\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"kiosk_search-2022.01.07\",\"index_uuid\":\"_na_\",\"index\":\"kiosk_search-2022.01.07\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index [kiosk_search-2022.01.07]\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"kiosk_search-2022.01.07\",\"index_uuid\":\"_na_\",\"index\":\"kiosk_search-2022.01.07\"},\"status\":404}"} 

### ISSUE THREAD

**Issue by ravellavenky91** [elastic/logstash#13591]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `LS_JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by yaauie** [comment]
This is not a bug. Please use the [community forums](discuss.elastic.co/c/elastic-stack/logstash/14) for guidance.

The warning is coming from an Elasticaearch filter in your pipeline. It indicates that it is making a request to Elasticaearch, and that Elasticaearch is replying with a 404 indicating that the index is not found. When the Elasticaearch filter cannot enrich an event, the event is emitted to downstream filters/outputs and this warning is emitted to the logs.
