### ISSUE TITLE
Edit urls are not working because they are hard coded to master

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#13627]
The edit_urls in the Logstash docs incorrectly point to master, which has changed to main recently. For example:

:edit_url: https://github.com/logstash-plugins/logstash-input-azure_event_hubs/edit/master/docs/index.asciidoc

They all need to be updated to main

**Comment by dedemorton** [comment]
@karenzone Let me know if you want me to fix this.

**Comment by xeraa** [comment]
Note to myself (otherwise I might not find this again): Reply to https://twitter.com/j__st/status/1481917033772167171 once done :)

**Comment by karenzone** [comment]
Already tracking here: https://github.com/elastic/logstash/issues/13619
