### ISSUE TITLE
Cisco ASA pattern error

### ISSUE THREAD

**Issue by dav3860** [elastic/logstash#1369]
Hi,

There is an issue with the built-in pattern for Cisco ASA firewalls. The line :
```
# ASA-6-302020, ASA-6-302021
CISCOFW302020_302021 %{CISCO_ACTION:action}(?: %{CISCO_DIRECTION:direction})? %{WORD:protocol} connection for faddr %{IP:dst_ip}/%{INT:icmp_seq_num}(?:\(%{DATA:fwuser}\))? gaddr %{IP:src_xlated_ip}/%{INT:icmp_code_xlated} laddr %{IP:src_ip}/%{INT:icmp_code}( \(%{DATA:user}\))?
```
should be replaced by :
```
# ASA-6-302020_302021 inbound
CISCOFW302020_302021_1 %{CISCO_ACTION:action}(?: (?<direction>inbound))? %{WORD:protocol} connection for faddr %{IP:src_ip}/%{INT:icmp_seq_num}(?:\(%{DATA:fwuser}\))? gaddr %{IP:dst_xlated_ip}/%{INT:icmp_code_xlated} laddr %{IP:dst_ip}/%{INT:icmp_code}( \(%{DATA:user}\))?
# ASA-6-302020_302021 outbound
CISCOFW302020_302021_2 %{CISCO_ACTION:action}(?: (?<direction>outbound))? %{WORD:protocol} connection for faddr %{IP:dst_ip}/%{INT:icmp_seq_num}(?:\(%{DATA:fwuser}\))? gaddr %{IP:src_xlated_ip}/%{INT:icmp_code_xlated} laddr %{IP:src_ip}/%{INT:icmp_code}( \(%{DATA:user}\))?
```

Indeed, the src_ip & dst_ip are different if the direction is inbound or outbound.

You will need to update the Logstash Cookbook page for Cisco ASA too, because we replace the pattern CISCOFW302020_302021 by two patterns (CISCOFW302020_302021_1 and CISCOFW302020_302021_2).

**Comment by untergeek** [comment]
@GregMefford @stonith @dav3860 

Beginning with Logstash 1.5, the patterns are in their own repository, https://github.com/logstash-plugins/logstash-patterns-core

You can create issues and pull requests directly against the patterns repo now.  The resulting patterns ruby gem will be versioned with semver, allowing users to revert to an earlier build, should something go wrong.

We can migrate PRs to the new repo, but not issues.  If you're willing to take a look at this, would you consider making a PR for the proposed changes?

**Comment by untergeek** [comment]
By the way, this means that updating your patterns (in 1.5) will be as easy as:
```
bin/plugin install logstash-patterns-core
```
and restarting Logstash.

**Comment by GregMefford** [comment]
Pretty neat! I'll try to take a look at getting this moved over to the new
repo.

~Greg Mefford

**Comment by purbon** [comment]
Got this moved to https://github.com/logstash-plugins/logstash-patterns-core/issues/46 as it really belogs nowadays to the patterns-core repo.

**Comment by purbon** [comment]
The PR https://github.com/elastic/logstash/pull/1383 was also moved to the patterns-core repo. closing this issue and moving all there.
