### ISSUE TITLE
Can't find a logstash image build from this repo

### ISSUE THREAD

**Issue by ikus060** [elastic/logstash#13815]
I'm looking for a docker image of logstash that contains all the required dependencies to build a logstash plugin.  The Dockerfile within this repo seams to contains all the required parts to mention `rubyUtils.gradle` file that is required for logstash java plugins.

The following docker images seams to be generated using another Dockerfile.
* logstash:8.0.0
* elastic/logstash:8.0.0

Here the question:
Where is the docker image generated from this repository ?

**Comment by yaauie** [comment]
We do not distribute a separate docker image for _building_ plugins; the docker images that we distribute contain _distribution_ artifacts, meant for running the Logstash program, as built by the tooling in this repo.
