### ISSUE TITLE
Central pipeline management scalability improvement

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#13868]
Logstash can be configured to retrieve the pipelines configurations from a central management cluster.

The actual implementation downloads from the remote `_logstash/pipelines` [endpoint]( https://www.elastic.co/guide/en/elasticsearch/reference/current/logstash-api-get-pipeline.html) the full list of pipelines and then keeps only the ones that match the `xpack.management.pipeline.id` option. This filtering, which involves also the application of the `*` start operator, is done completely on Logstash side, so if the central management contains many pipelines and only a small number of them match the criteria, then there is a waste.
The situation is even worst if there are many Logstash instances that pulls continuously from the remote endpoint, because generates a lot of traffic on the management cluster.

This issue is to request the implementation of filtering on the endpoint side, so that  Logstash can pass the list of pipeline ids (included the one with the star operator) and in response receives only the ones that match this criteria.

Related to: #12366

cc @roaksoax

**Comment by Veshialle** [comment]
I'm sure that could be hard to achieve.
Couldn't be usefull to create an hash for every pipeline and retrieve only the hashes (instead the pipeline wall of text) during the request to endpoint `_logstash/pipelines`, to check if there is any changes on it.
Then, only when the two hashes (local and remote) are different, retrieve the whole pipeline?

Thanks

**Comment by andsel** [comment]
Yes @Veshialle that would be a great improvement in terms of transferred bytes, but changes a little bit the flow. 
As a first step we could imagine to execute the filtering part on the Elasticsearc cluster side, which is quite similar to what's done today, in terms of calls. If we introduce the hash check, then the logic change a little bit, could considered a further improvement.
