### ISSUE TITLE
Logstash 6.8.23 debian package doesn't work with OpenJDK

### ISSUE THREAD

**Issue by dariosusman** [elastic/logstash#13876]
Greetings!

I've tried to install logstash 6.8.23 on Debian Bullseye with OpenJDK 17 but had the following issue:

```
# apt-get install logstash
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  logstash
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/179 MB of archives.
After this operation, 313 MB of additional disk space will be used.
Selecting previously unselected package logstash.
(Reading database ... 38782 files and directories currently installed.)
Preparing to unpack .../logstash_1%3a6.8.23-1_all.deb ...
Unpacking logstash (1:6.8.23-1) ...
Setting up logstash (1:6.8.23-1) ...
Using provided startup.options file: /etc/logstash/startup.options
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unable to install system startup script for Logstash.
chmod: cannot access '/etc/default/logstash': No such file or directory
dpkg: error processing package logstash (--configure):
 installed logstash package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 logstash
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Commenting out the GC options from /etc/logstash/jvm.options and running a `touch /etc/default/logstash` and finishing the install worked it around, but these should be resolved on package install. Not afterwards.

```
# java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Debian-1deb11u1, mixed mode, sharing)
# cat /etc/debian_version 
11.2
```

**Comment by yaauie** [comment]
Logstash 6.8 works exclusively with Java 8 and Java 11.

**Comment by yaauie** [comment]
The Logstash 6.8 docs call out that it works exclusively with Java 8 and Java 11.

> NOTE: Logstash requires Java 8 or Java 11.
> -- [Installing Logstash – 6.8](https://www.elastic.co/guide/en/logstash/6.8/installing-logstash.html)

In this particular case, an option present in the `config/jvm.options` for Logstash 6.8 is not compatible with Java 17 and prevents the JVM from starting up; when Logstash 6.8 was released in May of 2019, Java 11 was the current LTS and its config JVM options were tailor fit for the available and supported Java versions. In subsequent Java releases, some of the features Logstash relies on have been removed.

While this _particular_ issue may be resolved by modifying the `config/jvm.options` to not use garbage collector configuration that is unavailable on modern Java 17, the Logstash 6.8 series has not been tested on unsupported JVMs and the behaviour is unverified.
