### ISSUE TITLE
Trying to parse cloudtrail logs using logstash 1.4.1

### ISSUE THREAD

**Issue by marianogg9** [elastic/logstash#1390]
Hi guys.

Just need a little help in getting this working. Here's my config file and output when I try to run it: https://gist.github.com/marianogg9/4ce7f551a0109076b3d4

It gets stuck and won't do anything else. Is there any way to debug this? any other way of getting info of what it's doing?

Thanks!

**Comment by vhdevera** [comment]
Hi untergeek!
i'm trying to configure logstash a locally stored (just for testing) cloudtrail file but couldn't make it work.  Do you have any link that I can follow for this configuration?
