### ISSUE TITLE
Environment variable not considered in logstash filter pipeline.

### ISSUE THREAD

**Issue by mominmaaz** [elastic/logstash#13992]
I am running logstash(sebp/elk) in docker. The below mentioned configuration is unable to use environmental variable 'MYVAL'. I am adding environment parameter in docker-compose.yml. 

30-output.conf located under /etc/logstash/conf.d
```
input {
  elasticsearch{
    ...
  }
}

filter {
  if ![my_field] {
    mutate {
      replace => { "my_field" => "${MYVAL:default-value}" }
    }
  }
}

output {
  elasticsearch {
    ...
  }
  stdout {
    codec => rubydebug {metadata => true}
  }
}
```

**Comment by yaauie** [comment]
I cannot reproduce this with vanilla Logstash 7.17.3 or 8.1.2. When the environment variable is set it is used, and otherwise the field is correctly populated with the default `default-value`.

Can you provide more details about your configuration, and how you are expecting the environment variable to flow through to the container?

**Comment by mominmaaz** [comment]
I am using 7.16.2. I am using this sebp/elk image in docker compose and passing environment variable file.
When printing the environment in running container, I can see that environment exist.

**Comment by yaauie** [comment]
We are not the maintainers of `sebp/elk` image. You may need to reach out to the maintainer directly.

**Comment by mominmaaz** [comment]
Yes I have created a similar ticket there https://github.com/spujadas/elk-docker/issues/366#issue-1202785965. I was looking in his Docker file and found that the image copies the configuration file in etc/logstash/conf.d folder. The while pipeline works nicely except for this environment part.

**Comment by mominmaaz** [comment]
This question has been answered by the image owner https://github.com/spujadas/elk-docker/issues/366
