### ISSUE TITLE
When assembling the source, plugin_aliased_hashed will not be updated. 

### ISSUE THREAD

**Issue by mashhurs** [elastic/logstash#14003]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
- `8.3.0`
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
- `local`
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
- we dont need to run Logstash
**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`): JDK 17

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `LS_JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Update `AliasRegistry.yml` file
 2. Run the `assemble` gradle job
 3. Check the `plugin_aliased_hashed.yml` file under the build folder that is old.
 
### Acceptance Criteria
- Alias related test cases should remove checksum file before running the tests.
- When assembling the Logstash source gradle job should remove the checksum value.

**Comment by yaauie** [comment]
I think that it may be a bit simper than that. I think we can simply hook the gradle task that has the hashed file as output and disable caching so that it always runs even if the target exists, or in a pinch we could delete the cached file before the task is invoked.

**Comment by andsel** [comment]
Gradle build cache should trigger the copy of the `AliasRegistry.yml` into `plugin_aliased_hashed.yml` because the task `SignAliasDefinitionsTask` uses  as input the plain file https://github.com/elastic/logstash/blob/09aa7a1aaca92bc43d3e089096a73c3ce62cbe7b/build.gradle#L218

Looking at task tree with
```
./gradlew :logstash-core:assemble taskTree --repeat
```
`assemble` should trigger the execution of the `markAliasDefinitions` , maybe there is a bug in the task of in the use of the cache done bu the task.
