### ISSUE TITLE
Generated input plugin encounters NoClassDefFoundError

### ISSUE THREAD

**Issue by seanstory** [elastic/logstash#14203]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`) : *8.3.0-SNAPSHOT (`main`) and 8.2.0*
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker): *built from source (8.3.0-SNAPSHOT) and dowloaded MacOS tar.gz (8.2.0)*
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes): *command line*

**Plugins installed**: (`bin/logstash-plugin list --verbose`) N.A.

**JVM** (e.g. `java -version`): 

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
  ```
  openjdk version "11.0.15" 2022-04-19
  OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
  OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
  ```
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc). : *homebrew*
3. Value of the `LS_JAVA_HOME` environment variable if set.: *unset*

**OS version** (`uname -a` if on a Unix-like system):
  ```
  Darwin Seans-MacBook-Pro-2.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
  ```

**Description of the problem including expected versus actual behavior**:

I generated an Input Plugin following [this documentation](https://www.elastic.co/guide/en/logstash/current/plugin-generator.html). When I then tried to follow the generated plugin's README and execute the tests, I hit:

<details><summary>this error</summary>

```
Seans-MacBook-Pro-2:logstash-input-confluence_cloud seanstory$ bundle exec rspec
/opt/homebrew/Cellar/rbenv/1.2.0/versions/jruby-9.3.3.0/lib/ruby/gems/shared/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:476: warning: constant ::Fixnum is deprecated
/opt/homebrew/Cellar/rbenv/1.2.0/versions/jruby-9.3.3.0/lib/ruby/gems/shared/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:480: warning: constant ::Fixnum is deprecated
/opt/homebrew/Cellar/rbenv/1.2.0/versions/jruby-9.3.3.0/lib/ruby/gems/shared/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:503: warning: constant ::Fixnum is deprecated
/opt/homebrew/Cellar/rbenv/1.2.0/versions/jruby-9.3.3.0/lib/ruby/gems/shared/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:507: warning: constant ::Fixnum is deprecated

An error occurred while loading ./spec/inputs/confluence_cloud_spec.rb.
Hint: Install the `did_you_mean` gem in order to provide suggestions for similarly named files.
Failure/Error: require "logstash/devutils/rspec/spec_helper"

LoadError:
  load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/jruby/util/io/FileExistsException
# ./spec/inputs/confluence_cloud_spec.rb:2:in `<main>'
# ------------------
# --- Caused by: ---
# Java::JavaLang::ClassNotFoundException:
#   org.jruby.util.io.FileExistsException
#   java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
No examples found.


Finished in 0.00026 seconds (files took 0.69981 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

</details>

**Steps to reproduce**:

 1. run `bin/logstash-plugin generate --type input --name xkcd --path ~/ws/elastic/plugins`
 2. cd into the generated plugin dir
 3. run `bundle install && bundle exec rspec`
 4. see the failure

**Workaround**:

interacting with some logstash team members (CC @robbavey @andsel) we found that the critical missing pieces were:
* referencing the local logstash checkout or install in the plugin's Gemfile, like:
```
logstash_path = ENV['LOGSTASH_PATH'] || 'path/to/local/logstash'
use_logstash_source = ENV['LOGSTASH_SOURCE'] && ENV['LOGSTASH_SOURCE'].to_s == '1'

if Dir.exist?(logstash_path) && use_logstash_source
  gem 'logstash-core', :path => "#{logstash_path}/logstash-core"
  gem 'logstash-core-plugin-api', :path => "#{logstash_path}/logstash-core-plugin-api"
end
```
* if using a local checkout of source, running `./gradlew clean bootstrap assemble installDefaultGems` to build it
* utilizing the same JRuby version as the local logstash (`java -cp path/to/local/logstash/vendor/jruby/lib/jruby.jar org.jruby.Main -v`)

**Comment by andsel** [comment]
Pointing `LOGSTASH_PATH` to a local copy of Logstash and setting `LOGSTASH_SOURCE` is the intended way to develop the plugins because the `logstash-core` gem is not published since `5.6.0`.
The documentation and/or the generated `README.md` has to be fixed accordingly.

**Comment by seanstory** [comment]
Will both of those env vars work if they're pointed to a local download of Logstash, and not necessarily a local git clone? Asking because I'd originally generated my plugin scaffolding from an unpacked logstash tarball. It would be cool if I didn't need an extra step to clone logstash, too.

**Comment by andsel** [comment]
@seanstory 
> Will both of those env vars work if they're pointed to a local download of Logstash

yes, is works also with a tzr.gz Logstash's distribution

**Comment by seanstory** [comment]
Excellent!
@andsel I've put together [a PR that attempts to patch this](https://github.com/elastic/logstash/pull/14229), but my feelings will not be at all hurt if y'all would rather tackle this, or do it in a totally different way.

**Comment by memexesdasdssa** [comment]
. #14339
