### ISSUE TITLE
filterworker fails with 'can't add a new key into hash during iteration'

### ISSUE THREAD

**Issue by cwensel** [elastic/logstash#1428]
full trace:

Exception in filterworker {"exception"=>#<RuntimeError: can't add a new key into hash during iteration>, "backtrace"=>["org/jruby/RubyHash.java:986:in `[]='", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/util/accessors.rb:60:in `store_path'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:865:in `inject'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/util/accessors.rb:60:in `store_path'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/util/accessors.rb:55:in `lookup'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/util/accessors.rb:39:in `set'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/event.rb:138:in `[]='", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/filters/urldecode.rb:29:in `filter'", "org/jruby/RubyHash.java:1339:in `each'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/filters/urldecode.rb:28:in `filter'", "(eval):232:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/pipeline.rb:262:in `filter'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/pipeline.rb:203:in `filterworker'", "/Users/system/sandbox/logstash/logstash-1.4.1/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error, :file=>"logstash/pipeline.rb", :line=>"212"}

**Comment by ph** [comment]
Hello @cwensel, Sorry for taking so long to answer.
Could you attach your configuration and log if possible to reproduce this issue?

**Comment by jsvd** [comment]
@cwensel are you still seeing this problem?

**Comment by cwensel** [comment]
I've seen enough issues to have moved on at this point. sorry i'm not of much more help.

i can say it continued to be persistent through a 1.5 beta I believe.

**Comment by suyograo** [comment]
@cwensel sorry for having a bad experience. Unfortunately its hard to debug without a config and a sample log.. If you can attach it, please reopen this issue

**Comment by lephix** [comment]
Following is my configuration.

    input {
        file {
            path => "/data/logs/nginx/access.log"
            start_position => "beginning"
        }
    #    stdin{}
    }
    filter {
        grok {
            match => { "message" => "%{HOSTNAME:requestHost} - %{IPV4:requestIp} - %{NOTSPACE:requestRemoteUser} \[%{HTTPDATE:requestHttpDate}\] %{QS:requestUrl} %{NUMBER:requestHttpStatus:int} %{NUMBER:requestBodySentBytes:int} %{QS:requestHttpReferer} %{QS:requestHttpUserAgent} %{QS:requestHttpXForwaredFor} \"%{NUMBER:requestTime:float}\""}
        }
        date {
            match => ["requestHttpDate", "dd/MMM/yyyy:HH:mm:ss Z"]
        }
        kv {
            source => "requestUrl"
            field_split => "&? "
            trimkey => "_"
            trim => " "
        }
        mutate {
            convert => {
                "launch" => "integer"
                "screenDpi" => "float"
                "screenWidth" => "integer"
                "screenHeight" => "integer"
                "longitude" => "float"
                "latitude" => "float"
            }
        }
        urldecode {
            all_fields => true
        }
    }
    output {
        elasticsearch {
            protocol => "transport"
            cluster => "mc-es-ai"
            index => "logstash-busybox-%{+MM.dd}"
            host => ["10.162.65.105"]
        }
    #    stdout {
    #        codec => "json"
    #    }
    }

Following is the error message

    {:timestamp=>"2015-08-24T07:09:51.349000+0800", :message=>"Exception in filterworker", "exception"=>#<RuntimeError: can't add a new key into hash during iteration>, "backtrace"=>["org/jruby/RubyHash.java:991:in `[]='", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/util/accessors.rb:65:in `set'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/event.rb:146:in `[]='", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-1.0.0/lib/logstash/filters/urldecode.rb:36:in `filter'", "org/jruby/RubyHash.java:1341:in `each'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-1.0.0/lib/logstash/filters/urldecode.rb:36:in `filter'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:163:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:160:in `multi_filter'", "(eval):157:in `filter_func'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:157:in `start_filters'"], :level=>:error}

Following is a example of our Nginx log. Some of the sensitive infos are replaced.

    busybox.kakamobi.com - 39.71.227.1 - - [24/Aug/2015:09:00:12 +0800] "GET /api/open/box/list.htm?productId=1&protocol=2.2&_platform=android&_srv=t&_appName=xxx&_product=%E9%A9%BE%E8%80%83%E5%AE%9D%E5%85%B8&_vendor=xxx&_renyuan=xxx&_version=6.2.2&_system=KOT49H&_manufacturer=YuLong&_systemVersion=4.4.2&_device=Coolpad%208675-HD&_imei=xxx&_productCategory=xxx&_operator=M&_androidId=xxx&_mac=3c%3A91%3A57%3Aa2%3A9c%3Ab5&_appUser=xxx&_pkgName=com.xxx.xxx&_screenDpi=2.0&_screenWidth=720&_screenHeight=1280&_network=wifi&_launch=19&_webviewVersion=4.3&_firstTime=2015-06-11%2020%3A59%3A22&_userCity=123456&_p=5C46565957561C4550555C&_gpsType=baidu&_cityName=%E6%B5%8E%E5%8D%97%E5%B8%82&_cityCode=123456&_gpsCity=123456&_longitude=180.9733&_latitude=336.719&_ipCity=123456&_j=1.0&schoolName=%E6%B3%89%E6%97%BA%E9%A9%BE%E6%A0%A1&schoolCode=123456&sign=xxx HTTP/1.1" 200 3057 "-" "Mozilla/5.0 (Linux; Android 4.4.2; Coolpad 8675-HD Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36" "-" "0.059"

**Comment by colinsurprenant** [comment]
seems to be same issue as #3780 with the urlencode filter.
