### ISSUE TITLE
Wrong path in events from multiple logfiles (same name, different directories) specified by wildcards

### ISSUE THREAD

**Issue by stbka** [elastic/logstash#1435]
Hi folks,

I think I have found a bug. Please correct me if I am wrong.

logstash version is 1.4.1. Also affects at least 1.3.3.

In my case it occurs while observing multiple logfiles with the same name in different directories specified by multiple wildcards using a multiline filter.

Here is a little demonstration

My logstash.conf
```
input {

   file {
      type => "test"
      path => [ "/sw/logstash-multifile-test/DIR*/da*i" ]
      start_position => "beginning"
      stat_interval => 1

      # sincedb
      sincedb_path => "./.sincedb_test"
      sincedb_write_interval => 5

      # multiline-codec
      codec => multiline {
         pattern => "^~~~"
         negate => "true"
         what => "previous"
      }

   }

}

filter { }

output {
  stdout { codec => rubydebug }
}
```

This is my directory lineup:
```
DIR1:
total 8
drwxr-xr-x  2 sea GROUP 4096 Jun 12 16:01 .
drwxr-xr-x 10 sea GROUP 4096 Jun 12 16:37 ..
-rw-r--r--  1 sea GROUP 0 Jun 12 16:38 datei

DIR2:
total 8
drwxr-xr-x  2 sea GROUP 4096 Jun 12 16:01 .
drwxr-xr-x 10 sea GROUP 4096 Jun 12 16:37 ..
-rw-r--r--  1 sea GROUP 0 Jun 12 16:38 datei
```

This is my test script:
```
#!/bin/bash

for (( i=0; $i < 2; i++ )) ; do

   echo "~~~" >> DIR1/datei
   echo "~~~" >> DIR2/datei

   echo "1-$i" >> DIR1/datei
   echo "2-$i" >> DIR2/datei

done
```
Log events with a leading 1 are always written to DIR1/datei, log events with a leading 2 are always written to DIR2/datei.

And this is what happens when I start the script:
```
Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.1/plugin-milestones {:level=>:warn}
{
    "@timestamp" => "2014-06-12T14:44:02.472Z",
       "message" => "~~~\n2-0",
      "@version" => "1",
          "tags" => [
        [0] "multiline"
    ],
          "type" => "test",
          "host" => "host",
          "path" => "/sw/logstash-multifile-test/DIR2/datei"
}
{
    "@timestamp" => "2014-06-12T14:44:02.476Z",
       "message" => "~~~\n2-1",
      "@version" => "1",
          "tags" => [
        [0] "multiline"
    ],
          "type" => "test",
          "host" => "host",
          "path" => "/sw/logstash-multifile-test/DIR1/datei"
}
{
    "@timestamp" => "2014-06-12T14:44:02.481Z",
       "message" => "~~~\n1-0",
      "@version" => "1",
          "tags" => [
        [0] "multiline"
    ],
          "type" => "test",
          "host" => "host",
          "path" => "/sw/logstash-multifile-test/DIR1/datei"
}
```
A log event with a leading 2 is obviously catched in the DIR1 directory - see second event in the output. But this is impossible. In the logfiles itself the entries are stored correctly.

Another issue is that last entry, which is missing. Is there something new up to now like a timer or something like that after which the event is parsed if nothing new happens to the logfile?
Ususally this is a per logfile issue. Curiously in this demonstration it is a per file plugin issue.

Thomas

**Comment by jordansissel** [comment]
Just posting an update - This is still on the todo list to fix.

**Comment by miguno** [comment]
Unfortunately it looks as if the workaround of switching from a multiline codec to a multiline filter does not solve the problem either.  In our case we're still seeing data from file A being merged into (or replacing) the event message for file B.

**Comment by miguno** [comment]
I tried the equivalents of:

```
# Variant 1 (multiline codec)
input {
  file {
    path => [ ... ]
    codec => multiline {
      pattern => "^%{TIMESTAMP_ISO8601} "
      negate => true
      what => "previous"
    }
    type => "foo"
  }
}
...
```

and

```
# Variant 2 (multiline filter with conditional)
input {
  file {
    path => [ ... ]
    type => "foo"
  }
}
filter {
  if [type] == "foo" {
    multiline {
      pattern => "^%{TIMESTAMP_ISO8601} "
      what => "previous"
  }
}
...
```

and

# Variant 3 (multiline filter with deprecated "type" parameter)
input {
  file {
    path => [ ... ]
    type => "foo"
  }
}
filter {
  multiline {
    type => "foo"
    pattern => "^%{TIMESTAMP_ISO8601} "
    what => "previous"
  }
}
...

```

**Comment by jordansissel** [comment]
Let's track discussion on one ticket. I'll close this one in favor of https://github.com/logstash-plugins/logstash-input-file/issues/10
