### ISSUE TITLE
unable to start when queue page size over 2147483648

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#14388]
Logstash fail to start when the page size is too high

**Step to reproduce**
logstash.yml
```
queue.page_capacity: 2048mb
```

**Log**
```
[org.logstash.execution.AbstractPipelineExt] Logstash failed to create queue.
org.jruby.exceptions.RangeError: (RangeError) integer 2147483648 too big to convert to `int'
```

**Comment by pedrosk** [comment]
The issue started with error "page file too small:
```
[2022-07-28T09:18:05,273][ERROR][org.logstash.execution.AbstractPipelineExt] Logstash failed to create queue.
java.io.IOException: Page file size is too small to hold elements
```

They increased the page file from 1058mb to 2048mb

The logstash config file:

[logstash.yml.txt](https://github.com/elastic/logstash/files/9213615/logstash.yml.txt)

Relevant config that triggered it
```
path.queue: /app/etss_data/data/logstash/persisted-queues
queue.max_bytes: 4096mb
queue.page_capacity: 2048mb
```

This cause the error:
```
[org.logstash.execution.AbstractPipelineExt] Logstash failed to create queue.
org.jruby.exceptions.RangeError: (RangeError) integer 2147483648 too big to convert to `int'
```

The full log can be found here:
[logstash.log.txt](https://github.com/elastic/logstash/files/9213619/logstash.log.txt)

Hope this helps.

Ed

**Comment by kaisecheng** [comment]
There is a size limitation in MappedByteBuffer.
[FileChannel.map()](https://docs.oracle.com/javase/9/docs/api/java/nio/channels/FileChannel.html#map-java.nio.channels.FileChannel.MapMode-long-long-)
size - The size of the region to be mapped; must be non-negative and no greater than Integer.MAX_VALUE
This issue wouldn't be fixed. An action item is to write max page capacity limit in doc
