### ISSUE TITLE
init script should kill LS if it fails to stop in time

### ISSUE THREAD

**Issue by electrical** [elastic/logstash#1445]
https://github.com/elasticsearch/logstash/blob/master/pkg/logstash.sysv#L73-L91

At the moment we just exit if LS doesn't exit on time or not at all.
We might want to send a -KILL after a while?

**Comment by jordansissel** [comment]
I'm on the fence. Forced termination by default on a "please shutdown" request will cause us to lose events (right now).

Once @colinsurprenant's persistent queue stuff lands I"ll be more comfortable with this.

**Comment by jsvd** [comment]
closing this, forced exit should not be done in the init script as it can result in loss of data as @jordansissel said. it's also consistent with how other projects behave, namely elasticsearch
