### ISSUE TITLE
[spacetime] A better logstash-to-logstash experience

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#14477]
This is a stub issue meant to capture the work of _designing_ a logstash-to-logstash experience that is:
 - simple to define in the simple cases (like the `pipeline` to `pipeline` config)
 - handles a variety of security requirements, including:
   - none/cleartext
   - privacy only (TLS with certificate validation disabled)
   - TLS without auth
   - TLS with Basic Auth
 - high throughput, failure-tolerant, and load-balanceable (akin to http output with `format => json_batch` and `retry_non_idempotent => true` -> http input)

Ideally, the sending Logstash would be able to negotiate with the receiving Logstash regarding capabilities, so that we could provide a simple `logstash` input/output pair, and the user would not need to care much about implementation details. This could be implemented in Logstash core (API path connecting directly to pipeline bus?), or as separately-installed plugins (that could themselves instantiate and manage instances of properly-configured http input/output plugins).

**Comment by yaauie** [comment]
Rough notes from the `{ON}week` exploration:

## Useful Boundary

We can produce a gradual path forward by introducing a `logstash` input/output pair that transparently _wraps_ their tried-and-tested `http` input/output counterparts, abstracting away much of their implementation details and _eventually_ allows sending data directly to an API-provided data-path _with minimal configuration changes_. Both the input and output plugins will use the local Logstash's `api.ssl` for sensible defaults for securing the HTTP layer; the input plugin will use `api.auth` for its own sensible defaults and will initially require a `port` to be specified. The output will be sent to a non-configurable URI that is forward-compatible with a future effort to have an in-API data path complete with a "virtual address" similar to the pipeline-to-pipeline flow.

Thus, on a Logstash with a secured API, sending data using the same security becomes as simple as:

~~~
output {
  logstash {
    host => "downstream.local"
    port => 9987
  }
}
~~~

And securely receiving data on an API-secured Logstash becomes:

~~~
input {
  logstash {
    port => 9987
  }
}
~~~

 - The input plugin will need to be able to _handle_ an `Expect: 100-Continue` flow, even if it is a no-op and always sends the `100 Continue` status when it is expected without doing any actual checks.
 - The input/output will need to support the full gamut of `ssl_` config that are supported by the API, using the values provided by `api.ssl` and `api.auth` as sensible defaults _that can be overridden_. We want users to be able to define this once instead of having the same config repeated for each pipeline, and since API data-path is the eventual future, relying on it for defaults provides a transition path.

## Batch-centric queueing

Currently, back-pressure from the queue occurs at the _event_ level, so it is both possible and likely for a partial batch to be persisted without back-pressure only to get blocked while pushing the Nth item. We can greatly reduce the likelihood of partial-batch blocking by guarding inserts with a queue capacity tracker, and only pushing to the actual queue if the capacity tracker can allocate the capacity for us. For example, if we have a memory queue that can hold 125*8 = 1000 events, we can create a data-structure that blocks for a configurable maximum amount of time while allocating "tickets" from a pool and errors appropriately if an insufficient quantity of tickets can be acquired in the allotted time _before_ inserting into the queue. Our queue guard could then "require" an unexpired ticket to insert events into the queue, and can re-issue tickets to the pool when events are popped by the workers. Using the existing `batch_push` method would transparently allocate tickets and instantly use them.

 - The output _should_ begin sending `X-Logstash-EventCount` header with the quantity of events
 - The input _may_ use a provided `X-Logstash-EventCount` to pre-reject batches with `429`'s that would not succeed or to send `100 Continue` when tickets could be acquired. This feature may or may not be implemented in the wrapped-`http`-input, or may be constrained to the API data-path implementation.

## API data-path

When we introduce an API data-path, sending data to it should be virtually indistinguishable to a user who is using any existing version of the `logstash` output plugin specified in this effort, _except_ the `port` is no longer a required in the output's configuration and the local `api.http.port` is used as a sensible default. By default, the output plugin _should_ send `Expect: 100-Continue` and wait until a `100 Continue` is received to transmit data.

A `logstash` input plugin that is run on a Logstash that provides an API data-path no longer requires a `port`, and when a port is omitted a user _must_ specify a virtual address and can no longer specify SSL/TLS/auth params so that we can bind to the API's data-path instead of spawning our own HTTP server.

Thus, on a Logstash with a secured API, sending data to a Logstash that is using the API data-path becomes:

~~~ diff
 output {
   logstash {
     host => "downstream.local"
-    port => 9987
+    path => "my_pipeline"
   }
 }
~~~

And securely receiving data on an API-secured Logstash becomes:

~~~ diff
 input {
   logstash {
-    port => 9987
+   path => "my_pipeline"
   }
 }
~~~

**Comment by mbudge** [comment]
Please don't set the headers field like the http input plugin.

We can drop the headers field at logstash, but can't prevent it clashing from any raw events which might contain the headers fields(s).
