### ISSUE TITLE
I reported a security issue in July 2021

### ISSUE THREAD

**Issue by yuanjunxiaoli** [elastic/logstash#14490]
I reported a security issue in July 2021 to email security@elastic.co. Why didn't you respond?

**Comment by jsvd** [comment]
hi @yuanjunxiaoli apologies for the lack of response, I'll get a response back to you asap.

**Comment by yuanjunxiaoli** [comment]
> 
Thank you.

**Comment by jsvd** [comment]
@yuanjunxiaoli we're having trouble locating your report using your github username as a lead. Can you provide the email it was sent from, or just resend the report again (if you don't want to paste your email here)?
Thanks.

**Comment by yuanjunxiaoli** [comment]
> @yuanjunxiaoli we're having trouble locating your report using your github username as a lead. Can you provide the email it was sent from, or just resend the report again (if you don't want to paste your email here)? Thanks.

My email address is worker_hard@163.com

**Comment by jsvd** [comment]
We couldn't find any reports from that email, please resend the report and we'll get back to you. Closing now.

**Comment by yuanjunxiaoli** [comment]
> We couldn't find any reports from that email, please resend the report and we'll get back to you. Closing now.

I just re-sent the report to your email security@elastic.co from worker_hard@163.com
