### ISSUE TITLE
RFC: Exposing timers as first-class metric

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#14544]
## Problem Statement

As we introduce rate-of-flow metrics (https://github.com/elastic/logstash/issues/14463), the current practice of overloading of counter metrics to act as timers (by incrementing them after the tracked execution has completed) prevents us from accurately accounting for in-progress execution. This in turn gives us the _least_ visibility when we need it _most_.

For example, a grok filter handling input that is reliably causing it to time-out with the default 30s per match, handling the default batch size of 125, can go ~62.5 _minutes_ without incrementing the relevant metrics about its execution time. If all of a pipeline's workers are in this state, its `worker_concurrency` can report 0, _despite all workers being fully-occupied_.

Similarly, a pipeline whose inputs are _entirely_ blocked pushing events into the queue will not report time spent in _queue-push-wait_ until _after_ the batches that are blocked have been accepted (which for a fully-stalled pipeline may be _never_). If all of a pipelines inputs are entirely blocked, its `queue_backpressure` can report a current rate of 0, _despite all inputs being fully-blocked_.

## Scope and Goals

I would like to propose adding timers as a first-class metric, so that we can provide an implementation that at accounts for in-flight long-running execution. This metric-type should be easily acquirable by code in Logstash core, and also from plugins using either the Ruby- or Java-Plugin APIs. We would migrate our existing internal timers transparently to use this new metric type, and maintainers of plugins would be free to migrate their own if/when they decided it was valuable to do so.

_This work is _related to_ but _independent of_ the work separately defined in #14463._

## Design

A phased approach would look like:
1) establish a new boundary, which executes a provided block/function and transparently reports the execution time
2) migrate existing timer-type metrics to this boundary
3)
   - a. expose boundary to Java plugins
   - b. implement live-timers as an opt-in implementation of that boundary

### Establishing a Boundary

Because a _part_ of this would be exposed via the Java interface, I believe we need to start there.

Proposed public interface, as exposed via `co.elastic.logstash.api`, that is either capable of timing the execution of a block of code, or reporting untracked execution. This is intentionally a write-only interface that provides a way to track fully-managed execution and a way to report unmanaged timings. API Documentation should encourage a user to prefer the use of the fully-managed execution timer.

~~~ java
package co.elastic.logstash.api

interface TimerMetric {
    <T, E extends Throwable> T time(Timeable<T, E> timeable) throws E;

    default void time(final Runnable runnable) {
        this.time(Timeable.of(runnable));
    };

    void reportUntrackedMillis(final long untrackedMillis);

    @FunctionalInterface
    interface Timeable<T,E extends Throwable> {
        T execute() throws E;
    
        static Timeable<Void,RuntimeException> of(final Runnable runnable) {
            return () -> { runnable.run(); return null; };
        }
    }
}
~~~

The _internal_ interface would need to extend this public write-only interface to provide read-access to the current value, and would likely need to extend `Metric<Long>` or similar:

~~~ java
package org.logstash.instrument.metrics

interface TimerMetric extends co.elastic.logstash.api.TimerMetric extends Metric<Long> {
    Long getValue();
}
~~~

We would then provide a simple implementation that tracks post-commits execution time:

~~~ java
package org.logstash.instrument.metrics

import static co.elastic.logstash.api.TimerMetric.Timeable

public class PostCommitTimerMetric implements TimerMetric {
    private final LongAdder longAdder = new LongAdder();

    @Override
    public <T, E extends Throwable> T time(Timeable<T, E> timeable) throws E {
        final long startNanos = System.nanoTime();
        try {
            return timeable.execute();
        } finally {
            final long durationNanos = System.nanoTime() - startNanos;
            this.reportUntrackedMillis(TimeUnit.MILLISECONDS.ofNanos(durationNanos));
        }
    }
    @Override
    public void reportUntrackedMillis(final long untrackedMillis) {
        this.longAdder.increment(untrackedMillis);
    }

    @Override
    public Long getValue() {
        return this.longAdder.sum()
    }
}
~~~

This simple implementation is _net-zero-change_ from our current behavior of reporting execution time after it has completed, and does not yet solve our initial problem, but is a necessary part of establishing a boundary.

### Migrating existing internal timers

Our `AbstractNamespacedMetric` and its implementations would need to be migrated:
 - add `getTimer`, which returns an instance of our internal-API `TimerMetric`
 - modify `doTime` to route through `TimerMetric#time(Timeable)`
 - modify `reportTime` to route through `TimerMetric#reportUntrackedMillis(Timeable)`
 - modify all _direct_ internal usage of counters being used for tracking execution time to instead use the above APIs
   
   NOTE: `org.logstash.instrument.metrics.TimerMetric` may need to be extended to handle current code-shape. As explored in https://github.com/elastic/logstash/pull/14519, many of our internal timer usages store their execution start-time out-of-band, and then retrieve it when finishing the execution to directly increment a _counter_ (not using the above-mentioned `reportTime`). I would _like_ to migrate to `TimerMetric#time` (since doing so allows us to track live execution in the future), but refactoring all of them _may_ be too large of a scope to handle all at once.
   
   One approach would be to extend our _internal_ interface to introduce a way to retrieve a committer-object from the timer, which a consumer _MUST_ commit upon completion of execution. This is _very_ risky, as we would have no compile-time guarantees that consumers of this API properly committed the executions that they began. This would _NOT_ be discoverable with the post-commit implementation described above, as abandoned executions would simply never increment the underlying counter, but would be quite problematic when later implementing live-tracking timers.
   
   Such an approach would look like:
   
   ~~~ diff
    package org.logstash.instrument.metrics
    
    interface TimerMetric extends co.elastic.logstash.api.TimerMetric extends Metric<Long> {
        Long getValue();
    
   +    Committer beginTrackedExecution();
   +    interface Committer {
   +        long commit();
   +    }
    }
   ~~~

### Exposing timer API to Java plugins

We would need to introduce a way to acquire a timer by its metric path, for both the Ruby- and Java-Plugin APIs. This is largely trivial and would mirror the way they both currently allow a consumer to get a counter.

 - On the Java side, this would involve adding methods to `co.elastic.logstash.api.NamespacedMetric` that expose our `co.elastic.logstash.api.TimerMetric`.
 - On the Ruby side, we _should_ largely get `AbstractNamespacedMetric#getTimer` introduced above for-free

### Implementing live-tracking timers

A spike for a highly-performant non-blocking, concurrency-safe live-timer is available in my [`{ON}week` spike](https://github.com/elastic/logstash/pull/14519/files#diff-b6910e247bd35bb5879b13d36ed1d44cd7626d5ae18d91de61c0481e5bdb91cb). Live-tracking would need to fully implement the _internal_ 
`org.logstash.instrument.metrics.TimerMetric` as described and expanded above, and should be made available in phases in order to reduce risk to our users:

1. opt-in
2. opt-out (requires performance validation)
3. only option (requires telemetry indicating very few users are opting out, deprecation and significant advance notice)

**Comment by andsel** [comment]
@yaauie great description, about your concert on the `Committer` internal class
> One approach would be to extend our internal interface to introduce a way to retrieve a committer-object from the timer, which a consumer MUST commit upon completion of execution. This is very risky, as we would have no compile-time guarantees that consumers of this API properly committed the executions that they began

If that class would implement `Autoclosable`, where many IDE could help identify the use away from the template like:
```java
try (Committer committer = timer.beginTrackedExecution()) {
  // do the task that has to be measured
}
```

Do you think it would help? Maybe I'm missing some inner aspects of the live-tracking timers, where the above pattern isn't simply applicable.

**Comment by yaauie** [comment]
On the committer and `AutoCloseable`:

I tried in my spike PR, and ended up making it _not_ implement `AutoCloseable`. 

In any scope where we can add a try-with-resources block, it would be trivial to instead supply a closure to the timer which would provide substantially more safety. We would not be relying on an IDE's warnings about using `AutoCloseable` outside of a try-with-resources, but instead would have true compile-time safety. 

However, in my spike I discovered that essentially all of the places where providing a closure  to the timer is impossible without significant refactor, we can't use a try-with-resources either and so we end up having to silence warnings about `Autocloseable` anyway (e.g., timers started and stashed by thread id in  `QueueReadClientBase#startMetrics` and acquired separately in `QueueReadClientBase#closeBatch` [[link](https://github.com/elastic/logstash/pull/14519/files#diff-45138dd8f27c00c367d18670a81cb76f586e4e55b4047a988a25137250c689afL131-L200)], or the `MetricExt#doTime`'s `ExecutionTimer` can be re-implemented in terms of an `AutoCloseable` committer , but that committer itself can't be try-with-resources'd either [[link](https://github.com/elastic/logstash/pull/14519/files#diff-fd718af85748a04cbd369f4ff3acde67f6a940c30d6208ec410653816b8d55aaR162)]).

I'm open to refactoring both of these areas as a part of this effort to make it practical to either perform a try-with-resources or provide a closure, and feel that _may_ be the safer route overall. The above comments were meant to highlight this complexity and to quantify the risk of scope growth.

**Comment by yaauie** [comment]
> The sooner we have users running Logstash with these metrics the better diagnostics we'll have and easier time solving user and customer issues.

I whole-heartedly agree and am +1 for skipping the opt-in phase, if at all possible.

But if the release train is leaving the proverbial station before we have fully completed performance validation, shipping live-tracking as opt-in provides more value than waiting to ship anything until the next minor. Keeping this as opt-in for initial delivery adds almost zero overhead and decouples merging an implementation from committing to it being the _primary_ implementation (even as we hope to do so in the same minor).

**Comment by yaauie** [comment]
This RFC and its commentary have been consolidated into a specification https://github.com/elastic/logstash/issues/14675
