### ISSUE TITLE
Kubernetes Guidelines Documentation - Setting Up - Document Sizing and Scaling Logstash in Kubernetes

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14579]
- [ ] Sizing and scaling Logstash in Kubernetes
      - [ ] Logstash and pod memory settings, including JVM config
      - [x] Sizing PQ and DLQ

**Comment by roaksoax** [comment]
Logstash on Kubernetes support is driven by Logstash on ECK. As such, I'm closing this issue in favor of https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-logstash.html
