### ISSUE TITLE
Kubernetes Guidelines Documentation - Setting Up - Document Logstash Plugins and Architecture Guide

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14578]
- [ ] Logstash plugins and Kubernetes architecture guide
      - [ ] Plugins and scaling concerns
        - [ ] Overview of the different types of plugins and how they impact Kubernetes scaling
        - [ ] Sections on how to configure/architect different classes of plugins
          - [ ] Pull based plugins that can autoscale by tracking work done externally to logstash (eg kafka, azure event hubs in certain configurations)
          - [ ] Push based plugins that can autoscale (beats, http)
          - [ ] Pull based plugins that cannot autoscale due to `sincedb`, or no automatic way to distribute work (eg jdbc, s3)
          - [ ] Plugins that require additional resources to be available to run (jdbc or jms requiring jars on classpath, for example

**Comment by roaksoax** [comment]
Logstash on Kubernetes support is driven by Logstash on ECK. As such, I'm closing this issue in favor of https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-logstash.html
