### ISSUE TITLE
Kubernetes Guidelines - Create Documentation structure

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14574]

**Comment by kilfoyle** [comment]
A basic [placeholder for the guide](https://www.elastic.co/guide/en/logstash-kubernetes/current/index.html) has been published. The guide shows up in the `Docs in Development` section of the [docs landing page](https://www.elastic.co/guide/index.html), and we have a `still in development` disclaimer at the top of every page so people will know that this is draft content. Instructions for building and updating the book are in the Logstash PR, below.

Logstash repo PR for the docs structure: https://github.com/elastic/logstash/pull/14532
Docs repo PR to add the guide to the docs build: https://github.com/elastic/docs/pull/2495
