### ISSUE TITLE
Kubernetes Guidelines Documentation - Operating Logstash - Logging

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14581]
- [ ] Logging
      - [ ] Viewing logstash logs 
      - [ ] Filebeat(?)

**Comment by roaksoax** [comment]
Logstash on Kubernetes support is driven by Logstash on ECK. As such, I'm closing this issue in favor of https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-logstash.html
