### ISSUE TITLE
Kubernetes Guidelines Documentation - Operating Logstash - Upgrading

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#14582]
- [ ] Upgrading
    - [ ] Pitfalls
    - [ ] Recommended best practices for upgrading a k8s logstash cluster

**Comment by roaksoax** [comment]
Logstash on Kubernetes support is driven by Logstash on ECK. As such, I'm closing this issue in favor of https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-logstash.html
