### ISSUE TITLE
discrepency between grok pattern TIMESTAMP_ISO8601 and ISO8601 in date filter

### ISSUE THREAD

**Issue by robin13** [elastic/logstash#1464]
I'm trying to import a log (elasticsearch incidentally...) which has a log format like this:

[2014-06-20 07:30:05,987][INFO ][snapshots                ] [es101] snapshot [backup:kibana-20140620073002] is done

This is my filter:

```
        grok {
            match => [
                "message", "\[%{TIMESTAMP_ISO8601:timestamp}\]\[%{DATA:level}\s*\]\[%{DATA:loggerName}\]\s*\[%{DATA:machineName}\] %{GREEDYDATA:message}"
            ]
            overwrite => [ "message" ]
        }

        date {
            match => [ "timestamp", "ISO8601" ]
            remove_field => [ "timestamp" ]
        }
```

The grok matches the timestamp, but the date filter does not...

I can make it work by replacing the date filter with this:

```
        date {
            match => [ "timestamp", "yyyy-MM-dd HH:mm:ss,SSS" ]
            remove_field => [ "timestamp" ]
        }
```

Seems that these could/should be homogeneous...

Cheers!
-Robin-

**Comment by Vlad777** [comment]
Seems the pattern accepts a comma separator before fractions of a second, but ISO1806 match does not. Had to explicitly use "YYYY-MM-dd HH:mm:ss,SSS" as my match.

**Comment by rawbertp** [comment]
Sorry, but why is this closed? The date filter still doesn't accept a comma between the time element and its fraction when using "ISO8601" (https://en.wikipedia.org/wiki/ISO_8601#cite_ref-15). Or are you saying the Yoda implementation is wrong and you can do nothing about this?

**Comment by wiibaa** [comment]
@rawbertp from a quick look to joda, it should be accepting either dot or comma but it enforces the use of 'T' and reject the space, please upvote https://github.com/logstash-plugins/logstash-filter-date/issues/32 and manually define your date pattern in the date filter configuration
