### ISSUE TITLE
Update Jackson version

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#14672]
Update `jackson` and `jackson-databind` to `2.13.4.1` or above.

**Comment by amaciejk** [comment]
watching

**Comment by babufrik-garage** [comment]
Can this be added in the next realase? It is cause of concern as it has severe vulnerabilites. !!!!

**Comment by amaciejk** [comment]
Looks like this needs bumps here:
https://github.com/guyboertje/jrjackson/blob/master/lib/jrjackson/build_info.rb#L16
https://github.com/guyboertje/jrjackson/blob/master/lib/jrjackson/build_info.rb#L20

Last PR to do the same was here: 
https://github.com/guyboertje/jrjackson/pull/87

**Comment by mashhurs** [comment]
`jrjackson` change PR is [here](https://github.com/guyboertje/jrjackson/pull/90) and we need to update `versions.yml` with followings once we release `jrjackson`.
```
jrjackson: 0.4.17
jackson: 2.14.1
jackson-databind: 2.14.1
```
