### ISSUE TITLE
Elasticsearch automatic alias creation

### ISSUE THREAD

**Issue by Jeppesen-io** [elastic/logstash#1467]
The ability to create an alias on index is creation (supported on ES 1.1x+). A limiting factor with Kibana is searching large number of indexes. Using aliases would allow to greatly reduce the size and number of HTTP POSTs and improve search time. Thanks

**Example logstash config**

```
  if [@delete_after] = "300"  {
    elasticsearch {
      host => "elasticsearch.local"
      index => "logstash-delete-after-300days-days-%{+YYYY.MM.dd}"

      #ADD THIS OPTION
      alias => "logstash-%{+YYYY.MM.dd}"

    }
  } else {
    elasticsearch {
      host => "elasticsearch.local"
      index => "logstash-delete-after-90-days-%{+YYYY.MM.dd}"

      #ADD THIS OPTION
     alias => "logstash-%{+YYYY.MM.dd}"
    }
  }
```

**Comment by palashkulsh** [comment]
@untergeek by any chance was this requirement/suggestion was brought to notice of  elasticsearch maintainers.
