### ISSUE TITLE
Bug: Lumberjack output & accents

### ISSUE THREAD

**Issue by renaudboutet** [elastic/logstash#1480]
Hi,

I am using a lumberjack output to communicate with a remote lumberjack input.
Everything worked fine until some accents got into the messages.

Version: 
1.4.2 on both side

My output configuration:
output { 
  lumberjack {
    codec => "json"
    hosts => "localhost"
    port => 5041
    ssl_certificate => ....
  }
}

My input configuration:
input{
  lumberjack {
      codec => "json"
      port => 5041
      ssl_certificate => ...
      ssl_key => ...
  }
}

When I write push "hello" with the client I get on the remove server:
{
         "message" => "hello",
        "@version" => "1",
      "@timestamp" => "2014-06-27T15:54:45.900+02:00",
            "type" => "stdin",
            "host" => "0.0.0.0"
}

Now if I push "héllo":
{
       "message" => "{\"message\":\"héllo\",\"@version\":\"1\",\"@timestamp\":\"2014-06-27T13:57:30.199Z\",\"host\":\"0.0.0.0\",",
      "@version" => "1",
    "@timestamp" => "2014-06-27T13:57:30.213Z"
}

You can notice that the last brackets is missing on the second message which makes it impossible to interpret it as a json object.

Thank you by advance!

**Comment by ph** [comment]
This is fixed in the 1.5.0RC2
