### ISSUE TITLE
Logstash and elasticsearch are not up

### ISSUE THREAD

**Issue by ihab-hachem** [elastic/logstash#14825]
I have a repo that contains logstash, filebeat, kibana, elasticsearch and a setup file. It is running and up on different servers using docker, but now i want to run it on another server, it shows that the build is successful but just filebeat is up elasticsearch and kibana are not and I got The following errors:
Logstash       error: open /usr/share/logstash/config/logstash.yml: permission denied
Elasticsearch  | Exception in thread "main" org.elasticsearch.common.settings.SettingsException: Failed to load settings from /usr/share/elasticsearch/config/elasticsearch.yml
Kibana         | FATAL CLI ERROR Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'

**Comment by yaauie** [comment]
Issues on this repository are for reporting confirmed bugs with clear and minimal reproduction steps, and for tracking our team's feature development work — they are not for general debugging or configuration conversations.

If you would like help debugging, please visit the [community forums](https://discuss.elastic.co/c/logstash) and open a new thread. When you do, please be sure to include _all_ relevant configuration, information about how Logstash was installed (package manager, tarball, source checkout), which plugins you are using, and a high-level description of what you _expect_ to be happening, what you _observe_ to be happening, and what you are attempting to accomplish.
