### ISSUE TITLE
Bump SnakeYaml in Logstash to 1.33

### ISSUE THREAD

**Issue by deepakLabs** [elastic/logstash#14843]
Logstash is currently using 1.30 this can be bumped to 1.33 in the newest release

The newer released snakeyaml comes with less vulnerabilities as it evident from the link below.
https://mvnrepository.com/artifact/org.yaml/snakeyaml/1.30

This will also aid organizations which are using logstash as it will be easier to approve new release with less vulnerabilities from security clearance point of view.

**Comment by deepakLabs** [comment]
@mashhurs @jsvd Can we upgrade the snakeYaml? mvn shows 1.30 is severely vulnerable.

**Comment by deepakLabs** [comment]
@jsvd @roaksoax @jordansissel @original-brownbear @fetep @robbavey @ph @suyograo @danhermann
Can you please look into it.

**Comment by mashhurs** [comment]
@deepakLabs My 15mins effort shows this should be easily solved by #14846 as compiling Logstash and running unit tests succeeded on my local. **_But_** if there is any _time consuming_ issue comes up, we should prioritize and deep dive.

**Comment by jsvd** [comment]
closed by https://github.com/elastic/logstash/pull/14563
