### ISSUE TITLE
[Doc] Document Guidance on sizing the PQ

### ISSUE THREAD

**Issue by roaksoax** [elastic/logstash#14871]
We need to provide a sizing guidance on how to size the PQ for the event of back pressure. For example:

```For example, if they receive 1000 eps and each event is 1kb, then every hour they receive 3.6gb. So if they need to tolerate one of the downstream components being down for 12h, they need a PQ of about 50GB in size.```

As such, the general guidance to size the PQ should be based by:

Total Events Size per second = EPS (Input) *  Size of Each Event
Total Received Per Hour = Total Event Size per second * 3600s
Tolerated Downtime = (Total Received Per Hour * X hours) * 1.10

**Comment by jsvd** [comment]
Here are a few findings on the bytes size of a raw message vs the corresponding serialized Logstash Event:

### Raw string message

| plaintext size (bytes) |	serialized logstash event size (bytes) | overhead (bytes) | overhead (%) |
| ---- | ---- | ---- | ---- |
| 11 | 213 | 202 | 1836% |
| 1212 | 1416 | 204 | 17% |

### JSON documents

| JSON document size (bytes) | serialized logstash event size (bytes) | overhead (bytes) |	overhead (%) |
| ---- | ---- | ---- | ---- |
| 947 | 1133 | 186 | 20% |
| 2707 | 3206 | 499 | 18% |
| 6751 | 7388 | 637 | 9% |
| 58901 | 59693 | 792 | 1% |

More at https://gist.github.com/jsvd/760e3c80cb67427485656202b6e3dadd
