### ISSUE TITLE
"RuntimeError Unknown frame type" using lumberjack input

### ISSUE THREAD

**Issue by OverlordAlex** [elastic/logstash#1488]
Using a lumberjack input, logstash (v1.4.2) crashes with the above runtime error (frame type 49). The crash is happening fairly regularly: on average, it crashes after receiving 5-15k events, which is about 20-30 seconds running time

This error is very similar to https://logstash.jira.com/browse/LOGSTASH-1851

The error reported on the lumberjack side is 
> Read error looking for ack: EOF

Stack trace from logstash:

RuntimeError: Unknown frame type: 49
  header (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:142
    feed at (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93
     run at (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:220
     run at (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:59

**Comment by surendranyl** [comment]
our logstash also crashing  with follwoing error 
RuntimeError: Unknown frame type: 0
  header at /prod/apps/elk/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:142
    feed at /prod/apps/elk/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93
     run at /prod/apps/elk/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:220
     run at /prod/apps/elk/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:59

**Comment by surendranyl** [comment]
any adjustments we should do to solve this error

**Comment by surendranyl** [comment]
seems this bug havent yet resolved

**Comment by untergeek** [comment]
LSF (Logstash Forwarder) 0.4.0 was released recently, and the lumberjack ruby gem was also updated around the same time.  It would be nice if those affected could retry with Logstash 1.5.0RC2

**Comment by jayeshpise** [comment]
@untergeek : Thanks for commenting on this. Is there any way i can apply the fix on top of logstash version 1.4.2 ? I am not comfortable using 1.5.0 (rc2) since there is no release version yet.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/16. Let's continue the discussion there! :)
