### ISSUE TITLE
Update compatibility matrix for JP page.

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/logstash#14895]
matrix_compatibility for logstash on Japanese page is having a blank. 
https://www.elastic.co/jp/support/matrix#matrix_compatibility

![image](https://user-images.githubusercontent.com/25199092/218348909-3696ab06-a2b0-4831-b067-84dea35e2074.png)

We do seem to have it filled for English page.
https://www.elastic.co/support/matrix#matrix_compatibility

![image](https://user-images.githubusercontent.com/25199092/218349110-fa48c922-d751-46fd-ab6a-bef7257a9d94.png)

**Comment by TomonoriSoejima** [comment]
pinging @sylvie777

**Comment by roaksoax** [comment]
Closing this issue as it seems fixed now.
