### ISSUE TITLE
lumberjack input causing logstash to crash

### ISSUE THREAD

**Issue by cjs226** [elastic/logstash#1489]
I'm trying to utilize logstash-forwarder/lumberjack but doing so is causing my logstash server to crash with the following:

{:timestamp=>"2014-07-01T01:49:04.731000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Lumberjack ssl_certificate=>\"/etc/logstash/certs/foo.pem\", ssl_key=>\"/etc/logstash/private/foo.key\", type=>\"lumberjack\", host=>\"0.0.0.0\">\n  Error: Bad file descriptor - Bad file descriptor", :level=>:error}
{:timestamp=>"2014-07-01T01:49:04.732000+0000", :message=>"Plugin is finished", :plugin=><LogStash::Inputs::Lumberjack ssl_certificate=>"/etc/logstash/certs/foo.pem", ssl_key=>"/etc/logstash/private/foo.key", type=>"lumberjack", host=>"0.0.0.0">, :level=>:info}

If I remove lumberjack from the input stanza logstash is stable.

I'm running Logstash v1.4.2 and attempting to use logstash-forwarder v0.3.1 on Ubuntu 12.04.

**Comment by HiteshG** [comment]
I am still seeing this issue, is this fixed?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/15. Let's continue the discussion there! :)
