### ISSUE TITLE
Add setting to http input plugin which disables logstash adding the headers field

### ISSUE THREAD

**Issue by mbudge** [elastic/logstash#14910]
Hi, 

Please add an option to the http input plugin so we can disable logstash adding the headers field. It's for when we use this plugin to do logstash to logstash communication. When using http input/output plugins for logstash to logstash communication, logstash is adding a headers object to all events. We can drop it, but can't stop it clashing with raw events.

Thanks,

Matthew

**Comment by roaksoax** [comment]
Hi @mbudge ,

Just to let you know that we have this issue on-roadmap, and we are hoping to solve it sometime in the shot-midterm

**Comment by roaksoax** [comment]
I'm going to go ahead and close this issue provided that we have introduced a new way to do Logstash to Logstash communication using `logstash-integration-logstash`. This new plugin provides the functionality for the use of a Logstash Input and Output and will be available by default in 8.11, effectively replacing the use of HTTP Input and HTTP Output.

This new plugin doesn't add metadata to the communication between LS instances. 

More information on https://github.com/elastic/logstash/issues/15163 and https://github.com/elastic/logstash/pull/15346
