### ISSUE TITLE
Bump SnakeYaml to 2.0

### ISSUE THREAD

**Issue by deepakLabs** [elastic/logstash#14944]
Please bump SnakeYaml to 2.0 as there are severe vulnerabilities with 1.33

**Comment by deepakLabs** [comment]
@jsvd @roaksoax @andsel

**Comment by andsel** [comment]
Thank you for your report.

Elastic's security reporting guidelines are available at https://www.elastic.co/community/security. Per those guidelines, all reports of potential security issues or vulnerabilities should be sent via email to [security@elastic.co](mailto:security@elastic.co)

We are unable to discuss potential issues of this nature here. Please send your report to the email address above, where it can be appropriately handled.

**Comment by roaksoax** [comment]
FWIW, I've closed this issue provided the above comment from @andsel.
