### ISSUE TITLE
Logstash udp size limit

### ISSUE THREAD

**Issue by bossy78** [elastic/logstash#1505]
I am monitoring my companies applications. They send their logs via an udp appender (log4net) and my logstash agent receives them via an udp input. Everything was working well: my logs were groked and  then stored in elasticsearch and displayed in kibana. Until today, I noticed that "big" logs where truncated, all the caracters after the 8151-th caracter are not displayed in the "message" field event, and so I am getting grokparsefailure. So basically, my question is the following : Does logstash have a limit size for each event/message received via udp, or more generally, via any input.

Thanks in advance, for your help.

**Comment by Redsandro** [comment]
I'm trying to get one xml file into logstash, but it keeps splitting up into pieces.

I've raised the 'limit' like so:

```
input {
	udp {
		port => 12203
		buffer_size => 16777216
	}
}
```

However, when I insert a file for testing like so:

```
cat 71_kb_file.xml | nc -uq8 -O100000 localhost 12203
```

I'm still getting 35 partials. Is `udp` not suitable for getting bigger XML logs across?

The `gelf` input seems to take huge logs fine, and it uses `udp` too. How can I make `udp` chain chunks together?

**Comment by Farfaday** [comment]
@Redsandro did you achieve that in the meantime ? I have a similar need.
Thanks!

**Comment by Redsandro** [comment]
@Farfaday I think the problem was using `nc` which caused buffering into chunks. Try it like this:

```
curl -H "content-type: text/xml" -XPUT 'http://localhost:12203' -d@71_kb_file.xml
```
