### ISSUE TITLE
tcp input connection threads tracking leak

### ISSUE THREAD

**Issue by dougmcclure** [elastic/logstash#1509]
Suspected TCP Input leak and/or overload condition.

This error message is returned gradually, increasing over time to a constant stream of this message.

"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Tcp type=>\"raw-syslog\", host=>\"0.0.0.0\", mode=>\"server\">\n  Error: closed stream", :level=>:error}

rsyslog --> haproxy --> four logstash instances (each with two TCP inputs) --> TCP output to a index/search product

jstack, netstat -na, lsof -i and lsof output as requested available here: https://gist.github.com/dougmcclure/c5badc31dae31a50d647

**Comment by mrmanc** [comment]
Hello. Awesome work here. I understand from reading that the conclusion was not that there was a memory leak, rather a build up of blocked filter threads caused by slow outputs (and a lack of back pressure to the input source). Is back pressure being implemented in 1.5.0?

**Comment by cold-gin** [comment]
Hello. I am seeing a memory leak with version v1.4.2 in logstash (and there's also a leak in v1.4.0 of Elasticsearch). In my particular case, I have 4 udp input sections (separate ports) which I am funnelling over to 2 output channels (elasticsearch & syslog). I am using:

wget https://download.elasticsearch.org/logstash/logstash/packages/debian/logstash_1.4.2-1-2c0f5a1_all.deb
wget https://download.elasticsearch.org/logstash/logstash/packages/debian/logstash-contrib_1.4.2-1-efd53ef_all.deb

What I am doing to observe the memory leak:

1. Start elasticsearch docker container
2. Start logstash docker container
3. Start logspout docker container
4. docker ps
5. docker inspect (elasticsearch, logstash container ids to get their pids)
6. top | grep <elasticsearch pid>
7. top | grep <logstash pid>

There is definitely a gradual memory leak in both containers when you observe the top output. Have all of the logstash input types been evaluated for memory leaks (not just tcp & lumberjack)?

**Comment by cold-gin** [comment]
Here's my config, which works correctly (port numbers have been removed):

# Logstash configuration

# Receive log input on different ports by environment
input {
  udp {
    port => ???
    type => "env1"
    tags => [ "env1" ]
  }
}

input {
  udp {
    port => ???
    type => "env2"
    tags => [ "env2" ]
  }
}

input {
  udp {
    port => ???
    type => "env3"
    tags => [ "env3" ]
  }
}

filter {
  if [type] == "env1" {
    mutate {
      add_field => [ "environment", "env1" ]
    }
  }
  if [type] == "env2" {
    mutate {
      add_field => [ "environment", "env2" ]
    }
  }
  if [type] == "env3" {
    mutate {
      add_field => [ "environment", "env3" ]
    }
  }
}

# Parse message format
filter {
  if [type] =~ "^env" {
    grok {
       # RFC 5424 syslog format
       match => { "message" => "<%{POSINT:syslog_pri}>%{DATA:syslog_version}%{TIMESTAMP_ISO8601:syslog_timestamp} %{DATA:logspout_host} %{DATA:syslog_program}%{POSINT:syslog_pid}(\s)*(\s-)*(\s)*\[%{POSINT:sd_id}*\] %{GREEDYDATA:syslog_message}" }
       add_field => [ "message_format", "rfc5424" ]
       add_field => [ "received_at", "%{@timestamp}" ]
       add_field => [ "received_from", "%{host}" ]
    }
  }
  syslog_pri { }
  date {
      match => [ "syslog_timestamp", "ISO8601" ]
  }
}

# Send message to output channels
output {
  # Elasticsearch
  elasticsearch {
    host => "elasticsearch"
    index => "logstash-%{environment}-%{+YYYY.MM.dd}"
  }

  # Standard out - Use for DEBUG ONLY (Turned off due to memory leak bug in docker)
  # stdout { codec => rubydebug }

  # Local env-* files
  if [type] == "env1" {
      syslog { host => "localhost"
               port => ???
               facility => "syslogd"
               severity => "debug" }
  }
  if [type] == "env2" {
      syslog { host => "localhost"
               port => ???
               facility => "syslogd"
               severity => "informational" }
  }
  if [type] == "env3" {
      syslog { host => "localhost"
               port => ???
               facility => "syslogd"
               severity => "informational" }
  }
}

**Comment by bbergstrom** [comment]
This is tagged with the 1.4 milestone but I don't see the patch for this in the 1.4 branch https://github.com/elastic/logstash/commits/1.4

Is this planned for 1.4.x?

**Comment by danielsand** [comment]
@bbergstrom:
i hate to say this - but just copy the tcp.rb from the commit into your current logstash 1.4.x installation && restart
It will do the trick.

**Comment by purbon** [comment]
@danielsand @bbergstrom you can also see it in another way, do a PR with the changes to backport it to 1.4, makes sense?

**Comment by danielsand** [comment]
@purbon here you go

**Comment by purbon** [comment]
thanks, much appreciate it. We'll review and merge as soon as possible!

**Comment by danielsand** [comment]
@purbon awesome :)
