### ISSUE TITLE
invalid UTF-8 sequences "crashes" the logstash 

### ISSUE THREAD

**Issue by mlausch** [elastic/logstash#15091]
**Logstash information**:

tested with  versions:
8.8.1,  7.12.1 and 7.17.10

**JVM** (e.g. `java -version`):
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux qadebuglog 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Pipeline
```
input {
  tcp {
    port => 33039
    codec => fluent
  }

filter {
    if [log] =~ "\A\{.+\}" {
      json {
        source => "log"
      }
      if "_jsonparsefailure" not in [tags] {
        mutate {
          remove_field => ["log"]
        }
      }
    }
    else {
      mutate {
        rename => ["log", "message"]
      }
    }
  }
}
output {
    file {
        path => "/var/log/logstash/data.log"
    }
}

```

If the "log" field contains a invalid UTF-8 sequence, logstash stopps itself (see logfile)
The issue happens on this line
 if [log] =~ "\A\{.+\}" {

yes, I think it would be possible to write the filters more elegant, but I think invalid UTF-8 shouldn't "crash" the logstash itself.

last year someone had posted this issue on https://discuss.elastic.co/t/input-tcp-codec-fluent-invalid-byte-sequence-in-utf-8-in-regex/296290  unfortunately there wasn't any response.   

**Steps to reproduce**:
deliver a json line like this via a fluentd instance 
`{"log": "�"}`

the invalid bytesequence is a 0x3c character

**Provide logs (if relevant)**:
```
[2023-06-13T15:55:50,315][ERROR][logstash.javapipeline    ][main] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"main", :error=>"(ArgumentError) invalid byte sequence in UTF-8", :exception=>Java::OrgJrubyExceptions::ArgumentError, :backtrace=>["org.jruby.RubyRegexp.match?(org/jruby/RubyRegexp.java:1170)", "RUBY.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:304)"], :thread=>"#<Thread:0x2c8de6c@/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:134 sleep>"}
[2023-06-13T15:55:52,330][WARN ][logstash.javapipeline    ][main] Waiting for input plugin to close {:pipeline_id=>"main", :thread=>"#<Thread:0x2c8de6c@/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:134 run>"}
[2023-06-13T15:55:54,658][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-06-13T15:55:54,965][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-06-13T15:55:54,972][INFO ][logstash.runner          ] Logstash shut down.

```

**Comment by mgovolt** [comment]
Was this ever resolved? I get these now too.

**Comment by Aloshi** [comment]
I am having this issue as well. I was able to hack around by adding this as the first filter in my pipeline:

```
  ruby {
    id => "replace-invalid-utf8-chars"
    code => '
      message = event.get("message")
      if message.is_a? String
        event.set("message", message.encode(Encoding::UTF_8, Encoding::UTF_8, invalid: :replace, undef: :replace).scrub)
      end'
  }
```

(based on the logic from [this PR](https://github.com/elastic/logstash/pull/16168/files#diff-02c2221ffae8fb845c8693e5aadbf90e5e635731debd2da420921ba88e52e7a9R25-R37) which I admittedly have not reviewed thoroughly)

**Comment by mashhurs** [comment]
I do believe this issue was addressed in Logstash 8.14+.

**Comment by Aloshi** [comment]
@mashhurs I am still able to reproduce this on Logstash 8.14.3.

**Comment by mashhurs** [comment]
> @mashhurs I am still able to reproduce this on Logstash 8.14.3.

This sounds like fluent codec specific issue.
Can you please provide DEBUG logs?

**Comment by Aloshi** [comment]
Logs from running with `LOG_LEVEL=trace`: [logstash-trace.log](https://github.com/user-attachments/files/16475822/logstash-trace.log) (didn't see anything helpful)

Archive with runnable example: [fluent-crash-example.zip](https://github.com/user-attachments/files/16475858/fluent-crash-example.zip)
To run:
```bash
docker compose up
# fluentd will print errors until logstash starts
# wait for logstash to start (you should see some fluentd logs appear in stdout)

# in another terminal, run this script to send a log with invalid utf-8
./gen-log.sh
# wait 5s for fluentd to flush
# logstash pipeline should crash and logstash should exit
```

**Comment by mashhurs** [comment]
I have just checked and it seems the issue with `codec-rubydebug`. If you remove it from `stdout` setting (`stdout { }`), Logstash handles without crashing (see below logs). `codec-rubydebug` has amazng print dependency which might be cause. What are your actual downstream outputs? Do you see issue with them as well?

```
logstash  | {
logstash  |     "@timestamp" => 2024-08-09T20:18:04.000Z,
logstash  |       "@version" => "1",
logstash  |        "message" => "{\"myjson\": \"vandflyver \xC5rhus\"}",
logstash  |           "tags" => [
logstash  |         [0] "app.log"
logstash  |     ]
logstash  | }


```
