### ISSUE TITLE
Allow adding multiple keys for logstash-keystore command

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#15186]
Currently, adding keys to the keystore need to call [command](https://www.elastic.co/guide/en/logstash/current/keystore.html#add-keys-to-keystore) `logstash-keystore add YOUR_KEY` one by one for each key, which is very time-consuming because it starts and stops jvm each time. 

A suggestion is to allow batch updates for keys in a single call.
`logstash-keystore add KEY1 KEY2 KEY3 ...`

**Comment by roaksoax** [comment]
When we look at doing this, we should also look at https://github.com/elastic/logstash/pull/12194 . Maybe, you an absorb this change as part of the work to add multiple keys support.

**Comment by seyeh** [comment]
@roaksoax @kaisecheng Can I try this PR, where I try to add multiple keys at once?
