### ISSUE TITLE
Contributing to logstash-output-syslog and status of the plugin?

### ISSUE THREAD

**Issue by tsaarni** [elastic/logstash#15236]
Sorry for writing here, but I would really appreciate some help from the maintainers:

We are using [logstash-output-syslog](https://github.com/logstash-plugins/logstash-output-syslog). I've worked with the code a bit and contributed several PRs ([see here](https://github.com/logstash-plugins/logstash-output-syslog/pulls/tsaarni)) and I would like to continue working with it for more features and fixes.

I wonder if any maintainers are watching over that github repo anymore?  It would be great to get someone to review / shepherd contributors since the plugin is very useful, but currently it seems a bit abandoned.

How do you see the status and further work on the plugin?

**Comment by roaksoax** [comment]
Hi @tsaarni ,

First and foremost, I just wanted to thank you for your contributions. The [logstash-output-syslog](https://github.com/logstash-plugins/logstash-output-syslog) plugin is a community driven plugin, and as maintainers, we review PRs from time to time.  As such, please rest assured we will be reviewing them soon.

That said, if you would be interested in becoming a co-maintainer of this plugin, we would be more than happy to work with you to make that a reality.

**Comment by tsaarni** [comment]
Thank you @roaksoax for your response! I will be eagerly waiting for reviews :) 

I'm curious, how does your projects work with community co-maintainers? As a contributor it would be great to see fixes and features go in faster and releases come out, but it still requires time from another developer to review and someone to be in charge of the releases. Oh, I should also mention. I'm not a ruby developer per se, I just manage somehow ;)
