### ISSUE TITLE
Make start scripts work with cygwin

### ISSUE THREAD

**Issue by BoronNitride** [elastic/logstash#1524]
Because of the path name mess in MS Windows the following changes are needed to start logstash with cygwin bash:
```
bin/logstash 
22d21
<
24,26d22
< if [[ "$OSTYPE" == "cygwin" ]] ; then
<     basedir=`cygpath -m ${basedir}`
< fi


bin/logstash.lib.sh bin
2,4d1
< if [[ "$OSTYPE" == "cygwin" ]] ; then
<     basedir=`cygpath -m ${basedir}`
< fi
```

**Comment by cleiter** [comment]
+1
I can confirm that this is needed with cygwin and that the patch works as expected.

**Comment by suyograo** [comment]
This has been fixed in https://github.com/elastic/logstash/commit/6cb438d7fc56e93b99d1e766a5b6573012d979f2

**Comment by cleiter** [comment]
@suyograo I don't see how that commit would fix that, since it only touches the `.bat` file but under cygwin `logstash` is executed.
