### ISSUE TITLE
Multiline filter with what="previous" cuts off last line when using stdin input

### ISSUE THREAD

**Issue by hoelzro** [elastic/logstash#1525]
Example:

``` conf
# test.conf
input { stdin {} }
filters {
  multiline {
    what => "previous"
    pattern => "never going to match!"
  }
}
output { stdout {} }
```

```
$ seq 1 10 | ./bin/logstash agent -f test.conf
2014-07-11T15:10:37.057+0000 lepus 1
2014-07-11T15:10:37.058+0000 lepus 2
2014-07-11T15:10:37.059+0000 lepus 3
2014-07-11T15:10:37.060+0000 lepus 4
2014-07-11T15:10:37.060+0000 lepus 5
2014-07-11T15:10:37.061+0000 lepus 6
2014-07-11T15:10:37.061+0000 lepus 7
2014-07-11T15:10:37.062+0000 lepus 8
2014-07-11T15:10:37.062+0000 lepus 9
```

Multiline buffers the current entry when run in previous mode, so it should probably flush that buffer when the input is exhausted.

**Comment by ajay2881** [comment]
Hey guys, I am new to logstash, I have done the installation and set up and ingested some sample data to elastic search though logstash but I see  a strange behaviour in logstash, it truncates  the input event stream for example I have data like this- 
job1,success,12-07-2015
job2, failed,12-07-2015
and in the filter i am mapping the input stream with jobname,status,endtime
but I sometime  see results like
jobname=job1, status=succ,endtime=12-

why is that ? please help.
