### ISSUE TITLE
Error: Your application used more memory than the safety cap of 500M.

### ISSUE THREAD

**Issue by metwally** [elastic/logstash#1540]
I get this error every day:
Error: Your application used more memory than the safety cap of 500M.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace

from where and how can I specify this "-J-Xmx####m" variable?

**Comment by colinsurprenant** [comment]
this is most probably related to logstash-plugins/logstash-codec-multiline#4

**Comment by iphone4plus** [comment]
maybe you are using ls1.5.2 and you could find this code "LS_HEAP_SIZE="${LS_HEAP_SIZE:=500m}""  from logstash.lib.sh , however the size is 5g in ls1.5.1
