### ISSUE TITLE
how to config timezone in china 

### ISSUE THREAD

**Issue by ansjsun** [elastic/logstash#1541]
i want rewrite @timestamp  it is only in UTC , but in china ..it must +8  

i found it in 

```
ruby {
    code => "event['@timestamp'] = event['@timestamp'].local('-08:00')"
}
```

but in version 1.4.2 it not work ...

how to tak it ..in server thanks very much !! my english is very bad ..bu  i good at chinese hehe

**Comment by shshxy98** [comment]
I use filter ruby plugin, my logstash version is  5.1.1

```
#ruby time format,you should check here，https://ruby-doc.org/core-2.2.0/Time.html
filter {
    ruby {
        code => "event.set('logtime',event.timestamp.time.localtime.strftime('%d/%b/%Y:%H:%M:%S +0800'))"
    }
}
```
only use it in out file plugin
