### ISSUE TITLE
filters/clone/conditionals bug

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#1548]
I am not sure what the source of this issue is but right now my brain is fried so I'll post it here for others to look at it, and when my brain is unfried I'll work on it.

with this configurations

```
input { stdin { } }

filter {
  clone { clones => ["clone"] }

  if [type] == "clone" {
    mutate { add_field => { "clone" => "true" } }
  } else {
    mutate { add_field => { "original" => "true" } }
  }
}

output { stdout { codec => "rubydebug" } }
```

type in any input, "foo" for example

```
{
       "message" => "foo",
      "@version" => "1",
    "@timestamp" => "2014-07-17T23:12:29.536Z",
          "host" => "colin-mbp13r",
      "original" => "true"
}
{
       "message" => "foo",
      "@version" => "1",
    "@timestamp" => "2014-07-17T23:12:29.536Z",
          "host" => "colin-mbp13r",
          "type" => "clone",
      "original" => "true"
}
```

clearly, the 2nd event, the clone, did not correctly went through the `if [type] == "clone"` conditional.

**Comment by oryband** [comment]
This happens with `clone` and `mutate` in that order in **1.4.2**:
```ruby
if some condition {
  clone {
    clones => "cloned"
  }
}

if [type] == "cloned" {
  mutate { .. }  # doesn't happen
}
```

**Comment by driverpt** [comment]
@colinsurprenant Has this bug been fixed ?

**Comment by mjscosta** [comment]
Think, it has been solved! But the documentation is not clear about the semantics of the clone behavior! 
Weather its reinserted into the queue, and reprocessed by the filter pipeline, or if it is added the the batch of events being filtered, and will only apply, the transformations/conditionals following the clone configuration ("call") ...

**Comment by jordansissel** [comment]
@mjscosta Indeed it's been solved. Good note about the documentation not being clear - can you file a new ticket about getting that documented?

To answer your question, your last detail is correct in describing the behavior -- this is right:

>  if it is added the the batch of events being filtered, and will only apply, the transformations/conditionals following the clone configuration ("call") ...
