### ISSUE TITLE
init does not log to .stdout and .err

### ISSUE THREAD

**Issue by Jasperswaagman** [elastic/logstash#1560]
Version 1.4.2 from the Logstash repository.

I had a problem with read permissions on a .crt file. Which I noticed when I looked in /var/log/logstash/logstash.log. However the init script should create a .stdout and .err which it does not. 
The directory /var/log/logstash is owned by the logstash user and as group: root. 
I'm running LS on Ubuntu 12.04.2. I did not change anything in /etc/defaults/logstash nor the init script.

**Comment by jordansissel** [comment]
This is probably a bug in pleaserun's generator. I'll take a look soon.

**Comment by jsvd** [comment]
@jordansissel have you got into checking this? does this affect ubuntu specifically?

**Comment by jordansissel** [comment]
I think this is fixed in 5.0
