### ISSUE TITLE
Issue with logstash trying to connect to http://elasticsearch:9200/ despite correct elasticsearch backend

### ISSUE THREAD

**Issue by patpatpat123** [elastic/logstash#15624]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)

FROM docker.elastic.co/logstash/logstash:7.17.10

2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)

docker

3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)

Kubernetes

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`):
built in JVM

**Steps to reproduce**:

 1. I have a correct logstash.conf as follow:

```
input {
  tcp {
    port => 5000
  }
}

output {
  elasticsearch {
    hosts => ["https://my-elastic-cluster.com:9200"]
```

By correct, I mean it is working, I can see the logs going through this logstash, and the logs are ending in elasticsearch

 However, periodically, I am getting this message:

**Provide logs (if relevant)**:

```
[2023-11-28T13:19:01,180][INFO ][logstash.licensechecker.licensereader] Failed to perform request {:message=>"elasticsearch: Name or service not known", :exception=>Manticore::ResolutionFailure, :cause=>java.net.UnknownHostException: elasticsearch: Name or service not known}
[2023-11-28T13:19:01,180][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch: Name or service not known"}
[2023-11-28T13:19:21,823][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"No Available connections"}

```

I just wanted to reach out and report the issue is that despite a correct host config, it seems logstash is still trying to go to http://elasticsearch:9200/.

**Comment by edmocosta** [comment]
Hey @patpatpat123,

Do you have any X-Pack feature enabled on your `config/logstash.yml` (`xpack.*`)? It seems those logs are coming from the license manager, and not from the `elasticsearch` output plugin.

**Comment by patpatpat123** [comment]
Thank you @edmocosta for the quick turnaround.

I think you are correct.
This is the file from inside the container:

```
logstash@logstash-5644b4978c-92t95:~/config$ cat logstash.yml
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
```

But I do not believe to have added any of those X-pack related features. 
Please see my full logstash.conf

```
input {
  tcp {
    port => 5000
  }
}

output {
  elasticsearch {
    hosts => ["https://my-elastic-cluster.com:9200"]
    ssl => true
    data_stream => "true"
    data_stream_type => "logs"
    data_stream_dataset => "foo"
    data_stream_namespace => "bar"
    keystore => "keystore.jks"
    keystore_password => "123"
    truststore => "truststore.p12"
    truststore_password => "123"
  }
}

```

How did it end up in the file?
What did I do wrong please?

**Comment by edmocosta** [comment]
Those two settings are configured by default when running in [docker](https://www.elastic.co/guide/en/logstash/7.17/docker-config.html#_docker_defaults) with no custom configuration defined. 
Explicitly disabling `xpack.monitoring` by setting the environment variable `XPACK_MONITORING_ENABLED=false`  or using a [custom logstash.yml](https://www.elastic.co/guide/en/logstash/7.17/docker-config.html#docker-bind-mount-settings) should get rid of those errors. 

If you want to keep/use the `xpack` feature, it needs to be configured on the `logstash.yml`. Those configurations are independent of your pipeline's elasticsearch plugin configuration :)

**Comment by patpatpat123** [comment]
Thanks a lot @edmocosta . Good day!
