### ISSUE TITLE
logstash-output-websocket plugin not installing on logstash 8.11

### ISSUE THREAD

**Issue by srinathpamukuntla** [elastic/logstash#15785]
Hi Team,

websocket output plugin is not installing in the current version of log file.
here is error message, i am getting:

>>bin/logstash-plugin install logstash-output-websocket
Using bundled JDK: /usr/share/logstash/jdk
Validating logstash-output-websocket
Resolving mixin dependencies
Installing logstash-output-websocket
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In Gemfile:
    logstash-core-plugin-api was resolved to 2.1.16, which depends on
      logstash-core (= 8.11.3)

    logstash-output-websocket was resolved to 0.1.4, which depends on
      logstash-core (< 2.0.0, >= 1.4.0)
Bundler could not find compatible versions for gem "sinatra":
  In Gemfile:
    logstash-core was resolved to 8.11.3, which depends on
      sinatra (~> 2)

    logstash-output-websocket was resolved to 3.0.5, which depends on
      sinatra (~> 1.4.6)

**Comment by jsvd** [comment]
Fixed by https://github.com/logstash-plugins/logstash-output-websocket/pull/19, please upgrade to version 3.1.0 of the plugin using the `bin/logstash-plugin update logstash-output-websocket` command
