### ISSUE TITLE
java.lang.ClassCastException: org.jruby.RubyArray cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#1579]
Elasticsearch output plugin w/ `transport => node` fails with certain kinds of events. Unsure what at this time.

**Comment by walkeran** [comment]
Thanks @jlintz for dropping the urldecode hint -- With that bit, I was able to track down my own problems quite a bit, and I'm now able to recreate with a very simple config and input.

Looks like the same stack trace that was reported at the beginning of this issue:
```
{:timestamp=>"2015-04-27T16:53:28.003000-0500",
  :message=>"Failed to flush outgoing items",
  :outgoing_count=>1,
  :exception=>#<JSON::GeneratorError: source sequence is illegal/malformed utf-8>,
  :backtrace=>[
    "json/ext/GeneratorMethods.java:71:in `to_json'",
    "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:100:in `bulk_ftw'",
    "org/jruby/RubyArray.java:2404:in `collect'",
    "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:97:in `bulk_ftw'",
    "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:80:in `bulk'",
    "/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315:in `flush'",
...
```

I'm running Logstash 1.4.2 (logstash-1.4.2-1_2c0f5a1 RPM)

Here's the config that I can recreate this with:
```
input {
  file {
    path => '/tmp/LS1579/*'
    start_position => "beginning"
    sincedb_path => '/dev/null'
    codec => json
  }
}

filter {
  urldecode {
    all_fields => true
  }
}

output {
  elasticsearch {
    protocol   => 'http'
    host       => '192.168.200.72'
    index      => "deleteme"
    index_type => "%{es_type}"
  }
}
```

And the input file:
```
{"message":"%BD"}
```

**Comment by webmstr** [comment]
It was implied earlier, but could the error be extended to print the offending message?

**Comment by colinsurprenant** [comment]
FYI, the encoding issue related to the urlencode filter has been solved in logstash-plugins/logstash-filter-urldecode#1 and also relates to #1695

I believe we can now close this issue.
