### ISSUE TITLE
logstash event: @timestamp when using json serializer is hash

### ISSUE THREAD

**Issue by pctj101** [elastic/logstash#1583]
Master branch:

When doing Event.to_json

I expect something more like:
  @timestamp":"2014-07-31T09:05:58.710Z"

But with the new cabin/oj serializers I see this:
  @timestamp":{"time":"2014-07-31T09:05:58.710Z"}

Maybe it's a new standard I'm not aware of, but just noting it here.  I'm still looking into it.  Maybe JSON serialization for the Logstash::Timestamp object is not the best approach for just this field?

**Comment by talevy** [comment]
@pctj101 are still finding this issue occurring in Logstash > 1.4?

**Comment by suyograo** [comment]
Can you reopen this if you can reproduce with 1.5.0?
