### ISSUE TITLE
logstash will not open a listening port.

### ISSUE THREAD

**Issue by heytchap** [elastic/logstash#1587]
Error message:

{:timestamp=>"2014-07-31T17:07:57.613000-0700", :message=>"syslog udp listener died", :address=>"0.0.0.0:514", :exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/opt/logstash/lib/logstash/inputs/syslog.rb:116:in`udp_listener'", "/opt/logstash/lib/logstash/inputs/syslog.rb:76:in `run'"], :level=>:warn}

config:

input {
        redis {
                host => "<IP>"
                data_type => "list"
                key => "logstash"
        }
        file {
                type => "syslog"
                path => ["/var/log/*.log"]
                sincedb_path => "/opt/logstash/sincedb-access"
        }
        syslog {
                type => "syslog"
                port => "5514"
                tags => ["______"]
        }
        syslog {
                type => "syslog"
                port => "514"
                tags => ["_____"]
        }
}

Have referenced the following:
https://github.com/elasticsearch/logstash/pull/1398
and
https://github.com/elasticsearch/logstash/blob/74dfd2b05eb2a5369370e5756963bdc0221b8449/pkg/logstash.sysv

Issue persists. 

Logstash user groupds: 

root@myServer:/etc/logstash/conf.d# id logstash
uid=999(logstash) gid=999(logstash) groups=999(logstash),0(root),4(adm),104(syslog)

Issue also exists for UDP input listeners.

Error also seen here:
https://groups.google.com/forum/#!topic/logstash-users/1skCn079h5g

Not sure where else. If logstash is unable to listen on 514 I am unable to send anything to logstash, making logstash useless for me.

**Comment by freshfrmthehood** [comment]
Just ran into this issue myself. Not recommended, but you can modify the logstash user in the init script to a privleged user also fixes the issue.

**Comment by craigafinch** [comment]
I configured the firewall on the Logstash server to forward port 514 to 5514, and configured Logstash to listen on 5514.

Advantages of this approach:
- No need to fiddle with Java options
- No need to escalate privileges for the Java binary with setcap, which could compromise the security of other Java-based applications that may may reside on the same server
- The rest of your infrastructure can use the standard Syslog port (514). Some appliances may not allow you to change the port.

**Comment by Lonck** [comment]
Hi for All,
I installed the Elastic Stack in Debian 8.5 by repositories. I'm having the same problem with Logstash to listen on udp port setting in the conf file (port => 9878).
I found the same solution reported by Kerry Milestone on other sites. However I do not know where the make this change (_JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true).
Cold anyone tell me?
Thanks.

**Comment by untergeek** [comment]
Please submit usage questions to https://discuss.elastic.co/c/logstash

GitHub issues are for code issues and bug reporting.

**Comment by Lonck** [comment]
Hi!
Sorry! I sent my question to this forum why read the posts with the same problem as mine.
I found the answer, however the reported solution in this forum did not fix the problem. This problem would not be a bug Logstash?

**Comment by Know1** [comment]
For anyone that encouters this on later versions of Ubuntu (mine is 16.04) the required command to allow java to open privileged ports is
  setcap cap_net_bind_service=+epi /usr/lib/jvm/java-8-oracle/

**Comment by talial1812** [comment]
Hi,
we have a 5 nodes elasticsearch cluster running 5.2.0, 
2 of the nodes are configured as client nodes (data=false, master=false),
3 nodes are elasticsearch cluster (data=true, master=true)

I install logstash in one of the 2 kibana servers, as follow:

groupadd logstash
useradd logstash -g logstash -d /home/logstash
cat /etc/passwd | grep logstash

vi /etc/sudoers
Add the following line :
logstash ALL=(ALL) NOPASSWD: ALL

cd /home/logstash
chown logstash:logstash logstash-5.2.0.rpm

passwd logstash

--> connect with logstash

sudo rpm --install logstash-5.2.0.rpm

sudo initctl start logstash

configured the IP of this server in the machine that send the syslog

config logstash.conf as follow:
```
input {
  tcp {
    port => 514
    type => syslog
  }
  udp {
    port => 514
    type => syslog
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}
```

output {
  elasticsearch { hosts => ["10.10.10.10:9200"] }
}

getting this error:
```
[INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:514"}
[ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<Errno::EACCES: Permission denied - bind(2)>, :backtrace=>["org/jruby/ext/socket/RubyTCPServer.java:124:in `initialize'", "org/jruby/RubyIO.java:871:in `new'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:279:in `new_server_socket'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:89:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:358:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:357:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:233:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:188:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:302:in `start_pipeline'"]}
[INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
```
java -version
java version "1.8.0_101"

follow this thread I ran:
export _JAVA_OPTIONS='-Djava.net.preferIPv4Stack=true'

But still getting the error

Any idea?

**Comment by jordansissel** [comment]
Logstash is not given permission on your system to open port 514.
