### ISSUE TITLE
consumer:  output tearsdown before `@worker_queue` is emptied

### ISSUE THREAD

**Issue by Gauravshah** [elastic/logstash#1588]
I have a rabbitmq as input and a custom buffered plugin as output.

My output's teardown is called before `@worker_queue` on the output is emptied

Order of events
SIGINT
rabbitmq closes connnection
rabbitmq send the remaining events to output buffer
output receieves SIGINT event
output joins threads
teardown is called in output
STD:Buffer calls finalflush

events lost due the following code:

``` ruby
    @worker_threads = @workers.times do |i|
      Thread.new(original_params, @worker_queue) do |params, queue|
        LogStash::Util::set_thread_name(">#{self.class.config_name}.#{i}")
        worker_params = params.merge("workers" => 1, "codec" => @codec.clone)
        worker_plugin = self.class.new(worker_params)
        worker_plugin.register
        while true
          event = queue.pop
          worker_plugin.handle(event)
        end
      end
    end
```

teardown does not wait for the threads to empty `@worker_queue` and the events inside that buffer are lost. So every instance would loose events in range of 1..20

Using:
Logstash: 1.4.2
Bundled jruby, rabbitmq & std_buffer

**Comment by untergeek** [comment]
In the absence of more feedback, and that #1545 was merged, I am closing this.

Feel free to re-open if the issue persists.

**Comment by colinsurprenant** [comment]
I will reopen this. After a quick review, the output shutdown sequence is in fact not correct. the `ShutdownEvent` triggers the call to `teardown` but nowhere are the worker queues emptied before calling teardown. This need to be be reviewed.

**Comment by colinsurprenant** [comment]
this behaviour should be reviewed in the context of the new batched pipeline, adding 2.3 milestone tag.

**Comment by guyboertje** [comment]
This is no longer applicable to the 2.X or 5.X releases. These versions we use batches. This batch serves the purpose of a buffer. Custom outputs should not buffer any events in order to bulk send.

Implement `multi_receive` to get the batch into the output.
