### ISSUE TITLE
Worker threads and multiline are not supported

### ISSUE THREAD

**Issue by lmorfitt** [elastic/logstash#1590]
Using the multiline filter and trying to enable "-w 2" causes errors. 

Updated documentation to note this issue.

{:timestamp=>"2014-08-01T20:12:17.651000+0100", :message=>"Error: Cannot use more than 1 filter worker because the following plugins don't work with more than one worker: multiline, multiline"}

```
                     multiline {
                            # If we DONT match a year then it belongs to the last line
                            pattern => "^(\d{4})"
                            what => "previous"
                            negate => true
                    }
```

**Comment by synaq** [comment]
Hi There,

We have a new ELK environment which we love, the only thing making it lame at the moment is the multiline filter not being threadsafe - we have a big setup.

Any chance this can happen? :)

**Comment by untergeek** [comment]
Try using the multiline codec instead. 



—Aaron

**Comment by aleksz** [comment]
Looks like using codec is not an option due to other bug, that mixes lines when multiline codec applied to multiple files.
