### ISSUE TITLE
Upgrade JRuby to 9.4 (to get `Zlib::GzipReader.zcat`)

### ISSUE THREAD

**Issue by eherot** [elastic/logstash#15908]
There are probably other good reasons for doing this, but here's the problem I've encountered...

The [logstash-input-s3](https://github.com/logstash-plugins/logstash-input-s3) plugin relies on Ruby's embedded ZLib to decompress GZipped log files, however AWS stores these files in a concatenated form that [can't be read](https://bugs.ruby-lang.org/issues/9790) by the normal `Zlib::GzipReader.new()` method. Thankfully a new `Zlib::GzipReader.zcat()` method was added that can read this type of file, however it is only available in Ruby 3.

Without this it is impossible to stream GZipped log files from S3, so it would be very helpful if JRuby could either be upgraded to a version that includes this feature or if another library could be included as a workaround.

**Comment by andsel** [comment]
Hi @eherot starting from Logstash `8.10` JRuby 9.4 is bundled with the package: https://www.elastic.co/guide/en/logstash/current/logstash-8-10-0.html

**Comment by eherot** [comment]
Oh hello! I looked at [/.ruby-version](https://github.com/elastic/logstash/blob/main/.ruby-version) but apparently I wanted [/versions.yml](https://github.com/elastic/logstash/blob/main/versions.yml#L16). Looks like I'll have to go push on [opensearch-project/logstash-output-opensearch](https://github.com/opensearch-project/logstash-output-opensearch) instead. Thanks for the quick response at any rate!
