### ISSUE TITLE
Google BigQuery crashes after temp file roatation

### ISSUE THREAD

**Issue by DaveTaboola** [elastic/logstash#1599]
hi
after investigating an major issue i had with google_bigquery plugin i've found the following:
every time a file is being deleted using the google_bigquery plugin, logstash crushes with the error it can't find the file.

to fix the issue i've added to the File.delete(filename) statement in both google_bigquery and google_cloud_storage ruby files the following change

File.delete(filename) if File.exist?(filename)
it fixes the issue as files can be deleted in couple of statements prior to that roll out 

for more info: 
https://logstash.jira.com/browse/LOGSTASH-2247

please implement the change in the upcoming versions of the product,
Thanks,
Dave

**Comment by untergeek** [comment]
Thanks!  We appreciate the ideas here.

Would you be willing to contribute these changes yourself?

You can now issue pull requests to each plugin independently:
https://github.com/logstash-plugins/logstash-output-google_cloud_storage
https://github.com/logstash-plugins/logstash-output-google_bigquery

**Comment by purbon** [comment]
Migrated this issue to https://github.com/logstash-plugins/logstash-output-google_bigquery/issues/10 as it belongs to the plugin.
