### ISSUE TITLE
Secrets in Source code apprise like Secret leak in scanners 

### ISSUE THREAD

**Issue by barakharyati** [elastic/logstash#16044]
The following Row contains the password. Secret scanners detect it as a Potential Secret leak. 
Keeping secrets in Source code is a bad practice, Can you please remove it? 

https://github.com/elastic/logstash/blob/aaaf0696e5afeb645fe03345772e366be2cc9428/x-pack/spec/license_checker/license_reader_spec.rb#L197

**Comment by yaauie** [comment]
It is a test validating behaviour with test-fixture inputs that are not a part of the build artifact.
