### ISSUE TITLE
Logstash Ingest Pipeline Converter Does not handle "copy_from" option for Set processor

### ISSUE THREAD

**Issue by woodywalton** [elastic/logstash#16098]
https://github.com/elastic/logstash/blob/830733d75856c3c4d3086facf46bbb2eb12c61c3/tools/ingest-converter/src/main/java/org/logstash/ingest/IngestSet.java#L56

https://www.elastic.co/guide/en/elasticsearch/reference/8.13/set-processor.html#set-processor

Value for "set" ingest processor can be one of either "value" or "copy_from"

**Comment by kaisecheng** [comment]
The tool ingest converter is not continued and will be remove in the next major version, v9. To run ingest pipeline in Logstash, you can try [elastic integration filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-elastic_integration.html)
