### ISSUE TITLE
Handling PagerDuty rate limits

### ISSUE THREAD

**Issue by cschotke** [elastic/logstash#1613]
We are using the PagerDuty output to generate alarms from log files. This works fine most of the time but sometimes we run into issues because of PD's rate limit. PD will cut you off if you send more than 60 messages in a minute. Is anyone aware of a way to suppress or limit the outgoing messages locally so we don't run into that rate limit?

Thanks.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-pagerduty/issues/5. Let's continue the discussion there! :)
