### ISSUE TITLE
bundle ES bin/plugin

### ISSUE THREAD

**Issue by kevinkluge** [elastic/logstash#1614]
It would be nice if LS bundled ES's bin/plugin.  Many people use ES as an output.  They are installing the AWS plugin, for example, by hand because they want the features associated with their ES output node.

Bundling ES's bin/plugin would make this install easier.

**Comment by suyograo** [comment]
Closing this is as we have separate infrastructure to install additional plugins in LS which are needed by ES. See for example the license plugin which installs the license jars needed for Shield and Watcher
