### ISSUE TITLE
Remove event_api.tags.illegal (default becomes locked to 'rename')

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#16356]
In https://github.com/elastic/logstash/pull/14822, we introduced the ability to guard against the use of the "reserved" field name `tags`. As part of that change, we introduced a setting `event_api.tags.illegal` that could be set with `warn`, which would still allow the previous behaviour, and continue to set the field `tag`, and only warn against it's use, and `rename`, which would move the illegal value and put it into a new `_tags` field. 

We should remove this setting, and always use the behaviour currently provided by the `rename` setting

* Mark setting as obsolete in `9.0`
* Update `8.x` deprecation log to state that this setting is being removed in `9.0`

**Comment by kaisecheng** [comment]
@robbavey Should Logstash keep the flag  `event_api.tags.illegal`  and set it default to `rename`? Or should the flag be removed completely?

**Comment by robbavey** [comment]
@kaisecheng The intent was to remove the setting for `9.0`, and use the behaviour previously provided by the `rename` settings.

cc @jsvd, @flexitrev
