### ISSUE TITLE
Set `pipeline.buffer.type` to `heap` by default

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#16353]
In #16054, we introduced a new setting to allow users to set the allocation of memory for certain input plugins to use either direct or heap memory. 

We should consider making this the default setting for Logstash `9.0`
```[tasklist]
### Tasks
- [x] on `8.x`, when `pipeline.buffer.type` is not set, we should emit a deprecation log guiding to do one of two things before upgrading to 9.x: _either_ (1) set `pipeline.buffer.type: heap` and tune heap size upward in advance of upgrading to 9.x _or_ (2) set `pipeline.buffer.type: direct` to lock in the existing behaviour. #16498
- [ ] on `main`, set default for `pipeline.buffer.type` to `heap` #16500
```

**Comment by flexitrev** [comment]
Would this be a breaking change if we are only changing the default?

**Comment by jsvd** [comment]
Any deployment out there consuming from Agent or Beats with a heap usage above 75% (or even 50%) can potentially crash on upgrade as any direct memory allocation from beats/agent/http/tcp inputs would now be done on the heap.

**Comment by robbavey** [comment]
Re-opened, as the deprecation warning sub-issue has not been closed
