### ISSUE TITLE
Disable allow_superuser by default

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#16355]
In https://github.com/elastic/logstash/pull/14046 and https://github.com/elastic/logstash/pull/14089, we introduced new functionality to guard against running Logstash as root with the introduction of a new setting `allow_superuser`. The initial implementation set this to `true` to avoid a breaking change in a minor release, but we should set this setting to `false` by default to disallow running Logstash as root by default
```[tasklist]
### Tasks
- [x] on `main` (8.x), when `allow_superuser` is not set, log a deprecation advising how to resolve prior to upgrading to 9.x by _either_ (1) setting `allow_superuser: false` to opt in _or_ (2) setting `allow_superuser: true` to opt out
- [x] on `9.x`, set default value of `allow_superuser` to `false`
```

**Comment by flexitrev** [comment]
Double check description here, was initial implementation set to true?

**Comment by robbavey** [comment]
Yes it was

**Comment by robbavey** [comment]
Closed as completed
