### ISSUE TITLE
Conflicting information in documentation

### ISSUE THREAD

**Issue by zanderle** [elastic/logstash#1651]
The documentation for [sincedb_path in file input](http://logstash.net/docs/1.4.2/inputs/file#sincedb_path) seems to be conflicting. It says
> There is no default value for this setting.
 
And afterwards it says
> The default will write sincedb files to some path matching “$HOME/.sincedb*”
  
Or maybe I just misunderstood, in which case I apologize.

**Comment by untergeek** [comment]
This should be part of the [file input plugin](https://github.com/logstash-plugins/logstash-input-file).  Migrating this issue to https://github.com/logstash-plugins/logstash-input-file/issues/110
