### ISSUE TITLE
Incorrect ERROR message

### ISSUE THREAD

**Issue by raghavbiyani-19** [elastic/logstash#16562]
**Logstash information**:

Please include the following information:

1. Logstash version: 7.8.0
2. Logstash installation source: docker
3. How is Logstash being run: docker compose

**Plugins installed**:
logstash-codec-avro (3.2.3)
logstash-codec-cef (6.1.1)
logstash-codec-collectd (3.0.8)
logstash-codec-dots (3.0.6)
logstash-codec-edn (3.0.6)
logstash-codec-edn_lines (3.0.6)
logstash-codec-es_bulk (3.0.8)
logstash-codec-fluent (3.3.0)
logstash-codec-graphite (3.0.5)
logstash-codec-json (3.0.5)
logstash-codec-json_lines (3.0.6)
logstash-codec-line (3.0.8)
logstash-codec-msgpack (3.0.7)
logstash-codec-multiline (3.0.10)
logstash-codec-netflow (4.2.1)
logstash-codec-plain (3.0.6)
logstash-codec-rubydebug (3.0.6)
logstash-filter-aggregate (2.9.1)
logstash-filter-anonymize (3.0.6)
logstash-filter-cidr (3.1.3)
logstash-filter-clone (4.0.0)
logstash-filter-csv (3.0.10)
logstash-filter-date (3.1.9)
logstash-filter-de_dot (1.0.4)
logstash-filter-dissect (1.2.0)
logstash-filter-dns (3.1.4)
logstash-filter-drop (3.0.5)
logstash-filter-elasticsearch (3.7.1)
logstash-filter-fingerprint (3.2.1)
logstash-filter-geoip (6.0.3)
logstash-filter-grok (4.3.0)
logstash-filter-http (1.0.2)
logstash-filter-json (3.1.0)
logstash-filter-kv (4.4.0)
logstash-filter-memcached (1.0.2)
logstash-filter-metrics (4.0.6)
logstash-filter-mutate (3.5.0)
logstash-filter-prune (3.0.4)
logstash-filter-ruby (3.1.5)
logstash-filter-sleep (3.0.6)
logstash-filter-split (3.1.8)
logstash-filter-syslog_pri (3.0.5)
logstash-filter-throttle (4.0.4)
logstash-filter-translate (3.2.3)
logstash-filter-truncate (1.0.4)
logstash-filter-urldecode (3.0.6)
logstash-filter-useragent (3.2.4)
logstash-filter-uuid (3.0.5)
logstash-filter-xml (4.1.0)
logstash-input-azure_event_hubs (1.2.2)
logstash-input-beats (6.0.9)
logstash-input-couchdb_changes (3.1.6)
logstash-input-dead_letter_queue (1.1.5)
logstash-input-elasticsearch (4.6.0)
logstash-input-exec (3.3.3)
logstash-input-file (4.1.18)
logstash-input-ganglia (3.1.4)
logstash-input-gelf (3.3.0)
logstash-input-generator (3.0.6)
logstash-input-graphite (3.0.6)
logstash-input-heartbeat (3.0.7)
logstash-input-http (3.3.4)
logstash-input-http_poller (5.0.1)
logstash-input-imap (3.0.7)
logstash-input-jms (3.1.2)
logstash-input-pipe (3.0.7)
logstash-input-redis (3.5.1)
logstash-input-s3 (3.5.0)
logstash-input-snmp (1.2.2)
logstash-input-snmptrap (3.0.6)
logstash-input-sqs (3.1.2)
logstash-input-stdin (3.2.6)
logstash-input-syslog (3.4.2)
logstash-input-tcp (6.0.5)
logstash-input-twitter (4.0.1)
logstash-input-udp (3.3.4)
logstash-input-unix (3.0.7)
logstash-integration-jdbc (5.0.1)
 ├── logstash-input-jdbc
 ├── logstash-filter-jdbc_streaming
 └── logstash-filter-jdbc_static
logstash-integration-kafka (10.2.0)
 ├── logstash-input-kafka
 └── logstash-output-kafka
logstash-integration-rabbitmq (7.0.3)
 ├── logstash-input-rabbitmq
 └── logstash-output-rabbitmq
logstash-output-cloudwatch (3.0.8)
logstash-output-csv (3.0.8)
logstash-output-elastic_app_search (1.0.0)
logstash-output-elasticsearch (10.5.1)
logstash-output-email (4.1.1)
logstash-output-file (4.3.0)
logstash-output-graphite (3.1.6)
logstash-output-http (5.2.4)
logstash-output-lumberjack (3.1.7)
logstash-output-nagios (3.0.6)
logstash-output-null (3.0.5)
logstash-output-pipe (3.0.6)
logstash-output-redis (5.0.0)
logstash-output-s3 (4.3.1)
logstash-output-sns (4.0.7)
logstash-output-sqs (6.0.0)
logstash-output-stdout (3.1.4)
logstash-output-tcp (6.0.0)
logstash-output-udp (3.1.0)
logstash-output-webhdfs (3.0.6)
logstash-patterns-core (4.1.2)

**JVM** (e.g. `java -version`):
Since we are installing logstash through docker, we have not installed jdk on our hosted vm.
I am providing the base image jdk version which is used by docker logstash internally:

1. JVM version: openjdk version "11.0.7" 2020-04-14 LTS
2. JVM installation source:
    OpenJDK Runtime Environment 18.9 (build 11.0.7+10-LTS)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10-LTS, mixed mode, sharing)
3. Value of the `LS_JAVA_HOME` environment variable if set: Not set

**OS version** (`uname -a` if on a Unix-like system): Host os version = CentOS 8.1

**Description of the problem including expected versus actual behavior**: If the indentation is not provided properly in pipelines.yml file is not provided properly, logstash is not throwing correct error. It should throw some validation error or some other error though which we can identify there is some problem in configuring pipelines.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Edit pipelines.yml file and intentionally put wrong indentation for one of the pipelines.
 2. Restart logstash
 3. Check for logstash logs. The error thrown is not conveying correct information.

**Provide logs (if relevant)**:
[ERROR] 2024-10-16 04:50:12.999 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (GemNotFound) Could not find gem 'logstash-output-jdbc java' in any of the gem sources listed in your Gemfile

**Comment by robbavey** [comment]
@raghavbiyani-19 This looks like you have a pipeline that is specifying a logstash jdbc _output_, which is not a plugin included in the default Logstash distribution, and this is an expected error message.

If you are intending to use JDBC output, please refer to the [Logstash documentation](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#installing-plugins) on how to add plugins that are not included.
