### ISSUE TITLE
Minimal package installation?

### ISSUE THREAD

**Issue by ghost** [elastic/logstash#1659]
Hi,

I'm looking to build an RPM, based on RHEL standards. I noticed that you bundle some unnecessary files into your current RPM. Myself, I will have Kibana set in a separate RPM (for example). Can you please provide with with a list of minimal/essential directories needed by `logstash`? For example, is the `/vendor` directory needed for the application? Thank your for your suggestions.

While here, please have a look at [AXIVO Elasticsearch RPM](https://www.axivo.com/resources/11/) details.

**Comment by mholland231** [comment]
Following up on this. Trying to minimize the logstash installation to include it as part of an iso. The /vendor directory is almost 170M - could you help me understand what is and is not needed as part of this? I would figure things like kibana are not critical but there are 2 versions of jruby? Not trying to restructure the package but lighten it. 

Thanks for looking at this.

**Comment by jirutka** [comment]
I also have interest in making minimal logstash installation.

**Comment by purbon** [comment]
@mholland231 you should check latest logstash versions, while still quite buggy, you the size is quite smaller. If you are willing to create your own minimal package I suggest you can setup a dev environment, and then:

* reduce the list of default plugins, see https://github.com/elastic/logstash/blob/master/rakelib/default_plugins.rb#L5 . This are the plugins bundled with logstash.
* run `rake artifact:tar` o `rake artifact:deb` (to create a tar or deb package) 

this will include minimal installation packages as selected on the first point.

hope it helps.

let me know if you need more help on it.
