### ISSUE TITLE
Logstash stop communicating with Elasticsearch

### ISSUE THREAD

**Issue by bigbo** [elastic/logstash#1663]
Logstash 1.4.1(or 1.4.2) & Elasticsearch 1.1.1(or 1.3.2) on Centos 6.5 
Everithing was working fine until Every morning when Logstash stop send new logs to Elasticsearch and when I stop then restart the losgstash process
it reprocess a bulk of new log lines and when it start to send it to Elasticserch it start writing this message again and again

my config file:
```
input {
   redis 
    {
    host => "192.168.1.120"
    data_type =>"list"
    port => "6379"
    key => "test"
    }
}

filter {
    grok {
    match => ["message", "%{TIMESTAMP_ISO8601:logtime},\d{3} info +"]
        remove_field => "message"
    }
    date {
        match => ["logtime", "YY-MM-dd HH:mm:ss"]
        remove_field => "logtime"
    }
    ruby {
        code => "event['@timestamp'] = event['@timestamp'].localtime('+08:00')"
    }
}

output {
    elasticsearch {
        host => "10.2.22.21"
        index => "logstash-%{+YYYY.MM.dd}"
        protocol => "http"
        workers => 4
    }
```

the error:
```
Failed to flush outgoing items {:outgoing_count=>616, :exception=>#<RuntimeError: Non-OK response code from Elasticsearch: 404>, :backtrace=>["usr/bin/logstash-1.4.1/lib/logstash/outputs/elasticsearch/protocol.rb:127:in `bulk_ftw'", "usr/bin/logstash-1.4.1/lib/logstash/outputs/elasticsearch/protocol.rb:80:in `bulk'", "usr/bin/logstash-1.4.1/lib/logstash/outputs/elasticsearch.rb:321:in `flush'", "usr/bin/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "usr/bin/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "usr/bin/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "usr/bin/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:159:in `buffer_receive'", "usr/bin/logstash-1.4.1/lib/logstash/outputs/elasticsearch.rb:317:in `receive'", "usr/bin/logstash-1.4.1/lib/logstash/outputs/base.rb:86:in `handle'", "usr/bin/logstash-1.4.1/lib/logstash/outputs/base.rb:78:in `worker_setup'"], :level=>:warn}
```

**Comment by bjolivot** [comment]
Same issue for me, need to re-open a lot of index.
Is it possible to add a check in logstash elasticsearch output plugin for closed index ?
Or in Elasticsearch to auto-open closed index when asked by logstash ?

**Comment by jordansissel** [comment]
> bulk call if repeatedly fails, then discarded

We will never discard things by default. However, we are working on a new feature in Logstash to help with failures (error that we can't reasonably recover from by waiting or other action by Logstas itself) - we'll soon (Logstash 2.0, I think) allow you to funnel such failures to a dead letter queue which wlil allow logstash to continue working under certain failures. The dead letter queue would then be usable by you to reprocess or repair the problem event(s).

**Comment by bjolivot** [comment]
Is there any schedule on Logstash 2.0 ?
My ELK stack is too easy to kill, just have to boot an old server with logstash-forwarder.

**Comment by jordansissel** [comment]
@bjolivot I'm not sure what you are wanting of "logstash 2.0". Logstash 1.5.0 should be out soon.  Is your problem related to this ticket? Can you provide more details? I'm not sure what logstash-forwarder has to do with Elasticsearch.

**Comment by bjolivot** [comment]
I have the problem described by bigbo in his comment :
I close old indexes ( > 3 days) in Elasticsearch.
If logstash receive logs older than 3 days, it try to send to elasticsearch in a closed index and begin an unending loop until I manualy open the good index.

Logstash-forwarder (previously called lumberjack) is a process used to parse logfiles and send them to logstash.
In case of starting longtime stoped server, with logstash-forwarder active, it could take hours reopening old logs manually (and 1 by 1 if I'm RAM short).

I'm looking for a solution :
 - Elasticsearch auto-open closed index
or
 - logstash ignore/delete/log...
or
- ???

**Comment by suyograo** [comment]
Closing this in favor of #73
