### ISSUE TITLE
Support RFC5424 message format 

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#1667]
Logstash has the [syslog input](http://logstash.net/docs/1.4.2/inputs/syslog) which only supports messages in RFC3164 (with some modifications). It would be useful to add a codec which supports [RFC5424](http://www.ietf.org/rfc/rfc5424.txt) messages which could be used with inputs like TCP. With this support users would not have to use a grok filter with `SYSLOG5424LINE` pattern

**Comment by jordansissel** [comment]
Still on the todo list, just haven't scheduled time to work on it.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-syslog/issues/15. Let's continue the discussion there! :)
