### ISSUE TITLE
8.16.1 Docker image corrupt

### ISSUE THREAD

**Issue by tyteen4a03** [elastic/logstash#16720]
The Docker image for 8.16.1 seems to be corrupt: https://hub.docker.com/layers/library/logstash/8.16.1/images/sha256-eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb?context=explore

There is no image.

**Comment by jsvd** [comment]
That is odd, that page does allow you to select an image for the arm64/v8 or amd64 and both of those images work correctly on my side:

![Image](https://github.com/user-attachments/assets/af5a5298-6eb3-44e0-a238-c16035861931)

**Comment by tyteen4a03** [comment]
It seems to be showing now. When I checked, it was 2 hours after publishing and there were no images.
