### ISSUE TITLE
Add `x-elastic-product-origin` header to Modules code in 8.x

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#16735]
Add header to all uses in Modules:
  - [ ] `api/status`
  - [ ] `api/kibana/dashboards/import`
  - [ ] `api/kibana/settings`

**Comment by donoghuc** [comment]
@robbavey I targeted my PR against `main` in logstash. Do we *only* want this in 8.x? Or should we merge in main then backport to 8.x?

**Comment by robbavey** [comment]
This should only be applicable for `8.x`, as we are targeting for removing modules code in `main`

**Comment by donoghuc** [comment]
Closed by https://github.com/elastic/logstash/pull/16765
