### ISSUE TITLE
Running `bin/logstash` will produce a `Gem::Specification.reset` warning on startup

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#16754]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
`main`

3. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)

Built from source

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

run `bin/logstash`

The following is printed on the command-line

```
robbavey@Robs-MacBook-Pro logstash % bin/logstash
Using system java: /Users/robbavey/.sdkman/candidates/java/current/bin/java
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      date (>= 0)
      Available/installed versions of this gem:
      - 3.4.1
      - 3.3.3
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
```

**Comment by donoghuc** [comment]
Investigation/analysis as to why this just started happening now: https://github.com/elastic/logstash/pull/16753#issuecomment-2518251941

**Comment by robbavey** [comment]
Closed by https://github.com/elastic/logstash/pull/16755
