### ISSUE TITLE
BufferedTokenizerExt does not clear size marker on flush

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#16762]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`): `6.x`->`9.x`

**Description of the problem including expected versus actual behavior**:

When a BufferedTokenizer emits events through its `flush` method, the buffer is cleared but the internal state tracking the size of the buffer is not reset ([link](https://github.com/elastic/logstash/blob/v8.16.1/logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java#L106-L110
)), resulting in subsequent use risking exceptions related to overfilling the buffer's size limit.

This is _especially_ true for cases where events are _only_ emitted through the flush method (e.g., sending json blobs without newline termination to the json_lines codec), in which case the metadata is never reset.

**Comment by jsvd** [comment]
fixed by https://github.com/elastic/logstash/pull/16760
