### ISSUE TITLE
Suspicious logstash mulitline behaviour

### ISSUE THREAD

**Issue by kosfar** [elastic/logstash#1677]
Hello all,
we use logstash-forwarder 0.3.1 and logstash 1.3.3 from the elasticsearch repo
We crashed on a very weird case with the following log line:
2014-08-28 11:55:05,112: ganeti-masterd pid=4426/ClientReq7 INFO
Received job poll request for 799610

The line has no newline inside it and we wonder what injected the
newline in the middle of the "request" string in the message field.
LSF or logstash? Is there some parameter that we should take into consideration? Several similar logs events come and go and are parsed correctly.

It seems that logstash received the event once as a mulitline event...

{:timestamp=>"2014-08-28T11:55:12.199000+0300", :message=>"filter
received", :event=>#<LogStash::Event:0x68d28bf2 @cancelled=false,
@data={"message"=>"2014-08-28 11:55:05,112: ganeti-masterd
pid=4426/ClientReq7 INFO Received job poll requ", "@version"=>"1",
"@timestamp"=>"2014-08-28T08:55:12.145Z", "type"=>"ganeti",
"file"=>"/var/log/ganeti/master-daemon.log", "host"=>"gnt-03",
"offset"=>"5291945", "log_type"=>"ganeti-master-log"}>, :level=>:info}

{:timestamp=>"2014-08-28T11:55:12.209000+0300", :message=>"filter
received", :event=>#<LogStash::Event:0x14423fb0 @cancelled=false,
@data={"message"=>"est for 799610", "@version"=>"1",
"@timestamp"=>"2014-08-28T08:55:12.151Z", "type"=>"ganeti",
"file"=>"/var/log/ganeti/master-daemon.log", "host"=>"gnt-03",
"offset"=>"5292033", "log_type"=>"ganeti-master-log"}>, :level=>:info}

{:timestamp=>"2014-08-28T11:55:12.230000+0300", :message=>"output
received", :event=>#<LogStash::Event:0x18dafb1a @cancelled=false,
@data={"message"=>"2014-08-28 11:55:05,112: ganeti-masterd
pid=4426/ClientReq7 INFO Received job poll requ\nest for 799610",
"@version"=>"1", "@timestamp"=>"2014-08-28T11:55:05.112+03:00",
"type"=>"ganeti", "file"=>"/var/log/ganeti/master-daemon.log",
"host"=>"gnt-03", "offset"=>["5291945", "5292033"],
"log_type"=>"ganeti-master-log", "tags"=>["multiline", "grokked",
"_multilinegrokparsefailure", "dated", "ganeti-unknown"],
"log_timestamp"=>"2014-08-28 11:55:05,112",
"proc_name"=>"ganeti-masterd", "proc_pid"=>"4426",
"ganeti_thread"=>"ClientReq7", "error_level"=>"INFO",
"ganeti_message"=>"Received job poll requ", "received_at"=>"2014-08-28
08:55:12 UTC"}>, :level=>:info}

... and once more after several minutes as a single line event

{:timestamp=>"2014-08-28T11:59:01.897000+0300", :message=>"filter
received", :event=>#<LogStash::Event:0x6736458d @cancelled=false,
@data={"message"=>"2014-08-28 11:55:05,112: ganeti-masterd
pid=4426/ClientReq7 INFO Received job poll request for 799610",
"@version"=>"1", "@timestamp"=>"2014-08-28T08:59:01.824Z",
"type"=>"ganeti", "file"=>
"/var/log/ganeti/master-daemon.log", "host"=>"gnt-03",
"offset"=>"5291945", "log_type"=>"ganeti-master-log"}>, :level=>:info}

{:timestamp=>"2014-08-28T11:59:01.931000+0300", :message=>"output
received", :event=>#<LogStash::Event:0x3041084c @cancelled=false,
@data={"message"=>"2014-08-28 11:55:05,112: ganeti-masterd
pid=4426/ClientReq7 INFO Received job poll request for 799610",
"@version"=>"1", "@timestamp"=>"2014-08-28T11:55:05.112+03:00",
"type"=>"ganeti", "file"=>"/var/log/ganeti/master-daemon.log",
"host"=>"gnt-03", "offset"=>"5291945",
"log_type"=>"ganeti-master-log", "proc_name"=>"ganeti-masterd",
"proc_pid"=>"4426", "ganeti_thread"=>"ClientReq7",
"error_level"=>"INFO", "received_at"=>"2014-08-28 08:59:01 UTC",
"tags"=>["grokked", "dated"]}>, :level=>:info}

Kindly,
Kostis

**Comment by jordansissel** [comment]
The behavior is very strange and I'm not sure what to make of it. Your first message is `INFO Received job poll requ` as if it gets cut off and continues in the next event. I don't have enough data to determine anything  that might help you, yet.

Are you still experiencing this? If so, can you provide you logstash and logstash-forwarder configs?

**Comment by kosfar** [comment]
Hi Jordan,
we have upgraded to logstash 1.4.2 but the random phantom multilines keep happening.

LSF configuration
{
    "network": {
                "servers": [ "logstash-broker:9999" ],
                "ssl ca": "/etc/logstash-forwarder.d/certs/server.crt",
                                                "timeout": 5
        },
    "files": [
                {
                    "paths": [ "/var/log/ganeti/node-daemon.log" ],
                                    "fields": { "log_type": "ganeti-node-log", "platform": "ganeti-test", "environment": "staging", "hostname": "our-server"  }
                },
    {
    }    
    ]
}

then there is a VM with a logstash input on port 9999 which filters like this for the specific log_type field value:
      multiline {
        pattern => "(^%{TIMESTAMP_ISO8601})"
        negate => true
        what => "previous"
      }
      mutate {
        add_tag => [ "redis-output" ]
      }

Redis queues the event and then another logstash instance pulls from redis and parses the events. But the harm has already been made as the events are already tagged for some reason with multiline.

**Comment by suyograo** [comment]
@kosfar can you update to 1.5? We fixed a bunch of issues in multiline filter

**Comment by kosfar** [comment]
After upgrading to 1.5, we have not experienced the problem again. Thanks!
