### ISSUE TITLE
Parse Failure slows down entire agent

### ISSUE THREAD

**Issue by galvinograd** [elastic/logstash#1678]
When logstash fails to parse a large log file with a large grok parse template, it slows down the entire agent's performance significantly. On the other hand, when the parsing succeeds, logstash is orders of magnitude faster.
Maybe it has something to do with exception handling?

**Comment by jordansissel** [comment]
We'll need a bit more information to go on. How do you observe the slowdown? Why do you think some kind of exceptions are the cause?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/41. Let's continue the discussion there! :)
