### ISSUE TITLE
Allow dynamic parsing of the timezone parameter to date filter

### ISSUE THREAD

**Issue by robinsmidsrod** [elastic/logstash#1685]
I'm using beaver to ship nginx error log to logstash, and it has an additional field with the timezone information from the server. I'd like to use the specified timezone to parse the timestamp properly.

```
if [tz] {
 date {
  match => [ "nginx_datestamp", "yyyy/MM/dd HH:mm:ss" ]
  timezone => "%{tz}"
  target => "nginx_timestamp"
 }
}
```

**Comment by webmstr** [comment]
+1.  No reason to not allow it.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-date/issues/23. Let's continue the discussion there! :)

**Comment by vishwastyagi** [comment]
Hi Everyone,
I am not to use date filter like the way mentioned above.
Help is required.
I have an xml which I am pushing into elasticsearch from logstash 

<Record><Date>2016-09-23</Date></Record>

My filter is:

filter{

 mutate {
       		 add_field => [ "nginx_timestamp", "/RECORD/DATE/text()" ]
    	}
    	date {
       		 match => [ "nginx_timestamp", "yyyy-MM-dd" ]
   	 }
    	mutate {
       		 remove_field => [ "nginx_timestamp" ]
    	}

}

I am getting warning in logstash saying:

"Failed parsing date from field {:field=>"nginx_timestamp", :value=>"/RECORD/DATE/text()", :exception=>"Invalid format: \"/RECORD/DATE/text()\"", :config_parsers=>"yyyy-MM-dd", :config_locale=>"default=en_IN", :level=>:warn}
"

And kibana is showing current date in @timestamp

Please help if I am missing anything.
