### ISSUE TITLE
Getting 'discover_file_glob' error message in logstash1.4.2 console output while trying to process vmstat output

### ISSUE THREAD

**Issue by pprasadrao** [elastic/logstash#1689]
Following is the logstash conf file which i am using. The log file input for it is generated based on redirecting vmstat command output. till yesterday it was working fine but suddenly it started giving 'discover_file_glob' error. Earlier i was using 1.4.0 and upgraded to 1.4.2 but the issue is same. Output is send to elasticsearch in local machine.
can you please let us know if there is any issue in the setup could cause this issue. i made sure the lnput file has proper permission.

====logstash conf
input {
 file {
       discover_interval => 60
       path => "/logstash/testLogs/vmstat.log"
 }
}
filter {
grok {
        match => ["message", "%{NUMBER:r:int}%{SPACE:space}%{NUMBER:b:int}%{SPACE:space}%{NUMBER:swapd:int}%{SPACE:space}%{NUMBER:free:int}%{SPACE:space}%{NUMBER:buff:int}%{SPACE:space}%{NUMBER:cache:int}%{SPACE:space}%{NUMBER:si:int}%{SPACE:space}%{NUMBER:so:int}%{SPACE:space}%{NUMBER:bi:int}%{SPACE:space}%{NUMBER:bo:int}%{SPACE:space}%{NUMBER:in:int}%{SPACE:space}%{NUMBER:cs:int}%{SPACE:space}%{NUMBER:us:int}%{SPACE:space}%{NUMBER:sy:int}%{SPACE:space}%{NUMBER:id:int}%{SPACE:space}%{NUMBER:wa:int}"]
    }
}
output {
  elasticsearch { }
}

====input log file content
 0  0      0 7535996  72612 232184    0    0     1     0   19   35  0  0 100  0
 0  0      0 7535988  72612 232188    0    0     0     5  283  532  0  0 100  0
 0  0      0 7535988  72620 232188    0    0     0     6  279  533  0  0 100  0
 0  0      0 7535988  72620 232188    0    0     0     7  275  530  0  0 100  0
 0  0      0 7536020  72628 232188    0    0     0     2  284  535  0  0 100  0

====logstash Console log
log4j, [2014-08-25T19:05:46.201] DEBUG: org.elasticsearch.cluster.service: [logstash-genieacs-VM1-23844-4010] set local cluster state to version 20
log4j, [2014-08-25T19:05:46.201] DEBUG: org.elasticsearch.cluster.service: [logstash-genieacs-VM1-23844-4010] processing [updating local node id]: done applying updated cluster_state (version: 20)
log4j, [2014-08-25T19:05:46.201]  INFO: org.elasticsearch.node: [logstash-genieacs-VM1-23844-4010] started
New Elasticsearch output {:cluster=>nil, :host=>nil, :port=>"9300-9305", :embedded=>false, :protocol=>"node", :level=>:info, :file=>"logstash/outputs/elasticsearch.rb", :line=>"252"}
Automatic template management enabled {:manage_template=>"true", :level=>:info, :file=>"logstash/outputs/elasticsearch.rb", :line=>"258"}
Using mapping template {:template=>"{  \"template\" : \"logstash-*\",  \"settings\" : {    \"index.refresh_interval\" : \"5s\"  },  \"mappings\" : {    \"_default_\" : {       \"_all\" : {\"enabled\" : true},       \"dynamic_templates\" : [ {         \"string_fields\" : {           \"match\" : \"*\",           \"match_mapping_type\" : \"string\",           \"mapping\" : {             \"type\" : \"string\", \"index\" : \"analyzed\", \"omit_norms\" : true,               \"fields\" : {                 \"raw\" : {\"type\": \"string\", \"index\" : \"not_analyzed\", \"ignore_above\" : 256}               }           }         }       } ],       \"properties\" : {         \"@version\": { \"type\": \"string\", \"index\": \"not_analyzed\" },         \"geoip\"  : {           \"type\" : \"object\",             \"dynamic\": true,             \"path\": \"full\",             \"properties\" : {               \"location\" : { \"type\" : \"geo_point\" }             }         }       }    }  }}", :level=>:info, :file=>"logstash/outputs/elasticsearch.rb", :line=>"278"}
_discover_file_glob: /logstash/testLogs/vmstat.log: glob is: ["/logstash/testLogs/vmstat.log"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /logstash/testLogs/vmstat.log: glob is: ["/logstash/testLogs/vmstat.log"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}

**Comment by jordansissel** [comment]
>  _discover_file_glob: /logstash/testLogs/vmstat.log: glob is: ["/logstash/testLogs/vmstat.log"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}

This is not an error message.

**Comment by jordansissel** [comment]
Closing this idle ticket. If you continue to have trouble, let us know.
