### ISSUE TITLE
Docs for conditionals aren't clear about what constitutes a true or false value 

### ISSUE THREAD

**Issue by timbunce** [elastic/logstash#1692]
For example, given `if [foo] { ... }` the docs don't make it clear when that expression will be false.

I presume it'll be false if there's no field of that name - but the doc's don't actually say that.
Will it be false if the field contains an empty string?
Or a numeric 0? Or a string "0"? Or an undefined/nil value?

Other clarifications are needed as well:
* there's no mention of operator precedence or associativity.
* the `in` operator has no documentation other than a list of examples, but they don't make it clear how `in` actually behaves when one side or the other is an array or a string.
* some operators will cause exceptions if the value they're applied to is of the wrong type (string instead of int or vice versa). Others silently fail to work.

That last point has caused me hours of difficulty a few months ago.

I continue to have a hard time with these basic issues and I'm not a newbie.

**Comment by dedemorton** [comment]
I’m trying to figure out what doc change are required for this PR.

When I read through to the end, it sounds like most of the confusion is around the fact that testing for “does field exist?” is indistinguishable from testing for “is field true?”

but is sounds like we can still do some things to make the doc better. Can you help me by answering these questions: 

What is the order of precedence for the operators that we support in  conditionals (listed in https://www.elastic.co/guide/en/logstash/master/event-dependent-configuration.html#conditionals)? 
How does the “in” operator behave? Does it return `true` if the value you’re testing for is in the specified string or array? Is there more we can/should say about this in the doc?
Can we say more about the types that are expected by specific operators? It sounds like the comparison operators for equality accept only numeric types and that the regexp operators only accept string types. Is that correct?

**Comment by dedemorton** [comment]
Accidentally deleted my previous comment, but here's what I think needs to go in the docs: a) list the operators in order of precedence, b) add more detail about the “in” operator, and c) explain which types are expected for specific operators.

**Comment by dedemorton** [comment]
Note that we've decided not to document operator precedence. Users should use parens in complex conditionals to be explicit.
