### ISSUE TITLE
Logstash collector "@timestamp" and spool

### ISSUE THREAD

**Issue by IsalineV** [elastic/logstash#1703]
Hi,

To centralise logs from multiples sources (multiples sites distributed in different locations) into a single location (main datacenter). I have a logstash "collector" in each remote location, they all push in a centralised logstash which push in ES for indexing and archive as final step.
I would like to secure the logs transfer path in case of network outage... and I'm trying to use/create a spool to put all logs in a temp buffer for this purpose. I can not lose any single log and would like to be 100% the communication between my logstash boxes, they can be resume without any humain intervention (keeping traces in this case is important).
I have two problems for now :
- When I am using the spool codec with a file, if the connexion is down, logs aren't store in the file and when the connexion is open again the field "@timestamp" is different from the event timestamp (for example, if I receive an event at 10:23am when the connexion between client and server is down, if my connexion is up at 10:50am the "@timestamp" is at 10.50am).
Moreover, when I close my connexion logs aren't store in the file but when it's open again they are send but with the wrong timestamp, and parse them when connexion is open again. But I need the event @timestamp and not the "open again connexion timestamp".

-If I use the file with the spool when my connexion is up and if hypothetically my logs are store in the file when connexion is close, when it's open again my logs are still in the file and they are not send with my output's plugin for open connexion.

Do you have anything to solve those problems ? Or any suggestions to help to do a plugin who can store logs at the good timestamp and send them like a buffer which is flushing logs gradually when connexion's up ?

Thanks :)

**Comment by jordansissel** [comment]
I don't think we have enough information to know how to help you.

Can you post some details? Seeing your logstash config, a sample event with the wrong `@timestamp`, and what you expected the timestamp to be, would help :)
