### ISSUE TITLE
GeoLite2 support

### ISSUE THREAD

**Issue by coder3000** [elastic/logstash#1709]
Will logstash support geolite2 in future? I am using geolite2 on server-side and there is some discrepancy caused by logstash. Specifying geolite2 db in geoip filter spits out errors.

**Comment by sdboer78** [comment]
+1

**Comment by chenryn** [comment]
any progress here? btw: I run a simple test about maxminddb and geoip, seems maxminddb is much slower than geoip...did anybody test those?

**Comment by garyelephant** [comment]
+1

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-geoip/issues/23. Let's continue the discussion there! :)
