### ISSUE TITLE
syslog input does not lookup IP addresses

### ISSUE THREAD

**Issue by Wilfred** [elastic/logstash#1713]
I've found that my logstash instance isn't doing reverse lookups for IP addresses if messages come in through the syslog input.

Have I configured it incorrectly, or is this a bug in logstash? My other inputs are happily converting IP addresses to hostnames.

**Comment by jordansissel** [comment]
DNS lookups are optional, and actually slow down performance quite a bit. If you need DNS lookups, then the dns filter should be useful for you: https://www.elastic.co/guide/en/logstash/current/plugins-filters-dns.html

Hope this helps :)

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-syslog/issues/16. Let's continue the discussion there! :)
