### ISSUE TITLE
Setting LS_WORKER_THREADS in /etc/sysconfig/logstash has no effect

### ISSUE THREAD

**Issue by alexjfisher** [elastic/logstash#1720]
The init.d file doesn't do anything with this variable.  It should add " -w ${LS_WORKER_THREADS}" to LS_OPTS

**Comment by alexjfisher** [comment]
The current logstash 1.4 rpm has this issue.  The 1.5 beta RPM doesn't.

**Comment by ph** [comment]
Since this issue is fixed 1.5 I'll close this.
