### ISSUE TITLE
Filterworker does not restart after exception.

### ISSUE THREAD

**Issue by devclef** [elastic/logstash#1721]
This may be the wrong issue, but was discovered during a load test and believed to be the underlying issue.

Setup:

```
RabbitMQ input with following settings:
    rabbitmq {
    host => ""
    queue => ""
    durable => true
    key => ""
    exchange => ""
    auto_delete => false
    ack => false
    threads => 1
    exclusive => false
    prefetch_count => 50
    port => 5672
    user => ""
    password => ""
    tags => ""
  }
```

LS agent was set with 2GB for the JVM, and let run. We are ingesting around 100k/minute, with a less than optimal filtering configuration. 

It was expected to let the LS agent to get behind to ensure that at some point it would stop receiving messages from MQ, and not crash.

Eventually this happened:

```
DefaultExceptionHandler: Consumer org.jruby.proxy.com.rabbitmq.client.DefaultConsumer$Proxy0@43f8a34c (amq.ctag-tmUVLzPlVJcp0Oe_GQ4vHg) method handleDelivery for channel AMQChannel(amqp://user@ip:5672/,1) threw an exception for channel AMQChannel(amqp://user@ip:5672/,1):
java.lang.OutOfMemoryError: Java heap space
```

and

```
Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Unknown Source)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Unknown Source)
```

The MQ started to fill up, and I started the other indexers to recover. I had expected the LS instance to recover and process the hundreds of thousands of messages it had ingested, but  it didn't.

It does this periodically

```
DefaultExceptionHandler: Consumer org.jruby.proxy.com.rabbitmq.client.DefaultConsumer$Proxy0@43f8a34c (amq.ctag-tmUVLzPlVJcp0Oe_GQ4vHg) method handleDelivery for channel AMQChannel(amqp://guest@10.9.201.136:5672/,1) threw an exception for channel AMQChannel(amqp://guest@10.9.201.136:5672/,1):
java.lang.OutOfMemoryError: Java heap space
```

Checking threads via top I never see a |worker thread start again. I could be entirely off, but if filter workers would start again, wouldn't the queue empty out and this LS agent recover?

I am confused if this is expected behaviour or not. I thought LS was suppose to set a sizeQueue of 20 and thus not take back up more messages than that? Why would it consume messages from rabbitMQ until it OOM's?

**Comment by thenom** [comment]
Hi,

Sorry to drag up old issues but i am having pretty much the same problem but with ACK set to true.  Also the logstash V2.0.0 (Don't seem to remember it happening in 1.5.x but am going to double check) collector does collect most of the logs but leaves a few un-ack'd in Rabbit.

This will continue over a period of time and the un-ack'd messages keep increasing until LS folds with this issue:

```
com.rabbitmq.client.impl.DefaultExceptionHandler: Consumer org.jruby.proxy.com.rabbitmq.client.DefaultConsumer$Proxy2@50b37528 (amq.ctag-94gr506hXuaRJyK2LLaJsw) method handleDelivery for channel AMQChannel(amqp://logstash@10.205.24.21:5672/,1) threw an exception for channel AMQChannel(amqp://logstash@10.205.24.21:5672/,1):
Exception in thread "pool-1-thread-4" java.lang.OutOfMemoryError: Java heap space
```

Increasing the heap size just seems to delay the inevitable.

If this is not an LS issue and lies now with the RabbitMQ input plugin dev then can you point me in their direction please.

Thanks.

**Comment by thenom** [comment]
I have just re-tested with 1.5.5 without changing anything else and this works fine.  No un-ack'd messages at all.

Processed 275124 messages.
