### ISSUE TITLE
win32ole failing

### ISSUE THREAD

**Issue by pf-nate-bennett** [elastic/logstash#1733]
Running most current RPMs on RHEL 6.5.  Commands to install:

```
1  yum localinstall https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.noarch.rpm
2  yum -y localinstall https://download.elasticsearch.org/logstash/logstash/packages/centos/logstash-1.4.2-1_2c0f5a1.noarch.rpm
3  yum -y localinstall https://download.elasticsearch.org/logstash/logstash/packages/centos/logstash-contrib-1.4.2-1_efd53ef.noarch.rpm
```

   10  history | grep localins

[root@ip-10-64-16-25 logstash]# tail -f logstash.err 
LoadError: load error: win32ole/win32ole -- java.lang.UnsatisfiedLinkError: /opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-win32ole-0.8.5/lib/racob-x64.dll: /opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-win32ole-0.8.5/lib/racob-x64.dll: invalid ELF header (Possible cause: endianness mismatch)
       require at org/jruby/RubyKernel.java:1085
       require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
       require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
       require at /opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/polyglot.rb:65
        (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-win32ole-0.8.5/lib/jruby-win32ole.rb:10
       require at org/jruby/RubyKernel.java:1085
       require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:135
       require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:133
       require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:124
       require at /opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/polyglot.rb:65
        (root) at /opt/logstash/lib/logstash/inputs/eventlog.rb:1
      register at /opt/logstash/lib/logstash/inputs/eventlog.rb:36
          each at org/jruby/RubyArray.java:1613
  start_inputs at /opt/logstash/lib/logstash/pipeline.rb:135
  start_inputs at /opt/logstash/lib/logstash/pipeline.rb:134
           run at /opt/logstash/lib/logstash/pipeline.rb:72
           run at /opt/logstash/lib/logstash/runner.rb:168
          call at org/jruby/RubyProc.java:271
       execute at /opt/logstash/lib/logstash/agent.rb:139

**Comment by JamesFischer-Stark** [comment]
I am using the Logstash1.5.3 release and still see this issue. 
![error1](https://cloud.githubusercontent.com/assets/13470204/9313471/2844a9ae-44f1-11e5-993c-b7cd5f564856.PNG)
![simple-conf](https://cloud.githubusercontent.com/assets/13470204/9313474/2951ee60-44f1-11e5-9ff2-4ad942a7135d.PNG)

Have any of you seen this?

**Comment by suyograo** [comment]
@JamesFischer-Stark would you mind opening a new issue with your environment details in it? `java -version` and such?

**Comment by JamesFischer-Stark** [comment]
Logstash-1.5.3 | load error: win32ole #3747
