### ISSUE TITLE
Refactor Logstash Rspec testing

### ISSUE THREAD

**Issue by electrical** [elastic/logstash#1737]
Along the way Logstash Rspec testing system has grown into an abomination.
This ticket is to list things that we need to fix in the first iteration.

- Move to Rspec 3
- Move all helper functions into their own modules and extend rspec
- Implement Docker support for testing against services
- Re-factor rspec files into correct naming convention and structure

**Comment by purbon** [comment]
Specially like this one

```Have plugins without tests cause a testing failure. (We can use a special rspec tag for this if desired.)```

will investigate how we can archive this in a nice way. :-)

**Comment by sherzberg** [comment]
Does this wiki page need updated as well with the current state of rspec tests? https://github.com/elastic/logstash/wiki/Tips:Testing-your-filters

While searching for how to write rspec tests, this wiki page came up and it looks like `test_utils` was renamed to `spec_helper`?

**Comment by sherzberg** [comment]
What was the resolution of this?
