### ISSUE TITLE
Sending invalid data to relp input crashes logstash

### ISSUE THREAD

**Issue by alexjfisher** [elastic/logstash#1742]
telneting to the relp port and entering garbage (then disconnecting) causes logstash to crash when the plugin tries to restart.

{:timestamp=>"2014-09-16T11:18:10.836000+0100", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Relp type=>\"haproxy\", host=>\"0.0.0.0\">\n  Error: Relp::ConnectionClosed", :level=>:error

**Comment by nicolasguyomar** [comment]
Hi @alexjfisher, I did try your patch and it solve @jamesbennet problem.
I did have the problem when I killed the nc connected to my logstash instance.
Thank you

**Comment by ph** [comment]
closing this one in favor of the https://github.com/logstash-plugins/logstash-input-relp/issues/5
