### ISSUE TITLE
Can't split strings with "\n" in mutate plugin.

### ISSUE THREAD

**Issue by chenryn** [elastic/logstash#1750]
I have a multiline message(php slow log), and had already grok part of it into a new field("stack"). But I can't split the new field string into an array by `mutate { split => ["stack", "\n"] }`. There is no error/warning messages, but just  put all data into new_field[0].

I try to use **filters/ruby** to write `event["stack"] = event["stack"].split("\n")`, and got what I want.

So, is there anything specially in **filters/mutate**?

**Comment by M0dM** [comment]
Hi,
I've found a workaround :
```
ruby {
  code => "event['message'] = event['message'].split(/\r?\n/)
}
```

**Comment by jiajie999** [comment]
@M0dM Thanks man!  it's working!

**Comment by suyograo** [comment]
Closing this issue in favor of https://github.com/elastic/logstash/issues/1645
