### ISSUE TITLE
Invalid mapping in ES allows for dropping events silently

### ISSUE THREAD

**Issue by jlintz** [elastic/logstash#1751]
I seem to have triggered a very odd behavior/bug last night.  I updated my ES mapping but typo'd "not_analyzed" for a field.  ES happily accepted the template, since it was valid JSON (anyone know how I can better validate this to catch these sort of things?).  When the indices went to rollover at midnight, no new index was created and logstash continued sending events to ES, but not logging any errors.  LSF continued sending events and since logstash thought everything was fine downstream in ES, it was ack'ing the events, so data was being silently dropped.

I'm not really sure what's at fault here so I'm opening the issue here as a start.  Is ES telling logstash it's indexing the events when it's not?

**Comment by DanielRedOak** [comment]
Very same thing just happened to me but the Logstash logs showed failed action with response of , dropping action: <event info>  Very bad behavior :(

**Comment by jordansissel** [comment]
This is fixed in 1.5

**Comment by jordansissel** [comment]
Many patches worked on this, but here's some:
* https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/2
* https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/49
* https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/62

**Comment by DanielRedOak** [comment]
I'll look those over, unfortunately this was happening for me on 1.5.0.rc2 from the tarball

**Comment by jordansissel** [comment]
Can you show the full log message?

**Comment by DanielRedOak** [comment]
Sure, here is one from the logs.  If you'd like the data portion too I can see about sanitizing it but its a large message:

{:timestamp=>"2015-03-16T16:16:07.963000-0500", :message=>"failed action with response of , dropping action: [\"index\", {:_id=>nil, :_index=>\"cloudtrail-logstash-2015.02.28\", :_type=>\"cloudtrail\"}, #<LogStash::Event:0x779c9f79 @metadata_accessors=#<LogStash::Util::Accessors:0x4a0763f5 @store={\"retry_count\"=>0}, @lut={}>, @cancelled=false, @logger=#<Cabin::Channel:0x4c17e968 @metrics=#<Cabin::Metrics:0x51c213a4 @metrics_lock=#<Mutex:0xd6ff0cb>, @metrics={}, @channel=#<Cabin::Channel:0x4c17e968 ...>>, @subscriber_lock=#<Mutex:0x5b9caebc>, @level=:warn, @subscribers={15592=>#<Cabin::Outputs::IO:0x69ad299f @io=#<File:/var/log/logstash/logstash.log>, @lock=#<Mutex:0x1b3675c9>>}, @data={}>, @data={ <REMOVED>

**Comment by JeanFrancoisContour** [comment]
Errors like this one "MapperParsingException[failed to parse [web_container_num]]; nested: NumberFormatException[For input string: "XXXXX"];"
are very likely to happen over time and I did not find any easy way to make them appear, in Logstash nor in Elasticsearch (found it with wireshark !). Any ideas (I'm sure you have some) ??
I'm not that familiar with the tools. 
thanks

**Comment by suyograo** [comment]
This has been handled in 1.5.0. See https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#_retry_policy

We log the mapping errors to stderr. Soon, we'll add these events to a dead letter queue
