### ISSUE TITLE
Elasticsearch http failure during template management will cause logstash to crash.

### ISSUE THREAD

**Issue by martinb3** [elastic/logstash#1756]
Sometimes when you start Elasticsearch and then Logstash right after, Elasticsearch is not yet listening on the http port before logstash tries to connect, yielding this error:

```
Faraday::ConnectionFailed: Connection refused - Connection refused
              call at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:44
    build_response at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139
       run_request at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/faraday-0.9.0/lib/faraday/connection.rb:377
   perform_request at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/http/faraday.rb:24
              call at org/jruby/RubyProc.java:271
   perform_request at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/base.rb:187
   perform_request at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/http/faraday.rb:20
   perform_request at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/client.rb:102
   perform_request at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.1/lib/elasticsearch/api/namespace/common.rb:21
      get_template at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.1/lib/elasticsearch/api/actions/indices/get_template.rb:24
  template_exists? at /opt/logstash/server/lib/logstash/outputs/elasticsearch/protocol.rb:132
  template_install at /opt/logstash/server/lib/logstash/outputs/elasticsearch/protocol.rb:21
          register at /opt/logstash/server/lib/logstash/outputs/elasticsearch.rb:259
              each at org/jruby/RubyArray.java:1613
      outputworker at /opt/logstash/server/lib/logstash/pipeline.rb:220
     start_outputs at /opt/logstash/server/lib/logstash/pipeline.rb:152
```

This is with a very simple output plugin in `/opt/logstash/server/etc/conf.d/output_elasticsearch.conf`:
```
output {
  elasticsearch {
    host => "127.0.0.1"
    protocol => "http"
  }
}
```

This immediate dependency on a running Elasticsearch seems to be related to index templates being configured on startup. It would be much, much more cloud-friendly if it could handle reconnecting and retrying so that if Elasticsearch has a bigger heap to allocate, it can take an extra second or two without causing Logstash to exit. Even just handling and retrying the `register at /opt/logstash/server/lib/logstash/outputs/elasticsearch.rb:259` would be a huge improvement, in case there are multiple output plugins.

I could see doing a sleep/reconnect like https://github.com/elasticsearch/logstash/pull/1299. It seems this would solve https://github.com/elasticsearch/logstash/issues/1745 and https://github.com/elasticsearch/logstash/issues/1717 too.

**Comment by cboettig** [comment]
+1

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/137. Let's continue the discussion there! :)
