### ISSUE TITLE
elasticsearch_http plugin should be deprecated

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#1757]
Since 1.4.0, the `elasticsearch` output plugin has supported `protocol => http`. This makes the `elasticsearch_http` now mostly duplicate and not needed anymore.

Let's mark it deprecated and provide users a helpful message for how to convert. For example, showing a full configuration example based on exactly their output config to convert it to elasticserach output:

```
The elasticsearch_http plugin has been merged into the elasticsearch output plugin. Please use this configuration instead:
output {
  elasticsearch {
    protocol => http
    < any relevant configuration we can provide for them based on their configuration >
  }
}
```

The message should be a warning and non-fatal.

**Comment by ph** [comment]
@jmara in logstash 1.5 you will be able to set a `user` and a `password` option when using the http protocol.

see: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L185-L186

**Comment by jmara** [comment]
Uhh nice :) and https support very cool thanks for letting me know!

**Comment by ph** [comment]
@jmara you are welcome :)

**Comment by untergeek** [comment]
@suyograo what exactly do you want me to document here?  Where do you want it documented?

**Comment by jsvd** [comment]
In 1.5.0 the plugin won't be there at all, we don't have a repo for it. So for me we can close this or at most open a documentation issue to warn users. would like some other opinion?

**Comment by ph** [comment]
We will create a non functional plugin that will abort logstash and will display the configuration to use with  the new elasticsearch output

**Comment by ph** [comment]
Graceful deprecation of the plugin.
https://github.com/logstash-plugins/logstash-output-elasticsearch_http/pull/1
