### ISSUE TITLE
zeromq overwrites host event tag if used as an agent-to-agent communication layer

### ISSUE THREAD

**Issue by nlloyd** [elastic/logstash#1762]
When using logstash in a client-server setup using zeromq to communicate between agents, the input zeromq agent on the server-side writes over the host field of the incoming events.

Compare:
https://github.com/elasticsearch/logstash/blob/master/lib/logstash/inputs/zeromq.rb lines 124 and 146
https://github.com/elasticsearch/logstash/blob/master/lib/logstash/inputs/file.rb lines 131 and 137

Then consider this setup:
web-server: file input and zeromq output
logs-server: zeromq input and elasticsearch-or-equivalent output

Result: all file log events in elasticsearch-or-equivalent have the host "logs-server" not "web-server".

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-zeromq/issues/2. Let's continue the discussion there! :)
