### ISSUE TITLE
plugins format vs message_format config inconsistencies

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#1770]
most codecs and some plugins use the `format` config but not 
- file output
- juggernaut output
- nagios_nsca output
- pipe output
- tcp output

which use `message_format`. 

shouldn't we just use `format` everywhere?

**Comment by colinsurprenant** [comment]
major version bump 3.0 is a perfect opportunity to make these changes.

**Comment by suyograo** [comment]
was deprecated in 2.0 https://github.com/elastic/logstash/pull/3950/files
