### ISSUE TITLE
remove redis input list_listener custom LUA

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#1780]
the custom LUA script used for batching items from list could be replaced with :

```ruby
redis.pipelined do
  redis.multi do
    redis.lrange(...)
    redis.ltrim(...)
  end
end
```

so basically, doing a lrange fetches a batch of items without deleting them, ltrim deletes them, wrapped in a multi to make this atomic and wrapped in a pipeline to avoid multiple network roundtrips.

**Comment by jordansissel** [comment]
This issue has been migrated to https://github.com/logstash-plugins/logstash-input-redis/issues/8
