### ISSUE TITLE
[Input-IRC] If the input crashes, reconnects, but doesn't drop old

### ISSUE THREAD

**Issue by coolacid** [elastic/logstash#1798]
If there is a bug in the IRC input plugin, logstash will restart the plugin. Unfortunatly, on restart, it's not checking to see if the connection already exists, thus you have multiple connections to IRC.

Bug in my code yielded :: 

    A plugin had an unrecoverable error. Will restart this plugin.
      Plugin: <LogStash::Inputs::Irc channels=>["##elk_dr", "#logstash"], host=>"irc.freenode.net", nick=>"LSTester", real=>"Ask CoolAcid", user=>"logstash"> 

When I finally killed logstash IRC reported:

    * LSTester___ has quit (Remote host closed the connection)
    * LSTester_ has quit (Remote host closed the connection)
    * LSTester__ has quit (Remote host closed the connection)
    * LSTester has quit (Remote host closed the connection)

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-irc/issues/11. Let's continue the discussion there! :)
