### ISSUE TITLE
Feature request: allow field to be set to analyzed or not_analyzed from within logstash

### ISSUE THREAD

**Issue by someperson** [elastic/logstash#1799]
I think it would be nice if we could set a field to be not_analyzed or analyzed in elasticsearch from logstash's configuration. I have no idea how easy or difficult this kind of thing would be to implement, but I figured I might as well throw it out there.

**Comment by jordansissel** [comment]
The best place for doing this is still with Elasticsearch index templates, I think. Going to close this.
