### ISSUE TITLE
Multiline needs to be more clear on not thread safe

### ISSUE THREAD

**Issue by coolacid** [elastic/logstash#1808]
Multiline documentation should be clearer that it's not thread safe - and that one needs to be careful to ensure the events pass though the same logstash instance to ensure the log lines can be processed by the same handler.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-multiline/issues/12. Let's continue the discussion there! :)
