### ISSUE TITLE
Not binding to ports when running as regular user

### ISSUE THREAD

**Issue by cdenneen** [elastic/logstash#1814]
Wanted to bring back:

https://logstash.jira.com/browse/LOGSTASH-840

Since running as logstash user can't open ports <1024. 
Is there any documented work around for this? Would be nice for logstash to ingest 514 for central syslog but not have to run as root to do so.

**Comment by jordansissel** [comment]
I think this is solved, given:

* Systems require privileged access to bind on ports 1-1023 (< 1024)
* This can be worked around with iptables, setcap, etc
