### ISSUE TITLE
split seems to prevent the usage of grok

### ISSUE THREAD

**Issue by gthvn1** [elastic/logstash#1820]
When I use _split_ I can not use _grok_ anymore. To reproduce what I see you can use exec input where the command is a _cat_ of a file that contains _"a test"_ for example and here is the filter:

```
filter {
    split { }
    grok { match => ["message", "(?<aTest>[a-zA-Z]+)"] }
}
```

I see:

```
      "message" => "justatest",
      "@version" => "1", 
   "@timestamp" => "2014-10-01T12:52:08.297Z", 
         "type" => "testing",
          "host" => "3bcf8babea32",
       "command" => "cat /tmp/test"
}
```

but If I comment the _split { }_ I see:

```
{
       "message" => "justatest\n",
      "@version" => "1",
    "@timestamp" => "2014-10-01T12:50:00.789Z",
          "type" => "testing",
          "host" => "3bcf8babea32",
       "command" => "cat /tmp/test",
         "aTest" => "justatest"
}

```

So the field _aTest_ has been added. And I also noticed that the message has a '\n' without using split

So can we use _split {}_ and after _grok {}_ ?

**Comment by beeblebrox** [comment]
I'm having the same/similar issue with 1.4.  I'm using the stdin input.  The input has newlines and I'm using split to emit multiple events based a different delimiter in the event ("/").  Afterwards I am attempting to use grok again and it does not work.  Using the codec line for the input does not workaround the issue.
Config:
```
input {
  stdin { codec => "line" }
}
filter {
        split {
                terminator => "/"
        }
}
filter {
        grok {
                match => ["message", "(?<message_again>.*)"]
        }
}

output {
  stdout { codec => "rubydebug"}
}
```

Result:
```
this/test
Using milestone 2 filter plugin 'split'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}

{
       "message" => "this",
      "@version" => "1",
    "@timestamp" => "2015-03-13T03:54:17.944Z",
          "host" => "jhart"
}
{
       "message" => "test",
      "@version" => "1",
    "@timestamp" => "2015-03-13T03:54:17.944Z",
          "host" => "jhart"
}
```
Typing using a value without a split results in the correct message_again field.
Is there a workaround?

**Comment by beeblebrox** [comment]
Created a new case (#2816) as this one is closed.
