### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by facundofarias** [elastic/logstash#1821]
On the web page (logstash.net), going to docs, and then getting started with logstash, when we want to see the logs on elasticsearch, the code should be:
*logstash -e 'input { stdin { } } output { elasticsearch { host => localhost protocol => "http" port => "9200" } }'*
Otherwise an exception is thrown (org.elasticsearch.discovery.MasterNotDiscoveredException: waited for [30s])

If you can guide me about how to update this, I can do it :)
Thanks

**Comment by krinkere** [comment]
+1

**Comment by suyograo** [comment]
I am closing this issue. Let me know if things are still not working for you @facundofarias
