### ISSUE TITLE
Commit History Cleanup

### ISSUE THREAD

**Issue by cdenneen** [elastic/logstash#1825]
Can someone remove this from the commit history:

2c5a955fc89df67e6aac08bfddac4db723ff222d 69535125 debian/debian/logstash.war

git filter-branch --prune-empty --index-filter 'git rm -rf --cached --ignore-unmatch debian/debian/logstash.war' --tag-name-filter cat -- --all

**Comment by jordansissel** [comment]
I'm still in favor of doing this, especially on master. However, it will break _every_ open pull request because Github's perspective on PRs is based on history, not on code diffs.

**Comment by suyograo** [comment]
Its too tricky to do this at this time, and we'll have to revisit if there are more complaints. Closing this for now
