### ISSUE TITLE
rubydebug doc page is misleading

### ISSUE THREAD

**Issue by jetblack87** [elastic/logstash#1833]
The documentation page for rubydebug code is misleading: http://logstash.net/docs/1.4.2/codecs/rubydebug

It contains an example for using rubydebug for input despite the fact that the codec is not implemented for input: https://github.com/elasticsearch/logstash/blob/v1.4.2/lib/logstash/codecs/rubydebug.rb
<pre>
public
def decode(data)
   raise "Not implemented"
end # def decode
</pre>

**Comment by jordansissel** [comment]
I think this should be resolved by #1569

**Comment by suyograo** [comment]
Closing this in favor of #1569
