### ISSUE TITLE
custom patterns - permissions denied

### ISSUE THREAD

**Issue by mcgkev29** [elastic/logstash#1841]
I setup a custom pattern file in /opt/logstash/patterns/patterns/

when I restart the service logstash will not work/filter logs

when I review the logstash logs in /var/log/ I see this:
The error reported is: \n  Permission denied - /opt/logstash/patterns/patterns"}

these are the permissions though:
drw-rw-rw- 2 logstash logstash 4096 Oct  3 10:02 patterns

here is my filter clause:
grok {
       break_on_match => "true"
        patterns_dir => "./patterns"

**Comment by MrShine** [comment]
There seems to be a general problem with folders placed in the *patterns* folder. Move your custom *patterns* folder outside the patterns folder and you should be fine. (Tested with logstash-1.4.2)

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/38. Let's continue the discussion there! :)
