### ISSUE TITLE
Grok matching syslog

### ISSUE THREAD

**Issue by luongvinhthao** [elastic/logstash#1846]
I used Rsyslog  send to logstash. I write grok like match => { "message" => " %{GREEDYDATA:OS_message}" }.That i get OS_message : controller 2014-10-06 12:27:47.536 1142 WARNING keystone.common.controller [-] RBAC: Bypassing authorization
But when i change match => { "message" => " %{HOSTNAME:hostname} %{GREEDYDATA:OS_message}" }. I get hostname is 00.So,I try to test with grokdebug, i get hostname controller. Anybody can help me explain it.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/25. Let's continue the discussion there! :)
