### ISSUE TITLE
Error while using logstash just as a Gelf Router

### ISSUE THREAD

**Issue by rikatz** [elastic/logstash#1847]
Using logstash with input gelf, and output gelf to another server (in this case, a graylog2 server), the following error occurs:

Using milestone 2 input plugin 'gelf'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Using milestone 1 input plugin 'syslog'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Using milestone 2 output plugin 'gelf'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
NoMethodError: undefined method `join' for "_grokparsefailure":String
        receive at /opt/programas/logstash/lib/logstash/outputs/gelf.rb:179
         handle at /opt/programas/logstash/lib/logstash/outputs/base.rb:86
     initialize at (eval):38
           call at org/jruby/RubyProc.java:271
         output at /opt/programas/logstash/lib/logstash/pipeline.rb:266
   outputworker at /opt/programas/logstash/lib/logstash/pipeline.rb:225
  start_outputs at /opt/programas/logstash/lib/logstash/pipeline.rb:152

Here is the logstash.conf file:

input 	{ 
	gelf {
	}
	syslog {
		port => 1514
	}
}

output {
	gelf {
		host => "192.168.0.12"
	}
}

Thanks in advice

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-gelf/issues/2. Let's continue the discussion there! :)
