### ISSUE TITLE
Weekly indicies

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/logstash#1848]
I've just started using weekly indices (Kibana speak myindex-GGGG.WW) with my ELK stack, but finding each component has a different idea of week numbers:

Kibana: http://momentjs.com/docs/#displaying/format/
Logstash: http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html
Curator: https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

Would it be possible for logstash to support the ISO8601 style week/year system, which is well defined and also what Kibana uses?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/133. Let's continue the discussion there! :)
