### ISSUE TITLE
config logic is broken ( if [type] in ['syslog'] fails ) 

### ISSUE THREAD

**Issue by JohnTheodore** [elastic/logstash#1850]
I looked at the debug output, it turns ['syslog'] into a field reference.

This fails  : if [type] in ['syslog']
This works: if [type] in ['foobar', 'iMadeThisUpAndDoNotWantThisVariable']
This works: if [type] == 'foobar'

**Comment by theanotherwise** [comment]
any news lol :D? the statement is really useful
