### ISSUE TITLE
Logstash export to gelf stops sending packages

### ISSUE THREAD

**Issue by ypasmk** [elastic/logstash#1856]
A simple configuration to export events from a file to graylog2 stops after sending some of them 

input{
    file {
        type => "myparser"
        path => [ "/tmp/myfile2.csv" ]
        sincedb_path => "/dev/null"
        start_position => "beginning"
    }
}

output {
    gelf{
        host => "xx.xx.xx.xx"
        port => 12201
        short_message => "my_message"
    }
}

myfile2.csv contains 100.000 records ... logstash stops sending messages when it comes around 20.000 .. randomly ... if I use 10.000 records in my source file then it stops at around 5.000 (randomly every time).... If I start logstash with -vvv then it comes almost at the end ... 99.997 one time ...

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-gelf/issues/3. Let's continue the discussion there! :)
