### ISSUE TITLE
Logstash not using /etc/default/logstash environment variables

### ISSUE THREAD

**Issue by vspiewak** [elastic/logstash#1866]
I installed Logstash from official .deb repository.
I set a custom Java JRE in /etc/default/logstash. (JAVACMD=/opt/jre/bin/java)
Logstash init.d script launch Logstash without the proper JAVACMD value.
It seems chroot exec command doesn't forward the environment properties

I fixed it adding in /opt/logstash/bin/logstash:
. "/etc/default/logstash"

**Comment by suyograo** [comment]
Fixed. Please reopen if it happens in later versions
