### ISSUE TITLE
Mutate ignores the configuration's operator order

### ISSUE THREAD

**Issue by ndelucin** [elastic/logstash#1877]
Hi,

I discovered a strange issue regarding mutate evaluation.
Don-t know if its a bug or a normal behavior of the Logstash "interpreter"...

Let me explain...
I have a "hostname" field containing a FQDN such like "mycomputer.my.domain.com"
Aim is to "clean" this field to only store the computer name (1st part of FQDN):
hostname="mycomputer.my.domain.com" => filtering => hostname="mycomputer"

So I applied the following filter{} in my logstash conf file:
```
filter {
	mutate {
		split => ["hostname", "."]
		add_field => { "shortHostname" => "%{hostname[0]}" }
		rename => ["shortHostname", "hostname" ]
	}
```

but, it did not work at all. Here is stdout:
```
{
"message" => "a\r",
"@version" => "1",
"@timestamp" => "2014-10-10T15:37:57.485Z",
"hostname" => [
        [0] "mycomputer",
        [1] "my",
        [2] "domain",
        [3] "com"
],
"host" => "LFR003256",
"shortHostname" => "mycomputer"
}
```

***BUT !!*** If I re-arrange instructions into 2 distinct mutate blocks like this:
```
filter {
	mutate {
		split => ["hostname", "."]
		add_field => { "shortHostname" => "%{hostname[0]}" }
	}

	mutate {	
		rename => ["shortHostname", "hostname" ]
	}
}
```

Then it works like a charm:
```
{
"message" => "a\r",
"@version" => "1",
"@timestamp" => "2014-10-10T15:32:57.077Z",
"hostname" => "mycomputer",
"host" => "LFR003256"
}
```

Do you know why ?

Thanks !

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-mutate/issues/28. Let's continue the discussion there! :)
