### ISSUE TITLE
Pagerduty output queuing?

### ISSUE THREAD

**Issue by cschotke** [elastic/logstash#1879]
We had an application issue today which generated a very large amount of errors in its log. We are monitoring the logfile with logstash and sending errors to PagerDuty using the PagerDuty output. We use Throttle to make sure a maximum of 50 errors are passed to the PagerDuty output every minute (to avoid PD rate limiting which kicks in at 60 per minute). Somehow, we are still receiving incidents in PD which are timestamped over an hour ago. Is there something within Logstash or the PD output which could be queuing up these messages? 

Thanks

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-pagerduty/issues/4. Let's continue the discussion there! :)
