### ISSUE TITLE
NameError: uninitialized constant I18n::Config::Set

### ISSUE THREAD

**Issue by wajiii** [elastic/logstash#1882]
When I try to start a "1.5.0.dev-1" agent built out of the repository (on RHEL5), I get: 
NameError: uninitialized constant I18n::Config::Set
               const_missing at org/jruby/RubyModule.java:2690
       available_locales_set at /opt/logstash/vendor/bundle/jruby/1.9/gems/i18n-0.6.11/lib/i18n/config.rb:47
           locale_available? at /opt/logstash/vendor/bundle/jruby/1.9/gems/i18n-0.6.11/lib/i18n.rb:277
  enforce_available_locales! at /opt/logstash/vendor/bundle/jruby/1.9/gems/i18n-0.6.11/lib/i18n.rb:285
                   translate at /opt/logstash/vendor/bundle/jruby/1.9/gems/i18n-0.6.11/lib/i18n.rb:150
                       Agent at /opt/logstash/lib/logstash/agent.rb:8
                      (root) at /opt/logstash/lib/logstash/agent.rb:7
                     require at org/jruby/RubyKernel.java:1085
                      (root) at file:/usr/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
                         run at /opt/logstash/lib/logstash/runner.rb:138
                        call at org/jruby/RubyProc.java:271
                         run at /opt/logstash/lib/logstash/runner.rb:158
                        call at org/jruby/RubyProc.java:271
                     require at file:/usr/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55

**Comment by suyograo** [comment]
@wajiii we have replaces make with rake now. would love your feedback on it! See https://github.com/elasticsearch/logstash#developing
