### ISSUE TITLE
Regex/grok patterns

### ISSUE THREAD

**Issue by gerdesj** [elastic/logstash#1884]
Grok patterns are a pretty fundamental utility for getting information out of many logs and are regularly combined with conditionals in the filter phase.

It would be useful to generalize grok patterns to the entire system, say by relabelling them regex patterns and being able to access them in all places where applicable.  For example something like this:

if [m] =~ /stuff ${PATTERN2} and other stuff/ { 
   grok { match => [ "m", "%{PATTERN1:p1}%{PATTERN2:p2}%{PATTERN3:p3}" ] }
}

I'm not sure what the correct syntax would be but the above tripped off the keyboard.  My example is a bit artificial.

**Comment by suyograo** [comment]
This is not an enhancement we will be tackling at this point. Closing
