### ISSUE TITLE
rspec helper for configuration Inputs/Outputs/filters 

### ISSUE THREAD

**Issue by ph** [elastic/logstash#1890]
Every plugins use some sort of configuration, it will help create the minimal tests for each plugin to have some sort of helpers to test them. We could take https://github.com/thoughtbot/shoulda-matchers as an inspiration.

- This will complete the pipeline helpers
- help us with the deprecated config

**Comment by purbon** [comment]
nice, love the idea.

**Comment by purbon** [comment]
working on this.

**Comment by purbon** [comment]
An initial work on that has been done at https://github.com/elastic/logstash-test-helpers with the intention to provide a common place for having shared helpers for developers (core and plugin) and for configuration testing too.

**Comment by sherzberg** [comment]
What was the resolution of this?

**Comment by purbon** [comment]
we recently revamped this again in regards of the current push for more complete testing framework. Keep you posted.
