### ISSUE TITLE
Errno::EBADF: Bad file descriptor - Bad file descriptor

### ISSUE THREAD

**Issue by rightm** [elastic/logstash#1903]
I just install logstash in a new environment . logstash version is 1.4.2 and jdk version is jdk1.7.0_60.
The logstash crushed when starting.does anyone know why ?the error below:

Using milestone 2 input plugin 'redis'. This plugin should b     e stable, but if you see strange behavior, please let us know! For more information on plugi     n milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Using milestone 2 output plugin 'elasticsearch_http'. This plugin should be stable, but if y     ou see strange behavior, please let us know! For more information on plugin milestones, see      http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Errno::EBADF: Bad file descriptor - Bad file descriptor
          close at org/jruby/RubyIO.java:2097
        connect at /data01/frontend/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/l     ib/ftw/connection.rb:173
           each at org/jruby/RubyArray.java:1613
        connect at /data01/frontend/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/l     ib/ftw/connection.rb:139
        connect at /data01/frontend/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/l     ib/ftw/agent.rb:406
           call at org/jruby/RubyProc.java:271
          fetch at /data01/frontend/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/l     ib/ftw/pool.rb:48
        connect at /data01/frontend/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/l     ib/ftw/agent.rb:403
        execute at /data01/frontend/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/l     ib/ftw/agent.rb:319
           get! at /data01/frontend/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/l     ib/ftw/agent.rb:217
       register at /data01/frontend/logstash-1.4.2/lib/logstash/outputs/elasticsearch_http.r     b:117
           each at org/jruby/RubyArray.java:1613
   outputworker at /data01/frontend/logstash-1.4.2/lib/logstash/pipeline.rb:220
  start_outputs at /data01/frontend/logstash-1.4.2/lib/logstash/pipeline.rb:152

**Comment by qwerty55** [comment]
Honestly, this is why people get frustrated with ruby in general. The error messages are difficult for non-ruby programmers to interpret.

The only clue that this was a connectivity issue to elasticsearch was this line near the bottom of the stack trace:
"register at /data01/frontend/logstash-1.4.2/lib/logstash/outputs/elasticsearch_http.r b:117"

How is a non-ruby programmer supposed to really understand that?

 In this particular case, logstash could have been written to catch the error or, even better yet, validate the connection configuration to elasticsearch before outputting an error message such as: "Connectivity to elasticsearch at http://localhost:9200 unreachable".
