### ISSUE TITLE
[logstash 1.4.2] : error with sincedb with multi file

### ISSUE THREAD

**Issue by Ced1984** [elastic/logstash#1907]
hello,
When we define more than one file in the input entry, the new log files lines are not seen:

input {
  file {
    type => "log4j"
    path => "/usr/users/gacna*/DATA/ARE/LOG/*.log"
  }
}
 
The .sincedb file contains only one line:
 cat .sincedb_498811a631a0364cebbcb69f2a736b2a
0   440023

This error appears in version 1.4.2.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/30. Let's continue the discussion there! :)
