### ISSUE TITLE
[logstash-1.4.1] Trouble parsing csv _csvparsefailure exception=>#<CSV::MalformedCSVError: Illegal quoting in line

### ISSUE THREAD

**Issue by bpesics** [elastic/logstash#1908]
The csv filter fails to parse a message and does not provide information on what is the problem with the input text.

logstash version and os:
```
logstash-contrib-1.4.1-1_6e42745.noarch
logstash-1.4.1-1_bd507eb.noarch

CentOS release 6.5 (Final)
```

the configuration:
```
input {
  file {
    path           => ["/path/to/testfile"]
    start_position => "beginning"
    codec          => plain {
      charset      => "UTF-8"
    }
  }
}

filter {
    csv {
      separator => ",,,,"
      columns   => [ "db_host", "start_time", "user_host", "query_time", "lock_time", "sql_text", "db" ]
    }
}

output {
  stdout { codec => rubydebug }
}
```

the error message:
```
Trouble parsing csv {:source=>"message", :raw=>"
....
:exception=>#<CSV::MalformedCSVError: Illegal quoting in line 1.>, :level=>:warn}
````
````
...
      "@version" => "1",
    "@timestamp" => "2014-10-16T16:09:14.559Z",
          "host" => "some.domain.tld",
          "path" => "/path/to/testfile",
          "tags" => [
        [0] "_csvparsefailure"
    ]
}
````

the content of the test file can be found here: https://gist.githubusercontent.com/bpesics/a2af6e6b585499081de5/raw/bdbda0cf4bbde052d33307854f72f2d788631b00/gistfile1.txt

**Comment by Rumbles** [comment]
Just a question, why is your separator 5 commas? Do you really have 5 commas between each field in your CSV? Or did you mean there are 5 fields? If the second option is right then you don't need to define it, the default should work fine:

http://logstash.net/docs/1.4.2/filters/csv#separator

I wouldn't be surprised if that's what is causing your issue, although better error messages would be good.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-csv/issues/11. Let's continue the discussion there! :)
