### ISSUE TITLE
Unable to delete old log files since logstash does not close active connections on them

### ISSUE THREAD

**Issue by ramreddy26** [elastic/logstash#1922]
Hi,

Currently I am parsing only last 7 days of IIS, HTTP logs using logstash shipper(windows). I am trying to delete the log files which are older than 7 days but I am unable to delete the old log files while logstash service is running. Is there a way to close the active connections on old files without stopping the service? So that I could delete them.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/31. Let's continue the discussion there! :)
