### ISSUE TITLE
Date filter truncates rather than rounds input

### ISSUE THREAD

**Issue by gerdesj** [elastic/logstash#1926]
I use %{SYSLOGBASE2} to parse the start of an RSyslog event.

Filter to get the date stamp from the original event:
date { match => [ "timestamp8601", "ISO8601" ] }

Example output in ES:
timestamp8601  2014-10-21T11:48:21.646972+01:00
@timestamp  2014-10-21T10:48:21.646Z

.646972 has been truncated to .646 rather than rounded to .647

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-date/issues/20. Let's continue the discussion there! :)
