### ISSUE TITLE
logstash-forwarder doesn't work with ipv6 address

### ISSUE THREAD

**Issue by soichih** [elastic/logstash#1935]
I have a logstash server running locally with following host name

2014-10-22 15:06:59 UTC [root@soichi6:/etc/grid-security/logstash]# host soichi.goc
soichi.goc has address 192.168.97.116
soichi.goc has IPv6 address fd2f:6feb:37:1::74

I have installed logstash-forwarder from http://packages.elasticsearch.org/logstashforwarder/centos/logstash-forwarder-0.3.1-1.x86_64.rpm and configured logstash-forwarder.conf as following

{
  "network": {
    "servers": [ "soichi.goc:5000" ],
    "timeout": 15,
    "ssl ca": "/etc/grid-security/logstash/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [
        "/var/log/messages",
        "/var/log/secure"
       ],
      "fields": { "type": "syslog" }
    }
   ]
}

When I start the forwarder, I see following log.

2014/10/22 15:04:56.617328 Connecting to fd2f:6feb:37:1::74:5000 (soichi.goc)
2014/10/22 15:04:56.617365 Failure connecting to fd2f:6feb:37:1::74: too many colons in address fd2f:6feb:37:1::74:5000

So, soichi.goc is resolved to the ipv6 address, and logstash-forwarder doesn't seem to like the ipv6 address. Is there any workaround to this?

**Comment by suyograo** [comment]
Opened https://github.com/elastic/logstash-forwarder/issues/504
