### ISSUE TITLE
Elasticsearch Output Drop Events Sent to Closed Index

### ISSUE THREAD

**Issue by detoor** [elastic/logstash#1937]
In our use case of logstash we have two outputs, Flume (long term archive), ES (short term search).  Occasionally old data is processed and logstash will attempt to write it to a closed index in ES.  This appears to eventually lead to logstash failing to write to either output (even for current/new data) as logstash continually attempts to write the old data to the closed index.

```
output {
	tcp {
		host => "FLUMEHOST"
		port => 4242
		mode => "client"
		codec => "json_lines"		
	}

	elasticsearch {
    host => "ESHOST"
	node_name => "LogstashMaster-one"
	cluster => "clustername"
	index_type => "%{logType}"
	}
}
```
One possible work-around/fix might be to expose the "ignore_unavailable" ES flag to the logstash elasticsearch output.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/134. Let's continue the discussion there! :)
