### ISSUE TITLE
logstash multiline filter: last part of message flush

### ISSUE THREAD

**Issue by tudit** [elastic/logstash#1938]
There was a know issue in the multiline filter that it doesn't print the last part of the input being filtered as it is still waiting for a pattern to follow and it isn't flushed out. 
Has the issue been resolved. If so how?Is there a tag to flush out the last part?

**Comment by rajacm2020** [comment]
While using enable_flush it works fine. But when using the grok match filter after the flush of events, the tag values gets duplicated. Is there any fix for it ?

**Comment by corey-cole** [comment]
I'm trying out 1.5.0RC2, but I'm not seeing any change when the terminal event is a multiline event.

I've distilled the example into a [gist](https://gist.github.com/corey-cole/94279e100b0e7561c696).

**Comment by harveysun** [comment]
Dear Logstash Team,
         I downloaded the logstash-1.5.0.tar.gz and test multiline filter fund the issue still exist.
         The last part of message couldn't flush out.
         Could you please show an example in the logstash-1.5.0? thanks in advance

**Comment by wanghq** [comment]
@harveysun, as others mentioned, you can use the multiline filter (not multiline codec):
https://www.elastic.co/guide/en/logstash/current/plugins-filters-multiline.html.
