### ISSUE TITLE
Logstash-forwarder: file lock

### ISSUE THREAD

**Issue by Neophyteone** [elastic/logstash#1944]
Hi, Logstash-forwarder running on windows from current fork.
I have an application that writes logs into a directory, and rotates them every night.

Logstash-forwarder does not release read-lock on the files and the files cannot be moved, 

"File is open in another process, logstash-forwarder"

This has been discussed alot: https://github.com/elasticsearch/logstash-forwarder/issues/77
Me and alot of other would appreciate a fix on this, it makes the product unusable for the moment unfortuenaly.

Thanks

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/elastic/logstash-forwarder/issues/464. Let's continue the discussion there! :)

**Comment by jordansissel** [comment]
(Moved to the logstash-forwarder project)
