### ISSUE TITLE
if check / mutate plugin misbehave when looking up a value in a hash, but an array is present instead

### ISSUE THREAD

**Issue by rarruda** [elastic/logstash#1948]
Given this input: (field Properties is an Array of Hashes, which is kind of evil in it self)
````
{"@version":"1","@timestamp":"2014-10-23T00:00:27.548+02:00","message":"stuff","Properties":[{"TRACE_ID":"8989430706579930843"}]}
````

And using a if check for different values of [Properties]
````
filter {
    if [Properties][UNIQUE_ID] {
      mutate { add_field => [ 'unique_id', '%{[Properties][UNIQUE_ID]}' ] }
    }
    if [Properties][remote_ip] {
      mutate { add_field => [ 'client_ip', '%{[Properties][remote_ip]}' ] }
    }
    if [Properties][client_ip] {
      mutate { add_field => [ 'client_ip', '%{[Properties][client_ip]}' ] }
    }
}
````

Logstash will act in rather unexpected way:
````
{
              "@version" => "1",
            "@timestamp" => "2014-10-23T00:00:27.548+02:00",
               "message" => "stuff",
            "Properties" => [
        [0] {
            "TRACE_ID" => "8989430706579930843"
        }
    ],
             "unique_id" => "{\"TRACE_ID\":\"8989430706579930843\"}",
             "client_ip" => [
        [0] "{\"TRACE_ID\":\"8989430706579930843\"}",
        [1] "{\"TRACE_ID\":\"8989430706579930843\"}"
    ]
}
````

While I am fully aware that one should not input an JSON array, and try to access it as a Hash, this is rather unexpected behaviour.

This is a workaround:
````
    if [Properties][UNIQUE_ID] =~ /.*/ {
      mutate { add_field => [ 'unique_id', '%{[Properties][UNIQUE_ID]}' ] }
    }
````
But seems like rather akward to use it.

Also worth noting that besides the unexpected behaviour, logstash slowsdowns quite a bit when it hits this issue. Also note, that this is was triggered by a bug in our json logger (of writing an array of hashes, instead of a simple hash with multiple values), which is now fixed, but as this can throw people off when hitting this same issue, It seems to be like it should be addressed anyhow.

**Comment by suyograo** [comment]
This has been fixed. Please reopen if still an issue
