### ISSUE TITLE
tcp input SSL chain/CA configuration issues

### ISSUE THREAD

**Issue by MikeN123** [elastic/logstash#1956]
At the moment, the SSL configuration options of the tcp input are fairly limited, and some are even useless. The following issues exist:

* It is not possible to specify `extra_chain_cert` for the server certificate, thus if a certificate chain is necessary this can only come from the CA store.
* The CA store (system-store or specified file) is only activated if `ssl_verify = true` (requiring client verification), so without client verification it is not possible to send a proper certificate chain.
* The system-store is always included if `ssl_verify = true`, making client certificate validation useless, since a client can send any certificate from any recognised CA, for any name.

I propose the following changes:

* Allow `extra_chain_cert` to be set, to specify a certificate chain (extra property)
* Allow the certificate store to be initialised from the system store even when not using client certificates (extra property: `ssl_set_default_paths` or something like that, and moving a couple of lines of code)
* Do not use the system store for client certs by default (i.e., make the previous property `false` by default). This may break existing configurations (but in these cases the peer verification was probably useless anyway).

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-tcp/issues/9. Let's continue the discussion there! :)
