### ISSUE TITLE
Regarding stop logstash automaticaly

### ISSUE THREAD

**Issue by upbalshetwar** [elastic/logstash#1960]
Hi,

I used time-out option in pipeline.rb and  integrated with groovy & grail application but here logstash is stopping but they are giving call to grail & groovy application context for stopping so complete application is down.
Please check my code from pipeline.rb
def filterworker
    LogStash::Util::set_thread_name("|worker")
    begin
      while true	 
	  Timeout.timeout(10) do 	   
        event = @input_to_filter.pop
        if event == LogStash::ShutdownSignal
          @input_to_filter.push(event)		  
          break
        end
        # TODO(sissel): we can avoid the extra array creation here
        # if we don't guarantee ordering of origin vs created events.
        # - origin event is one that comes in naturally to the filter worker.
        # - created events are emitted by filters like split or metrics         
		events = [event]
        filter(event) do |newevent|
          events << newevent
        end
        events.each do |event|		
          next if event.cancelled?
          @filter_to_output.push(event)		  
        end	
	   end
      end	  
    rescue => e		  
	  shutdown_outputs	
          wait_outputs	
	 shutdown_filters
        wait_filters
      @logger.error("Exception in filterworker", "exception" => e, "backtrace" => e.backtrace)
    end	
    @filters.each(&:teardown)
  end # def filterworker

**Comment by ph** [comment]
Hello @upbalshetwar,
I am not sure what you are trying to achieve and what is the issue with Logstash. 

Could you add how you are sending logs/events to logstash?
What is the configuration you are using and the expected behaviour?

Logstash is stand alone software, I don't understand how it could crash your groovy/grails application.

**Comment by suyograo** [comment]
Closing this since there has been no responses. Please reopen when you have more info
