### ISSUE TITLE
Error while parsing the hexadecimal data obtained via SNMP

### ISSUE THREAD

**Issue by janotherson** [elastic/logstash#1962]
Logstash crashes when trying to parse the hexadecimal data obtained via SNMP.
Logstash version: 1.4.2.

SNMP input config:
input {
  snmptrap {
    community => "public"
    host => "0.0.0.0"
    port => 162
    type => "snmp"
  }
}

Debug output:
output received {:event=>{"message"=>"#<SNMP::SNMPv2_Trap:0x436444e5 @error_index=0, @varbind_list=[#<SNMP::VarBind:0x194c10dd @value=#<SNMP::TimeTicks:0x50e72a24 @value=288384705>, @name=[1.3.6.1.2.1.1.3.0]>, #<SNMP::VarBind:0x787fcafa @value=[1.3.6.1.4.1.171.11.105.3.2.100.1.2.0.1], @name=[1.3.6.1.6.3.1.1.4.1.0]>, #<SNMP::VarBind:0x41205fdd @value=\"\\x01\\xB8\\x03\\x05\\xA5Np\\x01\\x001\\x00\", @name=[1.3.6.1.4.1.171.11.105.3.2.100.1.2.1.1]>], @error_status=0, @request_id=27864, @source_ip=\"10.90.90.140\">", "host"=>"10.90.90.140", "@version"=>"1", "@timestamp"=>"2014-10-27T12:35:05.798Z", "type"=>"snmp", "SNMPv2-MIB::sysUpTime.0"=>"33 days, 09:04:07.05", "SNMPv2-MIB::snmpTrapOID.0"=>"SNMPv2-SMI::enterprises.171.11.105.3.2.100.1.2.0.1", "SNMPv2-SMI::enterprises.171.11.105.3.2.100.1.2.1.1"=>"\x01\xB8\x03\x05\xA5Np\x01\x001\x00"}, :level=>:debug, :file=>"(eval)", :line=>"49"}

Error:
Encoding::UndefinedConversionError: ""\xB8"" from ASCII-8BIT to UTF-8
         encode at org/jruby/RubyString.java:7575
        to_json at json/ext/GeneratorMethods.java:71
        to_json at /opt/logstash/lib/logstash/event.rb:148
        receive at /opt/logstash/lib/logstash/outputs/file.rb:71
         handle at /opt/logstash/lib/logstash/outputs/base.rb:86
     initialize at (eval):50
           call at org/jruby/RubyProc.java:271
         output at /opt/logstash/lib/logstash/pipeline.rb:266
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:225
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152

**Comment by simmel** [comment]
Not helping, but yeah we have the same issue.

**Comment by LukeBeer** [comment]
Me too, even with codec => plain { charset => "cp1252" } the output says from ASCII-8BIT to UTF-8?


Failed to flush outgoing items {:outgoing_count=>6, :exception=>#<Encoding::UndefinedConversionError: ""\xDF"" from ASCII-8BIT to UTF-8>, :backtrace=>["org/jruby/RubyString.java:7575:in `encode'", "json/ext/GeneratorMethods.java:71:in `to_json'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:100:in `bulk_ftw'", "org/jruby/RubyArray.java:2404:in `collect'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:97:in `bulk_ftw'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:80:in `bulk'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch.rb:315:in `flush'", "/opt/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-snmptrap/issues/7. Let's continue the discussion there! :)

**Comment by zjcnew** [comment]
You solved it, now I have encountered such a problem, I'm going crazy！
