### ISSUE TITLE
Make filter failure logging more verbose to indicate affected input

### ISSUE THREAD

**Issue by deepybee** [elastic/logstash#1963]
Currently (logstash 1.4.2) when a filter fails to match a pattern logstash will output something akin to the below in its log;

```
{:timestamp=>"2014-10-27T13:14:57.927000+0000", :message=>"Failed parsing date from field", :field=>"timestamp", :value=>"Oct 27 13:14:57", :exception=>java.lang.IllegalArgumentException: Invalid format: "Oct 27 13:14:57", :level=>:warn}
```

This is of limited use when the filter in question is used on multiple inputs and targeting the same field on each input. In the above case, the date filter is used against the message field on most inputs in our logstash configurations. This leads to a scenario where the most effective debugging method is to restart logstash multiple times, removing a single input from the configuration each time until upon restart the failure notification is no longer written to the logs.

Although logstash concatenates all includes into a monolithic configuration at runtime, it would be very useful if the logging aspect would verbosely specify the last input called before the failing filter, or, in the case of the filter being called from a conditional statement, the condition that the filter was called from.

This would significantly reduce the time required for effective debugging of this type of error.

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5651
