### ISSUE TITLE
Netflow Codec cannot handle V9 Template record

### ISSUE THREAD

**Issue by haybeseret** [elastic/logstash#2002]
Hi,
I am using logstash netflow codec.
While generating only 1 flowset in a packet (i.e data flow set) everything work as expected.
When i am generating 2 flowsets in a packet Data+ template as per rfc3954, it seem that the logstash coded cannot handle the template flowset
image below show the 2 flowset in a a packet which the netflow codec cannot parse.
I am getting the following error

"Unsupported field {:type=>225, :length=>4, :level=>:warn}
No matching template for flow id 256 {:level=>:warn}"

![netflow1](https://cloud.githubusercontent.com/assets/5445223/4874714/d53ae8b2-626b-11e4-9444-f8c2a80ac00c.png)

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-codec-netflow/issues/12. Let's continue the discussion there! :)
