### ISSUE TITLE
Logstash threads not being cleaned up

### ISSUE THREAD

**Issue by bortek** [elastic/logstash#2005]
Hi guys,

I have an ELK installation with logstash 1.4.2 and elasticsearch 1.1.1. There is a problem with the threads , what I can see is that total number of threads are constantly increasing and are not being cleaned up when they are finished. At some point then I get Java outOfMemory and it crashes.

I have installed this FIX suggested from this discussion (https://github.com/elasticsearch/logstash-forwarder/issues/212) and since then I dont get OutOfMemory in the logs anymore but still the same behaviour.

Here is a screenshot from JVisualVM which shows this. You can see that the GC activity almost dies and the GC graph looks different after that. 
![logstash1](https://cloud.githubusercontent.com/assets/9476606/4880761/13fa58b0-6340-11e4-96be-efa7c9ed0ecc.png)

When I look at the threads I can see lots of finished threads which are not being cleaned up and clog the moemory.
![logstash2](https://cloud.githubusercontent.com/assets/9476606/4880800/796c5072-6340-11e4-8f6a-ddedaae423dd.png)

Can anyone help me shed some light on this and figure out whats happening?

**Comment by suyograo** [comment]
Closing this. Please open a new issue if you run into similar problems
