### ISSUE TITLE
grok filter: How to match one pattern multiple times?

### ISSUE THREAD

**Issue by stbka** [elastic/logstash#2006]
I want to match one pattern multiple times in a logevent. Tried different regex pattern but I don't get it working. 

Example-event: 
This is a statusCode="ERROR_121" text to demonstrate my logevent statusCode="WARNING_2408" structure

What I want to have is a statusCode field with "ERROR_121" as well as "WARNING_2408".
Notice that it is possible that the event does not contain any statusCode.

My problem is that grok filter finds either just one entry and breaks or if I combine one pattern with a * it does not find anything.

Example-pattern: 
STATUSCODE [a-zA-Z0-9_\-]+
STATUSCODEENTRY statusCode=.%{STATUSCODE:statusCode}.
STATUSCODES (%{STATUSCODEENTRY}.+)*

I hope somebody can help me.

Thanks.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/27. Let's continue the discussion there! :)
