### ISSUE TITLE
logstash main process terminated with status 143

### ISSUE THREAD

**Issue by zabbal** [elastic/logstash#2007]
I've got this error in the logs and at the same time logstash is eating 100% cpu.
What could be the reason and what does 143 means?
logstash is installed from http://packages.elasticsearch.org/logstash
version is 1.4.2-1-2c0f5a1

I've tried to look for this return code in man but no man is installed alongside with logstash.

Overall setup is rather simple: logstash is running on the same machine as elasticsearch - it receive logs from logstash-forwarder over the network and feeds it to elastic.

**Comment by suyograo** [comment]
logstash-web has been removed. Closing this
