### ISSUE TITLE
Lumberjack - Error: unable to create new native thread

### ISSUE THREAD

**Issue by Willberforce** [elastic/logstash#2010]
Running Lumberjack as an input - the input plugin died but the process carried on.

It looks like the same issue as raised on Jira - https://logstash.jira.com/browse/LOGSTASH-1887

The message in Logstash...

{:timestamp=>"2014-11-03T09:49:50.260000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Lumberjack type=>\"myInputType\", ssl_certificate=>\"/etc/pki/tls/certs/logstash-forwarder.crt\", ssl_key=>\"/etc/pki/tls/private/logstash-forwarder.key\", host=>\"0.0.0.0\">\n  Error: unable to create new native thread", :level=>:error}

This repeated until I killed logstash and restarted it.

On the Logstash-forwarder machine I have...

2014/11/03 09:49:50.370312 Loading client ssl certificate: /etc/pki/tls/certs/logstash-forwarder.crt and /etc/pki/tls/private/logstash-forwarder.key
2014/11/03 09:49:50.771406 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
2014/11/03 09:49:50.772084 Connecting to XXX.XXX.XXX.XXX:5001 (XXX.XXX.XXX.XXX)
2014/11/03 09:49:50.841208 Connected to XXX.XXX.XXX.XXX
2014/11/03 09:50:05.480101 Read error looking for ack: read tcp XXX.XXX.XXX.XXX:5001: connection reset by peer

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/14. Let's continue the discussion there! :)
