### ISSUE TITLE
Logs eventually die out

### ISSUE THREAD

**Issue by DashingChets** [elastic/logstash#2021]
Using logstash-forwarder 0.3.1 on 6 AWS instances sending logs to ELK on 2 instances. Elasticsearch 1.0.2, Logstash 1.3.3
Once deployed everything works but after sometime logstash-forwarder starts reporting errors:
Oct 30 06:28:39 ip-xxxxxx logstash-forwarder[7038]: 2014/10/30 06:28:39.044039 Failed to tls handshake with xx.xx.xx.xx read tcp xx.xx.xx.xx:6782: i/o timeout
Tried ntp, restarting logstash on cron but to no avail.  What is happening?

**Comment by jordansissel** [comment]
I don't know what's causing your tls handshake timeout. Maybe a network problem or cpu starvation on the forwarder or logstash side?

Is this still an issue for you the latest logstash-forwarder and logstash? What size EC2 instances are you using for all of these systems?

**Comment by suyograo** [comment]
Closing, no response received
