### ISSUE TITLE
MRI support: Need Joda-Time formatting support

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2024]
Joda's got a lovely date format syntax. We'll need to support this ourselves under MRI.

**Comment by ph** [comment]
Not sure if it is needed anymore since we are lurking at using more java inside logstash. Also might be worth it to check the built in date classes in java 8 if ever needed.

I have a parser done locally for 90% of the joda syntax in pure ruby, I'll at least open source it.

**Comment by untergeek** [comment]
We're not going to support MRI going forward, so this is moot.
