### ISSUE TITLE
log4j input performance problem

### ISSUE THREAD

**Issue by AndreSchulzBerlin** [elastic/logstash#2027]
If I use input{log4j {}} and log4j SocketAppender to send LogEvents some events get lost.
But this only happens if the events are posted without time between. If I wait e.g. 100ms between the events all events arrive.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-log4j/issues/10. Let's continue the discussion there! :)
