### ISSUE TITLE
Proposal: Allow per plugin log level configuration

### ISSUE THREAD

**Issue by driskell** [elastic/logstash#2040]
Hello,

Thinking of the new plugin system that will hopefully build a community of plugins - someone somewhere is going to need to debug a plugin, and to turn debugging on for logstash can produce thousands of entries a seconds on some installations.

It would be great to have the ability to configure a specific plugin for debug logging.

I guess the implementation would be something like:
1. Implement in input/filter/output base the new configuration option "log level" (like the "codec" and "add_field" etc)
2. When the input/filter/output base inits, if "log level" is set, it uses `@logger.clone` and `@logger.level=` to create a new logger, with same outputs, but different level
3. If "log level" wasn't set, it simply leaves the current @logger alone

@jordansissel might need to confirm clone is safe on the Cabin::Channel and maybe there's a better way to do this, but I think it'll definitely be worthwhile. Without this kind of feature plugin developers would end up having to avoid debug level entirely as it causes Logstash to print all events, so we essentially reduce the granularity for plugin logging. And without it there's always going to be more noise than necessary when you only want to debug a single plugin.

Let me know what you think! Thanks!

**Comment by jordansissel** [comment]
TODO:
* document naming scheme for loggers
* prepare for an API that allows control of this via the future logstash API

**Comment by driskell** [comment]
FYI. Cloning cabin channels doesn't work. The resulting clone is only shallow copy so the data array is actually the same still and so is subscriptions - any changes affects the original still.

I've been playing around with a channel fork feature for cabin though. It creates a new channel with proper modifiable duplicates of original data and subscriptions. Means logstash plugin base could attach plugin name data to a fork of the main logstash channel, so events logged by the plugin state the plugin name. The plugin could even fork again when passing libraries (that support cabin channels) so they can add more data too, whilst still having a copy of the calling plugins data.

Essentially creates hierarchical channels.

Untested but my thought is to pass a key value map of channel-name level pairs that sets the log levels for anything in the hierarchy, inheriting level where not explicitly set.
https://github.com/driskell/ruby-cabin/commit/77ebb4e37ce5756cc8e4be95e1a834254b482179

Not sure if on the right track?

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5651
