### ISSUE TITLE
example in pagerduty `details` field has syntax error

### ISSUE THREAD

**Issue by richchang0** [elastic/logstash#2046]
for the pagerduty plugin, i put the `details` example in.

details => ... # hash (optional), default: {"timestamp"=>"%{@timestamp}", "message"=>"%{message}"}

Got this error:
:message=>"Error: Expected one of #, {, } at line 44, column 51

Don't think you need the comma in between the two fields?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-pagerduty/issues/7. Let's continue the discussion there! :)
