### ISSUE TITLE
non-plugin logstash gems should not be installable by the plugin manager

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#2047]
non-plugin gems like [logstash-mixin-aws](https://github.com/logstash-plugins/logstash-mixin-aws) should not be installable by the new plugin manager. 

Not sure if we can just unset the [_logstash_plugin_ property](https://github.com/logstash-plugins/logstash-mixin-aws/blob/master/logstash-mixin-aws.gemspec#L19) or add a new _installable_ property?

**Comment by suyograo** [comment]
This is no longer relevant and not something anyone has asked. Closing
