### ISSUE TITLE
How to dump final grok regexes?

### ISSUE THREAD

**Issue by PAStheLoD** [elastic/logstash#2049]
It'd be very handy to get the resulting PCRE expressions for filter development and debugging purposes. (Since there are quite friendly online tools for interacting with regex as opposed to the slow trial-and-error restart-driven development.)

Thanks!

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/28. Let's continue the discussion there! :)
