### ISSUE TITLE
Initscript should stop both daemons and also on "purge"

### ISSUE THREAD

**Issue by lathspell** [elastic/logstash#2053]
The "prerm" script of the Debian package currently says:

    if [ $1 = "remove" ]; then
      service logstash stop >/dev/null 2>&1 || true

It should be improved to
1. work on "remove" as well as "purge" and
2. also stop "logstash-web"

Currently, when purging (Debian command for remove and remove config files, btw.), it fails to remove the user as the logstash-web process is still using that uid:

    # aptitude purge logstash
    The following packages will be REMOVED:  
      logstash{p} 
    0 packages upgraded, 0 newly installed, 1 to remove and 2 not upgraded.
    Need to get 0 B of archives. After unpacking 142 MB will be freed.
    Do you want to continue? [Y/n/?] 
    (Reading database ... 237196 files and directories currently installed.)
    Removing logstash (1.4.2-1-2c0f5a1) ...
    userdel: user logstash is currently used by process 1472
    groupdel: cannot remove the primary group of user 'logstash'

**Comment by jordansissel** [comment]
logstash-web is gone, so I think this can probably be closed. :)
