### ISSUE TITLE
Wrong error: "Upgrade Required Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9 or above."

### ISSUE THREAD

**Issue by lathspell** [elastic/logstash#2056]
After installing logstash=1.4.2-1-2c0f5a1 I started logstash-web but did not notice that logstash itself was not running. When pointing my browser to the web interface, it just gave me the error:

    Upgrade Required Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9 or above.

This is wrong, I installed the Logstash Debian package which bundles Elasticsearch 1.1.1. As a newbie was puzzled and removed / downloaded / reinstalled the package several times until I noticed that there was a second error message:

    Error Could not reach http://localhost:9200/_nodes. If you are using a proxy, ensure it is configured correctly

Maybe this could be improved so that it says "... If you use the bundled Elasticsearch, make sure the logstash agent daemon is running, if you use a dedicated Elasticsearch daemon, check if is in version 0.90.9 or higher!"

**Comment by dweinstein** [comment]
So what's the way to fix/get rid of this error?

**Comment by electrical** [comment]
When running Logstash with node protocol ( which is by default ) its part of the cluster.
Kibana sees that as an other node which has an to older version of ES.
if you run LS with the ES output set to protocol => transport  it should solve the issue.

**Comment by jianfengye** [comment]
i use kibana 3.0.1 not the one which in logstash. the versions follow the download page:http://www.elasticsearch.org/overview/elkdownloads/

**Comment by kervinpierre** [comment]
This is a misleading error.  The problem is often with ElasticSearch CORS settings. See...
http://stackoverflow.com/a/26884367/16549

Pretty much add...

http.cors.allow-origin: "/.*/"
http.cors.enabled: true

To your elasticsearch.yml then restart.

**Comment by MarkMurphy** [comment]
> http.cors.allow-origin: "/.*/"
> http.cors.enabled: true

This worked for me.

**Comment by cfeller** [comment]
> This is a misleading error. The problem is often with ElasticSearch CORS settings. See...
> http://stackoverflow.com/a/26884367/16549

Misleading indeed - thank you Kervin.

**Comment by FatmaG** [comment]
Greatly misleading!! Thank you!

**Comment by smancke** [comment]
> http.cors.allow-origin: "/.*/"
> http.cors.enabled: true

Great, also solved it for me!!

**Comment by fb64** [comment]
Working also for me. Thanks :)

**Comment by Mindscope** [comment]
For me worked as follows:

> http.cors.allow-origin: "*"
> http.cors.enabled: true

**Comment by ckuharski-drc** [comment]
Worked for me.  Thanks!

**Comment by spmkd** [comment]
Worked for me as well.

**Comment by enilu** [comment]
http.cors.allow-origin: "/.*/"
    http.cors.enabled: true

me too,thank you!!!

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/147. Let's continue the discussion there! :)
