### ISSUE TITLE
Logstash on Windows crash - OutofMemory

### ISSUE THREAD

**Issue by AGirin** [elastic/logstash#2062]
For some reasons java process does not honor these settings in logstash.bat:

if "%LS_MIN_MEM%" == "" (
set LS_MIN_MEM=2g
)

if "%LS_MAX_MEM%" == "" (
set LS_MAX_MEM=2g
)

Java process core dumps when memory is ~1GB. Is this a known issue? We use Java 8 Update 25 (64-bit.)

**Comment by rudibroekhuizen** [comment]
Take a look a my workaround. It uses the convertto-json option in powershell 4: https://github.com/rudibroekhuizen/puppet-windows_role_logstash/blob/master/files/logstash-win-base-20.conf. This solution works, I've been running it for over 24 hours now, with a 10 seconds interval, memory stays stable.

**Comment by ph** [comment]
This a bad bug, logstash should never OOM.
Can you port your whole logstash configuration? Are you using the Elasticsearch output?

**Comment by rudibroekhuizen** [comment]
The logstash configuration I used in the test is this one: https://github.com/rudibroekhuizen/puppet-windows_role_logstash/blob/master/files/logstash-win-base-17.conf

**Comment by suyograo** [comment]
Fixed via https://github.com/jruby/jruby/issues/3446

Please open a new issue if you are seeing this again
