### ISSUE TITLE
RabbitMQ message properties cannot be read

### ISSUE THREAD

**Issue by Fresa** [elastic/logstash#2069]
There does not seem to be a way to include the message properties from a RabbitMQ message into logstash? Headers, message id and correlation id for example.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/24. Let's continue the discussion there! :)
