### ISSUE TITLE
--configtest misses invalid grok pattern

### ISSUE THREAD

**Issue by robin13** [elastic/logstash#2074]
I have a deployment setup where I run logstash with --configtest before I commit/deploy the configuration.  Today however it tripped me up because I ran the config test, deployed, and half an hour later noticed that all the logstash agents had started, but then exited because of an invalid grok pattern:
A typo in a grok pattern (NOSPACE rather than NOTSPACE) caused it to exit when parsing the first event (which hit that rule):

    The error reported is: \n  pattern %{NOSPACE:[das][key_value]} not defined"

I assume now that logstash --configtest only actually checks if the configuration is syntactically correct, but not if it will work.  Would it be possible to allow plugins to test their own configurations for configuration errors?  i.e. --configtest would first test whether the config file as a whole is syntactically correct, and following delegate each input/filter/output section to be tested by their respective plugins?

**Comment by purbon** [comment]
Related to #3301

**Comment by jsvd** [comment]
we can close this in favor of #3301
