### ISSUE TITLE
elasticsearch_http encoding problem

### ISSUE THREAD

**Issue by t1nkerer** [elastic/logstash#2075]
Hello,

I have installed the latest elasticsearch/kibana4 and it does not support simple elasticsearch output because of version check on kibana side. So I found the temp solution - using elasticsearch_http, but when I do that logstash crashes after a few events with the following events in logstash.log:

{:timestamp=>"2014-11-14T03:07:03.986000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>76, :exception=>#<Encoding::UndefinedConversionError: ""\xC3"" from ASCII-8BIT to UTF-8>, :backtrace=>["org/jruby/RubyString.java:7575:in `encode'", "json/ext/GeneratorMethods.java:71:in `to_json'", "/opt/logstash/lib/logstash/event.rb:148:in `to_json'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:207:in `flush'", "org/jruby/RubyArray.java:2404:in `collect'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:195:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
{:timestamp=>"2014-11-14T03:07:04.990000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>76, :exception=>#<Encoding::UndefinedConversionError: ""\xC3"" from ASCII-8BIT to UTF-8>, :backtrace=>["org/jruby/RubyString.java:7575:in `encode'", "json/ext/GeneratorMethods.java:71:in `to_json'", "/opt/logstash/lib/logstash/event.rb:148:in `to_json'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:207:in `flush'", "org/jruby/RubyArray.java:2404:in `collect'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:195:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
{:timestamp=>"2014-11-14T03:07:05.994000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>76, :exception=>#<Encoding::UndefinedConversionError: ""\xC3"" from ASCII-8BIT to UTF-8>, :backtrace=>["org/jruby/RubyString.java:7575:in `encode'", "json/ext/GeneratorMethods.java:71:in `to_json'", "/opt/logstash/lib/logstash/event.rb:148:in `to_json'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:207:in `flush'", "org/jruby/RubyArray.java:2404:in `collect'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:195:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
{:timestamp=>"2014-11-14T03:07:06.998000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>76, :exception=>#<Encoding::UndefinedConversionError: ""\xC3"" from ASCII-8BIT to UTF-8>, :backtrace=>["org/jruby/RubyString.java:7575:in `encode'", "json/ext/GeneratorMethods.java:71:in `to_json'", "/opt/logstash/lib/logstash/event.rb:148:in `to_json'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:207:in `flush'", "org/jruby/RubyArray.java:2404:in `collect'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:195:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

How can I solve this?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/135. Let's continue the discussion there! :)
