### ISSUE TITLE
elasticsearch output template mapping is not applied consistently

### ISSUE THREAD

**Issue by dineshbhat** [elastic/logstash#2076]
I am using a custom template with elasticsearch output. I need some fields not_analyzed. A new index is created everyday. 
I see that the mapping template is not applied on some indexes. I have correlated that to my use of the kv{} filter and a log message that has a few additional key value pairs that get added to the event. Has anyone else experienced this?

**Comment by sugansan** [comment]
When we rename the field, elastic search says that field not found. Do i have to create field in mapping  template for the renamed field?

**Comment by j2o** [comment]
@sugansan Did you manage to resolve the rename issue?
