### ISSUE TITLE
Logstash throws cannot assign requested address - bind

### ISSUE THREAD

**Issue by kimoo88** [elastic/logstash#2082]
I'm new to Logstash. I have some logs written from a Java application in Log4J. I'm in the process of trying to get those logs into ElasticSearch. 
My logstash.conf:
input { 
stdin {
type => "stdin-type"
}
log4j{
mode=> "server"
host => "192.168.128.20"
port => 9200
}
}

output {
stdout { 
codec => rubydebug
}
elasticsearch {
embedded => true
host => "localhost"
port => "9200"
protocol => "http"
}
}

and my log4j.xml

```
<param name="RemoteHost" value="192.168.128.21" />
<param name="Port" value="80" />
<param name="LocationInfo" value="true" />
<param name="ReconnectionDelay" value="60000"/>
 <param name="Threshold" value="INFO"/>
```

and when I run my logstash.conf i get 
error_msg
![error_msg](https://cloud.githubusercontent.com/assets/9746139/5062119/58bbdc2c-6dbc-11e4-8b94-4f7464d1318a.jpg)

I wish if anyone can help.

**Comment by OhadR** [comment]
if i want to connect my logstash to multiple log4j-s. for example, I have 3 tomcats on 3 different machines, and i want all logs (log4j) of all services from all tomcats to send their data to logstash. how can i configure it? does it make sense?

**Comment by jiubanmoli** [comment]
请问我启动logstash一直报这个错是什么原因？
![QQ截图20201012092816](https://user-images.githubusercontent.com/27392418/95696372-62978d80-0c6d-11eb-89e6-b950528ce487.png)
![QQ截图20201012092923](https://user-images.githubusercontent.com/27392418/95696381-6e834f80-0c6d-11eb-871a-111163fb63d8.png)
