### ISSUE TITLE
Mutate filter (gsub) not working when fieldname contains period

### ISSUE THREAD

**Issue by clay584** [elastic/logstash#2092]
When trying to do a mutate gsub on a field in which the fieldname contains a period (i.e. - netflow.protocol), gsub is not working.  If I use a field that has no period in the name, it works fine.

Current config:
https://gist.github.com/clay584/a45871a73e911ff0ccbd

Sample data showing that the field is not updated:
https://gist.github.com/clay584/cac6126aee96ce85b26a

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-mutate/issues/29. Let's continue the discussion there! :)
