### ISSUE TITLE
Add offending input file name/line number to the error generation

### ISSUE THREAD

**Issue by andrewjsledge** [elastic/logstash#2093]
When getting an error such as

{:timestamp=>"2014-11-10T15:05:13.345000-0500", :message=>"Received an event that has a different character encoding than you configured.", :text=>"{t\\xC2h....\\x81", :expected_charset=>"UTF-8", :level=>:warn}

add the offending input file name/line number to this entry such that it could look like 

{:timestamp=>"2014-11-10T15:05:13.345000-0500", :message=>"Received an event that has a different character encoding than you configured.", :text=>"{t\\xC2h....\\x81", :expected_charset=>"UTF-8", :level=>:warn, :file=>"my_input.conf", :line=> 32}.

Makes it easy to trap down misconfigurations.

**Comment by suyograo** [comment]
This option is enabled in `--debug` mode
