### ISSUE TITLE
CSV parsing empty fields

### ISSUE THREAD

**Issue by t1nkerer** [elastic/logstash#2099]
Hello,

How can I remove empty fields from log entry when parsing csv file? I have diverse range of log files with fixed number of columns that may be empty. As a result I get:

"destinationHostName": "",

 in my elasticsearch.

Although it is empty I cannot use _exists_ anymore because the field is there.

Is there an easy way to do this or do I have to check all the fields for empty values and remove them one by one?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-csv/issues/9. Let's continue the discussion there! :)
