### ISSUE TITLE
Whitespace in Cisco ASA output breaks firewall pattern

### ISSUE THREAD

**Issue by roderickm** [elastic/logstash#2101]
If a Cisco ASA has a logging device-id set (for instance with `logging device-id string asa.sfo`), the syslog message emitted does not match the grok pattern `CISCO_TAGGED_SYSLOG`. An additional space should be allowed by the pattern between the device_id and the colon.

Here are example messages to demonstrate:

**without** device-id:
```<164>Nov 19 2014 17:27:56: %ASA-4-733100: [ Scanning] drop rate-1 exceeded. ...```

**with** device-id:
```<164>Nov 19 2014 17:30:36 asa.sfo : %ASA-4-733100: [ Scanning] drop rate-1 exceeded. ...```

The example with device-id is not matched by `CISCO_TAGGED_SYSLOG` because of the space in
```asa.sfo :```

**Comment by seang-es** [comment]
We've seen this issue at a customer site as well.  Can we update the default filter to handle this?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-patterns-core/issues/39. Let's continue the discussion there! :)
