### ISSUE TITLE
Imap input plugin doesn't support html emails in UTF-8. 

### ISSUE THREAD

**Issue by kireevco** [elastic/logstash#2103]
Imap input plugin doesn't support html emails in UTF-8.
It breaks on s.encode(Encoding::UTF_8, :invalid => :replace, :undef => :replace)

Tested with Outlook + Office365. 
Plain text has no issues.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-imap/issues/8. Let's continue the discussion there! :)
