### ISSUE TITLE
Syslog input keeps dying with the message "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by ilyalozovyy** [elastic/logstash#2104]
Running on Windows 2008 R2 with Java 8u25
Getting the following stack trace:

←[33msyslog udp listener died {:address=>"0.0.0.0:514", :exception=>#<SocketError: recvfrom: name or service not known>,
 :backtrace=>["D:/Apps/logstash/lib/logstash/inputs/syslog.rb:119:in `udp_listener'", "org/jruby/RubyKernel.java:1521:in
 `loop'", "D:/Apps/logstash/lib/logstash/inputs/syslog.rb:118:in `udp_listener'", "D:/Apps/logstash/lib/logstash/inputs/
syslog.rb:76:in `run'"], :level=>:warn, :file=>"/Apps/logstash/lib/logstash/inputs/syslog.rb", :line=>"80"}←[0m

The configuration that I am using is:

input { 
	syslog {
		type => "syslog"
		port => 514
	}
	tcp {
		type => "web"
		port => 10000
		codec => "json"
	}
	tcp {
		type => "eventlog"
		port => 10001
		codec => "json"
	}
}

output {
	if [type] == "syslog" {
		stdout {
			codec => rubydebug
		}
	}
}

Any ideas what could be causing this failure?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-syslog/issues/11. Let's continue the discussion there! :)
