### ISSUE TITLE
There aren't any configuration files

### ISSUE THREAD

**Issue by disappear89** [elastic/logstash#2106]
Hi,

when installing logstash via debian repo and setup multiple configfiles under:
/etc/logstash/conf.d/
like this:
01-lumberjack-input.conf  10-syslog.conf  30-lumberjack-output.conf
the init script: /etc/init.d/logstash-web
fails with the following error:
There aren't any configuration files
--
# /etc/init.d/logstash-web restart
There aren't any configuration files in /etc/logstash/conf.d ... failed!
test too many arguments
--
If i manually trigger test, i can confirm this:
--
# test -e /etc/logstash/conf.d/*.conf
-bash: test: too many arguments
--
As a workaround i changed:
 if !  test -e $CONF_DIR/*.conf ; then
to:
 if !  ls $CONF_DIR/*.conf ; then
And it is starting fine now.

**Comment by suyograo** [comment]
Please reopen if the issue is still valid. Could not reproduce on our side
