### ISSUE TITLE
Logstash 1.4.2 grok filter with multiple match statements not working as expected

### ISSUE THREAD

**Issue by YuvalBenAri** [elastic/logstash#2108]
I tried to use a grok filter with multiple match statements to match various possible formats of a certain log file. The synatax I used was:

```
grok {
        break_on_match => false
        match => [ "message", "regex1" ]
        match => [ "message", "regex2" ]
        match => [ "message", "regex3" ]

}
```

However only the first match is working. If I change the order so regex2 is the first one only it works

The workaround I found is:

```
grok {
        match => [ "message", "regex1" ]
        tag_on_failure => []
}
grok {
        match => [ "message", "regex2" ]
        tag_on_failure => []
}
grok {
        match => [ "message", "regex3" ]
        tag_on_failure => []
}
```

I have seen other complaints about the same issue but no confirmation that it's still a known issue on 1.4.2

**Comment by tabs11** [comment]
Hi, It's possible to have two different logfiles (in my case logs with different number of columns) and create different matchs to each one inside the same grok?

How can I assume the match to respective file or to respective path where is stored?

**Comment by untergeek** [comment]
@tabs11 Please ask usage questions in our discussion forums at https://discuss.elastic.co.
