### ISSUE TITLE
Logstash init script does not respect the logstash user groups (FIX included)

### ISSUE THREAD

**Issue by idanov** [elastic/logstash#2110]
I have experienced the issue that logstash (when started as a service) does not read log files unless they are world readable or owned by the logstash user itself. I have added the logstash user to the user group of the files (in my case apache user group) and that did not work. Then I found a solution to the problem here:
http://serverfault.com/questions/632079/logstash-not-reading-logs-unless-world-readable

**Comment by spuder** [comment]
possibly related? 

https://github.com/elastic/logstash/pull/1398

**Comment by Crote** [comment]
Please note that this bug, in combination with https://github.com/elastic/logstash/issues/2110, results in some incredibly hard-to-debug situations.

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/1398
