### ISSUE TITLE
logstash 1.4.2 crashes without permissions on csv output dir

### ISSUE THREAD

**Issue by beardyneedle** [elastic/logstash#2115]
to replicate create an CSV output to a dir you do not have write perms to.

**Comment by ph** [comment]
What would be the most appropriate behavior?
Should we return a clearer error message? The check need to be done on each write since the path is dynamic.

I can confirm this behavior with:

```
[..]
testing
Errno::EACCES: Permission denied - /etc/dfsfsfs.csv
     initialize at org/jruby/RubyFile.java:361
            new at org/jruby/RubyIO.java:852
           open at /Users/ph/Downloads/logstash-1.4.2/lib/logstash/outputs/file.rb:147
        receive at /Users/ph/Downloads/logstash-1.4.2/lib/logstash/outputs/csv.rb:36
         handle at /Users/ph/Downloads/logstash-1.4.2/lib/logstash/outputs/base.rb:86
     initialize at (eval):20
           call at org/jruby/RubyProc.java:271
         output at /Users/ph/Downloads/logstash-1.4.2/lib/logstash/pipeline.rb:266
   outputworker at /Users/ph/Downloads/logstash-1.4.2/lib/logstash/pipeline.rb:225
  start_outputs at /Users/ph/Downloads/logstash-1.4.2/lib/logstash/pipeline.rb:152
```
config
```
~/D/logstash-1.4.2 ❯❯❯ cat server.conf                                                                                                                                             ⏎
input { stdin {}}
output {
  csv {
    fields => ['message']
      path => '/etc/dfsfsfs.csv'
  }

  elasticsearch_http {
    host => '127.0.0.1'
  }
}
```

**Comment by clemherreman** [comment]
Unsuccessful writes should trigger an alert/an error message, most likely written in logstash's own log file, but should not bring down the whole daemon, without any outputs.

It outputs to `stderr` (I guess) but it should at least output to its own log, so people have a clue why their service is down. Currently one have to stop their daemon, run it manually, through the `logstash` user to finally get an error message.

**Comment by beardyneedle** [comment]
agreed - it should at least output to its own log, so people have a clue
why their service is down.

On Thu, Feb 12, 2015 at 1:07 PM, Clément Herreman <notifications@github.com>
wrote:

> Unsuccessful writes should trigger an alert/an error message, most likely
> written in logstash's own log file, but should not bring down the whole
> daemon, without any outputs.
>
> It outputs to stderr (I guess) but it should at least output to its own
> log, so people have a clue why their service is down. Currently one have to
> stop their daemon, run it manually, through the logstash user to finally
> get an error message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/logstash/issues/2115#issuecomment-74067374>
> .
>

-- 


This email, including attachments, is private and confidential. If you have 
received this email in error please notify the sender and delete it from 
your system. Emails are not secure and may contain viruses. No liability 
can be accepted for viruses that might be transferred by this email or any 
attachment. Any unauthorised copying of this message or unauthorised 
distribution and publication of the information contained herein are 
prohibited.

7digital Limited. Registered office: 69 Wilson Street, London EC2A 2BB.
Registered in England and Wales. Registered No. 04843573.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-csv/issues/3. Let's continue the discussion there! :)
