### ISSUE TITLE
When Gelfd parser fails to process message, the exception message returned is not helpful enough

### ISSUE THREAD

**Issue by taliesins** [elastic/logstash#2116]
It would be nice to know who is sending dodgy udp packets to GELF endpoint. In my case it turned out to be a misconfigured load balancer.

My monkey patch was to change gelf.rb:

```
@logger.warn("Gelfd failed to parse a message skipping", :exception => ex, :backtrace => ex.backtrace)
```

to

```
@logger.warn("Gelfd failed to parse a message skipping. Client was: #{client.inspect} .Message was: #{line.inspect}", :exception => ex, :backtrace => ex.backtrace)
```

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-gelf/issues/10. Let's continue the discussion there! :)
