### ISSUE TITLE
logstash different character

### ISSUE THREAD

**Issue by ton31337** [elastic/logstash#2121]
Hi All,

is it possible that logstash stops working after getting similar warning like this:

```
{:timestamp=>"2014-11-21T12:20:19.762000-0500", :message=>"Received an event that has a different character encoding than you configured.", :text=>"2014/11/21 12:20:19 [info] 20322#0: *317 recv() failed (104: Connection reset by peer) while reading client request line, client: 111.249.118.237, server: , request: \\\"\\u0004\\u0001\\u0000\\u0019\\xCBER\\\"\\u0000\\\"", :expected_charset=>"UTF-8", :level=>:warn}
```

After this, logstash doesn't ships logs to elastic search and it stops working at all while I truncate the log file it watches. 

I don't know if it's a bug or a normal behavior, but would be great to find an answer. Google doesn't answer much about this.

D.

**Comment by suyograo** [comment]
Closing this, no responses. Please reopen if you have more info
