### ISSUE TITLE
ssl_key option missing in lumberjack output

### ISSUE THREAD

**Issue by zabbal** [elastic/logstash#2126]
There's significant difference between logstash-forwarder and logstash when it comes to ssl configuration:
forwarder supports following options - ssl_certificate, ssl_key, ssl_ca - which are pretty-much self-explanatory
However if I want to ship logs from one logstash to another it becomes much tricker: there is only single "ssl_certificate" option with no example or explanation in the docs I've found so far.
How should I supply private key for ssl certificate for logstash sender?
How will logstash sender verify receiver certificate without option for CA certificate?

I've found numerous toy configuration examples which are of not much use because I'd like to roll out logstash for production setup - which means we already have CA issuing proper certificates for both logstash instances, sender and receiver.

Would be nice to have an example of shipping logs from one logstash to another in a secure way. Ideally, the option names should be compatible between logstash-forwarder and logstash so migration between those 2 would be as easy as possible.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-lumberjack/issues/1. Let's continue the discussion there! :)
