### ISSUE TITLE
Conditional 'in' operator ignores first string of the list

### ISSUE THREAD

**Issue by arnauldvm** [elastic/logstash#2129]
Using logstash 1.4.2

Config file:
````ruby
mutate { add_field => { "format" => "html" } }
(...)
if [format] in ["html"] {
  mutate { add_field => { "static" => "false" } }
} else {
  mutate { add_field => { "static" => "true" } }
}
````

Output:
````json
static: true
````

But:
````ruby
(...)
if [format] in ["dummy","html"] {
(...)
````

Gives:
````json
static: false
````

**Comment by jordansissel** [comment]
I believe this is still an issue. Nothing further to update, though. Patches welcome. I am happy to provide guidance if desired.

**Comment by jsvd** [comment]
closing as dup of https://github.com/elastic/logstash/issues/1850, please continue tracking this problem there
