### ISSUE TITLE
Improve RabbitMQ input and output plugin docs

### ISSUE THREAD

**Issue by deepybee** [elastic/logstash#2133]
Just a minor improvement, but when setting up an output to a RabbitMQ broker yesterday I ran into an issue which was not immediately obvious given the socket connection errors returned by March Hare.

The issue was that in my config I had specified a vhost including the leading forward slash "/"

The documentation only states that a vhost entry should be a string and that the default is "/" - it would be handy if this were amended to clarify a non default vhost should not contain any leading slash.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/25. Let's continue the discussion there! :)
