### ISSUE TITLE
Multiple file input cause loosing data

### ISSUE THREAD

**Issue by arnauldvm** [elastic/logstash#2135]
I'm loosing lots of records when using a setup like this:
````ruby
input { file {
  path => 'D:/some/path/access/*.log'
  sincedb_path => "target/.sincedb.xxxxxxxx.log"
  start_position => "beginning"
 (...)
} }
(...)
output { elasticsearch {
  host => localhost
  index => "logstash-xxxxxxxx-%{+YYYY.MM.dd}"
} }
````
Results:

index name | actual (wc file.log) | actually indexed in elasticsearch
---------- | -------------------- | --------
logstash-xxxxxxxx-2014.11.17 | 27493 | 27493
logstash-xxxxxxxx-2014.11.18 | 18428 | 18308
logstash-xxxxxxxx-2014.11.19 | 18871 | 695
logstash-xxxxxxxx-2014.11.20 | 15517 | 15399
logstash-xxxxxxxx-2014.11.21 | 23700 | 7897
logstash-xxxxxxxx-2014.11.22 | 1442 | 1442
logstash-xxxxxxxx-2014.11.23 | 1440 | 1380
logstash-xxxxxxxx-2014.11.24 | 10570 | 9042
logstash-xxxxxxxx.failed-1970.01.01 | - | 2

Moreover some log lines are truncated, leading to parsing errors (cf. ...failed... index).

If I do:
````sh
$ cat /D/some/path/access/*.log > /D/some/path/all_access.log
````
and adapt the logstash config accordingly, nothing is lost.

On another hand, keeping the multiple files input, but outputting to a file instead of elasticsearch, also leads to no loss of data !?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/32. Let's continue the discussion there! :)
