### ISSUE TITLE
filter/clone/documentation optional option "clones" seems not to be optional

### ISSUE THREAD

**Issue by widhalmt** [elastic/logstash#2141]
I treid the clone filter without giving the `clones` option and was hoping that it would create clones with the same type as the original event. But no clones were created. 

    clone {
      add_tag => [ "cloned", "icinga_alert" ]
    }

Using the following clones are created.

    clone {
      add_tag => [ "cloned", "icinga_alert" ]
      clones => [ "clone" ]
    }

Maybe I misread the documentation because both configurations get through the `configtest`of logstash but since the first example doesn't do anything I would have liked at least a hint that it won't do anything.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-clone/issues/1. Let's continue the discussion there! :)
