### ISSUE TITLE
Logstash don't exit after click ctl+c in ubuntu12.10

### ISSUE THREAD

**Issue by leiding** [elastic/logstash#2143]
step 1: start logstash 
./bin/logstash agent -f index.conf
Using milestone 2 input plugin 'redis'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}

Step2: Try to exit with cto+c, but the cursor can't return to the shell.

^CInterrupt received. Shutting down the pipeline. {:level=>:warn}

cat index.conf
input {
    redis
    {
    host => "10.111.96.175"
    data_type =>"list"
    port => "6379"
    key => "logstash"
    type => "redis-input"
    }

}

output
    {
    elasticsearch {
    host => "10.111.96.175"
    port => "9300"
    }
}

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-redis/issues/9. Let's continue the discussion there! :)
