### ISSUE TITLE
getting only raw logs

### ISSUE THREAD

**Issue by vinnu5064** [elastic/logstash#2145]
i'm getting only raw logs

this is my agent.conf and i'm running it like
#logstash-1.4.0/bin/logstash --verbose agent -f /etc/logstash/agent.conf 

input {
  file {
    path => "/var/log/apache2/access.log"
  }

}

filter {
grok {

pattern => "Current request is from the IP %{IPORHOST:clientip}"
     }
}

output {
  stdout { }
  elasticsearch { cluster => "elasticsearch" }
}

**Comment by suyograo** [comment]
Closing, please use https://discuss.elastic.co/c/logstash for more debugging help
