### ISSUE TITLE
Logstash dies using redis batch output and non UTF-8 characters

### ISSUE THREAD

**Issue by nb71** [elastic/logstash#2147]
Hi, 
We noticed that some of our logstash servers started to die frequently.
Making a very long story short the exact situation is:

Logstash from RPM on Centos or Redhat 6.5 and 6.6: logstash-1.4.2-1_2c0f5a1.noarch
Config:
>input {
>        tcp {
                        type => rsyslog
                        port => 6666
                        codec =>   line
        }
}
output {
         redis {
                 host => [ "10.10.10.10"]
                 data_type => "list"
                 key => "logstash"
                  batch => true
                  batch_events => 100
         }
}

If we send 0xFF char to port 6666 Logstash **dies immediately**.
Sometimes logging errors, sometimes not.

If we **comment out redis "batch" settings**, logstash complains but keep running.

Error messages:
With batch (dies after this message): 
>{:timestamp=>"2014-11-28T16:28:53.914000-0300", :message=>"Received an event that has a different character encoding than you configured.", :text=>"\\xFF\\xF4\\xFF\\xFD\\u0006\\r", :expected_charset=>"UTF-8", :level=>:warn}
OR
{:timestamp=>"2014-11-21T20:30:14.379000-0300", :message=>"Received an event that has a different character encoding than you configured.", text=>"\\x80\\x80\\u0001\\u0003\\u0001\\u0000W\\u0000\\u0000\\u0000 \\u0000\\u0000\\u0016\\u0000\\u0000\\u0013\\u0000\\u0000", :expected_charset=>"UTF-8", :level=>:warn}

And this in error log:
>Encoding::UndefinedConversionError: ""\xFF"" from ASCII-8BIT to UTF-8
         encode at org/jruby/RubyString.java:7575
        to_json at json/ext/GeneratorMethods.java:71
        to_json at /opt/logstash/lib/logstash/event.rb:148
        receive at /opt/logstash/lib/logstash/outputs/redis.rb:148
         handle at /opt/logstash/lib/logstash/outputs/base.rb:86
     initialize at (eval):17
           call at org/jruby/RubyProc.java:271
         output at /opt/logstash/lib/logstash/pipeline.rb:266
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:225
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152

-------------
the same test without batch redis settings:
> {:timestamp=>"2014-11-28T17:20:34.168000-0300", :message=>"Failed to convert event to JSON. Invalid UTF-8, maybe?", :event=>"#<LogStash::Event:0x58e289cb @accessors=#<LogStash::Util::Accessors:0xc49c04 @store={\"message\"=>\"%{syslog_message}\", \"@version\"=>\"1\", \"@timestamp\"=>\"2014-11-28T20:20:34.115Z  .......................

and logstash keeps running

Hope this helps...
Thanks!

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-redis/issues/8. Let's continue the discussion there! :)
