### ISSUE TITLE
Logstash metrics plugin in 1.4.2

### ISSUE THREAD

**Issue by AGirin** [elastic/logstash#2154]
Does metrics plugin actually work in 1.4.2? I cannot make it output any rates or count:

generator {
    type => "generated"
  }
}
filter {
  metrics {
    meter => "events"
    add_tag => "metric"
  }
}
output {
  stdout {
    codec => line {
        format => "Rate: %{events.count}"
    }
  }

  stdout {

      codec => rubydebug

  }
}

All I get is:

Rate: %{events.count}
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2014-12-01T21:35:11.195Z",
          "type" => "generated",
          "host" => "Servername",
      "sequence" => 10,
        "events" => {}
}

I tried both on Windows and Linux with no success.

**Comment by suyograo** [comment]
this was fixed in https://github.com/logstash-plugins/logstash-filter-metrics/pull/5/files. Will keep this open in case we do a 1.4.3 release

**Comment by juise** [comment]
+1, the fix doesn't work

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-metrics/issues/13. Let's continue the discussion there! :)
