### ISSUE TITLE
Avoid use of 'and' and 'or' in ruby code.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2169]
This is an internal code-quality improvement. Not a feature for Logstash itself.

The reason behind this is that `&&` and `and` (similarily, `||` and `or`) have very different orders of operations (`and` is very late). Best to avoid.

**Comment by purbon** [comment]
+1

**Comment by suyograo** [comment]
Added to style guide https://github.com/elastic/logstash/pull/4799
