### ISSUE TITLE
SSL/TLS Usage Allow for Cipher Suite Config

### ISSUE THREAD

**Issue by masteinhauser** [elastic/logstash#2170]
Any plugins utilizing TLS/SSL should also accept a list of accept/reject cipher suites and/or other options. Ideally, the defaults could come from the [Mozilla TLS recommendation guide](https://wiki.mozilla.org/Security/Server_Side_TLS) or another reputable source.

This would allow for the end user to tailor the encryption needs per input at the input source and what the sending client supports. Currently, we are evaluating proxying our Logstash installation with stunnel or haproxy for similar functionality.

This seems to similar to/aligned with #2151.

**Comment by suyograo** [comment]
Hardened SSL/TLS in 1.5.3. https://github.com/elastic/logstash/pull/3622
