### ISSUE TITLE
Frequent "Broken pipe" exceptions while using 'tcp' or 'syslog' inputs

### ISSUE THREAD

**Issue by lgoldstein** [elastic/logstash#2172]
The plugins seem to break down frequently and then recover - even if only 1 client is accessing them at any time. Furthermore, even when logstash is started it does not show up as LISTENING in the *netstat --all --tcp* command (strangely enough UDP does...)

I have not been able to find documentation as to how to enable some logging for logstash so I can provide more useful information.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-tcp/issues/10. Let's continue the discussion there! :)
