### ISSUE TITLE
Add generic support for retrying events in output plugins

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#2177]
Currently, there is no general supported way to effect a retry-policy in an output plugin.

This is being done in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/2

It would be nice if there was a general retry-buffer for plugins to insert into and call to flush upon their own retry policy for each specific use-case.

**Comment by untergeek** [comment]
Perhaps we can close this since we're getting there with PQ and the approach of the DLQ?

**Comment by talevy** [comment]
@untergeek agreed. closing.
