### ISSUE TITLE
Error reading SQS queue

### ISSUE THREAD

**Issue by PraveenJayakrishnakumar** [elastic/logstash#2190]
We are using logstash indexer to read all logs from logstash-agent. But, sometime, we are getting checksum failed error. we are using logstash verion 1.4.3

:message=>"Error reading SQS queue.", :error=>#&lt;AWS::SQS::Errors::ChecksumError: 2 messages failed checksum verification&gt;,

**Comment by keithhigbee** [comment]
Praveen,

Take a look at the last message in the thread for a workaround to keep you moving forward. 

https://groups.google.com/forum/#!topic/logstash-users/PXAPD0JntyU

**Comment by PraveenJayakrishnakumar** [comment]
Thanks for your response, Like you said, it is just workaround. But, I am looking for the permanent solution in production box.

**Comment by slevine** [comment]
+1

**Comment by loganbhardy** [comment]
+1 as well.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-sqs/issues/9. Let's continue the discussion there! :)
