### ISSUE TITLE
missing unit in documentation for discover_interval (file input plugin)

### ISSUE THREAD

**Issue by evanroode** [elastic/logstash#2191]
Documentation for the file input plugin does not specify what unit discover_interval is in

http://logstash.net/docs/1.4.2/inputs/file
---
discover_interval
  Value type is number
  Default value is 15
  How often we expand globs to discover new files to watch.
----

sincedb_write_interval does specify a unit "in second", stat_interval does not.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/33. Let's continue the discussion there! :)
