### ISSUE TITLE
unexplained behaviour without --debug command line argument

### ISSUE THREAD

**Issue by acarzis** [elastic/logstash#2192]
I am using logstash/elasticsearch/kibana with input from nxlog on a windows 7 computer.

my configuration is such that nxlog is communicating to logstash on 4 tcpip channels (output = om_tcp). Hence, my logstash config is listening on 4 tcp servers.

My logstash filter is broken into 4 sections via 'if [type] == 'xxxx' { } sections. All 4 sections are rather complex. Output is to elasticsearch, stdout (rubydebug codec), and to a file.

During testing, it was observed that processing of input would stop after some time and data was not being inserted into elasticsearch. Further testing revealed that output to elasticsearch was failing (halted) yet output to a file would continue as long as input was being provided.

This behaviour was found to be true for one of the logstash inputs. For what it's worth, the filter uses the xml filter.

After further testing, it has been determined that running logstash with the --debug argument does not cause any issues.

Note: I have not run tests to determine whether or not the issue is true with the other 3 inputs. Perhaps the issue is caused by the xml filter. I don't know this yet.

Any feedback is greatly appreciated.

**Comment by untergeek** [comment]
Ticket stale, with no updated information in over a year.  Since then, there have been many changes to Logstash and the plugins, which may have had some effect on the behavior described.

Feel free to re-open if more information can be provided so we can replicate what happened.
