### ISSUE TITLE
Date filter issues could not use log date

### ISSUE THREAD

**Issue by waleedsaud** [elastic/logstash#2194]
Date filter did not work for me on netscreen firewall logs and this is my config:
input {
  tcp { 
    type => "J-NS5400-5"
    port => 3333
  } 
}

filter {
  if [type] == "J-NS5400-5" {
    grok {
      
      match => { "message" =>"%{NETSCREENSESSIONLOG}"}
    }

    date {

      match => [ "date", "MMM dd HH:mm:ss" ]
      timezone => "Asia/Riyadh"
      locale => "en_SA"

    }
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
   embedded => true
  }
}

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-date/issues/18. Let's continue the discussion there! :)
