### ISSUE TITLE
logstash and monolog formatter

### ISSUE THREAD

**Issue by tzookb** [elastic/logstash#2196]
I am using the monolog logstashFormater to create my logs, than I want to insert it in to my logstash.

Here is an example of a log created by monolog:

    {"@timestamp":"2014-12-08T09:07:54.810335+00:00","@source":"devServer","@fields":{"channel":"orderLogger","level":100,"ctxt_site":"roulette","ctxt_country":"uk","ctxt_type":"virtual"},"@message":"order","@tags":["orderLogger"],"@type":"core"}

It is built good for logstash,
now I load the logstash with this config

    input {
       stdin { }
    }
  
    output {
       stdout { codec => rubydebug }
    }

but now I try to paste the created log from monolog and I get this:

    {
       "message" => "{\"@timestamp\":\"2014-12-08T09:07:54.810335+00:00\",\"@source\":\"devServer\",\"@fields\":{\"channel\":\"orderLogger\",\"level\":100,\"ctxt_site\":\"roulette\",\"ctxt_country\":\"uk\",\"ctxt_type\":\"virtual\"},\"@message\":\"order\",\"@tags\":[\"orderLogger\"],\"@type\":\"core\"}",
      "@version" => "1",
    "@timestamp" => "2014-12-08T09:08:24.800Z",
          "host" => "logstash"
    }

so as you can see, logstash didn't parse it right, it simply place all the string inside the message.

Any ideas?

**Comment by jordansissel** [comment]
This has had needs-more-info label since December 2014; gonna close this as idle.
