### ISSUE TITLE
.logstash-forwarder needs a default location

### ISSUE THREAD

**Issue by dlangille** [elastic/logstash#2209]
It would be useful to have .logstash-fowarder in a default location, such as /var/db/.loststash-forwarder

ref:https://groups.google.com/forum/#!searchin/logstash-users/.logstash-forwarder$20file$20location/logstash-users/DYGt8ngR98c/Ldy29Andg5gJ

A configuration option would set any other location.

**Comment by suyograo** [comment]
moved to https://github.com/elastic/logstash-forwarder/issues/505
