### ISSUE TITLE
plugin nagios_nsca doesn't work

### ISSUE THREAD

**Issue by pulecp** [elastic/logstash#2213]
Hi,
I have problem with nagios_nsca plugin on following setup:

    logstash: 1.4.2-1_2c0f5a1
    kernel: 2.6.32-358.14.1.el6.x86_64
    java: version "1.7.0_25"
    OpenJDK Runtime Environment (rhel-2.3.10.4.el6_4-x86_64)
    OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

run of plugin is ending with following error:

<pre><code>
{:timestamp=>"2014-12-10T08:35:52.571000+0100", :message=>"Backtrace", :backtrace=>["org/jruby/RubyIO.java:2097:in `close'", 
"/opt/logstash/lib/logstash/outputs/nagios_nsca.rb:119:in `receive'", "org/jruby/RubyIO.java:4433:in `popen3'", 
"file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/open3.rb:74:in `popen3'", 
"/opt/logstash/lib/logstash/outputs/nagios_nsca.rb:117:in `receive'", "/opt/logstash/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):44:in 
`initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:266:in `output'", 
"/opt/logstash/lib/logstash/pipeline.rb:225:in `outputworker'", "/opt/logstash/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:debug}
</code></pre>

I unsuccessfully tried fix described here: https://logstash.jira.com/browse/LOGSTASH-2286

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-nagios_nsca/issues/3. Let's continue the discussion there! :)
