### ISSUE TITLE
Add newer_than option to file input.

### ISSUE THREAD

**Issue by stp72** [elastic/logstash#2224]
I'm trying to use the logstash file input to ingest logs.  The directory structure is as follows /logs/YYYY/MM/DD/<log_file_name_with_date_time_stamp>.  It would be nice to be able to have a newer_than option in order to limit what files are ingested either by the file's date timestamp or via an expression to parse out the date timestamp from the file name.  It would also be nice if it could handle relative dates as in 5d for anything new in the last 5 days, etc.

Thanks!

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/34. Let's continue the discussion there! :)
