### ISSUE TITLE
Logstash plugin documentation renders very badly on mobile platforms.

### ISSUE THREAD

**Issue by dbeckham** [elastic/logstash#2226]
The Logstash [plugin documenation](http://www.elasticsearch.org/guide/en/logstash/current/filter-plugins.html) in the newly released [1.5 Beta Guide](http://www.elasticsearch.org/guide/en/logstash/current/index.html) renders very badly on mobile platforms.  The lists in the middle and right side of the page overlap and are impossible to read and it's very difficult to find and click the link you are looking for.  This happens for all plugins, output, filter and codec.

Please, won't someone think of the mobile children?

**Comment by jordansissel** [comment]
Confirmed this is still an issue.

**Comment by untergeek** [comment]
Agree this is still a problem.  Assigning this to our docs lead, @palecur

**Comment by jsvd** [comment]
![screenshot_20160311-171232](https://cloud.githubusercontent.com/assets/31809/13709619/c37c1462-e7ac-11e5-83a4-1dc48164decd.png)

**Comment by suyograo** [comment]
Closing this ATM. Will not be fixing.
