### ISSUE TITLE
The Logstash Ruby plugin documentation is incomplete.

### ISSUE THREAD

**Issue by dbeckham** [elastic/logstash#2227]
The [Ruby plugin documentation](http://www.elasticsearch.org/guide/en/logstash/current/plugins-filters-ruby.html) is incomplete and only documents the basic configuration option details.

Specifically, the code configuration option is the most important part of the configuration options, but it is one of the least documented options.

Issues:
- There are no links to documentation or Logstash code that describes what the ```event``` variable is, or even what type of variable it is. We can assume it's some sort of hash or object based on the single example, but other than that, there are no details. What attributes or methods are available? Is it immutable? Can you alter the contents of other fields?
- What constraints are placed on Ruby code used with this plugin? i.e. are there any special keywords that can not be used, limits on methods used, or any particular characters that need special escaping?
- What happens when Ruby code throws an exception?  Does Logstash silently drop the event, or does the filter just fail?

A simple link to the description of the event variable, or a wider range of examples may help solve several of these issues.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-ruby/issues/7. Let's continue the discussion there! :)
