### ISSUE TITLE
Ensure "at least one" semantic

### ISSUE THREAD

**Issue by Fodoj** [elastic/logstash#2242]
Is there a way to ensure "at least one" semantic in logstash? I want to be sure that no events are lost between input and output. Typical example is:

1. In input - take a message from a queue
2. Send it to filters and output
3. If output succeeds (let's say I post message via http and "success" is 200 response) then remove message from queue.

So message is removed from queue _only_ if output successfully delivers this message and if something terrible happens (logstash crashes, destination for output is not available or behaves weird) I will never lose any data I need to deliver.

**Comment by suyograo** [comment]
Closing this in favor of https://github.com/elastic/logstash/issues/3693 and #2609
