### ISSUE TITLE
Logstash does not properly pick up the last position in file on restart

### ISSUE THREAD

**Issue by jchalos** [elastic/logstash#2246]
Symptom:  Logstash misses log events when using the file input if the logstash process is restarted or stops unexpectedly and is restarted.  It appears that the sincedb file is not being utilized on startup.

Utilizing 'start_from => "beginning"' will result in duplicate data and is not the intended behavior.  It should pick up the log from the last read position when re-starting.

Logstash version:1.4.2

Reproduction:

input {
  file {
    path => "/tmp/\*\*/\*.log"
    sincedb_path = "/tmp/logstash.sincedb"
  }
}

1. Start logstash
2. Append data to multiple logs in the directories being scanned.
3. Stop logstash
4. Append additional data to logs(This data will be missing including all data appended to the logs while logstash is starting)
5. Start logstash
6. Append additional data to logs(Eventually the logs will be read from the end again)

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/35. Let's continue the discussion there! :)
