### ISSUE TITLE
Bug whitelist_name in prune filter?

### ISSUE THREAD

**Issue by alejgamez** [elastic/logstash#2253]
Hi everyone,

 I have a problem with the whitelist of prune filter, I don't know if this filter has some bug . I want to insert some fields in Elasticsearch and the logstash insert more fields. 

Thanks

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-prune/issues/1. Let's continue the discussion there! :)
