### ISSUE TITLE
Multiple patterns applied to a single event caused confusion.

### ISSUE THREAD

**Issue by shufang** [elastic/logstash#2257]
We have two kinds of log files need to be indexed. I created 2 input files and 2 filter files for each kind of the log files. In the filter files I have if statement to check if is type a, use type a's custom pattern, and if is type b, use type b's customer pattern. What I see from kibana later is that for a part of message, it has both patterns applied.  You can check this from the image I uploaded. (The log types are different from the image and what I have copy pasted the code following. But the issues are the same). How can I avoid this? I thought the if statement should tell specifically which pattern to use. Why it search and apply all the patterns?

$ cat 10-bi-nqcluster-input.conf 
input {
  file {
    type => "binqcluster"
    tags => "binqcluster"
    path => [ "/xx/coreapplication_obiccs1/nqcluster.log" ]
    codec => plain { charset => "ISO-8859-1" }
  }

$ cat 10-bi-scheduler-input.conf
input {
  file {
    type => "binqscheduler"
    tags => "binqscheduler"
    path => [ "/xx/coreapplication_obisch1/nqscheduler.log" ]
    codec => plain { charset => "ISO-8859-1" }
  }
}

$ cat 20-bi-nqcluster-filter.conf 
filter {
if [type] == "binqcluster" {
  grok {
    patterns_dir => "/opt/logstash/patterns"
    match => ["message", "%{BI_NQCLUSTER_LOG}"]
  }
}

$ cat 20-bi-nqscheduler-filter.conf
filter {
  if [type] == "binqscheduler" {
  grok {
    patterns_dir => "/opt/logstash/patterns"
    match => ["message", "%{BI_NQSCHEDULER_LOG}"]
  }
}

$ cat /opt/logstash/patterns/binqcluster 

BI_NQCLUSTER_LOG_FMT1 \[%{TIMESTAMP_ISO8601:binqcluster-logtimestamp}\] \[%{DATA:binqcluster-component}\] \[%{DATA:binqcluster-loglevel}\] \[%{DATA:binqcluster-misc_data1}\] \[%{DATA:binqcluster-misc_data2}\] \[ecid:%{DATA:binqcluster-ecid}\] \[tid: %{DATA:binqcluster-tid}\]  \[%{DATA:binqcluster-misc_data3}\] %{GREEDYDATA:logmessage}

BI_NQCLUSTER_LOG_FMT2 \[%{TIMESTAMP_ISO8601:binqcluster-logtimestamp}\] \[%{DATA:binqcluster-component}\] \[%{DATA:binqcluster-loglevel}\] \[%{DATA:binqcluster-misc_data1}\] \[%{DATA:binqcluster-misc_data2}\] \[ecid:%{DATA:binqcluster-ecid}\] \[tid: %{DATA:binqcluster-tid}\] %{GREEDYDATA:logmessage}

BI_NQCLUSTER_LOG %{BI_NQCLUSTER_LOG_FMT1}|%{BI_NQCLUSTER_LOG_FMT2}

$cat /opt/logstash/patterns/binqscheduler 

BI_NQSCHEDULER_LOG \[%{TIMESTAMP_ISO8601:binqscheluder-logtimestamp}\] \[%{WORD:binqscheluder-server}\] \[%{DATA:binqscheluder-loglevel}\] \[%{DATA:binqscheluder-code}\] \[%{DATA:binqscheluder-codepath}\] \[tid: %{DATA:binqscheluder-tid}\] \[userId: %{DATA:binqscheluder-userid}\] \[ecid: %{DATA:binqscheluder-ecid},%{DATA:binqscheluder-afterecid}\] \[APP: %{DATA:binqscheluder-app}\] %{GREEDYDATA:logmessage}

![logstash](https://cloud.githubusercontent.com/assets/10224421/5477603/9fc1b3de-85e1-11e4-9404-1ced5532c38e.jpg)

**Comment by suyograo** [comment]
Please open a new topic in https://discuss.elastic.co/c/logstash
