### ISSUE TITLE
Logstash stops working if PagerDuty output encounters errors

### ISSUE THREAD

**Issue by cschotke** [elastic/logstash#2260]
Our logstash environment has been taken down a couple times this week due to a misconfiguration in one of our config files with the PagerDuty output. It took us a long time to identify the issue. I'm wondering if there is any way to prevent this going forward or at least an easier way to pinpoint what is causing the issue in the future. 

We typically process 5,000,000 + msgs per hour. We use the PagerDuty output pretty heavily but always use the Throttle filter to make sure we are not sending too many messages to PD. PD has rate limiting which will start rejecting requests if you send it more that 60 in a minute. We misconfigured the Throttle config in one of our files which resulted in us trying to send a large number of requests to PD really quickly. It appears this is what crippled our environment and took us down to < 1,000 msgs per hour. 

We are assuming PagerDuty started rejecting requests from our PagerDuty output, which resulted in the Logstash queue getting filled up, which stopped us from grabbing messages from Redis for processing. 

Is there a way to configure the PagerDuty output to prevent this type of issue? Also, is it possible to view the status of the logstash queues or even see which messages are currently in the queue? This would have allowed us to identify and solve the issue much more quickly. 

Thanks

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-pagerduty/issues/6. Let's continue the discussion there! :)
