### ISSUE TITLE
Any plan to eval/merge outstanding contrib/plugin pull requests before starting yet another project?

### ISSUE THREAD

**Issue by bitsofinfo** [elastic/logstash#2264]
After reading this: http://www.elasticsearch.org/blog/plugin-ecosystem-changes

I see that there is now yet another copy of the plugins projects, and there are still 25 issues and 70+ outstanding pull requests from the old "logstash-contrib" project @ https://github.com/elasticsearch/logstash-contrib. 

Why not merge these in before starting yet this second version of the plugins? Isn't this going to lead to more confusion with everyone's fixes/contributions that will now be orphaned?

**Comment by jordansissel** [comment]
(I think this is resolved)
