### ISSUE TITLE
Logstash email SMTP options documentation needs work

### ISSUE THREAD

**Issue by mefforda-avalon** [elastic/logstash#2267]
The documentation around custom SMTP connections on the outbound email connector is inadequate and inaccurate.  It appears it is a cut and past from the Ruby Mail documentation and following does not result in a working config.  

More specifically, the options block is listed as an hash, but when using a hash the options are ignored.  If however you encode those options as an array they do seem to work, but there is no example in the documentation that suggests this is the case.  What is there suggests it should be a hash.

I.E.

Documentation suggests that this works:
               options => { "smtpIporHost","gmail.com" }

It does not.

However, this does work
               options =>  [ "smtpIporHost","gmail.com" ]

Also some of the older versions of this documentation are worse and don't even state the config value name correctly instead refer to 'address' while the code clearly references 'smtpIporHost'.

This was tested using 1.4.2

**Comment by jordansissel** [comment]
Agreed; First, the docs would benefit from improvement.
Second, I think the plugin should probably not have this `options` setting and instead expose specific settings for each thing currently available via this confusing `options` setting.

**Comment by jordansissel** [comment]
Filed https://github.com/elastic/logstash/issues/3242 to track splitting up the `options` setting

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-email/issues/24. Let's continue the discussion there! :)
