### ISSUE TITLE
grok should ignore tilde backup files when processing patterns_dir 

### ISSUE THREAD

**Issue by mrec** [elastic/logstash#2271]
(This comes from the discussion of #2244)

When testing a config using grok and custom patterns, a user will often be editing pattern definition files in `patterns_dir` between run attempts. Many (most?) Linux-ey text editors create backup files, named as the original filename plus a `~` suffix, in the same location as the original; even though they aren't hidden these are often invisible by default in file browsers. When dealing with multiple pattern definition files, and especially when renaming them, it's possible to have a lot of these tilde files lying around after a while.

`grok` currently reads *everything* in `patterns_dir`, including any tilde backups. It quite reasonably doesn't define the order in which it reads them, and it doesn't warn if e.g. the definition of `MYPATTERN` in a stale `patterns~` or `previousfilename~` backup file overrides the definition of `MYPATTERN` in `patterns`. Hilarity ensues. Also hair-tearing, teeth-gnashing, bad language and various other undesirable outcomes.

I propose that `grok` should ignore any files in `patterns_dir` ending in a `~`. There may be other things it'd be beneficial to blacklist too, but this seems like a good start.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/33. Let's continue the discussion there! :)
