### ISSUE TITLE
Logstash - Date Plugin - What's wrong ?

### ISSUE THREAD

**Issue by tombishop-83** [elastic/logstash#2273]
I provided two date format, but only one seems to work. Despite all three lines are being matched. Briefly, here is my config 

input{ 
 stdin {
   type => "DefaceTimestamp"
 }
}

filter{
  grok{
   match => { "message" => "%{DATESTAMP:DefaceTimestamp}|%{TIMESTAMP_ISO8601:DefaceTimestamp}" }
  }
  date{
   match => ["DefaceTimestamp","dd/MM/yyyy HH:mm:ss", "yyyy-MM-dd HH:mm:ss"]
   timezone => "UTC"
  }

 if "_grokparsefailure" in [tags] {
    mutate{
     remove_field => ["host","@version","_id","_type"]
    }
 } 
 else if [type] == "DefaceTimestamp" {
    mutate{
#     add_field => { "Malware_type" => "%{SHD_drone_type}"}
     remove_field => ["host","@version","_id","_type", "message"]
    }
  }
}

output{
 stdout{ codec => rubydebug }
}

Here is my input 

09/03/2014 08:36:00
08/03/2014 05:44:00
2014-01-03 13:47:24

Here is the output 

{
         "@timestamp" => "2014-03-09T08:36:00.000Z",
               "type" => "DefaceTimestamp",
    "DefaceTimestamp" => "09/03/2014 08:36:00"
}
{
         "@timestamp" => "2014-03-08T05:44:00.000Z",
               "type" => "DefaceTimestamp",
    "DefaceTimestamp" => "08/03/2014 05:44:00"
}
{
         "@timestamp" => "0014-01-03T13:47:24.000Z",       <-------  Weird ??????  
               "type" => "DefaceTimestamp",
    "DefaceTimestamp" => "14-01-03 13:47:24"

Thanks

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-date/issues/19. Let's continue the discussion there! :)
