### ISSUE TITLE
Quotes being escaped

### ISSUE THREAD

**Issue by kxr** [elastic/logstash#2275]
Hi,

I am running a ELK stack setup (udp_input->logstash->elasticsearch). I am using the "udp" input method on port 514 to get the syslog messages.
(I switched from "syslog" input to "udp" input because one of the major appliance (barracuda WAF) is not using a standard syslog format that the syslog-input in logstash can understand.)

The problem I am facing is quite odd. Some of the log messages (very randomly and very few i.e. 1 out of 10K) received from the WAF would appear to have their quoutes escaped in the message.

At first I thought its the WAF doing this. However, I watched the tcpdump traffic and noticed that the original packet/message for these messages (the ones having their quotes escaped) were fine. Apparently its the logstash adding the escaped characters.

Here is my logstash filter for the WAF: http://pastebin.com/raw.php?i=Sv7QpG6s

Here are a few incidents that show you the tcpdump message and the corresponding logstash mesage: http://pastebin.com/raw.php?i=zaVY9eFq

I really thank you in advance for any help/hints you can provide me to debug this problem.

Thanks,
Khizer

**Comment by jordansissel** [comment]
I'm not sure what the issue was here. There's not enough info for me to easily figure out what the problem was (no input configuration is available, for example). If you continue to have issues, please visit https://discuss.elastic.co/ and create a new topic on the logstash forum, and we'll see what we can help with :)

**Comment by jordansissel** [comment]
(closing since last update was December 2014)
