### ISSUE TITLE
Logstash having trouble accessing a file it has permissions to access

### ISSUE THREAD

**Issue by patcable** [elastic/logstash#2281]
Hi! 

I'm trying to reuse Puppet keys for Lumberjack (since they're already distributed on all my hosts anyways). This is on CentOS 7.

I have lumberjack set as an input:
```
  lumberjack {
    port => 10514
    ssl_certificate => "/var/lib/puppet/ssl/certs/coolhost.pem"
    ssl_key => "/var/lib/puppet/ssl/private_keys/coolhost.pem"
  }
```
I added the `logstash` user to the `puppet` group, and i'm able to run `sudo -u logstash cat /var/lib/puppet/ssl/{...}` etc. (I can run `ls` too)

I'm getting an error when I try to start logstash:
```
{:timestamp=>"2014-12-22T20:31:48.781000+0000", :message=>"Invalid setting for lumberjack input plugin:\n\n  input {\n    lumberjack {\n      # This setting must be a path\n      # File does not exist or cannot be opened /var/lib/puppet/ssl/private_keys/coolhost.pem\n      ssl_key => \"/var/lib/puppet/ssl/private_keys/coolhost.pem\"\n      ...\n    }\n  }", :level=>:error}
```
Which is odd, because:
```
[cat@logstash ~]$ id logstash
uid=998(logstash) gid=997(logstash) groups=997(logstash),52(puppet)
```
It's also odd because I can cat those files as the `logstash` user (`sudo -u logstash cat/ls blah`). SELinux is in permissive mode. It works fine if in `/etc/init.d/logstash` I change `LS_GROUP` to `puppet`, but that doesn't seem like the Right Thing To Do™.

**Comment by davidmach14** [comment]
Hi, we have same problem with Logstash Agent 1.4.2. Unfortunately there is no record in Logstash error log though {{--debug}} parameter is set. It seems like Logstash is ignoring permission system in Linux (CentOS 6.5)...

**Comment by lfrancois** [comment]
My way to fix it was to just to make sure the files are owned by the logstash user.

RUN chown -R logstash:logstash my_certificates

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/1398
