### ISSUE TITLE
multiline matching woes

### ISSUE THREAD

**Issue by jasperla** [elastic/logstash#2282]
I'm having a hardtime understanding how to make logstash match my given input.

The log file looks like this, though it may have multiple indented lines like "Storage", "Job", etc:

```
27-Nov 20:25 obsidian.office.jasper.la-sd JobId 17: Please mount append Volume "Inc-0003" or label a new one for:
    Storage:      "obsidian.office.jasper.la-device" (/usr/backup2)
27-Nov 20:25 obsidian.office.jasper.la-sd JobId 17: Finished
27-Nov 20:25 obsidian.office.jasper.la-sd failed to connect to db:
user=foo
password=bar
```

The input is very irregular, which makes this even harder, but my config looks like:

```
input {
  file {
    path => [ '/tmp/bacula.log' ]
    type => "bacula"
	  codec => multiline {
		  pattern => "^\s"
		  what    => "previous"
	  }
  }
}

filter {
	if [type] == "bacula" {
		grok {
			match => [ "message", "(?<timestamp>%{MONTHDAY}-%{MONTH}\s+%{HOUR}:%{MINUTE})\s+(?<hostname>%{HOSTNAME})-(?<daemon>(dir|sd|fd))\s+JobId\s+(?<jobid>%{NUMBER}):\s+(?<message>.?*)|\s+Storage:\s+(?<device>%{GREEDYDATA})\s+\((%{PATH:mountpoint})\)" ]
			add_tag => [ "grokked" ]
		}
		date {
			match => [ "timestamp", "dd-MMM HH:mm"]
			add_tag => [ "dated" ]
		}
	}
```

However this results in only parsing of the second part:
```
{
    "@timestamp" => "2014-12-22T02:02:51.999Z",
       "message" => "0:25 obsidian.office.jasper.la-sd JobId 17: Please mount append Volume \"Inc-0003\" or label a new one for:\n    Storage:      \"obsidian.office.jasper.la-devic
e\" (/usr/backup2)",
      "@version" => "1",
          "tags" => [
        [0] "multiline",
        [1] "grokked"
    ],
          "type" => "bacula",
          "host" => "smoker.fritz.box",
          "path" => "/home/jasper/bacula.log",
        "device" => "\"obsidian.office.jasper.la-device\"",
    "mountpoint" => "/usr/backup2"
}
```

Should I perhaps have some logic in the filter{} block to switch on `multiline in [tags]` or could I have both in a single `type == "bacula"`? My regex is sane according to grokdebug as given a single line of input, it correctly shows all the right fields, but something goes wrong when it's multilined..

**Comment by suyograo** [comment]
Hi @jasperla do you still have this issue?

**Comment by codearoo** [comment]
I left a comment regarding my opinion that multiline   what => next   has a bug.  and that "next" seems much more useful than "previous" because using "previous" causes you it to "stall" if a log event follows that is not multi-line.. logstash won't output that event unless it receives another event after it.

https://github.com/elasticsearch/logstash/issues/2262

**Comment by jordansissel** [comment]
@codearoo the stall is prevented with by having the multiline filter flush out anything that is probably "done" (no new messages for a given pending "next" in some time period, configurable). This setting is controllable with `max_age` in the multiline filter. In Logstash 1.4.x this was not working due to a bug and is now fixed in 1.5.0 beta1 and beyond

**Comment by codearoo** [comment]
oh.. I see... I only have ver 1.4.2.

May I still suggest that the solution is just a fix for what really should
be used which is "next" upon finding what a user would define is a valid
"log entry"   However from my post I find the "next" feature not working
correctly, and maybe there is some workaround.

**Comment by codearoo** [comment]
oh.. this is wrong I think...  I guess   multiline   will cause the process to stop if the entry is a single line. That just seems...  really hard to deal with. If that's by desired design, maybe another property like "continue_if_notwhatever => true"  ??

**Comment by jordansissel** [comment]
>  I guess multiline will cause the process to stop if the entry is a single line

I'm not sure I understand what you're saying. What stops?

**Comment by suyograo** [comment]
Closing this since 2.0 has a lot of improvements in multiline. Please reopen if still an issue
