### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by igor-derzhavin** [elastic/logstash#2284]
Hi, all. I use logstash 1.4.2 and I run into a memory leak on my server. This is a graph from Zabbix: 
![logstash](https://cloud.githubusercontent.com/assets/8733909/5536355/77bf0ae8-8aa1-11e4-8ea2-f6ac2d09e50c.png)

15.12 - logstash has been restarted (manually).

Server config:
Ubuntu 14.04 LTS
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
Logstash CMD:
/usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=10961 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Xmx1024m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintClassHistogram -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:./logstash-gc.log -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -I/opt/logstash/lib /opt/logstash/lib/logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log

Logstash config:

```
input {
  tcp {
    port => 5000
    type => syslog
  }
  udp {
    port => 5000
    type => syslog
  }
  tcp {
    port => 5001
    type => cisco_syslog
  }
  tcp {
    port => 5002
    type => skylark_log
    codec => json
  }
  tcp {
    port => 5003
    type => records
    codec => json
  }
}
filter {
  if [type] == "syslog" {
    grok {
      patterns_dir => [ "./grok_patterns" ]
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:hostname} %{DATA:program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => {
              "received_at" => "%{@timestamp}"
              "received_from" => "%{host}"
           }
    }
    syslog_pri { }
    date {
      locale => "en"
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      timezone => "Etc/GMT-3"
    }
  }
  if [type] == "skylark_log" or [type] == "records" {
    date {
       add_field => { "received_at" => "%{@timestamp}" }
       match => [ "timestamp", "ISO8601" ]
       remove_field => [ "timestamp" ]
       timezone => "Etc/GMT-3"
    }
    metrics {
       meter => [ "log_counter.%{hostname}" ]
       add_tag => [ "zbx_metric" ]
       flush_interval => 60
       rates => [1]
       add_field => [ "zabbix_host", "%{hostname}",
                      "zabbix_item", "log_counter_1m",
                      "send_field",  "log_counter.%{hostname}.rate_1m" ]
       }
  }
  if [type] == "records" {
    if [host] =~ /192\.168\.118\.\d+/ {
      mutate {
        add_field => { "project" => "Сибирь" }
      }
    }
    else if [host] =~ /192\.168\.208\.\d+/ {
       mutate {
        add_field => { "project" => "Центр" }
       }
    }
  }
  if [type] == "cisco_syslog" {
    grok {
       match => { "message" => ": %{SYSLOGHOST:hostname}: %{SYSLOGTIMESTAMP:syslog_timestamp}: %{DATA:program}: %{GREEDYDATA:syslog_message}" }
       add_field => [ "received_at", "%{@timestamp}" ]
       add_field => [ "received_from", "%{host}" ]
       add_field => [ "device_type", "cisco" ]
     }
     syslog_pri { }
     date {
       locale => "en"
       timezone => "UTC"
       match => [ "syslog_timestamp", "MMM  d HH:mm:ss.SSS", "MMM dd HH:mm:ss.SSS" ]
     }
   }
   if [program] =~ /^zabbix-[a-z]+$/ {
     grok {
       match => { "syslog_message" => "(?<zbx_timestamp>\d{8}:\d{6}\.\d{3}) %{GREEDYDATA:zbx_message}" }
     }
     date {
       match => [ "zbx_timestamp", "YYYYMMdd:HHmmss.SSS" ]
     }
     mutate {
       replace => [ "syslog_message", "%{zbx_message}" ]
       remove_field => [ "zbx_timestamp", "zbx_message" ]
     }
   }
}
output {
        elasticsearch { 
            protocol => http
            host => localhost 
        }
}
```

Also I have no suspicious events at any logs.
Average messages rate ~4000 per minute.

**Comment by chenbekor** [comment]
@iGaryk  can you please advice on how to perform such graphs ? is logstash jmx ready? can we connect to it using some monitoring tools?

**Comment by iGaryk** [comment]
Hello, @chenbekor! I use Zabbix with zabbix-java-gateway for retrieve data from jmx. This feature is completely documented there https://www.zabbix.com/documentation/2.2/manual/config/items/itemtypes/jmx_monitoring

**Comment by chenbekor** [comment]
@iGaryk Oh - nice. So I guess logstash exposes JMX counters right? can you point me to the docs? I only see a JMX Input Plugin but I guess that's another story.

**Comment by iGaryk** [comment]
I just specify in /etc/defaults/logstash parameters for java like this:
LS_JAVA_OPTS="-Djava.io.tmpdir=${LS_HOME} \
             -Dcom.sun.management.jmxremote \
             -Dcom.sun.management.jmxremote.port=10961 \
             -Dcom.sun.management.jmxremote.authenticate=false \
             -Dcom.sun.management.jmxremote.ssl=false"
And in Zabbix I use "Interface JMX" for that host with specified jmxremote port.
This is not logstash feauture, but is java JVM feature.

**Comment by chenbekor** [comment]
sounds great - thanks!

**Comment by SkaveRat** [comment]
If anyone lands here via google: before suspecting a LS memory leak, check your client.

Upgraded to 1.5 and still had leaks, because my client didn't close the connection and LS kept them in memory
