### ISSUE TITLE
Multiple field patterns for message

### ISSUE THREAD

**Issue by OlesyaShell** [elastic/logstash#2286]
Hi!
Need to extract all fields from the events. Any fields that may not be or may be in a different order.
Examples:
<6> CEF:0|Stonesoft|IPS|5.2.6|271281|HTTP_SLS-Successful-Status-Code|1|spt=60494 deviceExternalId=IPS-1030 (moff) Sensor dmac=E4:C7:22:A4:17:E4 dst=192.168.0.1 requestMethod=GET cat=Protocol Information requestURL=www.ttttt.org app=HTTP rt=Dec 17 2014 20:18:49 act=Permit proto=6 dpt=80 src=172.16.0.1 dvc=172.16.0.1 dvchost=172.16.0.1 smac=90:E2:BA:19:A1:1B cs1Label=RuleId cs1=100.1

I try some configuration like at:
grok {
match => [
"message" => "dpt=%{INT:[dst][port]}"
"message" => "dst=%{IP:[dst][ip]}"
"message" => "src=%{IP:[src][ip]}"
"message" => "rt=%{STONEGATE_DATE:[event][time]}"
"message" => "deviceFacility=%{DATA}"
"message" => "src=%{IP:src_ip}"
"message" => "dst=%{IP:[dst][ip]}"
.....
]}
and other format:
grok {
match => {
"message" => [ "dpt=%{INT:[dst][port]}",  "dst=%{IP:[dst][ip]}", "src=%{IP:[src][ip]}" ]
}}
with fail result.
What is the correct syntax?
I try this config with 1.4.2, logstash 2.0.0.dev, 1.5.0.beta1

i also create full string patterns for this type message, check on https://grokdebug.herokuapp.com and try parse events at:
grok #first try
{
break_on_match => false #except in 4.2.X
match => ["message", "patern_1_from_patterns"]
}
grok { #next try - NOT WORK 
match => ["message", "patern_2_from_patterns"]
}
Thank you for help.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/34. Let's continue the discussion there! :)
