### ISSUE TITLE
Drupal en host filtering 

### ISSUE THREAD

**Issue by Karen09** [elastic/logstash#2295]
i just recieve crashing form grok filter when i add this code`s to my logstash config file 
any idee how to solve it ?

that is default config which worked 
filter {
      grok {
        match => ["message", "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{PROG:syslog_program} %{COMBINEDAPACHELOG}"]
      }

and i have added for drupal
      grep {
        type => "syslog"
        match => [ "syslog_program", "drupal" ]
        add_tag => "Drupal"
        drop => false
      }
      grok {
        type => "syslog"
        tags => [ "Drupal" ]
        match => [ "@message", "^https?://%{HOSTNAME:drupal_vhost}\|%{NUMBER:drupal_timestamp}\|(?<drupal_action>[^\|]*)\|%{IP:drupal_ip}\|(?<drupal_request_uri>[^\|]*)\|(?<drupal_referer>[^\|]*)\|(?<drupal_uid>[^\|]*)\|(?<drupal_link>[^\|]*)\|(?<drupal_message>.*)" ]

and for some host this confings
 
ex,message         <133>Dec 26 14:21:02 mediasalsa05 mds-err-ssl [Fri Dec 26 14:20:58 2014] [error] [client 127.0.0.1] Symbolic link not allowed or link target not accessible: /mnt/mediasalsa-edu0/mediasalsa_backendprod/media/1/D/D1YWnitidgCt8Z7fYaKQr4qR/D1YWnitidgCt8Z7fYaKQr4qR,mediamosa_sb_normal.jpg

grok {
        type => "syslog"
        host => "iphost"
        match => [ "@message", "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{PROG:syslog_program} %{SYSLOG5424SD} %{SYSLOG5424SD} %{SYSLOG5424SD} Symbolic link not allowed or link target not accessible: %{URIPATHPARAM}"]

when i manually set code at http://grokdebug.herokuapp.com/ its worked but not in logstash conf file,many thanks

**Comment by suyograo** [comment]
Please open a new topic in https://discuss.elastic.co/c/logstash. We can help you debug there.
