### ISSUE TITLE
document if file input support inotify

### ISSUE THREAD

**Issue by bfx81** [elastic/logstash#2301]
On this old jira entry seems that file input plugin support inotify since version 1.0
https://logstash.jira.com/browse/LOGSTASH-39

But looking at the docs http://logstash.net/docs/1.4.2/inputs/file
it's not mentioned, and the following option really sounds like a polling source.

>stat_interval
>How often we stat files to see if they have been modified. Increasing this interval will decrease the number >of system calls we make, but increase the time to detect new log lines.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/37. Let's continue the discussion there! :)
