### ISSUE TITLE
riemann output crashes logstash

### ISSUE THREAD

**Issue by kosfar** [elastic/logstash#2303]
Hello,
i tried to use something like this (LS version 1.4.2):
output {
...some other config here...

if [proc_name] == "kernel" and [syslog_severity] != "informational" {
   riemann {
    map_fields => true
     riemann_event => {
       "service"   => "Kernel traces"
        "state"    => "%{syslog_severity}"
     }
   }
 }

...some other config here...
}

but when an event that matches reaches the riemann output, logstash crashes with the following error message:
NoMethodError: undefined method `each' for #<LogStash::Event:0x55f721a9>
     map_fields at /opt/logstash/lib/logstash/outputs/riemann.rb:109
        receive at /opt/logstash/lib/logstash/outputs/riemann.rb:143
         handle at /opt/logstash/lib/logstash/outputs/base.rb:86
     initialize at (eval):1698
           call at org/jruby/RubyProc.java:271
         output at /opt/logstash/lib/logstash/pipeline.rb:266
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:225
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152

We use map_fields => true so that we can further split streams per host in riemann.

Any hints?

**Comment by kosfar** [comment]
Yeah, it seems to be related.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-riemann/issues/3. Let's continue the discussion there! :)
