### ISSUE TITLE
if directory structure has 'rspec' in the name it fails to startup logstash

### ISSUE THREAD

**Issue by electrical** [elastic/logstash#2305]
To make sure we don't startup logstash when running checks via rspec we do a check at https://github.com/elasticsearch/logstash/blob/master/lib/logstash/runner.rb#L200
This however also catches anything that has 'rspec' in any part of the path of the file.
In my case i have 'rspec' in one of the directory names.

We should improve the check.

**Comment by jordansissel** [comment]
haha, oops!

**Comment by suyograo** [comment]
No longer valid
