### ISSUE TITLE
Use of unset scriptname variable in init scripts

### ISSUE THREAD

**Issue by rtoma** [elastic/logstash#2314]
Files:
pkg/logstash-web.sysv.redhat 
pkg/logstash.sysv.redhat 
pkg/logstash-web.sysv
pkg/logstash.sysv 

... contain:

```
echo "Usage: $SCRIPTNAME {start|stop|force-stop|status|restart}" >&2
```

But $SCRIPTNAME is never set. It probably should be set with something like:

```
SCRIPTNAME=$( basename $0 )
```

**Comment by jsvd** [comment]
still a valid issue https://github.com/elastic/logstash/search?utf8=%E2%9C%93&q=SCRIPTNAME

**Comment by ph** [comment]
This seems to no be an issue anymore.
