### ISSUE TITLE
logstash binds to 9300 by default

### ISSUE THREAD

**Issue by stensonb** [elastic/logstash#2336]
the docs say the "embedded" version of elasticsearch is disabled by default: http://logstash.net/docs/1.4.2/outputs/elasticsearch#embedded

however, when omitting any reference to embedded elasticsearch in the logstash config, logstash binds to 9300.

this is causing a port-binding start-up race condition when a standalone ES process is on the same host (ES, by default, binds to 9300 for intra-cluster communication).

can we default logstash to some other port, by default, or by command-line argument?

**Comment by stensonb** [comment]
logstash  9040  6.2 37.9 1922876 190296 ?      SNsl 19:52   0:40 /usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -I/opt/logstash/lib /opt/logstash/lib/logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log
root@somehost:~# netstat -lanpt | grep LIST | grep java
tcp        0      0 0.0.0.0:46056           0.0.0.0:*               LISTEN      618/rpc.statd   
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      598/rpcbind     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      8181/nginx      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1148/sshd       
tcp6       0      0 :::111                  :::*                    LISTEN      598/rpcbind     
tcp6       0      0 :::9300                 :::*                    LISTEN      9040/java       
tcp6       0      0 :::57972                :::*                    LISTEN      618/rpc.statd   
tcp6       0      0 :::22                   :::*                    LISTEN      1148/sshd       
tcp6       0      0 :::16161                :::*                    LISTEN      9040/java

**Comment by untergeek** [comment]
Can you provide your config?  This is strange.  I don't see Logstash binding to port 9300 when I do not specify `elasticsearch` output with the default node protocol.

**Comment by untergeek** [comment]
My own logstash configuration:
```
input {
  redis {
    data_type => "list"
    host => "192.168.123.204"
    key => "logstash"
    threads => 2
  }
}

filter {
}

output {
  elasticsearch {
    host => "192.168.123.204"
    template_overwrite => true
    template => "/usr/local/etc/elasticsearch-template.json"
    protocol => "http"
  }
}
```

```
logstash  9923  7.8  1.5 2830336 253676 ?      SNsl  2014 2698:12 /usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Xmx760m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -I/opt/logstash/lib /opt/logstash/lib/logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log
buh@blackbox (01:01 PM) [~] » sudo netstat -lanpt | grep LIST | grep java
tcp6       0      0 :::9200                 :::*                    LISTEN      5993/java
tcp6       0      0 :::9300                 :::*                    LISTEN      5993/java
tcp6       0      0 192.168.123.204:25562   :::*                    LISTEN      3163/java
tcp6       0      0 192.168.123.204:25563   :::*                    LISTEN      25974/java
tcp6       0      0 :::12381                :::*                    LISTEN      2966/java
```
And the process that does own port 9300 is Elasticsearch:
```
buh@blackbox (01:04 PM) [~] » ps auwwx  |grep 5993
elastic+  5993 15.9 28.4 12168964 4670992 ?    Sl    2014 5501:28 /usr/bin/java -Xms5g -Xmx5g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.path.home=/opt/elasticsearch-1.4.2 -cp :/opt/elasticsearch-1.4.2/lib/elasticsearch-1.4.2.jar:/opt/elasticsearch-1.4.2/lib/*:/opt/elasticsearch-1.4.2/lib/sigar/* org.elasticsearch.bootstrap.Elasticsearch
```

**Comment by untergeek** [comment]
Also, in your elasticsearch.yml file, is port 9300 hard-coded as the only option?  By default, Elasticsearch should immediately try to use port 9301, 9302, etc. all the way up to 9399 if ports are unavailable.

My guess here is that even though you're not using the embedded Elasticsearch, you do have Logstash configured to use the elasticsearch output as a node (which will make it use port 9300).  The race condition is met because one or the other is hard-coded to only use port 9300.

**Comment by stensonb** [comment]
Thanks for jumping on this so quickly @untergeek !

I should clarify, I'm using the elasticsearch output plugin, but intend to NOT use the embedded version (I'm running ES in a separate JVM).

Here's my config:

```bash
input { 
  tcp { 
    port => 16161
    codec => json_lines 
  } 
}

filter {
  json {source => "message"}
}

output { 
  elasticsearch {
    host => '127.0.0.1'
    cluster => mozstash
  }
}
```

My standalone ES config has no explicit port range specified.

I'm working on a solid reproduction, but it's pretty simple...I'll confirm here when I've got it figured out (I filed this mostly to track my progress...we're not doing anything super "strange" with ES/logstash, but we are seeing this race condition).

**Comment by stensonb** [comment]
my ES config:

```bash
bryanstenson@somebox01:/etc/logstash/conf.d$ egrep -v '^($|#)' /etc/elasticsearch/elasticsearch.yml 
cluster.name: mozstash
node.name: somebox01
node.max_local_storage_nodes: 1
index.mapper.dynamic: true
action.auto_create_index: true
action.disable_delete_all_indices: true
path.conf: /etc/elasticsearch
path.data: /data/elasticsearch/data
path.work: /data/elasticsearch/work
path.logs: /var/log/elasticsearch
bootstrap.mlockall: true
network.publish_host: 10.10.10.10
http.port: 9200
gateway.expected_nodes: 1
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: 10.10.10.10,10.10.10.11
cloud.node.auto_attributes: true
```

**Comment by untergeek** [comment]
@stensonb Here it is:
```
output { 
  elasticsearch {
    host => '127.0.0.1'
    cluster => mozstash
  }
}
```
This configuration means that Logstash will spin up an Elasticsearch client-only node.  Unless you specify a port, it will automatically choose 9300.  You can get around this being a collision by specifying something 9301+ (recommend 9399 perhaps), or by using `protocol => "http"` instead (which is just as performant up to around 20,000 events per second).  Using the http protocol will mean that Logstash won't bind to 9300 because it won't spin up a client-node of Elasticsearch.

**Comment by untergeek** [comment]
To sum up:
- Logstash +  Embedded Elasticsearch => Elasticsearch server instance
- Logstash + elasticsearch output + node protocol (default protocol) => Logstash spins up Elasticsearch client-only instance

In both cases there will be an Elasticsearch instance spun up which will try to bind to port 9300.  One is a server instance, the other is a client-only instance.

The way to correct is to use `protocol => "http"` for your Elasticsearch output block, or `port => 9399` if you wish to keep using `protocol => "node"` (the default).

**Comment by stensonb** [comment]
Yup, that makes sense.

Does the "port" option for the elasticsearch output specify the port logstash binds to, or the port it communicates to ES on?

For the "http" protocol, it makes sense that the "port" option is the target port...are you saying the "node" protocol uses the "port" option as the source port?

**Comment by untergeek** [comment]
The `host` and `port` directives change behavior based on your choices.  With `protocol => "node"` it will be the `host` and `port` the client binds (See [here](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L291-L307)).  

With `protocol => "http"` `host` and `port` are the remote host:port you are targeting.

**Comment by stensonb** [comment]
I just added the "port" option, and now (per our discussion), expect logstash to be bound to 9501...it restarted and is still bound to 9300:

```bash
output { 
  elasticsearch {
    host => '127.0.0.1'
    cluster => mozstash
    port => 9501
  }
}
root@somebox01:~# sudo netstat -lanpt | grep LIST | grep java
tcp6       0      0 :::9300                 :::*                    LISTEN      8183/java       
tcp6       0      0 :::16161                :::*                    LISTEN      8183/java 
```

**Comment by untergeek** [comment]
9501 is a bad choice because it's outside the scope of what Elasticsearch expects (9300-9399).

That said, perhaps the code segment I linked is different from what's in your version (1.4.2?).  That code is from 1.5.

Personally, I recommend NOT using node protocol.  It introduces more complexity (Logstash's heap is now split to be able to accommodate an Elasticsearch client), and no real performance gains.

If you insist on keeping the node protocol, the most sure-fire way to force the issue is to put an elasticsearch.yml file in the Logstash directory.  Ensure it is configured to be client-only (master no, data no) and specify the ports you wish it to be using.  It will be read from at Logstash start-up and will use that configuration.

**Comment by untergeek** [comment]
Or, my bad, use `bind_port => 9399`.  That will work too.

**Comment by stensonb** [comment]
Well, I just verified that ```port``` seems to be ignored:

```bash
output { 
  elasticsearch {
    host => '127.0.0.1'
    cluster => mozstash
    port => 9302
  }
}
vagrant@mozstash-ubuntu-1404:/$ sudo netstat -lanpt | grep LIST | grep java
tcp6       0      0 :::9300                 :::*                    LISTEN      6610/java 
```

but ```bind_port``` works:

```bash
output { 
  elasticsearch {
    host => '127.0.0.1'
    cluster => mozstash
    bind_port => 9302
  }
}
vagrant@mozstash-ubuntu-1404:/$ sudo netstat -lanpt | grep LIST | grep java
tcp6       0      0 :::9302                 :::*                    LISTEN      7155/java    
```

So, at least the docs for ```bind_port``` are wrong...if omitted, ```bind_port``` is set to 9300 when in ```protocol = node``` (which is the default, if protocol is omitted).

I think ```bind_port``` should default to 9301 so that running ES and logstash in separate JVMs will "just work" -- with no race condition.

**Comment by stensonb** [comment]
http://logstash.net/docs/1.4.2/outputs/elasticsearch#bind_port

"There is no default value for this setting."  Should read "The default value for this setting is 9300."

**Comment by jordansissel** [comment]
@stensonb the default is the first port available to be bound to in the range 9300-9400, I believe.

The reason the documentation says "there is no default value" is because the docs are automatically generated. The default value his buried deep within Elasticsearch (outside of Logstash's codebase).

It is in these strange cases where I regret automatically-generated documentation.

**Comment by vivekmenon222** [comment]
On my windows machine logstash binds to port 9600.

If you look at 
logstash-6.0.0\config\logstash.yml

there is a part that says what port number it will use (pasted below)

# ------------ Metrics Settings --------------
#
# Bind address for the metrics REST endpoint
#
# http.host: "127.0.0.1"
#
# Bind port for the metrics REST endpoint, this option also accept a range
# (9600-9700) and logstash will pick up the first available ports.
#
# http.port: 9600-9700
