### ISSUE TITLE
TCP input and Log4j SocketAppenders

### ISSUE THREAD

**Issue by jeschergui** [elastic/logstash#2341]
I have a log4j version 1.2.17 socketAppender on one cloud sending data to my logstash server on another cloud.  I would like to secure the communication using SSL.

My original idea was to use the logstash TCP input and setup all my SSL stuff within it.
When I try this with the codec set to "plain", i get this - expected - error:

>{:timestamp=>"2015-01-12T11:06:52.961000+0100", :message=>"**Received an event that has a different character encoding than you configured.**", :text=>"**\\xAC\\xED\\u0000\\u0005sr\\u0000**!org.apache.log4j.spi.LoggingEvent\\xF3\\xF2\\xB9#t\\v\\xB5?\\u0003\\u0000", :expected_charset=>"UTF-8", :level=>:warn}
>{:timestamp=>"2015-01-12T11:06:52.968000+0100", :message=>"Received an event that has a different character encoding than you configured.", :text=>"threadNameq\\u0000~\\u0000\\u0001L\\u0000\\rthrowableInfot\\u0000+Lorg/apache/log4j/spi/ThrowableInformation;xp\\u0000\\u0000\\u0000\\u0000\\u0001Jݜ?\\u001Dt\\u0000\\eProjectSpecificAppenderTestpppt\\u0000\\u0005DEBUGt\\u0000\\u0004mainpw\\u0004\\u0000\\u0000'\\u0010pxysr\\u0000!org.apache.log4j.spi.LoggingEvent\\xF3\\xF2\\xB9#t\\v\\xB5?\\u0003\\u0000", :expected_charset=>"UTF-8", :level=>:warn}

The tcp input's attempt to decode the entry and fails since the message sent from log4j is Serialized and therefore makes use of some charsets that are not recognized UTF-8 chars...

Meanwhile, if I use the log4j input then the following code would make a perfect deserialization of the message - although with no possibility to use SSL :(

```# JRubyObjectInputStream uses JRuby class path to find the class to de-serialize to
      ois = JRubyObjectInputStream.new(java.io.BufferedInputStream.new(socket.to_inputstream))
      loop do
        # NOTE: log4j_obj is org.apache.log4j.spi.LoggingEvent
        log4j_obj = ois.readObject
        event = LogStash::Event.new("message" => log4j_obj.getRenderedMessage)```


So to my question... Will it be smart to develop a new logstash codec that I could use to deserialize the TCP data with - so that the hanlde_socket implementation inside the TCP input would deserialize the result in:
   *codec.decode(buf) do |event|
        event["host"] ||= client_address
        event["sslsubject"] ||= socket.peer_cert.subject if @ssl_enable && @ssl_verify
        decorate(event)
        output_queue << event
      end*

Also, Is my approach correct? Using TCP to make use of SSL to secure the communication and deserilize to catch the data?

By the way, All this hassle is due to my very limited access to the machine generating the logs. As a matter of fact, I only have log4j v1.2.17 SocketAppender at my disposition to solve this and insert some security to the cross cloud communication.

**Comment by wiibaa** [comment]
@jeschergui That's indeed a smart and lovely idea, moving log4j as a codec of the TCP input.
However I see a blocking point with the current tcp input and codec interfaces in that log4j input use directly the socket stream vs. tcp input is sending chunk of data to the codec that should do buffering and processing. But in the case of java serialized object [**you cannot identify end of object**](http://stackoverflow.com/questions/880457/how-do-i-identify-that-i-am-at-the-last-byte-of-a-serialized-java-object)
Need an architecture advice from the core logstash team for sure

**Comment by jeschergui** [comment]
That is exactly what I was perplexed about; the Log4j input's .to_inputstream VS. the TCP inputs's buf.sysread(k).

I think that an easier solution would be to extract the SSL operations to be done by a reverse proxy - something like nginx, and then let logstash work its way through the simple log4j input. Thanks for your insight.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-log4j/issues/11. Let's continue the discussion there! :)
