### ISSUE TITLE
Date format do est work with add_field

### ISSUE THREAD

**Issue by zhenghu** [elastic/logstash#2354]
I met a stranger problem with the date format.

When I put the %{+YYYY.MM.dd} by add_field, it does not work.
Here is the config and exception of elasticsearch : 

    input {
        rabbitmq {
                codec => oldlogstashjson
                host => "zer332o3"
                queue => "queue-test"
                user => "user"
                password => "password"
                threads => 1
                prefetch_count => 1
                type => "type-test"
                add_field => { "es-index" => "logstash-%{+YYYY.MM.dd}" }
                tags => [ "logstash-indexer-test" ]
        }
    }

    filter {

    }

    output {
        if ("logstash-indexer-test" in [tags]) and !("_grokparsefailure" in [tags]) and !("_jsonparsefailure" in [tags]) {
                elasticsearch_river_ha {
                        rabbitmq_host => "host"
                        es_host => "eshost"
                        exchange => "es-test"
                        exchange_type => "direct"
                        index => "%{es-index}"
                        key => "key-es-test"
                        queue => "queue-es-test"
                        user => "user"
                        password => "password"
                }
        }
    }

This is the exception of elasticsearch.

    <[2015-01-14 12:01:48,399][SUP][DEBUG][action.admin.indices.create] [dev142-zeg332o6] [logstash-%{+YYYY.MM.dd}] failed to create org.elasticsearch.indices.InvalidIndexNameException: [logstash-%{+YYYY.MM.dd}] Invalid index name [logstash-%{+YYYY.MM.dd}], must be lowercase
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:172)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:523)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$100(MetaDataCreateIndexService.java:87)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:220)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:309)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    >
    <[2015-01-14 12:01:48,401][SUP][WARN][river.rabbitmq] [dev142-zeg332o6] [rabbitmq][logstash-siklog-1.4.2-queue-es] failed to executefailure in bulk execution:[0]: index [logstash-%{+YYYY.MM.dd}], type [apache-access-log], id [null], message InvalidIndexNameException[[logstash-%{+YYYY.MM.dd}] Invalid index name [logstash-%{+YYYY.MM.dd}], must be lowercase]] >

But, when I put it directly in output for index, it works well.

    input {
        rabbitmq {
                codec => oldlogstashjson
                host => "zer332o3"
                queue => "queue-test"
                user => "user"
                password => "password"
                threads => 1
                prefetch_count => 1
                type => "type-test"
                tags => [ "logstash-indexer-test" ]
        }
    }

    filter {

    }

    output {
        if ("logstash-indexer-test" in [tags]) and !("_grokparsefailure" in [tags]) and !("_jsonparsefailure" in [tags]) {
                elasticsearch_river_ha {
                        rabbitmq_host => "host"
                        es_host => "eshost"
                        exchange => "es-test"
                        exchange_type => "direct"
                        index => "logstash-%{+YYYY.MM.dd}"
                        key => "key-es-test"
                        queue => "queue-es-test"
                        user => "user"
                        password => "password"
                }
        }
    }

This is the log of elasticsearch

    <[2015-01-14 11:56:53,506][SUP][INFO][cluster.metadata] [dev142-zeg332o6] [logstash-2015.01.14] creating index, cause [auto(bulk api)], shards [2]/[1], mappings [batch-wls, _default_, mersi-tech, log4erdf-default, storm, esri-service-system, log4erdf-fonctionnel, hadoop-yarn, es-log, fhm-access, hadoop-flume, esri-service-util, kafka, batch-etl, dynparklive-total, esri-service-app, jboss-stdout, ora-monitor, datapower, sic-appli, weblogic-admin-stdout, apache-access-log, mersi-home, fhm-alert, jboss-jdg, log4erdf-lsp-audit, kafka-lag, es-slow, hadoop-zookeeper, dynparklive-alert, log4erdf-flux, hadoop-hbase, fhm-error, jboss-boot, esri-server, log4erdf-monitoring, maximo, ora-alert, controlm, activemq, etl-error, weblogic-managed-stdout, apache-front-error-log, weblogic-access, jboss-server, log4erdf-erreur, apache-wls-error-log, drools, mersi-reveil, hadoop-hdfs, weblogic-server] >
    <[2015-01-14 11:56:53,822][SUP][INFO][cluster.metadata] [dev142-zeg332o6] [logstash-2015.01.14] update_mapping [apache-access-log] (dynamic) >

**Comment by wiibaa** [comment]
@zhenghu good catch, the decorate method of inputs/base does not currently use `event.sprintf(value)` neither for `add_field` nor `tags`.
https://github.com/elasticsearch/logstash/blob/master/lib/logstash/inputs/base.rb#L118

Could be indeed harmonized between inputs and filters

**Comment by zhenghu** [comment]
@wiibaa Thanks. So this issue is actually a bug, it will be fixed for the next release?

**Comment by wiibaa** [comment]
that's not really a blocker one as you can also easily use a mutate filter, so I'm not confident that the Logstash team will have time to look at it for next release, but I will try to find some time soon and submit a pull request.

**Comment by jordansissel** [comment]
Looks like #2390 fixed this. I tested Logstash 2.2.2 w/ generator input, and add_field supports `%{+YYYY}` etc.
