### ISSUE TITLE
Testing style: Refactoring tests to permit `it` and more focused tests

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2362]
Today, filter specs usually do something like this:

```ruby
describe "..." do
  config <<-CONFIG
  filter {
    some { filter => here }
  }
  CONFIG

  sample "some sample event" do
    expect(subject["field"]).to(eq("some value"))
  end
end
```

---

Problems with this:
1) `config` is not implemented in a way that is usable properly in rspec.
2) `sample` implies `it` and other oddities.

Doing this more closely aligning with rspec norms, using `let` and `subject` to setup our testing inputs and using `it` to test the behaviors.

Additionally, I would propose instead of using logstash config strings, we could just use the plugin objects themselves.

For example, instead of:
```ruby
  config <<-CONFIG
  filter {
    something { foo => "bar" }
  }
  CONFIG
```

We would use

```ruby
  subject { LogStash::Filters::Something.new("foo" => "bar") }
```

We can add helpers to abstract event processing, such as having an `event` helper take an `input` value via `let` or similar trick:

```
# encoding: utf-8
require "logstash/devutils/rspec/spec_helper"
require "logstash/event"
require "logstash/plugin"

describe "grok" do
  let(:plugin) { LogStash::Plugin.lookup("filter", "grok") }
  describe "with a single pattern" do
    subject { plugin.new("match" => { "message" => "hello %{WORD:fancy}" }) }
    let(:word) { "world" }
    let(:event) { LogStash::Event.new("message" => input) }
    before do
      subject.register
      subject.filter(event)
    end

    context "when successful" do
      let(:input) { "hello #{word}" }
      it "should create the 'fancy' field" do
        expect(event["fancy"]).to(eq(word))
      end
    end

    context "when failing to match" do
      let(:input) { "something else #{word}" }
      it "should not create the 'fancy' field" do
        expect(event["fancy"]).to(be_nil)
      end
    end
  end
end
```

Or something similar. It hopefully will make our tests easier to read/write/maintain.

**Comment by jordansissel** [comment]
Proposed helpers:
* `sample` - shorthand for let(:sample) { ... }
* `plugin(x, y)` - shorthand for let(:plugin) { LogStash::Plugin.lookup(x,y) }`

How about a `pipeline` helper that is perhaps short hand for: LogStash::Pipeline.new("some config text") ?

**Comment by jordansissel** [comment]
cc @colin, @pere, and @electrial who (I think?) have been working in the specs area lately.

**Comment by ph** [comment]
@electrical ^

**Comment by jordansissel** [comment]
@ph <3

**Comment by purbon** [comment]
Hi, my five cents here https://github.com/purbon/logstash/commits/feature/refactoring_rspecs_and_tests, this include a big rspec style refactor.

**Comment by purbon** [comment]
I looks mostly similar to yours @jordansissel as I could see.

**Comment by purbon** [comment]
Not sure if is the best example, but I do really like how files like https://github.com/purbon/logstash/blob/e057bb99766dd542bacfa222ee08cf62187e707b/spec/util/accessors_spec.rb looks like, or files like https://github.com/purbon/logstash/blob/e057bb99766dd542bacfa222ee08cf62187e707b/spec/core/conditionals_spec.rb (just think there are no fixtures going around)

What do you think?

- purbon

**Comment by jordansissel** [comment]
I'm not sure hwo I feel about fixtures this way, but maybe this will work well.

Assigned to @purbon to lead the charge :)

**Comment by purbon** [comment]
@jordansissel I started with the fixtures, but then @jsvd make very good points on changing that so I was more on the way of using some Factories, lets see where do we get with that.

My point was that we should somehow be happy with the test and make sure they are very easy to follow and update.

**Comment by purbon** [comment]
@jordansissel we should all have an open discussion how do we want this to happen. I will open an example PR tomorrow morning, so we might discuss over there.

**Comment by purbon** [comment]
You guys can check https://github.com/elasticsearch/logstash/pull/2380 and comment about the style, let me know if there are parts that will make everything great!

**Comment by untergeek** [comment]
We now have this functionality, as `let` and `subject` are available.  We've been refactoring tests to use this style as we've come across them.
