### ISSUE TITLE
Can not custom "path" in message.

### ISSUE THREAD

**Issue by zhenghu** [elastic/logstash#2366]
It seems logstash-1.4.2 can not custom the "path" fields. 
When I put "path":"customPath" in Input, the output is always the real path of the input file. 
What is the purpose?

**Comment by wiibaa** [comment]
@zhenghu the file input is overriding the path after "decorating" the event, so you cannot do it in the input itself. But you could definitely modify any part of the event using a mutate filter.

@jordansissel need a consistent design decision across inputs **when to decorate**, even maybe a common method `sendEventToFilterWorker` in inputs/base.rb to encapsulate and ensure the behaviour
`````
decorate(event)
queue << event
````

**Comment by zhenghu** [comment]
@wiibaa thanks for your response.
I am working on the IT for my filters of logstash. 
Since there are lots of match => [ "path", "regex" ] in my filter, so that is not suitable for adding a mutate filter to test the other filter.

**Comment by wiibaa** [comment]
Maybe I didn't catch your problem correctly 
What I supposed is that you try to **override in the input** the `path` value with the add_field for your event, but this does not prevent the input to also **add the real path** ? Am I right?
so doing something like that could be correct
````
input {
  file {
    type => "specific_type"
    path => [...]
    add_field {custom_path => "customPath"}
}
filter {
  if [custom_path] {
    mutate {
      replace => ["path", "%{custom_path}]
  }
[...] 
````
The main point is that path a no special meaning, just a common name convention, 
once the event is issued by the input, if you do not care about the "path" field, you can modify/remove it to your heart content in the filters

**Comment by zhenghu** [comment]
Actually I wanna test my filter like this : 

    filter {
      if [type] == "specific_type" {
	      if [path] =~ /regex/ {
		    mutate {
		          add_field => {"application" => "APP"}
	           }
             }
    [...]

To do this, i create a test conf below and try to verify is there a field "application":"APP" in output. 

    input {
          file {
            type => "specific_type"
            path => "/path/to/test/test.txt"
            add_tags => "test"
          }
    }

    filter {
      if [type] == "specific_type" {
	      if [path] =~ /regex/ {
		    mutate {
		          add_field => {"application" => "APP"}
	           }
             }
    }
    output {
        path => "/path/to/test/output.txt"
        tags => [ "test" ]
    }
And the content of test.txt is {"path":"regex"}.

This works well withe logstash-1.1.13(for this, I override with "@source_path":"regex"). 
But with logstash-1.4.2, the output is always "path":"/path/to/test/test.txt". The path can not be overried by "regex".

**Comment by wiibaa** [comment]
Cristal clear now! 
I would recommend trying to use rspec to test your filter but I cannot describe now in details how to do it. I will try to do it over the weekend.
If modifying very slightly the source code is an acceptable workaround for the moment you should add `if !event.include?("path")` in lib/logstash/inputs/file.rb on [this line ](https://github.com/logstash-plugins/logstash-input-file/blob/master/lib/logstash/inputs/file.rb#L138)

**Comment by zhenghu** [comment]
@wiibaa thanks a lot.
I do not use repec because I do not get how to use the custom pattern file for test.
There is an exmple : 
    
    require "test_utils"

    describe "linkylog logs" do
      extend LogStash::RSpec

      config <<-CONFIG
      filter {
       if [type] == "mersi-tech" {
            grok {
	    	patterns_dir => "C:\dev\workspaces\sup\sup-log-test\target\logstash-grok-pattern-test\logstash-files\patterns\custom-pattern"
                match => [ "message","%{MERSI_TECH}" ]
                add_field => { "application" => "cft-mersi" }
                add_field => { "level" => "DEBUG" }
        }
        date {
            match => [ "date", "yy/MM/dd HH:mm:ss" ]
        }
    }
    
      }
      CONFIG

      sample({'message' => ' 14/11/03 00:00:00  CFTR12I SWITCH LOG  Treated from command cache 00:00:00.00',
              'path' => 'path',
              'type' => 'mersi-tech',
          }) do

         insist { subject["application"] } == [ "cft-mersi" ]
         reject { subject["@timestamp"] } == "2013-10-08T06:46:47Z"
      end
    end

And I put this in test.rb, but when I run bin/logstash rspec test.rb, there is exception below : 

    Using Accessor#strict_set for specs
    Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :elasticsearch=>true,  :broken=>true, :export_cypher=>true}

    Failures:

      1) linkylog logs "{"message":" 14/11/03 00:00:00  CFTR12I SWITCH LOG ..." when processed
     Failure/Error: pipeline.instance_eval { @filters.each(&:register) }
         Grok::PatternError:
           pattern %{MERSI_TECH} not defined
         # C:/dev/workspaces/sup/sup-log-test/logstash/lib/logstash/filters/grok.rb:268:in `register'
         # C:/dev/workspaces/sup/sup-log-test/logstash/lib/logstash/filters/grok.rb:266:in `register'
         # C:/dev/workspaces/sup/sup-log-test/logstash/lib/logstash/filters/grok.rb:256:in `register'
         # C:/dev/workspaces/sup/sup-log-test/logstash/spec/test_utils.rb:89:in `results'
         # C:/dev/workspaces/sup/sup-log-test/logstash/spec/test_utils.rb:89:in `results'
         # C:/dev/workspaces/sup/sup-log-test/logstash/spec/test_utils.rb:107:in `subject'
         # C:\dev\workspaces\sup\sup-log-test\logstash\lib\logstash\runner.rb:58:in `run'
         # C:\dev\workspaces\sup\sup-log-test\logstash\lib\logstash\runner.rb:136:in `run'
         # C:\dev\workspaces\sup\sup-log-test\logstash\lib\logstash\runner.rb:175:in `run'
         # C:\dev\workspaces\sup\sup-log-test\logstash\lib\logstash\runner.rb:92:in `main'
         # C:\dev\workspaces\sup\sup-log-test\logstash\lib\logstash\runner.rb:215:in `(root)'

    Finished in 0.24 seconds
    1 example, 1 failure

I can not figure out why logstash rspec do not find the my custom pattern. So I do not use rspec to test my filter.

**Comment by wiibaa** [comment]
@zhenghu I suspect you have an issue with the backslashes and the multiline HEREDOC , either using slashes or replacing multiline string delimiters `<<-CONFIG` by `%q{` should solve this.

However it would be event better to read your actual config file, please have a look to this gist and tell me if it is usable in your case https://gist.github.com/wiibaa/80251d5ae56872f7803e

**Comment by zhenghu** [comment]
@wiibaa It works! Thanks very much.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/36. Let's continue the discussion there! :)
