### ISSUE TITLE
auto_delete settings for RabbitMQ queue used by elasticsearch river

### ISSUE THREAD

**Issue by nabheet** [elastic/logstash#2370]
How do I set the queue created by the elasticsearch river logtash output to be auto-deleted when the last consumer disconnects?

I don't see anything at http://logstash.net/docs/1.4.2/outputs/elasticsearch_river.

**Comment by jordansissel** [comment]
The `elasticsearch_river` plugin has been abandoned in favor of the `elasticsearch` output because Elasticsearch itself is removing the rivers feature.
