### ISSUE TITLE
unable to disable logstash-web component

### ISSUE THREAD

**Issue by zabbal** [elastic/logstash#2377]
It's completely unclear how to disable old kibana version bundled with logstash under the name of logstash-web. It seems to be interfering with the new kibana I'm using.

What exactly starts "/opt/logstash/lib/logstash/runner.rb web" and how to kill it once and for all?
Is there any chance to avoid installing it as a bundle in a 1st place?

**Comment by jordansissel** [comment]
logstash-web is gone in Logstash 1.5.0

For reference, if you installed logstash 1.4.x with the deb file and see logstash web running, you should be able to stop it with `service logstash-web stop` - assuming you aren't going to upgrade yet.

**Comment by jordansissel** [comment]
Closing since logstash-web is gone in 1.5.0
