### ISSUE TITLE
Packaging as single jar to run in AWS elastic beanstalk

### ISSUE THREAD

**Issue by marcboscher** [elastic/logstash#2382]
I have cases where we run logstash in a VM completely independent of any inputs and outputs. For example, using an S3 input and an elasticsearch output. In these cases we care very little about the local machine and file system. So deploying, configuring and monitoring a full VM just to run logstash is a pain. I would just prefer to run a jar in AWS Elastic Beanstalk.

This would require packaging logstash and any custom plugins in an executable jar (or jar in jar).

**Comment by p14n** [comment]
I'd find this useful.  Presumably the old Makefile in 1.3 did this (the flatjar).  Have there been any significant changes that would prevent this working again?

**Comment by jordansissel** [comment]
@p14n yes. The new plugin ecosystem currently assumes it has write access to the directory in which Logstash is deployed. Putting Logstash in a jar would probably block this.

While it's possible to achieve this, I don't anticipate much work from my side to achieve this. I don't know anything about AWS Beanstalk, so I can't offer much advice there.

**Comment by jordansissel** [comment]
AWS Elastic Beanstalk says this about itself:

> AWS Elastic Beanstalk is an easy-to-use service for deploying and scaling web applications and services developed with Java, .NET, PHP, Node.js, Python, Ruby, Go, and Docker on familiar servers such as Apache, Nginx, Passenger, and IIS.

I don't see a requirement for a jar as a deployment mechanism. Why do you require a jar?

**Comment by p14n** [comment]
We deploy zips of jars for our entire application, and have an automated process for doing this.  Nothing needs any special setup, it's just unpack and run the bootstrap  Deploying logstash for shipping works in sympathy if deployed as a jar - deploying as a tar needs more setup to hook into this process.

Having spent a bit more time looking at this I think our needs will be better met by not using logstash as a shipper, but rather using something else to send the logs over the network to logstash.  ZeroMQ (JeroMQ) seems like a good fit as we can write a logging appender that uses ZeroMQ and ZeroMQ can act as our buffer on the server (where many people use Redis).

Cheers

**Comment by jsvd** [comment]
I don't see this happening in the near future due to reasons mentioned above. Closing this. If there are motivations for packaging logstash in a jar please reopen the issue
