### ISSUE TITLE
logstash - gelf - input

### ISSUE THREAD

**Issue by karthiklml** [elastic/logstash#2387]
Hi, 

I am enabling the GELF input in the logstash and pushing some json code for testing . 
Testing scenario is json test input => logstash-shipper => logstash => ES => UI . i am getting the following error .  logstash version is 1.4.2

:message=>"Gelfd failed to parse a message skipping", :exception=>#<Gelfd::UnknownHeaderError: Could not find parser for header: [123, 34]>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/parser.rb:14:in `parse'", "/opt/logstash/lib/logstash/inputs/gelf.rb:83:in `udp_listener'", "/opt/logstash/lib/logstash/inputs/gelf.rb:60:in `run'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn}

Please suggest me what is the root cause of it . and how to fix it . 

Thanks

**Comment by karthiklml** [comment]
Hi, 

Any updates ..

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-gelf/issues/11. Let's continue the discussion there! :)
