### ISSUE TITLE
support ssl client certificate

### ISSUE THREAD

**Issue by runningman84** [elastic/logstash#2394]
I would like to auth with RabbitMQ using a ssl client key. This is the same concept as sensu is doing:
http://sensuapp.org/docs/0.16/certificates

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/27. Let's continue the discussion there! :)
