### ISSUE TITLE
Logstash => MQ => Logstash-index-server => ES => kibana

### ISSUE THREAD

**Issue by karthiklml** [elastic/logstash#2395]
Hi, 

I am using logstash 1.4.2 on centos 6.5

My input format is gelf 

input {
gelf {
host => "127.0.0.1"
port => 12201
type => "gelf"
}
}

filter {
}

output {
MQ details

}

It has to pass the data to MQ . But the error indicate it couldn't parse the data from the json input . And the data not going to MQ servers. It get dropped with the below error. 

:message=>"Gelfd failed to parse a message skipping", :exception=>#, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/parser.rb:14:in parse'", "/opt/logstash/lib/logstash/inputs/gelf.rb:83:inudp_listener'", "/opt/logstash/lib/logstash/inputs/gelf.rb:60:in run'", "/opt/logstash/lib/logstash/pipeline.rb:163:ininputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn}

Test input data is ,

echo '{"version": "1.1","host":"example.org","short_message":" what is going on","full_message":"Hello ","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}' | nc -w 1 -u localhost 12201

Am not sure what is the wrong in this . could you please guide me to fix this issue .

Thanks .

**Comment by jsvd** [comment]
Hi! Thanks for reporting, we're going to investigate.

Is this a different situation than the one you reported yesterday in https://github.com/elasticsearch/logstash/issues/2387?

**Comment by karthiklml** [comment]
Hi, 

Yes both are same scenario .

**Comment by karthiklml** [comment]
Hi,

Could you please update me the status.

Thanks

**Comment by karthiklml** [comment]
Could you please confirm is it bug? or my mistake. Please guide me.

Thanks

**Comment by karthiklml** [comment]
Hi, 

Any update.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-gelf/issues/11. Let's continue the discussion there! :)
