### ISSUE TITLE
`rake bootstrap` on windows says it can't find Java. Neat.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2401]
```
C:\Users\jls\Documents\GitHub\logstash [master +2 ~1 -0 !]> rake bootstrap
Cannot find Java 1.5 or higher.
C:\Users\jls\Documents\GitHub\logstash [master +2 ~1 -0 !]> java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by wiibaa** [comment]
Having java in the PATH does not mean you have JAVA_HOME set correctly ? `echo %JAVA_HOME%` ?

**Comment by jordansissel** [comment]
@wiibaa JAVA_HOME is not set by the Oracle JDK 8 installer, for whatever reason.

Setting it manually is easy if you know how, but I'm hoping to avoid requiring that pointless ceremony. I'll see if there's a way we can automatically detect it.

**Comment by wiibaa** [comment]
Got it reproduced, It seems that bin/jruby.exe is doing lookup only for 32 bits JDK into `C:\Program Files (x86)\Java` but not for 64-bits in `C:\Program Files\Java`

**Comment by jordansissel** [comment]
@wiibaa how'd you check that? windows debugger to trace the file calls?

**Comment by wiibaa** [comment]
nope manual testing, 
````
set JAVA_HOME=
set PATH=C:\Windows\system32
bin\jruby.exe -v
````
jruby pointed to my 32-bits JDK 1.7, renaming the folder to dummy-jdk, then he found my 32-bits 1.8 jdk, renaming the folder to dummy-jdk-1.8 and then **Cannot find Java 1.5 or higher.**

**Comment by wiibaa** [comment]
I think the status from jruby side is still blurry https://jira.codehaus.org/browse/JRUBY-6696

**Comment by wiibaa** [comment]
Just found out `bin\jruby -Xtrace trace.log -v` 
and https://github.com/jruby/jruby-launcher/blob/master/jvmlauncher.cpp
Crazy...but necessary

**Comment by suyograo** [comment]
+1 I had to manually set `%JAVA_HOME%`

**Comment by suyograo** [comment]
@jordansissel moving to 1.5.0

**Comment by jordansissel** [comment]
+1. For rc1, folks will have to set JAVA_HOME in the environment.
