### ISSUE TITLE
input file is json format  output to elasticsearch data is not json key value format

### ISSUE THREAD

**Issue by baozhaxiaoyuanxiao** [elastic/logstash#2405]
hello, everyone!
when i use logstash+elasticseach+kibaba, I have a problem.

1. my log format is json like this:
    {"logintime":"2015-01-14-18:48:57","logouttime:"2015-01-14-18:50:48"}

2. my logstash config file content is 
  input {
   file {
	type => "syslog"
	path => ["/var/log/mylog/*.*","/var/log/messages"]
	exclude => ["*.gz"]
  }
 }
output {
  stdout { }
  elasticsearch {
    cluster => "logstash"
}
}

3. the problem is 
   stdout is  2015-01-23T07:44:36.343+0000 ubuntu {"logintime":"2015-01-14-18:48:57","logouttime:"2015-01-14-18:50:48"}

 the kibana message is blew
 Field	Action	Value
......
host		ubuntu
message		{"logintime":"2014-12-22-11:07:59","logouttime:"2014-12-22-11:26:24"}
type		syslog

 but i want kibaba display like is 
 Field	Action	Value
......
host		ubuntu
logintime    2014-12-22-11:07:59
logouttime   2014-12-22-11:26:24
type		syslog

can anybody tell me how to write logstash config file, thank you very much.

**Comment by wiibaa** [comment]
You need to add codec definition in your input otherwise it will read raw lines.
Something like `codec => json`

**Comment by baozhaxiaoyuanxiao** [comment]
thank you @wiibaa 
I am changed config file but the also some problem

1.config file 
input {
  file {
        codec =>"json"
	path => "/home/way/log/log/test/*"
 }
}

filter{
    json{
        source => "message"
    }
}

output{
    stdout{
	codec => "rubydebug"
    }
}

2. log file 
way@ubuntu:~/log/log/test$ cat test-accoff-error.log 
{"ontime":"2014-12-22-11:07:59","offtime:"2014-12-22-11:26:24","offreason":"ACC-OFF"}
way@ubuntu:~/log/log/test$ cat test-dropoff.log 
{"ontime":"2014-12-26-14:47:54","offtime":"2014-12-26-18:52:31","offreason":"DROP-OFF"}
way@ubuntu:~/log/log/test$ 


3.logstash output

way@ubuntu:~/software/logstash-1.4.2$ bin/logstash -f jsontest.conf 
Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Using milestone 2 filter plugin 'json'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Trouble parsing json {:source=>"message", :raw=>"{\"ontime\":\"2014-12-22-11:07:59\",\"offtime:\"2014-12-22-11:26:24\",\"offreason\":\"ACC-OFF\"}", :exception=>#<JSON::ParserError: unexpected token at '{"ontime":"2014-12-22-11:07:59","offtime:"2014-12-22-11:26:24","offreason":"ACC-OFF"}'>, :level=>:warn}
{
        "ontime" => "2014-12-26-14:47:54",
       "offtime" => "2014-12-26-18:52:31",
     "offreason" => "DROP-OFF",
      "@version" => "1",
    "@timestamp" => "2015-01-26T10:13:56.711Z",
          "host" => "ubuntu",
          "path" => "/home/way/log/log/test/test-dropoff.log"
}
{
       "message" => "{\"ontime\":\"2014-12-22-11:07:59\",\"offtime:\"2014-12-22-11:26:24\",\"offreason\":\"ACC-OFF\"}",
      "@version" => "1",
    "@timestamp" => "2015-01-26T10:13:56.799Z",
          "host" => "ubuntu",
          "path" => "/home/way/log/log/test/test-accoff-error.log",
          "tags" => [
        [0] "_jsonparsefailure"
    ]
}

why one file can not parse to json format ? 
is my config error can anybody tell me thanks very much

**Comment by wiibaa** [comment]
You must be clear that if you use the json codec, you do not have to use the json filter anymore.

From the failing event you posted, there is a missing `\"` after offtime so it is not valid json
2- the second event still contains the **message** field, it means you did not use the json codec

**Comment by baozhaxiaoyuanxiao** [comment]
thank you @wiibaa

**Comment by jordansissel** [comment]
Sounds like this was resolved. If you have further questions or need help, I invite you to check out our new support and discussion forum, https://discuss.elastic.co/

**Comment by abhishekkumarsingh1** [comment]
Hey is there any way that even by using json codec, I can preserve raw message to display in kibana.
