### ISSUE TITLE
Query on stout type setting elasticsearch

### ISSUE THREAD

**Issue by wingZero21** [elastic/logstash#2407]
Hi,

This is a query about setting the output type.

Currently checking the docs its saying that the type variable is being deprecated, however if I want to enforce the type of data that is getting outputted how else can you do this to ensure it does not break in new versions of logstash.

Eg:
Details: - http://logstash.net/docs/1.4.2/outputs/elasticsearch
```
type DEPRECATED
DEPRECATED WARNING: This config item is deprecated. It may be removed in a further version.
Value type is string
Default value is ""
The type to act on. If a type is given, then this output will only act on messages with the same type. See any input plugin’s “type” attribute for more. Optional.
```

```
output {

stdout { }
        elasticsearch {
                cluster => "cluster"
                protocol => "http"
                port => "9200"
                host => "host"
                type => "syslog"
        }
}
```

**Comment by wiibaa** [comment]
type will still be available in 1.5.0 release but you can already have a look to using conditionals in the outputs block http://www.elasticsearch.org/guide/en/logstash/current/configuration.html#conditionals

**Comment by wingZero21** [comment]
Hi,

Do you mean doing something like this?

```
output {
if syslog == "true"  {

stdout { }
        elasticsearch {
                cluster => "cluster"
                protocol => "http"
                port => "9200"
                host => "host"
                type => "syslog"
        }
   }

}
```

**Comment by wiibaa** [comment]
converting your outputs config to conditionals would look more like 
````
output {
  #write everything to stdout
  stdout{}
  #send syslog events to ES
  if [type] == "syslog" {
    elasticsearch {...}
  }
````

**Comment by wingZero21** [comment]
Hi,

That is fine but it also suggests that the type field on stdout is going to be deprecated as well.

http://logstash.net/docs/1.4.2/outputs/stdout

```
type DEPRECATED
DEPRECATED WARNING: This config item is deprecated. It may be removed in a further version.
Value type is string
Default value is ""
The type to act on. If a type is given, then this output will only act on messages with the same type. See any input plugin’s “type” attribute for more. Optional.
```

**Comment by wiibaa** [comment]
It is because conditionals is the preferred solution for event flow control in filters and outputs,
so anything like
````
outputs {
  stdout { type=> "my type"}
}
````
should be replaced by 
````
outputs {
  if [type] == "my type" {
    stdout{}
  }
}

**Comment by jordansissel** [comment]
> it also suggests that the type field on stdout is going to be deprecated as well

The `type` field isn't deprecated. By field, I mean a property of an event named "type". The `type` setting on outputs has been deprecated in favor of using conditionals.

These are equivalent:

```
# Old way, deprecated in favor of conditionals.
output {
  elasticsearch {
    type => "example"
    ...
  }
}

# With conditionals
```
output {
  if [type] == "example" {
    elasticsearch {
      ...
    }
  }
}
```

If you have further questions, I invite you to check out our new support and discussion forum, https://discuss.elastic.co/ :)
