### ISSUE TITLE
Memory leak when utilizing ruby{} block in a filter, any suggestions to fix?

### ISSUE THREAD

**Issue by PeterGrace** [elastic/logstash#2413]
Hi there,

utilizing the filter block, below, I have a reproducible memory leak in my configuration.  This only started yesterday when I changed my assignments to ||= to remove a repetitive warning that a constant was already defined.  Can anyone shed some light on why this code might be causing a memory leak?

    filter {
            ruby {
                code => "
                    require 'socket'
                    CollectorName ||= Socket::gethostname
                    FieldName ||= 'collector'
                    event[FieldName] = CollectorName
                    "
            }
    }

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-ruby/issues/8. Let's continue the discussion there! :)
