### ISSUE TITLE
Redis/RabbitMQ output/input with multiple hosts for "silent" fail over

### ISSUE THREAD

**Issue by MarxDimitri** [elastic/logstash#2414]
Given a cluster of RabbitMQ/Redis nodes, it would be desirable that LS silently fail over in case a RabbitMQ/Redis node, pointed by LS, dies. This should be true for input and output.

**Comment by rlanore** [comment]
+1

**Comment by colinsurprenant** [comment]
Could you clarify your notion of cluster for both Redis and RabbitMQ? Do you mean actual clusters per Redis or RabbitMQ definition of a cluster? If so, is failing over a list of hosts in these clusters allowed for both pushing and polling? Does the cluster semantic of both message brokers compatible with this idea?

**Comment by jdblack** [comment]
In our case, we have a cluster of rabbitmq servers. However, I believe we're only allowed to specify one of the servers with the rabbitmq input plugin.

**Comment by stefan79** [comment]
Hi,
yeah we are talking about "native" RabbitMQ and Redis clusters, i.e. the nodes guarantee message delivery even if a node fails. But if logstash only knows one machine from the cluster and this specific one goes down, the messages will no longer be delivered.

Does this answer the question properly?

Regards

Stefan

**Comment by memelet** [comment]
An alternative, if you already use or are willing to add consul to your stack, is described here http://doics.co/2015/05/18/increto ase-your-elk-herd-with-consul-io/.

**Comment by joerocklin** [comment]
@memelet can you fix your link? It seems to have gotten some extra characters tossed in.

**Comment by untergeek** [comment]
If this feature is desired, it should be reported as an issue to https://github.com/logstash-plugins/logstash-output-rabbitmq or https://github.com/logstash-plugins/logstash-output-redis (or the associated input plugins).  Closing this ticket in the core Logstash repository.
