### ISSUE TITLE
Document JRuby OOM behavior and how to address

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#2415]
From #1496 

> When LS runs out of memory, it writes out the following message:
>```
"Error: Your application used more memory than the safety cap of 500M.            
Specify -J-Xmx####m to increase it (#### = cap size in MB).                      
Specify -w for full OutOfMemoryError stack trace""
>```
> This can be confusing to the end user given that -w is the flag for specifying worker threads in LS.

This behavior should be documented in some form of "Troubleshooting Logstash" page, along with steps which can be taken to address the situation.

**Comment by rtoma** [comment]
What would you write on this Troubleshooting Logstash page?


Got bitten by this one:
```
Error: Your application used more memory than the safety cap of 1024M.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace
```

Most likely cause: our event stream occasionally contains some huge json objects.

**Comment by purbon** [comment]
Having a Troubleshooting is a good idea! :+1:

**Comment by suyograo** [comment]
Closing this, we can only say its running out of memory, but not why.

**Comment by suyograo** [comment]
The APIs should help here
