### ISSUE TITLE
Give plugins a place to write local state

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2418]
file input has `sincedb_path`. Some S3 input has a similar, but different setting. Other plugins need state. The new Persistent QUeues feature will require somewhere to write.

We should make a setting for the pipeline that provides a place to store state for use by persistent queue, file input, and all other things needing to write local state.

Related: https://github.com/elasticsearch/logstash/issues/1535

**Comment by wiibaa** [comment]
Also related to #1980

**Comment by suyograo** [comment]
Closing this in favor of #1535

**Comment by phutchins** [comment]
Looks like a circular reference between a few of these issues. Is there one that is still discussing this, or has it been resolved?
