### ISSUE TITLE
[Terraxia] Message not fully read (request)

### ISSUE THREAD

**Issue by versnel** [elastic/logstash#2421]
Hallo there,

I'm getting the following Error msg in my log file.
Can someone help me to solve this.
Thank you

Extra info:
Elasticsearch: 1.4.2
Logstash: 1.4.2-1
Kibana: 3.1.2

log4j, [2015-01-25T17:11:43.739]  WARN: org.elasticsearch.transport.netty: [Terraxia] Message not fully read (request) for [871] and action [indices:admin/get], resetting

**Comment by jordansissel** [comment]
Is this still an issue? It might be a bug or a misconfiguration, it's hard to tell. You might find wider support for this on https://discuss.elastic.co/ (our discussion/support forum). 

Let me know if you have any other concerns, and I'll do my best to help direct you :)
