### ISSUE TITLE
Should deprecate pluginpath command line flag

### ISSUE THREAD

**Issue by wiibaa** [elastic/logstash#2423]
With the new plugin ecosystem, shouldn't the pluginpath flag be deprecated for 1.5 in favor of packaging plugins as gems ? or is it too early ?

**Comment by rtoma** [comment]
I do not understand the reasons for removing this feature.

Before I could write a .rb file, put in the correct directory structure, start up a logstash instance, point it the path and my plugin was active.

Now I need to make a gem of it and put it in my logstash installation, making it visible for all logstash instances. 

So for me this deprecation makes local development AND isolation a pain.

**Comment by TinLe** [comment]
This should not be closed.   Seriously, removing --pluginpath causes lots of problems for us as we have internally written plugins that for one reason or another we can not shared, but need to keep using.

**Comment by jordansissel** [comment]
> we have internally written plugins that for one reason or another we can not shared

There is no requirement that you share your plugins. You can have private plugins that only you use and that you do not publish to rubygems.org.

**Comment by colinsurprenant** [comment]
fyi, per #3580 we will re-introduce the --pluginpath option!

**Comment by colinsurprenant** [comment]
closing this, `--pluginpath` has been restored in #3587 and will be available in 1.5.3
