### ISSUE TITLE
Filter and output threads arent named correctly

### ISSUE THREAD

**Issue by ph** [elastic/logstash#2425]
Naming thread will help us debug problematic plugins.

```
4210 cashmol  20  0  9.804g 1.017g  15816 S 34.2 13.3  0:51.41 |worker 
4209 cashmol  20  0  9.804g 1.017g  15816 S 32.2 13.3  0:50.56 |worker 
4211 cashmol  20  0  9.804g 1.017g  15816 R 31.6 13.3  0:49.91 |worker 
4212 cashmol  20  0  9.804g 1.017g  15816 S 30.9 13.3  0:49.18 |worker

i know they are filters.. but nobody knows which one

or   4247 cashmol  20  0  9.804g 1.017g  15816 S  3.3 13.3  0:06.46 >output 
4318 cashmol  20  0  9.804g 1.017g  15816 S  3.3 13.3  0:05.38 >output 
4264 cashmol  20  0  9.804g 1.017g  15816 S  2.7 13.3  0:01.67 >output
```

https://github.com/elasticsearch/logstash/blob/master/lib/logstash/pipeline.rb#L196

**Comment by ph** [comment]
cc @electrical

**Comment by purbon** [comment]
Agreed, this should be fix, it will simplify the debugging.

**Comment by ph** [comment]
After discussing with @talevy this isn't an easy fix to do for 1.5, we need to refactor the pipeline to do it in a clean way. Because one output thread  consist of multiple plugins and some plugins can run in their own thread if `workers > 1`

But we both agreed that we need to give more visibility to user about what logstash is doing.

**Comment by ph** [comment]
@jsvd this ticket should be included in the pipeline discussion.

**Comment by jsvd** [comment]
noted :+1:

**Comment by untergeek** [comment]
This is moot now with the next generation pipeline, where filters and outputs are merged.
