### ISSUE TITLE
Provide common code for zeromq filter and output

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2434]
logstash-filter-zeromq and logstash-output-zeromq are using [utils/zeromq.rb](https://github.com/logstash-plugins/logstash-filter-zeromq/blob/master/lib/logstash/util/zeromq.rb) file which was duplicated during beta1 as part of https://github.com/elasticsearch/logstash/issues/2055. Previously, before the plugin separation, they shared the same file. We know have to DRY this up to a new plugin like https://github.com/logstash-plugins/logstash-mixin-aws which has common utils code for EC2 input and output.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-zeromq/issues/5. Let's continue the discussion there! :)
