### ISSUE TITLE
Logstash and redis

### ISSUE THREAD

**Issue by n1njai** [elastic/logstash#2436]
Hi,
I am trying to use logstash 1.4.2 with redis, I wrote application on Java, which writes logs to Redis, and then logstash read them and wrote to file. I wrote 5000 logs to Redis, but when I am doing:
```
cat logstash_output | wc -l
```
I didn't see all logs. I checked it twice and saw 4992 and 4995 logs. It seems that some logs was lost.  
My logstash config is:
``` ruby
input {
    redis {
        codec => json
        host => "192.26.10.11"
        port => 6379
        key => "logstash"
       data_type => "list"
    }
}
output {
   file {
      path => "/tmp/logstash_output"
   }
}
```

**Comment by longshiptech** [comment]
Are you able to run logstash in debug mode to confirm all the messages are being received at the input?

**Comment by n1njai** [comment]
Hi, 
today I tested with debug mode, and on input logstash has 5000 logs, but on output only 4998, two logs was lost.

**Comment by jordansissel** [comment]
Are you able to verify _what_ logs were lost?

I don't think the file output flushes on each write, which may be the cause of your problem. I'll move this to the file output repo.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-file/issues/11. Let's continue the discussion there! :)
