### ISSUE TITLE
Configcheck accepts incorrect syntax for date filter

### ISSUE THREAD

**Issue by thomasmarkus** [elastic/logstash#2437]
`bin/logstash -t -e 'filter { date { match => [ "field" => "YYYYmmdd"] } }'` == true negative 
`bin/logstash -t -e 'filter { date { match => [ "field", "YYYYmmdd"] } }' `  == true positive 
`bin/logstash -t -e 'filter { date { match => { "field" => "YYYYmmdd"} } }' ` == false positive

I suggest extending the configtest with support for the third case.

**Comment by purbon** [comment]
Nowadays the config test is nowaday only checking for syntax and not content of it. I'll #3301 in benefit of where we can discuss the right solution for this kind of error. I will add a comment there regarding this specific issue.
