### ISSUE TITLE
Logstash Ganglia gmond support

### ISSUE THREAD

**Issue by wadudmiah** [elastic/logstash#2438]
I would like to feed in Ganglia gmond metric data into logstash so the direction of data flow is gmond -> logstash and not logstash -> gmond. I can't find any documentation on how to do this, so any help will be greatly appreciated. 

Thanks in advance,
Wadud.

**Comment by jordansissel** [comment]
Sorry for the delays in responding. Logstash has a ganglia input (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-ganglia.html) which supports gmond's protocol, I think. 

If you have further questions or need help on this, I invite you to ask about it on https://discuss.elastic.co/ :)
