### ISSUE TITLE
Add in GEO for tweets?

### ISSUE THREAD

**Issue by brizzbane** [elastic/logstash#2448]
Is this something that twitter supports, and could be added to the plugin?  i.e. only insert tweets that are from 'US'

**Comment by jordansissel** [comment]
The [twitter input](https://github.com/logstash-plugins/logstash-input-twitter) now has a `full_tweet` setting that gets you the entire tweet object including location information if that is available.

In my experience, less than 0.1% of tweets (as observed via the filtered sampling stream) contain location details.
