### ISSUE TITLE
KV filter splitting on a field_split value within data

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#2458]
If I have a KV document similar to this;
```csv
"sentence": "the quick brown fox, jumped over the duck", "author": "Mark Walkom"
```

And a LS config like;
```
input {
  stdin {}
}

filter {
  kv {
    trim => "\""
    trimkey => "\"\ \(\)"
    field_split => ","
    value_split => ":"
    }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

The `sentence` field is split at the first comma which ends up dividing the string value and the loss of the data in the output;
```bash
$ echo ""sentence": "the quick brown fox, jumped over the duck", "author": "Mark Walkom""|bin/logstash agent -f kvbug.conf
Using milestone 2 filter plugin 'kv'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
{
       "message" => "sentence: the quick brown fox, jumped over the duck, author: Mark Walkom",
      "@version" => "1",
    "@timestamp" => "2015-01-28T02:47:22.726Z",
          "host" => "bender.local",
      "sentence" => " the quick brown fox",
        "author" => " Mark Walkom"
}
```

Ideally it shouldn't do this and my `sentence` field would be complete.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-kv/issues/9. Let's continue the discussion there! :)

**Comment by kiranmai444** [comment]
I want to grok logs with repeated fields like

[2017-05-29 02:17:18] INFO – [ActivityServiceRest:89] – [{“callId”:”kjwefkjweqkfb”},{“callId”:”nwekgwnkqgkqr”},{“callId”:”ohjiwnwbnwbrk”}]

I want to capture all the callId's into a field called call_Id

where the number of times callId appears is dynamic. Can someone please help.
