### ISSUE TITLE
KV whitespace trim should only do beginning/end of value

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#2459]
If I have a dataset like this;
```csv
"sentence": "the quick brown fox, jumped over the duck", "author": "Mark Walkom"
```

And this Logstash config, which removes quotes and also trims whitespace;
```
input {
  stdin {}
}

filter {
  kv {
    trim => "\"\ "
    trimkey => "\"\ \(\)"
    field_split => ","
    value_split => ":"
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

The output I get is mashed together `sentence` and `author` values;
```shell
 echo ""sentence": "the quick brown fox jumped over the duck", "author": "Mark Walkom""|bin/logstash agent -f conf/kvbug.conf
Using milestone 2 filter plugin 'kv'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
{
       "message" => "sentence: the quick brown fox jumped over the duck, author: Mark Walkom",
      "@version" => "1",
    "@timestamp" => "2015-01-28T02:57:09.654Z",
          "host" => "bender.local",
      "sentence" => "thequickbrownfoxjumpedovertheduck",
        "author" => "MarkWalkom"
}
```

I realise that [the docs](http://logstash.net/docs/1.4.2/filters/kv#trim) explicitly say _"A string of characters to trim from the value"_ which implies it'll trim these chars from the entire string irrespective of location, but given `trim` in the other filters only does the start and beginning of a field, it'd be great if it did the same for the kv filter.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-kv/issues/10. Let's continue the discussion there! :)
