### ISSUE TITLE
Gelf output  with multiple hosts for "silent" fail over

### ISSUE THREAD

**Issue by rlanore** [elastic/logstash#2460]
Given a cluster of gelf nodes, it would be desirable that LS silently fail over in case a gelf node, pointed by LS, dies.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-gelf/issues/4. Let's continue the discussion there! :)
