### ISSUE TITLE
Logstash monitoring  tools

### ISSUE THREAD

**Issue by devarajc** [elastic/logstash#2462]
We setup the environment for logstash & elastic search for log analysis.My hardware environment is high end even though the performance of the logstash is slow. Now our goal is to find the following area where it takes much time   input,filter or output. So we decided to go with monitoring it. We have one option as of now is to go with Java thread dump analysis.Is this the only way or any other options available.

**Comment by suyograo** [comment]
@devarajc we are working on #2611. Closing in favor of that
