### ISSUE TITLE
Add windows testing to jenkins

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2467]
Currently Jenkins doesn't test Logstash on Windows. This needs to be changed.

**Comment by electrical** [comment]
No windows host available on EU jenkins master. will need to ping @mrsolo about this.

**Comment by mrsolo** [comment]
There is one window host but it is controlled by us-00.   So  attaching a window slave to eu-00 will be required.

**Comment by mrsolo** [comment]
window host up

**Comment by ph** [comment]
ty @mrsolo for providing this.

**Comment by gmoskovicz** [comment]
I am on this.

**Comment by suyograo** [comment]
Implemented
