### ISSUE TITLE
Document the use of @metadata feature

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2486]
We added `@metadata` syntax to the Event class which helps store arbitrary data while an event flows through the pipeline stages. This helps certain configs like in data filter to avoid creating intermediate fields. We should document the use of this functionality with examples configs (with and without metadata)

See https://github.com/elasticsearch/logstash/pull/1836

**Comment by suyograo** [comment]
this doc could be used to close https://github.com/elasticsearch/logstash/issues/1840

**Comment by suyograo** [comment]
@untergeek lets document this feature with a few examples in http://www.elastic.co/guide/en/logstash/current/configuration.html

**Comment by untergeek** [comment]
Will do!
