### ISSUE TITLE
Windows test results 

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2487]
@ph and I are working on fixing logstash bugs on Windows in the `wip/bundler-move` branch (Confusingly name, I know. It's a mix of work in there)

I had to disable some plugins because they were causing rspec to crash (not a test failure, rspec would raise exception and abort execution)
```
#gem 'logstash-input-file'
#gem 'logstash-input-generator'
#gem 'logstash-input-pipe'
#gem 'logstash-input-syslog'
#gem 'logstash-input-tcp'
#gem 'logstash-output-statsd'
```

The full test output is here: https://gist.github.com/jordansissel/622db419dc1b284794bd

I will file bugs on individual repos as a result, but this ticket tracks the study.

**Comment by jordansissel** [comment]
We can ignore any tests that failed because the generator input was missing: (output csv, etc), the error looks like this:

```
LogStash::PluginLoadingError:
       Couldn't find any input plugin named 'generator'.
```

**Comment by ph** [comment]
one more test failing in the S3 output look related to the generator input.

**Comment by jordansissel** [comment]
@ph can you link to the issue here?

**Comment by ph** [comment]
https://github.com/logstash-plugins/logstash-input-generator/issues/3

**Comment by jsvd** [comment]
I proposed a fix for encoding issues in #2507 
Since there are other vectors besides Socket.gethostname, neither monkey patching Socket or wrapping the call in Logstash::Util is enough.

**Comment by ph** [comment]
We will need to merge #2507 or find a better fix for windows and rerun the tests with the latest changes.

**Comment by ph** [comment]
Second run of test in https://gist.github.com/ph/1d83c833d89b7c1de9b4

**Comment by jsvd** [comment]
My latest results with the bundler-move branch:

Using the following as "rake test:plugins2": 

```ruby
task "plugins" do
  gem_root = File.expand_path('./vendor/bundle/jruby/1.9/')
  pattern = File.join(*"gems/logstash-*/spec/{input,filter,codec,output}s/*_spec.rb".split("/"))
  sh "#{LogStash::Environment::LOGSTASH_HOME}/bin/logstash rspec --format documentation --order rand #{gem_root} -P '#{pattern}'"
end
```

rake test:plugins => 30 failures
rake test:plugins2 => 11 failures

Results: https://gist.github.com/jsvd/f6ab54b5b4c8ed9537a8

**Comment by ph** [comment]
Closing this since all the related tickets were closed, will open a new one if needed.
