### ISSUE TITLE
What happened to all the issues raised in Jira (like LOGSTASH-2226 Collect weblogs in french)?

### ISSUE THREAD

**Issue by jmroth** [elastic/logstash#2488]
The OP had a problem concerning french characters in log files.
The issue has been confirmed but what was the outcome of it?
We have the same issue.
For now we have circumvented it by manually specifying in the input

    codec => plain {
       charset => "ISO-8859-1"
    }

The manual however states that specifying a charset is deprecated.
So how are we supposed to handle this in the future?

Thanks.

**Comment by wiibaa** [comment]
Indeed charset in input is deprecated 
http://www.elasticsearch.org/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-charset
because it has been moved to codec
http://www.elasticsearch.org/guide/en/logstash/current/plugins-codecs-plain.html#plugins-codecs-plain-charset
so your configuration is already correct.

**Comment by suyograo** [comment]
@jmroth thanks for raising this. We are in the process of migrating old JIRA issues to github. Currently we are doing this migration case by case. We have also started a weekly triage[1] where we go through old issues (in JIRA and github). We then migrate JIRA issues, and make sure we respond, or collect information on issues. Same goes for pull requests here. Rest assured, we will not be neglecting any old issues in JIRA.

[1] https://github.com/elasticsearch/logstash/issues/2357

**Comment by jordansissel** [comment]
I think the two questions in this ticket were answered (1: what is happening to the old jira tickets?, 2: what to do with the charset setting?). Marking closed.
