### ISSUE TITLE
Logstash 1.5 beta hanging, requires restarts, help debug?

### ISSUE THREAD

**Issue by johnwards** [elastic/logstash#2490]
Hello,

I've got an issue with my central logstash collector. It randomly hangs and stops picking up messages from Redis, nothing in the error log or any log, I'm at a loss as to how to debug.

Background...

So I've got a logstash 1.5 setup, ala the logstash book. The collectors are running on 5 servers, with no filters, just stuffing stuff to redis. Then I have a central server processing these logs. I have two types of logs, a standard log that I grok on to process and a XML based log.

I run various filters on these logs to sort them out into a structure, then I do two things. Of type one I save to a file, which rotates hourly using the date format in the filename inside the output filter, I also save to elasticsearch. The second type just gets saved to elasticsearch.

Right, that is the background.

So as I said, the central logstasher just hangs, stops writing to the file or sending data to elasticsearch, with no errors in the logs.

All I need to do to "fix" this, is to restart logstash. This seems to have no adverse affect to anything, and instantly fixes the problem.

At the moment, I've got a cron restarting logstash every 3 hours to stop Redis filling up when I'm sleeping. Even this 3 hour restart doesn't fully fix it, as sometimes in that 3 hour window logstash can hang.

Any tips to help me diagnose this?

**Comment by markwalkom** [comment]
You can turn on debug mode using -vv, but it'll likely be very verbose.

What OS, java version?

**Comment by johnwards** [comment]
Running Ubuntu 14.04 LTS and java 1.8.0_31.

About to try -vv, lets see how verbose....

**Comment by johnwards** [comment]
Ah -vv is a little too verbose. I've logged 1 gig of data in under 5 minutes, I'll run out of hard drive space at that rate. Any other tips?

**Comment by jglanz** [comment]
I've got the exact same issue going on - my inputs are log-courier and collectd - that said logstash flat out hangs - identical config to above.

debugging now - any insights would be great

**Comment by mikapp** [comment]
I am experiencing the same problems with Logstash 1.5.0-1 and it just hands without dropping any errors in logs. I am using working config from Logstash 1.4.2. Any tips how to find what is going on? Running log stash agent with -debug option doesn't show any data other that "reading configuration".

**Comment by jsvd** [comment]
This is very likely related to https://github.com/elastic/logstash/issues/3361, and a fix has been proposed in https://github.com/elastic/logstash/pull/3378
