### ISSUE TITLE
logstash use local time zone

### ISSUE THREAD

**Issue by techbobo** [elastic/logstash#2491]
I want to use local TZ in logstash. 
I change "@time = time.utc" to "@time = time" in logstash/lib/logstash/timestamp.rb 23 line.
Is it feasible?

**Comment by untergeek** [comment]
This is not recommended.  Elasticsearch expects time in UTC and Kibana translates from UTC back into your timezone based on your browser location.

Logstash should automatically use your local timezone for the date filter, but if you need to use a different timezone, please consider using the date filter:

```
date {
  match => [ "source_date", "...date_pattern..." ]
  timezone => "America/Los_Angeles"
}
```

**Comment by techbobo** [comment]
Thank you very much.
