### ISSUE TITLE
multiline logger server cause host field error.

### ISSUE THREAD

**Issue by Guinoutortue** [elastic/logstash#2492]
Actually I have two server (A & B) that send log to logstash (on server C). There is some multiline log so I created a codec multiline configuration.

```
input {
	syslog {
		port => 5000
		type => "type1"
		codec => multiline {
			charset => "ISO-8859-1" 
			pattern => "^%{TIMESTAMP_ISO8601}"
			negate => true
			what => "previous"
		}
	}
}
```

But I discover that some **logs from server A have a host field which server B adress**. This appends even with simple ligne log. I tried to use filter multiline too but that solve nothing.

I'm not sure if this is a bug or maybe I just do something wrong?

I use a **syslog appender (log4j libraries)** for sending log.
For now I will create a custom appender in purpose to append host to log (and parse it).

PS : if you need more information on my configuration to reproduce tell me :-)

**EDIT :** That seems that using filter multiline solve problem. I will come after few hour of work from my servers to add some news. But the problem persist with codec multiline!!!

**Comment by Guinoutortue** [comment]
I confirm that filter multiline works fine instead of codec multiline.

**Comment by wiibaa** [comment]
Seems similar to the issue reported for file input https://github.com/elasticsearch/logstash/issues/1754

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by untergeek** [comment]
This should no longer be an issue with recent changes to the multiline codec.  If issues persist, please open an issue at https://github.com/logstash-plugins/logstash-codec-multiline

Closing.
