### ISSUE TITLE
Try to address new-user expectations with multiple configuration files

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2493]
Several times a month, it seems, I see an upset Logstash newbie who is confused and frustrated at the way the `-f` flag behaves with respect to loading multiple config files.

Expectations I've seen by new users:
* Expectation that multiple config files will not interact *at all*, that a `filter { }` or `output { }` in one file is not seen by another.
* Expectation that Logstash should be ignoring any swapfiles or backup files created by editors

Examples (a non-exhaustive list):
* #2393 - expectation that two config files do not execute in the same pipeline
* #2271 - grok's `patterns_dir` tries to read an emacs/vim backup file.
* #2234 - hard-code directory support to implicitly append `*.conf` and ignore other file extensions.

I don't know exactly how to solve this. Can we have some confidence that logging the behavior will help folks observe this more directly?

**Comment by untergeek** [comment]
With regards to the expectation that multiple config files will not interact, perhaps we need to document it better.  That was an assumption someone made.

Can we test for globbing and issue a warning-level message?

**Comment by jordansissel** [comment]
I hesitate to use a warning log because new users interpret "warn" as "something horrible has gone wrong, I should ask for help"

**Comment by untergeek** [comment]
What if the warning message had a URL link which talked about file globbing?

**Comment by jordansissel** [comment]
I like this idea.

I'm also open to adding a 'notice' level log that would fit in between info/warn

**Comment by jsvd** [comment]
Logstash could support globbing in the -f parameter such as `bin/logstash -f *.config`
This would allow, for examples, rpm/deb init scripts to read only "*.conf" files, but not hard code this restriction in logstash.

**Comment by electrical** [comment]
@jsvd we already support that :-)

**Comment by jsvd** [comment]
Then we broke it in 1.5.0 beta1

```
% pwd
/tmp/logstash-1.5.0.beta1
% cat a.meh
input { generator { count => 20 } }
% cat b.meh
output { stdout { codec => dots } } 
% bin/logstash -f *.meh
bin/logstash -f *.meh  9.86s user 0.41s system 294% cpu 3.483 total
% bin/logstash -f a.meh b.meh 
bin/logstash -f a.meh b.meh  9.77s user 0.41s system 292% cpu 3.478 total
% bin/logstash -f a.meh -f b.meh 
Using milestone 1 codec plugin 'dots'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}
bin/logstash -f a.meh -f b.meh  9.91s user 0.40s system 288% cpu 3.574 total
% cat a.meh b.meh > meh
% bin/logstash -f meh
Using milestone 1 codec plugin 'dots'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}
....................bin/logstash -f meh  10.40s user 0.44s system 291% cpu 3.718 total
```

**Comment by jsvd** [comment]
Doesn't work on 1.4.2 either:

```
% pwd
/tmp/logstash-1.4.2
% bin/logstash -f *.meh
No such command "b.meh"
Usage: logstash <command> [command args]
Run a command with the --help flag to see the arguments.
For example: logstash agent --help

Available commands:
  agent - runs the logstash agent
  version - emits version info about this logstash
  web - runs the logstash web ui (called Kibana)
  rspec - runs tests
bin/logstash -f *.meh  13.34s user 0.44s system 258% cpu 5.329 total
% bin/logstash -f a.meh b.meh 
No such command "b.meh"
Usage: logstash <command> [command args]
Run a command with the --help flag to see the arguments.
For example: logstash agent --help

Available commands:
  agent - runs the logstash agent
  version - emits version info about this logstash
  web - runs the logstash web ui (called Kibana)
  rspec - runs tests
bin/logstash -f a.meh b.meh  14.15s user 0.48s system 258% cpu 5.656 total
% bin/logstash -f a.meh -f b.meh 
Using milestone 1 codec plugin 'dots'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
bin/logstash -f a.meh -f b.meh  17.52s user 0.57s system 272% cpu 6.637 total
% cat a.meh b.meh > meh
% bin/logstash -f meh
Using milestone 1 codec plugin 'dots'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
....................bin/logstash -f meh  18.47s user 0.69s system 260% cpu 7.364 total
```

**Comment by ScoobyDooWho** [comment]
As a newbie to LS (About a month in now) ... I can say that the multiple config issue caught me...but I could also see right away from just having one config file and multiple inputs etc. that a Conditional flow of some sort must be used... and there is... so I got to thinking...and keep in mind, new to LS here...your .conf files are like open ended pieces of dynamic code (JSON) ... INPUT, Filter, Output...if we just added a root (namespace) to each of the .conf files... eg: {LogstashLogsOne: {Input{},Filter{},Output{}} ...that would give you the key needed to handle different configs per some 'config_type' value set at INPUT or at the source...Inputs could still be global, perhaps just the Filter and Outputs are namespaced... But something like that would easily allow the code internally to still generate this one big pipeline, but now you'd just build a pipeline of hash entries...and still have the core one that's there today (the default) if no namespaces are used at all.

**Comment by M0dM** [comment]
@jsvd 
It works like this : bin/logstash -f "*.meh"
That's how I am using it, with double quotes ;)

**Comment by untergeek** [comment]
This is much better documented now, and more visible with #4182 merged in.
