### ISSUE TITLE
Logstash hangs on Non-OK response code from Elasticsearch - logs are lost!

### ISSUE THREAD

**Issue by kosfar** [elastic/logstash#2509]
Hi,
I am using logstash 1.4.2 and elasticsearch output with protocol => "http". Our ES cluster is version 0.90.13 and we use redis as a queue mechanism. 
logstash --> redis --> logstash --> ES 

In random times we experience logstash indexer freezes, redis queue length increases and the software logs:
{:timestamp=>"2015-02-03T18:01:07.257000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>71, :exception=>#<RuntimeError: Non-OK response code from Elasticsearch: 404>, :backtrace=>["/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:127:in `bulk_ftw'", "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:80:in `bulk'", "/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

Logstash comes back in life after process restart but the problem is that logs that are waiting in redis seem to land to nowhere, they are gone. 
In the last time, problems started at 18:01:07, stopped at 19:56:10 after logstash restart but logs that managet to get indexed are only after 19:34 (verified this on kibana). The logs between 18:01:07 and 19:34 were lost. You can check this on the screenshot. I have noticed that there is already a related open issue here:
https://logstash.jira.com/browse/LOGSTASH-2203

Can you elaborate on this plz?

![screenshot from 2015-02-03 20 09 52](https://cloud.githubusercontent.com/assets/701533/6041822/8256d2e8-ac88-11e4-9f58-94d01c3251d0.png)

**Comment by jordansissel** [comment]
Pretty sure the intrepid bugsquasher, @talevy, fixed this and we just haven't released it yet. @talevy? Thoughts?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/136. Let's continue the discussion there! :)
