### ISSUE TITLE
replace json_spooler with json codec

### ISSUE THREAD

**Issue by CrackerJackMack** [elastic/logstash#2514]
Example implementation: https://gist.github.com/CrackerJackMack/e89dc7459669e6264441

I didn't like the json_spooler.rb implementation and it being marked deprecated wasn't a wise go-forward plan for my production use.

Using the above patch and creating codecs/json_split.rb using the same internals of codecs/json.rb I'm now able to utilize top-level array json bodies.  This greatly helps both my producers and consumers using rabbitmq and I thought I'd offer up the concept for discussion in augmenting the codecs/json.rb file with this super small patch that also replaces json_spooler.rb

**Comment by jordansissel** [comment]
In master, I believe this is fixed automatically.

When json is decoded, if that json's root is an array, then we will yield each element as an event. Observed with this test case:


```
% bin/logstash -e 'input { stdin { codec => json_lines } }'
[ { "hello": "world" }, { "event": "two" } ]

{
  "hello"      => "world",
  "@version"   => "1",
  "@timestamp" => 2016-03-08T23:21:01.330Z,
  "host"       => "localhost.localdomain"
}
{
  "event"      => "two",
  "@version"   => "1",
  "@timestamp" => 2016-03-08T23:21:01.330Z,
  "host"       => "localhost.localdomain"
}
```

Two events are output. Yay! :)

**Comment by CrackerJackMack** [comment]
Awesome, ty for the follow up!
