### ISSUE TITLE
Logstash SQS too slow to process

### ISSUE THREAD

**Issue by PraveenJayakrishnakumar** [elastic/logstash#2515]
I observed that logstash SQS input queue is making too slow to process the logs and sometimes it breaks the process, if it processing more log messages.

Following error messages am getting when it started to process more logs,
1. Errno::EBADF: Bad file descriptor - Bad file descriptor
2. AWS::SQS::Errors::SignatureDoesNotMatch
3. AWS::SQS::Errors::BatchRequestTooLong
4. AWS::SQS::Errors::ChecksumError

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-sqs/issues/8. Let's continue the discussion there! :)
