### ISSUE TITLE
ipfix input plugin

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#2525]
migrated from: https://logstash.jira.com/browse/LOGSTASH-799
info on ipfix: http://en.wikipedia.org/wiki/IP_Flow_Information_Export

related:
```
yaf
bprobe/nprobe
https://github.com/britram/ripfix/tree/master/lib/ipfix
```

**Comment by bodgit** [comment]
See logstash-plugins/logstash-codec-netflow#10

**Comment by untergeek** [comment]
Closing in favor of the net flow codec listed above.
