### ISSUE TITLE
Rspec do not work for @timestamp

### ISSUE THREAD

**Issue by zhenghu** [elastic/logstash#2527]
I found the rspec do not work with @timestamp.
Below is a test.

Here is the sample
  
   ```
   sample({"type" => "test",
                 "date" => "2014-12-25 23:00:09"}) do
      #Test
      insist { subject["@timestamp"] } == "2014-12-25T22:00:09.000Z"
      reject { subject["tags"] } == "_grokparsefailure"
   end
   ```
This is the filter

   ```
    if [type] == "test" {
         date {
             match => [ "date", "yyyy-MM-dd HH:mm:ss" ]
         }
     }
   ```
I got the error : Expected "2014-12-25T22:00:09.000Z", but got "2014-12-25T22:00:09.000Z"

**Comment by ph** [comment]
The error is misleading, you are comparing an instance of the timestamp class to a string and not the string value, rspec will transform the instance into a string before reporting the error to you.
If you want to compare string you will have to transform the timestamp instance in a string.

I did not test this but It should work.
```ruby
insist { subject["@timestamp"].to_s } == "2014-12-25T22:00:09.000Z"
```

**Comment by ph** [comment]
This is the normal behavior, the assert in this case is just wrong.
We are moving away from using `insist` in the code and will rely on the core `rspec` methods, from my experience they will provide better context.

**Comment by zhenghu** [comment]
Thanks for your response.
But with .to_s, I got : 2014-12-25 22:00:09 UTC
Is there a good way to test @timestamp?

**Comment by untergeek** [comment]
You could convert timestamps to epoch and do a straight-up numeric comparison.

**Comment by jordansissel** [comment]
This ticket seems idle. I hope the issue was resolved. If not, let us know over at the forums at https://discuss.elastic.co/ :)
