### ISSUE TITLE
Logstash API

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#2529]
Logstash's current lack of metrics, visibility to its internal state and inability to manipulate a running pipeline calls for a much needed API!!
This should be implemented alongside the current `-f logstash.conf` feature and not replace it.

Logstash should expose resources such as itself (or LogStash::Agent), the pipeline(s) and plugins:
 * Logstash instance: a single logstash instance started with `bin/logstash -f ...` that runs 1 or more pipelines
   * URL: `http://localhost:9400`
 * Pipeline: a `Logstash::Pipeline` instance with 3 stages: input, filter and output 
   * URL: `http://localhost:9400/<pipeline_id>`
 * Pipeline stage: one of three stages of a Pipeline, containing an ordered list of 0 or more plugin instances
   * URL: `http://localhost:9400/<pipeline_id>/input`
 * Plugin instance: one instance of a plugin (e.g. `mutate`, `stdin`, `tcp`, etc.)
   * URL:  `http://localhost:9400/<pipeline_id>/filter/<plugin_instance_id>`

This would then allow one to start an empty LS instance and POST a configuration to it, creating a new pipeline: `curl -X POST http://newnode:9400 -d "<config>"` or updating a configuration through `curl -X PUT http://node:9400/pipeline_name -d "<config>"`

Each resource would also have a state or status API that included metrics.

Migrated from https://logstash.jira.com/browse/LOGSTASH-85

**Comment by untergeek** [comment]
Migrating https://logstash.jira.com/browse/LOGSTASH-169 and https://logstash.jira.com/browse/LOGSTASH-223 here, which are exposing plugin and pipeline metrics via API.

**Comment by untergeek** [comment]
Migrating https://logstash.jira.com/browse/LOGSTASH-227 here as well.

**Comment by jsvd** [comment]
More details on each resource's changes to accommodate an API:

1. Allow an agent to have 0 or more pipelines => this requires decoupling the agent from the pipeline so that an agent can start with no pipelines

2. Improve the Pipeline API => necessary actions are:
 a) create - starts a paused pipeline instance w/ a config and instantiates all the plugins
 b) destroy - sends shutdown to all its plugins and eventually stops
 c) status - should include pipeline state, list of plugins, the config itself and some runtime metrics
 d) pause - halts inputs; unpause resumes inputs

3. Improve the Agent API => expose pipelines and basic status information (number of pipelines, state, metrics?)

**Comment by untergeek** [comment]
Migrating: https://logstash.jira.com/browse/LOGSTASH-224 here also.

**Comment by untergeek** [comment]
https://logstash.jira.com/browse/LOGSTASH-220 will be addressed by this as well.

**Comment by untergeek** [comment]
https://logstash.jira.com/browse/LOGSTASH-334 will be handled here (but REST vs. JMX).

**Comment by untergeek** [comment]
Migrating https://logstash.jira.com/browse/LOGSTASH-961 here.

**Comment by untergeek** [comment]
And yet another ticket: https://logstash.jira.com/browse/LOGSTASH-1758

**Comment by palmerabollo** [comment]
IMO, LOGSTASH-220 "Make SIGHUP cause agent to reload" should be addressed on an separate issue.

**Comment by jordansissel** [comment]
@palmerabollo there will be nothing to "reload" once we have an API. Can you help me understand what you mean?

**Comment by palmerabollo** [comment]
Sorry, I meant that hot configuration reloading is an interesting feature that might be addressed before logstash 2.x. In case that's not an option, do you think it would be easy to add that feature to the current logstash 1.x  architecture on my own?

**Comment by jordansissel** [comment]
@palmerabollo A general-purpose reload is difficult because I'm not really sure what precise behavior everyone is looking for. A simple "reload the config" right now can be achieved with restarting logstash. Is restarting not an option? Here are some challenges I see with a "reload" that has no downtime effects:
1) networked plugins have no way to share their resources (if you reload the tcp input, you'd have to hand off the tcp sockets or close them all and reopen, either way it's difficult or messy)
2) reloading would probably have to quiesce the system (no events in-flight) which will pause all processing of events before doing the reload, and a quiesced logstash may be indistinguishable from a down logstash (udp packets lost, etc)

There are probably other concerns specific to reload, and _lots_ of work is going to be going into Logstash for 2.0 so that we can do an api and it's similar to the work required to implement reload effectively.

**Comment by suyograo** [comment]
This was a very early prototype idea. Closing this because we have put more thought and we have concrete details, API wireframes we can discuss.

**Comment by suyograo** [comment]
Closed in lieu of https://github.com/elastic/logstash/issues/2612 and future concrete issues
