### ISSUE TITLE
String field expansion thingy should support 'default if no value present'

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#2530]
Migrated from: https://logstash.jira.com/browse/LOGSTASH-268

> Currently, if you use `%{foo}` and there is no such field, it leaves `%{foo}` literally.
>
> In many cases, you probably want to specify a default value. Bourne shells let you do this by saying `${foo:=default value}`
> 
> Maybe permit folks to do `%{foo=bar}` and also `%{foo=%{baz}fizz}` and such.

**Comment by wiibaa** [comment]
related to https://github.com/elasticsearch/logstash/issues/2315

**Comment by jordansissel** [comment]
Still interest in this?

**Comment by suyograo** [comment]
Dup of https://github.com/elastic/logstash/issues/4416.Closing
