### ISSUE TITLE
Optionally append to a route field as the event flows through the system

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#2534]
When you have N redis nodes and M logstash indexers, it can get a bit difficult to find the issue in the system.
Having a route-taken field would be a major plus.

migrated from: https://logstash.jira.com/browse/LOGSTASH-633

**Comment by jordansissel** [comment]
+1 this would be neat to include with some of our monitoring/tracing stuff. Nothing in the roadmap yet, as far as I Know though.

**Comment by talevy** [comment]
Closing due to lack of traction
