### ISSUE TITLE
Test on FreeBSD

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#2538]
migrated from: https://logstash.jira.com/browse/LOGSTASH-854

**Comment by benoitBrayer** [comment]
I had the same issue on HP-UX Operating system.

On HP-UX the stat.st_dev value does not exist, I don't know for FreeBSD.

I solved it by forking the filewatcher gem.
Check my fork maybe it could help you.

https://github.com/jordansissel/ruby-filewatch/pull/41

**Comment by jordansissel** [comment]
Testing on other platforms would be lovely, but I don't know if we have the bandwidth right now to do so.

**Comment by jordansissel** [comment]
(Also, we have no access to HP-UX systems of our own so even if we had bandwidth, we don't have jenkins or travis-ci able to test on HP-UX.)
