### ISSUE TITLE
Worker Thread Setting Not Being Respected [ 1.4.x ]

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#2542]
migrated from: https://logstash.jira.com/browse/LOGSTASH-2161

I installed logstash via the official RPM. The 'LS_WORKER_THREADS' variable in /etc/sysconfig/logstash is not being respected by the init script.
Workaround:
In /etc/init.d/logstash, append the following to the DAEMON_OPTS line:
--filterworkers $
{LS_WORKER_THREADS}
"

**Comment by jordansissel** [comment]
LS_WORKER_THREADS is not referenced in master, that I can see, so I believe this may be resolved.

**Comment by webmstr** [comment]
I think @talevy is reporting that it *should* be referenced in the code, as in used to provide info to the "-w"/"--filterworkers" param in the init scripts.

+1.

**Comment by webmstr** [comment]
Comment https://github.com/logstash-plugins/logstash-input-lumberjack/issues/36 says we need to add it to LS_OPTS instead.
