### ISSUE TITLE
Logstash 1.4 crashes on windows

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#2544]
I am getting the following message on the console
[ timer expired, abort... ]
#
A fatal error has been detected by the Java Runtime Environment:
#
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007feef3a1aa4, pid=7956, tid=6536
#
JRE version: Java(TM) SE Runtime Environment (7.0_40-b43) (build 1.7.0_40-b43)
Java VM: Java HotSpot(TM) 64-Bit Server VM (24.0-b56 mixed mode windows-amd64 compressed oops)
Problematic frame:
C

migrated from: https://logstash.jira.com/browse/LOGSTASH-2076

**Comment by talevy** [comment]
@jordansissel is this still applicable?

**Comment by jordansissel** [comment]
Idle ticket. Closing.
