### ISSUE TITLE
Reject (or warn strongly) if running on a known-buggy JVM

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2547]
See https://github.com/elasticsearch/logstash/issues/2537 for context.

There are known bugs in the JVM/Java that we'd like to avoid by not using known buggy versions.

Should we abort execution on these JVMs? Just warn strongly? Add a flag that permits running, like `--i-know-my-java-is-broken` ?

**Comment by tbender** [comment]
Could you elaborate on the buggy VMs a bit?

**Comment by jordansissel** [comment]
@tbender For a bug specific to Logstash, see #2537. 

For bugs found by the Lucene project, they also maintain a list http://wiki.apache.org/lucene-java/JavaBugs

**Comment by electrical** [comment]
I think we should always allow it to run but we could print out a warning about it referring to a web page with known java related bugs.

**Comment by andrewvc** [comment]
@jordansissel I'm thinking that we just check for JVMs < 1.7.0_51 b04 and print the warning there. A lot of the Lucene bugs are for fairly old versions. Additionally, JDK7 is almost EOL anyway.

Your thoughts?

**Comment by jordansissel** [comment]
@andrewvc +1 on your proposal.

**Comment by andrewvc** [comment]
Thanks for the idea @electrical ! Merged into master.
