### ISSUE TITLE
Update github description and website

### ISSUE THREAD

**Issue by wiibaa** [elastic/logstash#2548]
I suppose you overlooked it as much as me but when landing on https://github.com/elasticsearch/logstash/ a new user is still pointed to http://logstash.net 
Is it time to point to http://elasticsearch.org/guide/en/logstash/current/index.html or another elasticsearch resource ?

**Comment by jordansissel** [comment]
@wiibaa the docs on the es.org guide for lgostash are for an unreleased version of logstash, which is why we haven't updated all the links yet.

**Comment by jordansissel** [comment]
When Logstash 1.5 is released, we can point users at the 1.5 docs there. :)

**Comment by wiibaa** [comment]
The link was changed but the description should also be reduced to **manage events and logs** as kibana is not bundled

**Comment by jordansissel** [comment]
@wiibaa done!
