### ISSUE TITLE
ZeroMQ input does not working with libzmq 4.0.5

### ISSUE THREAD

**Issue by milgendd** [elastic/logstash#2549]
After starting logstash with the following configuration:
```
input {
  zeromq { topology => "pubsub" type => "zeromq-input" }
}

output { stdout { codec => rubydebug } }
```

The following error occurred:

LoadError: The libzmq version 4.0.5 is incompatible with ffi-rzmq.

Logstash 1.4.2

**Comment by milgendd** [comment]
A solution could be found here: https://github.com/elasticsearch/logstash/issues/1870

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-zeromq/issues/3. Let's continue the discussion there! :)
