### ISSUE TITLE
Elasticsearch 0.90.0 or above required

### ISSUE THREAD

**Issue by ostraaten** [elastic/logstash#2551]
I installed elasticsearch using deb https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.deb

So I installed 1.4.2.

This versions seems to be incompatible with logstash because when I run the web interface and go to browser I can see message
"Upgrade Required Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9 or above."

The version check seems to be wrong. Assuming 1.4.2 is a newer version that  0.90.9.

How can I run logstash with newer versions than 0.90.9? Should I downgrade elasticsearch?

**Comment by ostraaten** [comment]
I tried to downgrade to 0.90.9 using https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.9.deb but that version of elasticsearch doesn't seem to work at all.

When I start service and go to page http://localhost:9200/_search?pretty I see error message

    {
      "error" : "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed]",
      "status" : 503
    }

**Comment by jsvd** [comment]
In ES 1.4.2 cors is disabled by defaulthttp://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-http.html

Changing that in elasticsearch.yml and restarting it should fix it, no need to downgrade.

**Comment by ostraaten** [comment]
I added to that file

    http.cors.allow-origin: "/.*/"
    http.cors.enabled: true

In Kibana it looks like the message is gone. LogStash is however no longer working. Last week this working it seems that something changed along the way

ostraaten@kore:~/Apps/logstash-1.4.2$ bin/logstash -e 'input { stdin { } } output { elasticsearch { host => localhost } }'
log4j, [2015-02-09T15:29:06.812]  WARN: org.elasticsearch.discovery.zen.ping.unicast: [logstash-kore-6190-2010] failed to send ping to [[#zen_unicast_2#][kore][inet[localhost/127.0.0.1:9301]]]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[localhost/127.0.0.1:9301]][discovery/zen/unicast] request_id [2] timed out after [3751ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
log4j, [2015-02-09T15:29:06.812]  WARN: org.elasticsearch.discovery.zen.ping.unicast: [logstash-kore-6190-2010] failed to send ping to [[#zen_unicast_3#][kore][inet[localhost/127.0.0.1:9302]]]

**Comment by jsvd** [comment]
that usually happens when LS can't reach ES, either because it's down or ES is listening on a different host/port

**Comment by ostraaten** [comment]
Ok, thanks, it must be the port because I can reach http://localhost:9200/ and http://localhost:9200/_search?pretty=1&q=* is also working

When I use
    bin/logstash -e 'input { stdin { } } output { elasticsearch { host => localhost port => "9300" protocol => "node" } }'

It is not much better. There are no error messages but I can stdin what I want. It all won't be added to the index.

bin/logstash -e 'input { stdin { } } output { elasticsearch { host => localhost port => "9200" protocol => "http" } }'

will result in error message. 

Configuration is most likely not at all straightforward. I expected it straightforward because there is hardly any documentation. Some examples but these don't work. 

Logstash/elasticsearch looks great first impression but my experiences so far beg a question: is logstash used?

**Comment by jsvd** [comment]
Is the elasticsearch's cluster name the default "elasticsearch"? if you changed it you need to set it as well if you're using "protocol"=> "transport" or "protocol"=> "node"

**Comment by ostraaten** [comment]
```ostraaten@kore:~/Apps/logstash-1.4.2$ bin/logstash -e 'input { stdin { } } output { elasticsearch { host => localhost cluster => "elasticsearch" protocol => "http" } }'
Elasticsearch::Transport::Transport::Errors::BadGateway: [502] <HEAD><TITLE>Connection refused</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>Connection refused</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
Description: Connection refused</B></FONT>
<HR>
<!-- default "Connection refused```

**Comment by jsvd** [comment]
wow that's strange, you're getting html!?
what's the output of "curl http://localhost:9200"?

**Comment by ostraaten** [comment]
ostraaten@kore:~/Apps/logstash-1.4.2$ curl http://localhost:9200
{
  "status" : 200,
  "name" : "Wysper",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}
ostraaten@kore:~/Apps/logstash-1.4.2$

**Comment by jsvd** [comment]
I assume there's no proxy in front of ES

**Comment by ostraaten** [comment]
Actually, this was the issue. Proxy server settings

**Comment by ostraaten** [comment]
no_proxy does not seem to work, when I do

    export no_proxy="localhost,127.0.0.1"

It fails. I have to use
  
    unset http_proxy

**Comment by jsvd** [comment]
sorry that you hit that issue, it has been recorded in the plugin's repo https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/44

**Comment by jordansissel** [comment]
A quick glance at this ticket makes me think it's resolved (or at least, further tickets were filed elsewhere). Closing it :)
