### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset: ffi

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2556]
Filed upstream with rubygems: https://github.com/rubygems/rubygems/issues/1070

**Comment by jordansissel** [comment]
Might be fixed in Jruby 1.7.20 when released according to this comment: https://github.com/rubygems/rubygems/issues/1070#issuecomment-73358102

**Comment by colinsurprenant** [comment]
will tackle a monkey patch

**Comment by colinsurprenant** [comment]
committed a temporary monkey patch in 76bb77fd117a21b9eb82d40718571e171e2da44a for #2475

it specifically silence ffi warning. let's keep this issue open until we can remove that patch, hopefully with JRuby 1.7.20.

**Comment by ph** [comment]
(rejoice)

**Comment by suyograo** [comment]
tested works using 76bb77f for #2475

**Comment by ph** [comment]
Moving this to 2.0

**Comment by untergeek** [comment]
It looks like this has been addressed in https://github.com/rubygems/rubygems/issues/1070.

Closing.
