### ISSUE TITLE
Document http proxy support for installing plugins

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2557]
`bin/plugin install` and other commands should be able to work when using a http proxy.

We should simply document the standard way of using proxy support with RubyGems.org:
```
export http_proxy=http://user:password@host:port
```

**Comment by suyograo** [comment]
This should go into the "how-to" as well

**Comment by electrical** [comment]
I'm not sure if the jar-dependencies part will pick it up since it was specifically trailered to pick up the Gem.proxy settings.

**Comment by smougenot** [comment]
It might help others: you may need to proxy both HTTP and HTTPS

    export http_proxy=http://user:password@host:port
    export https_proxy=http://user:password@host:port
    /opt/logstash/bin/plugin install logstash-???-??

**Comment by DarkKnightCZ** [comment]
Since Logstash uses JRuby, Java proxy settings need to be applied, either as temporary (just export) or persistent (modify bin/plugin and add it before ruby exec)

export JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=HOST -Dhttp.proxyPort=PORT"

**Comment by SydOps** [comment]
@DarkKnightCZ 's solution are very closed. But miss one setting:

    JARS_SKIP='true' 

https://discuss.elastic.co/t/5-1-1-plugin-installation-behind-proxy/70454/10
```
export JRUBY_OPTS="-J-Dhttp.proxyHost=proxy.host -J-Dhttp.proxyPort=3128"
DEBUG=1 JARS_SKIP='true' bin/logstash-plugin install logstash-filter-json_encode
```
