### ISSUE TITLE
Remove the message "Can one of the admins verify this patch?"

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2573]
I don't know what the reason for having this message is; it is just confusing. 

https://github.com/elasticsearch/logstash/pull/2572#issuecomment-73779643

**Comment by purbon** [comment]
As you can see in https://github.com/elastic/logstash/pull/2961 this can be considered done by now.

**Comment by purbon** [comment]
Can we close this?

**Comment by jordansissel** [comment]
Done!
