### ISSUE TITLE
Rename message "Can you test this please" to trigger Jenkins build

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2574]
Today we can manually trigger a new Jenkins build for a commit using the message "Can you test this please?". This is confusing to the contributors/reviewers. We should qualify that this message is for Jenkins. Something like "@Jenkins retest" or something on those lines

**Comment by purbon** [comment]
This has been renamed, should we close it?

**Comment by jordansissel** [comment]
Yep!
