### ISSUE TITLE
[Debian package] Start Logstash at boot time

### ISSUE THREAD

**Issue by davux** [elastic/logstash#2578]
When Logstash is installed using a Debian package, it should be set to be started automatically on boot. I'm not familiar with the intermediate layers used to build the package, but at the end of the day the package should issue a `update-rc.d logstash defaults` command in its postinst script.

I only noticed the issue on Debian because that's what I'm using, but it might be true on other systems as well.

Also, I'm currently using logstash 1.3.1 but it doesn't look like anything related to that has changed since then.

**Comment by jordansissel** [comment]
It should be starting by default without the need for update-rc.d; we'll take a look.

**Comment by davux** [comment]
Checking back – did you find a way? I checked that package and there's no mechanism to start the service at boot time.

**Comment by jordansissel** [comment]
I haven't made time to investigate this yet.

**Comment by untergeek** [comment]
Has anyone tried this with 2.2.0 and the recent changes?  1.3.1 is quite old.

**Comment by suyograo** [comment]
Closing this, LS will not start by default when installed via unix service
