### ISSUE TITLE
Logstash loses path to `ruby` on running `git init` on extracted logstash folder

### ISSUE THREAD

**Issue by swarajgiri** [elastic/logstash#2581]
### Error message
`No ruby program found. Cannot start.`

### Steps to reproduce
- Download [logstash-1.4.2](https://download.elasticsearch.org/logstash/logstash/logstash-1.4.2.tar.gz)
- Extract it to a folder `logstash-1.4.2` and cd into it.
- Run `bin/logstash -e 'input { stdin { } } output { stdout { codec => rubydebug } }'`. It works.
- Run `git init`.
- Logstash throws error `No ruby program found. Cannot start.`
- Remove `.git` folder using `rm -rf .git` and logstash starts working again.

**Comment by jkirk** [comment]
I can confirm this problem. But you do not even have to run ```git init```, ```mkdir .git``` is enough...

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by jkirk** [comment]
Just tested with [logstash-2.2.2](https://download.elastic.co/logstash/logstash/logstash-2.2.2.tar.gz) and the problem seems to be gone! Thank you!

**Comment by swarajgiri** [comment]
Closing
