### ISSUE TITLE
build rpm logstash 1.4.2 will require /home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby

### ISSUE THREAD

**Issue by xugangsh** [elastic/logstash#2584]
Hi all,

My system is rhel 7.0
We need build logstash 1.4.2 rpm for our customer.
We used source tarball from official website

But when try to build rpm, it seemed automatically pull in more deps than I wrote in spec file

Below is log:

+ /usr/lib/rpm/check-buildroot
Processing files: logstash-1.4.2-2.ibm.el7.noarch
Provides: logstash = 1.4.2-2.ibm.el7 osgi(com.rabbitmq.client) = 3.2.0 osgi(com.spatial4j) = 0.4.1 osgi(log4j) = 1.2.17 osgi(org.apache.commons.codec) = 1.4 osgi(org.jruby.jruby) = 1.7.11 osgi(org.msgpack) = 0.6.6
Requires(interp): /bin/sh /bin/sh /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(pre): /bin/sh shadow-utils
Requires(post): /bin/sh
Requires(preun): /bin/sh
Requires(postun): /bin/sh
Requires: /bin/bash /bin/sh /home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby /usr/bin/env /usr/bin/ruby
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/xugang/tmp3/rpmbuild-logstash/BUILDROOT/logstash-1.4.2-2.ibm.el7.x86_64
Wrote: /home/xugang/tmp3/rpmbuild-logstash/RPMS/noarch/logstash-1.4.2-2.ibm.el7.noarch.rpm

My spec file is like below

Name:           logstash
Version:        1.4.2
Release:        2.ibm%{?dist}
Summary:        Logstash is a tool for managing events and logs.

Group:          System Environment/Daemons
License:        Apache License, Version 2.0
URL:            http://logstash.net
Source0:        https://download.elasticsearch.org/%{name}/%{name}/%{name}-%{version}.tar.gz

Source10:       logstash.init
Source11:       logstash-web.init

Source20:       logstash.logrotate
Source30:       logstash.sysconfig
Source40:       default.conf

BuildArch:      noarch

Requires:       jpackage-utils
Requires:       java-1.7.0-openjdk

Requires(post): chkconfig initscripts
Requires(pre):  chkconfig initscripts
Requires(pre):  shadow-utils

%description
Logstash is a tool for managing events and logs

%prep
#true
%setup -q

%build
#true

%install
rm -rf $RPM_BUILD_ROOT

%{__mkdir} -p %{buildroot}%{base_install_dir}
%{__cp} -r * %{buildroot}%{base_install_dir}

%{__mkdir} -p %{buildroot}%{base_install_dir}/tmp

# Plugins & Patterns
%{__mkdir} -p %{buildroot}%{base_install_dir}/plugins/%{name}/inputs
%{__mkdir} -p %{buildroot}%{base_install_dir}/plugins/%{name}/filters
%{__mkdir} -p %{buildroot}%{base_install_dir}/plugins/%{name}/outputs

# This is needed because Logstash will complain if there are no *.rb files in its Plugin directory
/bin/echo "Dummy file due to https://logstash.jira.com/browse/LOGSTASH-1555" > %{buildroot}%{base_install_dir}/plugins/%{name}/inputs/dummy.rb

%{__mkdir} -p %{buildroot}%{_localstatedir}/log/%{name}
%{__mkdir} -p %{buildroot}%{_localstatedir}/lib/%{name}
%{__mkdir} -p %{buildroot}%{_localstatedir}/run/%{name}

%{__mkdir} -p %{buildroot}%{_sysconfdir}/%{name}/conf.d
%{__install} -D -m 644 %{SOURCE40} %{buildroot}%{_sysconfdir}/%{name}/conf.d/sample.conf

%{__mkdir} -p %{buildroot}%{_initrddir}
%{__install} -m 755 %{SOURCE10} %{buildroot}%{_initrddir}/logstash
%{__install} -m 755 %{SOURCE11} %{buildroot}%{_initrddir}/logstash-web

%{__install} -D -m 644 %{SOURCE20} %{buildroot}%{_sysconfdir}/logrotate.d/logstash

%{__install} -D -m 644 %{SOURCE30} %{buildroot}%{_sysconfdir}/sysconfig/logstash

%pre
# create logstash group
if ! getent group logstash >/dev/null; then
        groupadd -r logstash
fi

# create logstash user
if ! getent passwd logstash >/dev/null; then
        useradd -r -g logstash -d %{base_install_dir} \
            -s /sbin/nologin -c "Logstash" logstash
fi

%post

%preun

%postun

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{base_install_dir}/*
%{_sysconfdir}/*
%{_localstatedir}/*

But when I try to install, 

Error: Package: logstash-1.4.2-2.ibm.el7.noarch (/logstash-1.4.2-2.ibm.el7.noarch)
           Requires: /home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby

I found the same issue by google

https://logstash.jira.com/browse/LOGSTASH-2287

Could you support ?
Thanks!

**Comment by xugangsh** [comment]
I think below files are not correct format

vendor/bundle/jruby/2.1/bin/ldiff:#!/home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby
vendor/bundle/jruby/2.1/bin/bundler:#!/home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby
vendor/bundle/jruby/2.1/bin/htmldiff:#!/home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby
vendor/bundle/jruby/2.1/bin/bundle:#!/home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby
vendor/bundle/jruby/2.1/extensions/universal-java-1.7/2.1/murmurhash3-0.1.4/gem_make.out:/home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby extconf.rb

**Comment by mriedem** [comment]
Maybe check this out?

http://fedoraproject.org/wiki/Packaging:Ruby#Filtering_Requires_and_Provides

**Comment by rogerwelin** [comment]
Was this ever resolved? I'm having the exact same problem with:  "Failed dependencies:
	/home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby is needed"

**Comment by xugangsh** [comment]
Not yet.
Seemed no one respond me.

Thanks!

**Comment by Loyc59** [comment]
Hi,

Thank you for your spec file.
I was having the same problem with jruby dependency.

Here the changes I made
```
#Requires:       java-1.7.0-openjdk
Requires:       jre >= 1.6.0

AutoReqProv: 	no

Requires(post): chkconfig initscripts
Requires(pre):  chkconfig initscripts
Requires(pre):  shadow-utils
```

Hope this helps.

**Comment by jordansissel** [comment]
For those of you needing help with your custom rpm specs, I don't know what to offer. We use fpm to build our release RPMs, and it doesn't use a spec file.

I recommend y'all get together on https://discuss.elastic.co/ and see what you can work out together :)

**Comment by Jmainguy** [comment]
Add AutoReqProv: no to your spec file to stop it from autochecking dependencies, such as 
/home/jls/.rvm/rubies/jruby-1.7.12/bin/jruby is needed"

**Comment by xugangsh** [comment]
fpm will try to use pypi to solve all depdency
We used rpm spec.
The solution of AutoReqProv: no is good which I used the same in our env.
Now the problem solved.

Thanks all!
