### ISSUE TITLE
Logstash 1.4.2 - Kibana 3 Terms panel fails sometimes !

### ISSUE THREAD

**Issue by pleroch** [elastic/logstash#2586]
Hello,
I use Logstash 1.4.2, elasticsearch 1.0.15, Kibana 3 on Windows 2008.
With Kibana, the TERMS panel is sometimes wrong when datas includes the "-" character (dash) :
![ls_kibana_bug_01_2](https://cloud.githubusercontent.com/assets/10956803/6145331/f6ee08ee-b1e0-11e4-9b47-b077eee5a2bb.jpg)
This failure appears sometimes after long display update...
The only way to go back i found is to delete the dashboard, to restart the Logstash server, to clean browser cache and reload the dashboard.
Is-it ok with Logstash 1.5 and Kibana 4 ?
Thanks
Patrick

**Comment by jordansissel** [comment]
This is the default behavior of Elasticsearch's text tokenization and analysis process. Elasticsearch will by default treat strings like written language and split things into terms, so `foo-bar` becomes two terms `foo` and `bar`. Further, in your screenshot, you'll also notice that `CAPITALIZED WORDS` become lowercased. This is also part of Elasticsearch's tokenization and analysis features.

We know this happens, so Logstash compensates by adding a special field for every string. In your case, the field `LOG_platforme` will be available in un-analyzed form as `LOG_platforme.raw`. If you do a terms panel on this field instead, it should work nicely for you.

Elasticsearch has features to let you change the default analyzer, but hopefully Logstash's default behavior (the `.raw` field) will help you more.

**Comment by jordansissel** [comment]
Given Logstash provides the .raw field, I think this isn't a bug (many users want both normal/tokenized and unprocessed/raw searching and terms listings). I'll close this, but if you have any other questions like this, I welcome you to visit our new discussion forum here: http://discuss.elastic.co/

(Obviously, if you find bugs, this is a good place to file them)
