### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by onknows** [elastic/logstash#2587]
I am hitting yet another issue. There seems to be no end to it.

I am using config 
input {
  file {
    path => "/tmp/access_log"
    start_position => beginning
  }
}

filter {
  if [path] =~ "access" {
    mutate { replace => { "type" => "apache_access" } }
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
}

output {
  elasticsearch {
    host => localhost
    port => 9200
    protocol => 'http'
  }
  stdout { codec => rubydebug }
}

I see stuff being index in http://localhost:9200/_search?pretty=1 but LogStash web only shows one messsage:

No results There were no results because no indices were found that match your selected time span

I am starting this thing with
bin/logstash agent -apache-elasticsearch.conf web 

In web interface http://localhost:9292/ I only see this message

IMHO there should be a whole lot more documentation. Configuration of this thing created is not all straightforward. Creating a working demo of LogStash and ElasticSearch will take weeks. Not hours or days.

In any case I hoped to demo this thing tomorrow but getting more and more convinced there is just no way that timeline is realistic.

**Comment by jsvd** [comment]
Sorry you're hitting so many problems, assuming you imported your data, you can select the timespan of the dashboard option shown below:

![screen shot 2015-02-11 at 10 49 50](https://cloud.githubusercontent.com/assets/31809/6145641/c30b061c-b1db-11e4-830a-de29d5c69543.png)

This process should not be so troublesome, steps for a simple demo should be:

1. unpacking elasticsearch
2. adding `http.cors.enabled: true` to elasticsearch.yml
3. starting elasticsearch with `bin/elasticsearch`
4. unpacking logstash
5. creating a configuration file that outputs events to ES: `input {...} filter {..} output { elasticsearch { } }``
6. running `bin/logstash -f conf` to import data
7. running `bin/logstash web` to start kibana
8. accessing kibana through http://localhost:9292
9. clicking on "Logstash Dashboard" and selecting the correct time span

I just tried these steps with logstash 1.4.2 and elasticsearch 1.4.2 and got data:

![screen shot 2015-02-11 at 10 58 57](https://cloud.githubusercontent.com/assets/31809/6145746/13729e70-b1dd-11e4-81bd-88750d85bdc0.png)

**Comment by jsvd** [comment]
@ostraaten also, logstash remembers how far it has read the files using a [configurable .since_db file](https://github.com/logstash-plugins/logstash-input-file/blob/master/lib/logstash/inputs/file.rb#L49-L52) (default location `$HOME/.sincedb*`)
if you want logstash to read the file from the start every time you launch it, set `input { file { sincedb_path => "/dev/null" } }` so that the file isn't written.
