### ISSUE TITLE
grok overwrite not working for empty strings 

### ISSUE THREAD

**Issue by Vad1mo** [elastic/logstash#2590]
So when I have this input 

input="<14>2015-02-11T17:49:29Z logspout dev_ziservice_1[1]: ASDF"
```
  grok {      
    match => ["message", "<%{NUMBER}>%{TIMESTAMP_ISO8601:syslogTimestamp} %{SYSLOGHOST} %{DATA:container_name}(?:\[%{POSINT}\])?:%{SPACE}%{GREEDYDATA:message}"]
    overwrite => [ "message" ]
  }
````

message is = ASDF

if I have this input="<14>2015-02-11T17:49:29Z logspout dev_ziservice_1[1]: "
or this="<14>2015-02-11T17:49:29Z logspout dev_ziservice_1[1]:"

The message is not  " " or "" like displayed in http://grokdebug.herokuapp.com/

**Comment by harshamadala** [comment]
Is there any workaround for this?

**Comment by jsvd** [comment]
moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/77
