### ISSUE TITLE
RFE: Accept native logs from systemd-journal-upload

### ISSUE THREAD

**Issue by duncaninnes** [elastic/logstash#2594]
systemd now has the ability to send logs remotely via systemd-journal-upload

http://www.freedesktop.org/software/systemd/man/systemd-journal-upload.html

Being able to configure s-j-upload on every client is very much lighter than installing logstash on every client.  This requires that logstash could set up an input to accept s-j-upload data in native format.

**Comment by duncaninnes** [comment]
From previous discussions with s-j-upload developer, it would appear relatively simple to patch s-j-upload to support export in JSON format:
https://bugs.freedesktop.org/show_bug.cgi?id=77013#c7
"Adding json support to systemd-journal-upload (the sender part, which is
currently unmerged) would probably be quite simple... But for this to be useful,
it has to support whatever protocol the receiver uses. I had a look at the
logstash docs, and it seems that json_lines codec should work. I'm not
sure about the details, but it looks like something that could be added
without too much trouble. Maybe some interested party will write a patch :)"

It could be worthwhile to produce a suitable patch for s-j-upload and just use the TCP input to then receive the stream?
The systemd devs have no impetus to do this and I wouldn't prove a useful source of patching with coding skills that rate lower than rusty.  If any Logstash dev has the ability to look into this, it would provide a simpler method for end users to be able to send journald remote and have centralised Logstash instances receive the stream.

**Comment by jordansissel** [comment]
If it's a situation that requires patching systemd, I'm less worried about what serialization is used and more concerned lately with transport reliability. TCP alone is lossy in many situations, and I would prefer a transport that wasn't lossy.

**Comment by duncaninnes** [comment]
I've been using TCP from our current rsyslog clients in a fail over configuration to multiple Logstash servers. Didn't realise it was lossy.
What would be a better stream?
I've not tried s-j-upload to Logstash at all yet (even to see what comes in). 
I'm trying to figure a client config with minimum changes over what would already be running/installed on a Linux system (hence s-j-upload). Then push to Logstash in as native a format as Logstash would like to receive. 
Apologies if I've not refined these thoughts enough yet.

**Comment by jordansissel** [comment]
@duncaninnes hey no worries about refined thoughts - I'll be more clear about some things to reinforce that I'm enthusiastic about supporting systemd more readily:

1) Patches, ideas, etc, do not have to be well-refined to be submitted. I like working with folks to iterate on improving stuff :)
2) We can support TCP from systemd, but would love a less-lossy log shipping mechanism
3) If systemd has a binary form of logs instead of json, we can support this, too.

Let me know what I can help with! If you know how to wrangle the systemd-side of things, but not sure on logstash, lemme know, and we can work together to make it be awesome.

**Comment by duncaninnes** [comment]
OK, my original thought was to try to send native JSON from s-j-upload via TCP because I believed it to be robust. That's what I've done with my RHEL6 clients. I installed rsyslog7 on them (now available in RHEL6.6) and tweaked the configuration to output JSON over TCP to a pair (or 3) of Logstash servers in failed mode. This works very well and also allows me to insert bespoke key/value pairs in each log entry sent (e.g. "MY_Environment": "Production", "MY_Project": "Website", "MY_Type": "Webserver")
Here I'm labouring under a few (mis)conceptions; (a) TCP provides a reliable transport, (b) low effort on client to output logs in JSON, (c) low effort on Logstash to parse this input.
If any or all of a, b & c are wrong, or can be improved, I'm happy to change tack. But that was the premise I was basing my original thought on - to provide the lowest impact/footprint on the client side, while using a robust transport to ship to Logstash, where there also isn't a big overhead.
What transport would you prefer to use instead of TCP?
I'll look into the native output from s-j-upload tomorrow and update this ticket. I think someone has tried to receive this into Logstash, but again I think they were using TCP.

**Comment by duncaninnes** [comment]
This Gist has a logstash & s-j-upload config that might work. I have yet to test it though as my work machine doesn't have s-j-upload. Will look into it ASAP:
https://gist.github.com/brianredbeard/d5b02a1e998c63827b03

**Comment by jordansissel** [comment]
>  What transport would you prefer to use instead of TCP?

I don't have specific suggestions, just would note that TCP's reliability is a contract between the local program and the local network stack. Once the program does a write() on a socket, it is assumed "good" and there is little-or-no way to know if/when the network stack (OS kernel, usually) has transmitted it. This means if you send data, and logstash crashes before processing it fully, it is gone. Or if you send data, and a firewall or network problem interrupts the transfer, that data is gone without knowledge of how much was lost.

**Comment by duncaninnes** [comment]
OK - after digging further, s-j-upload uses https as default transport, but can also use http.  It sends by by HTTP POST to /upload on port 19532.  That sounds better to me - how about to you?

It uses "Content-Type: application/vnd.fdo.journal" and "Transfer-Encoding: chunked".

I'm streaming to http://localhost:19532/upload at the moment and receiving via a modified version of the logstash.conf from the gisthub I posted in my last comment.  I've simply changed it to output to a file at the moment:

output {
  file {
    path => "/home/logstash/logstash-output"
  }

}

and I'm now watching this file grow at a huge rate of knots as my entire journald history is pumped out via s-j-upload.

The format used to upload entries is the Journal Export Format: http://www.freedesktop.org/wiki/Software/systemd/export

**Comment by duncaninnes** [comment]
Looks like someone captured this in: https://github.com/moshen/logstash-http-input/issues/5

Although that ticket perhaps only touches on the https input?  Is logstash in a position to natively pull this data in?  The export format looks simple enough.  systemd only going to grow in Linux space as more distros move over to it.  Elegant solutions such as systemd-journal-upload sending direct to Logstash without the need for complex logstash configuration files would go down very well with end users and customers.

**Comment by duncaninnes** [comment]
Jordan, did my last 2 comments make any sense?  Wondering how this can be progressed on the Logstash side.

**Comment by duncaninnes** [comment]
Hi - revisiting this to see how practical it will be.
Speaking with various projects, there seems to be a willingness to become first-class integrators with journald (with logs using full key:value pairs for rich searching rather than simply dumping a log line into journald).  But nobody seems to want to be first.
Is the Logstash side of things a reasonable proposition at least?  Receiving native s-j-upload logs will be a powerful tool for Logstash - especially as there is the potential to rebase systemd in RHEL 7 to include such options as s-j-upload.  i.e. it's more "round the corner" than "over the horizon" in terms of timescale.

**Comment by duncaninnes** [comment]
Asking Red Hat for an estimate as to when the systemd-journal-gateway package will be enhanced to include the systemd-journal-upload tool.  The latest I have is that Red Hat Development are on board for my RFE and I've seen the work progress through the community side of things in Fedora.

**Comment by jordansissel** [comment]
@duncaninnes we're working on an http input that maybe able to support this stuff. I don't know if there's a ticket tracking that, though, @suyograo may know?

**Comment by duncaninnes** [comment]
@suyograo - do you have a ticket tracking the http input development for Logstash?  I'd like to keep track of it and hopefully help ensure that it covers the requirements for native input of systemd-journal-upload logs.
I'm taking a wild guess here that tagging someone in a comment alerts them somehow.  If not, how can I get a question to him @jordansissel ?

**Comment by zabbal** [comment]
It's unclear from the description of https://github.com/logstash-plugins/logstash-input-http whether HTTPS is supported properly (with certificate validation etc) or not. Anyway, we're still interested in getting log stream from systemd's journald - are there any progress on this?

**Comment by copumpkin** [comment]
:+1:

**Comment by suyograo** [comment]
@duncaninnes http-input is now at https://github.com/logstash-plugins/logstash-input-http . Please file any enhancement requests so we can take a look

**Comment by duncaninnes** [comment]
Cheers, will take a look.

**Comment by rogerwelin** [comment]
@duncaninnes just curious, did you manage to get this to work? I'm interested in solving the exact same thing

**Comment by duncaninnes** [comment]
Sorry, no. Work took me in a different direction about 6 months ago. It was a bit hopeful of me to say I'd look I to testing it. Now you bring it up again (and because work is slightly more back in that direction) I'll give it a go.

**Comment by rogerwelin** [comment]
@duncaninnes I see =) Cool, I have a go at it as well. I'll post an update if I manage to set something up worth using

**Comment by gbolo** [comment]
I tried to sending logs from `systemd-journal-upload` to `logstash-plugins-inputs-http` but systemd sends them chunked and the http input is not able to handle it properly, resulting in an empty message field (however the other http headers are populated in fields)

**Comment by justinasjaronis** [comment]
I'm also more than interested in this feature. It would be awesome..

**Comment by duncaninnes** [comment]
I'm trying to get a 'simple' setup going where systemd-jopurnal-upload is pushing logs to http://127.0.0.1:8080 and Logstash http input is running with default settings (i.e. on 0.0.0.0:8080).

I know logstash is listening as I can push data in via: curl -XPUT 'http://127.0.0.1:8080' -d 'test' and see the result produced in my log file output.

I have yet to get systemd-journal-upload to push anything however.  Initially there was a bug with starting the service up, but creating the /var/lib/systemd/journal-upload folder manually works around this.  Struggling to find much help diagnosing why systemd-journal-upload isn't sending anything.

**Comment by b0ch3nski** [comment]
@duncaninnes I think I got the reason why ``systemd-journal-upload`` is not sending anything to Logstash.

Logstash http plugin sends this response for any request (and it's currently not configurable):
```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 2

ok
```

While ``systemd-journal-upload`` is looking for this:
```
HTTP/1.1 100 Continue
```

There is an open PR regarding this functionality in ``logstash-input-http`` repo [Allow custom HTTP responses and message to be set in the config file](https://github.com/logstash-plugins/logstash-input-http/pull/59).

**Comment by jordansissel** [comment]
@b0ch3nski My intuition is that the systemd-journal-upload problem is more complex than just having the http input allow a custom response to an http request.

If we know exact behavior of the http call(s) used by systemd-journal-upload, this will be easier to answer.

**Comment by jordansissel** [comment]
I checked the HTTP RFC -- https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html

It seems like the web server the http input uses needs to support this kind of upload style where the client sets `Expect: 100-continue`. According to the RFC, the server still needs to respond with a final status code, so it is my conclusion that adding a custom response code will not solve this problem.

**Comment by jordansissel** [comment]
Let's move this issue to the http input plugin instead. Thank you :)

**Comment by b0ch3nski** [comment]
@jordansissel You are right, that PR doesn't solve this issue completely.

I have wrote a handy one-liner to patch Logstash with that PR:
```
wget -q -O - https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-input-http/pull/59.diff | sed 's/lib\/logstash\/inputs\/http.rb/vendor\/bundle\/jruby\/1.9\/gems\/logstash-input-http-3.0.3\/lib\/logstash\/inputs\/http.rb/g' | patch -p1
```

Modified http input config in pipeline:
```
input {
  http {
    port => 19532
    response_headers => {}
    response_ok_status => 100
    response_ok_message => ""
  }
}
```

And now I'm getting this error log in Logstash:
```
2016-12-12 18:42:29 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2016-12-12 18:42:29 +0000: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:fd 2>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"2.16.0", "GATEWAY_INTERFACE"=>"CGI/1.2"}
```

So this is now more ``puma`` issue than ``logstash-input-http``, unfortunately :(

BTW. If someone find this useful, this is how ``systemd-journal-upload`` POST looks like:
```
POST /upload HTTP/1.1
Host: 127.0.0.1:19532
User-Agent: systemd-journal-upload systemd 231
Content-Type: application/vnd.fdo.journal
Transfer-Encoding: chunked
Accept: text/plain
Expect: 100-continue

3fd9
<log messages>
```

Good bless Wireshark :)

**Comment by jordansissel** [comment]
@b0ch3nski can you open a new issue for this on logstash-input-http?

**Comment by duncaninnes** [comment]
This IS progress. I'll have to fire up my test boxes again.

**Comment by b0ch3nski** [comment]
@jordansissel @duncaninnes I could open a new issue in different place, but is ``logstash-input-http`` a best place for it?

In general, ``systemd-journal-upload`` uses unique and sophisticated standards - we have no support for it in ``logstash-input-http`` and in ``puma`` and even if we overcome these, we will still need to somehow parse those log entries that, unfortunately, aren't in _json_ format...

IMO this is a ``never-gets-properly-resolved`` case there, until someone truly determined takes this topic and write all the necessary code by his own.

Frankly, I'm now looking for a different solution... My only requirement is just to get journal logs into ES.

**Comment by duncaninnes** [comment]
Whilst I'm not sure I agree with the first few paragraphs (based on it being information I now need to investigate), the final one nails it for me. 

My only requirement is to get journal logs into ES. But I'll tailor that and say - in the most direct, native way possible (just in case someone suggests rsyslog).  

Do systemd-journal-upload logs not arrive in JSON format? Somehow I thought they would, but never saw the output from the push.

**Comment by b0ch3nski** [comment]
@duncaninnes ``systemd-journal-upload`` log format looks like this:
```
MESSAGE=log1
KEY=value
...

MESSAGE=log2
KEY=value
...
```

**FYI**: I did get the journal logs into ES by using [journal-gateway-gelf](https://github.com/travelping/journal-gateway-gelf) and Logstash HTTP plugin with very little finetuning. I think that, at least for now, this is the most simple and straightforward solution.
