### ISSUE TITLE
DRY lib/logstash/util/filetools.rb and rakelib/fetch.rake

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#2598]
once the `wip/bundler-move` branch is merged

**Comment by colinsurprenant** [comment]
wip/bundler-move branch is merged in #2475

**Comment by colinsurprenant** [comment]
@suyograo @purbon  unless this is in progress and/or almost finished I say we move it to post-rc1

**Comment by colinsurprenant** [comment]
looks like `filetools.rb` could just be removed, it is not used anywhere...

**Comment by ph** [comment]
We can close this, I've look at the code and we removed the files.
