### ISSUE TITLE
where is the syslog output plugin?

### ISSUE THREAD

**Issue by liycheng** [elastic/logstash#2600]
I am seeing that there is a syslog output plugin here
 http://logstash.net/docs/1.4.2/outputs/syslog
but why I can not find it in the repo?

**Comment by wiibaa** [comment]
In preparation of 1.5.0 release each plugin will become a rubygem and have therefore a separated repo under logstash-plugins, please look  at:
* https://github.com/logstash-plugins/logstash-output-syslog
* www.elasticsearch.org/blog/plugin-ecosystem-changes/

**Comment by jordansissel** [comment]
I think this question was answered based on [this comment](https://github.com/elastic/logstash/issues/2600#issuecomment-74208431). I'll close it.
