### ISSUE TITLE
Provide APIs to manage pipeline 

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2612]
Currently, whenever Logstash configuration needs to be modified, you have to edit a configuration file and restart the Logstash process. This process requires the user to either temporarily halt the pipeline or accept the fact that an interruption in processing will occur. While file-based configuration works well (especially with Puppet/Chef), it becomes increasing difficult to deploy Logstash instances. We plan to add a REST based Logstash management API to make it easier to interact with Logstash. This will allow dynamic configuration updates without the need to restart the process. To be clear, at this time we are not looking to change the existing configuration syntax. Also, file-based configuration will continue to be supported.

Important manageability functions for this end-point are:

* **reload** - restarts a paused pipeline instance with new config and instantiates all the plugins
* **add** - Add specific parts of the pipeline dynamically. For example, we may want to add a file input to follow a new file. 
* **destroy** - sends shutdown signal to all plugins and eventually stops
* **status** - include pipeline state, list of plugins, the config itself
* **pause** - pauses the pipeline
* **unpause** - resumes the paused pipeline

When interacting with the manageability APIs, care should be taken to not drop in-flight messages.

**Comment by Vineeth-Mohan** [comment]
Looking forward to this feature.

**Comment by spacediver** [comment]
+1 to live-reload. How not to lose any log events when you need to change just parsing rules?

**Comment by ph** [comment]
@spacediver the implementation of the live reload will shutdown gracefully the pipeline (we have updated all the plugins in 2.0 to support that) and will restart the pipeline with the new configuration.

The shutdown process is the following,

`Shutdown inputs -> shutdown filter -> shutdown output`

So we will stop consuming any new events, when the pipeline restart it will consume the new events again.Depending on your configuration and the inputs used you may of may not have data loss, this is really configuration specific.

**Comment by spacediver** [comment]
@ph Thanks for detailing, 

It has come to me now that the solution is quite obvious if events are posted in some queue (redis), from which consumed by logstash.

Considering reliability: could you please hint me, is it possible that logstash removes item from redis list but fails to process it?  How atomic is that? I'm thinking of scaling this among many redises and many logstashes. What if many logstashes consume the same redis instance list, will they miss events or produce duplicates on output? My ultimate goal is to build robust logspout-redis-logstash-elasticsearch setup.

Thanks,

**Comment by spuder** [comment]
@spacediver The github issues isn't the place for questions. You will find lots of helpful people ready to answer questions at https://discuss.elastic.co

**Comment by spacediver** [comment]
@spuder thanks for pointing out, let me clean this up.

**Comment by elvarb** [comment]
Will community plugins have to be upgraded to support this? If so what is the behavior if a plugins does not support it?

**Comment by suyograo** [comment]
@elvarb during the shutdown semantics work for 2.0 (https://github.com/elastic/logstash/issues/3963), we've updated almost all plugins to properly implement the new calls and reviewed the shutdown logic. This should help. There may still be some plugins which may not gracefully support these semantics (shutdown, reload, start) and we aim to tackle it one by one.

**Comment by driverpt** [comment]
@suyograo Will it work like nginx?

e.g.: 
```
service nginx reload
```

**Comment by suyograo** [comment]
@driverpt yes we just added reload in #5088

**Comment by suyograo** [comment]
Will reopen a new issue with updated details. Config reloading has shipped in 2.3

**Comment by ashishpok** [comment]
Was a new issue ever opened or has there been a concrete date for this?

**Comment by MorrieAtElastic** [comment]
A customer is inquiring about such an API; has this enhancement been scheduled?

**Comment by Allaoua9** [comment]
Any update on this ?

**Comment by kdHub** [comment]
Was this feature ever released or new issue generated to track progress?
