### ISSUE TITLE
SSLError while using tcp ssl input

### ISSUE THREAD

**Issue by maciekit** [elastic/logstash#2615]
Logstash version 1.4.2 on Ubuntu 14.04

Three scenarios:
1. rsyslog client IP 10.0.0.2 -> tls -> rsyslog server IP 10.0.0.1 -> logstash on the same server IP 10.0.0.1

This one is working just fine, logs are being forwarded by using secure connection and they are successfully received by logstash.

2. rsyslog client IP 10.0.0.2 -> logstash tcp input IP 10.0.0.1

This one is also working just fine, logs are being forwarded by using non-secure connection and they are successfully received by logstash.

3. rsyslog client IP 10.0.0.2 -> tls -> logstash tcp ssl input IP 10.0.0.1

This one is not working, I'm getting below error:
{:timestamp=>"2015-02-14T22:49:03.771000+0100", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: SSLv2Hello is disabled>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:216:in `accept'", "file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:164:in `accept'", "/opt/logstash/lib/logstash/inputs/tcp.rb:160:in `run_server'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/lib/logstash/inputs/tcp.rb:157:in `run_server'", "/opt/logstash/lib/logstash/inputs/tcp.rb:148:in `run'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:error}

I'd really like to get rid of rsyslog server and use build-in tcp input with ssl support.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-tcp/issues/11. Let's continue the discussion there! :)

**Comment by hemanath1982** [comment]
I'm getting a Similar Error, it this resolved ?

**Comment by jordansissel** [comment]
@hemanath1982 this ticket was moved https://github.com/logstash-plugins/logstash-input-tcp/issues/11
