### ISSUE TITLE
1.5.0.beta1 on AIX fails with Errno::ENOENT: ENOENT - .../vendor/bundle/jruby/1.9/gems/activesupport-4.1.8/lib/i18n

### ISSUE THREAD

**Issue by lmgray** [elastic/logstash#2616]
I've been using logstash 1.4.2 on AIX (7.1) and hoping to get 1.5.0.beta1 going but I'm hitting the same problem others have reported on Solaris, FreeBSD...

bash-4.2$  ./bin/logstash -f config/basic.conf
Errno::ENOENT: ENOENT - /home/kafka/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/activesupport-4.1.8/lib/i18n
                      file? at org/jruby/RubyFileTest.java:131
  contains_requirable_file? at /home/kafka/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/basic_specification.rb:46
                       any? at org/jruby/RubyEnumerable.java:1473
  contains_requirable_file? at /home/kafka/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/basic_specification.rb:46
                       any? at org/jruby/RubyEnumerable.java:1473
  contains_requirable_file? at /home/kafka/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/basic_specification.rb:44
      find_inactive_by_path at /home/kafka/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/specification.rb:898
                       find at org/jruby/RubyEnumerable.java:592
      find_inactive_by_path at /home/kafka/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/specification.rb:897
               try_activate at /home/kafka/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems.rb:183
                    require at /home/kafka/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:132
               load_locale! at /home/kafka/logstash-1.5.0.beta1/lib/logstash/environment.rb:111
                     (root) at /home/kafka/logstash-1.5.0.beta1/lib/logstash/runner.rb:10

I'm using the latest IBM JDK 7.1 which, again, seems fine with logstash 1.4.2
bash-4.2$ java -version
java version "1.7.0"
Java(TM) SE Runtime Environment (build pap6470_27sr2fp10-20141218_02(SR2 FP10))
IBM J9 VM (build 2.7, JRE 1.7.0 AIX ppc64-64 Compressed References 20141215_227395 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR2_20141215_1631_B227395
JIT  - tr.r13.java_20141003_74587.07
GC   - R27_Java727_SR2_20141215_1631_B227395_CMPRSS
J9CL - 20141215_227395)
JCL - 20141217_01 based on Oracle jdk7u75-b12

I've read folks suggesting this isn't a logstash problem but rather a jruby problem, but since it seems to be cropping up on multiple platforms, I'm wondering if there will be a logstash fix or at least a "blessed" workaround for logstash 1.5.0?  jruby or not, if folks using logstash can't upgrade it seems like a regression of sorts for logstash.

**Comment by joekiller** [comment]
I would try building the 1.5 branch and see if that works. They have fixed quite a bit since beta1.

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by lmgray** [comment]
logstash 1.5.0 seems to work now (using IBM Java 8)

-bash-4.3$ bin/logstash --version
io/console not supported; tty will not be manipulated
logstash 1.5.0

-bash-4.3$ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pap6480sr1-20150417_01(SR1))
IBM J9 VM (build 2.8, JRE 1.8.0 AIX ppc64-64 Compressed References 20150410_243669 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR1_20150410_1531_B243669
JIT  - tr.r14.java_20150402_88976.03
GC   - R28_Java8_SR1_20150410_1531_B243669_CMPRSS
J9CL - 20150410_243669)
JCL - 20150413_01 based on Oracle jdk8u45-b13

**Comment by untergeek** [comment]
Logstash is not officially supported on AIX or ppc.  Please see [the official support matrix(https://www.elastic.co/support/matrix).

Closing.
