### ISSUE TITLE
Add an option to json_lines codec to ignore blank lines

### ISSUE THREAD

**Issue by dimas** [elastic/logstash#2621]
When connection to logstash is established through some kind of proxy like Amazon ELB, you need to keep that connection alive byt sending something from time to time or load balancer will kill it.

For json_lines codec the most logical choice for that "keepalive" payload is a single newline character without any JSON. Unfortunately, the way json_lines if written, it will result in an event to be generated.

It would be nice to have an option for json_lines to tell it to ignore blank lines (or just ignore blank lines by default). 
(It is much more tricky to filter out these messages on a later stages because as lots of fields is added by logstash itself, the only reliable of a keepalive message is "message" set to "". But if you think of it, that indicator is not reliable at all because it is perfectly valid for a "message" to be blank and carry all the information in other fields)

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-codec-json_lines/issues/5. Let's continue the discussion there! :)
