### ISSUE TITLE
see if we can refactor & reuse rubygems classes

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#2624]
`lib/logstash/gemfile.rb` has a basic/minimal `Gemfile` parser tailored to our own needs. maybe we could actually reuse rubygems code for this?

**Comment by colinsurprenant** [comment]
as discussed in #2475

**Comment by jordansissel** [comment]
Is this something we still want to look at? The plugin manager's been reasonably stable lately, so my vote is "meh" ;P

**Comment by ph** [comment]
closing with `meh`
