### ISSUE TITLE
DRY the Gemfile handling and make sure we close the File handlers

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#2626]
there's repeated code like 

``` ruby
    raise(LogStash::PluginManager::Error, "File #{LogStash::Environment::GEMFILE_PATH} does not exist or is not writable, aborting") unless File.writable?(LogStash::Environment::GEMFILE_PATH)

    gemfile = LogStash::Gemfile.new(File.new(LogStash::Environment::GEMFILE_PATH, "r+")).load
```

related to #2475

**Comment by colinsurprenant** [comment]
also rework the File.new + closing per https://github.com/elasticsearch/logstash/pull/2475#discussion_r24667846

**Comment by colinsurprenant** [comment]
@suyograo @jsvd @ph unless this is in progress and/or almost finished I say we move it to post-rc1

**Comment by suyograo** [comment]
Fixed by https://github.com/elasticsearch/logstash/pull/2740

**Comment by jsvd** [comment]
due to https://github.com/jruby/jruby/issues/779#issuecomment-45154930, https://github.com/elasticsearch/logstash/pull/2740 needs to be reverted. for more context, check https://github.com/elasticsearch/logstash/issues/2744

**Comment by jordansissel** [comment]
Still an issue?

**Comment by ph** [comment]
This is not an issue anymore with the change to install.
