### ISSUE TITLE
bin/plugin install --development should be sticky

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#2631]
currently after doing 

``` sh
bin/plugin install --development
```

to install development dependencies, if we do any other plugin installation like

``` sh
bin/plugin install logstash-input-foobar
```

then the development dependencies are not available anymore and any rspec run will fail.

Once `bin/plugin install --development` has been executed development dependencies should always be installed/visible, at least until `bin/plugin install --no-development` is called...

**Comment by ph** [comment]
To see the actual log of the behavior look at this gist: https://gist.github.com/jsvd/983af2dad9a144c602ba

**Comment by jsvd** [comment]
And also https://gist.github.com/jsvd/dde24df1acbb34b56771

**Comment by ph** [comment]
We could keep the state in a file and minic the bundler behavior.
``
.pluginmanager/config ?
```

**Comment by colinsurprenant** [comment]
well, the state is already in the `.bundle/config`with the `BUNDLE_WITHOUT` I think we should try to use that first instead of having a separate state file...

**Comment by ph** [comment]
Because of the smalls issues we had with `bundler/config` maybe it is wiser to define our own state file? 
Also this is not a `bundler` behavior but a pluginmanager behavior.

**Comment by ph** [comment]
Let's use the:
`Bundler.settings['STICKY_DEVELOPMENT"]`

**Comment by ph** [comment]
^ previous command will save this information to the `.bundler/config`, so we can use bundler settings hash to access it.

**Comment by jordansissel** [comment]
I *hate* the sticky feature of Bundler, btw. I even go as far as forcing `rm -rf .bundle` on every bundle call:
https://github.com/jordansissel/dotfiles/blob/master/.zshrc#L51-L56

I think a sticky flag would irrittate me on bin/plugin, too.

**Comment by ph** [comment]
@jordansissel It's only affecting us the developers, 
I  am perfectly OKAY to have to do `bin/plugin install --development` after installing a new plugin? Maybe the fix is to actually document it?

**Comment by ph** [comment]
Let me bring up another related bundler subject.

Our current `plugin install` actually create a `.bundler/config` file, I guess you would be in favor of not persisting anything to disk?

**Comment by ph** [comment]
@jordansissel You were [concerned](https://github.com/elastic/logstash/issues/2631#issuecomment-76284738) to add `sticky development` feature for the dev dependencies. This problem isn't blocking our development but we as the developers we are running into this issue often.

I want to know if it's still something we want to close before 1.5 GA?

**Comment by colinsurprenant** [comment]
@jordansissel @ph ok, so, the goal here is to be able to install development dependencies at some point  and have these development dependencies also installed for any new plugins that get installed. 

instead of a sticky/stateful feature, why not use the development environment option `LOGSTASH_ENV` and then rely on `LogStash::Environment.development?` in the plugin manager to *do the right thing*?

**Comment by jordansissel** [comment]
@colin I am in favor of anything that is not stateful. In my opinion, env vars are exactly equivalent to flags (FOO=bar vs --foo=bar), so if you're going to the trouble of setting env, you might as well just have a flag. I added support a while ago for clamp to support environment variables, if you wish to use that here: http://www.rubydoc.info/gems/clamp#Environment_variable_support

**Comment by colinsurprenant** [comment]
@jordansissel ^^ wrong **colin** :P

**Comment by jordansissel** [comment]
lol, my bad.

**Comment by colinsurprenant** [comment]
@jordansissel yeah sure, I think we can support both too. support for `LOGSTASH_ENV` is [already in master](https://github.com/elastic/logstash/blob/master/lib/logstash/environment.rb#L77-L91) so I think we can just use that for now-now ?

**Comment by jordansissel** [comment]
https://github.com/elastic/logstash/blob/master/lib/logstash/environment.rb#L54

The env var is LS_ENV but the constant name is LOGSTASH_ENV. Confusing.

**Comment by colinsurprenant** [comment]
agree, let's clean that up. for the benefit of this PR, are we in agreement to move forward with the env var? @ph @jordansissel ?

**Comment by jordansissel** [comment]
+1 on allowing an env var for folks who like persistent settings :)

**Comment by ph** [comment]
persist all the things @jordansissel  :dancer:
