### ISSUE TITLE
Logstash doesn't ship tail of my log file until I terminate logstash process

### ISSUE THREAD

**Issue by fandrei** [elastic/logstash#2638]
My config:
```
input {
  file {
    path => "....../logs/*.in"
    start_position =>  "beginning"
    sincedb_path => "....../logs/sincedb"
    discover_interval => 1
  }
}

output {
  file {
    flush_interval => 1
    path => "......./logs/log.out"
  }
}
```

I write a bunch of lines to an input file; the most of these lines are shipped to the output successfully, however a few tailing lines aren't shipped for indefinite time (at least 5 minutes); they only get shipped when I stop the logstash process. I'm using logstash 1.4.2 on Windows 7.
Any ideas why this can happen?

**Comment by KarlikB** [comment]
Thre problem is caused by file output plugin that does not flush qickly incoming data.
Workaround is set flush_interval to 0.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-file/issues/12. Let's continue the discussion there! :)
