### ISSUE TITLE
Symlink causes issues

### ISSUE THREAD

**Issue by wojons** [elastic/logstash#2648]
When i symlink the /etc/logstash/conf.d or the files in it i get the following error.

```{:timestamp=>"2015-02-19T03:22:43.450000+0000", :message=>"You may be interested in the '--configtest' flag which you can\nuse to validate logstash's configuration before you choose\nto restart a running system."}
{:timestamp=>"2015-02-19T03:22:48.044000+0000", :message=>"Error: Expected one of #, input, filter, output at line 1, column 1 (byte 1) after "}
```

If i hard link or copy the files over it works fine i am using links because its using a file in a repo

**Comment by Poohblah** [comment]
Make sure that the logstash user has permissions to list the contents of the conf.d directory and read the conf files.

**Comment by suyograo** [comment]
Fixed in 2.x
