### ISSUE TITLE
Some of the plugins have their vendored files in their gem

### ISSUE THREAD

**Issue by ph** [elastic/logstash#2649]
Currently the gem that requires vendored files doesn't use the `file-dependencies` plugin, because I have released a version of the gem by mistake with the disabled install hook. It doesnt impact the current RC1 because the gems with the vendored files already include the files..

See the `collectd`, the `useragent` gem and the geoip gem.

**Comment by jordansissel** [comment]
@ph is this still an issue given all the issues filed from this ticket?
