### ISSUE TITLE
Adding an unpublished plugin to logstash-plugins breaks test:install-all

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#2656]
Example with the latest logstash-output-logentries plugin:

```
% rake test:install-all
Resolving dependencies...
Plugin not found, aborting
Error: Bundler::GemNotFound, Could not find gem 'logstash-output-logentries (>= 0) java' in the gems available on this machine.
Installation aborted
rake aborted!
```

The workaround is adding the plugin to the skip list in `rakelib/default_plugins.rake`

**Comment by purbon** [comment]
Yeah! we should make this more resilient, but for now I guess is good if we somehow catch this exception and just log something happened.

I guess @colinsurprenant used the same approach as the old code, fetching all plugins and then filtering the ones we don't want ;-)

**Comment by purbon** [comment]
Actually breaking the jenkins jobs for that with an error like:

```
asticsearch-ec2, logstash-patterns-core, logstash-mixin-aws, logstash-input-couchdb_changes, logstash-filter-metaevent, logstash-filter-zeromq, logstash-codec-s3plain, logstash-codec-cloudfront, logstash-codec-gzip_lines, logstash-codec-avro, logstash-input-heartbeat, logstash-filter-tld, logstash-filter-oui, logstash-output-logentries
Plugin not found, aborting
Installation aborted
rake aborted!

/home/jenkins/workspace/logstash_integration_all_plugins/rakelib/plugin.rake:7:in `install_plugins'
/home/jenkins/workspace/logstash_integration_all_plugins/rakelib/plugin.rake:55:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => test:install-all => plugin:install-all
(See full trace by running task with --trace)
rake aborted!
no such file to load -- rspec/core/runner
org/jruby/RubyKernel.java:1071:in `require'
/home/jenkins/workspace/logstash_integration_all_plugins/rakelib/test.rake:5:in `run_rspec'
/home/jenkins/workspace/logstash_integration_all_plugins/rakelib/test.rake:19:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => test:plugins
(See full trace by running task with --trace)
Build step 'Execute shell' marked build as failure
```

**Comment by jsvd** [comment]
that `Plugin not found, aborting` should include the missing plugin name

**Comment by purbon** [comment]
yap, working now on that, so we can have a green jenkins ;-)

**Comment by ph** [comment]
We could add a .yml file at the root of the plugin repository with an option to skip the build.. Similar to what travis is doing.

**Comment by purbon** [comment]
@ph actually this is not a bad idea, we could add some nice information that would help the build a lot. This was also one of my ideas to track this problem on.

**Comment by purbon** [comment]
For now I just added some code in here to check if the plugin has been released or not by doing a search at rubygems. When we make our testing infrastructure more complex we can simple add an config file to the repos as commented here.

Going to close this as #3021 fix this issue.
