### ISSUE TITLE
netflow codec and "Cannot find Serializer for class" issue

### ISSUE THREAD

**Issue by tomarch** [elastic/logstash#2667]
i use lastest logstash 1.5.0 beta1 and elasticsearch 1.4.4
I have an issue when using netflow codec

here's my logstash config :  https://gist.github.com/tomarch/d824d5781a725cf68a10

I've got an error when i use elasticsearch or file output: Got error to send bulk of actions to elasticsearch server at localhost : Cannot find Serializer for class: org.jruby.RubyObject {:level=>:error}

The complete error log for the elasticsearch output : https://gist.github.com/tomarch/3f16b02100717681242d

The stdout seems fine : https://gist.github.com/tomarch/dc3f0561b473d0542dcd

**Comment by tomarch** [comment]
Can i do more debug for helping ?
Do i have to post this issue to the netflow codec section ?
Thx.

**Comment by tomarch** [comment]
I've finaly find the cause of this issue, it was the "protocol => http" from the elastiscsearch output.
Removing this line made it work fine.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-codec-netflow/issues/13. Let's continue the discussion there! :)
