### ISSUE TITLE
Logstash + Lumberjack input hangs with lots of threads that are timing out.

### ISSUE THREAD

**Issue by austinhquinn** [elastic/logstash#2672]
occurred on logstash 1.5.0 beta1 and 1.4.2 (upgraded in an attempt to see if the issue was fixed)
elasticsearch 1.4.4
kibana 4

Logstash + Lumberjack input hangs with lots of threads that are timing out.
Below is a lot of information gathered during two occasions when log stash just hung. I've had this occur many many times over the last week or so.

seeing a bunch of these in elasticsearch logs:
[2015-02-23 18:48:14,903][DEBUG][action.search.type       ] [Leonard Samson] [logstash-2015.02.21][1], node[aRNlLembTQuU3kYN5wASqQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@11f10037] lastShard [true]
org.elasticsearch.search.SearchParseException: [logstash-2015.02.21][1]: from[-1],size[478]: Parse Failure [Failed to parse source [{"size":478,"sort":{"@timestamp":"desc"},"query":{"filtered":{"query":{"query_string":{"query":"\"Error reaching API server\"","analyze_wildcard":true}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":1424112494676,"lte":1424717294676}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}}},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"3h","pre_zone":"-08:00","pre_zone_adjust_large_interval":true,"min_doc_count":0,"extended_bounds":{"min":1424112494676,"max":1424717294676}}}},"fields":["*","_source"],"script_fields":{},"fielddata_fields":["@timestamp"]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:543)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:515)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.SearchParseException: [logstash-2015.02.21][1]: from[-1],size[478]: Parse Failure [No mapping found for [@timestamp] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:210)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:141)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:96)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	... 9 more

strace out of logstash(this seems to go in a loop):
[pid 41028] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41025] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41018] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41026] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41022] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41027] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41021] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41015] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41014] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41012] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41020] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41019] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41011] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41023] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41010] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41009] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41013] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41024] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41016] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41008] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41007] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41006] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41005] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41004] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41002] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41001] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41000] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40999] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40998] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40997] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40996] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40995] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40994] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40993] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40992] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40991] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40990] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40989] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40988] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40986] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41003] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40985] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40983] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40982] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40981] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40980] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40859] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 41028] epoll_wait(198,  <unfinished ...>
[pid 41027] epoll_wait(195,  <unfinished ...>
[pid 41026] epoll_wait(192,  <unfinished ...>
[pid 41025] epoll_wait(189,  <unfinished ...>
[pid 41024] epoll_wait(186,  <unfinished ...>
[pid 41023] epoll_wait(183,  <unfinished ...>
[pid 41022] epoll_wait(180,  <unfinished ...>
[pid 41021] epoll_wait(177,  <unfinished ...>
[pid 41020] epoll_wait(174,  <unfinished ...>
[pid 41019] epoll_wait(171,  <unfinished ...>
[pid 41018] epoll_wait(168,  <unfinished ...>
[pid 41016] epoll_wait(162,  <unfinished ...>
[pid 41015] epoll_wait(159,  <unfinished ...>
[pid 41014] epoll_wait(156,  <unfinished ...>
[pid 41013] epoll_wait(153,  <unfinished ...>
[pid 41012] epoll_wait(150,  <unfinished ...>
[pid 41011] epoll_wait(147,  <unfinished ...>
[pid 41010] epoll_wait(144,  <unfinished ...>
[pid 41009] epoll_wait(141,  <unfinished ...>
[pid 41008] epoll_wait(138,  <unfinished ...>
[pid 41007] epoll_wait(135,  <unfinished ...>
[pid 41006] epoll_wait(132,  <unfinished ...>
[pid 41005] epoll_wait(129,  <unfinished ...>
[pid 41004] epoll_wait(126,  <unfinished ...>
[pid 41003] epoll_wait(123,  <unfinished ...>
[pid 41002] epoll_wait(120,  <unfinished ...>
[pid 41001] epoll_wait(117,  <unfinished ...>
[pid 41000] epoll_wait(114,  <unfinished ...>
[pid 40999] epoll_wait(111,  <unfinished ...>
[pid 40998] epoll_wait(108,  <unfinished ...>
[pid 40997] epoll_wait(105,  <unfinished ...>
[pid 40996] epoll_wait(102,  <unfinished ...>
[pid 40995] epoll_wait(99,  <unfinished ...>
[pid 40994] epoll_wait(96,  <unfinished ...>
[pid 40993] epoll_wait(93,  <unfinished ...>
[pid 40992] epoll_wait(89,  <unfinished ...>
[pid 40991] epoll_wait(86,  <unfinished ...>
[pid 40990] epoll_wait(83,  <unfinished ...>
[pid 40989] epoll_wait(80,  <unfinished ...>
[pid 40988] epoll_wait(77,  <unfinished ...>
[pid 40987] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40986] epoll_wait(71,  <unfinished ...>
[pid 40985] epoll_wait(68,  <unfinished ...>
[pid 40983] epoll_wait(62,  <unfinished ...>
[pid 40982] epoll_wait(59,  <unfinished ...>
[pid 40981] epoll_wait(56,  <unfinished ...>
[pid 40980] epoll_wait(46,  <unfinished ...>
[pid 40859] futex(0x7f439000a928, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 40987] epoll_wait(74,  <unfinished ...>
[pid 40859] <... futex resumed> )       = 0
[pid 40859] futex(0x7f439000a954, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 674144548}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 559062568}, ffffffff <unfinished ...>
[pid 41038] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 41038] futex(0x7f4288002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 41038] futex(0x7f4288002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 634611798}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 609508570}, ffffffff <unfinished ...>
[pid 41017] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 41017] epoll_wait(165,  <unfinished ...>
[pid 40984] <... epoll_wait resumed> {}, 4096, 500) = 0
[pid 40984] epoll_wait(65,  <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 659923178}, ffffffff <unfinished ...>
[pid 41069] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 41069] futex(0x7f4318ff1d28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 41069] futex(0x7f4318ff1d54, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840926, 629425680}, ffffffff <unfinished ...>
[pid 40972] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40972] futex(0x7f4318790728, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40972] futex(0x7f4318790754, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 834177439}, ffffffff <unfinished ...>
[pid 41038] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 41038] futex(0x7f4288002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 41038] futex(0x7f4288002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 734849853}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 710175736}, ffffffff <unfinished ...>
[pid 40929] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40929] futex(0x7f439043ff28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40929] futex(0x7f439043ff54, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 862039923}, ffffffff <unfinished ...>
[pid 40859] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40859] futex(0x7f439000a928, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40859] futex(0x7f439000a954, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 874304588}, ffffffff <unfinished ...>
[pid 40878] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40878] futex(0x7f4390188828, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40878] futex(0x7f4390188854, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840926, 697161500}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 760503406}, ffffffff <unfinished ...>
[pid 41038] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 41038] futex(0x7f4288002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 41038] futex(0x7f4288002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 835303062}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 810812434}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 861145629}, ffffffff <unfinished ...>
[pid 40972] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40972] futex(0x7f4318790728, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40972] futex(0x7f4318790754, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840926, 34358367}, ffffffff <unfinished ...>
[pid 41038] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 41038] futex(0x7f4288002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 41038] futex(0x7f4288002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 934623314}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 911481182}, ffffffff <unfinished ...>
[pid 40929] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40929] futex(0x7f439043ff28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40929] futex(0x7f439043ff54, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840926, 62429987}, ffffffff <unfinished ...>
[pid 40859] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40859] futex(0x7f439000a928, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40859] futex(0x7f439000a954, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840926, 74627453}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 961802491}, ffffffff <unfinished ...>
[pid 40977] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40977] futex(0x7f4318844cb8, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40977] stat("/config/scripts", 0x7f430f7f2410) = -1 ENOENT (No such file or directory)
[pid 40977] futex(0x7f4318844ce4, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840925, 994824601}, ffffffff <unfinished ...>
[pid 41038] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 41038] futex(0x7f4288002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 41038] futex(0x7f4288002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840926, 34898212}, ffffffff <unfinished ...>
[pid 40888] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 40888] futex(0x7f43901cd328, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 40888] futex(0x7f43901cd354, FUTEX_WAIT_BITSET_PRIVATE, 1, {7840926, 12200353}, ffffffff <unfinished ...>

nginx logfile entry that logstash hung on:
#.#.#.# - - [20/Feb/2015:16:52:02 +0000] "GET /internal/r//publisher/content?ab_test_identifier=1&content_params=%7B%22content_type_id%22%3A+4%2C+%22content_data%22%3A+%7B%22type%22%3A+%22promo%22%7D%2C+%22actions%22%3A+%5B%5D%2C+%22priority%22%3A+1%2C+%22state%22%3A+%22live%22%2C+%22content_type%22%3A+%22interstitial_ad%22%7D&request_type=publisher&meta=%7B%22lifetime_duration%22%3A+284321%2C+%22app_secret%22%3A+%22ee81b26b945a475e8936b94b32dfaa2c%22%2C+%22height%22%3A+1920%2C+%22hardware%22%3A+%22SM-G900T%22%2C+%22metadata_request%22%3A+false%2C+%22lifetime_sessions%22%3A+4408%2C+%22clientip%22%3A+%2271.131.129.106%22%2C+%22skip_content%22%3A+%5B%5D%2C+%22opt_out%22%3A+0%2C+%22platform%22%3A+%22android%22%2C+%22skip_child_lock%22%3A+null%2C+%22token%22%3A+%22667619682ad6445e845a36105c2b334e%22%2C+%22languages%22%3A+%22en%22%2C+%22idiom%22%3A+2%2C+%22sdk_version%22%3A+%223.0.3%22%2C+%22allow_ecpm_shuffle%22%3A+null%2C+%22current_session_duration%22%3A+23%2C+%22app_version%22%3A+%224.1.3%22%2C+%22test_content%22%3A+false%2C+%22preload%22%3A+%221%22%2C+%22impression_id%22%3A+null%2C+%22scale%22%3A+3.0%2C+%22status_bar_height%22%3A+null%2C+%22country%22%3A+%22USA%22%2C+%22identifiers%22%3A+%7B%22ifa%22%3A+%22082375fc-aec2-4029-8aa0-8fb002068028%22%7D%2C+%22skip_rules%22%3A+false%2C+%22custom_args%22%3A+null%2C+%22connection%22%3A+%22wifi%22%2C+%22raw_languages%22%3A+%5B%22en_US%22%2C+%22en%22%5D%2C+%22user_agent%22%3A+%22Mozilla%2F5.0+%28Linux%3B+U%3B+Android+4.4%3B+en%3B+SM-G900T+Build%2FIMM76D%29+AppleWebKit%2F534.30+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Mobile+Safari%2F534.30%22%2C+%22os%22%3A+%2219%22%2C+%22width%22%3A+1080%2C+%22plugin%22%3A+%22android%22%7D&ifa=082375fc-aec2-4029-8aa0-8fb002068028&sid=286941620849653521&game_id=174084&content_id=1489484&app_os=android&test_device=False HTTP/1.1" 200 3914 "-" "-" "127.0.0.1, #.#.#.#" 0.311

from logstash console out:

{
        "message" => "#.#.#.# - - [20/Feb/2015:16:52:02 +0000] \"GET /internal/r/publisher/content?ab_test_identifier=1&content_params=%7B%22content_type_id%22%3A+4%2C+%22content_data%22%3A+%7B%22type%22%3A+%22promo%22%7D%2C+%22actions%22%3A+%5B%5D%2C+%22priority%22%3A+1%2C+%22state%22%3A+%22live%22%2C+%22content_type%22%3A+%22interstitial_ad%22%7D&request_type=publisher&meta=%7B%22lifetime_duration%22%3A+284321%2C+%22app_secret%22%3A+%22ee81b26b945a475e8936b94b32dfaa2c%22%2C+%22height%22%3A+1920%2C+%22hardware%22%3A+%22SM-G900T%22%2C+%22metadata_request%22%3A+false%2C+%22lifetime_sessions%22%3A+4408%2C+%22clientip%22%3A+%2271.131.129.106%22%2C+%22skip_content%22%3A+%5B%5D%2C+%22opt_out%22%3A+0%2C+%22platform%22%3A+%22android%22%2C+%22skip_child_lock%22%3A+null%2C+%22token%22%3A+%22667619682ad6445e845a36105c2b334e%22%2C+%22languages%22%3A+%22en%22%2C+%22idiom%22%3A+2%2C+%22sdk_version%22%3A+%223.0.3%22%2C+%22allow_ecpm_shuffle%22%3A+null%2C+%22current_session_duration%22%3A+23%2C+%22app_version%22%3A+%224.1.3%22%2C+%22test_content%22%3A+false%2C+%22preload%22%3A+%221%22%2C+%22impression_id%22%3A+null%2C+%22scale%22%3A+3.0%2C+%22status_bar_height%22%3A+null%2C+%22country%22%3A+%22USA%22%2C+%22identifiers%22%3A+%7B%22ifa%22%3A+%22082375fc-aec2-4029-8aa0-8fb002068028%22%7D%2C+%22skip_rules%22%3A+false%2C+%22custom_args%22%3A+null%2C+%22connection%22%3A+%22wifi%22%2C+%22raw_languages%22%3A+%5B%22en_US%22%2C+%22en%22%5D%2C+%22user_agent%22%3A+%22Mozilla%2F5.0+%28Linux%3B+U%3B+Android+4.4%3B+en%3B+SM-G900T+Build%2FIMM76D%29+AppleWebKit%2F534.30+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Mobile+Safari%2F534.30%22%2C+%22os%22%3A+%2219%22%2C+%22width%22%3A+1080%2C+%22plugin%22%3A+%22android%22%7D&ifa=082375fc-aec2-4029-8aa0-8fb002068028&sid=286941620849653521&game_id=174084&content_id=1489484&app_os=android&test_device=False HTTP/1.1\" 200 3914 \"-\" \"-\" \"127.0.0.1, #.#.#.#\" 0.311",
       "@version" => "1",
     "@timestamp" => "2015-02-20T22:24:43.943Z",
           "type" => "nginx-access",
           "file" => "/var/log/nginx/client_api.log",
           "host" => "#####.prod.########.com",
         "offset" => "221090",
       "clientip" => "#.#.#.#",
          "ident" => "-",
           "auth" => "-",
      "timestamp" => "20/Feb/2015:16:52:02 +0000",
           "verb" => "GET",
        "request" => "/internal/r/publisher/content?ab_test_identifier=1&content_params=%7B%22content_type_id%22%3A+4%2C+%22content_data%22%3A+%7B%22type%22%3A+%22promo%22%7D%2C+%22actions%22%3A+%5B%5D%2C+%22priority%22%3A+1%2C+%22stat

logstash config:
# cat /opt/logstash/conf.d/logstash.conf 
input {
lumberjack {
  port => 5043
  type => "logs"
  ssl_certificate => "/opt/logstash/ssl/logstash-forwarder.crt"
  ssl_key => "/opt/logstash/ssl/logstash-forwarder.key"
}

  file {
    type => "syslog"
    path => [ "/var/log/*.log", "/var/log/messages", "/var/log/syslog" ]
    start_position => "beginning"
  }
}
filter {
  if [type] == "haproxy" {
    grok {
      pattern => "%{HAPROXYHTTP}"
    }
  }

  if [type] == "apache" {
    grok {
      pattern => "%{COMBINEDAPACHELOG}"
    }
  }
  if [type] == "nginx-access" {
    grok {
      match => { "message" => "%{NGINXACCESS}" }
    }
  }
 
}
 
output {
  stdout { 
    codec => rubydebug
  }
elasticsearch { host => "10.#.#.#" }
}

**Comment by lmorfitt** [comment]
Do you have a load balancer between your LSF and your logstash instance? I have had similar issues when a load balancer was in use on logstash 1.4.2 and LSF.

**Comment by austinhquinn** [comment]
I did not.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/19. Let's continue the discussion there! :)
