### ISSUE TITLE
trouble parsing auth.log

### ISSUE THREAD

**Issue by jan-r0374778** [elastic/logstash#2683]
I get the following error
<pre>
Failed to flush outgoing items {:outgoing_count=>1, :exception=># NameError: no method 'type' for arguments (org.jruby.RubyArray) on Java::OrgElasticsearchActionIndex::IndexRequest , :backtrace=>["/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:225:in `build_request'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:205:in `bulk'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:204:in `bulk'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch.rb:315:in `flush'", "/opt/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash-1.4.2/lib/logstash/outputs/elasticsearch.rb:311:in `receive'", "/opt/logstash-1.4.2/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):130:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:266:in `output'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:225:in `outputworker'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn}</pre>

go figure what it means, but there is apparently something wrong with my grok, despite having it checked using the online debuggers
AUTH_LOG_TS %{MONTH:month}%{SPACE}%{MONTHDAY:day} %{HOUR:hour}:%{MINUTE:min}:%{SECOND:sec}
AUTH_LOG_TYPE %{NOTSPACE:type}\[%{INT:pid}\]|%{NOTSPACE:type}:
AUTH_LOGGING %{AUTH_LOG_TS} %{HOST:hostname} %{AUTH_LOG_TYPE}%{SPACE}%{GREEDYDATA:info}

the problem is located in AUTH_LOG_TYPE as far as trouble shooting goes, however, I can't find anything wrong. Suggestions are welcome in order to fix this. If this is a bug, please fix it.

things I'd like to parse from it:
- time
- hostname
- process (name of and, if applicable, pid)
- raw data (message after pid)

Logfile example
Feb 24 22:57:04 Server sudo: pam_unix(sudo:session): session closed for user root
Feb 24 23:03:16 Server sudo:     dude : TTY=pts/0 ; PWD=/home/dude/lsconf ; USER=root ; COMMAND=/usr/bin/nano /var/log/auth.log
Feb 24 23:03:16 Server sudo: pam_unix(sudo:session): session opened for user root by dude(uid=0)
Feb 24 23:05:48 Server sudo: pam_unix(sudo:session): session closed for user root
Feb 24 23:09:01 Server CRON[1954]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 24 23:09:01 Server CRON[1954]: pam_unix(cron:session): session closed for user root
Feb 24 23:17:01 Server CRON[1966]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 24 23:17:01 Server CRON[1966]: pam_unix(cron:session): session closed for user root
Feb 24 23:39:01 Server CRON[2046]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 24 23:39:01 Server CRON[2046]: pam_unix(cron:session): session closed for user root
Feb 24 23:47:10 Server sshd[2207]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.200.251  user=dude
Feb 24 23:47:12 Server sshd[2207]: Failed password for dude from 192.168.200.251 port 51242 ssh2
Feb 24 23:47:16 Server sshd[2207]: Connection closed by 192.168.200.251 [preauth]
Feb 24 23:55:21 Server sshd[2286]: Failed password for dude from 192.168.200.251 port 51272 ssh2
Feb 24 23:55:25 Server sshd[2286]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.200.251  user=dude
Feb 24 23:55:27 Server sshd[2286]: Failed password for dude from 192.168.200.251 port 51272 ssh2
Feb 24 23:55:35 Server sshd[2286]: Connection closed by 192.168.200.251 [preauth]
Feb 24 23:59:09 Server sshd[2359]: Failed password for dude from 192.168.200.251 port 51276 ssh2

**Comment by NoumanSaleem** [comment]
You can start with the build in `%{SYSLOGBASE2}`

**Comment by suyograo** [comment]
please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
