### ISSUE TITLE
Minor error in 1.4.2 Getting Started Docs

### ISSUE THREAD

**Issue by AirOnSkin** [elastic/logstash#2687]
http://logstash.net/docs/1.4.2/tutorials/getting-started-with-logstash

There's a small error. The text contains:
*but it’s easy enough to watch both the access_log and the error_log (actually, any file matching *log)*

And right below in the code block:
```
input {
  file {
    path => "/tmp/*_log"
...
```

The configuration (from the code block) would only match logs ending with **_log** (with an underscore) and not **log** like the text suggests.

A bit further down in the text as well: *and other random files which end with "log"*

**Comment by andrewvc** [comment]
Thanks for reporting this @AirOnSkin ! We'll pull this fix in soon :)

**Comment by jordansissel** [comment]
Deployed @andrewvc's fix to logstash.net

```
% curl -s http://logstash.net/docs/1.4.2/tutorials/getting-started-with-logstash | grep 'any file matching'
(actually, any file matching <em>*_log</em>), by changing one line in the above
```
