### ISSUE TITLE
logstash-core working as an standalone gem

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2704]
Hi,
  during some tests and fix of our beloved Jenkins, I encounter with the requirement by some gems (aka the filter-grok) to use the patterns directory and this raised a question.

Do we want the logstash-core gem to work as an standalone gem? I mean if someone require the logstash-core gem, for example a plugin, is he expected to have directories like the patterns one? or are the artifacts delivered with logstash the ones who are supposed to have them?

My take is more on the side of allowing logstash-core to work as an standalone gem, so including the patterns directory on it, but probably making sure to have this directory on the root of the importing project and not in the gemset path.

What do you think is the best way to go?

**Comment by suyograo** [comment]
@colinsurprenant @jordansissel @ph @talevy discussed this and reached consensus that logstash-core cannot be used as a standalone gem as-is. Its intention always was to be used as a dependency for the plugins. If this changes in the future, we can revisit this, but definitely not in the 1.5.0 timeframe.

@purbon let me know if you have concerns regarding this.
