### ISSUE TITLE
Allow prune to remove nil values

### ISSUE THREAD

**Issue by nellicus** [elastic/logstash#2707]
allow to easily and dynamically remove nil values

e.g. remove all fields containing nil

```
prune{ blacklist_values => [ "\S+", nil] }
```

**Comment by talevy** [comment]
Closing in favor of tracking this in the plugin repo

re: https://github.com/logstash-plugins/logstash-filter-prune/pull/10

**Comment by magnusbaeck** [comment]
> Closing in favor of tracking this in the plugin repo

Okay, but note that that issue covers nil field _names_ but this issue is for filtering field _values_.
