### ISSUE TITLE
Unable to passthrough file

### ISSUE THREAD

**Issue by alvassin** [elastic/logstash#2710]
For debugging purposes (when writing new config) i want to make logfile passthrough to see it's messages.

Stdin/stdout works fine, i can see my messages are handled:
```
input { stdin { } } 
output { stdout { } }
```

Problem comes, when i want to input file:
```
input {
  file {
    path => [ "/home/logstash/xunit.json" ]
    sincedb_path => "/dev/null"
  }
}

output {
  stdout {}
}
```

When i run config above with --verbose argument, i see following lines, then process hangs:
```
Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Registering file input {:path=>["/home/logstash/xunit.json"], :level=>:info}
Pipeline started {:level=>:info}
```

What's wrong? Why i do not see incoming messages from file?

**Comment by jordansissel** [comment]
What do you see that indicates a problem?

Logstash by default will treat files as live streams. This means it starts following unknown files (like your xunit.json, at first observation) at the end of the file. If no new data enters your file, logstash will see no new data.

If you are trying to process a whole file that is fixed and not changing, you probably want to set `start_position => beginning`

**Comment by masterzion** [comment]
I have a similar problem. The file plugin process only one time and stop.
I also tried removing the params start_position and  sincedb_path.

config
-----
input {
   file {
      type => "apache-access"
      path => ["/var/log/apache2/access.log", "/var/log/apache2/access.log.1"]
      start_position => "beginning"
      sincedb_path => "/dev/null"
      debug => true
   }

   file {
      type => "apache-error"
      path => "/var/log/apache2/error.log"
      start_position => "beginning"
      sincedb_path => "/dev/null"
      debug => true
   }

}
-----
command line: 
-----
/opt/logstash/bin/logstash -f /etc/logstash/conf.d  --debug
-----

**Comment by jordansissel** [comment]
Is this still an issue?
