### ISSUE TITLE
Possible to install different version of the same plugin

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2727]
The plugin manager does not take into account then version when installing a plugin, making possible to end up with version "0.1.3" and "0.1.4" of the same plugin installed.

The expected behaviour, for me, would be to keep the latest installed version of the plugin.

Example:

```
./bin/plugin list
No plugins found
➜  logstash git:(fix/install_old_plugins) ✗ DEBUG=true bin/plugin install --version "0.1.3" logstash-input-wmi
Validating logstash-input-wmi-0.1.3
Installing logstash-input-wmi
➜  logstash git:(fix/install_old_plugins) ✗ DEBUG=true bin/plugin install --version "0.1.4" logstash-input-wmi
Validating logstash-input-wmi-0.1.4
Installing logstash-input-wmi
➜  logstash git:(fix/install_old_plugins) ✗ ./bin/plugin list --verbose 
logstash-input-wmi (0.1.4)
logstash-input-wmi (0.1.3)
```

In my opinion the semantics of the commands can be confusing, because in this case we've two version of the same plugin installed, running the last one (but no command to tell that).

I guess bundler will remove for us many of the possible dependency issues, but we might still want to keep our dependencies clean.

**Comment by suyograo** [comment]
Not relevant or no user requests for this.
