### ISSUE TITLE
Bundler interface to the user.

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2728]
Hi,
  as we're now modeling our plugin behaviour versus bundler we should decide how do we want to handle the interaction with it. For now we're following the same notation as the one in ```Bundler.settings``` (1),  with things like the without option used to exclude groups.

I would like us to think if we like negated apis or positive ones? Bundler is also having some positive interface, for example the one used by ```Bundler.setup``` (2) when activating groups.

In my case I always found more nice to express what I want, and not what I don't want (as you never know what can he not being excluded).

(1) http://www.rubydoc.info/github/carlhuda/bundler/Bundler/Settings
(2) https://github.com/bundler/bundler/blob/master/lib/bundler.rb#L114

Looking forward to know what do you think on that!

**Comment by suyograo** [comment]
I think this is not a priority at this time. Closing
