### ISSUE TITLE
Logs being sent to a closed index cause logstash to lock up

### ISSUE THREAD

**Issue by efontana** [elastic/logstash#2745]
I moved this issue to here (from elasticsearch repo).    When sending logs (via logstash) if the log is sent to a closed index, there is no good error message reported and it causes logstash to lock up, which in turn causes redis to start filling up.   The real issue here is there is no reasonable error message indicating this other than:

"Non-OK response code from Elasticsearch: 404"

There is no mention of "Which Elasticsearch" (I have multiple outputs) and the real issue, what index is causing the problem, we had a queue backup and there were logs being sent to a closed index, the solution is to re-open that index, but you can't figure out which one to re-open.  Please enhance this message.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/140. Let's continue the discussion there! :)
