### ISSUE TITLE
logstash filters - add field with custom shell script/action

### ISSUE THREAD

**Issue by spacecwoboy** [elastic/logstash#2753]
Can logstash add a field to the log, by way of calling an O/S command or script?  (bash, lua, etc?)

Simplistic Example:
OriginalLog -- [1.TIME] - [2.SOURCE_IP] - [3.DESTINATION_IP] - [4.SOME_TEXT]

Desire to accomplish:
- [ ] A command
> curl http://server/lookup/[4.SOME_TEXT] | grep "tag" > [5.RESPONSE]

- [ ] A script
> #!/bin/bash/
> cat wordlist.txt | grep "[4.SOME_ARBITRARY_TEXT]" > [5.RESPONSE]

--
UpdatedLog --[1.TIME] - [2.SOURCE_IP] - [3.DESTINATION_IP] - [4.SOME_TEXT] - [5.RESPONSE]

**Comment by jordansissel** [comment]
Not at this time, but you could write a custom filter in ruby to achieve this. 

Closing this in favor of https://github.com/elastic/logstash/issues/2528 since I think it's the same request.
