### ISSUE TITLE
Jenkins: Create all plugins tests for master 

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2771]
We have a test for published plugins, but we also need to create one for tip of the master

1. Add a task to install the gems with `gem test:install-all-master`
2. Add a task to install the gems with `gem test:install-default-master`
3. Create a task `rake test:plugins-master` to use the checked repository.

**Comment by purbon** [comment]
Hi,
  there is an all plugins test for master http://build-eu-00.elasticsearch.org/view/LS%20Integration/job/logstash_integration_all_plugins/ 

how can we adapt this to fill this?
