### ISSUE TITLE
Generated packages include spec files

### ISSUE THREAD

**Issue by electrical** [elastic/logstash#2776]
Generated packages currently still include the spec directory. Should not need those.

**Comment by ph** [comment]
We were shipping the `spec/` directory in the logstash 1.4.2 packages (deb, rpm, tar), if we are removing the folder we should also hide the `bin/logstash rspec` command. If we are removing them, we should update the developer workflow to with: *to develop a plugin and run tests you need a fresh copy from master.

**Comment by purbon** [comment]
+1 on not removing test from the page (for now), but we should discuss what is the approach we aim to take. 

In guess source packages use to include the tests, but binaries (also debs, rpms, etc..) should not have them. Might be a good idea to just keep the test when necessary and make packages that will go to deployment (only) smaller.

**Comment by electrical** [comment]
Production packages != development environment. I still strongly feel that anything dev wise should not be in the created packages.
If people want to do development they will need to do a git clone.

**Comment by jordansissel** [comment]
I have always shipped the tests with the releases for as long as I can
remember with logstash.

It's not for development, but for testing. The idea is that if a user's
platform has issues, the test suite could hep find it.

-Jordan

**Comment by purbon** [comment]
agree with you @jordansissel that is how I see test when I compile a project.

**Comment by jordansissel** [comment]
If we decide to remove the tests, then we'll have to strip down lib/logstash/runner during a build, also, since it provides `bin/logstash rspec`, `bin/logstash pry`, etc, which are useful for testing.

**Comment by ph** [comment]
We are currently removing the tests for the plugins but not the tests for the core.

**Comment by colinsurprenant** [comment]
we currently cannot run test/specs in 1.5.rcX as the development dependencies are not included in the package, see #3229. 

Personally I am not convinced we should include tests and dev dependencies in a release package. Has it been really useful in supporting users?

**Comment by colinsurprenant** [comment]
note that if we include the `spec` dir in logstash-core, in a release package we can just do `bin/plugin install --development` and all dev dependencies will be installed. 

maybe the specs could be added as a logstash-core-specs gem as a development dependency? or we just include the `spec/` dir in logstash-core.

**Comment by purbon** [comment]
I see a point of not having the test included in the packages, actually I don't see many people running core test anyway. But then I don't see the benefit of maintaining a logstash-core-spec gem.

**Comment by jordansissel** [comment]
My original intent of including tests with logstash was for two reasons:
1) Folks with bugs could run the main logstash test suite and hopefully more easily find a failing case.
2) Folks could write tests to validate the behavior of their own logstash configurations (filters, etc)

I can't recall any instances where the first reason was validated. I think I can forget about the first one.

For the second one, I know there are some (unknown population size) users who use `bin/logstash rspec` to run their own test suites for their production use cases (filter configuration, etc). I think the ability for users to write tests to assert correctness of their event filters is very important, but I am open to exploring new ways to achieve that. If we cannot provide the old behavior, then, as a workaround, we can document how users can achieve this with 1.5.x even if that way is different than it was in 1.4.x

**Comment by colinsurprenant** [comment]
@jordansissel live example in #3229

**Comment by jordansissel** [comment]
@colinsurprenant +1 on this example. We can update the docs to reflect this and I think things will be OK.
