### ISSUE TITLE
Permissions issue on the `.bundler/config`

### ISSUE THREAD

**Issue by ph** [elastic/logstash#2777]
This was reported by @electrical on hipchat.

1. Install logstash from any packages (this is done as root)
2. Start Logstash as **root**, this will create a `.bundle/config` with root permission.
3. Start Logstash as **logstash** user, this will fail because it will try to write to the `bundler/config` and the user doesn't have the right permission.

A possible fix might be this PR https://github.com/elasticsearch/logstash/pull/2701 to have a stateless bundler, This PR wasn't extensively tested.

**Comment by electrical** [comment]
I did find that the logstash user can read it and starts up but its unable to take any action with the plugin manager. ( list, install, etc )

**Comment by suyograo** [comment]
We discussed to add an empty `.bundler/config` file (during packaging) owned by `logstash` user. This would solve the permission issue in deb, rpm packages
