### ISSUE TITLE
"Logstash Package Acceptance" is false positive

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2782]
http://build-eu-00.elasticsearch.org/view/LS%201.5/job/Logstash_Package_Acceptance_1.5/ is currently green. It shouldn't be green, at minimum, because of #2780

**Comment by suyograo** [comment]
After discussions with @electrical, package acceptance tests were never intended to be a release acceptance test. Today, these tests install an artifact, check init scripts, run with a basic config and shuts down LS. We'll need more for a release acceptance test, but this test can be kept as-is.

**Comment by suyograo** [comment]
https://github.com/elastic/logstash/issues/2852
