### ISSUE TITLE
logstash 1.5 RC1 - date filter not matching CET

### ISSUE THREAD

**Issue by dougmcclure** [elastic/logstash#2784]
This filter works fine for EST. Looks like 'z' should match any time zone represented as three letters or fully spelled out according to http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html.

Here's my filter:

date {
	match => [ "timestampOrig", "MM/dd/YY HH:mm:ss:SSS z" ]
} #end date

Error:

Failed parsing date from field {:field=>"timestampOrig", :value=>"03/03/15 19:24:37:839 CET", :exception=>java.lang.IllegalArgumentException: Invalid format: "03/03/15 19:24:37:839 CET" is malformed at "CET", :level=>:warn}

Tks!

**Comment by wiibaa** [comment]
From the DateTimeFormat, it is stated that **time zone names cannot be parsed**, digging for more details Joda embed only a [limited set of names](https://github.com/JodaOrg/joda-time/commit/14863a51230b3d44201646dbc1ce5d7f6bb97a33)
One strong solution would be to allow in logstash to configure the DefaultTimeZoneNames Maps but this is not implemented.
A workaround is to use the timezone config of the date filter and remove the mutate your string to remove the CET.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-date/issues/21. Let's continue the discussion there! :)
