### ISSUE TITLE
network bottleneck,need gzip transfer to redis or to kafka

### ISSUE THREAD

**Issue by xiaohelong** [elastic/logstash#2790]
my situation is to collect lots of nodes which are distributed across the country,so ,the network flow will be the bottleneck,I tried test my log file copressing,10:1 ration. I can't found plugin in logstash to transfer gzip log to redis or kafka,anybody know this?
I found flume has this feature,so ,I will try replace ELK  stack agent's part.

**Comment by abcfy2** [comment]
+1. Need gzip or other compress method for network transport.

**Comment by suyograo** [comment]
Kafka input/output already supports compression to and from the brokers
