### ISSUE TITLE
convert feature of mutate filter doesnot work while refering to the field values using %

### ISSUE THREAD

**Issue by VarunMaheshwari** [elastic/logstash#2797]
example:
 "message" => "SolrTime,20"

my configuration looks like following:

filter {
	grok{
                match => ["message","%{WORD:component},%{INT:time:int}"]
        }
        mutate{
                add_field => [ "%{component}", "%{time}" ]
        }
 mutate{
              	convert => ["%{component}", "integer"]
		remove_field => ["component","time"]
        }
}

my output should be something like:
        "SolrTime" => 20,
         ...
But the output I am getting is 
     "SolrTime" => "20",
      ...

that is type conversion didn't happen for %{component}, i.e. SolrTime field should have an integer value instead of String.

Is it a bug or is this feature not supported ?

**Comment by untergeek** [comment]
This is a bit of a stab in the dark, but try using:

```
mutate{
  convert => ["%{[component]}", "integer"]
  remove_field => ["component","time"]
}
```

The problem is that mutate convert usually just receives a field name.  I'm not sure that it would correctly interpolate the field reference here.

**Comment by VarunMaheshwari** [comment]
Hi Aaron,

that didn't solved the problem, the output that I am getting is 

{
        ...
        "message" => "SolrTime,20",
        "SolrTime" => "20",
             "%{" => {
        "component" => {}
    }
}

But instead I can see one more field in the output and that is
"%{" => {
        "component" => {}
    }

**Comment by VarunMaheshwari** [comment]
Hi Aaron,

that didn't solved the problem, the output that I am getting now is

{
...




*"message" => "SolrTime,20","SolrTime" => "20","%{" => {"component" => {}}*
}

and also I can see one more field in the output and that is


*"%{" => {"component" => {}}*

**Comment by untergeek** [comment]
Indeed.  It appears that for the present, you cannot use field reference format in a `convert` statement.

If you named the field instead of trying to refer to it, it would work as specified.

We can perhaps talk about making this into a feature request.

**Comment by VarunMaheshwari** [comment]
That would be a great.

Am also wondering if we can do that using grok(i don't know much about grok though), 

for example,  lets say 
message => "SolrTime,20"
and I want my output to be "SolrTime" => 20   (value is an integer)

If I use:
filter{
      grok{
                match => ["message","%{WORD:component},%{INT:time:int}"]
        } 
}

my output will be
"component"=>"SolrTime"
"time"=>20

but if it's possible using grok to refer to a field, like
match => ["message","%{WORD:component},%{INT:%{component}:int}"]

so that my output should be

"component"=>"SolrTime"
"SolrTime"=>20

**Comment by untergeek** [comment]
My apologies. It should work this way. You should be referencing the field, rather than the field value. 

```
mutate{
  convert => [ [component], "integer"]
  remove_field => ["component","time"]
}
```

**Comment by VarunMaheshwari** [comment]
I am getting the following error with that:

Exception in filterworker {"exception"=>#<NoMethodError: undefined method `split' for ["component"]:Array>, "backtrace"=>["/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:19:in `parse'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:15:in `get'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:59:in `store_path'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:55:in `lookup'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:34:in `get'", "/usr/local/lib/logstash-1.4.2/lib/logstash/event.rb:127:in `[]'", "/usr/local/lib/logstash-1.4.2/lib/logstash/event.rb:170:in `include?'", "/usr/local/lib/logstash-1.4.2/lib/logstash/filters/mutate.rb:256:in `convert'", "org/jruby/RubyHash.java:1339:in `each'", "/usr/local/lib/logstash-1.4.2/lib/logstash/filters/mutate.rb:255:in `convert'", "/usr/local/lib/logstash-1.4.2/lib/logstash/filters/mutate.rb:209:in `filter'", "(eval):60:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/usr/local/lib/logstash-1.4.2/lib/logstash/pipeline.rb:262:in `filter'", "/usr/local/lib/logstash-1.4.2/lib/logstash/pipeline.rb:203:in `filterworker'", "/usr/local/lib/logstash-1.4.2/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}

**Comment by untergeek** [comment]
Try nesting it inside a conditional.  It's presently configured to work on ALL events, whether they have that field or not.  If the field named `component` doesn't exist, you'd get that error.

```
if [component] {
  mutate{
    convert => [ [component], "integer"]
    remove_field => ["component","time"]
  }
}
```

**Comment by VarunMaheshwari** [comment]
the field component will always be there in my case
but still I have tried that and again i am getting the following error

Exception in filterworker {"exception"=>#<NoMethodError: undefined method `split' for ["component"]:Array>, "backtrace"=>["/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:19:in `parse'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:15:in `get'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:59:in `store_path'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:55:in `lookup'", "/usr/local/lib/logstash-1.4.2/lib/logstash/util/accessors.rb:34:in `get'", "/usr/local/lib/logstash-1.4.2/lib/logstash/event.rb:127:in `[]'", "/usr/local/lib/logstash-1.4.2/lib/logstash/event.rb:170:in `include?'", "/usr/local/lib/logstash-1.4.2/lib/logstash/filters/mutate.rb:256:in `convert'", "org/jruby/RubyHash.java:1339:in `each'", "/usr/local/lib/logstash-1.4.2/lib/logstash/filters/mutate.rb:255:in `convert'", "/usr/local/lib/logstash-1.4.2/lib/logstash/filters/mutate.rb:209:in `filter'", "(eval):58:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/usr/local/lib/logstash-1.4.2/lib/logstash/pipeline.rb:262:in `filter'", "/usr/local/lib/logstash-1.4.2/lib/logstash/pipeline.rb:203:in `filterworker'", "/usr/local/lib/logstash-1.4.2/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-mutate/issues/30. Let's continue the discussion there! :)

**Comment by Faheemul** [comment]
when we are converting some values to integer, if value is null then we see its value as 0, which gives wrong information in case where for some values we get values as 0.

EX:
if message is SignalStrength=
then we see #SignalStrength	  	0 as KV pair
we expect blank vlaue.

since in some message we get SignalStrength=0
then we cannot differentiate between if the value is real 0 or it is created by logtsatsh as 0 when there is no data in value.
