### ISSUE TITLE
[LOGSTASH/TCP]: A broken socket worker advertising low TCP receive window?

### ISSUE THREAD

**Issue by chiriaev** [elastic/logstash#2800]
Guys, Hi. I am using log-stash "1.4.2" on OEL 6.3 I am forwarding JSON via NXLOG from ~500 servers. (i.e.: a mix of Unix and Windows) I recently discovered that some connections
were in a very strange state. The TCP receive window advertised to the log forwarder was extremely and consistently low from 12 to 84 bytes. I am taking just two examples here. I know for a fact that these used to work fine and became "stuck" after several days of activity. 

Please note that this is not widespread. Most of the inbound connections are
working well and advertise proper buffer lengths. Please also note that a log-stash re-start fixes the problem, in the way that all the NX clients resume activity.

Any thoughts? Has it been reported before?

Thanks in advance.

Regards, Andrei

P.S.: the issue has only been spotted between a Windows client, NXLOG, and a UNIX log-stash server so far. The log-stash cluster, two servers, is fronted with a F5/BIGIP VIP.

**Comment by chiriaev** [comment]
Guys, Hi. Please note that I can also observer symptoms of "https://github.com/elasticsearch/logstash/issues/1509" Regards, Andrei

**Comment by jordansissel** [comment]
@chiriaev to my knowledge, logstash doesn't set the window size on its sockets and leaves that decision up to the operating system's network stack.

**Comment by suyograo** [comment]
We will not be able to support this at LS level. Sorry
