### ISSUE TITLE
Remove the elasticsearch_http plugins

### ISSUE THREAD

**Issue by ph** [elastic/logstash#2801]
We have deprecated the `elasticsearch_http` plugin in 1.5 it was replaced with the elasticsearch output using the http protocol. To do the deprecation we have created a dummy plugin, with the 2.0 release we should remove this plugin.

The deprecation was done in https://github.com/elasticsearch/logstash/issues/1757

**Comment by suyograo** [comment]
Plugin was removed from default plugins list.
