### ISSUE TITLE
File input appears to stop reading from NFS when rsyncing files

### ISSUE THREAD

**Issue by ScottChapman** [elastic/logstash#2803]
So, I have a file input clause, and logstash is actively reading files from an NFS share.

Then rsync comes along and updates files, and my logstash just stops.

I've watched the files that are getting updated, and no new files, and no inode changes. Just a log file increases in size.

I can do a tail -f on the file and that runs just fine which rsync-ing.

Any ideas?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/38. Let's continue the discussion there! :)
