### ISSUE TITLE
Implement more meaningful error messages for users

### ISSUE THREAD

**Issue by qwerty55** [elastic/logstash#2804]
Please read the comments from the following for an example:
https://github.com/elastic/logstash/issues/1903

If logstash is meant to be used by non-ruby programmers, then logstash should utilize configuration validation, connectivity testing, and begin-rescue blocks that output meaningful error messages for users. Giving nothing more than a stack trace to the user should be unacceptable if the error is something readily detectable such as an incorrect connectivity related attribute (hostname, password, username) or an accidentally unquoted string placed in the configuration file.

**Comment by nopejpg** [comment]
Also experienced this issue; the error should be caught and human readable connection information output.

**Comment by ph** [comment]
I will be closing this we should take care into consideration when doing any review.
