### ISSUE TITLE
Additional format support for dictionary_path within "translate" filter

### ISSUE THREAD

**Issue by landonix** [elastic/logstash#2805]
Currently when using the translate filter with a dictionary_path a yaml formatted file is required. I would like to make a request for supporting a json formatted file.

**Comment by landonix** [comment]
It would also be great to support a json array for dictionaries that contain more than a single value type.

**Comment by untergeek** [comment]
Thanks for the suggestion!  Can you please migrate this request to the appropriate plugin repository?

https://github.com/logstash-plugins/logstash-filter-translate

Thanks!

**Comment by landonix** [comment]
New issue created for logstash-plugins/logstash-filter-translate! This issue is closed. Thank you.
