### ISSUE TITLE
performance drop since v1.5.0

### ISSUE THREAD

**Issue by fandrei** [elastic/logstash#2807]
I've developed a logstash plugin to filter data using Java code; performance of this plugin reduced by ~30% since logstash v1.5.0. What might be the reason?

**Comment by jsvd** [comment]
Could you share the plugin so we have a better way of debugging this?
What does the configuration look like? Can you replace the plugin with another stock plugin and see if this still happens?

**Comment by fandrei** [comment]
@jsvd, https://github.com/fandrei/logstash-filter-java
Sample config:
```
  java { code => 'data.put("test", "some test val"); return true;' }
```
The same performance drop happens even if I remove all filters and keep the empty `filter {}` section.

**Comment by wiibaa** [comment]
@fandrei did you measure logstash global throughput only at the moment or did you already investigate if it was related to a specific input or output ?

**Comment by fandrei** [comment]
@wiibaa, I've measured average throughput over period of several minutes, using file input/output plugins:

```
input {
  file {
    path => "MY_PATH/*.in"
    start_position =>  "beginning"
    sincedb_path => "MY_PATH/sincedb"
    discover_interval => 1
  }
}

filter {
} 

output {
  file {
    flush_interval => 1
    path => "MY_PATH/log.out"
  }
}

```

**Comment by wiibaa** [comment]
@fandrei can you post a few details of your env please. OS ? JVM ?

**Comment by fandrei** [comment]
@wiibaa, Windows 7 x64 SP1, Java 8 update 40 x86.

**Comment by wiibaa** [comment]
@fandrei HAHA ! Using file input with wildcard on windows has important bug on windows.
Did you check that your output file is complete in terms of line number for 1.4. 
It would most probably not be the case. But 1.5 should be good.
So it would not really be a performance drop, just a strong difference on processed events

**Comment by fandrei** [comment]
@wiibaa, I did check. All records are present in the output file both on 1.4 and 1.5 (excluding a few trailing records, that aren't shipped on both).

PS What kind of bug?

**Comment by wiibaa** [comment]
@fandrei https://github.com/elastic/logstash/issues/1902 and https://github.com/jordansissel/ruby-filewatch/issues/39

**Comment by fandrei** [comment]
@wiibaa, no - that's unrelated to my test.

**Comment by wiibaa** [comment]
@fandrei so I missed it :( . therefore there is a change in either the input of output file plugin that is impacting. Can you try using the stdout output in your test to quickly check if the input file is the culprit between 1.4 and 1.5

**Comment by fandrei** [comment]
@wiibaa, it seems stdin/stdout is not affected by this performance drop. I'll do more tests to re-check this.
Btw, why logstash outputs json data with the config above? It should use "plain" by default, shouldn't it?

**Comment by wiibaa** [comment]
@fandrei what I had in mind was to try out file input + stdout output to check if the file input major changes for windows support was the root cause of your observation. Can you please have a go.

About stdout output, plain/line is still the default for the plugin, so if you do `bin\logstash -e 'output { stdout{}}'` the output will still be one line timestamp + host + message
However if you run simply `bin\logstash -e ''`, the default output will be set to **"output { stdout { codec => rubydebug } }"** and output ruby hashes with **key => value**, that's not valid json.
Is it what you are seeing ?

**Comment by fandrei** [comment]
@wiibaa,

1. no - I mean the config above with file output. It outputs JSON despite the default codec is plain, according to the docs. It seems it outputs JSON even if I set `codec => plain` explicitly.

2. I've switched my test to use both stdin and stdout, and what I see is that logstash performance drop with empty filter has disappeared in this case; however, my Java plugin still performs much slower with logstash 1.5.0 rather then 1.4.2

**Comment by wiibaa** [comment]
@fandrei file output does not respect codec yet, and still use the `message_format` options so as specified in the doc

>  If this setting is omitted, the full json representation of the
   event will be written as a single line.

**Comment by fandrei** [comment]
@wiibaa, I see. What about performance drop when executing my plugin? Any ideas what might be the reason?

**Comment by wiibaa** [comment]
@fandrei supposing it is a pure Jruby-Java related issue, my guess would be look at invokedynamics setting and try to set it off as mentionned in https://github.com/jruby/jruby/wiki/PerformanceTuning#enabling-invokedynamic

**Comment by wiibaa** [comment]
if you can conclude to a jruby to java perf degradation between the different jruby version from Logstash 1.4 to 1.5, then you need some strong jruby expertise that I do not have, the best would be to narrow down a test case preformance in calling java from jruby and report directly to jruby folks.

**Comment by fandrei** [comment]
@wiibaa, how do I pass this option through logstash.bat?

**Comment by wiibaa** [comment]
Taking http://stackoverflow.com/a/24570419 as an example you have to add it to the JAVA_OPTS inside logstash.bat for 1.4 but for 1.5 you can set JRUBY_OPTS before calling bin\logstash

**Comment by fandrei** [comment]
@wiibaa, unfortunately changing the invokedynamic option doesn't  solve this problem.

**Comment by colinsurprenant** [comment]
@fandrei please check my last comment on #2859 - I'd really appreciate if you could verify if that may be the cause of your performance regression.

**Comment by colinsurprenant** [comment]
@fandrei if its not related to the `JAVA_OPTS` then we can give a try to my latest performance changes in #2869

**Comment by fandrei** [comment]
@colinsurprenant, do I understand correctly that I need to set USE_JRUBY=1 env variable for my logstash 1.4.2 test to make it behave in the same way as logstash 1.5.0 ?

**Comment by fandrei** [comment]
@colinsurprenant, wrt this pull request - how do I setup dependencies and compile checked out copy of logstash source code?

**Comment by colinsurprenant** [comment]
@fandrei if you have a local JRuby installed, yes, use `USE_JRUBY=1 bin/logstash ...`  for force logstash to use its vendored JRuby so that we can compare apples to apples, using the same JVM options on both setups.

**Comment by colinsurprenant** [comment]
@fandrei to run the fix/perf_regression branch:
```sh
git clone git@github.com:elastic/logstash.git
cd logstash
git checkout -b fix/perf_regression origin/fix/perf_regression
rake bootstap
rake plugin:install-default
```

Are you running JRuby locally?

**Comment by fandrei** [comment]
@colinsurprenant, not sure if I understand how this works fully. I don't have a local JRuby installation, and setting USE_JRUBY for both tests. Is this enough to make them use the same JRuby options?

**Comment by fandrei** [comment]
It seems logstash 1.5 rc3 solves this problem.

**Comment by purbon** [comment]
Cool @fandrei!! do you think we can close this issue by now?

**Comment by fandrei** [comment]
@purbon, agreed
