### ISSUE TITLE
Converting to float

### ISSUE THREAD

**Issue by silviupanaite** [elastic/logstash#2808]
I'm new to logstash, and I'm trying to write my own patterns (with not much success). 

 My issue is that I want to convert an field from heroku input which has something like "6ms", as input, to a value, I converted that field to and float (no error promoted when I test the config!). When I try to plot it in histogram it doesn't work, obviously, shouldn't it at least throw something in the logs (No we can't do that).   

 Can anyone help me understand how I can extract a value from a field or a message?

Thanks.

**Comment by jsvd** [comment]
So you want to extract a number from the "6ms" string and transform it to float? You need to do something like this:

```
filter {
  grok {
    match => [ 'message', '%{NUMBER:ms:float}ms' ]
  }
}
```

testing this with the string "6ms" gives you: 
```
{
       "message" => "6ms",
      "@version" => "1",
    "@timestamp" => "2015-03-11T21:02:43.825Z",
          "host" => "Joaos-MacBook-Pro.local",
      "sequence" => 0,
            "ms" => 6.0
}
```

you can then use the ms field to plot the histogram.

**Comment by silviupanaite** [comment]
So, it does convert them to float. But I had to wait for a long time to finish the operation.
