### ISSUE TITLE
Set proxy on logstash client - exception

### ISSUE THREAD

**Issue by gilcoh33** [elastic/logstash#2810]
Hi Guys,

I'm trying to set a logstash to transfer my documents via a proxy (using windows client)

I've added the below JVM set to logstash.bat:

SET LS_JAVA_OPTS=-Dhttp.proxyHost=10.0.0.5 -Dhttp.proxyPort=3128

I can see the incoming connection to the proxy but I'm getting the below exception on the client:

?[33mFailed to flush outgoing items {:outgoing_count=>1, :exception=>#<SocketError: gethostbyname: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubySocket.java:286:in `gethostbyname'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/dns/dns.rb:13:in`resolve'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/dns.rb:38:in `resolve'", "org/jruby/RubyArray.java:1613:in`each'", "org/jruby/RubyEnumerable.java:865:in `inject'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/dns.rb:37:in`resolve'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:137:in `connect'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:406:in`connect'", "org/jruby/RubyProc.java:271:in `call'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/pool.rb:48:in`fetch'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:403:in `connect'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:319:in`execute'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:217:in `post!'", "c:/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:106:in`bulk_ftw'", "c:/logstash-1.4.2/lib/logstash/outputs/elasticsearch/protocol.rb:80:in `bulk'", "c:/logstash-1.4.2/lib/logstash/outputs/elasticsearch.rb:315:in`flush'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in`each'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "c:/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:159:in`buffer_receive'", "c:/logstash-1.4.2/lib/logstash/outputs/elasticsearch.rb:311:in `receive'", "c:/logstash-1.4.2/lib/logstash/outputs/base.rb:86:in`handle'", "(eval):17:in `initialize'", "org/jruby/RubyProc.java:271:in`call'", "c:/logstash-1.4.2/lib/logstash/pipelinerb:266:in `output'", "c:/logstash-1.4.2/lib/logstash/pipeline.rb:225:in`outputworker'", "c:/logstash-1.4.2/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn}?[0m

Can anyone help me solve this? Or tell me if I miss something?

Thanks

**Comment by lancehunt** [comment]
Any luck here?  I need the same.

**Comment by gilcoh33** [comment]
Nope..

**Comment by otisg** [comment]
@gilcoh33 @lancehunt my feeling is Logstash doesn't actually support going through the proxy... or maybe you had some luck with this recently?

**Comment by gilcoh33** [comment]
No luck at all :-/

On Wed, Jul 1, 2015 at 11:03 PM, Otis Gospodnetic <notifications@github.com>
wrote:

> @gilcoh33 <https://github.com/gilcoh33> @lancehunt
> <https://github.com/lancehunt> my feeling is Logstash doesn't actually
> support going through the proxy... or maybe you had some luck with this
> recently?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/2810#issuecomment-117808705>.
>



-- 
*Gil Cohen*
gilcohen84@gmail.com

**Comment by ph** [comment]
Still an issue see https://github.com/elastic/logstash/issues/6619
