### ISSUE TITLE
Issues in specifying path of indexer file in logstash command

### ISSUE THREAD

**Issue by ashusheva** [elastic/logstash#2811]
I tried to specify a path to the indexer file location when running the logstash.bat command. The problem is that the path contains a space and when I try to run logstash, I get an exception that no such command found. So far i have tried the following commands and none of them work:-

C:\Program Files\Logstash\bin>logstash.bat agent -f "C:\Latest Configs\Logstash\indexer.conf"
C:\Program Files\Logstash\bin>logstash.bat agent -f "C:\Latest Configs\Logstash\indexer.conf"
C:\Program Files\Logstash\bin>logstash.bat agent -f 'C:\Latest Configs\Logstash\indexer.conf'
C:\Program Files\Logstash\bin>logstash.bat agent -f "C:/Latest Configs/Logstash/indexer.conf"

Everytime, I get an error like "No such command as Configs" or "Configs=defs not defined at this point".

**Comment by jordansissel** [comment]
I think this is a known issue for Windows that we will fix.

**Comment by suyograo** [comment]
Fixed in 2.2
