### ISSUE TITLE
syslog input not following RFC3164

### ISSUE THREAD

**Issue by fajabird** [elastic/logstash#2812]
RFC3164 states the following:

1. "The HEADER part contains a timestamp and an indication of the
   hostname or IP address of the device"
2. "The MSG part has two fields known as the TAG field and the CONTENT
   field." 
3. "Any non-alphanumeric character will terminate the TAG field and will be
   assumed to be the starting character of the CONTENT field."

But logstash's syslog-input expects the TAG-Field to be terminated by a ":" which will not match some syslog-conform messages.

I manually modified the file "logstash/patterns/linux-syslog" to become the TAG optional:

OLD:
SYSLOGBASE2 (?:%{SYSLOGTIMESTAMP:timestamp}|%{TIMESTAMP_ISO8601:timestamp8601}) (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}:

NEW:
SYSLOGBASE2 (?:%{SYSLOGTIMESTAMP:timestamp}|%{TIMESTAMP_ISO8601:timestamp8601}) (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource}( %{SYSLOGPROG}:)?

Could this become available in the upstream?

**Comment by fajabird** [comment]
Example of a RSA-Appliance log which currently is not recognized by the syslog-input:

Mar 12 13:19:38 123.123.123.123 2015-03-12 13:19:38,494, , audit.runtime.com.rsa.ims.authn.impl.AuthenticationBrokerImpl, INFO, 8051e4291f4764991caf722e6b80783d,,,,,,,,,,,,,,,,,,,,

While this manually modified version matches:

Mar 12 13:19:38 153.100.71.31 TAG: 2015-03-12 13:19:38,494, , audit.runtime.com.rsa.ims.authn.impl.AuthenticationBrokerImpl, INFO, 8051e4291f4764991caf722e6b80783d,,,,,,,,,,,,,,,,,,,,

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-syslog/issues/14. Let's continue the discussion there! :)
