### ISSUE TITLE
Logstash 1.5.0.rc2-1 fails to run filters

### ISSUE THREAD

**Issue by fajabird** [elastic/logstash#2813]
I have updated my logstash 1.4.2 installation to 1.5 RC2 and now my grok filter is not beeing triggered anymore? Hints?

My configuration is slip up in multiple files unter /etc/logstash/conf.d   (ubuntu)
-rw-r--r-- 1 root root   54 Mar 12 16:16 filter_grok.conf
-rw-r--r-- 1 root root  866 Mar 12 16:09 input_syslog.conf
-rw-r--r-- 1 root root  808 Oct  1 15:54 input_tcp.conf
-rw-r--r-- 1 root root 1206 Sep 15 11:05 output_elasticsearch.conf
drwxr-xr-x 2 root root 4096 Mar 12 15:49 patterns

**Comment by ph** [comment]
Logstash should pickup all the files at start and compile it into a runtime
function.  Is your input and output configuration triggered?

**Comment by fajabird** [comment]
Yes, both are triggered. Only my grok filter ( maybe all filters)  is/are not triggered. Are there commands to verify the chain?

**Comment by fajabird** [comment]
I have found something that changed within conditional expressions I am using to trigger GROK:

This worked until 1.4.2:
if [host] in ["10.0.0.1"] { grok { .... } }

This does not work anymore and has to be changed to (without the [] brackets):
if [host] in "10.0.0.1" { grok { .... } }
OR:
if [host] == "10.0.0.1" { grok { .... } }

BUG?
Now my grok filter work!

**Comment by wiibaa** [comment]
@fajabird yes it is a bug https://github.com/elastic/logstash/issues/2737

**Comment by fajabird** [comment]
BTW: which is more efficient?

grok{ 
  match => [ "message", "(?:%{NETSCREEN}|%{NETSCREEN2}|%{NETSCREEN3})" ]
} 

OR:

grok {
  match => [
          "message", "%{NETSCREEN}",
          "message", "%{NETSCREEN2}",
          "message", "%{NETSCREEN3}"
        ]
}

**Comment by jordansissel** [comment]
@fajabird I suspect your first example may be more efficient, but it's easier to test that than it is to guess, I think. Throw a few thousand log samples at it with the file input and check throughput?
