### ISSUE TITLE
Add Routing-Paramter to Elasticsearch-Output

### ISSUE THREAD

**Issue by german23** [elastic/logstash#2814]
Hey guys,

it would be good if the elasticsearch(and the elasticsearch_http) output would support a elasticsearch-routing option. This option would allow more efficient storage of different ES-documents and thus would speed up queries.

It was discussed about 1,5 years ago:
https://logstash.jira.com/browse/LOGSTASH-1211

but the it either was forgotten or could not be implemented.

Any ideas on this?

**Comment by wiibaa** [comment]
Hello @german23 , is on-going work in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/65 suiting your needs? 
Also please pay attention that each plugin has now its own github repo so issues should be moved/reported there. Thanks

**Comment by german23** [comment]
Hi,
this should be sufficient for our needs.

thanks for clarifying this.
