### ISSUE TITLE
Can't sent message in plugin http in format json

### ISSUE THREAD

**Issue by Marfas1983** [elastic/logstash#2815]
I verify in version 1.4.2 of logstash that is not possible to sent message in format json in plugin http, because is not possible put double-quote.
for resolve this problem i put one WA in code of plugin http.rb that if in message existe the string '\"' i replace them to char '"'. in this form is possible to send message in format json to elasticsearch .

the code that i put in plugin is:
code present:

```
elsif @format == "message"
#puts msg
    request.body = event.sprintf(@message)
```

new code:

```
elsif @format == "message"
match = '\"'
msg=@message
    while(msg.include?(match))
        msg.sub!(match, '"')
    end
#puts msg
    request.body = event.sprintf(msg)
```

**Comment by wiibaa** [comment]
Just 2 questions: 
1- if you target elasticsearch over http, why not use ?
````
output {
  elasticsearch {
    protocol => "http"
  }
}
````
2- if you want to send your event as json with the http output, why not use ?
````
output {
  http {
    format => "json"
  }
}

**Comment by Marfas1983** [comment]
Because if you put in destiny a old version of elasticsearch e plugin d'ont work. i tried with elastic serach version 0.44

**Comment by wiibaa** [comment]
sorry but as far as I known 0.44 is not an elasticsearch version and all 1.x releases support the same http API so should work with logstash

**Comment by Marfas1983** [comment]
is true but if you do a simple test in your API http 
i want send a message to elasticsearch like that 

{
"TESTE1" : "teste"
}

i tried everithing that i found in google and d'ont work

for example:
http {
       		format=>"message"
       		content_type =>"application/json"
      	 	http_method=>"post"
       		message=>"{\"TESTE1\":\"teste\"}}"
    	}

the elasticsearch d'ont like because receive the same message that i send... and d'ont receive like 
{"TESTE1" : "teste"}

if put the message like message=>"{"TESTE1":"teste"}}" the logstash send error.

**Comment by Marfas1983** [comment]
other problem with plugin elasticsearch was when you want create a hierarqui like this
{
"Father": "F",
"Details":{ "child1": "C1", "child2": "C2"}
}

**Comment by wiibaa** [comment]
Sorry for the question, but I feel like that you are looking for a simple Elasticsearch client , did you have a look to the listing on http://www.elastic.co/guide/
Logstash is a pipeline to read - transfrom and load content where you should not think in term of string messages but in term of events to benefits from Logstash powers.
What kind of input are you experimenting with at the moment ?

**Comment by Marfas1983** [comment]
The input is log4j plugin, that receive information off operations in jboss and put them in files. the logstash receive, transform and put in elasticsearch.
For have the same information beetween two or more jboss, i decide customize the message that send to elasticsearch, for have for example sucess ou insucess of operation and if insucess, what parameters receive and what error appear.

understand?

**Comment by Marfas1983** [comment]
i want use log4j but i have limitation with my version off jboss (4.2.2) and log4j (1.2.17), and messages that i send with SocketAppender d'ont work very well, this is a reason that i choise the plugin file.

**Comment by wiibaa** [comment]
does your file already contains json formatted lines ?

**Comment by Marfas1983** [comment]
no.

**Comment by wiibaa** [comment]
ok.
so from the file input logstash create one event for each line read from the file with an initial structure mainly `"message" => "some line of log"`. This event structure can be manipule in the filter chain (adding tag, adding field) and when the format suits you this event should be sent to the output.
That's how the available outputs in logstash are working, that's why I do not understand why you focus on writting the json by hand in the output.

**Comment by Marfas1983** [comment]
I decide http output, because i have a old version of elasticsearch, but if one day i decide replace elasticsearch to another, the messages in json will be going to consumed and present in the same form.

i think that problem is very simple to explain:
i want see in elasticsearch this message: "JBOSS1|outResponde=200&reqid=4000|12345|bacd|" in this format:
{
    "abcd": "JBOSS",
    "result": "200",
    "details": {
        "reqid": 4000,
        "client": "12345",
        "info": "bacd"
    }
}
how you do?

**Comment by wiibaa** [comment]
using a filter config like this
````
filter {
 grok {
    match => { "message" => "%{WORD:abcd}\|outResponde=%{NUMBER:result}&reqid=%{NUMBER:[details][reqid]}\|%{NUMBER:[details][client]}|%{DATA:[details][info]}"}
  }
}
````
will populate the event like this
````
{
       "message" => "JBOSS1|outResponde=200&reqid=4000|12345|bacd|",
      "@version" => "1",
    "@timestamp" => "2015-03-13T16:22:27.273Z",
          "host" => "localhost",
          "abcd" => "JBOSS1",
        "result" => "200",
       "details" => {
         "reqid" => "4000",
        "client" => "12345"
    }
}
````
then it's up to you to use an output as I already explained before

**Comment by Marfas1983** [comment]
how add_field a field like [details][info]?
in this form 
grok{
add_field{[details][info] => "4000"}
}
or for have this field i need to do a match?
thank's a lot for your help.

**Comment by wiibaa** [comment]
grok filter purpose is to extract content from a string, I just made a typo in my previous comment (now it's correct) 
if you have constants value you can indeed use add_field in the same filter or a mutate
````
mutate {
  add_field => { "[details][info]" => "4000"}
}
````

**Comment by Marfas1983** [comment]
ok, one more question for finish this thread

i need put http output plugin then my message will be like these??
http{
format => "json"
message=>"%{abcd}, %{result}, %{details}{reqid},%{details}{info}"
}

**Comment by Marfas1983** [comment]
thank's a lot for your help.

**Comment by wiibaa** [comment]
with the http output, If you use `format => json` the complete event as build by logstash will be converted to json and sent, if you want to add/remove fields from the event, you must do it in the filters. 

If you want to send a custom string, you must use `format => message` and specify the message template string in the configuration using %{}. for example:
´´´´
message=>"%{abcd}, %{result}, %{[details][reqid]},%{[details][info]}"
´´´´
The syntax for referencing nested fields is explained here http://www.elastic.co/guide/en/logstash/current/configuration.html#logstash-config-field-references

**Comment by Marfas1983** [comment]
hi wiiba i need your help...

i have this string 00000000-0000-0000-0000-000000000000 and i want put one hash to mutate this string. can you help me?

**Comment by wiibaa** [comment]
@Marfas1983 can you please add an example of initial event structure and expected event structure after "mutation"

**Comment by Marfas1983** [comment]
i have this log for iis:
2015-02-25 00:00:06 172.16.2.125 GET /XXXX/AreaYYY.ashx guid=00000000-0000-0000-0000-000000000000&mode=subAreas&areaId=594&parentAreaId=98&mirrorColor=255-105-177-191&startIndex=0&itemCount=8&direction= 80 - 179.97.156.51 Microsoft-IPTV-Client/1.6+(Windows+CE+5.0;+Mediaroom+2.3.28669.155;+MPF+1.1;+MPF+3.0;+PACE;+IPH8000) 200 0 0 397

and i want to send this information to the google analytics.

i want send cid=00000000-0000-0000-0000-000000000000        // Anonymous Client ID

but i d'ont want sent this information like i see but put one hash to mutate.

**Comment by wiibaa** [comment]
1. are you already ok with the grok filter to extract the value needed ?
2. can you describe a precise example of the google API method you want to use ?
3. can you describe precisely the json payload you want to build ?

**Comment by Marfas1983** [comment]
1. yes i have in this moment the information that a need, with grok and mutate filter a have de information that i need.
2. the api is descrive hear Measurement Protocol https://developers.google.com/analytics/devguides/collection/protocol/v1/

that i need send for example this information:
v=1             // Version.
&tid=UA-XXXX-Y  // Tracking ID / Property ID.
&cid=00000000-0000-0000-0000-000000000000        // Anonymous Client ID.

&t=pageview     // Pageview hit type.
&dh=xpto.com.br  // Document hostname.
&dp=/XXXX/AreaBoundMenu.ashx       // Page.
&dt= mode_subAreas/areaId_594/parentAreaId_98/mirrorColor_255-105-177-191/startIndex_0/itemCount_8/direction_     // Title.
in http output.

3. in field cid, i want transform that with algorithm off hash that i send for example one number

**Comment by wiibaa** [comment]
did you already try out the fingerpring filter for hash creation? 
http://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html

**Comment by Marfas1983** [comment]
thank's for your help, this filter resolve my problem.
another question:
for have the difference beetween the date of generation of log "2015-02-25 00:00:06" and systimestamp in second's, what filter that i need use?

**Comment by wiibaa** [comment]
there is currently no filter for doing it, so you need to fallback to the ruby codec as reported in https://github.com/elastic/logstash/issues/2299

**Comment by Marfas1983** [comment]
how convert the date "2015-02-25 00:00:06" to timestamp?
because, when put the ruby filter for diferente beetween @timestamp and other date, the ruby need that have in the same format.
can help me?

**Comment by wiibaa** [comment]
the easiest would be to use the date filter specifying a target to store the resulting timestamp, so when reaching the two field to compare would already contain a Logstash::Timestamp object

**Comment by Marfas1983** [comment]
my filter:
date {
      match => [ "log_timestamp","YYYY-MM-dd HH:mm:ss","ISO8601" ]
      timezone => "Europe/Lisbon"
      target => "log_timestamp"
    }

        ruby
                {
                code => "event['elapsed'] = (event['@timestamp']-event['log_timestamp'])"
                }


log's:

Exception in filterworker {"exception"=>#<TypeError: no implicit conversion to rational from nil>, "backtrace"=>["org/jruby/RubyTime.java:578:in `-'", "(ruby filter code):1:in `register'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/filters/ruby.rb:38:in `filter'", "(eval):90:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:262:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:203:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}

any ideia?

**Comment by Marfas1983** [comment]
i need to send the diference beetween two dates in miliseconds...

i belive that put diference beetween two timestamp i will be the result.. if not i will need convert dates to milisencond...:(

**Comment by Marfas1983** [comment]
thank's wiiba for your help i resolve my problem with:


date {
      match => [ "log_timestamp","YYYY-MM-dd HH:mm:ss","ISO8601" ]
      timezone => "Europe/Lisbon"
      target => "log_timestamp"
    }

        ruby
                {
                code => "event['qt'] = ((event['@timestamp'].to_f)*1000-(event['log_timestamp'].to_f)*1000).to_i"
                }

**Comment by jsvd** [comment]
@Marfas1983 strange, your first case should work..

```
logstash-1.4.2 % cat config
input { generator { count => 1 } }
filter {
   ruby { code => "sleep 1; event['t'] = Time.now" }
   ruby { code => "event['test'] = (event['t']-event['@timestamp'])" }
}
output { stdout { codec => rubydebug } }
logstash-1.4.2 % bin/logstash -f config
Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2015-04-10T13:16:55.583Z",
          "host" => "Joaos-MBP-2.lan",
      "sequence" => 0,
             "t" => "2015-04-10T14:16:56.588+01:00",
          "test" => 1.005
}
```

**Comment by Marfas1983** [comment]
I d'ont no why d'ont work, but no problem.

one more question or problem...


i have this 

http {
        http_method=> "post"
        url => "www.google-analytics.com"
        format => "form"
        message=>"collect?%{v}, %{tid}, %{cid}, %{t}, %{dh}, %{dp}, %{dt}, %{qt}"
        }

in output.

but when start logstash i have this error:

Addressable::URI::InvalidURIError: Hostname not supplied: 'www.google-analytics.com'
       validate at /opt/logstash/vendor/bundle/jruby/1.9/gems/addressable-2.3.6/lib/addressable/uri.rb:2302
          port= at /opt/logstash/vendor/bundle/jruby/1.9/gems/addressable-2.3.6/lib/addressable/uri.rb:1292
        use_uri at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/request.rb:122
     initialize at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/request.rb:59
        request at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:287
           post at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:212
        receive at /opt/logstash/lib/logstash/outputs/http.rb:101
         handle at /opt/logstash/lib/logstash/outputs/base.rb:86
     initialize at (eval):186
           call at org/jruby/RubyProc.java:271
         output at /opt/logstash/lib/logstash/pipeline.rb:266
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:225
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152


any ideia that what is a problem?

**Comment by Marfas1983** [comment]
one more question,

when i want sent a http post, in format form the configuration is:

http {
        http_method=> "post"
        url => "http://www.abcd.pt/xpto"
        format => "form"
        message=>"%{v}, %{tid}, %{cid}, %{t}, %{dh}, %{dp}, %{dt}, %{qt}"
        }
is correct? for have one message like http://www.abcd.pt/xpto?v=1&tid=XPTO&cid=A&t=ui&dh=1&dp=teste&dt=a&qt=12

**Comment by jsvd** [comment]
instead of message =>, you should use `mapping => ["v", "%{v}", "tid",  "%{tid}", ........] }`

**Comment by Marfas1983** [comment]
is not easy to put work...:(


i have this:
http {
        #content_type=>"application/form-data"
        http_method=> "post"
        url => "http://www.google-analytics.com/collect"
        format => "form"
        mapping => ["v","%{v}","tid", "%{tid}","cid", "%{cid}","t", "%{t}", "dh","%{dh}","dp", "%{dp}","dt", "%{dt}","qt", "%{qt}"]
        }


and them receive this message:

Unhandled exception {:request=><FTW::Request(@4086) @protocol="http" @body="v=1&tid=UA-XXXXX-OI&cid=bf7321859328634c99e33c31d39175dc5d4268c8&t=pageview&dh=xpto.com.br&dp=%2FLIFEKids%2FAreaBoundMenu.ashx&dt=mode_contents%2FareaId_593%2FparentAreaId_591%2FmirrorColor_255-255-255-255%2FstartIndex_0%2FitemCount_8%2Fdirection_&qt=16348" @method="POST" @headers=FTW::HTTP::Headers <{"host"=>"www.google-analytics.com", "connection"=>"keep-alive", "content-type"=>"application/x-www-form-urlencoded", "content-length"=>258}> @logger=#<Cabin::Channel:0x2290fb5f @subscriber_lock=#<Mutex:0x5c672bb3>, @metrics=#<Cabin::Metrics:0x79662429 @channel=#<Cabin::Channel:0x2290fb5f ...>, @metrics={}, @metrics_lock=#<Mutex:0x20d03e03>>, @data={}, @subscribers={}, @level=:info> @version=1.1 @request_uri="/collect" @port=80 >, :response=>nil, :exception=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :stacktrace=>["org/jruby/RubyIO.java:2097:in `close'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:173:in `connect'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:139:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:406:in `connect'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/pool.rb:48:in `fetch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:403:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:319:in `execute'", "/opt/logstash/lib/logstash/outputs/http.rb:132:in `receive'", "/opt/logstash/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):182:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:266:in `output'", "/opt/logstash/lib/logstash/pipeline.rb:225:in `outputworker'", "/opt/logstash/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn}

i think that this message d'ont go to the destiny.

and i see that logstatsh is very slowly to process the file...

**Comment by Marfas1983** [comment]
any idea, about what appening?

**Comment by jsvd** [comment]
according to https://developers.google.com/analytics/devguides/collection/protocol/v1/reference you also need to set a user agent or the message will be ignored

to debug this you can try to send the http request to a local tcp port.
1) open port 9090 using `nc -l 9090` or similar command
2) send the request to url => "http://localhost:9090"

and then see if the request looks good

**Comment by Marfas1983** [comment]
i @jsvd i test use a user agent filter and a i have this:

  "name" => "Other",
               "os" => "Windows",
          "os_name" => "Windows",
           "device" => "Other"


i test, like you tell me and verify this:

POST /debug/collect? HTTP/1.1
host: localhost
connection: keep-alive
content-type: application/x-www-form-urlencoded
content-length: 257

v=1&tid=UA-XXXXX-Y&cid=bf7321859328634c99e33c31d39175dc5d4268c8&t=pageview&dh=XTP.com.br&dp=%2FVivoKids%2FAreaBoundMenu.ashx&dt=mode_contents%2FareaId_101%2FparentAreaId_98%2FmirrorColor_255-105-177-191%2FstartIndex_0%2FitemCount_8%2Fdirection_&qt=15507

but i identify diferentes beetween this invocation and invocation by chrome, when invocate by postman i verify the request is:

POST /collect?v=1&tid=UA-XXXX-Y&cid=bf7321859328634c99e33c31d39175dc5d4268c8&t=pageview&dh=xpto.com.br&dp=%2FVivoKids%2FAreaBoundMenu.ashx&dt=mode_subAreas%2FareaId_594%2FparentAreaId_98%2FmirrorColor_255-105-177-191%2FstartIndex_0%2FitemCount_8%2Fdirection_&qt=9319 HTTP/1.1
Host: www.google-analytics.com
Cache-Control: no-cache

they are diferent.  i d'ont have more ideias..

**Comment by Marfas1983** [comment]
i have proxy in my LAN. logstash use the http normal, invocation correct? because i define the http_proxy and https_proxy in user that invoke logstash.

another questione this plugin, can write in file the response of invocation?

**Comment by Marfas1983** [comment]
any idea, for help me?

**Comment by ph** [comment]
It is still an issue?
