### ISSUE TITLE
Can we get date variables in the config in local time? 

### ISSUE THREAD

**Issue by cschotke** [elastic/logstash#2818]
We are using date variables in some of our configuration files but they seem to use UTC time. This causes problems for us because we are in Chicago so if we use %{+YYYY.MM.dd}, it is wrong 5 hours out of the day. Is there a way to get the current local date/time?

**Comment by jordansissel** [comment]
Good idea! This is being discussed in #2315. I'll close this so we can continue that discussion over in that ticket.

**Comment by untergeek** [comment]
You are correct about UTC. This is used because it's canonical. Where are you using time strings that you'd like to see in your local time zone?
