### ISSUE TITLE
Logstash Grok Pattern

### ISSUE THREAD

**Issue by lakhera2014** [elastic/logstash#2820]
Hi

I am new to logstash and what I heard about logstash "If a newbie has a bad time, it's a bug" ;).I am bad at regular expression,I try to use default grok patterns and its not working.Any help is really appreciated

plakher1|r91|2015-03-13|13:12:45|iTrack: logstash-125 / new logstash|A   test/prashanttest3|

For eg: For this string I wrote 

(?:%{USERNAME}\|r[0-9][0-9]\|%{DATE_EU}\|%{TIME}\|%{EVERYTHING:logmessage}\|%{EVERYTHING:logmessage}\|)

**Comment by lakhera2014** [comment]
After not getting any response,I try to write my own custom patterns but its not working,I am not able to figure it out which parenthesis I am missing and what is this field a0,a1 ..here in the logs...

match => [ "message", "(?m)%{SVN_LOG_FORMAT}" ]

SVNUID ^[a-zA-Z0-9._-]+
SVNREVISION |r[0-9][0-9]+
SVNDATE [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
SVNTIME [0-9][0-9]:[0-9][0-9]:[0-9][0-9]
SVNCOMMENT iTrack:.*.[a-zA-Z0-9._-]+
SVNCHECKINFILES |[A-Z]\ [a-zA-Z0-9._-]+\/[a-zA-Z0-9._-]+\

SVN_LOG_FORMAT (%{SVNUID:userid}|%{SVNREVISION:revision}|%{SVNDATE:date}|%{SVNTIME:time}|%{SVNCOMMENT:comment}|%{SVNCHECKINFILES:checkinfile}|$)

The error reported is: end pattern with unmatched parenthesis:
 /(?m)(?<a0>((?<a1>^[a-zA-Z0-9._-]+)\|(?<a2>|r[0-9][0-9]+)\|
(?<a3>[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])\|(?<a4>[0-9][0-9]:[0-9][0-9]:[0-9][0-9])\|(?<a5>iTrack:.*.[a-zA-Z0-9._-]+)\|(?<a6>|[A-Z]\ [a-zA-Z0-9._-]+\/[a-zA-Z0-9._-]+\)\|$))/

**Comment by magnusbaeck** [comment]
I think you'll find that the [logstash-users mailing list](https://groups.google.com/forum/#!forum/logstash-users) is better for this type of support requests.

**Comment by lakhera2014** [comment]
@magnusbaeck: I already check in logstash mailing list but no help.Anyway I am not going to use logstash any more..As they are calming "If a newbie has a bad time, it's a bug" but writing grok parser is a real mess.

**Comment by magnusbaeck** [comment]
That's funny, I read that list and don't recall this question. But if you're going to parse logs you'll end up with regular expressions regardless if you use Logstash or not.
