### ISSUE TITLE
Support for ES native IP type

### ISSUE THREAD

**Issue by rabidscorpio** [elastic/logstash#2821]
All the documentation on mutate and grok says that only "integer", "float", and "date" are supported but some people have found that just changing the mapping on the elasticsearch side enables support for the native IP type.

This seems like a fairly trivial change to make, is there a particular reason it is not supported?

**Comment by untergeek** [comment]
The answer is in the JSON.  All events sent from Logstash to Elasticsearch are in JSON.

Integer and float types are valid JSON values and need no quote encapsulation.  Dates and IPs in JSON must be strings and therefore encapsulated in double-quotes.  There is nothing you can put in the JSON to "tell" Elasticsearch that an IP string is an IP address.  You have to create a mapping to tell Elasticsearch that a given field is going to be an IP. Elasticsearch must know which field(s) will have an IP _in advance._  

There is no way to do this via Logstash other than the templating mechanism.  Any attempt to do on-demand mapping through Logstash would result in severe performance degradation as there would have to be continuous checks against Elasticsearch.  This is why a seemingly trivial change has not been made: We cannot predict what field names people will use to hold their IP addresses.
