### ISSUE TITLE
Formatted JSON source should be colorized for better readability

### ISSUE THREAD

**Issue by bradvido** [elastic/logstash#2827]
As it was in Kibana 3, the JSON source of a document (in the table view) should be nicely formatted & colorized (e.g. fields are bold, numeric values & booleans are different color than strings).

Kibana 3 example:
![image](https://cloud.githubusercontent.com/assets/884611/6670101/d905a112-cbca-11e4-976b-3d67794a7df2.png)

Kibana 4 example:
![image](https://cloud.githubusercontent.com/assets/884611/6670126/fde1457c-cbca-11e4-975f-10f0a311fb2a.png)

I oftentimes view the document source and moving to Kibana 4 has been much more difficult because it's all the same color and kind of blends together.

**Comment by untergeek** [comment]
I'm puzzled.  Seeing that its a Kibana issue, how did it come to be registered in the Logstash repository?

**Comment by bradvido** [comment]
Arg, my bad. Too many github tabs open at once!  I'll re-post it on Kibana, unless you can move it?

**Comment by untergeek** [comment]
Can't move it, sorry.  Thanks for re-posting.

**Comment by bradvido** [comment]
Thanks.
For reference: https://github.com/elastic/kibana/issues/3365
