### ISSUE TITLE
Infinite loop searching logs in a directory tree

### ISSUE THREAD

**Issue by CalldiDoctor** [elastic/logstash#2828]
I'm having troubles searching logs within a directory tree.
I'm using the notation /**/*.log to do it.
My logstash instance does not end searching logs within a 120MB directory tree. How long it should take?

This is the path that I'm using:
path => "/home/user/logstash-1.4.2/logs/**/*.log"

The /**/ pattern is not the right option to search recursively?

Thanks

**Comment by ph** [comment]
Reading 120MB of data in a directory should be really fast.
I did a succesful test locally with this directory structure and the following configuration:
```
/tmp/testlog
├── a.log
└── test1
    ├── b.log
    └── test2
        └── ttt.log
```


```
input {
  file {
    path => '/tmp/o/**/*.log'
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

**Comment by CalldiDoctor** [comment]
It has taken 1.5 hours to index 120MB of log Data into elasticsearch.
My directory tree is much more deper, there are 8 levels until you reach the first log file, and all the log files are light, but there are a lot of them.
Could be possible that this 1.5 hours is due this fact? A lot of small log files at the end of the tree?

**Comment by jordansissel** [comment]
@CalldiDoctor how many log files?

**Comment by suyograo** [comment]
Closing, no response in a long time
