### ISSUE TITLE
Unix server requirement for ELK installation

### ISSUE THREAD

**Issue by vg15** [elastic/logstash#2829]
Hi Experts,

Need your valuable advice , I want to install ELK on Unix server , would you please suggest what Unix server should I use . I mean what system configuration I can use ?

**Comment by lmorfitt** [comment]
Hello,

More information is needed for this.

I've ran single server 4core, 8gb ram with ELS and logstash processing around 3000 events per second. This was for a test of the software.

In prod I've ran 3 x 4 core 8gb ram 100gb disk for ELS. 2x 2core, 4gb ram for logstash.

It all depends on the amount of data you need to move and how reliable you want the platform.
