### ISSUE TITLE
1.4.2 email plugin won't seem to send via exim

### ISSUE THREAD

**Issue by mpladna** [elastic/logstash#2831]
I've configured my email plugin like so:

...lots of config omitted
  if [log_level] == "ERROR" and [log_message] =~ "^\s*ALERT:" {
    email {
      via => "sendmail"
      to => "mpladna@lgscout.com"
      from => "no-reply@lgscout.com"
      replyto => "no-reply@lgscout.com"
      subject => "failure subject"
      htmlbody => "some html body"
  }
}

On my mac this sends fine.  However, on one of our dev unix systems, using exim4, it won't.  When I look in the exim logs I see the email being bounced like so:
2015-03-16 15:37:27 1YXX55-0002BY-TY <= <> R=1YXX55-0002BV-S2 U=Debian-exim P=local S=7074
2015-03-16 15:37:27 1YXX55-0002BY-TY => no-reply@lgscout.com R=smarthost T=remote_smtp_smarthost H=XX.XX.XX.XX [XX.XX.XX.XX]

Logstash is running via a debian package we created as the logstash user.  We've tried changing the 'via' option to exim, smtp, and sendmail.  We've also toyed with the options hash to no avail.  Exim4 is installed in the default location noted in the ruby Mail class.

We tested via our command line that we can send email from this box and we can do so as users, root, even sending the mail sudo -u logstash works.  It just appears with logstash is sending via the email plugin it gets bounced.

Any help/ideas would be appreciated.  Let me know if any other details are needed to help diagnose/fix.

**Comment by mpladna** [comment]
To note, our sendmail symlink is at /usr/sbin/sendmail and links to /usr/sbin/exim

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-email/issues/21. Let's continue the discussion there! :)
