### ISSUE TITLE
Document use case for es_bulk codec

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#2833]
The es_bulk codec is one that is useful for users who are migrating from the rabbitmq river to rabbitmq logstash plugin.  The rabbitmq river requires bulk index formatted messages to be placed into the rabbitmq, which means that when switching to rabbitmq input plugin in 1.5, the es_bulk codec will have to be used to decode these bulk index formatted messages back to individual events.  

It will be helpful to add to the documentation:

* Add a note to the rabbitmq plugin page (http://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html) for users migrating from rabbitmq river (eg. "For users migrating from rabbitmq river plugin, use the es_bulk codec to decode bulk index formatted messages to individual events.", etc..).  And then cross reference the es_bulk codec doc page.

**Comment by jordansissel** [comment]
Ahh, good idea! :)

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-codec-es_bulk/issues/5. Let's continue the discussion there! :)
