### ISSUE TITLE
Output file always tries to convert to UTF-8

### ISSUE THREAD

**Issue by CalldiDoctor** [elastic/logstash#2834]
I'm trying to write logs containing non UTF-8 data with the file output.
Logstash always return this error when it tries to write:

Encoding::UndefinedConversionError: ""\xAC"" from ASCII-8BIT to UTF-8

I've tried to change the charset from the default UTF-8 to ASCII-8BIT, in order to avoid the conversion:
output {
        file { codec => plain {charset => "ASCII-8BIT"} path => "PATH" }
}

But I'm still receiving the same error. Why is logstash trying to convert if I've written that the charset is  ASCII-8BIT??

Thanks

**Comment by wiibaa** [comment]
Sadly file output does not support codec configuration (see https://github.com/logstash-plugins/logstash-output-file/issues/7) no not respecting the charset neither
Also starting with logstash 1.5, each report have its own github repository so can you please close this issue and recreate it under https://github.com/logstash-plugins/logstash-output-file/issues
THanks
