### ISSUE TITLE
1.5.0rc2 email plugin warning unsupported popen on centos 6.x

### ISSUE THREAD

**Issue by sbarrier** [elastic/logstash#2838]
On Centos 6.x the email plugin work but generate a warning message :

*/opt/logstash/vendor/bundle/jruby/1.9/gems/mail-2.6.3/lib/mail/network/delivery_methods/sendmail.rb:72 warning: unsupported popen option: err*

the sendmail.rb line 72 is the following IO.popen

```
def self.popen(command, &block)
 IO.popen command, 'w+', :err => :out, &block
end
```
Centos use Postfix by default, the sendmail binary is a link :
lrwxrwxrwx. 1 root root 21 Nov  6  2013 /usr/sbin/sendmail -> /etc/alternatives/mta
lrwxrwxrwx. 1 root root 26 Nov  6  2013 /etc/alternatives/mta -> /usr/sbin/sendmail.postfix

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-email/issues/22. Let's continue the discussion there! :)
