### ISSUE TITLE
Ruby errors in logstash.err

### ISSUE THREAD

**Issue by codz67** [elastic/logstash#2839]
Good evening everyone. A bit bout my setup.
OS: RHEL 6.6
Logstash: 1.4.2
ElasticSearch: 1.4.4

Logstash starts and then dies within a few seconds.
Logstash.log reports no errors. Although some warnings about plugin milestones.
Logstash.err shows as below. 

Faraday::ConnectionFailed: Connection refused - Connection refused
              call at /opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:44
    build_response at /opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139
       run_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.0/lib/faraday/connection.rb:377
   perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/http/faraday.rb:24
              call at org/jruby/RubyProc.java:271
   perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/base.rb:187
   perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/http/faraday.rb:20
   perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/client.rb:102
   perform_request at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.1/lib/elasticsearch/api/namespace/common.rb:21
      get_template at /opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.1/lib/elasticsearch/api/actions/indices/get_template.rb:24
  template_exists? at /opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:132
  template_install at /opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:21
          register at /opt/logstash/lib/logstash/outputs/elasticsearch.rb:259
              each at org/jruby/RubyArray.java:1613
      outputworker at /opt/logstash/lib/logstash/pipeline.rb:220
     start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152

**Comment by markwalkom** [comment]
Please take this to the mailing list - https://groups.google.com/forum/?hl=en-GB#!forum/logstash-users

Github is for code issues, but it appears you have a config problem or something else not related to possible bugs.
