### ISSUE TITLE
Clarify default protocol for ES output plugin

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#2841]
In the beginning paragraphs of http://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch, we specify that `node` is the default protocol.

>With the default protocol setting ("node"), this plugin will join your Elasticsearch cluster as a client node, so it will show up in Elasticsearch’s cluster status.

But later on in the `protocol` section (http://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-protocol), it gets more fuzzy.  

It specifies that there is no default value for the setting:

>protocol
>Value can be any of: node, transport, http
>There is no default value for this setting.

And then there is this statement. 

>The default protocol setting under java/jruby is "node". The default protocol on non-java rubies is "http".

Since ES output plugin is a jruby implementation, the default in this case will be node.  It seems like we don't actually need the jruby vs. non-java rubies statement here.  

Maybe change 1)  "There is no default value for this setting." to specify the default to be node, 2) And remove the statement on jruby vs. non-java rubies?

**Comment by jordansissel** [comment]
I wonder if we could use this as a reason to have consistent behavior for all rubies. My proposal is to default to protocol => http.

Thoughts?

**Comment by suyograo** [comment]
+1 on defaulting to `http`. We can then stop shipping ES jars with LS core and maybe have a separate plugin for node and transport protocol?

**Comment by untergeek** [comment]
Rather than separate plugins, what about making those an add-on, like Shield?

**Comment by jordansissel** [comment]
@untergeek in this case, an "add on" is a subset of a thing we call a plugin, so these are the same things :P 

It will be like shield, but like shield, you'll have to install it explicitly and it won't come by default.

**Comment by untergeek** [comment]
Just clarifying, because it could also have implied a stand-alone plugin, too. :stuck_out_tongue_closed_eyes:

**Comment by suyograo** [comment]
The docs are clear now. For changing the default to http protocol, we can follow up here https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/150
