### ISSUE TITLE
Logstash deb package fails to uninstall

### ISSUE THREAD

**Issue by Mister-X-** [elastic/logstash#2842]
It happened on one system only and it was happened every single time it was uninstalled using 'apt-get remove logstash'. I wasn't able to reproduce the issue on another install. That was a test system (Ubuntu server 14.04.2 LTS with Logstash, ElasticSearch and Kibana), so it has been wiped now. However, you might be able to figure out where it fails based on the error message:

```
root@kibana:/etc# apt-get remove logstash
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  ca-certificates-java java-common libasyncns0 libavahi-client3
  libavahi-common-data libavahi-common3 libcups2 libflac8 liblcms2-2 libnspr4
  libnss3 libnss3-nssdb libogg0 libpulse0 libsndfile1 libvorbis0a
  libvorbisenc2 openjdk-7-jre-headless tzdata-java
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  logstash
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 142 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 121225 files and directories currently installed.)
Removing logstash (1.4.2-1-2c0f5a1) ...
userdel: user logstash is currently used by process 32379
groupdel: cannot remove the primary group of user 'logstash'
dpkg: error processing package logstash (--remove):
 subprocess installed pre-removal script returned error exit status 8
Errors were encountered while processing:
 logstash
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@kibana:/etc#
```

**Comment by magnusbaeck** [comment]
Okay, so Logstash or possibly some other process running as the logstash user was running when you tried to uninstall the package.  The Logstash package should have a prerm script that stops Logstash before trying to delete any files and users. This is what it can look like for Debian packages created with the standard tools that invoke dh_installinit:

    if [ -x "/etc/init.d/name-of-service" ]; then
            invoke-rc.d name-of-service stop || exit $?
    fi

(For packages that install Upstart-enabled services it probably look a bit different.)

**Comment by Mister-X-** [comment]
How about we kill it if invoke-rc.d fails to stop it?

Another question: how can I figure out why logstash is not stopping? Unfortunately, I don't have much time I can dedicate to that, so attaching a debugger is not an option. Is there any logging option I can enable or make it more verbose for the next time it happens?

**Comment by jordansissel** [comment]
Since we're removing the user, it may be simpler to just do `pkill -9 -u logstash` to terminate all processes under the 'logstash' user.

**Comment by jordansissel** [comment]
Any thoughts on the `pkill -9 -u logstash` step before attempting the user removal? This should be more reliable than the 'stop the service first' implementation.

**Comment by magnusbaeck** [comment]
I don't have a very strong opinion about it, but users _could_ have other processes running as the logstash user and silently SIGKILLing them seems antisocial. I think the correct behavior would be for the package to shut down the things it owns and if the user can't be deleted because there's still a process running it's something a human needs to look at.

**Comment by Mister-X-** [comment]
Just killing the logstash processes under the logstash users could be killed then. And if the user cannot be removed, then do not fail uninstalling the deb package.

**Comment by SkaveRat** [comment]
this is getting a problem for me.

I want to remove/purge the package from my system, but there are 2 logstash process who will automaticly respawn if killed, even with the service stopped

**Comment by magnusbaeck** [comment]
> I want to remove/purge the package from my system, but there are 2 logstash process who will automaticly respawn if killed, even with the service stopped

It sounds like you have an Upstart-based system (e.g. Ubuntu) and you're attempting to shut down Logstash without going through Upstart (i.e. you're not running `service logstash stop` or `stop logstash`).

**Comment by mapcentia** [comment]
I had the same issue on a Ubuntu 14.04 dev VM, so I ended up with:

sudo rm /var/lib/logstash/* -R
sudo dpkg --force-all -P logstash

Not pretty, but it worked.

**Comment by kpatryk** [comment]
Hava the same issue on Mint 17.

```
# pkill  -9 -u logstash; rm -R /var/lib/logstash/*;  dpkg --force-all -P logstash
(Reading database ... 219761 files and directories currently installed.)
Removing logstash (1.4.3-1-7e387fb) ...
userdel: user logstash is currently used by process 5169
groupdel: cannot remove the primary group of user 'logstash'
dpkg: error processing package logstash (--purge):
 subprocess installed pre-removal script returned error exit status 8
Errors were encountered while processing:
 logstash
```
and again:
```
# pkill  -9 -u logstash; rm -R /var/lib/logstash/*;  dpkg --force-all -P logstash
rm: cannot remove ‘/var/lib/logstash/*’: No such file or directory
(Reading database ... 219761 files and directories currently installed.)
Removing logstash (1.4.3-1-7e387fb) ...
userdel: user logstash is currently used by process 5211
groupdel: cannot remove the primary group of user 'logstash'
dpkg: error processing package logstash (--purge):
 subprocess installed pre-removal script returned error exit status 8
Errors were encountered while processing:
 logstash
```

**Comment by suyograo** [comment]
Closing this since it's a very old LS release (1.4.2)
