### ISSUE TITLE
Lumberjack protocol seems to strip fields

### ISSUE THREAD

**Issue by Mister-X-** [elastic/logstash#2843]
I'm doing some kind of log collector using logstash (not the forwarder since we won't collect logs from files) and forwarding all the logs to a central location for analysis. I am using Logstash 1.5RC2 from the debian package on Ubuntu 14.04.2 LTS 64 bit (on both sides)

Here is the configuration of the log collector (this is a test system, hence why it only has a single input):
```
input {
        syslog {
                port => 1514
                type => "syslog"
        }
}

filter {
        if [type] == "syslog" and [host] == "127.0.0.1" {
                mutate {
                        replace => [ "host", "192.168.110.143" ]
                }
        }
        mutate {
                add_field => {
                        "location" => "vmware"
                }
        }
}

output {
        lumberjack {
                hosts => "192.168.110.144"
                port => 6782
                ssl_certificate => "/etc/pki/tls/certs/logstash/server.crt"
        }
        file {
                path => "/var/log/logstash/output.log"
                codec => "rubydebug"
        }
}
```

and here is one log message I get from that output.log file:
```
{"message":"blah\n","@version":"1","@timestamp":"2015-03-17T19:54:58.000Z","type":"syslog","host":"192.168.110.143","priority":13,"timestamp":"Mar 17 12:54:58","logsource":"ubuntu","program":"user1","severity":5,"facility":1,"facility_label":"user-level","severity_label":"Notice","location":"vmware"}
```

And we can see that it is parsed correctly and the location field has been added.

On the other side, on the central system, fields from that log entry are stripped:
```
{"message":"2015-03-17T19:54:58.000Z 192.168.110.143 blah\n","@version":"1","@timestamp":"2015-03-17T19:54:58.255Z"}
```

Here is the config from that central system:
```
input {
        lumberjack {
                port => 6782
                ssl_certificate => "/etc/pki/tls/certs/logstash/server.crt"
                ssl_key => "/etc/pki/tls/private/logstash/server.key"
        }
}

output {
        elasticsearch { host => localhost }
        file {
                path => "/var/log/logstash/output.log"
                codec => "rubydebug"
        }
}
```

Based on a discussion I had on IRC in #logstash, it sounds like Lumberjack stripping all those fields is a bug.

**Comment by Mister-X-** [comment]
If I use the 'json' codec (on both sides) for lumberjack, it 'fixes' the issue: all fields are present.

**Comment by torrancew** [comment]
@jordansissel @suyograo Would it make sense to default the lumberjack output to the json codec? That in and of itself has some problems, admittedly, if the input defaults to plain - but given that json fails back to plain well, maybe swapping both would be worthwhile?

**Comment by jordansissel** [comment]
I"m open to switching it to json, but for the input that may hurt performance (all messages will try to parse as json first)

**Comment by torrancew** [comment]
Yeah, that's my main concern, as well. I don't have any numbers on that handy, but will see if I can get some, possibly (we do mixed json/plain with json as the default codec).

**Comment by torrancew** [comment]
I definitely think there's a strong case for defaulting the output, though - as far as I know, Logstash is the only server-side implementation of the lumberjack protocol (at least, that's publicly available). Thoughts?

**Comment by jordansissel** [comment]
I am in favor of defaulting the output to json, but wonder about how that may confuse users (input plain, output json defaults).

**Comment by torrancew** [comment]
That could definitely be an issue, but I think that in that case, we'd be comparing the relative confusion of the OP's scenario, versus the potential confusion of the new setting. I don't really know if there *is* a better answer, so maybe it's best to just not poke the bear?

**Comment by Mister-X-** [comment]
It will be more confusing if output default json and input to plain. Users might not understand why it's not working with the defaults.
Both should be set to json.

And logstash-forwarder will need to be modified too.

**Comment by torrancew** [comment]
@Mister-X- the main problem is the difference between the default use cases for each of these:
  * For logstash-forwarder, the main use case is reading log files from a server, and shipping them to logstash. these logs are generally not JSON, so it makes sense for LSF to send a text blob over and leave it at that (it passes fields out of band).
  * For lumberjack *input*, the main use case is receiving logs from logstash-forwarder, so again, it makes a fair amount of sense to default it to the plain codec, to match the sender (JSON would just waste performance and cycles for most users here)
  * For lumberjack *output*, things change. The main use case is shipping logs to another Logstash - and you're also always dealing with "real" LogStash::Event objects as input, so here, it makes sense for JSON to be a default

*Note* When I talk about "making sense", I mean from the system's point of view, not for a given user's perspective. I totally understand that the two may not agree, which is what @jordansissel and I are sort of mulling over out loud.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-lumberjack/issues/3. Let's continue the discussion there! :)
