### ISSUE TITLE
How to warn user on input/ouput not supporting codec

### ISSUE THREAD

**Issue by wiibaa** [elastic/logstash#2845]
There are several plugins like http output or file output that do not use codecs but the configuration allows user to define it. But having an open issue is not enough visibility for users!
Should a method similar to `workers_not_supported` be added to the base.rb class ad called from the register method of the plugins lacking codec support or do you see another way ?

**Comment by ph** [comment]
I agree this is a bad user experience :(

I think we should add another macro similar to the way were are defining the plugin config option.
The macros would alllow us to trap problems when we are parsing the config file (with or without using --configtest)


```ruby
config :name, :validate => :string
workers_not_supported
codec_not_supported

def register
end
```

**Comment by jordansissel** [comment]
The way we are solving this (idealy, for 5.x) is to make codecs not a default property of all input and output plugins. That solution is in https://github.com/elastic/logstash/issues/4767.
