### ISSUE TITLE
Logstash randomly stops sending access_log events to elasticsearch

### ISSUE THREAD

**Issue by codertux** [elastic/logstash#2848]
Hi guys,

Since a few days ago I've noticed a weird issue with logstash. We're using it with the file input for a java app running on tomcat. We have a few custom logfiles configured that have worked fine for months, but we recently added tomcat's access_log with a file input, and it randomly fails. There are no errors in the logfiles as far as I can tell, but I have noticed that removing the sincedb file for the access_log temporarily resolves the problem.

We're using logrotate with the copytruncate option to rotate the logs, but the issue doesn't seem to be linked to the log rotation.

Any ideas what could be going wrong?

**Comment by suyograo** [comment]
What's your platform details? Also, can you start with LS with `--debug` command line option?

**Comment by codertux** [comment]
We're running logstash on CentOS 6, with Oracle Java 1.7.0. I've started running logstash with --debug, but I'm not sure what to look for... The input seems to initialize properly as far as I can tell,
```
{:timestamp=>"2015-03-24T03:21:41.086000-0400", :message=>"config LogStash::Codecs::Plain/@charset = \"UTF-8\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.089000-0400", :message=>"config LogStash::Inputs::File/@path = [\"/var/log/tomcat6/access_log\"]", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.091000-0400", :message=>"config LogStash::Inputs::File/@type = \"access\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.094000-0400", :message=>"config LogStash::Inputs::File/@tags = [\"web\"]", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.096000-0400", :message=>"config LogStash::Inputs::File/@debug = false", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.103000-0400", :message=>"config LogStash::Inputs::File/@codec = <LogStash::Codecs::Plain charset=>\"UTF-8\">", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.111000-0400", :message=>"config LogStash::Inputs::File/@add_field = {}", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.113000-0400", :message=>"config LogStash::Inputs::File/@stat_interval = 1", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.115000-0400", :message=>"config LogStash::Inputs::File/@discover_interval = 15", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.117000-0400", :message=>"config LogStash::Inputs::File/@sincedb_write_interval = 15", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-03-24T03:21:41.119000-0400", :message=>"config LogStash::Inputs::File/@start_position = \"end\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
```

Then there's a lot of ```{:timestamp=>"2015-03-24T03:22:13.682000-0400", :message=>"_discover_file_glob: /var/log/tomcat6/access_log: glob is: [\"/var/log/tomcat6/access_log\"]", :level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}```, but no events are being processed...

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/41. Let's continue the discussion there! :)
