### ISSUE TITLE
[regression] Syntax error with "if" on multiple lines

### ISSUE THREAD

**Issue by ochedru** [elastic/logstash#2850]
Just tried 1.5.0 RC2 and got a syntax error with my configuration file (worked fine in 1.4.2):
```
SyntaxError: (eval):160: syntax error, unexpected kOR
      or [tag] == "catalina.out"
       ^
        eval at org/jruby/RubyKernel.java:1107
  initialize at /opt/logstash/lib/logstash/pipeline.rb:32
     execute at /opt/logstash/lib/logstash/agent.rb:114
         run at /opt/logstash/lib/logstash/runner.rb:124
        call at org/jruby/RubyProc.java:271
         run at /opt/logstash/lib/logstash/runner.rb:129
        call at org/jruby/RubyProc.java:271
  initialize at /opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/task.rb:12
```
Here is the culprit block from the configuration file `filter` section:
```
  if [tag] == "foo"
    or [tag] == "catalina.out"
    or [tag] == "bar" {
```
Workaround: put all "or" conditions on the same line.

**Comment by untergeek** [comment]
Thanks for submitting this.  We'll look at the config parser on this.

Here's a shorter potential workaround:
```
if [tag] in ['foo', 'catalina.out', 'bar'] {
```

**Comment by Mogztter** [comment]
@untergeek Is this issue will be fixed before the 1.5.0 release ?

**Comment by timbunce** [comment]
I just hit this with 1.5.0 RC4.

**Comment by jordansissel** [comment]
@timbunce for clarity, this is a bug and a regression. :)

**Comment by jordansissel** [comment]
Testing this:

```ruby
[14] pry(main)> a = LogStashConfigParser.new; config = a.parse("filter { if [foo]\n or [bar]\n or [baz] { test { } } }");; puts config.compile
...
          def cond_func_1(input_events)
            result = []
            input_events.each do |event|
              events = [event]
              if ((event["[foo]"]) or (event["[bar]"]) or (event["[baz]"])) # if [foo]
 or [bar]
 or [baz]
            events = @filter_test_3.multi_filter(events)


              end
              result += events
            end
            result
          end
```

**Comment by jordansissel** [comment]
The bug in the compiled code is this generation:

```ruby
              if ((event["[foo]"]) or (event["[bar]"]) or (event["[baz]"])) # if [foo]
 or [bar]
 or [baz]
```

It's including the 'or [bar]' for some reason. I'll take a look at the config AST to figure out what's causing this.

**Comment by jordansissel** [comment]
Haha, this bug...

```
[6] pry(#<LogStash::Config::AST::If>)> puts compile
=> "if ((event[\"[test]\"]) or (event[\"[whatever]\"]) or (event[\"[whatever]\"])) # if [test]\n   or [whatever]\n   or [whatever]\n            events = @filter_fancy_1.multi_filter(events)\n  \n"
```

The bug is that it takes your logstash config and tries to embed it in a comment in the compiled code (for easier debugging), but there are newlines, which make it invalid ruby code - when compiled. This should be an easy fix.

The line of code that causes it was introduced in 4211522d (April 2012), so I'm not yet sure how this only affects 1.5.0 and not 1.4.2.

**Comment by jordansissel** [comment]
I can confirm that 4211522 isn't included in 1.4.2

**Comment by jordansissel** [comment]
#3281 has a fix for this.

**Comment by ochedru** [comment]
Thank you Jordan!
I should learn Ruby some day to contribute.
