### ISSUE TITLE
Add proxy support for jar dependencies

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2851]
From the discussion in this issue https://github.com/elastic/logstash/issues/2557, jar-dependencies does not work with http_proxy environment variable and needs a code change. This existed before in beta1 and needs to be reinstated.

**Comment by ph** [comment]
Proxy reference from beta 1: https://github.com/elastic/logstash/blob/v1.5.0.beta1/lib/logstash/pluginmanager/install.rb#L13-L31

**Comment by ph** [comment]
Forwarded on the maven side with this
https://github.com/mkristian/jar-dependencies/blob/master/lib/jars/maven_exec.rb#L94-L99

**Comment by ph** [comment]
I have ugly workaround...
adding this to `$HOME/.m2/settings.xml` allow maven to use a proxy.

```xml
<settings>
  <proxies>
   <proxy>
      <id>example-proxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>127.0.0.1</host>
      <port>3128</port>
    </proxy>
  </proxies>
</settings>
```

Ruby maven doesn't correctly send the the option down to maven. 
filling an issue upstream.

**Comment by ph** [comment]
You STILL need to invoke plugin install with an explicit proxy. . .

```
http_proxy=http://127.0.0.1 bin/plugin install plugin-name

**Comment by ph** [comment]
I know we had issue with the latest ruby-maven, but I'll try an update again since the way maven is invoked is different.

**Comment by ph** [comment]
Closing this https://github.com/elastic/logstash/issues/2954 will take care of the issue with http_proxy and maven.
