### ISSUE TITLE
Create automated release acceptance test

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2852]
We need a Jenkins job that verifies the release artifacts and it needs to have more coverage than our existing Package Acceptance tests. This should have tests for plugin CLI, file inputs and test the existence of jars, vendor directories etc.

Test plan:
- [x] `bin/logstash version`: List current version
- [ ] `bin/logstash` with json input and check if parsing is successful
- [ ] `bin/plugin list`: Should list all plugins installed by default. Assert the count (currently 103)
- [x] `bin/plugin list --verbose`: Should list version info (Assert for stdin plugin)
- [x] `bin/plugin list stdin`: Should list logstash-input-stdin
- [x] `bin/plugin uninstall logstash-input-stdin`: Should uninstall, check for exit code
- [ ] `bin/plugin uninstall localgem`: Should uninstall, check for exit code.
- [x] `bin/plugin list stdin`: Should not list plugin
- [ ] `bin/plugin install logstash-input-wmi`
- [ ] `bin/plugin list --verbose wmi` : Should show current version (assert after getting from rubygems API)
- [x] `bin/plugin update` Mass update
- [x] Install locally built gem `bin/plugin install <file_path> --no_verify`
- [ ] `bin/plugin update` Try mass update after installing local gem
- [x] Test ES integration with geo, grok, and useragent filter with Apache logs. Send 50 Apache logs and check exact fields after doing a search on ES. Do this test on node, http and transport protocol
- [ ] Kafka input/output test. Bring up Kafka, send events through Logstash producer, and receive through Logstash consumer (@talevy has the scripts for these)
- [x] File input test: Follow test file (with known number of events) and assert if the events are received. Test `start_position => "beginning"` and also test tailing option
- [ ] File input test: Follow test file (with known number of events) and assert if the events are received. Test test tailing option
- [ ] Check for bundled jars. `find . -name *.jar | wc -l` should be 155.
- [ ] Add a `HTTP_PROXY` test for installing plugins

This should be run on all supported platforms

**Comment by ph** [comment]
Linux is working fine with `test-kitchen` is just a matter of create the appropriate docker file.
There is some work done for windows, I will try to experiment with it.

**Comment by purbon** [comment]
:dancer:

**Comment by ph** [comment]
@talevy can you point me to the kafka scripts?

**Comment by ph** [comment]
- [ ] use the `rakelib/default_plugins.rb` for the number of plugins installed assertion.
- [ ] get a random plugin for the majority of tests

**Comment by ph** [comment]
Random plugins doesn't work well because of https://github.com/elastic/logstash/issues/3152

**Comment by ph** [comment]
added a note  for `HTTP_PROXY`

**Comment by ph** [comment]
Updated with local gem uninstallation. https://github.com/elastic/logstash/issues/3336

**Comment by purbon** [comment]
Related to: #5013

**Comment by purbon** [comment]
Tried to describe in a bit more detail, also including the current new commands, different working situations (offline, proxy, etc) the expected plugin manager behaviour, see #5020 for more details.
