### ISSUE TITLE
Is it possible to configure logstash stop parsing logs under certain conditions?

### ISSUE THREAD

**Issue by alessiodelchiaro** [elastic/logstash#2858]
Hi Guys,

Is there any chance to allow logstash stop parsing a specific log (e.g., when it reaches EOF)?

My application might generate GB of logs so I would like to remove them once those are parsed.

If it is not possible, it would be great to have this feature in a future version.

Thanks,

Alessio

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-file/issues/39. Let's continue the discussion there! :)
