### ISSUE TITLE
s3.rb does not support cn-north-1 region

### ISSUE THREAD

**Issue by psu1025** [elastic/logstash#2862]
Logstash s3 plugin (s3.rb) does not support cn-north-1 region.

 config :endpoint_region, :validate => ["us-east-1", "us-west-1", "us-west-2",
"eu-west-1", "ap-southeast-1", "ap-southeast-2",
"ap-northeast-1", "sa-east-1", "us-gov-west-1"], :default => "us-east-1"

please add china region.

best regards.

**Comment by wiibaa** [comment]
@psu1025 Starting logstash 1.5, each plugin have its own github repository. Can you please close this issue and reopen it in https://github.com/logstash-plugins/logstash-mixin-aws/issues. Thanks
