### ISSUE TITLE
Docs: Make it easy to provide doc fixes from elastic.co/reference

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2864]
Doc generation in Logstash today uses an intermediate repository: https://github.com/elastic/logstash-docs. This is used to consolidate all the generated docs from plugins and the static docs from this repo. It is then converted from asciidoc to html and pushed to elastic.co/reference. There is an icon to directly edit the docs, but it points to the logstash-docs repo and frustrates the user. We need to make this better. See https://github.com/elastic/logstash-docs/pull/66#issuecomment-83341750

**Comment by ph** [comment]
Well, I love the idea of editing the plugins from the website this will probably help us a lot.
Maybe its only a matter of adding some metadata in the generated asciidoc with the link to the original repository.

**Comment by suyograo** [comment]
Fixed by @untergeek
