### ISSUE TITLE
DATE to include a DATE_INT (year/month/day) (1.4.2)

### ISSUE THREAD

**Issue by hevisko** [elastic/logstash#2866]
DATE in grok-patterns to please include something like:

DATE_INT %{YEAR}[./-]%{MONTHNUM}[./-]%{MONTHDAY}
DATE %{DATE_INT}|%{DATE_US}|%{DATE_EU}

This is to correctly match: 2014/09/03 00:11:05
else it only matches 14/09/03 00:11:05, and then any date function with YYYY gives me 0014 for a year ;(

**Comment by jordansissel** [comment]
My preference would be to remove DATE instead of growing the things it can match.

**Comment by suyograo** [comment]
Closing since we're not changing `DATE`
