### ISSUE TITLE
Apache common log format - bytes should be int?

### ISSUE THREAD

**Issue by colinmollenhour** [elastic/logstash#2868]
In experimenting with Kibana 3 I tried to do a histogram using the "mean" value of the apache combined log "bytes" value. However, I got this error:

ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]

Further searching reveals that perhaps this field should be cast to an int? Or should I add a filter to copy this value to say "bytes_int" and then build the histogram on that?

**Comment by StephenGoodall** [comment]
In the meantime, you could convert it using:
```
filter {
  mutate {
    convert => { "bytes" => "integer" }
  }
}
```

The documentation states:
>Valid conversion targets are: integer, float, string, and boolean.

That should work for you I think, not sure whether there would be a way to re-index the existing data though.

**Comment by colinmollenhour** [comment]
Thanks @StephenGoodall !

**Comment by purbon** [comment]
@colinmollenhour @StephenGoodall I agree this is something to be improved, as it makes not much of sense to me. Could you btw, open this issue at https://github.com/logstash-plugins/logstash-patterns-core ? this is the repo where all this patterns are living and would be awesome to have.

Then feel free to close this issue :+1: 

Thanks a lot for your time and contribution!

**Comment by colinmollenhour** [comment]
Thanks, I posted to an existing ticket.

Looks like another solution would be this PR: https://github.com/logstash-plugins/logstash-patterns-core/pull/102
