### ISSUE TITLE
Logstash [1.4.2] crashes with Lumberjack

### ISSUE THREAD

**Issue by cmahlig** [elastic/logstash#2875]
Hi !

I installed succesfully a standard Logstash client->server combination with ELK - it works fine, but i have one problem:

Sometimes (every 1-2 days) the Logstash server crashes with the following message:

Zlib::DataError: oversubscribed dynamic bit lengths tree
              finish at org/jruby/ext/zlib/ZStream.java:134
             inflate at org/jruby/ext/zlib/JZlibInflate.java:72
  compressed_payload at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:194
                feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:220
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:59

I hope someone can help or correct the problem or is it known ?!

**Comment by suyograo** [comment]
Hi, this was fixed in elastic/logstash-forwarder#384. LSF 0.4.0 already has this issue fixed

Dup of https://github.com/elastic/logstash/issues/1576
