### ISSUE TITLE
Incorrect Europe/Moscow timezone

### ISSUE THREAD

**Issue by EnotDuckWhyNot** [elastic/logstash#2877]
Hi, I'm parsing logs timestamp with Europe/Moscow timezone setting and get  -4 hour difference.
But since 26-10-2014 Russia switched to +3 standard offset. So this difference is incorrect now.

For instance:
in service log: 2014-11-28 00:00:15,212 === after parsing 2014-11-27T20:00:15.212Z
And should be:
in service log: 2014-11-28 00:00:15,212 === after parsing 2014-11-27T2**1**:00:15.212Z

Using logstash-1.4.2 latest release version

**Comment by wiibaa** [comment]
joda-time is responsible of timezone data and is bundled in jruby.
This seems fixed in jruby 1.7.17 per https://github.com/jruby/jruby/issues/2072
So logstash 1.5.0 release will contain the fix.
For 1.4.2 you could try replacing the jruby complete jar with a newer version.
