### ISSUE TITLE
add_tag and add_field does not resolve dynamic links in metrics filter

### ISSUE THREAD

**Issue by IldarMinaev** [elastic/logstash#2880]
I see that this is old issue (see https://logstash.jira.com/browse/LOGSTASH-1942)
Examples from documentation does not work (see http://logstash.net/docs/1.4.2/filters/metrics#add_field)

I have fixed this issue, please see my code:
https://github.com/IldarMinaev/files/blob/master/logstash/lib/logstash/filters/metrics.rb (all lines changed by me ended by comment #MINAEV)

**Comment by suyograo** [comment]
@IldarMinaev thanks, could you please open a pull request with your changes here? https://github.com/logstash-plugins/logstash-filter-metrics.

**Comment by IldarMinaev** [comment]
I added it. Thanks.
https://github.com/logstash-plugins/logstash-filter-metrics/pull/10
