### ISSUE TITLE
File Input Windows stops acceppting new files

### ISSUE THREAD

**Issue by MarkusMayer** [elastic/logstash#2882]
Hi,
I am using file input with logstash 1.5rc2 under windows to watch a directory of xml logs our app is writing to the file system (20 to approx. 1000k per XML file). The files are written by our app after the request has been processed and never changed again. 
Logstash is picking up the file, parses its filename and its (multiline) content and sends it off to elasticsearch for indexing. Parsing/Indexing of a couple of files works fine however after a couple of files have been processed, file input all of a sudden stops picking up any more files. 
When I try to shutdown logstash I get lots and lots of sincedb_write rename/synch failed: error messages. Just an example

sincedb_write rename/sync failed: C:\Users\y009324\xmlreq.new -> C:\Users\y009324\xmlreq: Permission denied - C:\Users\y009324\xmlreq.new or C:\Users\y009324\xmlreq {:level=>:warn}←[0m
sincedb_write rename/sync failed: C:\Users\y009324/.sincedb_8d0589aec078b447882a722be00c6dca.new -> C:\Users\y009324/.sincedb_8d0589aec078b447882a722be00c6dca: Permission denied - C:\Users\y009324/.sincedb_8d0589aec078b447882a722be00c6dca.new or C:\Users\y009324/.sincedb_8d0589aec078b447882a722be00c6dca {:level=>:warn}
sincedb_write rename/sync failed: C:\Users\y009324/.sincedb_cef44513da2c86f39bc79bf0aeac0bae.new -> C:\Users\y009324/.sincedb_cef44513da2c86f39bc79bf0aeac0bae: Permission denied - C:\Users\y009324/.sincedb_cef44513da2c86f39bc79bf0aeac0bae.new or C:\Users\y009324/.sincedb_cef44513da2c86f39bc79bf0aeac0bae {:level=>:warn}
sincedb_write rename/sync failed: C:\Users\y009324\xmlreq.new -> C:\Users\y009324\xmlreq: Permission denied - C:\Users\y009324\xmlreq.new or C:\Users\y009324\xmlreq {:level=>:warn}←[0m
sincedb_write rename/sync failed: C:\Users\y009324\xmlreq.new -> C:\Users\y009324\xmlreq: Permission denied - C:\Users\y009324\xmlreq.new or C:\Users\y009324\xmlreq {:level=>:warn}←[0m

Any idea what is going wrong here?

**Comment by jsvd** [comment]
@MarkusMayer I'll try to reproduce it tomorrow, sorry for hitting that bug.

**Comment by MarkusMayer** [comment]
Hi,
Thanks for your reply. I did some additional testing today. In my test sample are 3416 documents. The number of documents processed varies from run to run and doesn't seem to be reproducible. I checked the log with (-vv) and the glob discovery part in the beginning appears to be working correctly. It shows all documents of my testsample. The _discover_file that follows afterwards also shows all 3416 documents. Afterwards the log looks okay to me. After logstash stopped taking in new documents there are no errors showing in the log. One thing I noticed however is, that if I look at the sincedb after logstash stopped taking in new documents, the sincedb contains a couple less entries than were processed this also doesn't change if I wait for a couple of minutes and check again.
Shutting down logstash with CTRL-C from the console does not work 9 out of 10 times. I get lots of 

like:
sincedb_write failed: C:\Users\y009324\xmlreq.new: Permission denied - C:/Users/y009324/xmlreq.new
or
sincedb_write rename/sync failed: C:\Users\y009324\xmlreq.new -> C:\Users\y009324\xmlreq: Permission denied - C:\Users\y009324\xmlreq.new or C:\Users\y009324\xmlreq

Please let me know if I can provide any more testing / analysis ...
Thanks in advance and Bye,
Markus

**Comment by jsvd** [comment]
I was able to reproduce this "somewhat" consistently with a simple file input with 3 lines: when I exit logstash it get those permission denied errors..

**Comment by MarkusMayer** [comment]
Hi,
thanks for putting in the effort. I am not sure if there are 2 separate issues at work here or if one causes the other. As I see it:
- Logstash stops reading in files after lets say a few hundred fiels have been processed
- The sincedb permission denied message when shutting down logstash

The error message when shutting also seems to appear when working with a single file (instead of taking in a large number of small separate files).

If I can assist in testing this please let me know.
Bye,
Markus

**Comment by jsvd** [comment]
Sorry this is taking so long, I haven't been able to focus on this and debugging in this environment is very time consuming, hopefully next week I'll have news

**Comment by javalama** [comment]
Another showstopper for Windows...

**Comment by suyograo** [comment]
Fixed via 0.6.2 of ruby filewatch gem. This fix will be included in RC3
