### ISSUE TITLE
Logstash hangs with multiple sqs inputs

### ISSUE THREAD

**Issue by loganbhardy** [elastic/logstash#2884]
Logstash 1.4.2

Logstash seems stable with with a single SQS input but hangs after a short time if I add a two or more to my config. There is nothing written to the logs when this occurs. The cpu gets pegged at 100% and messages are no longer picked up from the SQS queue. I was told in passing by an engineer at Elasticon that lowering the number of threads on the SQS input could help but that had no effect. I've set threads as high as 8 with a single SQS input and things seemed stable. The problem only seems to occur if I add more than two SQS inputs. One other configuration of note is that I had to disable the SQS checksum validation in order to get around an issue there. (See issue #2190) I should also note that I am running two central logstash servers with this config. I have not yet tried this with Logstash 1.5. 

Here is my logstash config. 

input {
  sqs {
    region => "us-west-1"
    queue => "logstash-app1"
    access_key_id => "MYACCESSID"
    secret_access_key => "MYACCESSKEY"
    threads => 1
    use_ssl => false
  }
  sqs {
    region => "us-west-1"
    queue => "logstash-app2"
    access_key_id => "MYACCESSID"
    secret_access_key => "MYACCESSKEY"
    threads => 1
    use_ssl => false
  }
  sqs {
    region => "us-west-1"
    queue => "logstash-app3"
    access_key_id => "MYACCESSID"
    secret_access_key => "MYACCESSKEY"
    threads => 1
    use_ssl => false
  }
  sqs {
    region => "us-west-1"
    queue => "logstash-app4"
    access_key_id => "MYACCESSID"
    secret_access_key => "MYACCESSKEY"
    threads => 1
    use_ssl => false
  }
}
filter {
  if [type] == "app1" or "app2" or "app3" or "app4" {
    mutate {
      gsub => [ "message", "\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]", "" ]
    }
    grok {
      match => [ "message",  "(?m)%{TIMESTAMP_ISO8601:timestamp}\s-\s%{LOGLEVEL:level}:\s\[(?<label>[^\]]+)]\s(?<function>[^(]+)*\((?<file>[^:]+):%{INT:line}\)\s+%{GREEDYDATA:msg}" ]
      add_tag => [ "grokked" ]
    }
    date {
      match => [ "timestamp", "ISO8601" ]
      remove_field => [ "timestamp" ]
      add_tag => [ "dated" ]
    }
  }
}
output {
  elasticsearch {
    cluster => "es-metrics"
    host => "localhost"
    workers => 1
    document_id => "%{@uuid}"
  }
}

**Comment by suyograo** [comment]
@loganbhardy can you please try with LS 1.5 RC2?

**Comment by suyograo** [comment]
Could be related to https://github.com/logstash-plugins/logstash-input-sqs/issues/5

**Comment by ph** [comment]
@suyograo Yes this seems really related, but In the other case logstash never hang, the event performance dropped to 20% and it was after ~1h30mins.

@loganbhardy I'll give another shot with your config and I think we have talked at elasticon.

**Comment by loganbhardy** [comment]
@ph Yes, we spoke about the checksum issue at elasticon. :)

I've tested this with LS 1.5 RC2 and it's also not stable when I have more that one sqs input in my config. No errors are logged at all. 

I did find one positive result. I broke two sqs inputs out into two separate configs in conf.d and it seems to be running fine so far after about 15 minutes.  Everything in the config is identical but one config has only the first sqs input and the second config has the second sqs input.

**Comment by loganbhardy** [comment]
Update, logstash ran for about 20 minutes with two separate sqs inputs in two configs before hanging. My previous positive result was not actually positive at all.

**Comment by ph** [comment]
If you run logstash with a higher verbosity `--debug` do you get something in the output?
The stability issue worries me, we have seen performance drop in 1.5 that we are currently addressing but nothing about stability.

**Comment by PraveenJayakrishnakumar** [comment]
Hi,

Please try using these custom java Plugin for SQS, It is faster than default ruby plugin,  
https://logstash.jira.com/browse/LOGSTASH-1968

Praveen

**Comment by ph** [comment]
I wasn't aware of a java version of the SQS input, I'll check it out.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-sqs/issues/10. Let's continue the discussion there! :)
