### ISSUE TITLE
Output entire log into a message using multiline

### ISSUE THREAD

**Issue by Charles22** [elastic/logstash#2886]
Hello,

I am trying to input a file to logstash using a multiline codec or filter to allow me to add the log files contents into a single message. Parsing each line into a message is not useful considering many lines mean nothing independently. 

No matter what I try the output is the yellow text…

“Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}” 

and then nothing after, no error, no return to prompt and no desired output. I’ve posted about my problem but no one seems to be able to give me a straight answer. Is what I’m trying to do even possible? I want to import our applications log files into Kibana to use its query/search to help troubleshoot common problems.

I am using Logstash and Elasticsearch 1.5.0 with Kibana 4.
Here is my configuration file:
```
input {
  file {
    path => "/home/charles.moore/Logs/TestLog.log"
    start_position => "beginning"
    codec => multiline {
      pattern => "^\["
      negate => true
      what => "previous"
    }
  }
}

output {
  stdout { codec => rubydebug }
}
```

Thanks,

Charles

**Comment by colinsurprenant** [comment]
@Charles22 note that the file input will remember what it last read using its `sincedb`. so launching logstash multiple times using that config, your log file will only be read the first time. You can either add the options `sincedb_path => "/dev/null"` or use the `stdin` input while you test and just `cat` your file to logstash.
```sh
cat /home/charles.moore/Logs/TestLog.log | bin/logstash -f ...
```

If that does not help can you show/gist a sample of your logs?

**Comment by Charles22** [comment]
I'm still getting the same result, here is a sample of the log. 
https://gist.github.com/Charles22/abdfeb784e995f8d2f8a

**Comment by colinsurprenant** [comment]
@Charles22 are you sure your pattern is correct? using
```
pattern => "^["
negate => true
what => "previous"
```
does not seem to apply to your logs!?

**Comment by Charles22** [comment]
Tried your way but got..

```
The error reported is:
  premature end of char-class: /^[/m
```

We fixed that by changing it to `^\[`.  and its still stuck

**Comment by Charles22** [comment]
i chose something that wouldn't match so that all the lines would go together.

**Comment by Charles22** [comment]
Got it going, thank you for the help.
