### ISSUE TITLE
[ 1.5.0rc2 ] : "File descriptors are leaked when using HTTP" - Is it really gone?

### ISSUE THREAD

**Issue by chiriaev** [elastic/logstash#2887]
Guys, Hi. I just posted on a closed "issue" @ https://github.com/elastic/logstash/issues/1604 
It looks like there is still something wrong about the TCP input, I am afraid.

Regards, Andrei

**Comment by ph** [comment]
Yes it's possible that you found another memory leak, would you mind posting your configuration?
Concerning the http output if you are using elasticsearch RC2 we have stopped using ruby-ftw for this plugin so the leak from that library should be gone. This doesn't mean another one could sneak in.

**Comment by chiriaev** [comment]
Sure, as per the attached. Regards, Andrei
...
https://drive.google.com/file/d/0B5uNmWgizHGVZjl5alNCSWNTT2c/view?usp=sharing
...

**Comment by suraj-kamath** [comment]
Any updates on the above open issue ? I have experienced the file descriptor leak issue in the 1.4.1 version and have ideas to upgrading to 1.5.0 ! and the upgrade is going to be on a production server .So please let me know

Thanks
Suraj

**Comment by untergeek** [comment]
I presume this leak is addressed as there have been no updates, and we're on 2.2.0.

If you feel this is in error, please re-open this ticket, or open a new issue and reference this one.

Thanks.
