### ISSUE TITLE
Submitting an output for New Relic Insights

### ISSUE THREAD

**Issue by sschwartzman** [elastic/logstash#2888]
Hi Logstash Team,

I've written an output for LogStash that sends events into New Relic Insights. I would like to know how to go about getting this output contributed to the Logstash project.

Output: https://github.com/sschwartzman/logstash-output-newrelic
New Relic Insights: https://docs.newrelic.com/docs/insights/new-relic-insights/understanding-insights/new-relic-insights

Thanks in advance,
Seth

**Comment by suyograo** [comment]
Hi @sschwartzman thanks for your contribution to Logstash plugins! We can definitely help you add this plugin. Could you please review http://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html#_contributing_your_source_code_to_ulink_url_https_github_com_logstash_plugins_logstash_plugins_ulink_4 for guidelines to contributing a plugin to LS? 

Also, we strongly recommend adding tests to the plugins as noted in the above doc. Let me know if you need help writing tests

**Comment by sschwartzman** [comment]
Thanks, I'll look into writing the tests. As for the Code Review, how do we initiate that? Who in the community would do the reviewing?

Thanks,
Seth

**Comment by untergeek** [comment]
@sschwartzman Those of us on the Logstash team will certainly look it over.  We'll want to make sure it gets into the continuous integration testing, so we'll have a strong interest in making that work.

Others in the community will start looking it over too, perhaps.  We have several awesome individuals who go through the issues and help with them.  Chances are good they'll see this and take a peek.

**Comment by sschwartzman** [comment]
@suyograo @untergeek I've documented the code thoroughly and written some basic rspec tests. Do you need any more done to proceed?

**Comment by untergeek** [comment]
We'll take a look at it.  We may not get to it this week, as @suyograo is on vacation, but we'll get to it as soon as we can.  Thanks!

**Comment by sschwartzman** [comment]
Works for me, just let me know if you need anything else to proceed or anything needs fixing. @suyograo enjoy your vacation!

**Comment by untergeek** [comment]
@suyograo, since you're back from vacation, are we ready to move on this?

**Comment by suyograo** [comment]
@sschwartzman I created https://github.com/logstash-plugins/logstash-output-newrelic Can you create the initial PR there?

**Comment by sschwartzman** [comment]
Thanks @suyograo. It won't let me create a PR, any idea why?

**Comment by suyograo** [comment]
@sschwartzman can you try now?

**Comment by sschwartzman** [comment]
Yup, that worked, thanks!

**Comment by frutik** [comment]
Hi, All.

Pull request is still open. Any chances for it to be accepted?
