### ISSUE TITLE
The logstash would try reparse all the logs after each vagrant reload or host reboot

### ISSUE THREAD

**Issue by kamelzcs** [elastic/logstash#2890]
The ELK stack is installed in a `virtualbox` which is managed by `vagrant`.
I put all the files under the shared folder `/vagrant`

I suspect the reason is each `vagrant reload` would remount the shared folder `/vagrant`, then the recorded `since_db*` could not find out that these files have been parsed, then it would try to parse them again.

Is any way to deal with it?

---

`confs/logstash/logstash.conf` is as below:

```
input {
  file {
    path => "/vagrant/project/http/access_log*"
    type => "apache_access"
    start_position => beginning
  }
}
```

`Vagrant` is as below:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # set to false, if you do NOT want to check the correct VirtualBox Guest Additions version when booting this box
  if defined?(VagrantVbguest::Middleware)
    config.vbguest.auto_update = true
  end

  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 5601, host: 5601
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 9300, host: 9300
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", "2048"]
  end
  config.vm.provision "shell", inline: $script
  config.vm.provision "puppet", manifests_path: "manifests", manifest_file: "default.pp"

end
```

**Comment by ph** [comment]
Can you try to give a custom path to the `since_db` and point it to the shared folder?
```
input {
  file {
    path => "/vagrant/project/http/access_log*"
    type => "apache_access"
    start_position => beginning
    since_db_path => "/vagrant/sincedb"
  }
}
```
see http://logstash.net/docs/1.4.2/inputs/file#sincedb_path

**Comment by kamelzcs** [comment]
But there is a `/home/vagrant/.sincedb_74dc78074aa779929bf5c085a8a8b504`  file.

Why to manually refer to the shared folder?

**Comment by babadofar** [comment]
This has to do with using wildcards on the file input path in windows using Logstash 1.4.2. 
Upgrading to Logstash 1.5.0 RC4 fixes the issue.
