### ISSUE TITLE
Logstash consuming much memory | please provide solution

### ISSUE THREAD

**Issue by arifrahman4u** [elastic/logstash#2891]
Hi All,

using "logstash-1.4.2-1" and assigh 8G memory to logstash and fetching logs through logs-forwarder from only 6 server and total 12 logs file. After every 4-5 hour logstash OutOfMemory "java.lang.OutOfMemoryError: Java heap space" please provide any solution or any tuning parameeter.

Thanks alot in advance.

Rahman

**Comment by suyograo** [comment]
We need more information. Also please post this query on the logstash-users mailing list
