### ISSUE TITLE
Logstash fails to create an Index in Elasticsearch

### ISSUE THREAD

**Issue by imkarthikk** [elastic/logstash#2893]
I'm trying to setup a ELK stack on EC2, Ubuntu 14.04 instance. But everything install, and everything is working just fine, except for one thing.

Logstash is not creating an index on Elasticsearch. Whenever I try to access Kibana, it wants me to choose an index, from Elasticsearch. 

Logstash is in the ES node, but the index is missing. Here's the message I get:

`"Unable to fetch mapping. Do you have indices matching the pattern?"`

Am I missing something out? I followed this tutorial: [Digital Ocean][1]

**More Info:**
Here's the screenshot of the error I'm facing: 
![Logstash missing Indices in ES (Kibana4)][2]
Yet another screenshot:
![][3]

  [1]: https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04
  [2]: http://i.stack.imgur.com/JCuEc.png
  [3]: http://i.stack.imgur.com/WVU1c.png

**Comment by imkarthikk** [comment]
I hate doing this. Can someone please help me solve this? :)

**Comment by wiibaa** [comment]
Logstash will create indexes when pushing data to Elasticsearch. Ff there is no index, it means logstash did not process any data. Can you check logstash logs for any error or information

**Comment by imkarthikk** [comment]
Things have started becoming weird. Now from logstash-forwarder, I've started getting Failure to connect error: 
```shell
2015/03/26 10:53:33.559625 All prospectors initialised with 0 states to persist
2015/03/26 10:53:33.560066 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/03/26 10:53:33.560526 Connecting to [123.456.78.9]:5000 (123.456.78.9) 
2015/03/26 10:53:48.560942 Failure connecting to 123.456.78.9: dial tcp 123.456.78.9:5000: i/o timeout
2015/03/26 10:53:49.561227 Connecting to [123.456.78.9]:5000 (123.456.78.9) 
2015/03/26 10:54:04.561658 Failure connecting to 123.456.78.9: dial tcp 123.456.78.9:5000: i/o timeout
2015/03/26 10:54:05.562110 Connecting to [123.456.78.9]:5000 (123.456.78.9) 
```

**Comment by wiibaa** [comment]
Sorry for the question but Are you sure your logstash server is still up?

**Comment by imkarthikk** [comment]
Yup. It's still up and running. I tried installing new logstash on a dedicated new server, tried in on different IPs, and tried doing it over and over again thinking that I'm doing some mistake. But, nothing has worked till now. :/

**Comment by wiibaa** [comment]
Sorry but I do not use logstash-forwarder myself.
You can have a look to https://github.com/elastic/logstash-forwarder/issues/360 for similar issue.
Supposing it was working before, you would be in the case of "backpressure" where logstash fails to send data to Elasticsearch and this blocks up to senders thus causing the timeout...
Do you have anything in your logstash server logs that would indicate an error, like "failed to flush" ?

**Comment by imkarthikk** [comment]
After spending hours and hours on this issue. I figured out that the port 5000 was being used by some service that Im not able to identify. After changing the port to 5001, everything is working just fine. Thanks for the help @wiibaa
