### ISSUE TITLE
inputs rabbitmq plugin

### ISSUE THREAD

**Issue by plejik** [elastic/logstash#2895]
I create config for logstash rabbitmq plugin
        rabbitmq {
                host => "10.12.42.171"
                queue => "logstash-queue"
                passive => true
                durable => true
                user => "logstash"
                password => "logstash"
                vhost => "/logstash"
                key => "logstash-key"
                exchange => "logs"
        }
When start its try to connect to not existed queue. In docs i found that :
"
The default settings will create an entirely transient queue and listen for all messages by default. If you need durability or any other advanced settings, please set the appropriate options
"
and while i did not create by my hand, i will receive error that queue dosent exist.
Can someone tell me if rabbitmq plugins must create queue by himself or not?

**Comment by magnusbaeck** [comment]
With `passive => true` you have to predeclare the queue. If you don't want to do that, set it to false or just omit the setting (since it defaults to false).

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/28. Let's continue the discussion there! :)
