### ISSUE TITLE
Logstash often stops to send data to influxdb after influxdb shutdown/restart or network disconnect

### ISSUE THREAD

**Issue by evgygor** [elastic/logstash#2896]
Hi,
I have the cluster of 10 RHEL 6.4 servers.
9 servers with  logstash-1.5.0.rc2-1
1 server with logstash-1.5.0.beta1-1
All servers have logstash-output-influxdb.

I check the logstash behavior in case of influxdb crash/kill/shutdown for several minutes and restart, or network disconnect for server seconds or minutes
The results as follow:

1. Kill the influxdb for several minutes:
 --Message start to appear in logstash.log on each server

"{:timestamp=>"2015-03-25T14:21:13.456000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>Errno EBADF: Bad file descriptor - Bad file descr
iptor>, :backtrace=>["org/jruby/RubyIO.java:2099:in `close'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/connection.rb:176:in `connect'", "org/jruby/RubyArray.java:1613:
in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/connection.rb:142:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/agent.rb:421:in `c
onnect'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/pool.rb:49:in `fetch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0
.42/lib/ftw/agent.rb:418:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/agent.rb:283:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib
/ftw/agent.rb:181:in `post!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-influxdb-0.1.3/lib/logstash/outputs/influxdb.rb:237:in `post'", "/opt/logstash/vendor/bundle/jruby
/1.9/gems/logstash-output-influxdb-0.1.3/lib/logstash/outputs/influxdb.rb:231:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'",
 "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stu
d-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1
.9/gems/logstash-output-influxdb-0.1.3/lib/logstash/outputs/influxdb.rb:196:in `receive'", "/opt/logstash/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):4529:in `initialize'", "org/j
ruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:279:in `output'", "/opt/logstash/lib/logstash/pipeline.rb:235:in `outputworker'", "/opt/logstash/lib/logstash/pipe
line.rb:163:in `start_outputs'"], :level=>:warn}"

--Data doesn't sent to the influxdb.
Starting the influxdb:
 --The message stops to appear on all servers.
 --Several servers started to send data again to the influxdb as well. 
 --Other never recover the sending, only kill -9 and new start solved the issue.
 --Even /etc/init.d/logstash stop doesn't work as in the bug #2796.

I tried this test several times - each time another logstashes recovered and other stucks.
I checked the network status on servers with stucked logstash - the port 8086 (influxdb rest) was in close_wait status.

In the second test I shutdown the NIC for few minutes and started it back.
Same logstash's behavior found except one - no errors appeared in the log file at all.

**Comment by jordansissel** [comment]
Thanks for moving this to https://github.com/logstash-plugins/logstash-output-influxdb/issues/18! <3 I'll close this in favor of discussing the bug over there.
