### ISSUE TITLE
Changes with grok-matched fields in 1.5.0.rc2

### ISSUE THREAD

**Issue by dpb587** [elastic/logstash#2897]
Hello - when testing `1.5.0.rc2`, `grok` is now including unmatched, typed subpatterns which it previously didn't and I believe it still shouldn't. Using the same test configuration the additional, empty `duration` field is added with `1.5.0.rc2`...

    # 1.4.2
    $ ./logstash-1.4.2/bin/logstash --config testcase.conf 
    {"message":"test N/A"}
    {"message":"test 24.8ms","duration":24.8}

    # 1.5.0.rc2
    $ ./logstash-1.5.0.rc2/bin/logstash --config testcase.conf
    {"message":"test N/A","duration":0.0}
    {"message":"test 24.8ms","duration":24.8}

The following sample configuration was used as `testcase.conf`. It includes a commented out approach for backward compatibility that we're able to use for the short-term.

    input {
      generator {
        lines => [
          "test N/A",
          "test 24.8ms"
        ]
        count => 1
      }
    }

    filter {
      grok {
        match => [ "message", "test (N/A|%{BASE10NUM:duration:float}ms)" ]
      }

      # # backward compatible
      # grok {
      #   match => [ "message", "test (N/A|%{BASE10NUM:duration}ms)" ]
      # }
      # 
      # mutate {
      #   convert => [ "duration", "float" ]
      # }
  
      mutate { remove_field => [ "@version", "@timestamp", "host", "sequence" ] }
    }

    output { stdout { codec => json_lines } }

This issue affects us because we have conditionals relying on the presence of `duration` for later filter directives.

This is an unexpected change to us - I can't find references to it in `CHANGELOG` or in existing issues referencing `grok` - so I assume it is some sort of bug. I'd appreciate confirmation about this assessment though to know if this is actually a bug or if I'm just missing something else.

Thanks for your time!

**Comment by suyograo** [comment]
@dpb587 thanks. I was able to reproduce this regression. This was a side effect of the performance improvements we made in 1.5.0. Check https://github.com/jordansissel/ruby-grok/pull/11

I will make a fix soon. this should be available for 1.5 GA

**Comment by suyograo** [comment]
Verified works with jls-grok 0.11.2

**Comment by suyograo** [comment]
Added tests to cover it here: https://github.com/logstash-plugins/logstash-filter-grok/pull/21

**Comment by dpb587** [comment]
Thank you!
