### ISSUE TITLE
LogStash::Inputs::IMAP fails when header is nil

### ISSUE THREAD

**Issue by carloshanson** [elastic/logstash#2898]
I received the following error:

    Error: undefined method `encode' for nil:NilClass {:level=>:error}

The emails I was testing were Exchange Journals. The following is a nil header:

    X-MS-Journal-Report:

I added a check for nil to __transcode_to_utf8()__ in __/lib/logstash/inputs/imap.rb__:

```ruby
def transcode_to_utf8(s)
  if !s.nil?
    s.encode(Encoding::UTF_8, :invalid => :replace, :undef => :replace)
  end
end
```

**Comment by suyograo** [comment]
@carloshanson thanks, there's a fix here: https://github.com/logstash-plugins/logstash-input-imap/pull/5 but the contributor has not signed the CLA. 

I just left a comment there to follow up

**Comment by suyograo** [comment]
Merged
