### ISSUE TITLE
1.4.2 vs 1.5.0 kafka output performance regression

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#2899]
I am creating this issue here so we can better track it for the 1.5.0 release process. If we conclude that this is in fact a plugin-only regression then we'll move it to the proper logstash-*-kafka repo.

We got reports of a performance drop with the kafka output between logstash 1.4.2 and 1.5.0-rc2. The user reported using the logstash-kafka 0.6.2 plugins with logstash 1.4.2. I was in fact able to reproduce with:

- logstash 1.4.2
  - [logstash-kafka 0.6.2](https://github.com/joekiller/logstash-kafka/archive/v0.6.2.tar.gz)
  - [kafka_2.8.0-0.8.1](https://archive.apache.org/dist/kafka/0.8.1/kafka_2.8.0-0.8.1.tgz)
  - [jruby-kafka 0.2.1](https://rubygems.org/gems/jruby-kafka/versions/0.2.1-java)
 
vs

- logstash 1.4.2
  - [logstash-kafka 0.7.4 (latest)](https://rubygems.org/gems/logstash-kafka/versions/0.7.4-java) - with codec backport tweak + remove sprinf
  - [jruby-kafka 1.4.0 (latest)](https://rubygems.org/gems/jruby-kafka/versions/1.4.0-java)

vs

- logstash 1.5.0 (fix/perf_regression branch)
  - [logstash-output-kafka 0.1.8](https://rubygems.org/gems/logstash-output-kafka/versions/0.1.8)

using the following config:

```ruby
input {
 generator { count => 3000000 }
}

output {
  stdout{codec => dots}
  kafka {
    topic_id => "test-topic"
    compression_codec => "snappy"
    request_required_acks => 1
    serializer_class => "kafka.serializer.StringEncoder"
    request_timeout_ms => 10000
    producer_type => 'async'
    message_send_max_retries => 5
    retry_backoff_ms => 100
    queue_buffering_max_ms => 5000
    queue_buffering_max_messages => 10000
    queue_enqueue_timeout_ms => -1
    batch_num_messages => 1000
  }
}
```

using this command:
```sh
USE_RUBY=1 bin/logstash --quiet -f kafka.conf  | pv -Wbart > /dev/null
```

Version | Rate
---- | ----
1.4.2+0.6.2|2.86MiB 0:01:50 [26.6kiB/s] [26.6kiB/s]
1.4.2+0.7.4| 2.86MiB 0:02:22 [20.5kiB/s] [20.5kiB/s] 
1.5.0 | 2.86MiB 0:02:23 [20.4kiB/s] [20.4kiB/s]

We see that the regression actually occurs between version 0.6.2 and 0.7.4 in logstash 1.4.2. 

@joekiller @talevy can you confirm this?! Thoughts? If we agree this regression is somewhere in the plugin, we can move this issue in the proper repo.

**Comment by joekiller** [comment]
I'd suspect the sprintf primarily. Very busy recently so I'll take a shot
when I have a chance.

**Comment by suyograo** [comment]
Just as a reference, Kafka perf numbers from @TinLe

https://github.com/elastic/logstash/issues/2929#issuecomment-91370606

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-kafka/issues/20. Let's continue the discussion there! :)
