### ISSUE TITLE
graphite output doc looks incorrect

### ISSUE THREAD

**Issue by vortex314** [elastic/logstash#2902]
one of the parameters "metrics" is indicated as "hash" type, the example given is "array"
see documentation or source page

**Comment by wiibaa** [comment]
Thanks for noticing! for info, this is a still working but old style configuration when hash syntax was not supported in the syntax long ago. I have submitted a pull request in the plugin repository.
If you spot others issues can you please open them directly against the specific plugin repository like 
https://github.com/logstash-plugins/logstash-output-graphite/issues

**Comment by vortex314** [comment]
Philippe,
Thanks for the swift response !
I'm just struggling to get my performance logs into graphite, so I started doubting everything and looked deeper in the docs.
Continuing my search...

Lieven Merckx

**Comment by suyograo** [comment]
thanks for the PR @wiibaa https://github.com/logstash-plugins/logstash-output-graphite/pull/11
