### ISSUE TITLE
Populate a lookup table on the fly

### ISSUE THREAD

**Issue by dav3860** [elastic/logstash#2903]
We use logstash to collect web trafic logs among other things. Our application produces two kinds of logs. The trafic logs contain an application ID and an user-readable application name, and the other logs only refer to the application ID. The app ID isn't persistent. I mean that if we restart the server, the app ID changes. As we use Kibana to produce dashboards, we would like to add a field to the non-trafic logs, containing the application name, not only the application ID.
It would be easy if the application IDs were persistent, using the translate filter. However, as they often change, we need to build a lookup table on the fly, from application mappings found in the trafic logs.
Do you think it's possible ? Maybe with custom ruby code?

**Comment by talevy** [comment]
Either custom ruby code, or you can write your own filter plugin which maintains state somewhere, and can be used to decorate the events with the proper information.

**Comment by passing** [comment]
have a similar use case and found this plugin that should be able to solve this (but didn't try it out, yet):
https://github.com/logstash-plugins/logstash-filter-aggregate

**Comment by jordansissel** [comment]
> It would be easy if the application IDs were persistent, using the translate filter

The translate filter supports automatic refresh: https://github.com/logstash-plugins/logstash-filter-translate/blob/master/lib/logstash/filters/translate.rb#L68-L70 - is this not sufficient?

**Comment by ph** [comment]
I will close this the aggregate and the translate should be used in this case.
