### ISSUE TITLE
Installing Plugins from package. 

### ISSUE THREAD

**Issue by Seanmcn** [elastic/logstash#2907]
So I've installed the logstash package on Ubuntu using the repo here: http://logstash.net/docs/1.4.2/repositories

I'm wondering how I can install logstash plugins though, I figured navigating to /opt/logstash/ and doing the same "sudo bin/plugin install contrib" would work however that gives me the following:

```sh
Validating contrib
Plugin contrib does not exist
Installation aborted
```

Do I need to download these plugins from somewhere, is there another package? None of this seems to be documented anywhere.

**Comment by suyograo** [comment]
@Seanmcn instructions are here: http://logstash.net/docs/1.4.2/contrib-plugins.
