### ISSUE TITLE
Forwarding and multiline

### ISSUE THREAD

**Issue by j-maly** [elastic/logstash#2908]
I'd like to
1) watch a set of files (path defined with wildcards) on machine A
2) forward using logstash forwarder to machine B
3) process with logstash on machine B

All log files contain multiline messages which I would like to join. Where is the right place to do it? A filter or an input codec on machine A? or B? I want to do as little as possible of processing on A. 

If I have one lumberjack { } input on B and define a multiline codec there, am I in danger of messages originating from different files on A ending up in one multiline message on B? 

Apologies, but the documentation is note very clear on this.

**Comment by dpb587** [comment]
You might want to take a look at the [`stream_identity`](http://logstash.net/docs/1.4.2/filters/multiline#stream_identity) setting of the `multiline` filter. By default it relies on the combination of host name, path, and type to separate different streams whose lines can be combined. You should test it out of course, but it seems like it will work as you need.

**Comment by psampson** [comment]
I've tried using logstash-forwarder on my machine A to process on machine B, but even with a stream_identity keeping together machine/type/file, I still get mismatched messages from the same file when multiline logs are involved.  I haven't been able to work out a way to guarantee messages will be received in the same order they are sent in with logstash-forwarder and multiline messages.

**Comment by suyograo** [comment]
This is fixed by `stream_identity` and successfully being used by filebeat.
