### ISSUE TITLE
How do I distinguish logs output and logstash diagnostic messages when using stdout plugin?

### ISSUE THREAD

**Issue by fandrei** [elastic/logstash#2911]

**Comment by bigbo** [comment]
You ask is this it?

**Comment by bigbo** [comment]
You ask is this it?
output {
   stdout { codec => "rubydebug" }
}
or 
./bin/logstash agent -f xx.conf --log or --debug?

**Comment by fandrei** [comment]
@bigbo, nope. If I use stdout plugin all log output goes to the console, as well as logstash own diagnostic messages. How can I distinguish one from another?

**Comment by dougmcclure** [comment]
it'd be great to have a flag to filter in/out various types of debug messages - inputs, filters, outputs, pipeline, plugin startup, other...

**Comment by suyograo** [comment]
This is now possible in 5.0 with log4j logging improvements
