### ISSUE TITLE
Elasticsearch Input filter needs to be able to limit queries to only the latest index

### ISSUE THREAD

**Issue by elvarb** [elastic/logstash#2912]
It seems that the Elasticsearch Input is designed to pull all data from one cluster.

To be able to only search x amount of minutes/hours/days from now would open up the possibility to use Logstash to query log data stored in Elasticsearch and either alert on them or create a summary.

Using the Kibana Index config you could specify a Index pattern like "[logstash-]YYYY.MM.DD". Then you config it to run every x and then y amount back (most cases it would be the same value). For example, run every 10 minutes, search from "now" to "-10m", with the query "level:error".

Then using count of the returned value and conditionals that if this level is above x then output to email.

Another use case for this would be to create daily reports.

**Comment by untergeek** [comment]
There's an easy way to do this right now, and it's by using Aliases.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/13. Let's continue the discussion there! :)
