### ISSUE TITLE
Way to output date in Date filter

### ISSUE THREAD

**Issue by davmrtl** [elastic/logstash#2913]
In my scenario, the "timestamp" of the syslog lines Logstash receives is in UTC and we use the event "timestamp" in the Elasticsearch output:

    output {
        elasticsearch {
            embedded => false
            host => localhost
            port => 9200
            protocol => http
            cluster => 'elasticsearch'
            index => "syslog-%{+YYYY.MM.dd}"
        }
    }

My problem is that at UTC midnight, Logstash sends log to different index before the end of the day in out timezone (GMT-4 => America/Montreal) and the index has no logs after 20h (8h PM) because of the "timestamp" being UTC.

We've done a work arround to convert the timezone but we experience a significant performance degradation:

    filter {
        mutate {
            add_field => {
                # Create a new field with string value of the UTC event date
                "timestamp_zoned" => "%{@timestamp}"
            }
        }
        
        date {
            # Parse UTC string value and convert it to my timezone into a new field
            match => [ "timestamp_zoned", "yyyy-MM-dd HH:mm:ss Z" ]
            timezone => "America/Montreal"
            locale => "en"
            remove_field => [ "timestamp_zoned" ]
            target => "timestamp_zoned_obj"
        }
        
        ruby {
            # Output the zoned date to a new field
            code => "event['index_day'] = event['timestamp_zoned_obj'].strftime('%Y.%m.%d')"
            remove_field => [ "timestamp_zoned_obj" ]
        }
    }
    
    output {
        elasticsearch {
            embedded => false
            host => localhost
            port => 9200
            protocol => http
            cluster => 'elasticsearch'
            # Use of the string value
            index => "syslog-%{index_day}"
        }
    }

Is there a way to optimize this config?

**Comment by magnusbaeck** [comment]
Related Stackoverflow question: http://stackoverflow.com/questions/29302444/convert-timestamp-timezone-in-logstash-for-output-index-name

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-date/issues/22. Let's continue the discussion there! :)

**Comment by rp-happiestbaby** [comment]
Im trying to do same but i get an error 'Ruby exception occurred: undefined method `strftime' for 2017-06-02T01:04:11.000Z:LogStash::Timestamp'
Please help in this 
Im running logstash 5.4
