### ISSUE TITLE
Writing a logstash plugin, can someone give me some guidance on how the test framework works?

### ISSUE THREAD

**Issue by stephan-x-liu** [elastic/logstash#2915]

**Comment by talevy** [comment]
here are some example plugins with some documentation in the READMEs 
on how testing works:

https://github.com/logstash-plugins?query=example

**Comment by stephan-x-liu** [comment]
I was hoping to see examples of how the HTTP plugin was tested, but there doesn't seem to be tests for that....

**Comment by ph** [comment]
@stephan-x-liu sadly not all the plugins have tests, this is one of our goal in the short term, I suggest you look at other plugins like the elasticsearch output https://github.com/logstash-plugins/logstash-output-elasticsearch. You can also look at http://betterspecs.org/, this will give you some general guidance for writing test.

**Comment by ph** [comment]
@stephan-x-liu I have created a issue to tackle this task, we will see if we can land it for 2.0.
