### ISSUE TITLE
logstash 1.4.2 hangs after "invalid byte sequence in UTF-8", but only with init script 

### ISSUE THREAD

**Issue by StefanSa** [elastic/logstash#2918]
Hi,
logstash hangs after "invalid byte sequence in UTF-8" but "only" with original init script on CentOS 7.
Interestingly, when i start logstash in the console is everything OK.
What is the difference between the start of the init script and the start driekt in the console?
I think this is a init script problem. Any help here ?

**Comment by joshuar** [comment]
Sounds like a locale problem.  I'm guessing you've installed Logstash from an rpm?  Can you run `localectl` and check the output lists a UTF-enabled locale?

**Comment by StefanSa** [comment]
Hi, this rpm is from the elasticsearch repo.
With "localectl" i get this here.
root@logger01]# localectl
   System Locale: LANG=de_DE.UTF-8
       VC Keymap: de
      X11 Layout: de
     X11 Variant: nodeadkeys

**Comment by StefanSa** [comment]
OK with -vv i get this error message.
```
The error reported is:
  invalid byte sequence in UTF-8
org/jruby/RubyString.java:3270:in `index'
/opt/logstash/vendor/bundle/jruby/1.9/gems/treetop-1.4.15/lib/treetop/runtime/compiled_parser.rb:98:in `has_terminal?'
/opt/logstash/lib/logstash/config/grammar.rb:262:in `_nt_whitespace'
org/jruby/RubyKernel.java:1521:in `loop'
/opt/logstash/lib/logstash/config/grammar.rb:261:in `_nt_whitespace'
/opt/logstash/lib/logstash/config/grammar.rb:125:in `_nt_comment'
org/jruby/RubyKernel.java:1521:in `loop'
/opt/logstash/lib/logstash/config/grammar.rb:123:in `_nt_comment'
/opt/logstash/lib/logstash/config/grammar.rb:224:in `_nt__'
org/jruby/RubyKernel.java:1521:in `loop'
/opt/logstash/lib/logstash/config/grammar.rb:222:in `_nt__'
/opt/logstash/lib/logstash/config/grammar.rb:55:in `_nt_config'
/opt/logstash/vendor/bundle/jruby/1.9/gems/treetop-1.4.15/lib/treetop/runtime/compiled_parser.rb:18:in `parse'
/opt/logstash/lib/logstash/pipeline.rb:15:in `initialize'
/opt/logstash/lib/logstash/agent.rb:112:in `execute'
/opt/logstash/lib/logstash/runner.rb:168:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/task.rb:12:in `initialize'
```

**Comment by jordansissel** [comment]
@StefanSa can you attach all of your logstash configs on gist.github.com and put the link to it here?

**Comment by StefanSa** [comment]
Hi jordan,
you can close this ticket, i move from Centos 7 to FreeBSD 10 with out any errors.

**Comment by gonza8888** [comment]
My environment:   Ubuntu 14.04— Elasticsearch 1.4.4, Logstash 1.5.0, and Kibana 4
When I add the config file 10-syslog.conf, i get the following error in /var/log/logstash/logstash.log

```
{:timestamp=>"2015-08-25T15:49:30.806000-0300", :message=>"The error reported is: \n  invalid byte sequence in UTF-8"}
```
And here is the code of the config file. If someone need more log information, please tell me how to execute with -vv option.
```
root@logstash4:/etc/logstash/conf.d# cat 10-syslog.conf 
filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    syslog_pri { }
    date {
        locale => en
        match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
        remove_field => ["timestamp"]
    }
  }
}
```

**Comment by untergeek** [comment]
Logstash 1.4.x is no longer supported.  If this persists with 2.2.0, please open a new ticket and reference this one.
