### ISSUE TITLE
Beginning guide for writings tests for our plugins.

### ISSUE THREAD

**Issue by ph** [elastic/logstash#2919]
We have a really nicely written guide to write new plugins for logstash 1.5 but they don't cover how to write tests. I know writing tests is something we see really important as a project and we should encourage people to write them, but explaining testing isn't easy.

Since we are refactoring our tests suite and writing new helpers to help us, the developer, to tests against the pipeline we should take a few time to write some documentation or best practices so everyone can improve their code and support people to add them in their pull request. 

Ref: https://github.com/elastic/logstash/issues/2915

**Comment by suyograo** [comment]
Addressed in https://www.elastic.co/guide/en/logstash/master/contributing-patch-plugin.html
