### ISSUE TITLE
Timestamp kept last year "year" for default

### ISSUE THREAD

**Issue by plarivee** [elastic/logstash#2921]
I discovered after closing my 2014-* indices in ES that Logstash was still sending some data to them. I pinpoint the indices used and think I found the problem.

- servers with rsyslog sends data to a LS-shipper.  Format is 
"timestamp" => "Mar 30 13:36:54",

I don't have a debug dump since sdtout {} is not always active.

- The instance of the logstash shipper was last started in 2014

Once I restarted logstash to activate stdout {} , logs started to go into the 2015- indices.

So seems like that is the problem.

ii  logstash                          1.4.1-1-bd507eb               An extensible logging pipeline
ii  logstash-contrib                  1.4.1-1-6e42745               Community supported plugins for Logstash
DISTRIB_DESCRIPTION="Ubuntu 12.04.2 LTS"

![screen shot 2015-03-30 at 1 27 00 pm](https://cloud.githubusercontent.com/assets/4006309/6902869/844d6ea0-d6e4-11e4-8264-0ac02b9fc06c.png)
![screen shot 2015-03-30 at 1 27 20 pm](https://cloud.githubusercontent.com/assets/4006309/6902870/844f10e8-d6e4-11e4-99e4-e76e15ab5427.png)

**Comment by untergeek** [comment]
Thank you for so thoroughly documenting this, and even including screen captures.  You are not the first to report this.  It was first reported in #2306, and has since been migrated to https://github.com/logstash-plugins/logstash-filter-date/issues/3

Thanks!
