### ISSUE TITLE
rake packaging error with git dependencies in Gemfle

### ISSUE THREAD

**Issue by reecemarkowsky** [elastic/logstash#2923]
Hi.  I believe this is an problem on all branches.   This issue is raised after testing on the master branch.  When trying to reference jruby-kafka and logstash-output-kafka as git repos in gemfile so that I can then work on customizing forked repos and then package logstash using rake.  when i use rake artifact:tar or rake artifact:freeze-defaults-gemfile i encounter an error.  (attached pasetbin).  I have seen this error mentioned before but would like to know if there is a workaround for this as its blocking development without manually hacking together logstash package.  Here is my Gemfile and the error i get from rake.  Thanks!!

http://pastebin.com/fQCKMDbi

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by ph** [comment]
I think we can safely close this one.
