### ISSUE TITLE
Deleted indices come out again some time after being removed

### ISSUE THREAD

**Issue by shichao-an** [elastic/logstash#2926]
Hi,

Every time the disk usage warning emerges on the logstash server, I use [curator](https://github.com/elastic/curator) to delete indices older than 40 days with `curator delete --older-than 40` and confirm it by looking at `/data/elasticsearch/elasticsearch/nodes/0/indices` files. But the next time the warning comes out, I always find the deleted indices come out. I use logstash-forwarder to ship logs to this server.

Do you have any idea why it happens?

**Comment by untergeek** [comment]
I've had this happen to me.  For me, I had cron jobs which responded late, sometimes weeks late.  This generated log entries in the past, which opened up the "old" indices again.

The easiest way to see what's going on with these re-opened, old indices is to see what's inside them.

You could use Kibana 4 to browse the entries, or you could do a curl call to search those indices specifically:

```
curl -XGET 'localhost:9200/logstash-YYYY.MM.DD/_search?pretty' -d '
{
    "query" : {
        "match_all" : {}
    }
}'
```

Just be sure to replace `YYYY.MM.DD` with the actual timestamp on the index.  You should see what entries are there.  That should help to narrow it down.

**Comment by shichao-an** [comment]
OK. Since I've deleted the indices this time, maybe I have to wait for the old indices to show up again and run the curl to see what's in inside. Thanks.

**Comment by shichao-an** [comment]
The old logs showed up again. I checked some of them by index name, e.g. logstash-2015.01.03, it seems they are just old logs, but "received_at" is some later value, e.g. "2015-04-01 12:56:36 UTC".

**Comment by shichao-an** [comment]
It seems these old logs (from logstash-2014.11.25 to logstash-2015.02.19) were generated on Apr 1 in 6 hours. Is there any other way to set retention? like setting TTL?

Since I'm not very familiar with ES indexing and templating, so I Googled a while for ttl solutions, here's what i do for a try:

Create a json file `logstash-template.json`:

```
{
    "template": "logstash-*",
    "mappings": {
        "_default_": { 
            "_ttl": { "enabled": true, "default" : "40d" }
        }
    }
}
```

And run the command:

    curl -XPUT 'http://localhost:9200/_template/template_logstash/' -d @logstash-template.json

I'm not sure whether this will work. Any idea? Thanks

**Comment by untergeek** [comment]
TTL is a very, very bad idea for time-series data.  For more information, read: http://www.elastic.co/guide/en/elasticsearch/client/curator/current/_q_can_i_delete_only_certain_data_from_within_indices.html

**Comment by untergeek** [comment]
This indicates that you have very old log data coming into your system (again).  You should find out from where.  Are you tailing log files?  Is is possible that old log files are being re-read?  If using file input, what does your configuration block look like?

**Comment by shichao-an** [comment]
I use the problematic `nginx-access-main` type for example. 
The logstash server has this config for input:

```
input {
  lumberjack {
    port => 5000
    type => "logs"
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  }
}
```
The grok filter is:

```
filter {
  if [type] == "nginx-access-main" {
    grok {
      match => { "message" => "%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] \"(?:%{WORD:verb} %{URIPATHPARAM:request}(?: HTTP/%{NUMBER:httpversion})?|-)\" %{NUMBER:response} (?:%{NUMBER:bytes}|-)" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
  }

...
}
```
I use logstash-forwarder (very old deb package from elasticsearch) to ship logs, its `/etc/logstash-forwarder` is like this:

```
{
  "network": {
    "servers": [
      "logstash.example.com:5000"
    ],
    "timeout": 15,
    "ssl ca": "/etc/ssl/certs/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [
            "/mnt/log/nginx/example.com-https-access.log"
        ],
      "fields": {
            "type": "nginx-access-main"
        }
    }
   ]
}
```

**Comment by untergeek** [comment]
I would update logstash-forwarder first.  It was, from the beginning, labelled experimental.  We have released version 0.4.0 recently.  It solves many of the issues users of earlier versions were seeing.

If you're ingesting old logs still, chances are it's at that level.

**Comment by shichao-an** [comment]
OK, I'll try to upgrade logstash-forwarder first and see. Thanks

**Comment by suyograo** [comment]
Closing this, please reopen if you see this again
