### ISSUE TITLE
File Input should have option to spawn multiple reader threads

### ISSUE THREAD

**Issue by willhughes** [elastic/logstash#2930]
Scenario: I have a lot of different files that logstash monitors.  (One logfile per webserver) 
If, for whatever reason, logstash crashes or I need to reboot - it can take a very long time (hours, or more) for logstash to be able to catch up again, as it reads one file at a time per input. 

The current solution seems to be to create multiple file inputs, which does work. However this creates a management overhead (many file input entries). If I use any kind of 'elastic' capability to spin up/down servers on demand managing (and restarting) logstash configuration becomes particularly difficult. 

Suggested solution: Provide a 'readers' option that lets me specify the number of readers I'd like logstash to spin up.

**Comment by markwalkom** [comment]
Thanks for the suggestion.

We've split the plugins out to their own repo, could you please replicate this over at https://github.com/logstash-plugins/logstash-input-file/issues?

**Comment by willhughes** [comment]
Sure, sorry - didn't see that.
