### ISSUE TITLE
logstash-core jruby-httpclient runtime dependency required?

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#2931]
It looks like the jruby-httpclient gem is not used in logstash-core but yet it is listed as a runtime dependency [in the gemspec](https://github.com/elastic/logstash/blob/master/logstash-core.gemspec#L59)

Can we remove this dependency?

This is related to logstash-plugins/logstash-output-elasticsearch_http#2

**Comment by ph** [comment]
I think we can remove this dependency, I do not recall any plugin using this?

**Comment by purbon** [comment]
If is not used in the core, should go to each plugins, +1 on removing stale dependencies.
