### ISSUE TITLE
_sincedb_write failed: /dev/null.new: Permission denied

### ISSUE THREAD

**Issue by rmoff** [elastic/logstash#2935]
$ ./bin/logstash -V
logstash 1.5.0.rc2

On shutdown (Ctrl-C) on Mac, I get this warning: 

    SIGINT received. Shutting down the pipeline. {:level=>:warn}
    _sincedb_write failed: /dev/null.new: Permission denied - /dev/null.new {:level=>:warn}

Is this a benign warning, or have I got something setup wrong? 

Thanks.

**Comment by ph** [comment]
@rmoff would you mind posting your configuration?
Is your **sincedb_path** is set to `/dev/null` or something else?

**Comment by ph** [comment]
@rmoff nevermind, this look like a regression in the library we are using to tail the files.

**Comment by ralphbellofatto** [comment]
Is something being changed to fix this problem, or is this directions for a user workaround?  If it is a user level workaround what does the user have to change?

The release candidate appears to be a bit useless when doing file io, as it won't remember the sincedb info.

**Comment by suyograo** [comment]
@ralphbellofatto we are working on a fix here: https://github.com/jordansissel/ruby-filewatch/pull/54

We will be releasing a RC3 soon, or you can just update the file input using `bin/plugin update`

**Comment by suyograo** [comment]
Fixed in 0.6.2 of filewatch

**Comment by ph** [comment]
@ralphbellofatto we just pushed a new version of the plugin, if you do `bin/plugin update logstash-input-file` you should get the updated plugin.

**Comment by rmoff** [comment]
Can confirm this issue is fixed after updating the plugin. Thanks @ph, @suyograo.

**Comment by jsvd** [comment]
:fireworks: thanks for testing @rmoff
