### ISSUE TITLE
Geoip's "field" doesn't work as expected for "location"

### ISSUE THREAD

**Issue by volter** [elastic/logstash#2938]
What is happening:

If you don't specify "longitude" and "latitude" in "fields", "location" is not created, even if you requested it in "fields".

Why is it happening:

"location" is constructed from "longitude" and "latitude" property of the event.

Expected behaviour:

Construct "location" regardless whether "longitude" and/or "latitude" are specified in "fields".

**Comment by untergeek** [comment]
Please recreate this issue at https://github.com/logstash-plugins/logstash-filter-geoip, which is the proper place for this issue report.
