### ISSUE TITLE
Internet explorer causes logstash to crash

### ISSUE THREAD

**Issue by gunnarvelle** [elastic/logstash#2940]
I run logstash as a service using nssm on a windows server 2012 r2. The service is started with the arguments `agent -f logstash.conf -l logstash.log web -p 80`. When i try to access the server with Internet Explorer the process dies with the message:

Errno::ECONNABORTED: Software caused connection abort - An established connection was aborted by the software in your host machine
            sysread at org/jruby/RubyIO.java:3016
               read at C:/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:243
  read_http_message at C:/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/protocol.rb:30
  handle_connection at C:/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/rack/handler/ftw.rb:125
  handle_connection at C:/logstash/logstash-1.4.2/lib/logstash/kibana.rb:12
                run at C:/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/rack/handler/ftw.rb:107

Using any other browser works as expected. 

If I run agent and web as separate processes this happens a lot less, but still happens. Agent survives and web dies. Fortunately nssm restarts the process by default so the downtime is not long. Still this is irritating.

Regards 
Gunnar Velle

**Comment by suyograo** [comment]
Logstash `web` sub command has been removed. You can start Kibana using the instructions here: https://www.elastic.co/downloads/kibana
