### ISSUE TITLE
Very difficult to find failed events from elasticsearch bulk requests

### ISSUE THREAD

**Issue by dpb587** [elastic/logstash#2941]
Hi - when testing `1.5.0.rc2`, we're not able to reasonably investigate events which elasticsearch rejected due to mapping problems when using bulk methods. Rather than emitting a single error message about the problematic event, logstash appears to be emitting (verbosely) every item it included in the bulk request regardless of whether that individual item failed. For example, if I have an index with a field configured as a `date` type and try to send the following two records, it logs the following...

    $ ./logstash-1.5.0.rc2/bin/logstash --config testcase.conf
    {"dateful":"2015-04-01T02:04:08Z"}
    {"dateful":"stringful"}
    failed action with response of , dropping action: ["index", {:_id=>nil, :_index=>"test-index", :_type=>"test-type"}, #<LogStash::Event:0x2418b83c @metadata_accessors=#<LogStash::Util::Accessors:0x3c24a677 @store={"retry_count"=>0}, @lut={}>, @cancelled=false, @logger=#<Cabin::Channel:0x39e5e7f5 @metrics=#<Cabin::Metrics:0x58dd61ad @metrics_lock=#<Mutex:0x415373df>, @metrics={}, @channel=#<Cabin::Channel:0x39e5e7f5 ...>>, @subscriber_lock=#<Mutex:0x7002e29>, @level=:warn, @subscribers={15752=>#<Cabin::Outputs::IO:0x222f60ee @io=#<IO:fd 1>, @lock=#<Mutex:0x783832ff>>}, @data={}>, @data={"dateful"=>"2015-04-01T02:04:08Z"}, @metadata={"retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0xaac912e @store={"dateful"=>"2015-04-01T02:04:08Z"}, @lut={"host"=>[{"dateful"=>"2015-04-01T02:04:08Z"}, "host"], "sequence"=>[{"dateful"=>"2015-04-01T02:04:08Z"}, "sequence"], "@version"=>[{"dateful"=>"2015-04-01T02:04:08Z"}, "@version"], "@timestamp"=>[{"dateful"=>"2015-04-01T02:04:08Z"}, "@timestamp"]}>>] {:level=>:warn}
    failed action with response of , dropping action: ["index", {:_id=>nil, :_index=>"test-index", :_type=>"test-type"}, #<LogStash::Event:0x2dac70e @metadata_accessors=#<LogStash::Util::Accessors:0x4eccf28f @store={"retry_count"=>0}, @lut={}>, @cancelled=false, @logger=#<Cabin::Channel:0x39e5e7f5 @metrics=#<Cabin::Metrics:0x58dd61ad @metrics_lock=#<Mutex:0x415373df>, @metrics={}, @channel=#<Cabin::Channel:0x39e5e7f5 ...>>, @subscriber_lock=#<Mutex:0x7002e29>, @level=:warn, @subscribers={15752=>#<Cabin::Outputs::IO:0x222f60ee @io=#<IO:fd 1>, @lock=#<Mutex:0x783832ff>>}, @data={}>, @data={"dateful"=>"stringful"}, @metadata={"retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x43b0c8ab @store={"dateful"=>"stringful"}, @lut={"host"=>[{"dateful"=>"stringful"}, "host"], "sequence"=>[{"dateful"=>"stringful"}, "sequence"], "@version"=>[{"dateful"=>"stringful"}, "@version"], "@timestamp"=>[{"dateful"=>"stringful"}, "@timestamp"]}>>] {:level=>:warn}

Most notably, not only is the bad, `stringful` event logged, but so is the one with the valid date. But of course, the valid date was successfully indexed so it's just confusing and distracting to see in the logs...

    $ wget -qO- localhost:9200/test-index/test-type/_search | jq -c '.hits.hits[] | ._source'
    {"dateful":"2015-04-01T02:04:08Z"}

I realize this sort of bulk action handling/logging is new to 1.5, but with the current logging approach it's near impossible to track down our bad parse rules or event messages from logstash's logs. The output from the trivial example is a bit messy as it is, but in production where we're bulking hundreds of documents with dozens of fields the logs get far more crazier and unreadable when trying to track down a single bad event from hundreds. These verbose log messages also tend to temporarily slow down the logstash process while it spends time serializing and dumping these (very) large messages to disk, significantly affecting our overall parsing rates.

In the short-term, we're sort of able to work around this a couple ways, but with both methods we lose track of the original event which is helpful for correcting and writing updated tests against. First, we can enable `DEBUG`-level logging in elasticsearch for the `action.bulk` logger (although we generally want to avoid leaving debug on in prod). Second, if we notice we're having a surge of bad events come through we can manually run `tcpdump` between logstash and elasticsearch to capture the same sort of details without messing with our elasticsearch cluster:

    $ tcpdump -i lo -nn -A -s0 src port 9200 2>/dev/null | grep errors | grep -v '"errors":false' \
      | ./jq --unbuffered '.items[] | to_entries | select(.[0].value.error != null) | from_entries'
    {
        "create": {
            "_id": "AUxMJ4LKwaeWb8FE2u8A",
            "_index": "logstash-2015.03.24",
            "_type": "ci_log4net",
            "error": "MapperParsingException[failed to parse [Dispatched]]; nested: MapperParsingException[failed to parse date field [N/A], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: \"N/A\"]; ",
            "status": 400
        }
    }

It would be much more convenient for us if logstash was 1) only logging bulk items which failed and 2) if those logged events were more concise (rather than seemingly having a full copy of the event for every field it contains).

Here's the mapping and logstash config I used for the example test case.

    $ curl -X POST 127.0.0.1:9200/test-index -d '
      { "mappings": { "_default_": { "properties": {
        "dateful": {
            "type": "date",
            "format": "dateOptionalTime" } } } } }'
    
    $ cat testcase.conf
    input {
      generator {
        lines => [
          '{"dateful":"2015-04-01T02:04:08Z"}',
          '{"dateful":"stringful"}'
        ]
        count => 1
        codec => json
      }
    }

    filter { mutate { remove_field => [ "@version", "@timestamp", "host", "sequence" ] } }

    output {
      stdout { codec => json_lines }
      elasticsearch {
        protocol => "http"
        index => "test-index"
        index_type => "test-type"
        manage_template => false
      }
    }

I'm not entirely sure if this is a bug report or a feature request, but I appreciate the consideration regardless!

**Comment by untergeek** [comment]
Please move this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch

**Comment by dpb587** [comment]
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/98
