### ISSUE TITLE
1.5.0.rc2 output issue LogStash::Json::GeneratorError: Cannot find Serializer for class: org.jruby.Ruby Object

### ISSUE THREAD

**Issue by marantz2015** [elastic/logstash#2945]
LogStash::Json::GeneratorError: Cannot find Serializer for class: org.jruby.Ruby
Object
     jruby_dump at D:/elk/logstash-1.5.0.rc2/lib/logstash/json.rb:45
        to_json at D:/elk/logstash-1.5.0.rc2/lib/logstash/event.rb:152
         encode at D:/elk/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logsta
sh-codec-json-0.1.6/lib/logstash/codecs/json.rb:44
        receive at D:/elk/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logsta
sh-output-kafka-0.1.8/lib/logstash/outputs/kafka.rb:165
         handle at D:/elk/logstash-1.5.0.rc2/lib/logstash/outputs/base.rb:88
     initialize at (eval):28
           call at org/jruby/RubyProc.java:271
         output at D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:279
   outputworker at D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:235
  start_outputs at D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:163
[33mUDP listener died {:exception=>#<SocketError: recvfrom: name or service not
 known>, :backtrace=>["D:/elk/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/lo
gstash-input-udp-0.1.3/lib/logstash/inputs/udp.rb:79:in `udp_listener'", "D:/elk
/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.3/lib/lo
gstash/inputs/udp.rb:49:in `run'", "D:/elk/logstash-1.5.0.rc2/lib/logstash/pipel
ine.rb:174:in `inputworker'", "D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.r
b:168:in `start_input'"], :level=>:warn}[0m

**Comment by ph** [comment]
@marantz2015 Could you paste your configuration? From the error message you are using the kafka plugins..

**Comment by colinsurprenant** [comment]
@marantz2015 as @ph said, could you share your config and also sample logs that ca reproduce the problem?

In fact it should be possible to reproduce the problem by using the stdout output with the json_lines codec since the event will go through the same event.to_json method. Now what would be really useful is  to have sample data will trigger the problem.

**Comment by marantz2015** [comment]
many thanks for help,my configuration is:
input {
    udp {
      port => 9996
      codec => netflow {
        definitions => "D:\elk\logstash-1.5.0.rc2\vendor\bundle\jruby\1.9\gems\logstash-codec-netflow-0.1.4\lib\logstash\codecs\netflow\netflow.yaml"
        versions => [5]
      }
    }
}

output {
    stdout {}
      kafka {
        broker_list => "127.0.0.1:9092"  
        topic_id => "test"
      }
}

**Comment by marantz2015** [comment]
The same issue is follow configuration ,but in logstash-1.4.2 use  follow configuration is OK!
input {
    udp {
      port => 9996
      codec => netflow {
        definitions => "D:\elk\logstash-1.5.0.rc2\vendor\bundle\jruby\1.9\gems\logstash-codec-netflow-0.1.4\lib\logstash\codecs\netflow\netflow.yaml"
        versions => [5]
      }
    }
}

output {

      redis {
        host => "127.0.0.1"
        port => 6379
        data_type => "list"
        key => "tomcat"
    }
}

**Comment by colinsurprenant** [comment]
@marantz2015 ok, thanks. looks like an issue with the netflow codec. did you try with 
```ruby
output {
  stdout {
    codec => json_lines
  }
}
```
in 1.5.rc2 ?

**Comment by colinsurprenant** [comment]
I suspect [this Time object assignment](https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/lib/logstash/codecs/netflow.rb#L117) might be the issue. Will need to test that.

@marantz2015 would you happen to have sample netflow data you could share?

**Comment by marantz2015** [comment]
hi,I use 
output {
  stdout {
    codec => json_lines
  }
}
in 1.5.rc2 ,log is:
Logstash startup completed
LogStash::Json::GeneratorError: Cannot find Serializer for class: org.jruby.Ruby
Object
     jruby_dump at D:/elk/logstash-1.5.0.rc2/lib/logstash/json.rb:45
        to_json at D:/elk/logstash-1.5.0.rc2/lib/logstash/event.rb:152
         encode at D:/elk/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logsta
sh-codec-json_lines-0.1.6/lib/logstash/codecs/json_lines.rb:49
        receive at D:/elk/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logsta
sh-output-stdout-0.1.4/lib/logstash/outputs/stdout.rb:57
         handle at D:/elk/logstash-1.5.0.rc2/lib/logstash/outputs/base.rb:88
     initialize at (eval):23
           call at org/jruby/RubyProc.java:271
         output at D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:279
   outputworker at D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:235
  start_outputs at D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:163
[33mUDP listener died {:exception=>#<SocketError: recvfrom: name or service not
 known>, :backtrace=>["D:/elk/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/lo
gstash-input-udp-0.1.3/lib/logstash/inputs/udp.rb:79:in `udp_listener'", "D:/elk
/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.3/lib/lo
gstash/inputs/udp.rb:49:in `run'", "D:/elk/logstash-1.5.0.rc2/lib/logstash/pipel
ine.rb:174:in `inputworker'", "D:/elk/logstash-1.5.0.rc2/lib/logstash/pipeline.r
b:168:in `start_input'"], :level=>:warn}[0m

**Comment by marantz2015** [comment]
@colinsurprenant I print use output {stdout {}} netflow data is:

2015-04-08T16:52:55.727Z 10.32.255.1 %{message}
2015-04-08T16:52:55.727Z 10.32.255.1 %{message}
2015-04-08T16:52:55.727Z 10.32.255.1 %{message}
2015-04-08T16:52:55.727Z 10.32.255.1 %{message}
2015-04-08T08:38:47.570Z 10.32.255.2 %{message}
2015-04-08T08:38:47.570Z 10.32.255.2 %{message}

**Comment by colinsurprenant** [comment]
disregard my previous comment about the Time object assignment, I did not notice the iso8601 string conversion at the end. that's not the issue. investigating.

**Comment by colinsurprenant** [comment]
@marantz2015 could you please use the following output configuration and report the last debug event before the crash?

```ruby
output {
  stdout { codec => rubydebug }
  stdout { codec => json_lines }
}
```

**Comment by nitish-upadhyay** [comment]
Has any one find the solution to  this problem? i am having the same problem with kafka output.

**Comment by colinsurprenant** [comment]
FYI, I was just able to reproduce using `softflowd` and capture the packets using `netcat` - which means I can add specs for this codec and fix that bug!

Stay tuned.

**Comment by colinsurprenant** [comment]
fix in  logstash-plugins/logstash-codec-netflow#8
we will publish new plugin version as soon as we're done with the reviews.
