### ISSUE TITLE
IOError: closed stream

### ISSUE THREAD

**Issue by yusufcan141** [elastic/logstash#2947]
I'm using logstash 1.5 with input Elasticsearch and output S3 but i'm getting this error.

What might be the reason?
###### 

Logstash startup completed
IOError: closed stream
                size at org/jruby/RubyFile.java:1107
  rotate_events_log? at /home/ec2-user/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-output-s3-0.1.6/lib/logstash/outputs/s3.rb:287
        handle_event at /home/ec2-user/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-output-s3-0.1.6/lib/logstash/outputs/s3.rb:327
            register at /home/ec2-user/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-output-s3-0.1.6/lib/logstash/outputs/s3.rb:208
                call at org/jruby/RubyProc.java:271
              encode at /home/ec2-user/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-0.1.6/lib/logstash/codecs/json_lines.rb:49
             receive at /home/ec2-user/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-output-s3-0.1.6/lib/logstash/outputs/s3.rb:282
              handle at /home/ec2-user/logstash-1.5.0.rc2/lib/logstash/outputs/base.rb:88
          initialize at (eval):23
                call at org/jruby/RubyProc.java:271
              output at /home/ec2-user/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:279
        outputworker at /home/ec2-user/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:235
       start_outputs at /home/ec2-user/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:163

**Comment by jordansissel** [comment]
Is this still an error?

**Comment by siaw23** [comment]
yes. for me too @jordansissel

**Comment by ph** [comment]
We did a complete rewrite of the S3 plugin I suggest you test one of the latest Logstash 5.X release.
