### ISSUE TITLE
What is the best way to clean up the elasticsearch DB?

### ISSUE THREAD

**Issue by kkebb** [elastic/logstash#2948]
I have been searching for a clean way (other than curator) to handle data retention for elasticsearch through logstash. Is curator the only way at the moment? If so, suggestion to maybe adding a retention config field for elasticsearch plugin?

Any help would be great!

**Comment by talevy** [comment]
Curator is really the best way to curate indices with a high degree of customizability.

Why do you feel that Curator does not meet your needs?

**Comment by iangkent** [comment]
We are running the ELK stack in a docker container and would like to avoid introducing a cron/curator process within container and the needed processes manager (supervisord).

Also it seem that handling data retention seems to be a common requirement of all ELK deployments, so it would be good if we could just configure the retention config in logstash output and hide the complexity from ELK users.

**Comment by untergeek** [comment]
There is no clean way to do this from within Logstash or Elasticsearch at the moment.  If adding cron and/or supervisord is an issue, you could write a wrapper that daemonizes and runs calls to the Curator API with sleep intervals.
