### ISSUE TITLE
Publish logstash-core SNAPSHOT version

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2949]
As part of testing for #2928 we need to publish a new version for logstash-core gem. Lets publish a snapshot version before we are ready for a RC3 version

The version should be 1.5.0-rc3.snapshot

**Comment by purbon** [comment]
This issue if being track in #2932, if done, we should do this change in there.

My thought are that I would go for as many snapshots as needed before going for an RC3 before really doing the RC3, so +1 on doing snapshot release ... what do you think @colinsurprenant ?

**Comment by purbon** [comment]
Also we need to decide merging #2928, before we can move forward with the gem release.

**Comment by colinsurprenant** [comment]
the Gem version should be: 1.5.0.rc3.snapshot1  *no dash*

**Comment by ph** [comment]
1.5.0.rc3.snapshot1 Ok to me!

**Comment by purbon** [comment]
+1

**Comment by colinsurprenant** [comment]
:shipit:

**Comment by purbon** [comment]
done in #2958
