### ISSUE TITLE
geoip.location is not created as geo_point

### ISSUE THREAD

**Issue by evanwong** [elastic/logstash#2952]
I have setup a geoip filter and the location field is created automatically. However, the location is created as double not geo_point as the doc [indicates](http://logstash.net/docs/1.4.2/filters/geoip).

I am running ES 1.5 and logstash 1.4.2.

    geoip {
        source   => "src_ip"
        database => "/etc/logstash/GeoLiteCity.dat"
        add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
        add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
    }

![screen shot 2015-04-07 at 10 25 26 am](https://cloud.githubusercontent.com/assets/1258612/7025263/73cd5acc-dd10-11e4-9f57-824b4af5c0f2.png)

![screen shot 2015-04-07 at 10 26 08 am](https://cloud.githubusercontent.com/assets/1258612/7025274/8f32bb04-dd10-11e4-961c-06f5196af416.png)

**Comment by untergeek** [comment]
Are you using the built-in template from Logstash?  It should [map the geoip.location](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L35) field as a geo_point.  That's where the real mapping takes place, rather than within the geoip filter, which only makes a GeoJSON object.

**Comment by untergeek** [comment]
The documentation you linked to also indicates this:
>The field is stored in GeoJSON format. Additionally, the default Elasticsearch template provided with the elasticsearch output maps the [geoip][location] field to a geo_point.

**Comment by evanwong** [comment]
um.... I didn't change the template in the elasticsearch output. Now what I noticed is that the src link you are providing is using "logstash-*" but I have some different index names. 

![screen shot 2015-04-07 at 10 57 17 am](https://cloud.githubusercontent.com/assets/1258612/7025971/e3edaf56-dd14-11e4-870e-0bd3e4969065.png)

**Comment by untergeek** [comment]
That would indeed cause the mapping to not get applied.  You'll need to use a template that maps the GeoJSON to geo_point in order to use that functionality.

**Comment by evanwong** [comment]
I am adding these config now with a new template and it is working now.

    template => "path"
    template_overwrite => true

Thanks!
