### ISSUE TITLE
Bundling JAR dependencies with the main gem

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2954]
The way jar dependencies are managed through ruby-maven and jar-dependencies have had many issues, so as noticed in https://github.com/elastic/logstash/issues/2937#issuecomment-90608786 we aim to do to embeed the jars within the gem. 

In other words, we want to download the jars and package it at gem creation time and not at install time

NOTE: This is actually a meta issue to track the necessary changes in the different projects.

The list of plugins that might need to be changed are:

- [x] https://github.com/logstash-plugins/logstash-input-log4j
- [x] https://github.com/logstash-plugins/logstash-output-elasticsearch
- [x] https://github.com/logstash-plugins/logstash-output-elasticsearch-ec2
- [x] https://github.com/logstash-plugins/logstash-input-drupal_dblog

Others that are slightly related with this change as they use jars, or have wrong unexpected dependencies:

- [x] https://github.com/logstash-plugins/logstash-input-elasticsearch
- [x] https://github.com/logstash-plugins/logstash-filter-elasticsearch
- [x] https://github.com/logstash-plugins/logstash-input-jdbc

An special deal goes with 

- [x] https://github.com/logstash-plugins/logstash-input-kafka
- [x] https://github.com/logstash-plugins/logstash-output-kafka

as they use internally jar_dependencies.

This is a WiP list of plugins to be change, so there might be new ones added, but at the end we should be able to remove all references in devutils and the other projects of jar-dependencies, ruby-maven, etc.

This will help to provide a fix to #2937, https://github.com/logstash-plugins/logstash-input-log4j/issues/5 and help to build an offline installation package easy (related issue #2376)

**Comment by colinsurprenant** [comment]
also relates to #2376

**Comment by purbon** [comment]
@colinsurprenant wrote that in the last line of the main comment :-)

**Comment by wiibaa** [comment]
@purbon kafka plugins simply depends on jruby-kafka gem that already bundle all necessary jars, is there really work to be done in this case of transitive dependencies ?

**Comment by purbon** [comment]
@wiibaa with this strategy there is a hope the 3 party dependencies are well managed by the gem, or in case we know this is not the case, then we can handle them the same way as in here. Does this makes sense?

**Comment by purbon** [comment]
By looking at the hole set of plugins, the only ones that make direct usage of jars as in jar-dependencies are:

```
╭─purbon@Peres-MacBook-Pro-2  ~/work/logstash/vendor/bundle/jruby/1.9/gems  ‹master*› 
╰─$ grep -rn s.requirements . | grep logstash
./logstash-input-log4j-0.1.4-java/logstash-input-log4j.gemspec:24:  s.requirements << "jar 'log4j:log4j', '1.2.17'"
./logstash-output-elasticsearch-0.2.0-java/logstash-output-elasticsearch.gemspec:23:  s.requirements << "jar 'org.elasticsearch:elasticsearch', '1.5.0'"
./logstash-output-elasticsearch-ec2-0.2.2/logstash-output-elasticsearch-ec2.gemspec:23:  s.requirements << "jar 'org.elasticsearch:elasticsearch-cloud-aws', '2.4.1'"
```

and they are all changed by now, is there any other plugin that raises a bell of using jars (except from kafka? )

**Comment by wiibaa** [comment]
From a quick manual scan of gemspec I would only add https://github.com/logstash-plugins/logstash-input-drupal_dblog that depends on mysql jdbc driver, but this plugin future is incertain as per https://github.com/logstash-plugins/logstash-input-drupal_dblog/issues/6

**Comment by purbon** [comment]
Makes sense, is an easy change ... so lets do and if then go away no problem!

**Comment by purbon** [comment]
All changes in plugins are done for now, should notice things like the kafka plugins, even if the use jar-dependencies, they are not affected by this change as we pull the jruby-kafka gem all together, including dependencies. 

@jsvd @ph reviews?

**Comment by purbon** [comment]
The only test missing is to run all this updated plugins all together within a logstash instance.

**Comment by purbon** [comment]
I was wondering today, for now this is not a problem in our ecosystem, but I was thinking if makes sense to create gems out of a given set of jars, so in case two plugins need it we just have one copy of them. Does this makes sense?
