### ISSUE TITLE
Incorrect alert firing with HipChat output due to number of digits in source field

### ISSUE THREAD

**Issue by deepybee** [elastic/logstash#2956]
I've got a weird issue where depending on the number of characters in a numeric field Logstash 1.4.2-1-2c0f5a1 will or won't throw an error.

First, the error message (this may be a red herring, but for posterity I'll list it here):

"WARNING: unimplemented method called: StoreContext#error_depth"

Having trawled previous issues this is a JRuby flaw relating to their implementation of OpenSSL, as reported in #1612 and before that on https://logstash.jira.com/browse/LOGSTASH-1428.

The issue I am seeing manifests itself thus: I have an inbound message for OpenMQ stats, which grok splits out into several fields, including one containing the current number of queued messages. Based on this field's value, Logstash is configured to fire notifications to HipChat as red, yellow or green. For reference, these thresholds are set at < 20000 (green), >= 20000 and <= 50000 (yellow), finally > 50000 (red).

The problem is that Logstash appears to expect a 5 digit integer for all values in this field and treats the data as the leading characters of a 5 digit integer, which the source data does not write unless the value genuinely warrants a 5 digit integer; ie the value 65 is treated as 65000 and so fires the critical red alert which it should return green as it is under 20000, 499 is treated as 49900 and fires the yellow alert etc.

Is this expected behaviour? I can write a mutate filter to address this and insert leading zeroes but I can't fathom why this current behaviour is as it is.

Am I missing something blindingly obvious here or is this a bug?

**Comment by untergeek** [comment]
I'm confused.  Is this a HipChat plugin bug, or a JRuby bug, or a grok bug?

**Comment by deepybee** [comment]
I am erring toward a HipChat plugin bug, as I've not seen this behaviour with any other aspect of Logstash. The error message above seems to fire intermittently, and I think can probably be discounted as the known issue with the JRuby OpenSSL implementation, but I haven't had enough chance to test to rule out a correlation between the actual problem I'm having and the errors churning to stdout.

Sorry, that's probably as clear as mud :confused:

**Comment by deepybee** [comment]
Hopefully this will make it a bit clearer:

This is the HipChat output plugin config:

```ruby
if [queued_messages] > "50000" {
    hipchat {
      token => "our_api_key"
      room_id => "our_room_id"
      color => "red"
      format => "OpenMQ queue %{[queue_name]} has %{[queued_messages]} queued messages which exceeds critical threshold of 50,000"
    }
  }
  if [queued_messages] >= "20000" and [queued_messages] <= "50000" {
    hipchat {
      token => "our_api_key"
      room_id => "our_room_id"
      color => "yellow"
      format => "OpenMQ queue %{[queue_name]} has %{[queued_messages]} queued messages which exceeds warning threshold of 20,000"
    }
  }
  if [queued_messages] >= "0" and [queued_messages] <= "20000" {
    hipchat {
      token => "our_api_key"
      room_id => "our_room_id"
      color => "green"
      format => "OpenMQ queue %{[queue_name]} now has %{[queued_messages]} queued messages which is within threshold of 20,000"
    }
  }
```

The rubydebug output looks ok, with the exception of the trailing error messages (which do not occur on every event):

```ruby
{
                    "message" => "IndexQueue               Queue  RUNNING  0      -         1      -         8      0       8      13327.125",
                   "@version" => "1",
                 "@timestamp" => "2015-04-07T17:04:39.929Z",
                       "host" => "10.6.130.38:50978",
                       "tags" => [
        [0] "openmq"
    ],
                 "queue_name" => "IndexQueue",
                    "mq_type" => "Queue",
                "queue_state" => "RUNNING",
            "total_producers" => "0",
         "wildcard_producers" => "-",
            "total_consumers" => "1",
         "wildcard_consumers" => "-",
            "queued_messages" => "8",
            "remote_messages" => "0",
    "unacknowledged_messages" => "8",
               "average_size" => "13327.125"
}
WARNING: unimplemented method called: StoreContext#error_depth
WARNING: unimplemented method called: StoreContext#error_depth
WARNING: unimplemented method called: StoreContext#error_depth
```

But the alert in HipChat is red when it should be green because it's treating "8" as "80000":

```
[Apr-7 18:05] logstash: OpenMQ queue IndexQueue has 8 queued messages which exceeds critical threshold of 50,000
```

The same happens with here with 499 queued_messages, which should be a green level alert but is evidently being parsed as 49900 placing it in the yellow alert range:

```ruby
{
                    "message" => "mq.sys.dmq Queue RUNNING 0 - 0 - 499 0 0 2101.1692",
                   "@version" => "1",
                 "@timestamp" => "2015-04-07T17:03:51.222Z",
                       "host" => "10.6.130.38:50902",
                       "tags" => [
        [0] "openmq"
    ],
                 "queue_name" => "mq.sys.dmq",
                    "mq_type" => "Queue",
                "queue_state" => "RUNNING",
            "total_producers" => "0",
         "wildcard_producers" => "-",
            "total_consumers" => "0",
         "wildcard_consumers" => "-",
            "queued_messages" => "499",
            "remote_messages" => "0",
    "unacknowledged_messages" => "0",
               "average_size" => "2101.1692"
}
WARNING: unimplemented method called: StoreContext#error_depth
WARNING: unimplemented method called: StoreContext#error_depth
WARNING: unimplemented method called: StoreContext#error_depth
```

Resulting in the following:

```
[Apr-7 18:04] logstash: OpenMQ queue mq.sys.dmq has 499 queued messages which exceeds warning threshold of 20,000
```

When I tested with 501 queued messages it triggered a red alert illustrating that Logstash is somehow parsing these values as leading digits in a 5 digit value (I assume it's suffixing zeroes to make up the expected number of digits).

As I say I could write something pretty easily to transform input data into a 5 digit value where necessary, but that feels very much like I would be working around a bug.

**Comment by untergeek** [comment]
`if [queued_messages] > "50000"` indicates a string comparison.  Have you considered converting `queued_messages` to be an integer and doing numeric comparisons? Or changing your grok to be `%{INT:queued_messages:int}` (which would save the mutate convert step)?

Grok treats everything as a string, and unless you cast the _result_ as a `float` or `int`, the result from grok will always be a string, even if you are matching the `INT` pattern.

Not sure if this will change anything for you, but it might.

**Comment by deepybee** [comment]
I had a feeling it might have been string related. I'd added the following at the end of the working day just before leaving the office to the filter config:

```ruby
    ruby {
      code => "%{[queued_messages]}.to_i"
    }
```

which had no effect but I only just spotted after posting above I'd not removed the quotes from the output config.

Checking now.

**Comment by deepybee** [comment]
Hmmm, removing the quotes throws an error on the condition claiming queued_messages is a string;

```ruby
{
                    "message" => "mq.sys.dmq Queue RUNNING 0 - 0 - 499 0 0 2101.1692",
                   "@version" => "1",
                 "@timestamp" => "2015-04-07T23:46:49.614Z",
                       "host" => "10.6.130.38:35639",
                       "tags" => [
        [0] "openmq"
    ],
                 "queue_name" => "mq.sys.dmq",
                    "mq_type" => "Queue",
                "queue_state" => "RUNNING",
            "total_producers" => "0",
         "wildcard_producers" => "-",
            "total_consumers" => "0",
         "wildcard_consumers" => "-",
            "queued_messages" => "499",
            "remote_messages" => "0",
    "unacknowledged_messages" => "0",
               "average_size" => "2101.1692"
}
ArgumentError: comparison of String with 50000 failed
              > at org/jruby/RubyComparable.java:144
              > at org/jruby/RubyString.java:1837
     initialize at (eval):65
           call at org/jruby/RubyProc.java:271
         output at /opt/logstash/lib/logstash/pipeline.rb:266
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:225
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152
```

:-/

**Comment by untergeek** [comment]
For it to be an integer in Logstash, it must be converted, either using the grok syntax I showed:

```
%{INT:queued_messages:int}
```
or with the mutate filter:
```
mutate {
  convert => { "queued_messages" => "integer" }
}
```
I don't think that bit of ruby code in the ruby filter will actually convert the field.  It looks like it would just return the value of the field as an integer without affecting the field itself.

**Comment by deepybee** [comment]
A-ha! Just wiped my bleary eyes and re-read your post in its entirety;

"changing your grok to be %{INT:queued_messages:int} (which would save the mutate convert step)?"

that nailed it :+1: 

Thank you very much for your help!

**Comment by deepybee** [comment]
Fwiw the error messages are still appearing, so I'll chalk them down as expected behaviour due to the JRuby issues mentioned above. Thanks again.
