### ISSUE TITLE
  Getting compilation error when parsing Timestamp from logs file

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [elastic/logstash#2957]
Hi,
I am getting compilation error when trying to parse a timestamp in format '2013-02-03' i.e 'yyyy-MM-dd'. Actually i am trying to parse the timestamp in the logs file on 'http://grokdebug.herokuapp.com/' website with a input :
2015-02-02 11:00:58
and pattern :
date {
match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
}
Whenever i use yyyy-MM-dd format i get compilation error. Attaching screen shot for the same 

![compilation error](https://cloud.githubusercontent.com/assets/11851015/7044732/47f48cfe-de14-11e4-9dbe-93a622a568da.png)

If i give one space after the yyyy like yyyy -mm the error goes but i am unable to match this input, could you please look into this issue or suggest me any solution.

Thanks and regards,
Anand J.kadhi

**Comment by suyograo** [comment]
Date filter does not support grok as of now so you cannot use  'http://grokdebug.herokuapp.com/' . Date filter is implemented using JODA which has a set of patterns to parse date. You can check the reference here http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html

**Comment by Anand-J-Kadhi** [comment]
So as you said i cannot use 'http://grokdebug.herokuapp.com/' for the date filter.So is any other filter which can directly support this even without changing the logs date pattern which is the existing one. I mean we configured the dates using log4j ,so can we use the date filter directly it should work right ? .

**Comment by Anand-J-Kadhi** [comment]
Hey thanks i solved my problem by defining regular expression pattern in the patterns file
DATE (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})

and defining it in the grok pattern as :
grok {
  patterns_dir => "./patterns"
  match => ["message", "%{DATE:date}"]  
}

 date {
  match => ["date","YYYY-MM-dd HH:mm:ss"]
}

Thanks a lot for your time & effort and for this wonderful application.
