### ISSUE TITLE
Getting started doc incorrect to get started in up and running section

### ISSUE THREAD

**Issue by DannyvdSluijs** [elastic/logstash#2959]
The up and running action states 4 easy steps to get an initial setup working

```
curl -O https://download.elasticsearch.org/logstash/logstash/logstash-1.4.2.tar.gz
tar zxvf logstash-1.4.2.tar.gz
cd logstash-1.4.2
bin/logstash -e 'input { stdin { } } output { stdout {} }'
```

After typing "hello world" (or anything other for that matter) the expected result
```
2013-11-21T01:22:14.405+0000 0.0.0.0 hello world
```

Doesn't appear.

**Comment by purbon** [comment]
Hi @DannyvdSluijs, I just did your very same steps within my dev environment and got the hello world env, ... could you check if you get any kind of error? I guess you have java, etc.. isn't? we might need more details in order to know why this does not work for you.

**Comment by DannyvdSluijs** [comment]
I'm very sorry it seems that my Java installation is a bit slugish (Java 1.8 on Ubuntu 12.04) and was just causing long delays (+ 30 sec).

**Comment by purbon** [comment]
Ok, no problem man!
