### ISSUE TITLE
Elasticsearch Input Get Parent Field

### ISSUE THREAD

**Issue by yusufcan141** [elastic/logstash#2960]
What is the way of getting "_parent" field of a document using elasticsearch input?

Thanks

**Comment by yusufcan141** [comment]
Can anyone answer this? Because when i put "_paren" in docinfo_fields, it returns null for parent field.

**Comment by suyograo** [comment]
@untergeek ?

**Comment by untergeek** [comment]
In all honesty, I've never even done parent/child in ES, leave alone try to import a parent/child document with the elasticsearch input plugin.

Do you see anything with debug logging turned on?  Yes, it will be a lot of data, but you might see what's going on there.

**Comment by untergeek** [comment]
Wait.  It should be in the `@metadata` field, according to the plugin documentation.  Have you tried to access it as `[@metadata][_parent]`?

**Comment by yusufcan141** [comment]
No, it doesn't come in @metadata, that's why i wrote it in query as fields and get in fields in response.

**Comment by untergeek** [comment]
You mention that you used `docinfo_fields`.  The code and documentation say that if you put `_parent` into `docinfo_fields` it will be in `@metadata`:

https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/master/lib/logstash/inputs/elasticsearch.rb#L89-L95

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/14. Let's continue the discussion there! :)
