### ISSUE TITLE
Getting a NotImplementedError: fstat unimplemented unsupported in logstash.err

### ISSUE THREAD

**Issue by javifr** [elastic/logstash#2962]
Hi!

I'm writing input and output plugins for dropbox ( [input](https://github.com/javifr/logstash-plugin-input-dropbox), [output](https://github.com/javifr/logstash-plugin-output-dropbox) ).

For now everything is working fine in my local machine.

But on my remote machine ( an ELK installation of Ubuntu in Digital Ocean according to [this](https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04) tutorial ) I've been able to install both plugins, but once I try to start the logstash service I'm getting a ```NotImplementedError: fstat ...``` in my ```/var/log/logstash/logstash.err``` file, and the service stops running.

My input conf file:

```
input {
  dropbox {
    type => "customers"
    tags => ["customers","punt fresc","raw"]
    backup_to_folder => "/loyal_guru_files/raw/archived/customers/"
    backup_to_prefix_file => "%{type}.%{+yyyy.MM.dd.HH}"
    prefix => "/loyal_guru_files/raw/customers/"
    token => "XXXX"
  }
}
```

My filter conf file:

```
filter {
  csv {
    columns => [ "name", "surname_1", "surname_2" ]
    separator => ";"
  }
}
```

My output conf file:

```
output {
  dropbox {
    path => "/loyal_guru_files/customers/"
    temporary_directory => "/tmp/logstash/"
    type => "customers"
    size_file => 1048576
    time_file => 2
    tags => ["customers", "punt fresc", "raw"]
    csv_format => true
    csv_options => {"headers" => true}
    fields => ["name","surname_1", "surname_2"]
    token => "XXXXXX"
  }
}
```

My ```/var/log/logstash/logstash.err```:

```bash
NotImplementedError: fstat unimplemented unsupported or native support failed to load
                size at org/jruby/RubyFile.java:1108
  rotate_events_log? at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:234
        handle_event at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:274
            register at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:161
                call at org/jruby/RubyProc.java:271
              encode at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-0.1.5/lib/logstash/codecs/line.rb:53
             receive at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:222
              handle at /opt/logstash/lib/logstash/outputs/base.rb:88
          initialize at (eval):59
                call at org/jruby/RubyProc.java:271
              output at /opt/logstash/lib/logstash/pipeline.rb:279
        outputworker at /opt/logstash/lib/logstash/pipeline.rb:235
       start_outputs at /opt/logstash/lib/logstash/pipeline.rb:163
```

I think the error is coming from a function in the output plugin that is trying to get the size of a file:

[file](https://github.com/javifr/logstash-plugin-output-dropbox/blob/master/lib/logstash/outputs/dropbox.rb#L233)

```
def rotate_events_log?
 @tempfile.size > @size_file
end
```

Some ideas on why is this happening? 
May be I need to install something on the machine in order to be able to size a file?

**Comment by ph** [comment]
As soon as you deamonize logstash it crash but if you trigger it from the command line it work? Correct?

**Comment by javifr** [comment]
HI @ph,

noop.

Look, the service is stoped and I've tried to executed from the command line, that is still the output:

```
^Croot@elk-loyalguru:~/opt/logstash/bin/logstash -f /etc/logstash/conf.d
You are using a deprecated config setting "type" set in dropbox. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. You can achieve this same behavior with the new conditionals, like: `if [type] == "sometype" { dropbox { ... } }`. If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"type", :plugin=><LogStash::Outputs::Dropbox --->, :level=>:warn}
You are using a deprecated config setting "tags" set in dropbox. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. You can achieve similar behavior with the new conditionals, like: `if "sometag" in [tags] { dropbox { ... } }` If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"tags", :plugin=><LogStash::Outputs::Dropbox --->, :level=>:warn}
Logstash startup completed
NotImplementedError: fstat unimplemented unsupported or native support failed to load
                size at org/jruby/RubyFile.java:1108
  rotate_events_log? at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:234
        handle_event at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:274
            register at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:161
                call at org/jruby/RubyProc.java:271
              encode at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-0.1.5/lib/logstash/codecs/line.rb:53
             receive at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:222
              handle at /opt/logstash/lib/logstash/outputs/base.rb:88
          initialize at (eval):59
                call at org/jruby/RubyProc.java:271
              output at /opt/logstash/lib/logstash/pipeline.rb:279
        outputworker at /opt/logstash/lib/logstash/pipeline.rb:235
       start_outputs at /opt/logstash/lib/logstash/pipeline.rb:163
root@elk-loyalguru:~#
```

same error.
I'm a bit desperate :(

**Comment by ph** [comment]
Can you do a `java -version` on your **remote** server and on your **local** machine?

**Comment by javifr** [comment]
Thanks @ph.

Local:
```
➜  ~  java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
````

Remote:
```
root@elk-loyalguru:~# java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

It seems that the only difference is the last build number ( 25 / 27 ).

**Comment by jordansissel** [comment]
> NotImplementedError: fstat unimplemented unsupported or native support failed to load

This error usually occurs when JRuby fails to load FFI - in order to access the native OS's file stat structure.

On the system that is not working, what's the output of:

* `ls -ld /tmp`
* `mount | grep /tmp`

**Comment by javifr** [comment]
Thanks @jordansissel for the answer.

That's the output for `ls -ld /tmp`:

```
root@elk-loyalguru:~# ls -ld /tmp
drwxrwxrwt 9 root root 4096 Apr 24 09:17 /tmp
```
I have set 777 permissions in temp in order to allow the logstash-output-dropbox plugin to write at this folder.

Thats the output for ```mount | grep /tmp```  ( nothing ):
```
root@elk-loyalguru:~# mount | grep /tmp
root@elk-loyalguru:~#
```

Does this tell you something about the problem?

**Comment by jsvd** [comment]
This seems to be an [issue with JRuby and Oracle's JVM](https://github.com/jruby/jruby/issues/2913), are you able to install OpenJDK and check if the problem still occurs?

**Comment by javifr** [comment]
That totally did it! THANK YOU VERY MUCH!

**Comment by jordansissel** [comment]
Closing this in favor of tracking it in #3127

**Comment by johncarl81** [comment]
It looks like you found resolution to this issue by switching over to OpenJDK, but I'd thought I'd share another approach.

I was able to fix this issue by removing the "noexec" option on the /tmp directory.  This allowed fstat to execute successfully within JRuby (see https://github.com/asciidoctor/asciidoctorj/issues/402)
