### ISSUE TITLE
Is there a library of Logstash configuration examples?

### ISSUE THREAD

**Issue by uhammec** [elastic/logstash#2965]
Really struggling with how to use Logstash filters to format syslog input into reasonably index-able output for Elasticsearch to consume.

Several of my colleagues and I have spent many hours trying to understand how to configure Logstash.  The available documentation is less than ideal, and at times directly misleads the novice reader.  For example http://logstash.net/docs/1.4.2/filters/date where it suggests:
filter {
  date {
    match => [ "logdate", "MMM dd YYYY HH:mm:ss" ]
  }
}
says nothing about the fact that "logdate" must be an indexed field from a grok stanza.  That syntax example makes you think "logdate" magically exists just like "message" magically exists.

I have watched many of videos by Jordan Sissel, searched the web, asked on the IRC channel http://webchat.freenode.net/?channels=logstash etc. and still can't figure out what "good" Logstash configs look like.

What would be REALLY HELPFUL is to have a library of example Logstash configuration files knowledgeable users have created over time.  The files don't need to be documented nor clean, just a directory filled with examples would be nice.  If the contributor wants to obfuscate some of the file names in inputs and output that would be fine but is unnecessary.  I can't help but believe that hundreds or thousands of different configuration files are out there that have been used (some bad, some good, and some better).

My goal is to take raw syslog data of all sorts and enhance the data with labelled knowledge before inserting it into Elasticsearch.  Seems like a pretty reasonable thing to do, but turns out to be VERY HARD to understand given the lack of examples.

I've got something working, but can't seem to extend it very well ... I need to parse/format hundreds of different record types.  I have some of my own grok patterns created, and thus I can't even use the grok debugger (because I can't seem to extend the patterns available there).

Logstash looks like a great tool, but the learning curve is really tough.
   Thanks, Ed

**Comment by untergeek** [comment]
I am so sorry you're having a hard time.  We have started a project to put "cookbooks," as it were, into the Elastic Guide page (http://elastic.co/guide).  As they will reside in github, user contributions can be submitted via pull request.

The documentation for Logstash 1.5, and all plugins going forward, will be at http://www.elastic.co/guide/en/logstash/current/index.html

Feel free to see if the improved documentation meets your needs in the meanwhile.

The grok debugger is not in constant development, but this tool is: http://grokconstructor.appspot.com

See if that helps you with your grok patterns, some.

Also, what is your syslog source?  Which input(s) are you using?

**Comment by uhammec** [comment]
untergeek, Appreciate the response.

The use case is simple enough.  We have hundreds of globally distributed Cisco, Palo Alto, F5, and other appliances writing their syslog output to a centralized Solaris syslog server that merges them all to a single file.  We are trying to use Logstash to read the syslog file and forward the results to Elasticsearch for better reporting/visualization.

For Elasticsearch/Kibana to be of more value, we are trying to do some intelligent interpretation of the syslog records.  For selected records, we want to add more parsing intelligence (e.g. picking out a client IP).  We'd hope that filter{grok {match}} statements would provide that ability for the large variety of records we have.

We are struggling to find enough complete examples and "best practices" recommendations to construct an effective .conf file.  The most crude (minimally effective) filter specification we have working is below.

#### this works but does only the bare minimum ... we need more
`   filter {`
`       grok {`
`           match => [`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: "`
`           ]`
`           overwrite => [ "host" ]`
`       }`
`       date {`
`           match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]`
`           locale => "en"`
`           timezone => "US/Eastern"`
`           remove_field => [ "timestamp", "path", "pid" , "msgtext"]`
`       }`
`   }`

We need to extend this greatly!  I am trying to find some guidance on how to cascade multiple grok patterns.  For example, since the grok match statement is a list, I would expect syntax much like the date match statement.  I tried to have tried all the following with no success.

#### none of these seem to work to extend to multiple patterns
`           match => [`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: ",`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: %{IP:clientIP}"`
`           ]`

====
`           match => [`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: ",`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: %{IP:clientIP}"`
`           ]`

====
`           match => [`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: ",`
`           ]`
`           match => [`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: %{IP:clientIP}"`
`           ]`

====

What I think we got to work is the following, but it just seems wrong!

#### is this really the way to do it?
`       grok {`
`           match => [`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: ",`
`           ]`
`           overwrite => [ "host" ]`
`       }`
`       grok {`
`           match => [`
`               message,`
`               "%{SYSLOGTIMESTAMP:timestamp} %{IPORHOST:host} %{SYSLOGPROG}: %{IP:clientIP}"`
`           ]`
`           overwrite => [ "host" ]`
`       }`

**Comment by untergeek** [comment]
Before addressing this, is there any way you can get Rsyslog installed at your target host?  You can bypass all of the syslog-level grok grief by using Rsyslog to output JSON formatted text to a TCP port, which Logstash can ingest.  You could still capture direct to file, if you like, but would have Logstash consume direct from the network.

See https://gist.github.com/untergeek/0373ee85a41d03ae1b78 for an example.

**Comment by untergeek** [comment]
And the correct way to have grok select from an array of possible matches is:

```
grok {
  match => {
    message => [ "pattern1", "pattern2", "pattern3", ... "patternN" ]
  }
}
```

**Comment by pcrook** [comment]
There are lots of collections of logstash configuration on the web including here on github.  Google for [site:github.com master logstash conf](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=site:github.com+master+logstash+conf).  One example is [sexilog](https://github.com/sexilog/sexilog/tree/master/logstash/conf.d).

**Comment by suyograo** [comment]
There are no plans for this as of now.
