### ISSUE TITLE
File Input Multiline filter file Size Limit and Entity Size Limit

### ISSUE THREAD

**Issue by priteshpatel15** [elastic/logstash#2966]
## Background

Currently working on a Production implementation of Logstash and Elastic.  We are indexing data from SQL Server.  Files are being published from SQL Server and we are using the file input to grab all the files to index into Elastic. 

We ran into a bug where the last entry in the file gets dropped using the multiline filter.  Looks like thats a bug in Logstash still being worked on? (https://groups.google.com/forum/#!searchin/logstash-users/multiline$20last/logstash-users/SyxIgP8sStk/hHTj6jEpLKsJ)
## Questions

Since we are putting this into production, I'm getting a lot of questions about size limits.
1) What is the limit on the file size that logstash can input
2) What is the limit of each entity that is indexed.  Google searches tell me 4096.  Is that correct?

Anybody know the answers to these?

**Comment by untergeek** [comment]
Without addressing your other questions, I can tell you that the multiline hanging indefinitely while waiting for additional lines problem has been solved for Logstash 1.5.

**Comment by priteshpatel15** [comment]
Thanks Aaron!  Do you mean the problem of dropping the last entry has been fixed?

Would you have any recommendations for questions 1 and 2?

**Comment by untergeek** [comment]
I have no numbers for you for 1 and 2.  But the problem where the last entry of a multiline event has been fixed, yes.

**Comment by priteshpatel15** [comment]
OK thanks Aaron!

**Comment by dtrv** [comment]
From the source of 1.5 ../logstash/filters/multiline.rb:

    # The maximum age an event can be (in seconds) before it is automatically
    # flushed.
    config :max_age, :validate => :number, :default => 5

So the last multiline event always have a 5 seconds delay by default. Configure with <code>max_age</code>.

**Comment by ph** [comment]
This case has been fixed on codec and the multiline filter,
