### ISSUE TITLE
logstash  same filename input error 

### ISSUE THREAD

**Issue by baozhaxiaoyuanxiao** [elastic/logstash#2970]
I have config logstash input from file, I use same filename,
my app replace the filename every 10 minutes.

on the first time logstash work is well
when my app replace the file, filename is same but the content id different, all is json format.

the error is 

message:
tags:
    _jsonparsefailure
@version:
    1
@timestamp:
    April 9th 2015, 18:20:02.081
host:
    iZ235whxcttZ
path:
    /mnt/logstashinput/inputlog/appstatus.log
_source:
  
can anybody help me , thanks

**Comment by markwalkom** [comment]
You can't replace the format like that as Logstash doesn't know about the change.

I'd suggest you ask for some assistance on https://groups.google.com/forum/?hl=en-GB#!forum/logstash-users as Github issues are for code problems, whereas this is a setup one.
