### ISSUE TITLE
Add namespaces to avoid configuration redundancy

### ISSUE THREAD

**Issue by konradkonrad** [elastic/logstash#2971]
This is first of all a feasibility question:
When working with the `couchdb_changes` input plugin, I encountered, that I am going to have a lot of redundant configuration parameters. Now I am wondering, if it was possible to develop an input plugin, that allows for something I'd call "setup namespaces"? The idea is, that it allows you to setup a hash/dictionary at the beginning of the input chain, that you can "merge in" in later stages. Enough with the words, here is the configuration format I have in mind:

```
input {
  setup {
    ns => "connection"
    params => {
      host => "127.0.0.1"
      port => 6666
      username => "user"
      password => "the pwd"
    }
  }
  couchdb_changes {
    merge_from_ns => "connection" # will put the params defined above into the local context 
    db => "mydb" # other params, possibly allow to overwrite ns-params
  }
  couchdb_changes {
    merge_from_ns => "connection"
    db => "myotherdb"
  }
}
```

I believe the reasons for something like this are quite obvious - if not, or if there is another mechanism to keep configurations DRY, please let me know!

**Comment by wiibaa** [comment]
You can find some background discussion in  https://github.com/elastic/logstash/issues/1629#issuecomment-52093836

**Comment by untergeek** [comment]
This will be moot with Logstash 2.0 because it will use API-based configuration.  See #2612

**Comment by konradkonrad** [comment]
#2612 looks sweet!
However, as stated there:
> To be clear, at this time we are not looking to change the existing configuration syntax. Also, file-based configuration will continue to be supported.

I still believe, this could greatly help with file based configurations. Yay, nay??

**Comment by untergeek** [comment]
It may, so we'll leave this issue up for discussion.  We're aiming to replace file-based with the API, even if we continue to support it.  It's more for backward compatibility than something we aim to continue to aggressively support and add features to.

It won't make the cut for 1.5, though.  We'll see what happens after that's released.

**Comment by jinleileiking** [comment]
:+1:

**Comment by suyograo** [comment]
There are no plans of doing this now; so closing it.

**Comment by ph** [comment]
I'll mark it as config syntax if we ever want to do it again.
