### ISSUE TITLE
Mutate filter lowercase and uppercase not working

### ISSUE THREAD

**Issue by Hark82** [elastic/logstash#2973]
logstash-1.5.0.rc2

Adding mutate filter lowercase or uppercase in the config has no effect.

**Comment by suyograo** [comment]
@Hark82 i was able to reproduce it only for json data. Normal data works fine.

```
suyog@machine:~/ws/logstash (update_copyright)$ bin/logstash -e 'filter { mutate { lowercase => ["message"] }}'
Logstash startup completed
DEF
{
       "message" => "def",
      "@version" => "1",
    "@timestamp" => "2015-04-13T23:38:24.740Z",
          "type" => "stdin",
          "host" => "Suyogs-MacBook-Pro-2.local"
}
```

json data:

```
suyog@machine:~/ws/logstash (update_copyright)$ bin/logstash -e 'input { stdin { codec => json} } filter { mutate { lowercase => [ "foo" ] } }'
Logstash startup completed
{"foo": "BAR"}
{
           "foo" => "BAR",
      "@version" => "1",
    "@timestamp" => "2015-04-13T23:39:59.439Z",
          "host" => "Suyogs-MacBook-Pro-2.local"
}
```

**Comment by suyograo** [comment]
@Hark82 can you provide us your sample log input and config?

**Comment by Hark82** [comment]
@suyograo sorry for my minimal description. Here is a sample input and my config.

Sample input:

{"@timestamp":"2014-06-18T11:52:45.370636+02:00","Level":"Info","Machine":"X100","Session":{"MainId":0,"SubId":"5otec"},"Request":{"Url":"http://www.localhost:5000/Default.aspx","Method":"GET","Referrer":"http://www.localhost:5000/Default.aspx"},"EndRequest":{"Duration":{"Main":0,"Page":6720}}}

Config:

input {
  file {
    path => "D:/test.log"
	codec => "json"
	sincedb_path => "/dev/null"
	start_position => [ "beginning" ]
  }
}
filter {
	json {
        source => "message"
    }
	grok {		
		match => [ "[Request][Url]", "%{URIPATH:[Request][UrlBase]}" ]
	}
	mutate {
		lowercase => [ "[Request][UrlBase]" ]	
	}			
}
output {
  stdout { 
	codec => rubydebug 
	}
}

**Comment by doubret** [comment]
Uppercase / Lowercase only work with ansi strings, not with utf-8.
I opened a ticket in the logstash-filter-mutate repository.

**Comment by suyograo** [comment]
Ok that explains it. JSON is utf-8 so Ruby's `upcase` and `lowercase` does not work. We'll look into adding support for unicode

**Comment by suyograo** [comment]
Tracking here: https://github.com/logstash-plugins/logstash-filter-mutate/issues/17

**Comment by Cidan** [comment]
+1, just got bit by this bug.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-mutate/issues/33. Let's continue the discussion there! :)
