### ISSUE TITLE
jars_path is invalid in load_elasticsearch_jars method

### ISSUE THREAD

**Issue by Mogztter** [elastic/logstash#2974]
In my plugin I'm using `load_elasticsearch_jars` with LogStash 1.5.0-rc2.

The `load_elasticsearch_jars` in [environment.rb](https://github.com/elastic/logstash/blob/master/lib/logstash/environment.rb#L59) is looking for ElasticSearch jars in `$LOGSTASH_HOME/vendor/elasticsearch/**/*.jar`.

The default [logstash-1.5.0-rc2 package](https://www.elastic.co/downloads/logstash) doesn't contains the `vendor/elasticsearch` directory and the method throws `Could not find Elasticsearch jar files under...`.
Maybe this is intended ? but the jars can be found in ` bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib`.

A simple symbolic link `elasticsearch ->  bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java` in `$LOGSTASH_HOME/vendor/` can solve the issue but... is this a bug ? Am I doing something wrong ?

Thanks

**Comment by ph** [comment]
You are writing a plugin that uses the `logstash-output-elasticsearch`? If it is the case your gem should define a runtime dependencies on it, by doing that the gem will make the jar available after the installation process. Can I ask why you are building a plugin on top of the elasticsearch output?

Sadly the `load_elasticsearch_jars` is legacy code and should be removed in a future PR.

**Comment by Mogztter** [comment]
> You are writing a plugin that uses the logstash-output-elasticsearch? 

Not exactly, I'm using the [RabbitMQ river plugin](https://github.com/elastic/logstash/blob/v1.4.2/lib/logstash/outputs/elasticsearch_river.rb) from the 1.4.2 branch. I know that rivers are deprecated and will be removed (or are removed ?) from ElasticSearch 1.5 but this plugin is really useful to consume messages from RabbitMQ.

And I'm using LogStash 1.5.0 because we want to replace RabbitMQ with Kafka but while we are transitioning we need to keep RabbitMQ running (with river).

**Comment by purbon** [comment]
For what I understand from your description I would encourage you to use an idea similar to the one proposed in #2980, so by embedding in your gem/plugin them afterward in execution time you are basically done. If you need inspiration to write this code, is basically doing the same thing as it's done right now with the ```load_elasticsearch_jars!```.

Hope this helps you fix your issue.

**Comment by purbon** [comment]
@Mogztter was my last comment of help for you?

**Comment by Mogztter** [comment]
Yes that makes sense, thanks @purbon !
I will take a similar approach and embedded ElasticSearch jars (https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/101/files)

@ph Can I submit a working version of logstash-output-elasticsearch-river-rabbitmq in https://github.com/logstash-plugins/ ?

I know that rivers are deprecating in 1.5.0 but they should work until 2.0 as mentioned by Shay Banon (https://www.elastic.co/blog/deprecating_rivers).

**Comment by purbon** [comment]
Good @Mogztter !!

speaking about your new plugin, I suggest you open an issue with a pointer to your code so we can review and take a look. After this review phase is done very happy to have this within the logstash-plugins org.

I just did it myself for two plugins I created https://github.com/elastic/logstash/issues/2989.

Going to close this issue as we're set here, you can open other issues for the new plugin or issues you might be having by embedding the jars.

Thanks.

**Comment by purbon** [comment]
Good morning @Mogztter, I had a misunderstanding with how to add a new plugin, so I apologies for my last message.

so if you want to add a new plugin you should follow the guide in http://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html

but basically you can open an issue here and then we will create a new github repo inside the logstash-plugins organization, and start all the review, merge process.

Does this makes sense to you?
