### ISSUE TITLE
Migrate Logstash repository instructions to elastic.co

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2975]
Migrate http://logstash.net/docs/1.4.2/repositories to elastic.co

**Comment by untergeek** [comment]
What's the end result supposed to look like here, @suyograo?  Did you want me to address this?

**Comment by suyograo** [comment]
@untergeek the end result should be like this page in ES: http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
