### ISSUE TITLE
Elasticsearch version when using logstash 1.4.2

### ISSUE THREAD

**Issue by kkebb** [elastic/logstash#2976]
Hello,

I was wondering what version is elasticsearch considered to be at when using logstash 1.4.2 because I was wondering if the bloom command is available (according to the link below), or is it deprecated seeing that the version of logstash is above 1.4.2?

http://www.elastic.co/guide/en/elasticsearch/client/curator/current/bloom.html

**Comment by untergeek** [comment]
Are you using 
```
embedded => true
```
in your Elasticsearch output block?  If you are, then the Elasticsearch version is old enough to use the bloom command in Curator.  If your cluster is separate, which is the recommended way, then it depends solely on what version of Elasticsearch you have deployed.

**Comment by kkebb** [comment]
Perfect, thanks!
