### ISSUE TITLE
Bad mutate filter behavior due to nil type checking

### ISSUE THREAD

**Issue by theNewFlesh** [elastic/logstash#2977]
So I have a config in which I am trying to rename/delete fields which occasionally have nil values.  When I rename a field with the mutate filters rename parameter, I get a new field, but the event fails to remove the old field.  When I use the remove_field parameter, it simply fails to remove the field.  Event.remove calls the del accessor.  The problem lies with the del accessor in logstash/lib/logstash/util/accessors.rb.

Here is the offending code:
```
 def del(accessor)
      target, key = lookup(accessor)
      unless target.nil?
        target.is_a?(Array) ? target.delete_at(key.to_i) : target.delete(key)
      end
    end
```
unless target.nil? prevents me from deleting and properly renaming fields within logstash (via mutate) when the value of the field (ie target) is nil.

Perhaps this check should be removed.

**Comment by theNewFlesh** [comment]
I see that this behavior has been added to 1.5.  Is there a safe work around?

**Comment by jsvd** [comment]
@theNewFlesh the problem with mutate renaming also present in 1.4.2:

```
logstash-1.4.2 % bin/logstash -e "
input { generator { count => 1 } }
filter { 
  ruby { code => \"event['field'] = nil\" }
  mutate { rename => { 'field' => 'meh' } }
}
output { stdout { codec => rubydebug } }"

Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2015-04-10T14:23:19.732Z",
          "host" => "Joaos-MBP-2.lan",
      "sequence" => 0,
         "field" => nil
}
```

However I believe that accessor code works (same behaviour on 1.4.2 and master):
```
% bin/logstash -e "
input { generator { count => 1 } }
filter { 
  ruby { code => \"event['field'] = nil\" }
  mutate { remove_field => 'field' }
}
output { stdout { codec => rubydebug } }"
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2015-04-10T14:25:58.663Z",
          "host" => "Joaos-MBP-2.lan",
      "sequence" => 0
}
```

**Comment by jsvd** [comment]
I've only seen this happen on mutate's rename, and it's due to `Event#include?`'s brokenness..the following test fails on master and 1.4.2:

```ruby
 describe "#include?" do
   context "when field value is nil" do
     subject { LogStash::Event.new("field" => nil) }
     it "should return true" do
       expect(subject.include?("field")).to be_true
     end
   end
 end
```

code for Event#include?:

```ruby
def include?(key)
  return !self[key].nil?
end
```

**Comment by jsvd** [comment]
This could be renamed to: Accessor doesn't distinguish between a missing key and a key with nil value.

**Comment by theNewFlesh** [comment]
Your'e right, I assumed my logstash installation was the same as what I was seeing on github.  It actually doesn't include said type checking, so that can't be the problem.

**Comment by theNewFlesh** [comment]
If Logstash events were made to subclass Hash, or mirror its fetch method, this would probably solve it:

```
def include?(key)
    begin
        self.fetch(key)
        return true
    rescue KeyError
        return false
    end
end
```

**Comment by theNewFlesh** [comment]
So the callback chain is event.include? --> event[] --> @accessors.get

If you are still wanting to use [] instead of fetch then get needs to throw a KeyError, which is then caught by event[] and any other methods that call @accessors.get

logstash/lib/logstash/util/accessors.rb
```
def get(accessor)
    @cache ||= {}
    @cache.fetch(accessor) ||= parse(accessor)
end
```

Making a fetch accessor is probably the way to go.

**Comment by talevy** [comment]
@theNewFlesh @jsvd I went ahead and made a fix for `include?`

**Comment by theNewFlesh** [comment]
Thank you kindly.
