### ISSUE TITLE
Can't parse number with grok

### ISSUE THREAD

**Issue by jensgerle** [elastic/logstash#2978]
Part of my log has the following entries:
[u:username j:job s:session h:http]
I can parse username, session and http, but the "job" number will not parse (it's an integer).
Here's my grok:
[u:%{DATA:user} j:%{NUMBER:job} s:%{DATA:Session} h:%{DATA:http}\]
I also tried to use DATA and a convert, INT, BASE10NUM but nothing would do it.
NOPSACE before the j: wouldn't do it either...
If I change my log settings (which I can't do other than for testing) and add a space after "j:" it will parse the number.
Please advise.

**Comment by jensgerle** [comment]
Postfix ":int" didn't work either

**Comment by markwalkom** [comment]
Github is reserved for code bugs. It'd be better if you could raise this on the mailing list - https://groups.google.com/forum/?hl=en-GB#!forum/logstash-users

**Comment by jensgerle** [comment]
Ok. I will do that and close the issue here...
