### ISSUE TITLE
Lack of settings for input and ouput for Redis cluster ?

### ISSUE THREAD

**Issue by liuxingyishi** [elastic/logstash#2979]
When I set an output to a node in redis-cluster(Redis 3.0.0),it can not direct to other nodes in redis-cluster automatically.Port 7000 to 7005 are used by redis cluster.
logstash logstash-simple.conf:
input { stdin { } }
output {
  redis {
     host => ["localhost:7000"]
     data_type => "list"
     key => "key_count"}
  stdout { codec => rubydebug }
}
logstash logs:exception=>#Redis::CommandError: MOVED 15454 127.0.0.1:7002
I supposed that it may be caused by logstash(redis-client role) was not started in cluster mode.

**Comment by untergeek** [comment]
The redis input and output are not yet able to use the clustering features of Redis.

**Comment by liuxingyishi** [comment]
Thanks for your kindly reply. I want to know whether there will be a development plan for this function.

**Comment by untergeek** [comment]
Indeed, this is a feature we'd like to add.  If it depends on us to add it, it won't be until after Logstash 1.5 is GA, as all our efforts are focused there.  Because it's open source, if someone in the community wants to take a stab at it and submit a pull request, it will likely be sooner.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-redis/issues/10. Let's continue the discussion there! :)
