### ISSUE TITLE
Lost Message in multiline Codec

### ISSUE THREAD

**Issue by iemem15** [elastic/logstash#2985]
Every time I run the multiline codec always lost a line of a file, It happened previously with the multiline filter, but I have test it and seems to work right, because I need to increase the workers I am using the multiline codec.
Is there something like the issue with the filter?
I am using the 1.5rc2 logstash

**Comment by purbon** [comment]
Hi,
  to provide more insides for this issue, can you share an example configuration file and workflow, so we're able to reproduce your issue.

/cheers

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
