### ISSUE TITLE
Logstash 1.5 Beta issue with filter

### ISSUE THREAD

**Issue by jindov** [elastic/logstash#2986]
message=>"Exception in filterworker", "exception"=>#<TypeError: can't convert nil into String>, "backtrace"=>["org/jruby/RubyString.java:1159:in `+'", "(ruby filter code):7:in `register'", "org/jruby/RubyArray.java:1613:in `each'", "(ruby filter code):5:in `register'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-0.1.2/lib/logstash/filters/ruby.rb:38:in `filter'", "(eval):5875:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):5871:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):5868:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):5858:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:268:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:206:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:150:in `start_filters'"], :level=>:error}

This is an error when I ran logstash for filtering. When occur error, logstash doesn't skip this error to pass another, it's stop filtering and need restart

**Comment by colinsurprenant** [comment]
thanks for the report @jindov - could you share your config and ideally also sample data that can trigger the crash?

**Comment by jindov** [comment]
Please to see config and sample data here http://stackoverflow.com/questions/28059088/analyze-sensu-log-with-logstash

**Comment by suyograo** [comment]
copied from SO:

```
if [type] == "sensu" {
            grok {
                match => [ "payload.check.output", "%{CISCO_REASON}: Request error: %{URI}" ]
            }
            mutate {
                add_field => { "error" => "%{payload.check.output}" }
                remove_field => [ "timestamp" ]
            }
        }
```

@colinsurprenant looks related to java collection support: https://github.com/elastic/logstash/pull/2991

**Comment by suyograo** [comment]
@jindov with your config snippet and sample data, I was not able to reproduce the issue. I am using the master branch though

```
{
         "level" => "info",
       "message" => "publishing check result",
       "payload" => {
        "client" => "local.com",
         "check" => {
                   "name" => "instance_xxx_check",
                 "issued" => 1421808200,
                "command" => "xargs -I{} sh -c '/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-http.rb -u {}' < /etc/sensu/conf.d/live/list/xxx.txt",
               "handlers" => [
                [0] "default",
                [1] "mailer"
            ],
               "interval" => 60,
            "subscribers" => [
                [0] "live"
            ],
               "executed" => 1421808200,
               "duration" => 1.317,
                 "output" => "CheckHTTP OK: 200, http://link1.com\nCheckHTTP CRITICAL: Request error: http://link2.com\nCheckHTTP OK: 200, http://link3.com\n",
                 "status" => 123
        }
    },
      "@version" => "1",
    "@timestamp" => "2015-04-14T01:41:39.673Z",
          "host" => "Suyogs-MacBook-Pro-2.local",
          "tags" => [
        [0] "_grokparsefailure"
    ],
         "error" => "%{payload.check.output}"
}
```

**Comment by ph** [comment]
@suyograo The exception is related to a ruby filter, I think you copied the wrong config from stackoverflow.

**Comment by colinsurprenant** [comment]
Ok, I understand what's going on. 
The exception is related to the *ruby filter* on the String `+` method. 
The config used is the one given in the accepted answer in the stackoverflow thread. 

my take is that the problem is with this line
```ruby
errormsg = errormsg + splitlog.split('error: ')[1];
```
there is probably no `'error: '` string to split in `splitlog` and this will return `nil` and generate an exception. 

for exaple
```ruby
"foobar".split("baz")[1]
=> nil
```

and

```ruby
 "" + nil
TypeError: can't convert nil into String
```

**Comment by colinsurprenant** [comment]
So I think you will have to review or add robustness to your Ruby filter code

**Comment by colinsurprenant** [comment]
@jindov did you find a solution?

**Comment by jindov** [comment]
Dear all,

I removed above config and have no any solution for replacing now
