### ISSUE TITLE
add_field adds boolean values as string

### ISSUE THREAD

**Issue by babadofar** [elastic/logstash#2987]
When using mutate add_field trying to add fields as boolean, the field is added as string. Can be seen both with rubydebug and json output
Tested on windows in logstash 1.4.2, 1.5.0.rc2 and also latest version pulled from github.
`
logstash-1.5.0.rc2\bin\logstash.bat  agent  -e 'filter{mutate{add_field => {"isthisbool" => false}}} output{stdout {codec => json}}'
fisk
{"message":"fisk\r","@version":"1","@timestamp":"2015-04-10T09:24:40.573Z","type":"stdin","host":"CV-E6420","isthisbool":"false"}
`
In this sample, "isthisbool" should have been false, not "false".

**Comment by untergeek** [comment]
Thanks for reporting this!  We definitely will want to address this.

Can you open it in the mutate filter repository instead, please?

https://github.com/logstash-plugins/logstash-filter-mutate

Thanks so much!

**Comment by babadofar** [comment]
OK I copied it there, closing this one

**Comment by untergeek** [comment]
Thanks!

**Comment by untergeek** [comment]
I was wrong, this is in the [base filter code](https://github.com/elastic/logstash/blob/3eb5ba6450a2c241d469cc1740c5c46cc7509f02/lib/logstash/filters/base.rb#L162-L177).  Reopening.

**Comment by suyograo** [comment]
Closed in lieu of https://github.com/logstash-plugins/logstash-filter-mutate/issues/20
