### ISSUE TITLE
Logstash gelf input supporting TCP

### ISSUE THREAD

**Issue by maxhyjal** [elastic/logstash#2988]
Is there any way to configure logstash gelf input for logstash server to listen on the TCP port instead of UDP? If not, is it going to be supported on logstash server sometime soon?

Thanks
Max

**Comment by markwalkom** [comment]
We've split the LS inputs and outputs into their own repo, so it's best if you create these sorts of plugin related issues on the specific plugin repo at https://github.com/logstash-plugins/

However someone has already raised this as an issue, so it'd be worth you adding a comment there - https://github.com/logstash-plugins/logstash-input-gelf/issues/6
