### ISSUE TITLE
New plugins: neo4j input and output

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2989]
I just created two new plugins to manage graph data with logstash.

* https://github.com/purbon/logstash-input-neo4j

* https://github.com/purbon/logstash-output-neo4j

The input basically read events regularly from a neo4j database and create events out of it. It can be used in order to important graph data throw logstash. On the other hand there is the neo4j output that is able to write a time based index in neo4j coming from LS.

It would be great to have them review by the community and know if they are good.

**Comment by purbon** [comment]
@jsvd @talevy do you mind giving this two newbies plugins a review ?

**Comment by suyograo** [comment]
@purbon this can wait until after 1.5?

**Comment by purbon** [comment]
sure! :-) I just added this here for bookkeeping

**Comment by purbon** [comment]
I closed this issue as I moved the two plugins as new host in the logstash-plugins organization, including a PR to be reviewed in there.
