### ISSUE TITLE
Logstash can not be restarted

### ISSUE THREAD

**Issue by spuder** [elastic/logstash#2992]
I've encountered this problem 3 times now over the course of a month. 

A brand new install of logstash 1.5rc2 on ubuntu 14.04 will get into a state where I can not stop or restart the process. (Installed with chef using community cookbooks).

When attempting to restart logstash, it timesout and says 'got TERM'

```
 service logstash_server restart
timeout: run: logstash_server: (pid 11797) 839785s, got TERM
```

Also asking stackoverflow for help in identifying the problem

http://unix.stackexchange.com/questions/195998/how-to-identify-why-a-process-wont-die

**Comment by ph** [comment]
Hello @spuder 
Maybe one of the input or outputs is hanging the process.
Would you mind pasting your configuration?

**Comment by suyograo** [comment]
@spuder also we fixed a bunch of shutdown issues related to : https://github.com/elastic/logstash/issues/2863

**Comment by spuder** [comment]
Sure, the output is below. 

When I strace the process, I see the following

```
strace -p 11797
Process 11797 attached
futex(0x7f6d95d8e9d0, FUTEX_WAIT, 11811, NULL

```

Will there be a 1.5rc3 ? that includes #2863 ? 


```
input {
  kafka {
    zk_connect => 'zoo-example.com:2181/kafka'
    consumer_threads => 3
    topic_id => 'foo'
  }
}

input {
  kafka {
    zk_connect => 'zoo-example.com:2181/kafka'
    consumer_threads => 3
    topic_id => 'bar'
  }
}

filter {
  mutate {
    gsub    => [ "[id][batchID]", "\D", "" ]
  }
  mutate {
    convert => [ "[id][batchID]", "integer"]
  }
}

filter {
  mutate {
    gsub    => [ "[id][docID]", "\D", "" ]
  }
  mutate {
    convert => [ "[id][docID]", "integer"]
  }
}

output {
  elasticsearch {
    host => 'elasticsearchpool.example.com'
    cluster => 'example.com'
    embedded => false
    protocol => 'http'
  }
}
```

**Comment by ph** [comment]
RC3 will include #2863,  ETA is really soon.

**Comment by suyograo** [comment]
Please

**Comment by spuder** [comment]
I have another instance of this happening. Logstash just randomly stops responding on ubuntu 14.04. 
I'm not able to figure out a work around, I just have to do a kill -9 on the process.

**Comment by spuder** [comment]
The log file has some interesting information. I suspect that this correlates to when I shutdown one of the eleastic search nodes today. 


http://pastebin.com/HRT1DJzm#

**Comment by suyograo** [comment]
@spuder can you try with RC3?

**Comment by spuder** [comment]
Thanks for letting me know RC3 is out. I will try tomorrow

**Comment by svenmueller** [comment]
same issue for me with latest `RC3` version

**Comment by spuder** [comment]
I have been running for 11 days without a crash/hang which is longer than logstash has gone before. 
I have even done a rolling upgrade of elasticsearch from 1.4.4 to 1.5.2 without logstash freaking out. 

I'm going to do a little more testing before I declare victory and close the issue. 

@svenmueller I'd recommend uploading your log file to pastebin and linking here.

**Comment by spuder** [comment]
18 days without a crash on RC3. Thanks for the fix.
