### ISSUE TITLE
Logstash CSV file with TAB separator

### ISSUE THREAD

**Issue by SanketV** [elastic/logstash#2996]
Hello, I've been trying to parse tab separated file. However, no luck.

** This is the sample data from GDELT.

424668549	20140412	201404	2014	2014.2795	GOV	GOVERNMENT						GOV													1	051	051	05	1	3.4	20	1	20	-1.57232704402516	2	Minnesota, United States	US	USMN	45.7326	-93.9196	MN	0							2	Minnesota, United States	US	USMN	45.7326	-93.9196	MN	20150412	http://www.startribune.com/politics/299465601.html

** Tried different separator e.g. "\t", "<tab>", and "	" (actual tab)
However, logstash does not seem to recognize any of them. And, it displays the output replacing tabs with "\t" as shown below.

Output:
    "GLOBALEVENTID" => "424668549\t20140412\t201404\t2014\t2014.2795\tGOV\tGOVER
NMENT\t\t\t\t\t\tGOV\t\t\t\t\t\t\t\t\t\t\t\t\t1\t051\t051\t05\t1\t3.4\t20\t1\t20
\t-1.57232704402516\t2\tMinnesota, United States\tUS\tUSMN\t45.7326\t-93.9196\tM
N\t0\t\t\t\t\t\t\t2\tMinnesota, United States\tUS\tUSMN\t45.7326\t-93.9196\tMN\t
20150412\thttp://www.startribune.com/politics/299465601.html"

Here is the config file.
input {  
      stdin{}
      file {
          path => "C:\Logstash\GDELT_Mini.txt"
          start_position => beginning
      }      
}

filter {  
    csv {
        columns => ["GLOBALEVENTID", "SQLDATE","MonthYear", "Year",  "FractionDate",  "Actor1Code", "Actor1Name",  "Actor1CountryCode", "Actor1KnownGroupCode",  "Actor1EthnicCode",  "Actor1Religion1Code", "Actor1Religion2Code","Actor1Type1Code", "Actor1Type2Code", "Actor1Type3Code", "Actor2Code", "Actor2Name" , "Actor2CountryCode", "Actor2KnownGroupCode",  "Actor2EthnicCode",  "Actor2Religion1Code", "Actor2Religion2Code", "Actor2Type1Code", "Actor2Type2Code", "Actor2Type3Code", "IsRootEvent", "EventCode", "EventBaseCode", "EventRootCode", "QuadClass", "GoldsteinScale",  "NumMentions", "NumSources",  "NumArticles", "AvgTone", "Actor1Geo_Type",  "Actor1Geo_FullName",  "Actor1Geo_CountryCode", "Actor1Geo_ADM1Code",  "Actor1Geo_Lat", "Actor1Geo_Long",  "Actor1Geo_FeatureID", "Actor2Geo_Type",  "Actor2Geo_FullName",  "Actor2Geo_CountryCode", "Actor2Geo_ADM1Code", "Actor2Geo_Lat", "Actor2Geo_Long",  "Actor2Geo_FeatureID", "ActionGeo_Type",  "ActionGeo_FullName",  "ActionGeo_CountryCode", "ActionGeo_ADM1Code",  "ActionGeo_Lat", "ActionGeo_Long",  "ActionGeo_FeatureID", "DATEADDED", "SOURCEURL"]
        separator => "  "
    }
}

output {  
     stdout {
         codec => rubydebug
     }
}

![logstash](https://cloud.githubusercontent.com/assets/11076962/7125008/152d5bec-e1f3-11e4-9019-e1e4d07890d7.jpg)

**Comment by untergeek** [comment]
I appreciate that you're having a hard time.  Usage questions typically belong in the [logstash user group](https://groups.google.com/d/forum/logstash-users) and/or in the #logstash IRC channel on irc.freenode.org.  You can also reach the #logstash IRC channel via http://webchat.freenode.net/

While we will eventually try to respond here, time permitting, you may get a much faster response from the community in the venues mentioned.
