### ISSUE TITLE
New plugin: output to slack

### ISSUE THREAD

**Issue by cyli** [elastic/logstash#3000]
I've attempted to create a new plugin as per [these instructions](http://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html#_publishing_to_ulink_url_http_rubygems_org_rubygems_org_ulink_4) for pushing log messages to slack:

https://github.com/cyli/logstash-output-slack

I've manually tested this, but it doesn't really have fantastic rspec coverage (not sure how to test logging on errors, for instance), and would love a review (as I don't really know Ruby) + moving this to [logstash-plugins](https://github.com/logstash-plugins)  :)

This would supercede [this PR](https://github.com/elastic/logstash-contrib/pull/120).

**Comment by suyograo** [comment]
@cyli thanks for your contribution to LS plugins. I created https://github.com/logstash-plugins/logstash-output-slack

Create a initial PR and we can all review it there

**Comment by purbon** [comment]
I'm going to close this issue as the motivation of it has been accomplished with a new repo and plugin being created. Lets move the discussion about this plugin there :-)

Thanks for contributing @cyli

**Comment by cyli** [comment]
Thanks for setting up the repo!  Pull request submitted.
