### ISSUE TITLE
csv_options in csv of outputs should not be escaped.

### ISSUE THREAD

**Issue by GeiliCode** [elastic/logstash#3001]
I followed the guide in http://logstash.net/docs/1.4.2/outputs/csv#csv_options, but the separator was escaped. For example:

a\t2015-04-14 06:24:07 UTC\t1\nb\t2015-04-14 06:24:08 UTC\t1\nc\t2015-04-14 06:24:09 UTC\t1\n""\t2015-04-14 06:24:09 UTC\t1\nd\t2015-04-14 06:24:10 UTC\t1\n 

Configuration:
input {
  stdin {}
}

output {
   csv {
    fields => [ "message", "@timestamp", "@version" ]
    csv_options => {"col_sep" => "\t" "row_sep" => "\n"} 
    path => "/tmp/test.csv"
  }
}

logstash version: 1.4.2

**Comment by suyograo** [comment]
@GeiliCode filed in https://github.com/logstash-plugins/logstash-output-csv/issues/2. Please create new issues in individual repos
