### ISSUE TITLE
Logstash messes up with my xml data!

### ISSUE THREAD

**Issue by Lilion12** [elastic/logstash#3004]
Hi all, 

I'm trying to use logstash to parse daily reports XML reports. 
These reports are quite big (a least 300 lines) and i'dlike to use xpath to extract the data from these reports. Everything is working fine except there must be an error between file input and xml plugin. 

I'll try to put this in an easy way ... 

I'm writing the output in a file for now.
The data in the "message" field does not correspond with the "path" variable. Example : I have the entry from the 9 Apr but the data in the message field is the data from the 1st Apr. 

Output Example

{"@timestamp":"2015-04-14T10:07:32.193Z","message":"[[BIG XML DATA FROM THE report_2015_01_04.xml]],"@version":"1","tags":["multiline","_xmlparsefailure"],"path":"/home/ubuntu/work/lek/machines/HOUPNTU3/report_2015_04_09.xml","machine":"HOUPNTU3","year":"2015","month":"04","day":"09","report_date":"2015_04_09","@report_date":"2015-04-09T00:00:00.000+02:00"}

Here is the conf : 

 ```
input {
	file{
	 	path => "/home/ubuntu/work/lek/machines/*/*.xml"
	 	discover_interval => 10
	 	start_position => "beginning"
	 	sincedb_path => "/dev/null"
	 	codec => multiline {
		      pattern => "^<\?xml .*\?>"
		      negate => true
		      what => "previous"
		    }
	}
}
filter{
	grok{
		match=> ["path", "/home/ubuntu/work/lek/machines/%{WORD:machine}/report_%{NUMBER:year}_%{MONTHNUM:month}_%{MONTHDAY:day}.xml"]
	}
 	mutate {
    	add_field => {"report_date" => "%{year}_%{month}_%{day}"}
    }
	date{
		match => ["report_date", "yyyy_MM_dd"]			
		target => "@report_date"
	}
	ruby {
        code => "
                event['@report_date'] = event['@report_date'].localtime('+02:00')
        "
    }
	xml{
		store_xml => true
		source => "message"
		target => "xml"
		
	}
	mutate{
		remove_field => [ "host"]

	}
}
output {
  stdout { codec => json } 
  file {codec => json
  		 path => "/home/ubuntu/lek/output/result.out" } 
 
} 
```

Any idea?
Thanks in advance ;)

**Comment by wiibaa** [comment]
There is an open issue between file input and multiline codec https://github.com/logstash-plugins/logstash-input-file/issues/10
Current workaround is to use multiline filter

**Comment by Lilion12** [comment]
Ok thanks for your reply. I Ended up removing all the '\n' in the xml file (only one xml entry in the file) and appending a final '\n' at the end. 
Works like a charm excepted i'm getting a duplicated event without the xpath matched field but this is another issue. 

Cheers!
