### ISSUE TITLE
simplify or eliminate boilerplate code plugins need to load jars

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#3005]
Each plugin that has to load jars needs to have a `*_jars.rb` file with the fixed block of code:

``` ruby
# encoding: utf-8
require 'logstash/environment'

ROOT_DIR   = File.expand_path(File.join(File.dirname(__FILE__), ".."))
LogStash::Environment.load_runtime_jars! File.join(ROOT_DIR, "vendor")
```

This amount of code should not be necessary, we should reduce this to 1 liner executed during `register` or `initialize` or even detect the presence of jars automatically.

**Comment by purbon** [comment]
+1 on this idea. I like the automatic one liner task.

**Comment by ph** [comment]
We are using `jar-dependency` for that now we can safely close this issue.
