### ISSUE TITLE
Better filter documentation 

### ISSUE THREAD

**Issue by arei** [elastic/logstash#3007]
The documentation for the various filters should include better documentation including "before" and "after" examples that clearly illustrate the transform.

**Comment by acchen97** [comment]
Can you please provide some details on specific filter plugins you'd be interested in here?

**Comment by arei** [comment]
No, sorry.  Either the docs have been updated since I made this request and this was addressed or I cannot find any examples of what I was asking for.

**Comment by acchen97** [comment]
Thanks - please feel free to open another issue if it arises!
