### ISSUE TITLE
New plugin: log4j2 input

### ISSUE THREAD

**Issue by jurmous** [elastic/logstash#3019]
I would like to contribute back the log4j2 input plugin to the logstash community.

It is available here:
https://github.com/jurmous/logstash-log4j2

What would it take to get it in the logstash-plugins?

**Comment by purbon** [comment]
Hi,
  thank your for taking your time to contribute back! I took a look at your plugin and it's interesting, the process to have this done will be:

* we create a new repo inside the ls-plugins org.
* you do a PR there with your plugin code.
* we all review and merge.

is this ok for you? do you want me to start doing it?

I took a look at your plugin code base and before going forward and merging it would be great for you to add some test so you can make sure all works as expected always. You can take a look at https://github.com/logstash-plugins/logstash-input-log4j for some inspiration for write test.

Looking forward to have this merge.

**Comment by jurmous** [comment]
I have created a similar test as log4j in a feature branch and am not sure on how to run it yet. (Tried bundle exec spec but doesn't run it yet)

Let's make that repo and do a PR. Then we can work on everything from there.

**Comment by purbon** [comment]
you can run this test by calling ``` bundle exec rspec```  I will recommend you to do a PR including test as is something we are looking forward all the time when reviewing PR's ... but if you have problems with the testing we can always help you a lot.

I will create the repo, so we can work from there. Keep in mind to include the test :+1:

**Comment by jurmous** [comment]
I have a branch including the test here: https://github.com/jurmous/logstash-log4j2/tree/feature-spec

**Comment by purbon** [comment]
But this test has only a very simple registry test, there is no test for the behaviour ... so I propose you merge the two in a PR for the new repo and work from there to add more test, makes sense to you?

/cheers

**Comment by purbon** [comment]
Good morning.
  I just created a new repo for you in https://github.com/logstash-plugins/logstash-input-log4j2, feel free to commit a PR there so we all can review and merge :-) 

Keep in mind to include test in your PR.

Looking forward to have this plugin onboard.

Let me know any more questions you might have, but for now I'm closing this issue.
