### ISSUE TITLE
Running out of files and plugin not restartig

### ISSUE THREAD

**Issue by skshandilya** [elastic/logstash#3020]
This is the first time we have seen an issue where logstash is running as a process but has failed to send data with the error message too many open files...
Here are the failures and the version of logstash is logstash-1.4.1-1_bd507eb.noarch

{:timestamp=>"2015-04-15T03:12:09.284000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Tcp host=>\"0.0.0.0\", add_field=>{\"record_type\"=>\"event_record\"}, tags=>[\"\"], mode=>\"server\">\n  Error: closed stream", :level=>:error}
{:timestamp=>"2015-04-15T03:12:10.215000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>26, :exception=>#<SocketError: initialize: java.net.SocketException: Too many open files>, :backtrace=>["org/jruby/ext/socket/RubySocket.java:190:in `initialize'", "org/jruby/RubyIO.java:852:in `new'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:146:in `connect'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:139:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:406:in `connect'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/pool.rb:48:in `fetch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:403:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:319:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:217:in `post!'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:218:in `post'", "/opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:213:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

Our config at the input is
input {
        tcp {
                host        => "0.0.0.0"
                add_field => {record_type => "event_record"}
                port        => "10061"
                codec       => "json_lines"
                tags        => [ "" ]
        }

    udp {
        host        => "0.0.0.0"
        add_field => {record_type => "event_record"}
        port        => "10061"
        codec       => "json_lines"
        tags        => [ "" ]
        buffer_size => 10240
    }
}
The output is to a locally running redis server.

**Comment by torrancew** [comment]
@skshandilya I'm a bit confused, as the error you posted is due to a closed stream, not too many open files. Could you share one of the file-related errors, as well? Also, how do you currently run Logstash? (what distro, official package/init script, etc)

**Comment by skshandilya** [comment]
too many open files could also mean no available sockets?

# rpm -qa | grep release
centos-release-6-6.el6.centos.12.2.x86_64
# rpm -q jre
jre-1.7.0_25-fcs.x86_64

Here is how we do things
```
logging sources -> **logstash** -> redis -> logstash -> proxy load balancer -> elasticsearch
                           \ -> direct to elasticsearch if errors are found
```
the problem is occurring at the bolded location 
Did more searching and found this https://github.com/elastic/logstash/issues/1604

**Comment by untergeek** [comment]
@skshandilya You should upgrade to at least Logstash 1.4.2.

**Comment by suyograo** [comment]
Please reopen if this issue can be reproduced with latest 2.x version
