### ISSUE TITLE
Parent/Child updates no way to specify routing

### ISSUE THREAD

**Issue by crickeys** [elastic/logstash#3026]
I am NEW to logstash and elasticsearch, so forgive me if this is obvious.

I have a parent/child relationship setup in elastic search. When I try to update the parent with logstash it sometimes works and sometimes not. I believe I've narrowed it down to getting a missing document error because I can't figure out how to specify routing using logstash. (Parent/Child relationships must route to the same shard apparently).

I thought elasticsearch would do this automatically given that I have setup the routing path in the document mappings but it only seems to work when I specify the routing parameter in the REST API URL. But, logstash doesn't seem to have a way to add that when updating. I'm using the logstash elastic-search output plugin with http protocol.

To add to my confusion it seems elasticsearch 1.5 is deprecating the "path" property in mappings.

Is there any way to ensure proper routing with parent/child updates using logstash?

**Comment by untergeek** [comment]
If it's a routing question, it will have to go into the [logstash-output-elasticsearch](https://github.com/logstash-plugins/logstash-output-elasticsearch) plugin repository, rather than this, the main/core repository.

**Comment by crickeys** [comment]
I'll move it over, thanks.
