### ISSUE TITLE
Using logstash 1.5.0 we receive stat.st_dev error when reading from file

### ISSUE THREAD

**Issue by Borak-Dev** [elastic/logstash#3033]
Hi

Whenever we're trying to read a file in order to capture the log information we get the following error:
NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:188

We've tried to execute several changes we've found on the web but no success was obtained.

Our test conf file is:

input {
#       stdin {}
        file {
                path => "/home/borak/correo/prueba.txt"
                type => "log"
                }
}

Thanks in advance

**Comment by untergeek** [comment]
What operating system and file-system is this on?

**Comment by Borak-Dev** [comment]
OS is "Ubuntu 14.04.2 LTS"
file-system is a single machine with Linux fs

**Comment by untergeek** [comment]
Sorry, forgot to ask what machine architecture.  ARM?  x86-64? Something else?

JRuby has issues with many non-x86 architectures.

**Comment by Borak-Dev** [comment]
It's a virtualized server (Ubuntu based) over a Intel (64bit) infrastructure.

**Comment by suyograo** [comment]
@Borak-Dev we fixed a bunch of issue for file input in RC3 which is soon to be released. However, this particular error you are experiencing is not something we've seen before.

I tried 1.5.0-rc3.snapshot on Ubuntu 14.0.4.2 and file input works fine

```
ubuntu@ip-10-0-1-9:~/logstash-1.5.0-rc3.snapshot3$ cat /proc/version
Linux version 3.13.0-44-generic (buildd@lamiak) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014
```

```
input {
   file {
      path => "/var/log/syslog"
      start_position => "beginning"
      type => 'log'
   }
}
```

**Comment by Borak-Dev** [comment]
We have tested with version logstash 1.5 RC2 but it doesn't work

**Comment by suyograo** [comment]
Keeping it open until we can tests with RC3

**Comment by colinsurprenant** [comment]
related to jruby/jruby#1754 ? (sorry can't dig, using phone now :P)

**Comment by yoke88** [comment]
i have encounter the same error 

     ubuntu@elk:/opt/logstash$ bin/logstash -e 'input { file { path=> "/var/log/nginx/access.log_json" codec => "json" } } output { elasticsearch { host => localhost } stdout { } }'

NotImplementedError: stat.st_dev unsupported or native support failed to load dev_major at org/jruby/RubyFileStat.java:188

    ubuntu@elk:/opt/logstash$ cat /proc/version
    Linux version 3.13.0-49-generic (buildd@akateko) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015

    ubuntu@elk:/opt/logstash$ bin/logstash -V
    logstash 1.5.0.rc2

**Comment by suyograo** [comment]
@yoke88 @Borak-Dev what is your java version? 

related: https://logstash.jira.com/browse/LOGSTASH-1819

**Comment by Borak-Dev** [comment]
We're using Java 1.8.40 
borak@testelk:~$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

WE'vw checked jruby/jruby#1754  in the past with no success, we will check issue 1819 and come back to you.

**Comment by Borak-Dev** [comment]
Hi Suyog.

All actions described on https://logstash.jira.com/browse/LOGSTASH-1819 were performed before opening the request. No success, sorry

**Comment by scottundead** [comment]
I'm having the same issue. 

```
root@ubuntu:/etc/logstash/conf.d# /opt/logstash/bin/logstash -V
logstash 1.5.0.rc2
root@ubuntu:/etc/logstash/conf.d# cat /proc/version
Linux version 3.13.0-49-generic (buildd@akateko) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015
root@ubuntu:/etc/logstash/conf.d# java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

It appears that I'm only getting this with file input:

```
input {
  file {
    path => "/var/log/network.log"
    sincedb_path => "/etc/logstash/sincedb/logstash"
    start_position => "beginning"
    type => "syslog"
    tags => "netsyslog"
  }
}

filter {
}

output {
    elasticsearch {
      host => localhost
      template => "/opt/logstash/elasticsearch-template.json"
      template_overwrite => true
    }
}
```

Getting the same error:

```
NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:188
  _discover_file at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/watch.rb:150
            each at org/jruby/RubyArray.java:1613
  _discover_file at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/watch.rb:132
           watch at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/watch.rb:38
            tail at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/tail.rb:68
             run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-file-0.1.6/lib/logstash/inputs/file.rb:133
            each at org/jruby/RubyArray.java:1613
             run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-file-0.1.6/lib/logstash/inputs/file.rb:133
     inputworker at /opt/logstash/lib/logstash/pipeline.rb:174
     start_input at /opt/logstash/lib/logstash/pipeline.rb:168
```

**Comment by jordansissel** [comment]
For folks having this issue, can you attach the output of the following commands:

* `ls -ld /tmp`
* `mount | grep /tmp`

**Comment by colinsurprenant** [comment]
@jordansissel did you really mean to check specifically the `/tmp` directory/filesystem? because in the reported exceptions the `file { path =>` were all pointing on `/var/log/...` ?

**Comment by Borak-Dev** [comment]
@jordansissel. Our answer:

ls -ld /tmp
drwxrwxrwt 8 root root 4096 abr 27 16:57 /tmp

mount | grep tmp
none on /sys/fs/cgroup type tmpfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)

**Comment by deusofnull** [comment]
I am also encountering this stat.st_dev error while using the file input...

Input conf:
```
input {
     file {
               path => "/var/log/nginx/*access*"
               type => "nginx_access"
        }
}
```

Error:
```
NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:188
  _discover_file at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/watch.rb:150
            each at org/jruby/RubyArray.java:1613
  _discover_file at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/watch.rb:132
           watch at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/watch.rb:38
            tail at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.6.1/lib/filewatch/tail.rb:68
             run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-file-0.1.6/lib/logstash/inputs/file.rb:133
            each at org/jruby/RubyArray.java:1613
             run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-file-0.1.6/lib/logstash/inputs/file.rb:133
     inputworker at /opt/logstash/lib/logstash/pipeline.rb:174
     start_input at /opt/logstash/lib/logstash/pipeline.rb:168
```

The output of @jordansissel 's request:
```
$ ls -ld /tmp
drwxrwxrwt 9 root root 4096 Apr 28 10:33 /tmp

$ mount | grep tmp 
udev on /dev type devtmpfs (rw,mode=0755)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)

```

Best & Thanks!

**Comment by jsvd** [comment]
This seems to be an [issue with JRuby and Oracle's JVM](https://github.com/jruby/jruby/issues/2913), are you able to install OpenJDK and check if the problem still occurs?

**Comment by jordansissel** [comment]
Closing this in favor of tracking it in #3127
