### ISSUE TITLE
connecting with a mixed-version SSL certificate causes logstash to self-immolate

### ISSUE THREAD

**Issue by downneck** [elastic/logstash#3043]
using logstash-forwarder and connecting with an x509v1 SSL certificate that includes x509v3 extensions (due to misconfiguration in openssl) causes the following error:

```  no more data allowed for version 1 certificate```

after which logstash shuts down its network port and stops working, although the process is still running.

my stack is: logstash-1.4.2, kibana-4.0.2, elasticsearch-1.5.1, logstash-forwarder-0.4.0

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/17. Let's continue the discussion there! :)
