### ISSUE TITLE
Provide guidance on the right way to set charset

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#3044]
We have deprecated the charset option (http://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html#plugins-inputs-tcp-charset), it will be nice to provide the now-recommended alternative along with the deprecation message, eg.

```
codec => plain {
      charset => "your_charset"
}
```

**Comment by suyograo** [comment]
@palecur this can be changed here: https://github.com/elastic/logstash/blob/master/lib/logstash/inputs/base.rb#L43

**Comment by jordansissel** [comment]
Proposed fix: https://github.com/elastic/logstash/pull/3395
