### ISSUE TITLE
CSV::MalformedCSVError: Illegal quoting in line 1 with SmarterCSV

### ISSUE THREAD

**Issue by Rajasree** [elastic/logstash#3045]
I have an issue, when trying to process a csv file, using SmarterCSV. The error I get is -

CSV::MalformedCSVError: Illegal quoting in line 1
This is where the code I use to process the csv file

SmarterCSV.process(file_path)
I have gone through similar questions. But no where I find a good fit that could help me.

I tried to resolve it using some options of SmarterCSV such as -
:remove_empty_values, :remove_empty_hashes etc. But in vain.

I welcome the suggestions or refactoring to make this work? Thanks all

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-csv/issues/10. Let's continue the discussion there! :)
