### ISSUE TITLE
Add docker build environment?

### ISSUE THREAD

**Issue by ChristianKniep** [elastic/logstash#3046]
Hey there... To test the zeromq plugin I branched logstash and created a fig file to help me spin up a dev environment.
Something to consider? http://qnib.org/2015/04/19/logstash-dev/

**Comment by untergeek** [comment]
Thanks for sharing your idea!  We love that you're thinking of ways to improve Logstash.  

We're already on a path to use Docker images to test plugins.  We're going with custom-built Docker images which will be referenced through the RSpec files, like this: https://github.com/logstash-plugins/logstash-output-zabbix/blob/master/spec/outputs/zabbix_spec.rb#L233-L264

In this way, the Docker image can be referenced, built into a container, the test run, and the container torn down from within the RSpec test itself, and therefore no other processes are required.  

We have only just barely embarked on the journey to getting this working.  Zabbix was the first plugin to get the Docker treatment.  The Elasticsearch output plugin is getting the treatment now.

**Comment by ChristianKniep** [comment]
Sauber! I figured that docker is to much fun to be left out by you guys. Keep humming!
