### ISSUE TITLE
Detect the to use of `to_json`

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3050]
Plugins developpers should not use the ruby implementation of `to_json` but instead use our `LogStash::Json.dump` or `LogStash::Json.load` which use the Jrjackson gem.

**Comment by suyograo** [comment]
This should also be documented as an addendum to "How-to write a Plugin" -- best coding practices/rules while dealing with LS code base

**Comment by suyograo** [comment]
Thanks to @jsvd all plugins that have an outstanding PR to fix the use of `to_json`: https://github.com/search?utf8=%E2%9C%93&q=author%3Acolinsurprenant+is%3Apr+user%3Alogstash-plugins+is%3Aopen+api&type=Issues&ref=searchresults
