### ISSUE TITLE
Bad Install with Java 9

### ISSUE THREAD

**Issue by pcrook** [elastic/logstash#3054]
I installed logstash 1.4.2-modified on Ubuntu 14.04 that had no previously installed Java version.  This automatically installed and used a Java 9 package.  This resulted in logstash repeatedly respawning and dying until I was able to track down the problem.

I used the following installation procedure:
`wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -`
`echo "deb http://packages.elasticsearch.org/logstash/1.4/debian stable main" >> /etc/apt/sources.list`
`aptitude update`
`aptitude install logstash`
A list of dependencies was shown that included Java 9, whicvh I assumed was required:
`The following NEW packages will be installed:`
`binutils{a} gsfonts-x11{a} java-common{a} libfontenc1{a} libxfont1{a} logstash`
`oracle-java9-installer{a} x11-common{a} xfonts-encodings{a} xfonts-utils{a}`
Note the `oracle-java9-installer` above.  After I started the service (`sudo service logstash start`), the respawning started.  In `/var/log/upstart/logstash.log` I saw scores of this message:
`Exception in thread "main" java.lang.ExceptionInInitializerError`
`	at org.jruby.Main.<init>(Main.java:99)`
`	at org.jruby.Main.main(Main.java:193)`
`Caused by: java.lang.RuntimeException: unsupported Java version: 1.9`
`	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1878)`
`	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1585)`
`	... 2 more`
`Java HotSpot(TM) 64-Bit Server VM warning: The UseParNewGC flag is deprecated and will likely be removed in a future release`
Note the `unsupported Java version: 1.9` above.  So the Java version that was automatically installed was not acceptable to logstash.
I did an `apt-rdepends logstash` and got:
`logstash`
`  Depends: j2re1.7`
`  Depends: java6-runtime-headless`
`  Depends: java7-runtime-headless`
`j2re1.7`
`java6-runtime-headless`
`java7-runtime-headless`
No Java 9 dependency there, so I did an `apt-cache policy oracle-java9-installer` and saw that this package claimed to provide much:
`Provides: default-jre, default-jre-headless, icedtea-6-plugin, icedtea-7-plugin, java-compiler, java-jdk, java-runtime, java-runtime-headless, java-sdk, java-virtual-machine, java2-jdk, java2-runtime, java2-runtime-headless, java2-sdk, java5-jdk, java5-runtime, java5-runtime-headless, java5-sdk, java6-jdk, java6-runtime, java6-runtime-headless, java6-sdk, java7-jdk, java7-runtime, java7-runtime-headless, java7-sdk, java8-jdk, java8-runtime, java8-runtime-headless, java8-sdk, java9-jdk, java9-runtime, java9-runtime-headless, java9-sdk, openjdk-6-jre, openjdk-6-jre-headless, openjdk-7-jdk, openjdk-7-jre, openjdk-7-jre-headless, oracle-java7-bin, oracle-java7-fonts, oracle-java7-jdk, oracle-java7-jre, oracle-java7-plugin, oracle-java8-bin, oracle-java8-fonts, oracle-java8-jdk, oracle-java8-jre, oracle-java8-plugin, oracle-java9-bin, oracle-java9-fonts, oracle-java9-jdk, oracle-java9-jre, oracle-java9-plugin`
Note that the Java 9 package claims to provide both `java6-runtime-headless` and  `java7-runtime-headless`, two of logstash's dependencies.  I believe this is the root cause of the problem.
Here's the source of the package via `apt-cache policy oracle-java9-installer`
`oracle-java9-installer:`
  `Installed: 9b59-1~webupd8~0`
  `Candidate: 9b59-1~webupd8~0`
  `Version table:`
 `*** 9b59-1~webupd8~0 0`
        `500 http://ppa.launchpad.net/webupd8team/java/ubuntu/ trusty/main amd64 Packages`
        `100 /var/lib/dpkg/status`

**Comment by torrancew** [comment]
For clarity, I was chatting with @pcrook when he discovered this issue, and suggested he post it here, not because we think it is the fault of Logstash, persay, but as another "pro" in the argument for removing the JRE dependency - #1290. I see upon trying to find the right issues to reference, that that was merged in #1640. @pcrook, looks like 1.5.0 will fix this.

**Comment by jordansissel** [comment]
The packages we build no longer have a dependency on java as of Logstash 1.5.0
