### ISSUE TITLE
Strange management of event generated by elapsed filter

### ISSUE THREAD

**Issue by mbomassimo** [elastic/logstash#3057]
During the use of the elapsed filter I discovered the following strange behaviuor of the logstash pipeline.
The filter work correctly and, in the case of missing matched end event a new event with tag "expired_error" is generated.
At this event (without a type) will be apply also the filter present in the configuration file following the elapsed filter indipendently of the conditional statement present in the configuration file.
Thereafter an examples:

```
.......
filter {
   ...
   if [type] == "onetype" {
            elapsed {
             start_tag       => "STS-START"
             end_tag         => "STS-END"
             unique_id_field => "bcid"
             timeout         => 30
             new_event_on_match => true
         }
  }
  if [type] == "onotherype" {
         multiline {
            patterns_dir => "./patterns"
            pattern      => "^%{EVENTO}"
            negate       => "true"
            what         => "previous"
         }
         grok {
            patterns_dir => "./patterns"
            match => [ 
                       "message", "%{BC_EVENT_LOG_RESID}",
                       "message", "%{BC_EVENT_LOG}"
                     ]
            add_tag    => [ "BC_EVENT_OK" ]
         }  
   }
}
```
In this case the event generated y the elapsed filter is processed also by the filter multiline  and if multiline do not discard the event it will be processed also by grok.
The conditional statement on the event generated by the elapsed are not evaluated.

**Comment by wiibaa** [comment]
@mbomassimo can you please specify your logstash version ?

**Comment by mbomassimo** [comment]
logstash version 1.4.2

**Comment by wiibaa** [comment]
@mbomassimo thanks for confirming, 1.4.2 and previous version are all affected by a bug in the event pipeline resulting to the behaviour you describe, this is only fixed in 1.5 through #1545.
Could you envisage testing 1.5 release candidate package (currently rc2 but rc3 should come soon) or you must stick to  **new_event_on_match => false** if possible for you

**Comment by mbomassimo** [comment]
OK, Thanks.
My workaround is to put the elapsed filter at the end of the filter pipeline.
The errors is present in all event of tag "expired_error" and this events doesn't depend of flag new_event_on_match.

**Comment by wiibaa** [comment]
As you have a workaround and this won't be an issue in 1.5.0, would you accept to close this issue and then can you please do it.THanks

**Comment by mbomassimo** [comment]
NOTE:
The same test with logstash-1.5.0.rc2 doesn't work.
Elapsed doesn't generate any event (no match event and no expired event)..
Probably there is incompatibility between logstash 1.5.0 and logstash-filter-elapsed-0.1.5

**Comment by wiibaa** [comment]
@mbomassimo sorry for that. could you please raise the issue directly in https://github.com/logstash-plugins/logstash-filter-elapsed/issues for better tracking. Thanks
