### ISSUE TITLE
clean the jenkins package generation jobs

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3082]
as discussed with @ph and @purbon we need to:
- remove the first task that runs the tests prior to generating the artifacts in the artifacts jenkins jobs.
- was there any particular reason for using Ruby 1.9.3 for the jenkins artifacts task? if not, we should change it to JRuby.

**Comment by purbon** [comment]
Internal Jenkins job has been updated as requested, now there are specific test/regression jobs, with specific build jobs that are only triggered if the previous test job is successful.

**Comment by purbon** [comment]
Speaking about using ruby for building, is there any particular reason not to use it?

**Comment by colinsurprenant** [comment]
so can we close this?

**Comment by colinsurprenant** [comment]
@suyograo did you verify the changes?

**Comment by suyograo** [comment]
Verified the artifacts created from the new Jenkins job. They all pass the smoke tests, so calling this done
