### ISSUE TITLE
Logstash significantly slows down with longer grok pattern

### ISSUE THREAD

**Issue by rakesh91** [elastic/logstash#3094]
Hi,
I have been using logstash to parse my logs, lately I wanted to add few more fields to my logs. After updating my grok patterns for it logstash has significantly reduced its speed. I was getting around 3k output before the new pattern, now around 200 to 300. 

I had around 20 fields back then, I increased 6 more.
What is the reason for this sudden performance degrade?

**Comment by wiibaa** [comment]
Hello, can you please share your pattern before/after configuration ?

**Comment by rakesh91** [comment]
Hi,
Before all the logs were parsed by 
(%{IPORHOST:akamai-ip}|%{DATA:akamai-ip}) (?:%{QUOTEDSTRING:ident}|-) %{DATA:auth} \[%{HTTPDATE:time}\] \"(?:%{WORD:requesttype} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response-code} (?:%{NUMBER:bytes}|-) %{QS:referrer} %{QS:agent} %{QUOTEDSTRING:apache-cookie} %{NUMBER:seconds_delete} %{NUMBER:response-time-in-microsec}  \"(?:%{IPORHOST:client-ip}|-)\"

Now only few logs has this new parser
(%{IPORHOST:akamai-ip}|%{DATA:akamai-ip}) (?:%{QUOTEDSTRING:ident}|-) %{DATA:auth} \[%{HTTPDATE:time}\] \"(?:%{WORD:requesttype} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response-code} (?:%{NUMBER:bytes}|-) %{QS:referrer} %{QS:agent} %{QUOTEDSTRING:apache-cookie} %{NUMBER:seconds_delete} %{NUMBER:response-time-in-microsec}  \"(?:%{IPORHOST:client-ip}|-)\" \"%{NUMBER:apiversion}\" %{DATA:appagent} \"%{NUMBER:appversion}\" %{QS:SOURCETYPE} %{DATA:platform} %{QS:token}

Only around 5% of the original logs has to match this new format. So I have put the new parser above the old one.

**Comment by wiibaa** [comment]
Sorry I have no simple explanation right now for the drop of performance, maybe I would suspect the numerous QUOTEDSTRING as this is an heavy pattern
As you mention a very small ratio of events having the additional info, maybe you could try a workaround that would look like this **(untested)**
````
grok {
  match => { "message" => "(%{IPORHOST:akamai-ip}|%{DATA:akamai-ip}) (?:%{QUOTEDSTRING:ident}|-) %{DATA:auth} [%{HTTPDATE:time}] \"(?:%{WORD:requesttype} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response-code} (?:%{NUMBER:bytes}|-) %{QS:referrer} %{QS:agent} %{QUOTEDSTRING:apache-cookie} %{NUMBER:seconds_delete} %{NUMBER:response-time-in-microsec} \"(?:%{IPORHOST:client-ip}|-)\"%{SPACE}%{GREEDYDATA:remainder}" }
}
if [remainder] {
  grok {
    match => { "remainder" => "\"%{NUMBER:apiversion}\" %{DATA:appagent} \"%{NUMBER:appversion}\" %{QS:SOURCETYPE} %{DATA:platform} %{QS:token}" }
  }
}
````

**Comment by rakesh91** [comment]
The raise in performance is very little, now its parsing 500. What else can I do? Is it better to have new logstash instance for the new logs?

**Comment by wiibaa** [comment]
I'm not an expert in regexes but to raise your perf, you could try the following if applicable:
* specify that the regex should match only from the start of the message prefixing your regex with `^`
* try to change the quotedstring pattern to something simpler like https://github.com/weppos/apachelogregex/blob/master/lib/apache_log_regex.rb#L161
* replace the quoted string usage by `\"%{DATA}\"` when you are sure that the quoted contains do not contain additional *inner quotes*

**Comment by rakesh91** [comment]
Thanks a lot. Will try it out.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-grok/issues/39. Let's continue the discussion there! :)
