### ISSUE TITLE
Logstash User Survey Results

### ISSUE THREAD

**Issue by tbragin** [elastic/logstash#3095]
In case you hadn't heard about it, we asked all of our community members to tell us more about how they use Logstash, including praise and pain points. We just published the results of this survey on our blog: 
https://www.elastic.co/blog/logstash-user-survey-results

In this blog post, we shared our summary of the results as well as provided links to the raw results in case anyone is interested in doing more analysis.

This issue has been opened to discuss results of the survey, share additional analysis, and offer feedback and suggestions for future surveys. 

Thank you, all!

**Comment by jsvd** [comment]
Maybe this could be added to the project's [wiki pages](https://github.com/elastic/logstash/wiki) on github?

**Comment by jordansissel** [comment]
This survey was super useful <3

I think we can close this issue now - we had discussions last year about it and used it to make changes in our roadmap. Woo!

**Comment by katjavaljavec** [comment]
Hi @tbragin , I know it's been a while ago, but I ran into the post recently and I found the blog really useful, however, the link to the raw files seems to be broken. I'd be grateful if you could fix it because I would love to try it myself.
Thanks!
