### ISSUE TITLE
remove logstash-core directories and fix paths to use the logstash-core bundled gem

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3096]
The 1.5.0-rc3 package includes the `logstash-core` gem and also has the `lib/`, `spec/` and `locale/` directories in the root of the package. This is redundant and we should leverage our `logstash-core` gem.

For this here’s what I suggest:

1- add the `spec/` and `locale/` directories in the `logstash-core` gem.
2- remove the `lib/`, `spec/` and `locale/` directories from the package root when building the artifacts
3- add the concept of both a package-home dir and a core-home dir
4- fix the `bin/` scripts, the `Environment` module and the few places that rely on `__FILE__` to use the proper package-home dir or a core-home dirs
5- make sure these work in the dual dev/package contexts where in dev the `logstash-core` code is local and in the package context the `logstash-core` code is under the `vendor/bundle/…` directory
6- make the `logstash-core` gem a proper plugin updatable by the plugin manager

This is the last mile to our gemification process and will allow us to update the core code without having to necessarily release a whole new package. This is very very very useful for bug fixes.

The changes are not very complicated and I think we should aim for 1.5.0.

**Comment by ph** [comment]
I agree this is something we have discussed before and we should definitively do it.

But, I do not agree that we need to do it for 1.5. Even if this change isn't technically complicated it still involve messing with the the current packages structure. IMHO this change would require us to do a RC release, so I think we should do it for 1.6 and release the current RC.

**Comment by colinsurprenant** [comment]
My reasoning is that there is no core code change involved, "messing" with the package structure is really only removing unused files/directories. The changes are actually only adjusting paths and this is the kind of changes that either work or not, but once working it has zero impact on on the core code.  

In any case, let's first submit a PR for this then we can assess when/for which version it will be merged.

**Comment by ph** [comment]
Are we planning to allow people to update the core within logstash?

**Comment by jordansissel** [comment]
I haven't thought of a reason to allow or encourage that (logstash-core upgrade) yet. Anyone?

**Comment by colinsurprenant** [comment]
bug fixes, for exactly the same reasons as with the plugins, no?

Fo example, let's say this is in place, we do a release and we start having reports of pipeline shutdown problems and we discover the we introduced a regression and we are somehow passing the wrong shutdown event down the pipeline. it's a one-line fix. I think we could simply update the logstash-core gem and tell our users to do a `bin/plugin update logstash-core` (or something similar). problem solved, no release cycle. 

Now this raises the versioning strategy and such, but I think this brings value to our users and empowers us to be able to publish bug fixes really fast, again, just like with the plugins.

**Comment by purbon** [comment]
HI,
  even I'm a bit late to the party, I think this is a very good discussion!!! however I would like to point out a few things. First of all we start with the logstash-core change for the plugins, not actually for the core, so I vote for having a complete discussion in here before rushing into this kind of changes. From now on, we should just introduce bug fixes into logstash, we should start with something like this, if possible for later versions.

I'm however not sure of the big pros/cons of doing this, here are my open questions:

* do we really want people to get releases throw updating logstash-core? what is then the benefit of having a package? 
* If we go that direction, when do we release a package vs releasing just a gem? However I somehow see a benefit for patches and bug fixes.

I wonder then if devops people will like us going the rails way, or if they are more comfortable getting a package, what do you think? I say so, because if we go that way really nothing prevent us from just going ```gem install logstash-core``` and start working, isn't?

Just a lof of open questions from me.

/cheers

**Comment by colinsurprenant** [comment]
@pere I do not see the package vs logstash-core updates contradiction. we should still do packages as we always do but having the ability to live update logstash-core allows us to push **bug fixes** without having to do a full release+packaging cycle **just like with the plugins**. I am **not** suggesting we do full releases through a logstash-core update. I see this only for bug fixes, security fixes, etc. For your devops concerns, this is **not** going the rails way, I don't see how this is different than what we already do with the plugins?! we are already all-in with the ability to live update the plugins...

There are 2 discussions here:
1- removing unnecessary code duplication by leveraging the fact that all core code is already included in the logstash-core gem and thus everything in the package root that is already in the gem is redundant should  be removed. 

2- once #1 is done, it allows us to consider proper logstash-core live updates which I think is the natural evolution of our gemification process, with all the caveats I already raised in terms of versioning policy. 

I believe #1 can be *considered* in the scope of 1.5 but #2 certainly not, as we need to understand & agree on the implications of this.

**Comment by purbon** [comment]
@colinsurprenant clear to me what you mean now :+1:, I think this is a good idea. Lets see how a PR for 1 looks like and the possible effects to add this before 1.5 GA, we should be very confident this is not adding more probable issues :smile: . If everything looks fine, I'm happy to consider 1 for 1.5 GA as we can understand the current situation as a minor bug.

Looking forward to the discussion about 2.
- purbon
