### ISSUE TITLE
Improvements to plugins versions

### ISSUE THREAD

**Issue by allenmchan** [elastic/logstash#3098]
It would be great if we can get the following:
- version number of the gem when running bin/plugin list. (This way we can see if there is any drift between the locally installed gem and the latest.)

- a place where we can see the change logs between the different gem versions. (Right now I cannot get a list of the improvements added in each version of gem. I would have to go through the list of pull requests and guess at which pull went to which version. ).

**Comment by ph** [comment]
You can already see the version number for the plugins if you do this command:
```
bin/plugin list --verbose
```

I agree we need a way to display the changelog per gem.

**Comment by allenmchan** [comment]
Ah perfect for the verbose. Maybe update the help file so it is clear there is this option?
current help command only shows this:
Usage:
    bin/plugin [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    install                       Install a plugin
    uninstall                     Uninstall a plugin
    update                        Install a plugin
    list                          List all installed plugins

Options:
    -h, --help                    print help

**Comment by ph** [comment]
This is not obvious but you can get help for each subcommand.
```
~/e/logstash git:master ❯❯❯ bin/plugin list --help                                                                                                                                                                                                                                                                                                                  ⏎ ⬆ ◼
Usage:
    bin/plugin list [OPTIONS] [PLUGIN]

Parameters:
    [PLUGIN]                      Part of plugin name to search for, leave empty for all plugins

Options:
    --installed                   List only explicitly installed plugins using bin/plugin install ... (default: false)
    --verbose                     Also show plugin version number (default: false)
    --group NAME                  Filter plugins per group: input, output, filter or codec
    -h, --help                    print help
```

**Comment by allenmchan** [comment]
nvm i see it now. So that request is no longer needed.
Usage:
    bin/plugin list [OPTIONS] [PLUGIN]

Parameters:
    [PLUGIN]                      Part of plugin name to search for, leave empty for all plugins

Options:
    --installed                   List only explicitly installed plugins using bin/plugin install ... (default: false)
    --verbose                     Also show plugin version number (default: false)
    --group NAME                  Filter plugins per group: input, output, filter or codec
    -h, --help                    print help

**Comment by allenmchan** [comment]
This can probably be merged to 3099. Seems like we are asking the same thing.

**Comment by ph** [comment]
I'll close this one in favor of #3099
