### ISSUE TITLE
improvement suggestion for logstash-plugin repos

### ISSUE THREAD

**Issue by remotesyssupport** [elastic/logstash#3099]
Sorry to be creating this request here but https://github.com/logstash-plugins has many repository to make this improvement suggestion

It would definitely be of great help if git repository for every logstash plugins [as they will be maintained separately] contains 

* A README.md relevant to that plugin along with may be examples or use-cases. As of now most or all of them have a boiler plate README.md
* A CHANGELOG.md showing the changes made [in the same spirit as it is done here: https://github.com/docker/docker/blob/master/CHANGELOG.md]

**Comment by jordansissel** [comment]
+1 on having a changelog (focusing on user concerns, not developer concerns)

+1 on having an online-readable README - we can automate the generation of this with our documentation generator we already use for publishing the plugin docs, I think. Thoughts, @untergeek and @kurtado?

> Sorry to be creating this request here

This is a fine place to create this request :)

**Comment by suyograo** [comment]
@remotesyssupport we do have a changelog for core, which includes the plugin issues for 1.5.0. Good idea to have a changelog per plugin

**Comment by remotesyssupport** [comment]
@jordansissel  Thanks.
@suyograo Yes I have been tracking that changelog for core and has helped me a lot.

**Comment by allenmchan** [comment]
Any comments or updates on this?
Today i found that my logstash-output-elasticsearch plugin was out of date. (i had 0.2.4 locally and latest was 0.2.7). I looked on rubygems.org and github but neither can tell me what changed. I just blindly updated. At the very least, can you label what pull requests went into what version?

**Comment by suyograo** [comment]
We started to maintain changelog on every plugin repo. https://github.com/logstash-plugins/logstash-output-elasticsearch

We need to backfill the changes, but moving forward all changes will be recorded.

**Comment by suyograo** [comment]
CHANGELOG is being maintained now.
