### ISSUE TITLE
logstash startup

### ISSUE THREAD

**Issue by ethai** [elastic/logstash#3106]
Hello there - just getting started with Logstash so really appreciate answers to my ignorant inquiries.  Now just a general question about running logstash on single host and that is quickstart intro guide as well as logstash book itself seem to reference running logstash by issuing something to the effect of:

bin/logstash -f logstash-simple.conf

It would output back the proper usage would be to run with one of the following command:

agent
version
web
rspec

can someone clarify if it should be corrected as such:

bin/logstash agent -f logstash-simple.conf

or am i missing something to run logstash in some sort of non agent mode?

**Comment by jsvd** [comment]
Hi @ethai which version of logstash are you running?

on 1.4.2 in a linux environment `bin/logstash -f config` is enough (defaults to agent mode)
on windows you need `bin/logstash agent -f config`, however

In 1.5.0 (currently you can download rc3) agent is always the default mode so you just need `bin/logstash -f config`

**Comment by ethai** [comment]
Hi jsvd, thanks for your concise response.
