### ISSUE TITLE
filters don't match netflow plugin data

### ISSUE THREAD

**Issue by killafunkinmofo** [elastic/logstash#3108]
Hello,

I have setup netflow codec and try to use filters such as geo-ip. I notice this is not working. I have found a workaround if I do a GROK like this:
grok {
match => [ "[netflow][ipv4_dst_addr]", "%{IP:[netflow][ipv4_dst_addr]}" ]
overwrite => "[netflow][ipv4_dst_addr]"
}

Below is relevent config that doesn't work. If I add the grok at the top of the filter to rewrite the exact same value to that ipv4_dst_addr field it works.

I saw similar issue with conditionals "if [netflow][src_as] == "0"  won't work unless I do similar grok to that src_as field.

Then [netflow][ipv4_dst_addr] will then work in geoip filter. 

 input {
    udp {
      port => 5556
      codec => netflow {
        definitions => "/opt/logstash/lib/logstash/codecs/netflow/netflow.yaml"
        versions => [5]
      }
    }
  }
geoip {
database => "/opt/logstash/GeoLiteCity.dat"
source => "[netflow][ipv4_src_addr]"
}
 output {
    stdout { codec => rubydebug }
}

Am I doing something wrong, or is this a bug?

**Comment by wrigby** [comment]
@killafunkinmofo For the GeoIP data, this is because of some internals in the Netflow codec - see logstash-plugins/logstash-codec-netflow#3. Once this is merged, it should be fixed.

I'm not sure about the `src_as` field - I suspect this may have something to do with how BinData is parsing the net flow data.

**Comment by colinsurprenant** [comment]
@killafunkinmofo @wrigby logstash-plugins/logstash-codec-netflow#8 should fix that and also fix all other  field types coercion. 
Thanks @killafunkinmofo for reporting this and @wrigby for your work on helping resolve.

**Comment by colinsurprenant** [comment]
closing by logstash-plugins/logstash-codec-netflow#8 - @killafunkinmofo let me know if it solves the issue for you
