### ISSUE TITLE
How to output to ssh remote or other remote file system

### ISSUE THREAD

**Issue by yhjhoo** [elastic/logstash#3112]
Is it possible to do so with current plugin? 

Basically I would like to get the original log file, but I found I could not download either from logstash or elaricsearch engine...

**Comment by markwalkom** [comment]
You can't do this using any current plugin unless the remote FS has been locally mounted.

**Comment by suyograo** [comment]
@yhjhoo could you please use the logstash-users mailing list for asking questions?
