### ISSUE TITLE
Exception 232, 213, 212, 395

### ISSUE THREAD

**Issue by nipunarora** [elastic/logstash#3119]
Hi I am getting the following exception for a few logs when they match two of my patterns in my logstash configuration file. It seems that logstash generates a matched pattern, but it does not contain any of the fields that I had configured in the pattern. 

It does however contain the tag for the pattern itself. 

I generated a small input file which contained only the problematic log enteries.
The  strange thing is that this problem never happens for the first log amongst these log messages, but happens for the rest of the logs.

The following is the debug log:

https://gist.github.com/nipunarora/51d156fe0d48b8b3996e

Logstash Configuration - https://gist.github.com/nipunarora/13c240f866fef12e6e7b
Sample Input Data - https://gist.github.com/nipunarora/f404141e68587b0f8fcf

**Comment by jordansissel** [comment]
From the debug log:

```
{:timestamp=>"2015-04-27T15:40:11.631000-0400", :message=>"Grok regexp threw exception", :exception=>"232", :level=>:warn, :file=>"logstash/filters/grok.rb", :line=>"331"}
```

**Comment by nipunarora** [comment]
Just as an add on I am using logstash-1.4.2 downloaded from: http://logstash.net/

**Comment by nipunarora** [comment]
@jordansissel - any insight as to what is causing this bug? I can also provide a sample logstash conf and input file if required?

**Comment by jordansissel** [comment]
I haven't had energy to look into this yet, but attaching your logstash config could help yes :)

**Comment by nipunarora** [comment]
@jordansissel - I have added the configuration and input file. I think we have a few patterns which are custom, but for this particular configuration I think they should be in the default logstash library. Please let me know if you are able to figure this out.

**Comment by untergeek** [comment]
Logstash 1.4.x is no longer supported.  If this issue persists, please open a new issue and reference this one.

Thanks!
