### ISSUE TITLE
UDP listener died with logstash 1.5.0-rc3

### ISSUE THREAD

**Issue by sbarrier** [elastic/logstash#3124]
Since upgrade from 1.5.0-RC2 to 1.5.0-RC3 logstash randomly crash.

```
{:timestamp=>"2015-04-28T06:52:16.298000-0700", :message=>"UDP listener died", :exception=>#<SocketError: recvfrom: name or service not known>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.4/lib/logstash/inputs/udp.rb:79:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.4/lib/logstash/inputs/udp.rb:49:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:177:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:171:in `start_input'"], :level=>:warn}
```

**Comment by jordansissel** [comment]
Can you attach your logstash config?

**Comment by sbarrier** [comment]
I can't attach the configuration but if that can help there's 2 UDP listener in input one with type "syslog" and the other one is type "netflow".
The first one receive events from rsyslog, the second one don't receive events actually. 
For syslog there's multiline,... everything was working fine in 1.5.0-RC2 and previous versions since months, since RC3 it crash after few hours.

**Comment by untergeek** [comment]
Are there any updates to this with regards to Logstash versions 2.0, 2.1, or 2.2?  If not, please feel free to close this ticket.
