### ISSUE TITLE
How to create an alias on two indexes with logstash?

### ISSUE THREAD

**Issue by mehmetozerr** [elastic/logstash#3130]
In the cluster that I am working on there are two main indexes, let's say indexA and indexB but these two indexes are indexed each day so normaly I have indexA-{+YYYY.MM.dd} and indexB-{+YYYY.MM.dd}.

What I want is to have one alias that gathers indexA-{+YYYY.MM.dd} and indexB-{+YYYY.MM.dd} together and named alias-{+YYYY.MM.dd}.

Does anyone know how to gather two indexes in one alias with logstash ?

Thank you in advance

**Comment by wiibaa** [comment]
Relevant response about why it is not possible to manage alias from logstash: https://github.com/elastic/logstash/issues/2791#issuecomment-93450455

Also for future evolution I recommend to read the section  *Not Kibana, But Is Amazing  (Or, the death of timestamped indices)* in https://www.elastic.co/blog/kurrently-kibana-2015-04-24

**Comment by suyograo** [comment]
Thanks @wiibaa
