### ISSUE TITLE
support consistent env variables between the Linux and Windows startup scripts

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3134]
the supported environment variables are not consistent between Linux and Windows. 

for example, in Linux we use `LS_HEAP_SIZE` while on it's `LS_MIN_MEM` and `LS_MAX_MEM`. 

I don't know what the history is for this but I think we should make them consistent as much as possible.

**Comment by pickypg** [comment]
Noticed that `LS_HEAP_SIZE` in the shell variant only sets `-Xmx` rather than both `-Xmx` and `-Xms`.

**Comment by suyograo** [comment]
Fixed #4085
