### ISSUE TITLE
Logstash 1.5RC2 stops passing through events, stacktrace included

### ISSUE THREAD

**Issue by ianmacl** [elastic/logstash#3136]
I have a ZeroMQ input and statsd and Elasticsearch output.
Logs: http://pastebin.com/svnJGf7D
Config: http://pastebin.com/E6umv9gq

When I upgraded to 1.5RC2 I found that after some period of time data would no longer make it to ElasticSearch or Statsd.  Looking at the network traffic and memory usage it appears that Logstash was continuing to accept traffic but was no longer sending traffic out.  I have attached graphs which show this.

This doesn't happen immediately - it generally happens after a number of hours. It also doesn't happen consistently - we have 18 indexers and generally only one or two will go down before we catch it and kick it.  I have not yet had a chance to create a test environment in which to replicate this.

![logentries](https://cloud.githubusercontent.com/assets/176534/7417993/3e2f424c-ef38-11e4-9046-a994c938782a.png)
![memoryusage](https://cloud.githubusercontent.com/assets/176534/7417992/3e2f1fec-ef38-11e4-932d-9bc1b2cd939a.png)
![network](https://cloud.githubusercontent.com/assets/176534/7417991/3e2e99e6-ef38-11e4-9a59-35046be9a7df.png)

**Comment by untergeek** [comment]
No updates since 1.5RC2, and Logstash is on 2.2.0 now.  Closing, but if you feel this is in error, please feel free to open a new issue and reference this one.

Thanks!
