### ISSUE TITLE
DoS using malcrafted packet

### ISSUE THREAD

**Issue by celesteking** [elastic/logstash#3138]
It's possible to bring logstash lumberjack input down and thus stop it from accepting logs via following:

```openssl s_client -connect server:port ```
After connection, just write something and press enter. That's enough to trigger error on server:

```
RuntimeError: Unknown frame type: 101
  header at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:149
    feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:100
     run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:227
  invoke at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.5/lib/logstash/inputs/lumberjack.rb:71
```

Input is no longer active.

```
# rpm -qf /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.5/lib/logstash/inputs/lumberjack.rb
logstash-1.5.0_rc3-1.noarch
```

**Comment by ph** [comment]
The current code will only retry on TCP related error, the accept loop should recover from parser error.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/20. Let's continue the discussion there! :)
