### ISSUE TITLE
Occasional _grokparsefailure

### ISSUE THREAD

**Issue by afzal273** [elastic/logstash#3139]
I'm using 2 logstash instances/nodes and then logstash forwarders send logs from about 20 machines to the 2 logstash instances. At times I see logs like -

thostname	 	%{syslog_hostname}
tmessage	 	%{syslog_message}
tsyslog_facility	 	user-level
#syslog_facility_code	 	1
tsyslog_severity	 	notice
#syslog_severity_code	 	5
?tags	 	  _grokparsefailure

From the same machine other logs show up fine. Are my logstash instances overloaded? How many logs per second can a logstash instance process without parse failures? I see about 40k logs a minute.

Out of 550,000 messages in 15 minutes there are about 1000 _grokparsefailure messages. What can I do so that every log is parsed?

**Comment by jordansissel** [comment]
I'm not sure I have enough to go on. This seems like something the support and user community can help you with also, and we just launched a wonderful new forum for that: https://discuss.elastic.co/ - Can you try asking there? (I'll close this in the meantime)
