### ISSUE TITLE
Store encrypted ES password in config file or allow prompt

### ISSUE THREAD

**Issue by sherry-ger** [elastic/logstash#3140]
The password for ES user is stored in plain text in the Logstash config file, which is not secure.  It would be better if the password is masked or encrypted in the config file.  Or prompt for the password at Logstash startup.

**Comment by jordansissel** [comment]
I don't have much deep thought at this time, other than I agree we should help users protect their configuration files, but my general feeling is that if an adversary has access to the config file, you've probably already lost.

That said, I'd love to figure out what we can do to help users :)

In the meantime, a workaround that satisfies both the 'encrypted' and 'prompt for a password' methods would be to use gpg to encrypt the config file on disk and securely create a temporary file (w/ O_EXCL) to store the decrypted configuration and pass that to logstash, then delete the configuration file.

For the long term, it is likely that the following concepts will change drastically: configuration files and managing individual nodes. Both of these things will be shaken up a bit when we release the configuration API and clustering features.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/143. Let's continue the discussion there! :)

**Comment by jh12z** [comment]
I think this issue should be addressed in the core of logstash so all the plugins could benefit from it in a consistent manner instead of doing it on a plugin by plugin basis.

Ideally any attribute in logstash config that a user/admin considers contains sensitive information (passwords, access keys, ...) could be entered encrypted using some symmetric encryption algorithm (eg. AES) with the global secret stored in some config file, entered in the command line or prompted at startup. This way at least there is no immediate risk of another person viewing your config files.

If done this way it would work out of the box for all the plugins.

What do you think? Should this issue be reopened?

**Comment by vroomvroomvroom** [comment]
YES!
please re-open.

**Comment by whisller** [comment]
Any news about this feature?

**Comment by jordansissel** [comment]
No news. 

As a workaround example, gpg to encrypt your configuration file and decrypt it before handing to Logstash to use - this makes it sound a bit simpler than it is, but it could satisfy your requirements.

**Comment by raghusumanth** [comment]
Hi Jordansissel,
        
Have you got any way to encript the logstash configuration files and fed it to logstash so that we can secure our logstash configuration files.

**Comment by jordansissel** [comment]
Not at this time but it is similar to a feature we want to deliver.

**Comment by Shabirmean** [comment]
Have there been any new updates that support encryption of config files in Logstash?

If not, can someone help me understand the workaround suggested by @jordansissel when he says::

In the meantime, a workaround that satisfies both the 'encrypted' and 'prompt for a password' methods would be to use gpg to encrypt the config file on disk and securely create a temporary file (w/ O_EXCL) to store the decrypted configuration and pass that to logstash, then delete the configuration file. I think this solution may offer a good starting point for users who want on-disk configuration to be secret. It has the additional benefit of not assuming what fields are secrets (passwords, etc) and allows you to treat the entire configuration as a secret.

**Comment by jordansissel** [comment]
There are no updates. If you wish to learn updates, please watch this ticket. Any updates will appear on this ticket.

**Comment by jordansissel** [comment]
Erm, I mispoke. This issue is currently closed .. 

We have another open issue somewhere to add encrypted secrets to Logstash (similar to how Elasticsearch is doing it).

That issue is here: https://github.com/elastic/logstash/issues/6892

**Comment by Shabirmean** [comment]
Thank you @jordansissel.

**Comment by jordansissel** [comment]
@Shabirmean my suggestion was not detailed enough, but the rough summary is this as a workaround:

1) Encrypt your configuration file (with whatever tool you choose)
2) Decrypt it safely and pass it only to Logstash, then destroy the decrypted result after Logstash has it

how you choose to implement the above is up to you.

Time permitting, we should have a secrets tool in a few months.

**Comment by Shabirmean** [comment]
@jordansissel 
Thank you very much 👍 
Much appreciated.

**Comment by Shabirmean** [comment]
On a side note - Docker has a feature called *Docker Secrets* which enables only specific containers to access unencrypted versions of the data maintained by the secrets manager. 

Maybe running log-stash in a docker environment in a dedicated container will enable its configs to be protected via this feature.
