### ISSUE TITLE
netflow codec support for IPFIX

### ISSUE THREAD

**Issue by gonrada** [elastic/logstash#3143]
I was wondering if the current netflow codec would/could support decoding IPFIX flow rather than netflow v5/9.
Unless I am mistaken, wouldn't it be as simple as updating [/lib/logstash/codecs/netflow/netflow.yaml](https://github.com/elastic/logstash/blob/v1.4.2/lib/logstash/codecs/netflow/netflow.yaml) with the values from http://www.iana.org/assignments/ipfix/ipfix.xml?

I did find this ticket wanting a ipfix input plugin https://github.com/elastic/logstash/issues/2525, however I feel that with the tcp input plugin and the netflow codec this could be accomplished without an additional input plugin.

**Comment by bodgit** [comment]
No, you need to do more than just change the YAML file. Despite being based on and very similar to Netflow v9, IPFIX has subtly different packet formats and is its own protocol. There's also no need to support either Netflow or IPFIX, the codec can support all three versions simultaneously.

See logstash-plugins/logstash-codec-netflow#10 for a PR containing basic IPFIX support. Tested to date with `softflowd` and OpenBSD's `pflow(4)`.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-codec-netflow/issues/14. Let's continue the discussion there! :)
