### ISSUE TITLE
Logstash Stalls - logstash-1.5.0_rc3-1

### ISSUE THREAD

**Issue by flippedootninja** [elastic/logstash#3144]
Hi,

I've noticed after upgrading to RC3-1 that logstash hangs/freezes after a few seconds of starting. Just using the netflow codec.

OS:  Centos 7 x64

 ps -ef | grep logstash
root      30204  28111 11 10:06 pts/1    00:00:48 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Xmx500m -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/logstash/runner.rb agent -f /etc/logstash/conf.d/ --debug
root      30665   6116  0 10:13 pts/0    00:00:00 grep --color=auto logstash

rpm -qa | grep logstash
logstash-1.5.0_rc3-1.noarch

 strace -p 30204
Process 30204 attached
futex(0x7f83e910a9d0, FUTEX_WAIT, 30221, NULL

input {
udp { port => 6544 type => "netflow" codec => netflow }
}

output {

if [type] == "netflow" {
    elasticsearch {
    host => "localhost"
    template => "/etc/logstash/elasticsearch-template.json"
    template_overwrite => true
    cluster => "elasticsearch"
    index => "netflow-%{+YYYY.MM.dd}"
}
}

else {

  elasticsearch {
    host => "localhost"
    cluster => "elasticsearch"
  }
}

if [type] == "netflow" {
  stdout { codec => rubydebug }
}
}

**Comment by ph** [comment]
Do you have the same issue with the latest version logstash 1.5.0 GA?

**Comment by untergeek** [comment]
No updates since last comment, so closing.  If you feel this is in error, please feel free to open a new issue and reference this one.

Thanks!
