### ISSUE TITLE
[DOCS] - clarification around index_type deprecation

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#3151]
Using 1.5 RC3

```
You are using a deprecated config setting "index_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future.  If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"index_type", :plugin=><LogStash::Outputs::ElasticSearch --->, :level=>:warn}
```

Yet the docs don't show this as deprecated.

**Comment by ismriv** [comment]
+1. Any alternatives?

**Comment by jordansissel** [comment]
@markwalkom I'm guessing the docs site wasn't updated against RC3? We should see where in the release process this failed. @suyograo?

**Comment by suyograo** [comment]
Looking at it. Will refresh the docs. @ismriv you can use `document_type` now. For the rationale, check this issue #https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/102

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/146. Let's continue the discussion there! :)
