### ISSUE TITLE
Cannot grok or mutate split records

### ISSUE THREAD

**Issue by ianmacl** [elastic/logstash#3154]
See also #1820 and #2816

In Logstash 1.4 you were unable to mutate or grok records that were split using the split filter.  As documented, this was resolved in #1820 and consequently this functionality worked as described in Logstash 1.5.0RC2.

Unfortunately, it seems there has been a regression in RC3 with this issue.  Please see https://gist.github.com/ianmacl/17346ceacd25988e1040 for example config, input and output with 1.5.0RC2 and 1.5.0RC3 (as packaged in the deb files on the repo).

**Comment by jsvd** [comment]
Sorry that you're hitting this :( the regression was addressed by https://github.com/elastic/logstash/pull/3110 (already merged in master)

**Comment by ianmacl** [comment]
Thanks @jsvd.  I suppose I'll wait for RC3.

**Comment by suyograo** [comment]
Fixed by #3110
