### ISSUE TITLE
bin/plugin update fails when there is a local gem installed

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3157]
1. Build a local `foo-logstash-plugin.gem` and install on logstash core
2. Do `bin/plugin update`

it fails with: 

```sh
ERROR: Update is not supported for manually defined plugins or local .gem plugin installations: foo-logstash-plugin
```

We should: 
1. Ignore this local gem(s) and update remaining gems installed via RubyGems
2. Re-word the warning so it is more developer friendly.

**Comment by colinsurprenant** [comment]
I'd argue it's not a "bug" since it was coded to behave like this by purpose. I would label that an enhancement.

**Comment by jsvd** [comment]
Agree, as suggested before, this error could either become a warning or just be ignored.

**Comment by ph** [comment]
Marked as enhancement, I will tackle 1 and 2.
