### ISSUE TITLE
No events pushed to ES (1.5.0.rc2 ->1.5.0.rc3)

### ISSUE THREAD

**Issue by svenmueller** [elastic/logstash#3164]
After upgrading to RC3 (from RC2), events are only pushed to ES for a couple of seconds after starting logstash service (can be seen in Kibana). After a couple of seconds, ES/Kibana doesn't show any incoming events anymore. Logstash service is running properly and the log files don't give any hint. 

The configuration/settings are already provided here: https://github.com/elastic/logstash/issues/3003

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/148. Let's continue the discussion there! :)
