### ISSUE TITLE
Install plugin from private gem repository

### ISSUE THREAD

**Issue by felipegs** [elastic/logstash#3168]
It would be nice if on the command bin/logstash install plugin-name we can pass the source.
Something like this 
bin/logstash install plugin-name --source http://www.myprivategemrepo.com

**Comment by purbon** [comment]
@felipegs This is nice, and actually was also brouch by @electrical in benefit of the puppet modules. How do you feel about having a command that let you change the source ? and then you can do all the installs from there ? this would be a more or less easy fix to add.

**Comment by felipegs** [comment]
Could be better if I can add a source, not change the source.
Cause if I need to update some other plugins I have to mirror these plugins on my private repo.

**Comment by ph** [comment]
This should be possible with `bundler` with a source block.

```
source 'http://myserver/rubygems/' do
  gem 'logstash-plugin-piratespeak'
end
```

@felipegs @purbon might worth it to investigate that route, but you need your own gemserver.

I did not personally test this, but it seem to have some issues: https://github.com/bundler/bundler/issues/3537 if not all the gems are available?

**Comment by ph** [comment]
@felipegs by source do you mean a git repo?

**Comment by purbon** [comment]
I think he just wanted to run the plugin installer with a given source, no interaction of bundler or changing the gemfile.

**Comment by felipegs** [comment]
@purbon source I mean a gem repository.

**Comment by purbon** [comment]
makes sense @felipegs

**Comment by suyograo** [comment]
Fixed in 2.x
