### ISSUE TITLE
File output plugin does not flush last lines of batch of events

### ISSUE THREAD

**Issue by KarlikB** [elastic/logstash#3169]
The file output plugin do not flush last events to the file if the speed of incoming events is quick (E.g. when creating syslog TCP messages quckly by script).

The not-flushed events are flushed out by new incoming events or by logstash process stop.
The  stdout output plugin works well for the same events, events are flushed into console without any delays.

There is workardound (with performance cost) -> set flush_interval => 0 to force flush for each message.

**Comment by KarlikB** [comment]
Tested on version 1.4.2

**Comment by jberryman** [comment]
See also https://github.com/logstash-plugins/logstash-output-file/issues/11 . This is a duplicate of #2638
