### ISSUE TITLE
Pending plugins with issues with LOGSTASH_HOME

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3175]
There are a couple of missing plugins with pending issues regarding LOGSTASH_HOME

https://github.com/logstash-plugins/logstash-input-syslog/issues/9

https://github.com/logstash-plugins/logstash-patterns-core/issues/32

will apply, and share with a PR, the same idea of the fix introduced to mutate in order to provide a fix to them.

**Comment by purbon** [comment]
I made a couple of PR to such plugins that basically apply the same fix as it was for done for grok and mutate.

Feel free to review:

https://github.com/logstash-plugins/logstash-patterns-core/pull/33

https://github.com/logstash-plugins/logstash-input-syslog/pull/10

@jsvd @colinsurprenant

**Comment by suyograo** [comment]
Fixed both the plugins, Jenkins is greeeen :+1:
