### ISSUE TITLE
[Docs] Class description is not getting converted to asciidoc

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3184]
Trying to generate a doc after installing all plugins. First off, `rake docs:generate-docs` is not working again. I then tried manually generating docs; the asciidoc is created without the class description blob. Every other section is generated fine. 

```
bin/logstash docgen -o asciidoc ./vendor/bundle/jruby/1.9/gems/logstash-input-heartbeat-0.1.6/lib/logstash/inputs/heartbeat.rb
```

**Comment by purbon** [comment]
The documentation generation was broken because of the github input plugins was having problems, fixed at https://github.com/logstash-plugins/logstash-input-github/pull/5

**Comment by purbon** [comment]
There is certainly some room for a refactoring in here. I will open an issue for that.
