### ISSUE TITLE
[Question] Virtual memory usage of logstash

### ISSUE THREAD

**Issue by Gwan-He** [elastic/logstash#3185]
I've noticed that when launching logstash in the beginning, it would occupy about 2GB virtual memory. And a day after, this amount was increased to 4GB. Thus I have a question: what's the reason that logstash used so many virtual memory? Would this amount increase unlimitedly until reach the vm limit if certain conditions are satisfied?

**Comment by suyograo** [comment]
Hi @Gwan-He, please ask your question on logstash-users mailing list. We use GitHub for issues. Thanks!
