### ISSUE TITLE
Permissions denied /var/lib/logstash/.sincedb_*

### ISSUE THREAD

**Issue by djob** [elastic/logstash#3186]
Hi,

i'm trying to install and test logstash/elasticsearch/kibana, but i'm stuck with this error in /var/log/logstash/logstash.log

I've checked permisions for that folder, and seems to be fine: logstash:logstash 775
```
{:timestamp=>"2015-05-07T06:47:10.346000+0200", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2015-05-07T06:47:10.352000+0200", :message=>"_sincedb_write rename/sync failed: /var/lib/logstash/.sincedb_797dd3e863d00f2efaeaf7cdff671371.new -> /var/lib/logstash/.sincedb_797dd3e863d00f2efaeaf7cdff671371: Permission denied - /var/lib/logstash/.sincedb_797dd3e863d00f2efaeaf7cdff671371.new or /var/lib/logstash/.sincedb_797dd3e863d00f2efaeaf7cdff671371", :level=>:warn}
```

What i'm trying to do is connect logstash with nginx access (and error) logs.

/etc/logstash/conf.d/nginx.conf

```
input {
  file {
    path => "/var/log/nginx/access.log"
  }
}

filter {
  mutate { replace => { "type" => "nginx_access" } }
  grok {
    match => { "message" => "%{NGINXACCESS}" }
  }
  date {
    match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
  }
  geoip {
    source => "clientip"
  }
}

output {
  elasticsearch {
    host => "localhost"
    protocol => "http"
  }
  stdout { codec => rubydebug }
}
```

File: /opt/logstash/patterns/nginx 

```
NGUSERNAME [a-zA-Z\.\@\-\+_%]+
NGUSER %{NGUSERNAME}
NGINXACCESS %{IPORHOST:clientip} %{NGUSER:ident} %{NGUSER:auth} \[%{HTTPDATE:timestamp}\] "%{WORD:verb} %{URIPATHPARAM:request} HTTP/%{NUMBER:httpversion}" %{NUMBER:response} (?:%{NUMBER:bytes}|-) (?:"(?:%{URI:referrer}|-)"|%{QS:referrer}) %{QS:agent}

```

**Comment by jsvd** [comment]
What version of logstash are you using?

**Comment by djob** [comment]
Latest. Today installed - latest entry in CHANGELOG: 1.5.0.rc2

**Comment by jsvd** [comment]
Can you try with rc4 which has just been released ? https://www.elastic.co/downloads/logstash

**Comment by djob** [comment]
Thank you Joao for your help.

.sincedb_* permissions denied error is now gone. But kibana still shows error: "Unable to fetch mapping. Do you have indices matching pattern".
Could you please guide me, how to debug and isolate problem here?

1. How can i be sure that logstash is successfully receiving logs from inputs
2. How can i be sure that kibana successfully communicate with logstash? (Do kibana has logs somewhere? i can't find it)

**Comment by jsvd** [comment]
@djob there seems to be a thread on that issue in kibana https://github.com/elastic/kibana/issues/1950
can you see if the suggestions help you?
