### ISSUE TITLE
New feature request: Docker files for Power platform (SLES, RHEL, Ubuntu).

### ISSUE THREAD

**Issue by ChristinaGandham** [elastic/logstash#3187]
Hi,

I have written dockerfile for building Logstash from source and to run the test cases. I have built and tested the source code available on git successfully through the dockerfile for PPC64LE architecture. The dockerfile is successfully run on following platforms:
Ubuntu 14.10
SUSE Linux 12.0
RHEL 7.1

Kindly suggest me where can I (which repository) contribute this dockerfile for Logstash.

Regards,
Christina

**Comment by jordansissel** [comment]
Hmm, I don't know where they should go, actually. That's a good question.

**Comment by ChristinaGandham** [comment]
Hi,

I would like to contribute logstash dockerfile for power architecture by adding (_ppc64le) suffix in the file name.
Request you to please comment on the above suggestion for uploading dockerfiles for power architecture.

Regards,
Christina

**Comment by ppf2** [comment]
+1

**Comment by suyograo** [comment]
Please report any docker issues here: https://github.com/elastic/logstash-docker
