### ISSUE TITLE
Refactoring the doc generation process

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3191]
The way that documentation is generated nowadays is nice, but a good refactoring plus some strength up is going to be a very nice to have. 

Things that can be improved are:

* Refactore the code base to remove old code, and make everything a bit more clear.
*  Adding test for the process.
* Add strength checks, the documentation generation should not stop if a plugin can not be parsed. (for example)

**Comment by purbon** [comment]
@ph as you're working on it, I assign this to you :+1:

**Comment by ph** [comment]
I am sorry, I didnt not see this I was just angry not been able to test my documentation changes! :angry:

**Comment by purbon** [comment]
no problem, go for it :+1: it should be refactored!! :+1:

**Comment by suyograo** [comment]
Will fix in #5715
