### ISSUE TITLE
Metadata Field Conditional Issues

### ISSUE THREAD

**Issue by hugespoon** [elastic/logstash#3195]
I have been using Logstash 1.5RC3 and attempting to do a conditional on a field in the metadata. The following is a gist of the output of the rubydebug codec on stdout with metadata => true:

https://gist.github.com/hugespoon/ba7e714a772f20572eca

The output configuration is also included. For additional background, the es_bulk codec is being used on my input source, but it seems to be parsing things out into metadata properly as you can see from the rubydebug output.

**Comment by jordansissel** [comment]
I chatted with @hugespoon on IRC and, after reviewing the gist in the description, believe this to be a bug (or some serious wierdness otherwise).

**Comment by hugespoon** [comment]
I'd like to mention that since RC4 came out today (which I just discovered) I gave it a whirl on that as well. I am seeing the same behavior.

**Comment by ph** [comment]
This is a bit weird, I though we were having a bug in the code generation but the conditionals in this simple example is correctly applied to the event.

```
input {
  stdin { }
}
filter {
  mutate {
    add_field => { "[@metadata][action]" =>  "index" }
  }
}
output {
  if [@metadata][action] != "index" {
          stdout { codec => rubydebug { metadata => true } }
  }
}
```

Are you using other plugins outside of the es_bulk?

**Comment by ph** [comment]
OK, I found the issue!

**Comment by ph** [comment]
The es_bulk codec was assigning the `@metadata` key to a hash and it was overriding our accessor class providing the `[@metadata][action]` syntax.

Thanks @hugespoon for finding this!

**Comment by hugespoon** [comment]
@ph Not a problem, thanks for finding this so quickly!

**Comment by celesteking** [comment]
Still present in logstash-1.5.0.rc4-1.noarch

**Comment by ph** [comment]
@celesteking this fix will be part of GA.
