### ISSUE TITLE
mutate convert "int" causes ungraceful crash

### ISSUE THREAD

**Issue by weaseal** [elastic/logstash#3197]
I added this in a logstash config file (notice "int", not integer, thanks to torrancew on irc for catching my error):

    mutate {
      convert => [ "disk_read", "int" ]
      convert => [ "disk_write", "int" ]
    }

Then when when restarting logstash, it crashes with this error:

    $ cat logstash.stdout 
    Sending logstash logs to /var/log/logstash/logstash.log.
    +---------------------------------------------------------+
    | An unexpected error occurred. This is probably a bug.   |
    | You can find help with this problem in a few places:    |
    |                                                         |
    | * chat: #logstash IRC channel on freenode irc.          |
    |     IRC via the web: http://goo.gl/TI4Ro                |
    | * email: logstash-users@googlegroups.com                |
    | * bug system: https://logstash.jira.com/                |
    |                                                         |
    +---------------------------------------------------------+
    The error reported is: 
      undefined local variable or method `valid_types' for #<LogStash::Filters::Mutate:0x5d9d6359>

Changing "int" to "integer" fixed the issue.

This is on RHEL 7:

    $ sudo yum list installed | grep logstash
    logstash.noarch            1.4.2-1_2c0f5a1     @logstash-1.4

**Comment by suyograo** [comment]
@weaseal can you try this with 1.5.0 RC4? thanks

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-mutate/issues/31. Let's continue the discussion there! :)
