### ISSUE TITLE
File plugin fails with suricata eve.json file

### ISSUE THREAD

**Issue by Mister-X-** [elastic/logstash#3200]
Logstash (1.5RC3) input file plugin crashes with eve.json (from suricata).

My file is pretty big (about 2Gb) and I was told there might be an issue with file size.

I'm not entirely sure if the issue is in logstash (it could be in suricata) and I'd like to debug. Is there any documentation about the content of that sincedb file?

Here is the error:

```
{:timestamp=>"2015-05-01T10:45:14.565000-0600", :message=>"A plugin had an unrecoverable
 error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::File path=>
 [\"/var/log/suricata/eve.json\"], sincedb_path=>\"/var/logstash/suricata.db\",
 type=>\"suricata\", start_position=>\"end\", delimiter=>\"\\n\">\n
  Error: string not matched", :level=>:error}
```

and the configuration:

```
file {
   path => "/var/log/suricata/eve.json"
   sincedb_path => "/var/logstash/suricata.db"
   sincedb_write_interval => 1
   codec => json
   type => "suricata"
}
```

**Comment by jordansissel** [comment]
Two things:

1)  Can you rerun logstash with `--debug` and see if you get a stack trace?

2) Your concern about file size:

> I was told there might be an issue with file size.

There are no issue I am aware of with respect to large files. 2gb isn't very large, in my opinion, and should pose no problems.

**Comment by Mister-X-** [comment]
Unfortunately, I deleted the file a couple days ago. If I can reproduce it, I'll update this ticket.

Could you explain the format of the sincedb file?

**Comment by ph** [comment]
I will be closing this, @Mister-X- Feel free to reopen.
