### ISSUE TITLE
Logstash 1.5 fails to start when updating package from repo and plugins are used

### ISSUE THREAD

**Issue by Mister-X-** [elastic/logstash#3201]
When updating Logstash using the deb package (I'm using the repository but that doesn't matter), any plugin installed under the previous version are 'lost' and they have to be reinstalled manually.

And obviously, since there are missing plugins (used in the config), it doesn't start.

The package could check for installed plugins (either in the directory or in the configuration files) and reinstall them whenever possible. And it would be great if it was making a backup of the plugins installed
with the previous version (in case there are custom plugins or something wrong happens).

**Comment by dougmcclure** [comment]
I see something that sounds similar but with an RC4 RPM install on top of RC2 install.  My custom plugins are placed in lib/logstash/output normally and worked fine in RC2 and RC3.  They are not found by RC4.

**Comment by jordansissel** [comment]
@Mister-X- Is this with 1.5.0 RCs? I wonder why they are being removed. I will try to reproduce.

**Comment by colinsurprenant** [comment]
For the record, @dougmcclure issue is described in #3227 

Also @Mister-X- when you say «any plugin installed» you mean published plugins not included in the package you had to manually install with `bin/plugin install xxx`?

If so, @jordansissel - could it be simply that a new deb package will overwrite `Gemfile` and the `.lock` file (and `bundle/vendor`) effectively removing any added plugins?

**Comment by jordansissel** [comment]
@colinsurprenant ooh yes, those files being overwritten could cause this. hmm. tricky. We could mark them as config files, but I'm not sure what other effects that would have.

Files not present in the deb package won't be changes by an upgrade, but files present (even if modified) will be overwritten unless we mark them as config files in the package. Tricky!

**Comment by Mister-X-** [comment]
@jordansissel, it happened when updating between RC2 and RC3 or between RC3 and RC4, I don't remember exactly. It happened with the plugin translate.

@colinsurprenant, yes.

**Comment by driegel** [comment]
@jordansissel I would like to join this issue. I use the following setup:

logstash-1.5.0 from the yum repo (RPM)
logstash-filter-translate.
I updated 1.5.0 to 1.5.1
After this I had to install the plugin again before I could run Logstash again.

I could imagine one of the following posibilities:
1. RPM checks for installed plugins and installs the latest version after update.
2. you could mark the plugins as config files. However, logstash may require certain plugin versions to work. Somehow the user should be advised to update the plugins as well.
3. Create an individual RPM for each plugin and put them in logstash repo.

Thank you for addressing this issue.

**Comment by guyboertje** [comment]
Closing LS 1.5 went end-of-life on 2016-11-14.
