### ISSUE TITLE
Typo in NAGIOS_HOST_NOTIFICATION

### ISSUE THREAD

**Issue by sodar** [elastic/logstash#3202]
Hi,
When working with Nagios and Logstash (v 1.4.2), I have found a typo in nagios patterns. It does not correctly parse Nagios event type for host notifications. Instead of:

    NAGIOS_HOST_NOTIFICATION %{NAGIOS_TYPE_HOST_NOTIFICATION}

,there should be:

    NAGIOS_HOST_NOTIFICATION %{NAGIOS_TYPE_HOST_NOTIFICATION:nagios_type}

Summarizing - there is missing `nagios_type` capture in `NAGIOS_HOST_NOTIFICATION`.

**Comment by wiibaa** [comment]
Hello, thanks for reporting this. 
However this is a duplicate of https://github.com/logstash-plugins/logstash-patterns-core/issues/21 that is already solved.

If you spot other issues in patterns, can you please open a issue against the specific repository for them: https://github.com/logstash-plugins/logstash-patterns-core/issues
If ok for you , can you please close this ticket. Thanks

**Comment by sodar** [comment]
Ok, thanks. I wasn't aware of patterns repository.
