### ISSUE TITLE
Logstash wont kill after rabbit problem

### ISSUE THREAD

**Issue by iemem15** [elastic/logstash#3203]
Can't kill logstah with "kill" when thereś a problem in rabbitmq
logstash 1.5rc3

Killing logstash (pid 33582) with SIGTERM
Waiting logstash (pid 33582) to die...
Waiting logstash (pid 33582) to die...
Waiting logstash (pid 33582) to die...
Waiting logstash (pid 33582) to die...
Waiting logstash (pid 33582) to die...
logstash stop failed; still running.

**Comment by acchen97** [comment]
@iemem15 can you elaborate what problems you're seeing in RabbitMQ?

**Comment by iemem15** [comment]
Sure.

The problems is when theres is a disconnect to Load Balancer in rabbitmq or
also if it is directly to a single rabbitmq, is there a network connection
it starts creating a lot of connections.

Do you need some kind of logs.

I'v modified this file, Whit this modification , for every disconnect it
creates a new connection
vi
/cilos/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-rabbitmq-0.1.4-java/lib/logstash/inputs/rabbitmq/march_hare.rb
:automatic_recovery => true


Without
:automatic_recovery => true, it creates a connection every timeout for
recconnect. so if its every 10 seconds, every ten seconds creates a new
connection

2015-07-10 18:35 GMT-05:00 Alvin Chen <notifications@github.com>:

> @iemem15 can you elaborate what problems you're seeing in RabbitMQ?
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
Israel Elías Morales

**Comment by balooka** [comment]
Got the same issue described above, using logstash 2.3.4

Issue occurred with logstash shipping to rabbitmq (so rabbitmq output plugin)

There was indeed a global network issue, but the process didn't restore the connections to rabbitmq once the network was restored. Couldn't stop the process cleanly, kill -9 required


Here is a sample of log entry (similar entries showing up over 3000 times, frequency: 1 entry/sec

`{:timestamp=>"2016-09-23T13:26:15.662000+0200", :message=>"MarchHare::ChannelAlreadyClosed", :exception=>MarchHare::ChannelAlreadyClosed, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:976:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:974:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:606:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-3.1.0-java/lib/logstash/outputs/rabbitmq.rb:57:in `publish'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.4/lib/logstash/codecs/json.rb:42:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-3.1.0-java/lib/logstash/outputs/rabbitmq.rb:50:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:129:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}`

**Comment by andrewvc** [comment]
@balooka this should be fixed in the latest logstashes. Have you tried with Logstash 5.x yet?

**Comment by andrewvc** [comment]
I'm going to close this for now, but either open a new issue or ask in this one for a reopen if this is still an issue.
