### ISSUE TITLE
running test in logstash creates a Gemfile.lock file

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3204]
Hi,
 doing:
```
  rake bootstrap
  rake test:install-core
  rake test:core
```

creates a new Gemfile.lock file.

Might be bundler is not properly patch here to use the Gemfile.jruby-1.9.lock file?

**Comment by ph** [comment]
I will try to reproduce this.

**Comment by colinsurprenant** [comment]
on master? 
what is you current Ruby interpreter? `ruby -v`

**Comment by purbon** [comment]
happen to me on master (I use jruby always), why this might be a source of problems?

**Comment by purbon** [comment]
My hunch is more on bundler needing a patch in another location (might be) ...

**Comment by colinsurprenant** [comment]
Just trying to figure the environment combination so we can reproduce. if we cannot reproduce, it's going to be hard to fix. 

I just tried with current master,

    ruby -v
    jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_80-b15 +jit [darwin-x86_64]

and I cannot reproduce.

**Comment by purbon** [comment]
Ok

```
─$ ruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14 +jit [darwin-x86_64
``` 
you will see it after  ``` rake test:core ```

**Comment by colinsurprenant** [comment]
still cannot reproduce. here are my steps:

- clean master with

```
git checkout Gemfile
git checkout Gemfile.jruby-1.9.lock
````

```
rm -rf vendor/bundle .bundle 
```
```
rake bootstrap
```

verify, no `Gemfile.lock`

```
rake test:install-core
```

verify, no `Gemfile.lock`

```
rake test:core
```
verify, no `Gemfile.lock`


do you have the `bundler` gem installed locally?  on my side I have 1.9.6.

```
gem list

*** LOCAL GEMS ***

...
bundler (1.9.6)
...
```

**Comment by purbon** [comment]
Interesting, I repeated the same steps as you, coming from a clean master, doing each command as you.   After ```rake test:core```, still get the ```Gemfile.lock```, here there is some data that might help you setup the same env:

```
╰─$ gem list | grep bundler
bundler (1.9.6)
bundler-unload (1.0.2)
rubygems-bundler (1.4.4)
```

```
╰─$ ruby -v                
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14 +jit [darwin-x86_64]
```
```
╭─purbon@purbon-elastic  ~/work/logstash  ‹master*› 
╰─$ java -version                                                                                                                           1 ↵
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```

is there something else I can do to help you reproduce it ?

**Comment by colinsurprenant** [comment]
@purbon can you gist your Gemfile, Gemfile.jruby-1.9.lock (and Gemfile.lock if present) **before** and **after** `rake test:core` ?

**Comment by purbon** [comment]
@colinsurprenant here you've gist https://gist.github.com/purbon/f5cb4d3fd596109b8ad7, I check and after ```rake test:core``` Gemfile.lock is identical to Gemfile.jruby-1.9.lock

**Comment by colinsurprenant** [comment]
since I can't reproduce, can you add a couple traces in `bootstrap/bundler.rb`; at the top of the module to trace when it get required and in the `patch!` and `setup!` methods to see what gets called when. see if there is a difference between doing `rake test:core` and `bin/rspec`. (for the record, in a debugging chat we discovered that calling `bin/rspec` did not produce the `Gemfile.lock` but we ran out of time testing further).

**Comment by purbon** [comment]
@colinsurprenant I did some debugging and actually the problem for me is that I've also installed bundler in my rvm environment, If I remove bundler the ```Gemfile.lock``` gets not created. As far as I can understand, somehow this bundler (the non vendored one) gets also called when issuing the ```rake test:core``` command.

I guess the only way to patch it is by having something installed in the rvm/system rake that call it, might be there is another way to have a pre call hook in rake, but I'm not aware of it right now.

What do you think, is there an easy way to get rid of this? or should we just keep it as known issue?

**Comment by colinsurprenant** [comment]
@purbon what do you mean by « I've also installed bundler in my rvm environment» ? I also have bundler installed in all my local rubies and that does not seem to affect. 

The "only" difference between launching with `rake test:core` and `bin/rspec` is that with `rake`, the relaunch is done by `rakelib/z_rubycheck.rake` and with `bin/rspec` the relaunch is done in the shell by `bin/logstash.lib.sh`.

In both cases, the `bundler` required should be the one we installed in `vendor/` and we make sure it is in https://github.com/elastic/logstash/blob/master/lib/bootstrap/bundler.rb#L20-L28 ... 

So somehow, in your environment, Bundler is probably already required somewhere. Are you sure the relaunch is done properly by `rakelib/z_rubycheck.rake` ? could you verify this?

**Comment by purbon** [comment]
@colinsurprenant I meant, no bundle installed in rvm gemset, then no ```Gemfile.lock``` generated. I'm actually not that sure that there is a relaunch when se invoke by using ```bin/logstash.lib.sh``` as there is with the rake tasks.

I verified and the relaunch is done properly.

Who could be requiring  bundler in my env other than logstash when doing ``rake .... ```, ideas?

**Comment by colinsurprenant** [comment]
@purbon this is what you have to trace down, since I can't reproduce locally. 

the `bin/rspec` relaunch is done exactly the same way as `bin/logstash` so, yes, there is a relaunch unless you specify `USE_RUBY=1`. If there is no relaunch, we have a problem.

**Comment by purbon** [comment]
@colinsurprenant correctme if I'm wrong, but thanks to https://github.com/elastic/logstash/blob/master/bin/logstash.lib.sh#L115-L134, there is no actuall relaunch, but a selection of the right ruby, right?

**Comment by ph** [comment]
I also had this issue, I am trying to reproduce it.

**Comment by colinsurprenant** [comment]
@purbon I correct you: unless `USE_RUBY=1` is explicitly specified, you always get relaunched with the vendored JRuby in https://github.com/elastic/logstash/blob/master/bin/logstash.lib.sh#L152

**Comment by purbon** [comment]
@colinsurprenant but this is bash -> ruby, right? not a relaunch form ruby -> ruby as with rake isn't? please educate me if I'm wrong.

**Comment by colinsurprenant** [comment]
@purbon if you are unsure about the behaviour, just put `DEBUG=1` in from of which ever command you use between `bin/logstash`, `bin/rspec`, `bin/plugin` to see the exact launch command executed.

```sh
DEBUG=1 bin/logstash version
DEBUG: exec /Users/colin/dev/src/elasticsearch/logstash/vendor/jruby/bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-Xmx500m /Users/colin/dev/src/elasticsearch/logstash/lib/bootstrap/environment.rb logstash/runner.rb version
```

note the `... vendor/jruby/bin/jruby ...` <- relaunch using vendored JRuby.

**Comment by colinsurprenant** [comment]
@purbon in both cases it `exec` using the vendored JRuby, see https://github.com/elastic/logstash/blob/master/rakelib/z_rubycheck.rake#L35

**Comment by ph** [comment]
**Details:**
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26 +jit [darwin-x86_64]

**Local gems:**
https://gist.github.com/ph/4b7684bb92d500dd44d9

**Comment by purbon** [comment]
@ph and you're able to reproduce or not?

**Comment by ph** [comment]
@purbon I had this issue before, but I can't find a reliable way to create the `Gemfile.lock`

**Comment by ph** [comment]
I suspect we have a small issue with the environment (or a MRI/jruby difference).
If you bootstrap the environment with MRI 2.2.0 in my case it wont be able to find "bundler".

```
~/e/logstash git:master ❯❯❯ rake test                                                                                                                                           ⏎ ⬆ ✱
rake aborted!
no such file to load -- bundler
org/jruby/RubyKernel.java:1071:in `require'
/Users/ph/es/logstash/lib/bootstrap/bundler.rb:28:in `setup!'
/Users/ph/es/logstash/rakelib/test.rake:9:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
```

ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
local gems: https://gist.github.com/ph/b2ce7db3b62f78ffa056

**Comment by ph** [comment]
`bin/rspec` works under 2.2.0 but not `rake test`.

**Comment by ph** [comment]
If you look at the $LOAD_PATH before doing `require "bundler"`

**jruby 1.7.19**
```
["/Users/ph/.rbenv/rbenv.d/exec/gem-rehash",
 "/Users/ph/es/logstash/vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib",
 "/Users/ph/es/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.6/lib",
 "/Users/ph/es/logstash/vendor/jruby/lib/ruby/1.9/site_ruby",
 "/Users/ph/es/logstash/vendor/jruby/lib/ruby/shared",
 "/Users/ph/es/logstash/vendor/jruby/lib/ruby/1.9",
 "/Users/ph/es/logstash/lib"]
```

**MRI 2.2.0**

```
  ["/Users/ph/.rbenv/rbenv.d/exec/gem-rehash",
  "/Users/ph/es/logstash/vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib",
  "/Users/ph/es/logstash/vendor/jruby/lib/ruby/1.9/site_ruby",
  "/Users/ph/es/logstash/vendor/jruby/lib/ruby/shared",
  "/Users/ph/es/logstash/vendor/jruby/lib/ruby/1.9",
  "/Users/ph/es/logstash/lib"]
```

Not sure its related, maybe it should be his own ticket.

**Comment by purbon** [comment]
This is actually a good idea, we might encounter two different LOAD_PATH when doing the rake task.

**Comment by ph** [comment]
@purbon can you paste the content of your $LOAD_PATH here when you encounter the `Gemfile.lock` issue.

**Comment by colinsurprenant** [comment]
did we ever get to the bottom of this?

**Comment by suyograo** [comment]
@purbon open this if can reproduce this reliably
