### ISSUE TITLE
logstash regression test 1.5, not testing with dev version

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3205]
Logstash regression test is testing with the released logstash-core gem, and not using the current code version.

Logstash Regression test should test with the existing code, while we should have another job testing with the logstash-core gem.

**Comment by purbon** [comment]
Fixed the regression job for 1.5 to use the code in the project, and added another job to do the test with the logstash-core gem.

@suyograo @colinsurprenant can you review that please ? 

Relevant links:

http://build-eu-00.elastic.co/view/LS%201.5/job/logstash_regression_15/

http://build-eu-00.elastic.co/view/LS%201.5/job/Logstash%20Regression%201.5%20(logstash-core%20gem)/

**Comment by suyograo** [comment]
Reviewed the test on jenkins, LGTM
