### ISSUE TITLE
To have a known issue documentation it would be nice

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3206]
HI,
 having a central place for known issues and workaround that make the system happy again would be a good to have.

This can be a good source of knowledge when a user might encounter some issues.

**Comment by suyograo** [comment]
Makes sense. For starters, I created a known issues label. We can consolidated this to elastic.co/references 

https://github.com/elastic/logstash/labels/known%20issue

**Comment by purbon** [comment]
+1

**Comment by ph** [comment]
Adding this https://github.com/elastic/logstash/issues/1754 concerning thread safety for some plugins.

**Comment by suyograo** [comment]
We currently have a label https://github.com/elastic/logstash/labels/known%20issue. This is good for now
