### ISSUE TITLE
bin/plugin doesn't work if CDPATH env var is set

### ISSUE THREAD

**Issue by timbunce** [elastic/logstash#3207]
The fix is to unset CDPATH env var in bin/plugin
The bin/logstash.lib.sh already unsets CDPATH, but bin/plugin does a cd to _find_ logstash.lib.sh, so it needs to be explicitly unset before that cd.

**Comment by timbunce** [comment]
This is with 1.5.0 RC4

**Comment by colinsurprenant** [comment]
good catch, thanks, will fix.

**Comment by colinsurprenant** [comment]
fixed by #3215  - thanks @timbunce
