### ISSUE TITLE
Unrecognised option '--pluginpath' in 1.5.0 RC4

### ISSUE THREAD

**Issue by wfindley** [elastic/logstash#3208]
perhaps we skipped deprecation and went right to yanking it?  :-) ref #2423

```
bash-4.1$ /opt/logstash/server/bin/logstash agent -f /opt/logstash/server/etc/conf.d --pluginpath /opt/logstash/server/lib -l /opt/logstash/server/log/logstash.log -w 6
Clamp::UsageError: Unrecognised option '--pluginpath'
  signal_usage_error at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:103
         find_option at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:62
       parse_options at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:28
               parse at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:52
                 run at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/runner.rb:76
                call at org/jruby/RubyProc.java:271
                 run at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/runner.rb:92
                call at org/jruby/RubyProc.java:271
          initialize at /opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/task.rb:12
```

**Comment by untergeek** [comment]
`--pluginpath` becomes moot with the new ruby-gem based plugin system.  Not deprecated, but moot.  That's why it has been removed.

For more information about writing plugins, see the "How to write a Logstash [input|output|filter|codec] Plugin" pages at http://www.elastic.co/guide/en/logstash/current/index.html

**Comment by wfindley** [comment]
cool, then I'll try a PR again Lusis's cookbook.

**Comment by rtoma** [comment]
@untergeek 

I do not understand the reasons for removing this feature.

Before I could write a .rb file, put in the correct directory structure, start up a logstash instance, point it the path and my plugin was active.

Now I need to make a gem of it and put it in my logstash installation, making it visible for all logstash instances. 

So for me this deprecation makes local development AND isolation a pain.
