### ISSUE TITLE
Incorrect url in `Using milestone 1 filter plugin` warning

### ISSUE THREAD

**Issue by WoLpH** [elastic/logstash#3212]
When starting Logstash I get messages like these with a broken url:

```
{:timestamp=>"2015-05-10T23:29:11.527000+0200", :message=>"Using milestone 1 filter plugin 'syslog_pri'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones", :level=>:warn}
```

As you can see here: http://logstash.net/docs/1.4.2-modified/plugin-milestones
This results in a 404, would be good to fix :)

Some systeminfo:
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago)
Logstash: logstash 1.4.2-modified

Installed from the Elasticsearch repo and stock as far as I'm aware (only added my own custom pattern):
```
[logstash-1.4]
name=Logstash repository for 1.4.x packages
baseurl=http://packages.elasticsearch.org/logstash/1.4/centos
gpgcheck=1
gpgkey=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
enabled=1
```

**Comment by jordansissel** [comment]
This is a bug in 1.4.2; it'll be fixed in 1.5.0
