### ISSUE TITLE
Add libc6-dev dependency for packages

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3216]
@jsvd found that adding libc6-dev dependency fixed the file-input/file-watch issue https://github.com/elastic/logstash/issues/3127 for Oracle JDK. We should add this a dependency for our deb/rpm packages as a workaround until it is fixed upstream https://github.com/jruby/jruby/issues/2913

**Comment by jordansissel** [comment]
I don't think we want this given the digging from #3217.
