### ISSUE TITLE
@metadata not shown in rubydebug

### ISSUE THREAD

**Issue by celesteking** [elastic/logstash#3218]
Take following output code:
```
          file {
            path => '/var/log/logstash/test.log'
            codec => rubydebug { metadata => true }
            flush_interval => 0
          }
```
Even though `metadata` is `true` , metadata contents is not shown in test.log file. 

logstash-1.5.0.rc4-1.noarch

**Comment by wiibaa** [comment]
The root cause is that **file output does not support codec** as reported in https://github.com/logstash-plugins/logstash-output-file/issues/7 and proposed fix in https://github.com/logstash-plugins/logstash-output-file/pull/9

so it is simply outputting json as default.

**Comment by jordansissel** [comment]
Let's move this discussion here: https://github.com/logstash-plugins/logstash-output-file/issues/7
