### ISSUE TITLE
plugin installation : why local .gem installation differs from "rubygems.org" installation

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#3221]
If I install a plugin directly from rubygems.org, the plugin is installed like logstash provided plugins in `$logstash/vendor/bundle/jruby/1.9/gems`. (for example : `bin/plugin install logstash-filter-environment`)
But if I manually download the gem on rubygems.org, and then install it using "local install" (`bin/plugin install /path/to/logstash-filter-environment.gem`), the plugin is installed in `$logstash/vendor/local_gems/<random_folder>/`

So my questions are :
- why is there a difference ?
- why is there this random intermediate folder ? 

PS: On numerous servers, there is no internet connection (mainly for security reasons), and it's not possible to install a plugin directly from rubygems.org. A manual download elsewhere is firstable necessary.

**Comment by talevy** [comment]
> why is there a difference?
@fbaligand it is just there to keep track of what came from rubygems and what got bundled locally. the path to search for gems includes both. 

> why is there this random intermediate folder?
it is not entirely random, it represents gems installed from local files.
