### ISSUE TITLE
Grok conversion not working in Logstash 1.5.0 rc4 

### ISSUE THREAD

**Issue by nitinBloomz** [elastic/logstash#3223]
Looks like when I do %{NUMBER:latency:int} or %{NUMBER:latency:float} in the grok match, latency is still being stored as string.

**Comment by suyograo** [comment]
@nitinBloomz can we get a example log line with your pattern to reproduce this?

**Comment by nitinBloomz** [comment]
Sample (simplified) log line:
127.0.0.1 27.20ms
grok pattern:
%{IP:client} %{NUMBER:latency:int}
In this latency is not getting converted to an int.

**Comment by jsvd** [comment]
@nitinBloomz I've just tested:

```
% bin/logstash -e "input { generator { count => 1 message => '127.0.0.1 27.20ms' } } filter { grok { match => [ 'message', '%{IP:client} %{NUMBER:latency:int}' ] } } output { stdout { codec => rubydebug } }"
{
       "message" => "127.0.0.1 27.20ms",
      "@version" => "1",
    "@timestamp" => "2015-05-12T16:46:24.077Z",
          "host" => "Joaos-MBP-2.lan",
      "sequence" => 0,
        "client" => "127.0.0.1",
       "latency" => 27
}
```
So it seems to work.

Which operating system are you using?

**Comment by nitinBloomz** [comment]
I am on Ubuntu:
Ubuntu 14.04.2 LTS
Little more context: When viewing it in Kibana I see that latency is getting shown with a 't' (text) in front of it (instead of '#'), when I look at the details of the parsed message. It gets confirmed, when I go and try to create a report for average latency...where latency doesn't get listed, as only numbers are shown in the drop-down there.

**Comment by jsvd** [comment]
That would mean that the index was created such that the field "latency" was of type string. Is it possible that in the first insertions your logstash config didn't have the conversion to float yet?

**Comment by nitinBloomz** [comment]
You are right! That is the issue...I just tried changing the name from latency to time_ms and it is getting parsed as int. Thanks for pointing it out. I now need to figure out if there is an easy way to back-fix the data.

**Comment by jsvd** [comment]
you have to reindex that data, you can do a small app that will use the scroll api to read and reindex into another index.
oh and please close the issue if you consider it solved :)

**Comment by nitinBloomz** [comment]
Thanks again!
