### ISSUE TITLE
Kibana 3 deactivate Query problem

### ISSUE THREAD

**Issue by 6sco** [elastic/logstash#3225]
Hi,

I have a problem with queries in Kibana 3.0.1 - 42ad326.

I have a dashbord with 4 queries:

priority=INFO
priority=WARN
priority=ERROR
priority=DEBUG

I can see my graph (Events over time) and logs (All events) with these queries. 
When i deactivate INFO or DEBUG or ERROR queries, my graph and logs are normaly actualized.
When i deactivate WARN, my graph is normaly actualized but logs with priority WARN are always displayed.

Any solutions ? Is a kibana bug ?

thanks,

Mathieu

**Comment by suyograo** [comment]
Hey a better place to ask this question would be at https://discuss.elastic.co/c/kibana
