### ISSUE TITLE
logstash 1.4.2 - Redis input timeout / missing data

### ISSUE THREAD

**Issue by lmorfitt** [elastic/logstash#3226]
Hello,

I'm experiencing some issues with Logstash 1.4.2 and the redis input loosing data.  I'm wondering if anyone else has seen this issue.

If redis has no data added to the queue at least once an hour I see a "Redis Timeout, restating plugin" error. The data is then all pulled from the list in one go and out of 10 messages, only 2 will arrive in elasticsearch.

To try and track down if there was a timeout condition I added a test message to Redis once an hour. 

1431330002.916917 "rpush" "data" "{########################TEST############################}"
1431330953.161801 "blpop" "data" "0"
1431330953.821474 "blpop" "data" "0"
1431330959.191131 "blpop" "data" "0"
1431330959.867708 "blpop" "data" "0"
1431333602.272291 "rpush" "data" "{########################TEST############################}"
1431334560.613347 "blpop" "data" "0"
1431334560.613396 "blpop" "data" "0"
1431334566.661423 "blpop" "data" "0"
1431334566.668555 "blpop" "data" "0"

Test message added
1431333602 - GMT: Mon, 11 May 2015 08:40:02 GMT

Logstash  restarts redis plugin and picks up message.
1431334560 - GMT: Mon, 11 May 2015 08:56:00 GMT

Logstash server

{:timestamp=>"2015-05-11T07:55:58.829000+0000", :message=>"Failed to get event from Redis", :name=>"default", :exception=>#<Redis::TimeoutError: Connection timed out>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:222:in `io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:201:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:191:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:179:in `call_with_timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:244:in `with_socket_timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:242:in `with_socket_timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:178:in `call_with_timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:1038:in `_bpop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'", "file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'", "file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:1035:in `_bpop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:1064:in `blpop'", "/opt/logstash/lib/logstash/inputs/redis.rb:148:in `list_listener'", "/opt/logstash/lib/logstash/inputs/redis.rb:229:in `listener_loop'", "/opt/logstash/lib/logstash/inputs/redis.rb:245:in `run'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn}
{:timestamp=>"2015-05-11T07:55:58.833000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Redis host=>\"10.49.240.121\", key=>\"data\", data_type=>\"list\", name=>\"default\">\n  Error: Connection timed out", :level=>:error}

I was still seeing lost data so increased the addition of the test message to every 15 mins. This appears to have stopped the issue I was seeing. Not sure on the root cause at this time, any ideas?

thanks
Luke

**Comment by lmorfitt** [comment]
Hello,

The architecture is as follows

Logstash and redis installed on a remote box, at the other end of a VPN. Central logstash instance pulling data from the redis instance.

The below error is caused by our Firewall. What is happening is the firewall is seeing a idle TCP connection and killing it, thus causing Logstash to restart the redis input. 

{:timestamp=>"2015-05-11T07:55:58.829000+0000", :message=>"Failed to get event from Redis", :name=>"default", :exception=>#, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-

This does not explain why when logstash reconnects to redis it pulls all 10 messages in the queue and only places 2 of them into elastic search.

I will setup a test case and provide as much detail as possible, with the simplest setup possible in the near future.

thanks
Luke

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-redis/issues/11. Let's continue the discussion there! :)
