### ISSUE TITLE
Docs Error>The Life Of An Event>Consequences and Expectations

### ISSUE THREAD

**Issue by viruscmd** [elastic/logstash#3228]
Hello all,

I could be wrong but I am assuming that this line is suppose to have only one grow.
"Unlimited queues grow grow unbounded "

Regards,
Austin

**Comment by untergeek** [comment]
@viruscmd thanks for catching the error.  If you're willing, could you submit a PR with that doc change?

**Comment by viruscmd** [comment]
I would love to what is a PR?

**Comment by suyograo** [comment]
@viruscmd PR = Pull Request, You can click on the pencil icon on the docs and it will initiate the pull request for you to fix the error
