### ISSUE TITLE
rspec do not exist for logstash-1.5.0.rc4

### ISSUE THREAD

**Issue by zhenghu** [elastic/logstash#3229]
how to run tests with rspec in logstash-1.5.0.rc4 ?

**Comment by colinsurprenant** [comment]
Normally just `bin/rspec` should do.

Just tried and I confirm there's a problem with `rake`
```
Bundler::GemNotFound: Could not find rake-10.4.2 in any of the sources
      materialize at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/spec_set.rb:92
             map! at org/jruby/RubyArray.java:2444
      materialize at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/spec_set.rb:85
            specs at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/definition.rb:132
        specs_for at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/definition.rb:177
  requested_specs at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/definition.rb:166
  requested_specs at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/environment.rb:18
            setup at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/runtime.rb:13
            setup at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler.rb:122
           setup! at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/lib/bootstrap/bundler.rb:38
           (root) at /Users/colin/dev/src/elasticsearch/logstash/tmp/package/logstash-1.5.0.snapshot1/lib/bootstrap/rspec.rb:2
```

Will review this before GA. Thanks for reporting this.

**Comment by colinsurprenant** [comment]
@zhenghu in the meantime, you can run tests/specs from a cloned repo:
```
git clone https://github.com/elastic/logstash
# checkout a specific branch or tag?
rake bootstrap
rake test:install-core
rake test:core # or just bin/rspec
```

**Comment by suyograo** [comment]
@zhenghu any particular reason you want to run tests from a release package?

**Comment by zhenghu** [comment]
Thanks for all responses. 
In fact, I have a TU which run my tests with `logstash (logstash.bat) rspec test.rb`. 
With logstash-1.4.2, it works well. It works for both linux and windows.

But today when I try with logstash-1.5.0.rc4, it doesn't work any more.  
And in windows, there is no .bat to run test.

I was wondering that the `logstash.bat rspec` will not be support in release version of logstash-1.5.0 ?

If not, there is any way to run the test in windows ?

**Comment by colinsurprenant** [comment]
@zhenghu a *TU* ?

we decided to remove `bin/logstash rspec` in 1.5 and you are right, we are missing a Windows version of `bin/rspec`. 

Could you explain the context of running that `test.rb` from a release package? I'd like to understand how/why this is required for you and maybe offer alternative?

**Comment by zhenghu** [comment]
@colinsurprenant 

Sorry for TU, it should be UT (Unit Test).

I run the test from a release package for testing the filters in a logstash conf file.

I need run it in windows because we edit the conf file in windows, and we lanuch all unit test with maven(so far, we start logstash.bat rspec in a java process, and the unit test check the rspec report file to verify if there is an issue for the logstash conf).

So if there is no .bat for rspec, our unit test will not work.

**Comment by colinsurprenant** [comment]
@zhenghu I see. So, as of rc4, you don't have much options from Windows because we don't have a `bin/rspec.bat`. 

In linux you could do:
```
bin/plugin install --development
bin/rspec test.rb
```
can you try it in Linux? Then we can see about adding a `bin/rspec.bat`

**Comment by colinsurprenant** [comment]
@zhenghu can you try adding this `bin/rspec.bat` in your setup and testing it?
```
@echo off

SETLOCAL

set SCRIPT_DIR=%~dp0
CALL %SCRIPT_DIR%\setup.bat

:EXEC
if "%VENDORED_JRUBY%" == "" (
  %RUBYCMD% "%LS_HOME%\lib\bootstrap\rspec.rb" %*
) else (
  %JRUBY_BIN% %jruby_opts% "%LS_HOME%\lib\bootstrap\rspec.rb" %*
)

ENDLOCAL
```

so you'd need to do once in your package:
```
bin/plugin install --development
```
and to run your tests (using the `bin/rspec.bat` I copied ^^)
```
bin/rspec test.rb
```

Let me know if that works for you?

**Comment by colinsurprenant** [comment]
@zhenghu I just tested that in a Windows 8.1 VM and it works.

**Comment by colinsurprenant** [comment]
@zhenghu let me know if this solves your issue and if we can close this

**Comment by zhenghu** [comment]
@colinsurprenant Yes, it works. Thanks again. Sorry for response it late.

**Comment by colinsurprenant** [comment]
:thumbsup:
