### ISSUE TITLE
%{DATA} bug?

### ISSUE THREAD

**Issue by sitkawoof** [elastic/logstash#3230]
I am parsing a fairly complicated log file.  I have a parse pattern that works perfectly in grokdebug on sample log records from the file.  When I try to parse these same records in logstash I get a grokfailure.  The fail appears to occur when I use %{DATA} to match a bunch of XML I don't want to be in the JSON doc that goes to elasticsearch.   

I am running on Logstash 1.5.0-rc3.  Filter and sample log records that fails is in GIST.

**Comment by suyograo** [comment]
@sitkawoof can you please take this to https://discuss.elastic.co/c/logstash? GitHub is used mainly for issues.

**Comment by sitkawoof** [comment]
Sorry, I was directed here.
