### ISSUE TITLE
allow outputting resulting config file when merging multiple ones 

### ISSUE THREAD

**Issue by nellicus** [elastic/logstash#3243]
```
./bin/logstash --show-config -f /my_config_files_dir 
//don't start just show resulting config
input{
//all merged inputs
}
filter{
//all merged filters
}
output{
//all merged outputs
}
```

**Comment by jsvd** [comment]
We already have the -t flag to check the validity of the config file, I think it would be interesting to implement your suggestion as a verbose flag for -t, such as:

```
% bin/logstash -v -t -f config
input {
  stdin { codec => json }
}
output {
  elasticsearch { }
}

 {:level=>:info}
Using version 0.1.x input plugin 'stdin'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x codec plugin 'json'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x output plugin 'elasticsearch'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x codec plugin 'plain'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Configuration OK
% bin/logstash -t -f config
Configuration OK
```

**Comment by nellicus** [comment]
ideally show which file is contributing to each part of the merged config

**Comment by gmoskovicz** [comment]
+1 on this!

**Comment by jordansissel** [comment]
I think this should be pretty simple to do. I'll see about making it happen in the next release.

Can you confirm  what kind of output you want? Something like a comment-annotated form of what files are providing what sections of the config file?

**Comment by colinsurprenant** [comment]
+1 on a `-v` verbose option in conjunction of `-t`
+1 on comment annotated file reference for section

**Comment by jordansissel** [comment]
ooooh I like that, adding --verbose to --config-test would make it output an annotated, concatenated config file?

**Comment by jordansissel** [comment]
@nellicus @gmoskovicz Can you comment and let us know if that interface (`--config-test --verbose`) works for you as a way to view the full config (w/ annotation)?

**Comment by robin13** [comment]
+1

**Comment by gmoskovicz** [comment]
@jordansissel works  for me, but also, perhaps i was thinking something more like `--print-config`, but that could only be an alias for the --config-test --verbose right?

**Comment by nellicus** [comment]
@jordansissel I'm with @colinsurprenant 

+1 on a -v verbose option in conjunction of -t
+1 on comment annotated file reference for section

**Comment by untergeek** [comment]
This is resolved.  In 2.1, combining `--debug` with `--configtest` will result in output like this: https://gist.github.com/untergeek/e31bedbe5b34f21d1cba

**Comment by gmoskovicz** [comment]
This looks great!!

**Comment by jakommo** [comment]
nice :+1:
