### ISSUE TITLE
Java exception when trying to run plugin commands

### ISSUE THREAD

**Issue by allenmchan** [elastic/logstash#3247]
Version: logstash 1.5 GA
Issue: When trying to do plugin list, i get Java exception. 

    [achan@lsc011.scl bin]$ pwd
    /opt/logstash/bin
    [achan@lsc011.scl bin]$ ./plugin list
    Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9994;    nested exception is:
	java.net.BindException: Address already in use
    [achan@lsc011.scl bin]$ sudo /etc/init.d/logstash restart
    Killing logstash (pid 27913) with SIGTERM 
    Waiting logstash (pid 27913) to die...
    Waiting logstash (pid 27913) to die...
    logstash stopped.
    logstash started.
    [achan@lsc011.scl bin]$ ./plugin list 
    Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9994; nested exception is:
	java.net.BindException: Address already in use
    [achan@lsc011.scl bin]$ ./plugin list
    Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9994; nested exception is:
	java.net.BindException: Address already in use
    [achan@lsc011.scl bin]$ sudo !!
    sudo ./plugin list
    Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9994; nested exception is:
	java.net.BindException: Address already in use

I do have this configuration in logstash.lib.sh JAVA_OPTS to enable JMX monitoring

    # For JMX Monitoring
    JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote"
    JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.port=9994"
    JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
    JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.ssl=false"

Also there is nothing else running on that port
   
    [achan@lsc011.scl bin]$ netstat -an  | grep 9994
    tcp        0      0 :::9994                     :::*                        LISTEN

**Comment by suyograo** [comment]
@allenmchan can you remove those settings and check if it works? We can then isolate it to those java options

**Comment by suyograo** [comment]
I am suspecting it is trying to initiate JMX twice

**Comment by allenmchan** [comment]
i commented out those JMX monitoring lines from logstash.lib.sh and the plugin command works

    [achan@lsc011.scl bin]$ ./plugin list
    logstash-codec-collectd 
    logstash-codec-dots
    logstash-codec-edn
    logstash-codec-edn_lines
    logstash-codec-es_bulk

**Comment by suyograo** [comment]
@allenmchan we actually introduced a new way to set extra java options using `LS_JAVA_OPTS` environment variable. Can you try adding JMX config using this method? Documented here: https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html#_environment_variables

Let me know how it goes

**Comment by allenmchan** [comment]
confirmed that it works. 
In case anyone in the future needs this, i edited /etc/init.d/logstash

[achan@lsc011.scl ~]$ cat /etc/init.d/logstash | grep -i ls_java_opts
  LS_JAVA_OPTS="${LS_JAVA_OPTS} -Djava.io.tmpdir=${LS_HOME} -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9994 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
