### ISSUE TITLE
Update documentation to new 1.5 release

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3248]
We should revisit the documentation to be sure it's all naming 1.5 as the current GA, for example https://www.elastic.co/guide/en/logstash/current/package-repositories.html is still referencing to 1.4.x repos.

**Comment by technosf** [comment]
Please check for voracity too. For example, on the getting started page there is this cmdline example:

  `bin/plugin -install lmenezes/elasticsearch-kopf`

Which results in an error:

    ERROR: Unrecognised option '-i'

    See: 'bin/plugin --help

Thanks!

**Comment by untergeek** [comment]
Clearly that is in the [Elasticsearch Plugins (an aside)](https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html#_elasticsearch_plugins_an_aside) section.  Kopf is an Elasticsearch plugin, rather than a Logstash one.

We could be more clear about that, but it is mentioned as an Elasticsearch plugin, rather than a Logstash one.

**Comment by technosf** [comment]
Yup - but the flag is wrong ;)

it's _bin/plugin install foobar_ 

No minus before _install_

**Comment by untergeek** [comment]
Um, I know not what you mean:

```
bin/plugin -install lmenezes/elasticsearch-kopf
-> Installing lmenezes/elasticsearch-kopf...
Trying https://github.com/lmenezes/elasticsearch-kopf/archive/master.zip...
Downloading .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Installed lmenezes/elasticsearch-kopf into /Users/buh/elasticsearch-1.5.2/plugins/kopf
Identified as a _site plugin, moving to _site structure ...
```

It works just fine for me.

**Comment by technosf** [comment]
Ah... You're right. My appologies - Although it is in the _logstash_ doc, it is noted as being for ES as _an aside_. Interesting that ED and LS have the same command but one is _-install_ and one is _install_
