### ISSUE TITLE
Permission denied - /opt/logstash/.bundle

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#3249]
Install the `logstash-1.5.0-1.noarch.rpm` package using a user that is not the `logstash` user.  Then try to run `./logstash version` , you will get:

```
Errno::EACCES: Permission denied - /opt/logstash/.bundle
         mkdir at org/jruby/RubyDir.java:452
      fu_mkdir at /opt/logstash/vendor/jruby/lib/ruby/1.9/fileutils.rb:247
       mkdir_p at /opt/logstash/vendor/jruby/lib/ruby/1.9/fileutils.rb:221
  reverse_each at org/jruby/RubyArray.java:1693
       mkdir_p at /opt/logstash/vendor/jruby/lib/ruby/1.9/fileutils.rb:219
          each at org/jruby/RubyArray.java:1613
       mkdir_p at /opt/logstash/vendor/jruby/lib/ruby/1.9/fileutils.rb:205
       set_key at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.8/lib/bundler/settings.rb:158
           []= at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.8/lib/bundler/settings.rb:26
        setup! at /opt/logstash/lib/bootstrap/bundler.rb:31
        (root) at /opt/logstash/lib/bootstrap/environment.rb:46
```

If it is run using `sudo -u logstash ./logstash version`, it works.  Not sure if this is the right way to run it.  Documentation is light in this area.

**Comment by purbon** [comment]
I confirm this happen also for the deb package.  Some workarounds for now around this issue are:

* Start logstash by using the ```/etc/initd.d/logstash``` script
* Start logstash by using the command ```sudo -u logstash ```

**Comment by ph** [comment]
The only way to fix this reliably is to not create any `.bundle/config` when we start logstash if we want to allow people to run it with different users, this would make logstash stateless.

There is a PR to prevent bundler from creating the file here: https://github.com/elastic/logstash/pull/2701

**Comment by gtournie** [comment]
To fix it without having to run it every time with `sudo` or with the `/etc/init.d` script , I did:
```
sudo chown -R logstash:$USER /opt/logstash
/opt/logstash/bin/logstash version
sudo chown -R logstash:logstash /opt/logstash
```
It will create the `.bundle` and next logstash calls won't care about the `.bundle` permissions

**Comment by dpichard** [comment]
My observation as a user, having used one of the above workarounds the first time I ran `logstash`, is that the `/opt/logstash/.bundle/config` file seems to need to be generated once, and is then static.  

If this is true, and it's not different on everyone's machines, could an alternative to #2701 be to either:
- package a static `/opt/logstash/.bundle/config` file inside the RPM/DEB packages, or
- have the RPM/DEB post-install stage run `/opt/logstash/bin/logstash version` once as root, to generate the file at install time?

**Comment by wajiii** [comment]
I have an interesting variant of this issue: we are trying to run LogStash from a shared read-only file system(to conserve disk space across a large fleet of virtual machines). My initial solution was to create /opt/logstash/.bundle as a symlink to a writable local directory. This worked fine, BUT... the software we are using for distribution works on the principle of cloning the "reference system" via zip/unzip of the relevant contents and therefore cannot preserve or recreate such symbolic links. So at this point, I think I'm stuck unless there is another way to tell LS,JRuby,or Bundler to use a different .bundle location at startup...

**Comment by wajiii** [comment]
Never one to give up easily, I tried overriding the default Bundler directory by defining BUNDLE_DIR in /etc/sysconfig/logstash (by adding BUNDLE_DIR=/var/lib/logstash/.bundle to the end). Et voila, success! Unless this is expected to end catastrophically, may I suggest documenting this workaround somewhere?

**Comment by ph** [comment]
@wajiii we have merged a fix in master to stop creating a `bundler/.config` everything we start logstash this should fix the issue on read-only fs. This should be release short in a official release.
