### ISSUE TITLE
 Couldn't find any input plugin named 'sqlite'. Are you sure this is correct? Trying to load the sqlite input plugin resulted in this error: no such file to load -- logstash/inputs/sqlite

### ISSUE THREAD

**Issue by zeqi** [elastic/logstash#3250]
Couldn't find any input plugin named 'sqlite'. Are you sure this is correct? Trying to load the sqlite input plugin resulted in this error: no such file to load -- logstash/inputs/sqlite

input {
  sqlite {
    path => "/Users/zeqi/soft/db/example.db"
    type => "weblogs"
  }
}
output {
  # redis { host => "127.0.0.1" data_type => "list" key => "logstash-file-sqlite" }
  elasticsearch { host => localhost }
  stdout { codec => rubydebug }
}

**Comment by jsvd** [comment]
the sqlite plugin isn't [included by default](https://github.com/elastic/logstash/blob/master/rakelib/default_plugins.rb) in packages, you can install it by doing `bin/plugin install logstash-input-sqlite`

**Comment by purbon** [comment]
@zeqi doing ```bin/plugin list``` will list your installed plugins. 

I will proceed to close this issue as you've all the info necessary to install the plugin, if you encounter issues when installing the plugin, let us know throw a new issue.

Thanks

**Comment by zeqi** [comment]
Thank you very much！

zeqi-mac:logstash-1.4.2 zeqi$ bin/plugin list
Can only install contrib at this time... Exiting.
zeqi-mac:logstash-1.4.2 zeqi$ bin/plugin install logstash-input-sqlite
Can only install contrib at this time... Exiting.
zeqi-mac:logstash-1.4.2 zeqi$

Why is there such a prompt？－－－》Can only install contrib at this time... Exiting.

**Comment by purbon** [comment]
Even @jsvd or me refer to using 1.5 GA, if possible we encourage you to use it :-) ... then the plugin manager works as we told you.

**Comment by zeqi** [comment]
oh I have a try.

**Comment by purbon** [comment]
let us know everything work, so we can close the issue.
