### ISSUE TITLE
mutate must be in its own code block

### ISSUE THREAD

**Issue by spuder** [elastic/logstash#3255]
If you attempt to combine multiple mutations inside of one mutate block, then you get unexpected results. 

Broken config
```
input {stdin {codec => json}}
filter {
  mutate {
    # Change FOO to lowercase
    rename => [ "FOO", "foo" ]
    # Duplicate foo and name it bar
    add_field => {
      "bar" => "%{foo}"
    }
    # Remove all digits from foo except [0-9]
    gsub    => [ "foo", "\D", "" ]
    # Convert foo field to digit
    convert => [ "foo", "integer"]
  }
}
output { stdout { codec => rubydebug} }
```

Input

    {"FOO":"ABC123"}

Output
```
{
      "@version" => "1",
    "@timestamp" => "2015-05-15T21:53:57.090Z",
          "host" => "sowens-MBP",
           "foo" => 0,
           "bar" => "0"
}
```

Notice how both foo and bar are 0's? That is bad

If you expand the config out to use multiple mutates, it works properly. 

```
input {stdin {codec => json}}
filter {
  mutate {
    rename => [ "FOO", "foo" ]
  }
  mutate {
    add_field => {
      "bar" => "%{foo}"
    }
  }
  mutate {
    gsub    => [ "foo", "\D", "" ]
  }
  mutate {
    convert => [ "foo", "integer"]
  }
}
output { stdout { codec => rubydebug} }

```

```
{
      "@version" => "1",
    "@timestamp" => "2015-05-15T21:53:24.381Z",
          "host" => "sowens-MBP",
           "foo" => 123,
           "bar" => "ABC123"
}
```

This is either a bug in the mutate, or a bug in documentation. Nowhere that I can find does the documentation mention that combining mutates together is bad.

**Comment by purbon** [comment]
This does not looks like the expected behaviour to me, so makes sense to fix this.

**Comment by untergeek** [comment]
The issue belongs in http://github.com/logstash-plugins/logstash-filter-mutate 



—Aaron

**Comment by jordansissel** [comment]
@purbon the expectation is that the execution order of settings in a single mutate should follow the order in the config file, and it does not. At present, no other filter has so much behavior, and to be honest, I feel like the `mutate` filter should be split into multiple filter plugins anyway.

**Comment by jordansissel** [comment]
@untergeek agreed; we can move it there.

**Comment by purbon** [comment]
@jordansissel makes sense!

@untergeek @jordansissel I agree this issue should be moved to the very same logstash-filter-mutate plugin project.

**Comment by colinsurprenant** [comment]
wonder how hard it would be to surface the unordered mutate operations from the `config` class methods into an ordered list? If we could do that we'd preserve configuration backward compatibility.

**Comment by spuder** [comment]
Thanks, Moved to: 
https://github.com/logstash-plugins/logstash-filter-mutate
