### ISSUE TITLE
logstash 1.5.0 crash when using output plugin websocket 

### ISSUE THREAD

**Issue by mbomassimo** [elastic/logstash#3258]
Starting logstash (version 1.5.0) with the websocket output plugin configurated 
```
       websocket {
         codec => json {}
         port => 7777
       }
```
logstash crash with the following error:
```
LoadError: no such file to load -- sinatra/base
        require at org/jruby/RubyKernel.java:1071
        require at ........./log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/pol
yglot.rb:65
         (root) at ......../log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-websoc
ket-0.1.4/lib/logstash/outputs/websocket/app.rb:4
        require at org/jruby/RubyKernel.java:1071
        require at ......../log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/pol
yglot.rb:65
         (root) at ......../log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-websoc
ket-0.1.4/lib/logstash/outputs/websocket.rb:1
           each at org/jruby/RubyArray.java:1613
       register at ....../log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-websoc
ket-0.1.4/lib/logstash/outputs/websocket.rb:24
  start_outputs at ......./log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-ja
va/lib/logstash/pipeline.rb:164
            run at......./log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-ja
va/lib/logstash/pipeline.rb:82
        execute at ......../log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-ja
va/lib/logstash/agent.rb:142
           call at org/jruby/RubyProc.java:271
            run at ......./log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-ja
va/lib/logstash/runner.rb:87
           call at org/jruby/RubyProc.java:271
            run at ......./log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-ja
va/lib/logstash/runner.rb:92
←[33mUDP listener died {:exception=>#<SocketError: recvfrom: name or service not known>, :backtrace=>["......./log_
analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.4/lib/logstash/inputs/udp.rb:79:in `udp_listene
r'", "....../log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.4/lib/logsta
sh/inputs/udp.rb:49:in `run'", "......./log_analisys/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-
core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'", "........./log_analisys/logstash/logstash-1.5.0/vendo
r/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input'"], :level=>:warn}←[0m
```

This error is present either in the windows version (windows7 64 bit) either in the linux version (centos 6).
There is also an error on UDP input plugin but i think it is already signaled

**Comment by purbon** [comment]
@mbomassimo Hi, in took a look at the plugin and this is because of missing dependencies on the plugin. I think we can safely move this issue to https://github.com/logstash-plugins/logstash-output-websocket as it belogs to there.

If you're upto actually the fix is not complicated, you just need to add the missing dependencies in https://github.com/logstash-plugins/logstash-output-websocket/blob/master/logstash-output-websocket.gemspec. Let me know if you want to take the chance fix it. Happy to guide you in the process if you're up to it :+1:

**Comment by mbomassimo** [comment]
I added this line in the file
  s.add_runtime_dependency 'sinatra'
But this doesn't work.
Ok guide me

**Comment by purbon** [comment]
Hi,
  you should fix the plugin, by updating the dependencies in it, aka https://github.com/logstash-plugins/logstash-output-websocket (making your own fork), and creating a new version of the plugin.

The only two missing dependencies are sinatra and logstash-codec-plan.

You can get more info on how this plugins works from https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html

Let me know if you have more doubts.

**Comment by mbomassimo** [comment]
Thank you purbon but I don't have some programm installed on my PC in order to complete the plugin generation.
I never used jruby I need more time in order to prepare the environment.
In any case thanks a lot

**Comment by purbon** [comment]
ok, I had to try, no problem. I will make this fix soon in the plugin. Closing this issue as it belongs to the plugin websocket.

**Comment by purbon** [comment]
When this https://github.com/logstash-plugins/logstash-output-websocket/pull/3 gets merged and the new plugin released, this is going to be fix. Thanks for reporting.

**Comment by purbon** [comment]
A new version of the plugin has been released, if you do ```bin/plugin update ....``` you will get the new version that has no dependency problems. Let us know if you find more issues. Thanks for your report.
