### ISSUE TITLE
no spec_helper found for logstash-1.5.0

### ISSUE THREAD

**Issue by zhenghu** [elastic/logstash#3263]
I have an issue with the new release logstash-1.5.0 on testing.

I run my logstash unit test with the following steps : 
1. download all development dependencies : 
`bin/plugin install --development`

2. run test with : 
`bin/rspec test.rb`

Here is my test.rb : 
 ```
 # encoding: utf-8
require "spec_helper"

describe "Logstash filters test suite" do

  describe "Logstash filters for linkylog_type inputs" do
    #Charger le conf file
    config File.new("/tmp/logstash.conf").read

    #Using the type method, you do not have to repeat it in each sample
    type "test_type"

    #Test Sample
    #test case 1
sample({"type" => "test",
        "message" => "test message"}) do
 #Test
 insist { subject["message"] } == "message"
end

  end
end
 ```

Here is the error message : 
 ```
 LoadError: no such file to load -- spec_helper
          require at org/jruby/RubyKernel.java:1071
           (root) at /home/ZH16093N/test.rb:2
             load at org/jruby/RubyKernel.java:1087
           (root) at /home/ZH16093N/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:1
             each at org/jruby/RubyArray.java:1613
  load_spec_files at /home/ZH16093N/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896
  load_spec_files at /home/ZH16093N/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896
              run at /home/ZH16093N/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22
           (root) at /home/ZH16093N/logstash-1.5.0/lib/bootstrap/rspec.rb:10

 ```

I found the privious issue (https://github.com/elastic/logstash/issues/2743) which indicate that to run the 1.4.2 unit test template, just need to : 
1. replace require `test_utils` with require `spec_helper`
2. remove extend `LogStash::RSpec`

In addition, I try to install spec_helper with : 
`bin/plugin install spec_helper`. 
It does not work, here is the error message : 
 ```
 Validating spec_helper
Plugin spec_helper does not exist
ERROR: Installation aborted, verification failed for spec_helper

 ```

**Comment by purbon** [comment]
Hi,
  I think the most probably source of this error is the need to fins the spec_helper in https://github.com/elastic/logstash-devutils/blob/master/lib/logstash/devutils/rspec/spec_helper.rb (logstash spec_helper). you will need to have something like ```require 'logstash/devutils/rspec/spec_helper' ``` .  This file is located in the logstash-devutils.

/cheers

**Comment by zhenghu** [comment]
@purbon 
Thanks.

**Comment by purbon** [comment]
works? can I close this issue?

**Comment by zhenghu** [comment]
@purbon 
Yes, you can close it.
