### ISSUE TITLE
Newline interpretation in logstash is not as you can expect

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3265]
As noticed in #3238 newline interpretation by the config compiler might be not as you expected. If we take as an example

```
abonuccelli@w530 /opt/elk/TEST/logstash-1.5.0-rc3 $ ./bin/logstash -e 'input{stdin{}}filter{mutate{gsub=>["message","\\n","newline"]}}output{stdout{codec=>rubydebug}}'
Logstash startup completed
\n
{
       "message" => "newline",
      "@version" => "1",
    "@timestamp" => "2015-05-13T10:09:34.542Z",
          "host" => "w530"
}
```

what you might expect is that you replace a newline character with newline, however what really happen is that we transform the two characters `\\n` with newline because. Although you could expect that you are really replacing a newline, this happen like this because characters are not interpreted to newline, but deal as character.

If you really want to replace the newline character you need to create a config with an space.

Related with #3238 #3239 #1645

**Comment by wiibaa** [comment]
@purbon related to #1645 too?

**Comment by purbon** [comment]
@wiibaa makes complete sense, related to #1645

**Comment by suyograo** [comment]
Closing since covered in #1645
