### ISSUE TITLE
Formal / Informal specs about parts of logstash expected behaviour.

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3266]
In order to validate properly the different parts of logstash we need a documentation of what is expected out of it. This ticket is fill in order to start discussing possible ways to do this documentation/specs.

A good way to start documenting is the configuration grammar, so we can add test on it. Next steps would be to document the pipeline, stc.

**Comment by suyograo** [comment]
Not necessary at this point. We can revisit this later

**Comment by purbon** [comment]
Sorry to disagree here, but this will certainly benefit our testing, having a formal definition of the config grammar, or how we expect the pipeline to behave, would help and this is basically what I also started helping out for #5070 #5020 and #5139 , at less the formalization of configuration and event behaviour should be necessary to avoid confusion.
