### ISSUE TITLE
Urldecode prefix fields support

### ISSUE THREAD

**Issue by mcanes** [elastic/logstash#3273]
It can be useful to decode parameters from urls.
Right now, splitting url parameters it's extremely easy using the KV filter, but not decode the parameters values.

Let's put an example using: foo.com/bar?param1=value1&...&paramN=valueN

```
filters {
  ... # Split url using grok URI pattern or similar

   kv {
     source => "uriparams"
     field_split => "&?"
     prefix => "params_"
   }
 
   urldecode {
     field_prefix => "params_"
   }
}
```

With this we can url decode all params using one filter and supporting url params dynamically.

**Comment by purbon** [comment]
Hi @mcanes, thanks for your feedback. This looks to me like a feature request for the kv filter and/or the urlencode one, right? It would be great to move this issue there.

links:

https://github.com/logstash-plugins/logstash-filter-kv

https://github.com/logstash-plugins/logstash-filter-urldecode

Feel free to move it there and close this issue.

**Comment by mcanes** [comment]
Thank you @purbon.

New issue: https://github.com/logstash-plugins/logstash-filter-urldecode/issues/2

kv filter prefix support is already implemented.
