### ISSUE TITLE
New plugin logstash-output-webhdfs

### ISSUE THREAD

**Issue by dstore-dbap** [elastic/logstash#3274]
I created an output to write event data to hdfs via webhdfs, [logstash-output-webhdfs](https://github.com/dstore-dbap/logstash-output-webhdfs). 
It seemed to be useful to others, so if it meets the requirements concerning code quality I'd like it to be added to the logstash-plugins. Writing tests without a webhdfs node accessible for running the tests against seems a bit problematic. Thus, currently the test will only make sure that omitting required parameters will throw an error and that the default values are what they are supposed to be ;)

**Comment by untergeek** [comment]
We're working on ways to use the Docker api for Ruby to allow you to spin up a container with the actual service for integration testing.  Would you be able to write tests as though you *did* have a node?  We could help with writing the Docker api portion as it's a work in progress, but if you had functional tests to begin with, that would be terrific!

**Comment by dstore-dbap** [comment]
Ok, if you use docker for testing, I will try to whip up an image with an hdfs node and adjust the tests. Might take a couple of days, depending on spare time ;)

**Comment by purbon** [comment]
Hi, this is a nice addition to the logstash plugins, thanks for sharing. When talking about testing, here I see a couple of scenarios, the first one is to write unit test for the plugin behaviour (you can use mocking and stubs as defined by rspec, a bit of docs at https://github.com/elastic/logstash/issues/3142 ).

Then there are the integration test, for this I totally agree you should fire up a docker/something else and run the test versus this hdfs component. 

I see us having both kind of tests happening as both cover different areas of behaviour.

**Comment by dstore-dbap** [comment]
Thanks for the warm words, purbon...
Yes, I was tinkering with the idea of putting together a mocked up TcpServer, receiving the webhdfs calls and checking these. But after a coffee, that seemed a bit over the top ;)

**Comment by purbon** [comment]
Hi,
  I was more going on the direction of having:

1.- Short functions that check what is expected to happen as unit test. In order to do that you should mock the calls to the external service.
2.- Then you can have integration test that will check what happen when running with a real system.

Both test are complementary.

**Comment by dstore-dbap** [comment]
Added basic integration tests which assume a webhdfs service is reachable on localhost, port 50070.

**Comment by purbon** [comment]
@dstore-dbap Are you willing to host your plugin at https://github.com/logstash-plugins ? it would be great to have it there. What do you say?

**Comment by dstore-dbap** [comment]
@purbon  Yes, sure ;) If I understand the contrib docs correctly, I would need to transfer the repository. Is this correct? And how would this be achieved?

**Comment by purbon** [comment]
@dstore-dbap What we can do is:

* We create a new repo in the logstash-plugins organization.
* You can do a PR to that repo.

then after it's reviewed, we can merge it so the code is there. We encourage all the modifications to be made always by PR, including reviews so the code quality increases. 

So is not a simple repo transfer as in the way github does it.

Makes sense to you? Should I go ahead and add the repo?

**Comment by dstore-dbap** [comment]
Yes please, go ahead ;) I will do a pr when its up.

**Comment by purbon** [comment]
@dstore-dbap enjoy! https://github.com/logstash-plugins/logstash-output-webhdfs looking forward to your pr.

**Comment by dstore-dbap** [comment]
@purbon Enjoyed it quite a lot ;) Pull request done...

**Comment by purbon** [comment]
Thanks @dstore-dbap

**Comment by acchen97** [comment]
This is done, thanks for the contribution.
