### ISSUE TITLE
Logstash Delete/trim bigger size logs

### ISSUE THREAD

**Issue by PraveenJayakrishnakumar** [elastic/logstash#3282]
We are using SQS output, but unfortunately SQS allows only 256K size per messages/batch. Does logstash is providing any features to remove/trim log messages, if it reaches some threshold limits.

**Comment by wiibaa** [comment]
@PraveenJayakrishnakumar there is a pending pull request in sqs output repository for your case https://github.com/logstash-plugins/logstash-output-sqs/pull/4.
As Logstash 1.5 is released, it is best to open plugin specific issues in their specific repository. Can you please close this ticket and re-open it under https://github.com/logstash-plugins/logstash-output-sqs/issues. Thanks

**Comment by PraveenJayakrishnakumar** [comment]
Re-opening this ticket under SQS output https://github.com/logstash-plugins/logstash-output-sqs/issues/5
