### ISSUE TITLE
Bad documentation/handling for geo_point types in logstash

### ISSUE THREAD

**Issue by cosh** [elastic/logstash#3291]
As a user I want to be able to use the Kibana4 maps. In order to do that the user has to create a geo_point property. There is no documentation available how to create a geo-point property from a longitude/latitude. Furthermore there should be a dedicated filter for geo_point types done in a way that you don't need to do the cumbersome mutate/rename/convert oddysee.

**current oddysee**
logstash filter:

```
if [lat] and [lon] {

        mutate {
            rename => [ "lat", "[geoComplaint][location][lat]", "lon", "[geoComplaint][location][lon]" ]            
        }

        mutate {
            convert => [ "[geoComplaint][location][lat]", "float" ]
            convert => [ "[geoComplaint][location][lon]", "float" ]
        }
    }
```

template extension

```
"geoComplaint": {
                    "dynamic": true,
                    "path": "full",
                    "properties": {
                        "location": {
                            "type": "geo_point"
                        }
                    },
                    "type": "object"
                }
```

**proposal**

```
filter {
  geo {
    field => [ "location" ],
    longitude => %{lon},
    latitude => %{lat}
  }
}
```

**Comment by fifteen3** [comment]
I took a stab at solving this. I tested it and it works. Feedback is appreciated.

https://github.com/fifteen3/logstash-filter-geo
