### ISSUE TITLE
sincedb saves file position in the middle of a line

### ISSUE THREAD

**Issue by kipras** [elastic/logstash#3293]
When logstash is stopped - the file position written in the sincedb file is in the middle of a line. And if you do some custom filtering on that log (write a custom ruby { code => "..." } block for example), this can easily lead to logstash freezing after restart (because of values missing in the first retrieved line), with no good way to understand what happened.

But the [logstash file input documentation](http://logstash.net/docs/1.4.2/inputs/file) clearly states, that:

    By default, each event is assumed to be one line.

I've spent many hours on this issue already, and when this bug happens you only get useless error messages like this, that contain only references to logstash internal java & ruby files:

    Exception in filterworker {"exception"=>#<TypeError: can't dup NilClass>, "backtrace"=>["org/jruby/RubyKernel.java:2057:in `dup'", "/usr/local/logstash/vendor/jruby/lib/ruby/1.9/date/format.rb:833:in `_parse'", "/usr/local/logstash/vendor/jruby/lib/ruby/1.9/date.rb:1823:in `parse'", "(ruby filter code):6:in `register'", "org/jruby/RubyProc.java:271:in `call'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-0.1.5/lib/logstash/filters/ruby.rb:37:in `filter'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:162:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:159:in `multi_filter'", "(eval):55:in `cond_func_1'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):52:in `cond_func_1'", "(eval):41:in `filter_func'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:156:in `start_filters'"], :level=>:error}

------------------------------------------------------------------------------------------

Example, assume logstash is installed at `/usr/local/logstash` :

logstash config:

    input {
      file {
        path => "/usr/local/logstash/input.txt"
        type => "test"
        sincedb_path => "/usr/local/logstash/input.sincedb"
        sincedb_write_interval => 1
        stat_interval => 1
        start_position => "beginning"
      }
    }

    output {
      file {
        path => "/usr/local/logstash/output.txt"
      }
    }

Example input data: https://gist.githubusercontent.com/kipras/0579d663288f2535e37b/raw/44f198119730733d9ff97c8fcea342ad7ef4df1b/input.txt

Steps to reproduce:
1. install logstash
2. create `logstash.conf` in logstash directory, with the content specified above
3. put the source data (input.txt) in the above gist in logstash directory
4. in the logstash directory run `bin/logstash -f logstash.conf`
5. right after logstash starts up (on 1.5.0 - you get the message `Logstash startup completed`, on 1.4.2 - you get the message "Using milestone 2 input plugin 'file'.") - quit it with Ctrl+C. NOTE that this is easier to do with logstash 1.5.0, because it notes when it starts processing input and it closes more easily (1.4.2 sometimes doesn't respond to Ctrl-C for some time, you have to hit it several times and hope for the best).
6. check `input.sincedb` - it should contain one line, with 4 numbers. The last number contains the position in the file, where logstash stopped. This position should be lower than the file size, so logstash would have to continue from that point after it is restarted. Save this number (lets call it `SINCEDB_POS`).
7. open `output.txt` with a text editor and scroll all the way to the bottom. Note the position (line number) of the last outputted json entry, lets call it `LAST_LINE`.
8. restart logstash again, with `bin/logstash -f logstash.conf`
9. open `output.txt` again, go to the line after `LAST_LINE` - you will see that the `message` of the json is trucated, i.e. it does not contain the full input line.

If logstash consumed the entire file before you were able to close it, or (by some miracle) logstash did stop at a line break - 
1. delete `input.sincedb`
2. delete `output.txt`
3. try again - start from step 4

Optional:
Manually check `SINCEDB_POS`, to see that it indeed saved a position in the middle of a line.
1. Run:
    ```
    dd count=500 if=input.txt of=input.txt.cut bs=1 skip=<SINCEDB_POS>
    ```
2. Now open `input.txt.cut` and note that it indeed starts from the middle of a line (doesn't begin with a capital letter).

This seems kinda critical, as this leads to generating bad output data in the best case and freezing logstash (with no clue as to what happened) in the worst case.

Whenever this issue happened during testing for me (and my ruby filters would break) - if i changed the stored `sincedb` file position value to a position in between-lines (the position of a _\n_ line break) - it worked correctly.

Logstash versions observed to have this behavior : 1.4.2, 1.5.0
Again, note that it's easier to debug this issue with 1.5.0 (explained above)

**Comment by jsvd** [comment]
I was able to reproduce this quite consistently with your steps. This, however, is an issue with the https://github.com/jordansissel/ruby-filewatch/ library that this plugin uses.

I'll leave this open but create a new one there and link it here.

**Comment by jsvd** [comment]
created an issue about this in the ruby-filewatch project: https://github.com/jordansissel/ruby-filewatch/issues/56

**Comment by kipras** [comment]
Thanks so much! :)

**Comment by jsvd** [comment]
Fixed in https://github.com/jordansissel/ruby-filewatch/commit/ba083a1244b1df23f89d5aded6420bb7761d970f

**Comment by kipras** [comment]
Thank you again!
