### ISSUE TITLE
How to collect JVM metrics of running logstash instance?

### ISSUE THREAD

**Issue by svenmueller** [elastic/logstash#3294]
i would like to gather JVM metrics of the running logstash java process (ubuntu 12.04) and push it to graphite. Any idea what's the best way to achieve that?

**Comment by m1k3ga** [comment]
+1

**Comment by ph** [comment]
This is related to a stats/metrics API https://github.com/elastic/logstash/issues/2611

**Comment by Xylakant** [comment]
we use JMX in combination with jmxtrans. works fine.

**Comment by suyograo** [comment]
Will be solved in #2611
