### ISSUE TITLE
Failing on Windows doing 'getting started' examples

### ISSUE THREAD

**Issue by technosf** [elastic/logstash#3296]
Java 1.8 build 40
Windows 7 x64

First, unexpected output:
`  C:\logstash-1.5.0>bin\logstash -V`
`    io/console not supported; tty will not be manipulated`    _<= Unexpected_
`    logstash 1.5.0`

Then to an example that _does_ work:
`  C:\logstash-1.5.0>bin\logstash -e 'input { stdin { } } output { stdout {} }'`
`    io/console not supported; tty will not be manipulated`
`    Logstash startup completed`
`    Hello World`
`    2015-05-21T19:34:29.934Z 0.0.0.0 Hello World`

Then to an example that _does not_ work:
`  C:\logstash-1.5.0>bin\logstash -e 'input { stdin { } } output { stdout { codec => rubydebug } }'`
`    io/console not supported; tty will not be manipulated`

Log stash then exits. No error message, even when --debug is on

Thank you!

**Comment by wiibaa** [comment]
The issue is how windows command line understand single quote! It is not a valid parameter delimiter. You can either:
* use double quotes only in windows cmd
* use powershell that allows both type of quotes as delimiter

In a general way, if you have issue with the **-e** parameter, save your configuration to a file and use `-f <yourfilepath>`

**Comment by suyograo** [comment]
@technosf can you reopen this if @wiibaa suggestion does not work?

**Comment by technosf** [comment]
Double quotes work. 

Debug message leak still exists.

Let me clarify my bug - examples should be expounded for Windows so that they work as they would on *nix. 

Thank you.

**Comment by scottlawrencelawson** [comment]
I have a similar, but slightly different issue, I get the same error of: "io/console not supported; tty will not be manipulated" in my cygwin terminal. 

I am a total newbie to ELK stack and am following along with this tutorial (https://www.found.no/foundation/analyzing-weblogs-with-elasticsearch/) on my Win7 Laptop. I installed all bits and have Logstash working with the basic examples and now am trying to send data to my Found Elastic Search instance with a file. I made the example .conf file (in the tutorial and when I run this command "$ bin/logstash agent --verbose -f found.conf" at the end I get the error: "message=>"Failed to install template: connect timed out", :level=>:error".

Are these two related? Is the io terminal issue causing the tutorial to fail?

**Comment by CarolTozzi** [comment]
I just installed elasticsearch and logstash on my windows 7 machine and I got this error:
"io console not supported; tty will no be manipulated
The signal HUP is in use by the JVM and will not work correctly on this platform."

I tried using the full path to the conf file and it still doesn't work. I am using logstash version 2.3.4.
Is there a way to fix that?
