### ISSUE TITLE
Logstash 1.5.0 configtest does not verify output elasticsearch index case

### ISSUE THREAD

**Issue by naisanza** [elastic/logstash#3297]
I'm running Logstash 1.5.0 on Ubuntu server 14.10. I was given the erro, "logstash failed action with response of 400" when I had uppercased letters in my index, but the --configtest passed it as OK.

output {
    if [type] == "TestData" {
	elasticsearch {
	    index => "TestData"
	}
    }
}

**Comment by purbon** [comment]
Nowadays the config test is nowaday only checking for syntax and not content of it. I'll #3301 in benefit of  where we can discuss the right solution for this kind of error.
