### ISSUE TITLE
Provide multiple internal loggers 

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3300]
Migrated from: #1600

from https://github.com/elastic/logstash/issues/1600#issuecomment-71285923

> @colinsurprenant I think this belongs in our discussion of multiple internal loggers where we could  allow users to silence log messages from certain plugins. Context - provide functionality to Elasticsearch's configurable per-component log levels.

**Comment by suyograo** [comment]
Closing this in favor of #3321
