### ISSUE TITLE
Crashes using riemann output

### ISSUE THREAD

**Issue by falzm** [elastic/logstash#3303]
I'm trying out the [Riemann output plugin](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-riemann.html), but when Logstash processes an event it crashes with the following error:

```
NoMethodError: undefined method `each' for #<LogStash::Event:0x17271176>
     map_fields at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-riemann-0.1.4/lib/logstash/outputs/riemann.rb:110
        receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-riemann-0.1.4/lib/logstash/outputs/riemann.rb:144
         handle at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88
    output_func at (eval):261
   outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:244
  start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:166
```

Logstash version : 1.5.0 (installed via official Debian package), with `logstash-output-riemann` installed via the `plugin` Logstash command as stated in the documentation.
JRE version : Oracle 8u45

Let me know if you need more information about my setup.

**Comment by wiibaa** [comment]
@falzm starting with logstash 1.5, it is strongly recommended to open plugin specific issue into the plugin repository. Can you please check that https://github.com/logstash-plugins/logstash-output-riemann/issues/2 already describe your error correctly and then close this ticket.
If you are able to hack logstash, you could even test the proposed fix in https://github.com/logstash-plugins/logstash-output-riemann/pull/1.
Thanks

**Comment by falzm** [comment]
OK, sorry for the noise.
