### ISSUE TITLE
./plugin install does not install a local plugin as described in docs

### ISSUE THREAD

**Issue by tnolet** [elastic/logstash#3306]
Simply put, this https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html#_test_installation doesnt work. Running logstash 1.5.0, the install script reports success, however listing the plugins my new plugin is not there. Also running logstash with the new input throws an error:

```bash
Tims-MacBook-Pro:logstash-1.5.0 tim$ bin/plugin install /Users/tim/IdeaProjects/logstash-input-sse/logstash-input-sse-0.1.0.gem 
Validating /Users/tim/IdeaProjects/logstash-input-sse/logstash-input-sse-0.1.0.gem
Installing logstash-input-sse
Installation successful
Tims-MacBook-Pro:logstash-1.5.0 tim$
```

```bash
Tims-MacBook-Pro:logstash-1.5.0 tim$ bin/logstash -e 'input { sse {} } output {stdout { codec => rubydebug }}'
The error reported is: 
  Couldn't find any input plugin named 'sse'. Are you sure this is correct? Trying to load the sse input plugin resulted in this error: no such file to load -- logstash/inputs/sse
```

Notice no logstash-input-sse plugin is there.

```bash
Tims-MacBook-Pro:logstash-1.5.0 tim$ bin/plugin list
...
logstash-input-rabbitmq
logstash-input-redis
logstash-input-s3
logstash-input-snmptrap
logstash-input-sqs
logstash-input-stdin
logstash-input-syslog
logstash-input-tcp
logstash-input-twitter
logstash-input-udp
...
```

**Comment by ph** [comment]
@tnolet Can you paste the content of your `Gemfile` and is the source code of the plugin available somewhere?

**Comment by tnolet** [comment]
@ph certainly. I just pushed it. It is a rough initial sketch of using SSE as an input. https://github.com/magneticio/logstash-input-sse

**Comment by tnolet** [comment]
@ph Ok, so I `rm -rf`-de my on local repo and then pulled the remote one again. Rebuild the gem and registered it. Now it works fine! I have no clue what happened there, but it must me a mismatch between RVM environments and local gem installations somehow. Closing this issue.

**Comment by ph** [comment]
Nice thank you for updating this :)

I've tested locally and it work for me too, if you encounter this problem again do not hesitate to create an issue!
