### ISSUE TITLE
How to change log level in the output plugins?

### ISSUE THREAD

**Issue by BrickXu** [elastic/logstash#3307]
Hi all,

I used elasticsearch as an output with the logstash 1.5, and I could get some INFO level logs when elasticsearch output plugin startup, how could I change the output plugin log level, I want to see some DEBUG logs to track some issues.

I've try ` --debug` and ` --verbose` options, it does not work.

thanks.

**Comment by suyograo** [comment]
@BrickXu you cannot control log level per plugin but you can use `--verbose` to get debug logs for entire LS. Specifically for ES output, if you are using node/transport protocol you can change log levels through logging.yml in `$ES_HOME/config`

**Comment by BrickXu** [comment]
@suyograo It works well, thanks very much :)
