### ISSUE TITLE
Raspberry Pi2 logstash installation

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3316]
@benoiton figured how to setup logstash on the Raspberry Pi2 - I think we should either maybe try to include the missing library as described in jruby/jruby#1561 or document in a howto/blog/wiki the installation steps in #3287

**Comment by nthx** [comment]
Actually same solution is also required (and works) for Odroid XU3 Lite. The currently attached lib doesn't work out of the box on Odroid. (tested with v4.2.0)

**Comment by driegel** [comment]
Well, I feel that the real problem is that Logstash ships binaries :-( On the other side, there are no repositories for jruby and libjffi for all enterprise linux distributions. If there were, the logstash package could be smaller and there would be proper binaries on each platform and linux distribution.

**Comment by suyograo** [comment]
Not sure if there have been more requests for this or it's on anyone's radar; so closing this. Please reopen a new issue if this is still important.

**Comment by benoiton** [comment]
For the records:

- Current way to install Logstash 5.2 on raspbian is:
> sudo apt-get install ant texinfo openjdk-8-jdk build-essential
> git clone https://github.com/jnr/jffi.git
> cd jffi
> ant jar
> sudo cp build/jni/libjffi-1.2.so /opt/logstash/vendor/jruby/lib/jni/arm-Linux
- Logstash works on Pi3 after replacing jffi. 10 minutes to start and slow to process lines.
- Processing syslog with filebeat + pipeline is faster by 2 orders.

**Comment by driegel** [comment]
One more thought:
Raspberry Pi2 and Raspberry Pi3 support hardfloat (vfp, vfpv3, vfpv4)
So it is best to use Java that can use hardfload as well (that is not the OpenJDK). With that, Logstash will start up much faster.

source:
```
# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5
```

**Comment by benoiton** [comment]
On a Raspberry Pi 3:

> \# cat /proc/cpuinfo | head -10
> processor       : 0
> model name      : ARMv7 Processor rev 4 (v7l)
> BogoMIPS        : 76.80
> Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
> CPU implementer : 0x41
> CPU architecture: 7
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4

With OpenJDK 8:

> \# java -version
> openjdk version "1.8.0_40-internal"
> OpenJDK Runtime Environment (build 1.8.0_40-internal-b04)
> OpenJDK Zero VM (build 25.40-b08, interpreted mode)
> \# time /opt/logstash-5.2.0/bin/logstash --help
> [...]
> real    13m52.024s
> user    14m11.280s
> sys     0m2.110s

With Oracle JDK 8:

> \# update-java-alternatives -s jdk-8-oracle-arm32-vfp-hflt
> \# java -version
> java version "1.8.0_65"
> Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
> Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
> [...]
> real    0m39.721s
> user    0m48.060s
> sys     0m1.690s

It's indeed much much faster!
Thanks for the tip.
