### ISSUE TITLE
Missing unique filter plugin in 1.5.0

### ISSUE THREAD

**Issue by adamjt** [elastic/logstash#3318]
Running a config check results in:

```
The error reported is:
  Couldn't find any filter plugin named 'unique'. Are you sure this is correct? Trying to load the unique filter plugin resulted in this error: no such file to load -- logstash/filters/unique
```

Plugin is missing:

```
Validating logstash-filter-unique
Plugin logstash-filter-unique does not exist
ERROR: Installation aborted, verification failed for logstash-filter-unique
```

**Comment by purbon** [comment]
HI @adamjt, I just check the 1.4 branch and I don't see any filter unique (https://github.com/elastic/logstash/tree/1.4/lib/logstash/filters), there is also no unique filter in the 1.5 (https://github.com/logstash-plugins). 

Can you provide more intel on where you found this unique filter? might be something custom of yourself?

**Comment by adamjt** [comment]
Sure thing! It's part of the contrib that 1.4 used. https://github.com/elastic/logstash-contrib/blob/master/lib/logstash/filters/unique.rb

**Comment by purbon** [comment]
This is actually an issue, this plugin was missed during the migration. Thanks for reporting, I will make sure to create the new plugin.

**Comment by adamjt** [comment]
Great, thanks @purbon!

**Comment by purbon** [comment]
With the creation of https://github.com/logstash-plugins/logstash-filter-unique, and the release of the gem, you're now able to run:

```
╰─$ bin/plugin install logstash-filter-unique
Validating logstash-filter-unique
Installing logstash-filter-unique
Installation successful
``` 

Closing this for now, if you encounter more problems, feel free to open other issues.
