### ISSUE TITLE
Enable finer control of log levels, e.g. per-plugin, per-message etc

### ISSUE THREAD

**Issue by timbunce** [elastic/logstash#3321]
For non-trivial applications simply enabling `-v -v`, to get more insight into what's happening results in being drowned in debug output. Some means of finer control of log levels would be very helpful.

Some possibilities:
- per-plugin control, perhaps via a `log_level => ...` attribute. It might not do much to start with but once there's a common attribute defined plugin developers can start using it.
- per-message control, perhaps via a meta attribute.
- combine the two so that an input plugin can set a meta attribute to trace messages from that plugin.

For efficiency I'd be happy to see this extra logic only enabled when logstash is run with an extra option, perhaps require a single `-v` to enable the extra checks.

(Follows on from #3307 and years of annoyance at the verbosity of `-v -v`.)

**Comment by allenmchan** [comment]
I think this is a great idea and might be helpful to understand why a specific output or filter is slowing down the pipeline

**Comment by suyograo** [comment]
Agreed. Related https://github.com/elastic/logstash/issues/3300

**Comment by BrickXu** [comment]
+1, it could help us to tuning filter and do some optimizing, very useful feature if it could be done.

**Comment by driskell** [comment]
This duplicates my #2040?

**Comment by suyograo** [comment]
Fixed in 5.0.0
