### ISSUE TITLE
Logstash 1.5.0-1 fails to uninstall with yum

### ISSUE THREAD

**Issue by pschipitsch** [elastic/logstash#3322]
I installed using the repository.

When I do yum erase logstash I get the following error:

<pre><code>Loaded plugins: security
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package logstash.noarch 1:1.5.0-1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================================
 Package                                 Arch                                  Version                                  Repository                                    Size
===========================================================================================================================================================================
Removing:
 logstash                                noarch                                1:1.5.0-1                                @logstash-1.5                                127 M

Transaction Summary
===========================================================================================================================================================================
Remove        1 Package(s)

Installed size: 127 M
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Error in PREUN scriptlet in rpm package logstash
1:logstash-1.5.0-1.noarch was supposed to be removed but is not!
  Verifying  : 1:logstash-1.5.0-1.noarch                                                                                                                               1/1 

Failed:
  logstash.noarch 1:1.5.0-1                                                                                                                                                

Complete!</code></pre>

**Comment by pschipitsch** [comment]
It looks like something is managing the memcached user in passwd but nothing in the group file.

<pre><code>
sudo rpm -e logstash-1.5.0-1.noarch
groupdel: cannot remove the primary group of user 'memcached'
error: %preun(logstash-1:1.5.0-1.noarch) scriptlet failed, exit status 8

egrep "logstash|memcached" /etc/passwd
memcached:x:499:499:Memcached daemon:/var/run/memcached:/sbin/nologin
logstash:x:495:499:logstash:/opt/logstash:/sbin/nologin

egrep "logstash|memcached" /etc/group
logstash:x:499:
</pre></code>

**Comment by AdeMiller** [comment]
This still seems to be an issue with 2.0.0-1
```
cmd           : yum -y remove logstash
stdout:
    Loaded plugins: fastestmirror
    Setting up Remove Process
    Resolving Dependencies
    --> Running transaction check
    ---> Package logstash.noarch 1:2.0.0-1 will be erased
    --> Finished Dependency Resolution
    
    Dependencies Resolved
    
    ================================================================================
     Package       Arch        Version         Repository                      Size
    ================================================================================
    Removing:
     logstash      noarch      1:2.0.0-1       @/logstash-2.0.0-1.noarch      130 M
    
    Transaction Summary
    ================================================================================
    Remove        1 Package(s)
    
    Installed size: 130 M
    Downloading Packages:
    Running rpm_check_debug
    Running Transaction Test
    Transaction Test Succeeded
    Running Transaction
    userdel: user logstash is currently used by process 14908
    groupdel: cannot remove the primary group of user 'logstash'
    error: %preun(logstash-1:2.0.0-1.noarch) scriptlet failed, exit status 8
  Verifying  : 1:logstash-2.0.0-1.noarch                                    1/1 
    
    Failed:
      logstash.noarch 1:2.0.0-1                                                     
    
    Complete!
stderr:
    Error in PREUN scriptlet in rpm package logstash
    1:logstash-2.0.0-1.noarch was supposed to be removed but is not!
```
