### ISSUE TITLE
Include message in errors with uninitialised variable

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#3326]
A user had a problem whereby a device generating logs changed what was being sent to LS, this caused the a variable to no longer be populated and it was generating this error;

```
{:timestamp=>"2015-05-22T16:48:02.759000-0400", :message=>"Failed parsing date from field", :field=>"sourcetime", :value=>"%{date}:16:48:00", :exception=>java.lang.IllegalArgumentException: Invalid format: "%{date}:16:48:00", :level=>:warn}
```

Would it be possible to include the full message when we error on this sort of thing?
Also can we try to catch this thing before we get to the point above and error the event out?

**Comment by suyograo** [comment]
It maybe possible to validate it but maybe if `--verbose` is on?

**Comment by suyograo** [comment]
Closing this for now.
