### ISSUE TITLE
Add mechanism for filter plugins to declare themselves thread-safe or not

### ISSUE THREAD

**Issue by timbunce** [elastic/logstash#3329]
Relates to #1590 and several other issues around multi-threading.

Simply _documenting_ the fact that a filter "will not work with multiple worker threads" (as in #1591) isn't safe because, as we know, humans don't always read _and remember_ the documentation.

Also "will not work" isn't quite true because, generally, the filter _will seem to work fine_ in testing but become a source of possibly subtle corruption bugs under load in production.

I suggest that filter plugins are given a way to declare themselves thread-safe or not. So each plugin is either declared thread-safe, declared not-thread-safe, or thread-safety-unknown.

Then, if multiple filter worker threads are enabled, then the filter plugins are checked. Any not-thread-safe filter plugins cause an error to be logged at startup, listing the relevant plugins, and the `-w` option would be ignored. Any thread-safety-unknown filters would cause a warning.

**Comment by timbunce** [comment]
Oops. Now I look at the error message in #1590 I see that something like this already exists in 1.5. Thanks! Feel free to close this if there's nothing of value in the description.

**Comment by purbon** [comment]
Thanks for your sharing, more details on how to use this in your plugins, take a look at https://github.com/logstash-plugins/logstash-filter-multiline/blob/master/lib/logstash/filters/multiline.rb#L130 ... then internally LS will handle this. 

I will close this issue, as you point out, feel free to open it again is you have more related issues.
