### ISSUE TITLE
Source json file contains duplicate "host" field (and it's being replaced with a LSF shipper hostname)

### ISSUE THREAD

**Issue by landonix** [elastic/logstash#3333]
I'm not sure if this belongs under lumberjack input (https://github.com/logstash-plugins/logstash-input-lumberjack), but the problem involves losing the integrity of the original message that contains a host field.
The input is:
https://gist.github.com/landonix/ac0cb86987b79823ec92

The source log file and post digested file (LSF->LS->ES)
https://gist.github.com/landonix/d326a672d2d50284b9cc

If more information is needed, please let me know. I've been troubleshooting this for a few weeks as time allows (and also asking on IRC). Any help would be greatly appreciated!

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/24. Let's continue the discussion there! :)
