### ISSUE TITLE
Logstah "kafka_client" plugin Discuss

### ISSUE THREAD

**Issue by happyfishyxf** [elastic/logstash#3335]
I found the dependency "kafka_client" in the logstash V1.5.0 directory. However I did not find the configuration of it  anywhere except for the introduction of "kafka" plugin. 
And U can get the introduction of "kafka_client" just from http://kafka.apache.org/documentation.html#producerapi

**Comment by markwalkom** [comment]
There's details on how to configure it in the docs - https://www.elastic.co/guide/en/logstash/current/index.html

**Comment by suyograo** [comment]
also the input/output docs are here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html
