### ISSUE TITLE
Uninstall plugin fails

### ISSUE THREAD

**Issue by felipegs** [elastic/logstash#3336]
If I install a plugin using a gem file, and after that I try to remove with the command `bin/plugin uninstall plugin-name` it fails, saying that plugin is not installed.

**Comment by jsvd** [comment]
confirmed:

```
~/logstash-1.5.0 % bin/plugin install logstash-input-http-0.0.1.gem
Validating logstash-input-http-0.0.1.gem
Installing logstash-input-http
Installation successful
bin/plugin install logstash-input-http-0.0.1.gem  18.15s user 0.84s system 54% cpu 34.936 total
joaoduarte@Joaos-MBP-2 ~/logstash-1.5.0 % bin/plugin uninstall logstash-input-http
ERROR: Uninstall Aborted, message: This plugin has not been previously installed, aborting
```

**Comment by purbon** [comment]
Fixed in #3362

**Comment by felipegs** [comment]
I update to 1.5.1 and the issue persist

**Comment by purbon** [comment]
@felipegs Sorry to heard that, can you provide more information about your environment? I would like to reproduce your exact environment and make this issue go away. Looking forward to have more inside from your env to reproduce it.

**Comment by felipegs** [comment]
@purbon, I did more test, I think I made a mistake. If I try to remove using root, it works fine, if I try to remove using logstash user, I have an error about plugin not installed.
Sorry

**Comment by purbon** [comment]
Issues with permissions, funny ones. I guess the idea here would be to detect this better on LS side and report an appropriate message to you as user. Thanks for reporting this.
