### ISSUE TITLE
squid grok pattern

### ISSUE THREAD

**Issue by hrchu** [elastic/logstash#3342]
There are many logstash config example for squid on line, e.g., 
https://gist.github.com/sakalajuraj/6339942
https://gist.github.com/fetep/e2d8678cd2952d876c39
but patterns in these example does not fit default squid log format: 
http://www.squid-cache.org/Doc/config/logformat/

I just create one:
https://gist.github.com/hrchu/0cc5e783387f5453f528

**Comment by purbon** [comment]
@hrchu since 1.5.0 there is the https://github.com/logstash-plugins/logstash-patterns-core repo working as repository of patterns. Do you mind making a PR there to add your gist? it would be very nice.

/cheers

**Comment by hrchu** [comment]
@purbon ok I will go to the right place.
