### ISSUE TITLE
Logstash-forwarder on OpenSUSE13.2 don't harvest log 

### ISSUE THREAD

**Issue by Limskya** [elastic/logstash#3343]
Hi everyone,

I got an issue with logstash-forwarder, i have install logstash ( on Ubuntu 14.04) and a logstash forwarder (on OpenSUSE 13.2 ) 

When i run logstash forwarder:
![image](https://cloud.githubusercontent.com/assets/12657880/7880564/0cbf94f8-05fb-11e5-9810-868ba8ba9d30.png)

And then there is nothing more, logstash forwarder doesn't send any logs...

Here i give you my logstash config: 
![image](https://cloud.githubusercontent.com/assets/12657880/7880600/610ff58e-05fb-11e5-96bb-96f3056f489b.png)

thanks !!

**Comment by ph** [comment]
Resolved in  https://github.com/elastic/logstash-forwarder/issues/467 ?
