### ISSUE TITLE
how monitor es'data change?

### ISSUE THREAD

**Issue by rfyiamcool** [elastic/logstash#3344]
how monitor es'data change one day  and send mail

**Comment by suyograo** [comment]
@rfyiamcool This is not specific to Logstash project. There are number of open source monitoring/alerting solutions like zabbix which you can use for example. 

Also, if you are interested, we will be releasing a commercial plugin called [watcher](https://www.elastic.co/products/watcher) which is an alerting solution for Elasticsearch.

**Comment by ycombinator** [comment]
@rfyiamcool Also, if you are curious to try out the beta version of Watcher and learn about using it, you can check it out at https://www.elastic.co/products/watcher.
