### ISSUE TITLE
Error while using socket class

### ISSUE THREAD

**Issue by aabed** [elastic/logstash#3349]
I think the following error is because you don't have the Socket class fully implemented in the bundled jruby with logstash

jruby-1.7.19 :001 > require "socket"
=> true
jruby-1.7.19 :002 > Socket::Option.bool(:INET, :SOCKET, :KEEPALIVE,true)
ArgumentError: wrong number of arguments calling bool (4 for 1)
from (irb):2:in evaluate' from org/jruby/RubyKernel.java:1107:ineval'
from org/jruby/RubyKernel.java:1507:in loop' from org/jruby/RubyKernel.java:1270:incatch'
from org/jruby/RubyKernel.java:1270:in catch' from /usr/local/rvm/rubies/jruby-1.7.19/bin/irb:13:in(root)'

**Comment by suyograo** [comment]
@aabed what version of Logstash?

/cc @purbon @wiibaa: I know you both were debugging this..

**Comment by aabed** [comment]
well I am using 1.5, however the problem is with Jruby itself
kindly check 
https://github.com/jruby/jruby/issues/2997

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
