### ISSUE TITLE
Logstash 1.4.2 "leaking" CPU

### ISSUE THREAD

**Issue by ryanbrink** [elastic/logstash#3356]
I apologize if this is something that has been fixed, but we've been experiencing a cyclical CPU "leak" on Logstash that eventually resolves itself by killing the process, which restarts are service and keeps things running for another few days. Here is what it looks like (AWS instance):
![screen shot 2015-06-01 at 7 51 20 am](https://cloud.githubusercontent.com/assets/5272967/7912376/d5374468-0834-11e5-81ea-462c6c23e122.png)
(orange line is the average CPU for the instance in 15 minute intervals)

We're using the SQS input and the Elasticsearch HTTP output and process a pretty regular stream of about 6 records per second.

**Comment by purbon** [comment]
Can you share your config? so we might try to reproduce somehow? thanks a lot!

Might be related to same issues as in #3302 .

**Comment by suyograo** [comment]
@ryanbrink can you try your config on latest 1.5?
