### ISSUE TITLE
A few bad redirects on logstash.net

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#3359]
The following are redirecting to elastic.co (correctly) but are directing users to pages that are missing.

These should be easy to fix, but here's the list:

/docs/VERSION/
/docs/VERSION/filters/advisor
/docs/VERSION/filters/grep
/docs/VERSION/filters/grok
/docs/VERSION/filters/grokdiscovery
/docs/VERSION/filters/noop
/docs/VERSION/filters/useragent
/docs/VERSION/flags
/docs/VERSION/inputs/collectd
/docs/VERSION/inputs/gemfire
/docs/VERSION/inputs/s3
/docs/VERSION/outputs/amqp
/docs/VERSION/outputs/elasticsearch
/docs/VERSION/outputs/elasticsearch.html
/docs/VERSION/outputs/elasticsearch_http
/docs/VERSION/outputs/file
/docs/VERSION/outputs/s3
/docs/VERSION/release-notes

**Comment by jordansissel** [comment]
With thanks to @russorat for pointing me at the right place to find this data! <3

**Comment by jordansissel** [comment]
@sylvie777 poked me about these today; I'll see if I can't clean them up on the logstash.net side of things first, so hopefully, we won't need to make changes to anything on elastic.co

**Comment by sylvie777** [comment]
@jordansissel Thanks, Jordan! If I can help (e.g., test links), please let me know. Happy to help.  :)

**Comment by jordansissel** [comment]
Also these pages are 404 on logstash.net and should redirect to appropriate places on elastic.co:

/docs/1.5.0/extending/example-add-a-new-filter
/docs/1.5.0/getting-started-centralized
/docs/1.5.0/extending/
/docs/1.5.0/release-notes
/docs/1.5.0/tutorials/metrics-from-logs
/docs/1.5.0/life-of-an-event
/docs/1.5.0/installation
/docs/1.5.0/tutorials/getting-started-simple
/docs/1.5.0/contrib-plugins
/docs/1.5.0/tutorials/getting-started-centralized
/docs/1.5.0/repositories
/docs/1.5.0/flags
/docs/1.5.0/tutorials/10-minute-walkthrough/
/docs/1.5.0/configuration
/docs/1.5.0/tutorials/getting-started-with-logstash

**Comment by jordansissel** [comment]
Most common links from within logstash.net to 404s against pages missing in 1.5.0:

```
% grep '" 404 [0-9]' other_vhosts_access.log | fex '"2 2' '"4' | grep '^/docs/1.5.0' | sort | uniq -c | sort -n | awk '$1 > 50'
     53 /docs/1.5.0/release-notes http://www.logstash.net/docs/1.4.2/release-notes
     60 /docs/1.5.0/tutorials/getting-started-centralized http://logstash.net/docs/1.1.0/tutorials/getting-started-centralized
     63 /docs/1.5.0/tutorials/getting-started-with-logstash http://www.logstash.net/docs/1.4.2/tutorials/getting-started-with-logstash
     66 /docs/1.5.0/tutorials/10-minute-walkthrough/ http://www.logstash.net/docs/1.1.12/tutorials/10-minute-walkthrough/
     70 /docs/1.5.0/tutorials/10-minute-walkthrough/ http://logstash.net/docs/1.1.0/tutorials/10-minute-walkthrough/
     70 /docs/1.5.0/tutorials/getting-started-with-logstash http://www.logstash.net/docs/latest/tutorials/getting-started-with-logstash
     72 /docs/1.5.0/tutorials/getting-started-with-logstash http://logstash.net/docs/1.4.0.beta1/tutorials/getting-started-with-logstash
     79 /docs/1.5.0/configuration http://www.logstash.net/docs/1.2.2/configuration
     83 /docs/1.5.0/flags http://logstash.net/docs/1.4.0.rc1/flags
     88 /docs/1.5.0/installation http://logstash.net/docs/1.0.14/installation
    102 /docs/1.5.0/contrib-plugins http://logstash.net/docs/1.4.0.rc1/contrib-plugins
    105 /docs/1.5.0/configuration http://logstash.net/docs/1.4.0.beta2/configuration
    132 /docs/1.5.0/tutorials/getting-started-with-logstash http://logstash.net/docs/1.4.0.rc1/tutorials/getting-started-with-logstash
    133 /docs/1.5.0/repositories http://www.logstash.net/docs/1.3.2/repositories
    312 /docs/1.5.0/tutorials/getting-started-with-logstash http://logstash.net/docs/latest/tutorials/getting-started-with-logstash
```

I'll use these as a basis for updating the 404 routing on logstash.net's 404 page

**Comment by jordansissel** [comment]
![screen shot 2015-06-16 at 4 32 02 pm](https://cloud.githubusercontent.com/assets/131818/8196848/43bc877e-1445-11e5-8230-543a08bc22d8.png)

Here's a few samples of improved redirects. The specific redirects and recommendations improvements can be seen in the javascript here: https://github.com/logstash/logstash.net/commit/6af9f355cf632db441cf9229e8b592c57ff3fec8#diff-eaf2b86188ec63e62e4c3e71eb198df1R24

I'll deploy this tomorrow once I test a bit more.

**Comment by jordansissel** [comment]
I fixed up a few other links I forgot to add in my first pass. Things are looking pretty solid now when I test locally.

I'll deploy to logstash.net tomorrow unless I need to wait; @russorat and @sylvie777; thoughts?

**Comment by sylvie777** [comment]
@jordansissel Cool! I don't have anything holding back the deployment on my end.

**Comment by jordansissel** [comment]
Deployed on logstash.net.

Example http://logstash.net/docs/1.1.13/outputs/elasticsearch_http now recommends folks visit the 'elasticsearch' output on the latest version:

![screen shot 2015-06-17 at 12 13 49 pm](https://cloud.githubusercontent.com/assets/131818/8216280/62e02b60-14ea-11e5-8d1d-4d74eba5fa0f.png)

I'll check back in a week or two to see how 404s from logstash.net-to-elastic.co have reacted.

**Comment by sylvie777** [comment]
@jordansissel Excellent! Thanks, Jordan!

**Comment by suyograo** [comment]
nice!

**Comment by russorat** [comment]
@jordansissel could you update the link on this page? http://logstash.net/docs/1.4.1/outputs/elasticsearch.html

**Comment by sejiek** [comment]
@suyograo @jordansissel what are the actions for this to be completed now and for all traffic to direct straight to elastic.co? cc @sylvie777

**Comment by jordansissel** [comment]
@russorat I will investigate that bad link.

**Comment by jordansissel** [comment]
@sejiek I don't think we'll ever have all traffic directed to elastic.co because, at this time, there is no plan to move the old documentation (logtash 1.0 through 1.4.x) to be hosted on elastic.co. Long term, once we EOL Logstash 1.4, it is likely logstash.net can be decomissioned fully and maybe at that time all traffic directed to elastic.co?

**Comment by sejiek** [comment]
Ok I thought that is what we were working towards, @tbragin @jeffyosh see ^^ message from Jordan so you also are aware that this will remain open for now - thanks for the update @jordansissel

**Comment by tbragin** [comment]
@suyograo @acchen97  looks like we are delaying Logstash EOL until Nov 1st
