### ISSUE TITLE
RabbitMQ connection error: MarchHare::ChannelAlreadyClosed causes an infinite opening of connections in RabbitMQ

### ISSUE THREAD

**Issue by DKribl** [elastic/logstash#3360]
Hey,

I get following error (infrequent) while shipping logs to RabbitMQ:

```
{:timestamp=>"2015-06-02T10:12:12.822000+0200", :message=>"RabbitMQ connection error: MarchHare::ChannelAlreadyClosed. Will attempt to reconnect in 10 seconds...", :exception=>#<MarchHare::ChannelAlreadyClosed: MarchHare::ChannelAlreadyClosed>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:965:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:963:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:595:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:40:in `publish_serialized'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/json.rb:44:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:31:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):26:in `output_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:error}
```

For every reconnect, there is a new channel and connection being created. So after a few minutes there are tons of connections opened in RabbitMQ. At this point, there is no data coming into RMQ anymore. I have to kill the process of the shipper because the service won't stop. ( It says:  "logstash stop failed; still running) After starting up logstash again it works fine for a few minutes.
Because this error is infrequent and Logstash is normally sending Logs to RabbitMQ, I dont think its a configuration issue... Well I hope so. 

Here's my output config:

    output {
      rabbitmq {
        codec => "json"
        persistent => true
        host => "myconsumerip"
        durable => true
        key => "logstash-key"
        exchange => "logstash-exchange"
        exchange_type => "direct"
        user => "admin_iw"
        password => "mypassword"
        port => 5672
        ssl => false
        verify_ssl => false
        vhost => "logstash"
      }
    }

I updated Logstash to 1.5.0-1 because of [this](https://logstash.jira.com/browse/LOGSTASH-1886) post, but it didn't help. That's why I decided to make a new Post about this kind of issue. I hope you guys can help me :)

**Comment by suyograo** [comment]
hi, thanks for the info, I moved your issue to rabbitmq output repo here: https://github.com/logstash-plugins/logstash-output-rabbitmq/issues/10
