### ISSUE TITLE
On Windows, bugfix_jruby_2558.rb breaks plugins using peeraddr with a parameter

### ISSUE THREAD

**Issue by driskell** [elastic/logstash#3364]
`wrong number of arguments calling 'peeraddr' (1 for 0)`

Following file is the cause:
https://github.com/elastic/logstash/blob/f97c01da0631566e0ec07c9a076286e22a8f43a9/lib/logstash/patches/bugfix_jruby_2558.rb

Seems to be a very old patch that re-implements `peeraddr`, albeit not allowing any parameter. `TCPSocket.peeraddr` and `UDPSocket.peeraddr` have allowed a parameter in MRI since at least 1.9.3 (http://ruby-doc.org/stdlib-1.9.3/libdoc/socket/rdoc/IPSocket.html#method-i-peeraddr), and in JRuby since 1.7.0 (https://github.com/jruby/jruby/commit/d835b3c2adf7f87fbbc8e4cfe8b952c65fd3c3a9). This parameter allows reverse lookup to be disabled.
MRI allows :numeric symbol as well as boolean value, but JRuby only supports the boolean value. 

However, using either when using Logstash breaks the plugin.

**Comment by jsvd** [comment]
Nice catch @driskell, changing the method definition and delegation from:

```ruby
    def peeraddr
      orig_peeraddr.map do |v|
```

to

```ruby
    def peeraddr(*args)
      orig_peeraddr(*args).map do |v|
```

Seems to address the problem. I'll submit a PR to fix

**Comment by Rajeshkumar123** [comment]
I couldn't find RubyIPSocket.java in logstash 1.5.0

**Comment by driskell** [comment]
@Rajeshkumar123 You'll be looking for lib/logstash/patches/bugfix_jruby_2558.rb
(Best to ignore your error trace you had as this file is a special patch that is hidden away and doesn't show in the trace)

See here for the change details:
https://github.com/elastic/logstash/pull/3365/files

**Comment by Rajeshkumar123** [comment]
@driskell  Awesome Its working fine.

**Comment by suyograo** [comment]
Closed https://github.com/elastic/logstash/pull/3365
