### ISSUE TITLE
Read from file misbehavior

### ISSUE THREAD

**Issue by CalldiDoctor** [elastic/logstash#3374]
I'm trying to read logs from a file while more logs are added to it.
Every time one log is added, logstash reads again all the previous log events.

My input configuration setup is the following one:
file {
        path => "/path/to/logs"
        type => "type"
      }
If I'm not wrong this should read starting from the end of the file and from the line stored in .sinceDB, but instead logstash is reading the whole file again.

Thanks

**Comment by jsvd** [comment]
@CalldiDoctor which operating system and logstash version?

You are correct, logstash should not re-read old files.

**Comment by CalldiDoctor** [comment]
Ubuntu 14.04 and Logstash 1.4.2

**Comment by jsvd** [comment]
can you do a full run with --debug and post the output here?

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
