### ISSUE TITLE
connect Logstash 1.5.0 with log4j of several servers

### ISSUE THREAD

**Issue by OhadR** [elastic/logstash#3376]
i've opened this thread in SO, but im not sure whether it should be on SO or here...
http://stackoverflow.com/questions/30624467/connect-logstash-1-5-0-with-log4j-of-several-servers

if i want to connect my logstash to multiple log4j-s. for example, I have 3 tomcats on 3 different machines, and i want all logs (log4j) of all services from all tomcats to send their data to logstash. how can i configure it? does it make sense?

**Comment by suyograo** [comment]
Hey @OhadR thanks for the question. You can also discuss it here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enahncements
