### ISSUE TITLE
Ability to run action after log file process (improvement)

### ISSUE THREAD

**Issue by yehosef** [elastic/logstash#3377]
While there are times that logs are continually written and you want to always look for new entries, the more common practice is that logs are generated for each day and after that day has passed, it will never be written to again.  Idealling, we would like to clean up the log files (compress, copy to s3, delete locally) as soon as possible after processing by logstash. 

I think it would be helpful if logstash could run a process after a log has been processed (once it's hit the end and it's not updated for x amount of time).  I would think the file input config would just have a parameter of "post-process-script"  and "idle-time-for-finish" (or similar).

**Comment by jordansissel** [comment]
Seems many folks are interested in this kind of thing. Cool! Let's continue this discussion here on the file input: https://github.com/logstash-plugins/logstash-input-file/issues/52
