### ISSUE TITLE
Logstash 1.5.0-1 hangs while reading configuration

### ISSUE THREAD

**Issue by mikapp** [elastic/logstash#3381]
I can't get Logstash 1.5.0-1 running with my working config file from Logstash 1.4.2. It just hangs without dropping any errors in logs. I have it installed as a service on Ubuntu 14.04.2 LTS. /var/log/logstash/ files as logstash.log and logstash.err are of size 0 and don't have any lines. "sudo service log stash service " says "running" and I left it for few hours with no effect. My config is pretty large (around 10K lines) but it is mostly conditional if else blocks with "mutate" filter inside and it is running without any issues on 1.4.2

Running logstash agent with -debug option doesn't show any data other that one line "reading configuration".

Any suggestions how I can get more details from logstash or get it fixed?

Thanks

**Comment by jsvd** [comment]
Hi @mikapp I saw your comment on #2490, it should be a manifestation of https://github.com/elastic/logstash/issues/3361, specially since you have a big configuration. A fix has been proposed in https://github.com/elastic/logstash/pull/3378

**Comment by suyograo** [comment]
@mikapp we'll soon release 1.5.1 with this fix. If you'd like to try, you can always test #3378 directly. Closing this for now.

**Comment by mikapp** [comment]
Looks like same issue with 1.5.1:

/logstash agent --debug --configtest --config ~/monitoring/logstash/config/indexer/ppas_dev.conf
Reading config file {:file=>"logstash/agent.rb", :level=>:debug, :line=>"301", :method=>"local_config"}

... and it just hangs here. Is there any way to get more information on what 1.5.1 doesn't like in config? The same config works without issues with 1.4.3
