### ISSUE TITLE
Add warning to bin/plugin update when updating to a new major version of plugin

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#3383]
Soon, there are going to be some backwards-incompatible changes bubbling up in plugins, and it would 
be helpful to users to understand that there is a risk in updating to such versions.

maybe it'll look something like this:

```
$ bin/plugin update logstash-output-elasticsearch
You are updating logstash-output-elasticsearch to a new version 5.0, which may not be compatible with 
4.2. are you sure you want to proceed (Y/N)?
```

**Comment by purbon** [comment]
This makes complete sense to me, specially if we follow with the plugins a more or less semver policy, then this warning is informative for users updating.

**Comment by suyograo** [comment]
Closed by https://github.com/elastic/logstash/pull/3423
