### ISSUE TITLE
New input plugin: logstash-input-httpclient

### ISSUE THREAD

**Issue by bradvido** [elastic/logstash#3387]
I've created a new Logstash input plugin: https://github.com/bradvido/logstash-input-httpclient

It acts as a HTTP Client and periodically queries a http server, processing the response body using the provided codec).  It also optionally uses a few custom `X-Logstash-...` HTTP headers to indicate to the server how fast it is processing events and the server can also indicate if more events are available (in which case the client doesn't wait the sleep interval before getting more events).

It currently has no tests (PR's welcome!), but is working well for us.

Disclaimer: this is my first writing Ruby code!

**Comment by bradvido** [comment]
FWIW, I've been using this input plugin for the past few weeks and it's been solid. I just committed some finishing touches and released the 0.9.0 gem.
Let me know what else I can do.

**Comment by suyograo** [comment]
@bradvido thanks for the awesome contribution! we are evaluating multiple submissions for this functionality here: https://github.com/elastic/logstash/issues/3387 and we need to consolidate all the PRs  into one :)

**Comment by bradvido** [comment]
Found it, I believe you mean https://github.com/elastic/logstash/issues/3497

**Comment by bradvido** [comment]
@andrewvc Since this isn't being used as a base for the [official http input](https://github.com/logstash-plugins/logstash-input-http-poller), should I abandon efforts to get this added as an official Logstash plugin, or does it make sense to have this listed as well (probably with a name change to better reflect the more specific queueing-over-http use case)?

**Comment by andrewvc** [comment]
@bradvido apologies for the delay. While your plugin is cool it's a bit niche for what we're looking for in logstash core plugins currently. Thanks for the submission however!

**Comment by suyograo** [comment]
@bradvido to add to what @andrewvc mentioned, you can continue to host this in your own github account and distribute it via RubyGems.
