### ISSUE TITLE
New input plugin: logstash-input-perfmon

### ISSUE THREAD

**Issue by NickMRamirez** [elastic/logstash#3388]
I've created a new input-plugin for gathering performance metrics on Windows.

On Windows, performance metrics can be collected using Windows Performance Monitor. This plugin collects the same sort of counters by using the command-line tool Typeperf.

[Github repo](https://github.com/NickMRamirez/logstash-input-perfmon)

I've added this gem to [rubygems.org](https://rubygems.org/gems/logstash-input-perfmon):

I've also verified sending its data to a Redis output, then to elasticsearch and kibana.

**Comment by purbon** [comment]
Cool, this looks promising, are you willing to have this plugin at the logstash-plugins org? if so I can start the process. 

Before that, as this is a very windows plugin, might be the name can be tricky, how do you feel about adding something win label in the name? I say so, because then people might know this only works for windows. Make sense?

**Comment by NickMRamirez** [comment]
Something like logstash-input-winperfmon? I'm okay with that. 

I am currently trying to find a way to add an IP or hostname to the data, to show where the data originates. Can the process be started before or after I make those changes?

**Comment by purbon** [comment]
Hi,
  new naming is ok to me. we can start the process as soon as you feel
confortable, let us know.



On Saturday, June 6, 2015, NickMRamirez <notifications@github.com> wrote:

> Something like logstash-input-winperfmon? I'm okay with that.
>
> I am currently trying to find a way to add an IP or hostname to the data,
> to show where the data originates. Can the process be started before or
> after I make those changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/3388#issuecomment-109580035>.
>


-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by NickMRamirez** [comment]
Looking around, others just use "perfmon" as the name:

NewRelic: https://github.com/nickfloyd/newrelic-perfmon-plugin
node.js: https://www.npmjs.com/package/perfmon

And "Perfmon" is the shorthand for the tool: https://technet.microsoft.com/en-us/library/bb490957.aspx. 

I'm starting to think that keeping it named just that would be understood, at least amongst Windows developers. 

I have added the hostname to the event, so it should be ready to go now.

Thanks!

**Comment by NickMRamirez** [comment]
Just saw a thread about another plugin and integration tests. I have integration tests for this, but they would only work if run on a Windows machine. Might need a work-around for that.

**Comment by purbon** [comment]
Hi,
 speaking about the name, it makes sense all you share. My only concern here is for users who are not on window, I mean speak for myself, I might find this plugin and think, oh nice, a perfmon for linux :-1:, but then found out that is only windows. We should make this distinction clear somehow. Might be we can do that throw the documentation, or also introducing a warning when installing this that raises an exception if install in linux, makes sense? 

Speaking about the integration test, what I would recommend, is we create the repo and then we can work there with a PR. 

should I move forward?

**Comment by NickMRamirez** [comment]
Sounds good to me, yes let's move forward.

**Comment by purbon** [comment]
perfect! will setup the repo for you.

**Comment by purbon** [comment]
done @NickMRamirez, you can find the repo at https://github.com/logstash-plugins/logstash-input-perfmon, I will close for now this issue and wait to continue this converstation as a PR in the new repo. Looking forward to it.
