### ISSUE TITLE
[doc] Logstash.net /docs/1.5.0/ redirect is a 404

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3394]
http://logstash.net/docs/1.4.2/ has a banner mentioning the latest version. The link at the end pointing to /docs/1.5.0/ is broken. Maybe we have a dummy page there which redirects to https://www.elastic.co/guide/en/logstash/current/index.html or having this link in the banner directly

![screen shot 2015-06-08 at 14 39 58](https://cloud.githubusercontent.com/assets/1595958/8046031/8bc35ebc-0dec-11e5-98cc-b36bc1eb841c.png)

**Comment by suyograo** [comment]
Works...I really did see it 404

**Comment by jordansissel** [comment]
I believe you :)
