### ISSUE TITLE
Warning about inflight messages when trying to stop Logstash

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3406]
When you send a ^C signal to Logstash and if it is processing in-flight events, it will not stop immediately. It will first stop the input and wait for existing events in the internal buffer to completely drain before quitting. We should provide feedback to the user that it is waiting for events to drain, so it is clear that LS is not stuck, but this is designed behavior. We should also suggest a force kill option introduced in https://github.com/elastic/logstash/pull/3379, but warn that users will lose data.

**Comment by colinsurprenant** [comment]
maybe print a message like "... still waiting for in-flight event to be processed, to force abort with the risk of loosing in-flight events hit ^C" 

Also, if a second ^C is hit to force abort, we could first try to abort all plugins/workers and then pop all events from queues and log these as "lost" events?

**Comment by r00219985** [comment]
Hi, suyograo:
    "if it is processing in-flight events, it will not stop immediately. It will first stop the input and wait for existing events in the internal buffer to completely drain before quitting. "     Which logstash version add this feature ?   My project is using logstash 1.4 and we use iptables to avoid in-flight events loss,  now we encounter another problem with iptables, so I want to know which logstash version solve this problem or logstash 1.4 solved ?   I have looked for related version changlog, but no record with this feature.
