### ISSUE TITLE
grok template

### ISSUE THREAD

**Issue by alqasem** [elastic/logstash#3409]
how to create a grok template,
thank you

**Comment by untergeek** [comment]
We always try to help new users with their configuration questions.  However, GitHub issues are for reporting software errors, problems, and failures.

We do have an online forum where requests for assistance are answered by the community. Please make this request for assistance in our [logstash discussion forum](https://discuss.elastic.co/c/logstash).

**Comment by alqasem** [comment]
thank you,
i found how to create it.
