### ISSUE TITLE
[site] Migrate logstash.net content and redirects to elastic.co

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#3410]
It's time to merge logstash.net's purpose into elastic.co fully!

Main points:
* New users google for things and find old versions of content on logstash.net instead of newer content relevant to the current release of Logstash.
* SEO for Logstash.net isn't great right now, and the marketing team has better visibility/tooling to improve this problem on elastic.co's infrastructure.
* The documentation tooling we use to build and maintain elastic.co is pretty nice, and logstash.net's docs infrastructure is no longer maintained.
* Our wonderful tech writers are most experienced with elastic.co's docs infrastructure, not logstash.net's.

Steps already taken:
* Lots of work moving Logstash 1.5.0's docs to be on elastic.co (done long ago!)
* Setup redirects on logstash.net/ and logstash.net/docs/1.5.0/* to redirect to elastic.co in the correct places (done since a few weeks)

Steps to take next:
* Announce EOL of next EOL'd version of Logstash
* Setup permanent redirects for all the old docs, older than or equal to the most recent EOL'd version, to redirect to the most appropriate location on elastic.co (plugin docs, etc)
* Provide a public archive (tarball?) of the current state of logstash.net in the emergency case that someone needs access to the ancient docs

**Comment by jordansissel** [comment]
cc @tbragin & @suyograo

**Comment by suyograo** [comment]
:+1:

**Comment by palecur** [comment]
@jordansissel, migration looks done -- d'you want to close this? Assigning to you in the interim, feel free to reassign to Pubs if needed.
