### ISSUE TITLE
[docs] Organize plugin documentation better

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3418]
Today the plugins docs are rendered as a long list. We should look into adding a table with multiple columns to organize the docs better. The columns can be current version, quick description, link to github, link to rubygems.org and so on

* [x] Documenting plugins bundled in core https://github.com/elastic/logstash/issues/3841
* [x] Concerns on mobile readability https://github.com/elastic/logstash/issues/2226

**Comment by acchen97** [comment]
Linking concern around mobile readability
https://github.com/elastic/logstash/issues/2226
