### ISSUE TITLE
New input plugin REST call

### ISSUE THREAD

**Issue by maximede** [elastic/logstash#3419]
Hi, I've just created a new input plugin.
It allows logstash to make periodic call to a rest api ( currently only JSON ) and send the resulting JSON in an logstash event.

The idea behind this plugins came from a need to read springboot metrics endpoint, instead of configuring jmx to monitor my java application memory / gc/ etc.

https://github.com/maximede/logstash-input-rest

Cheers

Maxime

**Comment by purbon** [comment]
Cool, This is very interesting. Are you willing to have this integrated in the https://github.com/logstash-plugins plugins org? this would be very nice. If you're up for it, I can start having the repos setup.

**Comment by maximede** [comment]
Yes of course, that would be great. What do you need me to do for that?

**Comment by purbon** [comment]
I will create the repository and let you know, then you should submit a PR there and after a review process it will get merge in and you can start doing releases from there. Makes sense?  BTW, you also get access to our lovely jenkins for CI.

**Comment by maximede** [comment]
OK, perfect.

**Comment by jrgns** [comment]
Can't this be implemented by using the HTTP input plugin?

**Comment by maximede** [comment]
Which http input plug-in are you talking about? 
Most of the http plug-ins I saw were doing the opposite of mine.  They are using logstash as a Web server to receive http calls.

**Comment by jrgns** [comment]
Argh, I was thinking of the HTTP output that can be set up as a client and a server. A REST input would be great.

**Comment by purbon** [comment]
There is actually another proposal doing a similar thing with this plugin, reference at https://github.com/elastic/logstash/issues/3387, it would be nice to see what differentiate both :smile:

**Comment by maximede** [comment]
I think that the biggest difference is that the plugin in #3387 is putting the whole response in the message field.
As mine is expecting JSON, it decodes the payload and creates fields based on the received json. 
I think that they both serve a different purpose.

**Comment by maximede** [comment]
Hi, 

Is there something I could do to move forward with this ticket ?

**Comment by bradvido** [comment]
@maximede I authored #3387, it doesn't just put the whole response in the message field, it first decodes the response with the provided codec. So if your codec is `json_lines`, then it will process each line in the body as a JSON object and you may get 100 logstash events from a single response.

**Comment by maximede** [comment]
Hi @bradvido , 

Sorry, I did not really read your code, just the documentation ;). I guess that if I use json codec (not json_lines) in your plugin, I could achieve what I'm doing. Is there a way to deactivate the keep-alive connection in your plugin ?

**Comment by bradvido** [comment]
If keep alive isn't supported by the server, it should still work (but I haven't tested). Try it out.

**Comment by suyograo** [comment]
@maximede we are evaluating multiple submissions for this one here: https://github.com/elastic/logstash/issues/3387 and want to consolidate all the code into one plugin :)

**Comment by andrewvc** [comment]
Hi @maximede ! We've decided to base our official input plugin off your plugin. I'll be working on fleshing it out and adding specs over here: https://github.com/logstash-plugins/logstash-input-http-poller

I also created a rubygem for it. Shoot me your rubygems info if you'd like to be added to the gem owners list.

Our official gem will be named `logstash-input-http-poller` to reflect its purpose more clearly. Thanks so much for the contribution!

**Comment by maximede** [comment]
Hi @andrewvc , 

That's great !  Is there anything I can do to help ? 
I was thinking about adding a few test, but I had the feeling that I was gonna test more the Httpclient library than the actual code. What are the best practice regarding testing a logstash plugin ?

**Comment by purbon** [comment]
Hi @maximede, regarding testing of a logstash plugin here are a few things to point you to:

* We use rspec for testing plugins, there is a WiP issue describing the most relevant features of it.
* A good example, to take inspiration from, on how to write test for a logstash input is actually https://github.com/logstash-plugins/logstash-input-s3/

I'm more than happy to drive you too creating test, let me know doubts you might have.

/cheers

**Comment by andrewvc** [comment]
@maximede we've ported the plugin to use our new standard HTTP client (manticore). You're right that you want to avoid testing the client. 

Let's discuss on this new issue here: https://github.com/logstash-plugins/logstash-input-http-poller
