### ISSUE TITLE
XML Filter not parsing fields mentioned inside XPATH in Logstash 1.5.0

### ISSUE THREAD

**Issue by Rajeshkumar123** [elastic/logstash#3422]
When I pass the xml files to logstash via logcourier. The xml files are not parsing properly.

Below is my logstash code.

input{
courier {
port => 10545 
transport => "tcp"

}
}

filter{

if [type] == "system_log" {

 xml {
    source => "message"
    store_xml => false 
    xpath => [
        "/system/@message","system_message",  
        "/system/@detail","detail",
        "/system/@host","host",
        "/system/@user","user",
        "/system/@time","timestamp",
        "/system/@type","Type",
        "/system/item/@name", "systemNames"
]
}
output{
stdout{codec=>rubydebug}
}

In my output I didnt see the fileds mentioned inside xpath. I am getting the entire xml in "message" field.

**Comment by splashx** [comment]
Please post a sample of your message.

**Comment by wiibaa** [comment]
If still an issue, please reopen against https://github.com/logstash-plugins/logstash-filter-xml/issues

@suyograo can you close please

**Comment by guyboertje** [comment]
maintainer asked to close this.
