### ISSUE TITLE
Using a private offilne gem server might not work

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3424]
There was a report on IRC that using a private gem server in the Gemfile did not work as expected, the `bin/plugin install --no-verify XXX` command would just hang.

Running the command with the `DEBUG=1` options is returning this:

```
DEBUG: exec /opt/logstash/vendor/jruby/bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-Xmx500m /opt/logstash/lib/pluginmanager/main.rb install --no-verify logstash-filter-oui \nInstalling logstash-filter-oui
```

The machine has no direct access to the internet and there is no proxy available.

**Comment by ph** [comment]
Related to #2376 and #3404

**Comment by purbon** [comment]
@ph If the private Gemserver has access to rubygems or all dependencies I see no particular reason why this should not work.

If the private gemserver has already all dependencies on it, so it has no need to go to rubygems it should work even if no connection in the gemserver ( but it should vary from gemserver to gemserver configuration).

**Comment by ph** [comment]
@purbon _it should work_, I think we have to test this scenario.

**Comment by purbon** [comment]
But define the scenario for the gemserver?  Which scenario are we talking about?

```LS -> private gemserver -> internet -> rubygems.org ```

or 

```LS -> private gemserver -> (no connection to anywhere)```

w.

**Comment by ph** [comment]
**LS -> private gemserver -> (no connection to anywhere)**

**Comment by purbon** [comment]
now is more clear to me, we should definitely test this situation, and not hang without a warning :+1:

**Comment by robmckeown** [comment]
I have the same situation - an environment with no internet connection, and I need to install plugins which have dependencies on other gems.  
Is there any way for me to just drop all the gems I need into some specific directory that Logstash will use or do I need to go down this 'private gemserver' route ?

**Comment by purbon** [comment]
@ph the situation you describe in https://github.com/elastic/logstash/issues/3424#issuecomment-111142060 is never going to work unless you've all dependencies available in your gemserver.

**Comment by ph** [comment]
@purbon Yes, it need to have all the dependencies on it or the gemserver can fetch them at query them (with internet access of course). A complete offline solution like your PR is a better way to do it.

**Comment by purbon** [comment]
@ph another option is to have this repo loaded with everything i regular basis, what is similar to the offline PR at #3404.

**Comment by purbon** [comment]
closing this private gem server support was all merge and released.
