### ISSUE TITLE
When using file wildcards, logstash drops initial lines

### ISSUE THREAD

**Issue by wastedepository** [elastic/logstash#3430]
When I use a wildcard character in the input file path, Logstash behaves very strangely. Say I have some input file, called test1, which I print some log entry message to 5 times ("message1", "message2", etc.), with each message coming half a second apart. I do this printing while Logstash is not running. However, Logstash is "up to date" with the file, except for these new lines.

When I start Logstash up, it'll read the file, but it will skip "message1", and sometimes even "message2", and start with "message3" instead. This *never* happens when I specify the file path directly, without using the wildcard character. Also, monitoring multiple files (test1 and test2) works fine, as long as I specify each of their paths manually, without using the wildcard character.

Even stranger, note that when I do not sleep for half a second between printing the log entries, Logstash ignores all of them!

I don't have problems with messages printed when Logstash is running; problems only occur when it is started on a file it is "behind" on.

I'm running Logstash 1.5.0 on Fedora.

Config file:
```
input {
    file {
        path => "/someabsolutepath/test*"
        start_position => "end"
    }
}

output {
    stdout {
        codec => rubydebug
    }
}
```

Output statement (run before Logstash is started):
`for i in {1..5}; do printf "message${i}\n" >> /someabsolutepath/test1; sleep 0.5; done`

**Comment by suyograo** [comment]
Can you test this with the latest 0.1.11 version of file input? /cc @jsvd 

`bin/plugin update logstash-input-file`

**Comment by wastedepository** [comment]
This seems to fix the problem -- however, see the paragraph below.

I noticed a perhaps something while testing this. This applies to files regardless of whether there's a wildcard in the path or not. However, say I'm looking for files with the wildcard "/someabsolutepath/test*" and I **create** and output to a file that matches this path while Logstash is starting up. Logstash will never detect that initial output, which was created while Logstash was starting up. It will detect any subsequent output when I create while Logstash is running, however.

Also, when I **create** and output to a file while Logstash is running, usually it takes a few seconds and then that initial output is finally processed as you would expect. Good, but if you were to exit Logstash during those few seconds, that output will never be processed.

Let me know if I should open a different ticket for this bug, or if this is known and accepted behavior.

**Comment by wastedepository** [comment]
After thorough testing, this seems to fix the problem, thanks.
