### ISSUE TITLE
logstash 1.5.0 - json filter - json parse failure on first line

### ISSUE THREAD

**Issue by mlecoq** [elastic/logstash#3436]
Hi, 

 I have a strange behaviour with logstash and json filtering (I am using logstash 1.5.0).

With the following configuration:

```
input {
        file {
                path => [ "/opt/import-data/*"] 
        }
}

filter{
    json {
        source => message
    }
}

filter{
     mutate{
        remove_field => ["message","@version","host","path","@timestamp"]
    }
}   


output {
  elasticsearch {
    protocol => "http"
    host => localhost
    index => "myindex"
    index_type => "myindextype"
    cluster => "mycluster"
    document_id => "%{myid}"
    #port => "9200"
  }
  stdout { codec => rubydebug }
}
```

For every file containing well formed json (one json document per line), a parse failure occurs on the first line (and only the first one !). 

In fact, logstash does not read the whole line: 

{:timestamp=>"2015-06-12T11:21:44.463000+0200", :message=>"Trouble parsing json", :source=>"message", :raw=>": \"entre ....

so logically, the json document cannot be parsed : 
:exception=>#<LogStash::Json::ParserError: Unexpected character (':' (code 58)): expected a valid value (number, String, array, 
object, 'true', 'false' or 'null'

Any idea ?

Thanks a lot,
Mickael.

**Comment by mlecoq** [comment]
Ok, found it. The file was being written before launch of logstash.

**Comment by pixelatedpic** [comment]
how did you fix it?
