### ISSUE TITLE
failed to open C:/xxx/xxx.log: cannot link Java class RubyFileExt

### ISSUE THREAD

**Issue by coolzong** [elastic/logstash#3438]
When run logstash 1.5 on Windows, always meet such lines in it's log, and collect log function also fail.

**Comment by markwalkom** [comment]
What version of LS, what does your config look like.

**Comment by coolzong** [comment]
version: 1.5.0

config:
input {

  file {
    type => "TPLOG"
    path => [ "C:/TPS/TPLOG_*.log" ]
    sincedb_path => "D:/logstash/sdb_TPS.txt"
    start_position => "end"
    add_field => { "Fab" => "S1" 
                   "Location" => "TPS" }
  }

  file {
    type => "TPError"
    path => [ "C:/TPS/MESError\-*.log" ]
    sincedb_path => "D:/logstash/sdb_TPErr.txt"
    start_position => "end"
    add_field => { "Fab" => "S1" 
                   "Location" => "TPS" }
  }

}

filter {

    if [type] == "TPLOG" {
	
  		# split log
  		multiline { 
  			pattern => "\A-{60}\r\Z"
  			negate => true
  			what => "previous"
  		}
  
  		# delete the 60 dash signs
  		mutate {
  		  gsub => [
  			"message", "\-{60}\r\n", ""
  		  ]
  		}
  		
  		# delete unused separator lines
  		if  [message] =~ "\A\-+\r\Z" {
  			drop {}
  		}

  		# delete unused null lines
  		if  [message] =~ "\A\r\n\Z" {
  			drop {}
  		}
  		if  [message] =~ "\A\Z" {
  			drop {}
  		}
      
    } else if [type] == "TPError" {
    
  		# split log by header
  		multiline { 
  			pattern => "^\d{4}\-\d{1,2}\-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2} .*$"
  			negate => true
  			what => "previous" 
  		}
  
  		# delete the lastest \n of the multiline lines
  		mutate {
  		  gsub => [
  			"message", "\n\Z", ""
  		  ]
  		}
  		
      # delete unused empty lines
  		if  [message] =~ "\A\Z" {
  			drop {}
  		}  

    }

}

output {
  redis { 
    host => ["10.224.142.131", "10.224.142.132"]
    shuffle_hosts => true
    data_type => "list"
    key => "logstash"
  }
}

**Comment by coolzong** [comment]
After change into JRE1.7, the problem solved.

**Comment by markwalkom** [comment]
What version were you on previously?

**Comment by coolzong** [comment]
I run JRE1.6 because the machine resource is limited and HW config is low( just are many PC with 2G memory and 2 core cpu), and just can run client type JVM. JRE 1.6 consume less resource.

**Comment by markwalkom** [comment]
LS 1.5 doesn't support java that old.
Take a look at https://www.elastic.co/subscriptions/matrix
