### ISSUE TITLE
Grok pattern for NCSA log

### ISSUE THREAD

**Issue by JulienPalard** [elastic/logstash#3445]
I was reading [grok patterns](https://github.com/elastic/logstash/blob/v1.4.2/patterns/grok-patterns) and found your pattern to parse combined apache log
your pattern to parse combined apache log, namely the NCSA log format, does not accept spaces in the `authuser` field:

```
USERNAME [a-zA-Z0-9._-]+
USER %{USERNAME}
[...]
COMMONAPACHELOG %{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] ...
```

I read [every](https://en.wikipedia.org/wiki/Common_Log_Format) [documentations](http://httpd.apache.org/docs/2.2/mod/mod_log_config.html) [I](http://www.w3.org/Daemon/User/Config/Logging.html) [could](http://www.loganalyzer.net/log-analyzer/apache-combined-log.html) find on the subject, even [NCSA HTTPd source code](https://github.com/TooDumbForAName/ncsa-httpd/blob/master/src/http_log.c), and could _not_ find any reference of escaping, forbidding, or replacing spaces in the `authuser` field.

Yet a lot [of](http://docstore.mik.ua/orelly/webprog/pcook/ch11_14.htm) [people](http://www.java2s.com/Code/Java/Development-Class/ParseanApachelogfilewithRegularExpressions.htm) [do](http://www.perlmonks.org/?node_id=733540) [it](http://stackoverflow.com/questions/7603017/parse-apache-log-in-php-using-preg-match) [wrong](http://stackoverflow.com/questions/2221636/regex-for-apache-logs-in-php) too (starting by _me_, I personally have the habit to split my NCSA log lines on space, or use `awk`, `cut`, etc on them).

I personally thought at first I was right (to split on spaces, use awk, etc...), so I even [opened a ticket on Varnish bug tracker](https://www.varnish-cache.org/trac/ticket/1748).

I think we should open a conversation here on this subject, in one hand we either have a lot of people doing the same thing wrong, on the other hand we'll have hard times finding a clean way to encode authuser without dropping information, and convincing Apache, Microsoft, and Varnish, nginx, etc... to change their log handling code to change this...

**Comment by purbon** [comment]
@JulienPalard I think is safe, and might be better to move this issue to https://github.com/logstash-plugins/logstash-patterns-core ? where all this patterns are nowadays living, makes sense to you? can you reopen this issue there?

**Comment by JulienPalard** [comment]
Reopened here: https://github.com/logstash-plugins/logstash-patterns-core/issues/60

**Comment by purbon** [comment]
Thanks a lot man!
