### ISSUE TITLE
Logstash 1.5.0 - Can not reliably create tests for my grok patterns.

### ISSUE THREAD

**Issue by simonjohansson** [elastic/logstash#3448]
Howdie. We want to roll out 1.5, currently we are on 1.4.

We have a bunch of tests to make sure our patterns are correct but half of them are not passing with 1.5, for the sake of easy debug I have supplied a working and a failing test here(if you want my real tests and configs, please let me know). Curiously I noticed that grok matching does not work, unless the source field comes from a previous operation.

To reproduce

How I setup logstash
```
➜  ~  cd ~/src
➜  src  git clone https://github.com/elastic/logstash.git
➜  src cd logstash
➜  logstash git:(master) git checkout -b v1.5.0 v1.5.0 # I have also tried HEAD.
Switched to a new branch 'v1.5.0'
➜  logstash git:(v1.5.0) rake test:install-core
...... Lots of output...
```

My tests specs.
```
➜  logstash git:(v1.5.0) cat /tmp/logstash/working.rb 
require "spec_helper"
require "logstash/filters/grok"

describe "A working test" do
  config <<-CONFIG
    filter {
      json {
         source => 'message'
      }
      grok {
        match => {
          'foo' => '%{WORD:grokMatched}'
        }
      }
    }
    CONFIG

  sample '{"foo": "matchThisStringAsgrokMatched"}' do
    insist { subject['foo'] } == "matchThisStringAsgrokMatched"
    insist { subject['grokMatched'] } == "matchThisStringAsgrokMatched"
  end
end

➜  logstash git:(v1.5.0) cat /tmp/logstash/failing.rb 
require "spec_helper"
require "logstash/filters/grok"

describe "A non working test" do
  config <<-CONFIG
    filter {
      grok {
        match => {
          'message' => '%{WORD:grokMatched}'
        }
      }
    }
    CONFIG

  sample 'matchThisStringAsgrokMatched' do
    insist { subject['grokMatched'] } == "matchThisStringAsgrokMatched"
  end
end
```

Test output
```
➜  logstash git:(v1.5.0) ./bin/rspec /tmp/logstash/working.rb
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.

Finished in 0.258 seconds
1 example, 0 failures

Randomized with seed 44926

➜  logstash git:(v1.5.0) ./bin/rspec /tmp/logstash/failing.rb 
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
F

Failures:

  1) A non working test "matchThisStringAsgrokMatched" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "matchThisStringAsgrokMatched", but got nil
     # /tmp/logstash/failing.rb:16:in `(root)'
     # ./lib/bootstrap/rspec.rb:10:in `(root)'

Finished in 0.066 seconds
1 example, 1 failure

Failed examples:

rspec ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.13-java/lib/logstash/devutils/rspec/logstash_helpers.rb:52 # A non working test "matchThisStringAsgrokMatched" when processed

Randomized with seed 4585
```

**Comment by simonjohansson** [comment]
Ok, with help from @mrdavidlaing, I managed to sort the failing test.

adding to the top of the failing test
```
# encoding: utf-8
```

solves the issue.

**Comment by purbon** [comment]
on the other side, have you check the way to create test for patterns at https://github.com/logstash-plugins/logstash-patterns-core/blob/master/spec/patterns/mongodb_spec.rb ? this might be of help for you to make simple test.

**Comment by simonjohansson** [comment]
@purbon 
Yeah, I had a look at that, our patterns are quite big, containing multiple groks and json parsing in one big filter clause, and I would like to test the whole filter file(one filter file per "log type") in one go.

**Comment by suyograo** [comment]
@simonjohansson did adding `# encoding: utf-8` solve the problem?

**Comment by simonjohansson** [comment]
@suyograo sorry for late reply(holiday).

Yes, that is correct. Adding  ```# encoding: utf-8``` to the top of the test file solved the issue. I have not looked into why this is thought.

**Comment by purbon** [comment]
@simonjohansson where you using logstash with the embedded ruby? or using a system one? if the latest, which version? 

Thanks,

- purbon

**Comment by simonjohansson** [comment]
@purbon When I execute the tests I just use ./bin/rspec which in turn uses ${LOGSTASH_HOME}/vendor/jruby/bin/jruby

**Comment by purbon** [comment]
Makes sense then that you have to add this magic comment always, we use jruby in 1.9 mode, what means default encoding is not UTF-8, so you might need to add this special comment. In ruby 2.0 this changes, see https://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/ for more info.

Is good to always add this magic comment everywhere.

As we're done here, I will close this issue. Feel free to reopen/open a new one, in case you find more problems :smile: 

/cheers

**Comment by simonjohansson** [comment]
@purbon ah, ok, that makes sense. Thanks!
