### ISSUE TITLE
Add "Verbose" to GROK Log Level Pattern Matching

### ISSUE THREAD

**Issue by ghost** [elastic/logstash#3454]
Currently the default Grok patterns for {LOGLEVEL} does not include handling for log levels that are pushing out in Verbose (though Trace is there).

To save me just having to use the regex in the Grok pattern, it'd be great if this could be included in the default pattern.

**Comment by yair5124302** [comment]
I'd like this too.
Winston node logger have 'verbose' in it's default npm logging levels [https://www.npmjs.com/package/winston#logging-levels](https://www.npmjs.com/package/winston#logging-levels)

**Comment by kares** [comment]
Hey Yair, PRs for these are welcome.
```
{ 
  error: 0, 
  warn: 1, 
  info: 2, 
  http: 3,
  verbose: 4, 
  debug: 5, 
  silly: 6 
}
```
Looking at npm logging levels a few seem quite (`http` domain) specific (`silly` seriously? :astonished:).
Having a separate `NPM_LOG_LEVEL` might be better.

**Comment by kares** [comment]
closing - as suggested this should have been moved to the patterns tracker.
