### ISSUE TITLE
update the plugin jar dependency documentation

### ISSUE THREAD

**Issue by codekitchen** [elastic/logstash#3455]
As discussed at https://github.com/elastic/logstash/pull/2980#issuecomment-112597218 , the documentation at https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html#_jar_dependencies is now out of date with the new jar dependency vendoring method.

Ideally the new documentation would include some details about how best to get your required jars into `vendor/`, including their runtime dependencies, I'm not very familiar with the JVM or Maven so that was the most difficult part for me.

**Comment by suyograo** [comment]
Not using jar dependencies ATM
