### ISSUE TITLE
Bug with "-" : character class has '-' without escape

### ISSUE THREAD

**Issue by equinoxefr** [elastic/logstash#3456]
Hi,

I have an error logged in logstash.err since version 1.5 on Centos 6.X with official rpms.

/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.2/lib/grok-pure.rb:177 warning: character class has '-' without escape

It seems that logstash 1.5 can't handle hostnames with "-".

How can i debug this ?

Regards
Pierre

**Comment by jordansissel** [comment]
Can you show your logstash config?

**Comment by equinoxefr** [comment]
input {
udp { 
 port => 5514 ## change me to whatever you set your ASA syslog port to
 type => "cisco-fw"
 host => "172.31.112.6"
 tags => ["cisco-asa"]
 }

udp { 
 port => 5514 ## change me to whatever you set your ASA syslog port to
 type => "syslog"
 host => "172.31.112.4"
 tags => ["vcenter"]
 }

syslog {
 host => "172.31.112.5"
 tags => ["linux"]
 type => ["linux"]
}

syslog {
 host => "172.31.112.4"
 type => "esx"
 tags => ["esx"]
}

gelf {
 tags => ["windows", "gelf"]
 type => ["windows"]
}


syslog {
 host => "172.31.112.24"
 codec => 'json'
 tags => ["nxlog-win"]
 type => ["windows"]
}

lumberjack { 
port => 3333
ssl_certificate => "/etc/pki/logstash-forwarder.crt"
ssl_key => "/etc/pki/logstash-forwarder.key" 
codec => plain {
      charset => "ISO-8859-1"
}
}

}

filter {
if [type] == "nagios" {
       grok {
          match => { "message" => "%{NAGIOSLOGLINE}" }
       }

    }
if "vcenter" in [tags] {
	grok {
		break_on_match => true
		match => [
			"message", "<%{INT:syslog_pri}>%{SYSLOGTIMESTAMP} %{IPORHOST:syslog_hostname} %{TIMESTAMP_ISO8601:syslog_timestamp} (?<message-body>(?<message_system_info>(?:\[%{DATA:message_thread_id} %{DATA:syslog_level} \'%{DATA:message_service}\'\ ?%{DATA:message_opID}])) \[%{DATA:message_service_info}]\ (?<syslog_message>(%{GREEDYDATA})))",
			"message", "<%{INT:syslog_pri}>%{SYSLOGTIMESTAMP} %{IPORHOST:syslog_hostname} %{TIMESTAMP_ISO8601:syslog_timestamp} (?<message-body>(?<message_system_info>(?:\[%{DATA:message_thread_id} %{DATA:syslog_level} \'%{DATA:message_service}\'\ ?%{DATA:message_opID}])) (?<syslog_message>(%{GREEDYDATA})))",
			"message", "<%{INT:syslog_pri}>%{SYSLOGTIMESTAMP} %{IPORHOST:syslog_hostname} %{TIMESTAMP_ISO8601:syslog_timestamp} %{GREEDYDATA:syslog_message}"
			]
 		}
}
if [type] == "esx" {
	grok {
        match => ["message", "(?:%{SYSLOGTIMESTAMP:timestamp}|%{TIMESTAMP_ISO8601:timestamp8601}) (?:.* (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}|(?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}): (?:(?:\[[0-9A-Z]{8,8}) (?:%{GREEDYDATA:esxi_loglevel}) \'(?:%{GREEDYDATA:esxi_service})\'] (?:%{GREEDYDATA:message})|(?:%{GREEDYDATA:message}))"]
    }
 }
  if [type] == "cisco-fw" {
    # Split the syslog part and Cisco tag out of the message
    grok {
      match => ["message", "%{CISCO_TAGGED_SYSLOG} %{GREEDYDATA:cisco_message}"]
    }

    # Parse the syslog severity and facility
    syslog_pri { }
   # Parse the date from the "timestamp" field to the "@timestamp" field
    date {
      match => ["timestamp",
        "MMM dd HH:mm:ss",
        "MMM  d HH:mm:ss",
        "MMM dd yyyy HH:mm:ss",
        "MMM  d yyyy HH:mm:ss"
      ]
      timezone => "Europe/Paris"
    }

    # Clean up redundant fields if parsing was successful
    if "_grokparsefailure" not in [tags] {
      mutate {
        rename => ["cisco_message", "message"]
      }
    }
    grok {
      match => [
        "message", "%{CISCOFW106001}",
        "message", "%{CISCOFW106006_106007_106010}",
        "message", "%{CISCOFW106014}",
        "message", "%{CISCOFW106015}",
        "message", "%{CISCOFW106021}",
        "message", "%{CISCOFW106023}",
        "message", "%{CISCOFW106100}",
        "message", "%{CISCOFW110002}",
        "message", "%{CISCOFW302010}",
        "message", "%{CISCOFW302013_302014_302015_302016}",
        "message", "%{CISCOFW302020_302021}",
        "message", "%{CISCOFW305011}",
        "message", "%{CISCOFW313001_313004_313008}",
        "message", "%{CISCOFW313005}",
        "message", "%{CISCOFW402117}",
        "message", "%{CISCOFW402119}",
        "message", "%{CISCOFW419001}",
        "message", "%{CISCOFW419002}",
        "message", "%{CISCOFW500004}",
        "message", "%{CISCOFW602303_602304}",
        "message", "%{CISCOFW710001_710002_710003_710005_710006}",
        "message", "%{CISCOFW713172}",
        "message", "%{CISCOFW733100}"
      ]
}
geoip {
source => "src_ip"
target => "geoip"
add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}" ]
}

mutate {
convert => [ "[geoip][coordinates]", "float" ]
}  
  }
}
output {
elasticsearch { embedded => "false" cluster => "syslog01" }
#if  "vcenter" in [tags] {
#stdout { codec => rubydebug }
#  }
}

**Comment by jordansissel** [comment]
> warning: character class has '-' without escape

This message is because of one your grok patterns, not because of a hostname being processed by grok.

In plain ruby, I can cause your warning by using simply this as a regexp `[--]`:

```
>> /[--]/
(irb):4: warning: character class has '-' without escape: /[--]/
```

I'm not sure which of your grok patterns is causing it, or if one of the standard patterns we ship causes this. Hope this helps.

**Comment by suyograo** [comment]
Hi @equinoxefr moving forward, can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
