### ISSUE TITLE
License report

### ISSUE THREAD

**Issue by mrsolo** [elastic/logstash#3468]
See 

https://github.com/elastic/elasticsearch/issues/10684

> We should go through all the third party dependencies that we redistribute and make sure 
> NOTICE.TXT has all the info needed to comply with the license terms of the dependencies.

Similar information is required for logstash project

**Comment by suyograo** [comment]
@mrsolo can i close this for https://github.com/elastic/logstash/issues/3453?

**Comment by mrsolo** [comment]
@suyograo yes please
