### ISSUE TITLE
logstash is not processing most of the gelf messages

### ISSUE THREAD

**Issue by achechen** [elastic/logstash#3471]
Hello there,

I have a 2 node logstash cluster receiving 3000 messages per second on average. I have just noticed that it is not processing all the messages it receives - they are lost somewhere (UDP packets are coming in but logstash seems to be ignoring them). I am using nxlog and sending logs in gelf format through UDP. Logstash input config looks like this:

gelf {
port => 12205
type => windows
codec => "json" }

gelf {
port => 12201
type => windows
codec => "json" }

12201 is the main port I am using where hundreds of Windows servers are sending eventlogs while input with port 12205 was created for troubleshooting purposes. I'll explain why.

I picked up one server and compared the logs in the eventlog and logs that are in elasticsearch and found out that most of them never reached elasticsearch (checked with standard output to rule out any issues with elasticsearch).

I manually created test events on that server and set up standard output on logstash to capture them. Most of the events never showed up on the screen (only 1 out of 10 showed up).

Then I decided to create a second gelf input with port 12205 (while keeping port 12201 open and hundreds of servers still sending logs) and did not experience any message loss. The problem is, I have to use one port and cannot afford splitting servers between different ports.

Any idea why this is happening and what should I do to remedy this? I appreciate your help.

**Comment by untergeek** [comment]
If this is a GELF specific error or issue, please open the ticket at https://github.com/logstash-plugins/logstash-input-gelf

If it's a general question about performance or configuration, please ask your question at https://discuss.elastic.co/c/logstash

With those said, I can tell you that the UDP socket reader being used by the gelf input plugin is single-threaded.  When I was trying to capture UDP collectd packets, I found that I could only manage, at most, around 3150 events per second.  UDP is fire and forget.  If Logstash is unable to ingest fast enough for any reason, the messages not ingested will simply drop.  We have a new UDP input plugin that is multithreaded and has a buffer/queue to keep messages from dropping.  It sounds like use cases like this would benefit from having a GELF _codec_ which the regular UDP input plugin can use.

**Comment by achechen** [comment]
Yes, I have noticed that gelf plugin is single threaded and logstash is simply cannot consume everything, which is frustrating. I guess I am going to have to use redis or Rabbit to queue messages. Also, UDP input with gelf codec sounds a good idea. Thanks a lot. I will try my chance in gelf input page.

**Comment by untergeek** [comment]
Closing in lieu of https://github.com/logstash-plugins/logstash-input-gelf/issues/13

**Comment by achechen** [comment]
Ok, I have changed the input to regular UDP, I can see 3 separete UDP input threads when I check but this did not fix the issue :(

Recv-Q of the input port is full:

[~] # netstat -c --udp -an | grep 12201
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address               Foreign Address             State
udp   124576      0 :::12201                    :::*
udp   124576      0 :::12201                    :::*
udp   126408      0 :::12201                    :::*
udp   126408      0 :::12201                    :::*
udp   126408      0 :::12201                    :::*
udp   126408      0 :::12201                    :::*
udp   126408      0 :::12201                    :::*

And udp packets are being dropped:

[~] # netstat -su
IcmpMsg:
    InType3: 9
    InType8: 1158
    OutType0: 1158
    OutType3: 141095
Udp:
    2884374 packets received
    145933340 packets to unknown port received.
    182791377 packet receive errors
    2631285 packets sent
UdpLite:
IpExt:
    InMcastPkts: 3
    InBcastPkts: 9425
    InOctets: 485111308743
    OutOctets: 2879422218
    InMcastOctets: 108
    InBcastOctets: 1000368

Tried increasing CPU, did not change anything. When I decrease the number of incoming messages, the queue clears up and everything is processed.

**Comment by achechen** [comment]
Ok, I have changed the input to regular UDP, I can see 3 separete UDP input threads when I check but this did not fix the issue :(

Recv-Q of the input port is full:

[~] # netstat -c --udp -an | grep 12201
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State
udp 124576 0 :::12201 :::*
udp 124576 0 :::12201 :::*
udp 126408 0 :::12201 :::*
udp 126408 0 :::12201 :::*
udp 126408 0 :::12201 :::*
udp 126408 0 :::12201 :::*
udp 126408 0 :::12201 :::*

And udp packets are being dropped:

[~] # netstat -su
IcmpMsg:
InType3: 9
InType8: 1158
OutType0: 1158
OutType3: 141095
Udp:
2884374 packets received
145933340 packets to unknown port received.
182791377 packet receive errors
2631285 packets sent
UdpLite:
IpExt:
InMcastPkts: 3
InBcastPkts: 9425
InOctets: 485111308743
OutOctets: 2879422218
InMcastOctets: 108
InBcastOctets: 1000368

Increased queue_type gradually to 1,000,000 to see if the UDP receive queue is getting cleared, not really...

**Comment by untergeek** [comment]
Please direct your comments to https://github.com/logstash-plugins/logstash-input-gelf/issues/13 as this issue is closed.

**Comment by lequyan** [comment]
Hi,
I'm having the same problem and wonder how to set GELF codec for UDP plugin. Is this something still in development? 

Thanks

**Comment by tarp2699** [comment]
Hi,
I'm seeing the same issue with the gelf plugin.  Is this new multithreaded release planned, is it out there?  I'm running, logstash 2.3.4.
Thanks,
