### ISSUE TITLE
Logstash fails to startup: rubyjit error

### ISSUE THREAD

**Issue by chris-david-taylor** [elastic/logstash#3480]
Hi guys,
I'm wondering if someone can help me.  I'm trying to install an ELK stack on a production machine, and during startup, logstash seems to continually do this:

[Loaded org.jruby.ext.openssl.Utils from file:/opt/logstash/vendor/jruby/lib/ruby/shared/jopenssl.jar]
[Loaded rubyjit$#<Module:0xaa7e604>$$normalize_key_62a82f4a26b627393d03ebd39bbfeb26d9821b65361149577$block_1$RUBY$__file__ from __JVM_DefineClass__]
The error reported is: 
  No message available

Running on a pretty clean VirtualBox instance I don't seem to have any issues, so I'm inclined to think the state of the OS install is the problem. Any suggestions on what I can do at this point before a clean install?  
I'm running on RHEL 6.6 x64, logstash-1.5.0-1 and java-1.7.0-openjdk-1.7.0.79-2.5.5.3.

Thanks,
Chris.

**Comment by chris-david-taylor** [comment]
Ah, as an update, I spotted this in the verbosity:

[Loaded rubyjit.Module$$method_missing_20d62b1d61b0eb3b2fb0311f0452a847295bc436361149577 from __JVM_DefineClass__]

**Comment by chris-david-taylor** [comment]
Hm,
Interestingly the issue is repeatable with logstash-1.4.3
The very same "No message available" verbose is spat out.  Since then, we have reprovisioned the VM.  Are there any quirks, however minor, that might manifest in a VMWare environment?

**Comment by chris-david-taylor** [comment]
Hi Suyograo,
Thanks for adding the label but this is a 'bug' not a question.  I've gone through as much as much trouble shooting as possible.  Frustratingly, apart from the above, there is no other verbosity to debug.  I suppose the next port of call would be to investigate modifying JVM parameters.

Cheers,
Chris.

**Comment by chris-david-taylor** [comment]
Anyone?

**Comment by tuukkamustonen** [comment]
No ideas, but at the moment I'm getting similar stdout+stderr of:

    '[DEPRECATED] use `require 'concurrent'` instead of `require 'concurrent_ruby'`
    [2015-08-07 11:51:21.861]  WARN -- Concurrent: [DEPRECATED] Java 7 is deprecated, please use Java 8.
    Java 7 support is only best effort, it may not work. It will be removed in next release (1.0).
    The error reported is: 
      No message available

Running OpenJDK 7 + Logstash 1.5.3.

I tried to draw more logging with:

      stdout {
        codec => rubydebug
      }

But I'm only getting these in the log:

    {:timestamp=>"2015-08-07T11:41:17.382000+0000", :message=>"The error reported is: \n  No message available"}

It works on another machine with Oracle Java 8. The installations should be similar, there should not be any difference.

**Comment by chris-david-taylor** [comment]
Hi tuukkamustonen,

In my case I found that I needed to generate a new SSL certificate.  I ended up running the whole Java command on the shell and captured X509Certificate errors.  I don't think this is your problem though. You are running Logstash 1.5.3 which is newer so maybe there is a specific preference for Java 8 - I haven't validated yet, but the verbosity you posted suggests it might.  Can you try it out with OpenJDK 8?

Let me know how you get on and I'll help you out if I can.

**Comment by tuukkamustonen** [comment]
Howdy @chris-david-taylor. I will try another java version, but it's not as easy as it may sound, because the malfunctioning machine is behind a corporate proxy and I have to practically beg for access to other than default reports (probably even backports)...

And true, it's probably different error. At least the common nominator is the vagueness of the actual error - although I'm not getting any hints at all, just that "No message available".

What was the actual problem for you? Did re-creating SSL cert help?

**Comment by chris-david-taylor** [comment]
My problem was specifically SSL related and recreating the Cert resolved it.  Looking at your verbosity, I would suspect it never gets as far as logging anything meaningful because the Java application that would log never starts up - at stderr/stdout its complaining about needing a newer Java 8; OpenJDK8 

Yes, I know your pain when it comes to corporate policies.  Is downgrading to logstash-1.5.0 a possibility?  That definitely works with OpenJDK 7.   I'll replicate your setup in a VM on Monday and see if I can duplicate your issue.  Can I ask, what is the exact version of your OS?

**Comment by tuukkamustonen** [comment]
@chris-david-taylor Sorry for the delay, but only today I got back to this.

And oh man it was a stupid mistake - also my SSL certs were invalid. Actually, my SSL cert files contained garbage, I mean, completely invalid.

Java version did not have effect on this. As the message states, OpenJDK 7 support is "best effort" - logstash still tries to run (and seems to work also). I've been running Debian wheezy.

Still, what needs to be done here is to *improve logging*. At least you got some hint about the problem - I didn't get anything (else than what I pasted above).

Thanks for the help on the issue - I hope you did not find time to replicate the setup? :)

**Comment by chris-david-taylor** [comment]
Hey, glad you got your problem solved.  Ah, its not a mistake, we make 'happy accidents' :)
I agree with you there, I got "No message available" at first, I had to run the java command separately in a terminal to get that.

**Comment by tuukkamustonen** [comment]
Then, what stream is the logging missing? As there's stdout and stderr being captured into separate files already (plus the actual .log file), what was the difference when you ran the command manually?

**Comment by suyograo** [comment]
Please reopen the issue if this still happens
