### ISSUE TITLE
Logstash Stalls

### ISSUE THREAD

**Issue by jlintz** [elastic/logstash#3481]
Since we've upgraded to 1.5.1 from 1.4.x we've been seeing random logstash stalls.  There is nothing in the logs before it happens but then we start seeing

```
{:timestamp=>"2015-06-22T08:14:46.087000-0400", :message=>"The error reported is: \n  Address already in use - bind - Address already in use"}
```

The only other error we've seen is
```
{:timestamp=>"2015-06-22T09:57:55.079000-0400", :message=>"Exception in lumberjack input thread", :exception=>#<ArgumentError: comparison of String with 1 failed>, :level=>:error}
```
but not sure if its related

Here are a couple of stack traces

https://gist.github.com/jlintz/200442667e07cc500ed0

**Comment by ph** [comment]
Thanks for the report @jlintz could you include your configuration and the result of `bin/plugin list --verbose` in a gist?

**Comment by jlintz** [comment]
@ph here you go https://gist.github.com/jlintz/45c12c1190d130e14b67 ,thanks, let me know if there is anything else you need

**Comment by ph** [comment]
@jlintz Did you use cmd `jstack <PID>` to create the thread dump?

**Comment by jlintz** [comment]
@ph yes, with -F flag IIRC

**Comment by ph** [comment]
Can you check the elasticsearch side? Do you see any errors in the logs?

**Comment by ph** [comment]
@jlintz Could you rerun it without the `-F` flag, this flag remove some information from jruby :(

**Comment by jlintz** [comment]
@ph no errors besides our issues with field datatype mismatches , I'll try and grab another jstack next time it happens without -F, knock on wood its been stable the last couple of days, thanks!

**Comment by ph** [comment]
@jlintz I'll close this one, if this issue ever happen to you feel to reopen or create a new one!
