### ISSUE TITLE
Logstash 1.5.1 : logstash can't send json that contains "lists"  to mongoDb

### ISSUE THREAD

**Issue by inptensib** [elastic/logstash#3482]
Hi everybody ! I am trying to insert a json in mongoDb using Logstash-output-mongodb plugin.The json objects contain arrayLists fields so i'm getting this exception:
NoMethodError: undefined method `bson_type' for #Java::JavaUtil::ArrayList:0x745ad733,
I am using logstash 1.5.1.Thank you !!!

**Comment by inptensib** [comment]
This is an example of  simple json that i want insert :
{"name":"aaaaaa",
"email":"aaaaaa@aaaa.com",
"Date":"Jun 25, 2015 10:04:10 AM",
"List":["chaine1","chaine2"]
}

**Comment by RyouZhang** [comment]
i have the same question. 
using logstash-output-mongodb-v2 and logstash-1.5.3

**Comment by RyouZhang** [comment]
NoMethodError: undefined method `bson_type' for #<Java::JavaUtil::LinkedHashMap:0x57eec9d2>
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/hash.rb:44
                              each at org/jruby/RubyHash.java:1341
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/hash.rb:43
  encode_with_placeholder_and_null at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/encodable.rb:57
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/hash.rb:42
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/array.rb:49
                              each at org/jruby/RubyArray.java:1613
                   each_with_index at org/jruby/RubyEnumerable.java:978
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/array.rb:46
  encode_with_placeholder_and_null at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/encodable.rb:57
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/array.rb:45
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/hash.rb:46
                              each at org/jruby/RubyHash.java:1341
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/hash.rb:43
  encode_with_placeholder_and_null at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/encodable.rb:57
                           to_bson at /opt/app/logstash-1.5.3/vendor/local_gems/79927e7d/bson-3.2.0/lib/bson/hash.rb:42
                         serialize at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/protocol/serializers.rb:155
                  serialize_fields at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/protocol/message.rb:153
                              each at org/jruby/RubyArray.java:1613
                  serialize_fields at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/protocol/message.rb:141
                         serialize at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/protocol/message.rb:70
                             write at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/server/connection.rb:123
                              each at org/jruby/RubyArray.java:1613
                             write at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/server/connection.rb:122
                          dispatch at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/server/connectable.rb:66
                               log at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/loggable.rb:44
                         log_debug at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/loggable.rb:67
                          dispatch at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/server/connectable.rb:65
                           execute at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/operation/executable.rb:35
                   with_connection at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/server/connection_pool.rb:99
                   with_connection at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/server/context.rb:63
                           execute at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/operation/executable.rb:34
             execute_write_command at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/operation/write/insert.rb:72
                           execute at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/operation/write/insert.rb:62
                       insert_many at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/collection.rb:190
                        insert_one at /opt/app/logstash-1.5.3/vendor/local_gems/14d195b4/mongo-2.0.6/lib/mongo/collection.rb:175
                           receive at /opt/app/logstash-1.5.3/vendor/local_gems/ba369f31/logstash-output-mongodb-v2-0.2.2/lib/logstash/outputs/mongodb.rb:65
                            handle at /opt/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88
                      worker_setup at /opt/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:79

**Comment by RyouZhang** [comment]
json data: {"poi":[116.48063456132, 40.006281942295]}
logstash log:
{"poi"=><Java::JavaUtil::ArrayList:-2033510418 [116.48063456132, 40.006281942295]>

**Comment by deepvoice** [comment]
Using: logstash-1.5.3
data schema = 
{ main: { data:data child1: { data:data child2: { data:data }}}}
Getting same error. Also getting-
NoMethodError: undefined method `error_code' for #<NoMethodError:0x5ea4300e>
       receive at /local/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-mongodb-0.1.4/lib/logstash/outputs/mongodb.rb:60
        handle at /local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88
  worker_setup at /local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:79

**Comment by jhitze** [comment]
The riemann output is having this issue too :( 

https://github.com/logstash-plugins/logstash-output-riemann/issues/9

**Comment by vaidas-lungis** [comment]
+1
Having same issue with output MongoDb plugin and logstash 1.5.4

**Comment by jordansissel** [comment]
Agreed this looks like a bug.

**Comment by makarchuk** [comment]
Is there any way to work with logstash and mongo at the moment? 
My best Idea is put elements in redis and use standalone script to take them from redis to mongo but this looks really stupid.

**Comment by purbon** [comment]
@makarchuk you could check https://github.com/logstash-plugins/logstash-output-mongodb does what you expect.

**Comment by makarchuk** [comment]
@purbon, it's not since my events has pretty complicated structure with lots of  hashes and I'm getting exactly same error message as @inptensib

**Comment by guyboertje** [comment]
I am closing this. Moving discussion to the plugin issue - https://github.com/logstash-plugins/logstash-output-mongodb/issues/9
