### ISSUE TITLE
Logstash input for Cloudwatch

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#3483]
We need an input to read logs directly from AWS CloudWatch.

Should be similar to https://github.com/logstash-plugins/logstash-output-cloudwatch.

**Comment by ggeligible** [comment]
How about https://github.com/lukewaite/logstash-input-cloudwatch-logs??

**Comment by timbunce** [comment]
See also #3437.

**Comment by suyograo** [comment]
Dup of https://github.com/elastic/logstash/issues/3437

**Comment by bob22233** [comment]
This is not a dupe of #3437 as that one is purely about metrics, and not about logs.  You can not for example obtain VPC flow logs from logstash-input-cloudwatch which is why logstash-input-cloudwatch-logs is needed.

**Comment by marek-obuchowicz** [comment]
@suyograo can you please re-open it? It's NOT dupe of #3437
