### ISSUE TITLE
Logstash hangs after startup

### ISSUE THREAD

**Issue by PavanRGowda** [elastic/logstash#3487]
I'm trying to add data from csv file into my elasticsearch. And below is my configuration file - 

input {  

      file {

          path => "/home/pavan/Downloads/sample.csv"
          type => "core2"
          start_position => "beginning"
      }

}

filter {  

    csv {

        columns => ['cdatetime', 'address', 'district', 'beat', 'grid', 'crimedescr', 'ucr_ncic_code', 'latitude', 'longitude']
        separator => ","

    }

}

output {  

    elasticsearch {
	
        action => "index"
        host => "localhost"
	protocol => "http"
	index => "logstash-%{+YYYY.MM.dd}"        
    }

    # stdout {
    #     codec => rubydebug
    # }

}

When I run logstash with the following command 
                                                   bin/logstash -f sample.conf
I just get the message
                                                   Logstash startup completed
and nothing is getting indexed into elasticsearch.

**Comment by markwalkom** [comment]
This isn't a bug, LS won't display anything there unless you either use stdout or if it encounters an error.

Please join us in #logstash on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)
