### ISSUE TITLE
logstash-output stalls when using HTTP/JSON-POST and Status 204 is send back

### ISSUE THREAD

**Issue by rogerthat** [elastic/logstash#3488]
we're using Logstash-Output to send JSON to a REST-API, and the API answered with Status 204 when processing is OK. When we do this, the LS-Output stalls and stops processing/output for approx 30 seconds (we have on avg 2000 events/second process by different Logstash-workers). when we change the Status to "200" processing works as expected.. 

> https://www.elastic.co/guide/en/logstash/current/plugins-outputs-http.html
> https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success

**Comment by duylong** [comment]
I have the same issue here: https://github.com/logstash-plugins/logstash-output-http/issues/6

**Comment by suyograo** [comment]
We've added retries to HTTP output. Let's follow up in that repo.
