### ISSUE TITLE
New filter plugin: HTTP Rest

### ISSUE THREAD

**Issue by lucashenning** [elastic/logstash#3489]
Hi guys,
I've created a new logstash filter plugin which can be used to handle complex rest calls. It supports custom headers and parameters as well as the logstash sprintf format to use event fields as configuration values.

Sample config:

``` sh
rest {
  url => "http://example.com"       # string (required, with field reference: "http://example.com?id=%{id}")
  json => true                      # boolean (optional, default = false)
  method => "post"                  # string (optional, default = "get")
  sprintf => true                   # boolean (optional, default = false, set this to true if you want to use field references in url, header or params)
  header => {                       # hash (optional)
    "key1" => "value1"
    "key2" => "value2"
    "key3" => "%{somefield}"        # Please set sprintf to true if you want to use field references
  }
  params => {                       # hash (optional, only available for method => "post")
    "key1" => "value1"
    "key2" => "value2"
    "key3" => "%{somefield}"        # Please set sprintf to true if you want to use field references
  }
}
```

Github: https://github.com/lucashenning/logstash-filter-rest
RubyGems: https://rubygems.org/gems/logstash-filter-rest

I use it to gather environment information and to obtain a public encryption key for each event but I think there are several use cases. Currently the test makes sure that a json rest call works as expected.

Feedback and suggestions are most welcome.

**Comment by bradvido** [comment]
:+1: Looks great. Definitely something we could use to inject or enrich with extra data from a webservice. Filter is probably a misnomer, but that's what logstash calls everything between the inputs and outputs, so what can you do :)

**Comment by elvarb** [comment]
I have been longing for this plugin for so long! 

My expanded idea is to use the heartbeat input plugin to trigger this plugin to run. That way you can have logstash for example query http api's at an interval. 

Get rabbitmq queue stats every minute. Use conditions to send alerts. 

Get elasticsearch health stats every minute. 

Query just about any api at an interval to ingest into ELK! 

Does it support authentication?

**Comment by lucashenning** [comment]
Hi @elvarb,
the plugin does support authentication. You can use the http basic auth url format (e.g. `http://user:pass@example.com`) or you can pass an authorization header with a base64 encoded password.
You might also consider looking at the new [logstash-input-http_poller](https://github.com/logstash-plugins/logstash-input-http_poller) plugin and its integrated interval function.

**Comment by kevinyan815** [comment]
I recently use logstash-filter-rest, and configure it like below:

rest {
    url => "http://example.com/api"
    sprintf => true
    method => "post"
    params => {
      "post_key" => "%{a_field_in_log}"
    }
    response_key => "my_key"
}
after this, logstash make a post request to my api, but something is wrong, the value of a_field_in_log is identical in every request ( I check api access log, all of the value is the first  "a_field_in_log" value sent to api ) it seems like there have caches for referenced field.

Have you ever encountered same problems?

**Comment by acchen97** [comment]
@lucashenning hello there Lucas. Thanks for being an awesome member of the Logstash community.

As there's quite a bit of value in this plugin, it'd be great to further surface it for the whole community. If you were still interested in contributing it to the logstash-plugins repo with documentation on elastic.co, please send me an email at alvin@elastic.co. We'd be happy to have you continue owning and maintaining it either way. :)

Thanks!

**Comment by lucashenning** [comment]
Hi @acchen97 thanks much for your message. Nice to hear that this plugin actually gets some attention of the community. Sure, I'd love to have the plugin listed on elastic.co. I don't have much time to maintain it currently but there's other contributors, too. 
I sent you an email.

**Comment by gandalfb** [comment]
Hi @lucashenning and @acchen97,
this is great to hear. Do you have any update?
Thanks!

**Comment by alp-java** [comment]
Hi @lucashenning!
This plugin seems exactly what I'm looking for to add to the project I'm working on. However, I have an issue trying to install it. I can't use `logstash-plugin install <name>` command due to the firewall settings and logstash-install expects *.zip archive(on Windows) when I tried to install it manually by downloading a *.gem file from rubygems.org. However, I couldn't find a zip version of the plugin anywhere.

Can you suggest any solution/workaround for this issue? I am a Java developer and I don't know Ruby at all, so I will appreciate any feedback. Thanks!

**Comment by seanziee** [comment]
I'm in full support of this! I want to do a lookup on facebook's api for certain events and this is very helpful for that!

**Comment by melvynator** [comment]
I think this plugin is great and allows indeed to do look up on external APIs for data enrichment.
Any update on this @acchen97 @lucashenning ?

**Comment by fbaligand** [comment]
I can only agree with Melvyn!

**Comment by lucashenning** [comment]
Thanks @melvynator @fbaligand - I haven't updated this plugin in a while but I'm happy that it's still helpful. @acchen97 I know that we had a conversation about this a year ago but could you jog my memory on the next steps to make this an official plugin? Thanks everyone for supporting this. Especially @gandalfb who contributed a lot on updates and bug fixes.

**Comment by fbaligand** [comment]
Hi @lucashenning !

Happy to see that you’re motivated to make http filter, an official Logstash plugin!

The steps are the following :
- first open an issue on elastic/logstash repository to ask to create logstash-plugins/logstash-filter-http repository (reference your existing repo)
- a logstash core member will create the repo
- then open a PR on this repo to add all your code
- for the doc, you could ask that a core member generates the initial doc (docs/index.asciidoc), using your code. Then you can make a PR to add explainations and samples. 

If you have more questions, don’t hesitate :)

**Comment by fbaligand** [comment]
And yes, you already made the first step :)

**Comment by fbaligand** [comment]
@jsvd @suyog @ph
Could you create the GitHub repository on logstash-plugins ?

**Comment by acchen97** [comment]
@fbaligand @melvynator @alp-java @gandalfb @kevinyan815 @bradvido thanks for all your feedback and interest. We appreciate your patience.

To better understand the lookup coverage this plugin could provide, do you mind elaborating on your particular use cases for this? In particular: 
1. What type of data you're pulling from the HTTP endpoint to enrich with
2. What type of events/fields you are planning to enrich

**Comment by gandalfb** [comment]
Hi @acchen97, as I changed field of work a year ago, I am a bit rusty.

But the main usecase was to send a http request with a given `rest` request and receive the response.

See example:
```sh
bin/logstash --debug -e 'input { stdin{} } filter { rest { request => { url => "https://jsonplaceholder.typicode.com/posts" method => "post" body => { "userId" => "%{message}" } headers => { "Content-Type" => "application/json" } } target => 'rest' } } output {stdout { codec => rubydebug }}'
```

With this you may i.e. take an IP address and enrich it with a `json` response to a given key or any other metadata you need to enrich your event with.

Clearly, the main usecase at my time was `json`

Hope this helps and thanks for the effort.

**Comment by fbaligand** [comment]
Hi Alvin,

To me, an http filter is as useful as elasticsearch filter or jdbc filter. It lets to enrich an event using an external http service. 

An example of use is calling a http business service that provides referential data. 
So for example, you have a service that provides data on products. You have an event which contains a product id, you call the http service with the id to get product details and you store product details into event.

**Comment by fbaligand** [comment]
Then, at a recent Elastic Meetup in Paris, @melvynator used the rest filter to call a sentiment analysis http service.
Its pipeline takes a Twitter input, and then uses the sentiment analysis service to tag the event as positive, negative or neutral.

**Comment by melvynator** [comment]
@acchen97 It can be used in a lot of use cases. Simple look up to filter event or even in a data science use case.

<img width="1104" alt="pipeline-2" src="https://user-images.githubusercontent.com/5473562/44403253-4f11a000-a597-11e8-94ad-4e737f816fe2.png">

You can find an example pipeline here: https://github.com/melvynator/ELK_twitter

**Comment by lucashenning** [comment]
Any update on this? @fbaligand @melvynator @acchen97

**Comment by test1230321** [comment]
How to pass JSON or XML input value as below through body filed in logstash
{
   "param1": {
          "param2": {
                "param3": "value"
           }
}

**Comment by melvynator** [comment]
I think this is closing this issue right? https://www.elastic.co/guide/en/logstash/6.6/plugins-filters-http.html

**Comment by fbaligand** [comment]
Yes!
Like @melvynator, the new http filter fulfills perfectly this issue!

@lucashenning @jsvd 
Could you close the issue?

**Comment by acchen97** [comment]
Yes, the new HTTP filter plugin is now officially out. Many thanks to @lucashenning for the original work on the plugin and appreciate all the feedback from the broader community. :)

https://github.com/logstash-plugins/logstash-filter-http
