### ISSUE TITLE
Logs "exception" missing without a restart

### ISSUE THREAD

**Issue by duylong** [elastic/logstash#3492]
Hi,

Some logs are only written on disk after a restart. For example, I have this problem with log message "Exception in filterworker".

I use Logstash 1.5.1. Do you know this issue ?

Best regards,

**Comment by suyograo** [comment]
@duylong can you provide more info regarding your setup? whats the config? can you send us sample data.. also you can ask these questions in https://discuss.elastic.co/c/logstash

**Comment by duylong** [comment]
Just create a exception in ruby filter ;)

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
