### ISSUE TITLE
Fold plugin script into logstash or rename

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/logstash#3498]
Both Elasticsearch (elastic/elasticsearch#11797) and Kibana (elastic/kibana#4204) are moving plugin functionality into the main elasticsearch and kibana script, respectively. One of the main reasons for this is to be a better Linux citizen and allow downstream distribution packaging without name clashes (eg. in the current Fedora Elasticsearch package they can't ship the plugin script). Should logstash follow suit, or at least rename plugin to logstash-plugin?

**Comment by suyograo** [comment]
@jimmyjones2 thanks for the issue. Makes sense to be consistent. We can do `bin/logstash plugin command [plugin_name]`

**Comment by suyograo** [comment]
Fixed in #4871
