### ISSUE TITLE
Standardize on http client libraries used in Logstash

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3500]
Today we have multiple http client libraries used in Logstash (and its plugins) that need http transport functionality. For example:

* [ruby-ftw](https://github.com/jordansissel/ruby-ftw) is used in logstash-output-http
* [jruby-manticore](https://github.com/cheald/manticore) is used in ES output

Do we need to standardize on one library, or should we use Faraday which allows pluggable backends? Standardizing would provide consistent configurations across the board. More importantly it provides us the knowledge to fix bugs, add features like security, control timeout settings etc rapidly. 

Manticore has better performance, but works only on JRuby -- so should we be using this for all plugins? Thoughts?

**Comment by andrewvc** [comment]
I took another look at Faraday today, and while I like the project (I recommended it to @suyograo), I'm a little worried that it isn't maintained as well as it used to be. They seem to have an issue backlog. Additionally, Faraday doesn't abstract away some client specific things like client timeout values (those aren't normalized between backends) and it doesn't support async as nicely as manticore.

I believe that manticore is the most sensible way forward for a few reasons:

1. A good interface
2. Great async support without external depencies
3. Completeness
4. Speed

I'm currently using it on https://github.com/logstash-plugins/logstash-input-http-poller without Faraday.

**Comment by untergeek** [comment]
Let's not forget [net/http](https://github.com/logstash-plugins/logstash-input-couchdb_changes/blob/master/lib/logstash/inputs/couchdb_changes.rb#L5).  The only reason I didn't use ruby-ftw is because the JRuby had SSL issues.

**Comment by jordansissel** [comment]
JRuby still has SSL issues, mostly related to IO::select; I ran into a few of them yesterday (IO::select doesn't work correctly on OpenSSL::SSL::SSLSocket, it's been on my todo list to help fix, but not made time yet)

**Comment by andrewvc** [comment]
@jordansissel given that Manticore uses apache commons and does not depend on ruby SSL stuff might that be another plus for Manticore and future java plugins?

**Comment by jordansissel** [comment]
@andrewvc +1 on that, but if we choose Manticore, we're left with an http client choice that doesn't work on MRI, right?

**Comment by andrewvc** [comment]
@jordansissel that is true, but it was my impression that we were slowly moving toward strongly encouraging java as a runtime. I apologize if that's incorrect.

It seems to me that there's a benefit given our java emphasis on embracing Java based gems. It's been the case for me that MRI first gems can have more issues on Jruby.

Additionally, as @suyograo pointed out, the ES output is essentially Java only due to its use of Manticore, and it doesn't seem that there are any complaints there.

**Comment by jordansissel** [comment]
@andrewvc yeah I don't know if we've decided to not care about MRI - we had been making progress towards more-strongly supporting MRI in the last 6 months. I'm OK if we change direction, but want to make sure everyone's on the same page about actively moving away from MRI.

**Comment by suyograo** [comment]
We recently ran into JRuby issues while trying to validate SSL functionality (with ruby-ftw lib) in [logstash-output-http](https://github.com/logstash-plugins/logstash-output-http/tree/feature/ssl-configuration). Given this, I am strongly inclined for us to rewrite this plugin using Manticore as the client lib

**Comment by jordansissel** [comment]
Given the java core work that we're doing, I think it's safe to move to manticore.

As an aside, I am _extremely_ interested in fixing these SSL bugs in JRuby, so I'm making a note on my todo list to come back to it eventually. Related https://github.com/jruby/jruby/issues/2195

**Comment by andrewvc** [comment]
There was a sidebar conversation about ca_file support in hipchat. After looking into it, Manticore supports both .jks and x.509 PEM files: https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L571

**Comment by suyograo** [comment]
Manticore it is.
