### ISSUE TITLE
Add documentation to describe offline plugin install

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3501]
We added ability to install plugins offline in https://github.com/elastic/logstash/pull/3404 and there are changes to CLI that needs to be documented. 

https://www.elastic.co/guide/en/logstash/current/_command_line_flags.html

**Comment by suyograo** [comment]
@purbon can you give me a blob for this describing all the new commands. I'll stick it into the reference docs

**Comment by suyograo** [comment]
* ```bin/plugin package``` to build the cache of current installed plugins.
* ```bin/plugin package --zip``` to compress the dump as a zip file.
* ```bin/plugin package --tgz``` to compress the dump as tar.gz file.
* ```bin/plugin package --clean``` to cleanup the raw, not compressed dump.    
* ```bin/plugin unpack [file]``` to unpack a package file. 
* ```rake package:build-cache``` build a cache with the current installed plugins.
* ```rake package:plugins-default``` build a cache with default plugins on it, installing them if not there.
* ```rake package:plugins-all``` build a cache with all plugins on it, installing them if not there.

**Comment by purbon** [comment]
Here are my thoughts on it:

* I would not expose the rake tasks, as they are not going to be exported in the deliverables do provide not much of benefit to the end user.

* During the reviews I changed the name of the ```package``` command to ```pack```, so it's uniform with ```unpack```, but as I said in https://github.com/elastic/logstash/pull/3404#issuecomment-115170656 I forget to update the explanation, apologies for that. I would update the naming.

Speaking about the different options I would add a few things:

* (Add as a request of reviewer) : ```--tgz``` is the default for non windows environments, while ```--zip``` is the default for windows. (```pack``` and ```unpack``` behave the same)
* ```--clean``` is now default true. There is an option to run ```--no-clean``` to skip it.
* There is a new option named ```--force``` used to override (default false). This option is available in ```pack``` and ```unpack```.

I'm not sure if I would add the expected workflow to follow, does this makes sense? just in case you aim to added, this is the expected workflow:

* Pack all plugins + dependencies in a LS with internet connection. This generate a ```.tar.gz``` or a ```.zip`` file.
* Move this file around to the machines without internet.
* Foreach machine without internet, run ```bin/plugin unpack``` to install the plugins dump into logstash.

Then using, ``` bin/plugin install --local```  or  ```bin/plugin update --local``` will fetch stuff from the local source. 

Does it makes sense?

**Comment by palecur** [comment]
Closed in PR #4230.
