### ISSUE TITLE
 Events/logs_1m metrics seen at graphite end @ high very values, with no actual input given.

### ISSUE THREAD

**Issue by suraj-kamath** [elastic/logstash#3502]
Hi ,
     I have been trying out obtaining useful metrics from my logs/events from logstash. For this i have been testing with a sample logstash configuration file , with the input as generator plugin and the same is sent to graphite via statsD output plugin of logstash. Although I can see the file to be executing very well , and the metrics plots on graphite , the graphs doesn't seem to relate to the file inputs.

By this I mean i am not able to understand the nature of generator plugin as well as the statsD used together .

Please find the metric graphs attached. My test logstash configuration (example.conf) is as below:

input {
  generator {
    type => "generated"
  }
}
filter {
  if [type] == "generated" {
    metrics {
      meter => "events"
      add_tag => "metric"
    }
  }
}output {
  # only emit events with the 'metric' tag
  if "metric" in [tags] {
    stdout {
      codec => line {
        format => "rate: %{events.rate_1m}"
      }
    }
    statsd {
                  host => "127.0.0.1"
                  port => 8125
                  gauge => [ "events.rate_1m", "%{events.rate_1m}" ]
                  sender => "eventbroker"
            }
  }
}

![sk-eventbroker-71](https://cloud.githubusercontent.com/assets/12824518/8360881/463279ce-1b8d-11e5-8965-98b17529d478.png)
![sk-logbroker-71](https://cloud.githubusercontent.com/assets/12824518/8360882/463af874-1b8d-11e5-8064-afbd04ccc94a.png)

Here we see that just generator input , the logs/events_1m rate is around 40k. I wanted to analyse the metrics on a production server, so these values might lead me astray.
What can be done henceforth?

**Comment by jordansissel** [comment]
Seems like your subject got cut off. Can you provide more detail? I don't know what is meant by "random high values"

**Comment by suraj-kamath** [comment]
Hi @jordansissel , have updated the title and the changes . Can you please help me out with this

Thanks,
Suraj

**Comment by jordansissel** [comment]
> Here we see that just generator input , the logs/events_1m rate is around 40k. I wanted to analyse the metrics on a production server, so these values might lead me astray.

What were you expecting instead? Can you show me or describe roughly what you wanted to see instead of this graph? 

The graph looks normal to me. Slight variability in output performance is not unexpected.

**Comment by jordansissel** [comment]
oh, I may have misread - let me try this -

> with no actual input given

Your configuration _has_ input. The generator input generates events as fast as possible. According to your graphs, your configuration (generator input) is outputting at a rate roughly in the range of 30k to 40k events per second.

This seems expected to me with the generator input. I don't know what you mean by "no actual input" because your configuration explicitly uses the generator input which generates input. Can you help me understand what you were expecting?

**Comment by jordansissel** [comment]
Based on your config, what you are observing looks normal to me. If you have further questions about how to do this, our [discussion forum, discuss.elastic.co](http://discuss.elastic.co/), gives you a broader audience for asking questions and getting help. We can always come back here if there's a bug.

Given I don't think there's a bug here, let's continue the discussion on http://discuss.elastic.co/ going forward :)
