### ISSUE TITLE
Logstash fails with e notation in range filter

### ISSUE THREAD

**Issue by PraveenJayakrishnakumar** [elastic/logstash#3508]
Hi all,
I am using range filter, but i am getting following error messages, If am using e notation.

Error: Expected one of #, { at line 29, column 52 (byte 807) after filter {
        
    range {
                ranges => [ "message", 0, 1000, "tag:short",
                            "message", 1001, 1e1000

**Comment by jordansissel** [comment]
Is e notation documented? I wouldn't expect this to work, but am on my
phone and can't check the code right now.

**Comment by PraveenJayakrishnakumar** [comment]
I referred these document, http://logstash.net/docs/1.4.2/filters/range#ranges

**Comment by jordansissel** [comment]
Ahh, We should remove the e-notation from the docs here. It isn't supported.

**Comment by palecur** [comment]
PR https://github.com/elastic/logstash-docs/pull/143/files is up to address this.
