### ISSUE TITLE
Add type to grok patterns

### ISSUE THREAD

**Issue by palmerabollo** [elastic/logstash#3511]
Is there any reason to not use types in the default patterns? For example, in [COMMONAPACHELOG](https://github.com/gemsi/grok/blob/389d18866adc70f1a5c7ec7a0127789bfc80b965/patterns/base#L95) why do we have `%{NUMBER:bytes}` instead of `%{NUMBER:bytes:int}`? Thanks.

**Comment by kares** [comment]
these has been addressed with our ECS efforts (a new set of patterns to be used https://github.com/logstash-plugins/logstash-patterns-core/pull/297), for the legacy patterns the conversion rules are going to stay due backwards compatibility.
