### ISSUE TITLE
If condition, compairing field with list not working

### ISSUE THREAD

**Issue by ayashjorden** [elastic/logstash#3512]
Version Logstash 1.5.0
Consider the following condition:
```
if [type] in ["webpagetest"] { # **NOT WORKING**
        stdout {
            codec => rubydebug {
                metadata => true
            }
        }
    }
```
The condition fails unless the list contains two elements:
```
if [type] in ["webpagetest", "foo"] { # **WORKING**
        stdout {
            codec => rubydebug {
                metadata => true
            }
        }
    }
```

Is it a feature or a bug ?

Thanks,
Yarden

**Comment by wiibaa** [comment]
Hello, indeed it is a bug already reported in #2129 and #2737, with a still open proposal fix #1361

**Comment by ayashjorden** [comment]
Ok, any timeframe for the fix ?

**Comment by suyograo** [comment]
@ayashjorden closed in favor of https://github.com/elastic/logstash/issues/2129. We'll try to get this in 1.5.3
