### ISSUE TITLE
Logstash crashes with geoip filter

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3526]
Found this while reviewing the test failure in acceptance tests. http://build-eu-00.elastic.co/job/logstash_integration_15_docker/SUITE=logstash-config,label=metal-pool/45/console

Don't know if this is a red herring or not, but geoip filter crashes LS in 1.5.2.snapshot1 version. I narrowed down to this filter by elimination -- it *could* be that something else in pipeline is triggering this, but, this config brings out the crash during startup. Checked 1.5.1 with same config, and its all good.

```
suyog@machine:/tmp/logstash-1.5.2.snapshot1$ bin/logstash version
logstash 1.5.2.snapshot1

suyog@machine:/tmp/logstash-1.5.2.snapshot1$ bin/logstash -f complete.conf
The error reported is:
  can't convert nil into String

suyog@machine:~/bin/releases/1.5.1/logstash-1.5.1$ bin/logstash version
logstash 1.5.1
suyog@machine:~/bin/releases/1.5.1/logstash-1.5.1$ bin/logstash -f complete.conf
Logstash startup completed

```

Config

```
input {
  stdin { }
}

filter {
  grok {
    match => {
      "message" => '%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "%{WORD:verb} %{DATA:request} HTTP/%{NUMBER:httpversion}" %{NUMBER:response:int} (?:-|%{NUMBER:bytes:int}) %{QS:referrer} %{QS:agent}'
    }
  }

  geoip {
    source => "clientip"
  }
}

output {
 stdout { codec => rubydebug }
}
```

**Comment by suyograo** [comment]
Triggered by https://github.com/elastic/logstash/commit/c83fd9f3dc3fb7634dfd5c78fe273b755f3c6b9a

**Comment by suyograo** [comment]
I am thinking the `geoip` gem upgrade is mostly the culprit https://github.com/elastic/logstash/commit/c83fd9f3dc3fb7634dfd5c78fe273b755f3c6b9a#diff-efbf03f6386a8f9610003e5858706663R87

**Comment by purbon** [comment]
This simple conf:

```
input {
 stdin {}
}

filter {
 geoip {
    source => "message"
  }
}

output {
   stdout { codec => rubydebug }
}
```
also break's LS.

**Comment by purbon** [comment]
This error comes from: https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb#L64-L70 being unable to find the vendored database.

**Comment by purbon** [comment]
The Geolittle database got no bundled with the last released gem, https://rubygems.org/gems/logstash-filter-geoip/versions/1.0.0 as you can see the size is quite smaller. Fixing this by releasing a new gem.

**Comment by purbon** [comment]
Fixed by merging https://github.com/logstash-plugins/logstash-filter-geoip/pull/31 and releasing a new gem who actually contains the vendored databases files.

**Comment by purbon** [comment]
@ph can you review https://github.com/logstash-plugins/logstash-filter-geoip/pull/31 so we can get this merge in and the test/release happy :+1:  thanks man!

**Comment by purbon** [comment]
This as of now closed so all test are green. /cc @suyograo
