### ISSUE TITLE
logstash returns an error when there are spaces in JAVA_HOME on a mac

### ISSUE THREAD

**Issue by grbinho** [elastic/logstash#3534]
Hi all,

I have this set up as my JAVA_HOME in .bash_profile
export JAVA_HOME="/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"

This is a standard path for Oracle Java on a mac.

When i run logstash i'm getting 

"Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME."

Any ideas how this should be escaped?

This is actually the only way I could get it to run Elastic search on my dev machine.

Tnx,
Ivan

**Comment by grbinho** [comment]
Hi all,

what I ended up doing is adding a simlink to a path without the space.
That works.

Ivan

**Comment by talevy** [comment]
@grbinho I was investigating this issue. and tried testing it by doing the opposite. by making a symlink of a path with spaces, but it continued to work for me

**Comment by talevy** [comment]
@grbinho I think I know what the issue is. by placing the `Internet\ Plug-Ins` in quotes. you are including this escape character.

here is an example:

```
$ echo "hello\ world"
hello\ world
$ echo "hello world"
hello world
$ echo hello\ world
hello world
```

so you can set:

```
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
```

OR
```
export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
```

and that should work without having to manage symlinks.

**Comment by talevy** [comment]
let me know if that helps!

**Comment by grbinho** [comment]
I tried this for test directly in the console

    export JAVACMD="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"

and 

    export JAVACMD=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

in both cases if i do

    $JAVACMD -version

will get

    -bash: /Library/Internet: No such file or directory

Maybe I'm making some stupid mistake here. It does not matter.
I'm using it just for test, so simlink works fine for me :)

Tnx for the help.

**Comment by talevy** [comment]
```
$JAVACMD -version
```
the above makes sense that it should fail. when being rendered it will render itself without escape 
characters, as a string. so it would be the same as running

```
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
```

If this is what you intend on doing, then running the following will work

```
"$JAVACMD" -version
```

**Comment by grbinho** [comment]
Well yes, You are right. 

Problem is that I'm running kibana from source with elastic search and if i have it set up like that (correctly), it fails with java path exception. Maybe elastic search startup does not handle it correctly.

Simlink works, so i will just leave it like that.

**Comment by talevy** [comment]
I see, but, is this still an issue for Logstash specifically (without symlink)?

**Comment by grbinho** [comment]
No,

logstash works fine with your setup and without the simlink.

**Comment by talevy** [comment]
good luck!
