### ISSUE TITLE
Logstash 1.5 fails to bind to port (lumberjack input plugin)

### ISSUE THREAD

**Issue by chris-david-taylor** [elastic/logstash#3535]
Hi guys,

I'm trying to install an ELK stack on a production machine, and during startup, logstash seems to continually do this:

[Loaded org.jruby.ext.openssl.Utils from file:/opt/logstash/vendor/jruby/lib/ruby/shared/jopenssl.jar]
[Loaded rubyjit$#Module:0xaa7e604$$normalize_key_62a82f4a26b627393d03ebd39bbfeb26d9821b65361149577$block_1$RUBY$file from JVM_DefineClass]
The error reported is: 
No message available

If I run the shell script directly, logstash implies that it has a problem binding to the port or, that the SSL cert has an issue - I know the SSL cert is fine, and there is nothing preventing the process binding to the port.
# ./bin/logstash agent -f /etc/logstash/conf.d -vv

config LogStash::Codecs::RubyDebug/@metadata = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@codec = <LogStash::Codecs::RubyDebug > {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@type = "" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@exclude_tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@workers = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
Starting lumberjack input listener {:address=>"0.0.0.0:1514", :level=>:info, :file=>"logstash/inputs/lumberjack.rb", :line=>"45", :method=>"register"}
The error reported is: 
  No message available
org/jruby/ext/openssl/X509Cert.java:204:in `initialize'
org/jruby/ext/openssl/X509Cert.java:181:in`initialize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:41:in `initialize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.9/lib/logstash/inputs/lumberjack.rb:46:in`register'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/pipeline.rb:148:in `start_inputs'
org/jruby/RubyArray.java:1613:in`each'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/pipeline.rb:147:in `start_inputs'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/pipeline.rb:80:in`run'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/pipeline.rb:80:in`run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/agent.rb:150:in `execute'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/runner.rb:87:in`run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/runner.rb:92:in`run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/task.rb:12:in`initialize

I'm running on RHEL 6.6 x64, logstash-1.5.0-1 and java-1.7.0-openjdk-1.7.0.79-2.5.5.3.

Thanks,
Chris.

**Comment by chris-david-taylor** [comment]
Update, if I use a simple syslog input filter, like the following, it starts up fine:

input {
udp
{ type => "syslog" port => "514" }
}

**Comment by riceluxs1t** [comment]
I also have exactly the same issue. Except that mine was working before it mysteriously started giving that error.

**Comment by suraj-kamath** [comment]
Facing the same issue ....  @jordansissel  can you please provide some inputs .
Thanks

Suraj

**Comment by chris-david-taylor** [comment]
Hi Chaps, I (eventually) found that the solution was to generate new SSL certs.

**Comment by chris-david-taylor** [comment]
@riceluxs1t  I suspect that your SSL Cert may have expired.  Did anything change at all?  Hostname, IP, or maybay they were just no longer valid.

**Comment by jstangroome** [comment]
I had the exact error and call stack as the OP when I messed up the configuration and pointed `ssl_certificate` and `ssl_key` both at the same file, the key.

Could this information help to improve the error message in the future?

**Comment by suyograo** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
