### ISSUE TITLE
logstash-plugins versioning / packaging

### ISSUE THREAD

**Issue by alex-leonhardt** [elastic/logstash#3541]
Hi All,

I was wondering if for all those logstash-plugins out there, is there a yum repo source to fetch those instead of using the /opt/logstash/bin/plugin (install / update) - unless there is a way to fetch specific versions of a plugin already ? I tried the --help but it didn't say anything about specific versions one could use/pin to.

Pinning a version is required for operational management and ensuring that "the same version is used" when installing them at different times (e.g. day1: version is 1.0.1, day5: version is 1.0.2, day8: version is 1.0.3, etc. etc.). 

Thanks
Alex

**Comment by vincentbernat** [comment]
There was a `logstash-contrib` package but it doesn't exist anymore.

**Comment by purbon** [comment]
@alex-leonhardt what you can do nowadays is run the plugin install command like:

``` bin/plugin install [plugin] --version [major.minor.patch] ```

update on the other side is always going to update you to the last one. When we speak about pinning versions, if you're able to see a file end up in ```.lock``` in your logstash directory, this is the file that hold which versions of what you have installed.

On the other side, when we merge #3404, you will be able to generate a package with all plugins + dependencies installed, to then be used to do installations.

Does this makes sense to you?

**Comment by vincentbernat** [comment]
`--version` should be before specifying plugin name (at least with 1.5.2).

```
bin/plugin install --version [major.minor.patch] [plugin] 
```

**Comment by purbon** [comment]
yeah, sorry I apologies! you're right.

**Comment by alex-leonhardt** [comment]
Hi, 

yes I found that a bit after I opened this - I haven't looked at the PR into too much detail but will bin/plugin list report the version ? I guess I'll ask in that ticket though.

Thanks!
Alex

**Comment by purbon** [comment]
@alex-leonhardt ```bin/plugin list --verbose``` reports the version, yes.

**Comment by alex-leonhardt** [comment]
@purbon thanks! :+1:
