### ISSUE TITLE
Logstash now consumes 100% of CPU on some machines.

### ISSUE THREAD

**Issue by razzam21** [elastic/logstash#3544]
We have about 35 machines that collect data that is then pushed into a redis server and then three servers pull it off and push it into an elastic search cluster.

Yesterday about 80% of our servers started reporting that they were under load however it was when we typically are not under load.  After investigating the cause of the load was logstash.  It didn't happen on all server but on most of the servers.  These servers have been in production for the past 2 years and the last update of any kind that was made to them happened a month ago.  I have turned off logstash for now.  We refer these to as our "shippers" because they collect the data  and then ship it off to redis where another logstash process handles injecting it into elastic search.  They are running 1.3.3.  I tried to take out portions of the config file thinking that maybe and external dependency changed that caused the issue.  No matter what I did nothing fixed it.  So I updated one of the servers to 1.5 and got it configured.  But the same thing is happening.  To eliminate load I took one server out of the cluster.  It still runs but that way nothing is hitting it to see if I can get the program to finish whatever it is trying to do.  That didn't work.  I turned on debugging and that isn't helping because after the initial load nothing.

NOTE to make my life easier I output my apache access file in json format.

Here is my shipper config:

```
input {
        file {
                path => "/var/log/httpd/json_log"
                type => "access"
                debug => true
                add_field => ["access_type","ui"]
                add_field => ["program","httpd"]
        }
}
filter {
        json {
                source => "message"
        }
        if [agent] {
                useragent {
                        source => "agent"
                        target => "details"
                }
        }
        grok {
                match => ["request", "/%{WORD:controller}"]
        }
        if [controller] == "webservices" {
                if [request] =~ /wsdl/ {
                        grok {
                                match => ["request", "/%{WORD:controller2}\?version=%{DATA:ws_version}&%{WORD:ws_type}"]
                                remove_field => ["controller2"]
                        }
                } else {
                        grok {
                                match => ["request", "/%{WORD:controller2}/%{WORD:ws_type}/%{USERNAME:ws_version}"]
                                remove_field => ["controller2"]
                        }
                }
        }
        if [remote_ip]  {
                geoip {
                        source => "remote_ip"
                        target => "geoip"
                }
        }
}
output {
        redis { host => "192.168.0.95" data_type => "list" key => "logstash" }
}
```
 Any ideas?

**Comment by jordansissel** [comment]
> Yesterday about 80% of our servers started reporting that they were under load

Yesterday had a leap-second occur. Is your OS linux? If so, what Linux kernel and Java version are you running?

**Comment by razzam21** [comment]
Thank you for the quick response.

All of the servers are running Centos and either version 6.0 or 6.2.  They are all running java version
java version "1.6.0_22".

**Comment by jordansissel** [comment]
Centos 6.0 was released prior to the Leap second crash of 2012, and may be affected by the bug. This is just hypothesis at this time, but your symptoms seem quite familiar that:
* A leap second just occurred
* Some of your servers are consuming tons of CPU in Java processes (logstash)
* You are running an old operating system that may predate the leap second bug fix.

Possible details for you to investigate:
* https://blog.mozilla.org/it/2012/06/30/mysql-and-the-leap-second-high-cpu-and-the-fix/
* https://lwn.net/Articles/504744/

i'm not 100% certain that the leap second kernel bug is affecting you, but the timing and symptoms are too strongly coinciding to give me any other hypothesis.

**Comment by razzam21** [comment]
Thank you that was the issue.

I resolved it by stoping logstash, stopping ntpd, setting the time to the proper time, starting ntpd and then starting logstash.  I have included the command the solved it for me below in the event someone else needs it.

/etc/init.d/ntpd stop; date; date `date +"%m%d%H%M%C%y.%S"`; date;

**Comment by suyograo** [comment]
Thanks @razzam21
