### ISSUE TITLE
Logstash agent ingestion rate slow,how to  optimize?

### ISSUE THREAD

**Issue by VicentJ** [elastic/logstash#3549]
Appearance：
      my logstash agent(client) can only read about 350 records(about 85M) per second which is not even close to what we need.
Version： 
      my  logstash agent version is logstash-1.5.1(logstash-1.5.1.zip),get from The official website. i didn't change the default settings.only add a Configuration file named logstash.conf and the content as below:
input {
	file {
		type => "computer1347"
		path => ["D:/testLog/stdout.log", "D:/testLog/stderr.log"]
		exclude => ["*.gz", "error.log"]
	}   
}

output {
	stdout {}
	redis {
		host => "10.6.2.19"
		port => 6379
		data_type => "list"
		key => "key_count"
	}   
}
Running Environment:
      client computer is a windows system.windows7 64bit with 8G RAM,CPU i5 3.3GHz.
so i was wondering  what might made my ingestion rate slow.

**Comment by markwalkom** [comment]
Please join us in #kibana on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)
