### ISSUE TITLE
logstash file input plugin performance issue in production

### ISSUE THREAD

**Issue by reecemarkowsky** [elastic/logstash#3552]
Hi. I am seeing a performance issue when running logstash (reading log file and sending logline events) in production that I am not seeing in test.

in production i am seeing logstash rate low at around 200-250eps.

after troubleshooting, I suspected the issue was manifesting itself within file input plugin. so i used a "barebones" config that included only the file input, metrics filter and stdout (to print the 1m rate).  (I will paste my test config below)

in test, the rate was high. starting at 4500eps and rising steadily to >8000eps
in production, the rate was low, around 200eps constantly.
sometimes, however, intermittently, in production, the rate would be good initially (4500 eps) but then immediately slowly degrade to 200 eps again.  it would never maintain a rate as we see in test.

I modified file.rb to print a message everytime it queues 1000 events to witness this slowness within the plugin. in production, i could see that it took seconds to queue 1000 events.  

I did not see anything  going on with cpu or io. i also tried various settings on the file input plugin with the input:  eg. no multiline codec, only single path, single explicit (fully qualified path) and all had same result. low performance about 200 eps.

here is the barebones config i used to see this issue:

input {
  file {
    path => "/somelogfile.log"
    type => "core"
    sincedb_path => "/some/path/sincedb"
  }
}

filter {
  metrics {
    meter => "events"
    add_tag => "metric"
    flush_interval => 10
  }
}

output {
  if "metric" in [tags] {
    stdout {
     codec => line {
       format => "rate: %{events.rate_1m}"
     }
    }
  }
}

Here is the modification i made to file.rb (run function) - note, i get the same results with or without this change. i only added this to see the issue manifesting at the input plugin level.
````
public
  def run(queue)
    @count = 0                     <==== COUNT EVENTS 
    @tail = FileWatch::Tail.new(@tail_config)
    @tail.logger = @logger
    @path.each { |path| @tail.tail(path) }
    hostname = Socket.gethostname

    @tail.subscribe do |path, line|
      @logger.debug? && @logger.debug("Received line", :path => path, :text => line)
      @codec.decode(line) do |event|
        decorate(event)
        event["host"] = hostname if !event.include?("host")
        event["path"] = path
        time2 = Time.now      <===== PRINT A MESSAGE EVERY 1000 EVENTS
        @count = @count + 1
        if @count % 1000 == 0
          @logger.info("1000 EVENTS + #{time2.inspect} + #{@count}") 
        end
        queue << event
      end
    end
    finished
  end # def run
````

So here are the test results: (in my test environment, vagrant VM):  Can see good performance.  queueing upto 5000 events / sec ... note, this steadily climbs to upwards of 8000 eps.
Pipeline started {:level=>:info}
Logstash startup completed
1000 EVENTS + 2015-07-02 16:31:33 UTC + 1000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:33 UTC + 2000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:34 UTC + 3000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:34 UTC + 4000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:34 UTC + 5000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:34 UTC + 6000 {:level=>:info} <-- queued 6000 events in 16:31:34
1000 EVENTS + 2015-07-02 16:31:35 UTC + 7000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:35 UTC + 8000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:35 UTC + 9000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:35 UTC + 10000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:35 UTC + 11000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:36 UTC + 12000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:36 UTC + 13000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:36 UTC + 14000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:36 UTC + 15000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:36 UTC + 16000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:36 UTC + 17000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 18000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 19000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 20000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 21000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 22000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 23000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 24000 {:level=>:info}
1000 EVENTS + 2015-07-02 16:31:37 UTC + 25000 {:level=>:info}
rate: 5089.8 <--- -metrics plugin output. rate steadily increases upwards of 8000 eps.   

THIS IS PRODUCTION:  can see that it takes seconds to queue 1000 events and the rate reporting is very low. 

{:timestamp=>"2015-07-02T07:10:08.209000+0000", :message=>"Pipeline started", :level=>:info}
{:timestamp=>"2015-07-02T07:10:10.349000+0000", :message=>"1000 EVENTS + 2015-07-02 07:10:10 UTC + 1000", :level=>:info}
rate: 0.0
{:timestamp=>"2015-07-02T07:10:13.555000+0000", :message=>"1000 EVENTS + 2015-07-02 07:10:13 UTC + 2000", :level=>:info}
{:timestamp=>"2015-07-02T07:10:15.722000+0000", :message=>"1000 EVENTS + 2015-07-02 07:10:15 UTC + 3000", :level=>:info}
{:timestamp=>"2015-07-02T07:10:18.866000+0000", :message=>"1000 EVENTS + 2015-07-02 07:10:18 UTC + 4000", :level=>:info}
{:timestamp=>"2015-07-02T07:10:20.984000+0000", :message=>"1000 EVENTS + 2015-07-02 07:10:20 UTC + 5000", :level=>:info}
rate: 419.41754562910046

NOTE:   I have run the same test in production multiple times.  intermittently, i have seen seen it start off with 4000-5000 events/sec.  but then, it slowly declines back to 200eps.  

Running it for extended periods of time in production. performance consistent at 200 eps.

stumped on this one.  cannot reproduce in the test environment.    any ideas or things to look at?

thanks!
reece

**Comment by ph** [comment]
Which version of logstash are you running?

**Comment by ph** [comment]
Can you also run this command `bin/plugin list --verbose logstash-input-file`

**Comment by reecemarkowsky** [comment]
thanks!

-bash-4.1$ bin/logstash --version
logstash 1.5.0.rc2

-bash-4.1$ bin/plugin list --verbose logstash-input-file
logstash-input-file (0.1.6)

**Comment by ph** [comment]
@reecemarkowsky We did a lot of changes in the file input and in logstash since rc2.
We also fixed a deadlock issue in 1.5.1, I strongly suggest that you try with the latest version of logstash which is 1.5.2

**Comment by reecemarkowsky** [comment]
Ok. Thank you for the (incredibly) quick response. its very appreciated.  Ok , will check into that right away.

**Comment by buddyp450** [comment]
I am able to replicate this same issue with logstash-1.5.5 and logstash-input-file 1.0.1.

**Comment by purbon** [comment]
@buddyp450 I wonder if you are also able to replicate this with the 2.x branch of logstash and the input? are you?

**Comment by suyograo** [comment]
A lot of fixes have gone into file input. Please try the latest. An alternate suggestion is to use Filebeat
