### ISSUE TITLE
Support for using custom plugins using --pluginpath

### ISSUE THREAD

**Issue by TinLe** [elastic/logstash#3553]
We need support for --pluginpath.   With just released v1.5.2, I am getting the following errors when I start logstash.

bin/logstash --filterworkers 10 --pluginpath /export/content/logstash/plugins --config /export/content/logstash/config/m-logstash
Clamp::UsageError: Unrecognised option '--pluginpath'
  signal_usage_error at /export/content/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:103
         find_option at /export/content/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:62
       parse_options at /export/content/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:28
               parse at /export/content/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:52
                 run at /export/content/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.2.2-java/lib/logstash/runner.rb:80
                call at org/jruby/RubyProc.java:271
                 run at /export/content/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.2.2-java/lib/logstash/runner.rb:96
                call at org/jruby/RubyProc.java:271
          initialize at /export/content/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/task.rb:12

**Comment by ph** [comment]
We are thinking about bringing it back, for now there is a workaround. You can define `RUBYLIB` env with the path. See this discussion in our forum for more details.
https://discuss.elastic.co/t/logstash-new-plugin-system-too-restrictive/24247/2

**Comment by TinLe** [comment]
Thanks.  RUBYLIB allows me to get around this, but it feels hacky.   Please bring back support for --pluginpath.   We have in house written plugins that we can not share and need to keep using.

**Comment by jordansissel** [comment]
@TinLe using the new plugin tooling doesn't require you share your plugins.

**Comment by TinLe** [comment]
@jordansissel How does the tooling work?   We are required to use our own deployment tool, so ELK packages are re-packaged into our own repo, and deployed from there.   The plugins must be pre-installed and ready in the repo.   Packages in production can not be changed, no installation allowed in production environment.

It's becoming painful if we have to take source from github and adapt them into our own source repo.

**Comment by jordansissel** [comment]
>  We are required to use our own deployment tool, so ELK packages are re-packaged into our own repo

I confess that I don't know anything about your deployment tool or your repackaging practices, so I'm not sure what advice I can offer for that.

One option, though I am speculating because I don't know anything about your requirements, is to install local plugins packages `bin/plugin install myplugin.gem` and then package up that whole logstash installation as your custom repackaged thing. This solves your "no installation allowed in production environment" problem.

**Comment by TinLe** [comment]
Yeah, that's not going to work for us.    It gets.... complicated.   Back when --plugins worked, we have the plugins source located in a dedicated directory that other engineers in the company can add their own plugins.   Each one  own their own subdir (plugin) within there.   They do not have access to logstash tree, and can not make changes to it.   That is own by a dedicated ELK support team.   That allows our users to deploy the ELK packages we maintain, but using their plugins via specifying --pluginpath.   We don't know when they update their plugins and don't care.

Same goes for configs, users own their own configs. and can deploy with new changes anytime.  They do not have access to the main logstash package.   At least here, we can use the --configdir flag.

**Comment by jordansissel** [comment]
Given enough users are affected by the removal of `--pluginpath`, we are willing to restore the flag. The implementation cost of the flag is low (it does the same thing as RUBYLIB env setting), so the burden on us maintaining it is nearly zero.

We may need to remove it again in the future, but we'll make sure we figure out a solution first for existing users before we do that. Thank you for providing details on why you liked the remvoed feature! :)

We'll keep this issue updated as work progresses on restoring the flag.

**Comment by suyograo** [comment]
ref: https://github.com/elastic/logstash/issues/2423

**Comment by colinsurprenant** [comment]
we are restoring the `--pluginpath` option see #3580

**Comment by colinsurprenant** [comment]
closing this, `--pluginpath` has been added back in #3587 and will be available in 1.5.3
