### ISSUE TITLE
custom codec no longer loaded in 1 .5.2

### ISSUE THREAD

**Issue by fcntl** [elastic/logstash#3554]
I updated to 1.5.2 and my codec stopped working
I was dropping it in another codec dir /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/
It worked fine under 1.5.1. Now under 1.5.2 I get "Couldn't find any codec plugin..." message.
Where can I just drop a custom .rb file somewhere so it will be loaded as a codec?

**Comment by suyograo** [comment]
@fcntl currently, LS on upgrade loses locally installed plugins. We will be working on a fix for this soon. Closing this as a dup of https://github.com/elastic/logstash/issues/3540.

**Comment by suyograo** [comment]
@fcntl not a great workaround, but still: you can reinstall custom/local plugins after the upgrade using `bin/plugin install`
