### ISSUE TITLE
"logstash" directory not getting created after upgrading to logstash 1.5.0 from 1.4.1

### ISSUE THREAD

**Issue by suraj-kamath** [elastic/logstash#3555]
Hi , 
     After the recent logstash upgrade to 1.5.0 , the logstash subdirectory under /opt/logstash/lib cannot be found .

The following is the folder structure previously getting formed in logstash 1.4.1
![logstash version](https://cloud.githubusercontent.com/assets/12824518/8494330/9711634c-2181-11e5-9ff6-ae9b370498f0.JPG)

The logstash folder would contain the necessary plugins/dependencies which we use .

After the logstash upgrade , it was found that the "logstash" folder along with the other ruby files went missing .Henceforth our newer deployments started to fail, missing the dependencies .

I looked at the change-log but couldn't find any right reference ! What is the workaround for this? 
Are these files/directories being moved to a different location ?

**Comment by suraj-kamath** [comment]
@jordansissel , @suyograo  ... Any suggestions ? This information is critical for me , please help me out,

**Comment by suyograo** [comment]
@suraj-kamath plugins source code in 1.5 has been separated into individual gems and they get installed in `./vendor/bundle/jruby/1.9/gems/`. So for mutate filter plugin, the lib files will be in `./vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-1.0.0/lib/logstash/filters/mutate.rb`

Do you have a need to use in-house plugins? You can follow our guide here to convert them to ruby gems here: https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html

Also, the rationale for plugin separation in 1.5 has been explained in this blog: https://www.elastic.co/blog/plugin-ecosystem-changes

**Comment by suraj-kamath** [comment]
Hi Suyog, 
                Thanks for the comment, but what i wanted to know is whether there is a way to have the same directory structure as the previous versions. This would be easier for us to continue with our framework without having to do much changes in our production code.

Please let me know if this is possible and if yes how ?
Regards
Suraj

**Comment by kares** [comment]
closing as this one is defunct by now
