### ISSUE TITLE
Debian/Ubuntu init script returns incorrect exit codes

### ISSUE THREAD

**Issue by vincentbernat** [elastic/logstash#3556]
Hey!

The init script used for Debian and Ubuntu doesn't respect [LSB specification](http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html).

Notably, start always exit with 0, stop always exit with 0, restart always exit with 0 and will happily start logstash even when it was unable to stop it.

Moreover, the integration is pretty poor by using echo instead of log_\* helpers. This makes the script outputs text even when quiet boot has been configured.

A good skeleton for an init script is available as [/etc/init.d/skeleton](http://sources.debian.net/src/sysvinit/2.88dsf-41%2Bdeb7u1/debian/src/initscripts/etc/init.d/skeleton/) (but of course, Debian/Ubuntu specific).

From what I understand, the new init script has been generated by `pleaserun`. Maybe this is just a matter of running `pleaserun` to get an updated and fixed version. But this doesn't seem the case (just looking at the template used).

**Comment by vincentbernat** [comment]
Changes to pleaserun suggested here: https://github.com/jordansissel/pleaserun/pull/84

**Comment by coder-hugo** [comment]
:+1:

**Comment by jordansissel** [comment]
> A good skeleton for an init script is available as /etc/init.d/skeleton (but of course, Debian/Ubuntu specific).

Cannot use that skeleton file because it is GPL2 licensed and incompatible with this project.

We'll get this working better soon, if it isn't already fixed.

**Comment by vincentbernat** [comment]
I don't think an example can be copyrightable. I can ask some advice on debian-legal@.
