### ISSUE TITLE
Input S3 config Error

### ISSUE THREAD

**Issue by bsjin** [elastic/logstash#3565]
Hello.

I want input data from S3 bucket to elasticsearch when using logstash

So, I don't know Why this Error
---------------------------------------------------------------------------------------------------------
jbs01@jbs01:~/logstash-1.4.2$ ./bin/logstash -f conf/s3.conf

Using milestone 1 input plugin 's3'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 region_endpoint=>"eu-west-1", bucket=>"prd-eu-etl-log", prefix=>"20150705/eu/023", backup_to_dir=>"/tmp/logstashed/", sincedb_path=>"/tmp/s3.sincedb", tags=>["s3", "example", "caen"], type=>"s3-test", credentials=>["AK~~~~~~~~~~~~~AQ", "TS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~uQ"]>
error: execution expired {:level=>:error}

---------------------------------------------------------------------------------------------------------

my logstash config file
---------------------------------------------------------------------------------------------------------
input {
        s3 {
                region_endpoint => "eu-west-1"
                bucket => "devl-log"
                prefix => "20150705/test"
                backup_to_dir => "/tmp/logstashed/"
                sincedb_path => "/tmp/s3.sincedb"
                tags => ["s3", "example", "caen"]
                type => "s3-test"
                credentials => ["AKIAJ~~~~~~~~~~~3U5MAQ","TSME0~~~~~~~~~~lpTquQ"]
        }
}

output {
  elasticsearch { host => localhost }
  stdout { codec => rubydebug }
}
---------------------------------------------------------------------------------------------------------

Credentials => ["AWS acceess key", "AWS security key"]
Is this okay?

Please check whether the well where the bad part.

Thanks.

**Comment by suyograo** [comment]
Hi @bsjin can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
