### ISSUE TITLE
Issue with mutate -> add_field and parentheses

### ISSUE THREAD

**Issue by orweinberger** [elastic/logstash#3569]
I have the following filter which works perfectly on v1.4.2:

```
mutate {
    add_field => { "destinationIPHost" => "%{destinationHostName} (%{destinationAddress})" }
}
```

So when `destinationHostName=MYHOST` and `destinationAddress=1.2.3.4` the expected result is `destinationIPHost=MYHOST (1.2.3.4)`

When this filter is processed with v1.5.2 the result is `destinationIPHost=MYHOST (1.2.3.4` - missing the final `)` character.

Also, when I tried changing the filter to

```
mutate {
    add_field => { "destinationIPHost" => "%{destinationHostName} (%{destinationAddress}))" }
}
```

I got this result on v1.5.2: `destinationIPHost=MYHOST (1.2.3.4))`

**Comment by webmstr** [comment]
It looks like it's any *single* character after the *last* pattern, so:

    add_field => { "c" => "%{a}%{b}x" }

fails, while:

    add_field => { "c" => "%{a}%{b}xx" }

will add the "xx" at the end.

**Comment by wiibaa** [comment]
@ph can you confirm this is fixed by https://github.com/elastic/logstash/commit/935ac9285b6bb34f8b261cda93203223fe46e76c and close this

**Comment by ph** [comment]
I can confirm that its fixed, thanks @wiibaa
