### ISSUE TITLE
about elasticsearch_template.json

### ISSUE THREAD

**Issue by hy05190134** [elastic/logstash#3573]
I used to modify elastic search_template.json in log stash/lib/logstash/outputs/elasticsearch, and it will make sense, I wonder where should I modify in log stash 1.5.1, I find one in deep bundle directory, but I find it doesn't make sense, please help me , thanks

**Comment by suyograo** [comment]
You should not modify the stock template. You can copy it to a different location and use `template` path to make modifications. See https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-template
