### ISSUE TITLE
Make init script 'stop' configurable behavior on timeout

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#3578]
If Logstash doesn't shutdown fast enough, we should give the user a configurable option for doing `kill -9` as an alternative to giving up like it does today.

Proposal to have a 'TERMINATION_TIMEOUT_ACTION' setting in the /etc/default (or sysconfig, whatever) that defaults to "ignore" but has an option for "kill" where instead of ignoring it will kill -9 if logstash hasn't terminated fast enough.

**Comment by untergeek** [comment]
For **debian**, this is nearly all present: 

> [--retry=TERM/20/KILL/5 >/dev/null](https://github.com/elastic/logstash/blob/master/pkg/logstash.sysv.debian#L126)

From the [start-stop-daemon manpage](http://manpages.ubuntu.com/manpages/hardy/man8/start-stop-daemon.8.html):

``` 
-R, --retry timeout|schedule
              With  --stop,  specifies  that  start-stop-daemon  is  to  check
              whether  the  process(es)  do  finish.  It will check repeatedly
              whether any matching processes are running, until none  are.  If
              the  processes  do  not exit it will then take further action as
              determined by the schedule.

              If timeout is specified instead of schedule  then  the  schedule
              signal/timeout/KILL/timeout  is used, where signal is the signal
              specified with --signal.

              schedule is a list of at least two items  separated  by  slashes
              (/);  each  item  may be -signal-number or [-]signal-name, which
              means to send that signal, or timeout, which means to wait  that
              many  seconds  for processes to exit, or forever, which means to
              repeat the rest of the schedule forever if necessary.

              If the end of  the  schedule  is  reached  and  forever  is  not
              specified, then start-stop-daemon exits with error status 2.  If
              a schedule is specified, then any signal specified with --signal
              is ignored.
 ```
I read this to mean that our current configuration will wait for it to terminate from a SIGTERM for 20 seconds, and if that fails, it will do a SIGKILL and check again after 5 seconds.  If it still fails to die (not likely after a kill -9), then after those 5 seconds, an exit code of 2 results.

We can clearly make the 20 second timeout configurable.  What say you?

(More to follow with regard to the redhat script as I look that one over)

**Comment by untergeek** [comment]
The RedHat stop command needs some help:

```
do_stop()
{
    killproc -p $PID_FILE $DAEMON
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${PID_FILE}
}

case "$1" in
...
  stop)
    echo -n "Stopping $DESC: "
    do_stop
    rm /var/run/logstash/$NAME
    ;;
```

I can work on writing up something that will do what Debian's `start-stop-daemon` does for our RedHat script, and makes use of a config file variable.

**Comment by jordansissel** [comment]
@untergeek just fyi, I'd like to have these improvements in pleaserun (https://github.com/jordansissel/pleaserun/tree/master/templates/sysv/lsb-3.1) if we can.

**Comment by untergeek** [comment]
Would that replace the awesome functionality in Debian?  We can still go that route.

I wasn't sure if we were using pleaserun for Debian installs, but the start-stop-daemon is pretty slick.  I think I can help with this.

**Comment by jordansissel** [comment]
@untergeek I'm open to having a 'debian' and 'redhat' targets for sysv support in pleaserun - instead of the general "lsb-3.1" we have today.

**Comment by untergeek** [comment]
First draft: https://github.com/jordansissel/pleaserun/pull/86

**Comment by suyograo** [comment]
Closed via https://github.com/elastic/logstash/pull/3609
