### ISSUE TITLE
Add back --pluginpath command line option

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3580]
In 1.5.0 plugins went through a big revamp, separating it into individual gems. The de facto way of developing custom plugins was to create ruby gems and installing it on LS using the following ways:
1. Publish to RubyGems.org and `bin/plugin install <my_new_plugin>` 
2. Building the gem locally and installing using `bin/plugin install <my_new_plugin.gem>`
3. Changing the `gemspec` to [point](https://github.com/logstash-plugins/logstash-output-elasticsearch#2-running-your-unpublished-plugin-in-logstash) to a github repository remotely or to a cloned copy on disk (using `:git =>` or `:path => plugin_path` ) 

We need to add back `bin/plugin --pluginpath` to allow users to point to ruby files which contain custom plugin code. This will allow for rapid prototyping and experimenting with new plugins

Issues:

- [ ] custom plugins not recognized in RC4 https://github.com/elastic/logstash/issues/3227
- [ ] Support for using custom plugins using --pluginpath https://github.com/elastic/logstash/issues/3553

Discuss:

https://discuss.elastic.co/t/logstash-new-plugin-system-too-restrictive/24247

**Comment by suyograo** [comment]
Related: https://github.com/elastic/logstash/issues/2423

**Comment by colinsurprenant** [comment]
fixed by #3587
