### ISSUE TITLE
Install a Logstash plugin from a local GEM repository

### ISSUE THREAD

**Issue by fcntl** [elastic/logstash#3581]
I would like to host a Logstash plugin (built as a GEM) in an Artifactory RubyGems repository, and install it using the "/opt/logstash/bin/plugin install" command.

Where can I set the path of my local RubyGems repo for logstash to source the gem from?

**Comment by jordansissel** [comment]
Related:
* https://github.com/elastic/logstash/issues/3576
* https://github.com/elastic/logstash/issues/3424
* https://github.com/elastic/logstash/issues/3168

Last update from a meeting today was that @purbon was experimenting with a solution for this.

**Comment by dforste** [comment]
+1

**Comment by purbon** [comment]
@dforste this is nowadays possible, but require some hacks, we're working to include a neat solution for this for next 1.6.0 release.

For nowadays situation you need to:

* Add your new source in the Gemfile, same thing as the rubygems one is already.
* Run the install command with the --no-verify option

Is your environment connected to the internet?

**Comment by dforste** [comment]
It is currently not connected to the internet. 
Adding the --no-verify flag worked like a charm. 

Thanks.

**Comment by purbon** [comment]
you're welcome! :panda_face:

**Comment by fcntl** [comment]
> we're working to include a neat solution for this for next 1.6.0 release.

Can you also add an option to the KV filter to allow field/value splits as full REGEXs rather than character classes (which limit you to a SINGLE character as the delimiter). It is really annoying having to choose 2 ASCII characters that cannot appear in any key/value as they are reserved. It would be good to choose multi-character splitters.

**Comment by purbon** [comment]
@fcntl this is out of the scope of this issue, I encourage you to open an issue with it at the repository for this plugin, https://github.com/logstash-plugins/logstash-filter-kv.

**Comment by suyograo** [comment]
Closing this in favor of https://github.com/elastic/logstash/issues/3576
