### ISSUE TITLE
logstash-1.5.2: problem with closing bracket in file -> output -> message_format 

### ISSUE THREAD

**Issue by kb1** [elastic/logstash#3585]
Test parameters:
test_message: {  "fname": "foo", "lname": "bar"}
logstash_config: 'input { stdin { codec => json } } output { file { codec => plain path => "/tmp/my.log" message_format => "%{fname} [Tags: %{fname}]" } }'

1) Using the config above results in a missing closing bracket at the end of the log line in /tmp/my.log:
message_format => "%{fname} [Tags: %{fname}]"
foo [Tags: foo           #no closing bracket

2) Adding a space before the final bracket in the logstash config adds the space and final bracket:
message_format => "%{fname} [Tags: %{fname} ]"    #space between '}' and ']'
foo [Tags: foo ]         #closing backet

3) Adding another field after closing bracket results in bracket being output:
message_format => "%{fname} [Tags: %{fname}] %{lname}"   #added "%{lname}" to end
foo [Tags: foo] bar    #closing bracket

**Comment by jaylik** [comment]
Same problem with this,

    grok {
        match => [
            "message", "^Alarm cleared: %{GREEDYDATA:alarm_description}$"
        ]
        add_tag => [ "alarm-clear" ]
        add_field => {
            "[@metadata][zabbix_sender]" =>  "true"
            "[@metadata][zabbix_key]" => "CiscoExternalAlarmContact[%{alarm_description}]"
            "[@metadata][zabbix_value]" => "0"
        }
    }

...will result output,

    {
                  "message" => "Alarm cleared: rittal-cooling-unit",
                 "@version" => "1",
               "@timestamp" => "2015-10-09T06:18:13.463Z",
                     "type" => "syslog",
                     "host" => "host.na.me",
                     "tags" => [
            [0] "cisco-syslog",
            [1] "alarm-clear"
        ],
                 "priority" => 0,
                 "severity" => 1,
                 "facility" => 23,
           "facility_label" => "local7",
           "severity_label" => "alert",
                "timestamp" => "Oct  9 2015 09:18:13.452 EEST",
            "ciscofacility" => "PLATFORM_ENV",
            "ciscoseverity" => "1",
            "ciscomnemonic" => "EXTERNAL_ALARM_CONTACT_CLEAR",
        "alarm_description" => "rittal-cooling-unit",
                "@metadata" => {
            "zabbix_sender" => "true",
               "zabbix_key" => "CiscoExternalAlarmContact[rittal-cooling-unit",
             "zabbix_value" => "0"
        }
    }

...so closing bracket is missing in zabbix_key.

**Comment by jaylik** [comment]
Verified that this problem doesn't exist with 1.5.1

    C:\work\logstash\logstash-1.5.1\bin>logstash agent -f test.conf
    io/console not supported; tty will not be manipulated
    Logstash startup completed
    test
    {
           "message" => "test\r",
          "@version" => "1",
        "@timestamp" => "2015-10-09T19:07:12.608Z",
              "host" => "octane",
              "test" => "[test\r]"
    }

...

    C:\work\logstash\logstash-1.5.4\bin>logstash agent -f test.conf
    io/console not supported; tty will not be manipulated
    Logstash startup completed
    test
    {
           "message" => "test\r",
          "@version" => "1",
        "@timestamp" => "2015-10-09T19:08:09.329Z",
              "host" => "octane",
              "test" => "[test\r"
    }

...and conf,

    input {
    	stdin {}
    }
    
    filter {
    	mutate {
    		add_field => { "test" => "[%{message}]" }
    	}
    }
    
    output {
    	stdout { 
    		codec  => rubydebug {
    			metadata => true
    		}
    	}
    }

**Comment by ph** [comment]
I have fixed this in https://github.com/elastic/logstash/pull/3937, I will backport that fix into the 1.5 branch so the next 1.5 release contains it.

**Comment by ph** [comment]
2.0 beta isn't affected by this issue.

**Comment by suyograo** [comment]
Fixed #3937
