### ISSUE TITLE
Integrate community-driven logstash plugins into logstash reference documentation

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#3586]
This would be nice to integrate into logstash reference documentation (https://www.elastic.co/guide/en/logstash/current/index.html), all community-driven plugins that are hosted in "logstash-plugins" github account.

Furthermore, it would fulfill benefits announced here :
https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html#_contributing_your_source_code_to_ulink_url_https_github_com_logstash_plugins_logstash_plugins_ulink_3

**Comment by suyograo** [comment]
@fbaligand thats always been our goal. Could you please let us know which plugins in logstash-plugins are missing docs?

**Comment by suyograo** [comment]
Ok I see that https://github.com/logstash-plugins/logstash-filter-aggregate is missing, I will push it soon

**Comment by fbaligand** [comment]
You get it ;)
@purbon told me to open a global issue, so I did it.

**Comment by fbaligand** [comment]
@suyograo Do you want I rename the issue to be specific to aggregate plugin ?

**Comment by purbon** [comment]
@suyograo as of #3590 the documentation generation seems to be broken, in the process now to get this fix so plugins as the one from @fbaligand could be seen in the documentation.

**Comment by purbon** [comment]
With the fix in #3590 the documentation is now generated properly, I basically run ```rake docs:generate``` and then check all installed plugins were actually listed in the documentation.

**Comment by fbaligand** [comment]
@purbon @suyograo 
At next Elastic French Meetup (in september), I will make a presentation about aggregate plugin and the process to integrate a plugin into logstash-plugins repository.
It would be great if "aggregate" plugin was integrated into logstash documentation before this meetup.

**Comment by suyograo** [comment]
@fbaligand generating docs now. weird issue, the asciidoc generated is missing a lot of sections and only providing base filter config options. It also names this as "filter" not "aggregate". Investigating

My process:
`bin/plugin install logstash-filter-aggregate`
`bin/logstash docgen -o asciidoc ./vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-0.1.3/lib/logstash/filters/aggregate.rb`

Generated asciidoc: https://gist.github.com/suyograo/18bc495f970da048d43c

**Comment by suyograo** [comment]
@fbaligand Done! https://www.elastic.co/guide/en/logstash/current/plugins-filters-aggregate.html Apologies for the delay!

**Comment by fbaligand** [comment]
@suyograo
Perfect !
Thank you very much !
