### ISSUE TITLE
Bad URL to LS overview page

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#3588]
Reported [here](https://discuss.elastic.co/t/recommended-es-version-for-logstash-docs-link-broken/25143).

https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html
> Make sure they match based on the [Logstash version](http://www.elastic.co/overview/logstash) you’re running!

We're linking to http://www.elastic.co/overview/logstash instead of https://www.elastic.co/products/logstash (or maybe the downloads page?).

**Comment by Flupsy** [comment]
Sorry to be a pain, but this isn't fixed in the live documentation: the broken link is still there.
