### ISSUE TITLE
[docs] Messaging queue > messaging broker

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#3598]
On [this](https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html) page we refer to messaging queues, which may inadvertently mislead people to thinking we recommend/prefer MQ products when the concept is something more general.

I'd suggest that we `s/queue/broker/`, then either leave it as a concept for the user to then define or provide some commonly used ones such as redis, MQ and kafka.

**Comment by palecur** [comment]
Dup of #3786
