### ISSUE TITLE
Change Logstash config to json

### ISSUE THREAD

**Issue by yehosef** [elastic/logstash#3600]
currently logstash has it's own config format which doesn't have existing syntax checks in editors.  I humbly suggest and request that this should be changed to json (or at least yaml) so we can use regular editors with syntax parsing for editing the files.

**Comment by colinsurprenant** [comment]
@yehosef do you have any suggestions for transposing the conditionals syntax in json?

**Comment by yehosef** [comment]
Sure - can you give me a semi-complicated example in logstash and I'll try to convert it to json.

you basically would create a structure like:

    {
       filter: {

            cond: {
                if :{},
                then: {mutate:{}},
                else:{}
            } 
     }

alternatively -

     {
         filter: [
              {mutate: 
                  {cond: {
                      if:{},
                      then:{},
                      else:{}
                   }
              }
             
     }

obviously rough draft - but the point being you just need to get concepts into json structures.

I understand that this is more convoluted - but the advantage is I have a nice parser to work with.  And I assume/hope that one goal one day is that logstash will be a server that you can send commands to (have processors running - check on status, have dashboard, etc) - then the config will be amenable to a rest interface like elasticsearch.

**Comment by yehosef** [comment]
If you want to include a more complex real example, I can try to convert it to show how it would look.  My examples are pretty simple so I don't think they would be useful.

**Comment by colinsurprenant** [comment]
@yehosef first for your hope ;) this is somewhat the direction we are taking see our roadmap, in particular the "Manageability" sections https://www.elastic.co/guide/en/logstash-roadmap/current/index.html#_manageability

Thanks for the json conditional syntax proposal, this will be definitely useful in our reflexion. Another approach is to also look at the Elasticsearch bool query syntax https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

**Comment by yehosef** [comment]
great to hear.  The ES bool is where I drew inspiration from.  Once I started writing queries for elasticsearch, I realized you could do anything with json :)

**Comment by colinsurprenant** [comment]
:thumbsup:

There are all sorts of obvious benefits for using json for the config syntax, but one thing that *scares* me a little bit is the added complexity for creating "complex" configs. very big config files with tons of conditionals are not rare out there. the current syntax is quite expressive with regards to conditionals and I am afraid that complex configs will become a lots more complex using json. 

As you suggested, I'd like to see examples for non-trivial configs to get a feel of that added complexity and see how we can mitigate this.

**Comment by yehosef** [comment]
If you can include an example to a more complex config, I would be happy to give it a try.  I'm not sure that with json they will be much more complex, per say, but they will probably be more lines given traditional json formatting.  

You could probably shorten the syntax a little if you imply the pieces - eg `cond[{<if clause>},{<then clause>},{<else clause>}]` but in general I prefer it to be explicit than compact.

**Comment by Xylakant** [comment]
I think json would be a bad option. Yaml might be a better fit, but fundamentally a real DSL might be better. My primary grief with JSON is that it does not allow comments which are really important in longer files. Also JSON is pretty hard to generate if you have individual blocks that you want to piece together on a host-by-host basis (hashes and arrays need commas to separate them, except for the last, ...)

**Comment by jordansissel** [comment]
> has it's own config format which doesn't have existing syntax checks in editors

JSON syntax checkout would only tell you about the validitity of the json syntax, not the validity of what you have described for Logstash (example: Did you say "inpuuuuuut"  instead of "input" ? Both are valid json, one is invalid logstash)

Regarding JSON not having comments, we have a trick for that in logstash-forwarder that works well to allow `# comments like this` in the json, so I'm not concerned about that.

>  a real DSL might be better

This is what the logstash config syntax is today. :)

**Comment by jordansissel** [comment]
As a note, we're adding an API for management and monitoring in Logstash. This API will, unless plans change, be JSON over HTTP just like Elasticsearch's API is today. This means we will have to represent  Logstash pipeline functionality in JSON. Basically, the road to JSON for configuration is a road we are already on. We'll work on providing clients (like Elasticsearch does) for configuring Logstash via this API also.

**Comment by Xylakant** [comment]
> Regarding JSON not having comments, we have a trick for that in logstash-forwarder that works well to allow # comments like this in the json, so I'm not concerned about that.

But that trips up syntax checkers which will negate the whole idea of having a format that has syntax highlighting in editors.

**Comment by jordansissel** [comment]
> that trips up syntax checkers

Nothing prevents us (the community) from providing syntax validation/highlighting for Logstash's configuration :)

**Comment by Xylakant** [comment]
> Nothing prevents us (the community) from providing syntax validation/highlighting for Logstash's configuration :)

certainly. but if the community wants to write syntax highlighters for a custom format (json with comments) it could already have done that for the current DSL.

I'm not entirely sold on the idea of an api to configure the running LS process - where's the perceived benefit? Restarting an ES node is a resource intensive operation that I want to avoid - it may trigger rebalances etc, restarting a logstash process is cheap. On the flip side configuration via API plays notoriously bad with configuration management systems such as chef and puppet. Just look at the stunts the puppet-elasticsearch module needs to pull for index template management. What happens when I update an LS pipeline while the process runs? Does it stop all inputs, drain all events then load the new config and restart? Restarting the process is easier to reason about.

**Comment by jordansissel** [comment]
> it could already have done that for the current DSL

Some have - http://www.vim.org/scripts/script.php?script_id=5001

> What happens when I update an LS pipeline while the process runs?

We are still working to define and design that.

> Just look at the stunts the puppet-elasticsearch module needs to pull for index template management

Puppet in most cases works to manage and maintain a single server. Multiply this by running a puppet agent on every server. 

Contrast with Elasticsearch which forms a cluster of individual nodes. The control layer for Elasticsearch is the _cluster_ - it is not a _node_. You ask a node to do work, and it forwards it throughout the cluster as necessary.

Logstash is moving towards this clustered approach - where the interface will be at a cluster level. I am leaving some details out for brevity (there are several tickets describing some ideas/approaches to clustering, api, etc that I haven't linked here), so I want to calm any instinct for having imagination run away from you to fill in the blanks of "How will I manage Logstash if only over API? or if only via a Cluster?" - we are working on solving these things. 

I spent 9 years as a full-time systems administrator before joining Elastic to focus on Logstash development. I have not forgotten how difficult some software is to maintain and operate. I do not want Logstash to be _harder_ to manage than it is today; it is our belief that adding API and later Clustering will make things easier, simpler, faster, and more reliable.

**Comment by yehosef** [comment]
I'm all in favor of the server/cluster approach (not that you were waiting for my approval ;)  I think it will open up significant possibilities (monitoring, logging, faster response time, change config in-flight,etc).

While I understand that json won't help with "input" vs "inpuut", the config format now also doesn't help with it.  But I have additional problems that I need to ensure the structure of the config is correct in addition to the syntax of the commands. If I could put it in a json editor, I could format the json and I think most of the problems would be more obvious.

As for comments - there are systems that just allow comments and use post-processors to clean it up - but that would defeat most of the purpose because it wouldn't even be valid json in the editor and I'll have errors.  And while you could provide your own extension to json to support comments, I would still be  a pain.  (If you want to propose a new JSON standard, that supposed comments, that might be  different approach. )What I've done in other contexts is add some other field like 

    {
        filter: {
            "#": "this is my comment",
            "mutate": "..."
        }
    }

That basically the parser knows that any time I encounter a field labeled "#" - ignore it.  I'm not sure if that's an option here, but it might work.

**Comment by talevy** [comment]
Although configuring a pipeline in JSON may be more simple and straighforward for simple pipeline, it gets complicated very quickly. Conditionals are rather difficult to describe in json (e.g. Ingest Pipelines had to leave it outside). Changes being worked on in master like LIR (https://github.com/elastic/logstash/pull/6708) will make this easier, but it doesn't mean this would be the right approach. If there are editor limitations around syntax, it is better to work on better Logstash config support in the editor, rather than using Json.

Closing since it is not necessarily the right thing to do moving forward.
