### ISSUE TITLE
Logstash v1.5.2 udp input fails to handle packages larger than 2048 bytes

### ISSUE THREAD

**Issue by SteamRiC** [elastic/logstash#3601]
We have a logstash instance with udp input and elasticsearch output running on our server and for some time now data going to one of the inputs failed. 
We found out that the problem was caused by one app that was sending large packets. After we restart logstash, it works fine for a few seconds but then the input gets blocked and doesn't accept any more logs.

After some debugging we managed to find out that packets larger than ~2048 bytes don't get logged.

To replicate:
This goes through
echo -n $(ruby -e "puts '{\"application\":\"test\", \"a\": \"' + 'a'*200 + '\"}'") | nc -4u -q1 localhost 5228

This doesn't
echo -n $(ruby -e "puts '{\"application\":\"test\", \"a\": \"' + 'a'*2200 + '\"}'") | nc -4u -q1 localhost 5228

our logstash input looks like this:
input {
  udp {
    port => 5228
    codec => json
    queue_size => 2000
    buffer_size => 16384
    workers => 5
  }
}

output    {
 elasticsearch {
      host => localhost
      workers => 10
      index => "logstash-%{+YYYY.MM.dd}"
    }
}

**Comment by dbrgn** [comment]
![img](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/2048_win.png/220px-2048_win.png)

**Comment by untergeek** [comment]
As this is a plugin-specific issue, would you please close this and re-open the issue at https://github.com/logstash-plugins/logstash-input-udp ?

Thank you.
