### ISSUE TITLE
When adding values to Event instances the class should handle the conditional add

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#3605]
Apply the 'tell don't ask' principle.
Turn this...

``` ruby
event["host"] = @host if !event.include?("host")
```

into this

``` ruby
event.or_equals("host", @host)
```

The method name could be called anything...

or_equals (literal translation)
store_when_unset
set_unless
add_if_unset
add_if_missing
insert (as opposed to update|replace)

**Comment by jordansissel** [comment]
+1 add_if_missing (or similar wording "set if missing" or something).

I'd like to see, in the long term, `Event#[]` and `Event#[]=` go way in favor of `#set(key, value)` and `#get(key)` also, but that's not necessary for this particular issue :)

**Comment by guyboertje** [comment]
In addition, while fixing a bug on the mutate filter, the ``` Event#[] ``` and ``` Event#[]= ``` methods provided a false sense that it was acting like a Hash.  However the ``` Event#[] ``` cannot be relied upon to deliver the exact same result as the Hash#[] call.

**Comment by guyboertje** [comment]
Redundant
