### ISSUE TITLE
Codecs should support 'target' option

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#3607]
It is often the case for input/filter plugins that a `target` configuration option is desired. This option will decode the source into a specific field of an event. This can be desirable to simplify processing, and provide strict segmentation of data and metadata. 

The current codec interface however does not support this. `Codec#decode` will yield a `LogStash::Event` with `@timestamp` and other metadata. There is no way to know if these `@` fields were in the source data that is being decoded or were injected into the event. There is, therefore, no safe way to decode data with a codec and know precisely which fields were in the original event.

I propose adding a `target` option to `Codec#decode`. This would make this functionality easy to implement in plugins. Unfortunately, due to the interface exposed in the Codec API this would need to be added to every existing codec plugin. 

Ideally, this refactor would also change the interface codec plugins use, expecting them to return `Hash` objects, not full `LogStash::Event` objects. I propose renaming all current plugins' `decode` methods to `decode_hash`, and having `LogStash::Codecs::Base#decode` wrap `decode_hash` to return a `LogStash::Event` and perform the `target` work internally.

**Comment by andrewvc** [comment]
This proposal sprang from the discussion here: https://github.com/logstash-plugins/logstash-input-http_poller/issues/13

**Comment by andrewvc** [comment]
To make this more practical and backward compatible I will create a new method `#decode_to_target(target, event)` so as to preserve backward compatibility. Any comment on this @suyograo @jordansissel @ph?

**Comment by ph** [comment]
I like the idea, having been in the `ruby-lumberjack` which has many block, removing the codec one would certainly make it clearer. I would go with `decode_to_target`,returning the hash would make things more flexible.

**Comment by kares** [comment]
most (supported) codecs now support `target`, closing
