### ISSUE TITLE
split current Logstash Event Object into own gem

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#3613]
For more modularity within the logstash core, it would be great to see the existing Logstash Event to be split out into its own gem that can possibly be swapped with another implementation.

**Comment by talevy** [comment]
possible name for gem in rubygems: `logstash-core-event`

**Comment by colinsurprenant** [comment]
+1 `logstash-core-event` since we started with `logstash-core` and logstash-core-event is a part of logstash-core and it will avoid having to deal *now-now* with the legacy logstash-event that still exists for historical reasons.

related to #3479

**Comment by jordansissel** [comment]
@colinsurprenant :+1: logstash-core-event

**Comment by talevy** [comment]
this is already been done
