### ISSUE TITLE
Issue with documentation and inserting logstash version

### ISSUE THREAD

**Issue by tyleriguchi** [elastic/logstash#3615]
![screen shot 2015-07-16 at 11 10 50 am](https://cloud.githubusercontent.com/assets/5283926/8731311/5b3e24e8-2bab-11e5-908b-a89ec2c534fb.png)

The {logstash_version} variable isn't being injected properly into the doc. Found on this page https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html

**Comment by suyograo** [comment]
@tyleriguchi thanks will fix right away!

**Comment by suyograo** [comment]
@tyleriguchi this has been fixed. Thanks for the report!

**Comment by tyleriguchi** [comment]
@suyograo Great, thanks!
