### ISSUE TITLE
File Input fails on Linux with NotImplementedError: block device detection unsupported or native support failed to load

### ISSUE THREAD

**Issue by yangxiaobin** [elastic/logstash#3619]
Using: Ubuntu 14.04.2, JDK 1.8.0_40, Logstash 1.5.2
NotImplementedError: block device detection unsupported or native support failed to load
       blockdev? at org/jruby/RubyFileTest.java:67
         device? at /data/log/logstash-1.5.2/vendor/bundle/jruby/1.9/gems/filewatch-0.6.4/lib/filewatch/helper.rb:67
  _sincedb_write at /data/log/logstash-1.5.2/vendor/bundle/jruby/1.9/gems/filewatch-0.6.4/lib/filewatch/tail.rb:233
   sincedb_write at /data/log/logstash-1.5.2/vendor/bundle/jruby/1.9/gems/filewatch-0.6.4/lib/filewatch/tail.rb:206
        teardown at /data/log/logstash-1.5.2/vendor/bundle/jruby/1.9/gems/logstash-input-file-1.0.0/lib/logstash/inputs/file.rb:152
     inputworker at /data/log/logstash-1.5.2/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.2.2-java/lib/logstash/pipeline.rb:202
     synchronize at org/jruby/ext/thread/Mutex.java:149
     inputworker at /data/log/logstash-1.5.2/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.2.2-java/lib/logstash/pipeline.rb:202
     start_input at /data/log/logstash-1.5.2/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.2.2-java/lib/logstash/pipeline.rb:170

config:
input {
file {
type => "mytest"
path => "/data/info.log"
}
stdin { }
}
output {
elasticsearch { host => "192.168.1.11" cluster => "elasticsearch11" }
stdout { codec => rubydebug }
}

**Comment by markwalkom** [comment]
What does your config look like?

**Comment by yangxiaobin** [comment]
input {
  file {
        type => "mytest"
        path => "/data/info.log"
  }
  stdin { }
}
output {
  elasticsearch { host => "192.168.1.11" cluster => "elasticsearch11" }
  stdout { codec => rubydebug }
}

**Comment by suyograo** [comment]
This is a known issue with Java 1.8. See the workaround suggested at the bottom of https://github.com/elastic/logstash/issues/3127#issuecomment-101068714

Dup issue #3127, closing
