### ISSUE TITLE
Docs: field reference should be documented in the "How to write a Logstash filter plugin"

### ISSUE THREAD

**Issue by EricDeveaud** [elastic/logstash#3620]
documentation on how to write a logstahs filter is clear and really helpful for  beginners 

there's one point that it is not covered is how to use the "%{fieldname}" syntax.

see: https://discuss.elastic.co/t/field-reference-syntax/25589/2

**Comment by untergeek** [comment]
We love documentation improvements.  Where would you put it?  You can click the edit pencil icon and submit documentation changes from within the document itself.

We do mention the need for using sprintf formatting in our [Configuring Logstash](https://www.elastic.co/guide/en/logstash/current/configuration.html#sprintf) page.

**Comment by EricDeveaud** [comment]
main concern in the plugin filter howto is which one from logstahs or from the plugin should take care of the sprintf formatting.

from my reading I thougth that "%{foo}" was interpreted//expanded//evaluated by logstash itself and then provided to the plugin as value.
Magnus Bäck pointed me that it should be the pluggin to take care of expansion. 

I'll try to edit the doc but with my english it may be more confusing than no doc ;-)
