### ISSUE TITLE
Improve docs for how to check for the presence of a field

### ISSUE THREAD

**Issue by timbunce** [elastic/logstash#3621]
In #2442 a simple example was added to the docs, but the example is ambigious.

The patched doc says "You can test whether a field was present, regardless of its value".
People used to dynamic languages will not be helped much by that wording because it doesn't explicitly clarify if the expression is true even if the value of the field is false (like 0, an empty string, or undef/nil).

Please extend to wording to clarify he behaviour if the _value_ of the field is false.

**Comment by dedemorton** [comment]
The documentation was updated awhile back (for a different issue), but the fix resolves this issue, too, so I'm closing this very old issue.

The clarification is in the doc [here](https://www.elastic.co/guide/en/logstash/5.0/event-dependent-configuration.html#conditionals) and says:

You can check for the existence of a specific field, but there’s currently no way to differentiate between a field that doesn’t exist versus a field that’s simply false. The expression if [foo] returns false when:

    [foo] doesn’t exist in the event,
    [foo] exists in the event, but is false, or
    [foo] exists in the event, but is null
