### ISSUE TITLE
Elasticsearch protocol "Transport" Errors

### ISSUE THREAD

**Issue by AGirin** [elastic/logstash#3626]
Hi!

We recently switched from "node" ES connection to "transport". We started seeing this events after that:

{:timestamp=>"2015-07-20T08:55:21.343000-0500", :message=>"Failed to flush outgoing items", :outgoing_count=>14, :exception=>org.elasticsearch.client.transport.NoNodeAvailableException: No node available, :backtrace=>["org.elasticsearch.client.transport.TransportClientNodesService$RetryListener.onFailure(org/elasticsearch/client/transport/TransportClientNodesService.java:263)", "org.elasticsearch.client.transport.TransportClientNodesService.execute(org/elasticsearch/client/transport/TransportClientNodesService.java:231)", "org.elasticsearch.client.transport.support.InternalTransportClient.execute(org/elasticsearch/client/transport/support/InternalTransportClient.java:106)", "org.elasticsearch.client.support.AbstractClient.bulk(org/elasticsearch/client/support/AbstractClient.java:147)", "org.elasticsearch.client.transport.TransportClient.bulk(org/elasticsearch/client/transport/TransportClient.java:360)", "org.elasticsearch.action.bulk.BulkRequestBuilder.doExecute(org/elasticsearch/action/bulk/BulkRequestBuilder.java:165)", "org.elasticsearch.action.ActionRequestBuilder.execute(org/elasticsearch/action/ActionRequestBuilder.java:85)", "org.elasticsearch.action.ActionRequestBuilder.execute(org/elasticsearch/action/ActionRequestBuilder.java:59)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:207)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:207)", "LogStash::Outputs::ElasticSearch.flush(/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315)", "LogStash::Outputs::ElasticSearch.flush(/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219)", "org.jruby.RubyHash.each(org/jruby/RubyHash.java:1339)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193)", "RUBY.buffer_initialize(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112)", "org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1521)", "RUBY.buffer_initialize(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110)"], :level=>:warn}

We are running ES 1.7 and Logstash 1.4.2. Tried it again ES 1.2.2 and had the same issue.

Can anybody provide some light on this?

Thanks!

Andrew

**Comment by suyograo** [comment]
Can you move this to https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
