### ISSUE TITLE
Date filter not working - 1.5.2

### ISSUE THREAD

**Issue by rumikjain** [elastic/logstash#3632]
I am trying to configure the date filter for logstash 1.5.2 as per the documentation https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html

My config file as follows.

input {
  file {
    path => "/path-to-server/logs/server1/services-trace*.log"
    start_position => beginning
    }
}

filter {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:Time} - \[*.* : %{NUMBER:WebContainer}\] \[*.*:%{DATA:SessionId}\] %{DATA:logLevel} %{DATA:className} \(*.*:%{DATA:line}\) %{GREEDYDATA:logMessage}" }
    add_field => [ "received_at", "%{@timestamp}" ]
    add_field => [ "received_from", "%{host}" ]
    }

date {
match => ["Time", "YYYY-MM-dd;HH:mm:ss.SSS"]
  }

}

output {
  elasticsearch {
    host=>"myElastic-ipAddress"
    port=>9200
    protocol=>http
    index => "logstash-hnv-syslog-%{+YYYY.MM.dd}"
  }
}

But it is giving me below error.
The error reported is:
  Couldn't find any filter plugin named 'date'. Are you sure this is correct? Trying to load the date filter plugin resulted in this error: no such file to load -- logstash/filters/date

Please help.

**Comment by barakSpoj** [comment]
Hey,

Go to the logstash bin folder and run:
plugin list
You'll get a list of the plugins installed, make sure "logstash-filter-date" is there,
If not, run:
plugin install logstash-filter-date

**Comment by rumikjain** [comment]
Thanks for the update but I already tried that but there is nothing named 'plugin' available in my 'bin' folder. hence giving me the error  as below : 

$ plugin install logstash-filter-date
$ plugin: command not found

FYI :- I am using logstash 1.5.2 linux 64bit version.

Please suggest.

**Comment by barakSpoj** [comment]
Can you copy to here your logstash directory hierarchy?
How did you install logstash on your machine?

**Comment by suyograo** [comment]
what distro of Linux? I can't reproduce this in 1.5.2 or 1.5.3. Also can you move this to https://discuss.elastic.co/c/logstash. We'll help you debug there. Github is mainly used for issues/enhancements. Thanks!
