### ISSUE TITLE
New Jdbc Filter Plugin

### ISSUE THREAD

**Issue by pafq** [elastic/logstash#3633]
This plugin allow to execute JDBC Querys with input from the "INPUT" and the previous executed query.

This plugin was develop to respond to this forum Post "https://discuss.elastic.co/t/how-to-get-jdbc-data-from-multiple-queries/25631".

The configuration format for this plugin is the same (with another options) for this Jdbc Input Plugin that I allready submit a Pull Request (https://github.com/logstash-plugins/logstash-input-jdbc/pull/30)

I'm new with Ruby and don't know how to program the Test batery needed to submit plugin under your rules.

This any information is needed please contact me.

Source Code: https://github.com/pafq/logstash-filter-jdbc

**Comment by dadoonet** [comment]
I wonder if this plugin is similar to https://github.com/logstash-plugins/logstash-filter-jdbc_static/ ?

**Comment by jsvd** [comment]
@dadoonet ++ we can close this, we have both jdbc streaming and static filter plugins.
