### ISSUE TITLE
logstash locking file and preventing deletion on a windows machine

### ISSUE THREAD

**Issue by trekr5** [elastic/logstash#3639]
Hello,

I'm hoping someone can help me with this...

I've got logstash running on a windows machine. The logs from logstash are then transferred to an AWS S3 bucket using an S3 plugin (which is essentially a Ruby script).

Part of the plugin which deletes the logs from the local machine isn't working and I've been attempting to debug it. When I look at the log file to see why it isn't deleting, I can see that it is locked by a logstash Java process and even if I try to force delete the log, after the log has been uploaded to an S3 bucket, it will not be deleted.

I'm wondering if anyone else has had a similar situation and if so how did they fix it.

Many thanks

**Comment by suyograo** [comment]
@trekr5 can you move this to https://discuss.elastic.co/c/logstash. We can help you debug there! Github is mainly used for issues/enhancements. Thanks :)
