### ISSUE TITLE
logrotation - Error: string not matched

### ISSUE THREAD

**Issue by pts0** [elastic/logstash#3641]
When rotating log file I get the error "A plugin had an unrecoverable error. Will restart this plugin." and logstash stop processing input chain.

**How to reproduce**
1. stop logstash
2. remove .sincedb file
3. clean watched logdata folders
4. start logstash
5. move log file with contents to watched folder with name `my.log`

```
{"uuid":"46b0d6c9-560e-41d8-a318-9999999999"}
```
1. wait until file is picked up from logstash and then simulate rotation

```
echo "" > my.log
```
1. wait again until processed and then put some contents again in file

```
echo '{"uuid":"46b0d6c9-560e-41d8-a318-9999999999"}' >   my.log
```
1. You get then in logstash log file following exception every 3s and processing stops

```
{:timestamp=>"2015-07-23T11:13:46.021000+0200", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::File codec=><LogStash::Codecs::JSON charset=>\"UTF-8\">, path=>[\"/var/log/foobar/*.log\"], start_position=>\"beginning\", debug=>false, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, delimiter=>\"\\n\">\n  Error: string not matched", :level=>:error}

```

**Config:**

```
input {
    file {
        codec => json {
            charset => "UTF-8"
        }
        path =>  ["/var/log/foobar/*.log"]
        start_position => beginning
    }
}


output {
  stdout { }
}

```

logstash version 1.5.1 and 1.5.3

with logstash 1.4.2 all works without errors.

**Comment by zaakiy** [comment]
+1.  Same issue when using json file. Using json_lines codec and json filter.

**Comment by samdoran** [comment]
+1. I'm seeing this is well using the `json` codec with the `file` input module on Logstash 1.5.3-1.

**Config:**

```ruby
    file {
        path => "/var/log/remote/**/*.syslog.json.log"
        sincedb_path => "/opt/logstash/sincedb/sincedb_syslog"
        exclude => [ "*.gz" , "postfix-*" , "dkimproxy\.out-*" ]
        start_position => "beginning"
        codec => "json"
        tags => [ "syslog" ]
        type => "syslog"
    }
```

**Error:**

     {:timestamp=>"2015-08-05T11:13:14.779000-0400", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::File path=>[\"/var/log/remote/**/*.syslog.json.log\"], sincedb_path=>\"/opt/logstash/sincedb/sincedb_syslog\", exclude=>[\"*.gz\", \"postfix-*\", \"dkimproxy\\\\.out-*\"], start_position=>\"beginning\", codec=><LogStash::Codecs::JSON charset=>\"UTF-8\">, tags=>[\"syslog\"], type=>\"syslog\", debug=>false, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, delimiter=>\"\\n\">\n  Error: string not matched", :level=>:error}

**Comment by samdoran** [comment]
I'm also wondering if this has to do with the number of files the glob matches. The glob in my config should match 7,713 files. When I run `lsof -u logstash | grep '\.json\.log'` it only has 741 files open.

Immediately after the plugin crashes, that number drops down to 71. Those 71 files that Logstash keeps open are from other `file` input specifications in the same config. Looks like loading a huge glob causes the plugin to crash, but a glob that matches a smaller number of files is ok.

**Comment by pts0** [comment]
Hi, 
I don't think have relationship with number of files. We was tracking open files too, is true number of open files is increasing as soon as you rotate files, but we stripped down all to reproduce it with 1 file, very small file.
Maybe we miss an important information, we are running on SuSE Enterprise linux and with latest java version 1.8u45.
pts0

**Comment by samdoran** [comment]
I'm running on CentOS 6.6 with Java 1.7.0_85

**Comment by marcelhallmann** [comment]
Any news here?

**Comment by pts0** [comment]
logstash 1.5.5 and 2.0.0 I was not able to reproduce. 
Issue has been resolved ?
