### ISSUE TITLE
File input plugin: Automatic deletion of processed files

### ISSUE THREAD

**Issue by pueffl** [elastic/logstash#3643]
We are currently evaluating the ELK-Stack for our company and discussed how to handle a network failover or how to recover from a crash somewhere in the ELK-Stack in the most simple way. We came to the conclusion, that this would be to configure Log4j2 with a FailoverAppender and just write all log events in a file in that case. 
When everything is ok again, we would like to copy the failover-files to a directory where Logstash picks them up and processes the according events. The problem we see here is, that we don't know about the status of the processing (we are talking about 70-100 applications and probably hundreds of files). So what we would like to have is an additional configuration options 'delete_processed' or something like that, so that every processed file is automatically deleted (it would also possible to move the finished file somwhere else). At least we think such a behavior could be of great value for some specific situations  :-)

**Comment by kares** [comment]
Closing this old timer, file input these days has a [`file_completeted_action => delete`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-file_completed_action) (default)
