### ISSUE TITLE
Wrong links when trying to edit http and irc input plugin documentation.

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/logstash#3648]
The links to edit http plugin documentation at https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html points to the https://github.com/logstash-plugins/logstash-input-irc/edit/master/lib/logstash/inputs/irc.rb and the irc in the documentation points to http on GitHub.

**Comment by jordansissel** [comment]
Confirmed.

**Comment by suyograo** [comment]
Fixed
