### ISSUE TITLE
TCP input triggers "OpenSSL::SSL::SSLError: certificate verify failed" on LS-1.5.3

### ISSUE THREAD

**Issue by ayashjorden** [elastic/logstash#3650]
Hi,
Today I tried to upgrade from Logstash 1.5.2 to 1.5.3. Both versions were installed using package repository.
Our logstash machine is an OpenVZ container running Debian7, 8GB memory, 3GB allocated for Logstash.
Java version:
```
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

After installing 1.5.3, I installed environment filter plugin.
Logstash configuration consists of a Lumberjack and TCP input, several filters and 5 ES outputs which use the ```transport``` protocol.

The error occurred on the TCP input which accept TLS connections from our CDN log shippers:
```
{:timestamp=>"2015-07-26T15:20:15.661000+0000", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: certificate verify failed>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:238:in `accept'", "/opt/logstash/vendor/jruby/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:142:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:182:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:170:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:177:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:171:in `start_input'"], :level=>:error}
``` 
In order to clarify things, both 1.5.2 and 1.5.3 installations used the same SSL crt/key pair.
This issue is different than #3644 as here the SSL error is triggered in the TCP input and not in the Lumberjack input (which worked perfectly with Logtash-Forwarder 0.4.0).

Testing the TLS connection with ```openssl s_client LOGSTASH_153_IP:PORT``` connected successfully , unfortunately I didn't copy the connection output.

I had to downgrade back to 1.5.2 until this issue is resolved.

Thanks,
Yarden

**Comment by jordansissel** [comment]
Can you attach your logstash config?

**Comment by ayashjorden** [comment]
Hi @jordansissel ,
Below is my LS configuration:
```
input {
    lumberjack {
        host            => "LS_HOST_IP"
        port            => 5230
        ssl_certificate => '/ssl/logstash-forwarder.crt'
        ssl_key         => '/ssl/logstash-forwarder.key'
    }
    tcp {
        port => 5514
        type => "CDN"
        ssl_cert => "/ssl/logstash-forwarder.crt"
        ssl_key => "/ssl/logstash-forwarder.key"
        ssl_enable => true
        codec => line {
            charset => "ISO-8859-1"
        }
    }
}
filter {
# Grok filters for Postfix, CDN, Nginx and application logs
# General structure is:
if [type] == “<SOME_TYPE>” {
# process message with grok and other filter types.
}
}
output {
    if [@metadata][type] in [ "postfix", "CDN"] {
        elasticsearch {
            host     => [ "ES_HOST_IP" ]
            protocol => "transport"
            port     => "9300"
            cluster  => "elasticsearch"
            index    => "%{[@metadata][type]}-%{+YYYY.MM.dd}"
            document_type => "%{[@metadata][type]}"
            manage_template => false
        }
    } 
**# 3 more elasticsearch outputs to handle the rest of the event types.**
    else {
        file {
            path => "/var/log/logstash/unknown_messages.log"
        }
    }
}
```

Hope it helps,
Yarden

**Comment by suyograo** [comment]
@ayashjorden we are releasing 1.5.4 with this fix. Sorry for the inconvenience!

**Comment by derSascha** [comment]
Hi,

can you please release v1.4.5 soon too?!

A simple ,,apt-get upgrade'' breaks everything otherwise all the time...

Thanks!

**Comment by suyograo** [comment]
1.5.4 and 1.4.5 has been released
