### ISSUE TITLE
JSON filter doesn't support messages containing a message entry

### ISSUE THREAD

**Issue by RikACESDirect** [elastic/logstash#3651]
I'm using this configuration:
```
input {
  rabbitmq{
        type => "rabbitMQ"
        host => "somevalidip"
        passive => true
        queue => "somevalidqueue"
  }

}
filter{
  if [type] == "rabbitMQ"{
    json{
      source => "message"
    }
  }
}
output {
        elasticsearch {
                cluster => "logstash"
        }
}
```
A message like this enters the queue:
```
{"message":"Error sending to salesforce [null]: SOME ERROR MESSAGE "}
```
Which results in the following warning:
```
Trouble parsing json {:source=>"message", :raw=>"Error sending to salesforce [null]: SOME ERROR MESSAGE ", :exception=>#<LogStash::Json::ParserError: Unrecognized token 'Error': was expecting ('true', 'false' or 'null')
 at [Source: [B@745cabe9; line: 1, column: 7]>, :level=>:warn, :file=>"logstash/filters/json.rb", :line=>"96", :method=>"filter"}
```
A _jsonparsefailure tag and an unparsed entry in my elasticsearch database. This seems to be caused by the message entry. Because when I change my message to be:

```
{"test":"Error sending to salesforce [null]: SOME ERROR MESSAGE "}
```

it works as expected. I cannot change the format of the messages provided to me at the source. How can I make this work?

**Comment by wiibaa** [comment]
Sorry that it is not correctly represented in the documentation, but by default rabbitmq already use the **json codec** not the plain, so calling the json filter afterwards is misleading you, you must remove it from your config.
Documentation issue is logged as https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/26
Also please prefer https://discuss.elastic.co/c/logstash to discuss usage and questions and keep Github Issues focused on confirmed bugs and feature requests.
Cheers

**Comment by RikACESDirect** [comment]
Thank you! Removing the filter has fixed the issue. For those interested my config file now is:

```
input {
  rabbitmq{
        type => "rabbitMQ"
        host => "somevalidip"
        passive => true
        queue => "somevalidqueue"
  }
}
output {
        elasticsearch {
                cluster => "logstash"
        }
}

```
I didn't know about the discuss site. I will refer to that one first in the future.
