### ISSUE TITLE
Please Update Logstash 1.5 Repository

### ISSUE THREAD

**Issue by kaihawaii84** [elastic/logstash#3653]
Hey Logstash Guy's,

please update the Centos Repositories with Logstash 1.5.3:
http://packages.elasticsearch.org/logstash/1.5/centos

At the moment you can get only the 1.5.2 Release

Cheers,
Kai

**Comment by suyograo** [comment]
@kaihawaii84 thanks, we are looking into it now.

**Comment by jordansissel** [comment]
I cannot confirm this.

```
[root@2871735762ef ~]# yum list available logstash
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * extras: mirrors.xmission.com
 * updates: centos.sonn.com
Available Packages
logstash.noarch                                                                                1:1.5.3-1                                                                                logstash-1.5
```

@kaihawaii84 Are you sure you're using the right repo? Can you show me your logstash repo file from yum? Are you out of date and need to update the repo metadata?

Try this:

Run:
* `yum clean all`
* `yum list available logstash`

Can you attach the output of the `yum list available logstash` command _after_ running `yum clean all` ?

**Comment by kaihawaii84** [comment]
Hi Jordan,

we are using http://spacewalk.redhat.com/ and doing a sync every night and it went very well with dozens of other repos.
In general we expected that we can look after the packages via http like in this repository:
http://dl.fedoraproject.org/pub/epel/7/x86_64/

instead there is a error message:
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>logstash/1.5/centos</Key>
<RequestId>FEFDEBE5225F4760</RequestId>
...

maybe you have an advice for me.
Tank you!

**Comment by suyograo** [comment]
@kaihawaii84 not sure we support http://spacewalk.redhat.com/
