### ISSUE TITLE
Add section in ref docs to handle multiline logs 

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3659]
We need to clarify when to use multiline filter and multiline codec. There are concerns about thread safety and ordering of events which needs to be clearly addressed.

Related: https://github.com/elastic/logstash/issues/1808

**Comment by MarkusMayer** [comment]
@suyograo Some input from a user's perspective. Both the existence and the difference between multiline codec and multiline filter was something that confused me completely when I started out using logstash's multiline features. More docs / examples on that would be really cool. Something that also tripped me up was the effects of the periodic flush settings (the defaults changed in some previous version I think).

just my 2c.

**Comment by suyograo** [comment]
@MarkusMayer thanks for your feedback! We'll address these

**Comment by palecur** [comment]
PR #3784 is up to handle this; feedback is coming in and am updating to reflect it.

**Comment by palecur** [comment]
PR replaced by #3832.
