### ISSUE TITLE
Syslog example in doc does not parse PRI properly

### ISSUE THREAD

**Issue by peterskim12** [elastic/logstash#3661]
I could be missing something but just reviewing by inspection, it looks like the example provided in this config doc doesn't account for the pri field:

https://www.elastic.co/guide/en/logstash/current/config-examples.html#_processing_syslog_messages

It includes the syslog_pri filter but I don't think the syslog_pri filter would do anything because the preceding grok filter doesn't parse out a syslog_pri field.

**Comment by jordansissel** [comment]
Agreed. The docs look incorrect there. Good catch!

**Comment by palecur** [comment]
PR #4359 is up to correct this.
