### ISSUE TITLE
concurrent ruby warning received when starting LS 1.5.3

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3662]
From https://discuss.elastic.co/t/getting-a-warning-while-using-the-latest-version-of-logstash-1-5-3/26379

`Warning received : '[DEPRECATED] use require 'concurrent' instead of require 'concurrent_ruby'`

**Comment by ThomasdOtreppe** [comment]
It can be reproduced with stdin input and elasticsearch output with the following command:
```
/opt/logstash/bin/logstash -e 'input { stdin { } } output { elasticsearch { } }'  --configtest
```

And the output on Ubuntu 14.04.2 64bit server (with LS 1.5.3 coming from Elastic repositories) is the following:
```
'[DEPRECATED] use `require 'concurrent'` instead of `require 'concurrent_ruby'`
[2015-07-28 12:36:15.152]  WARN -- Concurrent: [DEPRECATED] Java 7 is deprecated, please use Java 8.
Java 7 support is only best effort, it may not work. It will be removed in next release (1.0).
Configuration OK
```

**Comment by ph** [comment]
Fix is done for the `output-elasticsearch` in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/215

**Comment by ph** [comment]
Also this is a similar error https://github.com/logstash-plugins/logstash-input-lumberjack/pull/39

**Comment by ph** [comment]
also fixed in https://github.com/logstash-plugins/logstash-input-syslog/pull/19
