### ISSUE TITLE
LS 1.5.3 fail to start when user and password fields are set

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/logstash#3663]
With the following config, the issue can be reproduced:
```
input {
        http {
                user => "logstash"
                password => "logstash"
        }
}

filter {
}

output {
        stdout { }
}
```

And just running logstash with that config file:
```
/opt/logstash/bin/logstash -f logstash.conf
```

It returns the following:
```
The error reported is:
  uninitialized constant LogStash::Inputs::Http::Base64
```

It works just fine when user/pass fields aren't used.

System: Ubuntu 14.04.2 64bit server
Logstash: 1.5.3 coming from the elastic.co repositories

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-http/pull/18. Dup of https://github.com/logstash-plugins/logstash-input-http/issues/17

@ThomasdOtreppe this is available in 1.0.2 of logstash-input-http. You can simply do:

`bin/plugin update logstash-input-http`
