### ISSUE TITLE
Can we have separate filter for separate panel in Dashboard ?

### ISSUE THREAD

**Issue by vg15** [elastic/logstash#3664]
Since we do not have this feature in Kibana 4 or above so I am raising this feature request. What I can see is while clicking on object/row or pie chart it will immediately add a global filter which affects the overall dashboard or panels.What I want is to apply filter on lets say first panel only ? So rather global what if someone wants filter on single dashboard panel ? 

Thanks
VG

**Comment by suyograo** [comment]
Please open an issue here: https://github.com/elastic/kibana/issues
