### ISSUE TITLE
gelf input accepts connection from localhost but not from ip

### ISSUE THREAD

**Issue by hex6ng** [elastic/logstash#3666]
## Logstash Input Configuration

    input {
      gelf {}
    }

## Telnet Test

    [root@localhost ~]# telnet localhost 12201
    Trying ::1...
    Connected to localhost.
    Escape character is '^]'.
    Connection closed by foreign host.
    [root@localhost ~]# telnet 192.168.1.149 12201
    Trying 192.168.1.149...
    telnet: connect to address 192.168.1.149: Connection refused

**Comment by suyograo** [comment]
Moved to https://github.com/logstash-plugins/logstash-input-gelf/issues/16
