### ISSUE TITLE
Specifying custom tags via LS command

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#3668]
This can be achieved today by updating every LS config for the LS instance to add tags to the event.  It will be nice if there is a LS-instance level feature allowing custom tags to be added via the LS command (which applies to all configurations run by the LS-instance).

**Comment by ppf2** [comment]
Here is a nice trick/workround which allows adding of a filter passed in via `-e` to the list of existing filters in the configuration. thx @kurtado !

```
bin/logstash -e 'filter {mutate{add_field => {"dc" => "us-east-1"}}}' -f logstash.conf
```

**Comment by jordansissel** [comment]
You can probably do this with environment variables?

```
filter {
  mutate {
    add_field => { "dc" => $DATACENTER }
  }
}
```

I'm content with this solution as folks are using this already today.

Can we close this?

**Comment by ppf2** [comment]
Yep, resolved by the GA of environment variables feature in 5.0+. thx!
