### ISSUE TITLE
[DOCS] Fix the old names in link 

### ISSUE THREAD

**Issue by johtani** [elastic/logstash#3669]
logstash-plugin has many old names in their README.md, such as https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/17

**Comment by suyograo** [comment]
@ph can we do a mass update?

**Comment by ph** [comment]
Yes we can do that, I don't think its worth doing a release of each plugin.

**Comment by ph** [comment]
Review this artefact generated by the script and I'll do the mass update: 
https://github.com/logstash-plugins/logstash-codec-avro/pull/10/files

**Comment by ph** [comment]
Done in a mass update script on august 26 2015.
