### ISSUE TITLE
Jdbc input plugin: Add predefined parameters and format them.

### ISSUE THREAD

**Issue by golabk** [elastic/logstash#3673]
It will be useful for build query statement with predefined parameters
sql_last_end - the last time a statement was finished.
sql_current_start - the current time a statement was started.

Also, will be useful, if the parameters can be converted to specific output format.
e.g.
parameters_format => [
  "name", "format", "time_zone"
]
name - parameter name
format - parameter output format
time_zone - optional and can be specified with name or utc_offset

parameters_format => [
  "sql_current_start", "%H:%M:%S", "",
  "sql_last_start", "%d/%m/%Y %H:%M:%S", "+09:00",
  "sql_last_end", "%Y-%m-%dT%H:%M:%S", "CST"
]

**Comment by suyograo** [comment]
Can you please open this in jdbc repo? https://github.com/logstash-plugins/logstash-input-jdbc/issues
