### ISSUE TITLE
http output error with OpsGenie

### ISSUE THREAD

**Issue by wastedepository** [elastic/logstash#3675]
I'm testing sending JSON data via the http output to OpsGenie. When using the appropriate OpsGenie URL, I get a strange error that doesn't happen when sending the data to other services. The exception data for this error is

*:exception=>#<OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure>, :stacktrace=>["org/jruby/ext/openssl/SSLSocket.java:195:in `connect_nonblock'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:413:in `do_secure'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:393:in `secure'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:449:in `connect'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:283:in `execute'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-http-1.0.0/lib/logstash/outputs/http.rb:126:in `receive'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):168:in `output_func'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:244:in `outputworker'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}*

The data is never received by OpsGenie. Sending JSON data via curl works without problems.

I'm using Logstash 1.5.3; the same error occurs with the older Logstash 1.5.0.

http filter:

    http {
        http_method => "post"
        url => "https://api.opsgenie.com/v1/json/alert"
    }

**Comment by suyograo** [comment]
Moved to https://github.com/logstash-plugins/logstash-output-http/issues/15
