### ISSUE TITLE
logstash 1.5.3 - java version checking - how to allow a known good version?

### ISSUE THREAD

**Issue by dougmcclure** [elastic/logstash#3677]
I've reviewed issue #2547 and get what's trying to be achieved.  Have we thought of an easy way to allow a java version that's known to be good?  Can this check be disabled, updated with a known pattern for something like IBM Java in my case?

bin/logstash agent -f foo.conf --pluginpath MyPlugins/ --verbose

NoMethodError: undefined method `captures' for nil:NilClass
        parse_java_version at /opt/logstash153/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/util/java_version.rb:33
         bad_java_version? at /opt/logstash153/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/util/java_version.rb:51
  warn_on_bad_java_version at /opt/logstash153/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/util/java_version.rb:10
                      main at /opt/logstash153/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/runner.rb:32
                    (root) at /opt/logstash153/lib/bootstrap/environment.rb:48

This is what I get from IBM Java. Maybe we can add a simple "allow IBM Java" if IBM J9 VM is detected or inspect more closely and look for "based on Oracle 7u51-b11".

java -version

java version "1.7.0"
Java(TM) SE Runtime Environment (build pxa6470sr6fp1-20140108_01(SR6 FP1))
IBM J9 VM (build 2.6, JRE 1.7.0 Linux amd64-64 Compressed References 20140106_181350 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR6_20140106_1601_B181350
JIT  - r11.b05_20131003_47443.02
GC   - R26_Java726_SR6_20140106_1601_B181350_CMPRSS
J9CL - 20140106_181350)
JCL - 20140103_01 based on Oracle 7u51-b11

Tks!  A quick work around would be appreciated so I can test LS153 out in my environments.

**Comment by suyograo** [comment]
@andrewvc maybe we can extract the known Java versions to a separate file that can be updated outside of the release artifact? @jordansissel ideas?

**Comment by andrewvc** [comment]
@suyograo I'm inclined to keep that in code for flexibility. It gets tricky to create a definitions file if there's a single bad release for instance. 

In this case I'm inclined to just fix the issue of the regexp not matching, assume all IBM JVMs are OK, and move on. Perhaps printing a warning at the same time.

**Comment by andrewvc** [comment]
By the way, thanks for finding this @dougmcclure ! I'm on it :)

**Comment by suyograo** [comment]
@andrewvc sounds good!

**Comment by suyograo** [comment]
@andrewvc would love to get it for 1.5.4 which is almost ready to ship!

**Comment by dougmcclure** [comment]
thanks a ton!

**Comment by andrewvc** [comment]
@dougmcclure I'm going to push a patch out to just ignore this. Do you have a minute to just try running `jruby -e 'puts java.lang.System.getProperty("java.runtime.version")'` ?

**Comment by suyograo** [comment]
Fixed by #3685

**Comment by dougmcclure** [comment]
$ bin/jruby -v
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 IBM J9 VM 2.6 on
pxa6470sr6fp1-20140108_01 (SR6 FP1) +jit [linux-amd64]

$ bin/jruby -e 'puts java.lang.System.getProperty("java.runtime.version")'
pxa6470sr6fp1-20140108_01 (SR6 FP1)

./java -version
java version "1.7.0"
Java(TM) SE Runtime Environment (build pxa6470sr6fp1-20140108_01(SR6 FP1))
IBM J9 VM (build 2.6, JRE 1.7.0 Linux amd64-64 Compressed References
20140106_181350 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR6_20140106_1601_B181350
JIT  - r11.b05_20131003_47443.02
GC   - R26_Java726_SR6_20140106_1601_B181350_CMPRSS
J9CL - 20140106_181350)
JCL - 20140103_01 based on Oracle 7u51-b11

**Comment by andrewvc** [comment]
Thanks @dougmcclure . Boy, is that a beast of a version string :)

**Comment by dougmcclure** [comment]
show me your regex/grok skills! :-)

**Comment by rolweber** [comment]
I'm trying logstash-1.5.4 on Windows with an IBM JDK, and I'm still hitting this problem.
Output is from a cygwin bash:

$ ./vendor/jruby/bin/jruby -e 'puts java.lang.System.getProperty("java.runtime.version")'
io/console not supported; tty will not be manipulated
pwi3270sr9fp10-20150708_01 (SR9 FP10)

$ "$JAVA_HOME/bin/java" -version
java version "1.7.0"
Java(TM) SE Runtime Environment (build pwi3270sr9fp10-20150708_01(SR9 FP10))
IBM J9 VM (build 2.6, JRE 1.7.0 Windows 7 x86-32 20150701_255667 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR9_20150701_0050_B255667
JIT  - tr.r11_20150626_95120.01
GC   - R26_Java726_SR9_20150701_0050_B255667
J9CL - 20150701_255667)
JCL - 20150628_01 based on Oracle jdk7u85-b15

**Comment by rolweber** [comment]
Reading the original description more thoroughly, it's not the exact same thing I'm doing. But the result is pretty close:


$ ./bin/logstash -e 'input { stdin { } } output { stdout { } }'
io/console not supported; tty will not be manipulated
NoMethodError: undefined method `[]' for nil:NilClass
         bad_java_version? at C:/projects/ELK/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/util/java_version.rb:57
  warn_on_bad_java_version at C:/projects/ELK/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/util/java_version.rb:11
                      main at C:/projects/ELK/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/runner.rb:31
                    (root) at C:\projects\ELK\logstash-1.5.4\lib\bootstrap\environment.rb:49

**Comment by andrewvc** [comment]
@rolweber tha

**Comment by andrewvc** [comment]
@rolweber thanks for reporting this. The initial patch was incorrect, we'll get one out in the next release.

**Comment by suyograo** [comment]
Fixed by https://github.com/elastic/logstash/pull/3824
