### ISSUE TITLE
Allow finer logging configuration for config compilation, pipeline and plugin system

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#3692]
Logging levels should be configurable per subsystem, and by subsystem I mean:
* configuration compilation
* pipeline
* plugins

For example, this would allow a person to start logstash only with debug level for the plugins.
Currently "--debug" is somewhat cumbersome to use due to amount of information it outputs, specially at the beginning.

**Comment by suyograo** [comment]
@jsvd have you seen this? https://github.com/elastic/logstash/issues/2040

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5651
