### ISSUE TITLE
Provide a mechanism for dumping unsuccessful events to file

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3697]
The Elasticsearch output has seen a lot of issues from users recently with Logstash stalled or retrying after unsuccessful attempts of indexing. In 1.5, we introduced retry logic to handle transient failures from bulk requests, and this may have surfaced more user frustration. This problem exists in general in Logstash, where in we retry constantly (by design) for events which were unsuccessful. In #2607 we proposed a dead letter queue (DLQ) to handle such *unsuccessful* or *poison* events. DLQ has a dependency on persistent queue infrastructure (#2605) which is targeted for 2.0.

In the interim, we should have a solution to shunt or redirect poison events to a file which would allow Logstash pipeline to continue processing subsequent events. This will also help shutdown issue (#3451) until we have the DLQ. 

Specifically:

* Pluggable DLQ: Provide a general interface to abstract the logic of sending rogue events from outputs
* Each plugin provides its own expectation of when an event is *rogue* and can be shunted. For example, in ES output, mapping errors.
* As a first implementation, use a file-per-output to store these events. Make it optional (feature flagged). Also need to provide config to rotate the file based on size/age.
* Having a file based store allows users to use the file input and json codec to reprocess the events if necessary.
* Once persistent queue is ready (#2605) make it the default implementation of the DLQ.
* Having a pluggable interface allows users to plug-in Kafka or external queues until we have the in-built DLQ.

This was proposed by @talevy and @jsvd during the discussions of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/144 and #3451 

Thoughts?

**Comment by jsvd** [comment]
@suyograo I think we can close this in favor of #2607

**Comment by suyograo** [comment]
Continuing the discussion in #2607
