### ISSUE TITLE
Trying setting up ELK stack

### ISSUE THREAD

**Issue by glandorf23** [elastic/logstash#3700]
hi im new to this,
so many guides are available,
but every single is special in part,
i installed elasticsearch, logstash and the forwarder,
then when i start logstash on the server,
with simple direct output and saving to ES,
checking ES works too with
http://172.16.50.66:9200/_search?pretty
works,
then with conf file       
bin/logstash -f logstash1.conf
its gettin startet,
ok kibana or "something to view" i decited to install later,
want to have it running first without kibana ( if thats possible)
i installed forwarder on client 
when i try starting the forwarder,
[root@localhost /]# /opt/logstash-forwarder/bin/logstash-forwarder -config /opt/logstash-forwarder/bin/forwarder.conf
2015/08/05 14:10:03.882581      --- options -------
2015/08/05 14:10:03.882981      config-arg:          /opt/logstash-forwarder/bin/forwarder.conf
2015/08/05 14:10:03.883016      idle-timeout:        5s
2015/08/05 14:10:03.883028      spool-size:          1024
2015/08/05 14:10:03.883039      harvester-buff-size: 16384
2015/08/05 14:10:03.883049      --- flags ---------
2015/08/05 14:10:03.883059      tail (on-rotation):  false
2015/08/05 14:10:03.883069      log-to-syslog:          false
2015/08/05 14:10:03.883080      quiet:             false
2015/08/05 14:10:03.883588
  "network": {
    "servers": [ "172.16.50.66:5000" ],

    "ssl_certificate => "/etc/ssl/logstash.crt"
    "ssl_key => "/etc/ssl/logstash.key"

    "timeout": 15
  },

  "files": [
    {
      "paths": [
        "/var/log/*.log",
        "/var/log/messages"
      ],
      "fields": { "type": "syslog" }
    }, {
      "paths": [ "/var/log/apache2/access.log" ],
      "fields": { "type": "apache" }
    }
  ]
}
2015/08/05 14:10:03.884474 Failed unmarshalling json: invalid character ':' after top-level value
2015/08/05 14:10:03.884492 Could not load config file /opt/logstash-forwarder/bin/forwarder.conf: invalid character ':' after top-level value

i think i pasted all paths right i think,
in the logstash-forwarder.err
i took this:
seems like client want to connect, but its not allowed?
i opened on both client and server all nessesary ports,

logstash-forwarder.err:
2015/08/05 14:26:25.827708 Failure connecting to 172.16.50.66: dial tcp 172.16.50.66:5000: connection refused
2015/08/05 14:26:26.829432 Connecting to [172.16.50.66]:5000 (172.16.50.66) 
2015/08/05 14:26:26.829731 Failure connecting to 172.16.50.66: dial tcp 172.16.50.66:5000: connection refused
2015/08/05 14:26:27.831514 Connecting to [172.16.50.66]:5000 (172.16.50.66) 
2015/08/05 14:26:27.831954 Failure connecting to 172.16.50.66: dial tcp 172.16.50.66:5000: connection refused
2015/08/05 14:26:28.833471 Connecting to [172.16.50.66]:5000 (172.16.50.66) 
2015/08/05 14:26:28.833777 Failure connecting to 172.16.50.66: dial tcp 172.16.50.66:5000: connection refused

i tried so much on configure the settings, and still not working :(
can someone help :S ?
sorry for my bad english :)
glan

**Comment by glandorf23** [comment]
on server:
[root@localhost logstash]# firewall-cmd --zone=public --list-all
public (default, active)
  interfaces: eth0
  sources:
  services: dhcpv6-client http ssh
  ports: 9200/tcp 9300/tcp 5000/tcp
  masquerade: no
  forward-ports:
  icmp-blocks:
  rich rules:

on client:
firewall-cmd --zone=public --list-all
public (default, active)
  interfaces: eth0
  sources:
  services: dhcpv6-client http ssh
  ports: 5000/tcp
  masquerade: no
  forward-ports:
  icmp-blocks:
  rich rules:

seems ports are open right?

**Comment by purbon** [comment]
HI @glandorf23 , If I understand you properly you have more a question of how to make this work than an known issue, right? I guess the best place to submit this is at https://discuss.elastic.co/c/logstash where you will leverage the power of the community, logstash devs included, to get a proper answer to this? makes sense? 

let me know if I can close this.

/cheers

- purbon

**Comment by glandorf23** [comment]
sure thanks for info
knew a bit im wrong here :P

**Comment by purbon** [comment]
so I will close the issue and you will post the question at discuss, ok? Feel free to open any other issue if you encounter problems while working with logstash!! 

Thanks!
