### ISSUE TITLE
_discover_file_glob

### ISSUE THREAD

**Issue by vhdevera** [elastic/logstash#3703]
hi,
i'm trying to configure logstash to receive cloudtrail files but for testing purposes we locally stored a json file and use this as an input. i'm following this http://techblog.mdsol.com/2014/01/27/parsing-amazon-cloudtrail-json-logs-with-a-customized-logstash-build.html but when i ran 
java -jar logstash-1.4.07.dev.medidata-flatjar.jar agent -f /etc/logstash/conf.d/combined.conf --debug

Automatic template management enabled {:manage_template=>"true", :level=>:info, :file=>"/etc/logstash/conf.d/logstash-1.4.07.dev.medidata-flatjar.jar!/logstash/outputs/elasticsearch_http.rb", :line=>"104"}
Template Search URL: {:template_search_url=>"http://localhost:9200/_template/*", :level=>:debug, :file=>"/etc/logstash/conf.d/logstash-1.4.07.dev.medidata-flatjar.jar!/logstash/outputs/elasticsearch_http.rb", :line=>"112"}
_discover_file_glob: /etc/logstash/conf.d/cloudtrail.json: glob is: ["/etc/logstash/conf.d/cloudtrail.json"] {:level=>:debug, :file=>"/etc/logstash/conf.d/logstash-1.4.07.dev.medidata-flatjar.jar!/filewatch/watch.rb", :line=>"117"}

researching i found this to be related to permission and deletig .sincedb* file but this didn't help and i'm kind of stuck at this point.

**Comment by suyograo** [comment]
We've fixed a lot of issues in 1.5 related to sincedb. Could you please try with that?

**Comment by suyograo** [comment]
Closing this, please reopen this issue if it happens in 1.5.4
