### ISSUE TITLE
Strange log  redis-input

### ISSUE THREAD

**Issue by rfyiamcool** [elastic/logstash#3704]
### bug ，In kibana html ，i find the following information  !

```
@timestamp      August 6th 2015, 17:15:15.572
t@version       1
t_id        AU8CSwuJVE0qPYRSd5FT
t_index     logstash-2015.08
t_source        {"message":"key_count","@version":"1","@timestamp":"2015-08-06T09:15:15.572Z","type":"redis-input"}
t_type      redis-input
tmessage        key_count
ttype       redis-input
```
### My logstash server config is

```
input {
        redis {
                host => "123123123123"
                port => 6379
                type => "redis-input"
                data_type => "list"
                key => "key_count"
        }
}


output {
        elasticsearch {
                host => "123123"
                protocol => "http"
                port => 9000
                index => "logstash-%{+YYYY.MM}"
                workers => 5
        }

#         stdout { codec => rubydebug }     \# stdout  result    is OK

}
```

**Comment by rfyiamcool** [comment]
root@wx-social-server02:~/logstash-1.4.2# tcpdump -i eth1 -vv -X port 9000|grep key_count
tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
	0x0130:  6167 6522 3a22 6b65 795f 636f 756e 7422  age":"key_count"
	0x01e0:  223a 226b 6579 5f63 6f75 6e74 222c 2240  ":"key_count","@
	0x0290:  6b65 795f 636f 756e 7422 2c22 4076 6572  key_count","@ver
	0x0490:  7361 6765 223a 226b 6579 5f63 6f75 6e74  sage":"key_count
	0x0540:  6522 3a22 6b65 795f 636f 756e 7422 2c22  e":"key_count","
	0x05f0:  226b 6579 5f63 6f75 6e74 222c 2240 7665  "key_count","@ve
	0x08a0:  6765 223a 226b 6579 5f63 6f75 6e74 222c  ge":"key_count",
	0x0950:  3a22 6b65 795f 636f 756e 7422 2c22 4076  :"key_count","@v
	0x0c00:  6167 6522 3a22 6b65 795f 636f 756e 7422  age":"key_count"
	0x0cb0:  223a 226b 6579 5f63 6f75 6e74 222c 2240  ":"key_count","@
	0x0d60:  6b65 795f 636f 756e 7422 2c22 4076 6572  key_count","@ver
	0x0f60:  7361 6765 223a 226b 6579 5f63 6f75 6e74  sage":"key_count
	0x1010:  6522 3a22 6b65 795f 636f 756e 7422 2c22  e":"key_count","
	0x10c0:  226b 6579 5f63 6f75 6e74 222c 2240 7665  "key_count","@ve
	0x1370:  6765 223a 226b 6579 5f63 6f75 6e74 222c  ge":"key_count",

**Comment by suyograo** [comment]
what exactly is the issue? Can you please explain in detail?

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
