### ISSUE TITLE
Logstash shutting down with exception related to opentsdb

### ISSUE THREAD

**Issue by harshamadala** [elastic/logstash#3706]
Logstash is shutting down with below exception, I am using opentsdb output plugin. I read that each output plugin should run in different thread and whenever it times out it should retry or in worst case it should just kill output thread. But this is not happening in my case, please help.

Opentsdb output configuration:
output {
        if [responsetime] {
                opentsdb {
                        host => "opentsdb_ip"
                        port => "4343"
                        metrics => ["%{component}.responsetime",
                                        "%{responsetime}",
                                        "host",
                                        "%{host}"
                                        ]
                }
        }
}

Exception i am getting:
"IOError: Connection timed out
          write at org/jruby/RubyIO.java:1412
          write at org/jruby/RubyIO.java:2490
           puts at org/jruby/RubyIO.java:2380
        receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-opentsdb-1.0.0/lib/logstash/outputs/opentsdb.rb:87
         handle at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88
    output_func at (eval):242
   outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:244
  start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:166"

**Comment by kares** [comment]
issue was output plugin (`opentsdb`) related, closing
