### ISSUE TITLE
Pipeline performance degradation when JSON parser is given a string that is not parseable

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#3707]
NOTE: this issue describes an abnormal situation that we can't do much about other that inform.

If the source line is not one of:
- {<some object internals>}
- [<some array internals>]
- "string"
- true
- false
- number
- null
  then the Json parser will raise an exception, which we handle but it slows everything down.
  The original input still flows down the pipeline however.

This raise rescue behaviour is normal.

All we can do is document it.  Perhaps later when we have internal metrics the user can be warned that the processing rate has deteriorated from 'normal'.

**Comment by jordansissel** [comment]
Agreed. Is the performance cost just the raise, though? I have vague memories that exceptions in Ruby (and JRuby) can easily hamper performance if use commonly in a critical path. Is it worth experimenting with the parser implementation to return some some kind of "Nope, not json!" sigil instead of raising an exception -- to see the performance differences?

**Comment by guyboertje** [comment]
Unfortunately the raise comes from inside Jackson Java.  We could preprocess the string to evaluate the parse-ability of it, but I don't like that idea.  BTW, Ruby JSON gem also raises parse errors for true/false/number and null.

**Comment by jordansissel** [comment]
@guyboertje agreed on most parser's current behaviors regarding exceptions. Documenting this problem for now should be enough, +1 on the idea :)

**Comment by guyboertje** [comment]
@jordansissel @suyograo - how do I document this externally? So I can close this issue.

**Comment by palecur** [comment]
@guyboertje I'll handle the documentation update.

**Comment by guyboertje** [comment]
Ahh, thanks very much Paul, you, sir, are a diamond geezer!
