### ISSUE TITLE
`groksample.log` link broken in documentation

### ISSUE THREAD

**Issue by selesse** [elastic/logstash#3714]
At https://www.elastic.co/guide/en/logstash/current/parsing-into-es.html, there's a broken link reference to `tbd.co/groksample.log`.

The commit that introduced it is 4e8bd0f15ad02e9d066d7954021e31206c5d6b4d.

I would have liked to submit a pull request to fix the link, but the `groksample.log` doesn't seem to be in the repository. :)

**Comment by purbon** [comment]
Yay! good finding. As far as I could grasp, the content of that file would have been a set of apache logs, but tbh this should be hosted internally so we don't have broken links.

Thanks for spotting it!

**Comment by palecur** [comment]
That sample was superseded by a specific, hosted Logstash tutorial, and that page no longer appears, so this ticket is moot. Closing thereby.
