### ISSUE TITLE
Logstash file reading `require concurrent` instead `require concurrent_ruby`

### ISSUE THREAD

**Issue by rafik991** [elastic/logstash#3719]
Hi All, I am getting below error after starting fresh logstash 1.5.3.
My elasticsearch on localhost is running fine.
Am I missing something?
I didn't find useful posts about that. 

It is working fine when I use standard input, but I want to read logs from file.

root@vz37980:~/elk/logstash-1.5.3# ./bin/logstash -f test.conf 
'[DEPRECATED] use `require 'concurrent'` instead of `require 'concurrent_ruby'`
NotImplementedError: block device detection unsupported or native support failed to load
       blockdev? at org/jruby/RubyFileTest.java:67
         device? at /root/elk/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/filewatch-0.6.4/lib/filewatch/helper.rb:67
  _sincedb_write at /root/elk/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/filewatch-0.6.4/lib/filewatch/tail.rb:233
   sincedb_write at /root/elk/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/filewatch-0.6.4/lib/filewatch/tail.rb:206
        teardown at /root/elk/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-input-file-1.0.0/lib/logstash/inputs/file.rb:152
     inputworker at /root/elk/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:203
     synchronize at org/jruby/ext/thread/Mutex.java:149
     inputworker at /root/elk/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:203
     start_input at /root/elk/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:171
Aug 11, 2015 6:42:05 PM org.elasticsearch.common.MacAddressProvider getSecureMungedAddress
WARNING: Unable to get a valid mac address, will use a dummy address

test.conf:

input {
  file {
    path => "/var/teamcity/buildserver/system/artifacts/Msc/All_Builds/578/server.log"
    start_position => beginning
  }
}

filter {
  if [path] =~ "access" {
    mutate { replace => { "type" => "apache_access" } }
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
}

output {
  elasticsearch {
    host => localhost
  }
  stdout { codec => rubydebug }
}

**Comment by colinsurprenant** [comment]
Hi @rafik991, thanks for reporting this. Could you share your `test.conf` and the platform & JVM you are running logstash on?

**Comment by suyograo** [comment]
@rafik991 the deprecation issue is benign, you can ignore it for now. We are fixing it in 1.5.4

> NotImplementedError: block device detection unsupported or native support failed to load
blockdev? at org/jruby/RubyFileTest.java:67

For this issue, see the fix in https://github.com/elastic/logstash/issues/3127#issuecomment-101068714
It is not a Logstash specific issue, but an OS/Java specific nuance.

**Comment by colinsurprenant** [comment]
to clarify: you can ignore the deprecation warning:
```
[DEPRECATED] use require 'concurrent' instead of require 'concurrent_ruby'
``` 

but it is not related to the *blockdev* error, which is a separate issue as noted by @suyograo 

```
NotImplementedError: block device detection unsupported or native support failed to load
blockdev?
```

**Comment by colinsurprenant** [comment]
@rafik991 let us know if the fix in #3127 works for you and  if we can close this issue.

**Comment by rafik991** [comment]
ok, I will check but in the meanwhile I've added test.conf

**Comment by kavithasrinu** [comment]
hi, I am new to ELK so I am have a log file in my local system and trying to filter only the top ten ip addresses from the file what I should have to fill in the filter block
