### ISSUE TITLE
Logstash Truck Factor

### ISSUE THREAD

**Issue by gavelino** [elastic/logstash#3720]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Logstash** and obtained a value of **1**.

The developer responsible for this TF is:

Jordan Sissel - author of 60% of the files

To validate our results, we would like to ask **Logstash** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Logstash**?

(b) Do you agree that **Logstash** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Logstash** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by suyograo** [comment]
Hi @gavelino thanks for your analysis. Its an interesting approach and perspective.

## Background
Logstash is part of [Elastic](http://www.elastic.co), the company behind popular open source projects such as [Elasticsearch](https://github.com/elastic/elasticsearch), [Kibana](https://github.com/elastic/kibana), and [Beats](https://github.com/elastic/packetbeat). As such, we in the Logstash team share the same philosophies and engineering culture as our other projects. @polyfractal has [provided](https://github.com/elastic/elasticsearch/issues/12726#issuecomment-128749831) an excellent background into Elastic's engineering culture in your question about Elasticsearch's bus factor, so I will not repeat it here. Everything he mentions in that reply applies here 100%.

## Specifically to address Logstash related questions:

> (a) Do you agree that the listed developer is the main developer of Logstash?
> (b) Do you agree that Logstash will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

Jordan Sissel is the architect and tech lead of the Logstash project. He still contributes code and product ideas, but he is one among the many developers of Logstash. For the 1.5 release, Jordan contributed less code than 1.4, and the trend continues for the recent maintenance releases on 1.5, and 1.6, which is our next feature release. Jordan focuses his energy and time on [high level roadmap](https://www.elastic.co/guide/en/logstash-roadmap/current/index.html), mentors other developers, reviews Pull Requests and is deeply involved in the community.

Colin, Joao, PH, Pere, Aaron and Tal over the last year have significantly contributed to Logstash's code base. I would consider them core contributors. 

For example, Colin, has contributed more code recently (last year) than Jordan has https://github.com/elastic/logstash/commits/master?author=colinsurprenant

We also get significant contributions from Philippe Webber, Joseph Lawson and many others.

#### Plugins split
In 1.5, the Logstash core repository was split and all plugin code were extracted into individual [repositories](https://github.com/logstash-plugins). This is another reason the truck factor mentioned here does not fully reflect Logstash's trajectory. We have multiple contributors across the 190+ plugin repositories available. In fact, the number of [new plugins](https://github.com/elastic/logstash/labels/new-plugin) developed by contributors recently provides evidence this project is not dependent on a single person. It is a thriving ecosystem

> (c) Does Logstash have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Again, alluding to @polyfractal's reply: We take knowledge sharing very seriously. If you look at our pull requests, we share the development load across team members. Developers are constantly rotated and encouraged to contribute to different areas/functionality of this product. We believe in clean code, strong testing culture, invest a lot of time and energy in mentoring new developers.

**Comment by wiibaa** [comment]
@suyograo as question is answered, can you please close
