### ISSUE TITLE
Date/timezone does not accept grok created fields

### ISSUE THREAD

**Issue by chandlermelton** [elastic/logstash#3726]
Using logstash version 1.5.3:
date    { match => [ "timestamp", "yyyy MMM dd HH:mm:ss" ] timezone => "%{timezone}" }

will results in: 
{:timestamp=>"2015-08-12T13:42:27.381000-0500", :message=>"Error: Cannot register filter date plugin. The error reported is: \n  The datetime zone id '%{timezone}' is not recognised for pattern 'yyyy MMM dd HH:mm:ss'"}

when:
timezone = UTC, America/Chicago, etc.

**Comment by wiibaa** [comment]
This is a known issue registered in the plugin repository => https://github.com/logstash-plugins/logstash-filter-date/issues/23

A possible workaroud is explained in https://github.com/elastic/logstash/issues/1685#issuecomment-54278158 

Can you please close this issue to avoid duplicated report, thanks

**Comment by vishwastyagi** [comment]
Hi Everyone,
I am not to use date filter like the way mentioned above.
Help is required.
I have an xml which I am pushing into elasticsearch from logstash

2016-09-23

My filter is:

filter{

mutate {
add_field => [ "nginx_timestamp", "/RECORD/DATE/text()" ]
}
date {
match => [ "nginx_timestamp", "yyyy-MM-dd" ]
}
mutate {
remove_field => [ "nginx_timestamp" ]
}

}

I am getting warning in logstash saying:

"Failed parsing date from field {:field=>"nginx_timestamp", :value=>"/RECORD/DATE/text()", :exception=>"Invalid format: \"/RECORD/DATE/text()\"", :config_parsers=>"yyyy-MM-dd", :config_locale=>"default=en_IN", :level=>:warn}
"

And kibana is showing current date in @timestamp

Please help if I am missing anything.
