### ISSUE TITLE
logstash forwarder error with special caracters

### ISSUE THREAD

**Issue by ibizista** [elastic/logstash#3730]
Hello, 

I have a problem with logstash forwarder.

Versions:
Ubuntu 14.04
logstash 1.5.3

When i send a log with special caracter like ñ or á the parse dont work and shows in logstash.stdout the error:

[0] "_grokparsefailure"

The same log in a local file work fine.
The locale in logstash forwarder is en_US.UTF-8 and the locale in logstash server  is es_ES.UTF-8

The config of forwarder:

{
      "paths": [
        "/var/log/varnish/varnishncsa-.log"
       ],
      "fields": { "type": "varnish-nsca" }
    }

The config in the server:

input {
  lumberjack {
    port => 5000
    type => "logs"
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
    }
  }
}

I´ve read that is it a fix for old version 1.5, but i´ve using the newest version 1.5.3.
Thank you a lot

**Comment by ibizista** [comment]
Update:

I´ve tried to change locale in the logstash forwarder to spanish, the same problem.
I´ve tried to change locale in the logstash server to english, the same problem.

But i´ve installed logstash forwarder in other servers, with the same OS and locales, and all works fine... Logstash parse the same line correctly in the other servers

O_o

Any idea?

**Comment by suyograo** [comment]
Our recommendation is to move to Filebeat, which has a ton of new enhancements and fixes. Filebeat is being actively maintained as well.
