### ISSUE TITLE
KV filter multi-character field/value splitters

### ISSUE THREAD

**Issue by fcntl** [elastic/logstash#3732]
For the KV filter the value_split/field_split options are characters that "...form a regex character class". This means they are only single characters.

Please turn this into a full REGEX and not a character class, as this would allow multi-character delimiters and avoid having to reserve 2 ASCII characters (only 128 of them) for them, and make the KV filter a lot less fragile.

People can still use character classes inside the REGEX if they really have multiple delimiters values for field and value splitting.

**Comment by purbon** [comment]
@fcntl As I told you https://github.com/elastic/logstash/issues/3581#issuecomment-131028600, I recommend you move this issue to the KV filter repo (https://github.com/logstash-plugins/logstash-filter-kv) where all issues are track for this particular plugin.
