### ISSUE TITLE
Add /robots.txt to logstash.net website host

### ISSUE THREAD

**Issue by eran-pinhas** [elastic/logstash#3734]
Currently google (and I guess the rest web search engines too) finds the NOT latest version when searching for some documentation. and I think it's not the way it should be.

The solution for this is adding the file robots.txt in the root of the host. currently [http://logstash.net/robots.txt](http://logstash.net/robots.txt) returns 404.

thanks :)

**Comment by suyograo** [comment]
Related to https://github.com/elastic/logstash/issues/3410
