### ISSUE TITLE
logstash 1.5.3 on windows won't read custom patterns

### ISSUE THREAD

**Issue by nickak** [elastic/logstash#3736]
Hi, 

logstash 1.5.3 on windows won't read custom patterns file
I use patterns_dir
grok{
			patterns_dir => "C:/devtools/logstash-1.5.3/patterns"

it works only when I put the patterns file in 
C:\devtools\logstash-1.5.3\vendor\bundle\jruby\1.9\gems\logstash-patterns-core-0.1.10\patterns

best regards

**Comment by purbon** [comment]
This looks to me like an issue to be reported in the patterns-core repo (https://github.com/logstash-plugins/logstash-patterns-core) where all this things are living and happening. Do you mind reopening the issue there?

**Comment by nickak** [comment]
Ok, reopened it in https://github.com/logstash-plugins/logstash-patterns-core and i'm closing this one
