### ISSUE TITLE
Logstash with .pdf files

### ISSUE THREAD

**Issue by poonaminfor** [elastic/logstash#3741]
Logstash is converting .pdf files text into some unreadable format something like:
\x8C\xC9\"\xB3qDx\u001C9\u0011\t\x84p<N\x99ޙ\x8D\xB6v\x9Fv\
How can I read whole .pdf in one single event in readable format from Kibana?

**Comment by purbon** [comment]
@poonaminfor can you explain a bit more what you are doing? are you sending pdf (binary) data throw LS?

**Comment by poonaminfor** [comment]
I tried LS with below setting
input { 
file {
    path  => "//usalwalqadata1/eservice/knowbase/es/root/DLPublic/**/*.pdf"
	type=> "test1"
	start_position =>"beginning"  
	
	
    
  }
  
}
filter {
  multiline {
    type => ".pdf"
    pattern => "^\n"
    what => "next"
	negate=>false
  }
}

output {
  elasticsearch{  
     type=>"test1"  
    host => localhost
    port => "9200"
	protocol => "http"
    cluster => "elasticsearch_dev"
    node_name => "devnode"
	index =>"QA_Kbs"
	index_type =>"QA"
    }

  stdout { codec => rubydebug }
}
=======================================
This did not work as required,so I tried with NEST also:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Nest;
using Newtonsoft.Json;
using System.IO;




namespace WebApplication1
{
    public class Person
    {
        public string Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    }
    [ElasticType(
   Name = "document"
  )]
    public class Document
    {
        public int Id { get; set; }

        [ElasticProperty(Store = true)]
        public string Title { get; set; }

        [ElasticProperty(Type = FieldType.Attachment,
            TermVector = TermVectorOption.WithPositionsOffsets)]
        public string Content { get; set; }
        public string ContentType { get; set; }
    }
    public partial class _Default : System.Web.UI.Page
    {
      
        protected void Page_Load(object sender, EventArgs e)
        {
           
           
   

            string index = "myindexdoc";

            var node = new Uri("http://localhost:9200");
            var settings = new ConnectionSettings(
                node,
               defaultIndex: "myindexdoc"
            );

            var client = new ElasticClient(settings);

            // delete index if any
            client.DeleteIndex(index);

          //  var index = client.Index(person);
            string path = "D:\\examples\\LTM10020CriticalUpdate10NetChangeReport.pdf";
            var doc = new Document()
            {
                Id = 1,
                Title = "test",
                Content =Convert.ToBase64String(File.ReadAllBytes(path)),
                ContentType = "application/pdf"

            };
            client.Index(doc);
        }
    }
}


=====================================================
These content feed are not searchable,like if I have "test" text in pdf  m notable to search it.Its something like:
	
\x8C\xC9\"\xB3qDx\u001C9\u0011\t\x84p<N\x99ޙ\x8D\xB6v\x9Fv\

**Comment by markwalkom** [comment]
Logstash cannot process PDF files. You will need to use something like [Apache Tika](https://tika.apache.org/) to do this.

**Comment by poonaminfor** [comment]
can I do it with NEST or I need to use java coding for that?I am basically from .net background.Can i get Any sample with NEST.

**Comment by markwalkom** [comment]
Not sure, that's not my area of knowledge.

However please join us in #logstash on Freenode or at https://discuss.elastic.co/ for troubleshooting help or general questions. 
We reserve Github for confirmed bugs and feature requests :)
