### ISSUE TITLE
Logstash-1.5.3 | load error: win32ole

### ISSUE THREAD

**Issue by JamesFischer-Stark** [elastic/logstash#3747]
I am using the Logstash1.5.3 release and still see this issue. 
![error1](https://cloud.githubusercontent.com/assets/13470204/9313984/1dcd97e4-44f4-11e5-9d63-fb309968c8e4.PNG)
![simple-conf](https://cloud.githubusercontent.com/assets/13470204/9313985/1eb47056-44f4-11e5-92d1-6c15fcb539a8.PNG)

Java Environment: 
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by wiibaa** [comment]
@JamesFischer-Stark from the screenshot, this is not a windows machine, right ? As mentioned in previous ticket thread https://github.com/elastic/logstash/issues/1733#issuecomment-63014286, eventlog input only run on windows currently

**Comment by JamesFischer-Stark** [comment]
yes this is a ELK stack running on Ubuntu14.04.3. after reviewing the https://www.elastic.co/guide/en/logstash/current/plugins-inputs-eventlog.html
I did not realize that when it said pulls from windows event logs it meant while on a windows machine. That is my fault then. 

My goal is to create a logstash.conf file for indexing windows evtx files from the locahost. I saw the eventlog plugin and began following instructions to install and when failed began following cases to try workarounds. 

I apologize for this miscommunication.

**Comment by suyograo** [comment]
@JamesFischer-Stark we'll make sure the docs reflect this! https://github.com/logstash-plugins/logstash-input-eventlog/issues/17

Thanks for the spot, @wiibaa!

**Comment by JamesFischer-Stark** [comment]
I kind of feel embarrassed lol for going to the issue board for something that was not intended to work. Though is there any way to process old windows event log files through logstash? Proper Syntax for a logstash.conf file to be used.

Thank you all for help!

**Comment by suyograo** [comment]
@JamesFischer-Stark hey, no worries! all questions welcome :)

if you have captured the event log in a file, you can use the file input to ingest those into LS. See https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html
