### ISSUE TITLE
Plugins installed from local .gem file do not install dependencies

### ISSUE THREAD

**Issue by seang-es** [elastic/logstash#3748]
A customer has reported a problem installing a plugin.  The gemspec for the new plugin contains a dependency for a non-logstash gem.  The installation reports a successful completion, but the plugin does not exist in the 'plugin list', and will not work if used in Logstash.  The dependency gem is not installed after the plugin installation completes.

**Comment by ph** [comment]
This is not a problem with logstash, but a problem with the gemspec definition for that specific plugin.
It's mandatory to add the **gemspec physical file** to the available files in the definition, without this bundler cannot generate the dependency graph.
```
  s.files = Dir.glob("lib/**/*rb") + Dir.glob("*.gemspec")
```
