### ISSUE TITLE
ISO8601 simple zone designator error

### ISSUE THREAD

**Issue by shindu** [elastic/logstash#3750]
I have a gork parsing error at TIMESTAMP_ISO8601 if I have timestamps with a simple zone designator e.g. 2015-08-17T18:19:50.569+02 does not work.

**Comment by shindu** [comment]
Workaround is to change the grok pattern of ISO8601_TIMEZONE.
From: ISO8601_TIMEZONE (?:Z|[+-]%{HOUR}(?::?%{MINUTE}))
To: ISO8601_TIMEZONE (?:Z|[+-]%{HOUR}?(?::?%{MINUTE}))

**Comment by suyograo** [comment]
Hi, can you please post this question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
