### ISSUE TITLE
Logstash 1.3.3 flat jar out of memory issue

### ISSUE THREAD

**Issue by murthym** [elastic/logstash#3760]
Hi,
I am using logstash 1.3.3 flat jar on solaris and seeing out of memory issues on production environment.

I have gone through this on jira https://logstash.jira.com/browse/LOGSTASH-2168.

I am afraid I cannot upgrade to the higher version other than 1.3.3 which I believe is compatible with the solaris version we are using

Could you please advice how should I add the patch or import the fix on the flat jar 1.3.3?

We have plans to deploy logstash on other set of production servers and this is based on how stable the version 1.3.3 is. So I need to know if this version really works or I need to move to a different version.

Any information would be really helpful.

Thanks in anticipation.

Regards,
Mohan

**Comment by jordansissel** [comment]
Same response as your question you posted on [this ticket](https://github.com/elastic/logstash/issues/1295#issuecomment-133071749)

----

1.3.x is not worked on anymore and does not receive any more bug fixes. Recommend you upgrade.

If you cannot upgrade, backporting that patch is possible, but I don't have any particular advice and I don't know how complex it will be to backport. Good luck! :)

**Comment by murthym** [comment]
Thanks Jordan for the quick reply.

Could you please let us know which is the latest version compatible with solaris servers?

We had tried 1.4.x but had seen jruby compatible issues.

Regards,
Mohan

**Comment by jordansissel** [comment]
I don't know. We don't test on Solaris at this time. We try to keep Solaris working, but currently have no energy invested in maintaining that so we rely on the community effort to help us find, fix, and test problems on that platform.

**Comment by murthym** [comment]
Thanks Jordan.

I will try backporting this fix  on 1.3.3 

https://github.com/elastic/logstash/commit/7b6ab95124cb1b4107e15ae78aeb2e4e4bb4c6d9.
