### ISSUE TITLE
mutate => lowercase empties content of field

### ISSUE THREAD

**Issue by andrejohansson** [elastic/logstash#3770]
In logstash 1.5.4 the following lines will cause my hostname field to become null/empty:
```
  mutate {
    lowercase => [ "hostname" ]
  }
```
Same lines worked in 1.5.3 and if I remove them  my field gets valued. Note that the hostname field in my case can come from a previously renamed field:

```
  mutate {
    rename => { "Hostname" => "hostname" }
    rename => { "machineName" => "hostname" }
    rename => { "MachineName" => "hostname" }
    rename => { "logsource" => "hostname" }    
  }
```

**Comment by jsvd** [comment]
@andrejohansson so you're renaming potential (that may not exist) hostname fields into the hostname field?

**Comment by jsvd** [comment]
can you provide the whole config file @andrejohansson ?

**Comment by jsvd** [comment]
My test with 1.5.4 went well:

```
/tmp/logstash-1.5.4 % cat config
input {
  generator {
    count => 1
    add_field => ["Test", "OMG"]
  }
}
filter {
  mutate {
    rename => ["hamburguers", "test"]
    rename => ["Test", "test"]
    rename => ["potatoes", "test"]
    lowercase => "test"
  }
}
output {
  stdout { codec => rubydebug }
}

/tmp/logstash-1.5.4 % bin/logstash -f config
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2015-08-21T11:18:43.521Z",
          "host" => "Joaos-MBP.lan",
      "sequence" => 0,
          "test" => "omg"
}
```

**Comment by andrejohansson** [comment]
Yes, I have multiple input sources which name the "hostname" field differently and I want to align them to one field. As I mentioned, this worked in version 1.5.3. The renaming part works in both 1.5.3 and 1.5.4. 

But the lowercase that follows part empties the hostname field. This is the section that breaks if I uncomment the lowercase filter:
```
  # Rename fields coming from different sources to align them better in the kibana ui
  # This is case sensitive
  mutate {
    rename => { "Host" => "host" }
    rename => { "Message" => "message" }
    rename => { "Hostname" => "hostname" }
    rename => { "machineName" => "hostname" }
    rename => { "MachineName" => "hostname" }
    rename => { "Severity" => "levelname" }
    rename => { "param1" => "source" }
    rename => { "logsource" => "hostname" }    
  }

# Keep commented until this is resolved: https://github.com/elastic/logstash/issues/3770
  # always lowercase hostnames
#  mutate {
#    lowercase => [ "hostname" ]
#  }
```

I can't put the full file here in public but i could email it to you if you contact me at my first and lastname at lexmark.com.

**Comment by suyograo** [comment]
Being tracked here: https://github.com/logstash-plugins/logstash-filter-mutate/issues/44

**Comment by derjohn** [comment]
+1 here. I use mutate with replace => and lowercase => . Since Upgrading from 1.5.2 to 1.5.4 I see the value "null" in ES.

**Comment by daveres** [comment]
I have the same behaviour after upgrade to 1.5.4 too.

mutate {
	gsub => ["uri","/","%2f"]
	lowercase => [ "uri","querystring" ]
}

Enviroment:
- Windows 2012 R2
- Java 1.8.0_51

**Comment by skokhanovskiy** [comment]
I have same issue with uppercase
```
                grok {
                        match => [ "source", "nlog://%{HOSTNAME:Hostname}/%{GREEDYDATA:LogName}" ]
                }
                # Broken in ver 1.5.4
#               mutate {
#                       uppercase => [ "Hostname" ]
#               }
```

**Comment by barchus** [comment]
same issue here, program field empty after :

mutate {
  lowercase => [ "program" ]
}

logstash 1.5.4-1

**Comment by jsvd** [comment]
version 1.0.2 was released with the fix done in logstash-plugins/logstash-filter-mutate#44
closing this issue. please reopen if you still seeing this after upgrading the plugin

**Comment by daveres** [comment]
Thanks, it works now

**Comment by sassyn** [comment]
logstash 1:1.5.4-1 under ubuntu give the same error when using 
    mutate {
      uppercase => [ "host" ]
    }

Output is : 
              "host" => nil,

**Comment by derjohn** [comment]
@sassyn The fixup is not part of Logstash 1.5.4. Sadly, Elastic @rashidkpc  didn't release a 1.5.5 with the fixup. You have to manually update the plugin in 1.5.4.
