### ISSUE TITLE
Displayed error message when connect from logstash to logstash with using lumberjack

### ISSUE THREAD

**Issue by Masa-Tyler** [elastic/logstash#3775]
Please let me know solution/workagound for the below issue.

I built logstash-server(v1.5.3).
This logstash-server can recieve logs from logstash-forwarder(v0.4.0) on windows.
But the one cannot recieve logs from logstash(v1.5.4) with using lumberjack on windows.
The below is error message on command prompt.

---

C:\logstash-1.5.4\logstash-1.5.4\bin\logstash.bat agent -f C:\logstash-1.5.4\logstash-1.5.4\conf\logstash.conf
io/console not supported; tty will not be manipulated
Logstash startup completed
[31mClient write error, trying connect {:e=>#<RuntimeError: Whoa we shouldn't get this frame: >, :backtrace=>["C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.24/lib/lumberjack/client.rb:132:in `ack'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.24/lib/lumberjack/client.rb:120:in`write_sync'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.24/lib/lumberjack/client.rb:41:in `write'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-lumberjack-1.0.2/lib/logstash/outputs/lumberjack.rb:71:in`flush'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in`each'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:112:in`buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:110:in`buffer_initialize'"], :level=>:error}[0m
## [31mClient write error, trying connect {:e=>#<RuntimeError: Whoa we shouldn't get this frame: >, :backtrace=>["C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.24/lib/lumberjack/client.rb:132:in `ack'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.24/lib/lumberjack/client.rb:120:in`write_sync'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.24/lib/lumberjack/client.rb:41:in `write'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-lumberjack-1.0.2/lib/logstash/outputs/lumberjack.rb:71:in`flush'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in`each'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:112:in`buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "C:/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:110:in`buffer_initialize'"], :level=>:error}[0m

Also, the below is conf for logstash(v1.5.4)

---

input {
    eventlog {
    type  => 'Win32-EventLog'
    logfile  => ["Application", "Security", "System"]
    }
}

output {
    lumberjack {
        hosts => "IP address of logstash-server"
        port => xxxx
        ssl_certificate => ".\lumberjack.crt"
    }

**Comment by ph** [comment]
Small question here, are you using the same certificate on both the forwarder and the lumberjack output?

**Comment by Masa-Tyler** [comment]
Hi ph,

I are using the same certificate with the forwarder.
Do you know what cause ?

Regars,

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
