### ISSUE TITLE
Logstash 1.5.4 on OS X: Error: Permission denied - /var/lib/logstash/.XXX

### ISSUE THREAD

**Issue by Drewshg312** [elastic/logstash#3778]
Hi! I've upgraded to Logstash 1.5.4 on OS X. And now getting this error:

    $ /usr/local/bin/logstash agent -f /usr/local/etc/logstash/conf.d/logstash.conf
    A plugin had an unrecoverable error. Will restart this plugin.
      Plugin: <LogStash::Inputs::File path=>["/var/log/suricata/eve.json"], sincedb_path=>"/var/lib/logstash/", codec=><LogStash::Codecs::JSON charset=>"UTF-8">, type=>"SuricataIDPS", start_position=>"beginning", debug=>false, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, delimiter=>"\n">
      Error: Permission denied - /var/lib/logstash/.13472.87395.399540 {:level=>:error}
    Errno::EACCES: Permission denied - /var/lib/logstash/.13472.87395.203614
          initialize at org/jruby/RubyFile.java:363
                 new at org/jruby/RubyIO.java:853
        atomic_write at /usr/local/Cellar/logstash/1.5.4/libexec/vendor/bundle/jruby/1.9/gems/filewatch-0.6.5/lib/filewatch/helper.rb:33
      _sincedb_write at /usr/local/Cellar/logstash/1.5.4/libexec/vendor/bundle/jruby/1.9/gems/filewatch-0.6.5/lib/filewatch/tail.rb:235
       sincedb_write at /usr/local/Cellar/logstash/1.5.4/libexec/vendor/bundle/jruby/1.9/gems/filewatch-0.6.5/lib/filewatch/tail.rb:205
            teardown at /usr/local/Cellar/logstash/1.5.4/libexec/vendor/bundle/jruby/1.9/gems/logstash-input-file-1.0.1/lib/logstash/inputs/file.rb:157
         inputworker at /usr/local/Cellar/logstash/1.5.4/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:203
         synchronize at org/jruby/ext/thread/Mutex.java:149
         inputworker at /usr/local/Cellar/logstash/1.5.4/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:203
         start_input at /usr/local/Cellar/logstash/1.5.4/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:171

Please help!

**Comment by jsvd** [comment]
@Drewshg312 please use a file path instead of directory path in the `sincedb_path` config parameter of the file input plugin
