### ISSUE TITLE
[DOCS] Include all possible actions in ES output

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#3779]
Currently for the [ES output](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-action) we state ` Valid actions are: index, delete` and then go on to mention index, delete and also create and create_unless_exists.

We just need to update the first sentence to include the other two :)

**Comment by suyograo** [comment]
Fixed https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-action
