### ISSUE TITLE
Logstash 1.5.4 RPM permission issue

### ISSUE THREAD

**Issue by driegel** [elastic/logstash#3781]
Hello,

yesterday I installed logstash 1.5.4 from the RPM in the repo. I am using rabbitmq as input and output module. Starting logstash with a regular user account other than 'logstash' or 'root' causes an error.

Fix:
```
chmod 644 /opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.11.0-java/lib/ext/rabbitmq-client.jar
```

Thanks!
Daniel

**Comment by andrewvc** [comment]
Great find @driegel , this looks like an issue with the march_hare gem. We've opened an issue with their maintainer here: https://github.com/elastic/logstash/issues/3781

**Comment by ph** [comment]
LGTM, I have tested the gem

```
/D/m/l/ext ❯❯❯ cd march_hare-2.12.0-java/lib/ext
~/D/m/l/e/m/l/ext ❯❯❯ ls
commons-io.jar      rabbitmq-client.jar
~/D/m/l/e/m/l/ext ❯❯❯ ls -l
total 952
-rw-rw-r--  1 ph  staff   65621 27 Aug 11:29 commons-io.jar
-rw-rw-r--  1 ph  staff  417376 27 Aug 11:29 rabbitmq-client.jar
~/D/m/l/e/m/l/ext ❯❯❯
```

**Comment by andrewvc** [comment]
Thanks for finding this @driegel .  I've released new versions of both the input and output plugins. You'll need to update them with: `bin/plugin update logstash-output-rabbitmq logstash-input-rabbitmq`
