### ISSUE TITLE
Array field, multivalue field, nested object

### ISSUE THREAD

**Issue by shaktest** [elastic/logstash#3787]
I need to get one to many relation from oracle database and create an elasticsaerch index  with documents with multi value field (array).
I have two oracle table 
CarMark (cmk_id integer, cmk_name varchar2(100) );  
               (1 , "BMW")
CarModeL (cml_id integer, cmk_id integer, cml_name varchar2(100));
                (1 , 1 , "X5")
                (2 , 1 , "M3")
my statment is: 
select cmk_id, cmk_name, cml_name 
  from CarMark left join 
          CarModel on CarModel.cmk_id = CarMark.cmk_id;

I should get a document with the below result:
"cmk_id" : "1",
"cmk_Name" : "BMW"
"cml_name" : [  "X5" ,  "M6"  ]

**Comment by suyograo** [comment]
Hi @shaktest can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
