### ISSUE TITLE
Init script from RPM package ignores JAVACMD setting from /etc/sysconfig/logstash

### ISSUE THREAD

**Issue by shoggeh** [elastic/logstash#3789]
Hi,

Version affected: =< 1.5.4, shipped in RPM
System: CentOS 6

Issue/Repro:

If you set custom JAVACMD path inside /etc/sysconfig/logstash it won't have any affect in how logstash is run. Logstash will be started with default java, ignoring this setting.

Fix: One way of fixing this is to export JAVACMD variable inside /etc/init.d/logstash
Diff for line 51:

-export PATH HOME LS_HEAP_SIZE LS_JAVA_OPTS LS_USE_GC_LOGGING
+export PATH HOME LS_HEAP_SIZE LS_JAVA_OPTS LS_USE_GC_LOGGING JAVACMD

**Comment by griggle** [comment]
+1, fix works for me.

**Comment by shoggeh** [comment]
Potentially not only RPM version is affected, see: 
- https://github.com/elastic/logstash/issues/1866 Logstash not using /etc/default/logstash environment variables

**Comment by suyograo** [comment]
1.5.4 is an old release and we have no plans to release a new bug fix version. Closing this.
