### ISSUE TITLE
input-salesforce for consideration

### ISSUE THREAD

**Issue by russorat** [elastic/logstash#3792]
https://github.com/russorat/logstash-input-salesforce

This plugin provides a way to pull salesforce data into your logstash pipeline. This is an issue to start the process of making it ready for production.

**Comment by suyograo** [comment]
Your plugin source code is currently lacking tests, you would need to add some tests to validate functionality. See rspec example here: 

https://github.com/logstash-plugins/logstash-input-http_poller/blob/master/spec/inputs/http_poller_spec.rb

Documentation for this plugin will be generated from comments, so please add a blob about how to use this plugin and other info (user auth, etc) here:
https://github.com/russorat/logstash-input-salesforce/blob/master/lib/logstash/inputs/salesforce.rb#L6

I created https://github.com/logstash-plugins/logstash-input-salesforce in logstash-plugin repo. Please create an initial commit PR when you have some tests and docs.

**Comment by russorat** [comment]
Added additional documentation to the beginning of the input: https://github.com/russorat/logstash-input-salesforce/blob/master/lib/logstash/inputs/salesforce.rb#L6

Working on tests.

**Comment by ph** [comment]
@russorat I think you might want to look at [VCR](https://github.com/vcr/vcr) to create tests, it can record http calls response from the saleforce api. 

You need to make sure that you remove any token, password or any sensitive information in the files and for that you need to use some specials hook in the code. I've done something similar in this file.

https://github.com/elastic/jarvis/blob/master/spec/spec_helper.rb#L17-L31

**Comment by ph** [comment]
This is a simple use case https://github.com/elastic/jarvis/blob/master/spec/lita/handlers/jls_spec.rb#L39-L46, if you have any problem do not hesitate to ping.

**Comment by russorat** [comment]
Added an initial set of tests using vcr: https://github.com/russorat/logstash-input-salesforce/blob/master/spec/inputs/salesforce_spec.rb

**Comment by russorat** [comment]
In order to create a PR into the logstash-plugins repo, is the best course of action to create a new branch, check things into that, then create a pr from that branch to master? or is there a better way?

**Comment by russorat** [comment]
@ph so what are the next steps? Should i write more tests or create an initial PR?

**Comment by russorat** [comment]
ok PR is here: https://github.com/logstash-plugins/logstash-input-salesforce/pull/1

**Comment by russorat** [comment]
merged in.
