### ISSUE TITLE
Exception handling in plugins 

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3794]
Hi,
  from the work I've been doing this days on adding test to plugins without I had the chance to revisit some of them, noticing an interesting pattern on them. Some plugins, use this pattern when handling exceptions:

```
   begin
     ....
   rescue Exception > e
      @logger.debug("...")
   end
```

even if this might makes sense for a first implementation of the plugin, so the plugin is not exploding when exceptions are thrown, I think we should improve the way we handle exceptions so we could do a fine granularity control. In some of the plugins there where situation when this exceptions hid errors that would be nice otherwise to notice.

Relates to #2477

**Comment by purbon** [comment]
@guyboertje your feedback is welcome

**Comment by colinsurprenant** [comment]
This is a very important issue and lots of thinking and design has been already invested in this and we already have many issues opened around this and in particular #2386 and #2477 (as noted). Do we need to open a new meta issue for this? @jsvd? 

This has to tie in with the new ongoing pipeline design and the shutdown work.

**Comment by purbon** [comment]
Closing this then as duplicate.
