### ISSUE TITLE
logstash stop processing after few days

### ISSUE THREAD

**Issue by sagaraga** [elastic/logstash#3795]
I am uploading  csv files from my local system to elastic search using   logstash-1.5.1.  
     My requirement is to run the logstash and elastic search continuously.   Because , for every new day one csv file is being downloaded from internet and   that csv file should be read by logstash and then get upload into elastic search-1.5.1       . This process is working fine for 2-3 days. But after that logstash stops   input csv file processing eventhough it has new csv file in its input folder   and hence no data of corresponding day in elastic search. I searched for   solution but didn't get. Please help me.

**Comment by guyboertje** [comment]
Closing, LS 1.5 went end-of-life on 2016-11-14.
