### ISSUE TITLE
Attempting TCP SSL connection: Unrecognized SSL message, plaintext connection? 

### ISSUE THREAD

**Issue by cedw93** [elastic/logstash#3797]
From what I understand the port being using for communication is not secure? I am not sure how to fix this.

I am attempting to log to my `Logstash` instance using `Logback` and the `LogstashTcpSocketAppender` with this config:

```
<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
     <!-- remoteHost and port are optional (default values shown) -->
     <remoteHost>MY IP</remoteHost>
     <port>8443</port>
     <!-- encoder is required -->
     <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
     <ssl/>
 </appender>
```

This is my `Logstash` config:

```
input {
  heartbeat {
    interval => 60
    type => "heartbeat"
  }
 tcp {
    port => 8443
    type => dummy
    ssl_verify => false
    ssl_enable => true
    ssl_cert => "/etc/pki/tls/certs/mycert.crt"
    ssl_key => "/etc/pki/tls/private/mykey.key"
  }

}

output {
  elasticsearch {
    host=>"localhost"
    bind_port=>9200
    protocol=>http
 }

  stdout { codec => rubydebug }
}
```

This is the error message I get (in full):
```
:message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: Unrecognized SSL message, plaintext connection?>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:238:in `accept'", "/opt/logstash/vendor/jruby/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:142:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:182:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:170:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:177:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:171:in `start_input'"], :level=>:error}
```

If I disable ssl then the logging works as expected so my app and `Logstash` can communicate.

I don't think its a key problem because wouldn't that tell me something like `cannot complete ssl handshake`? 

Is there a specific port that I need to use?

`Logstash forwarder` is not a solution here, there is a reason why we don't want to use it currently.

`Logstash` in hosted on an `Amazon EC2 `instance which allows `TCP port` access on `port 8443`.

**Comment by ph** [comment]
I am not really familiar with logback, but when you are using the TCP input with the SSL settings you have to configure your application to use the same certificate. Are you using https://github.com/logstash/logstash-logback-encoder ? They have some  (SSL)([https://github.com/logstash/logstash-logback-encoder#ssl] documentation that could help you.

**Comment by cedw93** [comment]
Yeah thats what I'm using. I added the x509 certificates I generated to my Java key store as the documentation states I'm using the default key store specified using the `<ssl/>` tag in the configuration. 

Looked online not really many resources to look at, some of the said the problem happens if trying to connect using `HTTP` instead of `HTTPS` but I'm not sure. If it was a certification credential problem wouldn't the error tell me `certificate problem` not  a `plaintext connection?`

**Comment by ph** [comment]
This error usually mean, I have received information but It do event try to do an SSL handshake. So I suspect a problem in the java truststore. 

Did you try to specify a custom truststore, snippet from logback documentation.

```xml
   <!-- Enable SSL and use a different truststore -->
      <ssl>
          <trustStore>
              <location>classpath:server.truststore</location>
              <password>${server.truststore.password}</password>
          </trustStore>
      </ssl>
```

**Comment by cedw93** [comment]
I tried specifying the following:
```
<ssl>
    <trustStore>
        <location>PATH TO CACERTS</location>
        <password>$PASSWORD</password>
    </trustStore>
</ssl>
```

where `PATH TO CACERTS` is:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/security/cacerts
```

And if I run this command 

```
keytool -list -v  -keystore /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/security/cacerts -alias logstash
```

The certificate I added shows up, what am I doing wrong?

**Comment by cedw93** [comment]
Well aren't I silly, apprently there is a `SSLLogstashTcpSocketAppender` I was using `LogstashTcpSocketAppender`

**Comment by ph** [comment]
Awesome! Thanks for updating this issue !:)
