### ISSUE TITLE
Input files are not read in parallel

### ISSUE THREAD

**Issue by jerome83136** [elastic/logstash#3798]
Hello,
I'm trying to use logstash-forwarder to read my webservsers logs ant to ship them to logstash. (logstash then send events to Elasticsearch)

I have 6 webservers (zam1-3 zaf1-3) and their access_logs files can be accessed in a central point on the server where LSF is running.

The path is "/central_logs/input/prod/webservers/[webserver_name]/ihs/[webserver_instance]/access_log" (sshfs mountpoint)

The "paths" part of my LSF setup looks like this:
![lsf_conf](https://cloud.githubusercontent.com/assets/5392480/9498934/b3c74b80-4c1c-11e5-92f4-6fce8e4fa7f2.png)

So LSF has to parse 24 different files. (I have also tried with wildcard into the paths)

Here is a screenshot of the number of lines for each file:

![lsf](https://cloud.githubusercontent.com/assets/5392480/9498925/a84101fc-4c1c-11e5-91d1-f438b843335c.png)

The problem:

In Kibana, when I check the number of records on each webserver; there is a big difference between "zaf3" and the other 5 webservers.

![lsf_kibana](https://cloud.githubusercontent.com/assets/5392480/9499040/2effc318-4c1d-11e5-93ed-85bdbd09f78c.png)

It seems the logs of "zam3" are read much slower than logs on the 5 others webservers.

The Kibana screenshot has been taken after a reset of the ".logstash-forwarder" and a restart of LSF. So the files have been processed from the beginning.

The behavior I was expecting: LSF reads each file with a round-robin fashion (zam1-log1 zam1-log2 zam2-log1 zam2-log2 , etc... then again zam1-log1 zam1-log2 zam2-log1 zam2-log2 , etc...)

Is there something wrong in my setup ? Maybe is it just not possible ?

Many thanks for your help

Regards

Jérôme

**Comment by guyboertje** [comment]
@jerome83136 - is this still a problem?

If not, can you close this issue.

Otherwise, I will need more detail: LS version, OS version, Java version + all your configs.

**Comment by jerome83136** [comment]
Hi,
Sorry; I missed your last message.
The topic can be closed yes.
Thanks
Regards
Jérôme
