### ISSUE TITLE
The pipeline should return the current active plugins

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3799]
The pipeline should be able to answer the following questions.

- returns activated plugins in that specific pipeline
- returns activated plugins grouped per type
- returns activated plugins filtered by type (input, output, filter, codec)

Either by keeping an internal registry or asking the specific ast for that pipeline.

Ref #2611

**Comment by jordansissel** [comment]
This is labeled metrics, but is more about 'current state' and less about performance/behavior. Does this sound right?

**Comment by ph** [comment]
Agree its more about `manageability`, we don't have an api tag yet.

**Comment by suyograo** [comment]
Fixed in alpha1
