### ISSUE TITLE
Global patterns_dir setting for grok

### ISSUE THREAD

**Issue by avleen** [elastic/logstash#3800]
```
$ grep -c patterns_dir logstash.conf
47
```

All of the `patterns_dir` settings are the same. I suspect others might be in the same boat.
Could we get a global setting for `patterns_dir` which we can point wherever we need?
Would help clean up configs a lot :-)

**Comment by guyboertje** [comment]
Closing, LS 1.5 went end-of-life on 2016-11-14.
