### ISSUE TITLE
Logstash Twitter Input: Retweeted Field Does Not Show True Values

### ISSUE THREAD

**Issue by Israaaaa** [elastic/logstash#3806]
I'm using ES 1.7 with Logstash 1.5 and Kibana 4

I'm using the Twitter input, and I'm streaming tweets from Twitter.

The field 'Retweeted' Always shows False values even though a lot of the tweets I've streamed in contain 'RT' in the message, meaning they've been retweeted, and then there are a lot of tweets that'd been retweeted normally the way Twitter would allow them to be retweeted. But the value is STILL False for all of the documents I have, resulting in a pie chart of 100% 'Original Tweets'.

Is this an issue with Logstash filters, or did I misconfigure something?

Here is my logstash config file:

```
         input {
                      twitter {
                                  consumer_key => ...
                                  consumer_secret => ...
                                  keywords => [ "..." ]
                                  oauth_token => ...
                                  oauth_token_secret => ...
                                  full_tweet => true
                      }
          }

      output {
                      elasticsearch {
                                  host => "localhost"
                                  index => "twitter"
                                  document_type => "tweet"
                      }
      }
```

**Comment by jamime** [comment]
Same issue here, did you solve this?

**Comment by Israaaaa** [comment]
@jamime Nope.

**Comment by guyboertje** [comment]
Closing, LS 1.5 went end-of-life on 2016-11-14.
If this is still an issue please create a ticket on the [twitter input repo](https://github.com/logstash-plugins/logstash-input-twitter/issues), after upgrading to latest LS version.
