### ISSUE TITLE
Logstash - File Input Plugin

### ISSUE THREAD

**Issue by sureshadapa** [elastic/logstash#3807]
I am trying to upload data from *.txt file into elasticsearch using logstash.I have installed the input and output plugins respectively as per config file below.

csv-config.txt
===========
input {  
      file {
          path => "E:\Apps\elasticsearch\logstash-1.5.3\input*.txt"
      }
}

#filter {  
#    csv {
#        columns => ["id","firstname","lastname","email","@timestamp"]
#        separator => ","
#    }
#}
output {  
    elasticsearch_http {
		host => "localhost"
		port => 9200
		user => "logstash"
		password => "logstash"
		codec => "json"
        workers => 1
    }
     stdout {
         codec => json
     }
}

When i run logstash with config.txt, i get below output, But i am unable to view the data in elasticsearch "data/dev/nodes/.." or at http://localhost:9200/_plugin/marvel/sense/index.html
Basically my data is not been pushed into elasticsearch. Please advice.

E:\Apps\elasticsearch\logstash-1.5.3\bin>logstash.bat -f ../config.txt
io/console not supported; tty will not be manipulated
'[DEPRECATED] use `require 'concurrent'` instead of `require 'concurrent_ruby'`
←[33mThe elasticsearch_http output is replaced by the elasticsearch output and will be removed in a future version of Logstash
The following configuration example is based on the options you specified and should work:
elasticsearch {
host => ["localhost"]
port => 9200
user => "logstash"
password => <password>
codec => "json"
workers => 1
index => "logstash-%{+YYYY.MM.dd}"
manage_template => true
template_name => "logstash"
template_overwrite => false
flush_size => 100
idle_flush_time => 1
protocol => "http"
}
 {:level=>:warn}←[0m
←[33mYou are using a deprecated config setting "type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. You can achieve this same behavior with the new conditionals, like: `if [type] == "sometype" { elasticsearch { ... } }`. If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"ty
pe", :plugin=><LogStash::Outputs::ElasticSearch host=>["localhost"], port=>9200, user=>"logstash", password=><password>, codec=><LogStash::Codecs::JSON charset=>"UTF-8">, workers=>1, index=>"logstash-%{+YYYY.MM.dd}", manage_template=>true, template_name=>"logstash", template_overwrite=>false, flush_size=>100, idle_flush_time=>1, protocol=>"http">, :level=>:warn}←[0m
←[33mYou are using a deprecated config setting "tags" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. You can achieve similar behavior with the new conditionals, like: `if "sometag" in [tags] { elasticsearch { ... } }` If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"tags",
 :plugin=><LogStash::Outputs::ElasticSearch host=>["localhost"], port=>9200, user=>"logstash", password=><password>, codec=><LogStash::Codecs::JSON charset=>"UTF-8">, workers=>1, index=>"logstash-%{+YYYY.MM.dd}", manage_template=>true, template_name=>"logstash", template_overwrite=>false, flush_size=>100, idle_flush_time=>1, protocol=>"http">, :level=>:warn}←[0m
←[33mYou are using a deprecated config setting "exclude_tags" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. You can achieve similar behavior with the new conditionals, like: `if !("sometag" in [tags]) { elasticsearch { ... } }` If you have any questions about this, please visit the #logstash channel on freenode irc. {:na
me=>"exclude_tags", :plugin=><LogStash::Outputs::ElasticSearch host=>["localhost"], port=>9200, user=>"logstash", password=><password>, codec=><LogStash::Codecs::JSON charset=>"UTF-8">, workers=>1, index=>"logstash-%{+YYYY.MM.dd}", manage_template=>true, template_name=>"logstash", template_overwrite=>false, flush_size=>100, idle_flush_time=>1, protocol=>"http">, :level=>:warn}←[0m
Logstash startup completed

**Comment by wiibaa** [comment]
@sureshadapa question are best suited to https://discuss.elastic.co/c/logstash, so please close this, try the `start_position => "beginning"` option of the file input, and ask next question to the best place to get answer :)

**Comment by sureshadapa** [comment]
Its works now. thankyou.
