### ISSUE TITLE
logstash1.5.3 crash 

### ISSUE THREAD

**Issue by LiangAllen** [elastic/logstash#3811]
Exception in thread ">output" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)

And

Exception in thread "Ruby-0-Thread-10: /usr/local/src/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:92" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)

**Comment by markwalkom** [comment]
What does your config look like.

**Comment by LiangAllen** [comment]
@markwalkom   my conf：

input {
        redis {
                host => "xx.xx.xx.xx"
                port => 6379
                data_type => "list"
                key => "logstash"
                codec => json
        }
}
filter {
	   if "iis" in [type] {
			grok {
					match => ["message", "%{TIMESTAMP_ISO8601:Time} %{IP:HostIp} %{URIPROTO:Method} %{URIPATH:Url} (?:%{NOTSPACE:RequestParam}|-) %{NUMBER:Port} (?:%{WORD:UserName}|-) %{IP:ClientIp} %{NOTSPACE:UserAgent} (?:%{NOTSPACE:Referer}|-) %{NUMBER:State} %{NUMBER:SubState} %{NUMBER:Win32State} %{NUMBER:TimeInterval}"]
			}
			date {
					match => [ "Time" , "yyyy-MM-dd HH:mm:ss" ]
					timezone => "Etc/UCT"
					target => "@timestamp"
			}
        }
        if "_jsonparsefailure" in [tags] {
                drop {
                }
        }
        if "_grokparsefailure" in [tags] {
                drop {
                }
        }
}
output {
        stdout {
                codec => rubydebug
        }
        elasticsearch {
                host => "127.0.0.1"
                cluster => "elasticsearch"
                codec => "json"
                protocol => "http"
                user => "logstash"
                password => "xxx"
                index => "logstash-%{type}-%{+YYYY.MM.dd}"
                index_type => "%{type}"
                #workers => 1
                flush_size => 20000
        }
}

**Comment by ph** [comment]
Can you add your OS, JDK version (`java -version`) and a sample of your log?

**Comment by theorange** [comment]
I also experienced this issue. See https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/164
Reducing the flush_size for the elasticsearch output seems to keep this from happening:

      elasticsearch {
         host => "localhost"
         ...
         flush_size => 1
      }

**Comment by ph** [comment]
theorange, the `flush_size => 1` will greatly reduce the performance if you have a big volume of events, I suggest that you try 500 or 1000, the default is currently 5000 and we will be lowering it in the next version.

**Comment by theorange** [comment]
Thanks ph. The ones going through this output are infrequent and large, so I'm more concerned with keeping logstash running than the performance when they hit. I may try tweaking later.

**Comment by blavoie** [comment]
I've hit the same.
Is increasing JVM memory an option?
What are defaults and where to increase it?
Thanks

**Comment by ph** [comment]
@blavoie by default the logstash's JVM heap is 500mb, but you can set the  `LS_HEAP_SIZE` environment variable to an higher values, see https://github.com/elastic/logstash/blob/master/bin/logstash.lib.sh#L6

But in the next iteration of logstash we have changed the default flush size to 500 which is a more conservative value. So if everything is fine when reducing the batch size, I would not increase the memory.

**Comment by suyograo** [comment]
Reopen if this still happens
