### ISSUE TITLE
Plugin manager should not present beta plugins as upgrade options

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#3818]
Rubygems defines a beta as any plugin version with an alphabet character in it.

The code [here](https://github.com/elastic/logstash/blob/028d76497ccef3a8d11a3528cdf6b99e8d10f070/lib/pluginmanager/update.rb#L72) should skip past these versions.

**Comment by purbon** [comment]
I wonder why it should be skip? I think we should do that but offering the option to actually skip that restriction. I mean for testing purposes or investigation, to have beta's or rc's in is not a bad thing. So having something like --enable-pre-release I think to do something like bundler does.

/cheers

- purbon

**Comment by andrewvc** [comment]
@purbon what if we have a beta out but also need to release a bugfix? I think upgrading to a beta should be an explicit choice. This is the decision bundler has made for normal use and I think its a good one

The other issue is that saying 'y' doesn't actually update it to the beta version. The code [here](https://github.com/elastic/logstash/blob/028d76497ccef3a8d11a3528cdf6b99e8d10f070/lib/pluginmanager/update.rb#L57) does what is IMHO the right thing, and updates to the latest non-beta version.

I think the correct beta upgrade process should be to either add a new flag `bin/plugin update --beta logstash-output-elasticsearch`, or to require users to manually edit the Gemfile.

**Comment by purbon** [comment]
Yes, I agree on having something like a flag! :+1:, like this using prereleases is going to be explicit. I would avoid any need to change the Gemfile as at the end is not really need if we do the right thing in the plugin manager.

+1 on having this in.

**Comment by purbon** [comment]
Related issue 3744

**Comment by purbon** [comment]
I wonder if we should also add the option to update to the last non pre release version? so having update to actually install the last non pre release version of a plugin, does this makes sense to you?

The easiest thing to implement here (without much of refactoring) is actually to skip the update when the most recent version is a pre release, and require the user to specify an explicit update. However I kinda find nice that the tool is smart enough to update to the last non pre release, do you like the idea?

/cc @andrewvc @suyograo

**Comment by andrewvc** [comment]
Yes, I think it should update to the latest non-prerelease by default, and only present the option for a prerelease when the special flag is passed in.

**Comment by suyograo** [comment]
Made this a blocker for 2.0.0-beta1 since ES output and Kafka plugins will be installed on top of LS as pre releases (beta1)

**Comment by purbon** [comment]
@suyograo @andrewvc made some changes in #3826 to provide closure (as much as possible) to the issues stated here, feel free to provide feedback :smile_cat:
