### ISSUE TITLE
kv filter: case insensitive keys

### ISSUE THREAD

**Issue by coderlol** [elastic/logstash#3819]
Would be nice if kv filter include_keys / exclude_keys could support an option to treat keys as case insensitive.  It would make it easy to use kv to parse http headers.

**Comment by purbon** [comment]
I would recommend to move this issue to https://github.com/logstash-plugins/logstash-filter-kv as nowadays plugins have their own way as independent repos.

Thanks a lot for your proposal @coderlol !

**Comment by coderlol** [comment]
Sure...I move it...
