### ISSUE TITLE
logstash 1.5.4 conf file testing

### ISSUE THREAD

**Issue by santublr** [elastic/logstash#3820]
Hello,

I'm new to this tool and after downloading and running the log with a simple config file stops progress with the below message when run with --debug.

I am testing my conf file so normally I run ^C to stop the logash and after couple of runs I end up the logstash totally stop uploading with continuous flush messages  on debug.

Logstash startup completed
Flushing {:plugin=><LogStash::Filters::Multiline pattern=>"^Perforce server info:", what=>"previous", negate=>true, periodic_flush=>true, source=>"message", allow_duplicates=>true, stream_identity=>"%{host}.%{path}.%{type}", max_age=>5>, :level=>:debug, :file=>"(eval)", :line=>"16", :method=>"initialize"}
_discover_file_glob: /opt/elasticsearch/logstash-1.5.4/bin/test.log: glob is: ["/opt/elasticsearch/logstash-1.5.4/bin/test.log"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"132", :method=>"_discover_file"}

Config file:
input {
        file {
                path => "/opt/elasticsearch/logstash-1.5.4/bin/test.log"
                type => "p4datanew"
                start_position => "beginning"
        }
}
filter {
        multiline {
               pattern => "^Perforce server info:"
               what => "previous"
               negate=> true
        }
        grok {
                 match => { "message" => "^Perforce %{GREEDYDATA} pid %{DATA:p4pid} %{WORD:p4user}@%{DATA:p4client} %{IP:p4remoteclient} \[%{DATA:p4version}\] \'%{DATA:p4action}\'" }
        }

}

output {
  if( [type] =~ "p4datanew" ) {
     elasticsearch {
        embedded => false
        host => "localhost"
        index => "logstash-perforce5-%{+YYYY.MM.dd}"
        protocol => "http"
        port => "9200"
     }
  }
  stdout { codec => rubydebug }
}

**Comment by markwalkom** [comment]
Please join us in #logstash on Freenode or at https://discuss.elastic.co/ for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)

**Comment by santublr** [comment]
Thanks Mark. I've created a topic on Freenode.
