### ISSUE TITLE
About use the plugin JDBC

### ISSUE THREAD

**Issue by starckgates** [elastic/logstash#3840]
Hello, 
In your doc : https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html
that show how to use jdbc
but,in Logstash1.5.4, I can't find input plugin jdbc.
so,why i can't find it? did it remove?

------------------------

$. ./logstash -f jdbc.conf
The error reported is:
  Couldn't find any input plugin named 'jdbc'.

------------------------
and 
use ./plugin list
i can't find 'jdbc'

**Comment by markwalkom** [comment]
You need to install it - `bin/plugin -i logstash-input-jdbc`.

Also please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)
