### ISSUE TITLE
[DOCS] Clarify if plugins are core or need installing

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#3841]
It'd be nice for users to know by reading the docs if the plugin is included in core (eg grok, date) or if they need to install it (eg jdbc).

Also including instructions on how to install (yes that is repetitive, but it's explicit) would be a nice bonus.

**Comment by purbon** [comment]
yeah! this would be super nice to have.

**Comment by suyograo** [comment]
@markwalkom we do have a banner that says a plugin is not shipped by default: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-drupal_dblog.html

I am +1 to make this banner appear on plugins docs which are shipped by default. See for example: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html
