### ISSUE TITLE
kibana mapping depends on index name :D

### ISSUE THREAD

**Issue by dqunbp** [elastic/logstash#3844]
I run logstash with the same configuration, only changing the index name(logstash-2 and logstas-2). The input will send a list of ip addresses.
Field geoip.location matches differently
![image](https://cloud.githubusercontent.com/assets/14041229/9644615/cb5b08f0-51cf-11e5-90bd-3180d4d1eda1.png)
![image](https://cloud.githubusercontent.com/assets/14041229/9644618/cfb50f9a-51cf-11e5-9f80-7c1679f79003.png)

**Comment by suyograo** [comment]
Can you check if the template is same for both the indexes? Do a `GET localhost:9200/_template`. Also, lets take this on our [forum](https://discuss.elastic.co/c/logstash) where we can help you debug further. Github is mainly used for issues/enhancements. Thanks!
