### ISSUE TITLE
Mass update all plugins with 2.0.0 version of logstash-core

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3846]
We published LS core 2.0.0.snapshot1 in prep for a beta. But all plugins have this constraint in their gemspec:

`s.add_runtime_dependency "logstash-core", '>= 1.4.0', '< 2.0.0'`

This needs to be updated to `'< 3.0.0'`for beta1 and when the shutdown changes make it in, we can pin the min version to be `2.0.0`

Also, I am not really sure how things are working on jenkins with this constraint!! Plugins are getting installed on LS core now! 
http://build-eu-00.elasticsearch.org/view/LS%20Master/job/Logstash_Master_Default_Plugins/439/

**Comment by purbon** [comment]
I would say we should this days be more resilient with the versions in here. Why not changing this pattern to something like '~> 2.0', this would be equivalent to the ['>= 2.0.0', '< 3.0.0'], then we can update the pattern for the next major, etc. 

I mean in this case we want to explicitly avoid older plugins as they will not work, or supose not to work, right?

What do you think?

**Comment by purbon** [comment]
The reason why you are seeing plugin installed in master is because of https://github.com/elastic/logstash/blob/master/lib/logstash/version.rb#L3, the version number here is '2.0.0.dev' that by the end of the day is a pre release of '2.0.0'. If you remove the ```.dev``` termination plugins should not be able to be installed.

**Comment by purbon** [comment]
About my last comment, just did an small test with master:

```
purbon-elastic% bin/logstash --version
logstash 2.0.0
purbon-elastic% bin/plugin list
ERROR: No plugins found
purbon-elastic% bin/plugin install logstash-input-file
Validating logstash-input-file
Installing logstash-input-file
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.0.0)

  In Gemfile:
    logstash-input-file (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (= 2.0.0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-input-file (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-input-file (>= 0) java', in any of the sources.
```

this is what happen if the remove the prerelease label from the version :-)

/cheers

**Comment by suyograo** [comment]
Closing this for https://github.com/elastic/logstash/issues/3949
