### ISSUE TITLE
Malformed data sent to JSON codec hangs down the plugin COMPLETELY!

### ISSUE THREAD

**Issue by JakeFromTheDark** [elastic/logstash#3856]
```
$ bin/logstash -e 'input{stdin{codec=>json}} output{stdout{codec=>rubydebug}}'
Logstash startup completed
{}
{
      "@version" => "1",
    "@timestamp" => "2015-09-03T14:27:16.132Z",
          "host" => "localhost"
}
0
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Stdin codec=><LogStash::Codecs::JSON charset=>"UTF-8">, debug=>false>
  Error: can't convert String into Integer {:level=>:error}
Logstash shutdown completed
```

**Comment by JakeFromTheDark** [comment]
Got similar results also for:
* `-3`
* `3.3`
* `10e3`
* `true`
* `false`
* `[1, 2, 3]`

**Comment by guyboertje** [comment]
@JakeFromTheDark - please add your version of LS

**Comment by JakeFromTheDark** [comment]
logstash 1.5.4

**Comment by guyboertje** [comment]
The documentation is not clear.  While the values that were entered are valid serialised JSON, the code is expecting a serialised JSON object.

@JakeFromTheDark - what would you expect the output event to look like if you supplied a JSON scalar value as the representation of the input?

**Comment by JakeFromTheDark** [comment]
[It depends](http://www.mattlunn.me.uk/blog/2014/01/what-is-the-minimum-valid-json/)!

But in the context of Logstash, only JSON object (`{...}`) has sense, and anything else (arrays, numbers, strings, `true`, `false`, `null`) should result in `_jsonparsefailure` (without plugin restart).

**Comment by guyboertje** [comment]
@JakeFromTheDark - OK. However the JSON scalar and array do not create a JSON parse failure because they are valid!

Because a JSON Object parses into a Ruby Hash and Event.new is expecting a Hash, my question was more to do with: if we had to synthesize a Ruby Hash from the scalar value (to fix the bug) what would the key be to store the value against? e.g `{'scalar_value' => 0}` or `{'message' => true}` or `{'initial_value' => [{'a' => 3.3}, 6, false]}`

OR

Would a more appropriate reaction (to fix the bug) be to test whether parsed value as not a Hash and if so then log and skip?

But if we choose the latter option the the plugin(s) is misnamed - it should be called json_object(_lines)

**Comment by JakeFromTheDark** [comment]
@guyboertje - If you'll synthesize a Ruby Hash from the scalar value (Boolean, Integer, Float, FixInt, ...), then I vote for placing them into `message` field as a string: `{'message' => 'true'}`.

**Comment by guyboertje** [comment]
@JakeFromTheDark - I am trying to imagine if there is a real-world use case for a JSON based stream that has a mix of objects and scalars, and if so would the user wish to choose the key in the config?  OTOH what if the stream was JSON arrays of objects...?

**Comment by JakeFromTheDark** [comment]
@guyboertje - As I already told, "in the context of Logstash, only [JSON object](https://tools.ietf.org/html/rfc7159#page-6) (`{...}`) has sense", therefore I agree with your hard imagination. But it's mainly a **security issue** - do not allow to anyone|anything to send just a single character `0` to a Logstash TCP port with `json` codec (typically opened for any internal hosts) causing a related plugin restart with disconnecting all other long-time connected clients. Sending this malformed data every second means plugin restarting all the time, so de-facto UNAVAILABLE service.

JSON arrays are [already supported](https://github.com/logstash-plugins/logstash-codec-json/blob/master/lib/logstash/codecs/json.rb). JSON arrays are fine, if all it's members are JSON objects (not checked now). But it's also hard to imagine using that in the real world. So for backward compatibility - let's support JSON array also (with a meaning of a list of events), but every non-object member will have the same result as if this member is sent alone (not in the array) - `_jsonparsefailure` or saving it to a hard-coded|configured field.

And yes, let's this fallback field to be configurable with some clever default (`message` ?).

**Comment by jordansissel** [comment]
@JakeFromTheDark hmm, the behavior _should_ be that a json failure falls back to assumption that it is  plain text. If it's not doing this, I think it's a bug. So sending a single character `0` should result in a `{ "message": "0", "tags": [ "_jsonparsefailure" ] }` kind of event.

**Comment by JakeFromTheDark** [comment]
@jordansissel - I agree to be strict, but clear, safe and simple. So allow only `{ ... }`. Then *Anything else* will results in `{ "message": "Anything else", "tags": [ "_jsonparsefailure" ] }`. But let's ignore `/^\s*$/` to not emit practically empty `_jsonparsefailure` events.

**Comment by guyboertje** [comment]
@JakeFromTheDark , @jordansissel - Ok agreed. But the `"tags": [ "_jsonparsefailure" ]` will have to be synthesized as there is no actual parse failure.

**Comment by mkulke** [comment]
```
$ echo -e "[1,2]\n{\"a\":[1,2]}" | docker run -i logstash -e 'input { stdin { codec => json_lines } } output { stdout { codec => json } }'
{:timestamp=>"2016-06-03T07:23:33.059000+0000", :message=>"Pipeline main started"}
{:timestamp=>"2016-06-03T07:23:33.315000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Stdin codec=><LogStash::Codecs::JSONLines charset=>\"UTF-8\", delimiter=>\"\\n\">>\n  Error: can't convert String into Integer", :level=>:error}
{:timestamp=>"2016-06-03T07:23:34.380000+0000", :message=>"Pipeline main has been shutdown"}
{:timestamp=>"2016-06-03T07:23:36.062000+0000", :message=>"stopping pipeline", :id=>"main"}
```

it chokes on the array and does process the (legal) 2nd jsonline, while an actually invalid json will be handled gracefully:

```
$ echo -e "invalid\n{\"a\":[1,2]}" | docker run -i logstash -e 'input { stdin { codec => json_lines } } output { stdout { codec => json } }'
{:timestamp=>"2016-06-03T07:28:50.223000+0000", :message=>"Pipeline main started"}
{"message":"invalid","tags":["_jsonparsefailure"],"@version":"1","@timestamp":"2016-06-03T07:28:50.433Z","host":"82b4ef25d16b"}{"a":[1,2],"@version":"1","@timestamp":"2016-06-03T07:28:50.437Z","host":"82b4ef25d16b"}{:timestamp=>"2016-06-03T07:28:50.574000+0000", :message=>"Pipeline main has been shutdown"}
{:timestamp=>"2016-06-03T07:28:53.230000+0000", :message=>"stopping pipeline", :id=>"main"}
```

is this supposed to be this way?

**Comment by jsvd** [comment]
closed in favor of https://github.com/logstash-plugins/logstash-codec-json_lines/issues/27
@mkulke let me know if this issue correctly reflects your concern
