### ISSUE TITLE
Increase the default heapsize for LS to 1GB

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3861]
I suggest we increase the default heap size (`LS_HEAP_SIZE`) to 1gb. 500mb seems too low, but I really don't know how the 500mb became the default. 

One thing we did to alleviate heap usage is reduce ES output `flush_size` from 5000 to 500. This is typically the source of OOMs in LS. 

Also, JRuby is not clear about OOMs when it happens, tripping a new user. See
https://github.com/elastic/logstash/issues/3817

Thoughts?

**Comment by untergeek** [comment]
:+1: 

If 512M of heap is an issue, you're probably going to want to send via LSF anyway.

**Comment by ph** [comment]
I think we need to gather more information about the oom scenarios, but 1 gig isn't that big, but I can hear people already complaining about it.

On top of my head the problematic plugins are:

- Lumberjack with multiline codec (hello java stacktrace)
- Multiline filter
- ES output
- Lumberjack output.

**Comment by suyograo** [comment]
Another issue without using the ES output. https://github.com/elastic/logstash/issues/3914

**Comment by suyograo** [comment]
Fixed in #4085
