### ISSUE TITLE
How can i calculate numbers in a field.

### ISSUE THREAD

**Issue by John-ding** [elastic/logstash#3871]
I have field "Duration" like this  "3 days 2 hrs 2 mins"
I want to calculate to mins, so i change this field to numbers with
mutate {
       gsub => [ "Duration"," days | day | hrs | hr ",","]
       gsub => [ "Duration"," mins| min",""]
       split => { "Duration" => "," }
          }
then i got this.
 "Duration" => [
        [0] "3",
        [1] "2",
        [2] "2"
    ]
but don't know how to calculate them.
Can anyone help? thank you very much!

**Comment by magnusbaeck** [comment]
As this is more of a usage question than a bug report, can you please post the question at https://discuss.elastic.co/c/logstash instead?
