### ISSUE TITLE
codec chaining execution strategy

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3874]
this is a task issue for #3873 

How to implement codec chaining. A few ideas have been expressed:

- introduce a meta codec or codec multiplexer (see logstash-plugins/logstash-codec-multiline#10) which would avoid refactoring the plugins 
- refactor the plugins to improve codec decoupling and support chaining in the codec "executor" strategy

**Comment by wiibaa** [comment]
@colinsurprenant @guyboertje can this 3 issues be closed in favor of future work on event mills ??

**Comment by guyboertje** [comment]
@wiibaa - I suppose so, closing.
