### ISSUE TITLE
Logstash 2.0 should require Java 8

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#3877]
Oracle marked the EOL of Java 7 in April 2015, and as of July 2015 they no longer provide downloads for Java 7.

Logstash 2.0 is a good time to upgrade to Java 8. Benefits being:

* This version of Java still receives improvements
* concurrent-ruby (a dependency library) will require Java 8 for v1.0
* We can explore using [JSR-310, the new Java 8 Date/Time tooling](https://docs.oracle.com/javase/8/docs/api/index.html?java/time/package-summary.html) as a replacement to Joda-Time. Benefit that it's native and supports nanosecond-precise times (Joda is millisecond-precise).

**Comment by runningman84** [comment]
That should not be a big deal because elasticsearch requires java 8 too.

**Comment by jasontedor** [comment]
> That should not be a big deal because elasticsearch requires java 8 too.

That's true for the next major version of Elasticsearch, but not the 2.x line of Elasticsearch.
