### ISSUE TITLE
Enhancement: Force Raw unindexed 

### ISSUE THREAD

**Issue by deepvoice** [elastic/logstash#3879]
Since 1.5 don't have any .raw in Kibana anymore. I store domain names and many of them have hyphens. Which are cut off. Would like the ability to force .raw for certain fields.

**Comment by jordansissel** [comment]
@deepvoice Logstash still ships a template for Elasticsearch that creates .raw fields for strings. This sounds like a configuration problem - could you ask this on https://discuss.elastic.co/ and include your logstash config and a rough description of how you are seeing Kibana not having the '.raw' fields?

**Comment by jordansissel** [comment]
(Closing since  I think this is a question)
