### ISSUE TITLE
Create a Timing matcher for rspec

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#3884]
This is quite an [old post](https://www.ruby-forum.com/topic/894409) but it gives a solution.

``` ruby
require 'benchmark'

RSpec::Matchers.define :take_less_than do |n|
  chain :seconds do; end

  match do |block|
    @elapsed = Benchmark.realtime do
      block.call
    end
    @elapsed <= n
  end

end

describe "addition" do
  it "runs fast" do
    expect do
      10000.times { 1 + 2 }
    end.to take_less_than(0.001).seconds
  end
end
```

**Comment by purbon** [comment]
I'm not sure I like the idea of mixing benchmarks and rspec, not sure how would rspec affect this. Are you thinking more on timing executions? there were some rspec helpers for that already existing. You can check for example the jdbc input specs.

What do you think?

**Comment by guyboertje** [comment]
Let me record my thoughts after a zoom with pere and joao.

1) I want to rename the concept to Timing because Benchmark is an overloaded term.
2) The tests that measure timing should be tagged so it does not run normally or removed altogether.
3) The timings expected are not meant to be transportable across machines.
4) The timing is done in RSpec, instead of e.g. a rake task, because one wants to leverage the unit test mocking environment that should already be setup to isolate the Unit method call from external dependency calls.
5) During refactoring experiments, one uses the timing test to measure behaviour speed improvements and the regular unit tests to measure behaviour correctness.
6) Once the refactoring experiment ends the timing tests are redundant.

For the above reasons I am advocating a matcher to make it really easy to add, gain value and discard.

We should still have a general purpose performance regression checks though.

**Comment by purbon** [comment]
The general purpose regression check for speed and performance is baking, ideas are sum up https://github.com/elastic/logstash/issues/3499, basic idea is to have benchmarks for:

* the row pipeline (available nowdays from https://github.com/elastic/logstash-performance-testing) 
* the most used plugins, this include how things like files, elasticsearch, kafka, http, etc.
* all together.

There is still a long way to get there, for sure!

- purbon

**Comment by guyboertje** [comment]
not worth doing
