### ISSUE TITLE
Parsing Json

### ISSUE THREAD

**Issue by silviupanaite** [elastic/logstash#3890]
I'm trying to parse:
{"log":"86.121.176.201 - - [09/Sep/2015:14:14:06 +0000] \"GET /css/style.less HTTP/1.1\" 304 0 \"http://developer.unificationengine.com/login\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36\" \"-\"\r\n","stream":"stdout","time":"2015-09-09T14:14:06.112442077Z"}

But I'm not able to:

if [type] == "docker-logs" {
        grok {
        match => ["message", "%{QS}:%{QS:message_log},%{QS}:%{QS:log_type},%{QS}:%{QS:time}"]
        match => ["message", "\A\{\\"log\\":\\"%{IP} - - \[%{HTTPDATE:time}] \\\\\\"%{WORD} %{PATH} %{PROG}%{NOTSPACE}%{SPACE}%{NUMBER} 0 \\\\\\"%{URI}%{NOTSPACE}%{SPACE}%{GREEDYDATA}"]
        }
          mutate {
            rename => ["log", "message"]
          }
          date {
            match => ["time", "ISO8601"]
            remove_field => ["time"]
          }
        }
}

Can you help me out, I don't know what I'm doing wrong?

**Comment by magnusbaeck** [comment]
As this is more of a usage question than a bug report, can you please post the question at https://discuss.elastic.co/c/logstash instead?

**Comment by markwalkom** [comment]
Spot on, this should be on the forums @silviupanaite :D

(Thanks @magnusbaeck)

**Comment by silviupanaite** [comment]
:) thanks
