### ISSUE TITLE
replace field with a string that ends in a special character does not work

### ISSUE THREAD

**Issue by omnidepp** [elastic/logstash#3896]
I try to add a special character to the end of a field by using mutate/replace. 

````
mutate {
            replace => { "myfield" => "%{myfield}@" }
 }
mutate {
            replace => { "myotherfield" => "%{myotherfield}:" }
 }
```
...does not do anything. Surprisingly, adding two special characters works:

````
mutate {
            replace => { "myfield" => "%{myfield}@@" }
 }
mutate {
            replace => { "myotherfield" => "%{myotherfield}::" }
 }
```

Please excuse this post if this is a feature and not a bug. How can I just add a colon or @ at the end of a field?

**Comment by wiibaa** [comment]
@ph can you please confirm this was fixed in https://github.com/elastic/logstash/commit/935ac9285b6bb34f8b261cda93203223fe46e76c and can be closed

**Comment by ph** [comment]
Confirmed.
