### ISSUE TITLE
Internal message bus

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3897]
The agent, the pipeline and the plugins will emit some kind of metrics or performance stats.
If we generalize that action, we are actually emitting a message of the type `metric`.

Instead of creating a custom collector for the metrics, I think we could create some kind of internal message bus that would take care of any internal messages that the system create and let consumer subscribes to theses messages and act upon them.

This would allow to decouple the message from that actual work. This could allow us to do some neat trick like dynamic resources allocation for slower plugins based on the metric data.

**Really high level syntax**

```ruby
class MetricMessage < Message
end

metric = MetricMessage.new

bus = MessageBus.new
bus.send(metric)


class MetricInternalSnapshot < MessageBusConsumer
  def on_message(message)
  end
end

snapshot = MetricInternalSnapshot.new() # create a local aggregated view for the web api?
external = MetricExternalReporter.new() # Push metrics event to external system like elasticsearch or statsd
adapt_pipeline = AdaptPipeline.new() # Listen to metrics events detect bottlenext and do resource reallocation

bus.add_subscriber(snapshot, :type => MetricMessage)
bus.add_subscriber(external, :type => MetricMessage)
bus.add_subscribe(adapt_pipeline, :type => [MetricMessage, NeedResourceMessage])

```

This architecture would also allow us to use the persistent queue and do replays of metrics if the system goes down and we need to.

**Comment by colinsurprenant** [comment]
interesting proposal. I like the idea of having metrics as an event stream but I wonder if for all intents and purposes this will not be over-engineering? I think that practically there's probably just a handful of "base" metrics that will be really useful and snapshotting can easily be done by gathering all metrics periodically and outputting them as normal logstash events that can be processed by the pipeline and ultimately outputted somewhere; il a file, or in a ES cluster, etc.

**Comment by ph** [comment]
Well, I don't think this is over-engineering, this allow us the flexibilty to evolve in more complex solution.
The base metrics are, 

`MetricExternalReporter ` probably want to have all the events, and this is probably an interface around a a pipeline and the outputs plugins, this will be the first to be implemented using elasticsearch.

---

`MetricInternalSnapshot` is a way to provide a windows of the stats, give me a view of the last hour and would not rely on any external service, **this is not required** for the first phase.

`AdaptPipeline` is only a fun future idea and show what this kind of architecture could allow us to do.

**Comment by ph** [comment]
So instead of pushing events directly into the queue, we push them to a broker with one of the output configured output is a queue. 

I am writing another issue concerning the output as we speak.

**Comment by colinsurprenant** [comment]
i think what ever systems collects metrics internally, we should simply have a LogstashMetricsInput plugin that will gather a snapshot of internal metrics at a configured interval then we just leverage the logstash pipeline & plugins to process and output the metrics events?

**Comment by ph** [comment]
This proposal doesn't impact that, the input you are describing could just subscribe to the channel and does the snapshot and push the metrics down the pipeline.

**Comment by colinsurprenant** [comment]
I understand. What I am saying is that I can hardly see any practical use-case that would not be handled by simple metrics collection and simple query api plus the ability to also access these metrics through an input plugin. But I may very well lack vision on this now.

**Comment by guyboertje** [comment]
@colinsurprenant - consider this...
```ruby
Metric.capture_both(event, bus, 'input-enqueue') do
  output_queue << event
end

#where

class Metric
  def self.capture_both(event, bus, key, &block)
    bus.accept *metric_for(event, key, 'begin')
    block.call
    bus.accept *metric_for(event, key, 'done')
  end

  def self.capture_in(event, bus, key, &block)
    bus.accept *metric_for(event, key, 'begin')
    block.call
  end

  def self.capture_out(event, bus, key, &block)
    block.call
    bus.accept *metric_for(event, key, 'done')
  end

  def self.metric_for(k, suffix)
    ["#{k}-#{suffix}", Thread.current[:id], event.id, current_nanos]
  end
  #...
end
```
you will have two low level events that say when the input began to enqueue an event and when it succeeds and time between the two events is the queue blocking time.

**Comment by guyboertje** [comment]
I think we need to transmit the metrics (or perf stream) independently of the pipeline we are trying to measure.  We need the collection and transmission to be as light-weight as possible.

**Comment by colinsurprenant** [comment]
@guyboertje nothing should be transmitted to the pipeline internally unless you setup a metrics input plugin and this is for practical purposes of being able to leverage logstash to process metric events like any other events. 

Again, architecturally this seems very very sweet. But I have yet to see a practical & realist use-case where just collecting base metrics at strategic places for both the pipeline and plugins and collecting them internally and exposing a api to query them will not be sufficient for most use-cases. 

I think what we need to solve and expose and what users are expecting in terms of metrics & visibility does not have to be overly complicated and will provide a big improvement over the current no-visibility.

I'd really suggest iterating over the idea, start with the base of what is to be expected in terms of metrics MVP then improve. I am not convinced this architecture is required but your are definitely free to prove me wrong if you are convinced here, I may see this bigger than it really is.

**Comment by colinsurprenant** [comment]
part of this discussion is now moved to #3898 and #3901 - seems we are converging on the multiple pipelines idea for the processing of metrics events

**Comment by guyboertje** [comment]
As a 'blue-sky' example of an architecture I suggest that the actual metric structure is an Array not a custom object and then use the Disruptor or similar as the intermediary Bus, with switchable consumers for the different onward scenarios (ES, Rest)

**Comment by guyboertje** [comment]
I like the idea that our subclass of SizedQueue knows how to dump metrics to a collection endpoint.  Expanding on this, an input, filter or output would also know how to dump its metrics is enabled.  I guess a summary of this would be that the Pipeline would not know that metrics are being collected at all save to initialize the collection endpoint and make it available to the plugin components.

**Comment by ph** [comment]
@guyboertje What would be the avantages of using an array vs a class?

**Comment by guyboertje** [comment]
The array suggestion is only based on easy conversion to a native Java object for the Disruptor or a Java implementation of any Bus that we might write.  I don't think generating JSON hand off to the Bus endpoint is performant.  I suspect it is cheaper to build an Array of known ordinal values than a custom object of those same values. Also if we are concerned with immutability then freezing the Array would help.

**Comment by ph** [comment]
Valid point concerning serialization, the first item could be the type and we could use it for routing.

**Comment by guyboertje** [comment]
Many conventions are possible. Initially an Array for dev then perhaps something like [FlatBuffer](https://google.github.io/flatbuffers/)?

**Comment by ph** [comment]
I did some experimentation on my side and tracking all theses new evens in a second pipeline was really taxing on the system.  Keep in mind, If an event was generating 10 events, well the work needed to send the events to another logstash server was more important than the current pipeline which didnt make sense.

So the current implementation of the `message_bus` only support metrics primitives like an increasing counter (other types will come). This was a nice idea but was really hard to implement without having a prohibitive cost.

Also as an admin point of view, I would be inclined to believe that they want an higher view of the system and be able to answer the following question:

- What is the performance of a plugin?
- What is the performance of logstash?
- Can I correlated the performance with other metrics collected in my setup (like elasticsearch)

Getting the details at the event level will probably give more noise to the admin.

Also, the only was this could be possible and performant would be to record the trace at the jvm level?

**Comment by ph** [comment]
The current implement of the `MessageBus` in the feature/metrics is done by 3 classes:

- Metric: Create a uniform array for the collected metrics, make it context aware
- Collector: Take the metric event and create concrete class and call the needed actions (like `#increment` on a counter)
- MetricStore: Save the context and the metric for easy retrieval.

**Comment by ph** [comment]
Work is done in https://github.com/elastic/logstash/tree/feature/metrics
