### ISSUE TITLE
Every Logstash node or instance should have their own unique id

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3900]
When collecting stats in a multi nodes or cluster environment we need a way to identify a specific node when investigating performance issue. Currently when you start logstash we don't generate a unique id, some plugins use the local hostname to track where events came from.

**We should generate it by default:**
- It should be unique as much as we can, until we have the cluster in place we can't be sure.
- We should use a random name, the concept is similar to elasticsearch node name.
- Users should be able to change it with either a configuration change or a flag when starting logstash.

**Comment by jsvd** [comment]
yay marvel characters!

**Comment by ph** [comment]
I think the base of it is done in #4254

**Comment by suyograo** [comment]
Merged in master
