### ISSUE TITLE
Add support for multiples pipelines

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3901]
Currently Logstash support only **one** pipeline active at any time. The metrics implementation could reuse the pipeline code (input, filter and output) to send events to the metrics backend. We don't want  any hiccups of the main pipeline possibly impacting the collection and transport of the metrics.

This changes could also help us do live reload of configuration or cluster management.

Ref #3693 #3774 #3898

**Comment by colinsurprenant** [comment]
just for clarification, while a desirable feature to support metrics, multiple pipelines support is not strictly specific for metrics, so in that respect I would remove the "Metrics: " in the subject. Nitpicking, I know.

**Comment by ph** [comment]
@colinsurprenant agree, let me keep at least the metrics label so I can track it :P

**Comment by ph** [comment]
Each pipeline should have an ID to help identify it in the stats.

**Comment by jsvd** [comment]
The refactor work in https://github.com/elastic/logstash/pull/3872 opens up the possibility of multiple pipelines. That PR implements it as an array, but could be an hash, to include the id

**Comment by fbaligand** [comment]
I'm very happy to see this new feature in 2.1 roadmap. 
The feature I would love, based on this design improvement is that each input plugin can explicitly indicate which pipeline id for the filter chain. 
This is particularly interesting when you have numerous sources in input and we use single thread filter plugin like multiline or globally when we want to be assured that all logs from a same source are processed sequentially (for example when the output is 'file'). 
In this case, you can have one pipeline per source and each pipeline has one thread.

**Comment by purbon** [comment]
@jsvd @ph about the multiple pipelines design, I was thinking about the execution model of them. Have we thought about it? do we want them to be completely independent? to interact some way? pulling from the same config or from different ones? what do you think?

**Comment by ph** [comment]
@purbon I think the initial goal is to run them in isolation, but I agree this could benefit from resource sharing.

**Comment by suyograo** [comment]
Merged to master
