### ISSUE TITLE
file output plugin doesn't work with dynamic output file path

### ISSUE THREAD

**Issue by geshenyi** [elastic/logstash#3906]
What I would like to do is to output logs to another file per day.

But logstash just give me error message as follows:

[31mFile: The starting part of the path should not be dynamic. {:path=>"c:/test_%{+yyyy.MM.dd}.log", :level=>:error}[0m
Error: The starting part of the path should not be dynamic.

Here is my configuration
input {
    file {
	codec => multiline {
      		pattern => "^\s"
	     	 what => "previous"
    	}
        path => "C:\test1.log"
        start_position => beginning
    }
}
filter {
    grok{
    	match => {"message" => "^(?<datetime>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\s%{DATA:exception}\s+

%{GREEDYDATA:stacktrace}$"}
	}

}
output {
    file {
        message_format => "%{[message]}"
        path => "c:\test_%{+yyyy.MM.dd}.log"
    }
    stdout {codec => rubydebug}
}

**Comment by magnusbaeck** [comment]
For reasons I've forgotten, the first path component of the output path must not be dynamic. Try e.g. c:/logs/test_%{+yyyy.MM.dd}.log instead.

**Comment by jordansissel** [comment]
> For reasons I've forgotten, the first path component of the output path must not be dynamic

It's to prevent arbitrary file access. If we allowed `path => "%{foo}"` a specially-crafted event could cause 'foo' to be a chosen value allowing a remote person the ability to write to any file logstash on which had access.

**Comment by jordansissel** [comment]
>  path => "c:\test_%{+yyyy.MM.dd}.log"

At a glance, it looks like this _should_ work, but doesn't. hmm..

**Comment by jordansissel** [comment]
Let's move this to the file output plugin: https://github.com/logstash-plugins/logstash-output-file/issues

(I'll close this and we can continue the discussion there)

**Comment by milanrock** [comment]
It saves the filename on GMT/UTC time. How to save files in local time?
