### ISSUE TITLE
Other doc dependencies on changing to HTTP protocol

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#3911]
First line in Watcher [1] and Shield [2] Logstash integration need updates as we change to HTTP protocol as default.

Minor change, but needs change as we're changing to HTTP as the default.  There may be other changes similar to this in the docs.

[1] https://www.elastic.co/guide/en/watcher/current/logstash-integration.html
[2] https://www.elastic.co/guide/en/shield/current/logstash.html

**Comment by acchen97** [comment]
@palecur

**Comment by palecur** [comment]
Yeah, the protocol change is going to have a lot of ripple effects. Thanks for noting this one; I'll take care of it.
