### ISSUE TITLE
NoMethodError with replace-mutate using float values

### ISSUE THREAD

**Issue by Mortinke** [elastic/logstash#3913]
/opt/logstash/bin/logstash --version
logstash 1.5.3
ls -ltr /opt/logstash/vendor/bundle/jruby/1.9/gems/ | grep mutate
drwxr-xr-x 3 logstash logstash 4096 Aug  3 19:14 logstash-filter-mutate-1.0.0

I would like parse iostat statistics for performance analyse and have the following output:

```
          "log_message" => "Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util\nsda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00\nsdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00\n",
           "iostat_head" => "Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util\n",
                "device" => [
    [0] "sda",
    [1] "sdb"
],
       "read_req_merged" => [
    [0] "0.00",
    [1] "0.00"
],
      "write_req_merged" => [
    [0] "0.00",
    [1] "0.00"
],
         "read_requests" => [
    [0] "0.00",
    [1] "0.00"
],
        "write_requests" => [
    [0] "0.00",
    [1] "0.00"
],
               "read_mb" => [
    [0] "0.00",
    [1] "0.00"
],
              "write_mb" => [
    [0] "0.00",
    [1] "0.00"
],
"avg_request_size" => [
    [0] "0.00",
    [1] "0.00"
],
"avg_request_queue_size" => [
    [0] "0.00",
    [1] "0.00"
],
     "request_wait_time" => [
    [0] "0.00",
    [1] "0.00"
],
     "service_wait_time" => [
    [0] "0.00",
    [1] "0.00"
],
           "device_util" => [
    [0] "0.00",
    [1] "0.00"
]
```

I use the replace methode from the mutate-plugin the get a nested formated output:

```
  if [device][0] {
    mutate {
      replace => [
        "[disk1][device]", "%{[device][0]}",
        "[disk1][read_req_merged]", "%{[read_req_merged][0]}",
        "[disk1][write_req_merged]", "%{[write_req_merged][0]}",
        "[disk1][read_requests]", "%{[read_requests][0]}",
        "[disk1][write_requests]", "%{[write_requests][0]}",
        "[disk1][read_mb]", "%{[read_mb][0]}",
        "[disk1][write_mb]", "%{[write_mb][0]}",
        "[disk1][avg_request_size]", "%{[avg_request_size][0]}",
        "[disk1][avg_request_queue_size]", "%{[avg_request_queue_size][0]}",
        "[disk1][request_wait_time]", "%{[request_wait_time][0]}",
        "[disk1][service_wait_time]", "%{[service_wait_time][0]}",
        "[disk1][device_util]", "%{[device_util][0]}"
      ]
    }
  }
  if [device][1] {
    mutate {
      replace => [
        "[disk2][device]", "%{[device][1]}",
        "[disk2][read_req_merged]", "%{[read_req_merged][1]}",
        "[disk2][write_req_merged]", "%{[write_req_merged][1]}",
        "[disk2][read_requests]", "%{[read_requests][1]}",
        "[disk2][write_requests]", "%{[write_requests][1]}",
        "[disk2][read_mb]", "%{[read_mb][1]}",
        "[disk2][write_mb]", "%{[write_mb][1]}",
        "[disk2][avg_request_size]", "%{[avg_request_size][1]}",
        "[disk2][avg_request_queue_size]", "%{[avg_request_queue_size][1]}",
        "[disk2][request_wait_time]", "%{[request_wait_time][1]}",
        "[disk2][service_wait_time]", "%{[service_wait_time][1]}",
        "[disk2][device_util]", "%{[device_util][1]}"
      ]
    }
  }

                 "disk1" => {
                    "device" => "sda",
           "read_req_merged" => "0.00",
          "write_req_merged" => "0.00",
             "read_requests" => "0.00",
            "write_requests" => "0.00",
                   "read_mb" => "0.00",
                  "write_mb" => "0.00",
          "avg_request_size" => "0.00",
    "avg_request_queue_size" => "0.00",
         "request_wait_time" => "0.00",
         "service_wait_time" => "0.00",
               "device_util" => "0.00"
},
                 "disk2" => {
                    "device" => "sdb",
           "read_req_merged" => "0.00",
          "write_req_merged" => "0.00",
             "read_requests" => "0.00",
            "write_requests" => "0.00",
                   "read_mb" => "0.00",
                  "write_mb" => "0.00",
          "avg_request_size" => "0.00",
    "avg_request_queue_size" => "0.00",
         "request_wait_time" => "0.00",
         "service_wait_time" => "0.00"
}
```

This works fine! But if i use parse the values directly with float conversion:

IOSTAT_TDMX         (%{DISK_NAME:device}\s+%{IOSTAT_DEC_VALUE:read_req_merged:float}\s+%{IOSTAT_DEC_VALUE:write_req_merged:float}\s+%{IOSTAT_DEC_VALUE:read_requests:float}\s+%{IOSTAT_DEC_VALUE:write_requests:float}\s+%{IOSTAT_DEC_VALUE:read_mb:float}\s+%{IOSTAT_DEC_VALUE:write_mb:float}\s+%{IOSTAT_DEC_VALUE:avg_request_size:float}\s+%{IOSTAT_DEC_VALUE:avg_request_queue_size:float}\s+%{IOSTAT_DEC_VALUE:request_wait_time:float}\s+%{IOSTAT_DEC_VALUE:service_wait_time:float}\s+%{IOSTAT_DEC_VALUE:device_util:float}\n)

and replace the fields afterwards, i get the following error message:

{:timestamp=>"2015-09-14T07:22:53.201000+0200", :message=>"Exception in filterworker", "exception"=>#<NoMethodError: undefined method `[]' for 0.0:Float>, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/util/accessors.rb:57:in `get'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/event.rb:131:in`[]'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/string_interpolation.rb:107:in `evaluate'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/string_interpolation.rb:26:in`evaluate'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/event.rb:222:in `sprintf'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-1.0.0/lib/logstash/filters/mutate.rb:255:in`replace'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-1.0.0/lib/logstash/filters/mutate.rb:254:in`replace'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-1.0.0/lib/logstash/filters/mutate.rb:213:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:163:in`multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:160:in`multi_filter'", "(eval):36373:in `cond_func_1878'", "org/jruby/RubyArray.java:1613:in`each'", "(eval):36370:in `cond_func_1878'", "(eval):36500:in`cond_func_1877'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):36496:in`cond_func_1877'", "(eval):36525:in `cond_func_1876'", "org/jruby/RubyArray.java:1613:in`each'", "(eval):36519:in `cond_func_1876'", "(eval):3497:in`filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:157:in`start_filters'"], :level=>:error}

**Comment by kares** [comment]
closing LS 1.5 issue, hopefully things are better these days :wink:
