### ISSUE TITLE
bin/plugin update fails: initialize: name or service not known

### ISSUE THREAD

**Issue by jeroentbt** [elastic/logstash#3915]
I'm running logstash within a container from the official docker [logstash image](https://hub.docker.com/_/logstash/).

When I try to update a (or all) plugin(s) I get the error: `ERROR: Updated Aborted, message: initialize: name or service not known`

````
$ docker run -it --rm logstash:1.5.4-1 plugin update
ERROR: Updated Aborted, message: initialize: name or service not known
````

**Comment by purbon** [comment]
@jeroentbt not sure about docker internals, so please accept my ignorance for the question. Are you able to connect to rubygems.org from your image? this would be required to do the update?

On the other hand, would you be able to provide a complete script to reproduce your error?

Thanks a lot for your feedback,

**Comment by purbon** [comment]
@jeroentbt I just check, this images are not provided by Elastic, so not sure about the internals of them.

**Comment by jeroentbt** [comment]
@purbon, It is indeed a connectivity issue. From within the container I can not access rubygems.org.

I should have clarified that the image is provided by Docker indeed, sorry to have wasted your time.

As for a complete script:
````
#!/bin/bash
docker pull logstash:1.5.4-1
docker run -it --rm logstash:1.5.4-1 plugin update
````
I'll look in to why it's not connecting. Thanks again for your time!

Final note: damn you're fast!

**Comment by jeroentbt** [comment]
It was an issue with the docker daemon on my side.
My sincerest apologies!

**Comment by purbon** [comment]
No need to apologies man!
    my pleasure to help!

/cheers

- purbon

**Comment by purbon** [comment]
Thanks!
  this was an easy one, when the plugin manager fails with this error,
usually means no connection to the server. BTW, do you know if we can open
a bug for this in the docker image?

/cheers
