### ISSUE TITLE
Invalid Link in Wiki Page (Tips:Testing-your-filters)

### ISSUE THREAD

**Issue by hartfordfive** [elastic/logstash#3916]
Seems like the example url on the following wiki page is broken:
github.com/elastic/logstash/wiki/Tips:Testing-your-filters

Where can the correct url be found?

**Comment by suyograo** [comment]
Hi, the wiki has not been updated to recent changes. What specific info do you need regarding testing filters. Also can you please open a new topic in https://discuss.elastic.co/c/logstash to discuss this?

**Comment by hartfordfive** [comment]
I've opened up a new topic there: https://discuss.elastic.co/t/testing-logstash-filters-within-another-cookbook/29471.
