### ISSUE TITLE
How to handle nil keys in Event hashes from a JSON generation viewpoint.

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#3918]
In LS 1.5.4, JrJackson 0.2.9 will raise a GeneratorError when a `nil` key is found in an Event during serialization. See [this issue for background](https://github.com/elastic/logstash/issues/3912).

Votes required!

I can add an option that allows for a nil, object key value pair to be serialized as

A) ```"": <value>```
B) ```"null":<value>```
C) ignore the KV pair completely
D) create a random key

WDYT?

**Comment by jordansissel** [comment]
Tricky. In part, I'm interested in how a null key came to even be.

We only support (really) string keys. The same problem would kind of occur for any non-string key, not just null. Given I view this as a "non-string key" general problem and not the specific "null key" problem, maybe we can add validation at input-time to reject non-string keys with a clear error message?

**Comment by andrewvc** [comment]
![I have no strong feelings](http://www.quickmeme.com/img/16/164ee159072b52c35f6b52d35a5e5ddc9fb0b015ce95a4568f64c2fed8525f84.jpg)

Seriously though, this falls in the realm of undefined behavior IMHO. I personally think "" makes the most sense. There's a chance `"null"` could be an actual field name, but `""` is clearly something apart from that.

**Comment by jordansissel** [comment]
I don't know what I expected:

```
>> puts ({ nil => nil }.to_json)
{"":null}
```

I still think we should have option E that a null key is a program error. Munging it to an empty string (as ruby's json seems to do) may be an OK option, but it still feels really weird. I'd prefer to consider null key being invalid.

**Comment by jordansissel** [comment]
Python:

```
>>> json.dumps({ None: None })
'{"null": null}'
```

**Comment by guyboertje** [comment]
@jordansissel @andrewvc  - I am so sorry, I did not communicate successfully. I mean: I can make  changes to JrJackson to give LS the option to configure how JrJackson should respond to nil keys - what do people think those options should be. 
This depends on whether the values are considered important enough to try to preserve them.  For example, if we add an LS specific option to use `"nil_key_given'` instead of `""` or `"null"` it becomes more obvious to the LS user that there is a problem to solve.

This is because we don't want to double handle Hash keys in LS.

If no configuration is required I will follow the ruby Json gem's behaviour and return an empty string.

**Comment by andrewvc** [comment]
@guyboertje I'm a much bigger fan of `""` just because in-band signaling is hard, and its the most differentiated value. `""` is clearly wrong. Anything with actual chars could come from an upstream input source.

**Comment by guyboertje** [comment]
OK - I'm ambivalent.  I just want to give people a chance to influence JrJackson's code.

**Comment by jordansissel** [comment]
> I am so sorry, I did not communicate successfully

@guyboertje hah, no need for apologies! My suggestion was mostly a tangent - I agree we could make JrJackson handle null keys (and maybe we should, my vote at the bottom of this comment). My thought was that for Logstash, we should understand _how_ a null key gets into an event and fix _that_ bug also. Logstash should never emit an event with a null key anywhere in the event, in my opinion, and doing that is a bug.

As for my vote, I have no strong preference, and am amused that python and ruby have different behaviors (empty string and "null" text for ruby and python respectively). My leaning is towards "do what ruby does" and ruby's default json turns null key into an empty string.

That said, let's solve both problems (JrJackson's null key handling + Logstash shouldn't create nil keys)

**Comment by guyboertje** [comment]
OK @andrewvc and @jordansissel - an empty string it is. Its a bit more work in JrJackson to code for different treatment of nil keys.
