### ISSUE TITLE
Configuration File Ordering Does Matter for some reason

### ISSUE THREAD

**Issue by ayashjorden** [elastic/logstash#3920]
Hi all,
This issue is the result of [this](https://discuss.elastic.co/t/logstash-configuration-file-ordering-does-matter/28840) discussion. Per @magnusbaeck [suggestion](https://discuss.elastic.co/t/logstash-configuration-file-ordering-does-matter/28840/6), I'm opening this issue so we all can benefit and understand Logstash better.
I'm running logstash with a couple of `-f` switches and for some unknown reason, the order of the files does matter:

```
input-filter-output:
~/util/logstash-1.5.4/bin/logstash -f ./conf.d/input-50-email-sending.conf -f ./conf.d/filter-50-email-sending.conf -f ./conf.d/output-50-receiver.conf
Logstash startup completed
Logstash shutdown completed

input-output-filter:
~/util/logstash-1.5.4/bin/logstash -f ./conf.d/input-50-email-sending.conf -f ./conf.d/output-50-receiver.conf -f ./conf.d/filter-50-email-sending.conf
Logstash startup completed
Logstash shutdown completed

filter-output-input:
~/util/logstash-1.5.4/bin/logstash -f ./conf.d/filter-50-email-sending.conf -f ./conf.d/output-50-receiver.conf -f ./conf.d/input-50-email-sending.conf
Logstash startup completed
#gave is some time to run...
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
Logstash shutdown completed
```

With --debug, I found the following:

```
input-filter-output:
Plugin not defined in namespace, checking for plugin file {:type=>"output", :name=>"http", :path=>"logstash/outputs/http", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
Plugin not defined in namespace, checking for plugin file {:type=>"codec", :name=>"plain", :path=>"logstash/codecs/plain", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}

input-output-filter:
Plugin not defined in namespace, checking for plugin file {:type=>"filter", :name=>"csv", :path=>"logstash/filters/csv", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}

filter-output-input: Logstash starts and stays up:
Plugin not defined in namespace, checking for plugin file {:type=>"input", :name=>"file", :path=>"logstash/inputs/file", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
Plugin not defined in namespace, checking for plugin file {:type=>"codec", :name=>"plain", :path=>"logstash/codecs/plain", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
```

I didn't expect seeing errors in the 3rd bullet (filter-output-input), but Logstash stays up.

If the full log is needed, I can pastebin it, but it will take me some time to sanitize it.

FWIW, My config files are standardised as follows:

```
filter-[ORDERING_NUMBER]-[DESC].conf => filter-50-CDN.conf
input-[ORDERING_NUMBER]-[DESC].conf => input-50-sockets.conf
output-[ORDERING_NUMBER]-[DESC].conf => output-50-http.conf
```

Another interesting thing is that if I start Logstash with "bin/logstash - /etc/logstash/conf.d" (passing a directory containing my configuration) its working.

What is different between specifying specific files in certain order and specifying a directory containing the configuration?

Can someone explain this behaviour ?

Thanks,
Yarden

**Comment by jordansissel** [comment]
I'm not super sure what to expect here. The `-f` flag only supports a single path, specifying multiple `-f` flags is probably undefined behavior. 

Do we document that you can specify `-f` multiple times? I don't remember that feature being added, if so.

**Comment by magnusbaeck** [comment]
> The `-f` flag only supports a single path, specifying multiple `-f` flags is probably undefined behavior.

Oh. That would certainly explain things. Not bailing out on multiple `-f` occurrences would clearly be a bug, but instead of adding another error case we should support multiple options.

**Comment by ayashjorden** [comment]
I admit that the documentation doesn't specify multiple ```-f``` flags, but for me it seems intuitive that a program which can take specific file as a parameter, would also be able to take several files as well.

For example, let's say that my Logstash configuration directory contains 10 files and I want Logstash to load certain files but not others.

Another example from ```man tail```:
 ```tail [OPTION]... [FILE]...```
```With more than one FILE, precede each with a header giving the file name.```

tail can take multiple files as input source.

What do you think?

**Comment by jordansissel** [comment]
You can achieve multiple specific files today using the curly expansion syntax for wildcards. The `-f` flag supports 3 kinds of paths: a single file, a single wildcard text, or a single directory.

In your example, let's load 3 files specifically by name. We can do this using the wildcard feature:

```
% bin/logstash --debug -f '/tmp/{one,two,three}'
Reading config file {:file=>"logstash/agent.rb", :level=>:debug, :line=>"309", :method=>"local_config"}
Reading config file {:file=>"logstash/agent.rb", :level=>:debug, :line=>"309", :method=>"local_config"}
Reading config file {:file=>"logstash/agent.rb", :level=>:debug, :line=>"309", :method=>"local_config"}
```

You can see above it read 3 config files, and it was my 3 specific config files (/tmp/one, /tmp/two, /tmp/three).

Hope this helps!

----

I agree we should probably add a more complete description of the flag behavior (prior flags are overwritten by future flags, such that `-f foo -f bar` is the same as just `-f bar`)

**Comment by dedemorton** [comment]
Added clarification in #6289
