### ISSUE TITLE
Add a field from a dynamic field name

### ISSUE THREAD

**Issue by jeanpralo** [elastic/logstash#3921]
Hi Guys,

I have been googling up this but could not find anything that would match what I want to do. I am using the snmptrap input plugin to get linkUp/linkDown event for some of my switches.

This generated this sorts of events:

    "IF-MIB::ifIndex.20568" => "20568",
    "IF-MIB::ifDescr.20568" => "Loopback187",
    "IF-MIB::ifType.20568" => "24",

The field name is dynamic since it uses the index of the interface (the field name is the OID ). so when I want to assign things in the output it is a problem since I can't find a way to refer to that field name.

I have a way to get the index in a non dynamic field by matching the message field:
    filter {
       grok {
            match => { "message" => "%{GREEDYDATA}1.3.6.1.2.1.2.2.1.1.%{INT:intIndex}\]" }
       }

And basically I would like to be able to get the name of the interface via something like that:

    filter {
       mutate {
       add_field => { "intName" => IF-MIB::ifDescr.%{intIndex} }
    }

It will then allow me to get the name of the interface via %{intName}.

Does anyone know if there is a way to do that ?

Regards.
Jean.

**Comment by suyograo** [comment]
Hey @jeanpralo , can you please move this to https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
