### ISSUE TITLE
Logstash hangs because of urldecode filter

### ISSUE THREAD

**Issue by siddharthasahu** [elastic/logstash#3922]
I was trying to apply the urldecode filter to a field two times (for complete decoding). But because of the presence of non UTF-8 characters, the second urldecode operation seems to be hanging rather than ignoring/skipping the characters or printing an error.

Sample characters after 1st urldecode: \xF1\xC6c\x95\xC5. Logstash does throws a "Received an event that has a different character encoding than you configured." warning.

So logstash was getting stuck within 5-10 minutes of starting, I assume because of encountering a log line containing the non UTF-8 characters. Removing the second urldecode solved the hangs. Instead of hanging, urldecode should just ignore wrong encoding issues.

**Comment by jordansissel** [comment]
Hmm, this shouldn't cause logstash to hang, though. Can you show your config and a sample line that logstash hangs on?

**Comment by siddharthasahu** [comment]
Hmm, original log line (with non utf chars) will take some effort to extract. See if this helps first.

Sample 'request' field extracted using COMBINEDAPACHELOG grok pattern after first urldecode:
/url?Key1=value1&Key2=127.190.82.160&ua=Mozilla%2F4.0%20%28compatible%3B%20MSIE%208.0%3B%20Windows%20NT%205.1%3B%20Trident%2F4.0%3B%20GTB7.2%3B%20.NET%20CLR%201.1.4322%3B%20IEMB3%3B%20.NET%20CLR%202.0.50727%3B%20.NET%20CLR%203.0.4506.2152%3B%20.NET%20CLR%203.5.30729%3B%20InfoPath.1%3B%20AskTbORJ%2F5.14.0.19709%3B%20yie8%29&Key3=blahblah\\xCA\\xE5@14O7J@82I9\\xCA\\xE5@14O7J\\xCD\\n\\xB3\\u001F\\u001F\\u001F\\u001F\\u001F\\u001F\\u001F
.
Using urldecode two times leads to logstash stopping after some time.
urldecode {
        field => "request"
}
urldecode {
        field => "request"
}

Now I have only one urldecode, and logstash is working properly.

**Comment by siddharthasahu** [comment]
I also do a kv on this field after urldecode:
kv {
        source => "request"
        field_split => "&?"
}

**Comment by siddharthasahu** [comment]
Hi

I'm facing the same issue in a completely new setup.
Logstash config and example log line: https://gist.github.com/siddharthasahu/b9755470353ae996dd83

Logstash runs fine until it stops completely. No log output, no gc output nothing. Just sitting there taking up CPU.

Any ideas for further debugging?

**Comment by siddharthasahu** [comment]
Sending a SIGINT shuts down the stuck logstash instance properly in this case:
"SIGINT received. Shutting down the pipeline."

**Comment by siddharthasahu** [comment]
New errors sees:

["INFLIGHT_EVENTS_REPORT", "2015-10-08T11:02:36Z", {"input_to_filter"=>20, "filter_to_output"=>0, "outputs"=>[]}] {:level=>:warn}
Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss. {:level=>:warn}

["INFLIGHT_EVENTS_REPORT", "2015-10-08T11:02:46Z", {"input_to_filter"=>20, "filter_to_output"=>0, "outputs"=>[]}] {:level=>:warn}

So it seems the filter plugin is stalling?

**Comment by jsvd** [comment]
yes, there seems to be a filter that is preventing the filter section to flow normally, can you gradually remove filters to see where the problem lies?

**Comment by siddharthasahu** [comment]
Changing the grok pattern from (?<provider_request_id>.+?(?=@#@))? to (?<provider_request_id>((?!@#@).)+)? seems to have done the trick. (from lookahead to negative look-ahead)

Earlier, it was removing the second urldecode that stopped the stalls. So, it seems to a general filter issue then? Is there a simple way to debug logstash when its in a hung state?

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
