### ISSUE TITLE
Fieldref syntax should allow to retrieve the epoch value in milliseconds values of the timestamp

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3923]
I had a discussion with @sarwarbhuiyan over hipchat about what was the best way to retrieve the epoch value in milliseconds of the `@timestamp` field without using a ruby filter and I havent found any.

I think getting the milliseconds values of the timestamp could be a more common usecase than we think and we should provide a nicer way to do it. The current implementation of the `fieldref` parser supports `+%s` which will give you the epoch time in milliseconds. It would be easy to add `+%m` to get the milliseconds.

This would allow people to use the add field option to retrieve the time.

```
{
....
add_field => { "my_time_in_milliseconds" => "%{+%m}"}
}
```

**Comment by jordansissel** [comment]
Does "%{+%S}" not work?

**Comment by jordansissel** [comment]
```
% bin/logstash -e 'output { stdout { codec => line { format => "ms: %{+SSS} | %{@timestamp}" } } }'
Logstash startup completed

Hello world
ms: 209 | 2015-09-15T17:09:44.209Z
```

+SSS works for me on the current release :)

**Comment by ph** [comment]
My bad, I missed the `epoch` reference thanks for spotting this!

```
%{+SSS} will return the millisecond part of the timestamp.
```

To get the epoch in milliseconds you have to do this, Maybe Joda have something to retrieve it directly, but I haven't found any.. 

```ruby
LogStash::Timestamp.new().to_f * 1000
```

**Comment by sarwarbhuiyan** [comment]
+1 
DateTime has a strfprint('%Q') but can't use it here because it's a Time.

**Comment by jordansissel** [comment]
epoch in milliseconds? "%{+%s}%{SSS}"

**Comment by ph** [comment]
I am okay with "%{+%s}%{+SSS}" so closing this.
