### ISSUE TITLE
Load-balancing redis output

### ISSUE THREAD

**Issue by krzysztof-jurkowski-roche** [elastic/logstash#3924]
In my setup I have a F5 load balancer in front of multiple Redis instances running on different machines. F5 is configured tu use Round robin with no persistence.
The problem is that once a Logstash agent opens a new connection to Redis it is never closed, even if the delay between messages sent by this agent is as big as 30 seconds.
In the Wireshark capture all I can see is PSH, ACK.

This is problematic since load balancer cannot balance an open TCP session. This means that once an agent acquires a connection with one node, it will be assigned to it forever (assuming no connection drop etc).

We found a workaround by setting up an automatic connection reset every 5 seconds. With this not only agents are assigned to randomly to Redis instances, but also messages are shuffled across all nodes.

Our network expert complains that this workaround can introduce performance issues and he suggest that the agent should use UDP, as it is not session aware and it can be load balanced without connection reset.

Is it possible to use UDP instead of TCP for Redis output? What are your recommendations?

**Comment by jordansissel** [comment]
I don't think Redis supports UDP as a protocol.

For TCP, it is possible to improve how the redis plugin works. Could you open this discussion on the specific plugins on https://github.com/logstash-plugins/logstash-output-redis/issues and https://github.com/logstash-plugins/logstash-input-redis/issues?

**Comment by krzysztof-jurkowski-roche** [comment]
Moved to [logstash-plugins/logstash-output-redis/issues/15](https://github.com/logstash-plugins/logstash-output-redis/issues/15)
