### ISSUE TITLE
plugin initialization thread safety

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3930]
the pipeline initializes plugins by calling their `register` method from the pipeline thread, for example https://github.com/elastic/logstash/blob/7f9e81727d80935a672e843b402a767a93efd35d/lib/logstash/pipeline.rb#L149 but the plugin worker is executed in a separate thread right after, for example https://github.com/elastic/logstash/blob/7f9e81727d80935a672e843b402a767a93efd35d/lib/logstash/pipeline.rb#L170-L172

In some plugins, instance variables are initialized in the `register` method and these variables are used in the worker thread code. 

Generally speaking, sharing instance variables across thread is not safe. Here are a few guidelines for using ivar & thread safety:
- initialize all instance variables you will use in the `initialize` method.
- enclose ivars in a `Mutex#syncronize` or equivalent to force a memory barrier and make sure all threads have a consistent view on the ivar
- or use one of the `concurrent-ruby` thread-safe/atomic primitive

for our specific problem here, I believe we should call the plugin `register` method in the same thread as the plugin worker code. 

so instead of having, for example, 
```ruby
...
    @inputs.each do |input|
      input.register
      start_input(input)
    end
...

def start_input(plugin)
  @input_threads << Thread.new { inputworker(plugin) }
end
```

we'd have
```ruby
def start_input(plugin)
  @input_threads << Thread.new do
    plugin.register
    inputworker(plugin)
  end
end
```

This way we would avoid all the thread safety concerns between the `register` method and the worker code.

**Comment by jsvd** [comment]
I don't understand how this is a problem, because by the time we finish register we create the second thread that may touch these ivars, is there still an isolation problem after register finishes?

I do see this as a problem in the context of plugin.stop vs run, but this is already known.

**Comment by colinsurprenant** [comment]
@jsvd I think that to answer this question would require close examination of the JRuby code base related to that. generally speaking ivar across thread are not safe, their initialization, unless performed in the `initialize` method is not safe. a behaviour in that respect today could change in the future. Let's not be *wishful* and avoid any related potential problem by explicitly preventing any thread safety problems.

do you see any potential problem in moving the register method in the worker thread?

**Comment by colinsurprenant** [comment]
BOOM after having a discussion about this in the JRuby IRC channel, I just learned that, contrary to the info in the [JRuby concurrency wiki](https://github.com/jruby/jruby/wiki/Concurrency-in-jruby), ivars are actually volatiles across threads. There is not need to memory fence them.

This means here that ivars initialized in the `register` method in the pipeline thread will be correctly visible in the worker thread `run` method.
