### ISSUE TITLE
elasticsearch's index template duplicates last part of field name

### ISSUE THREAD

**Issue by XANi** [elastic/logstash#3934]
We're using logstash to feed suricata logs (that are just plain json) into elasticsearch(1.7.1)/kibana stack.

To have not analyzed fields available I've loaded `lib/logstash/outputs/elasticsearch/elasticsearch-template.json` template but I've notice that this made fields like `host` into `host.host.raw` and `http.http_user_agent`  into `http.http_user_agent.http_user_agent.raw`

I've managed to fix it by removing `{name}` like that:

    "fields" : {
        "{name}" : {"type": "string", "index" : "analyzed", "omit_norms" : true, "index_options" : "docs"},
        "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
    }

but I have no idea how and why it fixed it....

**Comment by untergeek** [comment]
@XANi 

It appears you are using an old version of the template.  The current version does not look like this:

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L22-L25

```
             "type" : "string", "index" : "analyzed", "omit_norms" : true,
               "fields" : {
                 "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
               }
```

Without ever specifying `template_overwrite => true`, it appears that the template never got updated from past versions of Logstash.  You could also remove the template manually with:

```
curl -XDELETE localhost:9200/_template/logstash?pretty
```

On the next start, Logstash would notice the absence of a template and add the current template.

**Comment by XANi** [comment]
Yup, it was that, thanks for help
