### ISSUE TITLE
Multiline codec needs a max_age option

### ISSUE THREAD

**Issue by mvintila** [elastic/logstash#3936]
Currently, by using the multiline codec on input, you never get the last message from the logs.

The codec will wait forever for the next line to come in order to check it against the pattern. This is OK if the source is very active, but for sources that produce 1 message every hour or so the multiline codec is simply not usable.

The multiline filter covers the above scenario but it has it's own problems ( not thread safe and #3935 ).

**Comment by suyograo** [comment]
Moved to https://github.com/logstash-plugins/logstash-codec-multiline/issues/11. Can you use `max_lines` or `max_bytes` in your scenario?
