### ISSUE TITLE
logstash - install & first test

### ISSUE THREAD

**Issue by franck-serot** [elastic/logstash#3940]
Hi,
I try to install and test logstash according to the following tutorial.
https://www.elastic.co/guide/en/logstash/current/first-event.html
I have the following error.
cd logstash-1.5.4
.\bin\logstash -e 'input { stdi { } } output { stdout {} }'
Erreur : impossible de trouver ou charger la classe principale org.jruby.Main
Could you help to understand the problem and solve it ?
Best regards,
Franck

**Comment by suyograo** [comment]
@franck-serot whats you java version? `java -version`. Also, can you create a topic here: https://discuss.elastic.co/c/logstash

Github is used for bugs and enhancements
