### ISSUE TITLE
Mass update on plugins for preparing logstash 2.0 beta 2

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3949]
Update all default plugins constraint to:
```
add_runtime_dependency "logstash-core", ">= 2.0.0", "< 3.0.0"
```

Make sure the plugins major version is updated to 2.0 or 3.0 if needed.

**Comment by ph** [comment]
Small question here, some of our plugins aren't even 1.0, I think they are mostly codecs (https://github.com/logstash-plugins/logstash-codec-avro/blob/master/logstash-codec-avro.gemspec)

What should be our strategy here? 
1. Make them 1.x
2. Bump them to 2.x

**Comment by suyograo** [comment]
@ph lets make it 2.0 to better reflect alignment with core 2.0

**Comment by ph** [comment]
:wine_glass:

**Comment by ph** [comment]
@suyograo https://github.com/logstash-plugins/logstash-mixin-aws/pull/18 This was created from a test run.

**Comment by ph** [comment]
Run on September 22 2015 9:47 EST.
