### ISSUE TITLE
renaming teardown to close in plugins

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#3952]
Some plugins still use `teardown`, an api that will disappear in 2.0. These need to be renamed:

##### Default plugins

- [x] [logstash-filter-multiline](https://github.com/logstash-plugins/logstash-filter-multiline)
- [x] [logstash-filter-zeromq](https://github.com/logstash-plugins/logstash-filter-zeromq)
- [x] [logstash-input-file](https://github.com/logstash-plugins/logstash-input-file)
- [x] [logstash-input-generator](https://github.com/logstash-plugins/logstash-input-generator)
- [x] [logstash-input-jdbc](https://github.com/logstash-plugins/logstash-input-jdbc)
- [x] [logstash-input-pipe](https://github.com/logstash-plugins/logstash-input-pipe)
- [x] [logstash-input-redis](https://github.com/logstash-plugins/logstash-input-redis)
- [ ] [logstash-input-tcp](https://github.com/logstash-plugins/logstash-input-tcp)
- [x] [logstash-input-s3](https://github.com/logstash-plugins/logstash-input-s3)
- [x] [logstash-input-udp](https://github.com/logstash-plugins/logstash-input-udp)
- [x] [logstash-input-zeromq](https://github.com/logstash-plugins/logstash-input-zeromq)
- [x] [logstash-output-elasticsearch](https://github.com/logstash-plugins/logstash-output-elasticsearch)
- [x] [logstash-output-elasticsearch_http](https://github.com/logstash-plugins/logstash-output-elasticsearch_http)
- [ ] [logstash-output-elasticsearch_java](https://github.com/logstash-plugins/logstash-output-elasticsearch_java)
- [x] [logstash-output-file](https://github.com/logstash-plugins/logstash-output-file)
- [x] [logstash-output-redis](https://github.com/logstash-plugins/logstash-output-redis)
- [x] [logstash-output-s3](https://github.com/logstash-plugins/logstash-output-s3)
- [x] [logstash-output-sqs](https://github.com/logstash-plugins/logstash-output-sqs)
- [x] [logstash-output-zeromq](https://github.com/logstash-plugins/logstash-output-zeromq)
- [x] [logstash-output-lumberjack](https://github.com/logstash-plugins/logstash-output-lumberjack)

##### Non default plugins

NOTE: these aren't a priority for now, can be done later

- [x] [logstash-codec-compress_spooler](https://github.com/logstash-plugins/logstash-codec-compress_spooler)
- [x] [logstash-codec-spool](https://github.com/logstash-plugins/logstash-codec-spool)
- [x] [logstash-input-couchdb_changes](https://github.com/logstash-plugins/logstash-input-couchdb_changes)
- [x] [logstash-input-gemfire](https://github.com/logstash-plugins/logstash-input-gemfire)
- [x] [logstash-input-github](https://github.com/logstash-plugins/logstash-input-github)
- [x] [logstash-input-jmx](https://github.com/logstash-plugins/logstash-input-jmx)
- [x] [logstash-input-neo4j](https://github.com/logstash-plugins/logstash-input-neo4j)
- [x] [logstash-input-rackspace](https://github.com/logstash-plugins/logstash-input-rackspace)
- [x] [logstash-input-relp](https://github.com/logstash-plugins/logstash-input-relp)
- [x] [logstash-input-varnishlog](https://github.com/logstash-plugins/logstash-input-varnishlog)
- [x] [logstash-output-gemfire](https://github.com/logstash-plugins/logstash-output-gemfire)
- [x] [logstash-output-google_bigquery](https://github.com/logstash-plugins/logstash-output-google_bigquery)
- [x] [logstash-output-google_cloud_storage](https://github.com/logstash-plugins/logstash-output-google_cloud_storage)
- [ ] [logstash-output-influxdb](https://github.com/logstash-plugins/logstash-output-influxdb)
- [ ] [logstash-output-jms](https://github.com/logstash-plugins/logstash-output-jms)
- [x] [logstash-output-juggernaut](https://github.com/logstash-plugins/logstash-output-juggernaut)
- [ ] [logstash-output-neo4j](https://github.com/logstash-plugins/logstash-output-neo4j)
- [x] [logstash-output-solr_http](https://github.com/logstash-plugins/logstash-output-solr_http)
- [x] [logstash-output-statsd](https://github.com/logstash-plugins/logstash-output-statsd)
- [x] [logstash-output-webhdfs](https://github.com/logstash-plugins/logstash-output-webhdfs)

**Comment by ph** [comment]
I don't think this should be a problem, personally I haven't seen a lot of code with a method named `teardown` outside of unit testing.

**Comment by ph** [comment]
We can always push a new version of a plugin if it doesn't work.

**Comment by purbon** [comment]
I agree with @ph it should be simple, but would not be less to do an small checkup.

@ph doing that you say in your last comment imply  there are test that check for this in the plugin, this is now the case of more plugins, but still not all. we should be careful with the ones we bundle with.

what do you think?

**Comment by jsvd** [comment]
what I can do is have a new logstash checkout of the 2.0 snapshot and devultils and run:
```
cd all_plugins
# get me all plugins with teardown in them
grep teardown . -r | cut -d ":" -f 1 | cut -d "/" -f 2 | uniq > teardown.txt
# rename all occurrences
find . -name '*.rb' -type f -exec sed -i '' "s/teardown/close/g" {} \;
# go through each plugin that was renamed
# commit changes
# modify gemfile to point to local logstash and devutils
# run specs
# if they pass push to master
for plugin in `cat teardown.txt`; do cd $plugin; git commit -a -m "renamed teardown to close"; cp ../Gemfile .; bundle install; bundle exec rspec && git push origin master; cd ..; done     
```

**Comment by ph** [comment]
I am OK with that @jsvd

**Comment by jsvd** [comment]
output: https://gist.githubusercontent.com/jsvd/78830d687f676881ed35/raw/abb49b58b0a02c6c3336d2fa123af6ee6be902dc/gistfile1.txt

some plugins either failed or specs hanged, this was expected since some have shutdown related prs being reviewed

**Comment by jsvd** [comment]
Plugins that still have teardown calls in them:

```
./logstash-input-pipe/lib/logstash/inputs/pipe.rb:  def teardown
./logstash-input-tcp/lib/logstash/inputs/tcp.rb:  def teardown
./logstash-input-tcp/lib/logstash/inputs/tcp.rb:  end # def teardown
./logstash-input-tcp/spec/inputs/tcp_spec.rb:      plugin.teardown
./logstash-input-tcp/spec/inputs/tcp_spec.rb:      plugin.teardown
./logstash-output-elasticsearch_java/lib/logstash/outputs/elasticsearch_java.rb:    @retry_teardown_requested = Concurrent::AtomicBoolean.new(false)
./logstash-output-elasticsearch_java/lib/logstash/outputs/elasticsearch_java.rb:      while @retry_teardown_requested.false?
./logstash-output-elasticsearch_java/lib/logstash/outputs/elasticsearch_java.rb:  def flush(actions, teardown = false)
./logstash-output-elasticsearch_java/lib/logstash/outputs/elasticsearch_java.rb:  def teardown
./logstash-output-elasticsearch_java/lib/logstash/outputs/elasticsearch_java.rb:    @retry_teardown_requested.make_true
./logstash-output-elasticsearch_java/lib/logstash/outputs/elasticsearch_java.rb:  # and once that thread is ended during the teardown process, a final call 
./logstash-output-elasticsearch_java/lib/logstash/outputs/elasticsearch_java.rb:  # to this method is done upon teardown in the main thread.
./logstash-output-elasticsearch_java/spec/integration/outputs/retry_spec.rb:    subject.teardown
./logstash-output-elasticsearch_java/spec/integration/outputs/retry_spec.rb:    subject.teardown
./logstash-output-elasticsearch_java/spec/integration/outputs/retry_spec.rb:    subject.teardown
./logstash-output-elasticsearch_java/spec/integration/outputs/retry_spec.rb:    subject.teardown
./logstash-output-influxdb/lib/logstash/outputs/influxdb.rb:  def flush(events, teardown = false)
./logstash-output-influxdb/lib/logstash/outputs/influxdb.rb:  def teardown
./logstash-output-influxdb/lib/logstash/outputs/influxdb.rb:  end # def teardown
./logstash-output-jms/lib/logstash/outputs/jms.rb:def teardown
./logstash-output-neo4j/lib/logstash/outputs/neo4j.rb:  def teardown
./logstash-output-neo4j/spec/outputs/neo4j_spec.rb:    it "should teardown" do
./logstash-output-neo4j/spec/outputs/neo4j_spec.rb:      expect { output.teardown }.to_not raise_error
./logstash-output-s3/spec/outputs/s3_spec.rb:      s3.teardown
./logstash-output-s3/spec/outputs/s3_spec.rb:        s3.teardown
./logstash-output-s3/spec/outputs/s3_spec.rb:        s3.teardown
```

**Comment by ph** [comment]
I will check the S3 output.
