### ISSUE TITLE
Question on "Multiple Connections for Logstash High Availability" diagram published in logstash documentation

### ISSUE THREAD

**Issue by rajkumarvenkatasamy** [elastic/logstash#3953]
Hi Logstash Team

Can you explain whether duplicate events or log messages will be processed if we implement the logstash stack as per HA architecture explained in 2nd diagram of "Multiple Connections for Logstash High Availability" section ? This is because when multiple logstash instances are pointing to same input sources and types, how do we restrict publishing of duplicate messages to output MQs ?

URL reference:
https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html

**Comment by untergeek** [comment]
This question should be in https://discuss.elastic.co, rather than as a GitHub issue.  Closing.
