### ISSUE TITLE
[2.0.0 beta1] json_lines codec seems to make Logstash stall or OOM

### ISSUE THREAD

**Issue by radu-gheorghe** [elastic/logstash#3956]
I'm using Logstash 2.0.0 beta1 and I'm trying to index JSON lines from a file. It worked perfectly with the JSON *filter* but I wanted to see how the JSON *codec* compares. When I started it, Logstash didn't index any message, but it quickly went up to the 1GB heap limit and threw an OOM. The same with 2GB.

Because I was sending to Solr and thought maybe this output is problematic, I switched to Elasticsearch. Then it gave me a warning saying Java 7 isn't supported (I was on OpenJDK 1.7.0_79) and OOMed again. So I switched to Java 8 (OpenJDK 1.8.0_45) and now it doesn't OOM any more, but I still don't see any documents in ES.

You can find the config and log sample here: https://gist.github.com/radu-gheorghe/e32a2ef29bc7dcb4ec10

Commenting the "json_lines" codec line makes it all work. As it does with JSON filter - so there is a workaround. But I thought that a) it would be nice to know and b) maybe the JSON codec is actually more efficient (even though it can only run on one thread AFAIK).

**Comment by guyboertje** [comment]
Never use the json_lines codec with the file input. Use the json codec instead.

The file input is already yielding lines of data without `\n`. The json_lines codec will accumulate the lines given by the file input while looking for `\n` to stop accumulating. However, there are none so it buffers everything until it goes OOM.
