### ISSUE TITLE
Logstash downloads for 1.4.4 and 1.4.5 missing?

### ISSUE THREAD

**Issue by trikosuave** [elastic/logstash#3960]
Trying to download either 1.4.4 or 1.4.5, only logstash-contrib is available and it requires logstash of the same version to be installed. I do not see the download for logstash itself.

https://www.elastic.co/downloads/past-releases
to either
https://www.elastic.co/downloads/past-releases/logstash-1-4-4
or 
https://www.elastic.co/downloads/past-releases/logstash-1-4-5

Only the contrib files are available to download. 

Where can I download logstash 1.4.5 (preferably rpm)?
Thanks!

**Comment by suyograo** [comment]
Fixed! Thanks for reporting this :+1:

**Comment by trikosuave** [comment]
Great Thanks! Where can one get the logstash-contrib rpms? I should've grabbed it when I had the chance. :)
