### ISSUE TITLE
mass update all plugins with API changelog

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3965]

**Comment by ph** [comment]
Something like this
```
2.0.0 (or 3.0.0)

- Plugins were updated to follow the new shutdown semantic, allowing Logstash to stop without hanging and cleanly empty his internal queues. Ref: https://github.com/elastic/logstash/pull/3895
- Dependency on logstash-core update to 2.0

**Comment by suyograo** [comment]
`Plugins were updated to use new shutdown APIs, allowing Logstash to perform a clean stop without hanging. Ref: https://github.com/elastic/logstash/pull/3895`

**Comment by suyograo** [comment]
@ph new text and good to go

**Comment by ph** [comment]
Awesome will get this going :dancer:

**Comment by ph** [comment]
PR review in https://github.com/logstash-plugins/logstash-patterns-core/pull/110

**Comment by jsvd** [comment]
I don't think this should be phrased as "clean stop without hanging", this change makes shutdown less abrupt by not using Thread.raise, giving the plugin the control to terminate itself.

My attempt:

```
Plugin updated to conform with new pipeline shutdown API.
This mainly allows Logstash to instruct input plugins to terminate gracefully, instead of using Thread.raise on the plugins' threads.
```

**Comment by ph** [comment]
@jsvd I think this message is more truthful and transparent, I will update the script and run it.

**Comment by ph** [comment]
done in mass update october 8 9h40 EST
