### ISSUE TITLE
How to change "https://rubygems.org/" to a mirror? v1.5.4 & v2.0.0. beta1

### ISSUE THREAD

**Issue by yokyo** [elastic/logstash#3966]
I simply changed  relative line in Gemfile.jruby-1.9.lock and Gemfile located in HOME_DIR , but it seems dont work.

**Comment by purbon** [comment]
@yokyo are you talking about a deliverable package? or from a git clone?

**Comment by yokyo** [comment]
Thanks for you reply!
I download ZIP file from the official site,  from v1.5.3 to v2.0.0 Beta1.

**Comment by yokyo** [comment]
@purbon After i did some nonsense-like work ,clone online repo, download ruby, exec 'gem install xxx' ,'bundle install', 'rake xxx' etc. 
It worked,dont know when,what trigger,without a reboot nor re-config. faint..
Thanks again..
