### ISSUE TITLE
Installed Gem is not really installed

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/logstash#3971]
As referenced here: https://discuss.elastic.co/t/local-filter-plugin-pretended-to-be-installed-but-not-listed-and-not-working/2016, plugin is said to be installed but isn't really installed.

This seems to happen when a local gem file is built and installed.  All that happens is a file like this is created: ./vendor/local_gems/e8f538bc/logstash-input-example-0.0.1 but nothing else.

**Comment by PhaedrusTheGreek** [comment]
For convenience, here is the summary of the Discussed Issue:

I tried writing a simple filter plugin, following this Howto: https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html2

When installing the plugin, it was reported to be installed:

```
# /opt/logstash/bin/plugin install /usr/local/src/logstash-plugins/logstash-filter-ticketracker/logstash-filter-ticketracker-0.1.0.gem
Validating /usr/local/src/logstash-plugins/logstash-filter-ticketracker/logstash-filter-ticketracker-0.1.0.gem
Installing logstash-filter-ticketracker
Installation successful
```
But when I list the plugins, it does not show up.
```
root@d0e2e5106842:/opt/logstash# /opt/logstash/bin/plugin list | grep ticket                                                          
root@d0e2e5106842:/opt/logstash#
```
When trying to test it, it shows an error:
```
 root@d0e2e5106842:/opt/logstash# bin/logstash -e 'input { stdin{} } filter { ticketracker {} } output {stdout { codec => rubydebug }}'
```
The error reported is: 
```
  Couldn't find any filter plugin named 'ticketracker'. Are you sure this is correct? Trying to load the ticketracker filter plugin resulted in this error: no such file to load -- logstash/filters/ticketracker
Environment:
```
Ubuntu 12.04
Logstash 1.5.0

Thanks.

**Comment by yokyo** [comment]
@packetb-old I guess there must be some warning when you build your project with "gem build" command,and still built successful,
but generated an empty gem file (almost) which you may not notice.
You should setup dependency packages if so.

**Comment by PhaedrusTheGreek** [comment]
Yes, there is a warning during gem build:

WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

**Comment by ph** [comment]
@PhaedrusTheGreek what do you have in your gemspec?

**Comment by PhaedrusTheGreek** [comment]
```
Gem::Specification.new do |s|

  s.name            = 'logstash-input-example'
  s.version         = '0.0.1'
  s.licenses        = ['Apache License (2.0)']
  s.summary         = "Rxample"
  s.description     = "This gem is a logstash plugin required to be installed on top of the Logstash core pipeline using $LS_HOME/bin/plugin install gemname. This gem is not a stand-alone program"
  s.authors         = ["Elastic"]
  s.email           = 'info@elastic.co'
  s.homepage        = "http://www.elastic.co/guide/en/logstash/current/index.html"
  s.require_paths = ["lib"]

  # Files
  s.files = `git ls-files`.split($\)+::Dir.glob('vendor/*')

  # Tests
  s.test_files = s.files.grep(%r{^(spec)/})

  # Special flag to let us know this is actually a logstash plugin
  s.metadata = { "logstash_plugin" => "true", "logstash_group" => "input" }

  # Gem dependencies
  s.add_runtime_dependency "logstash-core", '>= 1.4.0', '< 2.0.0'

  s.add_runtime_dependency 'logstash-codec-plain'
  s.add_runtime_dependency 'logstash-codec-line'
  s.add_runtime_dependency 'logstash-codec-json'
  s.add_runtime_dependency 'logstash-codec-json_lines'
  s.add_runtime_dependency 'concurrent-ruby'

  s.add_development_dependency 'rspec'
  s.add_development_dependency 'logstash-devutils'

end
```

**Comment by nathanclemente** [comment]
Running into the same issue as @PhaedrusTheGreek. Followed the same tutorial. No warnings on my gem build and have a practically identical gemspec. Let me know if this is being looked at/worked on or if there is any more information on how to test my local gem - thanks!

**Comment by ph** [comment]
@nathanclemente what is your logstash version and is the source code available somewhere I would like to look at it.

@PhaedrusTheGreek can you try with a more recent version of logstash?

**Comment by nathanclemente** [comment]
@ph Logstash 1.5.3 and https://github.com/nathanclemente/logstash-input-cloudwatchlogs is my repo - thanks!

**Comment by PhaedrusTheGreek** [comment]
@ph in my case the gem did not build because 'git ls-files' was not working.  I.e, git environment problem.

**Comment by Israaaaa** [comment]
Did you figure this one out yet? Help, please? As I am having the same error. I'm using Logstash 2.0.0

**Comment by ph** [comment]
@Israaaaa Which plugin `.gem` you are trying to install?

Can you look at the content of the **Gemfile** inside your logstash installation? You should see a line referencing your plugins with a relative path, If you look at the content of that path is there a `.gemspec` file in it?

**Comment by Israaaaa** [comment]
@ph I am trying to install a custom gem I created as a filter for logstash. When I do install it, it says install was successful. When I list the plugins using `plugin list` I can clearly see that gem in the list. But when I try use it in my config file, I get an error saying that the filter does not exist, and to make that it's been installed properly. The filter I made reads from jar files (don't know if this makes any different).

**Comment by Israaaaa** [comment]
Please note that the install happens locally, and the gem is install in the local_gems directory

**Comment by ph** [comment]
@Israaaaa Can you check the `vendor/local_gems/.../your_gem` to see if its include a `.gemspec`? the gemspec file itself need to be added to `files` option in the gemspec.

We are using in our plugin a line similar to this one to make sure all the required files are added to the gem at build time.
```
  s.files = Dir["lib/**/*","spec/**/*","vendor/**/*","*.gemspec","*.md","CONTRIBUTORS","Gemfile","LICENSE","NOTICE.TXT"]

**Comment by Israaaaa** [comment]
This is what can be found the `mygem.gemspec` file:

             # Files
             s.files = Dir['lib/**/*','spec/**/*','vendor/**/*','*.gemspec','*.md','CONTRIBUTORS','Gemfile','LICENSE','NOTICE.TXT']

**Comment by Israaaaa** [comment]
I'm also using jruby 1.7

**Comment by ph** [comment]
@Israaaaa is the source is available somewhere ?

**Comment by Israaaaa** [comment]
@ph It is available on my local machine. (I'm doing everything locally)

**Comment by Israaaaa** [comment]
And I also haven't created a remote repository to add the gem in it. I tried the following:

`gem install logstash-filter-mygem -v '0.1.0'`

But it gave me the following error:

`ERROR:  Could not find a valid gem 'logstash-filter-sentimentanalysis' (= 0.1.0) in any repository
ERROR:  Possible alternatives: logstash-filter-environment, logstash-filter-extractnumbers, logstash-filter-mixpanel, logstash-filter-docker_metadata, logstash-filter-units`

FYI, The following was also added to my Gemfile:

`gem "logstash-filter-mygem", "0.1.0", :path => "vendor/local_gems/4fc508c4/logstash-filter-mygem-0.1.0"`

**Comment by Israaaaa** [comment]
I think it's objecting on the jar files.

The exact error I get when I try to start the config file is the following:

`The error reported is:
  Couldn't find any filter plugin named 'mygem'. Are you sure this i
s correct? Trying to load the mygem filter plugin resulted in this e
rror: no such file to load -- thejarfilename`

To confirm, I commented out the lines that use the jar file, and guess what! It worked, and Logstash can now see it. However, this isn't going to work for me, as I need these jar files. Any help please?

Thank you.

**Comment by ph** [comment]
I will close this issue because all the case of local gems are resolved and answer you on the other issue you have just created https://github.com/elastic/logstash/issues/4171
