### ISSUE TITLE
s3 plugin - unable to change file extension of data in bucket

### ISSUE THREAD

**Issue by trekr5** [elastic/logstash#3973]
Hello,

I'm currently using the s3 plugin to upload logs from logstash into an s3 bucket. I'd like the uploaded files to be of the type json with a file extension of .json

My problem is that the uploaded files keep appearing as .txt text files even though I have made numerous changes to the s3 plugin code. The format of the file content is json but it has a file extension of .txt

Has anyone else experienced this issue? I don't know if it is because logstash runs constantly and locks the file while building it?

I would really appreciate some assistance.

Regards

**Comment by suyograo** [comment]
Hi can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
