### ISSUE TITLE
Create an obsolete syntax for config options 

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3977]
We need to create a special `obsolete` syntax/option for `config`. The idea is to use this for config options which have been marked deprecated. When `obsolete` is used on a config, it passes the config check, but LS will fail to start and it will provide a message that it has been deprecated and no longer relevant. This provides better feedback for users of deprecated configs.

Before a major version, config changes which are backward incompatible will be marked `deprecated`. A major version will remove the code usage, remove documentation, but keep the config option with the `obsolete` tag. The next major version will delete the config completely. 

Proposed by @andrewvc during the ES http default work. Ref issue from a user: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/258

**Comment by jordansissel** [comment]
Proposed user experience:

```
% bin/logstash -e 'input { stdin { debug => true } }'
Error: The setting `debug` in plugin stdin` is obsolete and is no longer available. Use the --debug flag instead. If you have any questions about this, you are invited to visit https://discuss.elastic.co/c/logstash and ask.
```

Very similar functionally to the `deprecated` setting with the exception that using an `obsolete` setting causes a configuration error on startup.
