### ISSUE TITLE
Flush doesn't happen on shutdown for some output plugins

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#3980]
If during shutdown the inputs didn't generate enough events to trigger a normal flush by reaching flush_size, the events won't be sent to elasticsearch.

reproduce steps:
1. start elasticsearch
2. use logstash 2.0 branch
3. bin/plugin install --version="2.0.0.beta6" logstash-output-elasticsearch
4. bin/logstash -e "input { generator { count => 50 } } output { elasticsearch { } }"
5. run logstash, wait to finish, then check elasticsearch event count

output from logstash using --debug: https://gist.github.com/jsvd/be4d7fafc2fc39b3eb8d

Plugins affected:
- [x] [logstash-output-elasticsearch](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/261) 
- [x] [logstash-output-lumberjack](https://github.com/logstash-plugins/logstash-output-lumberjack/issues/12) 
- [ ]  ????

**Comment by andrewvc** [comment]
For the ES output it looks like close isn't actually being invoked. I'll take a look at lscore and see where the issue is
