### ISSUE TITLE
When a filter is raising an exception, the filter worker dies.

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3983]
When there is an exception in a filter worker loop the thread dies and logstash just stop doing anything.
We should make sure we give a more explicitly error in the log.

```
:message=>"Exception in filterworker", "exception"=>#<NoMethodError: undefined method `<' for nil:NilClass>, "backtrace"=>["(eval):3636:in `cond_func_144'", "org/jruby/RubyArray.java:1613:in
```

**Comment by guyboertje** [comment]
we should give a better error message.  better still, we might not abort on exception, handle the exception, report up and respawn the worker thread.

**Comment by suyograo** [comment]
i think we should give a better error message for now and bubble it up. One problem with restarting is introducing poison messages which may need to be shunted to a dead letter queue after n tries

**Comment by ph** [comment]
I agree with poison messages, let it bubble the error  more clean first.  It was a bit weird for a user to debug.
