### ISSUE TITLE
Input file path has a broken placeholder behavior (does not match some dots)

### ISSUE THREAD

**Issue by func0der** [elastic/logstash#3988]
Hey there,

I am having a weird issue here.
I try to process a bunch of static apache access log files.
This is my logstash config:

```
input {
	file {
		path => "/tmp/logs/access.*.log"
	}
}
filter {
	grok {
		match => { "message" => "%{COMBINEDAPACHELOG}" }
	}
	date {
		locale => "en-US"
		match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
	}
}
output {
	elasticsearch {
		protocol => "http"
	}
        stdout {}
}
```

When I start logstash with that configuration file and the debug flag, everything is outputs is this (only the last line of the output):

```
_discover_file_glob: /tmp/logs/access.*.log: glob is: ["/tmp/logs/access.vm38-2.2015.10.01.log", "/tmp/logs/access.vm38-2.2015.10.02.log", "/tmp/logs/access.vm38-2.2015.10.03.log", "/tmp/logs/access.vm38-2.2015.10.04.log", "/tmp/logs/access.vm38-2.2015.10.05.log", "/tmp/logs/access.vm46-13.2015.10.01.log", "/tmp/logs/access.vm46-13.2015.10.02.log", "/tmp/logs/access.vm46-13.2015.10.03.log", "/tmp/logs/access.vm46-13.2015.10.04.log", "/tmp/logs/access.vm46-13.2015.10.05.log", "/tmp/logs/access.vm53-1.2015.10.01.log"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"132", :method=>"_discover_file"}
```

And this line is repeated over and over and over again without any logs being parsed.

Now comes the parts in which I think logstash is somehow broken.
I have tried to change the `path` in `input`. All of the following do work perfectly:

```
path => "/tmp/logs/*.log"
path => "/tmp/logs/access.*"
path => "/tmp/logs/access.*.*.*.*.log" # structure of all the file names
```

If I should test any other combination, please let me know.

So...this is weird.

What do you think about it?

Regards
func0der

**Comment by untergeek** [comment]
This belongs in https://github.com/logstash-plugins/logstash-input-file

Please move it there and close this one.

**Comment by func0der** [comment]
Oh. I did not know that. Thank you. I created it over there: https://github.com/logstash-plugins/logstash-input-file/issues/70

Closing this one.
