### ISSUE TITLE
redis connection problem does not log which host it has problems with

### ISSUE THREAD

**Issue by KlavsKlavsen** [elastic/logstash#3996]
I have 8 redis servers, which logstash is supposed to read from.. all seem to be fine.. but logstash sometimes logs:
{:timestamp=>"2015-10-07T12:33:01.812000+0200", :message=>"Redis connection problem", :exception=>#<Redis::TimeoutError: Connection timed out>, :level=>:warn}

Not really that helpful :(

it would be nice if it could log the name of the host in question.

**Comment by suyograo** [comment]
Moved to https://github.com/logstash-plugins/logstash-input-redis/issues/31
