### ISSUE TITLE
Loggly with Logstash

### ISSUE THREAD

**Issue by fizerkhan** [elastic/logstash#4003]
I installed Logstash `1.5.4` through `apt-get` under `/opt/logstash` . I want to send the log output to Loggly. 

I defined output configuration as follows
```
output{
   loggly{
      key => "my-token"
      tag => "logstash"
   }
}
```

Also installed Loggly output plugin as mentioned in [Loggly Doc](https://www.loggly.com/docs/logstash-logs/)

```
cd /opt/logstash/lib/logstash/outputs/
sudo wget https://raw.githubusercontent.com/psquickitjayant/logstash-output-loggly/master/lib/logstash/outputs/loggly.rb
```

But i got following error

```
{:timestamp=>"2015-10-08T13:53:34.372000-0400", :message=>"The error reported is: \n  Couldn't find any output plugin named 'loggly'. Are you sure this is correct? Trying to load the loggly output plugin resulted in this error: no such file to load -- logstash/outputs/loggly"}
```

Is there any problem in output plugin installed path? Where should i install `loggly.rb`?

**Comment by wiibaa** [comment]
The method mentionned in the doc is for `1.4.2`, it will not work with 1.5.
You should try using the plugin command `bin/plugin install logstash-output-loggly`

**Comment by fizerkhan** [comment]
@wiibaa Thanks. It works great. I think, Loggly did not update their documentation for 1.5.
