### ISSUE TITLE
Mention field exists/not exists options

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#4007]
[Here](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#conditionals).

eg if you want to check a field exists you can use `if [fieldname] { ....` and for not exists `if ![fieldname] { ....`. This is an implicit "does this exist/not exist" and it's super handy.

**Comment by palecur** [comment]
Render of the doc change is up at https://logstash-maint.firebaseapp.com; see PR https://github.com/elastic/logstash-docs/pull/144
