### ISSUE TITLE
install plugin from other gem source.

### ISSUE THREAD

**Issue by jinleileiking** [elastic/logstash#4008]
In some wired country ( I mean China).  We cannot access rubygems.org. So we need change the gem source. But in logstash, it seems use some black magic to set the source. I manage to use `ruby.taobao.org` to install plugin by change `rubygems/defaults.rb` default string to taobao. It is ugly,  Any other Solution ?

**Comment by suyograo** [comment]
@jinleileiking you should be able to use a mirrored plugins server. https://github.com/elastic/logstash/issues/3581 will be fixed in next LS version
