### ISSUE TITLE
nand and xor operators don't work

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/logstash#4012]
Judging by the definition of BooleanOperator in lib/logstash/config/config_ast.rb all boolean operator are implemented by interpolating the operator name into the Ruby code that's eval'ed, i.e. the Logstash expression `a or b` results in the `a or b` Ruby expression. Unfortunately there are no Ruby operators named `nand` and `xor` so use of those Logstash operators will result in an error message similar to this:

```
SyntaxError: (eval):22: syntax error, unexpected tIDENTIFIER
```

See also https://discuss.elastic.co/t/nand-and-xor-operators-not-working/31972.

**Comment by purbon** [comment]
good finding @magnusbaeck this makes complete sense and we should make sure this works as expected. not sure about the history behind this claims, most probably some old config never got updated.

@jordansissel can you provide us with some guidance here? I'm open to think we can implement this operators (https://github.com/elastic/logstash/blob/6d0298814226f419294c9b38022334d2eca103f2/lib/logstash/config/grammar.treetop#L226) to make sure all expectations are set, but might be this is an historical leftover. What do you think?

**Comment by andrewvc** [comment]
After discussing this with @jordansissel while  there isn't a lot of demand for these operators. We should remove them from the grammar before resolving this issue as a wontfix.

**Comment by original-brownbear** [comment]
@andrewvc damn I just spent 30 minutes making them work in the Java execution, work fine now. I guess we could keep them around, not sure if anyone cares though?

**Comment by original-brownbear** [comment]
Closing since this is now fixed in`master` as a result of switching it to Java execution.
