### ISSUE TITLE
Dot notation vs. Elasticsearch 2.0

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#4015]
Elasticsearch 2.0 will no longer accept dots in field names.  This will likely cause some issues with some (many?) user's configurations.

Options?  Suggestions?

One suggestion is to have the Elasticsearch output plugin automatically "de-dot" the fields with underscores or some other separator.

**Comment by electrical** [comment]
Do some auto expansion to make dot notated fields sub fields?
I think that was the whole idea in the past right?

**Comment by untergeek** [comment]
That may or may not be a desired outcome.  If we take that route, we'd have to perhaps have a configuration flag for it that allowed it to be optional.

**Comment by suyograo** [comment]
@untergeek I like your idea of using a de-dot codec. Making this a default behavior in ES output will be expensive (i.e. we need to go through every field in every doc for all use cases).

**Comment by jordansissel** [comment]
Wild thought: what about changing the field ref syntax to use dots like
Elasticsearch does?

**Comment by untergeek** [comment]
I like that idea!  But aren't we a little too feature-frozen to do that at this stage?

Also, unless we preserve the current behavior as well, this change would be a breaking one, where the stop-gap idea of the de-dot codec would be additive.

I'm a party-pooper, I know.  But I'm just sayin'...

**Comment by untergeek** [comment]
Logstash 5.0 for next spring?

**Comment by jordansissel** [comment]
Yeah totes. I wasn't clear - I meant moving to dot notation in a far future
release for consistency between Es and LS. For now, agree we need some kind
of workaround until then

**Comment by guyboertje** [comment]
How about, as a work around, we manipulate the final JSON string?

**Comment by untergeek** [comment]
I think we've addressed the chief offender [here](https://github.com/logstash-plugins/logstash-filter-metrics/issues/23).  Do we still want to keep this open?

**Comment by untergeek** [comment]
Okay, so de_dot filter it is, ref. https://github.com/logstash-plugins/logstash-filter-mutate/issues/54

**Comment by ppf2** [comment]
+1
