### ISSUE TITLE
graphite and exec input are failing tests

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4018]
Default plugin tests are failing in graphite and exec input. Details here: http://build-eu-00.elastic.co/view/LS%202.0/job/Logstash_Default_Plugins_20/322/console

**Comment by suyograo** [comment]
Interestingly, this works when I just clone logstash-input-graphite and run the specs inside the plugins.

**Comment by guyboertje** [comment]
I'm on the exec input now

**Comment by colinsurprenant** [comment]
I'm on the graphite input now

**Comment by guyboertje** [comment]
PR for input-exec - https://github.com/logstash-plugins/logstash-input-exec/pull/7

**Comment by suyograo** [comment]
Tracking in #3997
