### ISSUE TITLE
Logstash doesn't start with complex configuration

### ISSUE THREAD

**Issue by TeroPihlaja** [elastic/logstash#4019]
I have a few configuration files in logstash/conf.d

If I include the configuration file (http://pastebin.com/LALGveVk), logstash seems to get stuck on startup.

We are using the following inputs:
rabbitmq
lumberjack

And outputting to elasticsearch.

I see a lot of CPU and memory usage from logstash processes but it doesn't start up correctly (doesn't connect to rabbitmq or elasticsearch).

Logstash version is 1.5.4

**Comment by guyboertje** [comment]
@TeroPihlaja - you could try the translate filter, which I think is more suitable.  To double check this you should post a message on [Discuss](https://discuss.elastic.co/c/logstash)

**Comment by TeroPihlaja** [comment]
@guyboertje I agree, I changed the configuration to use the Translate-filter and now the configuration works as expected.
