### ISSUE TITLE
XML filter puts single xpath match into array

### ISSUE THREAD

**Issue by martinhynar** [elastic/logstash#4021]
Doc says: _Values returned by XPath parsing from xpath-syntax will be put in the destination field. Multiple values returned will be pushed onto the destination field as an array._

I have xml snippet:
```
<msg level="1">
  <txt>some text</txt>
</msg>
```

and logstash configuration:
```
input { courier { port  =>  1984 transport  =>  "tcp" } }
filter {
  xml {
    store_xml => "false"
    source => "message"
    target => "msg"
    xpath => [ "/msg/@level","level", "/msg/txt/text()", "txt" ]
  }
}
output { stdout { codec=> "json_lines" } }
```

The result contains unexpectedly this:
```
{
  "level": ["1"],
  "txt": [ "Some text" ]
}
```
I would expect that single matches will be put into plain field and as doc says, when more matches are available, array is created.

Logstash 1.5.4

**Comment by Guisardo** [comment]
This seems to be still happening.... is there any workaround?

**Comment by martinhynar** [comment]
What I did is to create temporary field with _ suffix, join it and overwrite the message field afterwards

```
filter {
  xml {
    store_xml => "false"
    source => "message"
    target => "msg"
    xpath => [ "/msg/@level","level", "/msg/txt/text()", "txt_" ]
  }
  mutate {
    join => [ "txt_", ""]
    update => { "message" => "%{txt_}"}
  }
}
```

After this I have index mapping that discards temporary fields with _ suffix - see https://goo.gl/PMCMII

**Comment by wiibaa** [comment]
Tracked directly in filter-xml issues

@suyograo can you close please
