### ISSUE TITLE
Logstash forwarder connection refused

### ISSUE THREAD

**Issue by Prashantpv** [elastic/logstash#4032]
Hi,

I am using the ELK stack on ubuntu. Its working well on the same server, but when I am sending the logs from the remote client using logstash forwarder then I am getting an error:

Failure connecting to X.X.X.X: dial tcp Y.Y.Y.Y:5000: connection refused

Also I am not getting an error when my logstash forwarder is on the same server where logstash server is installed.

To be added I am also using Kibbana 4 

Followed blog: https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04

**Comment by suyograo** [comment]
@Prashantpv please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
