### ISSUE TITLE
Elasticsearch 2.0.0-rc1 displaying strange data

### ISSUE THREAD

**Issue by clintongormley** [elastic/logstash#4048]
_From @robertsmarty on October 16, 2015 10:21_

I have logstash 2.0.0-beta2 sending AWS detailed billing data into elasticsearch 2.0.0-rc1 so I can test my setup. I've setup a template so all fields are doc_values.

Logstash rubydebug output looks great. Data is as expected. Elasticsearch dynamic mappings look great. Data types look great. Fields are not analysed. All good.

Then I look at the data. Weird, here's a small sample. Hopefully it'll make sense to someone...

            {
                "_index": "aws_billing-2015.08.31",
                "_type": "detailed_with_resources_and_tags",
                "_id": "\"60012830\",\"588738232867\",",
                "_score": 1,
                "_source": {
                    "@version": "1",
                    "@timestamp": "2015-08-31T23:00:00.000Z",
                    "host": "PBNEELK4001",
                    "type": "detailed_with_resources_and_tags",
                    "InvoiceID": "\"6001283",
                    "PayerAccountId": "\"60012830\",\"",
                    "LinkedAccountId": "\"60012830\",\"",
                    "RecordType": "\"6001283",
                    "RecordId": "\"60012830\",\"588738232867\",",
                    "ProductName": "\"60012830\",\"588738232867\",",
                    "RateId": "\"600128",
                    "SubscriptionId": "\"60012830",
                    "PricingPlanId": "\"60012",
                    "UsageType": "\"60012830\",\"58873823286",
                    "Operation": "\"600128",
                    "AvailabilityZone": "",
                    "ReservedInstance": "N",
                    "ItemDescription": "\"60012830\",\"588738232867\",\"128881676082",
                    "UsageQuantity": 0.00138889,
                    "BlendedRate": 1,
                    "BlendedCost": 0.00138889,
                    "UnBlendedRate": 1,
                    "UnBlendedCost": 0.00138889,
                    "ResourceId": null,
                    "aws_cloudformation_logical_id": null,
                    "aws_cloudformation_stack_id": null,
                    "aws_cloudformation_stack_name": null,
                    "user_Env": null,
                    "user_Environment": null,
                    "user_Name": null,
                    "user_Project": null,
                    "user_Purpose": null,
                    "user_Role": null,
                    "user_User": null,
                    "user_Workspace": ""
                }

This is what rubydebug looks like (it's not the same record though)...

{
                         "@version" => "1",
                       "@timestamp" => "2015-09-07T08:00:00.000Z",
                             "host" => "HOST4001",
                             "type" => "detailed_with_resources_and_tags",
                        "InvoiceID" => "xxx830",
                   "PayerAccountId" => "xxx867",
                  "LinkedAccountId" => "xxx944",
                       "RecordType" => "LineItem",
                         "RecordId" => "40214935098354950258880757",
                      "ProductName" => "Amazon Simple Storage Service",
                           "RateId" => "3510841",
                   "SubscriptionId" => "112242859",
                    "PricingPlanId" => "505699",
                        "UsageType" => "APS2-DataTransfer-Out-Bytes",
                        "Operation" => "ReadBucketPolicy",
                 "AvailabilityZone" => "",
                 "ReservedInstance" => "N",
                  "ItemDescription" => "$0.140 per GB - up to 10 TB / month data transfer out",
                    "UsageQuantity" => 1.16e-06,
                      "BlendedRate" => 0.13724872926531,
                      "BlendedCost" => 1.6e-07,
                    "UnBlendedRate" => 0.14,
                    "UnBlendedCost" => 1.6e-07,
                       "ResourceId" => "w-001006-emr-admin",
    "aws_cloudformation_logical_id" => nil,
      "aws_cloudformation_stack_id" => nil,
    "aws_cloudformation_stack_name" => nil,
                         "user_Env" => nil,
                 "user_Environment" => nil,
                        "user_Name" => nil,
                     "user_Project" => nil,
                     "user_Purpose" => nil,
                        "user_Role" => nil,
                        "user_User" => nil,
                   "user_Workspace" => ""
}

This worked perfectly on logstash 1.5 and elasticsearch < 2.x

_Copied from original issue: elastic/elasticsearch#14154_

**Comment by clintongormley** [comment]
This isn't an Elasticsearch issue. Moving to Logstash

**Comment by jsvd** [comment]
@clintongormley can you show me the logstash config and also the template you used? I just tried a normal logstash 2.0.0-beta2 and elasticsearch 2.0.0-rc1

`bin/logstash -e "input { generator { count => 20 } } output { elasticsearch { } }"`

and on elasticsearch side:

```
% curl -s 'http://localhost:9200/logstash-*/_search?pretty'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 20,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "logstash-2015.10.16",
      "_type" : "logs",
      "_id" : "AVBw3B9gWyGTIJZeUZFz",
      "_score" : 1.0,
      "_source":{"message":"Hello world!","@version":"1","@timestamp":"2015-10-16T13:34:44.531Z","host":"Joaos-MBP.lan","sequence":1}
    }, {
      "_index" : "logstash-2015.10.16",
      "_type" : "logs",
      "_id" : "AVBw3B9gWyGTIJZeUZF2",
      "_score" : 1.0,
      "_source":{"message":"Hello world!","@version":"1","@timestamp":"2015-10-16T13:34:44.532Z","host":"Joaos-MBP.lan","sequence":4}
    }, {
#....
```

**Comment by clintongormley** [comment]
Not me @jsvd, @robertsmarty opened the original issue.

**Comment by jsvd** [comment]
should have read the whole issue... @robertsmarty can you post the config and mapping?
thanks Clinton

**Comment by easyrasta** [comment]
+1 - I have same issue template working on beta1 and not on beta2 both on EL-rc1

**Comment by easyrasta** [comment]
```
 "message" => '%{INSERTERDATE:timestamp} -- %{DATA:file}\s+%{WORD:msg}\s+%{NUMBER:parsetime:int}\s+\w+-%{WORD:measuretype}-\d+\s+%{NUMBER:nbfile:int}\s+%{NUMBER:ok:int}\s+%{NUMBER:rows:int}\s+%{NUMBER:store:int}\s+%{NUMBER:elapsed:int}\s+%{NUMBER:wait:int}\s+%{DATA:transition:int}\s+%{NUMBER:nbTransition:int}\s+%{NUMBER:elapsedTransition:int}'
        }
```
rubydebug
```
{
              "message" => "20151016 170621,220 -- toto-20151016170306-4615-11306-25.90213            GOOD            0 INSERT           2      2     56     56     77      0 Transition-INSERT-70       0     11",
             "@version" => "1",
           "@timestamp" => "2015-10-16T17:06:21.220Z",
                 "host" => "host1",
                 "path" => "/usr/local/xxx/logs/mylog.log",
                 "file" => "toto-20151016170306-4615-11306-25.90213",
                  "msg" => "GOOD",
            "parsetime" => 0,
          "measuretype" => "INSERT",
               "nbfile" => 2,
                   "ok" => 2,
                 "rows" => 56,
                "store" => 56,
              "elapsed" => 77,
                 "wait" => 0,
           "transition" => 0,
         "nbTransition" => 0,
    "elapsedTransition" => 11
}
```
datastore in EL:
```
{
  "_index": "logstash-2015.10.16",
  "_type": "logs",
  "_id": "AVBxnr0jfVvUbEQe1TGR",
  "_score": 1,
  "_source": {
    "message": "20151016 170718,806 -- toto-20151016150224-4771-11463-25.95066            GOOD            0 INSERT          1      1     24     24     37      0 Transition-INSERT-70       0      6",
    "@version": "1",
    "@timestamp": "2015-10-16T17:07:18.806Z",
    "host": "host1",
    "path": "/usr/local/xxx/logs/mylog.log",
    "file": "20151016 170718,806 -- toto-20151016150",
    "msg": "2015",
    "parsetime": 0,
    "measuretype": "20151016 1",
    "nbfile": 1,
    "ok": 1,
    "rows": 24,
    "store": 24,
    "elapsed": 37,
    "wait": 0,
    "transition": 0,
    "nbTransition": 0,
    "elapsedTransition": 6
  },
  "fields": {
    "elapsedMeasure": [
      37
    ],
    "@timestamp": [
      1445015238806
    ]
  }
}
```

**Comment by splitice** [comment]
Perhaps related to https://github.com/elastic/logstash/issues/4055 ?

**Comment by suyograo** [comment]
@robertsmarty many thanks for reporting this issue. Beta3 has been released with this fix! https://www.elastic.co/blog/logstash-2-0-0-beta3-released
