### ISSUE TITLE
Trouble parsing comma separated long numbers from CSV files even though it's in double quotes. 

### ISSUE THREAD

**Issue by sirmodok** [elastic/logstash#4053]
I have a CSV file. A simplified row looks like this. 
`words,more words,23,"2,300",words`

When logstash parses this line, it ignores the fact that the "2,300" is in quotes and sees it as 2 fields. 
The CSV file is auto generated by a server(ServerA). It drops the CSV file in a folder and logstash forwards the file to my elasticsearch server(ServerB). 

This is the logstash config file for ServerA
```
input {
  file {
    path => "elk/*.csv"
    start_position => beginning
  }
}


output {
  stdout { }
  lumberjack {
     hosts => 'REDACTED'
     port => 5005
    ssl_certificate => "logstash-forwarder.crt"
  }
```
This is the config file on ServerB that does the filtering for the CSV file. 
```
filter {
  if [type] == "sample" {
    # Uses the csv plugin to parse information from a CSV file into elasticsearch
    csv {
      columns => ["header words", "header more words", "short number", "long number", "last words"]
      separator => ","
    }
    grok {
      match => {"header words" => "%{TIME:timestamp2}Z %{HOSTNAME:host} %{GREEDYDATA:Site}"}
    }
   # remove some useless fields
    mutate {
      remove_field => [ "timestamp2", "header words" ]
    }
    # Drop the top row of the CSV file
    if [header more words] == "header more words" { drop{ } }
  }
}
```
When logstash on ServerA picks up the CSV file and sends it to ServerB, the log on ServerA looks like this.

`2015-10-16T18:32:53.123Z words,more words,23,"2,300",words`

Notice that the quotes around 2,300 are still there. 

When I look at the log on ServerB as it receives this CVS file, I see this. 
```
 "message" => [[0] "2015-10-16T18:32:53.123Z words,more words,23,\"2,300\","words"],
                        "@version" => "1",
                      "@timestamp" => "2015-10-16T18:32:54.061Z",
                    "header words" => "words",
               "header more words" => "more words",
                    "short number" => "23",
                     "long number" => 2,
                           "words" => "words",
```
As a summery, what I see here is that my CSV file has quotes around any "cell" that has a long, comma separated value. That cell get's passed fine over the network to my logstash/elasticsearch server. When logstash on the logastah/elasticsearch server ingests the CSV file, it escapes out of the double quotes as seen here

`"message" => [[0] "2015-10-16T18:32:53.123Z words,more words,23,\"2,300\","words"],`

And then when the CSV filter parses the CSV file, it sees the comma as a separator. 

A few notes. 
1: The CSV file is auto-generated for me by a different process and I have no control over the output. 
2: I have, of course, obfuscated all of my real data and replaced it with place holder data such as "more words" 

Has anyone seen anything like this before and possibly have a work around?

**Comment by gmoskovicz** [comment]
You can use the gsub before using the csv filter:

```

      mutate {
        gsub => [
          "message", "\$([0-9]+)\,([0-9]+)", "$\1.\2"
        ]
      }

```

This will parse the following: `"$2,300",words` and create the following:

```
{
           "message" => "\"$2.300\",words",
          "@version" => "1",
        "@timestamp" => "2016-08-17T19:59:05.116Z",
              "host" => "Gabriels-MacBook-Pro.local",
             "Money" => "$2.300",
    "Something_else" => "words"
}
```

Then you can do anything else than you want at the filed level. You can set back the coma if you want in that number by using the reverse pattern in gsub.

Please use the discuss.elastic.co forum for any other question around this. We will be more than happy to help over there!
