### ISSUE TITLE
logstash 1.5.4 `|worker` thread crash

### ISSUE THREAD

**Issue by jstangroome** [elastic/logstash#4054]
I am running logstash 1.5.4 on Oracle Java 1.8 on Ubuntu Trusty 14.04 LTS.

```
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

$ uname -a
Linux ip-10-0-0-217 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

After a day or two of ingesting logs from ~12 servers, logstash stops processing new log entries. The process is still running but is not consuming any noticeable CPU time.

The `stderr` log only contains:
```
Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

This is similar to issues #3711 and #3811 but it is always only the `|worker` thread affected.

The `stdout` log only contains:
```
Sending logstash logs to /var/log/logstash/logstash.log.
```

And the `logstash.log` is has no new entries since the `SIGTERM received. Shutting down the pipeline.` message last time logstash was restarted.

Sending a `SIGQUIT` to the logstash process reveals a thread dump notably missing the `|worker` thread normally present in an operational logstash process, and all other normally running threads are `WAITING`. The (complete thread dump is available as a gist)[https://gist.github.com/jstangroome/0fb2a9fa4ff350804db5].

Normally restarting logstash (which requires `SIGKILL`-ing the current process) brings it back to life. In the most recent occurence, the restarted process failed almost immediately after processing only a relatively  small number of logs waiting in the redis input list.

The logstash host has ~2GB free memory and runs at <25% CPU during normal operation. At the point of failure, CPU usage falls.

**Comment by suyograo** [comment]
`java.lang.UnsupportedOperationException` usually means a heap issue. By default LS heap is 500mb. You can increase it by setting `LS_HEAP_SIZE`. Are you using ES output?

**Comment by jstangroome** [comment]
We are using ES outputs (via http) to two different ES clusters, both separate from the logstash server.

The LS_HEAP_SIZE does appear to be the default 500mb. Is there any guidance on increasing this by a particular factor, or estimating a required heap size based on logstash config?

full logstash args (notably `Xmx500m -Xss2048k`):
```
$ ps -F $(cat /run/logstash.pid)
UID        PID  PPID  C    SZ   RSS PSR STIME TTY      STAT   TIME CMD
logstash 28553     1 28 762615 794160 1 Oct18 ?        SNl  751:24 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.io.tmpdir=/var/lib/logstash/ -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.io.tmpdir=/var/lib/logstash/ -Djava.io.tmpdir=/var/lib/logstash -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log --log /var/log/logstash/logstash.log
```

full logstash environment (notably `LS_HEAP_SIZE=500m`):
```
$ while read -d $'\0' line; do echo $line;done < <(sudo cat /proc/$(cat /run/logstash.pid)/environ)
TERM=xterm
JAVA_OPTS= -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.io.tmpdir=/var/lib/logstash/ -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -Xss2048k
PATH=/sbin:/usr/sbin:/bin:/usr/bin
LS_HEAP_SIZE=500m
PWD=/var/lib/logstash
LS_JAVA_OPTS=-Xmx256m -Djava.io.tmpdir=/var/lib/logstash/ -Djava.io.tmpdir=/var/lib/logstash
LANG=en_US.UTF-8
SHLVL=0
HOME=/var/lib/logstash
JAVACMD=/usr/bin/java
LOGSTASH_HOME=/opt/logstash
```

**Comment by jstangroome** [comment]
Logstash just crashed again this morning in the same state. I've taken this opportunity to increase the `LS_HEAP_SIZE` from the default value to `1024m` hopefully this will mitigate the issue.

It would be great to get a build of Logstash 1.5 using JRuby 1.7.22 which will hopefully reveal more information in this situation which is currently obscured by the UnsupportedOperationException in Thread.stop().

We likely won't be able to adopt Logstash 2.x for a while.

**Comment by suyograo** [comment]
@jstangroome another suggestion is to reduce the `flush_size` in Elasticsearch output to 500. The current default (5000) can cause crashes if your document size is big. Also +1 on increasing `LS_HEAP_SIZE` to 1GB

re: UnsupportedOperationException, I commented on #3711 we will ship 1.5.5 with JRuby 1.7.22
