### ISSUE TITLE
build new filter plugin using sqlite3 gem for ruby, but can't be installed by bin/plugin

### ISSUE THREAD

**Issue by irenerong** [elastic/logstash#4058]
Hi i wanted to use logstash to parse a scsv file , and query a sqlite db in the filter. So i'm building a gem file using sqlite3 gem dependency. 
within my plugin directory, i use ruby 2.1.1 to do bundle install and gem build to have my logstash-filter-myplugin.gem, i had no probleme to resolve the sqlite33 dependency.
Then i use bin/plugin install, it can't continue with a problem:
**Validating /home/admin/logstash-filter-geoiata/logstash-filter-geoiata-0.0.1.gem
Installing logstash-filter-geoiata
Error Bundler::InstallError, retrying 1/10
An error occurred while installing sqlite3 (1.3.11), and Bundler cannot continue.**

i'm supposing , maybe it's because , bin/plugin method use "jruby's" bundler, but my sqlite3 is a ruby gem? or it's because i  have a network issue. 

i also have tried directly download sqlite3(1.3.11), i have no problem

**Comment by suyograo** [comment]
@irenerong was the `logstash-filter-geoiata` gem created using JRuby? To build LS plugins you need JRuby, it does not work on MRI at this point.

**Comment by irenerong** [comment]
non i didn't do that , because it's not mentioned in the tutorial (i think it's better to put this in the begining of the tuto:https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html) , But i figured out yesterday myself it's should be built by jruby! now it's working fine, thanks!

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
