### ISSUE TITLE
Host setting does not exists in elasticsearch input

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#4071]
https://www.elastic.co/guide/en/logstash/2.0/plugins-inputs-elasticsearch.html#plugins-inputs-elasticsearch-docinfo

The documentation is wrong, the `host` setting doesn't exists. It should be `hosts`:

```
input { 
    elasticsearch { 
        host => '<hostname>'
        index => "logstash-2015.10.21"
    } 
}
```

Should be:

```
input { 
    elasticsearch { 
        hosts => ['<hostname>']
        index => "logstash-2015.10.21"
    } 
}
```

**Comment by barryhatfield** [comment]
Additionally, on the same page index_type is deprecated so it shouldn't be an example:

output {
  elasticsearch {
    index => "copy-of-production.%{[@metadata][_index]}"
    index_type => "%{[@metadata][_type]}"
    document_id => "%{[@metadata][_id]}"
  }
}

**Comment by suyograo** [comment]
Fixed. https://www.elastic.co/guide/en/logstash/2.0/plugins-inputs-elasticsearch.html
