### ISSUE TITLE
[meta] codec stream identity

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4074]
this issue follows up the discussion in logstash-plugins/logstash-codec-multiline#10 about supporting stream identity in codecs to solve the problem of using the multiline codec in conjunction with the file or lumberjack inputs for example.

Since this issue involves many plugins and is an important issue to solve we should keep track of it here.

My [last suggestion](https://github.com/logstash-plugins/logstash-codec-multiline/issues/10#issuecomment-149993542) is to do the following:
- replace the codec instantiation in the config to instead instantiate a new "codec multiplexer" class, which will ultimately expose a **backward compatible** decode method like `decode(data, stream_identity = nil)`
- this new multiplexer `decode` method would take care of doing the bookkeeping of the stream identities vs actual codec instances.

This would allow to not touch/update all plugins where dealing with stream identities in codecs is not important and simply update the ones like file & lumberjack inputs to pass the values which makes sense as `stream_identity` to the `decode` method. for example for file input, the current code:

``` ruby
    @tail.subscribe do |path, line|
      @codec.decode(line) do |event|
```

would become:

``` ruby
    @tail.subscribe do |path, line|
      @codec.decode(line, path) do |event|
```

For the codecs nothing would change and we can all assume a single codec instance will always deal with a single consistent stream.

**Comment by guyboertje** [comment]
@colin, @ph - will each input know the full set of stream_identity values when starting or is there dynamic stream_identity detection and new codec spawn while receiving data?

**Comment by guyboertje** [comment]
As expressed in [this comment](https://github.com/logstash-plugins/logstash-input-file/issues/44#issuecomment-124762024), do I presume that multiple file inputs having different absolute paths will not use any form of codec multiplexing?

**Comment by jordansissel** [comment]
The following question is meant earnestly, and I am on my phone so I will
be brief -

Do we need an abstraction for this? How many plugins would benefit? Only
file and lumberjack? Maybe TCP? Each of these (3) plugins have different
thread models so it may be irritating to make one interface for all - my
counter question is this: can we just implement what each of these plugins
need in each plugin that needs it? For data points, what plugins need this
multiplexing?

**Comment by colinsurprenant** [comment]
@guyboertje `stream_identity` is specific to each input plugin and its the plugin developer to decide which attribute at hand in the plugin to identify streams. Ex. the file path in the file input is what identify each stream. I think we only need to be able to pass whatever attribute value identifies a stream within an input plugin down in the codec (de)multiplexer. I don't think there is a need to have stream_identity detection? all the information to identify a stream should normally be available at the input level, before the decoding takes place.

@jordansissel I don't see that as much as a potential "over engineering abstraction" but more of a way to actually introduce a consistent codec (de)multiplexing mechanism while preserving backward compatibility and avoiding having to re implement this logic in the few plugins we know will use that. 

It seems to me a clean and simple implementation (provided it actually does cover all bases :P ).

**Comment by ph** [comment]
Lets talk about `stream_identity` life and their relation to the UDP/TCP/Lumberjack usage.

Right now in the lumberjack input we clone the codec on each new connection, which would mean that the `stream_identity` would be valid until the connection dies. This can happen when we have back pressure. Do we want to make the `stream_identify` more resilient to theses can of scenario?

If we want to, the `stream_identity` would need to keep values with an expiration and do some book keeping?

**Comment by colinsurprenant** [comment]
in the lumberjack input, IMO the stream identity should not be defined by the connection, it should be defined from of one of the fields.

**Comment by ph** [comment]
@guyboertje Following with the information form the LSF, this is the metadata that LSF send.

```
writeKV("file", *event.Source, output)
writeKV("host", hostname, output)
writeKV("offset", strconv.FormatInt(event.Offset, 10), output)
writeKV("line", *event.Text, output)
```

**Comment by colinsurprenant** [comment]
perfect! file + host should be good for stream identity.

**Comment by ph** [comment]
For beats see this document:
https://github.com/elastic/filebeat/blob/master/etc/fields.yml

For 'filebeat' we are intested in the `shipper` and the `source` option.
The shipper will be the hostname or the configured beat name in the config file.

**Comment by guyboertje** [comment]
Yes.  It seems that we should have two stream_identity strategies for connection based inputs.

Firstly, the client end of the connection may wish to generate a robust and long lasting stream_identity per logical data source on its end - then it should specify this in a known field.

Secondly, if the client does not supply the stream_identity then the server end will best-efforts build a stream_identity from other fields.

**Comment by colinsurprenant** [comment]
we could introduce a new configurable option in the emitters to specify a stream identity, in LSF for example it could default to file + host. It could be something similar to what we have in the multiline filter:

```
config :stream_identity , :validate => :string, :default => "%{host}.%{path}.%{type}"
```

but instead of configuring this on the receiver end, it could be configured on the emitter end. So in LSF and beats we would end up with a consistent "stream identity" field.

In the multiline filter in makes sense to have this config option because we have access to a full Event and we can use any Event fields to figure a stream identity. But in this case we are discussing, we don't have access to an Event yet, and the information to figure a stream identity has to be available at the input level, prior to decoding. LSF & Beats works well for this because we are passing meta info available prior to decoding.

**Comment by acchen97** [comment]
@guyboertje @ph this appears to be solved, should be close this?
