### ISSUE TITLE
Fix protocol defaults

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#4076]
As per [here](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-protocol)
```protocol

 * Value can be any of: node, transport, http
 * There is no default value for this setting.
Choose the protocol used to talk to Elasticsearch.

The node protocol (default) will connect to the cluster as a normal Elasticsearch node (but will not store data). If you use the node protocol, you must permit bidirectional communication on the port 9300 (or whichever port you have configured).
```

Node is default, we need to fix that second point.

Reported [here](https://twitter.com/jrhunt/status/657097315446951936).

**Comment by jordansissel** [comment]
Agreed, though in logstash 2.0 the default (and only) value is http. So I
think this is resolved once that is released. Thoughts?

**Comment by markwalkom** [comment]
Yep, but if we're keeping older documentation around (a la ES) then we
should till fix it :)

**Comment by suyograo** [comment]
Fixed https://www.elastic.co/guide/en/logstash/1.5/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-protocol

Thanks @markwalkom
