### ISSUE TITLE
Postgresql grok pattern fails

### ISSUE THREAD

**Issue by grahamrhay** [elastic/logstash#4077]
The postgres grok pattern (https://github.com/elastic/logstash/blob/v1.4.2/patterns/postgresql#L2) doesn't seem to be compatible with postgres 9.4. I'm not sure when the format changed.

Specifically, the pid at the end is no longer there. This is what I'm using:

%{DATESTAMP:timestamp} %{TZ} %{DATA:user_id} %{GREEDYDATA:connection_id} %{DATA:level}:  %{GREEDYDATA:msg}

**Comment by purbon** [comment]
@grahamrhay thanks a lot for your contribution, this days patterns have they own repo in https://github.com/logstash-plugins/logstash-patterns-core .

Would you be so nice to open an issue there? you might also want to add a PR with this change, this would be really welcome.

After you open the issue there, please feel free to close this one.

Thanks a lot.

**Comment by grahamrhay** [comment]
ah, sorry, didn't realise. it hasn't got enough google juice yet :)

**Comment by grahamrhay** [comment]
https://github.com/logstash-plugins/logstash-patterns-core/issues/112

**Comment by purbon** [comment]
Thanks a lot @grahamrhay
