### ISSUE TITLE
Update elasticsearch output parameter names in Setting Up an Advanced Logstash Pipeline docs

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/logstash#4082]
The _Setting Up an Advanced Logstash Pipeline_ documentation ([advanced-pipeline.asciidoc](https://github.com/elastic/logstash/blob/master/docs/asciidoc/static/advanced-pipeline.asciidoc)) still refers to the obsolete `host` and `protocol` options (both replaced by `hosts`) in a couple of places. Technically the old options still work but the documentation should recommend the current options.

**Comment by untergeek** [comment]
Thanks for bringing this to our attention, @magnusbaeck

**Comment by suyograo** [comment]
Fixed https://www.elastic.co/guide/en/logstash/2.0/advanced-pipeline.html
