### ISSUE TITLE
Output plugin Elasticsearch ignores user:pass in proxy setting

### ISSUE THREAD

**Issue by scaarup** [elastic/logstash#4083]
Proxy is defined as (per documentation):
proxy => "http://user:pass@proxyhost:3128"

Works fine with curl etc, but logstash cannot figure out to use authentication:
    {:timestamp=>"2015-10-23T10:24:07.452000+0200", :message=>"Got error to send bulk of actions: [407] <html><head><title>407 Proxy Authentication Required</title></head>\r\n<body><h2>407 Proxy Authentication Required</h2><h3>Access to requested resource disallowed by administrator or you need valid username/password to use this resource</h3></body></html>\r\n", :level=>:error}

**Comment by arkadyi** [comment]
I actually has the same problem. I see this bug has been closed w/o any explanation/solution.
Where can I find how to solove this problem?
