### ISSUE TITLE
Running logstash from a symbolic link fails (possible fix/workaround included)

### ISSUE THREAD

**Issue by zachking** [elastic/logstash#4084]
Logstash fails when it is invoked from a symbolic link, */usr/bin/logstash* for example.

The following line in *bin/logstash* does not resolve symbolic links (line 22):

    . "$(cd `dirname $0`/..; pwd)/bin/logstash.lib.sh"

It could be changed to something along the lines of 

    . "$(cd $(dirname `readlink -f $0`); pwd)/logstash.lib.sh"

Similarly in *bin/logstash.lib.sh* (line 2):

    LOGSTASH_HOME=$(cd `dirname $0`/..; pwd)

It could be changed to something along the lines of 

    LOGSTASH_HOME="$(cd $(dirname `readlink -f $0`)/../; pwd)"

This issue occured on *Centos 7* using *logstash-1.5.4*

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/4292
