### ISSUE TITLE
Kafka input affects json filter add_field operation

### ISSUE THREAD

**Issue by siddharthasahu** [elastic/logstash#4095]
json {
        source => "message"
        add_field => { "parse_error" => 0 }
}

The parse_error field appears when I use stdin input, but does not appear when I use the kafka input plugin. Tried doing it for the same message, sending both through stdin and kafka.

Any ideas what could be the issue?

**Comment by Xylakant** [comment]
The kafka input uses the json codec by default and already decodes the message field. Probably using a json filter on an existing json fails and the field is not added. See https://www.elastic.co/guide/en/logstash/2.1/plugins-inputs-kafka.html#plugins-inputs-kafka-codec

**Comment by siddharthasahu** [comment]
Ah yes, that was it. It does not throw a jsonparseerror though.

Thanks for the tip.
