### ISSUE TITLE
Allow Logstash Queue Size to be Configurable

### ISSUE THREAD

**Issue by thelok** [elastic/logstash#4096]
I would like the ability for users of logstash to configure their own queue size instead of using the hardcoded value of 20 (there are multiple instances of this).

https://github.com/elastic/logstash/blob/93958be3cdc039db77789fa51f521fb19260eb79/lib/logstash/outputs/base.rb#L63

Users have different environments and this number could be tweaked for better performance (with the understanding that a bigger size could mean more loss of data if the logstash instance dies). If you want to supply a default value of 20 in a configuration file that's fine.

**Comment by untergeek** [comment]
The changes coming in future releases of Logstash will make this somewhat (if not completely) moot.

See #2609

**Comment by suyograo** [comment]
Hi @thelok as you mentioned, increasing the size could lead to potential loss of messages when Logstash crashes. We will be addressing the resiliency aspect using persistent queues, and our idea is to make those queues variable. Let us know if you have more questions!
