### ISSUE TITLE
Graphite output sending metrics every 1 to 5 seconds

### ISSUE THREAD

**Issue by trenb** [elastic/logstash#4099]
Hello! We're seeing an issue where the graphite output for logstash 1.5.x (tried both 1.5.1 and 1.5.4) are sending metrics far too often. Our graphite flush interval is 10s, but it looks like logstash is sending data every 1 to 5 seconds. In less than 60 seconds logstash sends over 30 metrics. I haven't found a way to set a flush interval for the graphite output to possibly curb this output. I've cleaned up the tcpdump data to only show the timestamp and the metric value. I've also attached the relevant sections of the configuration file.

Please let me know what other information you need to help resolve this issue.

Time Stamp | Metric value
---------- | ----------
18:36:06.218506 | 2014.0694022039097
18:36:09.109487 | 0.0003298800007348804
18:36:09.126179 | 0.01725653926907217
18:36:11.218657 | 1952.9458036527249
18:36:14.109839 | 0.00027923739202897867
18:36:14.126638 | 0.01725653926907217
18:36:16.218971 | 0.0
18:36:19.108619 | 0.00027923739202897867
18:36:19.126874 | 0.014607345126126827
18:36:21.219442 | 2057.4
18:36:24.109335 | 0.00025691080289192054
18:36:24.127625 | 0.014607345126126827
18:36:26.218453 | 2029.6873941105234
18:36:29.109612 | 0.0002363693492586465
18:36:29.127553 | 0.012364850698436342
18:36:31.218892 | 2034.6696349903889
18:36:34.109475 | 0.0002363693492586465
18:36:34.126486 | 0.012364850698436342
18:36:36.218827 | 2005.5122608578213
18:36:39.109726 | 0.0002000823344717311
18:36:39.126732 | 0.01046662014722731
18:36:41.219014 | 1971.8579746512391
18:36:44.109592 | 0.0002000823344717311
18:36:44.126960 | 0.01046662014722731
18:36:46.219230 | 1926.1987000074062
18:36:49.109215 | 0.00018408463429671232
18:36:49.126185 | 0.009629755406503232
18:36:51.218614 | 1916.620124821668
18:36:54.109384 | 0.00016936603960377174
18:36:54.126794 | 0.009629755406503232
18:36:56.218765 | 1910.6858112952668
18:36:59.109545 | 0.00016936603960377174
18:36:59.127051 | 0.008859802675999827

```
# filter_10_metrics_add_metrics
filter {
 metrics {
  add_tag => ['metric']
  meter => ['events']
  clear_interval => 60
 }
}

output {
 if 'metric' in [tags] {
    graphite {
        host => 'graphite.xxx.com'
        metrics => ["dw13_xxx_com.consumed.event_rate", "%{events.rate_1m}"]
    }
 }
}

**Comment by suyograo** [comment]
Have you tried setting the `flush_interval` in metrics filter? https://www.elastic.co/guide/en/logstash/1.5/plugins-filters-metrics.html#plugins-filters-metrics-flush_interval

**Comment by trenb** [comment]
Yes, I did. It made no difference. 

According to the documentation, the default flush_interval is 5s, and if you look at the time stamps, data is being sent more often than 5s even.

**Comment by purbon** [comment]
@trenb this is actually a good improvement for the graphite output, I would say we should add some flush_interval capabilities directly there, what do you think? if ok for you, can you reopen this issue in the output so we track this issue from there?

As a workaround from now on, you might like to use the sleep filter (https://www.elastic.co/guide/en/logstash/current/plugins-filters-sleep.html), this filter will let you sleep for a while each number of events.

/cheers

**Comment by trenb** [comment]
Once I get a few spare minutes, I'll move this ticket over.

@purbon - To get this working for now, I'm using the statsd output to aggregate the metrics into a useable number, which is working well. However the graphite output worked fine in LS 1.1.9, but broke for us when we upgraded to LS 1.5.x. A flush_interval for the graphite output would be a welcome addition.

Thank you!

**Comment by trenb** [comment]
Closing in favour of https://github.com/logstash-plugins/logstash-output-graphite/issues/19
