### ISSUE TITLE
Update logstash-filter-aggregate plugin documentation into logstash reference documentation

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#4122]
Hi, 

I have recently added enhancements to asciidoc documentation in logstash-filter-aggregate plugin.
Could you update logstash reference documentation to integrate these enhancements ?

To do this :
Could you update "logstash reference 2.0" and "logstash reference master" using logstash-filter-aggregate master branch ?
Could you update "logstash reference 1.5" using logstash-filter-aggregate "core-api-v1" branch ?

**Comment by suyograo** [comment]
@fbaligand can you please update the aggregate.rb with 2 space indentation instead of 4? That is messing up doc generation (not sure why?). But the spacing is consistent with all our other ruby code.

**Comment by suyograo** [comment]
@fbaligand also please don't use tabs, just spaces.

**Comment by fbaligand** [comment]
@suyograo ok, thanks for the tip.
I just fix indentation as you say, in all code, including tests.
This fix is a part of my last pull request : https://github.com/logstash-plugins/logstash-filter-aggregate/pull/9

Feel free to review it :)

**Comment by fbaligand** [comment]
@suyograo 
master branch and core-api-v1 have been merged.
So if it's all right for you, you can now update logstash-filter-aggregate official documentation (version 1.5 and 2.0).

**Comment by fbaligand** [comment]
@suyograo 
I saw that you updated "logstash 2.0 reference documentation" => thanks a lot !
Can you do the same on "logstash 1.5 reference documentation" ?

Thanks in advance ;)
Fabien
