### ISSUE TITLE
Unable to remove_field on [@metadata] fields

### ISSUE THREAD

**Issue by erik-stephens** [elastic/logstash#4124]
I would like to be able to clear/unset any fields that any upstream process or config may set in [@metadata] that clash with my configuration.  As a workaround, one can use mutate::replace but remove_field seems more natural since there is no way to replace a field with `null/nil/undefined` - perhaps that's a simpler change if touching remove_field seems too dangerous.

In the mean time, might want to update the docs for remove_field to make it clear that it will not operate on [@metadata].  Might also want to come up with some "rules of engagement" for using [@metadata].  It was my understanding that [@metadata] was a namespace reserved for my configuration but it's possible for inputs, filters, and outputs to modify it as well.

Please refer to [this issue for more background](https://github.com/logstash-plugins/logstash-input-beats/issues/6#issuecomment-152673153).

**Comment by ep4sh** [comment]
Still no solution?

**Comment by colinsurprenant** [comment]
Confirmed. As discussed in logstash-plugins/logstash-input-beats#6 I also agree `remove_field` should work against `@metadata`.

**Comment by colinsurprenant** [comment]
Fixed by #11334, closing.
