### ISSUE TITLE
Creating a new field using Logstash Filter

### ISSUE THREAD

**Issue by Israaaaa** [elastic/logstash#4128]
I have started writing my own Logstash-filter, based on the example filter provided on Github:

> https://github.com/logstash-plugins/logstash-filter-example

My new filter reads from a jar file called ``` Classficiation.jar ```. I would like to take the values coming from text and based on that, classify these texts. This will require creating a new field and adding the classification in it.

The operation should result in the following:

INPUT

``` {"text" : "This is a happy thought :)"} ```
OUTPUT

``` {"text" : "This is a happy thought :)", "classification" : "Positive"} ```

However......I'm not quiet sure how I should create this new field. As you can see, the class takes one parameter, which is text.

I would really appreciate guidance on how I can create the new field for the output from this logstash filter.

```
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require 'java'
require 'Classficiation.jar'

import 'classficiation.Classficiation'

class LogStash::Filters::Classify < LogStash::Filters::Base

  # This is how to configure this filter from Logstash config.
  #
  # filter {
  #   classify {
  #   }
  # }
  #
  config_name "classify"


  t = Java::classficiation::Classficiation.new
  result = t.Classify(:text)
  # This should return a classification for the text, either positive
  # or negative

  public
  def register
  end

  public
  def filter(event)    
    ..........
  end

    filter_matched(event)
  end
end
```

My problem is that I cannot find any sort of guide other than the following:

> https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html?q=logstash%20filte
 
that might explain on detail how to write a filter, if I was not an expert in Jruby. Please help! 

Thank you.

**Comment by purbon** [comment]
Hi,
  I think you will benefit the most to ask this question at the discuss forum, see https://discuss.elastic.co/c/logstash, there you might find more help. We prefer to keep github issues for issues. Please reopen this in case you find a particular problem with the documentation.

Adding fields in the event is as easy as doing ``` event[key] = value ```

/cheers.
