### ISSUE TITLE
Minor / Documentation: mention metrics filter continues generating messages after input is finished

### ISSUE THREAD

**Issue by buddyp450** [elastic/logstash#4132]
This stood out to me as some unexpected behavior for the metrics plugin.. I wanted to know my events per second while the input was being consumed for a file input. Once the file input was finished, metrics were being continually pushed to my output despite the input not having generated any messages (since it was at EOF and not tailing anything).

Might be worth mentioning on the metrics plugin page that this is the behavior.

**Comment by suyograo** [comment]
Thanks @buddyp450. Moved to https://github.com/logstash-plugins/logstash-filter-metrics/issues/27
