### ISSUE TITLE
Field value comparison should be fault tolerant when the field doesn't exist

### ISSUE THREAD

**Issue by garyelephant** [elastic/logstash#4138]
The following config:

```
if [ver] > '5.5.0' {
    # do something....
}
```

When field `ver` doesn't exist, logstash will throw exception at runtime.

```
{:timestamp=>"2015-11-03T18:00:38.480000+0800", :message=>"Exception in filterworker", "exception"=>#<NoMethodError: undefined method `>=' for nil:NilClass>, "backtrace"=>["(eval):3845:in `cond_func_206'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):3843:in `cond_func_206'", "(eval):903:in `filter_func'", "/usr/local/logstash-1.5.0.rc4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/usr/local/logstash-1.5.0.rc4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:156:in `start_filters'"], :level=>:error}
```

**Comment by jordansissel** [comment]
This comes up from time to time, but we never have found a way to really resolve it. A condition can be true or false, but comparing _nothing_ to anything else doesn't even really make sense, so we'd have to define that behavior, and I don't have ideas or any proposals for that yet.

As a workaround, you can do this:

```
if [ver] and [ver] > '5.5.0' {
  # do something
}
```

This will only do the greater-than check against `[ver]` if `[ver]` exists and has a value.

**Comment by untergeek** [comment]
Heh.  I had a similar response, and @jordansissel beat me to it by 60 seconds.

**Comment by jordansissel** [comment]
@untergeek *high five*

**Comment by untergeek** [comment]
:hand: woot!

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
