### ISSUE TITLE
Kibana 4.0 IE 11

### ISSUE THREAD

**Issue by bmorse526** [elastic/logstash#4142]
When kibana 4.0 is on a windows server, and IE 11 is used to access it the function icons do not show (new, save, load, etc...) on any of the various pages.  IE 11 is running in a secure state and no messages or errors are received.
Using Firefox, they do show.

**Comment by purbon** [comment]
@bmorse526 thanks a lot for your repo, but I think you confused the repo. If you're looking for kibana, please refere to https://github.com/elastic/kibana .

Closing this issue for now as it refer to kibana, not logstash.
