### ISSUE TITLE
Include JDBC logstash input plugin by default

### ISSUE THREAD

**Issue by CraigFoote** [elastic/logstash#4154]
This plugin is very useful and most of our sources use it. We're on a secured, non-internet-connected intranet and so I have to install this plugin manually at home, tar up the logstash folder, transfer to a USB key and walk it into work to install on our secure network. Additionally we just found a bug was introduced in 2.0 (https://github.com/logstash-plugins/logstash-input-jdbc/issues/77) so I'll have to repeat the process once a new release comes out.

**Comment by suyograo** [comment]
Thanks @CraigFoote. Will do this in the next release

**Comment by CraigFoote** [comment]
Thanks Suyog!

**Comment by suyograo** [comment]
Fixed in 2.1
