### ISSUE TITLE
Unable to find JRuby

### ISSUE THREAD

**Issue by eromoe** [elastic/logstash#4160]
I download logstash 2.0.0 from here. 
test output:
```
D:\logstash\bin>logstash -e 'input { stdin { } } output { stdout {} }'
Unable to find JRuby.
If you are a user, this is a bug.
If you are a developer, please run 'rake bootstrap'. Running 'rake' requires the 'ruby' program be available.
```
windows also alert to ask me how to open `.rb`, I have ruby installed, but not familiar with it. 
Because it says `If you are a user, this is a bug`.  so I think I don't need to install JRuby.Google also do not tell me how to go through it...

How do I solve this?

**Comment by suyograo** [comment]
@eromoe do you have a JVM? if so whats `java -version`?

**Comment by purbon** [comment]
@eromoe I wonder if you had just cloned the repo here in github? If you cloned the repo you need to first bootstrap your system, by using ```rake boostrap```, but this is usually for developers. For users is better to grab a packages as the ones provided at https://www.elastic.co/downloads/logstash

**Comment by eromoe** [comment]
@purbon you are right.package from https://www.elastic.co/downloads/logstash work well.Thanks.

**Comment by monster-hkim** [comment]
Using the package from https://www.elastic.co/downloads/logstash works under Windows 7 but fails with the same error messages under Windows Server 2012 R2. Any ideas? Thanks.
