### ISSUE TITLE
HOST pattern removed from Grok, breaking existing installations

### ISSUE THREAD

**Issue by mjs510** [elastic/logstash#4162]
Logstash 1.5.5 ships with updated Grok patterns and these have removed the HOST pattern that was previously defined. This causes existing installations that use this pattern to fail to start logstash, with errors such as:

{:timestamp=>"2015-11-10T15:12:02.106000+0000", :message=>"The error reported is: \n  pattern %{HOST:log_host} not defined"}

The pattern was removed in https://github.com/logstash-plugins/logstash-patterns-core/commit/24cc67919cdf8ab6058e0b1952b6eee501402d88 I'd say this change should not have been made as it breaks backwards compatability.

**Comment by suyograo** [comment]
This was fixed as part of https://github.com/logstash-plugins/logstash-patterns-core/issues/118

You can install the new version by:

```
bin/plugin install --version 0.1.10 logstash-patterns-core
```

This will be included in the next LS release.

**Comment by djkerya** [comment]
# bin/plugin install --version 0.1.10 logstash-patterns-core
Validating logstash-patterns-core-0.1.10
Installing logstash-patterns-core
Plugin not found, aborting
ERROR: Installation Aborted, message: You have requested:
  logstash-patterns-core = 0.1.10

The bundle currently has logstash-patterns-core locked at 0.4.0.
Try running `bundle update logstash-patterns-core`

# bin/bundle update logstash-patterns-core
bash: bin/bundle: No such file or directory
# bundle update logstash-patterns-core
bash: bundle: command not found

**Comment by boeboe** [comment]
My two cents:

**logstash configuration file:**

`
filter {
  if [type] == "nginx-access" {
    grok {
      patterns_dir => ["/etc/logstash/conf.d/patterns"]
      match => { "message" => "%{NGINXACCESS}" }
    }
  } else if [type] == "nginx-error" {
    grok {
      patterns_dir => ["/etc/logstash/conf.d/patterns"]
      match => { "message" => "%{NGINXERROR}" }
    }
  } 
}
`

**logstash pattern file:**
`
NGUSERNAME [a-zA-Z\.\@\-\+_%]+
NGUSER %{NGUSERNAME}
NGINXACCESS %{IPORHOST:clientip} %{NGUSER:ident} %{NGUSER:auth} \[%{HTTPDATE:timestamp}\] "%{WORD:verb} %{URIPATHPARAM:request} HTTP/%{NUMBER:httpversion}" %{NUMBER:response} (?:%{NUMBER:bytes}|-) (?:"(?:%{URI:referrer}|-)"|%{QS:referrer}) %{QS:agent}
NGINXERROR %{DATA} %{WORD:webserver} %{IPORHOST:myhost}\-%{WORD:class}\: (?<timestamp>%{YEAR}[./-]%{MONTHNUM}[./-]%{MONTHDAY}[- ]%{TIME}) \[%{LOGLEVEL:severity}\] %{POSINT:pid}#%{NUMBER}: %{GREEDYDATA:errormessage}(?:, client: (?<client>%{IP}|%{HOSTNAME}))(?:, server: %{IPORHOST:server})(?:, request: %{QS:request})?(?:, host: %{QS:host})?(?:, referrer: \"%{URI:referrer})
`
