### ISSUE TITLE
rake test:plugins on non-windows fails on logstash-input-eventlog 

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4167]
crashes trying to require the win32-eventlog gem:

```
rake aborted!
LoadError: Could not open library 'advapi32' : dlopen(advapi32, 5): image not found. Could not open library 'libadvapi32.dylib' : dlopen(libadvapi32.dylib, 5): image not found
```

This is because the windows specific gem has been moved from the `require` method to the file top. 

Not sure if we should add windows platform check or else... 

@jsvd @ph thoughts?

**Comment by colinsurprenant** [comment]
discovered while working on #4123

**Comment by suyograo** [comment]
we should skip this plugin install completely on default-plugins test because there is a separate job on Jenkins to validate this plugin behavior on Windows http://build-eu-00.elasticsearch.org/view/LS%20on%20Windows/job/Logstash_2.0_Eventlog_plugin_test_for_Windows/

**Comment by ph** [comment]
+1 for skipping them on linux since we already test them on windows.

**Comment by purbon** [comment]
+1 on skipping, we should just do that, easy to fix.

**Comment by colinsurprenant** [comment]
but then, the plugin will not be packaged by default? Windows users will have to manually install it after logstash install, is that what we want? 

also, if a non Windows user installs the plugin and try to use it (granted, this is a bit remote) it will crash in the same way, which is not very elegant.

**Comment by purbon** [comment]
why not using https://github.com/elastic/logstash/blob/master/rakelib/test.rake#L39 ? the EXCLUDE_PLUGIN env var that @gmoskovicz added?

**Comment by gmoskovicz** [comment]
The EXCLUDE_PLUGIN should work:

just export the list of plugins to exclude and we should be done.

**Comment by suyograo** [comment]
@gmoskovicz @purbon can one of you make this change in Jenkins?

**Comment by purbon** [comment]
yes

**Comment by colinsurprenant** [comment]
where would this `EXCLUDE_PLUGIN` env var specified? it would have to be present before launching `rake test:plugins`?

**Comment by purbon** [comment]
yes

**Comment by colinsurprenant** [comment]
so this is not very useful. I have to manually add this every time I want to run tests....

**Comment by purbon** [comment]
what about having this var (https://github.com/elastic/logstash/blob/master/rakelib/test.rake#L39) actually read from a file too, then you can define a local file that exclude plugins. makes sense?

**Comment by suyograo** [comment]
Can we add a platform check when returning defaults list so we filter?

**Comment by gmoskovicz** [comment]
Added, by the way, it's the right way to do this, tagging/using environment variables.

**Comment by purbon** [comment]
we can do that too, works probably better and cleaner. I like this idea.

**Comment by gmoskovicz** [comment]
My 2ç ;)

**Comment by colinsurprenant** [comment]
if we go in the direction of excluding a specific spec, I don't see why it couldn't be automatically excluded by checking platform?

**Comment by suyograo** [comment]
@purbon ah, platform check will not work because our packages are built from Jenkins which is running unix.

**Comment by purbon** [comment]
yes, platform works for me too. we can add some knowledge to the list than then we can filter out.

**Comment by colinsurprenant** [comment]
I don't agree on the principle that I should have to manually set an ENV var to exclude specific tests depending on my platform, it should either be done automatically OR we could have different tasks for different platform or something like that. the dev-test cycle need to be simple.

**Comment by purbon** [comment]
@suyograo will work because we can filter or just don't filter. will filter only for the test. is a good idea to make it automatic as @colinsurprenant proposes.

**Comment by colinsurprenant** [comment]
and it also have to be simple to setup for automatic testings, in which case an ENV setup can make sense since it's a one-off config editing.

**Comment by suyograo** [comment]
yes, makes sense to add a platform check while running tests

**Comment by purbon** [comment]
yes, will implement this. thanks guys. +1

**Comment by colinsurprenant** [comment]
maybe instead of maintaining a list of platform specific plugin, we could simply globally wrap the spec file with a 
```ruby
if LogStash::Environment.windows?
  ... 
end
```

this if would have to wrap the top `require` statements to avoid loading the actual plugin code.

this way the condition is in the test and we don't have to maintain a separate list. 

seems simple.

**Comment by colinsurprenant** [comment]
@purbon what do you think? ^^

**Comment by purbon** [comment]
Hi,
  this is a nice idea, the only situation I see is how is the expected
outcome if the validation is not meet?

* If we make the test pass, because then don't need to change anything in
core, a user might thing this is a bug as actually can run the test in
unix, but they pass.
* Test should fail if executed in a non valid OS.

I think we can add this, make the test complain as you run a windows
dependant test in a unix machine, and then wrap up in core somehow the
exception.

makes sense?

**Comment by colinsurprenant** [comment]
I agree, I would prefer to have an indication that this test has been skipped because of platform incompatibility. practically, the top `require 'logstash/inputs/eventlog'` has to be prevented from being evaluated. would it be possible to move this `require` inside a rspec condition/exclusion that checks for platform?

**Comment by gmoskovicz** [comment]
Make sense for me!

On Wed, Nov 11, 2015 at 12:41 PM, Colin Surprenant <notifications@github.com
> wrote:

> I agree, I would prefer to have an indication that this test has been
> skipped because of platform incompatibility. practically, the top require
> 'logstash/inputs/eventlog' has to be prevented from being evaluated.
> would it be possible to move this require inside a rspec
> condition/exclusion that checks for platform?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/4167#issuecomment-155820735>.
>



-- 

--
Gabriel Moskovicz | Support Engineer | +598 95-051-777
Uruguay

**Comment by colinsurprenant** [comment]
so it ends up we [already had provisions for platform exclusion using tags](https://github.com/elastic/logstash-devutils/blob/15c59bfaab592f22531d333a25e4dcac39256f18/lib/logstash/devutils/rspec/spec_helper.rb#L56-L60) which is perfect but the problem is that the `require` statement which tries to load windows specific stuff and crashed on non-windows platform happens **before** the tag exclusion. 

I pushed PR logstash-plugins/logstash-input-eventlog#26 to solve this by pushing that require down after the rspec tags exclusion. 

Let me know what you think.

**Comment by colinsurprenant** [comment]
@purbon let me know what you think of ^^

**Comment by purbon** [comment]
@colinsurprenant will add comments to the pr itself, but generally the idea is ok, except I would add some messaging to the user gets feedback why test are ignored.

**Comment by colinsurprenant** [comment]
this messaging should probably happen here https://github.com/elastic/logstash-devutils/blob/15c59bfaab592f22531d333a25e4dcac39256f18/lib/logstash/devutils/rspec/spec_helper.rb#L56-L60

**Comment by purbon** [comment]
not sure if the right place, that place is a configuration block. anyway, let's not block this for messaging, I would open an issue and lets it live here until we can work on it.

**Comment by colinsurprenant** [comment]
perfect.
