### ISSUE TITLE
LSF -> Filebeat doc items

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#4168]
- [x] Logstash docs - [s/logstash forwarder/filebeat](https://github.com/elastic/logstash/search?utf8=%E2%9C%93&q=logstash-forwarder) (Paul)
- [x] Remove LSF from [public roadmap](https://www.elastic.co/guide/en/logstash-roadmap/current/index.html#_status_ongoing) - https://github.com/elastic/logstash-docs/pull/137 (Alvin)
- [x] LSF Github [README](https://github.com/elastic/logstash-forwarder) note (Jordan)
- [ ] LSF [blog](https://www.elastic.co/blog/logstash-forwarder-0-4-0-released) note (Jordan)
- [x] Close issues and PRs in LSF repo that are marked "closing-suggested" (Jordan, PH)

**Comment by jordansissel** [comment]
PR for updating the LSF readme: https://github.com/elastic/logstash-forwarder/pull/545

**Comment by palecur** [comment]
PR #4223 is up to address the docs part of this.

**Comment by palecur** [comment]
Alvin, can we close this? I think it's all done.
