### ISSUE TITLE
Including local jar files

### ISSUE THREAD

**Issue by Israaaaa** [elastic/logstash#4171]
I'm trying to build and use a gem that is dependent on jar files. I do not wanna publish the jar files, I need them locally only.

in my .gemspec file, I have the following

          # Jar dependencies
          s.requirements << "jar 'org.elasticsearch:elasticsearch', '1.4.0'"
          s.add_runtime_dependency 'jar-dependencies'
How can I include my local jar files? Because not including them gives me the following error, when trying to use the filter in a config file:

          The error reported is: Couldn't find any filter plugin named 'mygem'. 
          Are you sure this i s correct? Trying to load the mygem filter 
          plugin resulted in this e rror: no such file to load -- thejarfilename

Is this an issue with Logstash? Or should I just include the jar files in a specific way in the gemspec file?

**Comment by ph** [comment]
> I do not wanna publish the jar files
I understand this by, You don't to put them on maven or on rubygems, Correct?

What you can do is manually adding a jar inside the gem and require it?
Similar to this project https://github.com/iconara/jar-gems/tree/master/netty-jars is doing.

Also why are you requiring elasticsearch jars? We have a gem that already include them named `logstash-output-elasticsearch_java`

**Comment by Israaaaa** [comment]
Should this:
`s.files = Dir['*.jar','lib/**/*','spec/**/*','vendor/**/*','*.gemspec','*.md','Gemfile','LICENSE']`
also include the jar files as well?
Because I already tried adding that (or something similar), and it gave me the same error. Please note that despite it saying '*.jar' I'd already moved the jar file to the same directory as the gemspec file, just for testing.

**Comment by ph** [comment]
@Israaaaa You have to puts the jars in `lib`, because that directory will be added to the ruby `$LOAD_PATH`, if the jar isn't in that directory the require wont work.

**Comment by Israaaaa** [comment]
I seeeee... okaaay.. it's working now. So this was all my fault. I thought something was up with logstash.. the verys first thing I tried to do was include the jar files in the `lib/logstash/filter/` directory, when they should be in the `lib/` directory. I thought it would make no different, especially that I'd included that
`s.files = Dir['*.jar','lib/**/*','spec/**/*','vendor/**/*','*.gemspec','*.md','Gemfile','LICENSE']`
to my gemspec file. Apparently, it did. Thank you, @ph really appreciate your help.

**Comment by ph** [comment]
@Israaaaa you are welcome, glad it work now. :)

**Comment by ph** [comment]
`s.files` its only to tell the gem builder what files it need to include in the build and there is no relation with that concept and the `$LOAD_PATH`
