### ISSUE TITLE
Unable to Grok the 'file' field.

### ISSUE THREAD

**Issue by incogniro** [elastic/logstash#4181]
When using Logstash-Forwarder to forward to Logstash, I would like to extract a number of values from the 'file' field (file names in the form 'this-is-a-sample.log') so I may name Elasticsearch indexes based upon the extracted values. However Logstash fails no matter how simple the GROK pattern and reports strange error messages (see sample below) as well as sometimes the _grokparsefailure message. When I revert to using the file input plugin (and changing the field to 'path') all processing occurs as expected.

==> logstash.log <==
{:timestamp=>"2015-11-04T12:12:18.324000+0000", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Lumberjack input", :exception=>LogStash::SizedQueueTimeout::TimeoutError, :level=>:warn}
{:timestamp=>"2015-11-04T12:12:18.335000+0000", :message=>"Lumberjack input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::CircuitBreaker::HalfOpenBreaker, :level=>:warn}

This is also reported at https://discuss.elastic.co/t/impossible-to-grok-on-file-field-causes-logstash-to-fail/33740.

**Comment by jsvd** [comment]
interesting..the following config makes logstash halt totally in 2.1.1:

```
input { generator { count => 1 message => "/tmp/a/aaaaaaaaaaaaaaaaaaaaaaaaaaaa.log" } }
filter {
  grok {
    match => [ 'message', "%{UNIXPATH}/a.log" ]
  }
}
output {
  stdout { codec => rubydebug }
}
```
