### ISSUE TITLE
Obfuscate the password in logstash  config files

### ISSUE THREAD

**Issue by ESamir** [elastic/logstash#4183]
Some companies have requirement to obfuscate all the passwords in the configuration files

**Comment by jordansissel** [comment]
I'm not sure I understand the request here. Obfuscation doesn't add any security.

**Comment by jordansissel** [comment]
> Obfuscation doesn't add any security

I'll rephrase, since what I said was blunt and inaccurate :)

What is the threat model being defended against for this request? Additionally, is there any propose implementation of this obfuscation?

**Comment by markwalkom** [comment]
Given people are storing database/API/user account details in config files they want to know that they cannot be read and used maliciously by others.

Being able to store encrypted or otherwise passwords in files reduces the possibility that this can happen.

**Comment by jordansissel** [comment]
@markwalkom Alright, that helps.

So we're talking less about obfuscation and more about encryption. Do we have an idea of what cipher(s) are desired and also how a user would provide the decryption key?

**Comment by jordansissel** [comment]
For some prior art, I've run Apache HTTPD in production before with SSL that had a passphrase on the key, and on start, httpd would prompt me (on the terminal, during startup) for the passphrase to decrypt the private key. 

Is that something that would be OK here?

**Comment by markwalkom** [comment]
That sounds reasonable, but there would need to be a way to automate this, perhaps by access a heavily restricted key file on disk (think 0400 perms)?

**Comment by jordansissel** [comment]
@markwalkom Why not just chmod 0400 the logstash config in the first place?

**Comment by markwalkom** [comment]
I don't disagree, but some users would like another layer.

**Comment by jordansissel** [comment]
Right right, but what I mean is that if you have 2 files in the same directory, 1 is readable but has encrypted values and the other is not-world-readable but is plain text, we haven't really fixed the problem of unsecured credentials.

As soon as we write _any_ decryption key to disk, we're in the same boat (basically) as Logstash having plain-text credentials in a file on disk.

**Comment by jordansissel** [comment]
Protecting secrets is now being discused in https://github.com/elastic/logstash/issues/6892
