### ISSUE TITLE
Coordinating Support on Multiple Logstash Instances

### ISSUE THREAD

**Issue by jeromefroe** [elastic/logstash#4187]
I have recently been looking into setting up an elasticsearch cluster, and I need to regularly index data from a database, which I can do using the jdbc input plugin. My problem is that there does not seem to be a way to coordinate this action across multiple logstash instances. If, for example, I run the action on only one instance, and that instance goes down, the data will not be ingested into elasticsearch. On the other hand, if I run the action on multiple instances, I will be protected from the failure of any one instance, but I will have duplicate data in elasticsearch. Is there any plan to support a feature like this in the future?

**Comment by markwalkom** [comment]
There are plans to have Logstash cluster multiple instances to allow this sort of thing. I don't know if we have a timeline for it yet though :)


Also please join us at https://discuss.elastic.co/ or at #elasticsearch on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)

**Comment by suyograo** [comment]
Closing in favor of https://github.com/elastic/logstash/issues/2632

**Comment by MarkusMayer** [comment]
@jeromefroe you could think about emulating some kind of at least once semantic by defining a custom document_id in elesticsearch derived from some sort of key columns in your db tables. if you import a row for the first time it will be inserted into es, if its already there it basically becomes an update of the old document. this works quite well for our use-case.

**Comment by jeromefroe** [comment]
@MarkusMayer that's a great suggestion. Thanks! The only drawback I can see to that approach is that it I will be querying the database multiple times, which might not be ideal with a production server.

My apologies for posting this to the wrong forum as well :)
