### ISSUE TITLE
core Event class Java rewrite

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4191]
### Overview

Rewrite the `Event` class in pure Java and its supporting classes like `Timestamp` and `Accessors` and keep 100% compatibility with current implementation of other core logstash components and all plugins. 

### Purpose

`Event`is the main object which encapsulates data and provides and API for the plugins to perform processing on the event content. Having `Event` implemented in pure Java will improve performance, make possible **faster serialization** by avoiding costly type conversion between JRuby and Java which in turn will help with an **efficient persistence** implementation.

Also, these critical and costly operations are related to the `Event` where the Java implementation should provide performance improvement:
- **fields reference getters and setters**: All `Event` data manipulation in the config is done using the logstash field reference syntax (ex. `[foo][bar][baz]`). This is implemented in the `Accessors` class. an optimized implementation should improve performance.
- **string interpolation**: (`Event#sprintf()`) The config syntax provides string interpolation in field references. The Ruby implementation was known to be slow and the Java implementation should provides a noticeable improvement. String interpolation is heavily used in all configs.

### Strategy

- [x] Extract the current `Event` implementation from logstash-core and make it a proper self-contained gem which should be drop-in replaceable with an alternate implementation. This is completed in #4123 and the gem is `logstash-core-event`.
- [x] Create the Java implementation gem logstash-core-event-java. This is in progress in #4123. 
- [x] provide benchmarks
- [x] have all core specs pass
- [x] have all core plugins spec pass
- [x] have all default plugins spec pass

**Comment by colinsurprenant** [comment]
All default plugins are now passing specs, all related PRs are tracked in #4264. Merge fest can now start.

**Comment by colinsurprenant** [comment]
quick benchmark update, I tested the config defined in https://gist.github.com/colinsurprenant/8143a0dfd30830d57b03 using 4 workers `-w 4` and default batch size of 125 (not specifying `-b`) on master pre-g-pipeline, ng-pipeline and ng-pipeline+java-event:

TPS|pipeline
--- | --- 
4.86k|pre ng-pipeline
6.29k|ng-pipeline
7.50k|ng-pipeline+java-event

**Comment by untergeek** [comment]
That's an impressive increase!

**Comment by acchen97** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2JA4c1bD&#x2F;1-java-event"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Java Event</a>

**Comment by colinsurprenant** [comment]
I am calling this issue closed, Java Event is merged and all core and plugins specs are passing. I will followup with a post-merge review process issue and we can create new issues as needed.
