### ISSUE TITLE
Add -XX:+HeapDumpOnOutOfMemoryError and related Java options to Logstash 2.0

### ISSUE THREAD

**Issue by joshuar** [elastic/logstash#4192]
It looks like the Logstash bin script (at least on Linux) does not add the `-XX:+HeapDumpOnOutOfMemoryError` Java option on start-up.  It would be good to add this (and `-XX:HeapDumpPath=...`) for the rare occasion where LS OOM's so we might be able to dig into the heap dump for post-mortem.

**Comment by yodog** [comment]
how do i disable this?
it's taking too much space on disk, and i'm tired of deleting the file manually.
