### ISSUE TITLE
Library for Logstash

### ISSUE THREAD

**Issue by nipunarora** [elastic/logstash#4193]
Is there a matching library for logstash which can be used independently, without using logstash. 
For instance is there a grok library? 
Also what are the advantages of logstash over grok apart from the input/output encoders etc. 
I would like to parallelize the matching for a large number of patterns (200-1000+)

**Comment by chenryn** [comment]
There is <https://github.com/jordansissel/grok>. for example I use it in rsyslog: <https://github.com/SinaMSRE/rsyslog-mmgrok>

**Comment by nipunarora** [comment]
Thanks for the link @jordansissel is this library kept up-to date with the existing logstash version?

**Comment by nipunarora** [comment]
@chenryn I looked into your rsyslog-mmgrok. Most of the readme is in Chinese, so I can't get what you are trying to achieve. Could you explain?

**Comment by suyograo** [comment]
@nipunarora take a look at https://github.com/elastic/elasticsearch/issues/14049
