### ISSUE TITLE
Edit link 404s for maintainers guide

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#4202]
eg [here](https://www.elastic.co/guide/en/logstash/current/community-maintainer.html) if you click `edit` it returns a 404, but other pages I checked also did this.

I couldn't find where the link should go to as I'm at Puppet Camp and don't really have time to dig, sorry :(

**Comment by palecur** [comment]
That link goes to master, and the changeset that included that file was never pushed to master, just 2.1. I'll cherry-pick it in.
