### ISSUE TITLE
Logstash custom filter is not taking the field for processing, and takes the filed name as the string instead

### ISSUE THREAD

**Issue by Israaaaa** [elastic/logstash#4213]
I tried to post this on discuss.elastic but I'm not receiving any answers...

The following is my filter .rb file

                      # encoding: utf-8

                      require "logstash/filters/base"
                      require "logstash/namespace"
                      require 'java'
                      require 'myProject.jar'

                      $CLASSPATH << 'lib'

                      class LogStash::Filters::Analyze < LogStash::Filters::Base

                        config_name "analyze"
                        config :text, :validate => :string

                        public
                        def register
                          @result = JavaUtilities.get_proxy_class('MyClass.myMethod')
                          @result_ = @result.new()
                          @final_result = @result _.myMethod(@text)
                        end

                        public
                        def filter(event)
                            event["text_being_proccessed"] = @text
                          filter_matched(event)
                        end

                      end

And the following is my configuration filter:

                      analyze {
                         text => %{text}  #note that the field I wanna analyze is also called text
                      }

However, the result is text and not the value of text. WHy is that??? HELP PLEASE

(Please note that there is nothing wrong with my ruby code and calling the jar file and using the methods and classes in it, as its all been tested before trying to use it as a filter for Logstash)

Thanks.

**Comment by ph** [comment]
The `%{text}` is our fieldref syntax (or templating syntax) if you want to use that syntax in the options of the plugin you have to pass that value to `event#sprintf` method.

Like this:

```ruby
# if @test == "%{text}" sprinft will return the value of "text" field
value = event.sprintf(@text)
 event["text_being_proccessed"] = value
```

**Comment by Israaaaa** [comment]
Ok I see. Is there a clear documentation you could recommend for me to read before actually developing my filters? I read this one

          https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html#_literal_require_literal_statements_3

 but it doesn't include much details, especially for ruby beginners..

**Comment by ph** [comment]
@Israaaaa I don't think we have specific information about all the internals of the event class, best strategy is to look at the content of the class itself or other plugins that implement a similar behavior.

**Comment by Israaaaa** [comment]
Okay. Thank you for your help :)
