### ISSUE TITLE
jps listing for logstash 1.5.3 does not show logstash name

### ISSUE THREAD

**Issue by mnikhil-git** [elastic/logstash#4224]
jps listing for java processes on a system running logstash shows the logstash process as 'Main' in 1.5.3 It was not certainly the case with older logstash versions.

'Main' is perhaps the jruby shell class. I think it would be appropriate to have logstash process register its name as logstash and be able to get listed and found accordinly when 'jps' command is run.

thanks

**Comment by kares** [comment]
`jps`
```
498375 Elasticsearch
953992 Logstash
1018299 RemoteMavenServer36
```
