### ISSUE TITLE
Logstash not closing connections correctly

### ISSUE THREAD

**Issue by GarryWalsh** [elastic/logstash#4225]
Hi,

I have 60ish servers connected to my Logstash instance. They are connecting using lumberjack protocol via Logstash-forwarder (java version - https://github.com/didfet/logstash-forwarder-java)

I am encountering an issue consistently where Logstash will reject / drop a connection for some unknown reason before it retrieves the data that was sent by the server. I believe this is resulting in data loss.

Using netstat -p  to show all active LSF connections to Logstash shows that the connection that was dropped has no PID attached but has data in it's RECV_Q. This is evidence that Logstash is dropping the connection after it was established as otherwise LSF would not have send data to Logstash.

As Logstash is not closing the connections properly they are being left in CLOSE_WAIT or SYN_RECV with no PID attached (Logstash has abandoned them). On the client side LSF thinks that it has an ESTABLISHED connection to logstash still as Logstash did not execute the correct shut down procedure and send the appropriate acks and continues to open new connections and send data. This results in maybe 5 or more CLOSE_WAIT connections per client with no PID attached and full RECV_Qs on the Logstash server.

An unfortunate side effect of this problem of this is that once a problem occurs with one server the effect snowballs and eventually all 60 servers will end up in this state with muliple CLOSE_WAIT or SYN_RECV connections with data piled up in their RECV_Qs and no way to recover the data.

Logstash is not recovering from the issue itself.

This problem occurs on both Logstash 1.5.4 and 2.0

**Comment by dfaropennetwork** [comment]
+1

**Comment by purbon** [comment]
Might be related to https://github.com/logstash-plugins/logstash-input-tcp/issues/16 ?

@GarryWalsh thanks for your report, I wonder if we can narrow down a way to reproduce this? can you share your configuration? operating system ?  are you using SSL? I wonder if this happen also with the new filebeat? have you tested that?

**Comment by GarryWalsh** [comment]
@Purbon I don't believe it is related to that issue.

Versions:
Logstash 2.0
Elasticsearch 2.0
Kibana 4.2
Logstash-forwarder java (https://github.com/didfet/logstash-forwarder-java)

Logstash setup:
port 5000 used to receive from all LSF clients (~60)
40 workers
1g heap

input = lumberjack on port 5000. Using SSL.
filters = basic grok and timestamp
output = file out with minimal filters + elasticsearch

Logstash server distro:
Red Hat Enterprise Linux Server release 6.7


I have not tested filebeat.

LSF client OS are MAC, AIX, Ubuntu, SUSE, Redhat, Windows server. There does not seem to be more problems on any particular OS. Logstash is unbiased about the client OS when it is abandoning connections.

We are using the java dist of LSF for consistency across all our operating systems

We plan on rolling out an updated config file to the LSF clients soon to increase the timeout significantly from the default 15 seconds. 

We don't run LSF with any spoolsize restrictions


I have been dealing with this problem for a number of weeks now and as of yet I have not been able to reproduce the error on demand. There is no discernible difference between times when logstash is running perfectly and when it crashes with this issue.

How I am dealing with this right now is not a long term solution due to the potential for data loss. I have a python script that will continuously monitor the logstash connections and simply restart logstash if logstash is beyond the point of self recovery. The hope is that it will minimize data loss by catching the problem as soon as it occurs. It also means I do not have to manually spam restart on logstash when the error occurs to get it operational again.

**Comment by purbon** [comment]
@GarryWalsh thanks a lot for your extense report, for now my got feeling is something fishy going on with ssl implementation, but as you said trying to reproduce this is had and non deterministic errors are the worst. Will try to setup an strategy to reproduce this and report, would be awesome to make this at less deterministic so we can track this down.

**Comment by GarryWalsh** [comment]
@purbon I have continued testing this since we spoke and tried to narrow down the problem. I have made some progress:

Changes I made:
Increased timeout on LSF from default 15 seconds to 60 seconds.
Added spool size option to all LSF instances. Spool size set to 100

Results:
1) Connections entering close wait / syn recv and crashing... fixed (so far)
This appears to be completely fixed now with the addition of spoolize. My guess is that the pipeline was getting flooded and started killing off connections.

2) Duplicate connections.... still a problem
This is still occurring. I had hoped the increased timeout would help with this but that is not so.
Today I saw one my servers with 5 established connections to logstash. They all were attached to the logstash process so none orphaned. I checked the server in question and there is only one LSF instance running.
Logstash should be cleaning up excess connections I don't understand why it is not.

**Comment by zyphlar** [comment]
I have a similar problem, not sure what the solution is but the "dead connections" rabbit hole seemed like the most promising one to investigate. https://github.com/elastic/logstash/issues/4815#issuecomment-234739206

**Comment by Rotwang** [comment]
I can see this happening with logstash 2.4.1 and beats input.

**Comment by ph** [comment]
I've will close this issue, with the change to logstash 2.4 and Logstash 5.0 the beats input is now correctly closing the connection and also communicate back pressure to the filebeat client. 

Related PRs:
- https://github.com/logstash-plugins/logstash-input-beats/pull/191
- https://github.com/logstash-plugins/logstash-input-beats/pull/169

**Comment by pputerla** [comment]
logstash 5.4, *http* input -> every closed http session results in CLOSE_WAIT...

**Comment by PhaedrusTheGreek** [comment]
In at least one case, this issue was resolved with an upgrade to Logstash 5.x

**Comment by BrianMBeaulieu** [comment]
I think this issue is back in 5.x.  I continue to increase the file descriptor limit. I'm up to 16k and it's just growing and growing and growing until it dies.

After logstash has been running for a few minutes, the # of open files keeps increasing and they are all tied to CLOSE_WAIT sockets.

Logstash has a bare minimum configuration.  Processing 

[root@es-broker logstash]# netstat -an | grep -c CLOSE_WAIT
1528

[root@es-broker logstash]# while [ -z $FOO ]; do lsof -p 2098 | wc -l;sleep 1;done
320
320
321
321
320
320
320
319
319
318
318
318
318
318
318
317
316
316
316
316
316
316
316
315
314
315
316
316
317
317
317
316
316
317
317
317
316
318
318
318
318
318
317
317
317
317
317
318
318
318
318
318
317
317
317
318
320
336
343
348
352
362
365
368
370
375
378
378
383
386
388
390
392
393
399
401
404
407
411
416
416
418
418
422
426
428
433
449
459
467
472
481
486
494
497
504
507
510
514
519
521
523
524
526
533
535
537
542
546
551
551
553
553
558
563
564
569
573
575
590
599
607
612
623
629
636
638
647
650
651
654
659
661
663
667
669
676
679
683
686
689
694
694
697
698
702
706
707

**Comment by BrianMBeaulieu** [comment]
I've adjusted net.ipv4.tcp_keepalive_time to 120s and that seem to keep the CLOSE_WAITs under control.  We'll see how it goes.

**Comment by daplho** [comment]
@BrianMBeaulieu how did that go?
