### ISSUE TITLE
1.5.x (core-api-v1) plugins gemspec broken

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4231]
Hi,
  while backporting https://github.com/logstash-plugins/logstash-output-file/pull/21 to the 1.5.x branch I found the gemspec to be broken:

* The logstash-core requirement ``` s.add_runtime_dependency "logstash-core", '>= 1.4.0', '< 2.0.0'` ``` is broken as it fetch the 2.0.0 pre releases that are basically incompatible with the 1.5 branch. This should be changed to ``` s.add_runtime_dependency "logstash-core", '~> 1.4' ``` that will fetch the last 1.x available dependency.

* The fix for concurrent-ruby was not backported to 1.5, here we either have two options, or force the version in the gemspecs as of ```s.add_runtime_dependency 'concurrent-ruby', '0.9.1'``` or backport the fix.

The last two changes might require a mass update of the plugins, or that we have this into account when updating a plugin.

See https://github.com/logstash-plugins/logstash-output-file/pull/22 for a backport example.

Related to #4188

**Comment by purbon** [comment]
@jordansissel @suyograo what do you think about it?

**Comment by colinsurprenant** [comment]
@purbon can you please elaborate on the exact context and problem you are experiencing. these are basically the different scenarios we need to assess:
- developement environment, using published logstash-core with local `bundle install` + `bundle exec rspec`
- development environment, using local logstash-core with local `bundle install` + `bundle exec rspec`
- development environment, running plugin from source from local logstash
- installing plugin from rubygem or using a local .gem file into a local logstash

**Comment by colinsurprenant** [comment]
for `concurrent-ruby` I think we should apply the same fix in the 1.5 branch, i.e. hard wiring version to 0.9.2 on the logstash-core gemspec. @ph thoughts?

**Comment by ph** [comment]
@purbon @colinsurprenant +1 removing the silence + fix version to 0.9.2.

**Comment by ph** [comment]
I just need to apply https://github.com/elastic/logstash/pull/4146 to the 1.5 branch, the gemspec already define 0.9.2 as the dependency.

**Comment by purbon** [comment]
@colinsurprenant @ph most important things, a part from the concurrent-ruby issue, is the requirement in the gemspec. Nowadays if anyone does a fix for 1.x branch in the plugin, the logstash-core fetch the last 2.0 prerelease.

**Comment by purbon** [comment]
this makes the development in plugins impossible, you need to pin for a 1.5.x version. see @wiibaa issue, he just hit the same two problems.

**Comment by colinsurprenant** [comment]
what we decide in #4236 will solve this.
