### ISSUE TITLE
logstash cluster scalability problem or lsf software issue?

### ISSUE THREAD

**Issue by maxhyjal** [elastic/logstash#4237]
Once my lsf hosts reaches a certain number, this keeps happening, even after I upgraded Elasticsearch and Logstash both to 2.0 and tweaked logstash configurations:

message=>"Lumberjack input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2015-11-19T21:49:50.388000+0000", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Lumberjack input", :exception=>LogStash::SizedQueueTimeout::TimeoutError, :level=>:warn}
{:timestamp=>"2015-11-19T21:49:50.388000+0000", :message=>"Lumberjack input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2015-11-19T21:49:50.718000+0000", :message=>"Lumberjack input: the pipeline is blocked, temporary refusing new connection.", :level=>:warn}

Is my only option to scale out my Logstash cluster???

**Comment by markwalkom** [comment]
This could be due to a few things.

However please join us at https://discuss.elastic.co/ or at #logstash on Freenode for troubleshooting help or general questions. 
We reserve Github for confirmed bugs and feature requests :)
