### ISSUE TITLE
 pattern not defined

### ISSUE THREAD

**Issue by simpleuser99** [elastic/logstash#4239]
Hello!
I used logstash 1.5.0, elasticsearch 1.4.4 and grok
When I update to logstash 2.0.0 and elasticsearch 2.0.0 I have a issue.

> {:timestamp=>"2015-11-20T12:23:57.757000+0300", :message=>"The error reported is: \n  pattern %{HOST:Alert.Sensor.Node.Name} not defined"}

How can I resolve it?

**Comment by simpleuser99** [comment]
I replace grok pattern file in pattern dir from old version, and it work. But i have the next problem:
>{:timestamp=>"2015-11-20T12:52:13.048000+0300", :message=>"Failed parsing date from field", :field=>"Alert.ReceiveTime", :value=>"2015-11-20T09:52:12.885Z", :exception=>"cannot convert instance of class org.jruby.RubyObject to class java.lang.String", :config_parsers=>"ISO8601", :config_locale=>"default=en_US", :level=>:warn}
 this message from logstash.log and i have the same messages that I:
>/opt/logstash/bin/logstash -f /etc/logstash/conf.d/20-ossec.conf
Default settings used: Filter workers: 1
UDP listener died {:exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:67:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:50:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:180:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:174:in `start_input'"], :level=>:warn}

How can fix it?

**Comment by jsvd** [comment]
can you show the configuration file? were you able to narrow down the problem to a couple of plugins?

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
