### ISSUE TITLE
List of logstash grok patterns for v2.0

### ISSUE THREAD

**Issue by koyadume** [elastic/logstash#4240]
I am using logstash v2.0 but unable to find list of grok patterns. Here is the link for v1.4 but unable to find same for v2.0 -
https://github.com/elastic/logstash/blob/v1.4.0/patterns/grok-patterns

**Comment by wiibaa** [comment]
You are looking for https://github.com/logstash-plugins/logstash-patterns-core/tree/v2.0.2/patterns
but I have to admit that it may be difficult to know the correct version number to look for without calling the `bin/plugin list --verbose` command

**Comment by wiibaa** [comment]
Also fyi, the link is given in the grok filter plugin documentation in https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html

**Comment by purbon** [comment]
closing this issue as is not really an issue and already got perfectly answered by @wiibaa, thanks man. feel free to reopen if there are other issues.

**Comment by koyadume** [comment]
Thank you @wiibaa.
