### ISSUE TITLE
main Gemfile logstash-core version constrains

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4244]
Related to #4243 and #4236.

Currently in the 2.0 tag and in the 2.1 release branch we pin `logstash-core` to a specific version, for example (= 2.0.0) and **not** a range (> 2.0.0, < 3.0.0) **nor** a pessimistic version (~> 2.0). 

See 
- [2.0 tag](https://github.com/elastic/logstash/blob/a566fab7d135886a33a1caadae9e548bee050179/Gemfile#L5) `gem "logstash-core", "2.0.0"`
- [2.1 branch](https://github.com/elastic/logstash/blob/2.1/Gemfile) `gem "logstash-core", "2.1.0.snapshot3"` 

The problem is see with this is that it will prevent upgrading logstash-core if we need to, either specifically or but updating/installing a plugin which could depend on a newer version of logstash core. 

I think that for released packages we should use the pessimistic versions constrain, for example in 2.0 we could use `~> 2.0`. This will allow installing future updated logstash-core versions and exclude prereleases which we typically don't want in a released package.

Thoughts?

**Comment by ph** [comment]
Well, this could have solved the problem of concurrent-ruby, since we would have been able to release a core not link on a specific version.

**Comment by colinsurprenant** [comment]
it is too late for such a change for 2.1, let's followup for post 2.1 releases.

**Comment by ph** [comment]
Can we close this issue ? 
I think https://github.com/elastic/logstash/issues/4236 is enough to track the problem?

**Comment by colinsurprenant** [comment]
agree, let's focus on #4236
