### ISSUE TITLE
Add a custom host for s3 output plugin

### ISSUE THREAD

**Issue by jindov** [elastic/logstash#4256]
Dear logstash devs,

I setup a ceph storage system like this http://docs.ceph.com/ and now I want to output log to ceph by s3 api http://docs.ceph.com/docs/v0.80.5/radosgw/s3/ruby/ but default s3 of logstash just support s3 aws, please add a function to custom s3 host to use with ceph storage, example: s3.myceph.com

The output settings may like this:

output {
    s3ceph {
        access_key_id => "my-access-key"
        secret_access_key => "my-access-secret-key"
        bucket => "logstash-output"
        use_ssl => false
    }
}

Thank you,

**Comment by jrha** [comment]
:+1:

We would also benefit from this, my suggestion would be to introduce a new field for hostname and possibly make this mutually exclusive with the region field.

**Comment by markwalkom** [comment]
Can you please raise this against the S3 plugin repo - https://github.com/logstash-plugins/logstash-output-s3/issues

Cheers!

**Comment by jsvd** [comment]
this has been opened in https://github.com/logstash-plugins/logstash-output-s3/issues/65
