### ISSUE TITLE
sql_last_start isn't persisted when executing logstash as non-sevice

### ISSUE THREAD

**Issue by digitalpacman** [elastic/logstash#4258]
The only shutdown method implemented is "stop". You also need to implement "close". Sometimes "stop" isn't called and only "close" is.  If you run logstash from the command line to do an import of data into elasticsearch, and at a future date want to run it again, but using the sql_last_start (like a monthly/weekly/daily job or something) then it'll never invoke the "stop" method of the plugin.

You should add the YAML.dump() command to the "close" method. I think the "stop" method shouldn't ever be used for this purpose, as it's not reliable.

**Comment by purbon** [comment]
Is this related to https://github.com/logstash-plugins/logstash-input-jdbc ? can you please reopen this issue there? thanks a lot.

**Comment by digitalpacman** [comment]
Sure. It should be noted that the logstash ruby gem links to here as to how to contribute to this input filter.

**Comment by digitalpacman** [comment]
https://github.com/logstash-plugins/logstash-input-jdbc/issues/88

**Comment by purbon** [comment]
bad, this should be fixed. thanks @digitalpacman
