### ISSUE TITLE
logstash truncate stdout

### ISSUE THREAD

**Issue by simpleuser99** [elastic/logstash#4273]
Hello.
I forward log messages ( 10000 symbols) to logstash, but logstah truncated those messages. how can i resolve it?

**Comment by purbon** [comment]
Thanks for your report, can you share your config and a sample log line?
Which os and jvm are you running?

Looking forward to understand,

**Comment by simpleuser99** [comment]
I'm sorry. Logstash didn't truncated messages. I use another application which forward truncated data to logstash.

**Comment by purbon** [comment]
closing this issue as is a no issue
