### ISSUE TITLE
Error: Your application used more memory than the safety cap of 500M.

### ISSUE THREAD

**Issue by FlorinAndrei** [elastic/logstash#4275]
Ubuntu-14.04

logstash-2.0.0
Plugins fully updated yesterday using ./bin/plugin
Using these plugins in my config files: beats, grok, date, elasticsearch

elasticsearch-2.0.0 running on localhost

Sending logs to logstash from a dozen instances, with filebeat-1.0.0-rc2

```
{:timestamp=>"2015-11-25T17:38:46.421000+0000", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::SizedQueueTimeout::TimeoutError, :level=>:warn}
{:timestamp=>"2015-11-25T17:38:46.424000+0000", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
```

```
Error: Your application used more memory than the safety cap of 500M.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace
```

Memory usage on that instance (the drop before 10am is probably the logstash crash):

![memory usage](http://i.imgur.com/SffLWmC.png)

**Comment by FlorinAndrei** [comment]
I've raised the heap to 1024 MB and logstash keeps crashing about once per day. I had to put it under Monit so at least it gets respawned after each crash, but obviously this is not optimal.

**Comment by suyograo** [comment]
@FlorinAndrei Whats the size of your documents you are sending to ES? Also in 2.0 we've reduced the bulk size to 500. 

This smells like a memory leak issue, can you paste your entire config?

**Comment by FlorinAndrei** [comment]
I use filebeats to ship regular logs from syslog, nginx, couchdb, and node.js from about one dozen instances. Not sure what's the average size of a line in those logs - maybe a couple hundred characters? Is there a way to look up the average record size in ElasticSearch?

As to the frequency, the peak seems to be around 500 lines / second (based on a 30 second time bucket), but the daily average is more like 200 / second.

Looking at the process size, it definitely looks like a memory leak.

This is the logstash configuration:

```
root@logstash10-prod-uswest2-aws:~# cat /etc/logstash/conf.d/*
filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGBASE}" }
    }
  }
  if [type] == "nginx_access" {
    grok {
      match => { "message" => "%{COMMONAPACHELOG}" }
    }
  }
  if [type] == "couchdb" {
    grok {
      match => { "message" => "\[%{DATA:timestamp}\] \[%{DATA:loglevel}\] \[%{DATA:pid}\] %{IP:clientip} %{USER:ident} %{USER:auth} %{WORD:verb} %{NOTSPACE:path} %{NUMBER:response}" }
    }
    date {
      locale => en
      match => ["timestamp", "EEE, dd MMM yyyy HH:mm:ss z"]
    }
  }
  if [type] == "node-server" {
    grok {
      match => { "message" => "%{DATA:timestamp} GMT+0000 (UTC) %{WORD:method} %{UUID:reqid} %{DATA:remainder}" }
    }
    date {
      locale => en
      match => ["timestamp", "EEE MMM dd yyyy HH:mm:ss"]
    }
  }
}
input {
  beats {
    port => 5044
  }
}
output {
  elasticsearch {
    hosts => "localhost:9200"
    sniffing => true
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}
root@logstash10-prod-uswest2-aws:~# grep -v '^$\|^\s*\#' /etc/default/logstash 
KILL_ON_STOP_TIMEOUT=0
export LS_HEAP_SIZE="1024m"
```

**Comment by sumanthakannantha** [comment]
We are also facing similar issue
{:timestamp=>"2015-12-22T13:33:56.582000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :level=>:warn}
{:timestamp=>"2015-12-22T13:33:57.109000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :level=>:warn}
{:timestamp=>"2015-12-22T13:33:57.738000+0000", :message=>"CircuitBreaker::Close", :name=>"Beats input", :level=>:warn}

**Comment by suyograo** [comment]
@FlorinAndrei thanks for the config. I believe you are hitting https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/306

LS 2.1.1 will fix this issue. You could also upgrade only the ES output to 2.2.0 by 

`bin/plugin install --version 2.2.0 logstash-output-elasticsearch`

**Comment by sumanthakannantha** [comment]
Thanks Suyog Rao!

**Comment by sumanthakannantha** [comment]
@suyograo I followed previous recommedation on updrading LS to 2.1.1. 
                Current Vesrion [kibana-4.3.1, logstash-2.1.1-1, elasticsearch-2.1.1]
But I frequemtly see below error in logstash log.
                 {:timestamp=>"2015-12-26T10:35:40.015000+0000", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::CircuitBreaker::HalfOpenBreaker, :level=>:warn}

 I see this issue whenever logstash service is stopped for few minutes for maitenance activity. I also obseverd it takes long time to recover backlog(Usualy I do not see recent log entires for last 30 mins in kibana for long time).
Before I was using logstash-forwarder there with similar maitenance activity it was not causing any delay in processing. Do we require any special tuning for filebeat?

**Comment by harishbsrinivas** [comment]
+1 I am facing same issue as well. Stopped logstash to upgrade the box but once it got back  I see  a lot of lines like this 
{:timestamp=>"2016-05-11T00:48:34.575000+0530", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}

In addition to the circuit breaker line.

**Comment by kares** [comment]
closing as this is outdated ever since (at least) LS 6.x (switch to JRuby 9K)
