### ISSUE TITLE
Users updating plugins in 2.0.0 version, will hit the concurrent ruby issue

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4281]
Hi,
  if you're updating a plugin, by calling ```bin/plugin update``` you will encounter the concurrent-ruby error, see #4141 for details. This error has been fix in the last versions, so the recommended way to fix this is updating your logstash.

Related to https://github.com/logstash-plugins/logstash-input-tcp/issues/27 and #4141

**Comment by pbmsys** [comment]
@purbon i made a quick workaround.
Reinstalled logstash, uinstalled the logstash-codec-json and the logstash-input-tcp. then the plugin manager stays on the current version.

Not an optimal fix but it seems to be working for now.
Do you know when a new release of logstash will hit the repos?

**Comment by purbon** [comment]
New release is there, if you update logstash, you will not hit this issue.

/purbon

**Comment by suyograo** [comment]
Fixed in 2.1
