### ISSUE TITLE
new Event APIs to properly abstract internal implementation

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4293]
Some plugins assumes that `Event#to_hash` returns a in-place mutable `Hash` object that will directly update the Event content.

While true now, moving forward we cannot assume this behaviour. It is also a very bad design. We need simply provide new APIs to directly set fields in the event without having to go through the field reference parsing overhead and also a way to set or merge a new hash structure at the root of the event event. 

this will allow plugins like the KV filter to use these new APIs to optimize the data injection in the event as done now in logstash-plugins/logstash-filter-kv#21

doing this will require a major version bump because it will add new API so that plugins that will use this new API can use the proper versions constrains.

issue #4140 is caused by this. 
this relates to #4191 

Upon progress on this we need to followup on:
- [ ] kv filter
- [ ] json filter

**Comment by andrewvc** [comment]
+1 to this. IMHO it'd be great if `#to_hash` could yield an immutable view of the real data, but this isn't clojure so we'll just have to make due with asking plugins not to mutate stuff :)

**Comment by colinsurprenant** [comment]
without being formerly immutable, what the Java `Event` yields is a Rubyfied deep copy of the inner Java structure so in that sense, mutating that hash does not change the event.

**Comment by colinsurprenant** [comment]
I also suggest we introduce setters/getters for the following *standard* fields:
- message
- tags

For example, this will allow to get rid of these repeated antipatterns in the plugins:
```ruby
tag = "_jsonparsefailure"
event["tags"] ||= []
event["tags"] << tag unless event["tags"].include?(tag)
```

and just replace that with something arounf the lines of:
```ruby
event.add_tag("_jsonparsefailure")
```

**Comment by jordansissel** [comment]
@colinsurprenant LogStash::Event#tag does this.

**Comment by colinsurprenant** [comment]
@jordansissel  doh. right. memory #fail. :P

**Comment by colinsurprenant** [comment]
I am currently struggling with the need for some pluggins to merge the content of a hash into the `Event` root and this should be as efficient as possible. This cannot be done **now** without assuming that `Event#to_hash` will return a mutable hash object that will update the `Event`. 

A temporary solution I came up with in the kv filter is in logstash-plugins/logstash-filter-kv#21 but I am not super happy with this, performance-wise. The problem here is having to live with the current `Event` API, until we figure here a new API for this and release it in an upcoming major version release.

In the mean time, I just had the idea of maybe adding support for the empty `"[]"` field reference to actually target the root data of the `Event`. For example, this current pattern:
```ruby
event.to_hash.merge!(some_other_hash_data)
```
could be replaced with
```ruby
event["[]"] = event.to_hash.merge(some_other_hash_data)
```
this would avoid going through the hoops of the `inject_fields` solution in the kv filter as per above ^^ and preserve similar performance and **not** introduce a new API but add this new `"[]"` empty field support which could be done without having to do a major bump.

Thoughts?

**Comment by colinsurprenant** [comment]
Also realizing that we should expose complete timestamp coercion and related error handling as done in https://github.com/elastic/logstash/blob/c2ea4a7a6eedee46fb7d169773b150cc44c78713/logstash-core-event/lib/logstash/event.rb#L250-L266. I just stumbled across this pattern in the json filter.

**Comment by andrewvc** [comment]
@colinsurprenant what are your thoughts on adding an `Event#merge` method to do that work instead of having a special designation for the root.

**Comment by jordansissel** [comment]
@andrewvc Event has an `append` method that merges another event into it, at the root. Thoughts on reusing or extending that? I think only multiline filter uses it today, but I may be mistaken.

**Comment by andrewvc** [comment]
@jordansissel that could work, I assume it takes a hash? I think it'd be a good idea to rename it to `merge`. `append` is confusing nomenclature IMHO.

**Comment by jordansissel** [comment]
It takes an Event. The `append` name comes from the fact that mutliline filter is appending two events together, and that it's a non-destructive operation (two fields with the same name? Keeps both values for that field)

**Comment by andrewvc** [comment]
@jordansissel interesting. Well, in that case maybe we DO want a semantically different `merge` that acts exactly like ruby's `Hash#merge`. Thoughts?

**Comment by jordansissel** [comment]
I think there's room for both, to be honest. However, I'd always had this kind of feeling that `append` belongs only in multiline filter since I don't recall much else using `append`. As for `merge` - do we have a sense of how many filters really need this feature? I'd _love_ to not have it at all if we can since it allows our API to be a little smaller, but if we must have it, then we'll have it.

**Comment by colinsurprenant** [comment]
@andrewvc @jordansissel the goal is to add API methods for the plugins to correctly manipulate the underlying data by abstracting away the internal hash and moving away from mutable interactions with the Event#to_hash returned object.

The current `Event#append` and `Event#overwrite` takes an `Event` as argument. This is fine for some plugins and yes, `Event#append` is only used by multiline. We can have a separate discussion about these. 

To minimize the API I think just adding a simple `set_data` or `from_hash` method would be sufficient. merging-in hash content into the `Event` root would then be something like
```ruby
data = event.to_hash.merge(external_data)
event.from_hash(data)
```
or you could swap-in the `Event` data completely with
```ruby
event.from_hash(external_data)
```

but also adding an extra `Event#merge_hash` would allow better optimizations for the merge user-case:
```ruby
event.merge_hash(external_data)
```

Personally I'd vote for both `Event#from_hash` and `Event#merge_hash` (other method names are welcome) but these are only for the next major release. **This is why** I also proposed a stop-gap **non-API-breaking** modification of adding a special field reference, either `"[]"` or `:root` to use with the current `Event#[]=` as an equivalent to `Event#from_hash`

afaics, both kv and json filters would benefit `Event#merge_hash` but as I explained above, we can live with only a `Event#from_hash` and do the merge in 3 steps.

**Comment by colinsurprenant** [comment]
@jordansissel @jsvd @ph @andrewvc would like your feedback on previous comment, especially the stop-gap solution of using a *special* fieldref to Event set root data object. the other API changes are not urgent to move forward.

**Comment by ph** [comment]
@colinsurprenant If I understand correctly the `from_hash` method will do the following.

```ruby
# This is pseudo code.
event # Contains { :message => "Hello world" }
hash1 # Containts { :source => "the best file in the world" }
event.from_hash(hash1) # Contains { :message => "Hello world", :source => "the best file in the world" }  }
```
Correct? If this is the intent, I think we should name it `#update_from_hash`

**Comment by ph** [comment]
Concerning backward compatibility, adding `from_hash`, `merge_hash`  or making fieldref accept a `:root` of `[]` both way will require a new release of the core? If i am not mistaken.

In that case, I don't see a problem of adding the `update_from_hash`  and `merge_hash` method and changes the plugins to use them? If we want the plugins to be backward compatible we could do a `respond_to` on the event class to use the correct logic. This would allow the plugins to use the new feature and remain backward compatible?

**Comment by colinsurprenant** [comment]
@ph doh:exclamation:, you are totally right, both strategies will require new release of core and backward compatibility need to be dealt with in both cases so my stop-gap fieldref proposal is just completely ridiculous.

**Comment by colinsurprenant** [comment]
Closing this issue and creating #4326  that specifically deals with the `from_hash` and `merge_hash` proposal - @ph I clarified in that issue, can you please followup there? thanks.
