### ISSUE TITLE
"SocketError: recv: name or service not known" while plugin install via proxy

### ISSUE THREAD

**Issue by romale** [elastic/logstash#4295]
Start issue here https://github.com/logstash-plugins/logstash-filter-translate/issues/6
Logstash version 1.5.4
OS: openSUSE 13.1 (Bottle) (x86_64)
IPv4

**Comment by purbon** [comment]
@romale thanks a lot for your report, will investigate your issue.

**Comment by romale** [comment]
@purbon, i've resolve this issue.
I was no dns server in /etc/resolv.conf. After setting nameserver, the plugin installation is Ok. So, bin/plugin install ... worked with proxy setting in different way than curl, for example.

**Comment by purbon** [comment]
@romale oh, then thanks then! good you fixed it.
