### ISSUE TITLE
Failed to Connect 127.0.0.1 Cannot assign requested address

### ISSUE THREAD

**Issue by kpcool** [elastic/logstash#4299]
ElasticSearch 2.0 
LogStatsh 2.0
TopBeat 2.0
CentOS 7

Setup (Single Node):
TopBeats -> LogStash -> ElasticSearch.

Issuing a simple GET command on ES:
[root@stats elasticsearch]# curl -XGET http://127.0.0.1:9200
curl: (7) Failed to connect to 127.0.0.1: Cannot assign requested address

Running logstash for more than 2 days (heavy traffic more than 1M requests per day). At the end of the 2nd day, Logstash was holding too many connections in Established state (more than 58k based on netstat -apln Command), eg:

tcp6       0      0 127.0.0.1:35682        127.0.0.1:9200           ESTABLISHED 4836/java

Once I killed the 4836 (Logstash PID), ES connections resumed properly. It was logstash that caused the issue. It was holding up too many connections in Established state.

Following is the information about processes and environment.

408 - ElasticSearch PID
4836 - LogStash PID

[root@stats elasticsearch]# java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

[root@stats elasticsearch]# cat /proc/408/cmdline
/bin/java-Xms8g-Xmx8g-Djava.awt.headless=true-XX:+UseParNewGC-XX:+UseConcMarkSweepGC-XX:CMSInitiatingOccupancyFraction=75-XX:+UseCMSInitiatingOccupancyOnly-XX:+HeapDumpOnOutOfMemoryError-XX:+DisableExplicitGC-Dfile.encoding=UTF-8-Djna.nosys=true-Des.path.home=/usr/share/elasticsearch-cp/usr/share/elasticsearch/lib/elasticsearch-2.1.0.jar:/usr/share/elasticsearch/lib/*org.elasticsearch.bootstrap.Elasticsearchstart-Des.pidfile=/var/run/elasticsearch/elasticsearch.pid-Des.default.path.home=/usr/share/elasticsearch-Des.default.path.logs=/var/log/elasticsearch-Des.default.path.data=/var/lib/elasticsearch-Des.default.path.conf=/etc/elasticsearch

[root@stats elasticsearch]# cat /proc/408/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             63368                63368                processes
Max open files            65535                65535                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       63368                63368                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

[root@stats elasticsearch]# cat /proc/4836/cmdline
/usr/lib/jvm/jdk1.8.0_65/bin/java-XX:+UseParNewGC-XX:+UseConcMarkSweepGC-Djava.awt.headless=true-XX:CMSInitiatingOccupancyFraction=75-XX:+UseCMSInitiatingOccupancyOnly-XX:+HeapDumpOnOutOfMemoryError-XX:HeapDumpPath=/opt/logstash/heapdump.hprof-Djava.io.tmpdir=/var/lib/logstash-Xmx1g-Xss2048k-Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni-XX:+UseParNewGC-XX:+UseConcMarkSweepGC-Djava.awt.headless=true-XX:CMSInitiatingOccupancyFraction=75-XX:+UseCMSInitiatingOccupancyOnly-XX:+HeapDumpOnOutOfMemoryError-XX:HeapDumpPath=/opt/logstash/heapdump.hprof-Djava.io.tmpdir=/var/lib/logstash-Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar-classpath:-Djruby.home=/opt/logstash/vendor/jruby-Djruby.lib=/opt/logstash/vendor/jruby/lib-Djruby.script=jruby-Djruby.shell=/bin/shorg.jruby.Main--1.9/opt/logstash/lib/bootstrap/environment.rblogstash/runner.rbagent-f/etc/logstash/conf.d-l/var/log/logst

[root@stats elasticsearch]# cat /proc/4836/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             63368                63368                processes
Max open files            65536                65536                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       63368                63368                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

Please let me know how to resolve this issue. Else, I would have to restart logstash every certain interval to avoid this problem, which is a workaround and not a fix.

**Comment by McStork** [comment]
What is the output of your config file. I had something similar and found a solution. See this ticket:
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/320

**Comment by kpcool** [comment]
Logstash output:

output {
  elasticsearch {
    hosts => "127.0.0.1:9200"
    sniffing => true
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}

As you mentioned, sniffing was enabled. I have disabled sniffing and will see if that resolves the issue. I will update here after 3-4 days to confirm that system is stable or not.

Thanks

**Comment by kpcool** [comment]
Indeed, it was 'sniffing' set to true, causing the problem. Disabling it, got the connections to normal. 

Shouldn't this be reported as a bug though?

**Comment by jsvd** [comment]
the sniffing fd leak has been fixed by https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/306
