### ISSUE TITLE
1.5.5 ThreadDeath UncaughtExceptionHandler, root cause help?

### ISSUE THREAD

**Issue by bitsofinfo** [elastic/logstash#4301]
We just upgraded from 1.4.1 to 1.5.5.

Now we see these super-un-helpful errors in the error log every few minutes.

How can we get the root stack trace logged or possibly determine what is causing this???

Exception: java.lang.ThreadDeath thrown from the UncaughtExceptionHandler in thread "Thread-28"

Never got these errors previously prior to upgrade

Running logstash with --debug and/or --verbose produces a huge log file but without the error message. The file does not contain ThreadDeath or UncaughtExceptionHandler. 

The exception error message gets only printed to logstash.err without any further information.

**Comment by jsvd** [comment]
@bitsofinfo is this still happening for you? maybe getting a thread dump would allow us to know what the threads are doing, and then wait for another threaddeath to know which one died.

**Comment by bitsofinfo** [comment]
We gave up and just moved to the latest 2.x version in our testing. Still in the process of this so will post something if it comes up again in the 2x line.
