### ISSUE TITLE
Event#clone do not copy @metadata

### ISSUE THREAD

**Issue by wiibaa** [elastic/logstash#4306]
Question triggered by report in https://github.com/logstash-plugins/logstash-filter-clone/issues/5

What is the expected behaviour of the _#clone_ method regarding @metadata ?
User expectaction is that an exact copy is done data + metadata, but it is not currently the case.

@colinsurprenant as you are in an heavy review of the event class, could you please comment on this ?

**Comment by purbon** [comment]
There is also another collateral effect related to that, as you can see from https://github.com/logstash-plugins/logstash-filter-multiline/blob/master/lib/logstash/filters/multiline.rb#L233-L234, override does not override metadata. I guess we should also track this as the expectations for this methods are confussing.

**Comment by wiibaa** [comment]
@purbon @colinsurprenant I'm working on a workaround for this in the clone filter but I'm stuck deciding the correct way of doing a shallow copy, otherwise the events would be sharing their @metadata field. 
`clone["@metadata"] = Marshal.load(Marshal.dump(event["@metadata"]))` looks ugly but seems rather common. Thoughts ?

**Comment by jordansissel** [comment]
@wiibaa seems like we're missing a nice `clone` method that an the Event could expose and solve this. Thoughts?

**Comment by original-brownbear** [comment]
fixed in #4640
