### ISSUE TITLE
Update logstash-filter-aggregate plugin documentation into logstash reference documentation

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#4307]
Hi,

Yesterday, some enhancements were added to asciidoc documentation in logstash-filter-aggregate plugin.
Could you update logstash reference documentation to integrate these enhancements ?

More precisely, could you update "logstash reference 2.0" and "logstash reference master" using logstash-filter-aggregate master branch ?

**Comment by dedemorton** [comment]
Closing because the plugin docs were update quite awhile ago. I guess we forgot to close this issue.
