### ISSUE TITLE
logstash and IDMEF

### ISSUE THREAD

**Issue by saidiahd** [elastic/logstash#4315]
Hi Folk,
is logstash support Collect, Enrich & Transport Data normalized in IDMEF (Intrusion Detection Message Exchange Format) format ? 

cheers,

**Comment by purbon** [comment]
@saidiahd not that I know about. Do you know more information about this format? might be a good addition.

**Comment by purbon** [comment]
@jordansissel what do you think?

**Comment by purbon** [comment]
on the other side @saidiahd, asking this kind of question at https://discuss.elastic.co/ might be a better place to reach more support. just you know about it.

**Comment by saidiahd** [comment]
@purbon  you can find all what you need about IDMEF in http://ietf.org/rfc/rfc4765.txt or throw this PDF http://ietf.org/rfc/rfc4765.txt.pdf. 
IDMEF it's define data formats and exchange procedures for sharing information of interest to intrusion detection and response systems and to the management systems that may need to interact with them.
ok, i will ask this question in discuss page. 

thx

**Comment by purbon** [comment]
you're welcome, thanks for sharing @saidiahd
