### ISSUE TITLE
[Logstash Performance Issue]

### ISSUE THREAD

**Issue by varunkumarmnnit** [elastic/logstash#4318]
Hello ,
Recently I observed  when I  am generating a huge log file and simultaneously using the logstash parsing on that file I am seeing the speed that log file is generated is slower with logstash as compared standalone log generation

**Comment by magnusbaeck** [comment]
Additional context here: https://discuss.elastic.co/t/sincedb-creation/34851

**Comment by suyograo** [comment]
@varunkumarmnnit can you supply more details from the discuss thread here? Add thread dump, config, config etc

**Comment by varunkumarmnnit** [comment]
Hello suyog ,Please find the data related  to the issue in performance I have observed .


Sample Log File Generation timing (141Mb file size) 31808.262ms    -- without running logstash 

Sample Log File Generation timing (141Mb file size) 40033.376ms ---  running logstash simultaneously 

Log stash parsing completed on above file 
6 minutes  


Config file :-1: 

input {
	file{
		path => "D:/Logs/*/MIP/*.log"
               start_position => "beginning"
                
                
              
	}
	
	
}

filter{
	mutate{
		gsub => ["path","D:/Logs/", ""]		
	}
	
}

output {
		

                file{
			path => "Z:/Logs/%{host}/%{path}"
			message_format => "%{message}"
			
}


}




You can see we have two issues here .
First simultaneously using log stash on the input log makes the input log file generation slow 

Logstash is taking huge time to get the final output .


All the above testing  I am doing on windows .


Please clarify my doubts .

Thanks and Regards
Varun

**Comment by varunkumarmnnit** [comment]
Hello ,
Any update on this issue .

**Comment by varunkumarmnnit** [comment]
Can I get update on this issue.

Thanks and Regards 
Varun

**Comment by andrewvc** [comment]
@jsvd do you have any insight on this? Looking through the thread looks like it could be a windows related perf issue perhaps?

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
