### ISSUE TITLE
Specifying JMX parameters in LS_JAVA_OPTS causes Logstash not to restart properly

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#4319]
We added LS_JAVA_OPTS [here](https://www.elastic.co/blog/logstash-1-5-0-rc3-released).  When using the RPM, there are multiple places you can specify LS_JAVA_OPTS, eg. in the /etc/sysconfig/logstash and /etc/init.d/logstash files.  But it looks like the /etc/init.d/logstash is the right place to specify it.

Here is an example when seeing up a JMX connection, if you specify it in /etc/sysconfig/logstash file, this causes issues when using /etc/init.d/logstash restart - it will eventually end up launching multiple RMI servers and fail with a bind exception, eg.

```
sudo /etc/init.d/logstash restart
Configuration error. Not restarting. Re-run with configtest parameter for details

sudo /etc/init.d/logstash configtest 
WARNING: Default JAVA_OPTS will be overridden by the JAVA_OPTS defined in the environment. Environment JAVA_OPTS are -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9994 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false 
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9994; nested exception is: 
java.net.BindException: Address already in use
```

So I moved the LS_JAVA_OPTS settings for the JMX connection from /etc/sysconfig/logstash to /etc/init.d/logstash.  After that, I am no longer able to reproduce the restart issue.

Not sure if this is a bug. If not, it will be nice to document this better in our guide (and as a comment within the sysconfig file, etc..).

**Comment by untergeek** [comment]
They absolutely should go in /etc/sysconfig/logstash for RedHat variants, or /etc/default/logstash for Debian/Ubuntu variants.  I'm not sure why it's failing for JMX in sysconfig, but we ought to fix that and verify the same isn't happening with Debian variants in /etc/default/logstash.

That said, using JMX to monitor Logstash leaves a bad taste in my mouth.  It's going to give broad and potentially meaningless metrics.  Sure, you can see how much heap you're using, but with Logstash that's really only useful if there's a memory leak.  I don't even know if GC is instrumented in JMX, and if so, if it's even a valuable thing with Logstash.  I hope we can get useful metrics out soon.

**Comment by ppf2** [comment]
Reproducible using LS 2.2.2 with the simplest configuration.  Once JMX is added to LS_JAVA_OPTS, it will not restart properly.  See video repro [here](https://drive.google.com/a/elastic.co/file/d/0B1rxJ0dAZbQvMjBLZE1nd1dNQTQ/view?usp=sharing). 

https://github.com/elastic/logstash/issues/4666 is another example of a community user running into the same issue.

**Comment by acchen97** [comment]
Logstash does not support JMX.  For monitoring, it's recommended to use the upcoming metrics API in Logstash 5.0, which will expose pipeline, JVM, OS metrics and hot threads.

**Comment by suyograo** [comment]
Reopening this. I found a fix for this and was able to validate it on deb packages. https://github.com/elastic/logstash/pull/4759

There is still a weird behavior of duplicating `LS_JAVA_OPTS` that is really baffling me, but I'll chase it for another day.
