### ISSUE TITLE
[Logstash configuration issue]

### ISSUE THREAD

**Issue by varunkumarmnnit** [elastic/logstash#4330]
Hello ,
Below is my configuration for a logstash config file 
               file{
			path => "Z:/Logs/%{host}/%{path}"
			message_format => "%{message}"
			flush_interval => 0
}

in one of my computer this is working but in another computer its not working and showing below error 

io/console not supported; tty will not be manipulated
Default settings used: Filter workers: 4
←[31mFile: The starting part of the path should not be dynamic. {:path=>"F:/%{ho
st}/%{path}", :level=>:error}←[0m
Error: The starting part of the path should not be dynamic.
You may be interested in the '--configtest' flag which you can
use to validate logstash's configuration before you choose

I am not able to figure out whats the issue .

Thanks and Regards 
Varun

**Comment by suyograo** [comment]
Hi can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
