### ISSUE TITLE
Upgrade to JrJackson 0.3.8 - JSON Decoding issues starting with 1.5.5

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#4332]
See - [JSON decoding issues starting with version 1.5.5](https://github.com/elastic/logstash/issues/4316)

**Comment by purbon** [comment]
According to:

```
    gem.add_runtime_dependency "jrjackson", "~> 0.3.7" #(Apache 2.0 license)
```

from https://github.com/elastic/logstash/blob/master/logstash-core/logstash-core.gemspec#L45

the new version will be pickup when we build another release or run any bootstrap/install action.

will be a good idea to document this issue in the meanwhile as we did with the concurrent-ruby issue? can you provide here more details about it and what people should do to fix it?

**Comment by guyboertje** [comment]
In the past, we have changed the gemspec to `~> <latest ver>`.

In this case 0.3.7 has a known problem in the Jackson lib so we should not give bundler the option to  pick ver 0.3.7.

Maybe this is exactly what we should be broadcasting on Twitter?

**Comment by purbon** [comment]
@guyboertje you can, I did it for the twitter updates there.

re:updating gemspec, all up to you, bundler will not pick it at any chance, unless some crazy requirements are there. feel free to update the gemspec :+1:

**Comment by suyograo** [comment]
@guyboertje +1, PR when you can

**Comment by suyograo** [comment]
v2.1.2 will have jrjackson 0.3.8. see #4377
