### ISSUE TITLE
Split by bytes filter

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#4335]
This is a feature request idea for a split filter that will split a potentially huge event into multiple smaller events.  Use case is that for application logs, it can be unpredictable when it decides to dump out an gigantic stack trace, or trace log with huge response bodies.  The byte-based flush_size in the future will help with this.  But what if a single event is huge enough so that at flush_size = 1, LS is still running out of memory?  For such edge cases, it can be helpful if there is a split filter that is based on size (bytes) that will split the large message into multiple pieces (and inject a key into each event so one can use it as a way to "link" up the split events thereafter).

**Comment by ppf2** [comment]
The split/multi-part events will need a common key tagged to it for association later on.  Maybe we can provide 2 options:

* For those with a key field in the pre-split event that is already uniquely identifying the event, we can provide an option for them to specify a field name for this filter so it will simply use that key field and tag it to each split event.
* For those without a key field in the event that uniquely identifies it, the filter can generate a unique  association key automatically and tag it to each split event

**Comment by acchen97** [comment]
Closed with alternate solution in the Elasticsearch output plugin https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/497.
