### ISSUE TITLE
RabbitMQ input fails to load

### ISSUE THREAD

**Issue by darinfisher** [elastic/logstash#4343]
When attempting to use the RabbitMQ input the start up fails.

/opt/logstash/bin/logstash agent --config rabbitmq.conf -v --debug
Reading config file {:config_file=>"/home/darinf/work/logstash/test_rabbitmq/rabbitmq.conf", :level=>:debug, :file=>"logstash/agent.rb", :line=>"325", :method=>"local_config"}
Compiled pipeline code:
        @inputs = []
        @filters = []
        @outputs = []
        @periodic_flushers = []
        @shutdown_flushers = []

          @input_rabbitmq_1 = plugin("input", "rabbitmq", LogStash::Util.hash_merge_many({ "host" => ("localhost") }, { "ssl" => ("true") }, { "verify_ssl" => ("false") }, { "queue" => ("df_metrics") }, { "exchange" => ("dftest") }, { "prefetch_count" => 10 }, { "durable" => ("true") }, { "codec" => ("json") }))

          @inputs << @input_rabbitmq_1

          @output_stdout_2 = plugin("output", "stdout", LogStash::Util.hash_merge_many({ "codec" => ("rubydebug") }))

          @outputs << @output_stdout_2

  def filter_func(event)
    events = [event]
    @logger.debug? && @logger.debug("filter received", :event => event.to_hash)
    events
  end
  def output_func(event)
    @logger.debug? && @logger.debug("output received", :event => event.to_hash)
    @output_stdout_2.handle(event)
    
  end {:level=>:debug, :file=>"logstash/pipeline.rb", :line=>"38", :method=>"initialize"}
Plugin not defined in namespace, checking for plugin file {:type=>"input", :name=>"rabbitmq", :path=>"logstash/inputs/rabbitmq", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"76", :method=>"lookup"}
The error reported is: 
  Couldn't find any input plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq input plugin resulted in this error: no such file to load -- ext/rabbitmq-client
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/plugin.rb:85:in `lookup'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:304:in `plugin'
(eval):7:in `initialize'
org/jruby/RubyKernel.java:1079:in `eval'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:40:in `initialize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/agent.rb:124:in `execute'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/runner.rb:90:in `run'
org/jruby/RubyProc.java:281:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/runner.rb:95:in `run'
org/jruby/RubyProc.java:281:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'
darinf@silo:~/work/logstash/test_rabbitmq$ 
darinf@silo:~/work/logstash/test_rabbitmq$ 
darinf@silo:~/work/logstash/test_rabbitmq$ 
darinf@silo:~/work/logstash/test_rabbitmq$ 
darinf@silo:~/work/logstash/test_rabbitmq$ 
darinf@silo:~/work/logstash/test_rabbitmq$ /opt/logstash/bin/logstash agent --config rabbitmq.conf --verbose --debug
The error reported is: 
  Couldn't find any input plugin named 'rabbitmq'. Are you sure this is correct? Trying to load the rabbitmq input plugin resulted in this error: no such file to load -- ext/rabbitmq-client

The resolution is to update the plugin:

bin/plugin update logstash-input-rabbitmq
Updating logstash-input-rabbitmq
Updated logstash-input-rabbitmq 3.1.1 to 3.1.2

Please fix in the distribution.

**Comment by andrewvc** [comment]
Hi Darin we just updated the plugin to fix this. Can you try updating and
reply back with the results?

**Comment by andrewvc** [comment]
To be clear you'll need to use bin/plugin update to fix this

**Comment by darinfisher** [comment]
Yes, the update worked great.
I will open a ticket with Elastic.co to update their repository distro

Thanks!
