### ISSUE TITLE
Hello, why I lose some fields:logtimestamp, level...

### ISSUE THREAD

**Issue by zhengfc** [elastic/logstash#4346]
* file:serverTest.log
<pre>
2015-11-20 13:56:23,969 ERROR  [org.jboss.ejb3.proxy.impl.jndiregistrar.JndiSessionRegistrarBase] (main) Binding the following Entries in Global JNDI1:

	SecureDeploymentManager/remote - EJB3.x Default Remote Business Interface
	SecureDeploymentManager/remote-org.jboss.deployers.spi.management.deploy.DeploymentManager - EJB3.x Remote Business Interface
2015-11-20 13:56:23,969 INFO  [org.jboss.ejb3.proxy.impl.jndiregistrar.JndiSessionRegistrarBase] (main) Binding the following Entries in Global JNDI2:

	SecureDeploymentManager/remote - EJB3.x Default Remote Business Interface
	SecureDeploymentManager/remote-org.jboss.deployers.spi.management.deploy.DeploymentManager - EJB3.x Remote Business Interface
</pre>

* conf: logstash_f5.conf, patterns: grok-java-pattern
<pre>
JAVACLASS (?:[a-zA-Z$_][a-zA-Z$_0-9]*\.)*[a-zA-Z$_][a-zA-Z$_0-9]*
#Space is an allowed character to match special cases like 'Native Method' or 'Unknown Source'
JAVAFILE (?:[A-Za-z0-9_. -]+)
#Allow special <init> method
JAVAMETHOD (?:(<init>)|[a-zA-Z$_][a-zA-Z$_0-9]*)
#Line number is optional in special cases 'Native method' or 'Unknown source'
JAVASTACKTRACEPART %{SPACE}at %{JAVACLASS:class}\.%{JAVAMETHOD:method}\(%{JAVAFILE:file}(?::%{NUMBER:line})?\)
#Java Logs
JAVATHREAD (?:[A-Z]{2}-Processor[\d]+)
JAVACLASS (?:[a-zA-Z0-9-]+\.)+[A-Za-z0-9$]+
JAVAFILE (?:[A-Za-z0-9_.-]+)
JAVASTACKTRACEPART at %{JAVACLASS:class}\.%{WORD:method}\(%{JAVAFILE:file}:%{NUMBER:line}\)
JAVALOGMESSAGE (.*)
#MMM dd, yyyy HH:mm:ss eg: Jan 9, 2014 7:13:13 AM
CATALINA_DATESTAMP %{MONTH} %{MONTHDAY}, 20%{YEAR} %{HOUR}:?%{MINUTE}(?::?%{SECOND}) (?:AM|PM)
#yyyy-MM-dd HH:mm:ss,SSS ZZZ eg: 2014-01-09 17:32:25,527 -0800
TOMCAT_DATESTAMP 20%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:?%{MINUTE}(?::?%{SECOND}) %{ISO8601_TIMEZONE}
CATALINALOG %{CATALINA_DATESTAMP:timestamp} %{JAVACLASS:class} %{JAVALOGMESSAGE:logmessage}
#2014-01-09 20:03:28,269 -0800 | ERROR | com.example.service.ExampleService - something compeletely unexpected happened...
TOMCATLOG %{TOMCAT_DATESTAMP:timestamp} \| %{LOGLEVEL:level} \| %{JAVACLASS:class} - %{JAVALOGMESSAGE:logmessage}
#Log Levels
LOGLEVEL ([Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)
#jboss
JBOSS_DATESTAMP 20%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:?%{MINUTE}(?::?%{SECOND})
JBOSSLOG %{JBOSS_DATESTAMP:logtimestamp} %{LOGLEVEL:level} \[%{JAVACLASS:class}\] %{JAVALOGMESSAGE:logmessage}
</pre>
<pre>
input { 
file {
    path => "/home/zhengfc/workstall/logstash-2.1.0/log/serverTest.log"
    type => "log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => multiline {
      patterns_dir => "/home/zhengfc/workstall/logstash-2.1.0/grok-java-pattern"
      pattern => "^%{JBOSS_DATESTAMP}"
      negate => true
      what => "previous"
    }
}
}
filter {
    grok {
      patterns_dir => "/home/zhengfc/workstall/logstash-2.1.0/grok-java-pattern"
      match => { "message" => "%{JBOSSLOG}" }
    }
#date {
#match => [ "logtimestamp" , "YYYY-MM-dd HH:mm:ss,SSS" ]
#}
}
output {
  elasticsearch { hosts => "127.0.0.1" }
  stdout { codec => rubydebug }
}
</pre>
* stdout
<pre>
{
    "@timestamp" => "2015-12-14T03:15:23.176Z",
       "message" => "2015-11-20 13:56:23,969 ERROR  [org.jboss.ejb3.proxy.impl.jndiregistrar.JndiSessionRegistrarBase] (main) Binding the following Entries in Global JNDI1:\r\n\r\n\tSecureDeploymentManager/remote - EJB3.x Default Remote Business Interface\r\n\tSecureDeploymentManager/remote-org.jboss.deployers.spi.management.deploy.DeploymentManager - EJB3.x Remote Business Interface\r",
      "@version" => "1",
          "tags" => [
        [0] "multiline",
        [1] "_grokparsefailure"
    ],
          "host" => "ubuntu",
          "path" => "/home/zhengfc/workstall/logstash-2.1.0/log/serverTest.log",
          "type" => "log"
}
{
    "@timestamp" => "2015-12-14T03:15:23.180Z",
       "message" => "2015-11-20 13:56:23,969 INFO  [org.jboss.ejb3.proxy.impl.jndiregistrar.JndiSessionRegistrarBase] (main) Binding the following Entries in Global JNDI2:\r\n\r\n\tSecureDeploymentManager/remote - EJB3.x Default Remote Business Interface\r\n\tSecureDeploymentManager/remote-org.jboss.deployers.spi.management.deploy.DeploymentManager - EJB3.x Remote Business Interface\r",
      "@version" => "1",
          "tags" => [
        [0] "multiline",
        [1] "_grokparsefailure"
    ],
          "host" => "ubuntu",
          "path" => "/home/zhengfc/workstall/logstash-2.1.0/log/serverTest.log",
          "type" => "log"
}
</pre>

Thanks for your answers

**Comment by suyograo** [comment]
Hi can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
