### ISSUE TITLE
Error and possible fix in Logstash grok exception handling 

### ISSUE THREAD

**Issue by nipunarora** [elastic/logstash#4348]
I am using logstash-1.4.2 and found a grok exception happening for some of our training and testing files.
Can anyone please confirm if the fix is correct? And why exactly the exception happens? 

I found the following:

The function match in the file logstash-1.4.2/lib/logstash/filters/grok.rb needs to be changed. The change is highlighted below. I basically added a return false in the rescue exception handler, and some logging informatitio The exception seems to happen for .* expression probably because of increased state machine, but I need to investigate this further. I think (although I am not sure) this is only happening for unmatched patterns. For now we can take the default option of "unmatched" for any exception happening in logstash. Hopefully these exceptions will be uncommon.

One additional thing to note is that the same line can throw multiple exceptions. I confirmed this by looking at the debug output information I added in the exception handler.

````
  private
  def match(grok, field, event)
    input = event[field]
    if input.is_a?(Array)
      success = true
      input.each do |input|
        grok, match = grok.match(input)
        if match
          match.each_capture do |capture, value|
            handle(capture, value, event)
          end
        else
          success = false
        end
      end
      return success
    #elsif input.is_a?(String)                                                                                                                                                                                    
    else
      # Convert anything else to string (number, hash, etc)                                                                                                                                                       
      grok, match = grok.match(input.to_s)
      return false if !match

      match.each_capture do |capture, value|
        handle(capture, value, event)
      end
      return true
    end
  rescue StandardError => e
    @logger.warn('------')
    @logger.warn("Grok regexp threw exception", :exception => e.message)
    @logger.warn(' The input is ')
    @logger.warn(input)
    @logger.warn('------')
    return false
  end
````

**Comment by suyograo** [comment]
Hey this is an old version of LS. Can you reproduce this with 1.5 or 2.1? There were a lot of grok related fixes in 1.5+

**Comment by nipunarora** [comment]
ok.. let me see if I can re-create the error in 1.5/2.1. 
However, for my purposes, I need to keep using 1.4.2 as that is the version we are using in our stable deployment. Is it possible to know if the fix shown above is correct or not? 
I would expect that if an exception happens it should return false (it returned nothing before the fix).

**Comment by nipunarora** [comment]
This error still exists in V2.1.1.
Here is the exception thrown in the execution:
````
{:timestamp=>"2015-12-15T11:36:40.050000-0500", :message=>"Grok regexp threw exception", :exception=>"63", :level=>:warn, :file=>"logstash/filters/grok.rb", :line=>"319", :method=>"match"}
````
 I believe it's from line 319 in this file, and the fix is the same as I proposed above.
vendor/bundle/jruby/1.9/gems/logstash-filter-grok-2.0.2/lib/logstash/filters/grok.rb

**Comment by nipunarora** [comment]
@suyograo Please let me know if more details are required. I'd like to verify the fix with the community before applying it locally in our deployment

**Comment by nipunarora** [comment]
Hi, Could anyone please let me know about the status of this issue? I'd like to resolve it in our current distribution.

**Comment by guyboertje** [comment]
@nipunarora - You are correct this is a bug of sorts.  I am not sure why your setup makes the exception get thrown in the first place.

You suggest that the rescue block should return false.  This is correct.  However the `@logger.warn(...)` does return something, a Hash, and this is truthy in Ruby.  Therefore the caller continues as if a match occurred which is wrong.

You can add the `return false` to your deployment and you should create an issue in the grok filter - but if you do you should also give details of what config and data will cause the exception to be thrown so someone can add a failing test to verify the fix.  It may also enable the fixing of whatever is causing the exception.

**Comment by nipunarora** [comment]
@guyboertje 
Thanks for the explanation. If possible, I'd like to find a patch to remove the exception.
Where is the grok filter community, where I can make this an issue?

**Comment by guyboertje** [comment]
On the [Elastic home page](https://www.elastic.co/) - in the top RH corner, is a link to the Discussion forums. Go to the Logstash forum and ask there first.  Once you have a better idea of the problem and what it takes to trigger it then create an issue in [logstash-filter-grok](https://github.com/logstash-plugins/logstash-filter-grok)
