### ISSUE TITLE
We need to be able to set a node name from the command line the name of the logstash instance

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4353]
This name will be used for the agent and also from the metrics collection.

After discussing with @andrewvc we think that `-n` of `--name` would be a good name. The name will be send to Agent for now and show in the log.

If no name is given we will fallback to the current hostname.

**Comment by andrewvc** [comment]
@ph will this also include a per-run UUID?

**Comment by ph** [comment]
@andrewvc what do you mean by per run UUID?

**Comment by andrewvc** [comment]
Errr, in the design discussions @jsvd and I have had there would be two IDs:

1. A name, that is overridable by the user and is an arbitrary string. Defaults to network hostname.
2. A per-run UUID. This is useful in separating out actual runs. Also useful in that if you migrate the host to a new box you are at least guaranteed a UUID change.

The name is more generally useful, but the UUID has its utility as well. Thoughts @ph?

**Comment by ph** [comment]
@andrewvc OK and this UUID is valid for the current instance of Logstash, when logstash restart we will get a new one?

**Comment by purbon** [comment]
@ph @andrewvc just a proposal, can we make more explicit this is the node name? only with ```--name``` is not clear to me which kind of name we are setting here. makes sense to you?

**Comment by ph** [comment]
@purbon I am ok with `--node-name` @andrewvc WDYT ?
