### ISSUE TITLE
Sincedb file per input

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#4381]
Using the **same** sincedb file for different inputs, no matter whether is the same pattern or a similar pattern, causes the file to **only store the information from a single location**. The sincedb file seems to be completely replaced with the information of a single input at a time.

**Comment by gmoskovicz** [comment]
@ph do you think that this is accurate and will clarify some issues?

**Comment by gmoskovicz** [comment]
@guyboertje also discussed with you, what do you think about this?

**Comment by ph** [comment]
@gmoskovicz I think this is accurate. Each `File input` has is own metadata data about the file it watches.  So if you use the same `sincedb` for each input the data the data may be erased from another plugin. Its better to define a new sincedb for each input.

**Comment by gmoskovicz** [comment]
@ph i've added a new PR on the file input, please take a look at logstash-plugins/logstash-input-file#88 . Feel free to leave some comments :D its just some extra information so we avoid issues with people using the same sincedb path for different inputs.

**Comment by gmoskovicz** [comment]
Closed by logstash-plugins/logstash-input-file#88
