### ISSUE TITLE
AbstractController::ActionNotFound not reported.

### ISSUE THREAD

**Issue by imnithin** [elastic/logstash#4394]
Ruby on Rails app.

I have integrated logstash and kibana.
From rails log - 
`AbstractController::ActionNotFound The action 'action_name' could not be found for MyController:`

Is not being reported into `logstash agent` log.

logstash 2.1.0

Let me know if any further information to be provided.

**Comment by suyograo** [comment]
@imnithin What are you trying to do? How are your integrating with the rails app? Its very unclear from your description.

Please take this discussion to https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
