### ISSUE TITLE
Logs from logstash indexer produce abnormal spam Logstash

### ISSUE THREAD

**Issue by szemlyanoy** [elastic/logstash#4398]
Dear community,

Logstash version 1.5.6

Problem:
I have some logstash configs populated cross the fleet as well as on logatash indexer itself.
When I simulate error from any agent, event is processed, stored in ES and emailed properly.
When I simulate the same event on indexer it starts sending countless amount of messages with mutated subject with multiply %{process} field.

Config below:

input{
file{
type => "syslog"
path => "/var/log/messages"
start_position => "end"
sincedb_path => "/etc/logstash-sincedb/syslog"
}
}

filter {
if [type] == "syslog" and [host] == "elk.improve" {
grok{
patterns_dir => [ "/etc/logstash/patterns" ]
match => ["message", "%{SYSLOGTIMESTAMP:timestamp} %{HOST} %{WORD:source}: %{WORD:process} ?(.oom-killer.): %{GREEDYDATA:info}"]
add_tag => ["syslog_oom_error"]
}

if "_grokparsefailure" in [tags] {
drop {}
}
}
}

output {
if [type] == "syslog" and [host] == "elk.improve"{
redis {
host => "redis.improve"
data_type => "list"
key => "logstash"
}
}
if "syslog_oom_error" in [tags] and [host] == "elk.improve"{
email{
to => "reciever"
from => "sender"
subject => "Logstash: %{process} invoked OOM-killer on %{host}"
body => "%{message}"
via => "smtp"
options => {
smtpIporHost => "mail.perrit.nl"
port => "25"
userName => "somename"
password => ***
authenticationType => plain
}
}
}

}

Outputs sent with subject

Logstash: sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd,sssd invoked OOM-killer on elk.improve

The same messages from rest servers as I mentioned are processing fine. Also other logs from indexer server itself are processed properly.  What is wrong with this particular config?

Thanks for any support,
Sergey

**Comment by markwalkom** [comment]
Please join us at https://discuss.elastic.co/ or at #kibana on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)
