### ISSUE TITLE
Geo_Point not populating no matter what i do please help..

### ISSUE THREAD

**Issue by Vikran** [elastic/logstash#4400]
Hi Team,

I have spend good last 3-4 days including re-indexing to get the Geo Location for Tile Map working but all in vein.
Multiple log of various type are indexed in logstash-* index.
I have applied geo filter example :

I am using Elasticserach, Logstash  2.1.1  and kibana kibana-4.3.0

I use filter like : 
    geoip {
      source => "dns_query"
      target => "geoip"
      add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
      add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
    }
    mutate {
      convert => [ "[geoip][coordinates]", "float"]
    }

also for one of the logs :-

 geoip {
                  source => "id_h"
                  target => "h_geoip"
                }
                geoip {
                  source => "id_r"
                  target => "r_geoip"
                }
Output :

output {
  elasticsearch {
          hosts => "es.cluster"
  }
  stdout { codec => rubydebug }
}

i can see geo.ip and geo.location and ofcourse its not indexed and when i tryto visulatize using tile map i dont get geohash
i have checked template for elasticsearch it does show mapping as geo_point which is default.

"properties" : {
        "@timestamp": { "type": "date", "doc_values" : true },
        "@version": { "type": "string", "index": "not_analyzed", "doc_values" : true },
        "geoip"  : {
          "type" : "object",
          "dynamic": true,
          "properties" : {
            "ip": { "type": "ip", "doc_values" : true },
            "location" : { "type" : "geo_point", "doc_values" : true },
            "latitude" : { "type" : "float", "doc_values" : true },
            "longitude" : { "type" : "float", "doc_values" : true }
          }

When i try to see in the indexes fields :

Mapping conflict! 2 fields are defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data. 

Confirmed the mapping :
"logstash-2015.12.28" : {
    "mappings" : {
      "dns" : {
        "geoip.location" : {
          "full_name" : "geoip.location",
          "mapping" : {
            "location" : {
              "type" : "geo_point"
            }
          }
        }
It used to work fine with previous version.

Please help as i am clueless on this.

Regards
Vik
<img width="128" alt="capture" src="https://cloud.githubusercontent.com/assets/8602704/12016340/bc00b7b8-ad9d-11e5-8a5e-d2d82d3b6692.PNG">

**Comment by jsvd** [comment]
can you show the full configuration?

**Comment by Vikran** [comment]
Hi ,

Although conf is huge here is relevant to the above :
Template used is the default with logstash.
DNS filter:
```
if [type] == "dns" {
     grok {
      match => { "message" =>  "query: %{IPORHOST:dns_query}" }
         }
       if [dns_query] == "-" {
            drop {}
       }
      geoip {
      		 source => "dns_query"
     		 target => "geoip"
      		 add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
     		 add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
    }
    mutate {
               convert => [ "[geoip][coordinates]", "float"]
    }
 }

 if [type] == "trans_log" {
                csv {
                 columns => ["id_h","id_r","duration","history","date"]
                 separator => " "
                }
                date {
                 match => [ "ts", "UNIX" ]
                }
                # add geoip attributes
               geoip {
			source => "id_h"
			target => "h_geoip"
		}
		geoip {
			source => "id_r"
			target => "r_geoip"
		}
}

Output.conf:

output {
     elasticsearch {
     hosts => "es.cluster"
    }
     stdout { codec => rubydebug }
}
```

the geoip.ip and geoip.location are the only one which are causing conflict.
I have even tried disabling one of the custom geo fields for transaction thinking it might be causing conflict but it does not.
Default index logstash-* is in place so default template should pick up.
Help would be appreciated.
~Vik

**Comment by jsvd** [comment]
ok. so I understand better, kibana shows a conflict in the mapping of geoip.location and geoip.ip. so the fields added by trans_log (r_geoip and h_geoip) aren't relevant, right? This is a problem only related to dns data

**Comment by jsvd** [comment]
do all new indices (created daily) have this conflict? have you tried restricting the stdout to dns logs and analyze the output to look for weird values in geoip.localtion and geoip.ip?

**Comment by Vikran** [comment]
correct, although right now i want geomapping for only dns, eventually i would like to have for trans_log as well (r_geoip and h_geoip) is next step but i am stuck with even the straight forward one i.e. dns.

**Comment by Vikran** [comment]
good point dns is giving following std output :
"geoip" => {
                      "ip" => "98.138.253.109",
           "country_code2" => "US",
           "country_code3" => "USA",
            "country_name" => "United States",
          "continent_code" => "NA",
             "region_name" => "CA",
               "city_name" => "Sunnyvale",
             "postal_code" => "94089",
                "latitude" => 37.42490000000001,
               "longitude" => -122.00739999999999,
                "dma_code" => 807,
               "area_code" => 408,
                "timezone" => "America/Los_Angeles",
        "real_region_name" => "California",
                "location" => [
            [0] -122.00739999999999,
            [1] 37.42490000000001
        ],
             "coordinates" => [
            [0] -122.00739999999999,
            [1] 37.42490000000001
        ]

Looks good to me for geoip and other coordinates

**Comment by jsvd** [comment]
My current guess is that not all logstash-* indices have the same mapping..can you check all existing logstash mappings ?

```
% curl -s 'localhost:9200/logstash-*/_mapping/?pretty' | grep location -A 1
              "location" : {
                "type" : "geo_point"
--
              "location" : {
                "type" : "geo_point"
--
              "location" : {
                "type" : "geo_point"
--
              "location" : {
                "type" : "geo_point"
```

**Comment by Vikran** [comment]
Hi,
In mean while i backed up indices and refreshed again and its populating fine for dns. Now for other log need to create template i believe will it work with same index logstash-* ?
For single dns log it worked after reindexing.

~Vik

**Comment by jsvd** [comment]
Not sure I understood, are you also sending translogs to logstash-*? if not (if they have different mappings) then you can do

```
output {
  if [type] == "dns" {
    elasticsearch { hosts => "es.cluster"    }
  } else if [type] == "trans_log" {
    elasticsearch { hosts => "es.cluster"  index => "translogs-%{+YYYY.MM.dd}"  }
  }
}
```

**Comment by Vikran** [comment]
Hi,yes  I am sending the translogs also to logstash-* . Considering the default template only have geoip mapping i need to add new mapping in default template or i need to change th output as suggested by you to log to different index.

Cant i add in default template similar to geoip, r_geoip, h_geoip ? do i have to created new index ?

**Comment by jsvd** [comment]
if you send all logs to the same index some events will not have the r_geoip and some will, which isn't optimal. but you can still do it, you need to modify the default template that logstash ships with and add 2 other fields with geopoint like the one for `geoip`:

```
% cat ./vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/elasticsearch-template.json | grep geoip -A 9
        "geoip"  : {
          "type" : "object",
          "dynamic": true,
          "properties" : {
            "ip": { "type": "ip", "doc_values" : true },
            "location" : { "type" : "geo_point", "doc_values" : true },
            "latitude" : { "type" : "float", "doc_values" : true },
            "longitude" : { "type" : "float", "doc_values" : true }
          }
        }
```

The alternative, if you're sending translogs to another index, is to copy the template, modify it, and use it in:

```
output {
  if [type] == "dns" {
    elasticsearch { hosts => "es.cluster"    }
  } else if [type] == "trans_log" {
    elasticsearch { hosts => "es.cluster"  index => "translogs-%{+YYYY.MM.dd}" template => "/path/to/special_trans_log_elasticsearch_template.json" }
  }
}
```

**Comment by Vikran** [comment]
Got it reasonable enough i will give it a go with separate index as it will help in production to keep optimal performance as geo can be heavy on resource.

**Comment by jsvd** [comment]
:+1: feel free to close the issue if you feel the initial concern is addressed.

**Comment by Vikran** [comment]
sure giving it a go as we speak :+1:

**Comment by Vikran** [comment]
Hi , I tried different index but my index still take pattern  _index 		logstash-2015.12.28 ? dont see any errors ..

**Comment by Vikran** [comment]
Ok got it been long day i mistyped the type of log

**Comment by jsvd** [comment]
I'm glad it's sorted!

**Comment by Vikran** [comment]
Thanks for help , yes go index working but tile map still not mapping with the saperate template giving it a go last time today :) 
Thanks for help will reach out if get stuck again. Appreciate patience
