### ISSUE TITLE
Change to a single agent.conf brings down logstash server

### ISSUE THREAD

**Issue by coutotyler** [elastic/logstash#4407]
I'm new to logstash. Today I tried updating a single agent.conf to test changes thinking that it would be safe, but it brought down my logstash server. I expect that this is not correct behavior, that a change to an agent.conf should only affect the agent itself. 

logstash version: 1.4.2
os - logstash server: centos 5.7
os - logstash agent: centos 5.11

Here are the original and modified agent.conf files along with the errors: 
https://gist.github.com/coutotyler/846f0c9bd4ab3873f613

**Comment by ph** [comment]
Any log on the logstash server/agent side?

**Comment by coutotyler** [comment]
The one I posted is from the server (indexer) side. I added the agent/shipper errors to the gist.

**Comment by ph** [comment]
@coutotyler thx, I note you are using 1.4.2 which is a really old version, the current version is 2.1, did you try a more recent version to see if the problem is fixed?

**Comment by coutotyler** [comment]
Thanks, @ph. I haven't done that. I'm picking up where someone left off, and we are using graylog which I've heard doesn't support elasticsearch 2. Anyway, that's definitely something I'll look into.

**Comment by magnusbaeck** [comment]
> I'm picking up where someone left off, and we are using graylog which I've heard doesn't support elasticsearch 2.

Logstash 2.x works just fine with ES 1.x as long as you use the HTTP protocol for connecting the two.

**Comment by coutotyler** [comment]
Good to know. Thank you

**Comment by suyograo** [comment]
@coutotyler can you try with 2.1.x and let us know if this is an issue still? Will reopen if so
