### ISSUE TITLE
Implement Proxy protocol support for tcp inputs

### ISSUE THREAD

**Issue by nneul** [elastic/logstash#4418]
Support for proxy protocol version 1 (and optionally version 2) for tcp inputs ('tcp', 'log4j', and 'syslog' at least) would be highly useful to allow logstash to sit behind an HAProxy or ELB load balancer.

**Comment by nneul** [comment]
Copy of thread from discuss:

https://discuss.elastic.co/t/proxy-protocol-support-for-logstash-elb-and-haproxy-for-inbound-failover/38117


Proxy protocol support for logstash? (ELB and HAProxy for inbound failover) 
Logstash
3 / 5
 

nneulNathan Neulinger7d
Is there any way to get proxy protocol support for logstash so that the indexer can see the originating IP/host for the connections if you have logstash sitting behind ELB or HAProxy?


Reply

created
Dec 29, '15
last reply
11 mins 4
replies
36
views
2
users
2
links
3 2 
Reply as linked Topic

magnusbaeckMagnus BäckLogstash Plugins Community Maintainer1h
Which inbound protocol(s)?


Reply
Reply as linked Topic

nneulNathan Neulinger36m
It would technically be for anything TCP based since the protocol (version 1 at least) is just a single line header added to the start of any tcp stream.

For my particular need, having it for the 'tcp', 'log4j', and 'syslog' inputs would cover everything I'm using.

A common use case would be a few logstash forwarders sitting behind an haproxy or Amazon ELB load balancer for failover handling.

From http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt :

`
The maximum line lengths the receiver must support including the CRLF are :

TCP/IPv4 :
"PROXY TCP4 255.255.255.255 255.255.255.255 65535 65535\r\n"
=> 5 + 1 + 4 + 1 + 15 + 1 + 15 + 1 + 5 + 1 + 5 + 2 = 56 chars

TCP/IPv6 :
"PROXY TCP6 ffff:f...f:ffff ffff:f...f:ffff 65535 65535\r\n"
=> 5 + 1 + 4 + 1 + 39 + 1 + 39 + 1 + 5 + 1 + 5 + 2 = 104 chars

unknown connection (short form) :
"PROXY UNKNOWN\r\n"
=> 5 + 1 + 7 + 2 = 15 chars

worst case (optional fields set to 0xff) :
"PROXY UNKNOWN ffff:f...f:ffff ffff:f...f:ffff 65535 65535\r\n"
=> 5 + 1 + 7 + 1 + 39 + 1 + 39 + 1 + 5 + 1 + 5 + 2 = 107 chars
`

2 RepliesReply
Reply as linked Topic

nneulNathan Neulinger32m
Note - Amazon only does Proxy protocol v1. HAProxy supports v1 or v2. v2 is a more complex binary format. Support for v1 would be sufficient for now, but keep option for protocol version in mind when implementing configuration syntax.

Reply
Reply as linked Topic

magnusbaeckMagnus BäckLogstash Plugins Community Maintainer11m    nneul
Okay. Sounds like something reasonable to support. I suggest filing an issue at https://github.com/elastic/logstash/issues since it should be included in a core library. I wouldn't assume the team picks up feature requests from here.


Reply
Reply as linked Topic

**Comment by jordansissel** [comment]
I'm open to this feature.

**Comment by nneul** [comment]
Bump? Is this still not supported?

**Comment by jordansissel** [comment]
as far as I know, no, there's been no patch to add proxy protocol support to the tcp input.

**Comment by nneul** [comment]
https://github.com/logstash-plugins/logstash-input-tcp/pull/57

Waiting for that to be accepted. If it is, will try to do the same for syslog and log4j inputs.

**Comment by greenkiwi** [comment]
@jordansissel This is a feature that we would love to have.  Is there anything I can do to help review/test it?

**Comment by jordansissel** [comment]
@greenkiwi Testing would be lovely --- https://github.com/logstash-plugins/logstash-input-tcp/pull/57 -- review is in-progress.

**Comment by nneul** [comment]
This is in place/merged for syslog and tcp inputs. Waiting for action on log4j input.

**Comment by Strum355** [comment]
Can this be closed? As far as https://github.com/logstash-plugins/logstash-input-tcp/pull/57 would imply is that its merged? Or am i missing something?

**Comment by jsvd** [comment]
++ closing. If there's an issue with the proxy support on tcp input please open an issue in https://github.com/logstash-plugins/logstash-input-tcp

**Comment by benvanstaveren** [comment]
Can we get this on the beats input as well?
