### ISSUE TITLE
Add section to 'How to Write an Output Plugin' covering changes in OutputDelegator

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#4423]
We should add a short section to [How to write an output plugin](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html) covering `declare_threadsafe!` and `declare_workers_not_supported` before we launch 2.2 as the blog post covering that will link to that . These changes were introduced in https://github.com/elastic/logstash/pull/4391

**Comment by suyograo** [comment]
Fixed in #4391
