### ISSUE TITLE
logstash agent service does not come

### ISSUE THREAD

**Issue by 467754239** [elastic/logstash#4424]
Exception in thread "<file" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)

**Comment by markwalkom** [comment]
There's very little to go by here.

What version? What does your config look like? Is this a bug or just a problem?

**Comment by 467754239** [comment]
logstash的版本 1.5.4
配置也比较简单
input {
    file {
        type => "xxx"
        path => [ "/var/log/xxxx1.log", "/var/log/xxx2.log" ]
        add_field => {
                "public_ip" => "xxxx"
                }
        codec => plain {
                charset => "UTF-8"
                }
        start_position => "beginning"
        }
}
output {
    redis {
        host => "xxx"
        port => 6379
        data_type => "list"
        key => "logstash:redis"
        }
}

**Comment by 467754239** [comment]
logstash version 1.5.4
configure file
input {
file {
type => "xxx"
path => [ "/var/log/xxxx1.log", "/var/log/xxx2.log" ]
add_field => {
"public_ip" => "xxxx"
}
codec => plain {
charset => "UTF-8"
}
start_position => "beginning"
}
}
output {
redis {
host => "xxx"
port => 6379
data_type => "list"
key => "logstash:redis"
}
}

**Comment by markwalkom** [comment]
Is that the entire error?

**Comment by 467754239** [comment]
Those are the version number and the configuration file for my logstash-agent.

Error as follows：
[ec2-user@ip-172-31-13-47 conf.d]$ ll /var/log/logstash/
total 16
-rwxrwxrwx 1 logstash logstash 287 Jan  6 05:00 logstash.err
-rwxrwxrwx 1 logstash logstash   0 Dec  9 10:01 logstash.log
-rwxrwxrwx 1 logstash logstash 317 Dec  9 10:01 logstash.log-20151112.gz
-rwxrwxrwx 1 logstash logstash 438 Dec  9 10:01 logstash.log-20151209
-rwxrwxrwx 1 logstash logstash  57 Jan  6 05:00 logstash.stdout
[ec2-user@ip-172-31-13-47 conf.d]$ cat /var/log/logstash/logstash.err 
Exception in thread "<file" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jsvd** [comment]
That happens in logstash < 2.1 when there's an OutOfMemory exception. It's strange that it's coming from file input, it's usually related to elasticsearch output..
Have you reduced the heap size for logstash by any chance?
Do those files have extra long lines?

**Comment by suyograo** [comment]
Lets move this to https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
