### ISSUE TITLE
Large overhead when logging events because of attribute @lut

### ISSUE THREAD

**Issue by breml** [elastic/logstash#4428]
Logging an event in Logstash could become very, very verbose. 

In some places, Logstash events got logged on warn level, for example if an output plugin is unable to connect to its destination (https://github.com/logstash-plugins/logstash-output-syslog/blob/master/lib/logstash/outputs/syslog.rb#L152).

In this case the whole event object is logged, I guess with the `inspect` method (as far as I can tell in: https://github.com/jordansissel/ruby-cabin/blob/master/lib/cabin/outputs/io.rb#L52).

The logstash event does include an attribute `@lut` (https://github.com/elastic/logstash/blame/master/logstash-core-event/lib/logstash/util/accessors.rb#L48) in the accessors class, which is used to perform direct access to the containing object for a key (description from the comment). In my opinion this information as almost never used, if one is checking the Logstash log for errors.

If the Logstash event does include a lot keys and has a flat structure, for every containing key nearly the whole event is printed again, which results in a lot redundant information, which makes reading the log file much harder and in most cases does not provide any useful information.

In our case, an Event with around 40 fields/keys produces a single log line with ~95KB. That is huge.

Is there a way to send an event in a "smaller" representation to the log? Are there any recommendations? Is it possible to modify the logging facility of Logstash to reduce the output automatically?

May also be related to: #3101

**Comment by breml** [comment]
One way to resolve this would be to implement `inspect` in `accessors` (https://github.com/elastic/logstash/blame/master/logstash-core-event/lib/logstash/util/accessors.rb#L38).

Example:

    def inspect
      return nil
    end

But I can not evaluate the consequences of this change. Because `inspect` is supposed to return a human-readable representation of the object, the consequences are may be minor.

**Comment by colinsurprenant** [comment]
+1 absolutely and I think your suggestion to override `Accessors#inspect` is good, either that or `Event#inspect` to exclude dumping `@accessors`. There could be valid cases of wanting to support `Accessors#inspect` and expect meaningful output (?) but I can hardly see when calling `Event#inspect` we'd want to see the `@accessors` internals. 

Thanks for the heads up, I've been wanting to fix that for a while. 

It's an easy fix either way so I'd vote to aim for 2.3 for this.

**Comment by colinsurprenant** [comment]
ahah, hold on a minute :D there is actually an interesting second degree to this problem! 

First: forget about my 2.3 fix proposal in my previous comment - my brain was still asleep while writing it. in 2.3 we are actually using a completely new `Event` implementation rewritten in Java and `Event#inspect` now basically falls back to `Event#to_s`.

In version < 2.3, using a config with `filter{ruby {code => "@logger.error(:event => event)"}}` yielded 
```
{:level=>:error, :event=>#<LogStash::Event:0x2d0e4385 @metadata_accessors=#<LogStash::Util::Accessors:0x6ae1458f @store={}, @lut={}>, @cancelled=false, @data={"message"=>"toto", "@version"=>"1", "@timestamp"=>"2016-01-27T21:44:57.659Z", "host"=>"colin-mbp13r.local"}, @metadata={}, @accessors=#<LogStash::Util::Accessors:0x4d21bcca @store={"message"=>"toto", "@version"=>"1", "@timestamp"=>"2016-01-27T21:44:57.659Z", "host"=>"colin-mbp13r.local"}, @lut={"host"=>[{"message"=>"toto", "@version"=>"1", "@timestamp"=>"2016-01-27T21:44:57.659Z", "host"=>"colin-mbp13r.local"}, "host"]}>>}
```

... which is what you described, `@accessors` and `@lut` and actual event data output 3 times. Now, in 2.3+ (master) this is what you get:

```
 {:level=>:error, :event=>2016-01-27T21:48:10.791Z colin-mbp13r.local toto}
```

So, the good news is that the fix for your problem is in fact already in 2.3 :D

The bad news is, we need a better `Event#inspect` implementation in the Java Event :P

**Comment by colinsurprenant** [comment]
@breml let us know if this is good enough for you and we can close this issue? We will followup in #4586 for the upcoming java event implementation.

**Comment by breml** [comment]
@colinsurprenant That's fine for me. We resolved our immediate problem directly within our version of https://github.com/logstash-plugins/logstast-output-syslog at https://github.com/u-s-p/logstash-output-syslog/blob/master-usp/lib/logstash/outputs/syslog.rb#L188. We are in need of our own version of this logstash plugin, because some of our pull request haven't been merged so far.

**Comment by colinsurprenant** [comment]
@breml ok, perfect, thanks.
