### ISSUE TITLE
New jruby-openssl release clashes with lock file in 2.2 branch

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#4437]
jruby-openssl is [locked to 0.9.12 in 2.2 branch](https://github.com/elastic/logstash/blob/902e127d710550f0ec33e4554021cd0f5c7a63c3/Gemfile.jruby-1.9.lock#L138)

now that this gem has been updated to 0.9.13 running:

`rake bootstrap && rake test:install-default && bin/plugin uninstall logstash-input-beats`

throws an error during `bin/plugin uninstall`:

```
[plugin:install-development-dependencies] Installing development dependencies of all installed plugins
Installing logstash-devutils, logstash-filter-mutate, flores, rspec, stud, pry, rspec-wait, logstash-codec-json, ftw, logstash-output-elasticsearch, gmetric, gelf, timecop, jdbc-derby, docker-api, logstash-codec-plain, simplecov, coveralls, longshoreman, rumbster, logstash-input-generator, logstash-filter-kv, logstash-filter-ruby, sinatra, webrick, poseidon, logstash-output-lumberjack, webmock, logstash-codec-line
Installation successful
Gem::LoadError: You have already activated jruby-openssl 0.9.13, but your Gemfile requires jruby-openssl 0.9.12. Prepending `bundle exec` to your command may solve this.
    setup at /Users/ph/es/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
    each at org/jruby/RubyArray.java:1613
```

A potential fix for this is just bumping the version in the lock file

**Comment by ph** [comment]
I have experienced this, so we need to lock `jruby-openssl` to .13

**Comment by purbon** [comment]
+1 on locking to a version we know works.

- purbon

On Fri, Jan 8, 2016 at 5:17 PM, Pier-Hugues Pellerin <
notifications@github.com> wrote:

> I have experienced this, so we need to lock jruby-openssl to .13
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/4437#issuecomment-170044735>.
>



-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by ph** [comment]
So probably wiser to set it to `.12` instead of the brand new release of `.13`, WDYT?

**Comment by jsvd** [comment]
one detail here is that somewhere the jruby-openssl is not being locked to whatever is specified in the lock file, maybe in the vendored jruby's system gems?

Is strange that, by the end of "rake bootstrap", jruby-openssl is locked to .12 in the lock file, but there's a .13 installed somewhere

this should probably be investigated too.

**Comment by ph** [comment]
`logstash-core`, define an open dependency on jruby-openssl.

Jruby, doesn't the gem, they have a virtual dependency on it.

**Comment by suyograo** [comment]
@jsvd also ran into an issue where an plugin update on 2.1.1 updates the vendored jruby openssl to 0.9.13 which is bad. The best approach now is to pin the logstash-core dependency to released version

**Comment by colinsurprenant** [comment]
+1 on pinning openssl version in logstash-core.gemspec.

**Comment by neowulf33** [comment]
I am running into this issue with v2.2.0. How should I fix this issue in my current installation?

**Comment by suyograo** [comment]
@neowulf33 can you describe in detail steps you took to get this issue?

**Comment by neowulf33** [comment]
Thank you for the quick response.

1. I have upgraded my installation to v2.2.0. 
2. I then get the following error when I am listing the plugins:
```
$ sudo /opt/logstash/bin/plugin list
Gem::LoadError: You have already activated jruby-openssl 0.9.15, but your Gemfile requires jruby-openssl 0.9.13. Prepending `bundle exec` to your command may solve this.
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
     each at org/jruby/RubyArray.java:1613
     each at /opt/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
   setup! at /opt/logstash/lib/bootstrap/bundler.rb:64
  execute at /opt/logstash/lib/pluginmanager/list.rb:17
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
  execute at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
   (root) at /opt/logstash/lib/pluginmanager/main.rb:41
```

**Comment by suyograo** [comment]
@neowulf33 did you try an update before this command? Or it was just upgrade LS using deb/rpm packages and then `/opt/logstash/bin/plugin list` ?

**Comment by neowulf33** [comment]
I have been using the rpm package. This issue is indeed fixed after executing `bin/plugin update`. Thanks!

**Comment by suyograo** [comment]
@neowulf33 you don't have to do `bin/plugin update` to *fix* this.. Its weird you were getting this issue right after an upgrade using RPM. We'll debug on our side, but hope we've unblocked you. Can you also tell us: 1) what version you upgraded *from*? 2) Java version?

**Comment by neowulf33** [comment]
I see.

Upgraded RPM package from 2.1.0 to 2.2.0

```
$ /usr/bin/java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (amzn-2.6.1.3.61.amzn1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

**Comment by shaharmor** [comment]
I can verify that it happened to me too.

Updated logstash using `apt-get` and now getting this error:
```bash
/opt/logstash# ./bin/plugin list
Gem::LoadError: You have already activated jruby-openssl 0.9.15, but your Gemfile requires jruby-openssl 0.9.13. Prepending `bundle exec` to your command may solve this.
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
     each at org/jruby/RubyArray.java:1613
     each at /opt/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
   setup! at /opt/logstash/lib/bootstrap/bundler.rb:64
  execute at /opt/logstash/lib/pluginmanager/list.rb:17
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
  execute at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
   (root) at /opt/logstash/lib/pluginmanager/main.rb:41
```

Upgraded from 2.1.1 to 2.2.0

```
/usr/bin/java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```

**Comment by veve90** [comment]
I had the same error. I did a  /opt/logstash/bin/plugin update and now it's working :)
