### ISSUE TITLE
bin/plugin pack on Windows creates zip only

### ISSUE THREAD

**Issue by pickypg** [elastic/logstash#4439]
While attempting to use the `bin/plugin.bat pack --tgz` feature from Logstash 2.1.0 running on Windows, I ended up building a zip file unexpectedly.

``` shell
$ bin/plugin.bat pack --tgz
io/console not supported; tty will not be manipulated
Packaging plugins for offline usage
Generated at C:/Users/earle/Downloads/elastic/logstash-2.1.0/plugins_package.zip
```

It's not the end of the world as the zip is still usable, but it was certainly a surprise.

**Comment by purbon** [comment]
Good catch @pickypg, this is actually a bug because of the way https://github.com/elastic/logstash/blob/master/lib/pluginmanager/pack_command.rb#L6-L8 handles the selection of the utility to compress.

**Comment by janbernhardt** [comment]
+1

**Comment by ph** [comment]
The pack/unpack command are now deprecated since https://github.com/elastic/logstash/pull/6404.

I understand it can cause some confusion, but I am more in favor of closing this since the command will go away and its not the preferred way to for offline.
