### ISSUE TITLE
Design: Metrics API endpoints for Logstash

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4446]
As part of the ongoing metrics implementation (#3908), this issue specs all the user facing endpoints for Phase 1.  
Aim is to be consistent as much as possible with ES API, so user experience is similar across products.

### 1. Root resource

Request

``` GET /  ```

Response

```
{
   "hostname": "skywalker",
    "version" : {
        "number" : "2.1.0",
        "build_hash" : "72cd1f1a3eee09505e036106146dc1949dc5dc87"
    }
  }
```

**Note:** For phase 1, we will only have a single pipeline (metrics is an internal pipeline and will not be exposed) so this API will only show `main`

### 2. Stats Info

We would like to slice viewing of runtime stats under 2 dimensions: 
* Node level: These are instance level stats. Logstash is not clustered today, and nodes do not communicate with other nodes. Hence the name `_node` instead of `_nodes`. The action `_nodes` imply communication with other nodes in a cluster.
* Pipeline level: When multiple pipelines are supported by a single Logstash instance, you can view stats per pipeline. 

```
/_node/stats/<types>
/_pipelines/stats/<types>
```
`types` are like events, jvm, os

**Filtering by pipeline: (not for Phase 1)**

`/_pipelines/apache, metric_beat/stats/<types>`

This will show stats for pipelines named `apache` *and* `metric_beat`.

#### 2.1 Events data

Get events information since startup. 

Request

``` GET /_node/stats/events  ```

Response

```
{
    "events": {
        "in": 91,
        "filtered": 91,
        "out": 91
    }
}
```

#### 2.2 JVM data

JVM stats, garbage collection

Request

``` GET /_stats/jvm ```

Response

```
"jvm":{  
   "timestamp":1453233447702,
   "uptime_in_millis":211125811,
   "mem":{  
      "heap_used_in_bytes":58442576,
      "heap_used_percent":5,
      "heap_committed_in_bytes":259522560,
      "heap_max_in_bytes":1037959168,
      "non_heap_used_in_bytes":56332256,
      "non_heap_committed_in_bytes":57475072,
      "pools":{  
         "young":{  
            "used_in_bytes":41672000,
            "max_in_bytes":286326784,
            "peak_used_in_bytes":71630848,
            "peak_max_in_bytes":286326784
         },
         "survivor":{  
            "used_in_bytes":260552,
            "max_in_bytes":35782656,
            "peak_used_in_bytes":8912896,
            "peak_max_in_bytes":35782656
         },
         "old":{  
            "used_in_bytes":16510024,
            "max_in_bytes":715849728,
            "peak_used_in_bytes":16510024,
            "peak_max_in_bytes":715849728
         }
      }
   }

```

### 3. Hot Threads

Request

``` GET /_node/hot_threads  ```

Default response is JSON. `?human` provides human readable format.

Response
```
::: {Ringo Kid}{Gv3UrzR3SqmPQIgfG4qJMA}{127.0.0.1}{127.0.0.1:9300}
   Hot threads at 2016-01-13T16:55:49.988Z, interval=500ms, busiestThreads=3, ignoreIdleThreads=true:
   
    0.0% (216micros out of 500ms) cpu usage by thread 'elasticsearch[Ringo Kid][transport_client_timer][T#1]{Hashed wheel timer #1}'
     10/10 snapshots sharing following 5 elements
       java.lang.Thread.sleep(Native Method)
       org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:445)
       org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:364)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       java.lang.Thread.run(Thread.java:745)

    0.0% (216micros out of 500ms) cpu usage by thread 'elasticsearch[Ringo Kid][transport_client_timer][T#1]{Hashed wheel timer #1}'
     10/10 snapshots sharing following 5 elements
       java.lang.Thread.sleep(Native Method)
       org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:445)
       org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:364)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       java.lang.Thread.run(Thread.java:745)
```

```
uyog@machine:~/ws/elastic/ls_plugins/logstash-output-elasticsearch (master)$ curl localhost:9600/_node/hot_threads?pretty
{
  "hostname" : "Suyogs-MBP-2",
  "time" : "2016-03-08T17:58:18-08:00",
  "busiest_threads" : 3,
  "threads" : [ {
    "name" : "LogStash::Runner",
    "percent_of_cpu_time" : 16.93,
    "state" : "timed_waiting",
    "traces" : "\t\tjava.lang.Object.wait(Native Method)\n\t\tjava.lang.Thread.join(Thread.java:1253)\n\t\torg.jruby.internal.runtime.NativeThread.join(NativeThread.java:75)\n\t\torg.jruby.RubyThread.join(RubyThread.java:697)\n\t\torg.jruby.RubyThread$INVOKER$i$0$1$join.call(RubyThread$INVOKER$i$0$1$join.gen)\n\t\torg.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:663)\n\t\torg.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)\n\t\torg.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)\n\t\torg.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)\n\t\torg.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)\n"
  }, {
    "name" : "Api Webserver",
    "percent_of_cpu_time" : 0.39,
    "state" : "timed_waiting",
    "traces" : "\t\tjava.lang.Object.wait(Native Method)\n\t\tjava.lang.Thread.join(Thread.java:1253)\n\t\torg.jruby.internal.runtime.NativeThread.join(NativeThread.java:75)\n\t\torg.jruby.RubyThread.join(RubyThread.java:697)\n\t\torg.jruby.RubyThread$INVOKER$i$0$1$join.call(RubyThread$INVOKER$i$0$1$join.gen)\n\t\torg.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:663)\n\t\torg.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)\n\t\torg.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)\n\t\torg.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)\n\t\torg.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)\n"
  }, {
    "name" : "Ruby-0-Thread-13",
    "percent_of_cpu_time" : 0.15,
    "state" : "timed_waiting",
    "path" : "/Users/suyog/ws/elastic/logstash/build/logstash-3.0.0.dev/vendor/local_gems/f5685da5/logstash-core-3.0.0.dev-java/lib/logstash/pipeline.rb:496",
    "traces" : "\t\tjava.lang.Object.wait(Native Method)\n\t\torg.jruby.RubyThread.sleep(RubyThread.java:1002)\n\t\torg.jruby.RubyKernel.sleep(RubyKernel.java:803)\n\t\torg.jruby.RubyKernel$INVOKER$s$0$1$sleep.call(RubyKernel$INVOKER$s$0$1$sleep.gen)\n\t\torg.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:667)\n\t\torg.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)\n\t\torg.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)\n\t\torg.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)\n\t\torg.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)\n\t\torg.jruby.ast.BlockNode.interpret(BlockNode.java:71)\n"
  } ]
```

### Common Options

Just like ES supports common options, following will be supported:

* `pretty`: When appending ?pretty=true to any request made, the JSON returned will be pretty formatted
* `human`: Statistics are returned in a format suitable for humans (eg `"exists_time": "1h"` or `"size": "1kb"`)

**Comment by ph** [comment]
Look good to me for the first draft, just a small note can we use `?pretty` instead of `?v` I think its clearer and at the same thing alligned with the same arguments for the elasticsearch api.

**Comment by purbon** [comment]
@ph makes sense to me, I agree with using ```?pretty```

**Comment by ph** [comment]
Oh @purbon ! Good job.

When you update an issue description please post a new comments so I get a notification, I almost missed that!

**Comment by suyograo** [comment]
Thanks @purbon. Couple of points:
* I think we should introduce 2 top level action names which will help, looking forward into the LS clustering functionality:
  * `_nodes` is similar to ES `_nodes` which is basically API calls filtered by node name. A node in ES is analogous to a node in LS. If you are issuing this request to a single LS instance, you would have - `GET localhost:9200/_nodes/stats/` to get node/instance level information. If running as a cluster, you can issue: `GET localhost:9400/_nodes/{node_name1, node_name2}/stats/`
  * `_pipeline` action will filter stats info based on multiple pipelines running in a single LS node. By default, we run a single pipeline, so we can omit the Pipeline ID. So you issue: `GET localhost:9400/_pipeline/stats/. Filtered by a particular pipeline, `GET localhost:9400/_pipeline/{pipeline_id}/stats/`

```
GET \
```

```
{
    "version": "3.0.0.dev",
    "hostname": "skywalker",
    "pipelines": {
        "pipeline_01": {
            "status": "ready",
            "uptime_in_millis": 3600000,
            "uptime_as_string": "1h"

        },
```

What is status? Where do we store it? IMO we should only add field names we are clear about. Adding new field are always easy, renaming/removing will break compatibility. So lets be careful here.


`GET /_stats/events`

```
{
    "events_since_startup": {
        "ingested": 91,
        "emitted": 91,
        "dropped": 91

    }
}
```
`events_since_startup` rename to `events`. And maybe just `in`, `out`, `dropped` to make it simple?

Thoughts?

**Comment by purbon** [comment]
I like the introduction of ```_nodes``` API, however I'm on the fence for a resource that works like ```GET localhost:9400/_nodes/{node_name1, node_name2}/stats/``` I would like to understand the best way to implement in a good way a resource like this, not sure this one is a proper way.

The introduction of a ```_pipelines``` API is planned, but we decided first to finish the ones defined in this example and then move one with the ```_plugins``` and ```_pipelines``` ones. Are you proposing to include ```_pipelines``` in the first set of resources? (see the issue description)

re: status. Status is the state of the pipeline, as we have in the code right now will be running, stopped, etc. Might include stale, paused or restarted in feature pipeline implementation. This information is already available in the pipeline class.

**Comment by purbon** [comment]
re: ```GET /_stats/events```

I'm good with 

```
{
    "events": {
        "in": 91,
        "out": 91,
        "dropped": 91

    }
}
```

The only reason to have ```_since_startup``` would be incase we want to show another events accounting, but not sure we will ever do that. What do you think? and also it would require a different schema in my opinion.

**Comment by ph** [comment]
@suyograo I have a small question concerning this resources

`GET localhost:9400/_nodes/{node_name1, node_name2}/stats` Do the clustering have already a communication channel in place? I though nodes where not able to communication with each other?

**Comment by ph** [comment]
@suyograo My understanding of the `nodes` if for future improvements that we take into consideration right now.

**Comment by acchen97** [comment]
I agree with introducing a _nodes top level resource, similar to ES, and focusing on that for Phase 1.  We can we make _pipelines (and _plugins) later phase items?  My understanding was multiple pipelines is currently only for metrics, and we can expose this later when we expose the feature for external consumption (same with plugin specific metrics).

For "status", we can probably leave it out for now as it'll be either up or down at the node level.  It may make more sense to introduce that metric as a "cluster" level item when we get there.

Regarding 'GET localhost:9400/_nodes/{node_name1, node_name2}/stats', it's good to proactively architect that structuring to query across nodes, but initially how about something like 'GET localhost:9400/_nodes/_local/stats' to get the local node stats?

**Comment by andrewvc** [comment]
There's complexity in defining 'online nodes'. I'd love to sync with everyone here + @jsvd for a meeting regarding this. We need to have the node idea cross across metrics/cluster of course, but where that exact point is will have some big ramifications.

**Comment by purbon** [comment]
I foresee a lot of challenges to properly introduce the ```_nodes``` api, specially as I understand (like @ph) that nodes don't talk to each other this days. Saying that, I see the benefit of adding this API only for the current node.

If we are going with the same API resource as elasticsearch, I found https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.html#cluster-nodes so I think we should do the same.

For now I think we can simply go for the full set of api, I tested, and confirmed, the elasticsearch api,  when the ```nodeID``` does not exist, data for this node is not returned. So we could only implement fetching information for localhost and ignore the rest. Then in next phases we can add info for other nodes in the cluster.

what do you think?

**Comment by suyograo** [comment]
@purbon also, `uptime_in_millis` should be default, and `uptime` (not `uptime_as_string`) should be returned when `human` is set to `true`. I changed it in your descriptions. Lets be consistent with ES as much as possible so it provides a common user experience across our products.

**Comment by suyograo** [comment]
@purbon @ph Edited directly from the discussion we had this morning.

**Comment by ph** [comment]
Excellent

**Comment by purbon** [comment]
good, @suyograo about the ```GET /_stats/jvm``` can we make it ```GET /_stats/jvm/memory``` ? and  I think it should be ```GET _nodes/_stats/jvm/memory``` to be consistent. What do you think?

**Comment by suyograo** [comment]
@purbon why `jvm` will include memory as response, why do we need to make it a resource? And please read the description again as to why it is `_node` and not `_nodes`

**Comment by purbon** [comment]
@suyograo, sorry typo! I meant to make it ```_node``` . I like the idea of having an specific resource for memory, or a filter like we have for other things so people can select only the things they are willing to get, not more information. For the JVM for example we could have more things showed like IO data, GC methods used, etc...

what do you think?

**Comment by suyograo** [comment]
@purbon `GET _node/stats/jvm/memory` sounds good. `GET _node/stats/jvm` should return the entire jvm stats while we can also filter by individual subtype

**Comment by purbon** [comment]
makes sense to me! thanks man!

- purbon

**Comment by clintongormley** [comment]
Hi all - @suyograo asked me to take a look and provide some feedback.

**`GET /`**

I'd keep this a simple small response.  In the ES clients we map this to the `info()` method.  Are you sure you want to have the pipeline status/uptime in there? Seems like it would fit better in the pipeline stats API, not least of all because then you'll be able to filter by pipeline ID.

**`/_node` vs `/_nodes`**

Having singular and plural versions of the API gets confusing later on.  Given that you're moving towards having multiple nodes in the cluster, I'd probably opt for the plural version.  As @suyograo says, the default incantation `GET _nodes/stats`  will return the stats from all nodes (ie in the current situation, just the local one).  I realise it'll look funny at first, but I think you'll be glad when clustering is implemented.

Then `GET _nodes/_local/stats` or `GET _nodes/foo*/stats` etc can be used later on.

**`events_since_startup` vs `events`**

Almost all stats will be since startup, so I'd prefer `events`.

**`GET _node/stats/jvm/memory`**

I'd perhaps leave that last level for later on... We've never had anybody ask us to filter down to individual metrics.

Another tip, if you're going to have something like `avg_load:` then rather go for named keys `{ "1m": 1.0, "5m", 1.0, "15m": 1.0 }`  instead of arrays `[1.0, 1.0, 1.0]` - they work better when indexing into ES.
