### ISSUE TITLE
Internal: Filter metrics by namespaces

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4461]
As a consumer of the metrics collector I aim to get meaningful namespaces that let me select and fetch data easy. For now we've:

* root.base.events_in
* root.base.events_filtered

I would propose to have something that matches more close, semantically speaking the resources defined for #4446, so we can make something like.

* root.stats.events, to get all events information
* root.stats.jvm, to get all jvm information
* root.stats.networking, to get all events information.

I also propose to rename root to a word with a bit more context, what do you think? might be something like metrics? or logstash? then we could have namespaces like:

* logstash.stats.events
* logstash.stats.jvm 

what do you think?

**Comment by ph** [comment]
All your proposition make a lot of sense to me, I think I will go with `logstash.*`
So for the main stats we will something like this.

`logstash.stats.events.*`

**Comment by purbon** [comment]
works for me! perfect!

**Comment by ph** [comment]
Like your proposition, whats exposed vs what we collect we should try to have a 1:1 mapping as much as possible, so this will make the web api more like a data format transform than an actual logic.

**Comment by purbon** [comment]
+1, but we should be careful not to take this as law, still important we have to send this data to other possible consumers, but the collector and store could be used to transform this data.

**Comment by suyograo** [comment]
TO clarify: who will use the filtering? is it for internal use?

For the API, I assume the filtering to be similar to ES. Like: `http://localhost:9200/_stats/os`

**Comment by purbon** [comment]
Internally the way the metrics collector works is by having a "tree" of maps, so you can fetch metrics, grouped by namespaces. This requirements is a due to have a simple, and semantically correct way of querying/fetching metrics internally. 

for example.

```logstash.stats.events``` should give us all events information, while ```logstash.stats.events.in``` for example shuold give us only ingested events per second, for example.

**Comment by ph** [comment]
@purbon I dont think we need "logstash" we can start at "stats" we already are in logstash, I would fine it a bit redundant.

So "stats" will replace "root" in your case.

**Comment by purbon** [comment]
@ph I agree, only motivation to have something before is in case we would have something like 

* A.B.C
* D.B.C

do we forecast that?

**Comment by ph** [comment]
@purbon I don't think we forecast that, but nothing would prevent to have a new keys at the same level of stats

**Comment by purbon** [comment]
Good with that.

/purbon

**Comment by ph** [comment]
Lets take a pipeline named "main01", when an events comes through it need to increments two counters.

- One representing the total number of events in the systems, **stats.events.in**
- One representing the  total number of events for this specific pipelines **stats.pipelines.main01.events.in**

The current code doesn't allow this flexibility, this is the change I propose.

Inside the pipeline and our main code base we will use the Metric library that accept the namespace as the first arguments. This will give more flexibility to us to correctly generate the right metric.

so instead of calling
```ruby
metric.increment(:in)
# we will do
metric.increment([:stats, :events], :in)
```

This make the code more explicit for us with a gain in flexibility.
For the plugin authors I think we should still have the namespaced managed by us.

**Comment by purbon** [comment]
@ph can ```stats.events.in``` be an aggregation of several ```stats.pipelines.main01.events.in``` ? if don't keep aggregated numbers we are simplifying the way we store/fetch elements, what do you think? also reducing some internal data store size.

**Comment by purbon** [comment]
> Inside the pipeline and our main code base we will use the Metric library that accept the namespace as the first arguments. This will give more flexibility to us to correctly generate the right metric.

this change is good as it give you a ton more of flexibility and also give metrics users more power on how to store data internally. I agree plugin authors should not care about internal namespaces, might be having some helpers for them will work? 

For helpers I mean some methods they can simply call when willing to increment a given api. On the other side, could it happen that a plugin author is willing to create their own metric? how do we handle this? I guess one good solution would be to preset a namespace that identifies his plugin, what do you think?

**Comment by ph** [comment]
@purbon I did some fiddling yesterday about "stats.events.in be an aggregation of several" but I havent found a nice way to declare it in the code. :(

This small refactor takes a bit more time that I had expected first.

**Comment by purbon** [comment]
@ph don't worry about, for now having no aggregations I guess is not a big deal ... I mean we can always aggregate in other layers, right?

**Comment by ph** [comment]
For the plugins author, I think what we had was already covering this case, this is how I see it.


At the initialization time of the plugin we pass a metric object with an already predefined namespaces.

```
named => "stats.pipeline01.plugins.elasticsearchXX"
```

So every newly declared metric will be done bellow this named space.

```
"stats.pipeline01.plugins.elasticsearchXX.errors_count"
"stats.pipeline01.plugins.elasticsearchXX.retry_count"
```

**Comment by ph** [comment]
@purbon Either we do it dynamically, which I don't really like.

```
stats.pipeline01.events.in
stats.pipeline02.events.in
```
Or we have 2 counters, one for the global rate and one for each pipeline.

**Comment by ph** [comment]
implement each and get which allow filtering of the metrics.
