### ISSUE TITLE
logstash 2.0 doesn't log failure to create new index as a result of mapping error

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#4475]
there has been a report that if an index request that results in a creation of an index fails due to a mapping conflict with the template no error is logged and logstash discards the event.

this was reported in 2.0 but hasn't been confirmed or checked if fixed in recent 2.x

**Comment by seang-es** [comment]
We have a confirmed report of this happening with Logstash 2.1.2.  Mapping contained "path":"full" in the template, so new indices could not be created.  This happened silently and events were dropped.

**Comment by purbon** [comment]
Moving this to the logstash-output-elasticsearch as this is logic that should be there.
