### ISSUE TITLE
MetricType Gauge

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4488]
Currently the metric collector only support the Counter type, we need to add support for a Gauge Type to support adhoc values, theses values could be:

- The size of queue 
- an eviction cache
- an uptime
- Number of threads
- a status?

**Comment by ph** [comment]
cc @purbon Might be useful for the jvm stats collecting?

**Comment by purbon** [comment]
sure, go ahead! for jvm collecting is mandatory as all values are gauged
