### ISSUE TITLE
Do not override existing (and newer) version of plugins

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#4491]
This will be a non-trivial enhancement since we do not have any state mechanism today to deal with existing/currently installed plugins.  

Filing a use case from the field:

The request for Logstash to detect when a local plugin is newer than the one it has. In these cases, do not override it.

> Use case 
> I upgraded to kafka plugin 2.0.3 to get the cpu fix. I finally got around to installing logstash 2.1.1 (with the rest of the stack) and noticed that the logstash install overwrote the kafka plugin with 2.0.2. So i had to install again. It would be really nice if we can do some checking so extra work is not needed.

**Comment by jordansissel** [comment]
At this time, when you upgrade, all plugin version information is destroyed. You'll have to install desired plugins after every logstash upgrade.
