### ISSUE TITLE
Upgraded to LS 2.1.1 and now getting JSON filter errors

### ISSUE THREAD

**Issue by jbehrends** [elastic/logstash#4507]
I just upgraded my install from 1.5.5 to 2.1.1.

I am now seeing the following messages in my logstash logs:

```
exception=>java.lang.IllegalStateException: Spill-over slots in symbol table with 4095 entries, hash area of 2048 slots is now full (all 256 slots -- suspect a DoS attack based on hash collisions. You can disable the check via `JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW`, :level=>:warn}
OR
exception=>java.lang.ArrayIndexOutOfBoundsException, :level=>:warn}
```

The events that are throwing this error are all running through this filter:

```
      json {
        source       => "message"
        target       => "amq"
      }
```

The output for these events is ES, and when i look in Kibana, the events get there, but none of the JSON is parsed like it was previous to the upgrade.  The events are also tagged with "_jsonparsefailure".

Any ideas?

**Comment by alexanderilyin** [comment]
Have similar problem. I have cluster of 3 {{logstash 2.1.1}} servers and one of them shows those errors:

```
{
    :timestamp=>"2016-01-25T18:51:21.516000-0800", 
    :message=>"Trouble parsing json", 
    :source=>"message", 
    :raw=>"{\"timestamp\":1453776676,\"type\":\"php_fpm_status\",\"php_fpm_status\":{\"process_manager\":\"dynamic\",\"start_time\":1453765811,\"start_since\":10865,\"accepted_conn\":7375,\"listen_queue\":0,\"max_listen_queue\":0,\"listen_queue_len\":0,\"idle_processes\":6,\"active_processes\":1,\"total_processes\":7,\"max_active_processes\":3,\"max_children_reached\":0,\"slow_requests\":2}}", 
    :exception=>java.lang.ArrayIndexOutOfBoundsException, 
    :level=>:warn
}
```

but there is no problems with JSON itself, also other LS instances process similar messages with no problems and as result events processed through that server get tagged with {{_jsonparsefailure}}.

I've restarted LS and problem gone.

**Comment by guyboertje** [comment]
I had a look at this a few days ago in the Jackson code.

It seems as if there is some caching of internally symbolised field names as an optimisation and this cache is full.  Restarting LS will help but the solution is a new version of JrJackson that disables the full check.

**Comment by ctramnitz** [comment]
I'm having the same problem with Logstash 1.5.6, so this is not 2.1.1 specific. It happens with a json-ized version of ESXi logs. Is there a way to pass a modified "JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW" from Logstash to Jackson?

**Comment by guyboertje** [comment]
@ctramnitz - I will be releasing a new version of JrJackson this week. I have a few more changes to do.
Unfortunately, I was not able to make a test case that failed with and symbol table overflow and passed when I disabled the setting. This means that have to trust that the disabling will fix the problem described here.

**Comment by guyboertje** [comment]
Stale
