### ISSUE TITLE
Apply changes from configuration file without restarting

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4513]
Today, any config changes made to LS pipeline requires a process restart, which is not ideal. Plan is to implement a feature which would track config file for changes and restart the pipeline (same process) with updated changes. This feature can be enabled by passing a CLI option `--auto_reload` with `--reload_interval` which controls how often LS should check the config files for changes.

**Comment by djschny** [comment]
For service oriented apps I wrote in the past that had this behavior, I expanded to include the refreshing from any URL, that way one easy way to get centralized config management was via a web server or similar. For example:
* file://
* http://
* https://
* ftp://

If you're in Java land, accomplishing this is pretty easy too using something similar to `new URL("<my_config_url>").openStream()` and regardless of what protocol you're given a stream to read from.

**Comment by jsvd** [comment]
@djschny we support the same in logstash through open-uri https://github.com/elastic/logstash/pull/4520/files#diff-5e1ebf137d1eab8a085fa7c1c4a6fd2cR37
However we're restricting to https and file (for no go reason).

**Comment by jsvd** [comment]
merged in master:

Branch | Commits
-------|--------
master | a90ed32d6d49d6150b23109c69e7ff6be3016d0f, e38d815ecb57153ef409abfe7bae6c2af0a177c6, 34ed3c34758eb0c280882ee3f34b13a9a7048bad, 7ee5038ccf8f93b54f96d12d6247a79e9405a14d, e32f732dba9e73e718fc25b0490e8f547d05ba93, 7d8d6e4c7ad088026bcfb0e6392d6c8e994dd365

I'll open a new PR to add this to 2.x since the branches have greatly diverged

**Comment by suyograo** [comment]
@jsvd great stuff

**Comment by lawre** [comment]
How does the dynamic reload work with systemd service?  I perused /etc/sysconfig/logstash and saw no variables corresponding to 'auto_reload' or 'reload_interval'

**Comment by jsvd** [comment]
in `#LS_OPTS=""` you can set `LS_OPTS="-r"` to have auto reloading

**Comment by jsvd** [comment]
merged in 2.x

Branch | Commits
-------|--------
2.x | 00995378682e90ff50eb3ed244838e9530997294
