### ISSUE TITLE
Features for v2.3

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4515]
- [x] Enable [Java Event](https://github.com/elastic/logstash/issues/4191) as default: https://github.com/elastic/logstash/issues/4480
- [x] Apply configuration changes from file without restarting https://github.com/elastic/logstash/issues/4513

**Comment by suyograo** [comment]
Test

**Comment by jordansissel** [comment]
test

**Comment by colinsurprenant** [comment]
merging in master the java event default per  #4494 & #4563

**Comment by driverpt** [comment]
Can you publish logstash-core-event-java artifact to Maven Central?

It would be cool to develop pure-java libraries receiving the Event object directly.

Currently we're using 

```
def filter(event)
     @instanciated_java_object.doSomeStuffWithEvent(event.to_hash)
end
```

**Comment by suyograo** [comment]
@driverpt Thats a good idea! Opened a new issue to track this https://github.com/elastic/logstash/issues/4902
