### ISSUE TITLE
Define config directories for RPM/DEB install

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#4516]
There's no mention of where various config files live, a la [Elasticsearch's paths](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/setup-dir-layout.html).

It'd be awesome to have this somewhere.

**Comment by jordansissel** [comment]
Elasticsearch has a default configuration path, so documenting that default makes sense. Logstash, however, _requires_ users explicitly specify the path to their Logstash pipeline configuration. What would we document?

**Comment by markwalkom** [comment]
> Logstash, however, requires users explicitly specify the path to their Logstash pipeline configuration. What would we document?

We ship with defaults that are applied when running as a service, that's what we should document :)

**Comment by jordansissel** [comment]
Ahh, fair point - the defaults we ship with rpm and deb packages.

**Comment by markwalkom** [comment]
Yeah, I didn't really make that clear sorry.

**Comment by jordansissel** [comment]
@markwalkom :heart:

**Comment by suyograo** [comment]
@jordansissel @markwalkom this also becomes important with the settings file we plan to introduce in #4401

**Comment by suyograo** [comment]
Fixed in 5.0

**Comment by suyograo** [comment]
https://www.elastic.co/guide/en/logstash/current/dir-layout.html
