### ISSUE TITLE
How to shutdown logstash after I import csv data?

### ISSUE THREAD

**Issue by zhaozhiming** [elastic/logstash#4519]
Hi, I use logstash to import csv file data to es. I use command `bin/logstash` to import csv, but after the data import to es, the logstash instance is always running.   
I don't need logstash always monitoring my csv file, because the file will be deleted after data imported to es.
My question is: How could I shutdown the logstash after I import data to es? Or could reuse the logstash instant to import different csv file?  
I found [the same problem in stackoverflow](http://stackoverflow.com/questions/18299337/how-to-automatically-kill-a-logstash-agent-when-tests-are-done) but the answer seems not work now.   
Please help, Thanks.

**Comment by suyograo** [comment]
@zhaozhiming Logstash was designed to handle continuous streaming data, so it will not automatically shutdown after reading a CSV file. You will have to manually shutdown LS.
