### ISSUE TITLE
./plugin uninstall - broken for offline uninstall

### ISSUE THREAD

**Issue by robgil** [elastic/logstash#4522]
logstash 2.1.1-1
centos6

Typically offline installs are installed with --local. This is fine, but when uninstalling, its trying to verify to the internet again.

```
bin # ./plugin uninstall logstash-output-s3
Uninstalling logstash-output-s3
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/
.....
```

--no-verify doesnt exist

```
bin # ./plugin uninstall --no-verify logstash-output-s3
ERROR: Unrecognised option '--no-verify'

See: 'bin/plugin uninstall --help'
```

**Comment by purbon** [comment]
I can confirm this bug.

**Comment by purbon** [comment]
Thanks a lot for your report, much appreciate it!

**Comment by purbon** [comment]
I think I was able to reproduce this error, looks like uninstall is unable to desice where to fetch data to rebuild care or not, see errors:

```
skywalker% bin/plugin uninstall logstash-input-stdin
Uninstalling logstash-input-stdin
Error NoMethodError, retrying 1/10
undefined method `source_uri' for nil:NilClass
...
Error NoMethodError, retrying 4/10
undefined method `source_uri' for nil:NilClass
WARNING: SSLSocket#session= is not supported
```

this might be due to need to improvement at ```lib/bootstrap/bundler.rb```

```
      ::Bundler::Source::Rubygems.module_exec do
        def cached_gem(spec)
          cached_built_in_gem(spec)
        end
      end
```

the patch we added because we empty the internal bundler cache before packaging (to reduce size). This will need more investigation.

**Comment by purbon** [comment]
The last comment is not related with this issue as is introduced by the new java event gem, sorry for the confusion.

**Comment by ph** [comment]
The remove/uninstall command doesn't require internet now to work corrrectly since this commit:
https://github.com/elastic/logstash/commit/12cfa69215e186bcdf39006e8964f6fcbe769942

We also have integration test on linux using seccomp to assert that.
