### ISSUE TITLE
Maximum Log Rate supported

### ISSUE THREAD

**Issue by Vikran** [elastic/logstash#4532]
Hi team,
Not exactly an issue but i am looking at what is maximum log rate logstash can ingest logs at i have got scenario where log rate will be 10k to 20k /sec has anyone got documented maximum log rate supported  ?

Vik

**Comment by suyograo** [comment]
Hi, can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
