### ISSUE TITLE
persistence reboot

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4537]
This is a design issue about the reboot of the persistence in the context of the new pipeline and the Java Event implementations. 

As been previously discussed, a pluggable persistence architecture would allow different persistence implementations, from using fast local persistence to the use of external storage or messaging systems like Kafka. To move forward with pluggable persistence we first need to properly define and and agree on the persistence interface. The tricky part here is that it will have to accommodate future resiliency (output acking) architecture that will be factored in the pipeline. 

For this, I think we could start by providing a drop-in replacement of the current *wrapped synchronous queue* implementation with a persisting one. This will provide a base implementation to play with and assess performance impact. I believe we could easily provide variable length persistent queuing at this point to. At the same time we should move forward with the design of output acking to move toward at-least-once semantic of the pipeline, with persistence. 

Here's what I propose we divide the work on this:
- [ ] persisting wrapped synchronous queue implementation
- [ ] variable length persisting wrapped synchronous queue
- [ ] output acking and at-least-once pipeline semantic design
- [ ] pluggable persistence interface design with support for at-least-once semantic
- [ ] refactor persistence implementation for pluggable persistence interface

background & reference issues #4254 #3693 #2609 #2606 #2605

**Comment by andrewvc** [comment]
More Todos from our meeting:

  * Make output encoding fully sync (with new API).
  * Build encoders out of encode side of codecs. Make encoders synchronous. Put them in the pipeline, take out of plugins
 * Define queue interface ( add a 'suggested' batch size for inputs based on pipeline batch )
 * Integrate @colinsurprenant 's mmap queue into pipeline
 * Add a plugin level option saying "I don't take codecs"
 * (maybe? TBD) Move decoding codecs to decoders, put on consume side of input queue
 * (maybe? TBD) Add decoding threads

**Comment by jsvd** [comment]
Build encoders out of encode side of codecs.

Does this also mean we're going to deprecate logstash-codec-* and create logstash-encoder-* and logstash-decoder-*? It doesn't make sense to have encoders and codecs with both jobs.

**Comment by suyograo** [comment]
Closing and moving this to https://github.com/elastic/logstash/issues/4767
