### ISSUE TITLE
Encoding/decoding issues in file path with require_relative on Windows

### ISSUE THREAD

**Issue by JoarSvensson** [elastic/logstash#4539]
Unable to run Logstash 2.1.1 on Windows 7, using swedish characters like 'åäö' in the path. It's probably a minor issue since having the above characters in the path is generally not recommended, but might be the reality for some users. It's perhaps more of a JRuby issue really..

```
Errno::ENOENT: No such file or directory - D:/ELK-???/ELK/logstash-2.1.1/lib/boo
tstrap/environment.rb
          realpath at org/jruby/RubyFile.java:847
  require_relative at file:/D:/ELK-Õõ÷/ELK/logstash-2.1.1/vendor/jruby/lib/jruby
.jar!/jruby/kernel19/kernel.rb:11
            (root) at D:\ELK-Õõ÷\ELK\logstash-2.1.1\lib\bootstrap\environment.rb
:6
```

**Comment by ph** [comment]
As a non native english speaker I understand the pain.

But I think this is more a jruby issue than a logstash issue, the file has the correct `UTF-8` header and the require_relative cannot be more minimal.

@JoarSvensson Can you create a small test case outside of logstash and create an issue upstream?

**Comment by liushun207** [comment]
Directory using the file name in English
