### ISSUE TITLE
Delete metrics in the metric store when a pipeline reloaded

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4542]
Currently the `MetricStore` will keep all the collected metrics since Logstash starts, the only way to clean the store is to physically restart Logstash. This is a problem with the introduction of config reloading, which could result in unwanted or inaccurate metric collection.

We collect metrics at two different level: **application** and the **pipeline**.

At the application level, we are gathering information about the jvm, cpu, os and events in/outs.
At the pipeline levels we also gather in/out and in/out of the different plugins.

So this generate a few questions at how we will handle the lifecycle of the metrics:

What should happen when a new config is reloaded inside logstash? Do we think that bringing a new config into Logstash is similar to a restart and we clear all the metrics collected before starting the new pipeline **OR** we clean only the information gathered at the pipeline level? 

In the first version of the metrics we only show that we gather information at the system level it might make more sense to clear the whole collected metrics? Since it will be the only way for people to know on their graph that something restarted logstash? (The spike)

If we consider clearing only the pipeline level we need to make a change to the way the ID of the pipeline are dealt with.. When we start logstash the default pipeline is called `main`, when logstash reload a new config the pipeline created from that config is also named `main`, We need to introduce a UUID to make sure no 2 pipeline can have the same ID in the metric store.

**Comment by ph** [comment]
@jsvd @purbon updated from our discussion, feel free to add more.

**Comment by ph** [comment]
@suyograo @purbon and myself have discussed that issues and we agreed it made more sense to start with a new metric store when the pipeline is reloaded. This is consistent with the behavior we are experiencing when we start logstash with a new config and this is also the behavior of ES concerning the gathered metrics.

**Comment by suyograo** [comment]
Fixed in #4801
