### ISSUE TITLE
unhandled data from input gives no complaints

### ISSUE THREAD

**Issue by KlavsKlavsen** [elastic/logstash#4543]
Hi,

I just had an issue where I had an input { file.. type => foo } and output { if type == 'foo' { .. }}

But type was in file source already (and file was of type json), so logstash didn't override type set in file - hence the output didn't match - and data just disappeared.. much to my dismay :(

After quite some debugging, I figured that out :(

it would be nice if logstash logged, when some input - didn't match any outputs at all.. like "are you sure this isn't an error?" :)

**Comment by jsvd** [comment]
this can be accomplished with a conditional:

input { file.. type => foo }
output { if type == 'foo' { .. } else { file { path => "/tmp/errors.log" } }

I understand your usecase but I can't see how we can add a fallback branch that would satisfy everyone.
Many people use the fact that not all events match the if condition to implicitly drop the "useless" ones.

**Comment by KlavsKlavsen** [comment]
I guess I'll go with the conditional then. my use case is logs.. I don't like logs missing.. :)
