### ISSUE TITLE
Add a Hidden flag to a pipeline

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4549]
Currently we have 2 pipelines running in parallels:
1. `main` logstash config
2. The other one for dealing with metrics

Right now when we access the web api we get the metrics for both pipeline, but in this case the metrics pipeline is just noise since it doesn't record any metrics for itself.

I suggest we add a flag when we initialize a new pipeline `hide` which will be set to false by default.
Since we don't have a  good control over the logger in logstash this flag will allow us to suppressing the double message concerning the workers.

```
Settings: Default pipeline workers: 4
Settings: Default pipeline workers: 4
```

This flag is not exposed to the end user but only for developers interacting with the pipeline.

**Comment by suyograo** [comment]
@ph are you talking about a CLI flag or an internal flag? users should not have to deal with this

**Comment by ph** [comment]
@suyograo only internal flags, I have updated the issue.

**Comment by ph** [comment]
@jsvd I think its related to your work on monitoring.

**Comment by jsvd** [comment]
pipelines already have a system property so they can be treated specially, so we can close this.
