### ISSUE TITLE
Logstash output Elasticsearch installation is wrong

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#4556]
For Logstash `2.1`, the documentation points that to install the shield output for elasticsearch you need to:

```
bin/plugin install logstash-output-elasticsearch-shield
```

However the correct way to install this plugin is to do the following command, which is correct for the documentation version for Logstash `2.0`

```
bin/plugin install logstash-output-elasticsearch_java_shield
```

**Comment by untergeek** [comment]
@gmoskovicz I looked over https://www.elastic.co/guide/en/shield/2.1/logstash.html and it needs a lot of updating, not just the java plugin name. The default elasticsearch output (http protocol) does not require a special shield plugin, as it already contains the keystore and truststore and other SSL options by default.

The `logstash-output-elasticsearch_java_shield` plugin is only for the transport protocol (don't try to use Logstash + node + shield).  The documentation is definitely based on the older releases of Logstash.

**Comment by gmoskovicz** [comment]
@untergeek thanks for looking at this.

> The logstash-output-elasticsearch_java_shield plugin is only for the transport protocol (don't try to use Logstash + node + shield). The documentation is definitely based on the older releases of Logstash.

Correct! I was talking about the `Connecting with Transport protocol` section in the documentation, which is correct for 2.0:

![screen shot 2016-01-22 at 11 32 34](https://cloud.githubusercontent.com/assets/1675411/12513290/ddd91d1e-c0fb-11e5-8230-e495e0782566.png)

**Comment by suyograo** [comment]
Java Plugin is not supported anymore
