### ISSUE TITLE
elasticsearch output is not creating the index with the defined template

### ISSUE THREAD

**Issue by chespix** [elastic/logstash#4557]
Hi.

Im working on a local envrionment with two VMs. One is running elasticserach and the other is running logstash.

For some reason, when logstash creates the index in elasticsearch, the template provided in the logstash config is not being used.  Any idea what may be causing this?

This are the config and log outputs:

logstash.conf

```
input {
        twitter {
                consumer_key => "REDACTED"
                consumer_secret => "REDACTED"
                oauth_token => "REDACTED"
                oauth_token_secret => "REDACTED"
                keywords => ["#DevOps", "#SRE", "#SysOps"]
                locations => "-74,40,-73,41"

                full_tweet => true
        }
}

filter {
}

output {
        elasticsearch {
                hosts  =>  ["10.42.0.101:9200", "10.42.0.102:9200", "10.42.0.103:9200"]
                index => "twitter"
                document_type => "tweet"
                template => "/etc/logstash/template/twitter_template.json"
                template_name => "twitter"
        }
} 
```

twitter_template.json

```
{
  "template": "twitter",
  "order":    1,
  "settings": {
    "number_of_shards": 3
  },
  "mappings": {
    "tweet": {
      "_all": {
        "enabled": true
      },
      "dynamic_templates" : [ {
         "message_field" : {
           "match" : "message",
           "match_mapping_type" : "string",
           "mapping" : {
             "type" : "string", "index" : "analyzed", "omit_norms" : true
           }
         }
       }, {
         "string_fields" : {
           "match" : "*",
           "match_mapping_type" : "string",
           "mapping" : {
             "type" : "string", "index" : "analyzed", "omit_norms" : true,
               "fields" : {
                 "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
               }
           }
         }
       } ],
    "properties": {
        "text": {
          "type": "string"
        },
        "created_at": {
                  "index": "not_analyzed",
          "type": "date",
                  "format": "EEE MMM dd HH:mm:ss Z yyyy",
                  "locale": "US"
        },
                "user": {
          "properties": {
             "created_at": {
                                "index": "not_analyzed",
                "type": "date",
                                "format": "EEE MMM dd HH:mm:ss Z yyyy",
                                "locale": "US"
             },
                        "screen_name": {
                                "index": "not_analyzed",
                                "type": "string"
                        },
             "type": {
                "type": "string"
             }
          }
       },
           "coordinates": {
          "properties": {
             "coordinates": {
                "type": "geo_point"
             },
             "type": {
                "type": "string"
             }
          }
       }
      }
    }
  }
}
```

elasticserach log at index creation (you can see the template is missing)

```
[2016-01-22 13:26:52,070][INFO ][cluster.metadata         ] [el1-es01] [twitter] creating index, cause [auto(bulk api)], templates [], shards [3]/[1], mappings [tweet]
```

thanks

**Comment by jsvd** [comment]
@chespix are there no other errors on elasticsearch side?
can you run logstash with --debug and post the log?

**Comment by chespix** [comment]
@jsvd I've fixed this error by deleting the index filter in Kibana, and recreating it. I still cannot understand why that would fix the issue, but its fixed after that.

**Comment by lucianosousa** [comment]
@chespix do you have the command to execute and delete this index in Kibana?

I'm with the same problem here and cannot fix this.

Thanks any help

**Comment by chespix** [comment]
In the kibana configuration options you can select the index in the left
and will show you options. One of them is to delete the index. Hope this
helps. Sorry I'm not more detailed but not in front of my computer. if
still have issues let me know and I'll send more detailed instructions.


El El vie, 10 de jun de 2016 a las 10:56, Luciano Sousa <
notifications@github.com> escribió:

> @chespix <https://github.com/chespix> do you have the command to execute
> and delete this index in Kibana?
>
> I'm with the same problem here and cannot fix this.
>
> Thanks any help
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/logstash/issues/4557#issuecomment-225205284>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANE-LxSozikeKy7F4dzuwgckiw2e6RX1ks5qKXsugaJpZM4HKW9->
> .
>
-- 
Perdón las faltas, enviado desde mi móvil

**Comment by lucianosousa** [comment]
@chespix thanks. I remove it with a post request on kibana namespace e generate all again

**Comment by Edely** [comment]
I am facing the same problem, so I remove the index filter and then recreated, but it did not solve the problem.

**Comment by Edely** [comment]
Ok. It works now.

So, In my case, what I did was to remove the license plugins folder. I had  installed some plugins that expired already and I had removed them, but I kept receiving this message:

`
[ERROR][license.plugin.core      ]## LICENSE EXPIRED ON  IF YOU HAVE A NEW LICENSE, PLEASE# UPDATE IT. OTHERWISE, PLEASE REACH OUT TO YOUR SUPPORT CONTACT.`

So I just removed the folder license in plugins folder and now it works.

**Comment by aduitsis** [comment]
I'd like to confirm this. I've been using a custom template in an elasticsearch output plugin for months without problem. After I added a second elasticsearch output plugin instance in my logstash.conf, this one with a different custom template, the first template stopped working. It is quite possible that both stopped working, but I cannot positively confirm it at present.

**Comment by talevy** [comment]
@aduitsis you may be overriding the template by name, you need to be sure to use a separate template name when storing the mapping

Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
