### ISSUE TITLE
Milestone warning is displayed when pluginpath is used

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4562]
`--pluginpath ` can be used with LS to load plugins which are not converted into RubyGems yet. LS will output a warning when used with this option:

> 
:message=>"abc plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec.", :level=>:warn} 

This is a benign message, and can be ignored, but we need to remove this warning so it does not confuse users.

**Comment by ph** [comment]
I came around this issue myself when working on metrics, I suggest we move the log level to `debug`?

**Comment by ph** [comment]
And we remove the support for milestone in the next major version.
