### ISSUE TITLE
Installed Gem is not recognized during configtest

### ISSUE THREAD

**Issue by CamJN** [elastic/logstash#4564]
I made a new version of the opentsdb output plugin, and built & installed it locally with `jgem build *.gemspec` and `logstash-plugin install *.gem` all of which succeeded. `logstash-plugin list` includes the plugin in the output, and I can see it in logstash's `Gemfile` and at `/usr/local/Cellar/logstash/2.1.1/libexec/vendor/local_gems/*/logstash-output-*` and it has a `*.gemspec` file at that path.

However when I try and do a configtest on an config file using my output plugin I get the error: `The error reported is: Couldn't find any output plugin named 'opentsdb'. Are you sure this is correct? Trying to load the opentsdb output plugin resulted in this error: no such file to load -- opentsdb`

I've read both of: https://github.com/elastic/logstash/issues/3971 and https://github.com/elastic/logstash/issues/4171 but I'm not depending on a jar with the name of my gem so the solution that worked there doesn't apply to me.

My plugin code is at: https://github.com/CamJN/logstash-output-opentsdb/tree/elasticsearch_inspired 

Other details: jruby(9.0.4.0) and logstash(2.1.1) were installed by homebrew on os x, and java is oracle jdk 1.8.0_72

**Comment by suyograo** [comment]
We don't support jruby 9K yet, only 1.7, but you wouldn't need that for runtime. Just java 8.. can you build your gem using JRuby 1.7?

**Comment by CamJN** [comment]
Rebuilt the gem with jruby 1.7.21, uninstalled previous version with `logstash-plugin uninstall logstash-output-opentsdb` and reinstalled with `logstash-plugin install logstash-output-opentsdb-2.4.0-java.gem`

Still get the same error.

**Comment by CamJN** [comment]
Are there more details needed still?

**Comment by CamJN** [comment]
Some more info:
```
Plugin not defined in namespace, checking for plugin file {:type=>"output", :name=>"opentsdb", :path=>"logstash/outputs/opentsdb", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"76", :method=>"lookup"}
The error reported is: 
  Couldn't find any output plugin named 'opentsdb'. Are you sure this is correct? Trying to load the opentsdb output plugin resulted in this error: no such file to load -- logstash/outputs/opentsdb
/usr/local/Cellar/logstash/2.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/plugin.rb:85:in `lookup'
/usr/local/Cellar/logstash/2.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/pipeline.rb:400:in `plugin'
(eval):243:in `initialize'
org/jruby/RubyKernel.java:1079:in `eval'
/usr/local/Cellar/logstash/2.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/pipeline.rb:57:in `initialize'
/usr/local/Cellar/logstash/2.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/agent.rb:172:in `execute'
/usr/local/Cellar/logstash/2.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/runner.rb:90:in `run'
org/jruby/RubyProc.java:281:in `call'
/usr/local/Cellar/logstash/2.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/runner.rb:95:in `run'
org/jruby/RubyProc.java:281:in `call'
/usr/local/Cellar/logstash/2.2.1/libexec/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'
```

**Comment by jordansissel** [comment]
@CamJN does your plugin show up when you do `bin/plugin list` ? Can you attach the output of `bin/plugin list --verbose | grep opentsdb` ?

**Comment by CamJN** [comment]
`logstash-output-opentsdb (2.4.0)`

**Comment by CamJN** [comment]
I've also switched to just using the jruby included with logstash in the vendor dir to build the gem, just to ensure there's no version incompatibility there.

**Comment by jordansissel** [comment]
Interesting. Can you attach the output of `find vendor/bundle/ -name '*opentsdb*'` ?

**Comment by CamJN** [comment]
nothing there, it's in `vendor/local_gems/0e890cf6/logstash-output-opentsdb-2.4.0`

**Comment by jordansissel** [comment]
doh, that's right! Thanks for the reminder ;P

Can you do the same `find vendor/local_gems/ -name *opentsdb*` ? Mostly, I'm looking to see what files exist there to see if Logstash should find it (or what I could theorize as to the bug). If I don't see anything obvious, I'll try building/installing your plugin myself to see what I can figure out.

**Comment by CamJN** [comment]
```
camdennarzt@SECUR-T:/usr/local/Cellar/logstash/2.2.1/libexec [master L|✔] $ find vendor/local_gems/ -name '*opentsdb*' -o -path '*opentsdb*'
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/CHANGELOG.md
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/CONTRIBUTORS
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/Gemfile
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs/opentsdb
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs/opentsdb/buffer.rb
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs/opentsdb/common.rb
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs/opentsdb/common_configs.rb
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs/opentsdb/http_client.rb
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs/opentsdb/http_client_builder.rb
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/lib/logstash/outputs/opentsdb.rb
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/LICENSE
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/logstash-output-opentsdb.gemspec
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/NOTICE.TXT
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/README.md
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/spec
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/spec/outputs
vendor/local_gems//0e890cf6/logstash-output-opentsdb-2.4.0/spec/outputs/opentsdb_spec.rb
```

**Comment by jordansissel** [comment]
looks ok to me. I'll try your plugin locally. Thanks for the details :)

**Comment by CamJN** [comment]
No problem, thank you so much for looking at this I've been so stumped.

**Comment by CamJN** [comment]
You likely figured this out but just in case, my version of the plugin is at https://github.com/CamJN/logstash-output-opentsdb/tree/elasticsearch_inspired ie the `elasticsearch_inspired` branch.

**Comment by CamJN** [comment]
Any progress?

**Comment by CamJN** [comment]
I found a way to force the http output plugin to generate valid opentsdb output. It would be nice though to be able to use codecs with it. Then I could simplify my config pretty thoroughly.

**Comment by jordansissel** [comment]
I haven't tried yet, it's on my todo list. Sorry for the delays.

**Comment by jordansissel** [comment]
I can confirm the problem: 

```
The error reported is:
  Couldn't find any output plugin named 'opentsdb'. Are you sure this is correct? Trying to load the opentsdb output plugin resulted in this error: no such file to load -- opentsdb
```

I am looking into it.

**Comment by jordansissel** [comment]
Looks like a misconfiguration in your gemspec.

I see `opentsdb` required here:
```
% ack 'require .opentsdb'

lib/logstash/outputs/opentsdb/http_client.rb
5:require "opentsdb"
6:require "opentsdb/transport/transport/http/manticore"
```

However, your gemspec has the necessary line commented out:

```
% grep runtime_dep logstash-output-opentsdb.gemspec| grep opentsdb
  #s.add_runtime_dependency 'opentsdb', ['>= 1.0.13', '~> 1.0']
```

If I remove the comment `#` and rebuild your gem, I get this error:

```
% bin/plugin install /home/jls/build/logstash-output-opentsdb/logstash-output-opentsdb-2.4.0-java.gem
Validating /home/jls/build/logstash-output-opentsdb/logstash-output-opentsdb-2.4.0-java.gem
Installing logstash-output-opentsdb
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "opentsdb":
  In Gemfile:
    logstash-output-opentsdb (= 2.4.0) java depends on
      opentsdb (>= 1.0.13, ~> 1.0) java
Could not find gem 'opentsdb (>= 1.0.13, ~> 1.0) java', which is required by gem 'logstash-output-opentsdb (= 2.4.0) java', in any of the sources.
```

Basically, you plugin has a dependency on `opentsdb` (probably? I have no idea, I haven't looked at your code to find out) and since Logstash doesn't ship with this, you'll need to specify it as a runtime dependency in your .gemspec file.

Hope this makes sense.

In summary, I think there's two problems:

1) The stack trace Logstash reports is ... incorrect. It correctly says the failure (cannot find the `opentsdb` library) but the stack itself is very confusing and misleading. It should be failing from your plugin's code, but something in Logstash, I think, is obscuring that fact.
2) Your plugin needs to express a dependency on whatever opentsdb library (if any) you want to use.

**Comment by CamJN** [comment]
I don't use an opentsdb gem, that was just left over from me search&replacing elasticsearch -> opentsdb but I commented it out b/c I don't have or use such a gem.

**Comment by jordansissel** [comment]
@CamJN ahh ok, then I think you could remove some of the `require` calls

**Comment by CamJN** [comment]
Ok cool, I guess I missed cleaning those up. Will test out after fixing that.

**Comment by CamJN** [comment]
Ok after I fixed that I started getting error messages that I understand again. I've now got the gem to the point where I can run a successful configtest, thanks.
