### ISSUE TITLE
Timestamp loses precision when parsed from a JSON

### ISSUE THREAD

**Issue by alex88** [elastic/logstash#4565]
I was trying to figure out why the GELF input wasn't showing milliseconds in kibana, turns out to be mainly a jRuby bug which I opened here https://github.com/jruby/jruby/issues/3616

Basically the gelf input plugin parses the JSON using `LogStash::Json.load` [here](https://github.com/logstash-plugins/logstash-input-gelf/blob/master/lib/logstash/inputs/gelf.rb#L107) and later it creates the timestamp value with `LogStash::Timestamp.at(event["timestamp"])`.

The real problem happens [here](https://github.com/elastic/logstash/blob/v2.1.1/lib/logstash/timestamp.rb#L26-L28), basically when `Time.at` is called with a BigDecimal (which LogStash::Json.load provides) the milliseconds are stripped.

Could it be worth to handle the case when it's a BigDecimal and call `to_f` on it? If so I can work on a PR.
Since you stil bundle an older jRuby version and maybe it's easier to handle the problem with a patch instead of waiting for a new jRuby release that you should also globally upgrade.

**Comment by suyograo** [comment]
@alex88 thanks for reporting this. We would absolutely love a monkey patch/PR to fix this for now. We are not on JRuby 9k

**Comment by alex88** [comment]
@suyograo sorry for the delay, is it possible that when using jruby https://github.com/elastic/logstash/blob/master/logstash-core-event/lib/logstash/timestamp.rb isn't touched by the tests?
I'm running 
```bin/rspec logstash-core-event/spec/logstash/timestamp_spec.rb logstash-core-event-java/spec/timestamp_spec.rb```
and even deleting the `at` method nothing changes, like I haven't removed the code

**Comment by alex88** [comment]
Ok nevermind, seems that running `rake test:install-core` installs the logstash-core-event-java which doesn't use the class I was trying to fix but it still has the same problem

**Comment by purbon** [comment]
@guyboertje what do you think?

**Comment by guyboertje** [comment]
@purbon, @alex88  /cc @colinsurprenant

We should not rely on side effects like this.

Git blame on [line 111](https://github.com/logstash-plugins/logstash-input-gelf/blame/master/lib/logstash/inputs/gelf.rb#L107) shows that it is very old.

For Ruby Event and Timestamp, we should be using [`Timestamp.coerce(time)`](https://github.com/elastic/logstash/blob/master/logstash-core-event/lib/logstash/timestamp.rb#L42) but as you can see numerical values are not coerced and perhaps they should be.

We will move to Java Event and Timestamp soon and the need to handle BigDecimal will go away:
- In [this line](https://github.com/elastic/logstash/blob/master/logstash-core-event-java/src/main/java/com/logstash/ext/JrubyTimestampExtLibrary.java#L162) we have the jruby `coerce` glue between Ruby Timestamp and Java Timestamp and it also does not coerce from a numerical value.  (**Colin** - notice spelling Timetsamp, my bad, I did not review very well)
- If we use `Event.from_json(string)` in all plugins - this will use Jackson and return converted Java objects and a Ruby Float for GELF timestamps. So we would need to coerce from Floats.
- If we use `LogStash::Event.new(LogStash::Json.load(data))` in plugins - this will incur a double conversion cost and we will get BigDecimal for GELF timestamps. So we need to coerce from BigDecimal.
- In the JRuby Event extension, `timestamp=` will throw an error if the value is not a Timestamp instance but the pure Ruby Event `timestamp=` accepts any value. Just saying :smile:.

So after the changes are made to `Timestamp.coerce` on the Ruby and Java sides we can change this plugin [here](https://github.com/logstash-plugins/logstash-input-gelf/blob/master/lib/logstash/inputs/gelf.rb#L110) to become...
```ruby
      event = LogStash::Event.from_json(data)
      event["source_host"] = client[3]
      event.timestamp = LogStash::Timestamp.coerce(event["timestamp"])
      event.remove("timestamp")
```
Until this time, I believe this input should use `to_f` as in...
```ruby
event.timestamp = LogStash::Timestamp.at(event["timestamp"].to_f)
```

**Comment by colinsurprenant** [comment]
@guyboertje  ouch `newTimetsamp` - missing test alert. good catch. 

Thanks for the headsup, we definitely need to clean this up. Let me dig some context around `Timestamp.at` and millis handling etc.

**Comment by colinsurprenant** [comment]
@guyboertje I am on the fence about your suggesting to use `Timestamp.coerce` in this case. My reasoning is that the `Timestamp.at` semantic is more clear than `Timestamp.coerce` since  `Timestamp.at`'s only purpose is to transform an epoch-style numeric to a proper `Timestamp` so in this particular case, if the GELF input specifically and only produces epoch-style *timestamp* field, I believe this is the right method to use. 

In that respect, I think the proper fix here is not to only to add `to_f` in the plugin to have this fixed now-now but also to add a `to_f` in the `Timestamp.at` when called with a `BigDecimal`, to fix any other potential bug like this. 

That being said, `Timestamp.coerce` should also correctly handle this case. 

@alex88 thanks for your work on this on the JRuby side in jruby/jruby#3616 ! good stuff!

**Comment by alex88** [comment]
@colinsurprenant glad to help ;)

**Comment by guyboertje** [comment]
@colinsurprenant - Your logic is sound, of course.  My mental tussle, is about whether plugin authors will know to use the appropriate call for the datatype they have - iow, either we make it clear in the docs or we only offer one method. I know that you mentioned yesterday that mechanism for all case coercing is complex - how about a second (defaulted to `:none`) parameter `hint :symbol` e.g. `:millis, :iso8601, :micros, :seconds, :datetime, :none`?

**Comment by colinsurprenant** [comment]
I suggest we adopt logstash-plugins/logstash-input-gelf#32 as the proper fix, with my proposed modifications.

**Comment by colinsurprenant** [comment]
@guyboertje this is now more a question of backward compatibility, both `Timestamp.coerce` and `Timestamp.at` are part of the API, I think we should continue to support *properly* support both (and correctly document).

**Comment by colinsurprenant** [comment]
Thanks everyone, the fix is in  logstash-plugins/logstash-input-gelf#32
