### ISSUE TITLE
[file input] multiline codec will never fully process last line

### ISSUE THREAD

**Issue by shoggeh** [elastic/logstash#4567]
Hi,

If you are using file input with multiline codec and files and you stop writing to the file (i.e. when file is rotated over) then last line from that file won't be ever processed as logstash will be always stuck on multiline codec waiting for continuation of that message.

Could you please check if it is possible to implement a timeout for this, so logstash won't wait longer than defined amount of time?

**Comment by shoggeh** [comment]
Hi,

If you are using file input with multiline codec and files and you stop writing to the file (i.e. when file is rotated over) then last line from that file won't be ever processed as logstash will be always stuck on multiline codec waiting for continuation of that message.

Could you please check if it is possible to implement a timeout for this, so logstash won't wait longer than defined amount of time?

**Comment by suyograo** [comment]
Hey @shoggeh this functionality has been implemented in multiline filter version 2.0.5 (https://github.com/logstash-plugins/logstash-codec-multiline/issues/15). This will also ship with LS 2.1.2 and 2.2 which will be released soon. 

FYI: https://github.com/logstash-plugins/logstash-codec-multiline/blob/master/CHANGELOG.md

**Comment by shoggeh** [comment]
Thanks a lot!
