### ISSUE TITLE
java heapspace error

### ISSUE THREAD

**Issue by Sreevatsa123** [elastic/logstash#4570]
My MySQL tables has 5,00,000 rows .I have to import it to elasticsearch to indexx the data.I am using LOGSTASH to do the same.THe following is my Logstash configuration file.

input {
  jdbc {
    jdbc_driver_library => "/home/vatsa/logstash/mysql-connector-java-5.1.38-bin.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://localhost:3306/LC"
    jdbc_user => "root"
    jdbc_password => ""

   
    statement => "select * from test WHERE ID<=50000"
  }
}
output {
    elasticsearch {
      
        index => "det"
        document_type => "contact"
        document_id => "%{ID}"
        hosts => "localhost:9200"
    }

}

Till the query is for ID<=45,000 ,it is properly indexing it and its working fine.But as soon as i make the sql query ID<=50000,it shows a java heap-space error.My system has 8gb ram.It is not able to handle 50,000 rows at once.How can i solve this???

thanks in advance

**Comment by suyograo** [comment]
@Sreevatsa123 you should use `pagination` https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-jdbc_paging_enabled

Also, moving this https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
