### ISSUE TITLE
plugin index doc generation is very whitespace intolerant

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#4571]
When generating the index of for a plugin type such as input, the lack of a final blank line a single plugin's documentation can cause the whole process to fail.

Example:
1. "bug" introducing PR https://github.com/elastic/logstash-docs/commit/2fdc8685be8911b5cea9e11fbdbb2c2b71df7a7a#diff-42452c263ebd72b9268e3f747dda5c77L417
2. resulting doc building fail: http://build-us-00.elastic.co/view/Doc/job/Docs/4284/console
3. fix: https://github.com/elastic/logstash-docs/commit/10e02d9d9b65093a6895da09b2ffd76af8880acf

It would be nice if the loop over the plugin collection didn't require this subtlety to work.

thoughts, @suyograo ?

**Comment by suyograo** [comment]
My editor removed blank lines which I need to fix. Plus, I'll make sure index.asciidoc has blank spaces before the includes. That should fix this weird bug

**Comment by suyograo** [comment]
There is not much we can do about this.
