### ISSUE TITLE
Move the `logstash-core/lib/api` to `logstash-core/lib/logstash/api`

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4574]
To be more consistent with the current architecture of logstash it should be move to `logstash-core/lib/logstash/api`

**Comment by purbon** [comment]
I will implement the change as requested and discussed with you, however I want to explain this is not the intended place where I do see the logstash API been living.

At my understanding, things inside logstash-core should be internal parts of the logstash infra, same reason why we've the plugin manager and bootstrap code living inside the main lib directory. Another piece that should be also not in core is the runner class as it's basically starting the agent and the pipelines (core logstash concepts). I will open (as also discussed) a follow up issue to discuss this concepts.

**Comment by ph** [comment]
merged in feature/metrics
