### ISSUE TITLE
sync Jackson dependencies between Java Event and JrJackson

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4577]
We have to make sure our Jackson dependency works well across the Java Event code and the JrJackson gem. Should JrJackson move to jar-dependencies usage, similar to https://github.com/elastic/logstash/blob/5a522a00370fb7bd7275d4ae7d7ab996a5fd329e/logstash-core-event-java/logstash-core-event-java.gemspec#L22-L25

@guyboertje ?

**Comment by guyboertje** [comment]
No longer an issue
