### ISSUE TITLE
fix coverage helper for use with java event

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4587]
the coverage helper uses a directory pattern for its skip list implementation. this [glob mecanism](https://github.com/elastic/logstash/blob/40b0685468b953cc8288ddac5c111443684ccf08/spec/coverage_helper.rb#L18) is not compatible with the new event implementations. it actually goes into the logstash-core-event directory and require all files event though this is not the right gem that is activated. 

we probably need to rethink this skip list thing. 

This is the cause of the current jenkins `Logstash_Master_Default_Plugins` build errors.

**Comment by colinsurprenant** [comment]
so the correct solution is **not** to just replace 
```
Dir.glob("{logstash-core{/,-event/},}lib/**/*.rb")
```
by 
```
Dir.glob("{logstash-core{/,-event-java/},}lib/**/*.rb")
```

since that will also hardcode the event implementation path which can change. 

- do we still need that require + skip list thing? I commented it out and it ran tests and generated coverage report. not sure why this is needed. 

@purbon I believe you introduced this, is that still needed? can you look at it?

**Comment by colinsurprenant** [comment]
I am not sure why we need to pre-require everything. I tried commenting out the require loop and it did not crash. Why is that still needed?

**Comment by purbon** [comment]
@colinsurprenant this is required due to coverage report giving incorrect numbers otherwise. Coverage is only accounted for loaded files.

**Comment by colinsurprenant** [comment]
I think we should disable coverage until we figure how to make it work correctly. At this point coverage is a nice to have but not essential. I'd rather have the test run without coverage than fail on broken coverage.

**Comment by suyograo** [comment]
This has been fixed in Jenkins
