### ISSUE TITLE
Please add this output plugin to the logstash-plugins project: logstash-output-rados

### ISSUE THREAD

**Issue by deathowl** [elastic/logstash#4590]
The plugin can be found here:
https://github.com/endticket/logstash-output-rados

The plugin makes possible to store logs in ceph.

**Comment by purbon** [comment]
Thanks a lot for your contribution, next move would be to do a first PR to https://github.com/logstash-plugins/logstash-output-rados and we will review and merge. 

Closing this for now as the new repo is created.
