### ISSUE TITLE
Undocumented behaviour with add_field

### ISSUE THREAD

**Issue by BellBiker** [elastic/logstash#4592]
I recognized that after calling the add_field method to get a copy of a field both fields point to the same content. So changes to the new field also cause the same change to the old field.
Let us assume I have created a field Mapping with the uppercase string "FOOBAR" and I do the following steps:
- mutate{add_field => {"mappingout" => "%{Mapping}"} }
- mutate{lowercase => ["mappingout"]}
Now both fields contain the lowercase string foobar
The following workaround is applicable:
- mutate{add_field => {"mappingout" => "tt%{Mapping}"} }
- mutate{lowercase => ["mappingout"]}
Using the workaround Mapping contains the original uppercase string FOOBAR and mappingout the lowercase ttfoobar.

I am not sure wether this behaviour is accidently or not. If not the documentation of add_field should be adapted and highlight this.

**Comment by jsvd** [comment]
confirmed:

```
/tmp/logstash-2.1.1 % cat add_field
input { generator { count => 1 message => "hello portugal"} }
filter {
  mutate { add_field => { "message_aux" => "%{message}" } }
  mutate { uppercase => "message_aux" }
}
output { stdout { codec => rubydebug } }
/tmp/logstash-2.1.1 % ./bin/logstash -f add_field
Settings: Default filter workers: 2
Logstash startup completed
{
        "message" => "HELLO PORTUGAL",
       "@version" => "1",
     "@timestamp" => "2016-02-01T13:23:23.428Z",
           "host" => "Joaos-MBP.lan",
       "sequence" => 0,
    "message_aux" => "HELLO PORTUGAL"
}
```

**Comment by jsvd** [comment]
more on this:

```
1.9 :003 > string = "hello"
 => "hello" 
1.9 :004 > event = LogStash::Event.new("message" => string)
 => #<LogStash::Event:0x5365419b @metadata_accessors=#<LogStash::Util::Accessors:0x5cbd8c55 @store={}, @lut={}>, @cancelled=false, @data={"message"=>"hello", "@version"=>"1", "@timestamp"=>"2016-02-01T13:29:46.644Z"}, @metadata={}, @accessors=#<LogStash::Util::Accessors:0x422a5833 @store={"message"=>"hello", "@version"=>"1", "@timestamp"=>"2016-02-01T13:29:46.644Z"}, @lut={}>> 
1.9 :005 > event["message"]
 => "hello" 
1.9 :006 > string.upcase!
 => "HELLO" 
1.9 :007 > event["message"]
 => "HELLO" 
 
 
1.9 :012 > LogStash::Util::Decorators.add_fields({"message_aux" => "%{message}"},event,"meh")
 => {"message_aux"=>"%{message}"} 
1.9 :013 > event["message"]
 => "HELLO" 
1.9 :014 > event["message_aux"]
 => "HELLO" 
1.9 :015 > string
 => "HELLO" 
 
 
1.9 :016 > string.downcase!
 => "hello" 
1.9 :017 > event["message"]
 => "hello" 
1.9 :018 > event["message_aux"]
 => "hello" 
```

**Comment by jordansissel** [comment]
The intent of "%{foo}" syntax is to produce text (string). It is an accident that it produces anything else. We're discussing this in #5114
