### ISSUE TITLE
symlink to logstash.log not working

### ISSUE THREAD

**Issue by trekr5** [elastic/logstash#4593]
Hello,

I'm hoping someone can help me with this issue.

I've installed logstash 1.5.4 on an amazon linux box and everything works fine. Because this runs in production, the log file /var/log/logstash.log tends to fill up very quickly and so I've decided to add an ebs volume and put the logstash.log onto this volume so that if the log file fills up, it doesn't make the device run out of space and then consequently shut down logstash.

When I have added the ebs volume and then created a symbolic link to the log file, on this volume, from /var/log/logstash.log. When I now check the logstash.log file, no errors are now being recorded even though the logstash service is running.

Is it possible to get symbolic links working with logstash-1.5.4? If so can someone tell me how?

Many thanks

**Comment by suyograo** [comment]
Why is the logstash log increasing? are you running it in debug mode?

> When I have added the ebs volume and then created a symbolic link to the log file, on this volume, from /var/log/logstash.log. When I now check the logstash.log file, no errors are now being recorded even though the logstash service is running.

This is weird. Can you check if you can manually write via this symbolic link?

Improving logging subsystem is something we are targeting as part of #3692. We will not be able to make backports to 1.5.x so I am closing this. For more debugging, please join us in https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements.
