### ISSUE TITLE
New java event interfere the plugin manager uninstall command with cached gems

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4599]
The introduction, and enablement, of the new java event in master broke the way the offline installation works, mostly affecting the uninstall command when there are plugins cached.

Due to the fact that we empty the internal bundler caches, aka app cache during package time, we introduced a hack that forced this caches to be rebuild, see

```
      ::Bundler::Source::Rubygems.module_exec do
        def cached_gem(spec)
          cached_built_in_gem(spec)
        end
      end
    end
```

https://github.com/elastic/logstash/blob/master/lib/bootstrap/bundler.rb#L35-L40

This basically pulls all requested specs from rubygems, in case they are not actually installed inside the internal cache. But as the new `logstash-core-event-java` is not at rubygems, this process fails. Uninstallation still works, but users see a set of nasty messages that can be misleading.

If no cache is present:

```
skywalker% bin/plugin install logstash-input-stdin
Validating logstash-input-stdin
Installing logstash-input-stdin
Installation successful
skywalker% ls vendor                              
_  bundle  jruby
skywalker% bin/plugin uninstall logstash-input-stdin
Uninstalling logstash-input-stdin
```

if there are plugins cached:

```
skywalker% ls vendor 
_  bundle  cache  jruby
skywalker% bin/plugin install logstash-input-stdin
Validating logstash-input-stdin
Installing logstash-input-stdin
Installation successful
skywalker% bin/plugin uninstall logstash-input-stdin
Uninstalling logstash-input-stdin
Error NoMethodError, retrying 1/10
undefined method `source_uri' for nil:NilClass
WARNING: SSLSocket#session= is not supported
Error NoMethodError, retrying 2/10
undefined method `source_uri' for nil:NilClass
WARNING: SSLSocket#session= is not supported
```

after that uninstalled plugin is gone, but the set of Error and warnings looks bad :smiley: :+1: 

@colinsurprenant what do you think about releasing event-java to rubygems? is this an option?

**Comment by colinsurprenant** [comment]
this problem should not be specific to `logstash-core-event-java`, the mechanism/setup should be **exactly** the same with the Ruby `logstash-core-event`

there are 3 logstash execution contexts:
1- local dev dir: where the gems are located in the source tree respective dirs `logstash-core-event/` or `logstash-core-event-java/`.
2- package generation for **dev** environment: (`rake artifact:...` with the Gemfile still pointing to local gem dirs) - in this case the  `logstash-core-event/` or `logstash-core-event-java/` gems are packaged as **local-gems**
3- package generation for **prod** environment (`rake artifact:...` with the Gemfile to *bare* gems on rubygems)

Unless there is a consistency problem in these scenarios the behaviour should be the same use wither gems in all cases.

**Comment by purbon** [comment]
this is all correct, but as we had the core-event released in rubygems the code is not complaining. In the case of core-event-java is not released, so the patch complain. 

Do you think we could just ignore it? I mean as is not a plugin. What do you think?

**Comment by colinsurprenant** [comment]
I think we should take that opportunity to correctly understand the implication of the cache rebuilding in the context of non-rubygems gems as we support the concept of `local_gems`. this definitely look like an incorrectly handled case.

**Comment by purbon** [comment]
Hi,
   at my understanding, we should ignore, for the cache rebuild, all gems
that are "build-in" logstash, so all logstash-core-* gems. We only need the
plugins and their dependencies there.

Except from the name, is there anything you might think we could use to
skip this logstash internal gems?

- purbon

**Comment by colinsurprenant** [comment]
at this point I have no idea, I did not dig into this issue, more investigation will be required.

**Comment by colinsurprenant** [comment]
fix for this in #4630

**Comment by purbon** [comment]
awesome,
   good!

- purbon

**Comment by purbon** [comment]
Sorry, must say the problem persist.

see

```
skywalker% bin/plugin install logstash-codec-rubydebug
Validating logstash-codec-rubydebug
Installing logstash-codec-rubydebug
Installation successful
skywalker% bin/plugin uninstall logstash-codec-rubydebub
c^[[A^C%                                                                                                                              skywalker% bin/plugin uninstall logstash-codec-rubydebug
Uninstalling logstash-codec-rubydebug
Error NoMethodError, retrying 1/10
undefined method `source_uri' for nil:NilClass
WARNING: SSLSocket#session= is not supported
Error NoMethodError, retrying 2/10
undefined method `source_uri' for nil:NilClass
WARNING: SSLSocket#session= is not supported
Error NoMethodError, retrying 3/10
undefined method `source_uri' for nil:NilClass
WARNING: SSLSocket#session= is not supported
Error NoMethodError, retrying 4/10
undefined method `source_uri' for nil:NilClass
WARNING: SSLSocket#session= is not supported
```

with 

```
skywalker% ls vendor 
_  bundle  cache  jruby
skywalker% 
```

I think there are two unrelated problems. I think the good solution for this is to skip from the cache rebuild "hack" internal built in logstash-core gems, something similar to what bundler does for ruby internal ones.

**Comment by ph** [comment]
I dont think this is a issue anymore, the remove command doesn't call rubygems at all and the new offline flow doesnt rely on rebuilding the cache and the previous pack command will be removed in logstash 6.0
