### ISSUE TITLE
Full encryption of events passing through Logstash

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#4606]
Currently, individual plugins can have their own encryption support (such as the upcoming Kafka 0.9 client and producer that supports the new SSL features in Kafka 0.9).  For the in-flight events, we have a request from the field to provide encryption capabilities for them as well (esp. when we start persisting these in the future).

**Comment by ph** [comment]
@colin @guyboertje  I came across this issue when looking for SSL ;) So I am bringing this to your attention since you are currently working on persistence, I am not saying we should have it for the version 1 of the feature, but this might influence how the architecture is done.

**Comment by jordansissel** [comment]
I think this is too general of a feature request. Logstash outputs don't all have a common mechanism for serialization (elasticsearch output, for example, doesn't use codecs at all).

It may be easier to achieve this if we start with specific use cases, such as kafka. Can we move this to the kafka output plugin? Looking at Kafka, I kind of expected an encrypted serializer (is this the right term?), but didn't find any at a quick glance. We could build one, maybe, but it's not a simple "just encrypt it" -- We'd need to know the threat model, etc.

Let's re-open this under the kafka input/output plugins. 

If we want to discuss threat models on the PQ, let's open a new ticket specific to that.

**Comment by jordansissel** [comment]
(Closing because I think we need to open more specific tickets for this on different repos)
