### ISSUE TITLE
Logstash fails to run by exception GemNotFound about ci_reporter_rspec gem

### ISSUE THREAD

**Issue by tagomoris** [elastic/logstash#4609]
I'm trying to create a new plugin, but after installing it (by `bin/plugin install ../path/of/logstash-output-treasure_data-0.9.0.gem`), Logstash 2.1.1 become to fail to start.

`ci_reporter_rspec` seems a gem for development, but it's included in `Gemfile.jruby-1.9.lock`, but it's not included in Logstash release package (I'm using tar.gz).

It seems weird for me that this exception doesn't occur without my new plugin. I'm reading bootstrapping code, but cannot find root cause for now.

Does someone have any idea about this problem?
```
$ bin/logstash -f ../example.conf 
Settings: Default filter workers: 2
Bundler::GemNotFound: Could not find gem 'ci_reporter_rspec (= 1.0.0) java' in any of the gem sources listed in your Gemfile or installed on this machine.
  verify_gemfile_dependencies_are_found! at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/resolver.rb:328
                                    each at org/jruby/RubyArray.java:1613
  verify_gemfile_dependencies_are_found! at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/resolver.rb:307
                                   start at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/resolver.rb:199
                                 resolve at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/resolver.rb:182
                                 resolve at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:192
                                   specs at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:132
                               specs_for at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:177
                         requested_specs at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:166
                         requested_specs at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/environment.rb:18
                                   setup at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:13
                                   setup at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
                                  (root) at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/setup.rb:18
                                 require at org/jruby/RubyKernel.java:1040
                                  (root) at /Users/tagomoris/github/logstash-output-treasure_data/logstash-2.1.1/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
^CSIGINT received. Terminating immediately.. {:level=>:fatal}
```

**Comment by jsvd** [comment]
can you post the gemspec of the plugin you created?

**Comment by purbon** [comment]
@tagomoris Good to see you here! 

as you said ```ci_reporter_rspec``` is not included in logstash, and is only required when running the test, not when running like you did.  are you doing anything with it inside your plugin?

**Comment by tagomoris** [comment]
@jsvd My gemspec is here: https://github.com/tagomoris/logstash-output-treasure_data/blob/master/logstash-output-treasure_data.gemspec

@purbon I do nothing around it intentionally, but dependencies of my gem might have something wrong or invalid... I haven't investigated it yet.

**Comment by tagomoris** [comment]
I tried some workaround, and then, found that all works well on logstash 2.1.1/2.1.2/2.2.0 without any changes from gemspec above.
It's very weird, but it might be any difference in console environment or anything else.
Sorry for bother you.

**Comment by lunarfs** [comment]
Had the same issue, in our case Gemfile.jruby-1.9.lock had 0 content, filling it with content from an similar server solved the issue

**Comment by rayprill** [comment]
Thumbs up to lunarfs.  That solved the same problem for me.  I believe the lock file got corrupted during a disk full event.  Restoring it fixed the problem.

**Comment by aslam-m** [comment]
Thanks @lunarfs It worked for me. I was in the same scenario as mentioned above by @rayprill and restoring it fixed the problem.

**Comment by aliaramli** [comment]
@lunarfs thanks it really work. our case was the file is missing/deleted.
