### ISSUE TITLE
Next steps on plugin management for Logstash

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4612]
Hi, during the implementation of #4535 many good ideas flowed to improve the way we handle plugins inside logstash. This issue is created with the intention to have a common place to discuss our vision for next steps.

**Comment by purbon** [comment]
From @ph 

> I am OK with that flow for a first version, what I would like is when we define a plugin in the config we load a generic files that define the plugin behavior or file.
> 
> **really high level thoughts here***
> "lib/plugins.rb"
> 
> ```ruby
> PLUGIN_CLASS = LogStash::Input::MQTT
> ```

I know your thoughts are really high level here, but I like the idea of having plugins define a more clever way to enable registration than standardizing a giving path to enable the ```require```. I will open a design issue to discuss next steps on plugin management, we can have all discussion there and follow up with implementation after it.

**Comment by andrewvc** [comment]
@ph I don't understand what you mean by this `lib/plugins.rb`. Doesn't the filename need to be unique for `require` to work right?

**Comment by ph** [comment]
@andrewvc yes if we do require "plugins" not if we require File.expand_path("....")

But in reality, while taking some steps back, we should check if we can adopt the same convention as rubygems. IE, creating a file in the `lib` with the same name as the plugin. SInce we assume that the plugins are unique this file should also be unique.

Lets take the rabbitmq family of plugins
```
require "logstash_rabbitmq"
```

```
# lib/logstash_rabbitmq
# pseudo code.
require "lib/logstash/inputs/rabbitmq"
require "lib/logstash/outputs/rabbitmq"
register_plugin Logstash::Inputs:;RabbitMQ
register_plugin Logstash::Inputs::RabbitMQ
```

The code is only there to illustrate a way of doing it.

**Comment by ph** [comment]
I think we can make this backward compatible,  if we can require the `logstash_rabbitmq` we could fallback to the other lookup/require.

**Comment by purbon** [comment]
@ph this idea works for me, but as you said, this is more of a feature vision on how plugins should work. I like it because if simplifies a lot of things in core, however I'm wondering we should provide a very clever API for the `lib/[plugin_name].rb` file, not sure if this could be a potential source of issues, what do you think?

**Comment by purbon** [comment]
And obviously this involve a lot of changes, like a mass update, or having booth systems living for a while.

**Comment by ph** [comment]
I believe it could be done in backward compatible way so this wouldn't require a mass update to make it work with existing plugin.

This suggestion was to complement @andrewvc's idea of merging plugins for a same service. IE. like `logstash-input-rabbitm/logstash-output-rabbitmq` into `logstash-rabbitmq`. I think we can make it work in a 5.X release.
