### ISSUE TITLE
Is the merging of -e and -f still a desirable behaviour?

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#4619]
currently when giving logstash both -e and -f, the config string and contents of the config files will be merged into a single pipeline.

I don't see a use case for this behaviour and only makes logic more complex.

So I propose that -e and -f become incompatible flags in the next major release of logstash.

**Comment by jordansissel** [comment]
I think support sometimes uses -e w/ -f for debugging/troubleshooting to add stdout or similar.

**Comment by purbon** [comment]
I agree with @jordansissel, I see this as something helpful for just adding things like stdout, however interface is a bit strange to me, we could probably provide an easier interface for this use case, isn't?

**Comment by suyograo** [comment]
+1 of making it not compatible when used together, it is just confusing. You can always add a new file using `-f`

**Comment by jsvd** [comment]
I collected a few more opinions, here are my translations (not actual quotes):

- "never used it"
- "I saw a production use case that resorted to -e to dinamically include a jdbc input to the pipeline described by -f"
- "not familiar with it, but felt the need for it, thanks :D"

**Comment by GlenRSmith** [comment]
Easy to implement equivalently using -f as @suyograo points out.

**Comment by suyograo** [comment]
This has been implemented in 6.0.0. `-f` and `-e` will not be merged starting with 6.0
