### ISSUE TITLE
Metrics to stdout not working with logstash 2.2.0

### ISSUE THREAD

**Issue by matejzero** [elastic/logstash#4620]
Hello,

today I updated logstash from 2.1.1 to 2.2.0 on my test server and metrics output stopped working.

I have the following setup (it's a test / benchmark server):
- file input plugins reads a file
- metrics plugins counts the number of events and adds tag 'metric'
- if there is 'metric' tag in the event, print it out to stdout, else send event to /dev/null

Somehow, I don't get any text on stdout.
Is it connected with the new pipeline? Is metrics plugin even useful now, with the new pipeline design?

My config:
```
input {
  file {
    path => "/mnt/logstash-test-log.1"
    start_position  => "beginning"
    sincedb_path => "/dev/null"
    ignore_older => 999999999999
    add_field => { "syslog_format" => "true" }
  }
}
filter {
    metrics {
        meter => "events"
        add_tag => "metric"
        add_field => { "metric_type" => "Input" }
        flush_interval => 10
    }
}
output {
  if "metric" in [tags] {
    stdout {
      codec => line {
        format => "%{[metric_type]}:  1m rate: %{[events][rate_1m]} ( %{[events][count]} ) | 5m rate: %{[events][rate_5m]} ( %{[events][count]} )"
      }
    }
  }
}
```

The same config is working on 2.1.1.

Matej

**Comment by andrewvc** [comment]
@matejzero thanks for reporting this. We've traced this to a bug in the flusher code for logstash 2.2.0 , there is a race condition where it sometimes will not start. This should be fixed by this new PR I just made: https://github.com/elastic/logstash/issues/4620

**Comment by matejzero** [comment]
@andrewvc: great, thanks... Will try the fix tomorrow at work

**Comment by andrewvc** [comment]
Thanks for the bug report @matejzero ! This was a bad bug. We hope to release a 2.2.1 version sometime this week to get this out.

**Comment by matejzero** [comment]
I did some testing and it looks like it's working as it should. Thanks for the fix.

**Comment by suyograo** [comment]
Released a snapshot version for anyone looking: 
https://download.elastic.co/logstash/logstash/logstash-2.2.1-SNAPSHOT.zip
https://download.elastic.co/logstash/logstash/logstash-2.2.1-SNAPSHOT.tar.gz
