### ISSUE TITLE
Travis CI PR testing fails, marking PR as failed

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4622]
See,

![screen shot 2016-02-03 at 16 51 53](https://cloud.githubusercontent.com/assets/68540/12787673/bf1ecdb6-ca96-11e5-8fc0-f63c61d1d852.png)

while the internal Jenkins pass, this should be fixed or the travis CI test disabled until they work as expected. Otherwise the information given for testing is contradictory to PR creators.

**Comment by andrewvc** [comment]
Fixed! I asked travis to build only if .travis.yml present.

**Comment by purbon** [comment]
good, @andrewvc do you know how we can re run the PR tests?
