### ISSUE TITLE
closing file descriptors logstash 2.2 

### ISSUE THREAD

**Issue by sharon77242** [elastic/logstash#4624]
Hi i have a problem,
I reading from a lot of files that changes all the time ,the files replaced with other files with same names , the old file descriptors remain open .
i saw new input flag on 2.2 (close_older) my question is: does it close files that moved already? That logstash opened it first but they moved
Without using this flag its making a lot of open files making an to many open files exception

**Comment by suyograo** [comment]
Hi can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!

**Comment by iwelch82** [comment]
@sharon77242  I'm having a very smilar issue. I did notice the 2.2 also introduces a new change to the file codec and multiline plugin, both of which I'm using. I'm wondering if this [commit](https://github.com/logstash-plugins/logstash-input-file/commit/60a626898ed14274a0ffafb5654b370ee610ce09) cause a bug. On linux I was ablt to work about the issue, temporarily by doing changing my maximum open files on the command line by running `ulimit -n 10000` as root. I also have to add the max_open_files flag in the file codec to `max_open_files => 9600`
I also noted that the max_open_files flag is missing from the [Logstash 2.2](https://www.elastic.co/guide/en/logstash/2.2/plugins-inputs-file.html) documentation

**Comment by sharon77242** [comment]
I solved this problem, i had logrotate running on the logs and it makes copy of the files with new name then moving them and the fd still remain open, i was chossing the logs by * (all files) so i choose them one by one, and also used the close older flag and it worked good
