### ISSUE TITLE
Grok pattern not matching in v2.2

### ISSUE THREAD

**Issue by shaunrampersad** [elastic/logstash#4636]
Hi

I'm trying to match a grok pattern in v2.2 for my jboss log application. 

`grok {
        match => ["message","(%{TIMESTAMP_ISO8601:datestamp}|%{TIME:timestamp}) +%{LOGLEVEL:loglevel} +\[%{GREEDYDATA:jbossclass}\] +\(%{GREEDYDATA:jbossthread}\) +%{GREEDYDATA:jbossmessage}"]
      }
`

Example log lines:
`2016-02-05 12:38:28,246 INFO  [org.platform.consumer.invokers.rest.RESTInvoker]  http-/x.x.x.x:8080-145) Invoking REST service using URL=[http://x.x.x.x:8080/report-service-2.0/api]`
`2016-02-05 12:38:28,256 ERROR [org.interfaces.ui.web.event.CustomFullAjaxExceptionHandler] (http-/x.x.x.x:8080-104) An exception has occurred......<truncated>
`

I've written the output to a logfile for debugging and I've picked up that the parsing is not working for the second log item.

1st logline output:
`
       "datestamp" => "2016-02-05 12:38:28,246",
        "loglevel" => "INFO",
      "jbossclass" => "org.platform.consumer.invokers.rest.RESTInvoker",
     "jbossthread" => "http-/x.x.x.x:8080-145",
    "jbossmessage" => "Invoking REST service using URL=[http://x.x.x.x:8080/report-service-2.0/api]"
`
2nd logline output:
`    "datestamp" => "2016-02-05 12:38:28,256",
        "loglevel" => "ERROR",
      "jbossclass" => "org.interfaces.ui.web.event.CustomFullAjaxExceptionHandler",
     "jbossthread" => "http-/x.x.x.x:8080-104) An exception has occurred.: javax.faces.FacesException: jav.....
`

NB: I have sanitised the above info. \<truncated\> is in place of a long java stack trace.

I've tested the above pattern and log samples here http://grokconstructor.appspot.com/do/match
and the log lines match perfectly, but in logstash the 2nd line keeps failing. 

Thanks
Shaun

**Comment by pemontto** [comment]
Your first log line is missing the opening parenthesis for "jbossthread"
`http-/x.x.x.x:8080-145)` should be `(http-/x.x.x.x:8080-145)`

Can't see anything wrong with the second line, it works in the [Grok Debugger](https://grokdebug.herokuapp.com/)

**Comment by shaunrampersad** [comment]
@pemontto, thanks for the response. The first line was probably a typo while I was sanitising the log line. 

Yes, the pattern and log line works perfectly on Gork Debugger or the other site I was using. But when running it via logstash it fails to match correctly.

I'm forwarding log items via filebeat v1.0.0 if that helps.

**Comment by shaunrampersad** [comment]
I've logged the output to a file to see how the data was being parsed. The below output has been truncated as it is a java stack trace that has been joined into one line by the multiline config.

The below output is the one that doesnt parse correctly. Seems to only happen when multiline joins a lot of lines together.
`
{
         "message" => "2016-02-18 20:13:33,720 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (http-/x.x.x.x:8080-3) could not log warnings: java.sql.SQLException: The statement is closed.\n\tat org.jboss.jca.adapters.jdbc.WrappedStatement.checkState(WrappedStatement.java:1324)\n\tat org.jboss.jca.adapters.jdbc.WrappedStatement.getWarnings(WrappedStatement.java:281)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.handleAndClearWarnings(SqlExceptionHelper.java:291) [hibernate-core-4.2.18.Final.jar:4.2.18.Final]...",
        "@version" => "1",
      "@timestamp" => "2016-02-18T18:13:33.720Z",
            "beat" => {},
           "count" => 1,
            "type" => "jbosslog",
            "host" => "host01",
            "tags" => [
        [0] "syslog_index",
        [1] "beats_input_codec_plain_applied"
    ],
      "datestamp" => "2016-02-18 20:13:33,720",
        "loglevel" => "DEBUG",
      "jbossclass" => "org.hibernate.engine.jdbc.spi.SqlExceptionHelper",
     "jbossthread" => "http-/x.x.x.x:8080-3) could not log warnings: java.sql.SQLException: The statement is closed.\n\tat org.jboss.jca.adapters.jdbc.WrappedStatement.checkState(WrappedStatement.java:1324)\n\tat org.jboss.jca.adapters.jdbc.WrappedStatement.getWarnings(WrappedStatement.java:281)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.handleAndClearWarnings(SqlExceptionHelper.java:291) [hibernate-core-4.2.18.Final.jar:4.2.18.Final]\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logAndClearWarnings(SqlExceptionHelper.java:250) [hibernate-core-4.2.18.Final.jar:4.2.18.Final]...",
     "jbossmessage" => "[rt.jar:1.8.0_60]\n"
}
`

This output is from a single line
`
{
         "message" => "2016-02-18 20:13:33,728 DEBUG [org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl] (http-/x.x.x.x:8080-3) Exception clearing maxRows/queryTimeout [The statement is closed.]",
        "@version" => "1",
      "@timestamp" => "2016-02-18T18:13:33.728Z",
            "beat" => {},
           "count" => 1,
            "type" => "jbosslog",
            "host" => "host01",
            "tags" => [
        [0] "syslog_index",
        [1] "beats_input_codec_plain_applied"
    ],
       "datestamp" => "2016-02-18 20:13:33,728",
        "loglevel" => "DEBUG",
      "jbossclass" => "org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl",
     "jbossthread" => "http-/x.x.x.x:8080-3",
    "jbossmessage" => "Exception clearing maxRows/queryTimeout [The statement is closed.]"
}
`

I'm not sure how else to debug this. IF you need more info please let me know

**Comment by shaunrampersad** [comment]
I've also moved the multiline config from logstash to the filebeat prospector. Both yield the same results which means that the issue is somewhere in logstash filter.

**Comment by shaunrampersad** [comment]
I've upgraded to logstash 2.2.1. The error has disappeared. 
Still monitoring though in case it crops up.

**Comment by shaunrampersad** [comment]
Problem still exists but with less errors. 
IS there a way to get logstash to log failed messages to a file?

**Comment by shaunrampersad** [comment]
I've managed to reproduce the issue more easily. I believe it has to do with the GREEDYDATA in the braces for jbossthread. 
`+\(%{GREEDYDATA:jbossthread}\)`

Have the following two lines will match differently due to () being in the body. GREEDYDATA takes everything up to the last ) within the message

`
09:51:44,668 INFO  [org.jboss.modules] (main) JBoss Modules version 1.3.6.Final-redhat-1
09:51:44,668 INFO  [org.jboss.modules] (main) JBoss Modules (version) 1.3.6.Final-redhat-1
`

The result is the jbossthread variable I'm creating will look like
`
"jbossthread" => "main"`
`"jbossthread" => "main) JBoss Modules (version"
`

The GREEDYDATA seems to look for the first and last closing brace within a message and grabs all that data. 

I'm playing with different options but I'm not any closer to a solution. The jbossthread in my case can be any combination of letters, numbers, characters, etc, hence the need for GREEDYDATA to capture everything within the ().

E.G: These are not exhuastive.
`(http-/172.0.0.10:8080-3) `
`(SimpleAsyncTaskExecutor-3)`
`(EJB default - 2)`
`(Periodic Recovery)`
`(WorkerThread#38[10.0.0.11:56952])`
`(Thread-35)`

**Comment by ph** [comment]
If the grok filter doesn't match it will tag the event with a `_grokparsefailure` you can use a conditionals in the file output to write them to a special index in ES or to a file.

You can also use this mechanism in the filter block to try other grok expression?
I think you will need your own version of greedydata for your case.

**Comment by ph** [comment]
I don't think this is a bug, but a problem with the grok expression used in the configuration for this specific case, its better to create a post in our discuss forum https://discuss.elastic.co/ we try to keep the issues trackers for bugs.
