### ISSUE TITLE
`LogStash::Event#clone` should also clone the `@metadata`

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4640]
The ruby event implements a custom `#clone` method, the code return a newly created object using the `@data` instance variable as the initial hash. This has the side effect of not cloning the `@metadata`, some filter use the clone and will drop any associated `@metadata` when the event goes through the filter chain.

original issue: https://github.com/logstash-plugins/logstash-filter-dns/issues/17
https://github.com/logstash-plugins/logstash-filter-dns/blob/master/lib/logstash/filters/dns.rb#L68

**Comment by ph** [comment]
This was a dupe of https://github.com/elastic/logstash/issues/4306

**Comment by jordansissel** [comment]
#5656 was merged into the 2.x branch but was never merged into 2.4.

2.4.0 was forked from d7bc5e1a54941e5f50eb9aa4b87d75d27b080a51 (according to `git merge-base v2.4.1 2.x`), and #5656 was only merged into the 2.x branch (by the Github merge button) and not backported to 2.4 branch (at least, not that I can see).

The org.logstash.Event.clone method in 5.x does not clone metadata either.

I have reopened this.

**Comment by johncollaros** [comment]
Has anything happened for 5.x clone filter yet?
I have just got hit by this bug.

**Comment by johncollaros** [comment]
@jordansissel Is anyone looking into this issue?

**Comment by dmarkhas** [comment]
+1 
This is very important to us as it breaks our ability to use the clone filter almost entirely.

**Comment by original-brownbear** [comment]
I will deal with this tomorrow :)

**Comment by original-brownbear** [comment]
fixed in #8291 and related backports
