### ISSUE TITLE
[offline installation] plugins installed locally can not be packaged for offline installation

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4644]
Plugins installed locally, see

```
tail Gemfile
gem "logstash-output-kafka"
gem "logstash-input-jdbc"
gem "logstash-input-foo", "2.2.1", :path => "vendor/local_gems/19ded85e/logstash-input-foo-2.2.1"
```

don't get packaged for offline installations.

The only possible workaround here is to set up a custom plugin server, for examples using geminabox, and do the installation through it.

**Comment by ph** [comment]
Locally installed gem are correctly packaged with the `prepare-offline-pack` in #6404
