### ISSUE TITLE
http server default port

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4648]
Change the default port of the http server, the current default is 9292. This port conflict with ES's range.
@suyograo  suggested we move to 9600, a quick google search doesnt show any popular application using that port.

Also we should be able to change it when starting logstash with a `cli` command, 
`--http-port` this can be moved to the settings file later to `http.port` setting.

**Comment by purbon** [comment]
++ for this, this is a relatively easy change we can very fast introduce.
