### ISSUE TITLE
Logstash metrics filter not working after logstash 2.2.0 upgrade

### ISSUE THREAD

**Issue by biswajit86** [elastic/logstash#4649]
I have an existing logstash config that reads data from topbeat and outputs data to kafka(config below). I have added the metrics filter to get the throughput of documents processed. After upgrading to logstash 2.2.0 ,I am not seeing any output in stdout from metrics filter.This only started happening after upgrading to logstash-2.2.0. 

```
 input {
   beats {
     port => 5044
   }
 }

> filter {
 if [type] == "process" {
 	if   [proc][username] == "root"  and [proc][cpu][total_p] < 0.1 and [proc][mem][rss] < 1000000 {
 	   drop{}
 	}else{
 	metrics {
 		meter => "documents"
 		add_tag => "metric"
 		flush_interval => 60
 	}
 	}
 }
 }

 output {
     if "metric" in [tags] {
                 stdout {
                         codec => line { format => "1m rate| %{@timestamp} | %{[documents][rate_1m]} 5m rate: %{[documents][rate_5m]} ( %{[documents][count]} ) "}
                 }
     }else    {
                 kafka {
                         topic_id => "topbeat-stage"
                         acks => "all"
                 }
         }
 }
```

PS:- This seems to be happening for all of my configs where I have referenced the metrics filter

**Comment by suyograo** [comment]
This is a dup of #4620 and has been fixed, awaiting a release of 2.2.1. 

Snapshot releases with bug fix:
https://download.elastic.co/logstash/logstash/logstash-2.2.1-SNAPSHOT.zip
https://download.elastic.co/logstash/logstash/logstash-2.2.1-SNAPSHOT.tar.gz
