### ISSUE TITLE
date filter not working

### ISSUE THREAD

**Issue by golauty** [elastic/logstash#4650]
Hi all,
I filter my event messages through a grok filter, afterwards i apply a date filter. Every time i use that date filter my successfull grok filtered messages are not shown in kibana, they just vanish somehow. No trace of them are left, usually i would expect a failure, but i cannot connect any error messages to that problem.
If i remove the date filter all my events are successfull parsed and i can see them in kibana.
The strangest thing for me is that the date filter already worked sometime ago. But then suddenly nothing worked at all. I did a complete new installation of the ELK Stack, but the behavior remained.

Here is my filter pipeline:

`grok 
 	 {
     	    pattern  => "%{TIMESTAMP_ISO8601:incidentTime:date}\s+%{WORD:level}\s+\[  {GREEDYDATA:thread}\]\s+\[%{GREEDYDATA:component}\]\s+%{GREEDYDATA:text}"
  	 }
     date 
     {
        match => ["incidentTime", "YYYY-MM-DD HH:mm:ss,SSS", "ISO8601"]
        target => "@timestamp"
        add_tag => [ "tmatch" ]
     }`

**Comment by ebuildy** [comment]
Hello, can you post your entire logstash config ? And some input messages ? so we can try it easier.

**Comment by golauty** [comment]
Here is my pipeline config:
```
input {
    beats {
       port => 5001
    }

    redis {
    host => "localhost"
    key => "logstash"
    data_type => "list"
    type => "jenkins"
    codec => json
    }
}
filter {
    if[type]== "jenkins"
    {        
         grok
         {
            match => { "message[0]"  => "%{TIMESTAMP_ISO8601:incidentTime:date}\s+\[(exec|%{WORD:host})\]\[%{WORD:TestNode}\]\s*\<%{GREEDYDATA:test}\s*\[%{WORD:result}\]\s*\[Warnings: %{WORD:WarningCount}\](\s*\[Errors: %{WORD:ErrorCount}\]\s*\[Exceptions: %{WORD:ExceptionCount}\])?\s*\[Duration: %{NUMBER:Duration}\]" }
         }         
         grok
         {
            match => {"[data][buildVariables][testsuite]" => "(\s*%{WORD:teamName}\\)?%{GREEDYDATA:testSuite}\s*"}
         }
         date 
         {
            match => ["incidentTime", "YYYY-MM-DD HH:mm:ss,SSS", "ISO8601"]
            target => "@timestamp"
            add_tag => [ "tmatch" ]
         }
         mutate 
         {
            convert => { "ErrorCount" => "integer" }
            convert => { "WarningCount" => "integer" }
            convert => { "ExceptionCount" => "integer" }
            convert => { "Duration" => "float" }
         }
  }
}
output {
    elasticsearch { hosts => ["localhost:9200"] }
}
```

Here are some sample log messages:
`
2016-02-12 09:14:35,976 [suv12qa03][TestCase]    <Open catalog page and check toolbar buttons [OK] [Warnings: 14] [Duration: 0.861]
`

`
2016-02-12 09:15:16,352 [suv12qa03][TestCase]    <Create a Product and open text editor [Error] [Warnings: 10] [Errors: 0] [Exceptions: 1] [Duration: 0.672883333333]
`

**Comment by golauty** [comment]
@ebuildy Do you have any update on this ?

**Comment by wiibaa** [comment]
@golauty just fyi this kind of usage question are best answered on https://discuss.elastic.co/c/logstash

What I strongly suspect in your config, is that you are using **DD** => day of year instead of **dd** => day of month, so your event are timestamped to **January 12th**, I'm pretty sure you would find them in kibana under this date.

**Comment by suyograo** [comment]
Hi as @wiibaa mentioned, can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
