### ISSUE TITLE
logstash service not running

### ISSUE THREAD

**Issue by radoslawcz** [elastic/logstash#4656]
Hi,

I have some problems with running logstash service on Ubuntu 14.04.3
I installed logstash 2.2 from APT repositories. When I start the logstash service it is running for a moment and after a few seconds it stops running. No logs are written to logstash log file. Below is a screenshot. 

http://snag.gy/uCZFg.jpg

**Comment by radoslawcz** [comment]
I forgot to add that running logstash from command line (with "logstash agent") does work.

**Comment by JamesBromberger** [comment]
See also: https://discuss.elastic.co/t/logstash-2-2-0-elasticsearch-output-connectivity-issue/41534
