### ISSUE TITLE
Logstash output plugin: AWS Firehose

### ISSUE THREAD

**Issue by chupakabr** [elastic/logstash#4657]
Hi guys,

Recently I implemented Amazon Kinesis Firehose output plugin for Logstash, so I'm thinking it might be useful for the community. I'm still improving it, but current version 0.0.1 has already basic functionality.

Please check if you think it worth it :)

Repository: https://github.com/chupakabr/logstash-output-firehose

PS While implementing this plugin I found out one critical bug in aws-sdk-ruby library by Amazon, see related pull request: https://github.com/aws/aws-sdk-ruby/pull/1086

With best,
Valera

**Comment by purbon** [comment]
HI @chupakabr how do you feel about the the plugin? from your issue, I can not grasp if you are willing to have it into logstash-plugins? please let us known.

**Comment by chupakabr** [comment]
hey @purbon, I'd like to have it in the standard logstash library, though the plugin is pretty fresh and lack of many useful features. On the other hard I already use it in our staging environments and it works well, so probably it could be useful for someone else as well.
Feel free to add into logstash standard plugin set if you feel good about it. I'm going to add more features (batch ingesting, fallback policy,..) into it later on when I have more time, but if it were in official logstash repo maybe some other people would like to contribute which would be great :)
Cheers

**Comment by purbon** [comment]
The best way to know that will be to actually try to have it in `logstash-plugins`, feel free to create a first PR in https://github.com/logstash-plugins/logstash-output-firehose and we can followup with review, etc.. to finally merge it.

/cheers

**Comment by chupakabr** [comment]
hey @purbon , it's not possible to submit pull request to an empty git repository.

**Comment by purbon** [comment]
Apologies for that, will fill it very soon.

**Comment by purbon** [comment]
solved, check again.

- purbon

**Comment by chupakabr** [comment]
hey @purbon , how some reason I cannot select my repository for pull request. I assume that's because this repo is not forked from the main one [https://github.com/logstash-plugins/logstash-output-example](https://github.com/logstash-plugins/logstash-output-example).

<img width="1104" alt="screen shot 2016-03-14 at 12 58 12" src="https://cloud.githubusercontent.com/assets/1623507/13745174/7a6732d6-e9e4-11e5-9aa7-6b07e88f3d67.png">

**Comment by purbon** [comment]
@chupakabr lets keep it simple, you should:

1.- Fork this repo.
2.- Copy over the code from your plugin.
3.- Do the PR

this should work without problems.

- purbon

**Comment by chupakabr** [comment]
@purbon , done. cheers!

**Comment by t-pascal** [comment]
We are interested in testing this code. Any reason the pull request is not in?

**Comment by t-pascal** [comment]
https://github.com/logstash-plugins/logstash-output-firehose/pull/1

**Comment by purbon** [comment]
@t-pascal because we need to review and test the PR before we commit to merge it, but this does not mean we are the only ones that can do it, if you are willing to review and test it, you are very welcome to drop there your comments.

Looking forward to it,
