### ISSUE TITLE
logstash 2.2.0 not creating indices in elasticsearch at day rollover

### ISSUE THREAD

**Issue by vhsjwp01** [elastic/logstash#4663]

**Comment by suyograo** [comment]
We need more info.

**Comment by vhsjwp01** [comment]
Certainly,

These configs under logstash 2.0.1 and elasticsearch 2.0.1 were working as expected:

============================
logstash.conf config (output portion, sanitized):
============================
output {
    elasticsearch {
      hosts              => ["XX.XX.XX.XX:9200"]
      template_name      => "logs"
      template           => "/config-dir/logs-template.json"
      index              => "logstash-%{+YYYY.MM.dd}"
      template_overwrite => true
      document_type      => 'logs'
    }
}

================
elasticsearch.yml config (sanitized):
================
bootstrap:
  mlockall: true
cluster:
  name: logdata
  routing:
    allocation:
      awareness:
        attributes: host
      cluster_concurrent_rebalance: 8
      same_shard:
        host: true
discovery:
  zen:
    minimum_master_nodes: 1
    ping:
      multicast:
        enabled: false
        ping:
          enabled: false
      unicast:
        hosts:
             - XX.XX.XX:9300
             - YY.YY.YY:9300
             - ZZ.ZZ.ZZ:9300
indices:
  fielddata:
    breaker:
      limit: 65%
path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs
http.cors.enabled: true
script.inline: on
script.indexed: on
http.cors.allow-origin: "/.*/"

With logstash 2.2.0 and elasticsearch 2.2.0 using these same configs, new indices are no longer being created at end of day in elasticsearch.  I can get it to work if I add "action.auto_create_index: true" to the end of the elasticsearch.yml file.  

It is not clear to me why it worked before, or even if it should have (although it did).  This feels like a change in default posture under ES 2.2.0 ...

**Comment by jordansissel** [comment]
I'm not sure this is a bug. Maybe ask for help on this over on the forums, https://discuss.elastic.co?
