### ISSUE TITLE
installing  all plugins pack offline is failing in logstash 2.2

### ISSUE THREAD

**Issue by ESamir** [elastic/logstash#4668]
Installing the all plugins pack offline is failing 

downloaded pack used :
https://download.elastic.co/logstash/logstash/logstash-all-plugins-2.2.0.tar.gz

The command used : 
 bin/plugin unpack --tgz /Users/samirbennacer/Testing/2.2.0/logstash-all-plugins-2.2.0.tar.gz 

the error 
```
Unpacking /Users/Testing/2.2.0/logstash-all-plugins-2.2.0.tar.gz
Errno::ENOENT: No such file or directory - /Users/samirbennacer/Testing/2.2.0/logstash-2.2.0/vendor/cache/logstash-2.2.0/LICENSE
  initialize at org/jruby/RubyFile.java:370
        open at org/jruby/RubyIO.java:1179
     extract at /Testing/2.2.0/logstash-2.2.0/lib/bootstrap/util/compress.rb:67
        each at /Users/Testing/2.2.0/logstash-2.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/tar_reader.rb:64
     extract at /Users/Testing/2.2.0/logstash-2.2.0/lib/bootstrap/util/compress.rb:61
         new at /Users/samirbennacer/Testing/2.2.0/logstash-2.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/tar_reader.rb:28
     extract at /Users/Testing/2.2.0/logstash-2.2.0/lib/bootstrap/util/compress.rb:60
        open at org/jruby/ext/zlib/JZlibRubyGzipReader.java:107
     extract at /Users/Testing/2.2.0/logstash-2.2.0/lib/bootstrap/util/compress.rb:59
     execute at /Users/Testing/2.2.0/logstash-2.2.0/lib/pluginmanager/unpack.rb:15
         run at /Users/Testing/2.2.0/logstash-2.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
     execute at /Users//Testing/2.2.0/logstash-2.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
         run at /Users/Testing/2.2.0/logstash-2.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
         run at /Testing/2.2.0/logstash-2.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
      (root) at /Users/Testing/2.2.0/logstash-2.2.0/lib/pluginmanager/main.rb:41

```

**Comment by untergeek** [comment]
I'm kind of confused.  The file logstash-all-plugins-2.2.0.tar.gz is not a pack of plugins, but the entire Logstash distribution _plus_ all plugins, rather than just the subset of supported plugins in the default download:

```
$ tar zxf ~/Downloads/logstash-all-plugins-2.2.0.tar.gz
$ ls
logstash-2.2.0
$ cd logstash-2.2.0/
$ ls
CHANGELOG.md           CONTRIBUTORS           Gemfile                Gemfile.jruby-1.9.lock LICENSE                NOTICE.TXT             bin                    lib                    vendor
```

I'm not sure where you found the instruction to unpack this via the plugin command, but it's unnecessary.

**Comment by purbon** [comment]
@untergeek is right @ESamir, this is a full distribution, not just the plugins.

**Comment by pricecarl** [comment]
Apologies all, I raised this issue with Samir.

If this is the case is there an rpm version of the all plugins distribution?

**Comment by purbon** [comment]
@pricecarl no problem at all, we should investigate all any time. I'm afraid is not there, only "default" plugins. You could also build yours if interested, but will need to checkout the source code.

**Comment by missnebun** [comment]
@untergeek 

From the documentation:
https://www.elastic.co/guide/en/logstash/current/offline-plugins.html

**2. Move the compressed bundle to the offline machines that are the source for offline plugin installation, then use the bin/plugin unpack subcommand to make the packaged plugins available**

If you extract plugins_package.tar.gz using tar then you need to make sure that you extract that in to /opt/logstash/vendor/cache if not when you try to install it will go to https://rubygems.org/

Gabriel

**Comment by untergeek** [comment]
@missnebun I understand that the documentation says what it says.  However, the file `logstash-all-plugins-2.2.0.tar.gz` is not a plugin pack, or a plugin bundle.  It is a full distribution of Logstash with _all_ plugins included.  The `bin/plugin unpack` command does not apply here.
