### ISSUE TITLE
Removal of --filterworkers considered harmful

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/logstash#4669]
I just learned the hard way that `--filterworkers` was removed in Logstash 2.2 (specifically, commit https://github.com/elastic/logstash/commit/028576ba6f141f57c180c8f3dbffa14cb24967c0). There are three problems with this:

* This was not mentioned in the [changelog](https://github.com/elastic/logstash/blob/2.2/CHANGELOG.md).
* There was no backwards compatible deprecation period which arguably would've made sense to match people's expectations for a non-major update like 2.2.
* The [command line docs for 2.2](https://github.com/elastic/logstash/blob/2.2/docs/static/command-line-flags.asciidoc) haven't been updated and still list `--filterworkers` as available.

This change broke Logstash Filter Verifier (https://github.com/magnusbaeck/logstash-filter-verifier/issues/4). Suggestions:

* Reinstate `--filterworkers` in 2.2.1 as a (possibly undocumented) alias of `-w`/`--pipeline-workers` to avoid additional breakage, and schedule the flag for permanent removal in 3.0.
* Update the changelog.
* Update the command-line documentation.

I can supply a PR for the latter two if you like. Do you want it to the 2.2 branch?

**Comment by andrewvc** [comment]
Thanks for bringing this up @magnusbaeck . You're right, we definitely should reistate that option as an alias. I'm going to start work on that today. We'll bring it back as a deprecated option.

The tricky thing here is that conceptually filter workers are gone, since the new pipeline doesn't have that concept. On the other hand we shouldn't be breaking configs with a minor release, and it's compatible enough. Apologies for the troubles you've faced here @magnusbaeck .

**Comment by suyograo** [comment]
For anyone reading this, `-w` flag still works. Agree `--filterworkers` should be reinstated as @andrewvc mentioned. We'll get this out asap.

**Comment by jordansissel** [comment]
@magnusbaeck thanks for catching this!

**Comment by suyograo** [comment]
@andrewvc keeping this open until we port this to master and 2.x

**Comment by andrewvc** [comment]
@suyograo I don't believe we should port to master since the next major won't support this functionality. This is already merged into 2.x. I think we can close it.

**Comment by suyograo** [comment]
Yep, not to master.

**Comment by magnusbaeck** [comment]
Thanks for the quick turnaround! But the 2.2.0 changelog should still be updated, right?

**Comment by suyograo** [comment]
@magnusbaeck yes, I will update the 2.2.0 changelog.
