### ISSUE TITLE
Production loglevel / make it configurable

### ISSUE THREAD

**Issue by lifeofguenter** [elastic/logstash#4673]
It seems that the current loglevel is hardcoded to warning:

https://github.com/elastic/logstash/blob/d74d41cb30c327ddb658e9b51fc2b2206a3d59fb/logstash-core/lib/logstash/logging.rb#L25

It would be great if it were configurable, or if in general log-output would be "usable for production". In my case for example the logfile was being filled endlessly due to two errors:

* filebeat input was too large, so instead of logging a "one-liner" logstash logged the whole content of the message
* there were problems with connecting to es, logstash kept logging those errors (instead of maybe one error per x-minutes)

**Comment by purbon** [comment]
Thanks a lot for your report, we're currently working on improving the hole logging experience in logstash.

**Comment by jordansissel** [comment]
> It seems that the current loglevel is hardcoded to warning

The intent is that warnings and errors are important for general production use. Everyone will have different opinions on what the words 'warning' 'error' and 'production' mean, so as @purbon mentioned, we are going to work on making logging configurable by component (so you could hide warnings from a certain part of Logstash, for example) eventually.

In terms of "hardcoded to warning" - this isn't true. The default is warn, but you can change the level with `--quiet` (error only), `--verbose` (informational), or `--debug` (debug level) command line flags for bin/logstash.

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5651
