### ISSUE TITLE
Logstash-input-jdbc plugin is not taking tracking column

### ISSUE THREAD

**Issue by pankajmalhotra** [elastic/logstash#4694]
I am trying to use following value in jdbc plugin but its not accepting "id" column.
use_column_value => true
tracking_column => "id" 

statement => "SELECT  id ,AccountId  FROM summary where  id > :sql_last_value"
But sql_last_value keeps on taking timestamp instead of id from summary table.

Please suggest

Logstash: 2.2.1
logstash-input-jdbc : 3.0.0
java version "1.8.0_66"

**Comment by ph** [comment]
@pankajmalhotra Can you run logstash with the `--debug` flag? We should see the SQL statement executed by the plugin?

Can you also check the content of the `ENV['HOME']/.logstash_jdbc_last_run` file?

**Comment by untergeek** [comment]
@pankajmalhotra any update here?

**Comment by pankajmalhotra** [comment]
I was able to resolve the issue. Previously .logstash_jdbc_last_run file was not getting created, but by putting option clean_run=>true it started working.

**Comment by untergeek** [comment]
Excellent.  Closing...
