### ISSUE TITLE
Enable ignore_unavailable for elasticsearch input plugin

### ISSUE THREAD

**Issue by tom-christie** [elastic/logstash#4696]
The REST API provides a parameter called ignore_unavailable which ignored unavailable (including closed) indices, i.e.  `ignore_unavailable=true`.

It would be great if this parameter was available for the Elasticsearch Input plugin for Logstash!  It is supported by the elasticsearch-js API. See for example [here](https://github.com/elastic/elasticsearch-js/blob/187ec62bbd734426a0b48bd204cc562794c89a1f/src/lib/apis/2_x.js#L5287).

Right now I get an error like this when I try to Input from an Elasticsearch instance with closed indices:

    Error: [403] {"error":"IndexClosedException[[MY_INDEX] closed]","status":403}

**Comment by suyograo** [comment]
Sounds good. moved here: https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/40
