### ISSUE TITLE
Format logstash output to a plain text pattern

### ISSUE THREAD

**Issue by gnhuy91** [elastic/logstash#4698]
I want to output to Papertrail log service, how can I transform logstash output to this plain text pattern: `<22>1 2014-06-18T09:56:21Z sendername programname - - - the log message` ?

**Comment by purbon** [comment]
@gnhuy91 you will need to create you a custom codec that composes your paper trail format, please take https://github.com/logstash-plugins/logstash-codec-plain as example as both will be very similar. Closing this as is not really an issue, more questions like this are very welcome in our forum at https://discuss.elastic.co/
