### ISSUE TITLE
LogStash 100% cpu consumption with particular regex/log line

### ISSUE THREAD

**Issue by sysmonk** [elastic/logstash#4699]
Hi,

Yesterday we got our logstash cluster almost to a full stop, all 16 logstash nodes with 24 core cpu's would consume 100% cpu on each core. It took me a while to find out where the problem is:

The log line:
`[17-Feb-2016 06:47:00 UTC] Warning: Invalid argument supplied for foreach() in /home/example/public_html/wp-content/advanced-cache.php(261) : runtime-created function on line 648 [example.com/media/something/something2013/] [/advanced-cache.php:262 __lambda_func(), /advanced-cache.php:182 do_variants(), ob(), wp-includes/functions.php:3517 ob_end_flush(), wp_ob_end_flush_all(), wp-includes/plugin.php:525 call_user_func_array(), wp-includes/load.php:636 do_action('shutdown'), shutdown_action_hook()]`

The regex:
`\[(?<timestamp>\d{2}-\w{3}-\d{4} \d{2}:\d{2}:\d{2} \w+)\] (PHP )?(?<severity>(Warning|Fatal error|Notice|Parse error)): +(?<error_text>.*) in (%{PATH:file}|(?<file>(Command line code)|Unknown)) on line (?<line>\d+)( \[(?<request>[^\]]+)\])?`

Expanded to normal regex (%{PATH} expanded):
`\[(?<timestamp>\d{2}-\w{3}-\d{4} \d{2}:\d{2}:\d{2} \w+)\] (PHP )?(?<severity>(Warning|Fatal error|Notice|Parse error)): +(?<error_text>.*) in ((?:(\/([\w_%!$@:.,~-]+|\\.)*)+|(?>[A-Za-z]+:|\\)(?:\\[^\\?*]*)+)|(?<file>(Command line code)|Unknown)) on line (?<line>\d+)( \[(?<request>[^\]]+)\])?`

Every log line like this would be accepted and sent to filter, and a filterWorker thread is started which then gets to consume 100% cpu. I tried waiting for it to finish (~15-20 mins) but it never did, so it might be some infinite loop. The regex101.com website shows that it is a "catastrophic backtracking", and it takes over 100k steps to run this regex with this exact log line ( https://regex101.com/r/jN8kF5/1 ).

I understand that the regex provided has issues, but:
1) it would be good if LogStash could see that a thread is taking longer than X seconds (5, 15, 30 ? ) and kill this thread + log the information (event in question, regex in question)
2) It took me quite a long time to find what is causing the issue. With around 4000 clients connected sending a lot of logs, finding THE log line that creates the issue was very hard/time consuming. I could see that filterWorker is taking up all cpu, but is there a way to know which message/event/regex is the filterWorker working on?

**Comment by sysmonk** [comment]
By the way, the grok pattern was written for a different log format, and the log message in question only started showing up yesterday. That's when everything stopped working.

**Comment by suyograo** [comment]
@sysmonk yes. this is a very popular ask. we'll get to this soon. Tracking here: https://github.com/logstash-plugins/logstash-filter-grok/issues/65
