### ISSUE TITLE
Experiencing java.lang.NoSuchMethodError for logstash version higher than 1.4.2

### ISSUE THREAD

**Issue by droidnxs** [elastic/logstash#4700]
Tried upgrading to releases 1.5 and up and keep getting this exception even though my config file seems to be correct:
io/console not supported; tty will not be manipulated
ObjectMapper.java:537:in `<init>': java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
        from ObjectMapper.java:448:in `<init>'
        from RubyJacksonModule.java:18:in `<clinit>'
        from JrJacksonRuby.java:104:in `__parse'
        from JrJacksonRuby.java:63:in `parse'
        from JrJacksonRuby$INVOKER$s$2$0$parse.gen:-1:in `call'
        from CachingCallSite.java:346:in `cacheAndCall'
        from CachingCallSite.java:204:in `call'
        from CallTwoArgNode.java:59:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from RescueNode.java:221:in `executeBody'
        from RescueNode.java:116:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:182:in `call'
        from DefaultMethod.java:203:in `call'
        from AliasMethod.java:61:in `call'
        from CachingCallSite.java:326:in `cacheAndCall'
        from CachingCallSite.java:170:in `call'
        from CallOneArgNode.java:57:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:182:in `call'
        from DefaultMethod.java:203:in `call'
        from CachingCallSite.java:326:in `cacheAndCall'
        from CachingCallSite.java:170:in `call'
        from FCallOneArgNode.java:36:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:182:in `call'
        from DefaultMethod.java:203:in `call'
        from CachingCallSite.java:326:in `cacheAndCall'
        from CachingCallSite.java:170:in `call'
        from FCallOneArgNode.java:36:in `interpret'
        from LocalAsgnNode.java:123:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from RescueNode.java:221:in `executeBody'
        from RescueNode.java:116:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:182:in `call'
        from DefaultMethod.java:203:in `call'
        from CachingCallSite.java:326:in `cacheAndCall'
        from CachingCallSite.java:170:in `call'
        from CallOneArgNode.java:57:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:139:in `call'
        from DefaultMethod.java:187:in `call'
        from CachingCallSite.java:306:in `cacheAndCall'
        from CachingCallSite.java:136:in `call'
        from VCallNode.java:88:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:139:in `call'
        from DefaultMethod.java:187:in `call'
        from CachingCallSite.java:306:in `cacheAndCall'
        from CachingCallSite.java:136:in `call'
        from CallNoArgNode.java:60:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:112:in `call'
        from DefaultMethod.java:169:in `call'
        from CachingCallSite.java:286:in `cacheAndCall'
        from CachingCallSite.java:81:in `callBlock'
        from CachingCallSite.java:85:in `call'
        from RubyClass.java:878:in `newInstance'
        from RubyClass$INVOKER$i$newInstance.gen:-1:in `call'
        from DynamicMethod.java:180:in `call'
        from CachingCallSite.java:296:in `cacheAndCall'
        from CachingCallSite.java:72:in `call'
        from CallSpecialArgNode.java:73:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from IfNode.java:116:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:268:in `call'
        from DefaultMethod.java:235:in `call'
        from CachingCallSite.java:366:in `cacheAndCall'
        from CachingCallSite.java:238:in `call'
        from FCallThreeArgNode.java:40:in `interpret'
        from InstAsgnNode.java:95:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from RootNode.java:129:in `interpret'
        from ASTInterpreter.java:95:in `INTERPRET_EVAL'
        from ASTInterpreter.java:184:in `evalWithBinding'
        from RubyKernel.java:1116:in `evalCommon'
        from RubyKernel.java:1079:in `eval19'
        from RubyKernel$INVOKER$s$0$3$eval19.gen:-1:in `call'
        from DynamicMethod.java:210:in `call'
        from DynamicMethod.java:206:in `call'
        from CachingCallSite.java:326:in `cacheAndCall'
        from CachingCallSite.java:170:in `call'
        from FCallOneArgNode.java:36:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from RescueNode.java:221:in `executeBody'
        from RescueNode.java:116:in `interpret'
        from BeginNode.java:83:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:247:in `call'
        from DefaultMethod.java:227:in `call'
        from CachingCallSite.java:356:in `cacheAndCall'
        from CachingCallSite.java:213:in `callBlock'
        from CachingCallSite.java:217:in `call'
        from RubyClass.java:864:in `newInstance'
        from RubyClass$INVOKER$i$newInstance.gen:-1:in `call'
        from JavaMethod.java:314:in `call'
        from CachingCallSite.java:346:in `cacheAndCall'
        from CachingCallSite.java:204:in `call'
        from CallTwoArgNode.java:59:in `interpret'
        from LocalAsgnNode.java:123:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from RescueNode.java:221:in `executeBody'
        from RescueNode.java:116:in `interpret'
        from BeginNode.java:83:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from RescueNode.java:221:in `executeBody'
        from RescueNode.java:116:in `interpret'
        from EnsureNode.java:96:in `interpret'
        from ASTInterpreter.java:74:in `INTERPRET_METHOD'
        from InterpretedMethod.java:139:in `call'
        from DefaultMethod.java:187:in `call'
        from CachingCallSite.java:306:in `cacheAndCall'
        from CachingCallSite.java:136:in `call'
        from CallNoArgNode.java:60:in `interpret'
        from ReturnNode.java:92:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
        from Interpreted19Block.java:206:in `evalBlockBody'
        from Interpreted19Block.java:194:in `yield'
        from Interpreted19Block.java:125:in `call'
        from Block.java:101:in `call'
        from RubyProc.java:300:in `call'
        from RubyProc.java:281:in `call19'
        from RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'
        from DynamicMethod.java:202:in `call'
        from DynamicMethod.java:198:in `call'
        from CachingCallSite.java:306:in `cacheAndCall'
        from CachingCallSite.java:136:in `call'
        from CallNoArgNode.java:60:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
        from Interpreted19Block.java:206:in `evalBlockBody'
        from Interpreted19Block.java:194:in `yield'
        from Interpreted19Block.java:125:in `call'
        from Block.java:101:in `call'
        from RubyProc.java:300:in `call'
        from RubyProc.java:281:in `call19'
        from RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'
        from DynamicMethod.java:202:in `call'
        from DynamicMethod.java:198:in `call'
        from CachingCallSite.java:306:in `cacheAndCall'
        from CachingCallSite.java:136:in `call'
        from CallSpecialArgNode.java:65:in `interpret'
        from DAsgnNode.java:110:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from BlockNode.java:71:in `interpret'
        from RescueNode.java:221:in `executeBody'
        from RescueNode.java:116:in `interpret'
        from BeginNode.java:83:in `interpret'
        from NewlineNode.java:105:in `interpret'
        from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
        from Interpreted19Block.java:206:in `evalBlockBody'
        from Interpreted19Block.java:194:in `yield'
        from Interpreted19Block.java:125:in `call'
        from Block.java:101:in `call'
        from RubyProc.java:300:in `call'
        from RubyProc.java:230:in `call'
        from RubyRunnable.java:99:in `run'
        from Thread.java:745:in `run'

The configuration goes on like this:
### input {
	file {
	path => "D:\Apache_web1.csv"
	start_position => "beginning"
	sincedb_path => "D:\.sincedb"
      }
### filter {
	csv
	{
		columns => ["time","CurrentlyExecutingRequests","IdleWorkers"]
		separator => ","
	}
	date
	{	
		match => [ "time", "MM/dd/YYYY HH:mm:ss"]
		locale => "en"
		target => ["@logtimestamp"]
	}
	mutate { convert => ["CurrentlyExecutingRequests", "integer"] }
	mutate { convert => ["IdleWorkers", "integer"] }
### output {  
	elasticsearch {
		hosts => "localhost:9200"
		workers => "3"
		index => "dt-web1-baseline1"
	}	
	stdout { codec => rubydebug }	
### }

Tried a lot of different versions and I get the same error. I'm using JDK 1.8.0_45, ElasticSearch 2.2.0, tried all releases from Logstash 1.5.0 to 2.2.2. Please help! :(

**Comment by ph** [comment]
Lets try to figure out what is going on here.

By the error I think there is something wrong when the serialization to JSON happen, which should be in the elasticsearch output.

If you move the stdout before the elasticsearch output block, we should see what is the actual content of the event, can you add it to the issue?

**Comment by suyograo** [comment]
Hi can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!

**Comment by droidnxs** [comment]
@ph 
I get the same output upon reordering the output plugins, but if I remove the ES output, the stdout reports nothing:
```
io/console not supported; tty will not be manipulated
Settings: Default pipeline workers: 4
Logstash startup completed
```
@suyograo 
Isn't this an issue too? Either way I've moved this to [https://discuss.elastic.co/t/experiencing-java-lang-nosuchmethoderror-for-logstash-version-higher-than-1-4-2/43077](url). Let's catch up there :)
