### ISSUE TITLE
Matching \ (backslash) in a conditional fails

### ISSUE THREAD

**Issue by sysmonk** [elastic/logstash#4705]
Hi,

I'm trying to match a \ (backslash) in a conditional:
`if [message] =~ /backslash/ { } ...
`
Unfortunately it fails with `Error: Expected one of #, and, or, xor, nand, { at line 2690, column 33 (byte 73184) after filter {` in all the ways i tried:
```
if [message] =~ /\/ { } ...
if [message] =~ /\\/ { } ...
if [message] =~ /\\\/ { } ...
if [message] =~ /\\\\/ { } ...
if [message] =~ #\# { } ...
if [message] =~ #\\# { } ...

```

Is this a bug? What's the proper way to match a backslash?

**Comment by sysmonk** [comment]
It looks like `=~ /[\\]/` works, and same is needed in gsub, i.e. to replace a backslash with double backslash: `gsub => { "message", "[\\]", "[\\\\]" }`

Would be nice to update the docs to be more specific about this.

**Comment by jordansissel** [comment]
Join us over at ticket #1645 where we are tracking this. :)
