### ISSUE TITLE
Default number of pipeline workers 

### ISSUE THREAD

**Issue by wkruse** [elastic/logstash#4706]
Either the blog or the documentation is wrong about the default number of pipeline workers.

> In Logstash 2.2 this number is by default the number of pipeline workers, which now default to be equal to the number of cores on the system.

https://www.elastic.co/blog/logstash-2-2-0-and-2-1-2-released

> Sets the number of pipeline workers (threads) to run for filter and output
 processing (default: half the number of cores).

https://www.elastic.co/guide/en/logstash/current/command-line-flags.html

Is it the number of cores or half?

**Comment by purbon** [comment]
@wkruse the number of pipeline workers are https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/pipeline.rb#L41, that is equal to total number of cpu cores. I confirm this problem, we'll need to update the documentation with last changes, please refer to `bin/logstash --help` for detailed info on the command line.

Thanks for reporting this error,
