### ISSUE TITLE
RabbitMQ input exchange not created when missing 

### ISSUE THREAD

**Issue by smetj** [elastic/logstash#4711]
Hi,

It seems that the input module does NOT create the defined exchange when missing and bind the defined queue to it, whilst that would be expected behavior from an amqp client (whether it's a consumer or producer) and is therefor a bug imo.

Also the RabbitMQ **input** "exchange_type" parameter is optional whilst in the **output** plugin it is an obligatory parameter.  Not a huge problem as such, but both input & output should have the same behavior in this regard.

**Comment by ebuildy** [comment]
Hello,

You should post plugin issues in the plugin repository itself:

https://github.com/logstash-plugins/logstash-input-rabbitmq/issues

You will have more chance to have the right help!

**Comment by smetj** [comment]
I overlooked that. Will do. Tnx for feedback.

**Comment by smetj** [comment]
ref https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/48
