### ISSUE TITLE
Duplicate records from logstash

### ISSUE THREAD

**Issue by rubinsaifi** [elastic/logstash#4719]
Hi, 

I have a remote server from where i am doing rsync to get the files which are gziped. after gunzip i store them to the location from where logstash takes the data.

the issue is  when the process starts it index the already indexed file and so creates redundant entries.
i am trying to understand if the timestamp change leads to create this issue

using logstash 1.4.2 with elastic version 1.7

**Comment by ph** [comment]
Are you uncompressing the files all the time? Logstash keeps track of the `inode` of the files to know if it need to process the files, uncompressing the files probably mean the inode is different every time and logstash keep reading them.

**Comment by suyograo** [comment]
Every log line is considered unique in Logstash and indexed as such in Elasticsearch. if you need at most once guarantee, you'll need to add an UUID to each log line and use it ES output `document_id` config

**Comment by rubinsaifi** [comment]
it was found to be the issue when i was uncompressing files again and again which resulted inode values getting changed.

to counter this, i made few changes such as
- storing gz file to a temp location and gunzip them
- only move file if the file does not exists at logstash logs directory (mv -i came handy) which resulted in no change in inode values

thanks you all for aesome replies, i have not gone through uuid solution provided by suyograo but yes it looks promising 


heil ELK
