### ISSUE TITLE
Provide guidance on tuning workers for the next gen pipeline in LS 2.2

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#4720]
From discussing with @andrewvc , the next gen pipeline in LS 2.2 defaults -w to the number of cores on the machine, but to get the best performance out of the next gen pipeline, we will actually want to set -w to > number of cores on the machine because some threads are now being used for IO.  

A general tuning exercise to determine the number of workers to use will be to keep increasing the -w beyond the # of cores until performance no longer improves (and that LS does not run out of memory).   We may want to document this guidance.

**Comment by andrewvc** [comment]
@ppf2 agreed. We definitely need a 'tuning' section in the LS guide. There's some info in https://www.elastic.co/guide/en/logstash/current/pipeline.html but we need a shorter article directed at performance.

**Comment by andrewvc** [comment]
We also need to update the 'breaking changes' section for 2.2 to include the perf recommendations.

**Comment by suyograo** [comment]
PR: https://github.com/elastic/logstash/pull/4725
