### ISSUE TITLE
Logstash Skipping Events from Logcourier in Linux

### ISSUE THREAD

**Issue by Rajeshkumar123** [elastic/logstash#4734]
I have deployed 3 logstash configuration files in my server which is processing 3 different kinds of log files(.xml,.log and .txt). I am using 3 logurier files(version 1.6) to fetch the log files and logstash(version 1.5.4) to process the log files. Daily I am getting tons of log files, log courier fetching all the log files from the location but my logstash skips many events.

I am running the setup in my redhat linux 3.10.0-229.e17.x86_64 version and JDK 1.7. Am I missing any thing to sort out this issue.

**My logstash file:**
```
input {
   courier {
		port => xxxx
		transport => "tcp"

	}
}
filter{
.....
}
output{
elasticsearch {		  
		  index => "logstash-server1-%{+YYYY.MM.dd}"
		  host => "XXXXXX"
				cluster => "server_cluster"	
				protocol => "http"
				document_id => "%{fingerprint}" 	  		  
		}
}

```
**Logcourier File:**

```
{
	"general": {
		"log level" : "debug",
		"persist directory" : "<.logcourier file location>"		
	},
	"network": {
		"servers": [ "127.0.0.1:xxxx" ],		
		"transport": "tcp"
	},

"files": [
		{
			"paths":[
					"/Mylogdata/error/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/vg67-*.xml"
					
					],
			"fields": { "type": "sss_log" },
			"codec": {
				"name": "multiline",
				"pattern":"<regular expression>",
				"negate": true,
				"what": "next"
			},
			"dead time": "1s",
			
		}
	]
}
```

Do I need to add any additional property to overcome this issue.. I am using the same configuration for all the 3 configuration files(Logstash and Logcourier)

**Comment by guyboertje** [comment]
If possible you should upgrade LS. There have been many improvements to LS since that version.
Is there a pattern to the events that are being skipped? If you turn debug logging on (with --debug), do you see any log output that helps to figure out why events are skipped?

**Comment by Rajeshkumar123** [comment]
In my logcourier file I have found this skipping file information. `2016/02/29 06:52:09.632178 Skipping file (older than dead time of 3s): /fgh/temp/root.xml`

**Comment by suyograo** [comment]
@Rajeshkumar123 logcourier issues should be logged here: https://github.com/driskell/log-courier
