### ISSUE TITLE
--configtest position is relevant

### ISSUE THREAD

**Issue by robin13** [elastic/logstash#4737]
`logstash --configtest -f /etc/logstash/conf.d` is not equal to `logstash -f /etc/logstash/conf.d --configtest`

If the configuration binds to a port (e.g. tcp input), the later will not actually do a config test and will actually start the server.
This is relevant (and wrongly used) in the sysv init script [here](https://github.com/elastic/logstash/blob/master/pkg/logstash.sysv#L147)

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/4738

**Comment by jordansissel** [comment]
FYI order of flags shouldn't matter. This is a bug in logstash, not
necessarily the unit script. But I appreciate the quick fix to the init
script :)

**Comment by robin13** [comment]
@jordansissel Where can I track the real bug being fixed?  Shall I create a new issue, or reopen this one?
