### ISSUE TITLE
File input with start_position => beginning does not works correctly on advanced usage tutorial

### ISSUE THREAD

**Issue by schovi** [elastic/logstash#4740]
I try official tutorials for logstash and fail on second example with

```
input {
    file {
        path => "/path/to/logstash-tutorial.log"
        start_position => beginning 
    }
}
```
https://www.elastic.co/guide/en/logstash/current/advanced-pipeline.html#configuring-geoip-plugin

When run my pipeline it doesnt do anything. After some digging how it works and googling I found solution which tells me to add `sincedb_path => "path/to/.sincedb*"` https://stackoverflow.com/questions/24144099/file-input-not-working-for-logstash

Is this **bug** or `sincedb_path` is required configuration?

**Comment by jordansissel** [comment]
@schovi start_position only affects the first-contact scenario where a file has never been seen before by Logstash and needs information on where to start reading. Judging from your report, it sounds like Logstash _has_ seen this file before and you were able to kind of work around this problem by changing the `sincedb_path` to a new file which would make your file input see all watched files as new.

I don't think this is a bug, if my assumptions about your scenario are right. And also, `sincedb_path` is not a required setting - Logstash has a default for this value if you don't specify it.

Hope this explains things.

**Comment by schovi** [comment]
@jordansissel Great! I understand what happened. It created sincedb into my home directory. And as you said I run it once probably without any meaningful output and missed that.
Can I configure where are default sincedb? I dont like to have infested my home directory :)

**Comment by suyograo** [comment]
@schovi yes `sincedb_path` lets you configure where to put the sincedb file.

**Comment by schovi** [comment]
@suyograo Got it. Home is default value in that input plugin. There is nothing like LOGSTASH_DATA_PATH.

Thanks
