### ISSUE TITLE
uninitialized constant LogStash::Outputs::ElasticSearch::HttpClientBuilder::Logstash

### ISSUE THREAD

**Issue by wenerme** [elastic/logstash#4741]
```
input {
    file {
        path => "/path/to/any/where/trace.log"
        start_position => beginning
        type => "test"
    }
}


output{
  elasticsearch{
    action => "update"
    document_id => "3"
    index => "test"
    document_type => "test"
    script => "ctx._source.obj.status='Wener'"
    upsert => '{"obj":{}}'
    scripted_upsert => true
    doc_as_upsert => true
  }
  stdout{
    codec => rubydebug{
      metadata => true
    }
  }
}
```

if I remove `doc_as_upsert => true` the error will dismiss.Maybe the error report should be more clear ?

logstash 2.2.2

**Comment by wenerme** [comment]
Should I report the issues to here https://github.com/logstash-plugins/logstash-output-elasticsearch/issues

**Comment by suyograo** [comment]
@wenerme yes, in general for issues which occur is specific plugins. I'll move this to ES output now.

**Comment by suyograo** [comment]
Created https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/378
