### ISSUE TITLE
Logstash jdbc input : Read password from external file

### ISSUE THREAD

**Issue by biswajit86** [elastic/logstash#4744]
Hi, We started using logstash jdbc input in a few of our configs and so far it has been working really great. We do have some problems with the way the connection credentials are passed in

 We do not store password for any of our apps in our config files.
* First of all, it violates our security guidelines
* Second, whenever we change a password , we do not want to change the configs for every since service that we have.

Therefore, we store our password in files on unix host and apply permissions using chmod to restrict access to the relevant applications.

However, logstash currently does not offer any other mechanism to read password files. Could you please add a config in jdbc-input plugin to read password from an external file instead of passing in a blank password.

PS:- This is not the same requirement as [PR 4183](https://github.com/elastic/logstash/issues/4183)

**Comment by untergeek** [comment]
Please close this ticket and re-open at https://github.com/logstash-plugins/logstash-input-jdbc, which is where JDBC input-specific issues should go.

**Comment by biswajit86** [comment]
@untergeek  , Thanks. will do

**Comment by biswajit86** [comment]
Created https://github.com/logstash-plugins/logstash-input-jdbc/issues/120 instead of thi sissue
