### ISSUE TITLE
Edit button has an extra asciidoc in URL

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#4747]
Clicking the `Edit` button [here](https://www.elastic.co/guide/en/logstash/current/_upgrading_using_package_managers.html) causes a 404. It should send you [here](https://github.com/elastic/logstash/edit/master/docs/static/upgrading.asciidoc) instead.

**Comment by markwalkom** [comment]
It seems to be a common issue across a bunch of the pages too.

**Comment by suyograo** [comment]
I just pushed a fix @palecur @markwalkom
