### ISSUE TITLE
Logstash log files json

### ISSUE THREAD

**Issue by robin13** [elastic/logstash#4751]
If this exists in another issue already, sorry for the duplicity...

Currently logstash logs are written out in rubydebug, and yet there is no rubydebug input option, making it very difficult to parse logstash logs.  Besides that IMO logstash logs are not easily human readable, so they encapsulate the worst of both worlds as far as logfiles go.
Would it be possible to have JSON formatted log files?

**Comment by suyograo** [comment]
@robin13 no worries. We are targeting 5.0 alpha2 for this. https://github.com/elastic/logstash/issues/1569
