### ISSUE TITLE
Compare two events and aggregate the difference into an array

### ISSUE THREAD

**Issue by thalesfsp** [elastic/logstash#4753]
Hello Guys!

We are processing some MSSQL tables via JDBC input plugin. Some times, 3 rolls will be almost equal. Our goal is merge these lines together and transform the values that are different in an array. So, given this 3 events

```ruby
event1 = {
  "id" => 1 ,
  "name" => "John",
  "country" => "Texas"
}

event2 = {
  "id" => 1 ,
  "name" => "John",
  "state" => "Alaska"
}

event3 = {
  "id" => 1 ,
  "name" => "John",
  "state" => "Oregon"
}
```

It need to be merged in something such as:

```ruby
finalEvent = {
  "id" => 1 ,
  "name" => "John",
  "state" => ["Texas", "Alaska", "Oregon"]
}
```
And finally saved into ES.

It's possible?

Thanks!

PS: I tried ask for help in IRC, research in Google and also in the LogStash forum

**Comment by untergeek** [comment]
This is not the correct place for usage questions. Those do belong in discuss.elastic.co (or whatever the url is--in on my phone here).

For _issues_, _bugs,, please go to the correct plugin repository: https://github.com/logstash-plugins/logstash-input-jdbc 

For the record, if your records are properly sorted, you may be able to use the aggregate filter to accomplish this.
