### ISSUE TITLE
Add size as metadata to Event class

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4757]
Size of an event is required in 2 places:
* To provide a `flush_size_bytes` in ES Output: This would allow users to control bulk requests based on size rather than number of events. See https://github.com/elastic/logstash/issues/4000
* Metrics: Provide bytes/sec processed through Logstash

Size can be calculated as an estimate and maybe stored in `@metadata` which can be accessed in other stages. This calculation should be easy with Java implementation of Event

**Comment by jordansissel** [comment]
(warning: the following is mostly stream-of-thought and not well-formed yet)

@suyograo for #4000, is there a reason we want this to be user-configurable? My hope is that we can have a good default that perhaps tunes itself according to Elasticsearch's configuration if necessary. I'd prefer not to burden users with having to set flush_size_bytes themselves.

For metrics, bytes/sec could be computed at input and output time -- example: tcp input reads a binary payload, knows how many bytes that is, etc. TCP output we have to serialize via the encoder and we'll know how long the encoding is. Further, the 'byte size' of an event would vary by what shape it takes when read or written -- like the beats input can use compression, so counting bytes (by decompressed payload? by compressed payload?) becomes a bit confusing. I think it makes the most sense to me specifically for metrics to count bytes at encode and decode phases. If we _do_ count bytes at encode-time, then we could reuse that calculation to determine if the bulk request to Elasticsearch would be too large, for example, and split it up.

Thoughts?

**Comment by suyograo** [comment]
> My hope is that we can have a good default that perhaps tunes itself according to Elasticsearch's configuration if necessary. I'd prefer not to burden users with having to set flush_size_bytes themselves.

IMO its tricky to guestimate a good default and then have it tune dynamically based on ES deployment. I do like the idea where users don't have to set this, but it may not be straightforward to implement correctly. How about we have this configurable for v1 and we can phase it out when we understand the behavior? plus we'll get more real world feedback from the first iteration?

> I think it makes the most sense to me specifically for metrics to count bytes at encode and decode phases

Makes sense

**Comment by suyograo** [comment]
At this point we'll focus on getting:

> To provide a flush_size_bytes in ES Output: This would allow users to control bulk requests based on size rather than number of events

Tracked by #4000.

Closing this since calculating size of Event is tricky and we don't have strong asks for this feature.

**Comment by voiprodrigo** [comment]
I'd like to add a ask for this feature. In terms of metrics, I have a strong interest to compare over time variations of volumes in size and average sizes per type of event. It could be an option, not everyone may need that.

**Comment by xavier-isecurity** [comment]
I also want to add that requirement. Could be possible get the bytes of events before any processing? Right when it arrives the input configuration. Would be appreciated for traffic controlling.
