### ISSUE TITLE
Logstash crashes with Your application used more memory than the safety cap of 1G.

### ISSUE THREAD

**Issue by onidlo** [elastic/logstash#4766]
Dear all,

my Logstash installation on Ubuntu crashes very often (several times per day, very low load, it receives only 10-50 lines per day). 

Here come two error messages:

./logstash.err
Error: Your application used more memory than the safety cap of 1G.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace

./logstash.stdout
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /opt/logstash/heapdump.hprof ...
Heap dump file created [1756253658 bytes in 62.044 secs]

My setup is quite simple, but I use multiline codec for input - maybe this is the reason?

Regards,
Ondrej

**Comment by purbon** [comment]
@onidlo can you please share your config and might be a sample log line? thanks a lot for your feedback.

**Comment by onidlo** [comment]
Here is my config, let me start with input part:
```
input {
      beats {
        port => 5044
        ssl => true
        ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
        ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"

        codec => multiline {
            pattern => "%{APACHE_ERROR_LOG_HEADER}(((PHP Stack trace)|(PHP   [0-9]\.)|(PHP  [1-9][0-9]\.))%{GREEDYDATA})"
            patterns_dir => ["/etc/logstash/patterns.d/apache-error"]
            what    => "previous"
        }
      }
} 
```
Then I will continue with filter part:
```
filter { 
  if [type] == "apache_error" { 
     # 1) -------- Parse Apache log file
     grok {
        match => { "message" => "%{APACHE_ERROR_LOG}" }
        patterns_dir => ["/etc/logstash/patterns.d/apache-error"]
        add_field => { "timestamp" => "%{year}-%{month}-%{day} %{time}" }
        remove_field => [ "day", "month", "year", "time" ]
     }

     # take first referer from multiline string
     grok {
         match => { "errormsg" => "%{DATA}((\, referer\: )%{URI:referer}){0,1}" }
     }
      # delete all additional referer's: (not working yet:-)
     #mutate {
     #gsub => ["errormsg", "\, referer\: %{DATA}\n", "__________________"]
     #} 

     # 2) --------- Determine PHP error level
     grok {
         match => { "errormsg" => "((PHP )%{DATA:phperrorlevel}\: )|%{GREEDYDATAMULTI}" }
         patterns_dir => ["/etc/logstash/patterns.d/apache-error"]
     }
     # clean PHP error level
     mutate {
        lowercase => [ "phperrorlevel" ]
        gsub      => [
                       "phperrorlevel", " ", "_"
                     ]
     }


     # 3) --------- If everything worked fine, remove original message
     if "_grokparsefailure" not in [tags] {
        mutate {
            remove_field => ["message"]
        }
     }
 }
} 
```

And finally output is sent to elasticsearch:
```
output {
    elasticsearch {
        hosts => ["localhost:9200"]
        sniffing => true
        manage_template => false
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
    }

    stdout {
        codec => rubydebug
    }
}
```
 
Here is the pattern used above:
```
GREEDYDATAMULTI (.|\r|\n)*
APACHE_ERROR_LOG_HEADER \[%{DAY} %{MONTH:month} %{MONTHDAY:day} %{TIME:time} %{YEAR:year}\] \[%{WORD}{0,1}\:%{LOGLEVEL:loglevel}\] \[pid %{NUMBER}:tid %{NUMBER}\] (?:\[client %{IPORHOST:clientip}\:%{POSINT}]{0,1} ){0,1}
APACHE_ERROR_LOG %{APACHE_ERROR_LOG_HEADER}%{GREEDYDATAMULTI:errormsg} 
```

It seems complicated, but it parses logs created by PHP's Xdebug + Apache, which look like this (sometimes multiline, sometimes oneline):

```
> [Wed Feb 17 13:50:38.647339 2016] [core:alert] [pid 2144:tid 936] [client fe80::8032:e1dc:870b:aae5:32569] C:/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration
> [Mon Feb 15 12:33:47.580722 2016] [:error] [pid 2144:tid 1000] [client fe80::8032:e1dc:870b:aae5:1485] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor in Project\\Engine\\Reporting\\MPDF\\mpdf.php on line 89, referer: http://web/accdocument.php?
> [Fri Feb 19 12:40:25.345737 2016] [:error] [pid 2012:tid 948] [client 192.168.0.229:59560] PHP Fatal error:  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY AccDocument.EvidNumber' at line 1<br /><br /> SQL query: <pre>ORDER BY AccDocument.EvidNumber </pre> Error occured in <strong>AccDocument::GetRecords_BySQL</strong> called from <strong>C:\\AccDocument.php</strong> on line <strong>614</strong>\n<br /><br />Catched by SQL error handler in C:\\SafeDB.php on line 71, referer: http://web/accdocument.php?
> [Fri Feb 19 12:40:25.345737 2016] [:error] [pid 2012:tid 948] [client 192.168.0.229:59560] PHP Stack trace:, referer: http://web/accdocument.php?
> [Fri Feb 19 12:40:25.345737 2016] [:error] [pid 2012:tid 948] [client 192.168.0.229:59560] PHP   1. {main}() C:\\accdocument.php:0, referer: http://web/accdocument.php?
> [Fri Feb 19 12:40:25.345737 2016] [:error] [pid 2012:tid 948] [client 192.168.0.229:59560] PHP   2. PageAccDocument->process() C:\\accdocument.php:7, referer: http://web/accdocument.php?
> [Mon Feb 15 12:33:47.580722 2016] [:error] [pid 2144:tid 1000] [client fe80::8032:e1dc:870b:aae5:1485] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor in C:\\mpdf.php on line 89, referer: http://web/accdocument.php?typeID=1
> [Mon Feb 15 12:21:56.999504 2016] [mpm_winnt:notice] [pid 1340:tid 364] AH00418: Parent: Created child process 2228
> [Mon Feb 15 12:21:57.625539 2016] [mpm_winnt:notice] [pid 2228:tid 256] AH00354: Child: Starting 64 worker threads. 
```

You can download all mentioned files here: http://dev.refis.sk/etc-logstash.zip

**Comment by suyograo** [comment]
@onidlo whats your LS version and Java version?

**Comment by onidlo** [comment]
Hi @suyograo 

root@elk-droplet:/opt/logstash/bin# ./logstash --version
logstash 2.2.2

root@elk-droplet:/opt/logstash/bin# java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Thanks!

**Comment by onidlo** [comment]
Hi @suyograo,

do you have any idea please?

Regards,
Ondrej

**Comment by LaurensBER** [comment]
I've run into the same issue with a even more minimal configuration:

logstash.conf:
```
input {
  beats {
    port => 5044
  }
  tcp {
    port => 5055
    codec => json
  }
}

filter {

  if [source] == "/var/log/audit/audit.log" {
    drop { }
  } else if [input_type] == "log" and 'access.log' in [source]  {
    grok {
      patterns_dir => "/opt/logstash/patterns"
      add_tag => [ "access" ]
      match => { "message" => "%{NGINXACCESS} ." }
    }
  }

}

output {
  elasticsearch {
    hosts => "elk-prod-es01:9200"
    sniffing => true
    manage_template => false
    document_type => "%{[@metadata][type]}"
  }
}
```

```
[laurens.bosscher@elk-prod-web01 ~]$ cat /opt/logstash/patterns/nginx 
NGUSERNAME [a-zA-Z\.\@\-\+_%]+
NGUSER %{NGUSERNAME}
NGINXACCESS %{IPORHOST:clientip} %{NGUSER:ident} %{NGUSER:auth} \[%{HTTPDATE:timestamp}\] "%{WORD:verb} %{URIPATHPARAM:request} HTTP/%{NUMBER:httpversion}" %{NUMBER:response} (?:%{NUMBER:bytes}|-) (?:"(?:%{URI:referrer}|-)"|%{QS:referrer}) %{QS:agent}
```


```
[laurens.bosscher@elk-prod-web01 ~]$ /opt/logstash/bin/logstash --version
logstash 2.2.2
```

```
[laurens.bosscher@elk-prod-web01 ~]$ java -version
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
```

Right now there is only 1 client actively sending logs to Logstash and we still get the error. In Kibana I can see that Logstash crashes after about ~6 hours.

**Comment by LaurensBER** [comment]
I can see with free -m that free memory on the server slowly decreases, if there is an more accurate way I could test for memory leaks or how I could debug this problem further, please let me know.

**Comment by LaurensBER** [comment]
It's been running stable for two days with the following configuration:

```
[laurens.bosscher@elk-prod-web01 ~]$ cat /etc/logstash/conf.d/config.json 
input {
  beats {
    port => 5044
  }
  tcp {
    port => 5055
    codec => json
  }
}

filter {

  if [source] == "/var/log/audit/audit.log" {
    drop { }
  } else if 'access.log' in [source]  {
    grok { 
      patterns_dir => "/opt/logstash/patterns"
      add_tag => [ "access" ]
      match => { "message" => "%{NGINXACCESS} ." } 
    }
  }

}

output {
  elasticsearch {
    hosts => "elk-prod-es01:9200"
    #sniffing => true
    manage_template => false
    document_type => "%{[@metadata][type]}"
  }
}
```

Please notice that the only difference with the previous configuration is that I removed the AND statement. Thus this seems unrelated to the issue @onidlo has.

**Comment by 00sivan** [comment]
I'm having the same issue running on CentOS 7 in a VM. Any help will be very appreciated.

This conf would populate something around 12 million rows running as command line. Is there a better way to do this? We were doing it with ES1 using rivers and didn't have much trouble.

Here is the config:

<pre><code>
input {

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select * from es_comm_hist"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select x.*, t.status, CAST(t.latitude AS CHAR) AS latitude, CAST(t.longitude AS CHAR) AS longitude, l.city_name, t.state, t.zip, 'comm_txt' as `type`, x.listno as esid from t_comm_txt x inner join t_comm t on (x.listno = t.listno) join lookup_city_name l on (t.city = l.city_code)"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select * from es_farm_hist"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select x.*, t.status, CAST(t.latitude AS CHAR) AS latitude, CAST(t.longitude AS CHAR) AS longitude, l.city_name, t.state, t.zip, 'farm_txt' as `type`, x.listno as esid from t_farm_txt x inner join t_farm t on (x.listno = t.listno) join lookup_city_name l on (t.city = l.city_code)"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select * from es_land_hist"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select x.*, t.status, CAST(t.latitude AS CHAR) AS latitude, CAST(t.longitude AS CHAR) AS longitude, l.city_name, t.state, t.zip, 'land_txt' as `type`, x.listno as esid from t_land_txt x inner join t_land t on (x.listno = t.listno) join lookup_city_name l on (t.city = l.city_code)"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select * from es_multi_hist"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select x.*, t.status, CAST(t.latitude AS CHAR) AS latitude, CAST(t.longitude AS CHAR) AS longitude, l.city_name, t.state, t.zip, 'multi_txt' as `type`, x.listno as esid from t_multi_txt x inner join t_multi t on (x.listno = t.listno) join lookup_city_name l on (t.city = l.city_code)"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
                jdbc_user => "user"
                jdbc_password => "password"
                jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
                jdbc_driver_class => "com.mysql.jdbc.Driver"
                jdbc_fetch_size => "1000"
                #schedule => "*/15 * * * *"
                statement => "select * from es_res_hist"
                jdbc_paging_enabled => "true"
                jdbc_page_size => "50000"
        }

	jdbc {
		jdbc_connection_string => "jdbc:mysql://sql.example.com:3306/db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
		jdbc_user => "user"
		jdbc_password => "password"
		jdbc_driver_library => "/etc/logstash/drivers/mysql-connector-java-5.1.40-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_fetch_size => "1000"
		#schedule => "*/15 * * * *"
		statement => "select x.*, t.status, CAST(t.latitude AS CHAR) AS latitude, CAST(t.longitude AS CHAR) AS longitude, l.city_name, t.state, t.zip, 'res_txt' as `type`, x.listno as esid from t_res_txt x inner join t_res t on (x.listno = t.listno) join lookup_city_name l on (t.city = l.city_code)"
		jdbc_paging_enabled => "true"
		jdbc_page_size => "50000"
	}
}

filter {
  mutate {
    add_field => { "[@metadata][document_id]" => "%{esid}" }
  }
}

output {
	#stdout { codec => json_lines }
	elasticsearch {
	hosts => "es4.example.com:9200"
	index => "jdbc"
	document_type => "%{type}"
	document_id => "%{esid}"
	}
}
</pre></code>

**Comment by untergeek** [comment]
@00sivan please ask your question at https://discuss.elastic.co/c/logstash as your particular issue is more of a usage question than a bug.  This is from having 10 separate inputs each trying to open a JDBC connection.

**Comment by 00sivan** [comment]
Thanks very much.

**Comment by braco** [comment]
For Googlers

https://discuss.elastic.co/t/changing-logstash-heap-size/69542/2

> you can edit the config/jvm.options file, or use the LS_JAVA_OPTS environment variable.
> LS_JAVA_OPTS="-Xmx2g -Xms1g" bin/logstash -e ""

**Comment by kares** [comment]
this issue is defunct by now, closing to avoid further side tracking with "same-here" comments
