### ISSUE TITLE
Auto_flush in multiline codec doesn't work with Kafka input plugin

### ISSUE THREAD

**Issue by ciprianpascu** [elastic/logstash#4771]

**Comment by ciprianpascu** [comment]
Configuration something like this:

input {
       kafka {
           topic_id => "test"
           zk_connect => ...
           consumer_threads => 1
           codec => multiline {
               auto_flush_interval => 3
               pattern => "TRACE HIGH ACTIVE"
               negate => true
               what => previous
           }
       }
   }

**Comment by jordansissel** [comment]
I wouldn't expect it to work well with kafka (based on my expectations of what multiline codec tries to solve). What are you trying to do?

**Comment by suyograo** [comment]
multiline is not supported in kafka because messages can come out of order in different partitions. You could use the message key to group all parts of multiline data into one partition, but this is not something we've tested or hear about.

**Comment by ciprianpascu** [comment]
Ok, that's really good to know! I was testing only with one Kafka partition and it worked pretty well, except that the last message from a burst was not handled, because of auto_flush not working. But, if there are issues when using multiple partitions, I will have to find another solution. Thanks!

**Comment by suyograo** [comment]
@ciprianpascu I don't know what your source of data is, but if it is files, you can use filebeat which has multiline functionality and it can send to kafka directly

**Comment by suyograo** [comment]
Also, any beats in general can send to Kafka

**Comment by TinLe** [comment]
According to this, https://github.com/elastic/beats/issues/943, beats can not yet send direct to Kafka.

Has that been implemented and released?

**Comment by suyograo** [comment]
@TinLe its been implemented and merged to master in https://github.com/elastic/beats/pull/942. Not yet released. I believe its targeted for the 5.0 release

**Comment by TinLe** [comment]
Nice! :)

**Comment by ciprianpascu** [comment]
My source of data is some processes sending logs, but now it seems I won't need the multiline codec, so auto_flush not needed either :).
