### ISSUE TITLE
Email option in ouput section - getting undefined method `on_load' for ActiveSupport:Module

### ISSUE THREAD

**Issue by cooldharma06** [elastic/logstash#4774]
hi all,

i am running logstash-2.2.2 in Ubuntu 14.04.3 LTS.

when i enable email in outoput section i am getting undefined method `on_load' for ActiveSupport:Module error.

please refer the follwoing debug logs:

---

New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["localhost:9200"], :level=>:info, :file=>"logstash/outputs/elasticsearch/common.rb", :line=>"19", :method=>"register"}
Plugin not defined in namespace, checking for plugin file {:type=>"output", :name=>"stdout", :path=>"logstash/outputs/stdout", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"76", :method=>"lookup"}
Plugin not defined in namespace, checking for plugin file {:type=>"codec", :name=>"rubydebug", :path=>"logstash/codecs/rubydebug", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"76", :method=>"lookup"}
config LogStash::Codecs::RubyDebug/@metadata = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
**The error reported is: 
  undefined method `on_load' for ActiveSupport:Module**
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/awesome_print-1.6.1/lib/awesome_print.rb:29:in `(root)'
org/jruby/RubyKernel.java:1040:in`require'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.5/lib/logstash/codecs/rubydebug.rb:1:in`(root)'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.5/lib/logstash/codecs/rubydebug.rb:18:in `register'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/config/mixin.rb:370:in`validate_value'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/codecs/base.rb:15:in `initialize'
org/jruby/RubyArray.java:1613:in`each'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/config/mixin.rb:311:in `validate_check_parameter_values'
org/jruby/RubyHash.java:1342:in`each'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/config/mixin.rb:306:in `validate_check_parameter_values'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/config/mixin.rb:305:in`validate_check_parameter_values'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/config/mixin.rb:220:in `validate'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/config/mixin.rb:102:in`config_init'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/outputs/base.rb:63:in `initialize'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/output_delegator.rb:28:in`initialize'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:403:in `plugin'
org/jruby/RubyKernel.java:1079:in`eval'
(eval):158:in `initialize'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:57:in`initialize'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/agent.rb:172:in `execute'
org/jruby/RubyProc.java:281:in`call'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/runner.rb:90:in `run'
org/jruby/RubyProc.java:281:in`call'
/home/opens/elk/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/runner.rb:95:in `run'

---

Suggest some solution to solve this error.

regards,
cooldharma06

**Comment by jordansissel** [comment]
This stack trace is from the rubydebug codec. I need more information to diagnose this. Can you attach your complete logstash configuration?

**Comment by cooldharma06** [comment]
hi jordan,

please refer the below configuration file:

___

input {
    redis {
       host => "127.0.0.1"
       type => "redis-input"
       data_type => "list"
       key => "logstash"
          }
    beats {
       port => 5044
       ssl => true
       ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
       ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
          }

      }


filter {    
     if [message] =~ /^[\s]*$/  {
                  drop { }
         }

      if [fields][log_type] == "nova"  {
        grok  {
               patterns_dir => "../patterns"
               match => [ "message", "%{TIMESTAMP_ISO8601:date_time} %{LOGLEVEL:loglevel} %{SYSLOGPROG:component} %{REQUEST_ID:requestid} %{GREEDYDATA:content}" ]
            }
    }

}
               
output {

 if "ERROR" in [message]  {
    email  {
     port           =>    "587"
     address        =>    "smtp.gmail.com"
     username       =>    "xxxxx@gmail.com"
     password       =>    "xxxxxx"
     authentication =>    "plain"
     use_tls        =>    true
     from           =>    "xxxxx@gmail.com"
     subject        =>    "logstash alert"
     to             =>    "cooldharma06@gmail.com"
     via            =>    "smtp"
     body           =>    "COOL 06... :) Here is the event line that occured: %{message}"
        }
    }

  elasticsearch {
    hosts => ["localhost:9200"]
    sniffing => true
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }

  stdout { codec => rubydebug }
}

**Comment by jordansissel** [comment]
Not sure what is causing it, but you can try commenting out your `stdout` codec to see if that helps.

**Comment by cooldharma06** [comment]
thanks @jordansissel i commented out its working fine.

then i moved the stdout before email section. now its working fine. thanks .:)
