### ISSUE TITLE
Add plugins list API

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4777]
Follow up from #4446 

### Plugins

Expose an endpoint to get information on all plugins currently installed. This is basically the output of `bin/plugins list --verbose`

```GET /_plugins```

Response:

```
"total": 102
"plugins" : [
  {
      "name": "logstash-output-pagerduty"
      "version": "2.0.2"
  },
  {
      "name": "logstash-output-elasticsearch"
      "version": "2.1.2"
  }
....
]  
```

**Comment by purbon** [comment]
changed the label to be in sync with the PR.
