### ISSUE TITLE
Logstash Out Of Memory error

### ISSUE THREAD

**Issue by chriss745** [elastic/logstash#4778]
Hi, we are using logstash 2.2.2 to feed elasticsearch with logs from RabbitMQ. We continuously experiencing a logstash crash with out of memory error. If I start it up with 2GB HEAP, the memory usage continuously grows:

![image](https://cloud.githubusercontent.com/assets/6066270/13631342/634b82d6-e5e4-11e5-923d-38d50f36a528.png)

until it reach the maximum, and GC keeps running 99% of the time and eventually logstash is crashing.

![image](https://cloud.githubusercontent.com/assets/6066270/13631464/13613c7e-e5e5-11e5-89f5-10ab5b2a62c3.png)

I already tried with also 32GB HEAP, it just delay the crash as it takes longer to fill all the memory.

We are using the following filters:

- grok
- json
- date
- mutate

I also tried with logstash 1.5, but we are experiencing the same issue. I also tried with JDK 1.7 and 1.8, but no change.

Logstash is running with the following parameters:

/usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/var/lib/logstash -Xmx2g -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/var/lib/logstash -XX:HeapDumpPath=/opt/logstash/heapdump.hprof -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log -w 6

Could you please advise?

Thanks!

Chris

**Comment by jsvd** [comment]
can you post the full config, and a link to the heap dump?
also, since it takes very little time to OOM, maybe also a few thread dumps?

**Comment by chriss745** [comment]
Hi, thanks for checking the issue, but it looks a VM reboot solved the problem:

![image](https://cloud.githubusercontent.com/assets/6066270/13665805/73afbe1a-e6ae-11e5-9030-9357a532fe59.png)

Now everything works fine.
