### ISSUE TITLE
Wrong messaging about removed settings

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#4789]
In [Breaking Changes](https://www.elastic.co/guide/en/logstash/2.2/breaking-changes.html) it is mentioned that:

> New options: bind_host, bind_port, cluster, embedded, embedded_http_port, port, sniffing_delay

However this are a mix of old options, and only a couple of them still exists. I think that this should be fixed in the documentation. We should mention that this settings should are **removed** already.

**Comment by suyograo** [comment]
Fixed
