### ISSUE TITLE
date match "ISO8601" does not match 2016-03-10T21:37:43.820Z

### ISSUE THREAD

**Issue by lawre** [elastic/logstash#4791]
The following date match does not pick up 2016-03-10T21:37:43.820Z.  This is from ESXi 5.5 syslog daemon.

```
date {
      match => [ "ISO8601" ]
    }
```

**Comment by untergeek** [comment]
@lawre The [match directive](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-match) is incorrect.  There should be a field name, e.g.

```
date {
      match => [ "timestamp", "ISO8601" ]
    }
```

Replace `timestamp` with whatever field name holds the ISO8601 date stamp.

In the future, please direct usage questions to our [discussion forums](https://discuss.elastic.co/c/logstash).  GitHub is reserved for issues and bugs.
