### ISSUE TITLE
stall detection vs. jmx-input

### ISSUE THREAD

**Issue by boernd** [elastic/logstash#4793]
Version: 2.2.2

When using the jmx-input plugin the logstash process won't stop. 

Logsnippet of one stalling thread:
`: stalling_threads_info=>[{
	"thread_id"=>39,
	"name"=>"[base]<jmx",
	"plugin"=>nil,
	"current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.2/lib/logstash/inputs/jmx.rb:356:in sleep"
},`

Workaround: I set the KILL_ON_STOP_TIMEOUT to 1, the --allow-unsafe-shutdown parameter did not work for me.

**Comment by ph** [comment]
I have moved this issue to the plugin repository https://github.com/logstash-plugins/logstash-input-jmx/issues/17
