### ISSUE TITLE
Explanation how to stop logstash

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#4800]
In the documentation (https://www.elastic.co/guide/en/logstash/2.2/stalled-shutdown.html#shutdown-stall-example), it is mentioned that stopping logstash should happen with `Ctrl+C`. However, when running this in other modes/environments sometimes it will be nice to explain the different methods to stop logstash smoothly, using `kill`.

**Comment by gmoskovicz** [comment]
`service logstash stop` is another way, but we need to explain which signal to send, so we stop the pipeline rather than kill only the process, as it will happen with `kill -9`.

**Comment by jordansissel** [comment]
We should document that here: https://www.elastic.co/guide/en/logstash/5.0/running-logstash.html

And any references to "start" or "stop" logstash should link to this page instead of providing a solution (ctrl+c) that may only work for some users.

**Comment by dedemorton** [comment]
Actually, I want to provide more info about what happens during a shutdown, so I'm renaming the following topic to "Shutting Down Logstash" and I'll add details about how to shut down Logstash there.

**Comment by jordansissel** [comment]
@dedemorton I like that idea ++

**Comment by jordansissel** [comment]
For adding to: https://www.elastic.co/guide/en/logstash/current/running-logstash.html

* systemd: systemctl stop logstash
* upstart: initctl stop logstash
* sysv: /etc/init.d/logstash stop
* If you have the PID: kill -TERM {logstash_pid}

**Comment by dedemorton** [comment]
Closed with #6771
