### ISSUE TITLE
Add https://github.com/angel9484/logstash-filter-lookup to logstash-plugins

### ISSUE THREAD

**Issue by angel9484** [elastic/logstash#4810]
URL https://github.com/angel9484/logstash-filter-lookup
Best regards!

**Comment by suyograo** [comment]
@angel9484 thanks for writing this filter!. Couple of questions:
* Would you be willing to rename this plugin to `logstash-filter-lookup`. This way we can get a generic filter plugin which can lookup values and replace it with matches from either a http webservice, local file etc. See https://github.com/logstash-plugins/logstash-filter-translate which deals with local file. `translate` is a bad name too
* What's the deal with Java tests and the pom.xml in your readme? Is that just an example?

**Comment by suyograo** [comment]
@angel9484 also, there's this: https://github.com/elastic/logstash/issues/3489 so it would be lovely if we can bring these into one such "lookup" plugin.

**Comment by angel9484** [comment]
Hello @suyograo!
Thanks to reply!
My intention was to write a PR to include this into logstash-filter-translate: https://github.com/logstash-plugins/logstash-filter-translate/pull/7
but this PR never merged into the plugin, don't know why.
The reason to make only this separated webservice plugin without file support, is because that, and because at work we want to use a webservice.
However, you're right! it will be great to merge the 3 plugins into one generic plugin. I will look the #3489 
Into the readme file are a functional example of a webservice to test the filter. It's better another place?

**Comment by angel9484** [comment]
The project is now renamed and republished as logstash-filter-lookup. No new functionalities however!
Now README hasn't the webservice example, instead, a folder called examples has it.
Regards!

**Comment by suyograo** [comment]
@angel9484 I've created https://github.com/logstash-plugins/logstash-filter-lookup. Can you please do a first PR there and we'll get it merged. Also would you mind merging the `logstash-filter-translate` functionality into this? Basically its the same file lookup functionality rolled into this one. This way we'll have one place to all this lookup magic!

Thanks for your contribution!

**Comment by angel9484** [comment]
@suyograo Ok!

**Comment by suyograo** [comment]
WIP:  https://github.com/logstash-plugins/logstash-filter-lookup
