### ISSUE TITLE
sync JAVA_OPTS strategy with ES

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4821]
This is related to ES issue elastic/elasticsearch#17121 which proposes to drop support for the _unofficially_ and _inconsistently_ supported `JAVA_OPTS` env var and only provide `ES_JAVA_OPTS`.

I agree with this strategy and we should sync with ES for consistency for passing JVM options and only support our own `LS_JAVA_OPTS` and drop `JAVA_OPTS`. This also relates to issue #2942 where this has been discussed in great length.

**Comment by jasontedor** [comment]
On the Elasticsearch side, I opened elastic/elasticsearch#17675. This drops support for `JAVA_OPTS`, removed all JVM-related environment variables, and adds a new jvm.options configuration file but still supports `ES_JAVA_OPTS` for ease of running from the command line. This effectively separates the configuration of the JVM from the packaging scripts.

**Comment by colinsurprenant** [comment]
closing - this has been done some time ago LS dropped support of JAVA_OPTS and is also using `jvm.options`.
