### ISSUE TITLE
How to check logstash  have listen snmptrap by logs?

### ISSUE THREAD

**Issue by andrewarnier** [elastic/logstash#4822]
I am a new to lostash and elastichsearch. I want to collection logs of network devices by snmptrap. I have a problem with logstash.

+snmptrapd.conf
`authCommunity log,net public`
`forward default localhost:1062`

+logstash-snmptrap.conf

input {
      snmptrap {
           community => "public"
           port => 1062
           type => "snmp_trap"
             }
         }

output {
if [type] == "snmp_trap" {
   file {
     codec => "rubydebug"
     flush_interval => 1
     path => "/tmp/logstash-snmptrap.log"
         }
      }
}

Is there any issue with the configuration ? Netstat output as follows,
`udp        0      0 0.0.0.0:162             0.0.0.0:* `
`udp6       0      0 :::1062                 :::*                                10771/java`

I didn't get any error msg when i execute the command as follows,
`root@pc:~# /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash-   
snmptrap.conf`

Settings: Default filter workers: 1
Logstash startup completed
Settings: Default filter workers: 1
Logstash startup completed

but I can't find the file "/tmp/logstash-snmptrap.log" , what's wrong with my logstash config ?

**Comment by suyograo** [comment]
@andrewarnier welcome. thanks for using Logstash. Can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
