### ISSUE TITLE
Java Event type casting conversion optimization

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4834]
While discussing over a possible type conversion bug in the Java Event @guyboertje suggested a very interesting new strategy to minimize the Ruby<->Java conversion costs.

Currently when setting an Event field value from the Ruby world, that value is converted into a pure Java object and stored into the Java event. Every time that field is read from the Ruby world later on, it is converted back into a proper Ruby object. There is obviously a cost to that type conversion which occurs at every field set and get.

@guyboertje's proposal is to create a Java value class for the Java Event that would store both Java and Ruby values representations. The actual type conversion would be done once and lazily only when required. For example, upon setting an initial value from the Ruby world into the Java Event, only the original Ruby value object would be stored into that new Java value class. Further read of that value fro the Ruby would would not require any type conversion, the original Ruby object could be directly be returned. If/when the Java Event need to access the Java object representation of that original Ruby value, then the original Ruby object would be converted once and store in that value class. If that Java representation of that value is read again, no conversion would be necessary.

The same idea would apply for the reverse case when a value would be originally set from the Java world and eventually read from the Ruby world.

This could very well significantly improve field access performance!

**Comment by guyboertje** [comment]
Woohoo - I want to do this, pick me, pick me.

**Comment by colinsurprenant** [comment]
@guyboertje you definitely are on the short list for a honorific "JRuby<->Java type conversion" PhD :laughing: so yeah, please do :thumbsup:

**Comment by guyboertje** [comment]
It is a little more complicated that I thought.  Timestamps being one problem where the RubyTimestamp wraps Java Timestamp.

**Comment by colinsurprenant** [comment]
which should not be a problem since we do have a proper Ruby class for it (as a JRuby ext) so the same logic can be applied?

**Comment by colinsurprenant** [comment]
Can we close this since #4999 is now merged?
