### ISSUE TITLE
Filebeat 1.1.1 could not scale higher - Performance Issue?

### ISSUE THREAD

**Issue by ykodgule** [elastic/logstash#4840]
Logstash 2.2.1
Filebeat filebeat-1.1.1-x86_64

Filebeat to Logstash can not keep up 500 small events per second.
- For 5 minutes of records generation, filebeat + logstash ran for 12 minutes before it completed.
- Logstash AVG CPU is 17%
- Filebeat AVG CPU is very small (< 10%)
- No cpu, disk, network bottleneck observed.

We tried with bulk_max_size=3000 as suggested from these links: 
https://github.com/elastic/beats/issues/587 
and 
https://discuss.elastic.co/t/performance-issues-with-input-beats-plugin/37516

and also increased filter worker threads from 8 to 10 but still did not help.

Is this is the ultimate limit on Filebeat? 
Or Logstash's Filebeat i/p plugin limits this?
Do we need more configs to be tried out?

**Comment by clems94** [comment]
I have the same problem

**Comment by clems94** [comment]
Hi

Did you try to add the parameter below to your section output of filebeat configuration 

workers: 4

**Comment by markwalkom** [comment]
Please join us at https://discuss.elastic.co/ or at #logstash on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)
