### ISSUE TITLE
logstash-output-s3 plugin error

### ISSUE THREAD

**Issue by wangxpeng** [elastic/logstash#4843]
I think this is a bug.
When I start the logstash, error log: 
"The error reported is: \n  initialize: name or service not known"
my logstash config file:  
...
region => "cn-north-1"
...

I check the request url: 
https://xxx.s3-cn-north-1.amazonaws.com
But when region is "cn-north-1", the url should be:
https://xxx.s3.cn-north-1.amazonaws.com.cn

Then I check the code, and found: 
vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.4/lib/logstash/outputs/s3.rb
ln 143:
:s3_endpoint => region_to_use == 'us-east-1' ? 's3.amazonaws.com' : "s3-#{region_to_use}.amazonaws.com

Then I modify this code, start success.

**Comment by wiibaa** [comment]
@wangxpeng can you please move this bug directly into the plugin issue tracker => https://github.com/logstash-plugins/logstash-output-s3/issues
Thanks

**Comment by wangxpeng** [comment]
OK, I'm sorry.^_^
