### ISSUE TITLE
Query ES with a log field before indexing 

### ISSUE THREAD

**Issue by sssh** [elastic/logstash#4848]
I am reading a csv log file which has zip code in one of its field. I have the details of this zips indexed in my ES index. Is there a filter to query ES with zip and get the details of it before logstash indexes this data, so that I can make more sense out of zip, which is just a number ? [Logstach-elasticsearch](https://www.elastic.co/guide/en/logstash/current/plugins-filters-elasticsearch.html) filter is closest I have found, but this queries the previous log event as per my understanding.

**Comment by markwalkom** [comment]
Please join us at https://discuss.elastic.co/ or at #elasticsearch on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)
