### ISSUE TITLE
[new plugin] - logstash-filter-language - detect language in field with CLD

### ISSUE THREAD

**Issue by thehybridtechnician** [elastic/logstash#4859]
https://github.com/thehybridtechnician/logstash-filter-language

Put this plugin together to detect language used in a field to specify which analyzer to use in Elasticsearch.

I would appreciate any help or improvements especially around testing.  Always ready to learn more.

**Comment by suyograo** [comment]
@thehybridtechnician neat stuff! created https://github.com/logstash-plugins/logstash-filter-language Can you create a PR to the new repo

**Comment by thehybridtechnician** [comment]
@suyograo - Absolutely.  Thank you!

**Comment by acchen97** [comment]
Merged in https://github.com/logstash-plugins/logstash-filter-language/pull/1.
