### ISSUE TITLE
failed with response of 400

### ISSUE THREAD

**Issue by andrewarnier** [elastic/logstash#4863]
Hi,
I am using logstash 2.1.3 on ubuntu 15.04. I tried to run my logstash config but get some error as follows,

+logstash-snmptrap.conf
input {
  snmptrap {
    community => "public"
    port => 1063
    type => "snmp_trap"
  }
}
output {
    elasticsearch { hosts => localhost }
   stdout {
         codec => rubydebug
       }
   file {
      codec => rubydebug
      flush_interval => 1
      path => "/tmp/logstash-snmptrap.log"
        }
}

When using this config , I get the following error in my logstash output:

"failed action with response of 400, dropping action" (full message is below)

Any idea what I've misconfigured?

Thanks in advance,

`Failed action.  {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2016.03.22", :_type=>"snmp_trap", :_routing=>nil}, #<LogStash::Event:0x28065b1 @metadata_accessors=#<LogStash::Util::Accessors:0x6da182fb @store={}, @lut={}>, @cancelled=false, @data={"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, @metadata={}, @accessors=#<LogStash::Util::Accessors:0x69a46f8e @store={"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, @lut={"type"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "type"], "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"], "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"], "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"], "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"], "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"], "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"], "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"], "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>[{"message"=>"#<SNMP::SNMPv1_Trap:0x4bb759ae @enterprise=[1.3.6.1.4.1.3607.6.10.30], @timestamp=#<SNMP::TimeTicks:0x63024a13 @value=15>, @varbind_list=[#<SNMP::VarBind:0x32358228 @name=[1.3.6.1.4.1.3607.6.10.100.10.20.1], @value=\"20080227205807S\">, #<SNMP::VarBind:0x433ec7e9 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.80.4103.220], @value=\"90\">, #<SNMP::VarBind:0x329d5f4f @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.20.4103.220], @value=\"670\">, #<SNMP::VarBind:0x2841bf5e @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.60.4103.220], @value=\"16386\">, #<SNMP::VarBind:0x367b5cbc @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.30.4103.220], @value=\"4\">, #<SNMP::VarBind:0x34fd415 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.40.4103.220], @value=\"10\">, #<SNMP::VarBind:0x5bf09414 @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.50.4103.220], @value=\"0\">, #<SNMP::VarBind:0x7e6e7b7b @name=[1.3.6.1.4.1.3607.6.10.20.30.20.1.100.4103.220], @value=\"testFAC-1-2\">], @specific_trap=220, @source_ip=\"127.0.0.1\", @agent_addr=#<SNMP::IpAddress:0x121c46b6 @value=\"\\x7F\\x00\\x00\\x01\">, @generic_trap=6>", "host"=>"127.0.0.1", "@version"=>"1", "@timestamp"=>"2016-03-22T01:07:10.278Z", "type"=>"snmp_trap", "SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1"=>"20080227205807S", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.80.4103.220"=>"90", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.20.4103.220"=>"670", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.60.4103.220"=>"16386", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.30.4103.220"=>"4", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.40.4103.220"=>"10", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.50.4103.220"=>"0", "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"=>"testFAC-1-2"}, "SNMPv2-SMI::enterprises.3607.6.10.20.30.20.1.100.4103.220"]}>>], :response=>{"create"=>{"_index"=>"logstash-2016.03.22", "_type"=>"snmp_trap", "_id"=>"AVOb3Hpteywo7olt5FB1", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field name [SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1] cannot contain '.'"}}}, :level=>:warn}
`

**Comment by suyograo** [comment]
See `Field name [SNMPv2-SMI::enterprises.3607.6.10.100.10.20.1] cannot contain '.'"}}}, :level=>:warn}`

https://www.elastic.co/blog/introducing-the-de_dot-filter

Also, can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
