### ISSUE TITLE
logtash server 2.2.2 - messages only flow in slowly

### ISSUE THREAD

**Issue by danielsand** [elastic/logstash#4864]
Hey Folks,

we are recently switch from logstash 1.4.x to logstash 2.2.x and using a pretty simple setup

input:
- lumberjack with ssl cert

output:
- elasticsearch ( local cluster )
- GELF ( Graylog2 )

we have around 150-200 systems to give you a number.

so before we had roughly around 10k 20k messages per minute. 
Now with logstash 2.2.2 we have around - 10-150 per minute

when i restart the logstash server,  for a brief second - around 15k - 20k messages get delivered.
Then all goes back to slowly delivering messages.

logs show nothing at all. neither on sender or receiver side.

i tried to tweak the
--pipeline-workers, --pipeline-batch-size, and --pipeline-batch-delay. The --pipeline-worker
parameters because i thought this was the bottleneck - but no result at all. Also tweak the Heap size.

currently im running on 8Gb memory 2000 Messages per worker which are in total 4.

so any tips ?
I have digged through the performance tweaking page and didn't find much more to look at.

the current server config
```
input {
  lumberjack {
    port => 5000
    ssl_certificate => "/etc/ssl/certs/logstash.crt"
    ssl_key => "/etc/ssl/private/logstash.key"
    codec => "json"
  }
}
input {
  syslog {
    tags => [ "syslog" ]
    port => 514
	type => "rsyslog"
  }

}

filter {
  if [type] == "rsyslog" {
      grok {
        match => [ "message",  "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" ]
      }
  }
}

output {
  gelf {
    host => ["127.0.0.1"]
 }
}
output {
  elasticsearch { hosts => ["127.0.0.1"] }
}
```

**Comment by danielsand** [comment]
i create 3 logstash servers with the same settings and put a TCP LB in front to share the load.

the effect seems the same - but more messages are now flowing in.

This is a histogram of 2 hours
each time i restarted one of the logstash servers a big push of messages come immediately through. then it clogs again.

![logstash_metrics_reveided_histogram](https://cloud.githubusercontent.com/assets/594865/13955179/01f1d020-f044-11e5-983a-bf25963c74b0.png)

**Comment by suyograo** [comment]
This is concerning. Whats the # of cores in your system? `--pipeline-worker` will be set to that. Also, can you get us 5 jstack dumps, each in 2 sec intervals?

**Comment by danielsand** [comment]
4 cores in each of the 3 systems. i tweaked already the --pipeline-worker lower and higher settings which hat no effect. So its defaulting currently to 4 again.

current cmd line options:
```
/usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=/var/lib/logstash -Xmx8g -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=/var/lib/logstash -XX:HeapDumpPath=/opt/logstash/heapdump.hprof -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log -b 2000
```

i needed to force the dump with jstack - here is the gist

https://gist.github.com/anonymous/24236c0bebe4c0be8c5b

**Comment by danielsand** [comment]
@suyograo hey again - you have any idea what is the problem ?
Currently im in a tight spot because this system is already productive and i dont really want to change to another solution.
