### ISSUE TITLE
Have ability to keep conf files seperate but listening to same input

### ISSUE THREAD

**Issue by NikolaeVarius** [elastic/logstash#4865]
I was wondering if it would be possible/advisable to try and see if there is a way to have logstash be aware of multiple conf files listening for the same reasource and then have it automaticall munge all conf files using that same resource into one thread.

Right now, we have to open tons of firewall ports in order to open servers to logstash and its quickly becoming complicated to deal with knowing that ports are open for what kind of log file.

Ideally we want all logs to go to a single port and have logstash deal with the logic for that input with type tags. However the issue is we can't have multiple conf files that have the same input because logstash will attempt to start multiple processes listening on a single port.

Any ideas?

**Comment by suyograo** [comment]
> However the issue is we can't have multiple conf files that have the same input because logstash will attempt to start multiple processes listening on a single port.

If you have the same ports specified, what would you have _different_ in the other config file snippets?
