### ISSUE TITLE
Create rake task to set version

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4875]
There are several places in LS now where version needs to be bumped which is error prone when done manually. See for example https://github.com/elastic/logstash/pull/4870/files. Most often, versions are the same, unless we make changes to core, but not the event?

Create an rake task to set version which will update all these files

```
rake release:set-version 5.0.0-alpha2
```

This script should also validate if version is in the acceptable format.

**Comment by jsvd** [comment]
done in https://github.com/elastic/logstash/commit/a859bd4a3fd71ac0b65d248988a2d30812ee3a63
