### ISSUE TITLE
Create rake task to build and publish gems

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4876]
For a single LS release, we need to publish 3 gems. Create a rake task to do `gem build... ` and then `gem push ...`

The 3 gems are:
* logstash-core
* logstash-core-event
* logstash-core-event-java

```
rake release:publish-gems
```

This version assumes the version has been bumped

**Comment by ph** [comment]
Because of #4829 I have created a rake task to generate the gems. we can reuse it.

**Comment by ph** [comment]
Just to make sure the build workflow will now look something (I used individual task here for simplicity)
```
rake bootstrap
rake release:update-version[5.0.0] # could be manual.
rake release:publish-gems
rake artifacts:tar
rake artifacts:deb
rake artifacts:zip
rake artifacts:rpm
```

**Comment by jsvd** [comment]
done in https://github.com/elastic/logstash/commit/a859bd4a3fd71ac0b65d248988a2d30812ee3a63

**Comment by jsvd** [comment]
actually keeping this open since we have the first half (a task to create the gems) but now to publish gem.
I think we won't actually need it since that will be taken care of by the umbrella tool that publishes all artifacts

**Comment by suyograo** [comment]
Yeah, not needed as you mentioned.
