### ISSUE TITLE
How to import my Vendor’s MIBs?

### ISSUE THREAD

**Issue by andrewarnier** [elastic/logstash#4878]
hi all,
how to import my Vendor's MIBs ?

If anyone knows how to do with it , please help. Thanks.

**Comment by ebuildy** [comment]
What is that ?

**Comment by purbon** [comment]
Hi,
 It will be necessary for you to provide more details about your request,
so we know what you exactly aim to process.

- purbon

**Comment by purbon** [comment]
Closing this issue for now as not more information is reported, please feel free to reopen when more information could be provided, or also feel free to ask in our discuss forums (https://discuss.elastic.co) we tend to keep this mostly for project issues.
