### ISSUE TITLE
logstash zabbix

### ISSUE THREAD

**Issue by wushun18** [elastic/logstash#4888]
The error reported is: 
  Couldn't find any output plugin named 'zabbix'. Are you sure this is correct? Trying to load the zabbix output plugin resulted in this error: no such file to load -- logstash/outputs/zabbix

output {
	zabbix {
		zabbix_host => "172.18.21.15"
		zabbix_key => "elk"
		zabbix_server_host => "172.18.20.12"
		zabbix_server_port => 10051
	}
}

logstash support  logstash-output-zabbix.where is wrong?

**Comment by untergeek** [comment]
The zabbix output plugin is not installed by default, as it is a community supported plugin.  You need to install it by first, `cd /path/to/logstash/install`, and then:

```
bin/plugin install logstash-output-zabbix
```

This requires network access, as it will pull the plugin and dependencies from rubygems.org
