### ISSUE TITLE
Mass publishing Fails for 2.3, the "logstash-core-plugin-api" update

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4890]
When I ran the mass publishing script to deploy the change for the dependency on `logstash-core-plugin-api` some plugins did not succesfully publish. We need to investigate those.

Also some tests are failling for the plugins, it may be a regression.

## Plugins that failed the mass publish process

- [x] logstash-input-syslog [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-input-syslog-unit/jdk=JDK7,nodes=metal-pool/)
  - [x] in progress

- [x] logstash-filter-mutate [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-filter-mutate-unit/jdk=JDKEA8,nodes=metal-pool/32/)
  - [x] in progress

- [x] logstash-input-syslog [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-input-syslog-unit/)
  - [x] in progress

- [x] logstash-output-syslog [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-output-syslog-unit/24/)
  - [x] in progress

- [x] logstash-patterns-core [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-patterns-core-unit/45/jdk=JDK8,nodes=metal-pool/)
  - [x] in progress

- [x] logstash-output-lumberjack 1 # Did not correctly pushed, new version is not on rubygems
  - [x] in progress

- [x] logstash-output-kafka 1 # Did not correctly pushed, new version is not on rubygems
  - [x] in progress

## Other plugins that also fails.
- [x] logstash-codec-cef [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-codec-cef-unit/jdk=JDKEA8,nodes=metal-pool/lastBuild/)
  - [x] in progress (PR: https://github.com/logstash-plugins/logstash-codec-cef/pull/18)

- [ ] logstash-filter-aggregate [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-filter-aggregate-unit/18/)
  - [x] in progress

- [x] logstash-filter-environment [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-filter-environment-unit/12/)
  - [ ] in progress

- [ ] logstash-filter-i18n [test failed](http://build-eu-1.elasticsearch.org/job/logstash-plugin-filter-i18n-unit/12/)
  - [ ] in progress

logstash-filter-oui 1
logstash-filter-tld 1
logstash-input-cloudwatch 18
logstash-input-neo4j 1
logstash-input-neo4j 1
logstash-input-rackspace 1
logstash-output-elasticsearch_http 1
logstash-output-google_bigquery 1
logstash-output-google_cloud_storage 1
logstash-output-influxdb 1
logstash-output-jms 1
logstash-output-mongodb 1
logstash-output-neo4j 1
logstash-output-rackspace 1

**Comment by IngaFeick** [comment]
+1 
Testing 2.3 with output influxdb, does not work but also does not produce any errors. The data just vanishes.

**Comment by ph** [comment]
I will revisit the other plugins to see what is going on.
