### ISSUE TITLE
Broken tcp/udp/websocket server output – 'Address already in use' error

### ISSUE THREAD

**Issue by galkin** [elastic/logstash#4892]
On all server output (tcp, udp, websocket, etc) we have error `Address already in use - bind - Address already in use`.

This problem opened at [discuss.elastic.co](https://discuss.elastic.co/t/tcp-server-output-address-already-in-use-after-upgrade-to-2-2/43501) 3 weeks ago, but steel not resolved.

[Example for demonstrate the error](https://gist.github.com/davemac30/7a12cda7e7b7d6d7a69d) 

Can somebody help?

**Comment by bluestix** [comment]
Having same issue running in docker. Any workaround or fix would be appreciated.

**Comment by galkin** [comment]
Fixed at [v2.3.0](https://github.com/elastic/logstash/releases/tag/v2.3.0)
