### ISSUE TITLE
how to add one more community  for snmptrap?

### ISSUE THREAD

**Issue by andrewarnier** [elastic/logstash#4896]
hi all ,
i have defined one community ,but how to add one more community in my config ?

`input {`
 `snmptrap {`
   ` community => "public"`
    ` type => "trap"`
      `}`
`}`

Thanks in advance,

**Comment by wiibaa** [comment]
Hello,

I admit that the documentation https://www.elastic.co/guide/en/logstash/2.2/plugins-inputs-snmptrap.html is scarce on examples

but the important point is that **community** config accepts **array**, so the following config should be valid `community => ["public", "onemore"]`

Just a kind reminder for next time:
* usage question are best answered on : https://discuss.elastic.co/c/logstash
* bug must be reported in the specific plugin issue tracker => https://github.com/logstash-plugins/logstash-input-snmptrap/issues

**Comment by suyograo** [comment]
Please move questions to https://discuss.elastic.co/c/logstash

Thanks @wiibaa :)
