### ISSUE TITLE
Test on master failing with NPE on HotThreadsCommand#schema

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#4909]
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-os-compatibility/os=ubuntu/lastBuild/console

Error is:

```
2) JVM stats LogStash::Api::HotThreadsCommand#schema return hot threads information
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaLang::NullPointerException:
     # com.purbon.jrmonitor.monitors.HotThreadsMonitor$ThreadReport.<init>(HotThreadsMonitor.java:36)
     # com.purbon.jrmonitor.monitors.HotThreadsMonitor.detect(HotThreadsMonitor.java:146)
     # com.purbon.jrmonitor.reports.RubyThreadsReport.generate(RubyThreadsReport.java:41)
     # com.purbon.jrmonitor.reports.RubyThreadsReport$INVOKER$s$generate.call(RubyThreadsReport$INVOKER$s$generate.gen)
```

**Comment by purbon** [comment]
working on this, //cc @ph

**Comment by purbon** [comment]
should be fixed by the release of https://rubygems.org/gems/jruby-monitoring/versions/0.3.1

**Comment by jsvd** [comment]
nice. thanks! can you link to the issue in the jruby-monitoring project?

**Comment by jsvd** [comment]
also, https://github.com/elastic/logstash/blob/master/logstash-core/logstash-core.gemspec#L33 should probably bumped to be at least 0.3.1, no?

**Comment by purbon** [comment]
is going to fetch it anyway, but yes we can bump the versions.

**Comment by ph** [comment]
lets bump it, quick turn around @purbon and good find @jsvd

**Comment by purbon** [comment]
done https://github.com/elastic/logstash/pull/4911
