### ISSUE TITLE
More clarity on dynamic reload error

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#4921]
Dynamic config reloading doesn't support usage of certain plugins like stdin input.  The outputted error message should be more clear to users.

Current:
"Logstash was not able to load configuration since it does not support dynamic reloading and -r or --auto-reload flag was enabled {:pipeline_id=>"main", :plugins=>[LogStash::Inputs::Stdin], :level=>:error}"

Proposed:
"Logstash was not able to dynamically load configuration (-r or --auto-reload flag) due to unsupported plugin(s). {:pipeline_id=>"main", :plugins=>[LogStash::Inputs::Stdin], :level=>:error}"

**Comment by pmusa** [comment]
+1

**Comment by pmusa** [comment]
I think it was solved in #4862

**Comment by jsvd** [comment]
proposed an alternative error message in #5270, what do you think @acchen97 @pmusa ?

**Comment by pmusa** [comment]
LGTM, curious about ".." instead of 1 or 3 :P
