### ISSUE TITLE
More metrics for monitoring API

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#4923]
Outlining plan to augment the following monitoring API endpoints with additional metrics ([phase 1](https://github.com/elastic/logstash/issues/4446)):
* Root Resource (/) - retrieve general node information
* Node Info (/_node) - retrieve node information
* Node Stats (/_node/stats) - retrieve current node statistics
* Hot Threads (/_node/hot_threads) - retrieve current node hot threads
* Plugins (/_plugins) - retrieve plugin information and statistics

# Additional Metrics
### Node Stats
| Metrics | Namespace | API Resource |
----------- | ------ | -------- | --------- |
Events In [bytes] | stats.events.in | /_node/stats/events |
Events Filtered [bytes] | stats.events.filtered | /_node/stats/events |
Events Out [bytes] | stats.events.out | /_node/stats/events |
Thread Count | stats.jvm.threads.count | /_node/stats/jvm |
Peak Thread Count | stats.jvm.threads.peak_count | /_node/stats/jvm |
Number of Open File Descriptors | stats.process.open_file_descriptors | /_node/stats/process |
Peak Open File Descriptors | stats.process.peak_open_file_descriptors | /_node/stats/process |
Max File Descriptors | stats.process.max_file_descriptors | /_node/stats/process |
CPU Usage (%) | stats.process.cpu.percent | /_node/stats/process/cpu |
CPU Time | stats.process.cpu.total_in_millis | /_node/stats/process/cpu |
Virtual Memory - Total | stats.process.mem.total_virtual_in_bytes | /_node/stats/process/mem

```
{
    "events": {
        "in": 91,
        "bytes_in": 900000
        "filtered": 91,
        "bytes_filtered": 900000
        "out": 91
        "bytes_out": 900000
    },
    "threads": {
        "count": 12,
        "peak_count": 12
    },
    "process": {
        "open_file_descriptors": 200,
        "max_file_descriptors": 400,
        "cpu": {
            "percent": 20,
            "total_in_millis": 30081091
        },
        "mem": {
            "total_virtual_in_bytes": 5621555200
        }
    }
}
```

### Node Info
| Metrics | Namespace | API Resource |
----------- | ------ | -------- | --------- |
Pipeline Workers | pipeline.workers | /_node/pipeline |
Pipeline Batch Size | pipeline.batch_size | /_node/pipeline |
Pipeline Batch Delay | pipeline.batch_delay | /_node/pipeline |
OS Name | os.name | /_node/os |
OS Architecture | os.arch | /_node/os |
OS Version | os.version | /_node/os |
OS Available Processors | os.available_processors | /_node/os |
JVM PID | jvm.pid | /_node/jvm |
JVM Version | jvm.version | /_node/jvm |
JVM VM Name | jvm.vm_name | /_node/jvm |
JVM VM Version | jvm.vm_version | /_node/jvm |
JVM VM Vendor | jvm.vm_vendor | /_node/jvm |
JVM Start Time | jvm.start_time_in_millis | /_node/jvm |
JVM Memory Heap Init | jvm.mem.heap_init_in_bytes | /_node/jvm |
JVM Memory Heap Max | jvm.mem.heap_max_in_bytes | /_node/jvm |
JVM Memory Direct Max | jvm.mem.direct_max_in_bytes | /_node/jvm

```
{
    "pipeline": {
        "workers": 12,
        "batch_size": 125,
        "batch_delay": 50
    },
    "os": {
        "name": "Mac OS X",
        "arch": "x86_64",
        "version": "10.11.2",
        "available_processors": 4,
        "allocated_processors": 4
    },
    "jvm": {
        "pid": 8667,
        "version": "1.8.0_45",
        "vm_name": "Java HotSpot(TM) 64-Bit Server VM",
        "vm_version": "25.45-b02",
        "vm_vendor": "Oracle Corporation",
        "start_time_in_millis": 1456775585344,
        "mem": {
          "heap_init_in_bytes": 268435456,
          "heap_max_in_bytes": 1038876672,
          "direct_max_in_bytes": 1038876672
        }
    }
}
```

### Root
| Metrics | Namespace | API Resource |
----------- | ------ | -------- | --------- |
UUID | id | / |
Instance Name | name | / |
```
{
   "host": "127.0.0.1",
    "version" : {
        "number" : "2.1.0",
    },
    "uuid": "3ee62187-1f88-4944-bf2d-1326e0dca42f",
    "name": "skywalker"
}
```

### Node Stats
| Metrics | Namespace | API Resource |
----------- | ------ | -------- | --------- |
Queue Size | stats.queue.size | /_node/stats/pipeline/queue |
Queue Max Size | stats.queue.max_size | /_node/stats/pipeline/queue
Other Queue Stats (revisit later) | - | - 

## Plugins

This section has moved to https://github.com/elastic/logstash/issues/5428

**Comment by andrewvc** [comment]
@acchen97 since there's no sensible way to determine bytesize of events I've replaced metrics like `bytes_in` with `in` which is just the # of events.

**Comment by andrewvc** [comment]
I've added a new `open_file_descriptors_peak` metric since that would seem useful.

**Comment by acchen97** [comment]
@andrewvc the # events in/filtered/out is already implemented.  "How many GB of data am I processing a day?" is a common question.  Is it difficult to get the byte size of even just the initial event coming in?

**Comment by andrewvc** [comment]
I removed os.allocated processors since that is ES specific

**Comment by andrewvc** [comment]
@acchen97 I assume by directMax you meant nonHeap? I'm pulling from sources here https://github.com/elastic/elasticsearch/blob/34da01f794ba892176376aafc18e901cacdd0fce/core/src/main/java/org/elasticsearch/monitor/jvm/JvmInfo.java

**Comment by acchen97** [comment]
@andrewvc there's a [direct](https://github.com/elastic/elasticsearch/blob/34da01f794ba892176376aafc18e901cacdd0fce/core/src/main/java/org/elasticsearch/monitor/jvm/JvmInfo.java#L78) memory max.  With your experience, do you find non heap stats to be helpful as well for troubleshooting?

**Comment by acchen97** [comment]
Closed in favor of https://github.com/elastic/logstash/issues/5475
