### ISSUE TITLE
Plugin for collecting performance counters.

### ISSUE THREAD

**Issue by Suren92** [elastic/logstash#4924]
Is there any plugin for collecting the performance counters of a windows system. I tried wmi plugin but I am getting an error saying 

"The error reported is:
  undefined method `value' for nil:NilClass"

is there any solution for the error or is there any other plugin through which I can collect the performance counters. 

Any information regarding this will be helpful.

Thanks!

**Comment by markwalkom** [comment]
Please join us at https://discuss.elastic.co/ or at #logstash on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)
