### ISSUE TITLE
rabbitmq input plugin fails to honor verify_ssl option

### ISSUE THREAD

**Issue by sjsadowski** [elastic/logstash#4927]
Docs here:
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html#plugins-inputs-rabbitmq-verify_ssl

Expected: when set to true, an invalid or self-signed certificate will prevent a connection

Actual: This option is never honored, whether true or false. Always connects.

Edit to clarify: when looking through source in the gem, this option is never checked.

**Comment by andrewvc** [comment]
Thanks for reporting this @sjsadowski ! It is very much appreciated. This has been merged in https://github.com/elastic/logstash/issues/4927 . Updated plugins will be released very soon.
