### ISSUE TITLE
Change bin/plugin to bin/logstash-plugin

### ISSUE THREAD

**Issue by michalterbert** [elastic/logstash#4942]
Logstash 2.3.0.

Please take a look and fix this very small issue ;)
`/opt/logstash/bin/logstash-plugin --help
Usage:
    bin/plugin [OPTIONS] SUBCOMMAND [ARG] ...`

`~# /opt/logstash/bin/logstash-plugin remove logstash-input-ganglia
ERROR: No such sub-command 'remove'
See: 'bin/plugin --help'`

`~# /opt/logstash/bin/plugin dupa
The use of bin/plugin is deprecated and will be removed in a feature release. Please use bin/logstash-plugin.
ERROR: No such sub-command 'dupa'
See: 'bin/plugin --help'`

**Comment by purbon** [comment]
@michalterbert thanks for your report, this is actually a sad inconsistency, will fix soon, be aware however that the different actions will work anyway, just showing this misleading feedback..

**Comment by purbon** [comment]
Fix for this got created at #4945

**Comment by purbon** [comment]
Fixed
