### ISSUE TITLE
Logstash 2.3 JDBC Input Problem

### ISSUE THREAD

**Issue by powderedegg** [elastic/logstash#4949]
Hi,

When trying to use logstash-2.3.0-1 with the JDBC input with Oracle 11g (https://www.elastic.co/blog/visualising-oracle-performance-data-with-the-elastic-stack) doesn't work with the statement command.   It looks to be failing to pick up the "V$" portion of the statement "SELECT * FROM V$ACTIVE_SESSION_HISTORY"

If I downgrade to logstash-2.2.2-1 it works fine.

**Logstash Config Input:**

input {
	jdbc {
		jdbc_validate_connection => true
		jdbc_connection_string => "jdbc:oracle:thin:@xxxxx:1521/xxxxx"
		jdbc_user => "xxxxx"
		jdbc_password => "xxxxx"
		jdbc_driver_library => "/opt/ojdbc7.jar"
		jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
		statement => "SELECT * FROM V$ACTIVE_SESSION_HISTORY WHERE SAMPLE_TIME > :sql_last_value"
		last_run_metadata_path => "/tmp/logstash-oradb.lastrun"
		record_last_run => true
		schedule => "*/2 * * * *"
	}
}

**Error Returned:**

./logstash -f /etc/logstash/conf.d/05-oracle-perf.conf
fetched an invalid config {:config=>"input {\n\tjdbc {\n\t \tjdbc_validate_connection => true\n\t\tjdbc_connection_string => \"jdbc:oracle:thin:@xxxxx:1521/xxxxx\"\n\t\tjdbc_user => \"xxxxx\"\n\t \tjdbc_password => \"xxxxx\"\n\t\tjdbc_driver_library => \"/opt/ojdbc7.jar\"\n\t\tjdbc_driver_class => \"Java::oracle.jdbc.driver.OracleDriver\"\n\t\tstatement => \"SELECT * FROM V\\$ACTIVE_SESSION_HISTORY WHERE SAMPLE_TIME > :sql_last_value\"\n \t\tlast_run_metadata_path => \"/tmp/logstash-oradb.lastrun\"\n\t
\trecord_last_run => true\n\t\tschedule => \"*/2 * * * *\"\n\t}\n}\n \nfilter {\n\tmutate { convert => [ \"sample_time\", \"string\" ] }\n \tdate { match => [ \"sample_time\" , \"ISO8601\" ] }\n}\n\noutput {\n \tstdout { codec => rubydebug }\n\telasticsearch { hosts => [\"10.16.0.121:9200\"] }\n}\n\n", :reason=>"Cannot evaluate ` $ACTIVE_SESSION_HISTORY`. Environment variable `ACTIVE_SESSION_HISTORY` is not set and there is no default value given.", :level=>:error}

**Comment by andrewvc** [comment]
Hi, apologies. This will be fixed shortly. We're targeting a fix for 2.3.1 where we'll revert to the old variable interpolation behavior. You can track this with this issue: https://github.com/elastic/logstash/issues/4958

**Comment by ph** [comment]
Thanks for reporting this! This is the same problem as https://github.com/elastic/logstash/issues/4953 Logstash 2.3.0 shipped with a environment variable interpolation for all the string we will be releasing 2.3.1 with a fix for follow #4958.
