### ISSUE TITLE
Logstash  service not starting?????? No Command Given

### ISSUE THREAD

**Issue by balaanand** [elastic/logstash#4951]
Dear,
Im very new new to logstash. I installed and started the elasticsearch service by giving the following command in terminal $ bin/elasticsearch

If i try the same process as $**bin/logstash** it's giving error as No Command given.
Im trying in logstash-2.3.0 version and faced the same error in logstash-2.2.2 also.

Even i tried this command also to start the logstash ==> **./logstash -f /logstash_accidents.conf -v**
gives error as : _translation missing:en.logstash.runner.configuration.file-not-found {:level+>:error}
starting agent {:level=>info}_
![screenshot from 2016-03-31 13_23_10](https://cloud.githubusercontent.com/assets/17297365/14174081/be67c56c-f75f-11e5-9334-acbb7ee104fe.png)
![screenshot from 2016-03-31 13_21_38](https://cloud.githubusercontent.com/assets/17297365/14174089/c6345062-f75f-11e5-9f28-6e21b19ed2b6.png)

**Comment by sjsadowski** [comment]
Try running 'logstash agent' as the output suggests. This is the expected behaviour if you simply use the 'logstash' command.

**Comment by ph** [comment]
I think the path to your configuration is incorrect, 
Assuming your logstash configuration is inside the logstash directory you need to start it with this path.

```
./logstash -f ./logstash_accidents.conf -v
```
**note the . before the logstash_accidents.conf**

**Comment by balaanand** [comment]
Thanks for your answer. 
Once i gave the **./logstash -f ./logstash-accidents.conf -v** it leads to an termination by showing some error. For your kind reference i added the screenshot of the issue. Add your suggestion.
![screenshot from 2016-04-01 16_36_54](https://cloud.githubusercontent.com/assets/17297365/14205527/7008e3fe-f829-11e5-8ebe-d2473882cb65.png)
![screenshot from 2016-04-01 16_38_08](https://cloud.githubusercontent.com/assets/17297365/14205533/82ebba32-f829-11e5-9b38-ac0271f0cde0.png)

**Comment by balaanand** [comment]
Thanks for your answer.
Once i gave the **./logstash -f ./logstash-accidents.conf -v** it leads to
an termination by showing some error. For your kind reference i added the
screenshot of the issue. Add your suggestion.



input {
    file {
        path => "/home/animalar/Downloads/FINAL1.csv"
        start_position => beginning
    }
}
filter {
    csv {
        columns => [
          "Accident_Index",
          "Type of vehicle",
          "VehicleName",
          "Longitude",
          "Latitude",
          "Location_Easting_OSGR",
          "State",
          "City",
          "Day_of_Week",
          "Time",
          "Speed_limit",
          "Road_Type",
          "Urban_or_Rural_Area",
          "Pedestrian_Crossing-Human_Control",
          "Light_Conditions",
          "Weather_Conditions",
          "Road_Surface_Conditions",
          "Did_Police_Officer_Attend_Scene_of_Accident",
          "Number_of_Vehicles"
        ]
        separator => ","
        }
}
output {
    elasticsearch {
        protocol => "http"
        host => localhost
        action => "index"
        index => "accidents"
    }
    stdout { }
}


my .conf file



On Thu, Mar 31, 2016 at 11:52 PM, Pier-Hugues Pellerin <
notifications@github.com> wrote:

> I think the path to your configuration is incorrect,
> Assuming your logstash configuration is inside the logstash directory you
> need to start it with this path.
>
> ./logstash -f ./logstash_accidents.conf -v
>
> *note the . before the logstash_accidents.conf*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/4951#issuecomment-204063874>
>



-- 



*REGARDS,*

*M.BALAANAND,*

*8807700218.**" Give and Forget !!!!  Get n don't forget !!!! "*

**Comment by purbon** [comment]
hi, it would be nice to get the full exception, from your screenshots it looks like it's cut somehow.

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
