### ISSUE TITLE
Logstash on Solaris is not using the systems file descriptor limits

### ISSUE THREAD

**Issue by darinfisher** [elastic/logstash#4962]
Logstash on Solaris is not using the systems file descriptor limits.

{:timestamp=>"2016-03-31T09:27:41.789000-0700", :message=>"Reached open files limit: 4095, set by the 'max_open_files' option or default, files yet to open: 386542", :level=>:warn} 
{:timestamp=>"2016-03-31T09:28:07.027000-0700", :message=>"Reached open files limit: 4095, set by the 'max_open_files' option or default, files yet to open: 386542", :level=>:warn} 
{:timestamp=>"2016-03-31T09:28:34.952000-0700", :message=>"Reached open files limit: 4095, set by the 'max_open_files' option or default, files yet to open: 386542", :level=>:warn} 
{:timestamp=>"2016-03-31T09:29:02.224000-0700", :message=>"Reached open files limit: 4095, set by the 'max_open_files' option or default, files yet to open: 386542", :level=>:warn}

[Thu Mar 31 09:36:04 root@dc1re02:/opt/logstash/current/bin ] # /usr/ucb/ps auxwww | grep logstash 
root 22560 3.6 2.122208482000484 ? O 09:21:21 20:15 /opt/java/jdk1.8.0_45/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Xmx2g -Xss2048k -Djffi.boot.library.path=/opt/logstash/logstash-2.2.2/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/logstash/current/heapdump.hprof -Xbootclasspath/a:/opt/logstash/logstash-2.2.2/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/logstash-2.2.2/vendor/jruby -Djruby.lib=/opt/logstash/logstash-2.2.2/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/current/lib/bootstrap/environment.rb logstash/runner.rb agent --config /opt/logstash/config -w 1 --log /var/log/logstash.log 
root 12092 0.0 0.0 1428 832 pts/2 S 09:36:07 0:00 grep logstash 
[Thu Mar 31 09:36:07 root@dc1re02:/opt/logstash/current/bin ] # plimit 22560 
22560: /opt/java/jdk1.8.0_45/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepG 
resource current maximum 
time(seconds) unlimited unlimited 
file(blocks) unlimited unlimited 
data(kbytes) unlimited unlimited 
stack(kbytes) 10240 unlimited 
coredump(blocks) unlimited unlimited 
nofiles(descriptors) 65536 65536 
vmemory(kbytes) unlimited unlimited 
[Thu Mar 31 09:36:12 root@dc1re02:/opt/logstash/current/bin ] #

**Comment by purbon** [comment]
I'm sorry to tell you we don't actually support Solaris and also test on it, so it's hard for us to narrow this down, we would however accept any improvements to make it works awesome there.

Closing this now as is an issue on a non supported platform.
