### ISSUE TITLE
Move repos to major version structuring

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#4967]
ES does this and makes operational management for upgrades a lot easier.

Can we change this so LS works the same? ie;
```
deb http://packages.elastic.co/logstash/2.x/debian stable main
```

**Comment by dhollinger** [comment]
I second this. My last two places of work have used Spacewalk for Package and Patch Management on our Linux systems and having to add a new Repo/Channel, then sync it to all our environments is a lot of work for a minor or bug fix release.

**Comment by untergeek** [comment]
@suyograo, is this still something we want to pursue?  I see you removed some tags.  I can make a "5.x" alongside the current 5.0, and we can keep both active until release, or beta, or something like that.

**Comment by untergeek** [comment]
Closed, per internal discussion.

**Comment by dhollinger** [comment]
@untergeek What was the decision on this, if I may ask?

**Comment by untergeek** [comment]
Our "unified release" implementation will handle this in the future.  This plan is being piloted by a different team in the company.  I'm not sure what the final structure will look like, but it should go to a major version structure, if I understand the plan correctly.
