### ISSUE TITLE
Logstash not consuming from RabbitMQ 

### ISSUE THREAD

**Issue by sornalingam** [elastic/logstash#4973]
I have configured Logstash to consume input from RabbitMQ. 

When I run this using   `./bin/logstash -f  sample.conf ` it is consuming message from Rabbitmq. 

But when I add my config file in the following path  `sudo vi /etc/logstash/conf.d/sample.conf ` 
and  start logstash   `sudo systemctl start  logstash` it is not consuming message from Rabbitmq. 

Following is my input setup 

```
input { 
beats {port => 5044}
rabbitmq {
  type => "XXXXX"
    host =>  "YYYYYYY"
  queue => "ZZZZZZZ"
        port => 5672
		user => "user"
		password => "password"
               connection_timeout => 30
subscription_retry_interval_seconds  => 5
durable => true  
}
```

What went wrong ?

**Comment by markwalkom** [comment]
Please join us at https://discuss.elastic.co/ or at #elasticsearch on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)
