### ISSUE TITLE
JRuby 1.7.24 regex thread safety regression

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4977]
per logstash-plugins/logstash-filter-useragent#25 and logstash-plugins/logstash-filter-useragent#26 it seems that the JRuby regex code is not thread safe. 

We need to
1- confirm that the JRuby regex implementation is not thread safe
2- if it's a bug, report and/or submit fix
3- verify out usage of regexes to make sure this problem does not surface elsewhere.

**Comment by colinsurprenant** [comment]
Per jruby/jruby#3670 this seems to be a regression in JRuby 1.7.24.

**Comment by colinsurprenant** [comment]
I suggest we downgrade to 1.7.23 for 2.3.1.  We just need to asses if some critical 2.3 bugs were fixed by 1.7.24 /cc @jsvd

**Comment by colinsurprenant** [comment]
per @jsvd the only critical issue 1.7.24 solved was the windows file stat problem

**Comment by ph** [comment]
IIRC the .24 was a release that fix an issue with windows 7 with the File.stats and a thread satefy issue. https://github.com/jruby/jruby/issues/3525

**Comment by ph** [comment]
http://jruby.org/2015/11/24/jruby-1-7-23.html

JRuby 1.7.23 fixed the memory leaks on recent windows 2012 server etc, are we thinking about reverting back to .23?

**Comment by jsvd** [comment]
if the fix in .24 targets only win7 it might be reasonable to switch to .23 for now and send out a big warning

**Comment by outcoldman** [comment]
Which version has this fix?
I see this issue in logstash 5.4.2

**Comment by jsvd** [comment]
@outcoldman can you provide some information on what you're seeing? there are many situations present in this issue

**Comment by outcoldman** [comment]
@jsvd created an issue for useragent plugin https://github.com/logstash-plugins/logstash-filter-useragent/issues/47 with some additional information, let me know if you need more info

**Comment by outcoldman** [comment]
@jsvd and about versions

```
$ ./opt/logstash/bin/logstash --version          
logstash 5.4.2
$ ./opt/logstash/vendor/jruby/bin/jruby --version     
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on OpenJDK 64-Bit Server VM 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11 +jit [linux-amd64]
```
