### ISSUE TITLE
Create 'Installing Logstash' header and include repository setup

### ISSUE THREAD

**Issue by LeeDr** [elastic/logstash#4980]
Logstash docs aren't too bad as far as finding how to install from a repo.  But all the docs could be more consistent and a bit easier to use.  I like the format of the Beats docs where they have a 

"Getting started with Packetbeat"  (section which contains)
   "Step 1: Installing Packetbeat"   (I don't care about the numbering, just the description)

 * Logstash docs don't have a section in the table of contents that says "Installing" or "Installation"
 * Logstash docs have a section "Package Repositories" but I think it should be either in the "Installing" section or adjacent to it, not in it's own major heading

Here's a screenshot of 4 of our products docs table of contents;
![installationscreens](https://cloud.githubusercontent.com/assets/13542669/14219748/91dbb202-f821-11e5-9c67-74fbc93b72d8.png)

**Comment by suyograo** [comment]
@dedemorton can you please take this one?

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5143
