### ISSUE TITLE
Using tag found as a variable

### ISSUE THREAD

**Issue by blindpet** [elastic/logstash#4990]
I have outlined what I am trying to do [here](https://discuss.elastic.co/t/using-tag-found-in-array-as-index-name/46057) and it seems this isn't currently possible so I'd like to request it as a feature.

To summarize, we are pulling data from a SAN which contains vdisk names, each vdisk is named appropriately since it belongs to a specific company. We want each company to have their own index named after the company. There are 200 companies with their own vdisk names.

So there are two parts we are trying to streamline so we do not have 200 if statements. This kind of logic is what we are after

```
if ['company1', 'company2' ...] in [tags] {
grok {
  match => [ "message", ".*(?i)]{FOUNDTAG}.*"]
  add_tag => { "{FOUNDTAG}"
  tag_on_failure => []
  }
}
```

Then in the output using the same logic

```
if ["company1", "company2", ... "company200"] in [tags] {
    elasticsearch {
        hosts => '10.35.1.38'
        index => "{FOUNDTAG}-svc-%{+YYYY.MM}"
        }
    }
```

**Comment by magnusbaeck** [comment]
A solution to the problem has been posted in the discuss.elastic.co topic that @blindpet links to.

**Comment by jsvd** [comment]
closing this, as conversation is happening on https://discuss.elastic.co/t/using-tag-found-in-array-as-index-name/46057
