### ISSUE TITLE
RubyKernel.java:1040

### ISSUE THREAD

**Issue by atlante77** [elastic/logstash#4993]
Hello,

I have tried to install the last version of logstash on my debian Jessie last friday but it never works.
Indeed i had this problem : https://github.com/elastic/logstash/commit/3b552732626595b03235e90f868cb89932a02983
I fixed it and now i have a new issue ;
`root@ip-00-00-00-00:~# /etc/init.d/logstash configtest
LoadError: no such file to load -- spec_helper
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/runner.rb:2
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/lib/bootstrap/environment.rb:66
`

Could you help me ?

Thanks in advance.

regards,

Atlante

**Comment by suyograo** [comment]
We only test on Deb 7. Not sure if this is Deb 8 specific.

**Comment by jakelandis** [comment]
We do now test on Deb 8, and haven't had any Debian specific issues. 

Closing as non-actionable. If you feel this is still an issue, please provide steps to reproduce.
