### ISSUE TITLE
Merge bin/logstash-plugin into bin/logstash

### ISSUE THREAD

**Issue by simmel** [elastic/logstash#5002]
Now that `bin/plugin` is `bin/logstash-plugin`, why not merge it into `bin/logstash` and make it a sub command of `bin/logstash plugin`?

Might as well do the same with `rspec`?

**Comment by purbon** [comment]
Good morning,
   what would be the benefits of this in your opinion?

on the other side, we moved from `bin/plugin` to `bin/logstash-plugin` with an idea of providing the same experience here as in kibana, elasticsearch, .... if you check this projects you will see similar commands there.

**Comment by suyograo** [comment]
@simmel as Pere mentioned, we'd like to be consistent with other components in Elastic Stack which use `bin/<product>-plugin`
