### ISSUE TITLE
Bring in logstaf-filter-cef into community plugins?

### ISSUE THREAD

**Issue by dkiser** [elastic/logstash#5004]
https://github.com/dkiser/logstash-filter-cef

Can someone help coach me into what needs to be done on this filter plugin to get it assimilated into elastic.co's build/test system?

Cheers,

--Domingo

**Comment by acchen97** [comment]
@dkiser apologize for the lack of response here. We decided to go down the codec route for this, and now have a formal [CEF codec](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-cef.html). For additional information on usage, please see this [blog post](https://www.elastic.co/blog/integrating-elastic-stack-with-arcsight-siem-part-1).

Closing this, but thank you for your interest and efforts. If you have further enhancement requests, feel free to create an issue in the [CEF codec](https://github.com/logstash-plugins/logstash-codec-cef) repository.
