### ISSUE TITLE
Please, add "max_bulk_buffer_size"  to let us set an upper limit on the buffer size for bulk operations to ElasticSearch

### ISSUE THREAD

**Issue by almico** [elastic/logstash#5015]
I just hit the HTTP content length of ElasticSearch while sending docs from LogStash.
This is the error message in ElasticSearch logs:

org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes

I could increase ES HTTP accepted size, but I think the lack of a check on LogStash side is the culprit and setting a higher limit in ES would just be a temporary workaround. Not the solution.
My suggestion is to add a "max_bulk_buffer_size" option to the ElasticSearch output plugin.
Thank you.

**Comment by suyograo** [comment]
Tracked in #4000
