### ISSUE TITLE
Logstash 2.3 added support for environment variables breaking ruby blogs with $

### ISSUE THREAD

**Issue by leepa** [elastic/logstash#5018]
As per subject. It's quite common to use $ in Ruby to declare a global variable - however the Environment variable injector comes in first and breaks as the environment variable doesn't exist.

**Comment by andrewvc** [comment]
Hi @leepa we are aware, and will be making this feature opt-in in our 2.3.1 release with a special '--allow-env' flag. We will also be only supporting the `${VAR}` syntax, not `$VAR`. See https://github.com/elastic/logstash/pull/4963 for more info.

**Comment by leepa** [comment]
Ah - I did hunt through the bug list but couldn't find a reference to the Ruby thing. At least this issue will serve as a helper for anyone else searching. I'll hit the close button as #4963 appears to resolve this well enough.
