### ISSUE TITLE
Official logstash ansible role

### ISSUE THREAD

**Issue by strootman** [elastic/logstash#5021]
Are there plans to create an official Ansible role for installing Logstash?

The `ansible-elasticsearch` role is pretty good, and is designed to deploy multiple instances of elasticsearch on a single host. This would be a nice feature for installing Logstash as well.

**Comment by andrewvc** [comment]
Not at the moment AFAIK unfortunately, but it's an awesome idea!

**Comment by strootman** [comment]
This may or may not be useful, but I've created an ansible role for logstash.
https://galaxy.ansible.com/cyverse/logstash/

Eventually, I want to make this role like the [elastic/ansible-elasticsearch](https://github.com/elastic/ansible-elasticsearch) role, where multiple instances can be deployed.
