### ISSUE TITLE
How to install earlier version of logstash?

### ISSUE THREAD

**Issue by amodakvnera** [elastic/logstash#5030]
I want to install earlier version of logstash 2.2.2 instead of 2.2.3.
 I tried installing logstash 2.2.2 using 
"echo 'deb http://packages.elasticsearch.org/logstash/2.2/debian stable main' | sudo tee /etc/apt/sources.list.d/logstash.list"

but this does not works. Any idea how to install it.

**Comment by abcfy2** [comment]
`sudo apt-get install logstash=2.2.2-1`

**Comment by markwalkom** [comment]
Thanks @abcfy2!

@amodakvnera please join us at https://discuss.elastic.co/ or at #logstash on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)

**Comment by amodakvnera** [comment]
Thanks for the update, and sorry for the late response.
I tried and it worked. It is "sudo apt-get install logstash=1:2.2.2-1"

**Comment by flavono123** [comment]
https://discuss.elastic.co/t/logstash-package-version-convention-in-debian/301607
Open the topic on it.
