### ISSUE TITLE
Missing Ruby class handling for full class name=org.jruby.java.proxies.ArrayJavaProxy

### ISSUE THREAD

**Issue by isayyid** [elastic/logstash#5033]
Is this a known issue and what is the workaround/fix?

:exception=>java.lang.IllegalArgumentException: Missing Ruby class handling for full class name=org.jruby.java.proxies.ArrayJavaProxy, simple name=ArrayJavaProxy, :backtrace=>["com.logstash.Javafier.deep(Javafier.java:111)", "com.logstash.Javafier$1.visit(Javafier.java:46)", "org.jruby.RubyHash.visitLimited(RubyHash.java:648)", "org.jruby.RubyHash.visitAll(RubyHash.java:634)", "com.logstash.Javafier.deep(Javafier.java:43)", "com.logstash.Javafier.deep(Javafier.java:116)", "com.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_set_field(JrubyEventExtLibrary.java:161)", "com.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.gen)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)", "rubyjit.LogStash::Inputs::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461fcb09221153617651.block_0$RUBY$__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-2.0.6/lib/logstash/inputs/kafka.rb:182)", "rubyjit$LogStash::Inputs::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461fcb09221153617651$block_0$RUBY$__file__.call(rubyjit$LogStash::Inputs::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461fcb09221153617651$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)", "org.jruby.runtime.CompiledBlock19.yieldSpecific(CompiledBlock19.java:97)", "org.jruby.runtime.Block.yieldSpecific(Block.java:120)", "rubyjit.LogStash::Codecs::JSON$$from_json_parse_80cf764bd64a968866feafe4085410d09c276f5f1153617651.block_0$RUBY$__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb:48)", "rubyjit$LogStash::Codecs::JSON$$from_json_parse_80cf764bd64a968866feafe4085410d09c276f5f1153617651$block_0$RUBY$__file__.call(rubyjit$LogStash::Codecs::JSON$$from_json_parse_80cf764bd64a968866feafe4085410d09c276f5f1153617651$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)", "org.jruby.runtime.Block.yield(Block.java:142)",

**Comment by isayyid** [comment]
Anybody able to help here ? Here is the full stack with message:

{:timestamp=>"2016-04-11T12:52:52.064000+0000", :message=>"{\"message\":\"type=EXECVE msg=audit(1442707202.266:3023935): argc=4 a0=\\\"su\\\" a1=\\\"vcap\\\" a2=\\\"-c
\\\" a3=7368202D632027756D61736B203030323B202E202F6574632F70726F66696C653B20756D61736B27\",\"@version\":\"1\",\"@timestamp\":\"2016-04-11T12:51:27.134Z\",\"host\":\"d6
5d6e66-5681-4165-9678-a138c432cc36\",\"ALCH_TENANT_ID\":\"1fb90c5d-84e6-452f-a131-9128c565a64f\",\"job_index\":\"router_1\",\"file\":\"/var/log/audit/audit.log\",\"blu
emix_env\":\"bluemix_public_ys0\",\"offset\":\"461809\",\"type\":\"linux_audit_log\",\"instance_id\":\"198.11.194.91\"}", :exception=>java.lang.IllegalArgumentExceptio
n: Missing Ruby class handling for full class name=org.jruby.java.proxies.ArrayJavaProxy, simple name=ArrayJavaProxy, :backtrace=>["com.logstash.Javafier.deep(Javafier
.java:111)", "com.logstash.Javafier$1.visit(Javafier.java:46)", "org.jruby.RubyHash.visitLimited(RubyHash.java:648)", "org.jruby.RubyHash.visitAll(RubyHash.java:634)",
 "com.logstash.Javafier.deep(Javafier.java:43)", "com.logstash.Javafier.deep(Javafier.java:116)", "com.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_set_field(Jruby
EventExtLibrary.java:161)", "com.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_fi
eld.gen)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)", "rubyjit.LogStash::Inputs::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461
fcb09221876326031.block_0$RUBY$__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-2.0.6/lib/logstash/inputs/kafka.rb:182)", "rubyjit$LogStash::In
puts::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461fcb09221876326031$block_0$RUBY$__file__.call(rubyjit$LogStash::Inputs::Kafka$$queue_event_7dcaf6a0c71524fb48b
d961e092a00461fcb09221876326031$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)", "org.jruby.runtime.CompiledBlock19.yieldS
pecific(CompiledBlock19.java:97)", "org.jruby.runtime.Block.yieldSpecific(Block.java:120)", "rubyjit.LogStash::Codecs::JSON$$from_json_parse_80cf764bd64a968866feafe408
5410d09c276f5f1876326031.block_0$RUBY$__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb:48)", "rubyjit$LogStash
::Codecs::JSON$$from_json_parse_80cf764bd64a968866feafe4085410d09c276f5f1876326031$block_0$RUBY$__file__.call(rubyjit$LogStash::Codecs::JSON$$from_json_parse_80cf764bd
64a968866feafe4085410d09c276f5f1876326031$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)", "org.jruby.runtime.Block.yield(
Block.java:142)", "org.jruby.RubyArray.eachCommon(RubyArray.java:1606)", "org.jruby.RubyArray.each(RubyArray.java:1613)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(
RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callI
ter(CachingCallSite.java:154)", "rubyjit.LogStash::Codecs::JSON$$from_json_parse_80cf764bd64a968866feafe4085410d09c276f5f1876326031.chained_0_rescue_1$RUBY$SYNTHETIC__
file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb:48)", "rubyjit.LogStash::Codecs::JSON$$from_json_parse_80cf764b
d64a968866feafe4085410d09c276f5f1876326031.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb)", "rubyjit.LogSta
sh::Codecs::JSON$$from_json_parse_80cf764bd64a968866feafe4085410d09c276f5f1876326031.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/
logstash/codecs/json.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)", "org.jruby.internal.runtime.methods.DefaultMethod.call(Defaul
tMethod.java:214)", "org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:86)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.j
ava:177)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)", "rubyjit.LogStash::Codecs::JSON$$decode_36b2548697fe5471c4fe1a258a06c46f0e1eb41
11876326031.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb:38)", "rubyjit.LogStash::Codecs::JSON$$decode_36b
2548697fe5471c4fe1a258a06c46f0e1eb4111876326031.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb)", "org.jruby
.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)", "org.jruby.runti
me.callsite.CachingCallSite.callIter(CachingCallSite.java:188)", "rubyjit.LogStash::Inputs::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461fcb09221876326031.chain
ed_0_rescue_1$RUBY$SYNTHETIC__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-2.0.6/lib/logstash/inputs/kafka.rb:179)", "rubyjit.LogStash::Input
s::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461fcb09221876326031.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-2.0.6/lib/logstash/in
puts/kafka.rb:178)", "rubyjit.LogStash::Inputs::Kafka$$queue_event_7dcaf6a0c71524fb48bd961e092a00461fcb09221876326031.__file__(/opt/logstash/vendor/bundle/jruby/1.9/ge
ms/logstash-input-kafka-2.0.6/lib/logstash/inputs/kafka.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:221)", "org.jruby.runtime.callsit
e.CachingCallSite.call(CachingCallSite.java:202)", "org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)", "org.jruby.ast.NewlineNode.interpret(NewlineNode
.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.WhileNode.interpret(WhileNode.java:131)", "org.jruby.ast.NewlineNode.interpret(Newl
ineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)", "org.jruby.ast.RescueNode.inte
rpret(RescueNode.java:116)", "org.jruby.ast.BeginNode.interpret(BeginNode.java:83)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockN
ode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod
.call(InterpretedMethod.java:182)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)", "org.jruby.runtime.callsite.CachingCallSite.cacheA
ndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.
java:57)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)", "org.jruby.ast.RescueNode.interpre
t(RescueNode.java:116)", "org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)", "org.jruby.ast.BeginNode.interpret(BeginNode.java:83)", "org.jruby.ast.NewlineNode.i
nterpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)",
 "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203
)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "
org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INT
ERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(
Interpreted19Block.java:194)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)", "org.jruby.runtime.Block.call(Block.java:101)", "org.jruby.Rub
yProc.call(RubyProc.java:300)", "org.jruby.RubyProc.call(RubyProc.java:230)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)", "java.lang.Thread.ru
n(Thread.java:745)"], :level=>:error}

**Comment by jsvd** [comment]
@colinsurprenant can you take a look at this?

**Comment by guyboertje** [comment]
@colinsurprenant : We have a ZD ticket on this too - also Kafka input.

**Comment by guyboertje** [comment]
@colinsurprenant - no need to worry.
The bug is in logstash-input-kafka, moving this issue there.

**Comment by guyboertje** [comment]
Moved -> https://github.com/logstash-plugins/logstash-input-kafka/issues/82

**Comment by guyboertje** [comment]
Readers please note:
use this workaround in your kafka input config...
`key_decoder_class => "kafka.serializer.StringDecoder"`
