### ISSUE TITLE
Define when a plugin should included in the all plugins package

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5051]
The current rake task to generate the `all_plugins` artefact uses the github api to retrieve the list of the available plugins. But this logic is not enough, lets take the case of the `logstash-filter-language` the repository is empty and a PR is waiting to get reviewed.

The problem is the gem is already out on rubygems, the current scripts task doesn't curate anything and including bad gems will result in a bad build. Also the build state for a specific version will be hard to reproduce if the state is not saved.

I suggest that the `all-plugins` plugins should be a curated list, that we know work.

**Comment by ph** [comment]
@acchen97 Did we define to the community contributors when their plugins will be included in the `all-plugins` package?

**Comment by acchen97** [comment]
@ph thanks for filing, will follow-up on this.

**Comment by acchen97** [comment]
@ph can we compile this list based on [all gems that Elastic owns](http://guides.rubygems.org/rubygems-org-api/#owner-methods)?  Having a gem is a prerequisite, and when we bring new plugins into the logstash-plugins repo, the Elastic user should then have push access to the gem.

Additionally, as long as we're still maintaining transport, I think we should include output-elasticsearch_java_shield in this list too?

**Comment by ph** [comment]
@acchen97 Using the rubygems api to make se we have pushes access make sense +1

**Comment by purbon** [comment]
@ph @acchen97 you've to think about one situation, we might have push access, gem could be released (by previous author), but the PR in the repo might be empty (pending review).

**Comment by ph** [comment]
@purbon Correct, this is a case that can happen, I haven't seen it so far but it still a possibility.

Most often I see the following an empty repo on the `logstash-plugins` organization and a published gems that we don't have access.

**Comment by purbon** [comment]
@ph just sharing situation I encountered myself. 👍 , I'm good with improvements here.

**Comment by acchen97** [comment]
Closing as all plugins pkg is no longer being shipped in 5.0.
