### ISSUE TITLE
Logstash 2.3.1 missing from yum & apt repos

### ISSUE THREAD

**Issue by msimos** [elastic/logstash#5064]
I can only see 2.3.0 in the yum and apt repos:

[ root@logstash:/data ]$ apt-get download logstash                                                                                                                   
Get:1 http://packages.elastic.co/logstash/2.3/debian/ stable/main logstash all 1:2.3.0-1 [74.5 MB]
Fetched 74.5 MB in 16s (4633 kB/s)

root@msi-gs60 yum.repos.d]# dnf list logstash --slowduplicates
Last metadata expiration check performed 0:00:46 ago on Thu Apr  7 16:41:20 2016.
Available Packages
logstash.noarch                                                                 1:2.3.0-1                                                                 logstash-2.3

**Comment by ph** [comment]
```
vagrant@vagrant-ubuntu-trusty-32:/$ sudo apt-get download logstash
Get:1 http://packages.elastic.co/logstash/2.3/debian/ stable/main logstash all 1:2.3.1-1 [76.1 MB]
```

```
yum
---> Package logstash.noarch 1:2.3.1-1 will be installed
```
