### ISSUE TITLE
Logstash filter -get fields

### ISSUE THREAD

**Issue by stefansaye** [elastic/logstash#5066]
I've got log lines in the following format and want to extract fields:

`"field1" => "content1","field2" => "content2",field3" => "content3",...
I neither know the field names, nor the number of fields.` 

I tried it with ruby but got errors:

>Error: Expected one of #, {, } at line 8, column 51 (byte 113) after filter { ruby { code => " fieldArray = event['message'].split('"
my conf are as follows,

`input {`
    `stdin {}`
     ` }`

`filter {`
`ruby {`
    `code => "`
        `fieldArray = event['message'].split('", "')`
       ` for field in fieldArray`
           ` field = field.delete '",'`
            `field = field.delete '"'`
           ` result = field.split(': ')`
          `  event[result[0]] = result[1]`
       ` end`
    `"`
`  }`
`}`

`output {`
   ` stdout {`
        `codec => rubydebug`
      `}`
 `}`

please tell me how to fix these errors? 
Thanks for your help.

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
