### ISSUE TITLE
Typo in /etc/init.d/logstash (2.3.1)

### ISSUE THREAD

**Issue by samuraiii** [elastic/logstash#5067]
$ /etc/init.d/logstash stop
Killing logstash (pid 8780) with SIGTERM
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
Waiting logstash (pid 8780) to die...
/etc/init.d/logstash: line 99: [: -eq: unary operator expected
logstash stop failed; still running.

 if [ $KILL_ON_STOP_TIMEOUT -eq 1 ] ; then
it should be as in v 2.3.0
 if [[ $KILL_ON_STOP_TIMEOUT -eq 1 ]] ; then

**Comment by samuraiii** [comment]
On scientific linux 6.7 (CentOS 6 like)

**Comment by samuraiii** [comment]
OK or better we really need that KILL_ON_STOP_TIMEOUT variable to be set (maybe add it as a zero to init script...)
`LS_OPTS=""
KILL_ON_STOP_TIMEOUT=0`

**Comment by purbon** [comment]
Interesting, I just tested with `centos-6-x86_64`, and got:

```
[vagrant@localhost conf.d]$ cat dummy.conf 
input {
  generator {}
}

output {
  stdout {}
  elasticsearch {
    hosts => [ "127.0.0.1:9200" ]
  }
}
[vagrant@localhost conf.d]$ sudo service logstash stop
Killing logstash (pid 4399) with SIGTERM
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
Waiting logstash (pid 4399) to die...
logstash stop failed; still running.
``` 

this happened with an stop without elasticsearch being up, so it was forced to pass though the code you mention. might be scientific linux does something else.

On the other side, we don't really support this linux flavor, but would love to know how to make it work for you (while keeping compatibility)

**Comment by samuraiii** [comment]
Possible fix...
https://github.com/elastic/logstash/pull/5071

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/commit/e7c05f9c0f5061d85807887e10b477167e3fed58
