### ISSUE TITLE
Unable to install logstash-input-pcap plugin in version 2.3.1

### ISSUE THREAD

**Issue by two7374** [elastic/logstash#5076]
plugin logstash-input-pcap is failing in version 2.3.1  . 

[root@linux logstash]# bin/logstash-plugin install logstash-input-pcap
Validating logstash-input-pcap
Installing logstash-input-pcap
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.3.1)

  In Gemfile:
    logstash-core-plugin-api (= 1.8.0) java depends on
      logstash-core (<= 2.3.1, >= 2.0.0) java

    logstash-input-mongodb (>= 0) java depends on
      logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-pcap (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (= 2.3.1) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by purbon** [comment]
logstash-input-pcap was created by me a long time ago for a demo I did in a conference, however the plugin needs a lot of love, for example to update it to the latest version of logstash.

Moving this issue to https://github.com/purbon/logstash-input-pcap was the source repo of this plugin :+1: 

thanks for your time.

**Comment by purbon** [comment]
See: https://github.com/purbon/logstash-input-pcap/issues/2
