### ISSUE TITLE
Split a field

### ISSUE THREAD

**Issue by xionglingfeng** [elastic/logstash#5077]
I am processing logs from squid including headers:

    1460260264.822    459 172.18.3.186 TCP_MISS/200 852 POST http://abroad.apilocate.amap.com/mobile/binary - ORIGINAL_DST/205.204.101.237 application/octet-stream [Connection: close\r\ngzipped: 1\r\nencr: 1\r\nlogversion: 2.1\r\nplatinfo: platform=Android&sdkversion=2.3.0&product=loc\r\nts: 1460260199519\r\nenginever: 4.2\r\nAccept-Encoding: gzip\r\nscode: 1d1d1d1d1d1d1d1d1d1d1d1d1d\r\nUser-Agent: AMAP_Location_SDK_Android 2.3.0\r\nKey: 1d1d1d1d1d1d1d1d1d1d1d\r\nConnection: Keep-Alive\r\nContent-Type: application/octet-stream\r\nX-INFO: 1d1d1d1d1d1d1/1d1d1d1d1d1d1d1d1d1+1d1d1d1d1d1+1d1d1d1d1/1d1d1d1d1d/1d1d1d1+1e11e1e1ee1=\r\ncsid: 1e1e1e1e1e\r\nHost: abroad.apilocate.amap.com\r\nContent-Length: 377\r\n] [HTTP/1.1 200 OK\r\nServer: Tengine\r\nDate: Sun, 10 Apr 2016 03:50:01 GMT\r\nContent-Type: application/octet-stream;charset=UTF-8\r\nContent-Length: 624\r\n\r]

I use grok to parse the logs:

	grok {
			match => [ "message", "%{NUMBER:timestamp}\s+%{NUMBER:response_time} %{IP:src_ip} %{WORD:squid_request_status}/%{NUMBER:http_status_code} %{NUMBER:reply_size_include_header} %{WORD:http_method} (%{WORD:http_protocol}://)?%{HOSTNAME:dst_host}(:%{NUMBER:port})?(%{NOTSPACE:request_url})? %{NOTSPACE:user} %{WORD:squid}/(?:-|%{IP:dst_ip}) %{NOTSPACE:content_type} \[%{DATA:header}\]" ]
			add_tag => ["squid-access"]
		}

After processing, `header` contains everything of HTTP headers. Is there any way can convert `header` to a list of fields (split the string into a list with `\r\n` as delimiter).

**Comment by markwalkom** [comment]
Please join us at https://discuss.elastic.co/ or at #logstash on Freenode for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)

**Comment by wiibaa** [comment]
For future question please do as @markwalkom just said.
What you are looking for is the split option of the mutate filter:
````
  mutate {
    split => { "header" => "\r\n" }
  }
````
