### ISSUE TITLE
[5.0.0-alpha1] logstash failed to start if "agent" in args

### ISSUE THREAD

**Issue by changsijay** [elastic/logstash#5079]
I am tring Logstash `5.0.0-alpha1`in Ubuntu 14.04
in `/etc/init.d/logstash`:

```
args="agent -f ${LS_CONF_DIR} -l ${LS_LOG_FILE} ${LS_OPTS}"
```

I read the doc here: https://www.elastic.co/guide/en/logstash/5.0/command-line-flags.html
the is no mention about `agent`

if I have "agent" in  `/etc/init.d/logstash`, logstash service failed to start by below error(/var/log/logstash/logstash.err)

```
ERROR: too many arguments

See: 'bin/logstash --help'
```

BTW, if I installed logstash by dpkg -i deb file, there is no `bin/logstash`, the above error message is really hard to debug.

**Comment by purbon** [comment]
@changsijay thanks for your report on 5.0.alpha1, I tried to reproduce your issue, see

```
vagrant@vagrant-ubuntu-trusty-64:~$ wget https://download.elastic.co/logstash/logstash/packages/debian/logstash_5.0.0~alpha1-1_all.deb
--2016-04-11 08:53:49--  https://download.elastic.co/logstash/logstash/packages/debian/logstash_5.0.0~alpha1-1_all.deb
Resolving download.elastic.co (download.elastic.co)... 184.73.171.50, 107.22.238.179, 184.73.186.87, ...
Connecting to download.elastic.co (download.elastic.co)|184.73.171.50|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65094672 (62M) [application/x-deb]
Saving to: 'logstash_5.0.0~alpha1-1_all.deb'

100%[================================================================================================================================>] 65,094,672  1.49MB/s   in 45s    

2016-04-11 08:54:35 (1.37 MB/s) - 'logstash_5.0.0~alpha1-1_all.deb' saved [65094672/65094672]

vagrant@vagrant-ubuntu-trusty-64:~$ ls
logstash_5.0.0~alpha1-1_all.deb
vagrant@vagrant-ubuntu-trusty-64:~$ sudo dpkg -i logstash_5.0.0~alpha1-1_all.deb 
Selecting previously unselected package logstash.
(Reading database ... 60992 files and directories currently installed.)
Preparing to unpack logstash_5.0.0~alpha1-1_all.deb ...
Unpacking logstash (1:5.0.0~alpha1-1) ...
Setting up logstash (1:5.0.0~alpha1-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
vagrant@vagrant-ubuntu-trusty-64:~$ ls /opt/logstash/bin/logstash
/opt/logstash/bin/logstash
vagrant@vagrant-ubuntu-trusty-64:~$ ls -la /opt/logstash/bin/logstash
-rwxrwxr-x 1 logstash logstash 1713 Apr  5 14:32 /opt/logstash/bin/logstash
```

but `bin/logstash` is there, where you doing an update, might be?

**Comment by changsijay** [comment]
I was confused by the message in */var/log/logstash/logstash.err*
`See: 'bin/logstash --help'` 
Bcause `/opt/kibana/bin/` is not in $PATH and I am not sure where the absolute path is, from the message.

The main issue is, should I remove `agent` from */etc/init.d/logstash* `args`?

Thanks :)

**Comment by purbon** [comment]
@changsijay thanks a lot for your report, still investigating that, expect a bit of feedback soon :smile_cat:

**Comment by purbon** [comment]
@changsijay bug confirmed, and reproduced. Are you willing to make a PR to get this fixed? this will be very nice of you.

**Comment by changsijay** [comment]
PR sent.

I have another question about packaging..
As you mentioned about the nstalled path.
I found logstash and kibana are installed in `/opt/` while elasticsearch is installed in `/usr/share/`, seems not very consistant, do you think it is good to make a new issue tracker about this?

**Comment by purbon** [comment]
@changsijay I agree is not consistent, you should definitely open an issue about it.

**Comment by suyograo** [comment]
@purbon We removed agent.. i think the right fix is to not add it back, but to improve the docs and add it to breaking changes doc /cc @jsvd

**Comment by purbon** [comment]
Sure, idea is not to add it back, but clean up stale usage in init.d
scripts, see attached pr for this issue.

/purbon

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5083
