### ISSUE TITLE
Multiline: flush downstream error {:exception=>#<ArgumentError: wrong number of arguments calling `config` (0 for 1)>, :level=>:error, :file=>"logstash/codecs/multiline.rb", :line=>"217", :method=>"flush"}`

### ISSUE THREAD

**Issue by 3tgame** [elastic/logstash#5084]
I use  logstash 2.3.1.
my config is 
`input { 
    beats {
        port => 5044
        codec => multiline {
            #pattern => "^%{TIMESTAMP_ISO8601}"
            pattern => "^2016"                                                                                                  
            negate => true
            what => "previous"
        }   
    }   
}
 
output {
  stdout { codec => rubydebug  } 
}`

I run logstash with this command:
`./bin/logstash  -f /etc/logstash/conf.d/logstash.conf --debug` 

there is no match message showed in the console and the console show this error:
`Multiline {:pattern=>"^2016", :text=>"2016-04-11 18:27:50 INFO [com.eyevision.framework.filter.SystemDebugFilter.doFilter] - <", :match=>true, :negate=>true, :level=>:debug, :file=>"logstash/codecs/multiline.rb", :line=>"193", :method=>"decode"}
Multiline: flush downstream error {:exception=>#<ArgumentError: wrong number of arguments calling `config` (0 for 1)>, :level=>:error, :file=>"logstash/codecs/multiline.rb", :line=>"217", :method=>"flush"}`

**Comment by guyboertje** [comment]
@3tgame - thanks for this bug report. I can confirm it is a bug in the beats input.

https://github.com/logstash-plugins/logstash-input-beats/blob/master/lib/logstash/inputs/beats_support/event_transform_common.rb#L36

I am creating an issue in the beats input.

**Comment by guyboertje** [comment]
in beats input - https://github.com/logstash-plugins/logstash-input-beats/issues/73

**Comment by suyograo** [comment]
Tracking it here: https://github.com/logstash-plugins/logstash-input-beats/issues/73
