### ISSUE TITLE
Timestamp NilClass

### ISSUE THREAD

**Issue by driverpt** [elastic/logstash#5089]
I believe i just found a bug.

This happens with
``
output {
  stdout {}
}
``

If we put
``
output {
   stdout { codec => rubydebug }
}
``

**UPDATE**
With ``codec => json`` it does not throw that error as well

This does not happen

> Pipeline main started
> NoMethodError: undefined method `to_iso8601' for nil:NilClass
>                   to_s at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-event-2.3.1-java/lib/logstash/event.rb:105
>                 encode at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.1.2/lib/logstash/codecs/line.rb:56
>                receive at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.6/lib/logstash/outputs/stdout.rb:55
>          multi_receive at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/outputs/base.rb:83
>                   each at org/jruby/RubyArray.java:1613
>          multi_receive at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/outputs/base.rb:83
>   worker_multi_receive at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:130
>          multi_receive at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:114
>           output_batch at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301
>                   each at org/jruby/RubyHash.java:1342
>           output_batch at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301
>            worker_loop at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:232
>          start_workers at /opt/logstash/dnsmalware-ng/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:201

**Comment by jsvd** [comment]
can you post the config? a normal line codec on stdout works fine:

```
/tmp/logstash-2.3.1 % bin/logstash -e "input { generator { count => 1 } } output {stdout { codec => line } } "
Settings: Default pipeline workers: 4
Pipeline main started
2016-04-12T09:18:55.728Z Joaos-MBP.lan Hello world!
```

**Comment by jsvd** [comment]
it may happen that you're using a custom plugin and it is creating an event without `@timestamp`?

**Comment by driverpt** [comment]
@jsvd, This happens because we are dropping @timestamp and @version information before output. We don't want that information to be outputed.

Perhaps change it to [@metadata][timestamp] and [@metadata][version] ?

**Comment by jsvd** [comment]
we have discussed moving timestamp to `@metadata` in the past, but that would break a lot of existing configurations and plugins, and so we just assume it exists.
what you can do is ensure the output does not resort to `to_s` by controlling the codec formatting. example:

broken:

```
/tmp/logstash-2.3.1 % bin/logstash -e "input { generator { count => 1 }} filter { mutate { remove_field => '@timestamp' } } output {stdout { } } " 
Settings: Default pipeline workers: 4
Pipeline main started
NoMethodError: undefined method `to_iso8601' for nil:NilClass
                  to_s at /tmp/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-event-2.3.1-java/lib/logstash/event.rb:105
                encode at /tmp/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.1.2/lib/logstash/codecs/line.rb:56
```

ok:

```
/tmp/logstash-2.3.1 % bin/logstash -e "input { generator { count => 1 }} filter { mutate { remove_field => '@timestamp' } } output {stdout { codec => line { format => '%{message}' } } } "
Settings: Default pipeline workers: 4
Pipeline main started
Hello world!
```

**Comment by jsvd** [comment]
more context on this topic: https://github.com/elastic/logstash/issues/4020 and https://github.com/elastic/logstash/issues/4044
closing as duplicate
