### ISSUE TITLE
Confusion with logstash and logstash-all-plugins downloads

### ISSUE THREAD

**Issue by micahlmartin** [elastic/logstash#5094]
I downloaded `logstash-2.3.1.tar.gz` and `logstash-all-plugins-2.3.1.tar.gz` expecting that I needed them both. It wasn't clear to me that the `logstash-all-plugins-2.3.1.tar.gz` wasn't just the plugins but actually had all the binaries for logstash as well. I was trying to run `bin/logstash-plugins unpack logstash-all-plugins-2.3.1.tar.gz` which was giving me strange errors. It would be great if this was a little more clear in the instructions on the download page.

Thanks!

**Comment by acchen97** [comment]
Thanks for the feedback @micahlmartin will add some clarity on the download page.

**Comment by acchen97** [comment]
Added a note on the All Plugins download option: https://www.elastic.co/downloads/logstash
