### ISSUE TITLE
Make rpm/deb packages more similar to Elasticsearch

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5101]
Reference: https://www.elastic.co/guide/en/elasticsearch/reference/master/rpm.html#rpm-layout

We currently install to /opt, where Elasticsearch uses /usr, /var, et al. Let's move towards Elasticsearch's model.

Major task:

* [x] Update `rake artifact:rpm` and deb tasks to use a file layout similar to [Elasticsearch's](https://www.elastic.co/guide/en/elasticsearch/reference/master/rpm.html#rpm-layout) See #5341
* [ ] Write tool for migrating stored plugin state to the new location.

Upgrade tooling needed. The following plugins store state somewhere by default. For rpm/deb, it will need to move to /var/lib/logstash/

* [ ] file
* [ ] s3
* [ ] jdbc

(please add other state-storing plugins to the above list)

**Comment by suyograo** [comment]
For these state file upgrades, we should start with an external script (bash, or ruby or whatever) which copies the state files from `$OLD_HOME` to new `/var/lib`. 

Also need to add breaking changes doc (edited the issue)

**Comment by suyograo** [comment]
Done in #5341
