### ISSUE TITLE
Filter/Output doc update needed

### ISSUE THREAD

**Issue by laidig** [elastic/logstash#5102]
Output and filter configuration settings: type, tags, exclude_tags were marked as obsolete in 2.3, but the doc for 5.0 still includes them.

I found this by passing my 1.X config through 5.0-alpha.  

https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-file.html#plugins-inputs-file-type

On a related note, any ideas for replacements?

**Comment by suyograo** [comment]
Will be fixed in https://github.com/elastic/logstash/pull/5720
