### ISSUE TITLE
Default Plugins test failling on jenkins

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5106]
- [x] https://travis-ci.org/logstash-plugins/logstash-input-beats [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-beats.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-beats)
    - [x] Fix in https://github.com/logstash-plugins/logstash-input-beats/pull/76 
- [x] https://travis-ci.org/logstash-plugins/logstash-input-imap [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-imap.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-imap)
    - [x] Fix in https://github.com/logstash-plugins/logstash-input-imap/pull/16
- [x] https://travis-ci.org/logstash-plugins/logstash-input-zeromq [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-zeromq.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-zeromq)
- [x] https://travis-ci.org/logstash-plugins/logstash-input-gelf [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-gelf.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-gelf) -> Guy [issue](https://github.com/logstash-plugins/logstash-input-gelf/issues/38)
- [x] https://travis-ci.org/logstash-plugins/logstash-input-rabbitmq [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-rabbitmq.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-rabbitmq)
- [x] https://travis-ci.org/logstash-plugins/logstash-filter-geoip [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-geoip.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-geoip)
 - [x] issue: https://github.com/logstash-plugins/logstash-filter-geoip/issues/67
- [x] https://travis-ci.org/logstash-plugins/logstash-codec-collectd [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-collectd.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-collectd)
- [x] https://travis-ci.org/logstash-plugins/logstash-output-opentsdb [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-opentsdb.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-opentsdb)
- [x] https://travis-ci.org/logstash-plugins/logstash-input-jdbc [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-jdbc.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-jdbc)
- [x] https://travis-ci.org/logstash-plugins/logstash-output-sqs [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-sqs.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-sqs)
- [x] https://travis-ci.org/logstash-plugins/logstash-output-cloudwatch [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-cloudwatch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-cloudwatch)

There is other non default plugins test faillings on travis too, but this list only include the plugins that we ship by default.

**Comment by ph** [comment]
The SQS output and the cloudwatch output suffer from the same issue, something is wrong with the dependency concerning the "aws-sdk-resources", not sure what cause this yet since they didn't break the package generation.

**Comment by purbon** [comment]
collectd output is only failing on linux machines.

**Comment by guyboertje** [comment]
Gelf input fails because the test assumed java event

**Comment by purbon** [comment]
collectd fails because `rake vendor` is not executed. updating the travis file.

**Comment by ph** [comment]
@guyboertje @purbon If Can review the small PRs in this issue that would be great

**Comment by guyboertje** [comment]
@ph - https://github.com/logstash-plugins/logstash-input-gelf/pull/39

**Comment by purbon** [comment]
@ph intersting imap input, test are green but badge says error.

**Comment by wiibaa** [comment]
@purbon I suppose we got bot tricked by https://github.com/travis-ci/travis-ci/issues/655 => **"Current" build shows status of latest PR build instead of latest master build**

**Comment by wiibaa** [comment]
maybe a woraround would be to point to https://travis-ci.org/logstash-plugins/logstash-input-imap/branches instead of https://travis-ci.org/logstash-plugins/logstash-input-imap
