### ISSUE TITLE
translation missing: en.logstash.agent.configuration.obsolete 

### ISSUE THREAD

**Issue by laidig** [elastic/logstash#5108]
running 5.0.0-alpha1

I get the following message when trying to run --configtest:

The given configuration is invalid. Reason: translation missing: en.logstash.agent.configuration.obsolete {:level=>:fatal}

The YAML for the message refers to en.logstash.**runner**.configuration.obsolete, not en.logstash.**agent**.configuration.obsolete 

https://github.com/elastic/logstash/blob/master/logstash-core/locales/en.yml#L107

The code that errors out is here:
https://github.com/elastic/logstash/blob/8af93d0f3a77f8e9bd2196077f23e0f6168bc576/logstash-core/lib/logstash/config/mixin.rb#L89

What is the preferred fix, change the YAML or the error?

**Comment by ph** [comment]
You PR is fine, since we have moved everything to the runner, Can you create the PR.
Also Would you mind doing step 2 of the contributing guide? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by ph** [comment]
I just merged your PR thanks for your contribution!
