### ISSUE TITLE
Support Environment Variable in conditionals

### ISSUE THREAD

**Issue by githubmui** [elastic/logstash#5115]
Hi,
in LS 2.3.0. I have got the problem that following expression doesn't evaluate to TRUE (if environment variable doesn't exists).

if "${LS_ENDP_JDBC:a}" == "a" { ... }

Thx in advance for reply.

**Comment by suyograo** [comment]
@githubmui The environment variable option was mostly added for substituting values, and not using it in conditional. But it seems this is a good usecase too. I'll keep this open as an enhancement.

**Comment by githubmui** [comment]
Hi, 
its also an missing issue for the parameters of all the input plugins! 
For example, it's not possible to use this nice feature for the URL of a "http_poller".

**Comment by IrlJidel** [comment]
As a workaround you could use mutate and @metadata fields

```
mutate {
  add_field => { "[@metadata][LS_ENDP_JDBC]" => "${LS_ENDP_JDBC:a}" }
}

if [@metadata][LS_ENDP_JDBC] == "a" {
...
}

```

**Comment by czerasz** [comment]
The usage in `if` would make the configs more generic:

```
output {
  if "${OUTPUT:elasticsearch}" == "debug" {
    stdout { codec => rubydebug }
  } else {
    elasticsearch { ... }
  }
}
```

**Comment by mayamsh** [comment]
any update on this ? currently I am using the same approach as @IrlJidel, but it's more convenient to have the env. var. in the condition

**Comment by berglh** [comment]
I also want conditional inputs based on comparisons with environmental variables:
```
LS_DEV_MODE=false ./logstash --debug -e '
input { 
  if "${LS_DEV_MODE}" == "false" { 
    file { path => "/tmp/file1" sincedb_path => "/dev/null" start_position => "beginning" } 
  } 
  if "${LS_DEV_MODE}" == "true" { 
    file { path => "/tmp/file2" sincedb_path => "/dev/null" start_position => "beginning" } 
  }
}
output { 
  stdout { codec => "rubydebug" } 
}'
```
This is because I wish to have development and production inputs in the one configuration stack and control the mode of the pipeline using `LS_DEV_MODE=(true|false)`.

**Comment by maxlock** [comment]
+1 I also would like to change behaviour based upon environment variables.

**Comment by PhaedrusTheGreek** [comment]
+1 for being able to use environment variables in conditionals.

**Comment by astropuffin** [comment]
Was very surprised and sad to find that I couldn't do this. I would have thought that environment variables would substitute anywhere in the config on load. Really confused as to why this isn't the case.

**Comment by mrjameshamilton** [comment]
+1

**Comment by addykim** [comment]
+1 although my desired use case is something like:

```
output {
    stdout { codec => rubydebug }
    if ${ELASTICSEARCH_HOST} is set {
        elasticsearch { 
            hosts => ["${ELASTICSEARCH_HOST}"]
            ...
        }
    }
}
```
Using psuedo code for the conditional because I'm not sure what the best way to check based on the [current documentation](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html), but that's a different topic.

**Comment by berglh** [comment]
You need to assign the environment variable to a field then do your if
statement. I assign it to metadata fields so they don't make it through the
output ie. `[@metadata][es-hosts]`

**Comment by joniba** [comment]
+1

**Comment by danizen** [comment]
+1 - just found this, and tried the other method first.

**Comment by nugend** [comment]
Can elastic please call this out  in documentation or put a warning for it at least? Got blocked for most of a day wondering what the hell I was doing wrong.

**Comment by lordbulb** [comment]
+1 
I've been debugging a Logstash configuration and the condition that should be used to identify the header in a CSV file is supposed to you environmental variables
`if ["${COLUMN_NAME_USED_TO_SKIP_HEADER_ROW}"] == "${COLUMN_NAME_USED_TO_SKIP_HEADER_ROW}" {`
And it appears that it is not working because of this issue.
Which is weird, when other parts of the Logstash configuration also use those variables and work as expected.

**Comment by duaraghav8** [comment]
Hi,
Has there been any progress on this issue?
Although it isn't a blocker for me, my workaround is pretty ugly and having this feature would make my pipeline configurations much more sane :)

**Comment by yinrong** [comment]
hello?

**Comment by dormunis** [comment]
any progress?

**Comment by Shubydo** [comment]
Any update on this issue? This is something we would really like to use in our pipelines.

**Comment by iTaybb** [comment]
Can we please push this?

**Comment by MorrieAtElastic** [comment]
I have a customer who opened a Support Ticket because his use of conditional logic on an env variable was being rejected as an error. 

In fact this is a very desirable enhancement and the existing documentation, while not showing examples of using an ENV within a conditional statement, does not explicitly forbid such use.

**Comment by brunocascio** [comment]
Anyone using env variables with conditionals?

I need something similar to this:

```
output {
  if "${IS_LOCAL}" == "true" {
    stdout {}
  } else {
    gelf { }
  }
}
```

**Comment by nicklan** [comment]
Surprised to find this isn't supported.  Furthermore, our use-case seems like it's basically impossible, even with the workaround above. We'd like to regex match against a pattern specified by an environment variable. It appears that even if you put the value into a field, this doesn't work:

`if [field] =~ /[@metadata][regex]/`

Meaning we're basically just stuck.

**Comment by luminous706** [comment]
I need this too. We use a systemd file that sets variables for our logstash pipeline. Very simple to set our variables in one place, instead of going through a logstash configuration. I just discovered that variables don't work inside a conditional, I'm baffled.

**Comment by asmith-elastic** [comment]
There have been a few users that have expressed interest in this functionality, as this would be a desirable enhancement in order to satisfy their use cases. 

+1 for being able to use environment variables in conditionals.

**Comment by AGenonGY** [comment]
I'm also voting for this one, it will definitely be helpful to control the Logstash pipelines using environment variables.

**Comment by ay27** [comment]
any progress?

**Comment by makefu** [comment]
I'd love to see this feature as well!

**Comment by kaisecheng** [comment]
This issue is fixed in Logstash 7.17

**Comment by kaisecheng** [comment]
Logstash 7.17 has a fix for this issue

**Comment by brunobastosg** [comment]
Is possible to use this to check if an environment variable is set?

Something like:

```
input {
  if "${BASE_URL}" {
    http_poller {
      urls => {
        url => "${BASE_URL}/api/v1"
      }
      request_timeout => 120
      socket_timeout => 60
      schedule => { cron => "0 7 * * *" }
      codec => "json"
    }
  }
}
```

I'm having trouble getting this to work.

**Comment by kaisecheng** [comment]
@brunobastosg You can alternatively check by the following

 ```
 if ("${VAR:}" != "") {
     http_poller { ... }
  }
```

You can give a default value by using the form `${VAR:default_value}`. Logstash uses the default value if the environment variable is undefined.

**Comment by brunobastosg** [comment]
@kaisecheng does logstash still try to parse the http_poller block? Because after I tried your suggesting I got the following error:

```
[2022-05-24T17:42:23,751][INFO ][logstash.inputs.http_poller][main] Registering http_poller Input {:type=>"myType", :schedule=>{"cron"=>"* * * * *"}, :timeout=>nil}
[2022-05-24T17:42:24,151][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: Invalid URL /api/v1>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http_poller-5.1.0/lib/logstash/inputs/http_poller.rb:142:in `validate_request!'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http_poller-5.1.0/lib/logstash/inputs/http_poller.rb:134:in `normalize_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http_poller-5.1.0/lib/logstash/inputs/http_poller.rb:65:in `block in setup_requests!'", "org/jruby/RubyHash.java:1415:in `each'", "org/jruby/RubyEnumerable.java:886:in `map'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http_poller-5.1.0/lib/logstash/inputs/http_poller.rb:65:in `setup_requests!'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http_poller-5.1.0/lib/logstash/inputs/http_poller.rb:55:in `register'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-mixin-ecs_compatibility_support-1.3.0-java/lib/logstash/plugin_mixins/ecs_compatibility_support/target_check.rb:48:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:232:in `block in register_plugins'", "org/jruby/RubyArray.java:1821:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:231:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:390:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:315:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:189:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:141:in `block in start'"], "pipeline.sources"=>["/usr/share/logstash/pipeline/logstash.conf"], :thread=>"#<Thread:0x2f63074d run>"}
```

Apparently it tried to validate the url `${BASE_URL:}/api/v1`, but since BASE_URL is undefined, the url becomes `/api/v1` which is not valid.

Here is the logstash.conf file:

```
input {
 # the http input is always available
  http {
    host => "0.0.0.0"
    port => 8080
  }
 # the http_poller input should only be available if BASE_URL is set
  if ("${BASE_URL:}" != "") {
    http_poller {
      urls => {
        url => "${BASE_URL:}/api/v1"
      }
      request_timeout => 120
      socket_timeout => 60
      schedule => { cron => "* * * * *" }
      codec => "json"
      type => "myType"
    }
  }
}

output {
  stdout { codec => rubydebug }
}
```

**Comment by kaisecheng** [comment]
@brunobastosg `if` statement only works in `filter { }` and `output { }`

**Comment by brunobastosg** [comment]
> @brunobastosg `if` statement only works in `filter { }` and `output { }`

Sorry, I hadn't noticed that in the documentation. I assumed it could be anywhere.

Thank you for your time!

**Comment by thom-vend** [comment]
_FYI . VAR cannot be evaluated to a number, hence cannot do number comparison._
