### ISSUE TITLE
Change how the I18n library fallback is done when running in test mode

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5122]
The I18n gem is the library we use to manage all the user facing string inside Logstash, it basically takes a key and try to find the corresponding text in a yml files. The default behavior for this library when a key is not found is to return a "translation missing for key: XXXXX", this feature is fine when Logstash is ran in a production environment since it will not make logstash crash  but it will return an unhelpful message to the user. 

In our past refactors we forgot to change some of the keys to reflect the new structure of the yml files, with the addition of more CLI testing I think It would be wise to change the behavior of the I18n gem **ONLY** when we are running the test.

I suggest to change from returning a `translation missing` to raise an exception and return where the key was called. I've use this strategy in the past with great success when testing rails views / controllers.

Related: #5013 #5119

**Comment by jsvd** [comment]
also, it shouldn't be hard to create a rake task that does some static analysis on I18n calls and compares them to the possible translation keys from en.yml

**Comment by ph** [comment]
@jsvd Agree, also a good way to find if we test all the user path..

**Comment by jsvd** [comment]
```ruby
require 'i18n'

I18n.enforce_available_locales = true
I18n.load_path << "logstash-core/locales/en.yml"
I18n.reload!

Dir.glob("logstash-*/**/*.rb").each do |file_name|
  File.foreach(file_name) do |line|
    match = line.match(/I18n.t\("(.+?)"\)/)
    next unless match
    puts "invalid key in #{file_name}: #{match[1]}" unless I18n.exists?(match[1])
  end
end
```


```
/tmp/logstash (git)-[master] % ruby /tmp/script.rb
/tmp/logstash (git)-[master] %

/tmp/logstash (git)-[master] % git checkout 5.0
Branch 5.0 set up to track remote branch 5.0 from origin.
Switched to a new branch '5.0'
/tmp/logstash (git)-[5.0] % ruby /tmp/script.rb
/tmp/logstash (git)-[5.0] %

/tmp/logstash (git)-[5.0] % git checkout 2.x
Switched to branch '2.x'
Your branch is up-to-date with 'origin/2.x'.
/tmp/logstash (git)-[2.x] % ruby /tmp/script.rb
invalid key in logstash-core/lib/logstash/agent.rb: logstash.runner.flag.debug_config
/tmp/logstash (git)-[2.x] %

/tmp/logstash (git)-[2.x] % git checkout 2.3
Branch 2.3 set up to track remote branch 2.3 from origin.
Switched to a new branch '2.3'
/tmp/logstash (git)-[2.3] % ruby /tmp/script.rb
invalid key in logstash-core/lib/logstash/agent.rb: logstash.runner.flag.debug_config
/tmp/logstash (git)-[2.3] %
```

**Comment by ph** [comment]
@jsvd We can wrap that already in a rspec test ^

**Comment by jsvd** [comment]
@ph should we close this as, hopefuly, we now prevent missing keys?

**Comment by ph** [comment]
Agree the static analysis is an event better solution.
