### ISSUE TITLE
Missing Environment Variable Replacement in Input Plugins

### ISSUE THREAD

**Issue by loms0815** [elastic/logstash#5128]
I am using LS 2.3.1 and it seems that there is a problem regarding environment variable replacement.
Following replacment doesn't work:

http_poller {
		urls => {
			create => {
				method => post
				url => "http://${ELK_LS_HOST:localhost}:9200/_sql"
				body => '{ "stmt": "CREATE TABLE IF NOT EXISTS test1 (host string)" }'
			}
		}
	}

**Comment by magnusbaeck** [comment]
Are you invoking Logstash with the `--allow-env` option? As of LS 2.3.1 this is necessary for the variable expansion to take place. See the [2.3.1 release announcement blog post](https://www.elastic.co/blog/logstash-2.3.1-and-2.2.4-released).

**Comment by suyograo** [comment]
Second what @magnusbaeck suggested..

Also, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
