### ISSUE TITLE
Sighup is ignored by logstash 2.3.1

### ISSUE THREAD

**Issue by randude** [elastic/logstash#5129]
https://discuss.elastic.co/t/sighup-doesnt-work-for-reloading-conf/47403

sighup is supposed to cause logstash 2.3.1 to reload conf files. This doesnt happen on my ubuntu 12 machine. 
However, --auto-reload does seem to be working.

Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

I'm sending the sighup using the kill command manually as the root user.

**Comment by jsvd** [comment]
Not sure, I just tested on ubuntu 14.04 and managed to reload a pipeline with kill -1.
The tested pipeline was very simple: generator -> sleep -> file

Is there anything logged at all when SIGHUP is sent?

**Comment by randude** [comment]
I only saw the autoreload log messages. Anyways, just tried it again with kill -1. Doesnt reload because i edited the conf files in such a way that it wont be able to reload without throwing an error but it didnt change anything.
When i try this iwth the auto reload, it crashes when it tries to reload the bad conf as expected.

**Comment by jordansissel** [comment]
> it crashes when it tries to reload the bad conf as expected.

Can you describe what you mean by "it crashes" ? Logstash should not crash if the configuration is bad upon reload. When I test this, I get this error message and Logstash continues running with the old configuration:

```
SIGHUP received. {:level=>:warn}
fetched an invalid config {:config=>"input { file { path => \"/tmp/x2\"  }\nfilt
er {\n  mutate {\n    add_tag => \"fancy1\"\n  }\n}\noutput { stdout { codec =>
rubydebug } }\n\n", :reason=>"Expected one of #, => at line 3, column 10 (byte 5
5) after input { file { path => \"/tmp/x2\"  }\nfilter {\n  mutate ", :level=>:e
rror}
```

Also, when I send SIGHUP, it seems to work fine for me (tested on Logstash 2.3.1). If the configuration is invalid, Logstash will log an error and continue with the old config. If the configuration file hasn't changed, Logstash will not do anything.

**Comment by randude** [comment]
I was able to solve this. It's related to issues that i did. I use another process to start logstash and that process set logstash to ignore sighup.

**Comment by randude** [comment]
Please mark this as not a bug.
