### ISSUE TITLE
Version 2.3.1 file plugin or elasticsearch plugin not works

### ISSUE THREAD

**Issue by josselinchevalay** [elastic/logstash#5131]
hello guys, 

i use logstash for load IIS log in elasticsearch but when upgrade to 2.3.1 version of logstash my config not works

- version : from 1.4.2 to  2.3.1 logstash
- OS : Windows server 2012 R2 datacenter 64 bit
- JAVA :  1.8.0_77

my config 
```
input 
{
    file{
         type => "iis"
         path => "C:\iisLog\mySite\u_ex*.log"
         start_position => "beginning"  
    }
}

filter {

  if [message] =~ "^#" {
    drop {}
  }
  grok {    
	match  => ["message", "%{TIMESTAMP_ISO8601:log_timestamp} %{WORD:iisSite} %{WORD:computerName} %{IPORHOST:serverIp} %{WORD:method} %{URIPATH:route} %{NOTSPACE:queryString} %{NUMBER:port} %{NOTSPACE:userName} %{IPORHOST:ipClient} %{NOTSPACE:httpVersion} %{NOTSPACE:agent} %{NOTSPACE:cookies} %{NOTSPACE:referer} %{IPORHOST:host} %{NUMBER:codeStatus} %{NUMBER:subStatus} %{NUMBER:win32Status} %{NUMBER:scByte} %{NUMBER:csBytes} %{NUMBER:timeTaken}"]
	add_tag => ["iis"]
  }  
}
output {
  #stdout {codec => "json"}
  elasticsearch{
     hosts => ["127.0.0.1:9200"]
  }
}
```

thx in advance for you help

**Comment by josselinchevalay** [comment]
ok i change my config for this

```
input 
{
    stdin {}
    #file{
    #     type => "iis"
    #    path => "C:\iisLog\mySite\u_ex*.log"
    #     start_position => "beginning"  
    #}
}

filter {

  if [message] =~ "^#" {
    drop {}
  }
  grok {    
    match  => ["message", "%{TIMESTAMP_ISO8601:log_timestamp} %{WORD:iisSite} %{WORD:computerName} %{IPORHOST:serverIp} %{WORD:method} %{URIPATH:route} %{NOTSPACE:queryString} %{NUMBER:port} %{NOTSPACE:userName} %{IPORHOST:ipClient} %{NOTSPACE:httpVersion} %{NOTSPACE:agent} %{NOTSPACE:cookies} %{NOTSPACE:referer} %{IPORHOST:host} %{NUMBER:codeStatus} %{NUMBER:subStatus} %{NUMBER:win32Status} %{NUMBER:scByte} %{NUMBER:csBytes} %{NUMBER:timeTaken}"]
    add_tag => ["iis"]
  }  
}
output {
  #stdout {codec => "json"}
  elasticsearch{
     hosts => ["127.0.0.1:9200"]
  }
}
```

i add in elasticsearch my data. So i think i have a problem with file plugin

**Comment by guyboertje** [comment]
@josselinchevalay - what version of LS did you upgrade from?

**Comment by josselinchevalay** [comment]
i upgrade to 1.4.2

**Comment by guyboertje** [comment]
The file input in 2.3.1 has changed a lot since then.  There is a new config called ignore_older (default 24 hours) - designed to prevent older files from being reprocessed from the beginning if LS is restarted.

When were your logs last modified?

Do you have a sincedb file - you may need to point the file input to that.

For further help please use the logstash discussion forum until you know there is a bug, https://discuss.elastic.co/c/logstash

**Comment by josselinchevalay** [comment]
i hope to load archive logfile for a test. this archive was  3 months old

**Comment by guyboertje** [comment]
Ahhh.
Do the windows equivalent of `touch C:\iisLog\mySite\u_ex*.log` to change the modified timestamp

**Comment by josselinchevalay** [comment]
Ok thx it's works. for next issue i create my issue on discuss https://discuss.elastic.co/c/logstash
