### ISSUE TITLE
geoip location field doesn't update as "geo_point" type in Elasticsearch/kibana

### ISSUE THREAD

**Issue by arunkaithe** [elastic/logstash#5144]
I have managed to get GeoIP filter working and field "geoip.location" is populated in kibana. However the type of field is 'integer'.  How do i make the field to be type "geo_point".  Below is the  configuration in logstash and mapping to elasticsearch am using:

logstash-filter.conf

```
filter {
  if [type] == "mesos" {


   geoip {
      source => "remoteAddress"
      target => "geoip"
      database => "/etc/logstash/GeoLiteCity.dat"
      add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
      add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
    }
    mutate {
      convert => [ "[geoip][coordinates]", "float"]
    }


  }
}
```

I have indexed below mapping to elasticsearch 

```
cat ~/filebeat-index-template.json
{
  "mappings": {
    "_default_": {
      "_all": {
        "enabled": true,
        "norms": {
          "enabled": false
        }
      },
      "dynamic_templates": [
        {
          "template1": {
            "mapping": {
              "doc_values": true,
              "ignore_above": 1024,
              "index": "not_analyzed",
              "type": "{dynamic_type}"
            },
            "match": "*"
          }
        }
      ],
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "message": {
          "type": "string",
          "index": "analyzed"
        },
        "offset": {
          "type": "long",
          "doc_values": "true"
        },
        "geoip"  : {
          "type" : "object",
          "dynamic": true,
          "properties" : {
            "location" : { "type" : "geo_point" }    # i tried both location and geoip.location here instead of location
          }
        }
      }
    }
  },
  "settings": {
    "index.refresh_interval": "5s"
  },
  "template": "filebeat-*"
}
```

"geoip.location" field  is still shown as type integer instead of geo_point. Where am i going wrong ???

Below are the versions of ELK used on Ubuntu
logstash : 2.2.2
kibana  : 4.4.1
ElasticSearch : Version: 2.2.0, Build: 8ff36d1/2016-01-27T13:32:39Z, JVM: 1.8.0_74

**Comment by jordansissel** [comment]
Your configuration has this:

```
      add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
      add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
```

The default fields provided by the geoip filter include a `location` field that is a geojson coordinate value. This add_field stuff is not necessary. :)

**Comment by alager** [comment]
@arunkaithe  Did you ever resolve this?  I too am having a similar issue with `geoip.location` not being a `geo_point`.

**Comment by hunterlong** [comment]
+1

**Comment by alager** [comment]
**UPDATE** So I did get it working with the rag-tag forum postings on the matter.
Turns out, if you use `filebeat`, then the `geoip.location` is not mapped as a  `geo_point`, so it's just a `float`.
I had to go into `/etc/filebeat` and edit the template to add the mapping to the properties section:
```
    "geoip": {
        "properties": {
          "coordinates": {
            "type": "geo_point"
        }
       }
      }
```
following this thread: [filebeat-and-tile-map-visualization](https://discuss.elastic.co/t/filebeat-and-tile-map-visualization/58969/14)
