### ISSUE TITLE
Changes to Logstash build and release process

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5151]
The goal of this project is to simplify Logstash's build and release process, paving the way for a 1-click release. Today, there are many manual steps which can be error prone. Also, the goal is to be able to release multiple snapshots (candidates) and transition from the candidate to actual release artifact without making any changes. 

Discussion from an internal meeting:

1) Logstash gems (core, event, plugin-api) don't need to line up with Elastic stack release versions. Plugin API gem does not change often and does not need to be published frequently.
2) Think about possibly making logstash-core not a gem anymore (may impact plugin developers, needs discussion)
3) Logstash internal gems will have a different release cycle from Elastic stack (same way Lucene has a different release cycle from Elasticsearch)
4) Release snapshots do not need to publish any gems
5) Figure out a way to run plugin tests with unpublished logstash-core gems
6) Update our build artifact processes to include more versionable metadata (git hash, build date, build host, etc) so we can differentiate between bug reports in same-versioned internal RCs

**Comment by rjernst** [comment]
What's happening here? The most important thing, which I dont see listed here (although implied by the first paragraph of the description), is the ability to build release packages (ie use a non-snapshot version) with a flag (ie not change a file to update the version).

**Comment by suyograo** [comment]
@rjernst we haven't made any progress here. We'll start working on it starting next week.

**Comment by suyograo** [comment]
Closed in favor of #5416 and #5414
