### ISSUE TITLE
Unable to run multiple logstash conf

### ISSUE THREAD

**Issue by sameerpanicker** [elastic/logstash#5166]
I have already raised an issue in elastic forums but coudn't get it resolved.
https://discuss.elastic.co/t/passing-multiple-arguments-while-logstash-startup/47805 

Can anyone please let me know how can I get this fixed ?

**Comment by sameerpanicker** [comment]
Any update on this please ?

**Comment by markwalkom** [comment]
Given you have asked this on the forums I will close this.

Note - We reserve Github for confirmed bugs and feature requests :)
