### ISSUE TITLE
Calculate the duration between two log events

### ISSUE THREAD

**Issue by linhntt41** [elastic/logstash#5182]
Hi all, 
I want to calculate time duration of username A, but error 
**Ruby exception occurred: can't dup NilClass {:level=>:error} and Ruby exception occurred: undefined method `gsub!' for "2016-04-25T03:45:00.000Z":LogStash::Timestamp {:level=>:error}**
Elk version: logstash 2.3.1, elasticsearch 2.3.1, kibana 4.5

file.log
      Apr 25 13:15:00 A in
      Apr 25 13:16:00 A out
This is file config:
input{
        file{
                path =>"/opt/file.log"
        }
}
filter{
        grok {
                match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{USERNAME:username} %{WORD:status}"}
            }
        if [status] == "in" {
           mutate {
              rename => {"timestamp" => "[started]"}
             }
           date {
           match =>["[started]","MMM dd HH:mm:ss","ISO8601"]
           target => "[started]"
         }
     }
        if [status] == "out" {
          mutate {
              rename => {"timestamp" => "[ended]"}
             }
           date {
           match =>["[ended]","MMM dd HH:mm:ss","ISO8601"]
           target => "[ended]"
         }
        }
          elasticsearch {
              hosts => ["localhost"]
              query => "status:in AND username:%{[username]}"
              fields => ["started","ended"]
         }
        ruby {
          init => "require 'time'"
          code => "event['duration_hrs'] = Time.parse(event['ended']).to_f - Time.parse(event['started']).to_f"
          add_tag => ["duration_hrs"]
        }
}
output {
        stdout { codec => rubydebug}
        elasticsearch { hosts => ["localhost:9200"]
                         index => "index-%{+YYYY.MM.dd}"}
}

Thanks

**Comment by purbon** [comment]
might I ask you which version of logstash are you using?

**Comment by linhntt41** [comment]
I using version 2.3 logstash

**Comment by purbon** [comment]
Interesting issue, I tested with:

event.json:

```json
{ "ended": "2016-04-25T04:45:00.000Z", "started": "2016-04-25T03:45:00.000Z"}
```

conf:

```bash
input {
  stdin { codec => json }
}

filter {
  ruby {
    init => "require 'time'"
    code => "event['duration_hrs'] = Time.parse(event['ended']).to_f - Time.parse(event['started']).to_f"
    add_tag => ["duration_hrs"]
   }
}

output {
  stdout {
   codec => rubydebug
  }
}
```

and got:

```bash
skywalker% cat event.json | ./logstash-2.3.0/bin/logstash -f date_diff.conf
Settings: Default pipeline workers: 4
Pipeline main started
{
           "ended" => "2016-04-25T04:45:00.000Z",
         "started" => "2016-04-25T03:45:00.000Z",
        "@version" => "1",
      "@timestamp" => 2016-04-25T12:15:18.194Z,
            "host" => "skywalker",
    "duration_hrs" => 3600.0,
            "tags" => [
        [0] "duration_hrs"
    ]
}
```

my thoughts are confused here, would be nice to that you take this conf in parts and try to see where this error might be coming from, certainly is not from the ruby filter parse as strings, so I guess the error might be comming from:

```ruby 
code => "event['duration_hrs'] = Time.parse(event['ended']).to_f - Time.parse(event['started']).to_f"
```

because at this point `event['ended']` and  `event['started']` are not strings, but from Timestamp class, can you make sure to either, to the `-` between them, without the parse, or do a `.to_s` when doing the parse?

I guess this might fix your issue.

**Comment by linhntt41** [comment]
Thanks @purbon 
after fix, I have problem ** Failed to query elasticsearch for previous event ** 
elasticsearch {
hosts => ["localhost"]
query => "status:in AND username:%{[username]}"
fields => ["started","ended"]
}

**Error**
Failed to query elasticsearch for previous event {:query=>"status:in AND username:test}", :event=>#<LogStash::Event:0x448769a0 @metadata_accessors=#<LogStash::Util::Accessors:0x68923cd6 @store={"path"=>"/opt/file1.log"}, @lut={"[path]"=>[{"path"=>"/opt/file1.log"}, "path"]}>, @cancelled=false, @data={"message"=>"", "@version"=>"1", "@timestamp"=>"2016-04-26T02:55:43.702Z", "path"=>"/opt/file1.log", "host"=>"elk.test.vn", "tags"=>["_grokparsefailure"]}, @metadata={"path"=>"/opt/file1.log"}, @accessors=#<LogStash::Util::Accessors:0xe6f39da @store={"message"=>"", "@version"=>"1", "@timestamp"=>"2016-04-26T02:55:43.702Z", "path"=>"/opt/file1.log", "host"=>"elk.test.vn", "tags"=>["_grokparsefailure"]}, @lut={"path"=>[{"message"=>"", "@version"=>"1", "@timestamp"=>"2016-04-26T02:55:43.702Z", "path"=>"/opt/file1.log", "host"=>"elk.test.vn", "tags"=>["_grokparsefailure"]}, "path"], "host"=>[{"message"=>"", "@version"=>"1", "@timestamp"=>"2016-04-26T02:55:43.702Z", "path"=>"/opt/file1.log", "host"=>"elk.test.vn", "tags"=>["_grokparsefailure"]}, "host"], "message"=>[{"message"=>"", "@version"=>"1", "@timestamp"=>"2016-04-26T02:55:43.702Z", "path"=>"/opt/file1.log", "host"=>"elk.test.vn", "tags"=>["_grokparsefailure"]}, "message"], "tags"=>[{"message"=>"", "@version"=>"1", "@timestamp"=>"2016-04-26T02:55:43.702Z", "path"=>"/opt/file1.log", "host"=>"elk.test.vn", "tags"=>["_grokparsefailure"]}, "tags"], "[status]"=>[{"message"=>"", "@version"=>"1", "@timestamp"=>"2016-04-26T02:55:43.702Z", "path"=>"/opt/file1.log", "host"=>"elk.test.vn", "tags"=>["_grokparsefailure"]}, "status"]}>>,

**Comment by purbon** [comment]
Hi,
 this looks to me like a more help issue, we try to keep this for tracker for bugs and use http://discuss.elastic.co/ as a forum to support our users, I encourage you to send this question there and the very suportive community will help you throught your configuration issues. If you find an issue don't hesitate to reopen an new issue here.
