### ISSUE TITLE
New output plugin for monasca-log-api

### ISSUE THREAD

**Issue by kejc87** [elastic/logstash#5195]
Hello,

my name is Kamil and i am a software developer at Fujitsu Enabling Software Technology in Munich. We are working on a Monitoring Solution called Monasca (https://wiki.openstack.org/wiki/Monasca). It is an Openstack project. Because we are using logstash as an agent for collecting logs, we wrote an output-plugin for monasca (called logstash-output-monasca-log-api, https://github.com/FujitsuEnablingSoftwareTechnologyGmbH/logstash-output-monasca_log_api). This is our first plugin and we would like to contribute/migrate this plugin to you.

Regards,

Kamil

**Comment by kejc87** [comment]
Hello,

i am wondering if you you need any additional information from us?

Regards,

Kamil

**Comment by witekest** [comment]
Dear Logstash developers,
we use Logstash as the agent for the OpenStack Monasca Log API https://github.com/openstack/monasca-log-api . The logstash-output-monasca_log_api plugin which is published at RubyGems.org is installed by our devstack plugin (https://github.com/openstack/monasca-log-api/tree/master/devstack). It would be great if we could also contribute the code to logstash-plugins. We would be grateful for code reviews.

Thanks
Witek

**Comment by untergeek** [comment]
Hello, friends!  Sorry for the delayed response.  We're hard at work on Logstash 5.0, so we've been a bit behind on community response, for which I apologize.

I think we can work with you on this.  I will raise this possibility with the rest of the team.  Thank you for your submission, and your willingness to support it going forward.

**Comment by kejc87** [comment]
Thanks for your help. If you need any additional information, just ask.

**Comment by suyograo** [comment]
@kejc87 thanks for your contribution. I created a new repo in our plugin org. Can you do a PR there to move it? https://github.com/logstash-plugins/logstash-output-monasca_log_api Let us know if you have a question.

**Comment by witekest** [comment]
Thanks Suyog. I have just submitted the PR with the content of our existing repo.

**Comment by suyograo** [comment]
@witekest @kejc87 Sorry for dropping the ball on this. I merged your PR and added you to contributors.

**Comment by witekest** [comment]
Thanks a lot for taking it in. Great!

**Comment by acchen97** [comment]
Closed with https://github.com/logstash-plugins/logstash-output-monasca_log_api/pull/1.
