### ISSUE TITLE
Ubuntu 14.04 logstash 2.3.2-1 service logstash restart failed

### ISSUE THREAD

**Issue by Slach** [elastic/logstash#5201]
after run
apt-get install logstash
and set /etc/default/logstash
KILL_ON_STOP_TIMEOUT=1

service logstash stop 
failed with following error

/etc/init.d/logstash: 100: [: 1: unexpected operator

on /etc/init.d/logstash in first line i see 

#!/bin/sh

but in line 100 i see 
if [ "$KILL_ON_STOP_TIMEOUT" == 1 ] ; then

this not work in sh, only for bash

**Comment by ph** [comment]
I will review this https://github.com/elastic/logstash/pull/5202

Oh `sh`!

**Comment by ph** [comment]
I have merged #5202 in the different branches, Thanks for reporting!
