### ISSUE TITLE
Internal variable length queuing

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5205]
We should add support for internal Logstash queues to be variable length.  This will help reduce the reliance of third party queuing layers like Kafka/Redis in order to gracefully handle ingestion spikes and backpressure.  It'll also help with overall overhead for scaling ingestion architectures from scratch with Logstash.

**Comment by jordansissel** [comment]
This is in the roadmap for persistence queues. I don't remember the issue though.

**Comment by suyograo** [comment]
Closing this as a dup of https://github.com/elastic/logstash/issues/2606. @acchen97 please enhance any requirements in #2606

**Comment by acchen97** [comment]
Didn't see this on initial search, thanks for linking...
