### ISSUE TITLE
Smoke tests in Java

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5207]
I'd like to be able to write smoke tests in Java because:
1. Its platform independent, so i can write 1 test for win and *nix
2. Its easy to start/stop ES from within the test. 

/cc @talevy

**Comment by purbon** [comment]
@suyograo would you be so nice to create a more detailed description about what an smoke test will looks like? this issue it's just a technology description 👍 

I've not much of problems to write them in java if is the easiest to handle ES in this case. One thing that would be nice to know of close by reality this test should be? how are you thinking to start your ES server? embed?

Thanks for taking care of it,

- purbon
