### ISSUE TITLE
.sincedb is not updated properly

### ISSUE THREAD

**Issue by alextsm** [elastic/logstash#5210]
Hello, I have a problem with update .sincedb database.
Sometimes (not always, but the input files always the same), a new record of last processed file appears in .sincedb only after logstash has restarted by me.

My environment are:
LS: 2.3.1
OS: RHEL 6.6
Config File is:
input { 

file {
path => "/mnt/ramdisk0/processing/*"
exclude => "*.gz"
start_position => 'beginning'
}
}

output {  
    kafka {
	codec =>  line {  format => '%{message}' }
	bootstrap_servers => 'cnode1:9092,cnode2:9092,cnode3:9092'  
        topic_id => 'test_p1_%{+YYYY.MM.dd}'

		}
}

**Comment by markwalkom** [comment]
You would be better off asking this on the forums - https://discuss.elastic.co

**Comment by alextsm** [comment]
Ok, thanks
