### ISSUE TITLE
Make the acceptance test use the the current logstash package.

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5212]
The current acceptance test only work with the remote logstash package.

I don't think this is necessary and should be refactored to work with the current logstash version which is a Logstash snapshot version by itself.

So running the acceptance test would do the following.

- Make the artifacts, tar, deb, rpm
- Run the acceptance test on the generated artifact.

**Comment by ph** [comment]
The packages will be generated and make available in a `vagrant shared folder` and will be renamed to 


```
logstash-current-snapshot.deb
logstash-current-snapshot.deb
logstash-current-snapshot.zip
logstash-current-snapshot.tar.gz
```

We will need some logic in place to simulate an upgrade scenario, fetch a previous package?

**Comment by purbon** [comment]
closing this as this is already an option and the way the test are designed.
