### ISSUE TITLE
translation missing: en.logstash.runner.flag.debug_config

### ISSUE THREAD

**Issue by ecki** [elastic/logstash#5216]
When I run logstash 2.3.2 on german Win64 with --help option the resulting usage text displays a missing translation for

    --debug-config                translation missing: en.logstash.runner.flag.debug_config (default: false)

BTW: it is not the first time I had this, maybe add an test calling `--help` and grepping for the error message before shipping?

**Comment by ph** [comment]
@ecki  We just merged a new test to make sure theses errors doesnt happen again, I will make a PR to fix that.

See this PR for the new test in place. https://github.com/elastic/logstash/pull/5158

**Comment by ph** [comment]
We seems to have a few missing keys in the 2.X branch.

http://build-eu-1.elasticsearch.org/job/logstash_regression_23/jdk=JDKEA8,label=metal-pool/lastBuild/console
