### ISSUE TITLE
Logstash - sendmail.rb:72 warning: unsupported popen option: err

### ISSUE THREAD

**Issue by parthuA1** [elastic/logstash#5220]
- Version: Logstash 2.3.1
- Operating System:UNIX

I recently moved to Logstash 2.3.1 and ever since then, I keep getting this issue: 

I just use this in the config file:   via => "sendmail" 

logstash/vendor/bundle/jruby/1.9/gems/mail-2.6.3/lib/mail/network/delivery_methods/sendmail.rb:72 warning: unsupported popen option: err

**Comment by purbon** [comment]
Thanks for reporting your error, I will close this as is duplicated of https://github.com/logstash-plugins/logstash-output-email/issues/22 that is the plugin responsible of this behaviour.

Feel free to report there all plugin related issues you might have.
