### ISSUE TITLE
Unwanted field merge

### ISSUE THREAD

**Issue by referup-tarantegui** [elastic/logstash#5231]
Hi, I have a problem. Logstash is merging two fields in one from a syslog message. I'm running the latest versions of logstash (2.3.2), kibana (4.5.0) and elasticsearch (2.3.2)

I've got this filter on my logstash conf file:

```
filter {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
    }
}
```

Here is a sample message from syslog:

```
May  2 11:38:34 localhost docker/mp-test-f57ac7634c2c[1815]: May 02, 2016 9:38:50 INFO atsNewStatus = 57
```

In kibana I'm seeing these fields, following my logstash filter

```
Time: May 2nd 2016, 11:38:34.713    
syslog_hostname: localhost  
syslog_message: atsNewStatus = 57   
syslog_program: docker/mp-infojobs-bidir-f57ac76 INFO
syslog_pid: 1815
syslog_timestamp: May  2 11:38:34
```

As you can see, logstash is merging a part of **syslog_message** inside of **syslog_program** and cutting the docker ID. 

Thanks for the help.

**Comment by kares** [comment]
seems like this was a grok pattern problem - the proper issue tracker for this is at: https://github.com/logstash-plugins/logstash-patterns-core/issues
