### ISSUE TITLE
Support default value for %{field}

### ISSUE THREAD

**Issue by mjiderhamn** [elastic/logstash#5238]
Logstash configuration has support for dynamic configuration using `%{field}` and `${ENVIRONMENT_VARIABLE}`. As per [the documentation](https://www.elastic.co/guide/en/logstash/current/environment-variables.html), environment variables also allows for specifying defaults as such: `${ENVIRONMENT_VARIABLE:default value}`.

Please add support for specifying defaults for `%{field}` too, i.e. `%{field:default value}`.

**Comment by suyograo** [comment]
Dup of https://github.com/elastic/logstash/issues/4416
