### ISSUE TITLE
Logstash reports [0] _grokparsefailure

### ISSUE THREAD

**Issue by kan1207** [elastic/logstash#5246]
I am using Logstash 2.3 and I have the following conf file.

I would expect to see in Kibana in the "Fields" section on the left the options for "JobID" displaying my job codebut I don't.

I see

@timestamp
@version
_id
_index
_type host path
I do see in the _source section on the right side the following...

This is the message I received when I run the .conf file
[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/fBio4.png

    input{
    	file{
    		path => "C:/Job/Code.txt"
    		start_position => "beginning"
    	}
    }
    filter{
    	json{source => "message"}
    	grok{
    	match => ["@message","%{WORD:job_id}"]
    	add_tag => "grokked"
        	}
    mutate {
            add_field => [ 'JobID', "%{job_id}" ]
        }
    }
    output{
      	elasticsearch { hosts => ["localhost:9200"] }
      	stdout { codec => rubydebug }	
    }

My txt file only contains 4 roles

    0001
    0002
    0003
    0004

Thanks

**Comment by jordansissel** [comment]
This sounds like a configuration issue, not a bug, and we use github issues for bugs and feature discussion. You'll find lots of great help for this kind of problem over at https://discuss.elastic.co/ in the Logstash forum :)
