### ISSUE TITLE
What is the best way to check the http_poller is sending logs to kibana logstash-* ?

### ISSUE THREAD

**Issue by navdeepghotra** [elastic/logstash#5247]
ELK and http_proxy is fully configured on my system: -

I did below steps to install http_poller plugin

But my question is,  i am not getting any data related to my http_poller on kibana logstash-*, I already tested my http_poller.config by "./logstash -f http_poller.config", which gives me status 200 ok. But while making data histogram graphs , i am not seeing tags related data on logstash-* kibana.  

**Steps to setup and below is attachment for http_poller.config which i am using **
1.  cd /opt/logstash/bin/  

run below command :-  (to install http_poller)
./logstash-plugin install logstash-input-http_poller
./logstash-plugin install --no-verify   (This command will add gem "logstash-input-http_poller" to path /opt/logstash/Gemfile) 

2. cd /application/logstash-2.3.1/bin

run below command :-  (to install http_poller)  
./logstash-plugin install logstash-input-http_poller
./logstash-plugin install --no-verify   (This command will add gem "logstash-input-http_poller" to path /application/logstash-2.3.1/Gemfile)

3. cd /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-http_poller-2.0.5
AND cd /application/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-input-http_poller-2.0.5

nano Gemfile = configure https://ruby.taobao.org/ instead of https://rubygems.org/

gem sources --remove https://rubygems.org/

gem sources --add https://ruby.taobao.org/

gem sources -l

4. Make ur http_poller.config at path (/opt/logstash/bin)by referening below files:- 
nano /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-http_poller-2.0.5/lib/logstash/inputs/http_poller.rb
nano /application/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-input-http_poller-2.0.5/lib/logstash/inputs/http_poller.rb

5. chmod a+rwx http_poller.cong

6. test the config "http_poller.cong" by  running this command " ./logstash -f http_poller.conf " at path "/opt/logstash/bin"

5.  gem install sinatra

**http_poller.config**

input {
  http_poller {
   urls => {
      test1 => "http://localhost:9200"
      test2 => {
        # Supports all options supported by ruby's Manticore HTTP client
        method => get
        url => "http://localhost:9200/_cluster/health"
        headers => {
          Accept => "application/json"
        }
        auth => {
          user => "AzureDiamond"
          password => "hunter2"
        }
      }
    }
    automatic_retries => 0
    
    interval => 10
    
    request_timeout => 8
    
    metadata_target => http_poller_metadata
    
    tags => website_healthcheck
  }
}

filter {
  if [http_poller_metadata] {
    mutate {
      add_field => {
        "@host" => "%{http_poller_metadata[name]}"
      }
    }
  }

  
  if [http_poller_metadata][runtime_seconds] and [http_poller_metadata][runtime_seconds] > 0.5 {
    mutate {
      add_tag => "slow_request"
    }
  }

  
  if [http_request_failure] or
     [http_poller_metadata][code] != 200 {

     mutate {
       add_tag => "bad_request"
     }
 }

 if "bad_request" in [tags] {
    throttle {
      key => "%{@host}-RequestFailure"
      period => 600
      before_count => -1
      after_count => 1
      add_tag => "throttled_poller_alert"
    }

    if "throttled_poller_alert" in [tags] {
      drop {}
    }
	
    mutate {
      add_field => {
        sns_subject => "%{@host} is not so healthy! %{@tags}"
        sns_message => '%{http_request_failure}'
        codec => json

      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
  }
  stdout {
    codec => rubydebug
  }
}

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
