### ISSUE TITLE
Logstash 5.0.0-alpha2 won’t start with RMQ output enabled

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#5257]
Unsure if this is a Logstash or RMQ plugin issue. I raised this on discuss.elastic.co several days ago but got no response.

Since upgrading from LS 5.0.0 alpha1 to alpha2, Logstash is aborting startup if the RMQ output is enabled.

> Pipeline aborted due to error {:exception=>java.security.NoSuchAlgorithmException: true SSLContext not available < snip >

Output config:
```
    rabbitmq {
      host => "dev-queue1"
      exchange => "from-ingress"
      exchange_type => "direct"
      key => "filter-routing-key"
      ssl => "true"
      port => "5671"
      user => "logstash_user"
      password => "..."
      durable => "true"
      persistent => "true"
    }
```

Ubuntu 14.04 amd64
Logstash 1:5.0.0~alpha2-1
logstash-output-rabbitmq 3.0.9
openjdk-8-jre-headless 8u91-b14-0ubuntu4~14.04

Attempting to upgrade the RMQ plugin fails.

Currently, alpha 2 is completely unusable in our dev environment due to our reliance on queues.

**Comment by purbon** [comment]
Thanks for reporting this @ceeeekay , where you able to isolate this as SSL error? is the error also showing up without `ssl => "true"` ?

**Comment by ceeeekay** [comment]
Hi @purbon, I've not tried *without* `SSL => true`, however setting `SSL => false` produces the same error, but with "false" in the error message.

I notice I had a double-quote in my paste earlier - this was a typo while entering this issue and is not present in my config.

Thanks :)

**Comment by andrewvc** [comment]
@ceeeekay this should be fixed in https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/22

Thanks for the report :)

**Comment by andrewvc** [comment]
@ceeeekay we hope to release new RMQ plugins soon to deal with this.

**Comment by suyograo** [comment]
Closing this in favor of logstash-plugins/logstash-mixin-rabbitmq_connection#22
