### ISSUE TITLE
Translate plugin documentation does not mention required file extension for dictionary

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/logstash#5261]
I ran into an issue where Logstash (2.3) wouldn't start and translate plugin threw an error telling me [the dictionary is not valid](https://discuss.elastic.co/t/failed-to-start-logstash-invalid-dictionary-format-for-translate-plugin/49088) even though it used to work and according to the documentation at https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html#plugins-filters-translate-dictionary_path the format is just fine.

It turned out the file needed to have a .yaml or .yml extension which is not mentioned in the documentation. According to Magnus Bäck, it might be a bug in the documentation generator since that requirement is mentioned in the source code.

**Comment by Akshaykapoor** [comment]
+1 Should be updated in the docs

**Comment by PhaedrusTheGreek** [comment]
+1 - hit this

**Comment by dedemorton** [comment]
Fixed in https://github.com/logstash-plugins/logstash-filter-translate/pull/40
