### ISSUE TITLE
Remove feature flag for environment variable support

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5263]
In 2.3 we [added a feature flag](https://github.com/elastic/logstash/pull/4963/files) for environment variable support in config since it broke stuff when passwords had `$`. Since this is a very popular feature, we should make it work out of the box for 5.0, where we have a chance to document breaking changes. 

- [ ] Only allow `${my_env_var}` syntax for expanding environment variables in config. Do not expand `$my_var`
- [ ] Remove `--allow-env` 
- [ ] Add tests for values with `$`
- [ ] Update documentation

**Comment by talevy** [comment]
let me know what you think!: https://github.com/elastic/logstash/pull/5265
