### ISSUE TITLE
Logstash 5.0.0-alpha2 - Can’t update plugins

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#5264]
I'm trying to update plugins to resolve an existing RMQ problem with 5.0.0-alpha2, but getting two different issues:

Updating a specific plugin with, e.g., `bin/logstash-plugin update logstash-output-rabbitmq` responds with 

> Update is not supported for manually defined plugins or local .gem plugin installations, skipping

Trying to update all plugins with `bin/logstash-plugin update` asks me to confirm upgrading a number of plugins, and then fails after confirming logstash-filter-fingerprint with

> ERROR: Updated Aborted, message: undefined method `version' for nil:NilClass

So it appears that I'm not able to update any plugins at all. Is this known behaviour for this version?

Ubuntu 14.04 amd64
Logstash 1:5.0.0~alpha2-1
openjdk-8-jre-headless 8u91-b14-0ubuntu4~14.04

**Comment by purbon** [comment]
Good morning,
   thanks for your report,

I just tested the tar.gz package now and for the case of plugin update I do see:

```
skywalker% ./bin/logstash-plugin list --verbose | grep rabbitmq
logstash-input-rabbitmq (4.0.1)
logstash-output-rabbitmq (3.0.9)
skywalker% ./bin/logstash-plugin update logstash-output-rabbitmq
You are updating logstash-output-rabbitmq to a new version 4.0.1, which may not be compatible with 3.0.9. are you sure you want to proceed (Y/N)?
Y
Updating logstash-output-rabbitmq
No plugin updated
```
(same thing for updating all plugins)

Also from the `deb` package in the same config as you:

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo /opt/logstash/bin/logstash-plugin update logstash-output-rabbitmq
You are updating logstash-output-rabbitmq to a new version 4.0.1, which may not be compatible with 3.0.9. are you sure you want to proceed (Y/N)?
y
Updating logstash-output-rabbitmq
No plugin updated
```
(same thing for all plugins update)

I guess what you encountered is a transitive problem while the big java event refactor took place, but any other detail you can provide is going to be helpful to debug this.

**Comment by ceeeekay** [comment]
Hi @purbon 

I think part of my issue is related to #5279 

The "update aborted" message is still occurring, however.
Here is the entire output from a fresh install (i.e., remove package, rm /opt/logstash, reinstall): 

>`# dpkg -i logstash_5.0.0~alpha2-1_all.deb`
Selecting previously unselected package logstash.
(Reading database ... 130403 files and directories currently installed.)
Preparing to unpack logstash_5.0.0~alpha2-1_all.deb ...
Unpacking logstash (1:5.0.0~alpha2-1) ...
Setting up logstash (1:5.0.0~alpha2-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
>
>`# /opt/logstash/bin/logstash-plugin update`
You are updating logstash-codec-collectd to a new version 3.0.1, which may not be compatible with 2.0.4. are you sure you want to proceed (Y/N)?
y
You are updating logstash-codec-dots to a new version 3.0.1, which may not be compatible with 2.0.4. are you sure you want to proceed (Y/N)?
y
`<snip>`
You are updating logstash-filter-drop to a new version 3.0.1, which may not be compatible with 2.0.4. are you sure you want to proceed (Y/N)?
y
You are updating logstash-filter-fingerprint to a new version 3.0.1, which may not be compatible with 2.0.5. are you sure you want to proceed (Y/N)?
y
ERROR: Updated Aborted, message: undefined method `version' for nil:NilClass

**Comment by purbon** [comment]
>  It turns out the error Update is not supported for manually defined plugins or local .gem plugin installations is related to a local plugin I had installed, however I don't think the plugin manager should be complaining about this when trying to update a completely different plugin by name, e.g., logstash-output-rabbitmq.

this is completely true both things, would you mind opening an specific issue for the latest?

**Comment by ceeeekay** [comment]
@purbon Happy to open a new issue, but I'm not 100% sure which of the issues you're referring to.

**Comment by purbon** [comment]
> is related to a local plugin I had installed, however I don't think the plugin manager should be complaining about this when trying to update a completely different plugin by name

plugin manager should not complain.

**Comment by purbon** [comment]
I can't reproduce your issue, I'm guessing this might be due to some problem in your custom plugin, can you share how your .gemspec file looks like?

**Comment by ceeeekay** [comment]
@purbon this is occurring on a fresh install without any custom plugins.

I don't see a specific .gemspec, unless you were referring to the .gemspec for the (absent) custom plugin. Do you have a path to the one you need?

**Comment by ceeeekay** [comment]
Further note: I can reproduce this on a number of machines. Steps to reproduce:

1. `dpkg -i logstash-5.0.0-alpha2_all.deb`

1. `/opt/logstash/bin/logstash-plugin update`

1. Answer Y or N to the update questions

1. After answering Y or N to `You are updating logstash-filter-fingerprint...` the error occurs.

Tested on Ubuntu 14.04 and 12.04, with no previous logstash installations and both openjdk-7and openjdk-8
