### ISSUE TITLE
Update required java version for Logstash in documentation

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5266]
According to https://github.com/elastic/logstash/blob/07887f8cf70079b3de0cd1e59ed6fc07b4a9ea74/logstash-core/lib/logstash/runner.rb#L157-L161 we enforce to use java8, however in the documentation we still see java7 requirement (see https://github.com/elastic/logstash/blob/master/docs/static/getting-started-with-logstash.asciidoc#installing-logstash).

this should be updated, including other possible missed old bits.

**Comment by suyograo** [comment]
Fixed in #5298
