### ISSUE TITLE
Example plugins are still using logstash-core in their references

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5269]
See:
- https://github.com/logstash-plugins/logstash-input-example/blob/master/logstash-input-example.gemspec
- https://github.com/logstash-plugins/logstash-output-example/blob/master/logstash-output-example.gemspec
- https://github.com/logstash-plugins/logstash-filter-example/blob/master/logstash-filter-example.gemspec

all this should be updated to use the new plugin-core-api dependency.

**Comment by ph** [comment]
Good catch!

**Comment by ph** [comment]
@purbon Can you look at the PR link in this issue so we can close this one?

**Comment by purbon** [comment]
this was done a few days a go @ph, good to merge all them 👍

**Comment by ph** [comment]
I've taken the time to recheck both PR and there was a small discrepancy  with the others plugins concerning the version constraints on the `logstash-core-plugin-API` gem. I've updated them to make sure they correctly followed the ranges.
