### ISSUE TITLE
a problem that  chinese words is  garbled

### ISSUE THREAD

**Issue by zxy12** [elastic/logstash#5272]
I am using the same logstash package and the same jre,but i found some machine's chinese words is garbled, i  am confuse,please help me fix this issue.

For all general issues, please provide the following details for fast resolution:

- Version:2.3
- Operating System:centos6.4
- Config File (if you have sensitive info, please remove it):
- Sample Data: 中文
- Steps to Reproduce:

the correct output is  like this：
[logstash@master1 logstash]$ bin/logstash -e 'input { stdin { } } output { stdout {} }'
Settings: Default pipeline workers: 1
Pipeline main started
abc
2016-05-10T14:18:52.616Z master1 abc
中文
2016-05-10T14:18:55.864Z master1 中文

the bad output is like this:
logstash-2.3.0]$ bin/logstash -e 'input { stdin { } } output { stdout {} }'
Settings: Default pipeline workers: 4
Pipeline main started
z
2016-05-10T13:15:45.175Z master1 z
中
2016-05-10T13:15:48.709Z master1 ?

the chinese is became a question-mark..i don't know why.

**Comment by zxy12** [comment]
i found the same issue when use filebeat, i try to use codec => plain {charset=>"UTF-8"} ,but not work

**Comment by zxy12** [comment]
does the logstash have any relation to /etc/sysconfig/i18n?

**Comment by suyograo** [comment]
Moved to #5048
