### ISSUE TITLE
Plugin test fails to run in the `plugin-api-v1` branch of the plugin

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5273]
This was originally reported by @andrewvc,

When you try to run the tests inside the v1 branch you could get the following

```
  6) outputs/elasticsearch with timeout set should fail after the timeout
     Failure/Error: Thread.new { eso.receive(LogStash::Event.new) }
     NoMethodError:
       undefined method `[]' for 2016-05-09T23:47:29.890Z %{host} %{message}:LogStash::Event
```
By doing a bit more investigation and by reading the log of the `bundle install` command we can see that `bundler` is picking up the last version of the `logstash-core-event-java` which implement the interface changes.

```
Using logstash-core-event-java 5.0.0.beta1.snapshot1
Using logstash-core 5.0.0.alpha2
Using logstash-core-plugin-api 1.13.0
```

This mean one of our dependency is incorrectly defined, in this case the `logstash-core` define the dependency on the `logstash-core-event-java` as this:

```
logstash-core-event-java ~> 5.0.0.alpha2 # incorrect version.
logstash-core-event-java = 5.0.0.alpha2 # correctly strict defined version.

# Verification
 Gem::Requirement.new("~> 5.0.0.alpha2").satisfied_by?(Gem::Version.new("5.0.0.beta1.snapshot1"))
=> true
```

The problem with declaring a dependency like this is that it will accept minor version and **beta1.snapshot** is considered a minor version update. 

**Actions to take to fix the problem**

- [x] We will publish a new `logstash-core-5.0.0.alpha3.snapshot1`
- [x] We will publish a new `logstash-core-plugin-api-0.14` depending on `logstash-core-5.0.0.alpha3.snapshot1`
- [x] We will yank the `logstash 5.0.0.beta1.snapshot1`,`logstash-core-event-java.beta1.snapshot1` and `logstash-core-plugin-api-2.0`
- [x] We will publish `logstash 5.0.0.beta1.snapshot2`,`logstash-core-event-java.beta1.snapshot2` and `logstash-core-plugin-api-2.1`

By releasing a new  `logstash-core-5.0.0.alpha3.snapshot1`, the bundle install will pick it up and use the right dependency on the event.

**Comment by colinsurprenant** [comment]
thanks @ph for digging this. the plan seems good.

**Comment by suyograo** [comment]
+1 to proceed

**Comment by colinsurprenant** [comment]
There is also an issue with devutils, see elastic/logstash-devutils/issues/48

**Comment by ph** [comment]
All the gems were publish and yanked following the plan.
