### ISSUE TITLE
Update Logstash to the new version of jrjackson to support json logging

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5278]
With the ability to log error in json we need to make sure that we ship the next release of Logstash (2.4.0 and 5.0.0 beta1) with new version of jrjackson that can handle serialization of exceptions and ruby class.

Reference:
https://github.com/elastic/logstash/issues/1569
https://github.com/guyboertje/jrjackson/issues/54

**Comment by guyboertje** [comment]
Will be publishing v 0.4.0 today.

**Comment by guyboertje** [comment]
0.4.0 is published
