### ISSUE TITLE
Logstash 5.0.0-alpha2 - Plugin manager always complains about user-installed plugins

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#5280]
If the user has manually installed plugins, and then attempts to update a *packaged* plugin, logstash-plugin notifies the user that manually installed plugins can not be updated:

This can be confusing to the user, as it's not relevant information if they are trying to update a specific packaged plugin by name.

E.g., 
`# /opt/logstash/bin/logstash-plugin update logstash-output-rabbitmq` 
> Update is not supported for manually defined plugins or local .gem plugin installations, skipping
... [remainder of plugin update proceeds from this point]

**Comment by ceeeekay** [comment]
@purbon

**Comment by purbon** [comment]
This happen due to https://github.com/elastic/logstash/blob/master/lib/pluginmanager/update.rb#L34-L36 and the fact that we run this for all plugins, logic there should be improved and made a bit more intelligent.

**Comment by suyograo** [comment]
Fixed in alpha5
