### ISSUE TITLE
Logstash 5.0.0-alpha2 - Host & port settings for monitoring APIs not documented

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#5285]
While trying to start a second Logstash instance, with no network input, I encountered the following
>`<Errno::EADDRINUSE: Address already in use - bind - Address already in use>`

This was caused by the monitoring API trying to bind to tcp:9600, which was already in use by another Logstash instance.

I was unable to find any reference to setting the API port or host in the 5.0.0-alpha2 docs. I've since found a reference to `--http-host` and `--http-port` elsewhere, however this was not easy to find.

Could the docs please be updated to include this info for other users? 

It may also be a good idea to have Logstash bind the API service to the next available port. This would avoid having to configure the API for new instances, especially in the case where Logstash is only running temporarily, e.g., in the case of performing a test on a box already running Logstash.

**Comment by acchen97** [comment]
@ceeeekay isn't the host and port settings documented [here](https://www.elastic.co/guide/en/logstash/5.0/command-line-flags.html)?

@ph thoughts on opening the default http bind port to a range?

**Comment by ceeeekay** [comment]
@acchen97 my apologies, I was looking in the API section for this info.

However searching the docs for "API port" doesn't return this result, and I couldn't get a hit from Google either.

Is it worth including a link from the API docs to the command line flags?

**Comment by ph** [comment]
> Is it worth including a link from the API docs to the command line flags?
+ 1

> thoughts on opening the default http bind port to a range?

This feel weird to me, software usually uses one port as their default and don't try multiple port, this would make stuff harder to debug.

I think its not a problem about binding to a specific port, I think we should do a better job at communicating what went wrong, maybe if we do something like this.

"Logstash tried to bind to port XXXX, but the port is already in use. You can specify a new port by launching logtash with the --http-port XXXX option."

**Comment by acchen97** [comment]
> This feel weird to me, software usually uses one port as their default and don't try multiple port, this would make stuff harder to debug.

@ph doesn't ES do 9200-9300?

> Logstash tried to bind to port XXXX, but the port is already in use. You can specify a new port by launching logtash with the --http-port XXXX option."

+1

> Is it worth including a link from the API docs to the command line flags?

@ceeeekay added this to our doc task list.. thanks

**Comment by ph** [comment]
> @ph doesn't ES do 9200-9300?

ES Web is 9200, internal cluster communication is done 9300, I think this is where both of your numbers are coming from?

**Comment by ph** [comment]
I've created https://github.com/elastic/logstash/issues/5290 for added better user feedback

**Comment by acchen97** [comment]
Fixed with https://github.com/elastic/logstash/pull/5489 and https://github.com/elastic/logstash/pull/5316.
