### ISSUE TITLE
Track slow execution in Logstash

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5287]
MySQL, Elasticsearch, and many other systems have a concept of a "slow log", and it makes sense to have something similar in Logstash.

Proposal:
- Configurable value of what is meant by "slow"
- Actions taking more than the slow-time to complete shall be logged.
- The log level for these slow actions shall be `warn`
- The content of the slow log shall contain the any context about the slow action. For example: the plugin, the event, the duration of the action, information about the action.

**Comment by suyograo** [comment]
Fixed in 5.2
