### ISSUE TITLE
Update the documentation concerning "How to create a plugin"

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5293]
All the documentation concerning creating a custom plugin need to have their gemspec updated.

https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html
https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_codec_plugin.html
https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html
https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html

This line need to be replaced

```
s.add_runtime_dependency 'logstash-core', '>= 1.4.0', '< 2.0.0'
```

With

```
  s.add_runtime_dependency 'logstash-core-plugin-api', '~> 2.0'
```

**Comment by suyograo** [comment]
Fixed
