### ISSUE TITLE
Unsafe shutdown config option not documented

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5294]
The --allow-unsafe-shutdown option is missing in command line flags [page](https://www.elastic.co/guide/en/logstash/master/command-line-flags.html).  Shall we add it for consistency?

Option: --[no-]allow-unsafe-shutdown  
Force logstash to exit during shutdown even if there are still inflight events in memory.  By default, logstash will refuse to quit until all received events have been pushed to the outputs. (default: false)

/cc @dedemorton @jsvd

**Comment by dedemorton** [comment]
@acchen97 Hasn't this option has been replaced and renamed --pipeline.unsafe_shutdown as part of this PR? https://github.com/elastic/logstash/commit/7783f76a4c29e2d944c807ceea1b4df85383c423

If so, it's documented now.

**Comment by acchen97** [comment]
You're correct, closing...
