### ISSUE TITLE
Logstash road map no longer existant

### ISSUE THREAD

**Issue by hartfordfive** [elastic/logstash#5295]
In a variety of [blog posts](https://www.elastic.co/blog/how-to-check-logstashs-pulse), [documentation pages](https://www.elastic.co/guide/en/logstash-roadmap/current/index.html) and [github issues](https://github.com/elastic/logstash/issues/3782#issuecomment-161443714), you make reference to the Logstash road map although it leads to a 404 page.  It would be great if that could be fixed.  It would be great to know when the new features such as the queue status and event throughput.

**Comment by dedemorton** [comment]
We've recently removed that topic from the documentation. We'll work on resolving the 404 error. I do not believe that there are any broken references with the documentation, but please let me know if you see any. Note that most of the references are in older blog posts.

@acchen97 Here's the list!

Blog posts:
https://www.elastic.co/blog/high-level-logstash-roadmap-is-published - March 2015
https://www.elastic.co/blog/how-to-check-logstashs-pulse - May 2015
https://www.elastic.co/blog/elasticsearch-storage-the-true-story - April 2015
https://www.elastic.co/blog/logstash-user-survey-results  - April 2015
https://www.elastic.co/blog/logstash-2-0-0-released - Oct 2015
https://www.elastic.co/blog/logstash-2-0-0-beta1-released - Sept 2015
https://www.elastic.co/blog/logstash-lines-2015-10-19 - Oct 2015
https://www.elastic.co/blog/logstash-forwarder-0-4-0-released - March 2015
https://www.elastic.co/blog/announcing-logstash-1-5-0-release-candidate - March 2015
https://www.elastic.co/blog/logstash-1-5-0-ga-released - May 2015

Forum topics:
https://discuss.elastic.co/t/logstash-2-0-monitoring-api/33551
https://discuss.elastic.co/t/logstash-shipper-to-redis/29948/8
https://discuss.elastic.co/t/final-word-on-the-need-for-brokers-with-logstash-2-0/34188

GitHub issues:
https://github.com/elastic/logstash/issues/4915
https://github.com/elastic/logstash/issues/3600

**Comment by dedemorton** [comment]
To fix the 404s, I've asked our web person to set up a redirect to point to the list of GitHub issues flagged as roadmap. Our PM is looking into other options.

**Comment by acchen97** [comment]
@hartfordfive thanks for bringing this up.  As mentioned, we'll fix the 404s soon.  We're working on introducing a higher level roadmap page along with details on how to view our short-term roadmap.

**Comment by dedemorton** [comment]
The redirect is in place. The old URL (https://www.elastic.co/guide/en/logstash-roadmap/current/index.html) now points to https://github.com/elastic/logstash/blob/master/ROADMAP.md
