### ISSUE TITLE
Update remaining plugins with Event API

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5309]
Issue to track updates to plugins which were not updated in https://github.com/elastic/logstash/issues/5227
- [ ] [logstash-filter-cidr](https://github.com/logstash-plugins/logstash-filter-cidr)(@guyboertje)
- [x] [logstash-filter-elasticsearch](https://github.com/logstash-plugins/logstash-filter-elasticsearch)(@guyboertje)
- [ ] [logstash-filter-translate](https://github.com/logstash-plugins/logstash-filter-translate)(@guyboertje)
- [ ] [logstash-filter-punct](https://github.com/logstash-plugins/logstash-filter-punct)(@guyboertje)
- [ ] [logstash-input-github](https://github.com/logstash-plugins/logstash-input-github)(@wiibaa)
- [ ] [logstash-filter-anonymize](https://github.com/logstash-plugins/logstash-filter-anonymize)(@guyboertje)
- [ ] [logstash-codec-cloudtrail](https://github.com/logstash-plugins/logstash-codec-cloudtrail)(@guyboertje)
- [ ] [logstash-codec-compress_spooler](https://github.com/logstash-plugins/logstash-codec-compress_spooler)(@guyboertje)
- [ ] [logstash-codec-oldlogstashjson](https://github.com/logstash-plugins/logstash-codec-oldlogstashjson)(@guyboertje)
- [ ] [logstash-filter-alter](https://github.com/logstash-plugins/logstash-filter-alter)(@guyboertje)
- [ ] [logstash-filter-checksum](https://github.com/logstash-plugins/logstash-filter-checksum)(@guyboertje)
- [ ] [logstash-filter-cipher](https://github.com/logstash-plugins/logstash-filter-cipher)(@guyboertje)
- [ ] [logstash-filter-collate](https://github.com/logstash-plugins/logstash-filter-collate)(@guyboertje)
- [ ] [logstash-filter-elapsed](https://github.com/logstash-plugins/logstash-filter-elapsed)(@guyboertje)
- [ ] [logstash-filter-environment](https://github.com/logstash-plugins/logstash-filter-environment)(@guyboertje)
- [ ] [logstash-filter-extractnumbers](https://github.com/logstash-plugins/logstash-filter-extractnumbers)(@guyboertje)
- [ ] [logstash-filter-i18n](https://github.com/logstash-plugins/logstash-filter-i18n)(@guyboertje)
- [ ] [logstash-filter-json_encode](https://github.com/logstash-plugins/logstash-filter-json_encode)(@guyboertje)
- [ ] [logstash-filter-multiline](https://github.com/logstash-plugins/logstash-filter-multiline)(@guyboertje)
- [ ] [logstash-filter-prune](https://github.com/logstash-plugins/logstash-filter-prune)(@guyboertje)
- [x] [logstash-filter-range](https://github.com/logstash-plugins/logstash-filter-range)(@guyboertje)
- [x] [logstash-input-rss](https://github.com/logstash-plugins/logstash-input-rss)(https://github.com/logstash-plugins/logstash-input-rss/pull/18)
- [x] [logstash-input-drupal_dblog](https://github.com/logstash-plugins/logstash-input-drupal_dblog)(@jsvd) note: doesn't use new or old event api
- [x] [logstash-input-eventlog](https://github.com/logstash-plugins/logstash-input-eventlog)(@jsvd)
- [x] [logstash-input-gemfire](https://github.com/logstash-plugins/logstash-input-gemfire)(@jsvd) note: doesn't use new or old event api
- [x] [logstash-input-heroku](https://github.com/logstash-plugins/logstash-input-heroku)(@jsvd) PR: https://github.com/logstash-plugins/logstash-input-heroku/pull/12 Master status: ![](https://travis-ci.org/logstash-plugins/logstash-input-heroku.svg?branch=master)
- [x] [logstash-input-jmx](https://github.com/logstash-plugins/logstash-input-jmx)(@jsvd) PR: https://github.com/logstash-plugins/logstash-input-jmx/pull/21 Master status: ![](https://travis-ci.org/logstash-plugins/logstash-input-jmx.svg?branch=master)
- [x] [logstash-input-puppet_facter](https://github.com/logstash-plugins/logstash-input-puppet_facter)(@jsvd) PR: https://github.com/logstash-plugins/logstash-input-puppet_facter/pull/6 Master status: ![](https://travis-ci.org/logstash-plugins/logstash-input-puppet_facter.svg?branch=master)
- [x] [logstash-input-rackspace](https://github.com/logstash-plugins/logstash-input-rackspace)(@jsvd) PR: https://github.com/logstash-plugins/logstash-input-rackspace/pull/5 Master status: ![](https://travis-ci.org/logstash-plugins/logstash-input-rackspace.svg?branch=master)
- [ ] [logstash-input-relp](https://github.com/logstash-plugins/logstash-input-relp)(@jsvd) PR: https://github.com/logstash-plugins/logstash-input-relp/pull/16 Master status: ![](https://travis-ci.org/logstash-plugins/logstash-input-relp.svg?branch=master)
- [x] [logstash-input-sqlite](https://github.com/logstash-plugins/logstash-input-sqlite)(@jsvd) PR: https://github.com/logstash-plugins/logstash-input-sqlite/pull/11 Master status: ![](https://travis-ci.org/logstash-plugins/logstash-input-sqlite.svg?branch=master)
- [x] [logstash-input-stomp](https://github.com/logstash-plugins/logstash-input-stomp)(@jsvd)
- [x] [logstash-input-varnishlog](https://github.com/logstash-plugins/logstash-input-varnishlog)(@jsvd) PR: https://github.com/logstash-plugins/logstash-input-varnishlog/pull/4 Master status: ![](https://travis-ci.org/logstash-plugins/logstash-input-varnishlog.svg?branch=master)
- [ ] [logstash-input-websocket](https://github.com/logstash-plugins/logstash-input-websocket)(@jsvd)
- [x] [logstash-input-wmi](https://github.com/logstash-plugins/logstash-input-wmi) (@ph) PR: https://github.com/logstash-plugins/logstash-input-wmi/pull/13 master status: [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-input-wmi.svg)](https://travis-ci.org/logstash-plugins/logstash-input-wmi)
- [ ] [logstash-input-zenoss](https://github.com/logstash-plugins/logstash-input-zenoss) (@ph)
- [x] [logstash-input-zeromq](https://github.com/logstash-plugins/logstash-input-zeromq) (@ph)
- [x] [logstash-output-email](https://github.com/logstash-plugins/logstash-output-email) (@ph)
- [x] [logstash-output-exec](https://github.com/logstash-plugins/logstash-output-exec) (@ph)
- [x] [logstash-output-ganglia](https://github.com/logstash-plugins/logstash-output-ganglia) (@ph)
- [x] [logstash-output-gelf](https://github.com/logstash-plugins/logstash-output-gelf) (@ph)
- [x] [logstash-output-hipchat](https://github.com/logstash-plugins/logstash-output-hipchat) (@ph)
- [x] [logstash-output-juggernaut](https://github.com/logstash-plugins/logstash-output-juggernaut) (@ph)
- [x] [logstash-output-lumberjack](https://github.com/logstash-plugins/logstash-output-lumberjack) (@ph)
- [x] [logstash-output-nagios_nsca](https://github.com/logstash-plugins/logstash-output-nagios_nsca) (@ph)
- [x] [logstash-output-opentsdb](https://github.com/logstash-plugins/logstash-output-opentsdb) (@ph)
- [x] [logstash-output-zeromq](https://github.com/logstash-plugins/logstash-output-zeromq) (@ph)
- [x] [logstash-output-boundary](https://github.com/logstash-plugins/logstash-output-boundary) (@ph) PR https://github.com/logstash-plugins/logstash-output-boundary/pull/4 
  [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-boundary.svg)](https://travis-ci.org/logstash-plugins/logstash-output-boundary)
- [x] [logstash-output-circonus](https://github.com/logstash-plugins/logstash-output-circonus) (@ph) https://github.com/logstash-plugins/logstash-output-circonus/pull/3 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-circonus.svg)](https://travis-ci.org/logstash-plugins/logstash-output-circonus)
- [x] [logstash-output-datadog](https://github.com/logstash-plugins/logstash-output-datadog) (@ph) https://github.com/logstash-plugins/logstash-output-datadog/pull/10  [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-datadog.svg)](https://travis-ci.org/logstash-plugins/logstash-output-datadog)
- [x] [logstash-output-datadog_metrics](https://github.com/logstash-plugins/logstash-output-datadog_metrics) (@ph) https://github.com/logstash-plugins/logstash-output-datadog_metrics/pull/8 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-datadog_metrics.svg)](https://travis-ci.org/logstash-plugins/logstash-output-datadog_metrics)
- [ ] [logstash-output-gemfire](https://github.com/logstash-plugins/logstash-output-gemfire) (@ph)
- [x] [logstash-output-google_bigquery](https://github.com/logstash-plugins/logstash-output-google_bigquery) (@ph) https://github.com/logstash-plugins/logstash-output-google_bigquery/pull/22 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-google_bigquery.svg)](https://travis-ci.org/logstash-plugins/logstash-output-google_bigquery)
- [x] [logstash-output-google_cloud_storage](https://github.com/logstash-plugins/logstash-output-google_cloud_storage) (@ph) https://github.com/logstash-plugins/logstash-output-google_cloud_storage/pull/7 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-google_cloud_storage.svg)](https://travis-ci.org/logstash-plugins/logstash-output-google_cloud_storage)
- [x] [logstash-output-graphtastic](https://github.com/logstash-plugins/logstash-output-graphtastic) (@ph) https://github.com/logstash-plugins/logstash-output-graphtastic/pull/3 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-graphtastic.svg)](https://travis-ci.org/logstash-plugins/logstash-output-graphtastic)
- [x] [logstash-output-influxdb](https://github.com/logstash-plugins/logstash-output-influxdb) (@ph) https://github.com/logstash-plugins/logstash-output-influxdb/pull/49 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-influxdb.svg)](https://travis-ci.org/logstash-plugins/logstash-output-influxdb)
- [ ] [logstash-output-jira](https://github.com/logstash-plugins/logstash-output-jira) (@ph) https://github.com/logstash-plugins/logstash-output-jira/pull/7 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-jira.svg)](https://travis-ci.org/logstash-plugins/logstash-output-jira)
- [x] [logstash-output-librato](https://github.com/logstash-plugins/logstash-output-librato) (@ph) https://github.com/logstash-plugins/logstash-output-librato/pull/6 
  [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-librato.svg)](https://travis-ci.org/logstash-plugins/logstash-output-librato)
- [x] [logstash-output-loggly](https://github.com/logstash-plugins/logstash-output-loggly) (@ph) https://github.com/logstash-plugins/logstash-output-loggly/pull/21 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-loggly.svg)](https://travis-ci.org/logstash-plugins/logstash-output-loggly)
- [x] [logstash-output-metriccatcher](https://github.com/logstash-plugins/logstash-output-metriccatcher) (@ph) https://github.com/logstash-plugins/logstash-output-metriccatcher/pull/5 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-metriccatcher.svg)](https://travis-ci.org/logstash-plugins/logstash-output-metriccatcher)
- [ ] [logstash-output-mongodb](https://github.com/logstash-plugins/logstash-output-mongodb) (@ph) https://github.com/logstash-plugins/logstash-output-mongodb/pull/30 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-mongodb.svg)](https://travis-ci.org/logstash-plugins/logstash-output-mongodb) 
- [ ] [logstash-output-rackspace](https://github.com/logstash-plugins/logstash-output-rackspace) (@ph) https://github.com/logstash-plugins/logstash-output-rackspace/pull/4 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-rackspace.svg)](https://travis-ci.org/logstash-plugins/logstash-output-rackspace)
- [x] [logstash-output-redmine](https://github.com/logstash-plugins/logstash-output-redmine) (@ph) https://github.com/logstash-plugins/logstash-output-redmine/pull/5 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-redmine.svg)](https://travis-ci.org/logstash-plugins/logstash-output-redmine)
- [ ] [logstash-output-riak](https://github.com/logstash-plugins/logstash-output-riak) (@ph) https://github.com/logstash-plugins/logstash-output-riak/pull/2  [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-riak.svg)](https://travis-ci.org/logstash-plugins/logstash-output-riak)
- [ ] [logstash-output-riemann](https://github.com/logstash-plugins/logstash-output-riemann) (@ph) https://github.com/logstash-plugins/logstash-output-riemann/pull/17 [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-riemann.svg)](https://travis-ci.org/logstash-plugins/logstash-output-riemann)
- [x] [logstash-output-solr_http](https://github.com/logstash-plugins/logstash-output-solr_http)
- [x] [logstash-output-stomp](https://github.com/logstash-plugins/logstash-output-stomp)
- [x] [logstash-output-syslog](https://github.com/logstash-plugins/logstash-output-syslog) (@untergeek)
- [x] [logstash-output-websocket](https://github.com/logstash-plugins/logstash-output-websocket) (@untergeek)
- [x] [logstash-output-zabbix](https://github.com/logstash-plugins/logstash-output-zabbix) (@untergeek)
- [ ] [logstash-input-meetup](https://github.com/logstash-plugins/logstash-input-meetup) (@talevy) (PR: https://github.com/logstash-plugins/logstash-input-meetup/pull/7)
- [x] [logstash-output-elasticsearch-ec2](https://github.com/logstash-plugins/logstash-output-elasticsearch-ec2) (@talevy) (PR: https://github.com/logstash-plugins/logstash-output-elasticsearch-ec2/pull/18)
- [x] [logstash-patterns-core](https://github.com/logstash-plugins/logstash-patterns-core) (@talevy)
- [x] [logstash-mixin-aws](https://github.com/logstash-plugins/logstash-mixin-aws) (@talevy)
- [ ] [logstash-filter-metaevent](https://github.com/logstash-plugins/logstash-filter-metaevent) (@talevy) (PR: https://github.com/logstash-plugins/logstash-filter-metaevent/pull/5)
- [x] [logstash-filter-zeromq](https://github.com/logstash-plugins/logstash-filter-zeromq) (@talevy) (PR: https://github.com/logstash-plugins/logstash-filter-zeromq/pull/12)
- [ ] [logstash-codec-s3plain](https://github.com/logstash-plugins/logstash-codec-s3plain) (@talevy) (PR: https://github.com/logstash-plugins/logstash-codec-s3plain/pull/1)
- [ ] [logstash-codec-cloudfront](https://github.com/logstash-plugins/logstash-codec-cloudfront) (@talevy) (PR: https://github.com/logstash-plugins/logstash-codec-cloudfront/pull/4)
- [ ] [logstash-codec-gzip_lines](https://github.com/logstash-plugins/logstash-codec-gzip_lines) (@talevy) (PR: https://github.com/logstash-plugins/logstash-codec-gzip_lines/pull/5)
- [x] [logstash-codec-avro](https://github.com/logstash-plugins/logstash-codec-avro)
- [x] [logstash-filter-metricize](https://github.com/logstash-plugins/logstash-filter-metricize) (@suyograo)
- [x] [logstash-input-journald](https://github.com/logstash-plugins/logstash-input-journald) (@suyograo)
- [ ] [logstash-filter-yaml](https://github.com/logstash-plugins/logstash-filter-yaml) (@suyograo)
- [ ] [logstash-input-example](https://github.com/logstash-plugins/logstash-input-example) (@suyograo)
- [ ] [logstash-codec-example](https://github.com/logstash-plugins/logstash-codec-example) (@suyograo)
- [ ] [logstash-filter-example](https://github.com/logstash-plugins/logstash-filter-example)
  (@suyograo)
- [ ] [logstash-output-example](https://github.com/logstash-plugins/logstash-output-example)
  (@suyograo)
- [x] [logstash-filter-tld](https://github.com/logstash-plugins/logstash-filter-tld)
  (@suyograo)
- [x] [logstash-input-jms](https://github.com/logstash-plugins/logstash-input-jms)
  (@suyograo)
- [x] [logstash-output-jms](https://github.com/logstash-plugins/logstash-output-jms)
  (@suyograo)
- [x] [logstash-filter-oui](https://github.com/logstash-plugins/logstash-filter-oui)
  (@suyograo)
- [x] [logstash-output-logentries](https://github.com/logstash-plugins/logstash-output-logentries)
  (@suyograo)
- [x] [logstash-output-newrelic](https://github.com/logstash-plugins/logstash-output-newrelic)
  (@suyograo)
- [x] [logstash-output-slack](https://github.com/logstash-plugins/logstash-output-slack)
  (@suyograo)
- [x] [logstash-filter-aggregate](https://github.com/logstash-plugins/logstash-filter-aggregate)
  (@suyograo)
- [ ] [logstash-input-neo4j](https://github.com/logstash-plugins/logstash-input-neo4j)
  (@suyograo)
- [ ] [logstash-output-neo4j](https://github.com/logstash-plugins/logstash-output-neo4j)
  (@suyograo)
- [x] [logstash-input-log4j2](https://github.com/logstash-plugins/logstash-input-log4j2)
  (@suyograo)
- [x] [logstash-input-fluentd](https://github.com/logstash-plugins/logstash-input-fluentd)
  (@suyograo)
- [x] [logstash-filter-unique](https://github.com/logstash-plugins/logstash-filter-unique)
  (@suyograo)
- [x] [logstash-codec-cef](https://github.com/logstash-plugins/logstash-codec-cef) (@suyograo)
- [x] [logstash-mixin-http_client](https://github.com/logstash-plugins/logstash-mixin-http_client) (@talevy)
- [ ] [logstash-input-dynamodb](https://github.com/logstash-plugins/logstash-input-dynamodb) (@talevy)
- [ ] [logstash-output-elasticsearch_java](https://github.com/logstash-plugins/logstash-output-elasticsearch_java) (@talevy)
- [ ] [logstash-mixin-rabbitmq_connection](https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection) (@talevy)
- [ ] [logstash-input-salesforce](https://github.com/logstash-plugins/logstash-input-salesforce) (@talevy)
- [ ] [logstash-filter-de_dot](https://github.com/logstash-plugins/logstash-filter-de_dot) (@talevy)
- [ ] [logstash-input-googleanalytics](https://github.com/logstash-plugins/logstash-input-googleanalytics) (@talevy)
- [ ] [logstash-codec-csv](https://github.com/logstash-plugins/logstash-codec-csv) (@talevy)
- [ ] [logstash-input-cloudwatch](https://github.com/logstash-plugins/logstash-input-cloudwatch)
- [ ] [logstash-codec-nmap](https://github.com/logstash-plugins/logstash-codec-nmap) (@suyograo)
- [ ] [logstash-filter-hashid](https://github.com/logstash-plugins/logstash-filter-hashid) (@suyograo)
- [ ] [logstash-filter-bytesize](https://github.com/logstash-plugins/logstash-filter-bytesize) (@suyograo)
- [ ] [logstash-output-rados](https://github.com/logstash-plugins/logstash-output-rados) (@suyograo)
- [ ] [logstash-output-firehose](https://github.com/logstash-plugins/logstash-output-firehose) (@suyograo)
- [ ] [logstash-mixin-zeromq](https://github.com/logstash-plugins/logstash-mixin-zeromq) (@suyograo)
- [ ] [logstash-input-perfmon](https://github.com/logstash-plugins/logstash-input-perfmon) (@talevy)

**Comment by suyograo** [comment]
Here's the plan:

* Update plugins to use the new `set` and `get` API.
* Bump version to next major
* Add `s.add_runtime_dependency "logstash-core-plugin-api", "~> 2.0"` to gemspec so it depends on Plugin API v2
* Update changelog to "Breaking: Updated plugin to use new Java Event APIs"
* Create PR to master.
* One the PR is reviewed, merge and publish

**Comment by suyograo** [comment]
Any help here to update these plugins will be much appreciated. /cc @wiibaa @fbaligand @magnusbaeck :)

**Comment by ph** [comment]
@suyograo Concerning the `logstash-input-zenos`, I believe this plugin is broken was never kept update to date. I've discovered that this plugin uses `bunny`  BUT it also inherit `Logstash::Input::RabbitMQ` which uses `march_hare`. There is not tests in that plugin, so I am not confident that its actually working.  There is an issue from March 31, https://github.com/logstash-plugins/logstash-input-zenoss/issues/4 that said this plugin isn't currently working. Should we rely on the community to update it?

**Comment by wiibaa** [comment]
It would be good to explicitly identify which plugins should be truly deprecated and **how to deprecate a plugin for 5.0**, because removal from default plugins list (https://github.com/elastic/logstash/pull/5254) may not be enough to drive users 

what I know is:

* filter-punct should be deprecated in favor of filter-fingerprint => no issue registered
* filter-checksum should be deprecated in favor of filter-fingerprint => https://github.com/logstash-plugins/logstash-filter-checksum/issues/2
* filter-alter plugin should be deprecated in favor of conditional and mutate with maybe addition to mutate like `coalesce` https://github.com/logstash-plugins/logstash-filter-alter/issues/1
* filter-unique is a one-liner, could go easily into mutate too with a better name => https://github.com/logstash-plugins/logstash-filter-unique/issues/1
* **what else ?**

What would be the expectation in the logstash documentation,
* move the deprecated plugins in a separated area ? avoiding the 404 with a deprecation notice ?
* display a warning notice in the plugin doc ? Instead of copy-pasting a notice in each plugin, maybe providing an asciidoc include one-liner would help

Is this too much breaking changes for 5.x and its ETA ?

**Comment by boernd** [comment]
What's the status of all those plugins? A lot of them do not work out of the box with 5.x (e.g. jmx input, prune filter, riemann output) atm. Any release soon?

**Comment by untergeek** [comment]
The unfinished plugins are community supported. If you're volunteering to help, we would be much obliged. We get to them as fast as we are able, but that is not often as fast as people would like.  That's why we are always looking for [community maintainers](https://www.elastic.co/guide/en/logstash/current/community-maintainer.html).

**Comment by clourens** [comment]
Any news on the plugin update progress ? It's quite a big list, and I don't know if there are major changes for each plugin but this way ELK 5.0 does not seem production ready to me. I would like to help but I can barely get ELK to work, so don't think I'm qualified to update the code ;-)

**Comment by untergeek** [comment]
> but this way ELK 5.0 does not seem production ready to me

Many of these plugins, while hosted in the logstash-plugins repository, were not created by Elastic employees and are not maintained by them, except tangentially as needed.  The benefit of hosting in our repository is that they can be easily found, and documentation can be on our site.  So to address your "production ready" statement, there's a bit more nuance to this.  These plugins are being addressed on an as-needed basis.  "The squeaky wheel gets the grease," kind of thing.

I will take a look at the extractnumbers filter and see if I can update it for 5.0.

**Comment by untergeek** [comment]
@clourens [v3.0 of the extractnumbers filter](https://rubygems.org/gems/logstash-filter-extractnumbers) has been published.  You should be able to install it now in 5.x
