### ISSUE TITLE
Logstash binary hangs abruptly

### ISSUE THREAD

**Issue by prashantabkari** [elastic/logstash#5311]
Hi - This is pretty basic tests that i am trying with logstash. I have followed the procedure mentioned in page https://www.elastic.co/guide/en/logstash/current/advanced-pipeline.html

I have just run the command with the input file. I have not installed the elasticsearch, hence i have given output as stdout. When i ran this initially, it gave me some valid results, but stopped it with either Ctrl+X/Ctrl-D in subsequent operations. 

I tried later executing the same commands. I have waited for as long as more than 10 minutes but this isn't giving me any results so far. 
I really dont know what the problem is .. 

[abkari@localhost logstash-2.3.2]$ bin/logstash -f first-pipeline.conf 
Settings: Default pipeline workers: 4
Pipeline main started

the configure file is pasted below 
# The # character at the beginning of a line indicates a comment. Use
# comments to describe your configuration.
input {
file {
        path => "/home/abkari/Downloads/logstash-tutorial.log"
        start_position => beginning
        ignore_older => 0
    }
}
# The filter part of this file is commented out to indicate that it is
# optional.
 filter {
    grok {
        match => { "message" => "%{COMBINEDAPACHELOG}"}
    }

 }
output {
stdout {}
}

For all general issues, please provide the following details for fast resolution:

- Version: logstash 2.3.2
- Operating System: Linux (CentOs 7 distro) 
- Config File (if you have sensitive info, please remove it):
- Sample Data: Same as present on the site. 
- Steps to Reproduce: Same as present on the site.

**Comment by jsvd** [comment]
the file input plugin uses a control file (that we call sincedb) to register how far it has read each file, in order to avoid duplicate lines.
This file is created, by default in the home directory of the user running logstash, so you can see it in `ls ~/.sincedb*`
deleting this file and restarting logstash will make it process the input file again from the beginning

**Comment by prashantabkari** [comment]
Ok. thanks for quick clarification. I have few queries

1. If i am writing an application then should i take care of deleting these files? If not how are these files supposed to get deleted? Because there would be scenarios where the application has to start reading it right from start of the file. 
2. Also does it create new .sincedb files for different input files?

**Comment by prashantabkari** [comment]
Kindly let me know if this is already recorded somewhere in the documentation. If not it would be helpful to include this info.

**Comment by jsvd** [comment]
You can find this information in https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html

**Comment by prashantabkari** [comment]
Thanks @jsvd  . But could you also kindly let me know how/when are these files get deleted? Or should this be taken care of by the application?

**Comment by prashantabkari** [comment]
From stackoverflow i got the response that its possible to indicate in logstash conf to reparse the input file. 
http://stackoverflow.com/questions/19546900/how-to-force-logstash-to-reparse-a-file
Not sure if these are recommended settings but deletion of such files becomes very important IMO.
