### ISSUE TITLE
Jenkins test failures - address in use [127.0.0.0:9600]

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#5314]
Consider creating an isolated WebRunner class that holds the starting, stopping and Thread + a rescue/retry mechanism for the actual run on line 50 of webserver.rb

---

1) LogStash::Agent metrics after config reloading resets the metric collector
     Failure/Error: Unable to find matching line from backtrace
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/oraclelinux/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/binder.rb:234:in `add_tcp_listener'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/oraclelinux/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/binder.rb:98:in `parse'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/oraclelinux/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/binder.rb:84:in `parse'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/oraclelinux/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/runner.rb:120:in `load_and_bind'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/oraclelinux/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/single.rb:79:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/oraclelinux/logstash-core/lib/logstash/webserver.rb:50:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/oraclelinux/logstash-core/lib/logstash/agent.rb:130:in `start_webserver'

**Comment by ph** [comment]
This should help too, I just create a PR for the tools I used with beats.

https://github.com/jordansissel/ruby-flores/pull/8

**Comment by purbon** [comment]
I agree for test will be a good idea to randomize the port.

**Comment by purbon** [comment]
also, it might be a case of an unclean shutdown issue, as discovered by @andrewvc in this refactoring efforts in #5307

**Comment by purbon** [comment]
Hi, I checked https://github.com/elastic/logstash/blob/master/logstash-core/spec/api/spec_helper.rb#L47 and the port is actually randomized for this test, I think the fix should be applied to the rest of the test, where they actually start the agent without mocking out the webapi.

**Comment by purbon** [comment]
This will be fixed when #5307 gets merged also when #5326 gets implemented, as of the strategy requested during #5359 if better to wait and do the change after @andrewvc gets merged and implement the logic there.

**Comment by jsvd** [comment]
is this still an issue? all referenced prs and issues have either been merged or closed

**Comment by ph** [comment]
I believe we can close this, since we now accept a range.
