### ISSUE TITLE
Variable in UDP output host property causes crash

### ISSUE THREAD

**Issue by srfoley** [elastic/logstash#5315]

**Comment by untergeek** [comment]
If this is plugin related, please create the issue in the associated plugin, e.g.

* https://github.com/logstash-plugins/logstash-input-udp
* https://github.com/logstash-plugins/logstash-output-udp

Also, please include the steps to reproduce, and your configuration data.

**Comment by srfoley** [comment]
Sorry, accidentally submitted with just the title. Will repost in the relevant plugin area.
