### ISSUE TITLE
Provide a mechanism to detect and report presence of back pressure

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5317]
Although in most scenarios logstash correctly applies back pressure to the inputs, only in the case of beats input that backpressure is signalled in the logs.

For sizing/scalling purposes, it'd be very helpful to get warnings from logstash about backpressure.

**Comment by dandrestor** [comment]
+1. I came here from https://discuss.elastic.co/t/where-do-incoming-events-go-when-logstash-is-cpu-bound/65197/2

**Comment by sevdog** [comment]
Will this feature be implemented sooner or later?

**Comment by yaauie** [comment]
I am closing this issue as superseded by #14463, which defines a multi-release effort to provide better visibility into the _flow_ of events through Logstash, both at a process and a pipeline level, and sets a framework for a future effort to add plugin-level metrics.

In the in-progress release of 8.5, we include #14518 which extends the node stats API to add [flow rates](https://www.elastic.co/guide/en/logstash/master/node-stats-api.html#flow-stats), providing the `current` and `lifetime` flow rates for several process- and pipeline-level metrics — including `queue_backpressure`.

In future releases we plan to _extend_ what we are delivering in 8.5 in several orthogonal ways, such as providing multiple rolling average rates for all flow metrics, adding new flow metrics to cover additional process- and pipeline-level metrics, and improving our ability to track in-flight execution.
