### ISSUE TITLE
Ship a configurable log4j.properties file

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5319]
We hardcode log4j settings in the method `setup_log4j` https://github.com/elastic/logstash/blob/065a82467a1ca43d2ba52e9a0ef0108b6bde0c52/logstash-core/lib/logstash/logging.rb#L47 

No plugins should be calling this because it does not allow log4j settings to be overriden. Kafka input and other plugins use this method. Instead we should ship a default `log4j.properties` to silence any warnings about missing log4j appenders (which is the original reason why this method was used in Kafka, ref:https://github.com/logstash-plugins/logstash-output-kafka/issues/62). This way we can tweak log4j settings as a whole in Logstash rather than doing this individually at plugin level.

For 5.0, I suggest we add a `log4j.properties` in `config` folder and include it in `CLASSPATH`
For 2.x, we need to add it in `LS_HOME` since there is no `config` dir

**Comment by fbaligand** [comment]
@suyograo
This would be great if, using log4j.properties, we could configure log level for each plugin or logstash-core component !

**Comment by suyograo** [comment]
This will be done via #4548
