### ISSUE TITLE
Bind http.port to a range instead of just 9600

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5326]
Can we bind the `http.port` to a range `[9600-9700]` instead of just `9600`. This makes running multiple LS on the same  box easier. Also follows ES user experience. 

Should indirectly fix https://github.com/elastic/logstash/issues/5314

**Comment by ph** [comment]
Oh, well I didnt know that es was actually doing that.

**Comment by purbon** [comment]
@suyograo should we take the range (random pickup)? or keep trying incrementally and take the first one free?

**Comment by andrewvc** [comment]
@purbon we should keep trying incrementally, which is what ES does. This makes it easy to predict what the instances are. In ES its easy to start up two and hit 9200 and 9201

**Comment by purbon** [comment]
@andrewvc agree with you in this.
