### ISSUE TITLE
Java Event `validate_value` needs to implement same algorithm as Ruby Event

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#5347]
Causes this failure in Jenkins:

1) LogStash::Filters::GeoIP an invalid IP filter method outcomes when IP is IPv6 format should set the target field to an empty hash
     Failure/Error: plugin.filter(event)
     RuntimeError:
       expected UTF-8 encoding for value=done, encoding=#Encoding:US-ASCII
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-event-2.2.4-java/lib/logstash/event.rb:223:in `validate_value'

The method is in the JRuby Extension.

http://build-eu-00.elasticsearch.org/view/LS%202.3/job/Logstash_Default_Plugins_23/219/console

**Comment by suyograo** [comment]
@guyboertje please don't forget to link Jenkins builds when filing test failures.

**Comment by talevy** [comment]
Looks like this was an oversight :sigh:

https://github.com/elastic/logstash/blob/master/logstash-core-event-java/src/main/java/com/logstash/ext/JrubyEventExtLibrary.java#L308

```java
        @JRubyMethod(name = "validate_value", required = 1, meta = true)
        public static IRubyObject ruby_validate_value(ThreadContext context, IRubyObject recv, IRubyObject value)
        {
            // TODO: add UTF-8 validation
            return value;
        }
```

**Comment by talevy** [comment]
So. this has nothing to do with java event. This test is failing on plugin-api-v1 because the spec file was ascii encoded by default.

this should fix it: https://github.com/logstash-plugins/logstash-filter-geoip/pull/79

**Comment by talevy** [comment]
The comment above regarding https://github.com/elastic/logstash/blob/master/logstash-core-event-java/src/main/java/com/logstash/ext/JrubyEventExtLibrary.java#L308 deserves its own PR. I will open an issue

**Comment by suyograo** [comment]
Can this be closed?

**Comment by talevy** [comment]
not sure. I'd like to hear @colinsurprenant's opinion on the matter

**Comment by talevy** [comment]
@colinsurprenant, I think this can be closed since we are well ahead of `2.x` and onto 5/6. 

feel free to re-open if you feel this is still relevant
