### ISSUE TITLE
Rename logstash-core-event-java

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#5348]
Jruby auto-appends `-java` to gems that are bundled. this makes it rather confusing to distinguish between `logstash-core-event-java` and `logstash-core-event` gems

**Comment by driverpt** [comment]
`logstash-java-core-event` ?

**Comment by talevy** [comment]
I'll buy that. any other takers?

**Comment by talevy** [comment]
Closing in favor of this refactor: https://github.com/elastic/logstash/issues/6431
