### ISSUE TITLE
[plugin] Logstash Output Zookeeper

### ISSUE THREAD

**Issue by oyld** [elastic/logstash#5356]
I wrote a output plugin and I want to contribyte contribute myc source code to logstash.
Should I make a pull request directly?

**Comment by purbon** [comment]
can you share details from your new plugin here? might be update this issue the details.

**Comment by oyld** [comment]
Yes.
It's a output plugin which send data to zookeeper.
[My github](https://github.com/oyld/logstash-output-zookeeper)

**Comment by suyograo** [comment]
@oyld created https://github.com/logstash-plugins/logstash-output-zookeeper. Can you create a first PR there? We'll review it.

**Comment by oyld** [comment]
I have created a PR, thanks.

**Comment by acchen97** [comment]
Closed with https://github.com/logstash-plugins/logstash-output-zookeeper/pull/1.
