### ISSUE TITLE
Logstash aborts at startup with "Java\java_1.8.0 unexpected at this time."

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5357]
This was a report made by a user during training using windows 10 and jdk8 32bit installed. Switching to 64bit solved the problem. there's no more information other than this.

There's a suspicion that it could be a problem when parsing JAVA_HOME or M2_HOME containing `(x86)`, but it hasn't been verified.

/cc @pmusa

**Comment by pmusa** [comment]
We had two users with the same problem and updating solved to both of them. The interesting thing is that executing java -version in the console works fine and Elasticsearch was also running without any problems. We tried changing the java_home to a few options based on [this](http://stackoverflow.com/questions/15392191/configuring-maven-for-windows-7-files-java-jdk1-6-0-23-was-unexpected-at-this) but there was no difference.

**Comment by Taffa** [comment]
Same issue here. 
Seems setup.bat  is not tolerant for such paths because of the way variables are defined referenced there.

http://stackoverflow.com/questions/15075799/batch-file-variable-with-spaces-and-parentheses
