### ISSUE TITLE
stdin input plugin specs failure

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#5361]
stdin input plugin  specs are failing with the error below. I suspect this will also affect other plugins.

The problem is that the settings setup at https://github.com/elastic/logstash/blob/5e5c0c0844e1c4e833bf6bcc23ac588c2f4a1f63/logstash-core/lib/logstash/environment.rb#L16  uses `Environment::LOGSTASH_HOME` which comes from bootstrap but has not been loaded when required from the plugins rspec context. 

There is a missing `bootstrap/environment.rb` require in the code path. At this point not sure where it should be added. 

To reproduce simply run rspec on stdin input plugin in master.

```
NameError: uninitialized constant LogStash::Environment
    const_missing at org/jruby/RubyModule.java:2743
         LogStash at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/logstash-core-5.0.0.alpha3.snapshot4-java/lib/logstash/environment.rb:8
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/logstash-core-5.0.0.alpha3.snapshot4-java/lib/logstash/environment.rb:6
          require at org/jruby/RubyKernel.java:1040
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/logstash-devutils-1.0.1-java/lib/logstash/devutils/rspec/spec_helper.rb:1
          require at org/jruby/RubyKernel.java:1040
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/logstash-devutils-1.0.1-java/lib/logstash/devutils/rspec/spec_helper.rb:16
             load at org/jruby/RubyKernel.java:1059
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/spec/inputs/stdin_spec.rb:1
             each at org/jruby/RubyArray.java:1613
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/spec/inputs/stdin_spec.rb:2
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1
  load_spec_files at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361
  load_spec_files at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359
            setup at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106
              run at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92
             load at org/jruby/RubyKernel.java:1059
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-stdin/vendor/bin/rspec:23
```

**Comment by ph** [comment]
Got it by it too this morning https://travis-ci.org/logstash-plugins/logstash-input-beats

**Comment by ph** [comment]
Seems related to the release of `5.0.0.alpha3.snapshot4`

**Comment by colinsurprenant** [comment]
because the settings stuff was recently merged I assume...

**Comment by ph** [comment]
Yeah, seems like it.

**Comment by ph** [comment]
@colinsurprenant good analysis, the problem is that `bootstrap/environment` doesn't exist in the concept of the `logstash-core` gem, so we can load it.

So I am wondering if we should do the following, check if the constant is defined and if its not define it with a default value?

**Comment by ph** [comment]
Or use another constant specific to the settings path?

**Comment by colinsurprenant** [comment]
hmm. this is a bit tricky.  I'd say that the problem here is that we are defining something `"path.settings"` which is only relevant for when logstash is actually launched, ie `Runner` is invoked.  

So the *real* problem is that the launching code like `Runner` should ultimately be moved out of `logstash-core` and into a level up in `logstash/lib/...`. and any launching specific settings should be there with it.

But in the meantime, I think we should just move the initialization of the default value for `"path.settings"` into `Runner`. 

WDYT?

**Comment by ph** [comment]
> this is a bit tricky

Agree on this.

> But in the meantime, I think we should just move the initialization of the default value for "path.settings" into Runner.

Agree, I can do a small PR for that.

**Comment by ph** [comment]
@colinsurprenant What would be your opinion to change the name of the `lib/bootstrap/environment` to something else? This could help reducing the confusion or bug.

**Comment by colinsurprenant** [comment]
@ph not sure which confusion of bug you're talking about - I don't see how changing the name would have helped in this situation for example?

**Comment by colinsurprenant** [comment]
the confusion is more about understanding that some environment are only relevant when launching logstash. so in that respect maybe having another module name would make that more obvious yes. So I amend my previous comment :P

**Comment by ph** [comment]
We have two different files that change the same module named `Environment` that don't have the same source code and defined variables.

The logstash application load both files.
The core only has one.

So I think it could make sense if the 2 files were not named the same and they were not defining the same module.

**Comment by ph** [comment]
@colinsurprenant Yup I accept the amend. ;)
