### ISSUE TITLE
Replace obsolete "Logstash startup completed" references in the docs

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/logstash#5372]
Previous versions of Logstash (up to and including 2.2, I think) printed "Logstash startup completed" to the log once it had started up correctly. This is no longer the case—it says "Pipeline main started" instead—but the documentation still refers to the old message which might confuse others (see https://discuss.elastic.co/t/logstash-problem-regarding-inout-plugin-logstash-startup-completed-does-not-get-dislayed/50979/8).

**Comment by dedemorton** [comment]
This is now fixed in the 2.3, master, and 5.0 alpha docs.
