### ISSUE TITLE
Unhandled IRubyObject full class name warning results in plugin restart

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#5382]
Sorry, opened in the wrong repo. See https://github.com/logstash-plugins/logstash-input-twitter/issues/40 instead.

An unhandled IRubyObject full class name warning results in a "Twitter too many requests error, sleeping for s {:level=>:warn}" warning followed by "A plugin had an unrecoverable error. Will restart this plugin." The documents from Twitter are still indexed in Elasticsearch, but it's not so good to see all these warnings in the log. I found this while testing the Logstash getting started doc for 5.0.0-alpha3, so I'm opening the issue in the Logstash repo. This is not a good getting started experience for users. Not sure if this is a plugin or Logstash issue.

- Version: logstash-5.0.0-alpha3.snapshot5
- Operating System: OS X
- Config File (if you have sensitive info, please remove it):
```
input {
    twitter {
        consumer_key => "---"
        consumer_secret => "---"
        keywords => ["Elastic"]
        oauth_token => "---"
        oauth_token_secret => "---"
    }
}
output {
  elasticsearch {
    hosts => "localhost:9200"
  }
}
```
- Steps to Reproduce: Run logstash with the above configuration (using valid keys and such).

console output:

`***** WARN: UNHANDLED IRubyObject full class name=Twitter::Entity::UserMention, simple name=RubyObject java class=class org.jruby.RubyObject toString=#<Twitter::Entity::UserMention:0x217b7978>
Missing Ruby class handling for full class name=org.jruby.RubyBasicObject, simple name=RubyBasicObject {:exception=>java.lang.IllegalArgumentException: Missing Ruby class handling for full class name=org.jruby.RubyBasicObject, simple name=RubyBasicObject, :backtrace=>["com.logstash.Javafier.deep(Javafier.java:111)", "com.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_set_field(JrubyEventExtLibrary.java:159)", "com.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.gen)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)", "org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)", "org.jruby.ast.IfNode.interpret(IfNode.java:116)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.IfNode.interpret(IfNode.java:118)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)", "org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.IfNode.interpret(IfNode.java:116)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)", "org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)", "org.jruby.runtime.Interpreted19Block.yieldSpecific(Interpreted19Block.java:135)", "org.jruby.runtime.Block.yieldSpecific(Block.java:120)", "org.jruby.ast.YieldOneNode.interpret(YieldOneNode.java:35)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.IfNode.interpret(IfNode.java:116)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)", "org.jruby.runtime.Block.call(Block.java:101)", "org.jruby.RubyProc.call(RubyProc.java:300)", "org.jruby.RubyProc.call19(RubyProc.java:281)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Twitter::Streaming::Response$$on_body_2b6528f4b67cc09eb8e71606efa18e7a5da2eefd1028566121.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/Users/dedemorton/BuildTesting/5.0.0-alpha3/logstash-5.0.0-alpha3.snapshot5/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.1/lib/logstash/inputs/twitter/patches.rb:69)", "rubyjit.Twitter::Streaming::Response$$on_body_2b6528f4b67cc09eb8e71606efa18e7a5da2eefd1028566121.block_0$RUBY$__file__(/Users/dedemorton/BuildTesting/5.0.0-alpha3/logstash-5.0.0-alpha3.snapshot5/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.1/lib/logstash/inputs/twitter/patches.rb:68)", "rubyjit$Twitter::Streaming::Response$$on_body_2b6528f4b67cc09eb8e71606efa18e7a5da2eefd1028566121$block_0$RUBY$__file__.call(rubyjit$Twitter::Streaming::Response$$on_body_2b6528f4b67cc09eb8e71606efa18e7a5da2eefd1028566121$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)", "org.jruby.runtime.Block.yield(Block.java:142)", "org.jruby.RubyArray.eachCommon(RubyArray.java:1606)", "org.jruby.RubyArray.each(RubyArray.java:1613)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "rubyjit.Twitter::Streaming::Response$$on_body_2b6528f4b67cc09eb8e71606efa18e7a5da2eefd1028566121.__file__(/Users/dedemorton/BuildTesting/5.0.0-alpha3/logstash-5.0.0-alpha3.snapshot5/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.1/lib/logstash/inputs/twitter/patches.rb:66)", "rubyjit.Twitter::Streaming::Response$$on_body_2b6528f4b67cc09eb8e71606efa18e7a5da2eefd1028566121.__file__(/Users/dedemorton/BuildTesting/5.0.0-alpha3/logstash-5.0.0-alpha3.snapshot5/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.1/lib/logstash/inputs/twitter/patches.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.RubyClass.finvoke(RubyClass.java:743)", "org.jruby.runtime.Helpers.invoke(Helpers.java:505)", "org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:364)", "org.ruby_http_parser.RubyHttpParser$8.cb(RubyHttpParser.java:291)", "http_parser.lolevel.ParserSettings.call_on(ParserSettings.java:80)", "http_parser.lolevel.ParserSettings.call_on_body(ParserSettings.java:67)", "http_parser.lolevel.HTTPParser.execute(HTTPParser.java:1440)", "org.ruby_http_parser.RubyHttpParser.execute(RubyHttpParser.java:370)", "org.ruby_http_parser.RubyHttpParser$INVOKER$i$1$0$execute.call(RubyHttpParser$INVOKER$i$1$0$execute.gen)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.runtime.callsite.ShiftLeftCallSite.call(ShiftLeftCallSite.java:24)", "rubyjit.Twitter::Streaming::Response$$\\=\\^\\^_dcb240c9bd1c2290176c84bd93e26d83150f325a1028566121.__file__(/Users/dedemorton/BuildTesting/5.0.0-alpha3/logstash-5.0.0-alpha3.snapshot5/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:16)", "rubyjit.Twitter::Streaming::Response$$\\=\\^\\^_dcb240c9bd1c2290176c84bd93e26d83150f325a1028566121.__file__(/Users/dedemorton/BuildTesting/5.0.0-alpha3/logstash-5.0.0-alpha3.snapshot5/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.runtime.callsite.ShiftLeftCallSite.call(ShiftLeftCallSite.java:24)", "org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.WhileNode.interpret(WhileNode.java:131)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)", "org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:290)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:243)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:376)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:247)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:251)", "org.jruby.ast.FCallThreeArgBlockPassNode.interpret(FCallThreeArgBlockPassNode.java:36)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)", "org.jruby.ast.CallOneArgBlockNode.interpret(CallOneArgBlockNode.java:60)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.IfNode.interpret(IfNode.java:118)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)", "org.jruby.ast.RescueNode.interpret(RescueNode.java:116)", "org.jruby.ast.BeginNode.interpret(BeginNode.java:83)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)", "org.jruby.ast.RescueNode.interpret(RescueNode.java:116)", "org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)", "org.jruby.ast.BeginNode.interpret(BeginNode.java:83)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)", "org.jruby.runtime.Block.call(Block.java:101)", "org.jruby.RubyProc.call(RubyProc.java:300)", "org.jruby.RubyProc.call(RubyProc.java:230)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)", "java.lang.Thread.run(Thread.java:745)"], :options=>nil, :level=>:warn}`

**Comment by vrsomu59** [comment]
Hi,

how to solve this ' chained_0_rescue_1$RUBY$SYNTHETIC__file__ ' , i am also facing similar issue when i see the logs. we are using jruby and deploying on weblogic server.
