### ISSUE TITLE
Removing a package in ubuntu (debian package) left residues in /usr/share/logstash

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5390]
If removing a package in an ubuntu machine (using the debian package) it left non deleted the directory ```/usr/share/logstash/vendor```. This will cause all gems/plugins to be still there and might incur on some state corruption as some of the files into this directory are gemspecs.

For more details:

* install latest package from master.
* remove the package with `dpkg -r`
* purge the package with `dpkg --purge`

you will still see files into the directory named at the beginning of this issue.

**Comment by suyograo** [comment]
This is normal behavior. if a directory is not empty, it will not fully remove it.

**Comment by purbon** [comment]
can not reproduce now the issue I saw with the acceptance test branch, so closing this for now. I will reopen with more data if I have it again.

**Comment by untergeek** [comment]
@purbon we _can_ remove the `vendor` directory with the `before-remove` scripts, but tend to not do this, as @suyograo pointed out, it's the default behavior.  

What if a user added their own, custom plugin, and they were counting on the packaging system to _not_ delete the directory?

**Comment by purbon** [comment]
this is a good test to make, but I guess it should be only in case you do
an upgrade, right? lets open a follow up issue. for this.
