### ISSUE TITLE
Enable to provide custom validation function for config values

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5395]
In https://discuss.elastic.co/t/custom-logstash-filter-validation-question/51338 there is a nice discussion on providing custom validation function for config values in plugins, this would enable users do a bit more complex validations when necessary.

In terms of implementation this would require some extensions to the current validation mechanism inside https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/mixin.rb#L394

**Comment by suyograo** [comment]
Makes sense! Covered in https://github.com/elastic/logstash/issues/3773
