### ISSUE TITLE
Add path.data to settings.yml

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#5404]
Elasticsearch uses `path.data` in its yaml file to indicate where the data directory should go.

Likewise, with Logstash plugins that need to keep state somewhere, we should use a `path.data` option, with the rpm/deb package default being `/var/lib/logstash`, and otherwise `$LS_HOME/data`.

Plugins should be able to piggy-back on this variable easily to allow them to keep state, perhaps in `/path.data/plugin-name/plugin-uuid` as the path, or something like that.  This completely eliminates painful ENV vars like `SINCEDB_DIR`, which is a highly desirable thing.

**Comment by suyograo** [comment]
+1. This `path.data` will also be used to store `logstash.uuid` a persistent UUID which is stable across restarts.

**Comment by jsvd** [comment]
+1, we have discussed adding this before, but there was no purpose yet in logstash for a path.data
