### ISSUE TITLE
[ANN] Dissect Filter, a sort of alternate grok engine

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#5406]
In recent weeks, many people (on LS discuss and via customer support) have reported stalling installations of LS. A good number of these have been from certain data patterns triggering a slow regex performance in a worker, a sequence of these data patterns sufficiently spaced apart can make all filter threads slow and unresponsive and if one has many events holding bad patterns in one batch then the worker thread may take minutes to hours to process the batch.

I got to thinking about a way not use regex patterns to describe the line structure - and I came up with a series of fields and delimiters - a bit like `split` but instead of having just one delimiter, there is a sequence of delimiters that get applied to the input string from left to right...
e.g `field1, delim1, field1, delim2, ... , fieldN`.

After discussion with @purbon, I decided on this description of the structure.

```
source line: "Mar 16 00:01:25 evita postfix/smtpd[1713]: connect from camomile.cloud9.net[168.100.1.3]"
mapping: %{timestamp} %{timestamp!} %{timestamp!} %{logsource} %{program}[%{pid}]: %{msg}
```

Notes:
- to collect up the timestamp across spaces one uses `%{timestamp} %{timestamp!} %{timestamp!}`, the two `%{timestamp!}` appends the text to the first timestamp field using the delimiter proceeding it,  this works too: `%{timestamp}:%{timestamp!}:%{timestamp!} %{...`.
- an empty field is a skip field e.g. `%{}`
- the last field will always capture all the remaining text.
- the filter config allows for repeated dissection i.e. break up `message` then break up `field X` in one filter invocation.

After discussion with @ph I decided to implement this in Java with a JRuby extension.

For lines that are semi-structured I imagine that user can use a combination of dissect then grok where the goal is to have a much simpler grok for part of the original line.

The Java implementation uses brute force string search for delimiter sizes of 1 and 2. For longer delimiters I read up on [string searching](https://en.wikipedia.org/wiki/String_searching_algorithm) and tested the Knuth–Morris–Pratt, Boyer-Moore-Horspool and Raita. I settled on using Boyer-Moore-Horspool from this [StringSearch java library](https://github.com/johannburkard/StringSearch). I welcome any other suggestions.

JMH benchmarks:
For this input.

``` text
"42 2016-05-25T14:47:23Z host.name.com RT_FLOW - RT_FLOW_SESSION_DENY: session denied 2.2.2.20/60000->1.1.1.10/8090 None 6(0) DEFAULT-DENY ZONE-UNTRUST ZONE-DMZ UNKNOWN UNKNOWN N/A(N/A) ge-0/0/0.0"
"%{} %{syslog_timestamp} %{hostname} %{rt}: %{reason} %{reason!} %{src_ip}/%{src_port}->%{dst_ip}/%{dst_port} %{polrt} %{polrt!} %{polrt!} %{from_zone} %{to_zone} %{rest}"

Result "aDissector":
  1.554 ±(99.9%) 0.173 us/op [Average]
  (min, avg, max) = (1.531, 1.554, 1.584), stdev = 0.027
  CI (99.9%): [1.381, 1.726] (assumes normal distribution)

Benchmark                    Mode  Cnt  Score   Error  Units
DissectBenchmark.aDissector  avgt    4  1.554 ± 0.173  us/op
```

i.e. ~ 650000 dissections per second.

Obviously this filter relies on having very regular message structures and a user will need to use an if block to ensure that it dissects the appropriate events.

Initially it needs Java Event - but it can be back-ported to use Ruby Event.

Thanks to @PhaedrusTheGreek for the name `dissect`

I will be submitting a PR soon for the initial version.

**Comment by guyboertje** [comment]
P.S. the Pull request is [here](https://github.com/logstash-plugins/logstash-filter-dissect/pull/1)

**Comment by jsvd** [comment]
this can be closed, I believe?
