### ISSUE TITLE
Change runner.rb to not need path.settings for --version output

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#5407]
As seen in #5399.  We shouldn't need to load settings if all we're doing is spitting out a version.

**Comment by suyograo** [comment]
Same for `--help`

**Comment by untergeek** [comment]
If this is not possible, e.g. due to `jvm.options` being needed to start up, then perhaps we should have an automatic test in place to check for `/etc/logstash` first, then fall back to `LS_HOME/config` if that's not found.

**Comment by purbon** [comment]
I agree, having version and help not possible to be run without passing the settings seems a bit too much for me

**Comment by jsvd** [comment]
this has been implemented only for *nix systems in https://github.com/elastic/logstash/pull/5490

**Comment by jsvd** [comment]
reopening another issue to implement the same on windows
