### ISSUE TITLE
Try path.settings in multiple locations?

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#5413]
5.0 Alpha 3.

If LS is installed via a package (eg. RPM) and the user attempts to start it up manually by calling the logstash binary, it currently defaults to /usr/share/logstash/config as the default config dir and because such directory doesn't exist because it is not installed by the RPM.  

While we do have a warning that talks about explicitly setting the --path.settings to the logstash settings file, it will be a better user experience if we will try multiple locations before failing, eg. try /usr/share/logstash/config first, if the settings file is not there, then fallback to /etc/logstash, and if both location fails, then throw the warning/error.

**Comment by untergeek** [comment]
This was the behavior until we realized that Elasticsearch has the same shortcoming. We opted to mirror the behavior.

**Comment by suyograo** [comment]
Also `/usr/share/logstash/config` is not where the config is when you install using the release packages..

**Comment by suyograo** [comment]
Related https://github.com/elastic/logstash/issues/5389

**Comment by suyograo** [comment]
@ppf2 does this answer your question?

**Comment by ppf2** [comment]
Yes, though I think the user experience can still be improved esp. since /usr/share/logstash/config will not be there for folks installing it to run via a package so this error will always show up for them.  But if the goal is to keep the behavior in sync across products as the priority (even though it has shortcomings), then we can close this :)

**Comment by untergeek** [comment]
@ppf2 the same thing happens if you try to launch Elasticsearch, too.  It says that there's no config file in /usr/share/elasticsearch/config.  We'll just document it well, so users will know where to find it.

Perhaps we can put better error messaging when /usr/share/logstash/config is not found, and suggest that if it was installed via package, that `--path.settings` should point to `/etc/logstash`

**Comment by ppf2** [comment]
+1 I haven't checked all the package installations, if they all default to /etc/logstash, let's update part of the error message to say:

```
If you installed Logstash through a package and are starting it manually, add the additional setting "--path.settings=/etc/logstash" to the command line options.
```

thx!

**Comment by untergeek** [comment]
This was already fixed by @jsvd in https://github.com/elastic/logstash/commit/595658f51263d67cbe1d22d9274e752a1398397a

This is the new message:

```
  @logger.warn("Logstash has a new settings file which defines start up time settings. This file is typically located in $LS_HOME/config or /etc/logstash. If you installed Logstash through a package and are starting it manually please specify the location to this settings file by passing in \"--path.settings=/path/..\" in the command line options")
  @logger.fatal("Failed to load settings file from \"path.settings\". Aborting...", "path.settings" => LogStash::SETTINGS.get("path.settings"), "exception" => e.class, "message" => e.message)
```

**Comment by robertchen** [comment]
This has not resovled, I got the issue on amazon ec2 instance,  no matter I install from yum or unzip from tar.gz file.

# /usr/share/logstash/bin/logstash --verbose --debug --path.settings=/etc/logstash

INFO: Logstash requires a setting file which is typically located in $LS_HOME/config or /etc/logstash. If you installed Logstash through a package and are starting it manually please specify the location to this settings file by passing in "--path.settings=/path/.."
ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/etc/logstash, exception=ArgumentError, message=>Setting "" hasn't been registered

**Comment by untergeek** [comment]
@robertchen Do you have a `logstash.yml` file in `/etc/logstash`? The absence of this file will generate that error.
