### ISSUE TITLE
Building release packages by not changing files

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5416]
We need to change the way we build snapshot packages and release packages. Basically, we should be able to promote a release candidate (RC) package to a final release package without changing any files. We can achieve this by:

* Having one source of truth + script to set version #5414 
* Build snapshot packages by default when we run a build. There is no need to specify snapshots in the version info. For example, we would never have `5.0.0-alpha4.snapshot1` in `version.yml`. It would only be `5.0.0-alpha4`.  This is kinda already done in master..
* `rake artifact:tar` should always build a snapshot. by passing `--release` flag, it should promote the sha to be a release instead of the usual snapshot. No changes should be made to any files.

The one gotcha is publishing logstash-core gems to RubyGems.org so plugins can use it for testing.. RubyGems.org has a constraint on unique versions for publish (i.e. we can't replace existing Gem with same versions). This means we can't actually replace existing snapshots when code changes are made and _still_ reference the same version in the gemspec.

**Comment by suyograo** [comment]
@jsvd @jordansissel and I had a zoom conversation yesterday. Rough notes:

### Enabling Multiple Snapshots
Gemfiles in release branches will not use published `logstash-core*` gems from RubyGem. It will be built locally and referenced, like we do in master branch now:

```
gem "logstash-core", "5.0.0-alpha4", :path => "./logstash-core"
gem "logstash-core-event-java", "5.0.0-alpha4", :path => "./logstash-core-event-java"
gem "logstash-core-plugin-api", "2.20.0", :path => "./logstash-core-plugin-api"
```

The version here will come from `pkg/version.yml` which is described in #5414. This way, we can publish as many snapshots as possible (without having to increment snapshot versions) for a particular version. Once we are ready to promote a snapshot to an actual release, we only have to use the `--release` switch and no files (version.yml, gemspecs) will be touched when creating the final package.

### Plugin Tests
Plugins tests will be affected by this. Today, plugins use the latest released `logstash-core*` in their tests. Our suggestion here was to test plugins against Logstash repo directly, eliminating the need for published snapshots. For example, travis.yml can be changed to be test using a matrix: 
     a) Test against head of master
     b) Test against head of latest release branch (for example 5.0). 

For b) travis.yml has to be changed to use:
```
before_install:
- git clone -b v5.0 https://github.com/elastic/logstash
```

and in gemspec:

```
source 'https://rubygems.org'
gemspec
gem "logstash-core", :path => "./logstash/logstash-core"
gem "logstash-core-plugin-api", :path => "./logstash/logstash-core-plugin-api"
gem "logstash-core-event-java", :path => "./logstash/logstash-core-event-java"
```

Alternatively, we can directly use `:git` and point to remote branches.

----------------------------------------------
With this strategy, `logstash-core-plugin-api` can be published outside of the release cycle, i.e. whenever we make plugin API based changes. Or, once we finally promote the candidate to an actual release, that process can publish `logstash-core*` gems for public consumption (also for packaging with plugins).

This travis flow described here needs to be validated for us to move forward.

Thoughts?

**Comment by jsvd** [comment]
this has been implemented by https://github.com/elastic/logstash/issues/5460
