### ISSUE TITLE
Invalid Semantic Versioning in Rubygems.org

### ISSUE THREAD

**Issue by driverpt** [elastic/logstash#5417]
When i'm doing `bundle install` i notice that Snapshots have invalid versioning and i noticed that versioning is being made with a dot instead of a hyfen.

Output
```
Installing kramdown 1.11.1 (was 1.10.0)
Installing logstash-core-event 2.3.3.snapshot1 (was 2.3.1)
```

The correct versioning should be **2.3.3-snapshot1**

[Source](http://semver.org/#spec-item-9)
[Rubygems](https://rubygems.org/gems/logstash-core-event)

This may affect existing developed plugins against version 2.3.x

**Comment by suyograo** [comment]
The problem is RubyGems does not allow dashes. We do follow semver so our package names are `x.y.z-pre`, but for RubyGems we need to re-process it as `x.y.z.pre`. Thats why you see `x.y.z.pre` in gemspecs. 

Why should this affect plugins against version 2.3.x? Is there an error?

**Comment by driverpt** [comment]
Closing. Gem needs to be Yanked. I based my plugin on logstash-codec-json and since it does not have `s.add_runtime_dependency "logstash-core", "~> 2.3.0"` it fetched the latest version.
