### ISSUE TITLE
Duration => nil

### ISSUE THREAD

**Issue by linhntt41** [elastic/logstash#5426]
Hi!
I want to calculate delta 2 events, use ruby to calculate delta time
This my config:
if [status] == "out"{
  elasticsearch {
    hosts => ["localhost"]
    query => 'status:in AND username:"%{username}"'
    fields => ["@timestamp","start"]
      }
_ruby{
     init => "require 'time'"
     code => "event['duration_hrs'] = (event['@timestamp'] - event['start']) / 3600 rescue nil"_
     add_tag => ["duration_hrs"]
}
But result duration => nil
===>  "@version" => "1",
      "@timestamp" => "2016-06-01T16:06:46.816Z",
            "path" => "/opt/file1.log",
            "host" => "archlinux",
           "start" => "2016-06-01T16:06:23.769Z",
        "username" => "linh",
          "status" => "out",
    **"duration_hrs" => nil,**
            "tags" => [
        [0] "duration_hrs"

if I use Time.parse().to_s or .to_f but ruby exception

ruby{
     _init => "require 'time'"
     code => "event['duration_hrs'] =Time.parse (event['@timestamp']).to_s - Time.parse(event['start']).to_s"
     add_tag => ["duration_hrs"]
}_

==> 
**Ruby exception occurred: undefined method `gsub!' for "2016-06-01T16:04:42.483Z":LogStash::Timestamp {:level=>:error}**
"@version" => "1",
    "@timestamp" => "2016-06-01T16:04:42.483Z",
          "path" => "/opt/file1.log",
          "host" => "archlinux",
         "start" => "2016-06-01T16:04:19.417Z",
      "username" => "linh",
        "status" => "out",
          "tags" => [
        [0] "_rubyexception"
    ]
I don't understands why wrong, can you help me?
Thanks

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
