### ISSUE TITLE
Initial Plugin Metrics

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#5428]
These plugins need the following metrics. Moved from https://github.com/elastic/logstash/issues/4923

### Plugins
- Exposing basic plugin instance specific stats
- **Phase 1** - focus initially on 3 most popular plugins, one of each type
- API Endpoint for plugin specific stats: `/_node/stats/pipeline/plugins`

### 5.0 Scope

**Beats Input**
- [x] `in` - events in
- [x] `duration_in_millis` - total time spent in plugin
- [x] `out` - events out
- [ ] `connections` - current count of Beats connected
- [ ] `peak_connections` - peak count of Beats connected
- [ ] `beat_types` - array list of types of Beats currently connected, i.e. Filebeat, Metricbeat, etc.

**Grok Filter**
- [x] `in` - events in
- [x] `duration_in_millis` - total time spent in plugin
- [x] `out` - events out
- [x] `matches` - number of matches
- [x] `failures` - number of failures

**Elasticsearch Output**
- [x] `in` - events in
- [x] `duration_in_millis` - total time spent in plugin
- [x] `out` - events out
- [ ] `bulk_requests` - number of bulk requests sent
- [ ] `request_latency_in_millis` - total time spent for completing bulk requests to ES
- [ ] `retry_count` - number of retries
- [ ] `sniffing_count` - number of times sniffing was triggered
- [ ] HTTP response code count, buckets i.e. 2xx, 3xx, 4xx, 5xx

**Comment by acchen97** [comment]
Updated initial issue with new 5.0 scope, adding a few additional plugin specific metrics in Beats in, grok, and ES out. /cc @suyograo @jordansissel 

@ph anything else we should add for Beats input? Host/port exposed feels more like "info" instead of "stat". We could add Beat type specific metrics, i.e. # of Filebeats connected, or Filebeat events in/out, but I think this can be a phase 2.

@andrewvc anything big missing here for ES output? Flush count? Events dropped/failed count? # of ES hosts connected to? Overall, I'd lean towards keeping the scope small for now.

**Comment by suyograo** [comment]
> average bulk request latency between LS and ES

We should defer this average calculation to Elasticsearch, IMO. This is to be consistent with other stats we have so far. Even `duration_in_millis` i.e. time spent in filters is a running total.

**Comment by acchen97** [comment]
Agreed and updated.

**Comment by suyograo** [comment]
Wait,we still need the latency or time spent between LS and ES for a bulk request. It just has to be a running total. We should also add # of bulk requests. So on ES side we can calculate the average latency  per bulk request.

**Comment by acchen97** [comment]
@suyograo makes sense, added `request_latency_in_millis` which is a longer, but hopefully clear description. Feel free to add the geoip, date, useragent stuff you mentioned earlier if you'd like.

**Comment by suyograo** [comment]
Closing this.
