### ISSUE TITLE
logstash5 init.d script

### ISSUE THREAD

**Issue by zozo6015** [elastic/logstash#5429]
Hello, 

I have just installed the complete version 5 setup on a docker container running debian jessie. 
When I run the system-install script to generate the init script which it generates the systemd scripts but not the one in the /etc/init.d and docker cannot start the service running on the systemd (or at least I did not find a way yet).

Is there any way I could generate the script in the /etc/init.d ?

Regards,

**Comment by untergeek** [comment]
That seems strange.  Why doesn't `systemctl start logstash` work on a systemd container?  What's the parent container's setup?

**Comment by zozo6015** [comment]
Whenever I start anything inside a docker container with systemctl I am getting the following error:

"Failed to get D-Bus connection: Unknown error -1"

This is not for logstash or any elastic based product, but really anything

**Comment by untergeek** [comment]
As I responded in the Discuss forums:

From what I can tell, this is more of a Docker issue, and it can be worked around:

https://github.com/systemd/systemd/issues/1224#issuecomment-139124387

> Do not drop CAP_SYS_ADMIN from the container. A number of fs namespacing related settings, such as PrivateDevices=, ProtectHome=, ProtectSystem=, MountFlags=, PrivateTmp=, ReadWriteDirectories=, ReadOnlyDirectories=, InaccessibleDirectories=, MountFlags= need to be able to open new mount namespaces and the mount certain file system into it. You break all services that make use of these flags if you drop the flag. Note that already quite a number of services make use of this as we actively encourage users to make use of this security functionality. Also note that logind mounts XDG_RUNTIME_DIR as tmpfs for all logged in users and won't work either if you take away the capability. (Also see section about fully unprivileged containers below.)

Re-adding `CAP_SYS_ADMIN` seems to fix the issue.  We _may_ try to allow users to force init styles, but this is not pressing if there's a way to fix the larger issue by fixing the container instead.

**Comment by zozo6015** [comment]
Yes, it is a docker issue that's why I was asking if it's possible to generate a systemv init script, since that would work.

**Comment by untergeek** [comment]
We do not believe it is appropriate to force SYSV.  We made the install script auto-detect the underlying startup mechanism, and create scripts accordingly.  We will not be fixing this.

**Comment by untergeek** [comment]
[As a confirmation](https://discuss.elastic.co/t/logstash-5-alpha3-not-starting/51641/5):

> Got it fixed. adding --cap-add SYS_ADMIN with the /sbin/init command will make systemctl command work as expected. Thanks for your help
