### ISSUE TITLE
Logstash hangs / unresponsive

### ISSUE THREAD

**Issue by michbsd** [elastic/logstash#5437]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: 2.3.2
- Operating System: FreeBSD 10.3-REL
- Config File:

```
input {

	redis {
		port => 6379
		host => "172.16.0.140"
		password => "xxxxx"
		type => filebeat
		key => "filebeat"
		codec => json
		data_type => "list"
		threads => 10
	}
}

filter {
	if [type] == "jaf_prod_varnish" {
		grok {
			match => { "message" => "(?:%{IP:ip1}|%{IP:ip1}, %{IP:ip2}|-) - \[%{HTTPDATE:timestamp}\] %{WORD:method} '%{URIHOST:host}' '%{PATH:path}' '(?:%{URIPARAM:param}|)' %{NUMBER:http_status} (?:%{NUMBER:bytes}|-) %{BASE10NUM:berespms} %{WORD:cache_handling}" }
			named_captures_only => true
		}
	}
	metrics {
    		meter => "events"
    		add_tag => "metric"
    		flush_interval => 10
  	}
}

output {
	if "metric" in [tags] {
		file {
			path => "/var/log/logstash-event-rate.log"
      			codec => line {
        			format => "%{[@timestamp]} --> 1m rate: %{[events][rate_1m]} - 5m rate: %{[events][rate_5m]} - 15m rate: %{[events][rate_15m]}"
      			}
    		}
  	}
	elasticsearch { hosts => [ "172.16.0.140:9200" ] }
	stdout { codec => rubydebug }

}
```

I fire up logstash - and everything is fine.
As soon as I start filebeat on the varnish machine (jaf_prod_varnish) - the CPU usage spikes to 800-1000% and avg load also increases drastically. 

But nothing is parsed / treated by logstash, and I cannot HUP the process. I have to do a kill -9 to terminate the process.

Here is the jstack output:
https://gist.github.com/michbsd/3af950b5234dc9e81f29db0868871e71

And here is more detailed info from the forum:
https://discuss.elastic.co/t/logstash-high-cpu-and-unresponsive/51254

Any pointers would be greatly appreciated.

thanks,

**Comment by michbsd** [comment]
Any other traces needed?

**Comment by michbsd** [comment]
Attaching truss to the pid, I see a lot of these (while logstash being unresponsive):

_umtx_op(0x80065ba88,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffd8f8d728) ERR#60 'Operation timed out'
kevent(331,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(143,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(268,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
_umtx_op(0x80065b3b0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdd8d6768) ERR#60 'Operation timed out'
kevent(161,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(292,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(113,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(316,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(95,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(259,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(319,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(227,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(212,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(295,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
lstat("/var",{ mode=drwxr-xr-x ,inode=4,size=24,blksize=4096 }) = 0 (0x0)
read(685,"7400000 0xb08000000 3052 0 0xfff"...,4096) = 4096 (0x1000)
kevent(179,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(236,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(203,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
_umtx_op(0x80065b398,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdd9d7848) ERR#60 'Operation timed out'
kevent(242,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(146,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(215,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(176,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(155,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(59,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(131,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(101,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(98,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(224,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(65,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(74,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(137,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(152,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(200,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(107,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(134,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(86,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(173,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(104,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(158,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(334,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(188,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
lstat("/var/db",{ mode=drwxr-xr-x ,inode=27,size=22,blksize=4096 }) = 0 (0x0)
kevent(233,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
kevent(248,0x0,0,{ },128,{ 0.500000000 })	 = 0 (0x0)
_umtx_op(0x80065ba88,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffd8f8d728) ERR#60 'Operation timed out'
_umtx_op(0x80065b1b8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdedebd18) ERR#60 'Operation timed out'

**Comment by michbsd** [comment]
Hi, 

I've updated the thread on the forum, with some more information:
https://discuss.elastic.co/t/logstash-high-cpu-and-unresponsive/51254/4

Any pointers on how to fix this would be much appreciated. 

thanks,

**Comment by purbon** [comment]
@michbsd usually we try to keep this forum for more project issues as you reported this here and also in the forums this end up like being a bit duplicated. I propose we close this one and keep the conversation at discuss. If during the debugging we asses something more clear to be an issue here I'm more than happy to reopen this, makes sense for you?

**Comment by michbsd** [comment]
Yes, perfect. Thanks
