### ISSUE TITLE
Add set and get API to Ruby Event implementation

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5449]
Java Event APIs (setters/getters) were introduced in 5.0 (as core-plugin-api 2.0). All plugins were updated to use these calls instead of directly using Ruby's hash syntax. While this works well for 5.0, it would be great if we can introduce the setter and getter API in 2.4 as well, for the Ruby Event implementation. Basically `set` and `get` in LS 2.4 would alias to existing `[]` and `[]=` respectively. 

This change would allow plugins developed with 2.0 API to be backward compatible. On top of it, development process becomes easier as well; we don't have to backport every change to v1 _and_ v2 branches, _and_ publish from both!

**Comment by suyograo** [comment]
Once this is in, plugin gemspecs needs to change plugin-api constrains from:

`s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.x", "< 3.0"`

where 1.x is the version of `plugin-api` gem which has `get` and `set`

**Comment by guyboertje** [comment]
PR https://github.com/elastic/logstash/pull/5457

**Comment by guyboertje** [comment]
Closed by #5457
