### ISSUE TITLE
Include hostname in all `_node` API outputs

### ISSUE THREAD

**Issue by jakommo** [elastic/logstash#5450]
Currently the output is not consistent, e.g. the `_node/hot_threads` includes the hostname in the output, while `_node/stats` doesn't.

Example:

```
curl http://localhost:9601/_node/hot_threads?pretty
{
  "hostname" : "LS5-Test",
...
```
```
curl http://localhost:9601/_node/stats?pretty
{
  "events" : {
...
```

It could be useful to have the have the hostname in the output, e.g. for monitoring that calls several instances etc.

**Comment by andrewvc** [comment]
@jakommo good catch! Should we really be using node.name instead however?

**Comment by jakommo** [comment]
@andrewvc, ah nice, didn't know there was a `node.name` available. 
In my opinion including both `hostname` and `node.name` would even be more unique to identify an instance.
I also think it is important to have this identical across all API responses.

**Comment by acchen97** [comment]
@jakommo thanks for filing, I agree we should be more consistent here.  Node name and uuid should be present across the different endpoints (node info, node stats, plugins).  I'll define an issue for more clarity tonight.

**Comment by acchen97** [comment]
Hey @jakommo new issue up https://github.com/elastic/logstash/issues/5475.  Any further comments are welcome. :)

**Comment by suyograo** [comment]
After discussing with @andrewvc and @acchen97 we decided to display just the hostname in APIs for now. `node.name` and `node.id` is still in flux.
