### ISSUE TITLE
%UNIXPATH can cause RegEx DOS

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/logstash#5458]
Repro is very simple.   This will peg your CPU:

```
input {
        stdin {
                add_field => { "test" => "/web/asdf/my_input_file_000223.xml name"  }
        }
}


filter {
        grok {
                match => {
                        "test" => [
                                "%{UNIXPATH}/asdf/my_%{DATA}_file_%{DATA:fileName} name"
                        ]
                }
        }
}

output {
        stdout {
          codec  => rubydebug {
            metadata => true
          }
        }
}
```

The more `/asdf/asdf` you add, the longer it takes.

It works without delay on this [online grok debugger](http://grokdebug.herokuapp.com/) app:

![grokdebug](https://cloud.githubusercontent.com/assets/4387023/15861888/c8a1dc04-2c9b-11e6-83e7-9630d8a33bd1.png)

Investigating, it was found that the UNIXPATH is different between tools:

Online App: `UNIXPATH (?>/(?>[\w_%!$@:.,-]+|\\.)*)+` (Works Better)
Logstash: `UNIXPATH (/([\w_%!$@:.,~-]+|\\.)*)+` (Can Blow Up)

**Comment by jsvd** [comment]
moved to https://github.com/logstash-plugins/logstash-patterns-core/issues/159
