### ISSUE TITLE
sincedb documentation incorrect

### ISSUE THREAD

**Issue by robin13** [elastic/logstash#5466]
Looks like the [default path](https://github.com/elastic/logstash/commit/4baf29dc5f76a05c3c1486d56bc7a973b0825f1f) is now $LOGSTASH_HOME and not $HOME for sincedb_path

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-sincedb_path

**Comment by suyograo** [comment]
Fixed in 5.0
