### ISSUE TITLE
Acceptance tests plugins update scenario broken.

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5468]
The update test in the acceptance layer does not work as expected causing many issues as you can see in https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=debian/15/console 

The source of this error is the code used to remove the version constran in the gemfile for the test gem used in tests, this is required because in logstash if you previously installed an specific version of a plugin you can not use the update command, you should remove it and do the install.

```
  before do
      logstash.run_command_in_path("bin/logstash-plugin install --version #{previous_version} #{plugin_name}")
      # Logstash wont update when we have a pinned versionin the gemfile so we remove them
      logstash.replace_in_gemfile(',\s"0.1.0"', "")
      expect(logstash).to have_installed?(plugin_name, previous_version)
    end
```

we need to improve the interaction specified in line `logstash.replace_in_gemfile(',\s"0.1.0"', "")`, as the cause of having this failing test.

**Comment by purbon** [comment]
After further investigation there might be also some issues for this scenario, currently for debian-8 target OS, we see if run manually:

```
vagrant@packer-virtualbox-iso-1452100235:~$ cat /usr/share/logstash/Gemfile
# This is a Logstash generated Gemfile.
# If you modify this file manually all comments and formatting will be lost.

source "https://rubygems.org"
gem "logstash-core", "5.0.0.dev", :path => "vendor/local_gems/aa5213f2/logstash-core-5.0.0.dev-java"
gem "logstash-core-event-java", "5.0.0.dev", :path => "vendor/local_gems/21764749/logstash-core-event-java-5.0.0.dev-java"
.....
gem "logstash-output-udp"
gem "logstash-output-webhdfs"
gem "logstash-filter-qatest"
```


```
vagrant@packer-virtualbox-iso-1452100235:~$ sudo /usr/share/logstash/bin/logstash-plugin update
Update is not supported for manually defined plugins or local .gem plugin installations, skipping: logstash-core, logstash-core-event-java, logstash-core-plugin-api
ERROR: Updated Aborted, message: ""\xC3"" from ASCII-8BIT to UTF-8
```

**Comment by purbon** [comment]
I did the same test with ubuntu-1404 host and got the same issue with the update all command, see

```
vagrant@packer-virtualbox-iso-1452039329:~$ sudo /usr/share/logstash/bin/logstash-plugin update
Update is not supported for manually defined plugins or local .gem plugin installations, skipping: logstash-core, logstash-core-event-java, logstash-core-plugin-api
ERROR: Updated Aborted, message: ""\xC3"" from ASCII-8BIT to UTF-8
vagrant@packer-virtualbox-iso-1452039329:~$ 
```

@ph as you created this test, any thoughts? might this be due to any problem with the dummy gems used?

**Comment by ph** [comment]
I think I know why, I believe the File.open of the `replace_in_gemfile` doesn't open the file with the correct mode.

**Comment by purbon** [comment]
Interesting, here I see two issues, 

1.- we can not use `bin/env` as this is not present in all different OS, or we should pick the right path for each OS.
2.- there is the issue with the command and the way we use it, my guess this is more a proper error, see previous comment for mode description.

**Comment by ph** [comment]
By curiosity which os doesn't have `/bin/env`?

**Comment by purbon** [comment]
this was a problem to me with debian-8, did not test more in deep but I
guess might be transferable to others (we should verify)

**Comment by ph** [comment]
With a freshly uncompressed `tar.gz`  I can install the dummy plugin, So I think sed it the culprit here.

```
root@packer-virtualbox-iso-1452039329:~/logstash-5.0.0.dev# bin/logstash-plugin install logstash-filter-qatest
Validating logstash-filter-qatest
Installing logstash-filter-qatest
Installation successful
root@packer-virtualbox-iso-1452039329:~/logstash-5.0.0.dev#
```

**Comment by ph** [comment]
I can replace the sed command with `sed` only the $PATH should allow us to find it hopefully on every os.

**Comment by ph** [comment]
@purbon I've loop at the original jenkins output carefully, I dont see any UTF error in it, how did you track it down, you just ran the command on the host itself after it fails?

**Comment by ph** [comment]
I fixed the update a specific plugin seems to work OK on ubuntu-1404, but updating all the plugins fails.

```
root@packer-virtualbox-iso-1452039329:/usr/share/logstash# bin/logstash-plugin update
Update is not supported for manually defined plugins or local .gem plugin installations, skipping: logstash-core, logstash-core-event-java, logstash-core-plugin-api
You are updating logstash-filter-xml to a new version 4.0.0, which may not be compatible with 3.0.1. are you sure you want to proceed (Y/N)?
```

**Comment by ph** [comment]
```
Encoding::UndefinedConversionError: ""\xC3"" from ASCII-8BIT to UTF-8
                      parse at org/jruby/ext/psych/PsychParser.java:178
               parse_stream at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/psych.rb:375
                      parse at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/psych.rb:323
                       load at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/psych.rb:250
                   versions at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/gems-0.8.3/lib/gems/client.rb:109
             method_missing at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/gems-0.8.3/lib/gems.rb:17
  fetch_latest_version_info at /usr/share/logstash/lib/pluginmanager/util.rb:55
   update_to_major_version? at /usr/share/logstash/lib/pluginmanager/util.rb:65
          validates_version at /usr/share/logstash/lib/pluginmanager/update.rb:75
               update_gems! at /usr/share/logstash/lib/pluginmanager/update.rb:50
                     select at org/jruby/RubyArray.java:2470
               update_gems! at /usr/share/logstash/lib/pluginmanager/update.rb:47
                    execute at /usr/share/logstash/lib/pluginmanager/update.rb:26
                        run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                    execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                        run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                        run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
                     (root) at /usr/share/logstash/lib/pluginmanager/main.rb:43
```

**Comment by purbon** [comment]
so encoding error in the dummy gemspecs?

**Comment by ph** [comment]
Adding `--no-verify` make the command works succesfully, the problem is when we call rubygems.

**Comment by ph** [comment]
@purbon LOL, look at this adding a begin;rescue;pry dance.

```
    52: def self.fetch_latest_version_info(plugin, options={})
    53:   require "gems"
    54:   exclude_prereleases =  options.fetch(:pre, false)
    55:   begin
    56:     versions = Gems.versions(plugin)
    57:   rescue => e
 => 58:     require "pry"; binding.pry
    59:   end
    60:   raise ValidationError.new("Something went wrong with the validation. You can skip the validation with the --no-verify option") if !versions.is_a?(Array) || versions.empty?
    61:   versions = versions.select { |version| !version["prerelease"] } if !exclude_prereleases
    62:   versions.first
    63: end

[1] pry(LogStash::PluginManager)> plugin
=> "logstash-output-webhdfs"
[2] pry(LogStash::PluginManager)>
```

I think its a genuine bug that we have found :D

**Comment by ph** [comment]
From https://github.com/logstash-plugins/logstash-output-webhdfs/blob/master/logstash-output-webhdfs.gemspec#L9

We see this, look at the o, so I think we have the wrong encoding in the file.
`s.authors         = ["Björn Puttmann, loshkovskyi, Elastic"]`

**Comment by purbon** [comment]
WHAT!! hunting bugs one at a time, happy to help!

thanks for your fix.

-purbon

**Comment by ph** [comment]
@purbon can you take a look at this PR https://github.com/logstash-plugins/logstash-output-webhdfs/pull/21 ?

**Comment by purbon** [comment]
this error is still there, also after the release of the new webhdfs plugin.

**Comment by purbon** [comment]
but is certainly related to this plugin as not having it in the bundle actually let update work again.
