### ISSUE TITLE
GeoIP2 MaxMind Database - Are the Logstash 5 docs correct?

### ISSUE THREAD

**Issue by dayjavid** [elastic/logstash#5480]
- Version: 5.0.0-alpha3
- Operating System: Centos7

Working through the Logstash setup documentation, the docs specify the following:

> Logstash releases ship with the GeoIP2 city database made available from Maxmind with a CCA-ShareAlike 3.0 license. For more details on GeoIP2, see http://dev.maxmind.com/geoip/

Visiting the maxmind site, there did not seem to be a way to download the GeoIP2 city database without paying.

Communicated with Maxmind support and they said:
> GeoIP2 City is a paid database. GeoLite2 City is free.

Is this an issue with the documentation? Or is all that in flux at the moment?

**Comment by suyograo** [comment]
This is a docs issue. I'll fix it

**Comment by suyograo** [comment]
Updated the docs.

**Comment by suyograo** [comment]
Fixed https://www.elastic.co/guide/en/logstash/5.0/plugins-filters-geoip.html

**Comment by dayjavid** [comment]
Awesome. Thanks!
