### ISSUE TITLE
"==" in if condition in /etc/init.d/logstash

### ISSUE THREAD

**Issue by mizeng** [elastic/logstash#5482]
Hi, I've downloaded logstash_2.3.2-1_all.deb from official site. But found there's one error in /etc/init.d/logstash after I installed the deb in Ubuntu14 server.

```
if [ "$KILL_ON_STOP_TIMEOUT" == 1 ] ; then
```

I think this should be 
```
if [ "$KILL_ON_STOP_TIMEOUT" = 1 ] ; then
```

Anything I missed?

**Comment by purbon** [comment]
A fix for this has been proposed and merged in https://github.com/elastic/logstash/pull/5479, will be released with next version, Keep in mind this does not happen in the newer version of LS, 5.0 and so on.
