### ISSUE TITLE
Logstash startup time

### ISSUE THREAD

**Issue by JamesMcTavish** [elastic/logstash#5491]
I've seen reports for logstash taking long times starting up (Issue #1511),  but I think my instance takes the cake:

```
> /usr/share/logstash/bin/logstash help
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.1 - omit version 2.7.0
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.1 - omit version 2.7.1-1

Usage:
    bin/logstash [OPTIONS]

Options:
    -n, --node.name NAME          Specify the name of this logstash instance, if no value is given
...
/usr/share/logstash/bin/logstash --path.settings=/etc/logstash --help  13.42s user 0.36s system 5% cpu 4:20.27 total
```
4 minutes to get the help screen seems wrong.  And 4+ minutes to start up the service with a minimal config.

```
> time /usr/share/logstash/bin/logstash --path.settings=/etc/logstash --version
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.1 - omit version 2.7.0
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.1 - omit version 2.7.1-1
Sending logstash logs to /var/log/logstash/logstash.log.
logstash 5.0.0-alpha3
/usr/share/logstash/bin/logstash --path.settings=/etc/logstash --version  14.28s user 0.40s system 11% cpu 2:07.78 total
```
2 minutes to get the version.

It is running in a KVM virtual machine, however during this, no swap is being used, CPU is more than 95% idle the entire time that logstash is starting.  This applies to both the VM and the host.

5.0.0alpha3 was installed from the instructions here:
https://www.elastic.co/guide/en/logstash/5.0/installing-logstash.html#package-repositories

Running on Ubuntu 14.04.4 LTS with everything up to date.

Java info:
```
> java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```
Configuration wise, I have an input for syslog:
```
input {
        tcp {
                port => 5000
                type => syslog
        }
        udp {
                port => 5000
                type => syslog
        }
}
```
and an output to elasticsearch:
```
output {
        elasticsearch {
                hosts => ["localhost:9200"]
                sniffing => true
                manage_template => false
                index => "syslog-%{+YYYY.MM.dd}"
                document_type => "syslog"
        }
}
```
And that is it.  Any help debugging why it is taking such a long time to startup would be greatly appreciated.

**Comment by bpapantonio** [comment]
I had the same problem with OpenJDK on CentOS 6. Logstash 5.0.0-alpha4.snapshot1 took 1-3 minutes to display the version. I reduced the startup time to 7 seconds (woeful, but better) by changing Java's entropy source from `/dev/random` to `/dev/urandom`

https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html
> 1. Open the `$JAVA_HOME/jre/lib/security/java.security` file in a text editor.
> 2. Change the line:
> `securerandom.source=file:/dev/random`
> to read:
> `securerandom.source=file:/dev/urandom`
> 3. Save your change and exit the text editor.

Note the security implication of such a change as it applies to your environment.

**Comment by JamesMcTavish** [comment]
That works far better.  Took it down to 18s.  Not that great, but much easier for debugging grok.  Thanks.

**Comment by JamesMcTavish** [comment]
I'm now just a duplicate of #1511, so I'll close this.

**Comment by jsvd** [comment]
related to https://github.com/jruby/jruby/issues/1896

**Comment by FlorinAndrei** [comment]
Please note that on many systems it's enough to just run `rng-tools`. This service will feed the pool extra entropy, thereby avoiding depletion. E.g. on Ubuntu 16.04 or newer, just install the `rng-tools` package:

```
apt-get install rng-tools
```

After installation, the `rng-tools` service (the `rngd` daemon) should start automatically.

**Comment by hicqu** [comment]
Or if you run logstash on Archlinux, it will be useful:
```bash
yaourt -S haveged
sudo systemctl start haveged.service
```
**haveged** will write some random thing into /dev/random.

**Comment by mrjameshamilton** [comment]
same issue. I've installed rng-tools and it doesn't help.
