### ISSUE TITLE
Mass update plugins gemspec so 5.x plugins can be installed on LS 2.4 and above

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5496]
We added `set` and `get` API for Ruby Event class in 2.4. When we release 2.4, we should relax the constraint for `logstash-core-plugin-api` so plugins developed for 5.x can be installed on 2.4. 

For example, if 2.4 ships with `logstash-core-plugin-api` version 1.60.0 we can then make 

```
s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.60.0", "< 3.0"
```

**Comment by jsvd** [comment]
Now that Logstash 2.x can use Event#get/#set, Logstash 2.4.x should be able to use plugins that use the event apis 1 and 2, which means:
* A plugin that works in Logstash 2.3 should work as is in Logstash 2.4
* A plugin that works in Logstash 5.0.0-alpha4 should work as is in LogStash 2.4, but not 2.3

This is a problem since logstash-core-plugin-api 1.x and 2.x are mutually exclusive. It's not possible to install and use both versions of the same gem on Logstash 2.4

At most, we can decide that either:
* Logstash 2.4 uses the same plugin api as 2.3, and therefore no 5.x compat
* Logstash 2.4 uses only v2 api, and so all v2 plugins become usable in Logstash 2.4.x and 5.x

Thoughts?

**Comment by jsvd** [comment]
ok so after some more discussion, I think I agree with @suyograo's proposal:

* We need to minor bump logstash-core-plugin-api 1.x (to 1.20.0) to introduce the .set/.get to the "old API"
* `logstash-core-plugin-api 1.20.0` will respect SEMVER by introducing this new API but not breaking bwc
* `logstash-core-plugin-api 1.20.0` will depend on logstash-core >= 2.4, < 6

All master branches of plugins will depend on `s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.20.0", "~> 2"`
All plugin-api-v1 branches of plugins can continue to depend on `s.add_runtime_dependency "logstash-core-plugin-api", "~> 1"`

**Comment by suyograo** [comment]
We had a discussion on Slack with @jsvd and @colinsurprenant. 

At the time of writing this comment, current core-plugin API version that tracks `2.3.4` is `1.20.0`. For LS 5.0.0-alpha4 it is version `2.1.x`. We choose `1.60.0` as plugin API version to start tracking LS 2.4. The gap from `1.20.0` to `1.60.0` is intentional and gives us enough wiggle room so we can release more versions of 2.3.x if necessary. In other words, we have reserved versions `1.20.0` to `1.60.0` for 2.3.x releases. 

| Plugin API Version | Logstash Version | Plugin gemspec definition |  Why? |
|:---------------:|:------------------:|:--------------:|:---------------:|:------|
| 1.0 to 1.59          | 2.0 - 2.3.x   | `"logstash-core-plugin-api", "~> 1.0"` | Legacy plugins with Ruby Event API `[]`,`[]=`,`get`,`set`. Already released versions, constraints cannot be changed |
| 1.60.0 to 2.00       | 2.4   | `"logstash-core-plugin-api", ">= 1.60.0 < 2.99"`  | Plugins developed with Event API, but with `get`, `set` aliased to `[]` and `[]=` |
| 2.00 to 2.99       | 5.x   | `"logstash-core-plugin-api", ">= 1.60.0 < 2.99"`  | Plugins developed with Event API with `get`,`set` using real Java Event implementation |

**Comment by ph** [comment]
Looks fine for me ^

**Comment by jsvd** [comment]
@ph when do you consider these mass updates "done"? all plugins that had a master branch with plugin_api ~> 2.0 dependency have been updated, so I guess this can be closed..

**Comment by ph** [comment]
@jsvd this is a hairy thing, it really depends on the purpose of the mass update in this case, I am wondering if we should mass publish them or not.

**Comment by jsvd** [comment]
All plugins that where plugin api v2 compatible have already been published.
Now that i think about it, I think it's safe to close this as done.
