### ISSUE TITLE
Mass update plugins to use :list => true over :type => :array

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#5498]
We now support a `:list => true` option that replaces the `:type => :array` setting. This will be supported in Logstash 2.4+ and 5+.  We need to mass update all plugins to prefer `:list => true`. Arrays are still necessary when the type is mixed or unknown, but if the array is expected to be of a single type it should be switched.

* [ ] logstash-codec-collectd/lib/logstash/codecs/collectd.rb
* [ ] logstash-codec-csv/lib/logstash/codecs/csv.rb
* [ ] logstash-codec-multiline/lib/logstash/codecs/multiline.rb
* [ ] logstash-codec-netflow/lib/logstash/codecs/netflow.rb
* [ ] logstash-filter-alter/lib/logstash/filters/alter.rb
* [ ] logstash-filter-anonymize/lib/logstash/filters/anonymize.rb
* [ ] logstash-filter-checksum/lib/logstash/filters/checksum.rb
* [ ] logstash-filter-cidr/lib/logstash/filters/cidr.rb
* [ ] logstash-filter-clone/lib/logstash/filters/clone.rb
* [ ] logstash-filter-csv/lib/logstash/filters/csv.rb
* [ ] logstash-filter-date/lib/logstash/filters/date.rb
* [ ] logstash-filter-de_dot/lib/logstash/filters/de_dot.rb
* [ ] logstash-filter-dissect/lib/logstash/filters/dissect.rb
* [ ] logstash-filter-dns/lib/logstash/filters/dns.rb
* [ ] logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb
* [ ] logstash-filter-fingerprint/lib/logstash/filters/fingerprint.rb
* [ ] logstash-filter-geoip/lib/logstash/filters/geoip.rb
* [ ] logstash-filter-grok/lib/logstash/filters/grok.rb
* [ ] logstash-filter-hashid/lib/logstash/filters/hashid.rb
* [ ] logstash-filter-i18n/lib/logstash/filters/i18n.rb
* [ ] logstash-filter-json/lib/logstash/filters/json.rb
* [ ] logstash-filter-kv/lib/logstash/filters/kv.rb
* [ ] logstash-filter-metrics/lib/logstash/filters/metrics.rb
* [ ] logstash-filter-multiline/lib/logstash/filters/multiline.rb
* [ ] logstash-filter-mutate/lib/logstash/filters/mutate.rb
* [ ] logstash-filter-prune/lib/logstash/filters/prune.rb
* [ ] logstash-filter-range/lib/logstash/filters/range.rb
* [ ] logstash-filter-syslog_pri/lib/logstash/filters/syslog_pri.rb
* [ ] logstash-filter-unique/lib/logstash/filters/unique.rb
* [ ] logstash-input-beats/lib/logstash/inputs/beats.rb
* [ ] logstash-input-elasticsearch/lib/logstash/inputs/elasticsearch.rb
* [ ] logstash-input-file/lib/logstash/inputs/file.rb
* [ ] logstash-input-generator/lib/logstash/inputs/generator.rb
* [ ] logstash-input-irc/lib/logstash/inputs/irc.rb
* [ ] logstash-input-kafka/lib/logstash/inputs/kafka.rb
* [ ] logstash-input-rabbitmq/lib/logstash/inputs/rabbitmq.rb
* [ ] logstash-input-salesforce/lib/logstash/inputs/salesforce.rb
* [ ] logstash-input-snmptrap/lib/logstash/inputs/snmptrap.rb
* [ ] logstash-input-sqlite/lib/logstash/inputs/sqlite.rb
* [ ] logstash-input-syslog/lib/logstash/inputs/syslog.rb
* [ ] logstash-input-tcp/lib/logstash/inputs/tcp.rb
* [ ] logstash-input-twitter/lib/logstash/inputs/twitter.rb
* [ ] logstash-mixin-rabbitmq_connection/lib/logstash/plugin_mixins/rabbitmq_connection.rb
* [ ] logstash-output-boundary/lib/logstash/outputs/boundary.rb
* [ ] logstash-output-csv/lib/logstash/outputs/csv.rb
* [ ] logstash-output-datadog/lib/logstash/outputs/datadog.rb
* [ ] logstash-output-datadog_metrics/lib/logstash/outputs/datadog_metrics.rb
* [ ] logstash-output-elasticsearch/lib/logstash/outputs/elasticsearch/common_configs.rb
* [ ] logstash-output-email/lib/logstash/outputs/email.rb
* [ ] logstash-output-gelf/lib/logstash/outputs/gelf.rb
* [ ] logstash-output-graphite/lib/logstash/outputs/graphite.rb
* [ ] logstash-output-irc/lib/logstash/outputs/irc.rb
* [ ] logstash-output-juggernaut/lib/logstash/outputs/juggernaut.rb
* [ ] logstash-output-lumberjack/lib/logstash/outputs/lumberjack.rb
* [ ] logstash-output-opentsdb/lib/logstash/outputs/opentsdb.rb
* [ ] logstash-output-redis/lib/logstash/outputs/redis.rb
* [ ] logstash-output-s3/lib/logstash/outputs/s3.rb
* [ ] logstash-output-statsd/lib/logstash/outputs/statsd.rb

**Comment by wiibaa** [comment]
Self-reminder => [search for occurences in logstash-plugins ruby sources for `:validate => :array`](https://github.com/search?p=2&q=org%3Alogstash-plugins+%22%3Avalidate+%3D%3E+%3Aarray%22&ref=searchresults&type=Code&utf8=%E2%9C%93)

**Comment by andrewvc** [comment]
@wiibaa thanks so much for putting that query in there!

**Comment by andrewvc** [comment]
This is just a lot of work for something that already works. We should update these plugins, but we can do so as we come across issues or are doing other refactors.
