### ISSUE TITLE
logstash http output plugin does not work with authenticated proxy via https

### ISSUE THREAD

**Issue by arkadyi** [elastic/logstash#5508]
- Version:  2.3.1
- Operating System: CentOS 7
- Config File (if you have sensitive info, please remove it):
  input {
      file {
              path => [ "/opt/seculert/*_/log/_.log" ]
              start_position => "beginning"
              type => "seculert_logs" # Used in filter and output bellow (change all values accordingly)
              codec => multiline {
                pattern => "(.|\r|\n)"
                max_lines => 10
                auto_flush_interval => 60
                what => "previous"
              }
              sincedb_path => "/opt/seculert/logStash/conf/sincedb"
      }
  }

filter {
        # Filter only events with type=seculert_logs
        if [type] == "seculert_logs" and [message] =~ /(?i)error/ {
                mutate {
                        add_tag => [ "log_error" ]
                }
        }
}

output {
        if [type] == "seculert_logs" {
                http {
                        http_method => "post"
                        url => "https:/mydomain.com/"
                        cacert => "/etc/ssl/certs/GeoTrust_SSL_CA_G2.cer"
                        codec => "json"
                        headers => {
                                "Proxy-Authorization" => "Basic XXXX"
                                "Pragma" => "no-cache"
                        }
                       proxy => "http://10.10.0.254:3128"
                }
        }
}
- Sample Data:
- Steps to Reproduce:
  When trying to configure logstash sends logs via https via authenticated proxy logstash does not add to CONNECT message any headers specified and hence failed proxy authentication.

Adding proxy prameters directly to JVM does not help either.
Form time to time I got an arror that logstash ruby code tries to use non-existing java method when tries to add headers.
It happens only if the original URL is HTTPS.
Here is an example of stack trace:

NameError: no method 'setHeader' for arguments (org.jruby.RubySymbol,org.jruby.RubySymbol) on Java::OrgApacheHttpClientMethods::HttpPost
  available overloads:
    (java.lang.String,java.lang.String)
    (java.lang.String,java.lang.String)
                   []= at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/java_extensions.rb:18
  request_from_options at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:490
                  each at org/jruby/RubyHash.java:1342
  request_from_options at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:490
               request at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:418
                  post at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:265
                  post at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client/proxies.rb:31
               receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.3/lib/logstash/outputs/http.rb:120
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.3/lib/logstash/outputs/http.rb:93
                  each at org/jruby/RubyArray.java:1613
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.3/lib/logstash/outputs/http.rb:93
  worker_multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:130
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:114
          output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301
                  each at org/jruby/RubyHash.java:1342
          output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301
           worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:232
         start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:201
~

**Comment by kares** [comment]
seems like the plugin missed proper a `to_s` for the Java method params.
anyways the plugin is at version 5.1 now and the issue is likely to have been resolved since, if someone feels it isn't please report at: https://github.com/logstash-plugins/logstash-output-http/issues
