### ISSUE TITLE
Add the idea of experimental platforms to the Acceptance test framework

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5509]
This will let us keep focus on platforms inside the support matrix, but also do some testing on upcoming platforms without mixing concepts. For example like happens with current failures inside ubuntu-1604 (#5504).

The experimental layer will need to be included as a new step inside https://logstash-ci.elastic.co .

This will keep the acceptance testing strictly to match the support matrix while letting us test on upcoming supported platforms and be sure they are in good health for our product. What do you think?

**Comment by purbon** [comment]
Feedback from @ph in the PR:

> I understand the intend, I find it similar to the possibility of making a test as pending. Marking a test as pending or disabling a test is the best way to make it rot.

>I think Its wiser and easier to communicate to have the the following strategy: when we add a new machine in the platforms matrix, we or the community make a commitment to support it until it make no sense to support it. Since we can run the tests locally we have the possibility to test how logstash behave before deciding to support a platforms.

>So in my opinion I am not in favor of having this feature, I am more into lets reduce the scope. But, if we decide to go ahead with a concept of experimental maybe its the responsibility of the CI to mark a job as experimental and not take it into consideration when this job fails for the dependent job.

>This PR target explicitly ubuntu-1604, which is the latest Ubuntu LTS, I think we should concentrate into fixing the root problem before having the possibility to mark as experimental.

**Comment by suyograo** [comment]
So when will `experimental` ever run?

**Comment by suyograo** [comment]
Or how would you trigger an experimental run?

**Comment by purbon** [comment]
@suyograo 
 will run whenever we like to, my proposal is to have another layer in the CI infra, but not tied to the full acceptance as this platforms are nice to test with, but not in our support matrix.

As you can see in the PR, #5506, to trigger the experimental OS's I added an ENV var, but this is open to discuss best way for sure. My thoughts are easy here, is better to have them available somehow, than removed so there is no test at all, also locally.
