### ISSUE TITLE
Metric input failling test

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5518]
```
Failures:
  1) LogStash::Inputs::Metrics#stop should unblock the input
     Failure/Error: t = Thread.new { subject.run(queue) }
     NoMethodError:
       undefined method `collector' for nil:NilClass
     # ./logstash-core/lib/logstash/inputs/metrics.rb:24:in `run'
     # ./logstash-core/spec/logstash/inputs/metrics_spec.rb:39:in `(root)'
  2) LogStash::Inputs::Metrics#update should fill up the queue with received events
     Failure/Error: t = Thread.new { subject.run(queue) }
     NoMethodError:
       undefined method `collector' for nil:NilClass
     # ./logstash-core/lib/logstash/inputs/metrics.rb:24:in `run'
     # ./logstash-core/spec/logstash/inputs/metrics_spec.rb:45:in `(root)'
Finished in 1 minute 45.12 seconds (files took 5.65 seconds to load)
1234 examples, 2 failures
Failed examples:
rspec ./logstash-core/spec/logstash/inputs/metrics_spec.rb:44 # LogStash::Inputs::Metrics#stop should unblock the input
rspec ./logstash-core/spec/logstash/inputs/metrics_spec.rb:24 # LogStash::Inputs::Metrics#update should fill up the queue with received events
Randomized with seed 11271
```

**Comment by ph** [comment]
@jsvd This is really a visibility issue across thread that get exposed by this failling test.
For performance reason I want to reduce to the maximum  the need to uses lock on the metric reference since the internal of the metric is thread safe.

The problem is the following, the metric get set in the plugin by calling setter method `metric=`, no lock is  done on the instance variable. The run is called from another thread, in some circumstances the memory barrier is not crossed at that stage and result in a nil exception.

I suggest the following fix, remove the `metric=` setter and move the set in the `initialize` method, initialize will allow synchronization of the value. WDYT?

**Comment by ph** [comment]
@andrewvc since you have been working with the metrics, WTDY of this proposal?

**Comment by jordansissel** [comment]
@ph and I paired on zoom about this. I'm not sure how `subject.metric` is somehow returning nil despite the `before` setting up an `allow()` that overrides `metric` method. Very funky.

Recommendations:

* See if we can reproduce and understand why this happens
* Worst case, use the `Plugin#metric=` method to set the metric instead of using `allow()` since we have this `metric=` accessor method anyway.

@ph is going to see if we can more easily reproduce this with Flores's `stress_it` stuff.

**Comment by ph** [comment]
10x run of stress without any errors with the first implementation with `allow`

**Comment by ph** [comment]
I havent been able to reproduce that, but I've changed the `allow` to use the setters in this PR #5542

**Comment by ph** [comment]
Since the change of the code I haven't seen this error surfaced, lets close this one.
