### ISSUE TITLE
make --version faster by not launch logstash

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5526]
This has been done already for *nix systems in https://github.com/elastic/logstash/issues/5407
in commit https://github.com/elastic/logstash/commit/72b277404b2da8586e23327e1659c06db69e274b but now this needs to be converted to windows BATCH script

**Comment by royalharsh** [comment]
Any updates on this issue? There's a pending PR.

**Comment by colinsurprenant** [comment]
merged in master and 6.x
