### ISSUE TITLE
Harden Gemfile used in release packages

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5534]
We should harden the [Gemfile](https://github.com/elastic/logstash/blob/5.0/Gemfile) used in release branches to be more restrictive w.r.t. versions. Today, its really easy to slip and include a major version of a plugin in a LS minor release, as long as its compatible with the core APIs. This is definitely not desirable from a user perspective because plugin major versions _can_ break compatibility. And we don't intend to break compatibility in LS minor releases. One protection would be to add tighter constraints to every plugin specified in `Gemfile` such that minor LS versions will only include patch releases for plugins. By using the [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic_version_constraint).

For example:

```
gem "logstash-filter-grok", "~> 3.0"
```

This means grok plugin versions `>= 3.x` is allowed but not ones `>= 4.0`. There would be no danger of accidentally including a major version release of a plugin for LS minor releases. 

For LS major releases, a new constraint file needs to be generated which relaxes the constraint to include the next majors.

Thoughts? /cc @jsvd @ph @jordansissel

**Comment by jsvd** [comment]
> One protection would be to add tighter constraints to every plugin specified in Gemfile such that minor LS versions will only include patch releases for plugins. By using the pessimistic version constraint.

I'm not sure if that is your intent, but I'd guess we want to set the pessimistic constraint to the minor version, not patch. So:

`gem "logstash-filter-grok", "~> 3"`

This way it won't upgrade to 4 but can upgrade to 3.1, 3.2, 3.2.3, etc

**Comment by jsvd** [comment]
done in #5535
