### ISSUE TITLE
Logstash v2.3.3: A plugin had an unrecoverable error

### ISSUE THREAD

**Issue by henghenghahai** [elastic/logstash#5550]
Hi,
I push windows eventlog using winlogbeat-dev(Version: 5.0.0-nightly2bfc1c4) to logstash v2.3.3,the logstash configuration is

input{
beats {
add_field =>["itcategory","it_security_windowslog"]
port => 5150
}
}
...

output{
elasticsearch {
hosts => "localhost"
index => "it_security_windowslog-%{+YYYY.MM.dd}"
document_type => "windowslog"
}
}
}

...

but on the second day ,logstash would crashed, logstash.err showed:
(I have increased the logstash memory from 500MB to 2048MB,no effect)

Error: Your application used more memory than the safety cap of 2G.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace

logstash.log shows:

{:timestamp=>"2016-06-24T07:09:12.797000+0800", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Beats add_field=>{\"itcategory\"=>\"it_security_windowslog\"}, port=>5150, codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">, host=>\"0.0.0.0\", ssl=>false, ssl_verify_mode=>\"none\", congestion_threshold=>5, target_field_for_codec=>\"message\">\n  Error: unable to create new native thread", :level=>:error}

anybody could help me? thanks.

**Comment by ph** [comment]
I would like to know which version of the beats input you are currently using. Could you add to this ticket the output of the command `bin/plugin list --verbose beats`

Thanks.

**Comment by ph** [comment]
Closing, since we haven't received any more details on it and we releases a new version which is a complete rewrite.
