### ISSUE TITLE
Syntax issue in Logstash File Plugin Docs

### ISSUE THREAD

**Issue by e-mars** [elastic/logstash#5558]
In https://www.elastic.co/guide/en/logstash/current/plugins-outputs-file.html

Top, change example on codec:
current: codec => { line { format => "custom format: %{message}"}}
new: codec => line {format => "%{message}" }

*extra "{}" cause issue with validation and parsing in logstash.

```
[root@lsnode2 bin]# service logstash configtest
The given configuration is invalid. Reason: Expected one of #, => at line 16, column 21 (byte 291) after output {
#  elasticsearch {
#    hosts => "esnode11:9200"
#    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
#    user => "esadmin"
#    password => "password123!"
#  }
  file {
    path => "/Data/fileoutput/fileplugintest.log"
    codec => { line  {:level=>:fatal}
```

Thanks,
Marcelo

**Comment by dedemorton** [comment]
Closing because this issue was fixed in the source here: https://github.com/logstash-plugins/logstash-output-file/pull/44. I've also changed it in the asciidoc to get the changes showing up in the doc build.
