### ISSUE TITLE
human parameter on the hot threads API returns a response that's not really human readable

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#5563]
When I run the hot threads API with `?human=true` specified, the results are not really human readable, and specifying `?human=false` does not seem to change the response.

In previous alpha versions, I believe that we returned a more readable response, as shown in the [documentation](https://www.elastic.co/guide/en/logstash/5.0/hot-threads-api.html) for the hot threads API. I'm opening this issue in case this change was not intentional.

- Version: 5.0.0-alpha4
- Operating System: OS X
- Config File: NA
- Sample Data: NA
- Steps to Reproduce:
Call the hot threads API and specify `?human=true`. The call returns a response that seems to be in XML format, but (IMHO) isn't really human readable. Setting `human=false` returns the same document. This makes me wonder if the `human` parameter is working as expected.

**Comment by purbon** [comment]
@andrewvc something got wrong in your during your refactoring?

**Comment by nemonster** [comment]
I just saw the same thing running this command from the diagnostic.  I used the exact syntax that was in the current alpha-4 documentation.  Copied it.
/_node/hot_threads?human=true

What I get is unpretty json.  It's essentially the same output as if you run it with no options at all.

Attaching a sample of what I got.
[nodes_hot_threads.txt](https://github.com/elastic/logstash/files/354732/nodes_hot_threads.txt)
