### ISSUE TITLE
Change rpm/deb metadata naming scheme

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5576]
Currently package names for rpm and deb are created like: `1:5.0.0~alpha4-1`

Even though the latest refactor to the package creation changed the file names to `logstash-5.0.0-alpha4.deb`, the metadata for the name has not changed.

Looking at the code, it's just a matter of removing the version modification in https://github.com/elastic/logstash/blob/master/rakelib/artifacts.rake#L389

**Comment by jordansissel** [comment]
> the metadata for the name has not changed.


This is correct. The version must use ~ in the string in order for sorting to work correctly such that "5.0.0" is considered greater/newer than "5.0.0 alpha4". This is true for both Debian and Red Hat packaging.

**Comment by jordansissel** [comment]
I'm closing this since I am pretty sure Logstash is doing the right thing (using `~` in the version field of deb/rpm metadata).

for historical reference, [this pr](https://github.com/elastic/logstash/pull/2461) has details on why we use tilde.
