### ISSUE TITLE
ruby-maven errors when installing plugins at ubuntu-1404

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5583]
Hi,
   since the development of our qa infra we've saw (till now a couple of times, #5325 and #5581) that for ubuntu-1404 ruby-maven needs up to date root certificates. If you're in this platform and can not install plugins, you might be hitting this error. To solve it you can use `sudo update-ca-certificates -f` to solve it.

@suyograo I'm wondering if we could add a documentation section to communicate this issue somehow? what do you think?

**Comment by suyograo** [comment]
@dedemorton Where would we put this in our documentation? I am hesitant to add a "Troubleshooting Guide". Maybe a note in https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html

**Comment by dedemorton** [comment]
@suyograo We can def add a note to the section about installing plugins, but this seems like a bit of an edge case because it involves a very specific scenario: if you're using Ubuntu and trying to install plugins and your root certificates need to be refreshed. This definitely warrants a post in the discussion forums. But to help users who run into this problem while installing, it seems to me that having a more meaningful error message would help users more than a note in the docs. But maybe that's not possible?

If I add a note to the doc, what should it say so that we don't confuse users who are having trouble installing, but for other reasons? And maybe they don't know anything about CAs or certificates?

**Comment by purbon** [comment]
> But to help users who run into this problem while installing, it seems to me that having a more meaningful error message would help users more than a note in the docs

This is for sure an edge case, only happening in ubuntu version 14.04 (LTS).

Not sure how hard would it be to catch this issue and report more concrete message, probably would it be very specific to include in the code base, jar-dependencies will need to be patched.

@suyograo not sure to follow why not to add some kind of `troubleshooting` section, might be not a full section for logstash, but small one in the working with plugins page? what do you think?

**Comment by purbon** [comment]
> If I add a note to the doc, what should it say so that we don't confuse users who are having trouble installing, but for other reasons? And maybe they don't know anything about CAs or certificates?

The initial error is somehow generic, but if you run the same command with `DEBUG=1` more detailed info will be printed, and with this issue you will see something like 

```
Using ruby-maven 3.3.12
0:  ruby-maven (3.3.12) from /usr/share/logstash/vendor/bundle/jruby/1.9/specifications/ruby-maven-3.3.12.gemspec
  jar dependencies for logstash-core-event-java-5.0.0.pre.alpha4-java.gemspec . . .
Warning: JAVA_HOME environment variable is not set.
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.4/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.4/lib/jars/gemspec_pom.rb) has 1 error
[ERROR]     Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.4/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

Errno::ENOENT: No such file or directory - /usr/share/logstash/logstash-core-event-java/deps.lst
```

I guess we can say something in the order of:

* If you can not install plugins in logstash.
* and run ubuntu 1404 version as OS.
* if you run the installation with DEBUG=1 and see something like the previous error with maven.
* you should update your ca certificates with `sudo update-ca-certificates -f`

@suyograo makes sense to you?

**Comment by suyograo** [comment]
@dedemorton Lets add it to the troubleshooting section. We can also link from that page to "known issues" label in GH. WDYT?

**Comment by dedemorton** [comment]
@purbon My hesitation to document edge cases comes from years of experience fixing documentation full of obsolete notes about edge cases. :-) The notes lose relevance quickly, but seem to persist in the docs long after they're relevant. Maybe we won't have that problem because we update the docs constantly, but my knee jerk reaction is to question whether we should be documenting edge cases in the core docs. :-) Also, we need to be careful about sending users down rabbit holes that might make it harder for them to diagnose a problem. Providing a meaningful error message, if feasible, is better from the user's perspective. 

Of this problem is likely to persist for some time, then it definitely warrants mention in the docs.

@suyograo Is there anything besides the Ubuntu issue that you'd like me to add to the troubleshooting section in the plugins page? Seems like focusing on this one issue will disappoint users who run into other installation issues.

**Comment by purbon** [comment]
@dedemorton completely understand that, will see if I can manage to make the error more clear to users, just in case this helps. Also the known issue here will help, might be we can add a section in documentation that actually point here (that we can probably change more dynamically). makes sense?

**Comment by mkoertgen** [comment]
I just checked the proposed solution using `sudo update-ca-certificates -f` on Ubuntu 16.04.

As said in https://github.com/elastic/logstash/issues/5581#issuecomment-232433116 please note that this does not resolve the issue on Ubuntu 16.04 LTS. 

I get a similar output erroring on `/usr/share/logstash/logstash-core-event-java/deps.lst` missing:

    Using ruby-maven 3.3.12
    0:  ruby-maven (3.3.12) from /usr/share/logstash/vendor/bundle/jruby/1.9/specifications/ruby-maven-3.3.12.gemspec
      jar dependencies for logstash-core-event-java-5.0.0.pre.alpha4-java.gemspec . . .
    [ERROR] [ERROR] Some problems were encountered while processing the POMs:
    [FATAL] Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.4/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
     @
    [ERROR] The build could not read 1 project -> [Help 1]
    [ERROR]
    [ERROR]   The project  (/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.4/lib/jars/gemspec_pom.rb) has 1 error
    [ERROR]     Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.4/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
    [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

    Errno::ENOENT: No such file or directory - /usr/share/logstash/logstash-core-event-java/deps.lst
    org/jruby/RubyIO.java:3804:in `read'
    org/jruby/RubyIO.java:3987:in `read'

**Comment by mkoertgen** [comment]
Coult it be that somehow the maven extensions are missing again?

- https://github.com/mkristian/ruby-maven/issues/8
- https://github.com/jruby/jruby/issues/3676

**Comment by suyograo** [comment]
This should be solved with the latest jar-dependencies. There is no need for doc changes at this point for this.
