### ISSUE TITLE
Better conditional error messages

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#5593]
Currently, if a logstash config contains a boolean expression like `if [foo] > 2` and `[foo]` is of the wrong type or nil it will raise exceptions that can be confusing. We should do the following:
1. Wrap all conditionals in a `begin; end` block, and re-raise the exception as a wrapped `LogStash::Pipeline::ConditionalError`. This can be caught be the code in https://github.com/elastic/logstash/pull/5562
2. Print out a friendlier error message like: "Your expression [foo] > 2 failed, probably because a field was null. The exact error wash ‘undefined method `>' for true:TrueClass".

**Comment by andrewvc** [comment]
Should be renamed to `continue_on_conditional_error`

**Comment by jsvd** [comment]
Sorry to backtrack here, but I'd like to steer away from focusing this too much on conditional errors.
The spectrum of exceptions that we can tolerate here should be more than conditional errors, but also uncaught filter exceptions and output exceptions.
This is also a commonly requested feature, so this flag would simply make logstash, as whole, try to plow through exceptions (disabled by default).

**Comment by andrewvc** [comment]
@jsvd we really need this feature if we're going to do #5641 , in fact we need it even more than we need #5641 because users are commonly confused with the error messages we currently give out and don't realize its their config that are going to be broken.

We should definitely wrap and re-raise all conditional errors and provide as much context as possible.

**Comment by C0rn3j** [comment]
`(TypeError) no implicit conversion of nil into Integer` is still a thing 8 years later (8.13.x).

It looks like 8.16.0+ will have something for this though? https://github.com/elastic/logstash/pull/16322
