### ISSUE TITLE
Deprecate --verbose and --debug

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5594]
In master/5.0, we removed --verbose and --debug. This was the right decision, but for reducing user pain, I think we should restore them with warnings about them being deprecated.

* `--debug` should warn users to use `--log.level debug` instead, and also imply that setting (debug)
* `--verbose` should warn users to use `--log.level info` instead, and imply that setting (verbose)

**Comment by jsvd** [comment]
closed by #5785
