### ISSUE TITLE
[2.x] Exception thrown if shutdown is requested during part of startup.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5604]
The error is this:

```
NoMethodError: undefined method `[]=' for nil:NilClass
```

This is caused when SIGTERM is sent between these lines of code: https://github.com/elastic/logstash/blob/v2.3.2/logstash-core/lib/logstash/agent.rb#L202-L213

This appears to be fixed in master (https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/agent.rb#L54)

**Comment by jsvd** [comment]
closed by #5829
