### ISSUE TITLE
Add support to monitoring API for specifying a comma-separated list

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#5609]
When users call the Elasticsearch APIs, they can specify a comma-separated list of resources to limit the data that's returned by the call. For example, see https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-stats.html.

The Logstash monitoring APIs in 5.0 should support the same capability.

**Comment by andrewvc** [comment]
@acchen97 @suyograo I tagged  this as v5.0.0 is that correct?

**Comment by acchen97** [comment]
Added this to the meta issue https://github.com/elastic/logstash/issues/5607

**Comment by purbon** [comment]
@acchen97 @suyograo got a first idea of this in https://github.com/elastic/logstash/pull/5630, let me know if this is what you expect to have, or you find something more missing.
