### ISSUE TITLE
The rationale behind using BiValues as leaf nodes in the Java Event.

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#5614]
#### In the beginning.

There was the Java Event and it was simply a basic translation from the Ruby event. It was not done done.

When performing a `set` via the Event JRuby extension, the Ruby key, a RubyString/RubySymbol, is converted to a Java String. The value is one of RubyHash, RubyArray or an implementation of IRubyObject. This value is converted to a Java value before storing it in the Event data HashMap. There is a strict conversion lookup - if the Ruby value's type is not found in the lookup mechanism an error is raised.

When performing a `get` via the JRuby extension, the RubyString key is converted to a Java string and then the value is retrieved from the data HashMap and converted back to a new IRubyObject.

This conversion happens each time a value is set or retrieved in any part of the pipeline.

Note that if the value is a collection type all nested values are converted too. So if one `get` an intermediate hash, mutate it and `set` it back it will be deeply converted both times.

In an all Ruby centric plugin/pipeline (at present, we do not have pure Java plugins), this continual conversion is bad for performance.

In a mixed Ruby Java plugin/pipeline we would have some values being get/set from the Ruby side and some from the Java side. The Java side set/get has no conversion penalty.

One upside to this design is that Java event serialization is fast because the java values always exist.

#### The BiValue proposal.

Instead of repeatedly doing the conversion and losing the original IRubyObject reference, we store both the original IRubyObject and the Java object in a BiValue. Note: BiValue instances are only stored as leaf objects in a collection. Collections, RubyHash <-> HashMap; RubyArray <-> ArrayList do not have a concrete BiValue class.
Instead, RubyHash and Java HashMap will be converted into a ConvertedMap instance. Likewise, RubyArray and ArrayList will be converted into a ConvertedList. These two classes are used so we can be certain that the internal data Map is always one of a collection of ConvertedMap, ConvertedList or leaf BiValue. Any value not of these three types must be converted.

Each acceptable IRubyObject type has a corresponding Java type as codified in the converter lookup. Therefore there are concrete BiValue classes that enforce this relationship.
Examples:
- SymbolBiValue: maps RubySymbol -> String (set one way from Ruby, a Java String will be paired with a RubyString if set from Java)
- StringBiValue: maps RubyString <-> String.
- DoubleBiValue: maps RubyFloat <-> Double.

When set from Ruby, a BiValue looks like this:
```
                - rubyValue: RubyString: "foo"
StringBiValue -|
                - javaValue: String: null
```
When set from Java, a BiValue looks like this:
```
                - rubyValue: RubyFloat: null
DoubleBiValue -|
                - javaValue: double: 42.42
```

There are some upsides to using BiValues.
1. The other pair value is only converted when needed. So the Ruby centric pipeline/plugins the get/set of leaf values have no conversion penalty, i.e. using `[branch][branch][leaf]` accessors.
2. We can properly represent RubyNil as a BiValue that understands that the Java value is supposed to be null.

If one uses an accessor that does not refer to a leaf, e.g. `[branch]`, conversion on the ConvertedMap/List is done but this is no worse than what we have now. There would be a small performance improvement if the ConvertedMap keys were BiValues i.e. `ConvertedMap<BiValue, Object>` because the when converting it back to a HashMap or a RubyHash the key is easily retrieved from the BiValue. We should consider this though.

Before the Persistent Queue is in use...
1. The Event, from the JRuby/Java viewpoint an IRubyObject, is stored as-is in the Synchronized Queue.

After the Persistent Queue is in use...
1. The Java values are set by converting the Ruby values just before writing the Event into the Persistent Queue, because the Java values are converted to binary and persisted.
3. When a Java Event is read from the PQ all its Java values in the BiValues will be set. The Ruby value will be converted and set only if a Ruby plugin gets that value.
4. When the Event is JSON serialised in any outputs we can use Jackson on the already set Java values.

**Comment by colinsurprenant** [comment]
Can we close this since #4999 is not merged?
