### ISSUE TITLE
Bug inside the java event when upgrading to jruby 9000

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5617]
When running the test for #5616 to upgrade to 900 broke the timestamp extension build inside the java event, you could see the long error at: https://gist.github.com/purbon/04f4a80244013e97f88057ba95dcbd80

All looks to be related to

``` java
 if (epoch instanceof RubyBigDecimal) {
                    // bug in JRuby prevents correcly parsing a BigDecimal fractional part, see https://github.com/elastic/logstash/issues/4565
                    double usec = ((RubyBigDecimal)epoch).frac().convertToFloat().getDoubleValue() * 1000000;
                    t = (RubyTime)RubyTime.at(context, context.runtime.getTime(), ((RubyBigDecimal)epoch).to_int(), new RubyFloat(context.runtime, usec));
                }
```

this code,  part of the at methods inside the extension.

this bug is a _blocker_ to finish the upgrade to jruby 9000.

**Comment by colinsurprenant** [comment]
Weird. Just looked and this API, RubyBigDecimal#frac is still in 9k ... not sure why this is happening, will require some investigation.

**Comment by guyboertje** [comment]
Fixed in the feature/9000 branch
