### ISSUE TITLE
Move sincedb from LS_HOME to LS_HOME/data

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5624]
In 5.0.0-alpha2 we moved location of `sincedb` file from `USER_HOME` to `LS_HOME`. Since we introduced `LS_HOME/data` in #5404 we should move the implementation in file input to use this setting. Thoughts about placing this `sincedb` in `path.data/plugins/file-input/`?

PS: I filed this in core because this will be an example implementation for other plugins to use `path.data` for storing plugin specific metadata.

**Comment by untergeek** [comment]
👍 times 1000!

> Thoughts about placing this `synced` in `path.data/plugins/file-input/`?

I'm even more inclined to have this be in `path.data/plugins/file-input/UUID` (or the like), since we're going to be uniquely identifying plugin instances for monitoring.

**Comment by untergeek** [comment]
In my WIP, I have it at `path.data/plugins/inputs/file`, with the individual .sincedb_HASH names the same as they presently are, which is `".sincedb_" + Digest::MD5.hexdigest(@path.join(",")`
