### ISSUE TITLE
Travis Build failing for 5.0

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5625]
Commit https://github.com/elastic/logstash/commit/1ed6b76b4d1404a2948682523c5584078adb0831 broke the 5.0 build: 
https://travis-ci.org/elastic/logstash/builds/142557377

**Comment by jsvd** [comment]
Travis is again green as a cucumber 
<img width="947" alt="screen shot 2016-07-19 at 08 58 36" src="https://cloud.githubusercontent.com/assets/31809/16942626/029c37ec-4d8f-11e6-94de-0748f7933740.png">
