### ISSUE TITLE
Unable to determine whether development dependencies have been installed

### ISSUE THREAD

**Issue by joshuaspence** [elastic/logstash#5633]
The `logstash-plugin` command can be used to install plugins (with `logstash-plugin install ${NAME}`) and also to check whether a plugin has been installed (with `logstash-plugin list ${NAME}`). The `logstash-plugin` command can also be used to install development dependencies (with `logstash-plugin install --development`), however I am unable to use `logstash-plugin list --development` in order to check whether the development dependencies have been installed. Is there some other way that I can check whether the development dependencies have been installed? For additional context, see elastic/puppet-logstash#292.

**Comment by purbon** [comment]
@joshuaspence the situation here is complex I think, for one side we added the `--development` flag to make sure all development dependencies for test are being installed, mainly for the logstash developer who is actually running the tests.

`logstash-plugin list` main task is to list plugins, not it's dependencies, so it should be expected it can not list them.

The only way to check for development dependencies to be installed is either the stdout message you will get or by parsing the Gemfile.lock generated after the installation.

on the other side, to actually run your test, I do not recommend using rspec for this task. checking for configuration it might be better done in integration fashion maner, thinking about LS as a black box.

closing this issue for now, happy to reopen.

**Comment by joshuaspence** [comment]
So there are no plans to fix this? Recommend treating Logstash as a black box, I really don't know how to go about implementing that. There is some similar discussions in #6479, but it doesn't seem like anyone has a solution.
