### ISSUE TITLE
NotImplementedError: stat.st_dev unsupported or native support failed to load dev_major at org/jruby/RubyFileStat.java:205

### ISSUE THREAD

**Issue by zhangyq1011** [elastic/logstash#5634]
[root@huaqindev logstash]# ./bin/logstash -f  conf.d/logstash_agent_nginx.conf

Settings: Default pipeline workers: 32
NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:205
       nix_inode at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:28
           inode at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:32
           inode at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:106
           watch at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:96
  _discover_file at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:313
            each at org/jruby/RubyArray.java:1613
            each at org/jruby/RubyEnumerator.java:274
  _discover_file at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:304
           watch at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:95
            call at org/jruby/RubyProc.java:281
    synchronized at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:357
     synchronize at org/jruby/ext/thread/Mutex.java:149
    synchronized at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:357
           watch at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:92
            tail at /opt/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/tail_base.rb:73
            tail at /opt/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
   begin_tailing at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-file-2.2.5/lib/logstash/inputs/file.rb:288
            each at org/jruby/RubyArray.java:1613
   begin_tailing at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-file-2.2.5/lib/logstash/inputs/file.rb:288
             run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-file-2.2.5/lib/logstash/inputs/file.rb:292
     inputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:342
     start_input at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:336

 

- Version:logstash 2.3.4
- Operating System:Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013
- Config File (if you have sensitive info, please remove it):
	
logstash_agent_nginx.conf
		input {
			file {
					type => "nginx_access"
					path => ["/var/log/nginx/access.log"]
					start_position => "beginning"  
			}
		}
		output {
			if [type] == "nginx_access" {
				redis {
						host => "192.168.1.85"
						data_type => "list"
						key => "logstash:nginx:redis"
				}
			}
		}
- Sample Data:
- Steps to Reproduce:

Thanks

**Comment by suyograo** [comment]
Dup of https://github.com/elastic/logstash/issues/3127

@zhangyq1011 see solution here: https://github.com/elastic/logstash/issues/3127#issuecomment-101068714

**Comment by zhangyq1011** [comment]
OS:
CentOS release 6.5 (Final)
Operating System:Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013
Java：
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

Without that Lib libc6-dev.No help to me. Still  Thank you.

**Comment by zhangyq1011** [comment]
Distributor ID:	CentOS
Description:	CentOS release 6.6 (Final)
Release:	6.6
Codename:	Final
Error messages no longer appear.

**Comment by sikadiamond** [comment]
same issue here
Ubuntu 14.04 
logstash 2.3.4
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
