### ISSUE TITLE
Persistence Design

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#5636]
This issue explains the Logstash persistence design that will be introduced in 5.x. Thanks to design sessions with @bleskes and @guyboertje, we decided to reuse persistence/resiliency concepts from Elasticsearch such as the sequencing, translog and checkpointing strategies. Currently the implementation is all in Java and can be found in the `feature/java_persistence` branch.

Note that from a Logstash perspective, `Event` objects will ultimately be persisted but from this Queue implementation perspective, we use the _Element_ naming which is more generic since any object which implement our `Queuable` interface can be queued/persisted.
### Sequence Number

First for this new design to work, a queue-wide unique and incrementing **sequence number** will be assigned to each Element at queue write/push operation and this sequence number will be used internally by the queue for its internal state tracking.
### Batch Object

A Batch object is also introduced that keeps track of all read/pop’ed elements and is responsible to handle acking and rejection when all processing over the elements batch is completed. all queue read/pop operation returns a batch object. 

Note that for the first iteration we decided to always return batches of elements within the same page which simplifies the design. The tradeoff is that _small_ batches may be produced when reaching the end of each fixed-sized data file.
### Pages, Data Files and Checkpoints

The basic architecture consist of in-memory Page objects with their associated checkpoint files and data files.

![persistence design 2](https://cloud.githubusercontent.com/assets/2010/16636182/81807e5a-43a4-11e6-8c30-6f109194f498.png)

The in-memory Page object keep track of the runtime unread elements with a simple _first unread sequence number_  and acked elements using a bitset for out-of-order acking support. 

Each data file is bounded by size by configuring a global per-page maximum capacity. Data files are append-only and writes can only happen in the head page data file. Once the head page data file fills up, the head page is beheaded and becomes the latest tail page which only consist on creating a new associated checkpoint file using the `checkpoint.{pageNum}` naming and a new empty head page is created with its special checkpoint naming `checkpoint.head`.

A tail page checkpoint file consists of only a few numeric pointers which tracks each page internal state: own page number, the minimum sequence number, the number of elements and the first unacked sequence number. These pointers are sufficient to reconstruct a complete page state when restarting/recovering.

A head page checkpoint file is identical to a tail page checkpoint but also track the first unacked page number, whish is the first page containing unacked elements.

![queue structure](https://cloud.githubusercontent.com/assets/2010/16637013/da4dcf2e-43a9-11e6-8535-105d9c45c86b.png)
##### Append-only Data File Layout

![data file 1](https://cloud.githubusercontent.com/assets/2010/16636323/6e0080f4-43a5-11e6-905c-dc8322eefb34.png)
### Recovery

Upon restart/recovery, first reading the `checkpoint.head` file provides information about the valid range of pages and complete state recovery is done by reading each of the checkpoint files within that range.

The idea behind the checkpoint file is by keeping this file very small, it can be assumed that all write operations on it will be **atomic**. By using this property the checkpoint file becomes our transaction mechanism and updating a checkpoint provides the last known valid state of each page. The sequencing of the checkpoint updates and the data file _fsync’ing_ provides the reliability layer.

The recovery strategy provided by this architecture respects the **at-least-once semantic**. In a crash scenario, the tradeoff of only keeping track of the per-page _first unacked sequence number_ is that previously acked elements but yet untracked in a checkpoint update, will be replayed upon recovery thus potentially producing duplicate elements. All other normal termination scenarios where the pipeline is correctly flushed should not replay duplicate elements.

**Comment by jordansissel** [comment]
@colinsurprenant, @guyboertje, @andrewvc, and I met on Zoom to discuss this stuff. Good stuff!

Additional questions:

* [ ] Should the page data be word-aligned?
* [ ] Should page data be segmented into parts (aligned on predictable boundaries, like 64kb or similar) so that a small corruption won't cause full page loss?
* [ ] In the checkpoint, should we add a byte offset to allow easy seeking to the `first unacked seq num` element?

Todo items:

* [x] Add a checksum on the checkpoint file at the end of the checkpoint file.
* [x] Add some extra data to the page header (page version, logstash version, creation date, etc)
* [ ] Document "beheading" process
