### ISSUE TITLE
Logstash fails to start as service after RPM upgrade

### ISSUE THREAD

**Issue by driegel** [elastic/logstash#5637]
Hi, 

I removed and updated Logstash, using
```
rpm -e logstash
yum install logstash
```

After this, logstash wasn't running anymore as service. The reason: the numerical uid of the logstash user had changed and so logstash couldn't write to the log file anymore. (Because old logfiles had an old numerical uid.)

- Version: 2.3.3 --> 2.3.4
- Operating System: CentOS 7.2

In the file `logstash/pkg/centos/after-install.sh` I would change the following:
```
  chown -R logstash:logstash /usr/share/logstash
- chown logstash /var/log/logstash
+ chown -R logstash /var/log/logstash
  chown logstash:logstash /var/lib/logstash
  chmod 0644 /etc/logrotate.d/logstash
```

Thanks.

**Comment by aarterberry** [comment]
Hi Daniel,

It's Aaron Arterberry, from USA (PNG).  I hope this email finds you well.  I am interested to know what you have been up to for the past 3 years?  Still involved with PNG and/or any mission work?  We returned to the US in 2013 because our youngest son at the time had a medical condition that forced our return.  We would like to go back in some capacity and are waiting on the Lord.

Do you keep in contact with Norbert?  I would be interested in checking on him, too.

My email address is aarterberry@gmail.com

Blessings to you, friend,
Aaron Arterberry

**Comment by untergeek** [comment]
Non-topical comments have been deleted.

**Comment by aarterberry** [comment]
Daniel, I have a comment about this event.  Please email me at aarterberry@gmail.com

**Comment by untergeek** [comment]
@aarterberry This is not a public forum, but a place to report bugs and software issues.  It is not a place for interpersonal communications.  Please refrain from requesting contact from other contributors, even if you know them, and they know you.  This is not the proper place for such.

**Comment by aarterberry** [comment]
I understand and appreciate your comment.  Daniel is a dear long-lost friend of whom I do not have his email address or any contact info.  Any way I can get hold of him or pass him my info I would be very grateful.  (understand you will delete this too, just need help!)

**Comment by untergeek** [comment]
@aarterberry He will have received the messages in his inbox, more than likely.

**Comment by suyograo** [comment]
@driegel thanks for the bug and proposed change.. Would you be able to do a Pull Request for this?

**Comment by driegel** [comment]
@suyograo Well, there is my first patch ;-) Please check if you could also add the 2.3 and 2.4 labels.

More generic, yesterday I had a very similar problem with missing kibana users. (https://github.com/elastic/kibana/issues/7937). It seams, that user accounts are deleted and recreated unter circumstances still unknown to me and that causes EACCES errors.

**Comment by driegel** [comment]
Here is the patch against the master repo:
https://github.com/elastic/logstash/pull/5737

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5737
