### ISSUE TITLE
Docs reference spooler codec, but there's no repo

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#5643]
We have a doc page for https://www.elastic.co/guide/en/logstash/current/plugins-codecs-spool.html, but https://github.com/logstash-plugins/logstash-codec-spool/ doesn't exist?

Raised [here](https://discuss.elastic.co/t/url-for-2-3-2-logstash-codec-for-spool-goes-to-404/55678).

**Comment by jordansissel** [comment]
We should remove these references. Thanks! <3

**Comment by suyograo** [comment]
Let's remove from the index
