### ISSUE TITLE
Updates to Kafka compatibility matrix

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5645]
Following some feedback around the Kafka comp matrix:
- [x] Add 'features' column (i.e. auth/SSL were introduced in 0.9) to Kafka compatibility matrix both for Kafka [input](https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-kafka.html) and output plugins.
- [x] We can probably remove either the Kafka broker or Kafka client version column. I think keeping the Kafka client version makes sense as it's what we bundle. The 'note' directly below can be augmented to say, in whole: "It's recommended to use the same Kafka client version with its respective Kafka broker version. During upgrades, brokers should be upgraded before clients as brokers target backwards compatibility. For example, the 0.9 broker is compatible with both the 0.8 and 0.9 consumer/producer APIs, but not the other way around."

**Comment by dedemorton** [comment]
@acchen97 Can you add more detail here about what the features column should contain for each version? I'm not sure what you want me to add. Thanks!

**Comment by acchen97** [comment]
@dedemorton thanks for following up! The features column will include the security features for now. In the 0.9 and 0.10 rows, we have Basic Auth and SSL/TLS. Just a heads up, we do plan to add Kerberos auth in the near future as well. Hoping this stuff will fit okay horizontally on the page.

Regarding removing either the Kafka broker or client, I'm +1 on removing the Kafka broker as that's on the client side. @suyograo let me know if that works for you.

**Comment by dedemorton** [comment]
@acchen97 Sorry about the delay in responding. I'll attach a screen capture of the built doc here so you can see what it looks like before I start adding it to the Ruby source code. Is this what you're looking for? Unfortunately, I don't have any control over column width or cell padding:

![kafkacompat](https://cloud.githubusercontent.com/assets/14206422/17914052/cc270a76-6953-11e6-925d-1983083d4cfe.png)

**Comment by acchen97** [comment]
@dedemorton looks like it fits just fine. :) Can you actually change "Features" to "Security Features" for clarity? We can make it more broad in the future if we decide to list other features; then LGTM.

**Comment by dedemorton** [comment]
Note that I also manually modified the asciidoc in the logstash-docs repo so that these changes get into the docs right away (just in case there is any delay while we wait on the new doc gen process).
