### ISSUE TITLE
@timestamp different format between 2.3.x and 1.4.2

### ISSUE THREAD

**Issue by AGirin** [elastic/logstash#5654]
- Version: 2.3.4 and 1.4.2
- Operating System: Centos 6.6

Is there any reason why Logstash 2.3.x displays @timestamp in a different format from 1.4.2?

Example - same config on both servers:

2.3.x: @timestamp: 2016-07-19T20:32:56.905Z
1.4.2: @timestamp: 2016-07-19T15:28:25.053-05:00

Was something changed as far as having default time in 2.3.x in UTC?

Thanks,

Andrew

**Comment by guyboertje** [comment]
I can't remember there being a specific reason.
Ruby versions have, over time, changed the default format of the string representation of the Time class.
In v5 the Timestamp class is an object that generally behaves like a Time object but we control the string representation.
