### ISSUE TITLE
Improve output nomenclature for 'threadsafe' outputs and other types

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#5661]
We now have 'threadsafe' outputs, but this nomenclature is confusing to some. The other types can have threads and work correctly! Perhaps we should change and improve this on the public facing side.

Additionally, we should move to deprecate the worker model (esp. as we move toward https://github.com/elastic/logstash/issues/5653). To that end we should by default mark plugins as only allowing a single worker unless they opt into another strategy.

I propose the following changes.

Replace the class method `Outputs::Base.declare_threadsafe!` with `Outputs::Base.worker_strategy=(strategy)`.

The strategies would be renamed `from->to`:

* `threadsafe->shared`. This indicates that the output can be shared amongst any number of pipeline workers.
* `(default)->single`. Only a single instance of this output can exist. Note that this would mean that most plugins today would no longer support multiple workers. You would need to opt-in rather than out. The effects here need to be discussed.
* `legacy_workers`. Multiple workers are supported, but its clear that this is deprecated. 

So, a plugin might look like the following:

```ruby
class MyOutput < LogStash::Outputs::Base
  worker_strategy :shared #default is :single
end
```

If no strategy is declared then `single` would be assumed as the default value.

**Comment by suyograo** [comment]
I like `threadsafe->shared`

> legacy_workers. Multiple workers are supported, but its clear that this is deprecated

Whats the purpose of this?

**Comment by talevy** [comment]
maybe allude to the fact that the plugin instance is used as is, across worker threads... or cloned/copied into each thread

**Comment by untergeek** [comment]
```ruby
class MyOutput < LogStash::Outputs::Base
  worker_strategy :not_broken_if_there_are_many_outputs #default is :single
end
```

😆 

All things honestly considered, I like the naming plan put forward by @andrewvc.  Whatever we name it, someone will be upset by it and find it unclear to them, so the simplest naming–as put forth–seems better than anything I could come up with.  I agree with @talevy that we should document what each does as well as we can, to help explain more clearly to those who don't initially "get" what the names mean.

**Comment by andrewvc** [comment]
@suyograo there may be plugins out there that we need to give worker support to without a full 'shared' refactor. Do you think it's worth it?

**Comment by jordansissel** [comment]
+1 on renaming "threadsafe" to calling it a "shared worker strategy"

**Comment by jordansissel** [comment]
@andrewvc what strategy (legacy? single?) will provide today's behavior (output workers > 1) ?

**Comment by andrewvc** [comment]
@jordansissel legacy_workers is today's behavior

The rationale here is that for your average plugin author they probably want 'single' as a default because most outputs involve IO and most programmers don't know how to write concurrent code.

Most logstash plugins will likely move over to the 'shared' setting ASAP. Once that happens we can completely remove the `legacy_worker` option in favor of `shared`/`single` for all outputs. We will want to tag existing plugins as `legacy_worker`for the 5.0 release so that users who depend on that behavior will still have it. It will be removed in 6.0.

**Comment by andrewvc** [comment]
I'm realizing now that this is called `worker_strategy`, but the entire point here is to eliminate workers. That doesn't make much sense. How bout we rename it all to just be `concurrency`? The pseudocode would be:

```ruby
class MyOutput < LogStash::Outputs::Base
  concurrency :shared #default is :single
end
```

**Comment by andrewvc** [comment]
Per an offline discussion with @suyograo and @jordansissel we'll be going with `concurrency`
