### ISSUE TITLE
Logstash 5.0 Alpha 4 & mutate filter error

### ISSUE THREAD

**Issue by tcaudrey** [elastic/logstash#5678]
Hi - I have simple .csv input files and a Logstash config that worked fine with Logstash 2.3.x, but when trying to use the same input files and config file in Logstash 5.0.0 alpha 4 produces the following error and crashes the pipeline:

`An unexpected error occurred! {:error=>#<NoMethodError: undefined methodeventget' for #>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.0.1/lib/logstash/filters/mutate.rb:390:in split'", "org/jruby/RubyHash.java:1342:ineach'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.0.1/lib/logstash/filters/mutate.rb:389:in split'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.0.1/lib/logstash/filters/mutate.rb:226:infilter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:155:in multi_filter'", "org/jruby/RubyArray.java:1613:ineach'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:152:in multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:42:inmulti_filter'", "(eval):164:in initialize'", "org/jruby/RubyArray.java:1613:ineach'", "(eval):159:in initialize'", "org/jruby/RubyProc.java:281:incall'", "(eval):179:in initialize'", "org/jruby/RubyArray.java:1613:ineach'", "(eval):175:in initialize'", "org/jruby/RubyProc.java:281:incall'", "(eval):123:in filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:287:infilter_batch'", "org/jruby/RubyArray.java:1613:in each'", "org/jruby/RubyEnumerable.java:852:ininject'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:285:in filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:237:inworker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:210:in start_workers'"], :level=>:fatal}`

Issue also posted here:

https://discuss.elastic.co/t/logstash-5-0-alpha-4-csv-input-and-mutate-split-error/55923

- Version: 5.0.0 Alpha 4

- Operating System: CentOS 7.2

- Config File:

```
input {
	file{
		path => [ "/var/log/pmta/powermta07/*.csv" ]
			tags => ["pmta4.0"]
				sincedb_path => "/etc/logstash/db/sincedb-pmtav4-powermta07"
				sincedb_write_interval => "15"
				discover_interval => "15"
				start_position => "beginning"
		}
}

filter {

if "pmta4.0" in [tags] {
  csv {
	columns => [
		"msgtype",
		"timeLogged",
		"timeQueued",
		"orig",
		"rcpt",
		"orcpt",
		"dsnAction",
		"dsnStatus",
		"dsnDiag",
		"dsnMta",
		"bounceCat",
		"srcType",
		"srcMta",
		"dlvType",
		"dlvSourceIp",
		"dlvDestinationIp",
		"dlvEsmtpAvailable",
		"dlvSize",
		"vmta",
		"jobId",
		"envId",
		"queue",
		"vmtaPool"
	]
	add_field => { "domain" => "%{rcpt}" }
	add_field => { "origDomain" => "%{orig}" }
	add_field => { "AccountID" => "%{orig}" }
	add_field => { "dlvPublicIp" => "%{dlvSourceIp}" }
}
	# Check if CSV was parsed correctly
	if [srcType] == "smtp" and "@" in [rcpt] {

	# Set message timestamp using timelogged field
	date {
	match => [ "timeLogged", "YYYY-MM-dd HH:mm:ssZ" ]
	}

	# Re-write fields that we search on to lowercase as we use not_analyzed strings
	mutate {
		lowercase => ["rcpt"]
		lowercase => ["origDomain"]
		lowercase => ["domain"]
	}

	# Split fields to arrays using seperators
	mutate {
	
		split => ["domain" => "@"]

		}
	 }
  }
}

output {
	if "csv-pmta" in [tags] {
		elasticsearch {
			hosts => "192.168.0.231:9200"
			index => "powermta-%{msgtype}-%{+YYYY.MM.dd}"
			document_type => "powermta"
			template => "/etc/logstash/powermta-template.json"
			template_name => "powermta"
			template_overwrite => true
			document_id => "%{@uuid}"
			flush_size => "15000"
		}
	}
	else {
		elasticsearch {
						hosts => "192.169.0.231:9200"
						index => "incomplete-%{+YYYY}"
		}
	}
}
```

- Sample Data: The log file consist of thousands of lines all in the following format:

`d	2016-07-18 12:47:06+0100	2016-07-18 12:47:05+0100	bo-1R8-4D9LK-3KH3KG-C0469@cmp.dotmailer.co.uk	****.******@rsmtenon.com	relayed	2.0.0 (success)	smtp	250 ok 1468842426 qp 4814 server-13.tower-208.messagelabs.com!1468842425!21681222!1 cluster1.eu.messagelabs.com (195.245.230.83)	smtp	sov-dm-droid8 (10.20.101.219)	smtp 172.20.114.14	195.245.230.83	PIPELINING,8BITMIME,STARTTLS	42751	105-114	rsmtenon.com/105-114	dotMailerNeutral9`

- Steps to Reproduce:

Try and process .csv log files containging data in the above format through Logstash 5.0.0. alpha 4 using the config posted above will result in errors as pasted at the top of this report. Removing the following section of the config:

```
mutate {
	
	split => ["domain" => "@"]

	}
```

will stop the errors from occurring. So there is an issue with the split function of the mutate filter.

**Comment by acchen97** [comment]
Fixed with https://github.com/logstash-plugins/logstash-filter-mutate/pull/81.
