### ISSUE TITLE
Logstash Central service restarts whenever we hit "retrying failed action with response code: 429"

### ISSUE THREAD

**Issue by cchiremath** [elastic/logstash#5689]
Hi team,
we see that whenever one of the data node is facing the issue we get "retrying failed action with response code: 429" . At this moment though we are having rest 13 data nodes active we see that logstash central service is going down.

logs from central:
{:timestamp=>"2016-07-21T16:44:06.888000+0000", :message=>"Got error to send bulk of actions: [504] <html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n", :level=>:error}
{:timestamp=>"2016-07-21T16:44:06.888000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>10, :exception=>"Elasticsearch::Transport::Transport::Errors::GatewayTimeout", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:135:in `__raise_transport_error'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:104:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:542:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:541:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:566:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:565:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
{:timestamp=>"2016-07-21T16:44:16.325000+0000", :message=>"retrying failed action with response code: 429", :level=>:warn}
{:timestamp=>"2016-07-21T16:44:16.326000+0000", :message=>"retrying failed action with response code: 429", :level=>:warn}
{:timestamp=>"2016-07-21T16:44:16.605000+0000", :message=>"retrying failed action with response code: 429", :level=>:warn}

Logs from /var/log/messages:
Jul 18 17:49:30 localhost haproxy[27349]: Server http_proxy/es-data-04 is DOWN, reason: Layer7 timeout, check duration: 5001ms. 13 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Jul 18 17:49:30 localhost haproxy[27349]: Server http_proxy/es-data-04 is DOWN, reason: Layer7 timeout, check duration: 5001ms. 13 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Jul 18 17:49:42 localhost haproxy[27349]: 192.168.90.229:51027 [18/Jul/2016:17:49:22.130] http_proxy http_proxy/es-data-02 0/0/1/-1/20002 504 194 - - sH-- 1/1/1/0/0 0/0 "POST /_bulk HTTP/1.1"
Jul 18 17:49:42 localhost haproxy[27349]: 192.168.90.229:51029 [18/Jul/2016:17:49:22.134] http_proxy http_proxy/es-data-03 0/0/1/-1/20001 504 194 - - sH-- 0/0/0/0/0 0/0 "POST /_bulk HTTP/1.1"
Jul 18 17:49:57 logbroker-04-internal monit[24248]: 'logstash-central-huron-log-2' process is not running
Jul 18 17:49:57 logbroker-04-internal monit[24248]: 'logstash-central-huron-log-2' trying to restart
Jul 18 17:49:57 logbroker-04-internal monit[24248]: 'logstash-central-huron-log-2' start: /etc/init.d/logstash-central-huron-log-2
Jul 18 17:49:57 logbroker-04-internal monit[24248]: 'logstash-central-huron-log-1' process is not running
Jul 18 17:49:57 logbroker-04-internal monit[24248]: 'logstash-central-huron-log-1' trying to restart
Jul 18 17:49:57 logbroker-04-internal monit[24248]: 'logstash-central-huron-log-1' start: /etc/init.d/logstash-central-huron-log-1

Wondering if this has been observed already ?  Can u please help.

we are using logstash-1.5.4-1 .

regards,
Chandrashekar

**Comment by cchiremath** [comment]
[1953.gz](https://github.com/elastic/logstash/files/390082/1953.gz)
[27272.gz](https://github.com/elastic/logstash/files/390083/27272.gz)
[29441.gz](https://github.com/elastic/logstash/files/390085/29441.gz)
[29480.gz](https://github.com/elastic/logstash/files/390084/29480.gz)

**Comment by cchiremath** [comment]
Attaching the java dumps from the hsperfdata ..appreciate your help to us.

**Comment by untergeek** [comment]
We're not really using Logstash 1.5.4 any more, as you can see.  We're on 2.3.4, and the plugin you're using, logstash-output-elasticsearch, has been upgraded to version 4.1.3, while you are using plugin version 1.0.7.

My most likely solution is to first upgrade Logstash to a more recent version.  The 429 retry error issues have been fixed in subsequent versions.

**Comment by suyograo** [comment]
Please reopen if you see this error in later versions (2.x) of LS
