### ISSUE TITLE
Logstash Stuck at Pipeline Main Started

### ISSUE THREAD

**Issue by DeepakPattnaik** [elastic/logstash#5694]
Hi,
I ran logstash to index an apache log file. It worked. After that I used an application log file. It also worked. Then all of a sudden when I try to re-execute the apache log file, logstash is stuck at 'Pipeline main started'
I tried to increase the LS_heapsize to 2048m.

Please help asap

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
