### ISSUE TITLE
Use Jackson CBOR for event serialization

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#5704]
See #5638

> refactor Event serialization to use JSON/CBOR

See [the conclusion from the Kryo binary experiments](https://github.com/elastic/logstash/issues/5253#issuecomment-222692691)

In all but the the most random of benchmarks Jackson JSON outperformed Kryo. 
Jackson CBOR is mostly Jackson JSON code with the output in binary that conforms to the CBOR standard. In theory the event maps serialized to binary will be deserializable by other Java CBOR implementations because the map contents are standard Java classes.

In Amsterdam Boaz suggested Jackson CBOR which aligned with my thinking in the link above.

**Comment by suyograo** [comment]
Can you please put in some more description?

**Comment by suyograo** [comment]
Fixed in #5746
