### ISSUE TITLE
Provide a more detailed list of steps for offline plugin installation

### ISSUE THREAD

**Issue by astefan** [elastic/logstash#5710]
[This section](https://www.elastic.co/guide/en/logstash/current/offline-plugins.html#_building_the_offline_package) of the documentation states the following:

> Move the compressed bundle to the offline machines that are the source for offline plugin installation, then use the bin/logstash-plugin unpack subcommand to make the packaged plugins available.

Can you be more specific about the folder in which this file should be placed and the `unpack` command where should be executed from?

Also, it would be good if the documentation could mention the expected output of running that command (ie. _the content of the file will be unpacked under `/vendor/cache` folder).

**Comment by dedemorton** [comment]
Closing because the new offline plugin install instructions contain steps that are more detailed.
