### ISSUE TITLE
Dependency conflict when installing logstash-output-jira re httparty versions.

### ISSUE THREAD

**Issue by vk126y** [elastic/logstash#5719]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: logstash-2.3.4
- Operating System: Microsoft Windows 8.1 Enterprise 6.3.9600 N/A Build 9600
- Java version : java version "1.7.0_65"
Java(TM) SE Runtime Environment (build 1.7.0_65-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode) 
- Config File (if you have sensitive info, please remove it): NO changes in file I am only installing JIRA plugin
- Sample Data: N/A
- Steps to Reproduce:
Dowload latest logstas-2.3.4 from the Elastic website
Executing bin\logstash-plugin install logstash-output-jira
Got the below Error : io/console not supported; tty will not be manipulated
Validating logstash-output-jira
Installing logstash-output-jira
Plugin version conflict, aborting
**ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "httparty":**
  In snapshot (Gemfile.lock):
    httparty (= 0.13.7)

  In Gemfile:
    logstash-output-hipchat (>= 0) java depends on
      hipchat (>= 0) java depends on
        httparty (>= 0) java

    logstash-output-jira (>= 0) java depends on
      jiralicious (= 0.2.2) java depends on
        httparty (< 0.12.0, >= 0.10) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.3.4)

  In Gemfile:
    logstash-core-plugin-api (= 1.20.0) java depends on
      logstash-core (<= 2.3.4, >= 2.0.0) java

    logstash-output-zeromq (>= 0) java depends on
      logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-zeromq (>= 0) java depends on
      logstash-mixin-zeromq (>= 2.0.0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-output-jira (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (= 2.3.4) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-output-jira (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-output-jira (>= 0) java', in any of the sources.

E:\Code_Athon\Setups\logstash-2.3.4\logstash-2.3.4\bin>gem install bundler
'gem' is not recognized as an internal or external command,
operable program or batch file.

**Comment by vk126y** [comment]
I was able to run logstash successfully at my system and want to configure this further for raising the JIRA calls and following the guidelines mentioned on https://www.elastic.co/guide/en/logstash/current/plugins-outputs-jira.html

But unfortunately getting the errors for the same and this happening for logstash-2.3.3 and logstash-2.3.4 both.

Any help will be appreciated.

Regards
Vinay Kumar

**Comment by purbon** [comment]
I confirm this issue, it basically needs to get this dependencies to be happy with each other:

```
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "httparty":
  In snapshot (Gemfile.lock):
    httparty (= 0.13.7)

  In Gemfile:
    logstash-output-hipchat (>= 0) java depends on
      hipchat (>= 0) java depends on
        httparty (>= 0) java

    logstash-output-jira (>= 0) java depends on
      jiralicious (= 0.2.2) java depends on
        httparty (< 0.12.0, >= 0.10) java
```

we bundle LS with the hipchat output plugin that sets the httparty dependency in a contradictory way with what the jira output needs.

One possible solution, for you now is if you don't need the hipchat output, remove it, then the logstash-output-jira installation will work, see

```
skywalker% ./bin/plugin uninstall logstash-output-hipchat
The use of bin/plugin is deprecated and will be removed in a feature release. Please use bin/logstash-plugin.
Uninstalling logstash-output-hipchat
skywalker% ./bin/plugin install logstash-output-jira     
The use of bin/plugin is deprecated and will be removed in a feature release. Please use bin/logstash-plugin.
Validating logstash-output-jira
Installing logstash-output-jira
Installation successful
skywalker% 
```

**Comment by vk126y** [comment]
While un-installing hipchat i got the below message : 
**ERROR**: Uninstall Aborted, message: This plugin has not been previously installed, aborting

But thereafter I again tried the command ### logstash-plugin install logstash-output-jira

And it worked for me , Hurray !! 
Really happy with your quick response and I love being the part of ELK team , i mean learning this stack is amazing.

Kindly close the case.

Thanks & Regards
Vinay Kumar
