### ISSUE TITLE
Offline plugin install with --no-verify still tries to reach https://rubygems.com

### ISSUE THREAD

**Issue by 3ygun** [elastic/logstash#5721]
The same issue talked about at the end of #4189 is present in Logstash 2.3.3
## Description --> I preform:
1. `bin/logstash-plugin install logstash-filter-prune` on a VM with internet
2. `bin/logstash-plugin pack`
3. `scp` to the offline machine
4. `bin/logstash-plugin unpack` which tells me to then use `--local` to install the unpacked plugins
5. `bin/logstash-plugin install --local logstash-filter-prune` resulting in the screenshot bellow:

![logstash-plugin failure](https://cloud.githubusercontent.com/assets/5482320/17338267/8f24ae6c-589b-11e6-9ceb-86a0b4a98251.PNG)

_Notice: it runs for >3 minutes before giving the first error (set `export HTTP_PROXY=http://127.0.0.1:3128` to make it appear faster)_
## Reality

`prune` **is** installed (`prune` is in `bin/logstash-plugin list`) and works correctly despite the **install error** but there error is confusing :confused:  
## Test:
- Input:  `{"foo":"foo","test":{"bar":1}}`
- Expected Output: `{"test":{"bar":1}}`
- Logstash .conf file:

```
input {
  stdin {
    codec => json
  }
}

filter {
  prune {
    whitelist_names => [ "test" ]
  }
}

output {
  stdout { codec => rubydebug { metadata => true } }
}
```

Other info:
- Version: Logstash 2.3.3
- Operating System: Ubuntu 16.4

**Comment by jordansissel** [comment]
I tested this with Logstash 5.0.0-alpha4 with a dead network, and it worked for me.

I tested in a docker container and used the following iptables rule to kill the network for docker:

```
sudo iptables -I DOCKER -j DROP
```

I verified that prior to that rule, I could ping google, but after, I cannot ping anything. 

<details>
<summary>Preparing the offline pack</summary>

```
root@6fe3961a8004:/opt/x# bin/logstash-plugin install logstash-output-gelf
Validating logstash-output-gelf
Installing logstash-output-gelf
Installation successful
root@6fe3961a8004:/opt/x# bin/logstash-plugin pack
Packaging plugins for offline usage
Generated at /opt/x/plugins_package.tar.gz
```
</details>

<details><summary>Unpacking</summary>

```
root@6fe3961a8004:/opt/1# bin/logstash-plugin unpack ../x/plugins_package.tar.gz
Unpacking ../x/plugins_package.tar.gz
Unpacked at /opt/1/vendor/cache
The unpacked plugins can now be installed in local-only mode using bin/logstash-plugin install --local [plugin name]
```
</details>

<details><summary>Installing from offline</summary>

```
root@6fe3961a8004:/opt/1# bin/logstash-plugin unpack ../x/plugins_package.tar.gz
Unpacking ../x/plugins_package.tar.gz
Unpacked at /opt/1/vendor/cache
The unpacked plugins can now be installed in local-only mode using bin/logstash-plugin install --local [plugin name]
root@6fe3961a8004:/opt/1# bin/logstash-plugin install --local logstash-output-gelf
Installing logstash-output-gelf
Installation successful
```
</details>

**Comment by ph** [comment]
We have seen some issue that the install flow was triggering an internet call, 5.2.0 will include a new offline flow that remove the need to use `--local` and uses a new strategy for installation.

more details in #6404

**Comment by 3ygun** [comment]
Thanks for the update @ph!
