### ISSUE TITLE
logstash 5.0 bundle/jruby issue. 

### ISSUE THREAD

**Issue by DreadPirateRob** [elastic/logstash#5723]
I got logstash and the remainder of ELK via yum. All via the repos, all version 5.0

Funny story, when I tried this command: 
```
[root@logstash]# /usr/share/logstash/vendor/bundle/jruby/1.9/bin/bundle update
```

I got this output: 
```
-bash: bundle/jruby/1.9/bin/bundle: /home/jenkins/workspace/logstash_create_rpm_artifact_50/jdk/JDK8/label/metal-p: bad interpreter: No such file or directory
```

looks like jenkins didn't clean up something. I haven't checked to see if this is messing up other things, but I'm going to assume so.

**Comment by andrewvc** [comment]
@DreadPirateRob why are you running bundle update? The normal method of updating plugins is `logstash-plugin update`

**Comment by DreadPirateRob** [comment]
Trying to install a plugin and it's erroring out, `bundle update` was a
suggesting I found via Google search

*Sent via mobile.

**Comment by andrewvc** [comment]
@DreadPirateRob I would definitely try it via `logstash-plugin` let us know if that fixes it.

**Comment by DreadPirateRob** [comment]
No. `logstash-plugin install logstash-email-outout` does not work.

*Sent via mobile.

**Comment by DreadPirateRob** [comment]
done it a few times on fresh VMs (centos 6.7 and 6.8). Still not able to install this plugin. I made a forum question on it. here's the link. 

https://discuss.elastic.co/t/5-0alpha-logstash-output-email/57013

**Comment by andrewvc** [comment]
Closing this in favor of he discuss discussion ^^
