### ISSUE TITLE
Unable to send emails from logstash.

### ISSUE THREAD

**Issue by vk126y** [elastic/logstash#5725]
- Version: **logstash2.3.4**
- Operating System:Microsoft Windows 8.1 Enterprise 6.3.9600 N/A Build 9600
-Java version : java version "1.7.0_65" Java(TM) SE Runtime Environment (build 1.7.0_65-b19) Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
- Config File (if you have sensitive info, please remove it): **Please refer sample data section**
- Sample Data: I am attaching all the configurations I have tried various configuration settings for email but no setting is working our for me. PFA file Sendloginconfiguration.txt for 1 sample configuration
PFA file user_scenarios.txt for all other sample configurations and errors we are getting.
- Steps to Reproduce: 

1. Create a logstash configuration file after configuring e-mail options
2. Start the logstash to read the logs 
3. Logstash will read the logs as expected and do apply the GROK as well , no issues till this point.
4. Try sending e-mail on all the events , I have not used any IF constraints to restrict e-mail delivery, as I am at very beginning level

[user_scenarios.txt](https://github.com/elastic/logstash/files/399096/user_scenarios.txt)
[Sendloginconfiguration.txt](https://github.com/elastic/logstash/files/399098/Sendloginconfiguration.txt)

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
