### ISSUE TITLE
Unable to update plugin

### ISSUE THREAD

**Issue by AGirin** [elastic/logstash#5727]
- Version: 2.3.4
- Operating System: CentOS 6.6

We are trying to update plugin and getting this:

You are updating logstash-filter-throttle to a new version 4.0.0, which may not be compatible with 2.0.4. are you sure you want to proceed (Y/N)?
Y
Updating logstash-filter-throttle
No plugin updated

No matter what we do we cannot update that plugin. What are we missing or this is a bug?

Thanks!

Andrew

**Comment by suyograo** [comment]
Dup of https://github.com/elastic/logstash/issues/5580
