### ISSUE TITLE
Set default log level to info

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5735]
Elasticsearch does this, so we must as well.

**Comment by suyograo** [comment]
We will not be able to do this for 5.0. There are way too many log lines being warned at `info` level in LS startup, which should actually be at `debug` or even `trace`. This needs a thorough audit and cleanup before we can default to `info` severity.

**Comment by jordansissel** [comment]
++

**Comment by suyograo** [comment]
@jordansissel actually @talevy and @jsvd just reviewed the log lines and we were able to set most of them to debug.
