### ISSUE TITLE
Host name '127.0.0.1' does not match the certificate subject provided by the peer (CN=localhost)

### ISSUE THREAD

**Issue by bujarmetaj2016** [elastic/logstash#5745]
hi, 
i am getting this:

Host name '127.0.0.1' does not match the certificate subject provided by the peer (CN=localhost)

Any ideas how to fix it ?

Many thanks

Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by jordansissel** [comment]
This sounds like a configuration issue. Can you as this on https://discuss.elastic.co/ instead?
