### ISSUE TITLE
Plugin docs infra enhancements

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#5762]
Couple more items discussed for the plugin docs infra; these will help enable the plugin doc template enhancements (https://github.com/elastic/logstash/issues/5148).

- [x] Logstash core compatibility for a plugin version, i.e. new set of plugins will work on Logstash 2.4 - 5.
- [x] Add version release date
- [x] Add link to changelog

These items build atop the changes here https://github.com/elastic/logstash/pull/5720.

**Comment by ph** [comment]
I am doing a bit more tests  to make sure the compatible version make sense.

**Comment by suyograo** [comment]
Will be fixed in #5720
