### ISSUE TITLE
Document the default log level

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/logstash#5783]
The revamped command-line and settings file documentation (#5713) details the `log.level` flag and setting but doesn't state the default. See https://discuss.elastic.co/t/logstash-log-option/58178.

Since it seems we're changing the default log level in 5.0 (see #5735) perhaps there's a point in trying to display the default level in any remaining 2.x releases so that it's easier to discover the change.

**Comment by ph** [comment]
This is now documented at https://github.com/elastic/logstash/blob/master/docs/static/settings-file.asciidoc
