### ISSUE TITLE
logstash-plugins/logstash-output-loggly doesnt seem to be maintained any more

### ISSUE THREAD

**Issue by Vincent--** [elastic/logstash#5784]
See https://github.com/logstash-plugins/logstash-output-loggly

Last commit was on 20th of April and some PR are waiting since April.
See https://github.com/logstash-plugins/logstash-output-loggly/issues/14
Can someone have a look? Thanks in advance.

Regards,
Vincent

**Comment by suyograo** [comment]
@Vincent-- the loggly output is community maintained, and I've asked the community for specific maintainers to help us with PRs/issues. https://github.com/logstash-plugins/logstash-output-loggly/issues/20
