### ISSUE TITLE
Bug when date match

### ISSUE THREAD

**Issue by AndreyKiryliuk** [elastic/logstash#5787]
when you try to convert a date, I receive an error:
from 2016-07-10 02:48:53,927
i recieve 2016-01-10T02:48:00.927Z

- Version: 
/opt/logstash/bin/logstash --version
logstash 2.3.4
- Operating System:
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:   	Ubuntu 14.04.5 LTS
Release:       	14.04
Codename:      	trusty
uname -a
Linux kvmde18-9286.fornex.org 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Config File (if you have sensitive info, please remove it):
    date {
      match => [ "timestamp" , "YYYY-MM-DD HH:mm:ss,SSS" ]
      timezone => "UTC"
      target => "tt"
    }
- Sample Data:
2016-07-10 02:48:53,927
- Steps to Reproduce:
in kibana i am view:
timestamp:2016-07-10 02:48:53,927
tt:2016-01-10T02:48:53.927Z

**Comment by magnusbaeck** [comment]
Your date pattern should be "YYYY-MM-dd HH:mm:ss,SSS", not "YYYY-MM-DD HH:mm:ss,SSS".

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
