### ISSUE TITLE
Issue in parsing the file which has # character at the beginning of the line

### ISSUE THREAD

**Issue by bkamesh88** [elastic/logstash#5796]
Hi All, 

I am new to logstash and recently started scripiting in logstash. we have a requirement where some logs files have # in the beginning of the line. Say
####&lt;Aug 11, 2016 11:40:53 AM CDT> &lt;Info> &lt;Security> &lt;HostName> 
####&lt;Aug 11, 2016 11:40:54 AM CDT> &lt;Info> &lt;Security> &lt;HostName> 
now, I want to parse each line separately if it has #### in the beginning, but i tried couple of scripts and all are failing with ""Expected one of #, input, filter, output at line 28, column 1 (byte 302) after ", :level=>:error}" error: 

Scripts i used: 

1:
input
{
  file
     {
        path => "/tmp/testXML1.log"
        codec => plain { charset => "US-ASCII"}
        type => "OSBLog"
     }
}
output {
  elasticsearch {
    hosts => ["192.168.99.100:9200"]
    codec => plain {charset => "US-ASCII"}
   }
  stdout { codec => rubydebug }
}
2:
input
{
  file
     {
        path => "/tmp/testXML1.log"
        codec => multiline
       {
       pattern => "^/####"
       }
        type => "OSBLog"
     }
}
output {
  elasticsearch {
    hosts => ["192.168.99.100:9200"]
   }
  stdout { codec => rubydebug }
}

Any help will be highly appreciated.

**Comment by magnusbaeck** [comment]
This is a support question that's better asked at discuss.elastic.co, which the OP indeed has done: https://discuss.elastic.co/t/issue-in-parsing-the-file-which-has-character-at-the-beginning-of-the-line/58486
