### ISSUE TITLE
run logstash 2.3.4 get the following error:

### ISSUE THREAD

**Issue by gitqizong** [elastic/logstash#5814]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:
- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by gitqizong** [comment]
io/console not supported; tty will not be manipulated
Settings: Default pipeline workers: 2
NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:205
       nix_inode at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:28
           inode at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:32
           inode at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:106
           watch at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:96
  _discover_file at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:313
            each at org/jruby/RubyArray.java:1613
            each at org/jruby/RubyEnumerator.java:274
  _discover_file at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:304
           watch at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:95
            call at org/jruby/RubyProc.java:281
    synchronized at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:357
     synchronize at org/jruby/ext/thread/Mutex.java:149
    synchronized at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:357
           watch at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/watch.rb:92
            tail at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/filewatch-0.8.1/lib/filewatch/tail_base.rb:73
            tail at /opt/logstash-2.3.4/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
   begin_tailing at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-input-file-2.2.5/lib/logstash/inputs/file.rb:288
            each at org/jruby/RubyArray.java:1613
   begin_tailing at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-input-file-2.2.5/lib/logstash/inputs/file.rb:288
             run at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-input-file-2.2.5/lib/logstash/inputs/file.rb:292
     inputworker at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:342
     start_input at /opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:336

Java -version:
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (IcedTea 3.1.0) (suse-14.3-s390x)
OpenJDK 64-Bit Zero VM (build 25.101-b13, interpreted mode)

OS
SUSE Linux Enterprise Server 12 (s390x)
VERSION = 12
PATCHLEVEL = 1

Tried suggestions from #3127 but still show the same error. Please help Thanks

**Comment by andrewvc** [comment]
When you say you tried suggestions from #3127 do you mean you tried fixing libc6?

**Comment by ph** [comment]
#3127 seems to be solving that case I will close this issue, feel free to create a new one or reopen it.
