### ISSUE TITLE
Option in `bin/logstash-plugin` to find the version of plugin installed in logstash

### ISSUE THREAD

**Issue by sumit-murari** [elastic/logstash#5816]
I was trying to find the version of kafka-input plugin installed in logstash in this [question](http://stackoverflow.com/questions/39114563/get-plugin-version-installed-in-logstash/39114648), is there already a way to find it ?

If not, I was thinking making one such option in `bin/logstash-plugin`, is it a nice idea to work on ?

**Comment by wiibaa** [comment]
`bin/logstash-plugin list --verbose`

I will check if this is documented properly

**Comment by wiibaa** [comment]
Correct command => `bin/logstash-plugin list --verbose logstash-input-kafka`

**Comment by sumit-murari** [comment]
thanks for response :).
I'll update the answer in stackoverflow and close the ticket
