### ISSUE TITLE
Logstash produces no output when input is a simple text file

### ISSUE THREAD

**Issue by haow85** [elastic/logstash#5817]
I'm using logstash-2.3.4. I wrote the following config file simple.conf

input {
	file {
		path => ["/home/es_user/logstash-2.3.4/bin/test.txt"]
		start_position => "beginning"
	} 
}
output {
	file {
		path => ["/home/es_user/logstash-2.3.4/bin/transfered_test.txt"]
	}
	stdout { codec => rubydebug }
}

The test.txt file contains one single line "Hello world."

When I ran ./logstash -f simple.conf I got stuck at "Pipeline main started" . How to fix this ?

**Comment by tomrade** [comment]
how old is the test file?, just check you don't need to use "ignore_older"

**Comment by haow85** [comment]
I set the ignore_older to be a very large value but still have no output.


input {
file {
path => ["/home/es_user/logstash-2.3.4/bin/test.txt"]
start_position => "beginning"
ignore_older => 999999999
}
}
output {
file {
path => ["/home/es_user/logstash-2.3.4/bin/transfered_test.txt"]
}
stdout { codec => rubydebug }
}



________________________________

**Comment by tomrade** [comment]
I was thinking more of setting it to "0" , but that would also have worked.

Couple of things I can thing of
is there a newline after hello world? might be still waiting for event 2?
can the user read/write the files

**Comment by haow85** [comment]
Hi Thomas,


Thank you for your help. After I've appended a newline to the end of the file, logstash started to function normally. Thank you again.


Best Regards,

Hao Wang

________________________________

**Comment by guyboertje** [comment]
Closing

**Comment by arunnaudiyal786** [comment]
Ya appending a newline in the text file also helped me in getting the logstash running .
