### ISSUE TITLE
Stats: change stats reset operation to only clear destroyed pipelined counts

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5818]
Currently, when recreating a pipeline (during configuration reload) all stats are reset and recreated.

For stats like jvm, gc, global event count and others there's no need to reset them.

Therefore, when reloading a pipeline, only the stats from that pipeline should be delete from the metric collector.

This helps support https://github.com/elastic/logstash/issues/5680

**Comment by acchen97** [comment]
Just to clarify, this **only** resets `/_node/stats/pipeline` stats, right? This is just the events/plugin pipeline stats, the remaining API resources will persist across pipeline reloads.

**Comment by jsvd** [comment]
Correct!

**Comment by jsvd** [comment]
resolved by #5819
