### ISSUE TITLE
http.port auto-increment if in use

### ISSUE THREAD

**Issue by ave19** [elastic/logstash#5835]
https://discuss.elastic.co/t/logstash-http-port-auto-increment/57370

For all general issues, please provide the following details for fast resolution:

- Version:  version 5.0.0-alpha4 and up
- Operating System:  Linux 2.6.32-573.12.1.el6.x86_64 #1 SMP 
- Config File (if you have sensitive info, please remove it):  N/A
- Sample Data:   N/A
- Steps to Reproduce:  

1)  Start an instance of logstash.
2)  It opens port 9600 for monitoring.
3)  Start a second instance of logstash on the same machine.
4)  It cannot start because port 9600 is in use.

Feature Request:  Automatically try 9601 and so on until an open port is found.

Thanks

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5774
