### ISSUE TITLE
Does the logstash support the various in the pattern

### ISSUE THREAD

**Issue by LazyerHong** [elastic/logstash#5846]
Can i use the var with pattern in the  logstash. For example:
 multiline {
                        pattern=>"($number)"
                        negate => "false"
                        what => "previous"
                }

the $number is various,   I have tried ,but it doesn't work . Is there another way to solve this problem?

**Comment by guyboertje** [comment]
@LazyerHong 
Is `$number` an environment variable?

**Comment by andrewvc** [comment]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
