### ISSUE TITLE
how to use the multiline plugin?

### ISSUE THREAD

**Issue by LazyerHong** [elastic/logstash#5847]
For example  i have logs here:

1111
2222
3333
1111
2222
3333

now i want to combine the log with the same number just like
11111111
22222222
33333333

how can i do with the multiline???It is very urgent for me now. Thanks!!

**Comment by jordansissel** [comment]
Questions like this will get the best answers if they are written on the [Logstash discussion forums](https://discuss.elastic.co/c/logstash).
