### ISSUE TITLE
I suggest to append some note in Gelf input plugin documentation: only UDP + gzipped message support

### ISSUE THREAD

**Issue by harobed** [elastic/logstash#5849]
Gelf input plugin support only:

* UDP
* gzipped Gelf message

This information isn't in documentation: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-gelf.html

**Comment by jordansissel** [comment]
I agree, though the best place to discuss this is on the gelf input repo: https://github.com/logstash-plugins/logstash-input-gelf

**Comment by harobed** [comment]
Ok thanks it's here: https://github.com/logstash-plugins/logstash-input-gelf/issues/45
