### ISSUE TITLE
Confusing and verbose core test output

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5863]
The logstash core test output is becoming very verbose causing confusion when reading it's outcome, example is:

```ruby
10:12:32.996 [main] FATAL logstash.shutdownwatcher - Forcefully quitting logstash..
.10:12:33.071 [main] ERROR logstash.shutdownwatcher - The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
10:12:33.167 [main] FATAL logstash.shutdownwatcher - Forcefully quitting logstash..
.10:12:33.243 [Ruby-0-Thread-127: /Users/purbon/work/logstash/logstash-core/spec/logstash/shutdown_watcher_spec.rb:71] ERROR logstash.shutdownwatcher - The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
................................................................................................................................................................................................................................................................................................................................10:13:18.085 [[main]-pipeline-manager] ERROR logstash.agent - Unable to reload configuration because it does not support dynamic reloading {:pipeline_id=>"main", :plugins=>[LogStash::Inputs::Stdin]}
...10:13:19.088 [Ruby-0-Thread-405: /Users/purbon/work/logstash/logstash-core/spec/logstash/agent_spec.rb:173] ERROR logstash.agent - Unable to reload configuration because it does not support dynamic reloading {:pipeline_id=>"main", :plugins=>[LogStash::Inputs::Stdin]}
10:13:19.096 [Ruby-0-Thread-405: /Users/purbon/work/logstash/logstash-core/spec/logstash/agent_spec.rb:173] ERROR logstash.agent - Unable to reload configuration because it does not support dynamic reloading {:pipeline_id=>"main", :plugins=>[LogStash::Inputs::Stdin]}
10:13:19.108 [Ruby-0-Thread-405: /Users/purbon/work/logstash/logstash-core/spec/logstash/agent_spec.rb:173] ERROR logstash.agent - Unable to reload configuration because it does not support dynamic reloading {:pipeline_id=>"main", :plugins=>[LogStash::Inputs::Stdin]}
```
More detailed output can be seen at https://gist.github.com/purbon/2d3290f632bda5f899cdb499c0d4c11e

Most of this output is uncontrolled print to stdout that might cause confusion when running the test, are the test properly passing, or not? As a good practice we should prevent printing this kind of messages to stdout as they give no feedback to test readers.

**Comment by talevy** [comment]
this is happening because there is no logger configured in the test environment. I will update devutils to include a log4j properties file in the classpath.

I think logging errors is good, would you prefer all logs to be muted?

**Comment by talevy** [comment]
PR to fix this: https://github.com/elastic/logstash-devutils/pull/60

**Comment by purbon** [comment]
@talevy I think there absolutely no right way to do this for everyone, but in general I tend to think about logging as the communication of a known state to the user, for example:

1. we encounter an exception
2. catch the exception
3. log the statement for user awareness.
4. Decide to raise or mask the exception in the codeflow.

so in test we should not be relying on logging messages as the state should be represented by something else like exceptions, variables, etc.

Another thing is testing the logging communication, so if the system properly communicated a situation to the user, @guyboertje made a while ago a very good proposal on rspec matchers for cabin, might be we can leverage some part now that we changed to log4j2.

So end of the day, I am all in for _mute_ logging messages in test.

What do you think?

**Comment by purbon** [comment]
@talevy @suyograo what makes me think now is if the errors we're seeing make the test unreliable or not? I am, like everytime I see taking a mute action if we are muting meaningful errors. Worst investigating the source of this errors? what do you think?

**Comment by suyograo** [comment]
This has been fixed with devutils
