### ISSUE TITLE
Upgrade from Logstash 2.3.4 to 2.4.0 causes beats input to fail due to PKCS8 error

### ISSUE THREAD

**Issue by alefebvre-ls** [elastic/logstash#5865]
Upon upgrading from 2.3.4 to 2.4.0, i started getting this error due to my beats inputs: 
```
Looks like you either have an invalid key or your private key was not in PKCS8 format.
```

Although the [breaking changes](https://github.com/elastic/logstash/blob/v2.4.0/docs/static/breaking-changes.asciidoc) does not indicate this error would occur with the beats input unless the key is converted to PKCS8 format.  Although I realize this was an issue with the logstash-input-beats plugin and not directly logstash itself, upgrading to logstash 2.4.0 directly caused logstash to upgrade to logstash-input-beats plugin >= 3.1.0, which [introduces the changes](https://github.com/logstash-plugins/logstash-input-beats/blob/master/CHANGELOG.md#311) to how the keys/certs are handled.

I finally found out this was documented on a blog [post](https://www.elastic.co/blog/logstash-2-4-0-released) although this probably should have also been indicated in the breaking changes as it is relatively major considering events were no longer being processed due to this.

**Comment by ph** [comment]
@alefebvre-ls I will update the breaking changes with that note, we mentioned it in the changelog/blost post but didn't do it in the breaking changes.

**Comment by ph** [comment]
On a related note, which version of openssl you are using to generate the keys?
