### ISSUE TITLE
service logstash start fails if its already running

### ISSUE THREAD

**Issue by LeeDr** [elastic/logstash#5872]
- Version: 5.0.0-alpha6 (master)
- Operating System: Ubuntu 14.04
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce: 

1. run `service logstash start` while it's already running
2. check the exit code `echo $?`

The exit code is 1 (error), but for beats, elasticsearch, and kibana they all exit code 0 in this case.

Might be related to https://github.com/elastic/logstash/issues/4817

**Comment by purbon** [comment]
might be related with #4817 as far as with an empty config [1] it does not have this behaviour:

see 

```
root@packer-virtualbox-iso-1452039329:~# sudo service logstash start
start: Job is already running: logstash
root@packer-virtualbox-iso-1452039329:~# sudo service logstash start
start: Job is already running: logstash
root@packer-virtualbox-iso-1452039329:~# echo $?
1
root@packer-virtualbox-iso-1452039329:~# sudo service logstash stop
logstash stop/waiting
root@packer-virtualbox-iso-1452039329:~# sudo service logstash start
logstash start/running, process 13791
root@packer-virtualbox-iso-1452039329:~# sudo service logstash start
start: Job is already running: logstash
root@packer-virtualbox-iso-1452039329:~# echo $?
0
```

first execution is with having elasticsearch as output and without connection to the end elasticsearch, so the backpreasure was kicking in. Second execution is with a basic stdin -> stdout pipeline, so no backpreasure happening.

**Comment by jordansissel** [comment]
@leedr On Ubuntu 14.04, the Logstash package should be installing an upstart job, so `service logstash start` should be invoking upstart and the exit code of that is not up to us.

Can you confirm what service platform (upstart, system, sysv init) is being used? I don't have any Ubuntu 14.04 boxes to test on right now.

**Comment by jordansissel** [comment]
Ahh, I see it is indeed using Upstart.

> start: Job is already running: logstash

^^ the above message comes from Ubuntu's Upstart system, not from Logstash.

I don't think there's anything to change here. If you need to check if Logstash is running, there's a `status` command you can invoke before trying to call `start` on it.

**Comment by suyograo** [comment]
Closing this based on https://github.com/elastic/logstash/issues/5872#issuecomment-250592345

**Comment by LeeDr** [comment]
So all our other products are not installing an upstart job?   I'm not sure how to check that.  And if they're not, should they?  We should file issues to get all the other products to be consistent?

**Comment by jordansissel** [comment]
@LeeDr I don't know what the plan for other products are. For Logstash, we use `pleaserun` to automatically install the best[1]. My feeling is that it is most correct to install Upstart jobs on platforms that use Upstart (CentOS 6, Ubuntu 8.10 through 15.10).

[1] where "best" is determined based on some discovery to see what service platforms are available at install-time.
