### ISSUE TITLE
API: Nearly any URL gives a successful response

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5874]
```
% curl http://192.168.1.124:9600/asfasdf/asdf/asdf/a/sdf
{"host":"localhost.localdomain","version":"5.0.0-alpha6","http_address":"0.0.0.0:9600"}
```

I expected this to fail somehow. It doesn't.

**Comment by ph** [comment]
Yup this a bug, we might have a catch all url somewhere in the sinatra routes.

**Comment by purbon** [comment]
Related to https://github.com/elastic/logstash/issues/5622 ?

**Comment by ph** [comment]
I will close this in favor of #5622, since its the strategy I took to solve that problem.
