### ISSUE TITLE
Plugin Option: Field that support String interpolation /fieldref should be more explicit.

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5877]
In the current documentation, we correctly report when a field is `deprecated` or `required` using the options hash like this.

```ruby
config :name, :type => :string, :required => true
```

But it's not obvious for the user when a field support the `fieldref` syntax unless the developer explicitly wrote a note in the documentation for the option. I suggest we add another **key** to the config option that could be picked up by the documentation generator to add a special mention.

I propose something like this.

```ruby
config :name, :type => :string, :required => true, :fieldref => true
```

**Comment by wiibaa** [comment]
For context old proposal and discussion in https://github.com/elastic/logstash/pull/2269

In particular the hash type is annoying
>  It also may not capture other meanings like if a :validate => :hash supports sprintf in the values, but not the keys, this may be misleading to users.

**Comment by ph** [comment]
I've will close this one, I should have searched for that, hash are a pain.
