### ISSUE TITLE
Discuss required Persistent Queue behaviour when reloading Config.

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#5888]
This is a preliminary discussion aimed to capture what technicalities we should consider when a config is reloaded.

When the config is compatible with the events currently in the queue, e.g.:
- close the queue before reload starts - this is this part of normal pipeline shutdown, but is more needed?
- reopen the queue when the pipeline starts again, this is normal but is more needed?

When the config is incompatible with the events currently in the queue.
- rename current queue folder and start a new queue etc.

**Comment by colinsurprenant** [comment]
closing in favour of #5916
