### ISSUE TITLE
Documentation for logstash-output-webhdfs outdated

### ISSUE THREAD

**Issue by dstore-dbap** [elastic/logstash#5934]
Hi everybody!

I'm the maintainer of the logstash-output-webhdfs.
I noticed that the documentation for the plugin at https://www.elastic.co/guide/en/logstash/current/plugins-outputs-webhdfs.html
is not up to date. This has caused some confusion with some users and lead to a couple 
of open issues on github.
There is even an open issue concerning this problem at https://github.com/logstash-plugins/logstash-output-webhdfs/issues/9.

I contacted purbon via mail who suggested to open an issue here in the logstash-core project.

My question is, what can I do to update the documentation for this plugin so users 
will not have to figure out how this plugin works?
Any idea or hint would be greatly appreciate ;)

@suyograo pinging you here as suggested by Pere ;)

Björn

**Comment by dedemorton** [comment]
The docs in current have the correct options now, so I'm closing this.
