### ISSUE TITLE
LoadError: load error: jruby/java/java_ext/java.lang -- java.lang.reflect.InaccessibleObjectException

### ISSUE THREAD

**Issue by biswajitdas** [elastic/logstash#5942]
Version: Logstash 2.4.0.deb
Operating System: Ubuntu server 16.04
Java : Java jigsaw
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+136-jigsaw-nightly-h5506-20160916)
Java HotSpot(TM) Server VM (build 9-ea+136-jigsaw-nightly-h5506-20160916, mixed mode)

Error

Java HotSpot(TM) Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
Java HotSpot(TM) Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
LoadError: load error: jruby/java/java_ext/java.lang -- java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "exports private java.lang" to unnamed module @16f2a7e
  require at org/jruby/RubyKernel.java:1040
   (root) at file:/opt/logstash/vendor/jruby/lib/jruby.jar!/jruby/java/java_ext.rb:3
  require at org/jruby/RubyKernel.java:1040
   (root) at file:/opt/logstash/vendor/jruby/lib/jruby.jar!/jruby/java.rb:1

**Comment by suyograo** [comment]
@biswajitdas You can't yet use Logstash with Java 9. It has to be Java 8

**Comment by biswajitdas** [comment]
Thanks
