### ISSUE TITLE
A possible alternative to retry_max_items?

### ISSUE THREAD

**Issue by ambodi** [elastic/logstash#5945]
According to the documentations, `retry_max_items` https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-retry_max_items. 

We are facing a serious issue with infinite retries that is causing our servers to go down. Is there any alternatives to that? 

Should we handle it in the code?

**Comment by jordansissel** [comment]
Please open this in the elasticsearch output repo.
