### ISSUE TITLE
Missing logstash-output-webhdfs from all-plugins DEB

### ISSUE THREAD

**Issue by maxtors** [elastic/logstash#5951]
- Version: 2.4.0 (all plugins) / logstash-all-plugins-2.4.0_all.deb
- Operating System: N/A

Downloaded logstash-all-plugins-2.4.0_all.deb from https://www.elastic.co/downloads/logstash. This .DEB does not include the plugins "logstash-output-webhdfs". The text on the download pages says: "Logstash bundled with the latest version of all available plugins at time of release." where "plugins" links to https://github.com/logstash-plugins. Here the webhdfs plugin is listed, but it is as mentioned, not in the all-plugins bundle.

**Comment by maxtors** [comment]
It has been a week since i created this issue. The plugin offline packing functionality / documentation is not exaclty up to speed / directly understandable, and i bet alot of users would like to just continue using logstash after their org has migrated to using HDFS, instead of introducing new software such as Flume, Nifi, etc.

**Comment by jordansissel** [comment]
By the way, with Logtash 5, we no longer ship an "all plugins" artifact.

Is this still a problem for you?
