### ISSUE TITLE
Kafka input plugin not able to parse beats output

### ISSUE THREAD

**Issue by dronadroid** [elastic/logstash#5956]
filebeats version: 5.0
kafka version:  kafka_2.11-0.10.0.1
logstash: 2.4

We have following workflow:
filebeat->kafka->logstash (using kafka input plugin)

Now, logstash when it receives messages from kafka it is not able to understand those messages. Ideally, logstash expects json {"key":"value"} pairs from kafka. However, since these messages are sent by filebeat they have additional metadata like this: "@timestamp":"2016-09-21T07:19:06.394Z","beat":{"hostname":"xyz,"name":"xyz"},"input_type":"log","message":"{\"process_name\": \"OS\", \"event_type\": \"abc\", \"time\": \"2016-09-21T12:49:04.1474442344+0530\"}.

How can we make kafka input plugin understand beats message format ?

**Comment by suyograo** [comment]
Can you paste your entire config here? It should not matter what messages are in Kafka..

**Comment by dronadroid** [comment]
Config is straightforward. I am only printing the stdoutput:
Logstash conf file:
--------------------------------------------------------
input {
   kafka {
        topic_id => test
    }
}
output {
    stdout {
        }
}
------------------------------------------------------------------------

Use kafka to send messages to logstash: 

1. Send message with filebeat metadata i.e they way filebeat would send it (you could start file and see the actual message sent to kafka. Here i am sending a sample filebeat message)
bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
{"hostname":"e2e-14-6","name":"e2e-14-6"},"input_type":"log","message":"{\"event_type\": \"abc_event\", \"host_name\": \"e2e-14-6\", \"time\": \"2016-09-26T14:50:21.1474881621+0530\", \"w\": 0, \"issue\": \"abc_event\", \"user\": \"\", \"process_name\": \"OS\", \"resource_type\": \"process\"}","offset":21435,"source":"/var/log/xyz.log","type":"alert"}

The output on logstash is following:
2016-09-26T09:35:46.247Z %{host} {"event_type": "abc_event", "host_name": "e2e-14-6", "time": "2016-09-26T14:50:21.1474881621+0530", "w": 0, "issue": "abc_event", "user": "", "process_name": "OS", "resource_type": "process"}","offset":21435,"source":"/var/log/xyz.log","type":"alert"}

2.
Now send proper formatted message to kafka with filebeat specific metadata:
Formated message:
{"event_type":"abc_event","host_name":"e2e-14-6","time":"2016-09-26T14:50:21.1474881621+0530","w": 0,"issue":"abc_event","user":"","process_name":"OS","resource_type":"process"}

logstash print:
2016-09-26T09:38:06.245Z %{host} %{message}  << {This is what we should get}

However due to filebeat metadata we dont see %{message} as seen in 1. above

**Comment by jordansissel** [comment]
Your JSON is invalid in `1. Send message with filebeat metadata ...`

The reason you see `%{message]` is because your json from `2. Now send ...` does not have a `message` field.

If there is a problem, I am not seeing it. Can you help me understand what is wrong?

**Comment by Prajotc** [comment]
Hi even i have similar kind of issue. 
from file beat i am dumping data to Kafka. logstash will read kafka data and dump into elastic search 
but logstash could not able to parse data, how i wanted...

filebeat send following JSON to Kafka:

{
"records": [
 {
   "value": {
      "index":"beat",
      "@timestamp":"2018-07-30 13:37:57.376937979 +0000 UTC",
       "src-name":"direct_direct1-1",
       "name":"kafka",
        "node-ip":"node-72-45"
    }
 }, {"value": {
      "index":"beat",
      "@timestamp":"2018-07-30 13:37:57.376937979 +0000 UTC",
      "src-name":"direct_direct1-1",
      "name":"kafka",
     "node-ip":"node-123"
    }
 } ]
} // each value will be one event, it will have many events

so now logstash should dump data to elastic search in following format :+1: 

Table format in elastic search :

 @timestamp	   	August 8th 2018, 13:05:43.000
 _id	   	AWUYiwsbdhYz_anUewI-
 _index	   	beat-v6-2018.08.08
 _score	   	 - 
 _type	   	core
 summary.@timestamp	   	2018-08-08T07:35:43.000Z
 summary.src-name   	direct_direct1-1
 summary.name	   	kafka
 summary.nodeip	   	node-72-45
 summary.value1	   	0
 summary.value2	   	0
 summary.value3	   	0

Json for above Table :+1: 

{
  "_index": "beat-v6-2018.08.08",
  "_type": "core",
  "_id": "AWUYiwsbdhYz_anUewI-",
  "_score": null,
  "_source": {
    "@timestamp": "2018-08-08T07:35:43.000Z",
    "summary": {
       "@timestamp": "2018-08-08T07:35:43.000Z",
       "src-name":"direct_direct1-1",
       "name":"kafka",
       "node-ip":"node-123",
       "value1" : 0
   }
}
}
second event  
{
  "_index": "beat-v6-2018.08.08",
  "_type": "core",
  "_id": "AWUYiwsbdhYz_anUewI-",
  "_score": null,
  "_source": {
    "@timestamp": "2018-08-08T07:35:43.000Z",
    "summary": {
        "@timestamp": "2018-08-08T07:35:43.000Z",
        "src-name":"direct_direct1-1",
        "name":"kafka",
        "node-ip":"node-123"
   }
}
}


My logstash template :+1: 

input {
 kafka {
    topics => "perfaccel"
 }
}
output {
  elasticsearch { hosts => ["192.168.1.168:9200"]
  index => "dgpmonitorbeat-v6-%{+YYYY.MM.dd}"
  document_type => "core"
  }
}

filter {
  json {
      source => "message"
      remove_field => [ "message" ]
    } 
}


any suggestion
