### ISSUE TITLE
Documentation does not reflect environment variable interpolation

### ISSUE THREAD

**Issue by tylerjharden** [elastic/logstash#5957]
Logstash documentation does not align with: https://github.com/elastic/logstash/pull/4963

The documentation states that environment variables can be referenced in configuration files as of 2.3.0; however, pull request 4963 hid this functionality behind a flag without documenting this anywhere.

Documentation needs updated to reflect this; our team rubbed our heads for several days as documentation led us to believe we could utilize environment variables, yet it didn't work.

- Version: 2.4.0
- Operating System: macOS Sierra, Dockerized Logstash

**Comment by suyograo** [comment]
<img width="763" alt="screen shot 2016-09-23 at 09 51 32" src="https://cloud.githubusercontent.com/assets/1595958/18794226/564874f6-8173-11e6-9c68-b4f8902775b6.png">

@tylerjharden There is a note about this env variable if you see the screenshot above. This is from https://www.elastic.co/guide/en/logstash/2.4/environment-variables.html

I've made a change to make that note bold. Thanks
