### ISSUE TITLE
Env variables does not work in output section ? 

### ISSUE THREAD

**Issue by rbolla** [elastic/logstash#5959]
For all general issues, please provide the following details for fast resolution:

- Version: logstash-2.4.0-1.noarch
- Operating System: CentOS release 6.7 (Final)
- Config File (if you have sensitive info, please remove it):
input{ 
         stdin{ type=>"sample"}
}
output {
 
     elasticsearch{
        hosts                         =>  ["internal-vip:443"]
        index                         =>  "u_%{type}-%{+YYYY.MM.dd}"
        ssl                           =>  "true"
        user                          =>  " ${ELASTIC_USER}"
        password                      =>  "${ELASTIC_PASS}"
     }

}
- Sample Data:
echo 'hello world' 
- Steps to Reproduce:

 echo 'hello world'  |  ELASTIC_USER=<user> ELASTIC_PASS='xxxxxxxx'  /opt/logstash/bin/logstash -f /etc/logstash/conf.d/  --debug | grep Basic
{:timestamp=>"2016-09-22T01:23:18.134000+0000", :message=>"Elasticsearch HTTP client options", :hosts=>["https:/internal-cip"], :ssl=>{:enabled=>true, :verify=>true}, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :headers=>{"Authorization"=>"Basic JHtFTEFTVElDX1VTRVJ9OiR7RUxBU1RJQ19QQVNTfQ=="}, :level=>:debug, :file=>"logstash/outputs/elasticsearch/http_client.rb", :line=>"127", :method=>"build_client"}

echo 'JHtFTEFTVElDX1VTRVJ9OiR7RUxBU1RJQ19QQVNTfQ=='|base64 --decode
${ELASTIC_USER}:${ELASTIC_PASS}

**Comment by magnusbaeck** [comment]
What if you start Logstash with `--allow-env`, as required by [the documentation](https://www.elastic.co/guide/en/logstash/2.4/environment-variables.html)?

**Comment by rbolla** [comment]
Thanks ,  closing this bug.
