### ISSUE TITLE
How to log nested objects with logstash

### ISSUE THREAD

**Issue by mrmayfield** [elastic/logstash#5961]
I am trying to log a JSON value with nested properties to a logzio ELK stack via NodeJS

The code is:

    var logger = require('logzio-nodejs').createLogger({
      token: config.LOGZIO_API_KEY
    });
    
    
    // sending text
    logger.log('This is a log message');
    
    // sending an object
    var obj = {
      message: 'Some log message',
      param1: 'val1',
      param2: 'val2'
    };
    
    logger.log(obj);

This works fine, but if I want to log nested data such as:

    // sending an object
    var obj = {
      message: 'Some log message',
      param1: {
        a : 'b',
        c : 'd'
      },
      param2: 'val2'
    };

This returns an error:

    {"type":"mapper_parsing_exception","reason":"failed to parse [param1]","caused_by":{"type":"illegal_argument_exception","reason":"unknown property [a]"}}

What can I adjust that will allow me to log this nested object?

**Comment by magnusbaeck** [comment]
At this point I'd say this is a question more than a bug report, so please open a thread at https://discuss.elastic.co/ instead. Quoting the issue template text:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

**Comment by mrmayfield** [comment]
I actually got a response on SO, can close this here, thanks!

http://stackoverflow.com/questions/39648019/how-to-log-nested-objects-with-elastic-elk-stack/39652347#39652347
