### ISSUE TITLE
Logging stopped working in logstash 5 beta1 on Windows - invalid URL for Windows paths

### ISSUE THREAD

**Issue by vbohata** [elastic/logstash#5971]
Logging stopped working after upgrading to logstash 5 beta1. Logstash has problem with Windows paths, see error from console:

ERROR StatusLogger Invalid URL D:/ELK/logstash/config/log4j2.properties
 java.net.MalformedURLException: unknown protocol: d
....

**Comment by RPGambit2** [comment]
I am having the same exact issue.  Have you figured anything out yet?

**Comment by allustin** [comment]
Dirty Hack - set the configuration file directly before start logstash

for example 
```
set JAVA_OPTS=-Dlog4j.configurationFile=file:///C:\LogStash\logstash-5.0.0-beta1\config\log4j2.properties && logstash.bat -f c:\LogStash\1CLogs\sqlite-to-logstash.1.conf
```

as you see there is a bug - we need an URL with fille:// protocol

**Comment by RPGambit2** [comment]
Is the part after -f "c:\LogStash",....   pointing to my .conf file for is there an sqlite-to-logstash.1.conf supposed to be present?

Thanks!!

**Comment by talevy** [comment]
@vbohata thanks for reporting this issue

**Comment by vbohata** [comment]
I upgraded to logstash 5 rc1. This issue should be fixed here but still the same problem.
