### ISSUE TITLE
S3 output stops due to XAmzContentSHA256Mismatch

### ISSUE THREAD

**Issue by runningman84** [elastic/logstash#5973]
Sometimes s3 output suddenly stops dues to a s3 AWS error:

```
{:timestamp=>"2016-09-27T07:23:29.417000+0000", :message=>"Pipeline main started"}
{:timestamp=>"2016-09-27T11:58:28.012000+0000", :message=>"S3: AWS error", :error=>#<AWS::S3::Errors::XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.>, :level=>:error}
```

Without a restart of logstash the s3 output does not restart. If I restart logstash manually logstash does not process old files from the temporary directory.

It would be cool if logstash would just retry in case of any error and retransmit all files from the temporary directory.

I had cases where the filesystem was full because of this issue.

**Comment by jordansissel** [comment]
Please open this on the S3 output plugin repo.

**Comment by jordansissel** [comment]
Please open this on the S3 output plugin repo.
