### ISSUE TITLE
[windows] Logstash 2.4.0 not processing files

### ISSUE THREAD

**Issue by todd-bowles-console** [elastic/logstash#5976]
Cross-posting from logstash-input-file Github, because I think that is the correct place, but I want to cover my bases.

https://github.com/logstash-plugins/logstash-input-file/issues/144

Feel free to delete this if the other place is the right place.

**Comment by jordansissel** [comment]
Closing in favor of https://github.com/logstash-plugins/logstash-input-file/issues/144
