### ISSUE TITLE
Disable offline plugin support until a working implementation is present.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5993]
We have numerous reports from customers and users about bugs in the plugin manager with respect to executing while offline (no external network).

Because offline plugin management has so many problems (noted in https://github.com/elastic/logstash/issues/5906), and because we don't have a working solution yet, I want to remove the offline plugins feature of Logstash.

Specifically, the scope of this is to remove the interfaces by which users are trying to manage plugins offline:

* bin/logstash-plugin pack
* bin/logstash-plugin unpack
* bin/logstash-plugin install --local

I propose disabling all 3 of these until we have a solution that allows users to successfully manage plugins without connectivity to external sites such as rubygems.org.

My hope is that we can fix the known issues with offline plugins in time for Logstash 5.1, but for 5.0 it should be disabled.

**Comment by shoggeh** [comment]
-1

**Comment by suyograo** [comment]
After discussing internally, we decided this change is too disruptive and too late for 5.0.0 affecting users we don't know about. 

Offline plugin installation still does not work as expected, but we have a plan to fix it in 5.x. We decided to keep these options in the CLI as-is so closing this issue.
