### ISSUE TITLE
New input plugin: logstash-input-google_pubsub

### ISSUE THREAD

**Issue by erjohnso** [elastic/logstash#5995]
Hello,

I would like to contribute a new logstash input plugin for [Google Cloud Pub/Sub](https://cloud.google.com/pubsub/). An additional use-case is to configure the [Stackdriver Logging export feature](https://cloud.google.com/logging/docs/export/using_exported_logs) to Google Cloud Pub/Sub so that all GCP logs can be ingested into Elasticsearch/Kibana.

The staged repo is at: https://github.com/erjohnso/logstash-input-google_pubsub

The gem has been published to rubygems.org: https://rubygems.org/gems/logstash-input-google_pubsub

I look forward to your feedback with the hope of transferring the repo to https://github.com/logstash-plugins.

Thank you and kind regards,
Eric

**Comment by erjohnso** [comment]
Hello!  Just checking in to see if there's anything I'm missing in order to get the plugin reviewed and hopefully accepted.

Thank you!

**Comment by suyograo** [comment]
@erjohnso Apologies for the delay. I created https://github.com/logstash-plugins/logstash-input-google_pubsub. Can you do a PR there? I'll review it and we can merge.

**Comment by erjohnso** [comment]
@suyograo - note that the PR is waiting on review / merge, https://github.com/logstash-plugins/logstash-input-google_pubsub/pull/1

Outstanding since Nov 7th 2016.

**Comment by acchen97** [comment]
Resolved with https://github.com/logstash-plugins/logstash-input-google_pubsub/pull/1. Thanks @erjohnso.
