### ISSUE TITLE
JDBC plugin not supports unsigned int?

### ISSUE THREAD

**Issue by rayenyang** [elastic/logstash#5997]
I have a table which has a unsigned int column in MySQL.Its a pity that exception occurred when I used Logstash to read this table:

**e[33mException when executing JDBC query {:exception=>#<Sequel::DatabaseError: J
ava::ComMysqlJdbcExceptionsJdbc4::MySQLDataException: '2.926689519E9' in column
'2' is outside valid range for the datatype INTEGER.>, :level=>:warn}e**

my lostash config:

input{
jdbc{jdbc_driver_library=>"mysql-connector-java-5.1.37.jar" 
jdbc_driver_class=>"com.mysql.jdbc.Driver" 
jdbc_connection_string=>"jdbc:mysql://localhost:3306/mydb
jdbc_user=>"root" 
jdbc_password=>"1234" 
schedule=>"* * * * *" 
jdbc_paging_enabled=>true 
jdbc_page_size=>1000 
statement=>"SELECT * from mytable where record_id>:sql_last_value order by record_id desc" 
use_column_value=>true 
tracking_column=>"record_id" 
}
}
output{
elasticsearch{

    }
}

**Comment by wiibaa** [comment]
As the exception is directly thrown by the mysql jdbc connector, I doubt logstash is directly responsible.
I would suppose you hit a bug in mysql connector/J a little similar to http://stackoverflow.com/questions/21770137/mysql-jdbc-exception-outside-valid-range-for-the-datatype-integer

**Comment by jsvd** [comment]
moved this to https://github.com/logstash-plugins/logstash-input-jdbc/issues/169
