### ISSUE TITLE
Logstash 5.0.0-beta1 - Beats input "failed to set certificate and key"

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#5998]
- Version: 5.0.0-beta1
- Operating System: Ubuntu 14.04.5
- Config File: https://gist.github.com/ceeeekay/70b3f2770fbc8220a9d17c11c19ababf

After converting my private key to pkcs8:
`openssl pkcs8 -in dev-beats-key.pem -topk8 -nocrypt -out dev-beats-key.pk8`

Logstash starts up fine but as soon as an incoming beats connection is attempted it throws this error:
>[2016-10-05T16:46:52,994][WARN ][logstash.inputs.beats    ] Error when creating a connection {:exception=>"failed to set certificate and key"}

This key has been working previously (except for alpha5 - see #5756).

Is this something I'm doing wrong? I can't find any docs to hold my hand with this.
Also, apologies if this is in the wrong place. The last issue I opened for beats turned out to be a Logstash issue, and vice versa.

**Comment by dtrv** [comment]
+1

**Comment by ph** [comment]
@ceeeekay I am looking at this issue, I used the certificate that you have provided in #5756 with FB  /LS 5.0.0-rc1. 

I've used a similar configuratin for LS and FB https://gist.github.com/ph/d521a14e659424c24f47d788dd68c95f

I don't get the same error as you, in the logstash log I don't seen anything unless I run logstash in debug mode, when I do I just see the beginning of SSL handshakes done by netty.

On the other hand when I look at Filebeat I see an `ERR` in the log:

```
 x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "localhost")
```

**Comment by ph** [comment]
Copied the content of the openssl configuration from #5756 for clarity:
```
[ v3_req ]
# Extensions to add to a certificate request
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = dev-ingress1
DNS.2 = dev-ingress2
```

I've looked at the output of openssl x509 -in ~/es/certificates/certificate.crt -text -noout

```
# openssl x509 -in ~/es/certificates/bad_certificates/certificate.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            8a:14:b6:ae:99:eb:8b:13
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=XX, ST=test, L=test, O=test, OU=test, CN=localhost/emailAddress=test@test.xx
        Validity
            Not Before: Aug 17 01:37:57 2016 GMT
            Not After : Aug 15 01:37:57 2026 GMT
        Subject: C=XX, ST=test, L=test, O=test, OU=test, CN=localhost/emailAddress=test@test.xx
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:e1:bf:a3:5a:f1:a5:05:bf:50:99:ec:76:44:d6:
                    c6:8a:86:02:7f:c7:76:1b:b0:e1:94:f1:de:c4:51:
                    19:18:e4:93:4b:66:fd:51:05:8e:a7:37:3b:a2:98:
                    e8:38:bb:2d:0d:0f:9f:05:f7:ff:38:37:9f:fc:bd:
                    d3:4e:dd:0d:9d:49:23:3f:d4:f5:23:51:33:01:1f:
                    ae:ac:cf:a2:af:fc:ee:fd:00:3e:74:f1:03:1f:af:
                    99:5d:7b:e4:3c:2a:48:fa:93:1b:21:2a:d5:0d:f0:
                    99:98:d2:09:4e:86:f1:bf:ad:81:b3:69:0b:2b:70:
                    1a:8f:8a:8f:ee:df:08:4d:58:23:2b:ed:24:d3:1d:
                    97:98:6f:e3:b0:a1:2f:e4:71:ad:ed:62:96:46:79:
                    c7:44:cb:9e:7f:27:50:e2:1d:45:09:93:da:eb:b0:
                    c8:97:b6:ae:9f:9a:43:f2:30:94:31:cb:e3:cb:c5:
                    ec:3d:a3:36:ba:bf:5a:46:eb:de:83:aa:31:9c:9e:
                    f4:c0:78:a0:17:d1:09:9d:b9:09:83:d3:9f:3e:71:
                    5a:24:19:ef:39:c8:5b:27:2b:51:e1:f3:fe:ce:80:
                    91:b9:c8:a0:4f:02:bb:58:93:b3:e0:b3:7d:b8:cf:
                    41:7c:00:f7:e8:25:82:49:a7:b6:13:a9:dd:04:a6:
                    3f:df
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:localhost, DNS:some-other-host
            X509v3 Subject Key Identifier: 
                84:C1:2D:99:6E:4E:EF:B0:9C:1A:0C:B9:AA:AE:4F:6D:EB:B7:65:9A
            X509v3 Authority Key Identifier: 
                keyid:84:C1:2D:99:6E:4E:EF:B0:9C:1A:0C:B9:AA:AE:4F:6D:EB:B7:65:9A

            X509v3 Basic Constraints: 
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
        80:28:cd:68:23:12:eb:3f:2f:3f:e2:21:d0:b5:30:6b:6c:a7:
        91:5e:f4:33:db:e3:4c:44:ed:80:27:09:e5:a7:b6:9d:eb:a4:
        e4:ba:9f:11:65:32:1b:3b:94:0c:d0:89:1c:1a:ee:11:33:d1:
        61:bd:63:6c:ce:64:dd:9b:1b:1c:61:69:98:5c:7d:c8:3a:db:
        61:64:42:bc:52:0f:20:82:58:4b:d8:99:01:e6:bc:f5:de:79:
        50:ac:9b:4b:a0:28:79:b3:35:ff:11:91:4b:e8:8e:61:22:e7:
        90:2e:8a:a2:16:88:fd:13:fb:5f:9c:52:1c:44:c3:34:12:4d:
        8b:32:8e:83:99:72:24:86:0f:42:89:ae:34:13:21:7a:3c:82:
        1d:eb:4e:d6:ac:66:ac:8c:c0:74:00:20:d6:f2:30:a3:88:42:
        82:5c:f2:a8:31:5b:2d:9b:d2:ee:6a:21:fd:25:d2:cb:64:02:
        85:be:64:0c:2c:30:47:bf:1d:ba:6f:d4:85:d1:7c:56:01:17:
        0e:2a:61:ab:11:c1:40:a2:27:05:30:d9:fe:58:6a:cb:33:5e:
        2a:cc:64:d1:8c:dc:a9:9c:8a:2d:bf:51:3f:b0:cd:39:b2:09:
        37:c7:77:44:11:9c:e3:c8:be:f3:ec:53:2c:d9:98:fd:87:7c:
        b4:73:9a:fd
```

One thing that is different from the certificate vs the config is the `Basic Constraints`, The config said **FALSE** but the value is **TRUE**. 

Another thing is the `Key Usage`:  Digital Signature, Non Repudiation, Key Encipherment. In my humble quick test I don't use theses options and the self sign certificate just works. I wonder when we use theses options if we need to specific an `Extended Key Usage`  with `serverAuth`.

**Comment by ph** [comment]
I did a bit more tests using the certificate/key that you have provided.

FB 5.0 => Logstash 2.3.2/beats 2.2.8, I get the same ` invalid signature: parent certificate cannot sign this kind of certificate` which is the same behavior that I had with 5.0.

To solve the problem above the **self signed** need to have `CA:TRUE` and the `KeyUsage` **keyCertSign**. If you don`t want the server certificate to be able to sign certificate you need to have a ROOT CA that sign a server certificate and use that CA as the certificate authorities in FB.

**Comment by ceeeekay** [comment]
HI @ph 
Sorry for the lack of updates - I haven't been able to spend a lot of time on this due to other recent commitments - I'm tied up for at least the next two months, and to be quite honest I'm not all that great with SSL configuration in the first place.

Does this look like there's an issue with my original cert so it's unable to be used in new LS releases? Rolling a new one for prod, once GA is released would be problematic here, but it is possible.

Is there any documentation on the Right Way to go about securing FB -> LS comms in the new build?

Thanks,
Chris

**Comment by ph** [comment]
@ceeeekay Agree, It look like to be a cert problem, but I wasn't able to make your cert/key works with our previous releases.

Concerning the documentation, generating ssl config is always a bit of pain, its a complex process and the documentation is to say the less cryptic. @jordansissel is working on a tool to help users debug ssl issues with their certificate or a least provide better feedback. We might be able to integrate some of it in our SSL enable plugins to provide better feedback when the certificate are parsed.


I will close this issue, but one thing you can try is this command.
```
 openssl s_client -connect localhost:5544 -CAfile ./certificates/certificate.crt
```
