### ISSUE TITLE
Missing message when logging "Pipeline aborted due to error" in agent.rb line: 493

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#6001]
Recently a customer misconfigured the jdbc driver class string in the jdbc input. The plugin make an effort to add a specific message to the exception that is raised.

The line in agent.rb does not log the exceptions actual message. It should.

**Comment by jsvd** [comment]
fixed in https://github.com/elastic/logstash/pull/6011, will be included in logstash 2.4.1
