### ISSUE TITLE
how to convert date string to time,example "10/Oct/2016:15:49:23 +0800"

### ISSUE THREAD

**Issue by zhangmingju** [elastic/logstash#6014]
this is my config:
 if [custom_time] {
    ruby {
     init => "require 'time'" 
     code => "
        if(event['custom_time'] =~ /\d{2}\/\D{3}\/\d{4}:\d{2}:\d{2}:\d{2}/);
          time = Time.strptime(event['custom_time'],'%d-%b-%Y:%H:%M:%S');
          event.sprintf('%{+YYYY-MM-dd HH:mm:ss}')
        else;
          time = Time.parse(event['custom_time']);
        end;
        event['time_sec']  = time.to_i;
        event['time_usec'] = time.usec;
      "
    }
  }

result:

127.0.0.1 - - [10/Oct/2016:15:49:23 +0800] 
Ruby exception occurred: invalid strptime format - `%d-%b-%Y:%H:%M:%S' {:level=>:error}
{
        "message" => "127.0.0.1 - - [10/Oct/2016:15:49:23 +0800] ",
       "@version" => "1",
     "@timestamp" => "2016-10-10T08:56:46.208Z",
           "host" => "zhang-X550JK",
             "ww" => "[10/Oct/2016:15:49:23 +0800]",
    "custom_time" => "10/Oct/2016:15:49:23 +0800",
           "tags" => [
        [0] "_rubyexception"
    ]
}

logstash version 2.4
os: centos

why invalid strptime format

**Comment by jsvd** [comment]
```

**Comment by zhangmingju** [comment]
how to get 
event['time_sec'] = time.to_i;
event['time_usec'] = time.usec;

**Comment by jsvd** [comment]
using the ruby filter with `event['time_sec'] = event['@timestamp'].to_i`, if you're using logstash 5.x it needs to be `event.set('time_sec', time['@timestamp'].to_i`
