### ISSUE TITLE
Offline plugin workflow known issues & workarounds docs

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6016]
Issue for tracking the clarification of offline plugin workarounds for 5.0
- Add known issues note in the "Install and Update a local plugin" [section](https://www.elastic.co/guide/en/logstash/current/offline-plugins.html#_install_or_update_a_local_plugin)
- Create an article on the known issues and recommended workarounds

**Comment by ph** [comment]
There is a workaround for `HTTP_PROXY` and `HTTPS_PROXY` see https://github.com/elastic/logstash/issues/6044#issuecomment-253854228

**Comment by acchen97** [comment]
Closing as a won't fix for now.
