### ISSUE TITLE
RPM install for Logstash 5.0.0-RC1 .yml is not indented

### ISSUE THREAD

**Issue by carnalim** [elastic/logstash#6027]
When using the .rpm install for logstash I've check the /etc/logstash/logstash.yml and it looks like none of the settings are properly spaced. It looks like:

```
# Which directory should be used by logstash and its plugins
# for any persistent needs. Defaults to LOGSTASH_HOME/data
#
path.data: /var/lib/logstash
#
```

```
Instead of being 
# Which directory should be used by logstash and its plugins
# for any persistent needs. Defaults to LOGSTASH_HOME/data
#
 path.data: /var/lib/logstash
#
```

**Comment by suyograo** [comment]
@carnalim why do we need an indentation/spacing there? What problem does it fix?

**Comment by untergeek** [comment]
@suyog, I think he means that it's indented and it shouldn't be.

**Comment by untergeek** [comment]
The fix would be to remove the spaces after these settings, so when the script uncomments them, there are no pre-spaces.

@carnalim is it non-functional this way, though? There are no nested data structures here, so I can't imagine that it's causing problems now, when it didn't before.  It seems this is a cosmetic fix.

**Comment by jordansissel** [comment]
The configuration after rpm install looks correct to me.

```
% grep -v '^#' logstash.yml
path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d
path.logs: /var/log/logstash
```

This is correct. No indentation should occur. I am not seeing the configuration being a problem. It's correct YAML.

@carnalim can you describe what is solved by adding leading spaces?

**Comment by untergeek** [comment]
With no response, I think we can probably close this as a non-issue.  It's been working, and no other users have reported an issue.

**Comment by untergeek** [comment]
Closing, as this has proven to be a non-issue.
