### ISSUE TITLE
Logging is not working in logstash 5 rc1 on Windows - invalid URL for Windows paths

### ISSUE THREAD

**Issue by vbohata** [elastic/logstash#6036]
Logstash has problem with Windows paths, see error from console:

ERROR StatusLogger Invalid URL D:/ELK/logstash/config/log4j2.properties
java.net.MalformedURLException: unknown protocol: d
....

See https://github.com/elastic/logstash/issues/5971

In rc1 it should be fixed but it is not.

**Comment by ph** [comment]
@vbohata I've checked the rc1 package and it doesn't contains the commit https://github.com/elastic/logstash/pull/6012 I think it was merged after the code freeze, can you confirm that the fix solve your problem?

**Comment by talevy** [comment]
right, unfortunately this bug fix didn't make the RC1 build. It will make it into GA. Apologize for the inconvenience. Please do try that code change @ph referred to see if it resolves your issue.

**Comment by vbohata** [comment]
OK, that fix should work. Currently I am using the hack with JAVA_OPTS which is working.
Please remove or change "Windows: Enabled logging on Windows by fixing log4j config location (Issue 5971). " from RC1 release notes because it says it is fixed in RC1.

**Comment by suyograo** [comment]
Will fix the RC notes. Closing since dup of 5971
