### ISSUE TITLE
Test and exit misses config issue

### ISSUE THREAD

**Issue by DigiAngel** [elastic/logstash#6037]
- Version: 5 Beta
- Operating System: Ubuntu 16.04, oracle-java8-installer 8u101+8u101arm-1~webupd8~2
- Config File:
~~~
input {
        file {
                type => "connlog"
                path => "/opt/bro/spool/bro/conn.log"
                sincedb_path => "/var/lib/logstash/.sincedbconn"
        }
}

filter {

                grok {
                        match => { "message"=> "(?<unixtime>(.*?))\t(?<uid>(.*?))\t(?<src_ip>(.*?))\t(?<src_port>(.*?))\t(?<dst_ip>(.*?))\t(?<dst_port>(.*?))\t(?<proto>(.*?))\t(?<service>(.*?))\t(?<duration>(.*?))\t(?<orig_bytes>(.*?))\t(?<resp_bytes>(.*?))\t(?<conn_state>(.*?))\t(?<local_orig>(.*?))\t(?<local_resp>(.*?))\t(?<missed_bytes>(.*?))\t(?<history>(.*?))\t(?<orig_packts>(.*?))\t(?<orig_ip_bytes>(.*?))\t(?<resp_packts>(.*?))\t(?<resp_ip_bytes>(.*?))\t(?<tun_parent>(.*))\t(?<protosig>(.*))" }
                }

                geoip {
                        source => "src_ip"
                        target => "src_geoip"
                }

                geoip {
                        source => "dst_ip"
                        target => "dst_geoip"
                }
                mutate {
                        convert => { "resp_bytes" => "integer" }
                        convert => { "resp_ip_bytes" => "integer" }
                        convert => { "orig_bytes" => "integer" }
                        convert => { "orig_ip_bytes" => "integer" }
                        convert => { "src_ip" => "ip" }
                        convert => { "dst_ip" => "ip" }
                        gsub => [
                        "ids_alert", "[ \-\(\)\/\:]",  "_",
                        "src_geoip.country_name", "[ ]", "_",
                        "dst_geoip.country_name", "[ ]", "_",
                        "proto", "tcp", "TCP",
                        "proto", "udp", "UDP",
                        "proto", "icmp", "ICMP"
                        ]
                }
}


output {
        stdout { codec => rubydebug }
        #elasticsearch {
        #        hosts => ["192.168.1.8"]
        #}
}
~~~
- Sample Data: Initial testing
- Steps to Reproduce: below
~~~
[10:06:43 @tester:/var/log/logstash$] sudo -u logstash /usr/share/logstash/bin/logstash --path.settings=/etc/logstash -f /etc/logstash/conf.d -t
Configuration OK
~~~

but starting gives me:
~~~
[2016-10-12T10:02:17,308][ERROR][logstash.agent ] Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: translation missing: en.logstash.agent.configuration.invalid_plugin_register>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.1.1/lib/logstash/filters/mutate.rb:178:inregister'", "org/jruby/RubyHash.java:1342:in each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.1.1/lib/logstash/filters/mutate.rb:172:inregister'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:197:in start_workers'", "org/jruby/RubyArray.java:1613:ineach'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:197:in start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:153:inrun'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:250:in start_pipeline'"]}
~~~

So either a) field type of "ip" is no longer valid and the test and exit misses it, or b) field type of "ip" IS valid, and logstash itself has an issue.  Thank you.

**Comment by untergeek** [comment]
The `-t` test only validates as far as the plugin syntax requires.  In this case, the mutate `convert` option [only requires a `hash`](https://github.com/logstash-plugins/logstash-filter-mutate/blob/master/lib/logstash/filters/mutate.rb#L67) to be considered valid:

```
config :convert, :validate => :hash
```

As such, your example is a valid configuration.  However, the valid types for conversion are `string`, `integer`, `float`, and `boolean`.  See https://github.com/logstash-plugins/logstash-filter-mutate/blob/master/lib/logstash/filters/mutate.rb#L243-L287 for more information on those.

The IP type is not a valid conversion type, as that "conversion" is internal to Elasticsearch and must be handled in a mapping, or mapping template.  I answered your post to that effect [in the discussion forum](https://discuss.elastic.co/t/supported-field-types/62839/2).

**Comment by untergeek** [comment]
This is technically not a bug, though I agree it is a less than perfect user experience.

**Comment by DigiAngel** [comment]
Ok cool...this upgrade to the latest ELK has certainly been a hoot :)

**Comment by untergeek** [comment]
@DigiAngel This configuration validation tactic has been the same since the early days of Logstash.  I'm not sure if you had a different experience with another version, but I'd like to know more.

**Comment by DigiAngel** [comment]
Truth be told it's the first time I've used it :D  My older ELK stack supported convert to type "ip"...looks like this was another change, so I wanted to test.  Ironically however, from the 5.0 help:
~~~
Note that grok patterns are not checked for correctness with this flag. 
~~~
which of course is exactly what I was doing 8-|.  Thanks again Aaron...I appreciate your help every time I post.

**Comment by untergeek** [comment]
> My older ELK stack supported convert to type "ip".

That must have been in the mapping template. Logstash ships with one, and uses it for all `logstash-*` indices, but it only captured a field called `clientip`, as that was the default from the Apache grok rule output.  But if you changed and use a different field name, like `src_ip` and `dst_ip`, you'd have to update the mapping to also capture those fields to get them mapped as IP type in Elasticsearch.
