### ISSUE TITLE
Clarify auto-reload functionality on grok pattern file changes

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6038]
The auto-reload feature is awesome :)

Would be nice to clarify the documentation (https://www.elastic.co/guide/en/logstash/2.4/reloading-config.html) here.  It's not very clear in the documentation how it affects the grok pattern files.  From talking to @jordansissel , it should work for grok patterns as well with a caveat - only if the Logstash config file itself also changes (because the patterns are only loaded when grok compiles the regex, and that happens on the loading of the Logstash config today).

**Comment by dedemorton** [comment]
Closed by PR #6261 and https://github.com/logstash-plugins/logstash-filter-grok/pull/102

**Comment by matejzero** [comment]
So in case we only changed pattern files, we need to restart Logstash in order for it to recompile the pattens? According to my tests, kill -SIGHUP doesn't work.

**Comment by jordansissel** [comment]
@matejzero Yes. Logstash only currently detects if a pipeline has changed if the configuration file(s) have changed. This means the files provided by the `path.config` setting (the `-f` flag).

**Comment by matejzero** [comment]
Thanks
