### ISSUE TITLE
Logstash 2.3.4 doesn't complains when EACCES (Permission denied) on folder

### ISSUE THREAD

**Issue by jlory** [elastic/logstash#6040]
When using the file{} input, if the path is not accessible from the Logstash user there is no errors / warnings anywhere, the only hint you have is by enabling the debug mode and looking at the glob line which doesn't match anything:

`{:timestamp=>"2016-10-12T22:29:48.387000+0000", :message=>"_globbed_files: /opt/app/logs/*.log: glob is: []", :level=>:debug, :file=>"filewatch/watch.rb", :line=>"346", :method=>"_globbed_files"}`

I used strace to find the issue:

`27686 stat("/opt/app/logs/*.log", 0x7fbe942a7ad0) = -1 EACCES (Permission denied)`

At least some warnings / error in the logstash.err could be very useful :)
- Tested on Amazon Linux
- RPM: logstash-2.3.4-1.noarch

**Comment by ph** [comment]
move to the file input.
