### ISSUE TITLE
jffi warning when running CI test on Alpine/musl libc.

### ISSUE THREAD

**Issue by jarpy** [elastic/logstash#6043]
Description
---------------
Invoking `ci_test.sh` in an Alpine Linux container passes, which is great! It does, however, produce a warning related to jffi, which I assume is triggered by the absence of glibc.

```
Oct 13, 2016 1:47:18 AM jnr.netdb.NativeProtocolsDB load
WARNING: Failed to load native protocols db
java.lang.UnsatisfiedLinkError: Symbol not found: Java_com_kenai_jffi_Foreign_dlerror
        at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:40)
```
[🔗 Full trace](https://gist.github.com/jarpy/1d2fbfec2b34bc3d546b690864d0da11).

Does this warning look like trouble? Does Logstash depend on jffi?

Ultimately, I'd like to make a reasonable call on whether it's sane and reasonable to use Alpine/musl as the base for Logstash containers.

Repro
--------
``` dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch-ci:latest
ENV JRUBY_VERSION 1.7.25
USER root
RUN curl -s -o - https://s3.amazonaws.com/jruby.org/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz | tar xzf - -C /usr/local
ENV PATH /usr/local/jruby-${JRUBY_VERSION}/bin:$PATH
CMD git clone http://github.com/elastic/logstash && cd logstash && ci/ci_test.sh
```

``` bash
docker build . --tag=jffi_repro
docker run -it jffi_repro
```

**Comment by jordansissel** [comment]
Logstash does depend on jffi because JRuby needs it for certain system features (file stat calls, etc)

**Comment by jordansissel** [comment]
Googling for some hints, 'jruby musl' found this: https://github.com/jruby/jruby/wiki/JRuby-on-Alpine-Linux -- hopefully it's helpful?

**Comment by jarpy** [comment]
Thanks. I reckon I should take that warning seriously then. Looks like Ubuntu may be a better target for the docker image.

... But I'll check that link too. Thanks again.

**Comment by jarpy** [comment]
Thanks. I reckon I should take that warning seriously then. Looks like Ubuntu may be a better target for the docker image.

... But I'll check that link too. Thanks again.

**Comment by jarpy** [comment]
Doesn't Logstash ship with its own JRuby?

**Comment by jordansissel** [comment]
@jarpy logstash ships with jruby, but on many less-travelled platforms (solaris sparc, aix, hpux, and it seems alpine), FFI support is unavailable.

I have no experience with Alpine so I can't really offer much in the way of advice :\

It looks like maybe you can install libc6-compat and that'll help? Not sure though.

**Comment by jarpy** [comment]
Thanks for the help, @jordansissel. Sadly, even with libc6-compat installed, the warning is still present. 

Digging into the warning, however, it looks safe to ignore. It's upset because it can't find `getprotobyname_r(3)`, but it's a [graceful failure, with two fallbacks built in](https://github.com/jnr/jnr-netdb/blob/3117d5fb29c57abbf3045025aaaf3ef4473e9897/src/main/java/jnr/netdb/Protocol.java#L105).

**Comment by jarpy** [comment]
Related issue and solution: https://github.com/jruby/jruby/issues/3955

**Comment by jarpy** [comment]
Actually, the symptoms are the same, but the cause is likely different. Alpine ships with `/etc/protocols`:

```
$ docker run -it alpine test -f /etc/protocols && echo OK
OK
```
but musl libc does not appear to have an implementation of `getprotobyname_r`:

https://git.musl-libc.org/cgit/musl/tree/include/netdb.h

So it's an easy fix for glibc-based Xenial, and not so much for musl-based Alpine.
