### ISSUE TITLE
Logstash cannot start with a LoadError

### ISSUE THREAD

**Issue by lyxhaven** [elastic/logstash#6052]
I installed Logstash 2.4.0 all plugin version on my Linux machine from the Zip file here:
https://download.elastic.co/logstash/logstash/logstash-all-plugins-2.4.0.zip

After installation, I run the following commands:
cd logstash-2.4.0
bin/logstash -e 'input { stdin { } } output { stdout {} }'

And I got this error: LoadError: no such file to load -- bundler/dep_proxy expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:590 each at org/jruby/RubyArray.java:1613 expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:589 each at org/jruby/RubyArray.java:1613 expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:586 converge_locked_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:554 resolve at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:187 specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:132 specs_for at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:177 requested_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:166 requested_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/environment.rb:18 setup at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:13 setup at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122 setup! at /logstash-2.4.0/lib/bootstrap/bundler.rb:64 (root) at //logstash-2.4.0/lib/bootstrap/environment.rb:65

I assume this means something is missing but what's missing exactly and what should I do ?

I didn't find anything related on official website or online.

Can anybody help ? Thanks !
 
- Version: 2.4.0
- Operating System: Linux
- Java version: 1.8.0_101
- ruby version: 1.8.7
- rubygems: rubygems.noarch 0:1.3.7-5.el6

**Comment by jsvd** [comment]
this is strange, I just did the same and worked well:

```
/tmp/meh % wget https://download.elastic.co/logstash/logstash/logstash-all-plugins-2.4.0.zip
/tmp/meh % unzip logstash-all-plugins-2.4.0.zip 
/tmp/meh % cd logstash-2.4.0
/tmp/meh/logstash-2.4.0 % bin/log
/tmp/meh/logstash-2.4.0 % bin/logstash -e 'input { stdin { } } output { stdout {} }'
Settings: Default pipeline workers: 4
Pipeline main started
hey
2016-10-13T16:55:23.811Z Joaos-MBP-5.lan hey
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}
```

can you try downloading and unpacking the zip again?

**Comment by tokai2010** [comment]
I tried it and got the same error as lyxhaven mentioned earlier. 
I tried the following to get around it:
#cd $HOME/logstash-2.4.0
#bundle install 
and got this new error further below.
Any thoughts?
Cheers Tokai.

Error:
[..]
HTTP GET https://index.rubygems.org/api/v1/dependencies?gems=faraday-middleware%2Cform_data%2Clogstash
HTTP 200 OK https://index.rubygems.org/api/v1/dependencies?gems=faraday-middleware%2Cform_data%2Clogstash
Query List: []
**Could not find gem 'logstash-core (= 2.4.0)' in any of the gem sources listed in your Gemfile or available on this machine.
Bundler::GemNotFound: Could not find gem 'logstash-core (= 2.4.0)' in any of the gem sources listed in your Gemfile or available on this machine.**
/usr/local/share/gems/gems/bundler-1.13.3/lib/bundler/resolver.rb:366:in `block in verify_gemfile_dependencies_are_found!'
  /usr/local/share/gems/gems/bundler-1.13.3/lib/bundler/resolver.rb:341:in `each'
  /usr/local/share/gems/gems
[..]

Software Versions:
-bash-4.2$ gem -v
2.0.14
-bash-4.2$ ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
-bash-4.2$ bundle -v
Bundler version 1.13.3
-bash-4.2$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by lyxhaven** [comment]
@jsvd I tried downloading and unpacking the zip several time and it just wouldn't work. 
I actually got it working the day before yesterday. Everything works fine with my own .config file. However from yesterday afternoon, all of a sudden this error came up and I couldn't even run this simplest Logstash command.

**Comment by jsvd** [comment]
@tokai2010 running bundle install on a packaged installation of logstash is a bad idea and can potentially corrupt it, as logstash contains everything necessary: jruby/bundler/etc

@lyxhaven have you also executed `bundle install`?

**Comment by lyxhaven** [comment]
@jsvd No I haven't.

**Comment by tokai2010** [comment]
@jsvd If I just unzip logstash-all-plugins-2.4.0.zip and run logstash -e 'input { stdin { } } output { stdout {} }'
I get the below errors:

```
bash-4.2$ logstash -e 'input { stdin { } } output { stdout {} }'
DEBUG: exec ruby /tmp/logstash-2.4.0/lib/bootstrap/environment.rb logstash/runner.rb agent -e input { stdin { } } output { stdout {} }
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /tmp/logstash-2.4.0/lib/bootstrap/bundler.rb:54:in `setup!'
        from /tmp/logstash-2.4.0/lib/bootstrap/environment.rb:65:in `<main>'
-bash-4.2$
```

What am I doing wrong? what would I need to do make this work?

**Comment by jsvd** [comment]
@tokai2010 please check that there's no ".bundle" directory in the logstash-2.4.0 folder
Also, I see you're just running "logstash -e ..", where are you executing that command?
Normally you run `bin/logstash -e ..` from the `logstash-2.4.0/` directory, or use a full path like `/tmp/projects/logstash-2.4.0/bin/logstash -e ""`

**Comment by lyxhaven** [comment]
I just tried it again, remove logstash-2.4.0 folder and unzip the zip file again. 

run following:
cd logstash-2.4.0
bin/logstash -e 'input { stdin { } } output { stdout {} }'

Still got LoadError: no such file to load -- bundler/dep_proxy just like above.

**Comment by tokai2010** [comment]
@jsvd - I am running the test command like so:
```
cd /tmp/logstash-2.4.0/bin
logstash -e 'input { stdin { } } output { stdout {} }'
```

**Comment by jsvd** [comment]
@tokai2010 please show me the output of `which logstash`

@lyxhaven something is strange..I can't reproduce your error. can you run `DEBUG=1 bin/logstash -e 'input { stdin { } } output { stdout {} }'`? and maybe paste into a gist?

**Comment by lyxhaven** [comment]
@jsvd Just tired. Still output exactly the same error. I even switch to another server and tried the same and got the same error again.

**Comment by tokai2010** [comment]
@jsvd  - I have  LOGSTASH_HOME=/tmp/logstash-2.4.0 set in my dot profile. 
`which logstash`
`/tmp/logstash-2.4.0/bin/logstash`

**Comment by jordansissel** [comment]
Can you attach the full output  of `env` ?

**Comment by lyxhaven** [comment]
@jordansissel 

When I run DEBUG=1 bin/logstash -e 'input { stdin { } } output { stdout {} }'

This is the full output:
DEBUG: exec //logstash-2.4.0/vendor/jruby/bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-XX:+HeapDumpOnOutOfMemoryError -J-Xmx1g -J-XX:HeapDumpPath=//logstash-2.4.0/heapdump.hprof //logstash-2.4.0/lib/bootstrap/environment.rb logstash/runner.rb agent -e input { stdin { } } output { stdout {} }
LoadError: no such file to load -- bundler/dep_proxy
    expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:590
                   each at org/jruby/RubyArray.java:1613
    expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:589
                   each at org/jruby/RubyArray.java:1613
    expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:586
  converge_locked_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:554
                resolve at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:187
                  specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:132
              specs_for at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:177
        requested_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:166
        requested_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/environment.rb:18
                  setup at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:13
                  setup at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
                 setup! at /logstash-2.4.0/lib/bootstrap/bundler.rb:64
                 (root) at //logstash-2.4.0/lib/bootstrap/environment.rb:65

**Comment by tokai2010** [comment]
@jordansissel 

With Load Error:

`-bash-4.2$ which logstash
/tmp/logstash-2.4.0/bin/logstash
-bash-4.2$ USE_RUBY=1 DEBUG=1 logstash -e 'input { stdin { } } output { stdout {} }'
DEBUG: exec ruby /tmp/logstash-2.4.0/lib/bootstrap/environment.rb logstash/runner.rb agent -e input { stdin { } } output { stdout {} }
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /tmp/logstash-2.4.0/lib/bootstrap/bundler.rb:54:in `setup!'
        from /tmp/logstash-2.4.0/lib/bootstrap/environment.rb:65:in `<main>'
-bash-4.2$
`

If you set USE_RUBY=0 it works! ;-)

`-bash-4.2$ USE_RUBY=0 DEBUG=1 logstash -e 'input { stdin { } } output { stdout {} }'
DEBUG: exec /tmp/logstash-2.4.0/vendor/jruby/bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-XX:+HeapDumpOnOutOfMemoryError -J-Xmx1g -J-XX:HeapDumpPath=/tmp/logstash-2.4.0/heapdump.hprof /tmp/logstash-2.4.0/lib/bootstrap/environment.rb logstash/runner.rb agent -e input { stdin { } } output { stdout {} }
Settings: Default pipeline workers: 2
Pipeline main started
Hello Taylor
2016-10-13T18:14:19.693Z dubpsvm040.openet-telecom.lan Hello Taylor
^CSIGINT received. Shutting down the agent. {:level=>:warn}
stopping pipeline {:id=>"main"}
Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss. {:level=>:warn}
^CSIGINT received. Terminating immediately.. {:level=>:fatal}
-bash-4.2$ ^C
-bash-4.2$
`

**Comment by lyxhaven** [comment]
@tokai2010 How did you get it working with USE_RUBY=0 ?

I tried it and still got the same error as above.

**Comment by lyxhaven** [comment]
Even if I run bin/logstash --version will return me the same error ...
And I have deleted the folder and reinstalled several times.

**Comment by lyxhaven** [comment]
I doubt this might relate to the server settings.

What should I look at on the server besides the ones I have listed ?

Version: 2.4.0
Operating System: Linux
Java: 1.8.0_101
ruby: 1.8.7
rubygems: 2.6.7

**Comment by tokai2010** [comment]
@lyxhaven Here is my setup:
`-bash-4.2$ cat redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
-bash-4.2$ gem -v
2.0.14
-bash-4.2$ ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
-bash-4.2$ bundler -v
Bundler version 1.13.3
-bash-4.2$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
-bash-4.2$ logstash --version
[..]
logstash 2.4.0
`

**Comment by lyxhaven** [comment]
@tokai2010 seems like your ruby version is higher than mine. I don't know if that matters.

**Comment by tokai2010** [comment]
@lyxhaven - Try the USE_RUBY = 0 option as I had mentioned earlier. Good luck.

**Comment by lyxhaven** [comment]
I tried that and still the same error :(

**Comment by jordansissel** [comment]
> -bash-4.2$ USE_RUBY=1

USE_RUBY is an env var that we use for debugging in development. It is not documented nor intended as something a user (yourself) would set. Your problems are caused by having USE_RUBY=1 set which instructs bin/logstash to use the system ruby instead of the one we ship, and you get the errors you show above.

Do not set USE_RUBY at all.

**Comment by jordansissel** [comment]
What problem were you trying to diagnose that caused you to even *look* for USE_RUBY, and set it? What was the original problem *before* you set USE_RUBY=1?

**Comment by lyxhaven** [comment]
Hi @jordansissel ,

I didn't set USE_RUBY=1.

My issue was stated in the very first post.

After installation, I run the following commands:
cd logstash-2.4.0
bin/logstash -e 'input { stdin { } } output { stdout {} }'

And then got the LoadError as above.

Even I tried bin/logstash --version would give the same error.

How can I resolve this issue ?

**Comment by jsvd** [comment]
can you post the result of `env`? please mask any sensitive data before posting

**Comment by lyxhaven** [comment]
@jsvd 

This is all I got after running bin/logstash --version

LoadError: no such file to load -- bundler/dep_proxy expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:590 each at org/jruby/RubyArray.java:1613 expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:589 each at org/jruby/RubyArray.java:1613 expand_dependencies at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:586 converge_locked_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:554 resolve at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:187 specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:132 specs_for at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:177 requested_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:166 requested_specs at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/environment.rb:18 setup at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:13 setup at /logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122 setup! at /logstash-2.4.0/lib/bootstrap/bundler.rb:64 (root) at //logstash-2.4.0/lib/bootstrap/environment.rb:65

**Comment by jsvd** [comment]
I understand, but can you run the command `env` to see what environment variables are set?

**Comment by lyxhaven** [comment]
@jsvd 

Here it is:

HOSTNAME=host
SHELL=/bin/bash
TERM=xterm
HISTSIZE=1000
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
USER=user
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/user
PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
PWD=//app/logstash-2.4.0
LANG=en_US.UTF-8
HISTCONTROL=ignoredups
SHLVL=1
HOME=/home/user
LOGNAME=user
QTLIB=/usr/lib64/qt-3.3/lib
CVS_RSH=ssh
LESSOPEN=||/usr/bin/lesspipe.sh %s
G_BROKEN_FILENAMES=1
_=/bin/env
OLDPWD=//app/

**Comment by lyxhaven** [comment]
I am going to close this since all of a sudden it works again and I didn't even touch a thing on the server. I believe this is something related to my server. I will try speak with my server guy to see what's going on there and why it stops working and starts working again for no reason.

**Comment by istvanszoboszlai** [comment]
Hello @lyxhaven , I had the dame problem. 
The problem in your config is exactly this line:
```
(root) at //logstash-2.4.0/lib/bootstrap/environment.rb:65
```
you have double / at the beginning. When I fixed my double /, the problem went away immediately

**Comment by RajeshCPaul** [comment]
Hello,
I also faced this issue and by making below changes resolved my problem in:
filename: solr_http.rb
path: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-solr_http-3.0.5/lib/logstash/outputs

where "/usr/share/logstash" is logstash installation directory.

```
require "rsolr"
#require "/home/impadmin/.gem/ruby/gems/rsolr-1.1.2/lib/rsolr"

```
Although couple of other posts suggested to keep -> require "rsolr" as commented and uncomment the latter one but that didn't work in my case so I did as above.

**Comment by hardik-goel** [comment]
@RajeshCPaul - Thanks for the fix. it worked for me as well.

**Comment by NirmitJain** [comment]
> Hello,
> I also faced this issue and by making below changes resolved my problem in:
> filename: solr_http.rb
> path: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-solr_http-3.0.5/lib/logstash/outputs
> 
> where "/usr/share/logstash" is logstash installation directory.
> 
> ```
> require "rsolr"
> #require "/home/impadmin/.gem/ruby/gems/rsolr-1.1.2/lib/rsolr"
> ```
> 
> Although couple of other posts suggested to keep -> require "rsolr" as commented and uncomment the latter one but that didn't work in my case so I did as above.

Thanks @RajeshCPaul . It worked for me as well.
