### ISSUE TITLE
bug on Logstash-5.0.0-rc1 : log4j2 config location is an invalid URL

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#6064]
When starting Logstash-5.0.0-rc1, I got the following stack trace :
```
ERROR StatusLogger Invalid URL C:/logstash-5.0.0-rc1/config/log4j2.properties
 java.net.MalformedURLException: unknown protocol: c
        at java.net.URL.<init>(URL.java:593)
        at java.net.URL.<init>(URL.java:483)
        at java.net.URL.<init>(URL.java:432)
        at java.net.URI.toURL(URI.java:1089)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFromUri(ConfigurationFactory.java:299)
```

It is because the path `C:/logstash-5.0.0-rc1/config/log4j2.properties` is not considered as a URL. It must be prefixed by `file:`

=> It's very easy to fix it here :
https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/runner.rb#L188

Following line :
`log4j_config_location = ::File.join(setting("path.settings"), "log4j2.properties")`
should be replaced by this one :
`log4j_config_location = "file:" + ::File.join(setting("path.settings"), "log4j2.properties")`

I tested on my computer, it fixes the issue.
If you want that I create a pull request, tell me.

Environment :
- logstash version : 5.0.0-rc1
- OS : windows 10

**Comment by jsvd** [comment]
Hey thanks for reporting but this is a dup of https://github.com/elastic/logstash/issues/5971 which has been fixed in master

**Comment by fbaligand** [comment]
Nice news !
Sorry, I should have checked before.
