### ISSUE TITLE
Allow a gem to have multiple defined plugins in it

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6065]
The way we load plugins in logstash core is tied to the file directory of the plugins and
all the plugins files are lazy loaded when they are required. Nothing prevent you today to
have multiple plugins in the same repo, if they respect the following structure.

```
logstash/(codec|input|output|filter)s/plugin_name
```

I suggest we allow plugins author to define their own structure as they wish, to do so I believe plugins should have a common entry file that get pick by logstash at boot time. 
It could be called "logstash_registry.rb and be present in any of the **$LOAD_PATH** defined by the plugin author in their gemspec. The first file found will be used.

The syntax to define plugins could look like this:

``` ruby
require "logstash/out_of_this_world"

LogStash::PluginRegistry.add(:input, "past", LogStash::OutOfThisWorld::Past)
LogStash::PluginRegistry.add(:input, "future", LogStash::OutOfThisWorld::Future)
LogStash::PluginRegistry.add(:input, "present", LogStash::OutOfThisWorld::Present)
```

**Comment by wiibaa** [comment]
Some previous github discussion to centralize here:
* https://github.com/elastic/logstash/issues/5757
* https://github.com/elastic/logstash/issues/4612

**Comment by ph** [comment]
Thanks @wiibaa I've closed the other issues.

**Comment by ph** [comment]
Fixed in https://github.com/elastic/logstash/pull/6109
