### ISSUE TITLE
Logstash stop processing metrics if one of the server stop responding

### ISSUE THREAD

**Issue by alyan2008** [elastic/logstash#6067]
I have configured logstash with jmx input:

`input {
  jmx {
    path => "/opt/logstash/configs/jmx/"
    polling_frequency => 10
    type => "jmx"
    nb_thread => 4
  }
}`

In /opt/logstash/configs/jmx/ direcroty I have a list of servers with JMX port. In case of one of the server jmx stops responding, logstash stops processing metrics from all other servers. In the log I found this error: 
`{:timestamp=>"2016-10-17T19:19:44.856000+0000", :message=>"Error unmarshaling return header; nested exception is: \n\tjava.io.EOFException", :level=>:error}
{:timestamp=>"2016-10-17T19:19:44.857000+0000", :message=>"sun.rmi.transport.StreamRemoteCall.executeCall(sun/rmi/transport/StreamRemoteCall.java:229)\nsun.rmi.server.UnicastRef.invoke(sun/rmi/server/UnicastRef.java:162)\njavax.management.remote.rmi.RMIConnector.getConnectionId(javax/management/remote/rmi/RMIConnector.java:384)\njavax.management.remote.rmi.RMIConnector.connect(javax/management/remote/rmi/RMIConnector.java:346)\njavax.management.remote.JMXConnectorFactory.connect(javax/management/remote/JMXConnectorFactory.java:270)\njava.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)\nJMX::MBean.create_connection(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/jmx4r-0.1.4/lib/jmx4r.rb:220)\nJMX::MBean.create_connection(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/jmx4r-0.1.4/lib/jmx4r.rb:220)\nJMX::MBean.create_connection(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/jmx4r-0.1.4/lib/jmx4r.rb:216)\nJMX::MBean.create_connection(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/jmx4r-0.1.4/lib/jmx4r.rb:216)\nJMX::MBean.connection(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/jmx4r-0.1.4/lib/jmx4r.rb:137)\nJMX::MBean.connection(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/jmx4r-0.1.4/lib/jmx4r.rb:137)\nRUBY.thread_jmx(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.4/lib/logstash/inputs/jmx.rb:217)\nRUBY.run(/opt/logstash-jmx/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.4/lib/logstash/inputs/jmx.rb:321)\njava.lang.Thread.run(java/lang/Thread.java:745)", :level=>:error}`

Why logstash can`t just skip problematic server and keep on processing metrics from all other servers?

**Comment by untergeek** [comment]
Please open this issue in https://github.com/logstash-plugins/logstash-input-jmx

The main logstash repository is for logstash core items, rather than plugins.
