### ISSUE TITLE
Release notes doc for GA should not mention betas/alphas/rcs.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6070]
https://www.elastic.co/guide/en/logstash/5.0/releasenotes.html

![2016-10-17-141101_473x329_scrot](https://cloud.githubusercontent.com/assets/131818/19455868/ad3c440a-9473-11e6-8ec7-e41318a07937.png)

For 5.0 GA, this page should not reference what changed in 5.0 alpha/beta/rc releases. Instead, it should prepare users for changes between 2.x and 5.0 and not mention prereleases.

**Comment by ph** [comment]
This seems to be fixed on the official site.
