### ISSUE TITLE
log4j default settings are unreasonable

### ISSUE THREAD

**Issue by dcode** [elastic/logstash#6073]
- Version: logstash 5.0.0-rc1
- Operating System: CentOS 7.2
- Config File (if you have sensitive info, please remove it): 100% defaults
- Sample Data: N/A
- Steps to Reproduce: Install the logstash-5.0.0-rc1 rpm

So, I support the move to log4j for all the reasons that I'm sure were given to motivate the change. And I'm going to try to focus on being constructive here because I just spent *hours* troubleshooting the fact that the setting for the log path changed from `path.log` to `path.log`. While mentioned in the beta1 release notes, you probably need to note this breaking syntax change that will prevent logstash from starting.

/sigh

Okay, so back to Log4J. After trying to figure out why logstash wasn't starting and finally figuring out the syntax error, logstash promptly told me that my log4j logs were being sent to `/usr/share/logstash/logs/`. I understand that `/usr/share/logstash` is `LS_HOME`, but this is an unreasonable and counter-intuitive location for log files. I think most sysadmins would expect this to be `/var/log/logstash` or even `/var/log`.

Rationale:

Various Filesystem Hierarchy Standards:
- [FreeBSD](https://www.freebsd.org/doc/handbook/dirstructure.html)
- [OpenBSD](http://man.openbsd.org/OpenBSD-current/man7/hier.7) (first defined for Version 7 Unix)
- [Linux](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html)

Security Engineering (sorry, don't have links for all of these, but you can plenty of people doing it):
- Many people like a read-only `/usr` filesystem, at the minimum a non-privileged user account shouldn't be able to modify these files (i.e. `logstash` user should not be able to modify anything under `/usr/share/logstash`)
- Applications like containers ideally have read-only layers of application homes. configuration data can be fed from `/etc/` and other transient data goes in `/var/` or `/run`. This reduces complexity and reduces shared container footprint.
- I hope to someday (in the not so distant future) create SELinux policies to constrain Logstash. Following the "standard" directory layout guidelines means fewer policy exceptions which means easier for other users to use and easier maintenance.

Sorry for the rant, and I hope it just conveys my frustration with this surprise. I'm filing this issue in an effort to make Logstash a better product.

**Comment by suyograo** [comment]
@dcode thanks for the feedback, appreciate it. Sorry about `path.log` to `path.logs` change across the pre-releases. Should have noted this in release notes.

Looking at the code, and with internal testing it looks like logs do go to `/var/log/logstash`. See https://github.com/elastic/logstash/blob/master/pkg/centos/after-install.sh#L6. 

I'll try a clean machine tomorrow, but definitely agree for package installs it should be in `/var/log/logstash` location not LS_HOME/logs.

**Comment by untergeek** [comment]
How are you launching Logstash?  You've installed via RPM on CentOS 7.2, but how are you starting?

The correct way to start Logstash in 7.2, if you've installed via RPM, is:

```
systemctl start logstash
```

Why does this matter? Because in `/etc/logstash/logstash.yml`, on CentOS 7, the defaults are automatically overwritten with those exact paths.  `path.logs` is set to `/var/log/logstash` for you.

If you are starting Logstash at the command-line, you will need to add `--path.settings /etc/logstash` so that this change is picked up.

I know this is a breaking change, but we did just barely update the documentation to reflect this better today.

**Comment by dcode** [comment]
I was initially using systemctl, but it was failing (due to the broken configuration). So, I tried the command line as executed by systemd (as close as possible): `sudo -u logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash`. This kept giving me an error that my `path.settings` was invalid, and `config.test_and_exit` wasn't helping either.

I guess the crack I slipped through was that the RPM didn't overwrite my `/etc/logstash/logstash.yml` config with pleaserun since the file already existed? I ended up deleting the `path.log` line when I realized this was what was probably causing the issue. Then `config.test_and_exit` told me logs were going to `/usr/share/logstash/logs`, which it conveniently created for me.

Thank you for the prompt response. Perhaps just need some smoother logic and/or documentation before the final 5.0.0 release to manage the upgrade from older versions. Since everything 5.x up to now it not production ready, it's probably sage advice to completely burn existing installations and reinstall fresh.

**Comment by untergeek** [comment]
https://www.elastic.co/guide/en/logstash/5.0/running-logstash.html
https://www.elastic.co/guide/en/logstash/5.0/config-setting-files.html
https://www.elastic.co/guide/en/logstash/5.0/dir-layout.html

Are these insufficient?

**Comment by suyograo** [comment]
@dcode Good point about upgrading from prerelease to GA. I'll note that in the docs, but there may be a legit bug about updating `logstash.yml` upon beta1 upgrade here.

**Comment by dcode** [comment]
The dir-layout page is wrong:

> logs  | Log files | /var/log/logstash | path.log

**Comment by untergeek** [comment]
@dcode Good catch.  Would you be willing to submit a PR with that doc fix? We have a Pioneer Program (see the label on this issue?) that results in a special _something_ for all those who participate.

**Comment by untergeek** [comment]
That said, @dcode, are the rest of the docs insufficient? Could we improve them somehow?

**Comment by dcode** [comment]
@untergeek I think the docs are generally fine (minus the typo, that I can get a PR for), but since this is a breaking change (the config parameter name), it should definitely be mentioned as such for people migrating from an older logstash config that will generate the strange situation I encountered.

With respect to RPM, the de facto approach is to generate a new default config and save it as `logstash.yml.rpmnew`. Of course, since you're using FPM + pleaserun, you lose that sort of configuration tracking in the %post-install hook. Ultimately I found my error by moving `logstash.yml` to `logstash.yml.bak` , generating a new one using the `system-install` script directly and running diff on the two. Maybe when running an upgraded package if there is an existing config, you could generate a `logstash.yml.dist` or something as a hint to people troubleshooting the situation.  ¯\_(ツ)_/¯

**Comment by dcode** [comment]
I'm not 100% sure on the x-ref to the Release Notes

**Comment by untergeek** [comment]
> Maybe when running an upgraded package if there is an existing config, you could generate a `logstash.yml.dist`

+1 to this idea.  I'll raise an issue for myself.

**Comment by suyograo** [comment]
@dcode fixed the docs issue: https://github.com/elastic/logstash/commit/72d14d870f301fda33dcf9d323fae8b468551f7e

**Comment by dcode** [comment]
Closing issue with better documentation and effort to ease upgrade with #6076
