### ISSUE TITLE
Make plugin descriptions consistent across the plugin docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6086]
We have multiple descriptions of Logstash plugins that appear in various places:
- In the overview tables in the doc (for example, the [Input plugins](https://www.elastic.co/guide/en/logstash/5.0/input-plugins.html) page).
- In the readme file for the plugin in GitHub (for example, the [logstash-input-beats](https://github.com/logstash-plugins/logstash-input-beats/blob/master/README.md) readme).
- In the Ruby Gems (for example, the [logstash-input-beats](https://rubygems.org/gems/logstash-input-beats) page on rubygems.com). This value comes from the `s.description` field in the gemspec.

We want to standardize on one description across plugins. Here's what we need to do:

Steps:
- [ ] Review and update the overview tables for each plugin to confirm that the overview tables contain the correct description of each plugin. Focus on Logstash-bundled plugins initially.
- [ ] Write a script that extracts the description in the table and uses it to populate the `s.description` field in the ruby gemspec. Whoever does the review of the overview tables should do a side-by-side comparison with the ruby gemspec to make sure no content is lost.

After we've done this, the `s.description` field in the ruby gemspec will become the authoritative short description to use for the plugin. The plugin build automation process will read from the gemspec files to generate the overview tables in the documentation.

**Comment by jordansissel** [comment]
I think we can work to resolve this more easily once the plugin-docs-to-asciidoc extraction has happened.

**Comment by jordansissel** [comment]
Following up here -- the asciidoc extraction will happen very soon, and we can work on this after. :)

**Comment by dedemorton** [comment]
@jsvd After talking to Andrew about this yesterday, I think we should revisit the idea of pulling the short description from the gemspec (when we spoke last, we talked about using the s.summary field instead of s.description, I think).

Andrew pointed out that we don't want to build dependencies on Ruby gems into our doc build process because what happens when we start building the docs for Java plugins?

Anyhow, I don't have a good answer at the moment, but wanted to bring it up as an issue for discussion.

**Comment by jsvd** [comment]
@andrewvc I think we should still use the gemspecs descriptions for a few reasons:
- we need a way to generate these tables automatically from a source of truth, and the only one we have right now is each plugin's repository
- java plugins and universal plugins will come soon but that doesn't impact this feature: whatever code calls a function to fetch the description of a plugin like `fetch_plugin_description(plugin_name, version)`, tha code can work with both maven, rubygems or any other plugin framework.

That said, outside of this automatization, I think it's worth taking the current descriptions from the asciidoc tables and push them to the individual plugin repos, as those are the ones we show the users. I have a script that scrapes the asciidoc for descriptions and changes the .gemspec file for each plugin repo.

**Comment by andrewvc** [comment]
@jsvd I think the universal plugin system should be the eventual source of truth, driven by some structured thing, but I agree with you as far as approach and incremental rollout.

**Comment by dedemorton** [comment]
closing because this issue is very old.
