### ISSUE TITLE
Bug in redis output

### ISSUE THREAD

**Issue by kavat** [elastic/logstash#6090]
Hi,
trying the version 5.0.0-rc1 of logstash we have this error on sending event to redis

[2016-10-19T13:44:47,688][WARN ][logstash.outputs.redis   ] Failed to send event to Redis {:event=>2016-10-19T13:44:39.000Z 127.0.0.1 pam_unix(sudo:session): session closed for user root
, :identity=>"default", :exception=>#<NameError: no method 'debug' for arguments (org.jruby.RubyHash,org.jruby.RubyHash) on Java::OrgApacheLoggingLog4jCore::Logger
  available overloads:
    (org.apache.logging.log4j.Marker,java.lang.String,org.apache.logging.log4j.util.Supplier[])
    (java.lang.String,java.lang.Object[])
    (org.apache.logging.log4j.Marker,java.lang.String,java.lang.Object[])
    (java.lang.String,org.apache.logging.log4j.util.Supplier[])>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/logging/logger.rb:41:in `debug'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-3.0.2/lib/logstash/outputs/redis.rb:216:in`connect'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-3.0.2/lib/logstash/outputs/redis.rb:241:in `send_to_redis'", "org/jruby/RubyProc.java:281:in`call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-3.0.2/lib/logstash/codecs/json.rb:42:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-3.0.2/lib/logstash/outputs/redis.rb:150:in`receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in`each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in`multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:302:in`output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in`output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:252:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:225:in`start_workers'"]}

Have we wrong in anything or is it a bug?

**Comment by IrlJidel** [comment]
Think this was fixed in 3.0.3 of plugin https://github.com/logstash-plugins/logstash-output-redis/commit/24635f635dce97257b2c1e3484275aacbd024ecc

**Comment by kavat** [comment]
Thanks, but I installed logstash from this guide:
https://www.elastic.co/guide/en/logstash/5.x/installing-logstash.html
I used apt mirror directly and I thought that this mirror was updated to the latest bugfix for all the components.
Is it not right?

**Comment by IrlJidel** [comment]
You're running 3.0.2 of plugin

/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-3.0.2/lib/logstash/outputs

**Comment by jordansissel** [comment]
Is this still an issue? If so, please open against the logstash-output-redis repo.
