### ISSUE TITLE
add logstash-input-udp performance regression fix to release notes

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6091]
@suyograo can we add the following to the release notes?

`logstash-input-udp 3.0.3 - fix performance regression calling IO.select for every packet`

This fixed a performance regression in place since logstash 2.x: https://github.com/logstash-plugins/logstash-input-udp/issues/21

changelog entry: https://github.com/logstash-plugins/logstash-input-udp/blob/master/CHANGELOG.md#303

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/commit/7e002ac9d34c2c0817ec4931cf63bf9b4ac172b1
