### ISSUE TITLE
Log level options when starting Logstash

### ISSUE THREAD

**Issue by alesnav** [elastic/logstash#6095]
- Version: 5.0.0-rc1
- Operating System: Centos 7.2
- Config File (if you have sensitive info, please remove it): N/A
- Sample Data: N/A
- Steps to Reproduce: `./bin/logstash --help`

If you executes `./bin/logstash --help` it shows that `--verbose`, `--debug` and `--quiet` are deprecated and you should use `--log.level=verbose` and so on.

The problem is that if you start Logstash with one of them as a parameter, it exits and shows this error:

```ERROR: option '--log.level': Invalid value "verbose". Options are: ["fatal", "error", "warn", "debug", "info", "trace"]```

How can I start the process with verbose enabled?

Thanks,
Best regards

**Comment by jordansissel** [comment]
`--log.level=info`

**Comment by jordansissel** [comment]
I see the mistake in the help output now, thank you for finding this! :)

**Comment by jordansissel** [comment]
https://github.com/elastic/logstash/pull/6104 should fix this. Manual testing:

```
% bin/logstash --help |& grep -A1 -- --verbose
    --verbose                     Set the log level to info.
                                  DEPRECATED: use --log.level=info instead.
```

**Comment by alesnav** [comment]
Thanks @jordansissel . I think that there is one more thing to fix:

```         quiet: |+
            Set the log level to info.
            DEPRECATED: use --log.level=quiet instead.```

Maybe `--log.level=quiet` neither works because of the following info:

`Options are: ["fatal", "error", "warn", "debug", "info", "trace"]`
