### ISSUE TITLE
Few updates for 5.0 breaking changes

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6098]
Two minor additions to the breaking changes list for 5.0.

- [ ] There are 15 plugins removed from 5.0 default bundle (https://github.com/elastic/logstash/pull/5899). These plugins can still be installed manually for use.
 - logstash-filter-clone
 - logstash-input-imap
 - logstash-input-irc
 - logstash-input-log4j
 - logstash-input-lumberjack
 - logstash-input-pipe
 - logstash-input-unix
 - logstash-input-xmpp
 - logstash-output-cloudwatch
 - logstash-output-exec
 - logstash-output-irc
 - logstash-output-pipe
 - logstash-output-sqs
 - logstash-output-statsd
 - logstash-output-xmpp

- [ ] The Logstash All Plugins download option has been removed. For users previously using this option as a convenience for offline plugin management purposes (air-gapped environments), please see the [Offline Plugin Management](https://www.elastic.co/guide/en/logstash/current/offline-plugins.html) documentation page.

**Comment by ppf2** [comment]
As part of this change, please also remove 

>Users who can work with a larger Logstash artifact size can use the Logstash (All Plugins) download link from the Logstash product page to download Logstash bundled with the latest version of all available plugins. You can distribute this bundle to all nodes without further plugin staging. 

from the [offline plugin management](https://www.elastic.co/guide/en/logstash/5.0/offline-plugins.html) page (which is still there in the 5.0, 5.x and  master docs) :)
