### ISSUE TITLE
Node JS client not connecting to LogStash 1.5.4 or 2.4.0

### ISSUE THREAD

**Issue by dcarissi** [elastic/logstash#6107]
I have a very strange problem with trying to get a Node JS client to connect with Logstash 1.5.4 or 2.4.0.  Everything is running on an Ubuntu 16.04.1 LTS VM.  I have Node version 6.9.1 installed, and I'm running Logstash from the command line so that I can switch between them.  My Logstash config is simple:
input {
  tcp {
    port => 5525
    ssl_cacert => "/root/workspace/certs/ibmlgshcombinedTEST6root.pem"
    ssl_cert => "/root/workspace/certs/ibmlgshTEST6server.crt"
    ssl_key  => "/root/workspace/certs/ibmlgshTEST6server.key"
    ssl_key_passphrase => "xxxxxxx"
    ssl_verify => "true"
    ssl_enable => "true"
    type => test_5525
  }
}
I also have my own sample client and server apps written in Java, Node and Ruby, all of which use the same set of key/cert files.  I can mix and match my "client" and "server" apps and I am able to connect.  When I try connecting to Logstash, the only client that is having a problem is Node.  The Logstash log file indicates <OpenSSL::SSL::SSLError: no cipher suites in common>.
I'm puzzled on why this is happening ... 
If you need more, please let me know.

ps.  I'm using IBM's JDK 1.8.0:
java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr2fp10-20160108_01(SR2 FP10))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20160106_284759 (JIT enabled, AOT enabled)
J9VM - R28_20160106_1341_B284759
JIT  - tr.r14.java_20151209_107110.02
GC   - R28_20160106_1341_B284759_CMPRSS
J9CL - 20160106_284759)
JCL - 20151231_01 based on Oracle jdk8u71-b15

In order to get Logstash to work with the IBM JDK, I had to touch the java.version.rb file.  At the bottom of this file, there is a this : 
parsed = parse_java_version(version_string)

and I added this line right after : 
return false unless parsed

**Comment by jordansissel** [comment]
I dont' think we test Logstash on IBM JDK, so I don't have much to offer here.

Let's focus the diagnosis on https://discuss.elastic.co/t/logstash-with-ibm-jdk-1-8-and-tls-connections/64571 as you filed already. If we determine this is a bug, we can move to this github forum.
