### ISSUE TITLE
LS 2.4 JDBC input errors: Cannot serialize instance of: Sequel::SQL::Blob

### ISSUE THREAD

**Issue by sempervictus** [elastic/logstash#6112]
- Version: 2.4.0
- Operating System: Ubuntu
- Config File (if you have sensitive info, please remove it):

```
input {
    jdbc {
        jdbc_validate_connection => true
        jdbc_connection_string => "jdbc:oracle:thin:@oradb:1521/orcl"
        jdbc_user => "system"
        jdbc_password => "Admin123"
        jdbc_driver_library => "/opt/ojdbc7.jar"
        jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
        statement => "SELECT * FROM V$ACTIVE_SESSION_HISTORY WHERE SAMPLE_TIME > :sql_last_value"
        last_run_metadata_path => "/tmp/logstash-oradb.lastrun"
        record_last_run => true
        schedule => "*/2 * * * *"
       }
}
filter {
    # Set the timestamp to that of the ASH sample, not current time.
    mutate { convert => [ "sample_time" , "string" ]}
    date { match => ["sample_time", "ISO8601"]}
}
output {
    #stdout { codec => rubydebug }
    elasticsearch {}
}
```
- Sample Data: Contents of V$ACTIVE_SESSION_HISTORY
- Steps to Reproduce: Follow ElasticCo tutorial @ https://www.elastic.co/blog/visualising-oracle-performance-data-with-the-elastic-stack

Looks like the JDBC input is bastardizing data, there's no BLOB data in the stats output of Oracle far as i know, and the error says nothing about _what data_ actually caused the failure

**Comment by guyboertje** [comment]
We use a Ruby library called Sequel to do the underlying handling of the data source. Please be aware that JDBC is already a kind of abstraction and then Sequel is another layer.
These datatypes get treated as a Blob:
```
        :BINARY => :Blob,
        :BLOB => :Blob,
        :LONGVARBINARY => :Blob,
        :VARBINARY => :Blob
```
We will be fixing the handling of Blob and Object Java class instances shortly.

In the meantime:
In your V$ACTIVE_SESSION_HISTORY table, could it have a binary encrypted password field?
I suggest you replace the `*` in your query to use fields that are of more regular DB datatypes.

**Comment by sempervictus** [comment]
We checked the schema and there are no binary fields in the table, plus, it works for several cycles, then locks up. It looks like the middleware is mishandling a datatype into a blob.

**Comment by sempervictus** [comment]
@guyboertje: any suggestions on how we can debug the pipeline to determine which field is coming back with the wrong data type?

**Comment by guyboertje** [comment]
When the error actually occurs, the code is deep inside the Java event and the key (field) is not known.
Are you able to modify the ruby code in the LS install, I.e. do you have a dev system set up? We would need to add a log statement to output the field if the value class name is Blob.
Alternatively, you could try divide and conquer by specifying half the fields, the half again until the field is found. This may not trigger the bug though if it is in the Sequel.

**Comment by sempervictus** [comment]
I've tried pruning the fields, and even reducing it down to a single field, and the error still occurs. Marshalling problem? Whats interesting is that disabling the ES output seems to stop it.

**Comment by guyboertje** [comment]
What is the SQL data type of the single field?

I'm confused about disabling the ES output. Try stdout with json codec. My guess would be that making it JSON triggers it.

**Comment by sempervictus** [comment]
Even an int will do it, will recreate the env and determine whether it
throws this exception on json-only output.

**Comment by guyboertje** [comment]
Actually, now that I look at the title of this issue - it **is** when serializing.

I think we should take a step back. It is clear that the set up in the blog article worked, so we need to track down what is different.

Are you using `Oracle 12c (12.1.0.1.0)`?

Does the View `V$ACTIVE_SESSION_HISTORY` contain different columns than the one from the article?

You might try Logstash 2.2.0 - the same version as used in the article https://www.elastic.co/blog/visualising-oracle-performance-data-with-the-elastic-stack

**Comment by jordansissel** [comment]
Please move this to the JDBC input plugin repo.

**Comment by guyboertje** [comment]
Moved to plugin. See https://github.com/logstash-plugins/logstash-input-jdbc/issues/177
