### ISSUE TITLE
Logstash S3 input doesn't recognise AWS region us-east-2

### ISSUE THREAD

**Issue by AlanKK** [elastic/logstash#6113]
Logstash v2.2.4

The error:
Invalid setting for s3 input plugin:

  input {
    s3 {
      # This setting must be a ["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "sa-east-1", "us-gov-west-1", "cn-north-1"]
      # Expected one of ["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "sa-east-1", "us-gov-west-1", "cn-north-1"], got ["us-east-2"]
      region => "us-east-2"
      ...
    }
  } {:level=>:error}
Error: Something is wrong with your configuration. {:level=>:error}

My configuration:
    s3 {
        bucket => "mybucketname"
        access_key_id => "key"
        secret_access_key => "secret"
        region => "us-east-2"
        prefix => "AWSLogs/89318..."
        type => "sometype"
    }

**Comment by jordansissel** [comment]
Please open this on https://github.com/logstash-plugins/logstash-input-s3/issues
