### ISSUE TITLE
How to build a Logstash xxxxx plugin guides using 1.x runtime dependencies in examples

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6124]
https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html#_runtime_amp_development_dependencies and https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_codec_plugin.html#_add_a_literal_gemspec_literal_file_2

The above guide still gives a logstash-core runtime dependecy example for the 1.x release: 

```
  s.add_runtime_dependency 'logstash-core', '>= 1.4.0', '< 2.0.0'
```

We should update it to the appropriate version, eg. for 5.0 (current), use something like below?

```
  s.add_runtime_dependency 'logstash-core', '>= 5.0.0', '< 6.0.0'
```

Same thing with jar dependency example:

https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html#_jar_dependencies

It's showing a ES jar dependency for ES 1.4.0 version which is ancient :)

Note that the logstash-core is a higher priority doc issue for this will cause gem building to fail on 5.0 if users follow the examples in the guides.

This applies to all 4 "How to build a Logstash xxxxxx plugin" sections in our guide.

**Comment by dedemorton** [comment]
Fixed in PR #6191
