### ISSUE TITLE
Document ES output workers removal in breaking changes

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6125]
The workers setting is a very commonly used setting for the Logstash Elasticsearch output in pre-5.0 versions.  Pipelines with this setting set will no longer start up on Logstash 5.0 and users will now have to use the pipeline.workers setting at the pipeline-level instead.  This will likely break the pipeline for a lot of users upgrading to 5.0.  Will be nice to document.

**Comment by dedemorton** [comment]
Fix added in PR #6141
