### ISSUE TITLE
LS 5.0 breaks standalone instances use-case

### ISSUE THREAD

**Issue by atnak** [elastic/logstash#6134]
**Operating system:** CentOS 6.5 (installed via the RPM `logstash-5.0.0.rpm`).

With LS 2.3.4 one could run multiple modular instances of logstash with:

```
/opt/logstash/bin/logstash agent -e "$CONFIG" -l "$LOG_FILE"
```

It's not very clear from documentation how the same is achieved in LS 5.0.

This is what I've figured:
- Need for the `agent` argument is now just gone
- `--path.settings` [must](https://www.elastic.co/guide/en/logstash/5.0/breaking-changes.html#_application_settings)  be specified
- A file named `logstash.yml` must be under this directory
- A file named `log4j2.properties` must be under this direcctory
- The `-l` option is no longer treated as a file path but rather how ever `${sys:ls.logs}` is used inside `log4j2.properties`.  If one copies the file created by the package install to `/etc/logstash/log4j2.properties`, this becomes a directory path.
- On the other hand, `log4j2.properties` can be a copy of `/dev/null` in which case `-l` can be disregarded altogether as all outputs go to _stdout_ regardless.
- The `path.data` should be specified to some place for the module that's writable.  This can be done through the `--path.data` command option or in the aforementioned `logstash.yml` file.

Does this sound about right?

Putting it together, the following is what one needs to do to get the same thing in LS 5.0.

``` bash
(
WORK_DIR=$(mktemp -d)
trap "rm -r -- '$WORK_DIR'" EXIT
touch "$WORK_DIR/logstash.yml" "$WORK_DIR/log4j2.properties"
/usr/share/logstash/bin/logstash --path.settings "$WORK_DIR" --path.data "$WORK_DIR" -e "$CONFIG" >"$LOG_FILE"
)
```

Even then, it's not the same as the former stdout and log outputs are now mixed into one.  However, I'm sure this can be rectified with some effort configuring log4j2.properties.

**Comment by untergeek** [comment]
What operating system are you using?

**Comment by atnak** [comment]
OS is CentOS 6.5 and installed from the RPM version (`logstash-5.0.0.rpm`).

**Comment by untergeek** [comment]
@atnak would you be ill disposed to using upstart in CentOS 6? There are new ways that are built-in to logstash to isolate these items and have upstart do the start/stop/restart thing it's good at.

**Comment by atnak** [comment]
@untergeek I have to admit I wasn't aware of what `upstart` is and had to look it up.  I still don't have a clear understanding of its practical usage (especially the isolation part) so I'm at a doubt on how viable it is.

Please let my outline my use case:

* I run multiple instances of `logstash`, each with their own data source and configuration.
* These instances can be started and stopped independently.
* More instances (data sources) can be added and then removed independently.
* These instances can be created, modified, started and stopped without super-user or a restricted user (e.g. a 'logstash' user) privilege.
* These instances log to their own separate log files.
* The configuration and scaffolding for these instances are placed in files under their own directories (or directory per multiple instances) that can be version controlled, packed up and moved to a different server to restart there.

* Aside: Many of these data sources are just plain `tail -F` on a log file, piped into scripts that format and jsonify.  `logstash` usually just pipes `stdin`, does some filtering/mutating, and writes to ES.

**Comment by untergeek** [comment]
If you do have to keep the instances start-able as a non-privileged user, then upstart is not going to be a good fit for you.  Truthfully, even using the package install is not a terrific fit for you at this point, but it can be made to work.

What you've outlined is a pretty good start.  You do need a `--path.settings` for each separate instance of Logstash you want to run, and with it `--path.data`, and the log4j settings file, as outlined.  At present, the one thing you cannot have separately is the `jvm.options` file.  If you have the package installed (not the tarball), it will look at `/etc/logstash/jvm.options` for _all_ instances.  However, since you're starting from the command-line, you should still be able to manually set `LS_JAVA_OPTS` and it will work the same that way. And lastly, of course, make sure that any paths (logs or data) used are writable by the user which will start Logstash.

**Comment by atnak** [comment]
Thanks @untergeek!  That's exactly the kind of insight I was looking for.

FWIW, I'm using the package install because of its ease of installation and update.
