### ISSUE TITLE
How to stop processing a specific file

### ISSUE THREAD

**Issue by gubr123** [elastic/logstash#6135]
Logstash version is 2.3.4

Can I stop processing logs from specific file? 
lets say the logstash already passed to elasticsearch half of the logs in the text file.
can I stop the processing in the middle and then "play" it again?

Thanks.

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
