### ISSUE TITLE
Can't install plugins on fresh Logstash v5 install

### ISSUE THREAD

**Issue by JorisAndrade** [elastic/logstash#6136]
Hi,

When I try to install a plugin in Ubuntu 16.04 I get a 

/usr/share/logstash/bin# ./logstash-plugin install logstash-filter-multiline
Validating logstash-filter-multiline
Installing logstash-filter-multiline
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
Error Bundler::InstallError, retrying 2/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported

Any ideas ?

Thanks in advance !

**Comment by suyograo** [comment]
this is usually transient and related to RubyGems.org. Can you try again?

I was able to successfully install it, multiple times.

```
suyog@machine:/tmp/logstash-5.0.0$ bin/logstash --version
logstash 5.0.0
suyog@machine:/tmp/logstash-5.0.0$ bin/logstash install logstash-filter-multiline
ERROR: Unknown command 'install'

See: 'bin/logstash --help'
suyog@machine:/tmp/logstash-5.0.0$ bin/logstash-plugin install logstash-filter-multiline
Validating logstash-filter-multiline
Installing logstash-filter-multiline
Installation successful
```

**Comment by JorisAndrade** [comment]
Was linked to https://github.com/elastic/logstash/issues/6044
