### ISSUE TITLE
YUM / APT wrong download urls

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#6137]
Source: https://www.elastic.co/guide/en/logstash/5.0/installing-logstash.html

The base url is wrong:

```
baseurl=https://artifacts.elastic.co/packages/5.x-prerelease/yum
```

This causes logstash to download rc1 instead of 5.0.  This should be fixed to the following:

```
baseurl=https://artifacts.elastic.co/packages/5.x/yum
```

<img width="949" alt="screen shot 2016-10-27 at 09 38 38" src="https://cloud.githubusercontent.com/assets/1675411/19767685/51d7f2b2-9c2a-11e6-9a0d-3b27635a2314.png">

**Comment by suyograo** [comment]
Fixed in  57ddd9f
