### ISSUE TITLE
Duration in missing seconds in the pipeline stats and the filter stats should be close

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6139]
> This is a recent metrics json capture from 5.0 release with Dissect installed.
> The log file being read is 2.12 GB, each line is 222 characters long excl newline.
> 
> Does the pipeline duration seem wrong when compared to the filter duration?
> 18080.05 seconds = 301.33 minutes = 5:01:20 hours.
> 750.972 seconds = 12:00 minutes.
> 
> ES shows first event at 11:46:59.737
> and last at 12:39:07.040
> difference of 3128 seconds = 52:08 minutes

```
{
"host": "onyx6",
"version": "5.0.0",
"http_address": "127.0.0.1:9600",
"pipeline": {
"events": {
"duration_in_millis": 18080057,
"in": 9502272,
"filtered": 9502272,
"out": 9502272
},
"plugins": {
"inputs": [],
"filters": [
{
"id": "dissect_81200653ac1de43ba0e2d41c2404c53e4f705eba-2",
"events": {
"duration_in_millis": 750972,
"in": 9502272,
"out": 9502272
},
"name": "dissect"
}
],
"outputs": [
{
"id": "81200653ac1de43ba0e2d41c2404c53e4f705eba-3",
"events": {
"in": 9502272,
"out": 9502272
},
"name": "elasticsearch"
}
]
},
"reloads": {
"last_error": null,
"successes": 0,
"last_success_timestamp": null,
"last_failure_timestamp": null,
"failures": 0
}
}
}
```

**Comment by ph** [comment]
@jsv @guyboertje yup the time seems wrong I am looking into it.

**Comment by ph** [comment]
@guyboertje Does your machine has 6 core?

**Comment by ph** [comment]
The pipeline `duration_ms` of  has the current following definition.

- its an ever increasing counter.
- batch oriented, the Time it takes for a batch to go through the the filters + Output stage (in this case: Dissect, ES)
- Its value is the aggregation of the time for each worker. 
- The time start at the `take_batch` and end at `close_batch`

The `duration_ms` for a filter plugin has a similar definition:
- Its the time it take for an array of events to go through `multi_filter(events)`
- Is an ever increasing counter.
- The time start before the call of `multi_filter(events)` and end after the call.
- its value is incremented with from all the worker threads.

Derivatives can be used to get the rate of the change for the time.

If you run your benchmark with the following scenario and share the numbers.

- With dissect and null plugin, the pipeline and the plugin should be really close.
- Without dissect but with ES

**Comment by ph** [comment]
Another things, I guess logstash and ES are on the same machine?

**Comment by guyboertje** [comment]
Correct - 6 cores.
ES and LS on the same box.

Thanks for the explanation, it makes more sense now (sort of).
301.33 minutes / 6 cores = 50 minutes 13 seconds.

But Dissect accumulative of 12 minutes then implies 2 minutes average for the filter stage - what was LS doing for the other 48 minutes? Input and output obviously - but in what proportion.

However, if we ever have variable workers, say for throttling, how would the user make sense of the the `duration_in_millis` value.

**Comment by ph** [comment]
@guyboertje I've discussed that later yesterday with @jordansissel we will add the time for the output collected at the delegator level this will helps us show the proportion or work.

**Comment by ph** [comment]
This is done in master.
