### ISSUE TITLE
Logstash uppercase MONTH

### ISSUE THREAD

**Issue by mostolog** [elastic/logstash#6143]
Hi

Using just-released logstash 5.0.0 and having the following time string:

> 03/ene/2016 11:52:14

When I try to grok it with:

> %{MONTHDAY}/%{MONTH}/%{YEAR} %{HOUR}:%{MINUTE}:%{SECOND}

It fails with _grokparsefailure. Stdout prints.

> "time_generated"=>"_03/Ene/2016 11:52:14"

So I suspected as "Ene" (First letters for January in spanish) aren't part of %{MONTH} I could use %{WORD} instead. **Have you considered adding _localized_ string for weekdays, months...?**

One step later, with %{WORD} workaround successfully parsing it, when I try to use date filter:

```
    date {
            locale => "es"
            timezone => "Europe/Madrid"
            match => ["time_generated", "dd/MMM/YYYY HH:mm:ss"]
        }
```

I'm getting a date parsing error. I then I realized months aren't written capitalized on spanish.

Why is logstash changing "ene" to "Ene"?

**Comment by jordansissel** [comment]
I'm confused. Your `time_generated` field has `Ene` capitalized -- it doesn't look like logstash did this? You didn't include your full config, so I can't comment further without more details.

**Comment by mostolog** [comment]
TBH: I have been trying to reproduce this issue, but I haven't been able so far...

**Comment by mostolog** [comment]
Hi.

I haven't been able to reproduce the uppercasing issue, but detected problem when trying to parse English dates using locale="es". I'll ask on list, thanks for your help.
