### ISSUE TITLE
/etc/init.d/logstash doesn't exist after installing with apt-get on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by mattharrington001** [elastic/logstash#6147]
**SUMMARY:**
/etc/init.d/logstash doesn't exist after following the instructions on https://www.elastic.co/guide/en/logstash/current/installing-logstash.html to install logstash 5.0 with apt-get on Ubuntu 14.04.4.

**REPRO:**
ubuntu@ip-172-31-44-56:~$ **sudo apt-get install logstash**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  logstash
0 upgraded, 1 newly installed, 0 to remove and 53 not upgraded.
Need to get 106 MB of archives.
After this operation, 198 MB of additional disk space will be used.
Get:1 https://artifacts.elastic.co/packages/5.x/apt/ stable/main logstash all 1:5.0.0-1 [106 MB]
Fetched 106 MB in 9s (11.3 MB/s)                                               
Selecting previously unselected package logstash.
(Reading database ... 54784 files and directories currently installed.)
Preparing to unpack .../logstash_1%3a5.0.0-1_all.deb ...
Unpacking logstash (1:5.0.0-1) ...
Setting up logstash (1:5.0.0-1) ...
Using provided startup.options file: /etc/logstash/startup.options
Sending all logs to /tmp/tmp.TYSHLmR3Ti
Successfully created system startup script for Logstash
ubuntu@ip-172-31-44-56:~$ **sudo update-rc.d logstash defaults 95 10**
update-rc.d: /etc/init.d/logstash: file does not exist
ubuntu@ip-172-31-44-56:~$ **sudo ls -la /etc/init.d/logstash**
ls: cannot access /etc/init.d/logstash: No such file or directory

**Comment by untergeek** [comment]
This is because Logstash automatically detects the startup system of the system in use and deploys the correct startup scripts.

For Ubuntu 14.04, that is [upstart](https://www.elastic.co/guide/en/logstash/current/running-logstash.html#running-logstash-upstart), so you need to run `sudo initctl start logstash`

**Comment by untergeek** [comment]
The full documentation is at https://www.elastic.co/guide/en/logstash/current/running-logstash.html

**Comment by arun2arunraj** [comment]
@untergeek : I am using CentOS 6.7 which supports Upstart and SysV. But I am getting Upstart pattern only. How to override and get SysV kind of startup ? Or Could you provide / share me the script ?

**Comment by untergeek** [comment]
@arun2arunaj There will be a way to manually add SysV scripts in 5.2.  See #6338
