### ISSUE TITLE
PeriodicPoller timeout error in the log

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6160]
When the Periodic Poller that run the stats collection for the JVM/OS timeout it will log the message using the `error` level. 

Under a Logstash running really high throughput this can be a problem when resource starvation occurs, and this error can appear in the log. 

I see two solutions:

A. We make the call never timeout and just block until it can receive the details.
B. We change the log level for debug.

I am more in favor of B.

**Comment by ph** [comment]
related to https://discuss.elastic.co/t/logstash-poller-error-concurrent-timeouterror-logstash-5-0-0-beta1/62448

**Comment by michaelburn** [comment]
Hi, I've the same issue with Logstash 5.0.0.
I tried to get rid of these events by modifying the log4j.properties file like this:
...
logger.logstash.instrument.periodicpoller.jvm = fatal
...
But I can't get this to work. Does anybody have the right configuration-entry to exclude the events from the Logstash-Logfile?

Thanks
