### ISSUE TITLE
Cannot install plugins on ubuntu 14.04 with Logstash 5.0.0

### ISSUE THREAD

**Issue by pvencill** [elastic/logstash#6162]
Clean Ubuntu 14.04 system, followed the install guide for Logstash.  Trying to run sudo bin/logstash-plugin install <any plugin> yields the error:

```
Installing logstash-input-beats
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```

I am behind a corporate proxy, but have configured same in the environment and have also tried passing it in the command as `sudo http_proxy=http://example.com:80/ bin/logstash-plugin install <plugin>`.  I have tried adding --no-verify in case there's an issue with untrusted certs or the like, for testing.

**Comment by ph** [comment]
This is a known issue, you need an additional file to make it work.

Can you try this comment and see if it work for you? https://github.com/elastic/logstash/issues/6044#issuecomment-253854228

**Comment by pvencill** [comment]
Ok, this only worked when I installed it at ~/.m2/settings.xml rather than ~/root/.m2/settings.xml.  But it worked.  Thanks!
