### ISSUE TITLE
logstash crashing on providing database attribute for geoip

### ISSUE THREAD

**Issue by darshanime** [elastic/logstash#6167]
I am running logstash:latest in a docker container. It hangs up without any error on using paths. If I comment out the paths(`geoip->database` or I don't use `grok->pattern`) in my logstash.conf (provided below), it works fine.

- Version: logstash:latest
- Operating System: Ubuntu 14.04
- Config File (if you have sensitive info, please remove it):

**patterns/django**:
```
DJANGO_LOGLEVEL (DEBUG|INFO|ERROR|WARNING|CRITICAL)
```
**logstash.conf**:
```
input {
    udp {
        port => 55555
        codec => json
    }

    tcp {
        port => 55554
        codec => json
        type => "devknox"
	}

    syslog {
        port => 54320
        type => "django"
    }
}

filter {

     if [type] == "django" {
        grok {
          patterns_dir => "/etc/logstash/patterns"
          pattern => "%{DJANGO_LOGLEVEL}"
        }
    }

     if [type] == "devknox" {

        geoip {
          source => "userip"
          target => "geoip"
          database => "/etc/logstash/GeoIP/GeoLiteCity.dat"
          add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
          add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
        }

        mutate {
          convert => [ "[geoip][coordinates]", "float"]
        }
     }
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}
```
Logstash exits with this:
```
logstash_1       | Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties.
elk_logstash_1 exited with code 1
```
It writes no logs to `/var/log/logstash`
```
--> dc run logstash ls -l /var/log/logstash/
total 0
```

Here is the Dockerfile for ref:
```
FROM logstash:latest
COPY ./config/logstash.conf /etc/logstash/conf.d/logstash.conf
COPY ./GeoLiteCity.dat /etc/logstash/GeoIP/GeoLiteCity.dat
COPY ./patterns/django /etc/logstash/patterns/django
```

It also doesn't seem to take the settings from command line. I start my logstash container with in my `docker-compose.yml`:
```
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf --log.level trace
```

**Comment by talevy** [comment]
since these two paths seem to be related to the error, are you sure you have the Docker system set up correctly? have you tried these same configs outside of Docker?

**Comment by talevy** [comment]
also, I recommend you check out the Docker image (`docker.elastic.co/logstash/logstash:5.0.0`) that is mentioned here:

https://github.com/elastic/logstash-docker#image-tags-and-hosting

the `logstash:latest` will pick up another, not maintained by Elastic, docker image

**Comment by jarpy** [comment]
To help with debugging, I don't think you will find the logs that way. The `docker-compose run` command runs in a fresh container each time, so the `ls` won't find any output from the Logstash process that ran in a previous container. For example:

```
$ echo 'test: { image: alpine }' > docker-compose.yml
$ docker-compose run test touch /telltale
$ docker-compose run test stat /telltale
stat: can't stat '/telltale': No such file or directory
```

This is one of the reasons that Elastic's Logstash Docker image (linked by @talevy) logs only to STDOUT by default. Managing file-based logs in ephemeral containers is a tricky proposition. So, if you choose to switch to the Elastic image, there really won't be any logs on disk unless you explicitly configure them.

**Comment by darshanime** [comment]
@jarpy, thanks for the tip! I was under the impression that if the container is running already, it won't run the command in a new clone, but the original one. 

@talevy, I have switched to the official image and I can see the logs in my STDOUT. However, it logstash refuses to accept the GeoIP file. I get it using: 
```
curl -O "http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"
gunzip GeoLiteCity.dat.gz
```

**Comment by jarpy** [comment]
I think you might need the newer GeoIP database format.

http://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by darshanime** [comment]
Yup, that works. Thank you for the pointers. Can be closed?

**Comment by talevy** [comment]
sounds good, glad you resolved your issue!

**Comment by jarpy** [comment]
Glad to help. It's always good to get someone "unstuck". 👍
