### ISSUE TITLE
Do not require logstash.yml when bootstrapping Logstash

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6170]
5.0.0 required Logstash to have a valid `logstash.yml` before it could start successfully. This was mostly fine for users who installed Logstash via `tar.gz`, but many many folks who install it via packages still start Logstash manually. Also, our documentation uses `-e` flag for getting started on Logstash and sending their first event. 

Initially, I thought we could disable settings for `-e` -- like we do now for `--help`, but this list can grow and it makes it hard to do this reliably across the bootstrap levels. (agent, runner, loader). 

`logstash.yml` has only defaults defined, and there is no required parameter to start Logstash. We should be able to use the defaults if no `logstash.yml`. Obviously, this is not ideal from a user point of view, so we should log a warning but continue to bootstrap.

**Comment by untergeek** [comment]
One of the biggest, ugliest things here is that Logstash is unhappy without a log4j settings file.  Perhaps we should have some kind of default log4j that spews to console if none is found.  That will take care of one of the other cases.

**Comment by suyograo** [comment]
@untergeek I have a fix for that as well. Log4j will use a default config which logs to console when no `log4j2.properties` is found.
