### ISSUE TITLE
Logstash not recognizing changes to config file

### ISSUE THREAD

**Issue by pvencill** [elastic/logstash#6171]
I have two inputs I'm trying to configure for my ELK setup, and after failing to get the first one (based on logstash-input-cloudwatch plugin) working, I decided to work with the second one (based on logstash-input-filebeat).  The problem is that after changing my config file to configure the second one, and restarting the logstash service successfully, `/var/log/logstash/logstash.log` is still getting new entries (errors) for the cloudwatch plugin which clearly shows the old config for it.  

- Version: 5.0.0
- Operating System:  Ubuntu 14.04
- Config File (if you have sensitive info, please remove it):

```
input{
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => "localhost:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[metadata][type]}"
  }
}

```
- Sample Data:
`{:timestamp=>"2016-11-02T11:27:58.708000-0400", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::CloudWatch metrics=>[\"CPUUtilization\"], filters=>{\"tag:Monitoring\"=>\"Yes\"}, region=>\"us-east-1\", namespace=>\"AWS/EC2\", aws_credentials_file=>\"/home/pvencill/.aws/credentials\", codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">, use_ssl=>true, statistics=>[\"SampleCount\", \"Average\", \"Minimum\", \"Maximum\", \"Sum\"], interval=>900, period=>300, combined=>false>\n  Error: No metrics to query", :level=>:error}`

- Steps to Reproduce:
This is a fresh install of Logstash (and plugins and related services) with nothing but the two config files used.  I created the cloudwatch based one first, found it not working, deleted it and replaced it with the filebeat based one, and then restarted the logstash service.  As shown above, when I `tail` the logstash.log file, I am still getting errors on the cloudwatch plugin, and no data either way regarding the filebeat one.

**Comment by talevy** [comment]
which version of Logstash are you running? you list `5.0.1`, but that is not out yet

**Comment by pvencill** [comment]
Sorry, I went quick on that.  It's 5.0.0 (dpkg -s returned 5.0.0-1 and my brain transposed digits).

**Comment by pvencill** [comment]
Just another datapoint, restarting the logstash service did not bring in the new config, but it appears restarting the server itself may have.  I say "may have" because I no longer get the error output shown above, but there's no actual new entries in `logstash.log`, so I'm not receiving filebeats from the other machine either b/c the new config hasn't been pulled in, or because the other machine isn't sending them correctly.

**Comment by jakelandis** [comment]
Closing this as non-actionable. Only major bug fixes are getting ported to 5.x and 6.x has substantial changes w/r/t how pipelines are loaded and reloaded.  I don't believe this is a major bug due since others are not reporting it as well. I have personally tested reloading of pipelines in 6.x and they work as expected (sans a couple other minor issues logged).
