### ISSUE TITLE
Documentation issue regarding elastic supported/unsupported filters

### ISSUE THREAD

**Issue by mostolog** [elastic/logstash#6181]
Hi

https://www.elastic.co/guide/en/logstash/current/filter-plugins.html is divided into:
- Elastic supported plugins
- Community supported plugins

The first supported plugin is **aggregate**, however when you click on it (browse to https://www.elastic.co/guide/en/logstash/current/plugins-filters-aggregate.html) it states:

_This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running bin/logstash-plugin install logstash-filter-aggregate._

Could someone have an eye on this?
Thanks.

**Comment by jordansissel** [comment]
We are working on fixing the problem.

**Comment by suyograo** [comment]
This has been fixed. The banner has been removed
