### ISSUE TITLE
Queue Monitoring API

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#6182]
With the addition of the new durable queueing infrastructure, it is time to add some monitoring for these structures!

> [P1](https://github.com/elastic/logstash/issues/5638)
> add monitoring info and API to expose PQ stats

thanks to @suyograo, we have an initial proposal on some metrics we wish to include:

| Metric Type | Metric Name | Description |
|- |- |- |
| metadata | type | the type of queue [persisted, memory]
| metadata | page_capacity_bytes | size (in bytes) of page size for the durable queue
| disk | path | directory where the queue data can be found on disk |
| disk | fs_type | the file-system where the queue data is being written to (e.g. ext4) |
| disk | total_bytes | total size of partition queue is located in |
| disk | available_bytes | extra unused space queue can grow into |
| disk | used_bytes | size, in bytes of the queue data |
| disk | pages | number of live pages used to store events |
| io_stats | reads_per_sec | number of read operations per second |
| io_stats | writes_per_sec | number of write operations per second |
| io_stats | read_kb | total kilobytes read from disk |
| io_stats | write_kb | total kilobytes written to disk |
| events | queued_flushed | number of events unread from queue that are committed to disk |
| events | queued_unflushed | uncommitted events queued up in memory to be flushed to disk |
| events | processed | number of events that have been popped/relinquished from queue |
| events | in_flight | number of events that are currently being operated on within the pipeline (being processed) |
| events | max | max events count that can be stored in the bounded queue |
| events | acked | **not sure, help!** |

These stats should be available via the API

**Comment by talevy** [comment]
One aspect that is not listed above is that of a sort of `iowait`. capturing a metric to signal that the queue has reached max-write capacity, and we are blocked on writes until the pipeline pops more events.... or maybe the queue is empty, and we are waiting on popping.

**Comment by colinsurprenant** [comment]
A few comments on the events type:
- **queued_flushed** / **unflushed** : I would defer these 2 metrics.
- **processed** : number of processed and acked events since startup
- **in_flight** : number of read and unacked events
- **max** : I suggest we name it "capacity" and this capacity will be either a max number of events or max number of bytes, which should be a multiple of the page size.
- **acked** : I don't think we need this

I suggest adding:
- **unread** : number of unread event in the queue

**Comment by suyograo** [comment]
I was thinking we should add this to `_node/stats`

```
queue {
  "type": "persisted"
  "page_capacity_bytes": "25000000"
  data {
    "path" : "/Users/suyog/bin/logstash-5.0.0/data/queue",
    "type" : ext4
    "total_in_bytes":
    "free_in_bytes"
    "available_in_bytes"
    io_stats {
      "read_operations":
      "write_operations":
      "operations":
      "read_kilobytes":
      "write_kilobytes":
    }
  }
  "events" {
    "remaining":
    "processed":
    "acked":
    "max":
  }
}
```
