### ISSUE TITLE
Logstash 5.0 s3 input plugin doesnt work

### ISSUE THREAD

**Issue by saravsathyamoorthy** [elastic/logstash#6189]
- Version: logstash 5.0
- Operating System: Mac
- Config File (if you have sensitive info, please remove it): s3 input plugin
- Sample Data:
- Steps to Reproduce:
1. Have logstash conf to have s3 input plugin
2. Gives a error saying the aws sdk version 2.3 has thrown a error. aws sdk 2.3 has a different namespace
Resolution: i uninstalled the aws sdk 2.3 gem adn it resolved the issues as the older aws sdk is also included and it got picked up.

**Comment by ph** [comment]
I've used the official LS 5.0 release on my mac with the following config, and I was able to download and parse the file from my s3 bucket. I do not see any error related to the aws sdk, both of the version can coexist and be used by different part of the code.

Would you mind sharing your complete configuration without your credentials of course and the log output when you start logstash in with the debug log level. `--log.level debug`

**Config**
```input {
    s3 {
        access_key_id => "XXX"
        secret_access_key => "XXX"
        bucket => "ls-ph-test"
    }
}

output {
    stdout {
        codec => json_lines
    }
}

**Comment by moesy** [comment]
My error might be related (except running on Amazon LInux) I initially had an error similar to @saravsathyamoorthy however when I changed my config file to not include access and secret key (hope to use IAM Profile instead) I receive the following error:

`{:timestamp=>"2016-12-14T03:53:00.190000+0000", :message=>"Using milestone 1 input plugin 's3'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more informatio$
{:timestamp=>"2016-12-14T03:53:00.438000+0000", :message=>"Using milestone 2 output plugin 'elasticsearch_http'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2-$
{:timestamp=>"2016-12-14T03:53:07.458000+0000", :message=>"+---------------------------------------------------------+\n| An unexpected error occurred. This is probably a bug.   |\n| You can find help with this problem in a few places:    |\n|   `

**Comment by moesy** [comment]
Ultimately solved this was because I was running the 5.1 stack with java 1.7 plus some minor config changes across versions with regards to how the output bracket is setup it should be as shown bellow. 

```
output {
  elasticsearch {
        hosts => ["https://url:port"]
        user =>"user"
        password =>"pass"
        action => "index"
  }
}

```

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by jsvd** [comment]
since it seems the problem was fixed by using jdk8, I'll close it, please reopen if problem still occurs
