### ISSUE TITLE
`manage_template` ignores `index` and creates `logstash-*` regardless

### ISSUE THREAD

**Issue by atnak** [elastic/logstash#6193]
**Version:** Logstash 5.0.0 (installed via RPM on CentOS 6)

### Problem in brief

Despite [what the documentation says](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-manage_template) template management seems to ignore the setting for `index` and always creates templates matching the pattern `logstash-*`.

### Steps to reproduce

I can reproduce the problem with the following command:

```bash
$ touch /tmp/logstash.yml /tmp/log4j2.properties && /usr/share/logstash/bin/logstash --path.settings=/tmp --path.data=/tmp -e 'input { stdin { } } output { elasticsearch { index => "foo-%{+YYYY.MM.dd}" } }'
```

Even though I have specified `foo-%{+YYYY.MM.dd}` for the index, template is created with the pattern `logstash-*` instead of `foo-*`.  FWIW, setting [`template_name` option](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-template_name) changes where the template is stored but does not change matching pattern.

Output of the command shows:

```
12:00:30.496 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Using mapping template from {:path=>nil}
12:00:31.388 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>50001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_all"=>{"enabled"=>true, "norms"=>false}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword"}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "include_in_all"=>false}, "@version"=>{"type"=>"keyword", "include_in_all"=>false}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
```

**Comment by untergeek** [comment]
The linked documentation states:

> Starting in Logstash 1.3 (unless you set option `manage_template` to false) a default mapping template for Elasticsearch will be applied, if you do not already have one set to match the index pattern defined (default of `logstash-%{+YYYY.MM.dd}`), minus any variables. For example, in this case the template will be applied to all indices starting with `logstash-*`

I think you misunderstood the documentation. "If you do not already have one" means your own index template.  The index pattern to match is defined in the template itself.

The template provided by the most recent logstash-output-elasticsearch plugin has [this line](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v5.2.0/lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json#L2):
>```
  "template" : "logstash-*",
```

The index matching pattern is handled in the template, not from the sprintf pattern defined in the output block.  The configuration directives provided in the elasticsearch output allow you to select your own template file to use.  It is in that file that you would define the index matching pattern.  The referenced `template_name` option is to name the template in Elasticsearch.  This is important if you manage multiple templates and don't want to overwrite them. It is not—as you have seen—to define an index matching pattern.

**Comment by atnak** [comment]
Thanks for the clarification!  If I understand correctly, wording like below may help avoid confusion:

> From Logstash 1.3 onwards, a template is applied to Elasticsearch at Logstash's startup if a template with the name `template_name` does not already exist.  The template to be applied can be altered by specifying the path to a custom template with `template`.  By default, the default template for `logstash-%{+YYYY.MM.dd}` that matches the index pattern `logstash-*` is applied.

> This behaviour may be disabled by setting `manage_template` to `false`.  If you have dynamic templating...

**Comment by untergeek** [comment]
By all means, click the "edit" button in the documentation and submit this as a PR!  We'd love to have your submission.
