### ISSUE TITLE
S3 plugin permissions issues throw an "uninitialized constant" error

### ISSUE THREAD

**Issue by patrobinson** [elastic/logstash#6201]
- Version: 5.0.0-rc1-1
- Operating System: Linux (docker container logstash:5.0.0-rc1-1)
- Config File:
```
input {
  s3 {
    bucket => "some-bucket"
    codec  => json_lines
    prefix => "firehose"
    type   => "firehose"
  }

  s3 {
    bucket => "some-bucket"
    prefix => "elb"
    type   => "elb"
  }
}
```

- Sample Data: N/A
- Steps to Reproduce: Run container with above config (using a real s3 bucket)

Output:
```
[2016-11-07T03:17:22,325][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 bucket=>"some-bucket", prefix=>"elb", type=>"elb", id=>"b5f5a4538615404515f06ab3ad934351b048b509-2", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_b4023de1-84e1-4e61-b74d-01eb189f7415", enable_metric=>true, charset=>"UTF-8">, region=>"us-east-1", delete=>false, interval=>60, temporary_directory=>"/tmp/logstash">
  Error: uninitialized constant Aws::Client::Errors
```

This appears to be related to the following JRuby bug https://github.com/jruby/jruby/issues/3645 which was fixed in version 9.1.0.0

**Comment by patrobinson** [comment]
Actually this is a permissions issue, but the message is rather obscure

**Comment by ph** [comment]
@patrobinson Yeah the jruby bug is hidding the real problem. Eager loading might fix this issue.

**Comment by ph** [comment]
I've migrated this issue to the plugin https://github.com/logstash-plugins/logstash-input-s3/issues/99
