### ISSUE TITLE
Add ability to choose startup style to system-install script

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#6209]
Have it pull override configuration from `startup.options` in `/etc/logstash` or `$LS_HOME/config` and put flags to catch this in system-install.

Not sure if this should be 5.1 or 5.0.1.  Whichever Label can be removed.

**Comment by suyograo** [comment]
Definitely 5.1.0 :)

**Comment by suyograo** [comment]
Fixed in #6338
