### ISSUE TITLE
Add deb/rpm package repository url change to breaking changes doc

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6212]
Our other 5.0 products (ES, Kibana, Beats) have the following documented in their breaking changes guide.  Let's add the following to the [Logstash 5.0 breaking changes](https://www.elastic.co/guide/en/logstash/current/breaking-changes.html) page to be consistent ? 

>URL changes for DEB/RPM packages
>The previous packages.elastic.co URL has been altered to artifacts.elastic.co. Ensure you update your repository files before running the upgrade process, or your operating system may not see the new packages.

**Comment by dedemorton** [comment]
Fixed in PR #6227
