### ISSUE TITLE
Logstash documentation page style is messed.

### ISSUE THREAD

**Issue by liweinan0423** [elastic/logstash#6213]
It seems the `logstash.css` is not available. 

![image](https://cloud.githubusercontent.com/assets/646159/20085887/184d4552-a5a7-11e6-9a9e-0058b74d5288.png)

**Comment by joshuar** [comment]
Hi @liweinan0423 we are aware of this issue.  I'll close this issue as it isn't LS specific, it's a problem with the elastic.co site that we are tracking internally :)
