### ISSUE TITLE
docs/packaging: bin/logstash has non-obvious location

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6219]
Example: bin/logstash could appear in different places depending on how a user installed it. Our docs mention `bin/logstash` as shorthand, but when installing rpm/deb this is really /usr/share/logstash/bin/logstash.

My main goal is to reduce user confusion, since bin/logstash has a discoverability problem ("Where is it?"), this means users are having a bad time.

Proposed solution: Update all mentions of `bin/logstash` to include a note indicating where to find `bin/logstash` depending on the method of installation (rpm/deb/tar/zip)

**Comment by dedemorton** [comment]
Closed by #6784
