### ISSUE TITLE
Offline plugins still not working with logstash 5.0.0

### ISSUE THREAD

**Issue by sbarrier** [elastic/logstash#6229]
- Package used logstash-5.0.0-1.rpm

```
Signature   : RSA/SHA512, Wed Oct 26 04:57:59 2016, Key ID d27d666cd88e42b4
Source RPM  : logstash-5.0.0-1.src.rpm
Build Date  : Wed Oct 26 04:10:26 2016
Build Host  : packer-virtualbox-iso-1474648640
```
Online server :

- Install logstash-output-email plugin

```
./bin/logstash-plugin install logstash-output-email
Validating logstash-output-email
Installing logstash-output-email
Installation successful
```

- Pack

```
./bin/logstash-plugin pack --tgz
Packaging plugins for offline usage

Generated at /usr/share/logstash/plugins_package.tar.gz
```

Offline server :

- Unpack
```
./bin/logstash-plugin unpack ~/plugins_package.tar.gz
Unpacking ~/plugins_package.tar.gz
Unpacked at /usr/share/logstash/vendor/cache
The unpacked plugins can now be installed in local-only mode using bin/logstash-plugin install --local [plugin name]
```

- Install logstash-output-email plugin

```
./bin/logstash-plugin install --local logstash-output-email
Installing logstash-output-email
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 2/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 3/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 4/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 5/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 6/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 7/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 8/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 9/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Error Bundler::InstallError, retrying 10/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
Too many retries, aborting, caused by Bundler::InstallError
ERROR: Installation Aborted, message: An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.
```
- Feature request :

For people using it for alerting it would have been nice to keep it included in the default list of plugins, as it's an "Elastic supported plugins".

**Comment by jordansissel** [comment]
@acchen97 is this an expected-to-work offline plugins scenario?

**Comment by sbarrier** [comment]
@jordansissel this what is documented here : https://www.elastic.co/guide/en/logstash/5.0/offline-plugins.html

**Comment by matejzero** [comment]
I came across this problem as well.

Logstash version: 5.0.0

On server1, where I have access to internet plugin installed fine and without any problem.
On server2, where I have limited access to internet and need to use proxy, I see same problem as sbarrier. I did setup proxy env variable, like shown in [Logstash doc](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#proxy-plugins).

**Comment by ph** [comment]
@matejzero on your machine with the proxy can you try settings the ENV variable and doing this work around.

https://github.com/elastic/logstash/issues/6044#issuecomment-253854228

Do this solve your issue?

**Comment by matejzero** [comment]
I created settings.xml in ~/.m2 and put the content in. After running logstash-plugin agains, I get:

```
$ /usr/share/logstash/bin/logstash-plugin install logstash-filter-translate
Validating logstash-filter-translate
Unable to download data from https://rubygems.org - Errno::ECONNREFUSED: Connection refused - Connection refused (https://api.rubygems.org/latest_specs.4.8.gz)
ERROR: Installation aborted, verification failed for logstash-filter-translate
```

It looks like proxy settings are not taken into account this time. Do I have to set any ENV variable?

**Comment by ph** [comment]
@matejzero You have to set both the ENV variables and the settings.xml.

**Comment by matejzero** [comment]
Did not think of that:)

I tried setting both and now it works.

**Comment by mcandre** [comment]
+1

**Comment by jordansissel** [comment]
@mcandre +1 to what? This comment doesn't have enough information to take action. 

Please be aware that sending +1 as a comment will generate hundreds of emails and provides basically no data. In the future, if you want to put a "+1" on an issue, use Github's reaction feature (click the smiley face in the top of the comment).

**Comment by schneidermatic** [comment]
### Offline plugins still not working with logstash 5.0.2

On my Ubuntu box
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial 
Linux okul 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I get the following error when I try to install the zabbix-3.0.1 plugin offline with logstash v5.0.2

$ logstash-plugin install logstash-output-zabbix-3.0.1.gem
Validating logstash-output-zabbix-3.0.1.gem
Installing logstash-output-zabbix
**LoadError: no such file to load -- fileutils**
  require at org/jruby/RubyKernel.java:944
    <top> at uri:classloader:/maven/tools/dsl.rb:1
  require at org/jruby/RubyKernel.java:944
    <top> at classpath:/parser.rb:1
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.2), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.2'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported

It seems that fileutils can't be installed.

**Comment by horatiucherebetiu** [comment]
I got the same error when trying to install  logstash-output-email on logstash 5.1.1 on Windows 8:
An error occurred while installing logstash-core-event-java (5.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.1.1'` succeeds before bundling.

I tried same thing on linux Cent OS 7 and installation went ok.

**Comment by ph** [comment]
I'll close this issue the meta issue concerning offline management was closed, we have completely changed the flow in 5.2, this version will be released soon, for more details see #6404

**Comment by martinjt** [comment]
Just a note for anyone else coming to this when they are not using "Offline mode".  Seems that I had the same error when there was a certificate issue in java...

`sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure`

fixed it for me.

**Comment by siditlef** [comment]
I get this error with Logstash ver 6.2.4

`sudo bin/logstash-plugin install --local /usr/share/logstash/logstash/logstash-filter-dissect-1.1.4.gem 
`
ERROR: Something went wrong when installing /usr/share/logstash/logstash/logstash-filter-dissect-1.1.4.gem, 
message: Failed to open TCP connection to artifacts.elastic.co:443 (execution expired)
