### ISSUE TITLE
Temporary network failure downloading JRuby

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6247]
https://logstash-ci.elastic.co/job/elastic+logstash+5.x+dockerubuntu-periodic/213/console

```
Downloading http://jruby.org.s3.amazonaws.com/downloads/1.7.25/jruby-bin-1.7.25.tar.gz
rake aborted!
Timeout::Error
```

**Comment by original-brownbear** [comment]
@jordansissel this one as well as #6904 are kind of questionable (in terms of being an actual issue) aren't they?
Problems connecting to external repos can't really be prevented and the only solution would be to invest time implementing some retry/secondary mirror(s) or similar logic I guess? (may that's not worth it? :))

**Comment by andrewvc** [comment]
Freak accident
