### ISSUE TITLE
fail to get file input and file output

### ISSUE THREAD

**Issue by semon9** [elastic/logstash#6253]
config file content like this:
input {
      stdin {
 }
}
output {
    file {
        path => "/home/ning/b.json"
    }
}
configtest is ok ,no err log in logstash.log, but after giving a stdin, the "b.json" is empty always-_-
and if i mk a log file with something in the input domain, the stdout is empty too, i had practiced many times but got nothing, it makes me crazy ...  i miss what? tell me ,please

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!

**Comment by semon9** [comment]
ok, sorry for that,thanks.
