### ISSUE TITLE
Default mapping template for Elasticsearch is not created - Logstash 5.

### ISSUE THREAD

**Issue by sbarrier** [elastic/logstash#6254]
The plugin logstash-output-elasticsearch is supposed to create a default mapping template for logstash index. The json template _/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.0-java/lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json_ is not applied.

- Configuration :
Elasticsearch 5
Logstash 5
Kibana 5
X-Pack 5

Doc: https://www.elastic.co/guide/en/logstash/5.0/plugins-outputs-elasticsearch.html

**Comment by sbarrier** [comment]
Additional information in logstash log i found a 403 

`[2016-11-17T01:10:51,259][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Got response code '403' contact Elasticsearch at URL 'http://~hidden~:~hidden~@1.2.3.4:9200'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError"}
`

but there's the user/password in the output configuration

```
output {
  elasticsearch {
    hosts => ["http://1.2.3.4:9200"]
    user => "logstash_internal"
    password => "hidden"
  }
}
```

The logstash_internal have logstash_writer role with manage_index_templates privilege and write/create_index/delete permission on logstash-* index

**Comment by suyograo** [comment]
The Logstash user needs the `monitoring` privilege since we issue a `GET /` request

**Comment by suyograo** [comment]
Docs: https://www.elastic.co/guide/en/x-pack/current/logstash.html#ls-http-auth-basic

**Comment by sbarrier** [comment]
It was missing the _monitor_ role, i suggest you to fix the documentation because it's not specified in this phrase :

`Create a logstash_writer role that has the manage_index_templates cluster privilege, and the write, delete, and create_index privileges for the Logstash indices.`

It's only specified in the POST example.
