### ISSUE TITLE
Couldn't find any filter plugin named 'date' 

### ISSUE THREAD

**Issue by magicdude4eva** [elastic/logstash#6262]
- Version: Logstash 5.0.1
- Operating System: CentOS 7

After doing a fresh install of Logstash 5.0.1 and then doing a
```
cd /usr/share/logstash/
bin/logstash-plugin install logstash-output-gelf logstash-filter-range
bin/logstash-plugin update
```

Logstash fails with
```
<snip>
reason=>"Couldn't find any filter plugin named 'date'. Are you sure this is correct? Trying to load the date filter plugin resulted in this error: no such file to load -- logstash-filter-date_jars"
```

The plugin-update updates the following which seems to cause the break:
```
Updated logstash-filter-date 3.0.3 to 3.1.0
```

Not doing the update does not result in the error

**Comment by ph** [comment]
It might be related to this issue https://github.com/logstash-plugins/logstash-filter-date/issues/78

**Comment by magicdude4eva** [comment]
Just strange that the update of logstash-filter-date 3.0.3 to 3.1.0 would then cause the error?

**Comment by suyograo** [comment]
logstash-filter-date 3.1.0 uses Java jars underneath, so the packing is broken. I removed the latets update for now. Sorry for the inconvenience.

**Comment by magicdude4eva** [comment]
Thanks.
