### ISSUE TITLE
Feature: 'date' filter supports grok patterns

### ISSUE THREAD

**Issue by vdun** [elastic/logstash#6264]
Let the `date` filter supports grok patterns instead of `joda.time.format.DateTimeFormat`.
e.g. for apache access log, instead of  using:
`date {match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]}`
->
`date {match => [ "timestamp" , "%{HTTPDATE}" ]}`

**Comment by jsvd** [comment]
moved to https://github.com/logstash-plugins/logstash-filter-date/issues/77
