### ISSUE TITLE
Fail loudly when missing plugins

### ISSUE THREAD

**Issue by mcandre** [elastic/logstash#6266]
When logstash fails to load a plugin required for a config file (e.g. grok, date, etc), please fail loudly so that this problem is easier to identify in a complex logstash setup.

**Comment by suyograo** [comment]
Can you give us more details? What version of Logstash? What does it output now? What does your config look like?

**Comment by suyograo** [comment]
Related: https://github.com/elastic/logstash/pull/6020

**Comment by jsvd** [comment]
closing as we're now too loud about a missing plugin :D https://github.com/elastic/logstash/issues/11272
