### ISSUE TITLE
update new short-batch strategy

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#6273]
in 5.x `WrappedSyncronousQueue#take_originals_from_queue` is now using a short-batch queue read strategy which is consistent with the Persistent Queue implementation and which should also reduce perceived latency in some cases.

We need to update docs where the queue read strategy is mentioned and also update the phrasing of the  command line flag `-u, --pipeline.batch.delay DELAY_IN_MS When creating pipeline batches, how long to wait while polling for the next event.`

**Comment by suyograo** [comment]
fixed in #6364
