### ISSUE TITLE
Elasticsearch password can not handle special characters

### ISSUE THREAD

**Issue by amitripshtos** [elastic/logstash#6291]
Hello,
I think there is a bug with elasticsearch configuration:

I have a password to elasticsearch cluster that contains special characters (example: Ass234!sdf@df)
In logstash 2, the password got encoded to URI and worked great, however in logstash 5 I get error about this password.

The fix in my side was to encode my password to URI (using http://www.urldecoder.org/) , but I think that should be fixed.

- Version: 5.0.1-1
- Operating System: running on docker
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce: Create a configuration that outputs to elasticsearch and set username to "test" and password to "test!sddf@%@#@"

Thank you for help very much!
cheers.

**Comment by PhaedrusTheGreek** [comment]
I'm hitting this issue as well

**Comment by andrewvc** [comment]
This was since fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/545

**Comment by mhnamaki** [comment]
I think I have the same issue when I'm trying to connect to an elasticsearch instance version 7.x using elasticsearch_dsl in Python 3.
My PASSWORD has $ and / in it.
ValueError: Port could not be cast to integer value as PASSWORD
