### ISSUE TITLE
logstash send request to ES with search_type=scan

### ISSUE THREAD

**Issue by sachavuk** [elastic/logstash#6299]
Hi,

I have upgrade  my ES to the version 5.X, when I run a logstash with the ES  input I have this error message " No search type for [scan]". I see that my logstash send this request : 

GET /infralog-2016.10.31/_search?scroll=1m&search_type=scan&size=1000 
 
I read that search_type=scan was removed ? It's true ? 
I didn't find any documentation how to change this setting :/

logstash configuration
input {
  elasticsearch {
    hosts => "XXX.XXX.XX:80"
    index => "infralog-2016.10.31"
    query => '{"query": {"wildcard": {"request": "/api/rules1*" }}}'
    size => 1000
    scroll => "1m"
  }

- Version: logstash V 2.4.1 (RPM installation), Elasticsearch 5.0.1
- Operating System: Centos 6.8

**Comment by sachavuk** [comment]
Hi,

After upgrading of logstash 2.4.1 to 5.0.1 , the  Elasticsearch input works now:

"GET /infralog-2016.10.31/_search?scroll=1m&size=500 HTTP/1.1" 200 357953 "-" "Faraday v0.9.2" 

It's seems that logstash version 2.4.1 with the ES input don't work on ES v5.X ?

**Comment by suyograo** [comment]
no, because ES deprecated scan search type

**Comment by sachavuk** [comment]
Please, can you update the logstash documentation for Elasticsearch input. I have spend many time to find this information..

Thanks
