### ISSUE TITLE
Duplicate list option on logstash-plugin usage output

### ISSUE THREAD

**Issue by bizzam** [elastic/logstash#6304]
- Version: logstash-5.0.1-1
- Operating System: CentOS Linux release 7.2.1511 (Core)

- Sample Data

[root@hostname logstash]# ./bin/logstash-plugin -h
Usage:
    bin/logstash-plugin [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    list                          List all installed Logstash plugins
    install                       Install a Logstash plugin
    remove                        Remove a Logstash plugin
    update                        Update a plugin
    pack                          Package currently installed plugins
    unpack                        Unpack packaged plugins
    list                          List all installed plugins
    generate                      Create the foundation for a new plugin
    uninstall                     Uninstall a plugin. Deprecated: Please use remove instead

Options:
    -h, --help                    print help

- Steps to Reproduce: just launch logstash-plugin -h

You can find two times the "list" option with a different description.

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/6205
