### ISSUE TITLE
Change to v0.4.1 of JrJackson

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#6305]
v0.4.1 changes the way Serialization detects the method to use for the different classes. Previously, an Enum lookup was used but this mechanism raises an exception when the class name is not in the Enum e.g. LogStash::Timestamp. This exception based flow control is very expensive.
It has been replaced with a simple loop to determine whether the class is in the Enum.

This should provide a performance boost when serialising Events for ES.

**Comment by suyograo** [comment]
Updated in commit https://github.com/elastic/logstash/commit/5438d7e90835ae813e871db0beafaf3734edc350
