### ISSUE TITLE
Acceptance test failure in master and 5.x

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6310]
This could be from the x-pack install commit. Both redhat and debian are failing with the same errors.

https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-acceptance/label=metal,suite=redhat/87/console

https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=redhat/203/console

**Comment by ph** [comment]
The messages where changes but the expectation where not updated.
