### ISSUE TITLE
after installation x-pack, logstash 5.0.1 does not work, does not recognize user/password in conf

### ISSUE THREAD

**Issue by robertchen** [elastic/logstash#6332]
Issue: after x-pack installation, logstash has many errors:
 Got a bad response code from server, but this code is not considered retryable. Request will be dropped {:code=>401}

Then I followed the this doc (https://www.elastic.co/guide/en/x-pack/current/logstash.html )  for adding user and password to logstash conf file.  The logstash could NOT recognize user and password,  error is:
[LogStash::Runner] FATAL logstash.runner - The given configuration is invalid. Reason: Expected one of #, { at line 7, column 8 (byte 81) after input { 

- Version:  logstash 5.0.1, ES 5.0.1, X-pack
- Operating System:  Redhat
- Config File (if you have sensitive info, please remove it):
input {

  beats {
        host => "10.8.12.53"
        port => "5044"
  }
  user => logstash_internal
  password => Logstash1
}

filter {
  if [type] == "webapps" {
    grok {
    match => ["message", "%{TIMESTAMP_ISO8601:timestamp}%{SPACE}\[%{NOTSPACE:worker}\]%{SPACE}%{LOGLEVEL:level}\s+%{NOTSPACE:javaclass}\s+(-\s+)?(?:(?<logmsg>(.*)))"]
    }
    date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss,SSS"]
    target => "@timestamp"
    }
    if [path] {
      mutate {
      split => ["path", "/"]
      add_field => {"channel" => "%{[path][1]}"}
      add_field => {"biller" => "%{[path][2]}"}
      }
      mutate { join => ["path", "/"]  }
    }
  }
 else if [type] == "apache" {
    grok {
      match => ["message", "%{IPORHOST:clientip} %{HTTPDUSER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] \"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response} (?:%{NUMBER:bytes}|-)"]
      match => ["message", "\[%{HTTPDERROR_DATE:timestamp}\] \[%{LOGLEVEL:loglevel}\] (?:\[client %{IPORHOST:clientip}\] ){0,1}%{GREEDYDATA:errormsg}"]
      remove_field => [ "ident" ]
    }
 }
 user => logstash_internal
 password => Logstash1
}

output {
  elasticsearch { hosts => ["10.8.12.123:9200", "10.8.12.121:9200", "10.8.12.50:9200"] }
  user => logstash_internal
  password => Logstash1
}

[2016-11-30T12:55:17,981][ERROR][logstash.agent           ] fetched an invalid config 
 :reason=>"Expected one of #, { at line 7, column 8 (byte 82) after input

**Comment by jsvd** [comment]
you have the output section as:

```
output {
elasticsearch { hosts => ["10.8.12.123:9200", "10.8.12.121:9200", "10.8.12.50:9200"] }
user => logstash_internal
password => Logstash1
}
```

but the user and password parameters must be in the same block as the elasticsearch output and they values must be surrounded by quotes, so it needs to be:

```
output {
  elasticsearch {
    hosts => ["10.8.12.123:9200", "10.8.12.121:9200", "10.8.12.50:9200"]
    user => "logstash_internal"
    password => "Logstash1"
  }
}
```

**Comment by robertchen** [comment]
thanks,  This resovled my issue. The doc is confusing. The doc says:
https://www.elastic.co/guide/en/x-pack/current/logstash.html  

input {
    ...
    user => logstash_internal
    password => changeme
  }
filter {
    ...
    user => logstash_internal
    password => changeme
  }
