### ISSUE TITLE
Remove multiline filter documentation

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6342]
Remove multiline filter documentation page since its no longer supported and is discouraged in favor of the multiline codec.

https://www.elastic.co/guide/en/logstash/current/plugins-filters-multiline.html

**Comment by ctindel** [comment]
@acchen97 My understanding of the filter is that it is still supported, it's just deprecated.

**Comment by acchen97** [comment]
@ctindel multiline filter is no longer supported with the release of 5.0.

**Comment by ctindel** [comment]
@acchen97 Ah, well then yeah the documentation is confusing because it says it is deprecated which usually means its still supported.

**Comment by dedemorton** [comment]
@acchen97 The changes related to this issue are ready for you to review. See the links shown above.

**Comment by acchen97** [comment]
Thanks @dedemorton LGTM aside from the one comment for @jordansissel in the pipe input PR, though I suspect it works fine.

**Comment by dedemorton** [comment]
Closing because all the related PRs for this issue are now merged.
