### ISSUE TITLE
Logstash error while installing codec - logstash-codec-nmap

### ISSUE THREAD

**Issue by xsallowed** [elastic/logstash#6351]
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core-plugin-api":
  In snapshot (Gemfile.lock):
    logstash-core-plugin-api (= 2.1.16)

**Comment by andrewvc** [comment]
Hmmm, this plugin needs to be updated to LS 5.x

**Comment by jsvd** [comment]
this is a duplicate of https://github.com/logstash-plugins/logstash-codec-nmap/issues/9
