### ISSUE TITLE
logstash-5.0.2 can't install plugins

### ISSUE THREAD

**Issue by rivencxl** [elastic/logstash#6359]
I download the logstash-5.0.2 (tar.gz), and I want to install logstash-filter-multiline, but I get the following error message:
bin/logstash-plugin install logstash-filter-multiline
Validating logstash-filter-multiline
Installing logstash-filter-multiline
LoadError: no such file to load -- fileutils
  require at org/jruby/RubyKernel.java:944
    <top> at uri:classloader:/maven/tools/dsl.rb:1
  require at org/jruby/RubyKernel.java:944
    <top> at classpath:/parser.rb:1
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.2), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.2'` succeeds before bundling.

Then I try to install my local plugin, it occurs again:
bin/logstash-plugin install ~/projects/logstash-filter-cutter/logstash-filter-cutter-1.0.0.gem
Validating /Users/caoxiaolei/projects/logstash-filter-cutter/logstash-filter-cutter-1.0.0.gem
Installing logstash-filter-cutter
LoadError: no such file to load -- fileutils
  require at org/jruby/RubyKernel.java:944
    <top> at uri:classloader:/maven/tools/dsl.rb:1
  require at org/jruby/RubyKernel.java:944
    <top> at classpath:/parser.rb:1
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.2), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.2'` succeeds before bundling.

- Version: 5.0.2
- Operating System: mac os x 10.11.5

**Comment by jsvd** [comment]
Interesting, I just tried on my mac (10.12.1)

```
/tmp % wget https://artifacts.elastic.co/downloads/logstash/logstash-5.0.2.tar.gz
....
/tmp % tar -zxf logstash-5.0.2.tar.gz
/tmp/logstash-5.0.2 % bin/logstash-plugin install logstash-filter-multiline
Validating logstash-filter-multiline
Installing logstash-filter-multiline
Installation successful
```

I can't seem to replicate this

**Comment by rivencxl** [comment]
I installed the plugin in my centos box，it succeed !
Maybe something wrong with my mac

**Comment by c0bra** [comment]
From https://github.com/elastic/logstash/issues/5581#issuecomment-230267277

`sudo update-ca-certificates -f` worked for me
