### ISSUE TITLE
Logstash checks default queue directory for write permissions even when overridden

### ISSUE THREAD

**Issue by jasontedor** [elastic/logstash#6378]
This is on Logstash 5.1.1 and is similar to #6004. My `${LOGSTASH_HOME}/data/queue` is not writable and I'm overriding `path.data`:

```
logstash -f /tmp/logstash-test-20161208-84600-14ga093/simple.conf --path.data=/tmp/logstash-test-20161208-84600-14ga093/data --path.logs=/tmp/logstash-test-20161208-84600-14ga093/logs --log.level=fatal
```

 yet I see:

```
[2016-12-08T12:54:47,884][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#
<ArgumentError: Path \"/usr/local/Cellar/logstash/5.1.1/libexec/data/queue\" must be a writable directory. It is not writable.>,
:backtrace=>[\"/usr/local/Cellar/logstash/5.1.1/libexec/logstash-core/lib/logstash/settings.rb:420:in `validate'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/logstash-core/lib/logstash/settings.rb:202:in `validate_value'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/logstash-core/lib/logstash/settings.rb:118:in `validate_all'\", \"org/jruby/RubyHash.java:1342:in `each'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/logstash-core/lib/logstash/settings.rb:117:in `validate_all'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/logstash-core/lib/logstash/runner.rb:205:in `execute'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/logstash-core/lib/logstash/runner.rb:178:in `run'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'\",
\"/usr/local/Cellar/logstash/5.1.1/libexec/lib/bootstrap/environment.rb:71:in `(root)'\"]}\n".
```

Steps to reproduce:

```bash
$ curl -sS -L -O https://artifacts.elastic.co/downloads/logstash/logstash-5.1.1.tar.gz
$ tar xf logstash-5.1.1
$ cd logstash-5.1.1
$ mkdir -p /tmp/logstash/data
$ mkdir -p /tmp/logstash/logs
$ chmod 000 data
$ ./bin/logstash -e 'input { stdin } output { stdout }' --path.data /tmp/logstash/data --path.logs /tmp/logstash/logs
```

I don't think I'm missing a configuration option, sorry if I am but it does [look like](https://github.com/elastic/logstash/blob/b859b64d9dd046a183489df98e9bb35ebd6e0f9e/logstash-core/lib/logstash/environment.rb#L57-L58) it should be using `${path.data}/queue` (and setting `--path.queue` gives `ERROR: unrecognized option '--path.queue'`).

**Comment by jsvd** [comment]
@jasontedor thanks for reporting this.
indeed logstash computes the default value of path.queue based on the default of path.data.
what is missing is the logic to recalculate path.queue if path.data is changed (and path.queue is not set).

The reason `--path.queue` fails is that we only allow in the cli a few of the most commonly changed settings, other must be set through the yaml file. looking at issues like this I can see this division wasn't a very wise decision.

Currently the only workaround is editing the yaml file on installation (we do this for rpm/deb installations).

I'll open a new issue to track the recalculation of path.queue on a path.data change.

**Comment by jasontedor** [comment]
> Currently the only workaround is editing the yaml file on installation (we do this for rpm/deb installations).

Thanks @jsvd! That gives me enough info to workaround this issue in Homebrew/homebrew-core#7683.

> looking at issues like this I can see this division wasn't a very wise decision.

In Elasticsearch we allow any node-level setting to be specified via `-E key=value`.

**Comment by jsvd** [comment]
> In Elasticsearch we allow any node-level setting to be specified via -E key=value.

we should do that we well, it is a limitation of the cli args library we use, iirc.

I opened https://github.com/elastic/logstash/issues/6387 to track this

**Comment by polynomial** [comment]
thanks @jasontedor for reporting, made resolving it much easier!

**Comment by bonzofenix** [comment]
When can we expect this to be released?

Thanks!
