### ISSUE TITLE
Windows logstash Reload of .conf file

### ISSUE THREAD

**Issue by gauravksahni** [elastic/logstash#6383]
In linux logstash can read all configuration files under the /etc/logstash/conf.d/ directory automatically.
but there is no such option available in windows, how do i reload the configuration file in windows automatically.
I'm running logstash 5.0.1

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
