### ISSUE TITLE
recalculate the value of path.queue when path.data is defined

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6387]
By default, `path.queue` [is a relative path](https://github.com/elastic/logstash/blob/5.1/logstash-core/lib/logstash/environment.rb#L57) from `path.data`.

However, if we pass a different `path.data`, then `path.queue` isn't changed, causing issues such as https://github.com/elastic/logstash/issues/6378

Logic should be added close to https://github.com/elastic/logstash/blob/5.1/logstash-core/lib/logstash/runner.rb#L167 in order to ensure dependant settings are updated before the validator does its job.

**Comment by suyograo** [comment]
Fixed in 5.4.0
