### ISSUE TITLE
node stats metrics ids for all inputs, filters and outputs

### ISSUE THREAD

**Issue by runningman84** [elastic/logstash#6391]
my node stats look like this
```
 {
        "id" : "77cfee1fb13ec964356fba5fce880498a72578f9-14",
        "name" : "date"
      }, {
        "id" : "77cfee1fb13ec964356fba5fce880498a72578f9-28",
        "patterns_per_field" : {
          "short_message" : 2
        },
        "name" : "grok"
      }, {
        "id" : "77cfee1fb13ec964356fba5fce880498a72578f9-45",
        "name" : "mutate"
      }, {
```

It would be cool if inputs, filters and outpus would have an id option to specify the id. The auto generated ids do not help us with 100+ filters...

It looks like some module supports an "id" like beats but I haven't found the id option for grok and other filters.

**Comment by ph** [comment]
@runningman84 All plugins now accept a `id` in their configuration this allow you to override the default uuid, I've look at our documentation and it seems we have a bug with our doc generator it doesn't include the `id` field. I will create an issue for that.

```
  # Add a unique `ID` to the plugin instance, this `ID` is used for tracking
  # information for a specific configuration of the plugin.
  #
  # ```
  # output {
  #  stdout {
  #    id => "ABC"
  #  }
  # }
  # ```
  #
  # If you don't explicitely set this variable Logstash will generate a unique name.

```
