### ISSUE TITLE
Logstash start fails if java-common is installed

### ISSUE THREAD

**Issue by sysinit** [elastic/logstash#6397]
- Version: 5.1.1-1 
- Operating System: Debian 8
- Other package versions:
  java-common                                    0.52  
  openjdk-7-jre-headless:amd64       7u111-2.6.7-2~deb8u1

Starting logstash fails if package java-common is installed.
Syslog message:
``
systemd[1]: Started logstash.
logstash[3846]: LoadError: JRuby ext built for wrong Java version in `com.purbon.jrmonitor.JRMonitorService': java.lang.UnsupportedClassVersionError: com/purbon/jrmonitor/JRMonitorService : Unsupported major.minor version 52.0
logstash[3846]: require at org/jruby/RubyKernel.java:1040
logstash[3846]: (root) at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jrmonitor-0.4.2/lib/jrmonitor.rb:4
logstash[3846]: require at org/jruby/RubyKernel.java:1040
 logstash[3846]: (root) at /usr/share/logstash/logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb:1
logstash[3846]: require at org/jruby/RubyKernel.java:1040
logstash[3846]: (root) at /usr/share/logstash/logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb:5
logstash[3846]: require at org/jruby/RubyKernel.java:1040
logstash[3846]: (root) at /usr/share/logstash/logstash-core/lib/logstash/instrument/periodic_pollers.rb:1
logstash[3846]: require at org/jruby/RubyKernel.java:1040
logstash[3846]: (root) at /usr/share/logstash/logstash-core/lib/logstash/instrument/periodic_pollers.rb:3
logstash[3846]: require at org/jruby/RubyKernel.java:1040
logstash[3846]: (root) at /usr/share/logstash/lib/bootstrap/environment.rb:70
systemd[1]: logstash.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit logstash.service entered failed state.
systemd[1]: logstash.service holdoff time over, scheduling restart.
systemd[1]: Stopping logstash...
``

Apparently there is a parsing error caused by java-common version 0.52. It works if java-common is removed, but in my case this isn't an option because of other package dependencies.

**Comment by ph** [comment]
@sysinit From the error message we see an unsupported major.minor error and from your listed dependencies we see that that you  hava openjdk7 (Java 7). Logtash 5.X requires Java 8 to run also Java 7 is End of life.

**Comment by Leryan** [comment]
For some reason not exporting `JAVA_HOME` when using a correct Java version, installed by hand (Oracle's tarball), a similar error raises.

Don't forget to `export JAVA_HOME=/your/location/to/java8/` before running logstash.

**Comment by jordansissel** [comment]
@sysinit As @ph mentioned, it looks like your system is using Java 7. Logstash 5.x requires Java 8.
