### ISSUE TITLE
ID field not showing up in the doc

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6398]
The **id** field from the base plugin class should show up in our documentation and this is currently not the case.

Code: https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/plugin.rb#L34
Doc: https://www.elastic.co/guide/en/logstash/master/plugins-filters-grok.html

Found in: https://github.com/elastic/logstash/issues/6391

**Comment by andrewvc** [comment]
Fixed! https://www.elastic.co/guide/en/logstash/master/plugins-filters-grok.html#plugins-filters-grok-id
