### ISSUE TITLE
metric ideas

### ISSUE THREAD

**Issue by runningman84** [elastic/logstash#6405]
It would be great to have these additional metrics:

```
{
        "id" : "syslog_grok_1",
        "events" : {
          "duration_in_millis" : 101,
          "in" : 103,
          "out" : 103
        },
        "matches" : 103,
        "patterns_per_field" : {
          "message" : 1
        }
```
* number of grok parse failures (maybe it is in - matches?)

```
{
        "id" : "syslog_date_1",
        "name" : "date"
      }
```
* number of date parse failures

```
{
        "id" : "http_useragent_1",
        "name" : "useragent"
      }
```
* number of useragent parse failures

**Comment by jordansissel** [comment]
@runningman84 agreed! Would you mind opening a ticket for each of these on their respective plugins?

https://github.com/logstash-plugins/logstash-filter-grok/issues

https://github.com/logstash-plugins/logstash-filter-date/issues

https://github.com/logstash-plugins/logstash-filter-useragent/issues

**Comment by ph** [comment]
@runningman84 Since you have created the issue in the plugin repo I will be closing this one.
