### ISSUE TITLE
Kafka plugin update command is wrong in Logstash 5-1-1 release page

### ISSUE THREAD

**Issue by sandeepkanabar** [elastic/logstash#6407]
In the 5.1.1 release[ page](https://www.elastic.co/blog/logstash-5-1-1-released), in the section 'Kafka Enhancements', it is mentioned that 
`bin/logstash update logstash-input-kafka`
 `bin/logstash update logstash-output-kafka`.

This should actually be
`bin/logstash-plugin update logstash-input-kafka`
`bin/logstash-plugin update logstash-output-kafka`

Also when you run the command `bin/logstash-plugin update logstash-input-kafka`, it is likely to throw an error 

> An error occurred while installing logstash-core-event-java (5.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.1.1'` succeeds before bundling.

The fix for this lies in this [comment](https://github.com/elastic/logstash/issues/5581#issuecomment-263593131)

**Comment by suyograo** [comment]
Fixed https://www.elastic.co/blog/logstash-5-1-1-released
