### ISSUE TITLE
install Logstash 5.1.1 does not work (install logstash-core-event-java)

### ISSUE THREAD

**Issue by niempy** [elastic/logstash#6411]
Hi,
we have some pecular behaviour when trying to install something simple like logstash-core-event-java.
RedHat Enterprise Linux Server version 7.3

Major +1 if someone could help us!

Internet is working (tested). Seems some files are installed (see below). But still error mesesages like:
ERROR: Installation Aborted, message: Could not find arr-pm-0.0.10 in any of the sources
[root@nlvora311 ~]# gem install logstash-core-event-java
ERROR:  Could not find a valid gem 'logstash-core-event-java' (>= 0) in any repository
ERROR:  Possible alternatives: logstash-codec-netflow, logstash-event, logstash-codec-nmap, logstash-codec-json, logstash-codec-csv2

all the details below:
Because gem update gives an error(!): cannot load such file -- json/pure (LoadError)
# gem install json_pure
# gem update --system 
# gem -v
2.6.8
# gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
io-console (0.4.2)
json (1.7.7)
json_pure (2.0.2)
psych (2.0.0)
rdoc (4.0.0)
rubygems-update (2.6.8)

So far, so good (internet connection works)

# gem search ^logstash|grep 5.1.1
logstash-core (5.1.1 java)
logstash-core-event-java (5.1.1 java)
logstash-core-queue-jruby (5.1.1 java)

[root@nlvora311 ~]# gem install logstash-core-event-java
ERROR:  Could not find a valid gem 'logstash-core-event-java' (>= 0) in any repository
ERROR:  Possible alternatives: logstash-codec-netflow, logstash-event, logstash-codec-nmap, logstash-codec-json, logstash-codec-csv2

I do not understand!??

I tried to instal dependencies first, see https://rubygems.org/gems/logstash-core-event-java

# gem install ruby-maven
Fetching: ruby-maven-libs-3.3.9.gem (100%)
…
Fetching: ruby-maven-3.3.12.gem (100%)
…
2 gems installed
# gem install jar-dependencies
Fetching: jar-dependencies-0.3.8.gem (100%)
…
1 gem installed

Get the gem manualy

# wget https://rubygems.org/downloads/logstash-core-event-java-5.1.1-java.gem
…
2016-12-14 10:44:02 (3.15 MB/s) - ‘logstash-core-event-java-5.1.1-java.gem’ saved [1815040/1815040]

Install the gem

# gem install logstash-core-event-java-5.1.1-java.gem
Successfully installed logstash-core-event-java-5.1.1-java
Parsing documentation for logstash-core-event-java-5.1.1-java
Installing ri documentation for logstash-core-event-java-5.1.1-java
1 gem installed

It's there:

# gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
io-console (0.4.2)
jar-dependencies (0.3.8)
json (1.7.7)
json_pure (2.0.2)
logstash-core-event-java (5.1.1 java)
psych (2.0.0)
rdoc (4.0.0)
ruby-maven (3.3.12)
ruby-maven-libs (3.3.9)
rubygems-update (2.6.8)

Okay, get the logstash-filter-translate gem manually (because the normal doesn't work, see below)

# wget https://rubygems.org/downloads/logstash-filter-translate-3.0.0.gem
# /u01/logstash/bin/logstash-plugin install --local /root/logstash-filter-translate-3.0.0.gem
Validating /root/logstash-filter-translate-3.0.0.gem
Installing logstash-filter-translate
Plugin not found, aborting
ERROR: Installation Aborted, message: Could not find arr-pm-0.0.10 in any of the sources

Oay, install the missing package

# gem install arr-pm
Fetching: cabin-0.9.0.gem (100%)
Successfully installed cabin-0.9.0
Fetching: arr-pm-0.0.10.gem (100%)
Successfully installed arr-pm-0.0.10
Parsing documentation for cabin-0.9.0
Installing ri documentation for cabin-0.9.0
Parsing documentation for arr-pm-0.0.10
Installing ri documentation for arr-pm-0.0.10
2 gems installed

Yes it's installed

# gem list

*** LOCAL GEMS ***

arr-pm (0.0.10)
bigdecimal (1.2.0)
cabin (0.9.0)
io-console (0.4.2)
jar-dependencies (0.3.8)
json (1.7.7)
json_pure (2.0.2)
logstash-core-event-java (5.1.1 java)
psych (2.0.0)
rdoc (4.0.0)
ruby-maven (3.3.12)
ruby-maven-libs (3.3.9)
rubygems-update (2.6.8)

Let's try again

[root@nlvora311 ~]# /u01/logstash/bin/logstash-plugin install --local /root/logstash-filter-translate-3.0.0.gem
Validating /root/logstash-filter-translate-3.0.0.gem
Installing logstash-filter-translate
Plugin not found, aborting
ERROR: Installation Aborted, message: Could not find arr-pm-0.0.10 in any of the sources

and again

[root@nlvora311 ~]# /u01/logstash/bin/logstash-plugin install --local --no-verify /root/logstash-filter-translate-3.0.0.gem
Installing logstash-filter-translate
Plugin not found, aborting
ERROR: Installation Aborted, message: Could not find arr-pm-0.0.10 in any of the sources

Maybe so

[root@nlvora311 ~]# /u01/logstash/bin/logstash-plugin install --local arr-pm-0.0.10.gem
Validating arr-pm-0.0.10.gem
ERROR: Installation aborted, verification failed for arr-pm-0.0.10.gem

nope

[root@nlvora311 ~]# /u01/logstash/bin/logstash-plugin install --local --no-verify arr-pm-0.0.10.gem
Installing arr-pm
Error Bundler::GemspecError, retrying 1/10
There was a Errno::ENOENT while loading arr-pm.gemspec:
No such file or directory - git from
  /u01/logstash/vendor/local_gems/d17fd8cf/arr-pm-0.0.10/arr-pm.gemspec:2:in `eval_gemspec'

**The normal way didn't work either**

[root@nlvora311 ~]# /u01/logstash/bin/logstash-plugin install  logstash-filter-translate
Validating logstash-filter-translate
Installing logstash-filter-translate
Exception: java.lang.ThreadDeath thrown from the UncaughtExceptionHandler in thread "Thread-3"
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.1.1'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
Error Bundler::InstallError, retrying 2/10
…

It even F%$@ed up the behaviour of logstash-plugin

# /u01/logstash/bin/logstash-plugin list
Bundler::GemNotFound: Could not find gem 'logstash-filter-translate (>= 0) java' in any of the gem sources listed in your Gemfile or installed on this machine.
  verify_gemfile_dependencies_are_found! at …..
# /u01/logstash/bin/logstash-plugin --help
Bundler::GemNotFound: Could not find gem 'logstash-filter-translate (>= 0) java' in any of the gem sources listed in your Gemfile or installed on this machine.
  verify_gemfile_dependencies_are_found! at

Files that are installed:
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/CHANGELOG.md
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/CONTRIBUTORS
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/Gemfile
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/LICENSE
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/NOTICE.TXT
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/README.md
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/lib
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/logstash-filter-translate.gemspec
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/lib/logstash
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/lib/logstash/filters
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/filters
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/fixtures
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/filters/translate_spec.rb
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/fixtures/dict-wrong.yml
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/fixtures/dict.csv
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/fixtures/dict.json
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/fixtures/dict.other
/u01/logstash/vendor/local_gems/1d77d6c1/logstash-filter-translate-3.0.0/spec/fixtures/dict.yml
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/CHANGELOG.md
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/CONTRIBUTORS
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/Gemfile
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/LICENSE
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/NOTICE.TXT
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/README.md
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/lib
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/logstash-filter-translate.gemspec
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/lib/logstash
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/lib/logstash/filters
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/filters
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/fixtures
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/filters/translate_spec.rb
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/fixtures/dict-wrong.yml
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/fixtures/dict.csv
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/fixtures/dict.json
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/fixtures/dict.other
/u01/logstash/vendor/local_gems/4d4b27e9/logstash-filter-translate-3.0.0/spec/fixtures/dict.yml
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/CHANGELOG.md
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/CONTRIBUTORS
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/Gemfile
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/LICENSE
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/NOTICE.TXT
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/README.md
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/lib
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/logstash-filter-translate.gemspec
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/lib/logstash
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/lib/logstash/filters
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/filters
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/fixtures
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/filters/translate_spec.rb
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/fixtures/dict-wrong.yml
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/fixtures/dict.csv
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/fixtures/dict.json
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/fixtures/dict.other
/u01/logstash/vendor/local_gems/56eda8cf/logstash-filter-translate-3.0.0/spec/fixtures/dict.yml
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/CHANGELOG.md
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/CONTRIBUTORS
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/Gemfile
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/LICENSE
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/NOTICE.TXT
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/README.md
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/lib
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/logstash-filter-translate.gemspec
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/lib/logstash
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/lib/logstash/filters
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/filters
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/fixtures
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/filters/translate_spec.rb
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/fixtures/dict-wrong.yml
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/fixtures/dict.csv
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/fixtures/dict.json
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/fixtures/dict.other
/u01/logstash/vendor/local_gems/993dfdf7/logstash-filter-translate-3.0.0/spec/fixtures/dict.yml

**Comment by ph** [comment]
Thanks for the complete report, we have received a lot of issues concerning theses problems 

See https://github.com/elastic/logstash/issues/6386 and https://github.com/elastic/logstash/issues/6403

We are working hard on it and should have a new release shortly.

You can follow the previous mentioned issues and this one https://github.com/elastic/logstash/pull/6410

**Comment by JohanHolman** [comment]
In #6386 you wrote "disable  jar-dependencies  with JARS_SKIP='true', making the error go away",
Sorry but that doesn't work either

# DEBUG=1 JARS_SKIP='true' /u01/logstash/bin/logstash-plugin install --local /tmp/logstash-filter-translate-3.0.0.gem
DEBUG: exec /u01/logstash/vendor/jruby/bin/jruby --1.9 /u01/logstash/lib/pluginmanager/main.rb install --local /tmp/logstash-filter-translate-3.0.0.gem
Looking if package named: /tmp/logstash-filter-translate-3.0.0.gem exists at https://artifacts.elastic.co/downloads/logstash-plugins//tmp/logstash-filter-translate-3.0.0.gem//tmp/logstash-filter-translate-3.0.0.gem-5.1.1.zip
SocketError, skipping Elastic pack, exception: initialize: name or service not known
Validating /tmp/logstash-filter-translate-3.0.0.gem
Installing logstash-filter-translate
Resolving dependencies........................
Bundler::GemNotFound: Could not find arr-pm-0.0.10 in any of the sources
          materialize at /u01/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/spec_set.rb:92
                 map! at org/jruby/RubyArray.java:2446

**Comment by jsvd** [comment]
@JohanHolman you also need https://github.com/elastic/logstash/commit/2a281730c177b6bb4a4610cdb15f159224cbf1f9

**Comment by JohanHolman** [comment]
This works (as user logstash, and correct settings of http_proxy)

DEBUG=1 JARS_SKIP='true' /u01/logstash/bin/logstash-plugin install logstash-filter-translate

output (with debug output DEBUG=1)
DEBUG: exec /u01/logstash/vendor/jruby/bin/jruby --1.9 /u01/logstash/lib/pluginmanager/main.rb install logstash-filter-translate
Looking if package named: logstash-filter-translate exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-translate/logstash-filter-translate-5.1.1.zip
SocketError, skipping Elastic pack, exception: initialize: name or service not known
Validating logstash-filter-translate
Installing logstash-filter-translate
HTTP GET https://bundler.rubygems.org/api/v1/dependencies
...
Installing arr-pm 0.0.10
...
Installing backports 3.6.8
...
Installing childprocess 0.5.9
...
Installing fpm 1.3.3
...
Installing logstash-filter-translate 3.0.0
...
Installing sawyer 0.6.0
...
Installing octokit 3.8.0
...
Bundle complete! 115 Gemfile dependencies, 204 gems now installed.
Gems in the group development were not installed.
Bundled gems are installed into /u01/logstash/vendor/bundle.
Installation successful

output (without DEBUG=1)
Validating logstash-filter-translate
Installing logstash-filter-translate
Installation successful

**Comment by ph** [comment]
The related PRs were successfully merged in master and will be released in 5.1.2 and 5.2

**Comment by devvrat-thakur** [comment]
DEBUG=1 JARS_SKIP='true' bin/logstash-plugin install logstash-input-s3
