### ISSUE TITLE
logstash-5.1.1.zip corrupt or just not up for windows?

### ISSUE THREAD

**Issue by cawoodm** [elastic/logstash#6412]
Downloaded logstash-5.1.1.zip and tried to unpack it (Windows 7, 64bit). With Windows Unzip it just fails. 7zip does it's best but comes up with an issue:
![14 12](https://cloud.githubusercontent.com/assets/498834/21191958/20650b48-c227-11e6-8873-1d81bb7ee798.png)

Don't know what it means but there is a limit in windows to how long a path can be - you can't just have any level of depth in paths...

**Comment by osDanielLee** [comment]
The logstash-5.1.1.zip you download is absolutely corrupt as show "Unexpected end of data", have you try to download again? Cause I haven't a Windows 7 on my hand, but I encounter this error in linux, my situation had been solved after re-download the logstash.

**Comment by ph** [comment]
On january 6, I've tested the logstash-5.1.1.zip on Windows 10, I used 7zip and the windows uncompress utility without any problems or error raised.

I also ran the following command: `bin\logstash -e 'input { generator{}} output { stdout{}}' with success.
