### ISSUE TITLE
An unexpected error occurred! when start logstash with syslog input

### ISSUE THREAD

**Issue by osDanielLee** [elastic/logstash#6415]
**- Version:**logstash-5.1.1
**- Operating System:** CentOS 6.5 , with linux kernel 3.10.10
**- Config File (if you have sensitive info, please remove it):**
`
input {
    syslog {
        port => "514"
    }
}

output {
    stdout {
        codec => rubydebug
    }
}
`
**- Sample Data:**2016-12-15T12:00:16
**- Steps to Reproduce:**
1. stop syslog:
sudo  service rsyslog stop
2. start logstash:
sudo ./bin/logstash -f conf.d/syslog.conf
then error happened.

**- error info detail:**

`

[logstash-5.1.1]$ sudo  service rsyslog stop
Shutting down system logger:                               [  OK  ]
[logstash-5.1.1]$ sudo ./bin/logstash -f conf.d/syslog.conf
Sending Logstash's logs to /home/xxx/elk/newest/logstash-5.1.1/logs which is now configured via log4j2.properties
[2016-12-15T12:00:16,523][FATAL][logstash.runner          ] An unexpected error occurred! {
:error=>#<ArgumentError: Setting "peline.workers" hasn't been registered>, 
:backtrace=>[
"/home/xxx/elk/newest/logstash-5.1.1/logstash-core/lib/logstash/settings.rb:29:in `get_setting'", 
"/home/xxx/elk/newest/logstash-5.1.1/logstash-core/lib/logstash/settings.rb:61:in `set_value'", 
"/home/xxx/elk/newest/logstash-5.1.1/logstash-core/lib/logstash/settings.rb:80:in `merge'", 
"org/jruby/RubyHash.java:1342:in `each'", 
"/home/xxx/elk/newest/logstash-5.1.1/logstash-core/lib/logstash/settings.rb:80:in `merge'", 
"/home/xxx/elk/newest/logstash-5.1.1/logstash-core/lib/logstash/settings.rb:115:in `validate_all'", 
"/home/xxx/elk/newest/logstash-5.1.1/logstash-core/lib/logstash/runner.rb:205:in `execute'", 
"/home/xxx/elk/newest/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'",
"/home/xxx/elk/newest/logstash-5.1.1/logstash-core/lib/logstash/runner.rb:178:in `run'", 
"/home/xxx/elk/newest/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", 
"/home/xxx/elk/newest/logstash-5.1.1/lib/bootstrap/environment.rb:71:in `(root)'"]}

`

Does anyone encounter the same situation as me? I'm new with ruby and logstash/ELK, and I don't know how to fix it at all.

**Comment by jordansissel** [comment]
This is a configuration problem and doesn't look like a bug.

For new user help, I highly recommend our nice forums at https://discuss.elastic.co/ for questions like this. Good luck! :)

**Comment by AashishChughHome** [comment]
I also have same problem and seems like its a bug.
