### ISSUE TITLE
Multiple SQL statement in Logstash configuration file

### ISSUE THREAD

**Issue by toxicashu** [elastic/logstash#6416]
Hello,

We are trying to manipulate a postgresql table after fetching data from it using logstash config file but we are not able to use multiple statement or statement block in config file.

Here is a demo of config file 
input {
    jdbc {
        jdbc_connection_string => "jdbc:postgresql://localhost:5432/postgres"
        jdbc_user => "postgres"
        jdbc_password => "demo"
        jdbc_validate_connection => true
        jdbc_driver_library => "C:\Users\demo\Downloads/postgresql-9.4.1212.jre6"
        jdbc_driver_class => "org.postgresql.Driver"
		schedule => "*/1 * * * *" 
        statement => "select * from public.demo " #here we need to add more statements to do                     #manipulation work
		
    }
}	
output {
#stdout { codec => json_lines }
 elasticsearch {
  index => "hilit"
     document_type => "sample"	
 }
   }

Please let us know if there is any wa to do that. Thanks

**Comment by jsvd** [comment]
@toxicashu currently we don't have a way to execute modifications on a database using the jdbc input data.
