### ISSUE TITLE
Logstash Kafka Version compatibility

### ISSUE THREAD

**Issue by sherry-ger** [elastic/logstash#6418]
- Version: 5.1.1
- Operating System: None
- Config File (if you have sensitive info, please remove it): None
- Sample Data: None
- Steps to Reproduce: None

The Kafka input and output plugins compatibility charts contain incorrect info as the Kafka plugins in LS 5.1 supports Kafka 0.9

* https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html
* https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html

**Comment by jordansissel** [comment]
It is very frustrating trying to keep this matrix up to date. Sorry about this.

**Comment by sherry-ger** [comment]
Closing.  Refiling at https://github.com/logstash-plugins/logstash-input-kafka/issues/161
