### ISSUE TITLE
Unable to set parent relation

### ISSUE THREAD

**Issue by AndrewBryukhov** [elastic/logstash#6427]
Logstash 5.0

1. After mapping relations, for example:
```
curl -XPUT 'localhost:9200/test' -d '{
	"mappings": {
		"products": {
			"_parent": {
				"type": "owner"
			}
		}
	}
}' 
```

I'm starting logstash and get:

> routing is required for [test]/[products]/[100]

2. If i use:
```
  mutate{
    add_field => { "_parent" => "%{_parentId}" }
  }
```

I get:

> Field [_parent] is a metadata field and cannot be added inside a document. Use the index API request parameters.

My jdbc input is:
1. statement => "SELECT * from owner_table"
2. statement => "SELECT * from products_table"

**Comment by jordansissel** [comment]
This sounds like a question more than a bug report. For this, you will probably find better answers at https://discuss.elastic.co/
