### ISSUE TITLE
Source repo structure change proposal

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6431]
This issue is only intended to impact the source repository and will not impact the logstash artifacts.

We (logstash team; discussed with @colinsurprenant, @ph, @talevy, @jordansissel), have an idea to restructure the files in the source repository.

Goals:
* Merge all component-like things into a single source tree (logstash-core, logstash-core-event, etc)
* Make it easier to compile things (one java source tree; one build.gradle)
* Make it easier to find a given piece of code (instead of looking across 5 components directories)
* Keep general expectations of Ruby and Java programmers in mind.

Here is the proposal in english:

* Move all ruby code into `lib/`.
* Move all java code into `src/{test,main}/java`
* Move `rakelib` into `lib/rakelib`
* Bring `devutils` into the logstash repo following the rules above.
* Move all ruby specs into `spec/`

This will remove the following directories:

* `logstash-core/`
* `logstash-core-event/`
* `logstash-core-event-java/`
* `logstash-core-plugin-api/`
* `logstash-core-queue-jruby/`

The following will not change:

* `docs/`
* `bin/`

Optional, undecided moves:

* `ci/`
* `pkg/`
* `qa/`
* `tools/`

**Comment by jordansissel** [comment]
PR tracking this is here: https://github.com/elastic/logstash/pull/6432

I stress that this PR exists to track this issue's proposal and will be updated accordingly as feedback comes through this issue.

**Comment by suyograo** [comment]
> Optional, undecided moves:

I don't think we should change ci, pkg, qa and tools dir. They seem to be in the right place.

**Comment by jordansissel** [comment]
@suyograo I want to move ci/pkg/qa/tools, and will propose it eventually, but I will make that proposal *after* this issue is resolved so we don't end up in a sad place with code ;)

**Comment by jordansissel** [comment]
@talevy the work I've started on this I have put into this branch: https://github.com/elastic/logstash/tree/master-reorg

Current status of this branch: It is incomplete. `rake test:install-core` works, but `rake test:core` fails because log4j2 is not found.

You are welcome to totally ignore the `master-reorg` branch and start over -- what I've done so far is not much hard work.

**Comment by suyograo** [comment]
This has been merged with #5348 and most of the directory renaming has been done. Closing for now.
