### ISSUE TITLE
Rename /_node APIs to /_instance

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6434]
Logstash monitoring API introduced a _node_ (`GET _node/*`) concept which returns stats about the running instance. At that time, node made sense in the context of multiple Logstash instances which _may_ or _may not_ run the same configuration. There is no notion of clustering in Logstash, so a node may not be an accurate term to define multiple Logstashes. This could lead to confusion, especially in a monitoring UI. Also, we've always referred to multiple Logstashes as _instances_. For example, we tend to say "Spin up a new Logstash instance to help with the load", etc

**Proposal:** Rename Logstash `_node` API and its friends to `_instance`. 

We can deprecate `_node` and reroute requests to a new route for `_instance`. Also, the monitoring APIs are marked experimental which provides room for such changes.

**Comment by jordansissel** [comment]
We discussed this today and the conclusion from our group was to not make any changes here.
