### ISSUE TITLE
why logstash is the best tool to send logs to Elasticsearch

### ISSUE THREAD

**Issue by rajasekaran07** [elastic/logstash#6435]
Hi Team,

It is a kind question. I am just curious to know why logstash is the best tool to send logs to elasticsearch. We are running our all applications in AWS so, we are planning to use AWS Cloudwarch logs to collect and send application logs to elasticsearch. please give some suggestion for best practices.

Regards,
Raja

**Comment by suyograo** [comment]
@rajasekaran07 
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
