### ISSUE TITLE
[foo][bar] throws exception for split filter if foo is a list and bar is an inner object field

### ISSUE THREAD

**Issue by el-yoss** [elastic/logstash#6441]
Reproducing:
`logstash -e 'input { generator { message => stdin codec => json } } filter { split { field => "foo" } } filter { if [foo][bar] == "" { drop {} } } output { stdout { codec => "rubydebug" } }`

with stdin:
{ "foo": [{"bar": "123"},{"bar": "456"}] }

Results same error as in issue #6260

**Comment by andrewvc** [comment]
Moved to https://github.com/logstash-plugins/logstash-filter-split/issues/24
