### ISSUE TITLE
Grok Benchmark Test

### ISSUE THREAD

**Issue by AGirin** [elastic/logstash#6451]
Hi!

I read this great blog:

https://www.elastic.co/blog/do-you-grok-grok

Can somebody point me in the right direction on how to actually run script mentioned in the above blog post (https://gist.github.com/jsvd/a2613ea1ba00f02926a302781ca62f7b)?

Thanks!

**Comment by jsvd** [comment]
@AGirin hi! I've updated the gist with a README that includes instructions to setup and run the scripts, hope that helps!
https://gist.github.com/jsvd/a2613ea1ba00f02926a302781ca62f7b#file-readme-md

**Comment by jsvd** [comment]
closing this issue, let me know if you have more troubles running the bench script
