### ISSUE TITLE
Out Of Memory issue with Logstash-5.5.1 (Bulk Upload)

### ISSUE THREAD

**Issue by rahulsri1505** [elastic/logstash#6460]
We have about 13GB data in about 13000+ files in a directory configDir.
When we try and load it using logstash by using the command:
logstash --verbose --path.config $FILE_LOCATION/configDir/

The following error is thrown:
**ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /home/geri/logstash-5.1.1/logs which is now configured via log4j2.properties
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid18194.hprof ...**

I have tried increasing the LS_HEAPSIZE, but to no avail.
Do we have any other provision in the config file to handle such a case ?
Any parameter etc that could be set to handle it ?

P.S.:We cannot share the data due to professional restrictions.

**Comment by guyboertje** [comment]
@rahulsri1505 

Your description seems to say this error occurs at startup, is this true?

**Comment by rahulsri1505** [comment]
Yes that is true
When we try to upload the files into Elastic search using log stash we get this error

**Comment by guyboertje** [comment]
What is in the heap dump, can you upload the file after you have removed any sensitive dat?

**Comment by rahulsri1505** [comment]
I guess you are talking about the   java_pid2384.hprof  file that log stash creates.
Its way too large to be uploaded (approx 17 GB)

**Comment by guyboertje** [comment]
it should compress well.

**Comment by cdpatelgit** [comment]
i'm working with rahulsri1505 

you need compress file of memory dump created by logstash ?

in logstash framework, is there any parameter supported that deal with huge number of files?
 if yes can yo u please suggest to us ?

how does file upload to elastic search works in log stash ? it it doing 1 by 1 ?

**Comment by guyboertje** [comment]
please post cleaned sanitised config then

**Comment by guyboertje** [comment]
are you using the file input?

**Comment by cdpatelgit** [comment]
here is the one of the config file

input {  file {type => "sample/test/test1" path => "/temp/sample_8887.json" codec => "json" start_position => "beginning" sincedb_path => "/dev/null" ignore_older => 0}} output { elasticsearch{ hosts => "localhost" index =>"sample_8887" } stdout { codec => rubydebug } }filter {mutate {convert => { "estAdvPayments" => "string" } convert => { "netPnlAccr" => "string" } convert => { "numberShares" => "string" } convert => { "grossCommissions" => "string" } convert => { "totalTurnoverUSD" => "string" } convert => { "isoft" => "string" } convert => { "data" => "string" } convert => { "pnl" => "string" } convert => { "netCommission" => "string" } convert => { "netPnl" => "string" } convert => { "tradeLR" => "string" } convert => { "netLR" => "string" } convert => { "retention" => "string" } convert => { "theoPnl" => "string" } convert => { "theoNet" => "string" } convert => { "theoNetLR" => "string" } convert => { "theoRetention" => "string" } convert => { "researchPayment" => "string" } convert => { "annYTDNet" => "string" } convert => { "grossYOYChg" => "string" } convert => { "netYOYChg" => "string" } convert => { "netYoyDiff" => "string" } convert => { "lastYrNetPnl" => "string" } convert => { "lastYrGross" => "string" } convert => { "budget" => "string" } convert => { "fYBudget" => "string" } convert => { "budgetDelta" => "string" } convert => { "budgetDiffPcnt" => "string" } convert => { "bsUsage" => "string" } convert => { "frc" => "string" } convert => { "roa" => "string" } convert => { "advTotal" => "string" } convert => { "advQ1" => "string" } convert => { "advQ2" => "string" } convert => { "advQ3" => "string" } convert => { "advQ4" => "string" } convert => { "exeTotal" => "string" } convert => { "exeQ1" => "string" } convert => { "exeQ2" => "string" } convert => { "exeQ3" => "string" } convert => { "exeQ4" => "string" } }}

**Comment by guyboertje** [comment]
how many of those configs do you have?

**Comment by rahulsri1505** [comment]
13000+
Each config stands for a particular index on elastic search.

**Comment by guyboertje** [comment]
That is not going work in one JVM at all, ever.

You are probably going to need something like this https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html#deploying-logstash-ha

Will your company pay for some Elastic Consulting?

**Comment by rahulsri1505** [comment]
Ok!
Is there a way to deduce that log stash has finished uploading a certain no. of files onto Elastic search?

**Comment by cdpatelgit** [comment]
thank you for all suggestion.

is there any JAVA API available which can upload data on ElasticSearch ?

**Comment by guyboertje** [comment]
The file input is designed for tailing a never ending (but rotated) log file. Therefore we never built in a mechanism to know when a file was 'done done'. There were some discussions about building a special file reader input that did not 'tail' and it would have had a signalling mechanism for EOF.

**Comment by guyboertje** [comment]
There are ways to use Beats, Node Ingest and ES to do simple ingestion without much transform. But this requires Elastic Stack 5.0.

**Comment by guyboertje** [comment]
ES has a Java Client.

**Comment by cdpatelgit** [comment]
yes, we are using ES java Client API for fetching data from Elastic Search Server 
does ES JAVA Client supports upload to ElasticSearch ?

We can use elasticsearch-5.1.1

do you want to suggest some tutorial to use Beats, Node Ingest and ES to do simple ingestion

I was thinking to  breakdown the file/data upload process in different instance of logstash but as you said its not easy to find upload process is done or not.

do you want to suggest some way from your experience to handle this scenario ?

**Comment by guyboertje** [comment]
You may have to script a way to "stage" say 100 files into 10 staging folders that is monitored by 10 LS instances. You can use [interpolated ES index strings](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index) that will resolve to a different index depending on the content of an event.

each event will contain the path that it was created from so you can extract the file name from the path key and add a field called say es_index that has e.g. "sample_8887" as its value.
Then the ES output will have this config:
```
output {
  elasticsearch {
   hosts => "localhost"
   index =>"%{es_index}"
  }
  stdout { codec => rubydebug }
}
```
About "knowing when a batch of 100 files is finished". LS 5.X has a metrics JSON Rest API. You can monitor that and see when the events-per-second falls to zero.
Or by using `close_older => 10` the file input will close the file 10 seconds after it is done with it - you can try `lsof` count on the staging folders to see when the open files drops to 0.

Hope this helps.

**Comment by cdpatelgit** [comment]
thank you very much for all suggestion and help

**Comment by cdpatelgit** [comment]
while uploading data on ES using logstash , I'm seeing below error. and i have already config changes  in order to convert numbers to string in config file, 

do you suggest, why its still failing 

[children.isoft] of different type, current_type [long], merged_type [double],

**Comment by ph** [comment]
I think the initial problems is solved.

@cdpatelgit for your last question I believe this is a mapping issue in the template,  I suggest you open a post on discuss at discuss.elastic.co
