### ISSUE TITLE
Monitoring:  Add hosts info to pipeline output stats

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6462]
When there are multiple instances of the same output plugin in the pipeline (eg. elasticsearch), the monitoring stats use an internal id to differentiate between them, which is not intuitive to the end user.  It will be nice if the outputs section will include the hosts array so it's easy to tell them apart.

```
      "outputs" : [ {
        "id" : "eaf58b94f952bc86193f0806aa7505382c0175c2-3",
        "events" : {
          "in" : 33215,
          "out" : 32590
        },
        "name" : "elasticsearch"
      }, {
        "id" : "eaf58b94f952bc86193f0806aa7505382c0175c2-2",
        "events" : {
          "in" : 33590,
          "out" : 33215
        },
        "name" : "elasticsearch"
      } ]
    }
```

Alternatively, have the output id -> hosts mapping as part of the nodes info api if we don't think the stats api is the right place for this.  Or provide a common option that can be used across plugins for users to label plugins and display that label as part of the stats output, etc..

**Comment by suyograo** [comment]
@ppf2 you can override `id` in each output section to call it whatever you want. For example, 

```
output {
  id => "ES output for host blah"
 ..
}
output {
     id => "ES output for host blah2"
 ..
}

**Comment by suyograo** [comment]
If no ID is specified in the config, LS generates a UUID.

**Comment by ppf2** [comment]
@suyograo Nice!  Can we document this "id" setting somewhere?  eg. as part of the plugins documentation as "common options" (either at the top level and/or at the different type level, eg. input/filter/output), and in the monitoring section?

**Comment by ph** [comment]
It appear we have a bug in the doc generator, it doesn't add the `id` attribute in the generated page.

I've created this issue https://github.com/elastic/logstash/issues/6398 concerning that problem and I will be closing this one.

Also we are working on a better algorithm to generate the ID this feature will be part of the LIR refactoring and the id will be consistent id between run if the pipeline doesn't change.
