### ISSUE TITLE
Beats: A plugin had an unrecoverable error

### ISSUE THREAD

**Issue by iyerabhi07** [elastic/logstash#6468]
Hi, I am using filebeat to send logs to logstash ( version: 5.1.1) on a remote machine. Both are on the same network and connectivity is there.

logstash config:
input {
  beats {
    port => 10001
  }
}

output {
  elasticsearch {
    hosts => "localhost:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}

Filebeat was configured to send on port 10001:
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.0.1:10001"]

I am getting the below error:
[ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Beats port=>10001, id=>"2cbcb83732a1b876f1b1ad45bed2946771191dee-1", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_aaae8008-b039-4eff-b272-81ac97192b0d", enable_metric=>true, charset=>"UTF-8">, host=>"0.0.0.0", ssl=>false, ssl_verify_mode=>"none", include_codec_tag=>true, ssl_handshake_timeout=>10000, congestion_threshold=>5, target_field_for_codec=>"message", tls_min_version=>1, tls_max_version=>1.2, cipher_suites=>["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"], client_inactivity_timeout=>60>
  Error: event executor terminated

I saw on some issue that this happens if there are multiple logstash instances running or if the port is being used. Solved all those. still problem persists.

**Comment by fxu-ppwd** [comment]
same as this: https://discuss.elastic.co/t/failed-to-submit-a-listener-notification-task-a-plugin-had-an-unrecoverable-error/60932 ?

**Comment by ph** [comment]
I've moved the issue there in the plugin repo. https://github.com/logstash-plugins/logstash-input-beats/issues/170 and i will take a look asap.
