### ISSUE TITLE
Docs sync is failing since #6464

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6469]
Since #6464 was merged, the docs sync jobs have been failing:

![image](https://cloud.githubusercontent.com/assets/131818/21595737/09ecb258-d0e6-11e6-8b17-269d2d59ca42.png)

A sample error from the docs-sync job (https://internal-ci.elastic.co/view/All/job/elastic+stack+5.x+unified-snapshot/125/console)

```
a2x: executing: "xmllint" --nonet --noout --valid "/var/lib/jenkins/workspace/elastic+docs-tools+master+sync-logstash-5.1-docs/logstash/build/elastic/logstash-docs/docs/html_docs/index.xml"

/var/lib/jenkins/workspace/elastic+docs-tools+master+sync-logstash-5.1-docs/logstash/build/elastic/logstash-docs/docs/html_docs/index.xml:2313: parser error : Opening and ending tag mismatch: section line 2305 and programlisting
slowlog.threshold.trace (default: -1)</programlisting>
```

Given this failure is coming from XML source, my best guess is that this is coming from whatever build_docs.pl does to turn asciidoc into html, presumably using xml as a middle step? I'm not sure, though.

Either way, I don't know how to debug this. The asciidoc change in #6464 seems ok to me.

@clintongormley, can you help with this?

**Comment by dedemorton** [comment]
This is an asciidoc problem. Created this PR with the fix: https://github.com/elastic/logstash/pull/6470

**Comment by suyograo** [comment]
All sync builds are green now.
