### ISSUE TITLE
Logstash slowlog field took_in_millis shows microseconds instead of milliseconds

### ISSUE THREAD

**Issue by nick4eva** [elastic/logstash#6476]
I configured Logstash slowlog like this:

slowlog.threshold.warn: 500ms
slowlog.threshold.info: 400ms
slowlog.threshold.debug: 300ms
slowlog.threshold.trace: 100ms

But I see in slowlog file trace entry with "took_in_millis":103180
I don't believe that my event processing 103 seconds, so I looked at source code and found that took_in_millis calculated incorrectly, it should be took_in_nanos / 1000000 instead of took_in_nanos / 1000:

[https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/logging/logger.rb#L109](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/logging/logger.rb#L109)

**Comment by suyograo** [comment]
Fixed in #6481
