### ISSUE TITLE
Typo in SQS output

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#6485]
[Here](https://www.elastic.co/guide/en/logstash/current/output-plugins.html) we have a typo;
> Pushes events to an Amazon Web Services Simple Queue Serice queue

Should be;
> Pushes events to an Amazon Web Services Simple Queue Service queue

I wasn't sure where this was to edit and issue a PR.

**Comment by ph** [comment]
You can do theses changes in the https://github.com/elastic/logstash-docs/pull/349 repo, I've made a PR on your behalf there.
Only the plugin page are automatic, the listing is still manual.
