### ISSUE TITLE
[docs] incorrect note about unreleased docker image in documentation for 5.x/5.1

### ISSUE THREAD

**Issue by weltenwort** [elastic/logstash#6487]
Instead of the instructions for retrieving the logstash docker image, the following paragraph is rendered in the ["Running Logstash on Docker" documentation page](https://www.elastic.co/guide/en/logstash/current/docker.html) even for the 5.x and 5.1 versions:

```
ifeval::["{release-state}"=="unreleased"]

However, version {logstash_version} of Logstash has not yet been
released, so no Docker image is currently available for this version.

endif::[]
```

The `ifeval` condition does not seem have the intended effect.

**Comment by dedemorton** [comment]
#6578 sets the release-state to "released" for 5.1. #6584 fixes the version info in the 5.x (prerelease) docs. "unreleased" is the correct release-state for 5.x.
