### ISSUE TITLE
Plugin uninstall requires being online

### ISSUE THREAD

**Issue by gquintana** [elastic/logstash#6491]
Being offline, removing a locally installed plugin requires being connected to internet.

- Version: 2.4.1
- Operating System: RHEL7
- Steps to Reproduce:
```
logstash-plugin install --no-verify --local /tmp/logstash-input-kafka-5.1.0.gem
...
logstash-plugin uninstall logstash-input-kafka
Uninstalling logstash-input-kafka
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/
```
After that failure, the plugin is not list anymore:
```
logstash-plugin list --verbose |grep kafka
```
returns nothing.
Yet plugin is still present on file system

**Comment by ph** [comment]
This was fixed in 5.2 which will be released shortly and include the new offline flow. see #6404 for more details.
