### ISSUE TITLE
Separation between global and pipeline specific settings

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6492]
Currently we have a big list of settings, and with the coming of multi pipeline, we need to know which settings should be set per pipeline.

Some are obvious such `pipeline.workers`, others are global (e.g. `http.port`), others should be per-pipeline even though they're not namespaced in the `pipeline.` (e.g. `slowlog.threshold.*`).

The ones I think should be per pipeline are:

- [ ] config.debug
- [ ] config.reload.automatic
- [ ] config.reload.interval
- [x] config.string
- [ ] log.format
- [ ] log.level
- [ ] metric.collect
- [x] path.config
- [x] pipeline.batch.delay
- [x] pipeline.batch.size
- [x] pipeline.id
- [x] pipeline.output.workers
- [x] pipeline.workers
- [x] queue.checkpoint.acks
- [x] queue.checkpoint.interval
- [x] queue.checkpoint.writes
- [x] queue.max_bytes
- [x] queue.max_events
- [x] queue.page_capacity
- [x] queue.type
- [ ] slowlog.threshold.debug
- [ ] slowlog.threshold.info
- [ ] slowlog.threshold.trace
- [ ] slowlog.threshold.warn

These could either be global or per pipeline:
- [ ] path.data
- [ ] path.logs

These are unique/global:
- [ ] interactive
- [ ] help
- [ ] version
- [ ] node.name
- [ ] config.multi_pipeline
- [ ] config.test_and_exit
- [ ] http.environment
- [ ] http.host
- [ ] http.port
- [ ] path.plugins
- [ ] path.settings

This is likely global, but we should consider deprecating it:
- [ ] pipeline.unsafe_shutdown

Thoughts?

**Comment by suyograo** [comment]
@jsvd I'm really wary of refactoring all the settings for v1 of multipipeline. My suggestion is to just identify the most important settings that users would want to be separate in different pipelines for the first iteration. I understand things like workers/metrics/delay etc can be configured to be pipeline specific, but for the first release, we should just go with these being global. We'll learn a lot from this release, and we can make iterative changes once we get feedback.

So, what I am suggesting is that we make:
`config.string`
`path.config`
`queue.*`

as the only available per-pipeline settings for v1. Everything else is global as it is today. For example, if you enable reload, you enable it for all pipelines.

**Comment by jsvd** [comment]
@suyograo the `pipeline.*` settings are also easy to customize per pipeline:

 pipeline.batch.delay
 pipeline.batch.size
 pipeline.id
 pipeline.output.workers
 pipeline.workers

I agree `config.string` and `path.config` should also be set per pipeline.

I'm going to investigate what's required to make `queue.*` work

**Comment by jsvd** [comment]
To sum up, the list of settings supported per pipeline for the first implementation will be:

-  path.config
-  pipeline.batch.delay
-  pipeline.batch.size
-  pipeline.id
-  pipeline.output.workers
-  pipeline.workers
-  queue.checkpoint.acks
-  queue.checkpoint.interval
-  queue.checkpoint.writes
-  queue.max_bytes
-  queue.max_events
-  queue.page_capacity
-  queue.type
-  config.string
