### ISSUE TITLE
[New Plugin] JDBC lookup enrichment - full local caching

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6502]
This encompasses the JDBC lookup enrichment piece of the meta issue [here](https://github.com/elastic/logstash/issues/5221). 

## Goals
Enable the ability to lookup and enrich events from relational databases, commonly needed for users running CMDBs or using traditional data warehousing. We've decided two separate plugins are needed for two use cases:

1. **Lookup on event** (logstash-filter-jdbc_streaming) - @wiibaa's [PR](https://github.com/logstash-plugins/logstash-filter-jdbc/pull/1) should cover this use case
    - Executes a SQL query per event and stores the result set in a new event field.
    - This could be useful for DB lookup data that changes frequently, but will have performance impact due to the query and network round trip per event.
    - We should add an LRU caching option, but caching in general is optional.
2. **Lookup & cache on start** (logstash-filter-jdbc_static) - requirements covered in this issue
    - Enables caching and refreshing a SQL result set locally in Logstash (in-memory, but potentially to disk in the future) for scalable lookup enrichment. Primary or composite key lookups should be supported.
    - This will be a new plugin, separate from "Lookup on event," since it has different behavior and goals.

## Features
- Allow for caching of JDBC result datasets, hashed in-memory by a specific key for fast lookup and field enrichment
- Lookups can be done with a primary key or composite key
- Max cache size should be configurable
- Periodic reloading of cache, in seconds - live refresh with subsequent JDBC query

When Logstash first starts up, it should automatically query the DB and load the result set locally in cache. For fast retrieval, each row can probably be hashed by the primary or composite key. Since we always know the key for every event, it should be O(1) access.

## Configuration
```
filter {
  jdbc {
    # Setup JDBC connection
    jdbc_driver_library => "/path/to/mysql-connector-java-5.1.34-bin.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => ""jdbc:mysql://localhost:3306/mydatabase"
    jdbc_user => "me"
    jdbc_password => "secret"
    
    # JDBC query statement - queries DB and caches dataset locally for enrichment purposes.
    # Pushdown filtering can be done here to mitigate unnecessary data movement across the network.
    load_statement => "select * from WORLD.COUNTRY"

    # Lookup query statement - select fields to enrich your events, and what keys to lookup on.
    # Define fields to enrich events with the SELECT clause, renaming new looked up fields is also possible with an AS clause
    # Define keys to lookup on with the WHERE clause. The '%{key}' syntax can be used to reference a Logstash event field.
    # Composite key lookups can be done using multiple WHERE predicates.
    lookup_statement => "SELECT country_name AS cname, country_details AS cdetails FROM local WHERE country_code = '%{code}' AND organization = '%{org}'"

    # Cache settings
    refresh_schedule => "0 * * * *"  # Refresh cache every hour. Cron syntax like the JDBC input scheduler. (Optional) - default = never refresh
    cache_size => "1MB"  # (Optional) - need to find a good default for this, maybe 500MB?
  }
}
```

## Example
**DB Data**
```
| country_code | organization | country_name | country_details |
| "USA" | "Elastic" | "United States" | "awesome" |
| "EU" | "Elastic" | "Europe" | "also awesome" |
```

**Starting Logstash Event**
```
{
  "@timestamp" => 2017-01-03T14:36:43.000Z,
  "@version" => "1",
  "code" => "USA",
  "org" => "Elastic",
  "message" => "DB lookup"
}
```

**Ending Logstash Event**
```
{
  "@timestamp" => 2017-01-03T14:36:43.000Z,
  "@version" => "1",
  "code" => "USA",
  "org" => "Elastic",
  "cname" => "United States",
  "cdetails" => "awesome",
  "message" => "DB lookup"
}
```

## Failure Handling
If lookups fail, we can tag it "_jdbclookupfailure".

**Comment by acchen97** [comment]
@untergeek @suyograo @jordansissel thoughts on the naming for this plugin? logstash-filter-jdbc_local? logstash-filter-jdbc_cache?

**Comment by suyograo** [comment]
@acchen97 my vote for `logstash-filter-jdbc_local` or `logstash-filter-jdbc_static`. I also suggest we rename https://github.com/logstash-plugins/logstash-filter-jdbc to `logstash-filter-jdbc_streaming`

**Comment by suyograo** [comment]
Also, `max_cache_size` to simply `cache_size`

**Comment by untergeek** [comment]
+1 to rename them `-static` & `-streaming`

**Comment by acchen97** [comment]
> Also, `max_cache_size` to simply `cache_size`

Updated.

For the naming, how about we do `logstash-filter-jdbc_local` and `logstash-filter-jdbc_streaming`? I prefer not to use `static` as the cache refreshes still essentially make it dynamic.

**Comment by untergeek** [comment]
`static` may be a poor name choice, but it's essentially static while it's _between_ cache cycles.  It's assumed this is a less frequently updated dataset, otherwise you'd use the `streaming` filter.

**Comment by untergeek** [comment]
I don't like `local` because it doesn't really define what it does.  Local is a place, not a behavior.

**Comment by acchen97** [comment]
Makes sense, I'm good with `static` and `streaming` as well then.

**Comment by suyograo** [comment]
Created https://github.com/logstash-plugins/logstash-filter-jdbc_static and renamed https://github.com/logstash-plugins/logstash-filter-jdbc_streaming

/cc @wiibaa

**Comment by paulmchugh777** [comment]
Hi, I'm very interested in using the proposed JDBC enrichment plugin.

Any idea when a version of this will be available for initial testing and when a final release will be available?

Many thanks

Paul

**Comment by jordansissel** [comment]
@paulcoghlan https://github.com/logstash-plugins/logstash-filter-jdbc_static and https://github.com/logstash-plugins/logstash-filter-jdbc_streaming are where development will be happening. You can watch these.

**Comment by acchen97** [comment]
@paulmchugh777 this is a high priority functionality. Let me know if you did happen to have any feedback on the current requirements.

**Comment by paulmchugh777** [comment]
Hi,

Thanks for getting back to me.

We are considering using logstash for an ETL into Elastic. 

The source of the data is a large single DB table of about 10 million rows and we are having to detect the delta in these rows every few minutes or so and read the changes and write them to Elastic.

The lookup is required as some of the fields in the table are IDs and they have to be dereferenced in lookup tables.

However, new entries to these lookup tables are added from time to time in an unpredictable way so a totally static cache will not work.

The **Lookup on Event** plugin you are proposing would only be usable for us if the caching were implemented, otherwise the performance hit would be too great. If a caching feature were provided so entries that are read are cached and any new ids that are added to the data result in a cache miss and the new entry being read, this would be ideal.

The **Lookup & cache on start** plugin as specified, would not be usable because new IDs appearing in the data would result in lookup misses.

However, if it was possible to configure the **Lookup & cache on start** plugin to refresh on a lookup miss, then this would also work for us; (if there was still a miss after the refresh, then it would be processed as a normal error).

Both ideas solve the problem of lookup data changing slowly over time.

Any idea on timelines for when these plugins might be available?

Many thanks

Paul

**Comment by acchen97** [comment]
@paulcoghlan no target yet, and thanks for your input. We do plan to add caching for the lookup on event use case https://github.com/logstash-plugins/logstash-filter-jdbc_streaming/issues/3.

**Comment by Guduowai** [comment]
Hello!
Please i have question about how to use jdbc_streaming
input{
  jdbc{
    statement => "select field1, field2, field3 from database1"
    ......
  }
}
filter {
  jdbc_streaming {
    statement => "select field5 from database2 where field 4 = :field2val"
    parameters => {"field2val" => "field2"}
}
this is how look my configuration file but seems doesn't work any help please

**Comment by jordansissel** [comment]
@Guduowai please open a discussion on https://discuss.elastic.co for this question.

**Comment by acchen97** [comment]
Closing as this has been delivered with PR https://github.com/logstash-plugins/logstash-filter-jdbc_static/pull/2.

Plugin documentation is still outstanding, but is tracked in a separate issue: https://github.com/elastic/logstash/issues/8683

/cc @guyboertje @dedemorton

**Comment by seanziee** [comment]
@acchen97  I'm looking for this exact functionality, thanks for putting this together... I'll be patiently waiting for the PR to come through!
