### ISSUE TITLE
Error bundle install Could not fetch specs from https://rubygems.org/ Im using windows 8.1

### ISSUE THREAD

**Issue by Ingosmar89219** [elastic/logstash#6503]
C:\Users\osmarvirux>bundler -v
Bundler version 1.13.7
C:\Users\osmarvirux>ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x64-mingw32]

C:\Users\osmarvirux>rails -v
DL is deprecated, please use Fiddle
Rails 4.2.3

C:\Users\osmarvirux\Documents\mackenzi_rails\platform_rails>bundle install
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs fr
om https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs fr
om https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs fr
om https://rubygems.org/Could not fetch specs from https://rubygems.org/

i hope your answer friends. thanks a lot

**Comment by guyboertje** [comment]
From what you have posted above, I can't see how this is related to Logstash.
Please provide the details requested in the New Issue Template...
```
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

```

**Comment by ph** [comment]
I will close this issue since it doesn't appear to be related to this project.

**Comment by untergeek** [comment]
Even if it were, Logstash runs exclusively in JRuby, not ruby or rails.
