### ISSUE TITLE
prevent multiple logstash instances from using the same path.data and path.queue

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6505]
currently there's nothing preventing a user from enabling the persistent queues and starting two logstash instances, likely corrupting the PQ or seeing strange event patterns.

This is a likely scenario in production environments where an init script malfunctions during restart and starts a second logstash instance.

/cc @colinsurprenant

**Comment by colinsurprenant** [comment]
Absolutely, will address this.

**Comment by colinsurprenant** [comment]
I am not sure how this will be possible to address in a practical way - file locking across different processes/JVM has portability issues and race condition problems. 

We could think about a flag file which indicates that the queue is in-use by another process but we have to figure how to deal with it upon a unclean shutdown? - what if LS starts and this flag file is set but there is actually not other LS process actually running?

Any thoughts?

**Comment by ph** [comment]
Maybe it's just to have a `logstash.lock` file in the queue path and try to release it when logstash stop or crash when possible, with the right signal. We will do our possible to release the lock at the end of the execution (keep the pid in the lock?)

But if the *.lock still exist, we can raise a warning and the script will fail to start, these scenario will be easily monitored with monit or even with the monitoring API.

I haven't check the code, but IIRC ES deal with that case too.

**Comment by jsvd** [comment]
After discussing with the team, we decided to broaden the scope of this issue to not just the queue but the path.data too.
So the solution will be to have two .lock files - one in path.data and another in path.queue - and use a file locking mechanism to prevent more than one instance from using those directories.

The mechanism to achieve file locking will depend on the operating system family. On linux systems the .lock file can be opened in exclusive mode, so two logstash instances will not be able to open the same file.
On Windows files are open exclusively already by default, so no extra functionality is required to detect this conflict.

**Comment by colinsurprenant** [comment]
@jsvd @jordansissel  I am not sure we need have different strategies between Windows and Linux if we use the `FileChannel` `FileLock` in a similar way as ES/Lucene per https://github.com/apache/lucene-solr/blob/8c2ef3bc7fbebe8105c2646c81489aa9393ad402/lucene/core/src/java/org/apache/lucene/store/NativeFSLockFactory.java#L86-L129

**Comment by colinsurprenant** [comment]
The queue exclusive access is now solved in #6656

**Comment by colinsurprenant** [comment]
I suggest we close this issue and re-open one specific for locking `path.data`.
