### ISSUE TITLE
Modify queue API response

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6508]
After a discussion on zoom with @jordansissel @colinsurprenant and @talevy, we decided to modify the queue response to make it most actionable to the user. 

- [ ] Introduce a page level API `_node/stats/queue` which provides detailed queue and page level stats to track acks per page
- [x] Modify existing response to only include `queue.events` as a single field that reports current unread events in the queue. Remove `acked_count`, `unacked_count` and `unread_count`
- [ ] Remove `current_size_in_bytes` and replace it with `queue_size_on_disk` which is a percent value calculated from `current_size_in_bytes` (the accurate value, not logical) and `max_queue_size_in_bytes`

**Comment by colinsurprenant** [comment]
This is being discussed in #8986

**Comment by colinsurprenant** [comment]
closing this as it is being followed up in #8986 and #8936.
