### ISSUE TITLE
mem type listed in Node Stats API documentation

### ISSUE THREAD

**Issue by inqueue** [elastic/logstash#6511]
Node Stats API documentation lists a `mem` type for collecting memory usage stats which does not exist as an endpoint. 

Mac OS X:
```
curl 'localhost:9600/_node/stats/mem'
{"path":"/_node/stats/mem","status":404,"error":{"message":"Not Found"}}
```

It looks like the docs just need updated since memory stats fall under JVM.

**Comment by dedemorton** [comment]
Closing because this is already fixed in 5.2 and later. Opened PR #7201 for 5.0 and 5.1 docs.
