### ISSUE TITLE
set queue path based on pipeline id

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6513]
With the upcoming multi pipeline features, it's necessary that each pipeline has its own queue, so the files needs to be namespaced in a directory that should be named after the pipeline id.

This extra namespace/directory could either be injected and created during the [build_queue_from_settings](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/pipeline.rb#L140) or somewhere during [create_file_based](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/wrapped_acked_queue.rb#L28)

required for multi pipeline feature (issue #6521)

**Comment by ph** [comment]
Could be part of https://github.com/elastic/logstash/issues/6513

**Comment by jsvd** [comment]
@ph still want to do this as part of that PR? I'm ok with merging this and then addressing it in a new PR

**Comment by ph** [comment]
lets merge #6498 and you can create a new pr for it?

**Comment by suyograo** [comment]
Fixed by #6540
