### ISSUE TITLE
Logstash can hang calculating hostname

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#6520]
We use `Socket.gethostname` in some spots in the API without caching its output under [some conditions](http://www.markhneedham.com/blog/2015/03/29/inetaddressimpllookupallhostaddr-slowhangs/) this can be very slow. @tsouza encountered this issue not too long ago. 

We should cache this value once at startup and reuse it to fix this issue. It is not safe to depend on it being fast all the time.

**Comment by tsouza** [comment]
Here is the original issue https://github.com/elastic/logstash/issues/6516

**Comment by jordansissel** [comment]
Just a note, `Socket.gethostname` is something we should expect to be a nonstable value during the life of Logstash - a server's hostname can change. Further, I think speeding up the Socket.gethostname call is just a band-aid on the problem -- why are we calling Socket.gethostname for every http request received by the http api?

Given the report in #6516, I think the best fix is to simply avoid this lookup.

**Comment by andrewvc** [comment]
@jordansissel we return the hostname as part of the standard response. 

While yes, it can change in the middle of a Logstash run, I don't think it's too much to ask a user to restart logstash if they change the hostname.

**Comment by jordansissel** [comment]
@andrewvc If we're going to do that, maybe we should do what other non-java tools do.

* ruby calls `uname` to get the hostname
* `hostname` calls `uname` to get the hostname
* `uname -n` calls `uname` to get the hostname
* JRuby seems to call `uname` and then make a bunch of socket calls that seems to be checking for what addresses are used when connecting on various networks (IPV6, IPV4)

I'm pretty content to just fetch our hostname using the `uname` syscall. It avoids doing dns lookups and avoids any possibly-bad cachine; caching is something we'd have to document and take bugs against.

**Comment by andrewvc** [comment]
@jordansissel I'm fine with that but how do we invoke the `uname` syscall on Java? I'd rather not get into JNI here.

**Comment by andrewvc** [comment]
@jordansissel an interesting SO post on the topic http://stackoverflow.com/questions/7348711/recommended-way-to-get-hostname-in-java

**Comment by jordansissel** [comment]
@andrewvc FFI or JNA are fine methods for calling native code, imo.

**Comment by jordansissel** [comment]
@andrewvc I don't' have any comment on the SO post, but for the platforms we support:

1) It's probably incorrect behavior to do a DNS lookup when asking what the system hostname is.
2) We support Linux and Windows and can target those (`uname` on Linux and `GetComputerNameEx` on Windows)
3) With a fallback to Socket.gethostname for other platforms.

**Comment by tsouza** [comment]
How about trying to do same as elasticsearch does? Does elasticsearch returns hostname in any of it's stats API (I don't recall any right now)? 

If yes, then how is it implemented? 

If not, then why should logstash return hostname anyway?

**Comment by suyograo** [comment]
Fixed in #7858
