### ISSUE TITLE
Remove Codec#flush

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#6523]
The `Codec` class still defines a `flush` method. This is problematic because asynchrony in codecs is incompatible with our goal of at-least-once durability.

Additionally, nothing calls this class at the moment, and no working official codecs use this method. The gzip codec does, but it's been broken for a long time ( we should delete it ).

I propose that we remove this method. This would be a breaking change technically, but seeing as how the feature never really 'worked' in 5.x Logstash I doubt it would be missed.

I would like to get feedback before this change is made.

**Comment by jsvd** [comment]
I haven't done any research on the current use of flush, are there any "non official" codecs that use it?

I don't see a reason to rush removing it in the 5.x line. I suggest a tactic of:
* detecting a plugin uses flush and warning that using such a plugin means this loss of the guarantee.
* marking the api as deprecated in the next 5.x
* make it obsolete (unusable) in 6.x

**Comment by andrewvc** [comment]
@jsvd I have to revise the approach here. We *need* flush for the encode side of codecs, esp. the Multiline codec. 

I'm changing my proposal to just be changing the documentation to clarify that `flush` only affects the `decode` side of a codec, but has no effect on the `encode` side.

Unfortunately it's too hard to detect whether a usage is proper or not given that its called `flush`. I propose that in 6.0 we should rename it to `flush_decode`.

**Comment by guyboertje** [comment]
or `decode_flush`

**Comment by andrewvc** [comment]
@guyboertje I'm thinking we really need to go ahead and split all codecs into separate encode/decode classes. Anything we come up with here will be a hacky band-aid.

**Comment by cwurm** [comment]
It seems to me that without some kind of flush method, the multiline codec cannot work reliably: https://github.com/logstash-plugins/logstash-codec-multiline/issues/57

`input-stdin` with `codec-multiline` should probably not be used at all.

**Comment by colinsurprenant** [comment]
Closing this. We can revisit this if/when we have plans to refactor the codecs design.
