### ISSUE TITLE
Cannot install any plugin on windows

### ISSUE THREAD

**Issue by dpanda** [elastic/logstash#6529]
Logstash 5.1.1 on Windows 7 32bit, trying without success to install logstash-filter-elapsed. Below the method I tried.

Before running plugin installer, I run:

    set DEBUG=1

to show debug output.

Then I run:

    logstash-plugin install logstash-filter-elapsed

This fails both when I'm in my corporate network (with proxy) and when using a network without proxy, with the following error:

    Looking if package named: logstash-filter-elapsed exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-elapsed/logstash-filter-elapsed-5.1.1.zip
    Errno::ECONNREFUSED: Connection refused - Connection refused
              initialize at org/jruby/ext/socket/RubyTCPSocket.java:126
                    open at org/jruby/RubyIO.java:1197
                 connect at C:/tools/logstash-5.1.1/vendor/jruby/lib/ruby/1.9/net/http.rb:763
                 timeout at org/jruby/ext/timeout/Timeout.java:98
                 connect at C:/tools/logstash-5.1.1/vendor/jruby/lib/ruby/1.9/net/http.rb:763
                do_start at C:/tools/logstash-5.1.1/vendor/jruby/lib/ruby/1.9/net/http.rb:756
                   start at C:/tools/logstash-5.1.1/vendor/jruby/lib/ruby/1.9/net/http.rb:745
                   start at C:/tools/logstash-5.1.1/vendor/jruby/lib/ruby/1.9/net/http.rb:557
                   start at C:/tools/logstash-5.1.1/lib/pluginmanager/utils/http_client.rb:13
      remote_file_exist? at C:/tools/logstash-5.1.1/lib/pluginmanager/utils/http_client.rb:23
       get_installer_for at C:/tools/logstash-5.1.1/lib/pluginmanager/pack_fetch_strategy/repository.rb:27
                  create at C:/tools/logstash-5.1.1/lib/pluginmanager/install_strategy_factory.rb:15
                    each at org/jruby/RubyArray.java:1613
                  create at C:/tools/logstash-5.1.1/lib/pluginmanager/install_strategy_factory.rb:14
                 execute at C:/tools/logstash-5.1.1/lib/pluginmanager/install.rb:27
                     run at C:/tools/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                 execute at C:/tools/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                     run at C:/tools/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                     run at C:/tools/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
                  (root) at C:\tools\logstash-5.1.1\lib\pluginmanager\main.rb:46

It seems that there's a timeout in contacting the url "https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-elapsed/logstash-filter-elapsed-5.1.1.zip".

Opening this url in a browser returns an xml with an error message (seems like the xml you when trying to access a not existing object from a AWS S3 bucket).

Adding the `--no-verify` flag yelds the same result.

I tried to bypass this problematic "Looking if package named:..." step: I edited `logstash-5.1.1\lib\pluginmanager\pack_fetch_strategy\repository.rb`, adding a `return nil` at the beginning of the `def get_installer_for(plugin_name)`.

Running the installation, I get another error:

    Installing logstash-filter-elapsed
    Error Bundler::HTTPError, retrying 1/10
    Could not fetch specs from https://rubygems.org/
    Error Bundler::HTTPError, retrying 2/10
    Could not fetch specs from https://rubygems.org/
    ...

**Comment by ph** [comment]
I will take a look

**Comment by ph** [comment]
We now give better error when this issue happen #7447 which seems to be a network error or a firewall issues.
