### ISSUE TITLE
validate set of required and optional settings on multi pipeline

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6541]
In a world of multiple pipelines, when creating a new pipeline, a list of constraints must be met:

* pipeline.id must be set and be unique
* either config.string or config.path (or both) must be set
* all settings defined for a pipeline must be from the ["per-pipeline settings" list](https://github.com/elastic/logstash/issues/6492)

Also, global settings like pipeline.id, config.string and config.path must not be changed from the defaults.

I'll update this issue if I find more constraints.

**Comment by suyograo** [comment]
@jsvd one other thing -- the automatic merging of config files should be turned off for multi-pipeline. We discussed in one of our design meetings that in a multi-pipeline scenario, each pipeline specified is a fully contained LS config. Merging would add unnecessary complexity to this definition.

**Comment by jsvd** [comment]
@suyograo you mean restricting `path.config` to a single file, or merging `path.config` + `config.string`? Or both?

**Comment by suyograo** [comment]
I was thinking about `path.config`, but you bring up a good point about that functionality already existing. 

In MP world, when would users want merging of `path.config` + `config.string` ? they could just have two pipelines for that, no? WDYT?

**Comment by jsvd** [comment]
well, they'd probably use path.config+config.string merging for the same purpose they do now: using config.string to debug the path.config, by doing something like
`config.string: "output { if [type] == "weird" { stdout { codec =>rubydebug } } }"

**Comment by jsvd** [comment]
done in https://github.com/elastic/logstash/pull/6525
