### ISSUE TITLE
Add filename field in logstash-input-s3 event

### ISSUE THREAD

**Issue by phirov** [elastic/logstash#6547]
The object's name or filename in a S3 bucket is an import information which can mark the record data where it came from (especially, when there are huge files in a bucket).

There are many requirements on the stackoverflow, e.g.

 - http://stackoverflow.com/questions/20512416/adding-tags-to-logstash-events-based-on-the-md5-of-the-filename
 - http://stackoverflow.com/questions/24566122/logstash-how-to-use-filter-to-match-filename-when-using-s3
 - http://stackoverflow.com/questions/24613281/extracting-fields-from-aws-s3-input-paths-in-logstash
 - http://stackoverflow.com/questions/35762625/logstash-config-s3-filenames

Mount S3 to a local file system and use logstash-input-file is another solution to get the filename infomation. But in some circumstance, this will become more complicated when it is used in docker.

Since there is path field in logstash-input-file, why cannot include this to logstash-input-s3.

**Comment by acchen97** [comment]
Closing as [duplicate](https://github.com/logstash-plugins/logstash-input-s3/issues/104) has been filed in the S3 input, which is the correct location for this.
