### ISSUE TITLE
Add bootstrap checks to persistent queue

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6552]
When persistent queue is enabled, add the following bootstrap checks when starting LS

- [ ] validate if there is enough disk space to allocate at least page-size worth of data.
- [ ] ensure `queue.max_bytes` is available on disk.

 If these are not satisfied, Logstash should fail to start up.

**Comment by jsvd** [comment]
When logstash starts, the first it does on the PQ code is to behead the head page and create a new one, so we could abort execution and page creation time.

Checking disk free size in runtime also solves the runtime corner case creating new pages while low on disk space but being under queue.max_bytes

**Comment by original-brownbear** [comment]
@suyograo gave it a shot here: https://github.com/elastic/logstash/pull/6998 :)

**Comment by colinsurprenant** [comment]
good stuff @original-brownbear. I started reviewing #6998 and I think we need to agree/discuss a few corner cases. I will followup in the PR.

**Comment by colinsurprenant** [comment]
@suyograo @jsvd your input welcome in #6998 :D

**Comment by colinsurprenant** [comment]
fixed by #8978
