### ISSUE TITLE
can not instal jira output plugi

### ISSUE THREAD

**Issue by pmobcc** [elastic/logstash#6557]
Hello,

I've just started with logstash and I'm not able to install JIRA output plugin. I'm using logstash 5.1.1 on Windows 7.
Error I got is below.
Please help.

Best
pmobcc

...
    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core-plugin-api (<= 2.99, >= 1.60) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core-plugin-api (<= 2.99, >= 1.60) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core-plugin-api (<= 2.99, >= 1.60) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core-plugin-api (<= 2.99, >= 1.60) java

    logstash-input-s3 (>= 0) java depends on
      logstash-mixin-aws (>= 0) java depends on
        logstash-core-plugin-api (<= 2.99, >= 1.60) java

    logstash-output-jira (>= 0) java depends on
      logstash-core-plugin-api (~> 1.0) java

    logstash-core-plugin-api (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.1.1)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.1.1) java

    logstash-output-jira (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.1.1)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.1.1) java

    logstash-output-jira (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-output-jira (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem
 'logstash-output-jira (>= 0) java', in any of the sources.

**Comment by ph** [comment]
There is a pending PR at https://github.com/logstash-plugins/logstash-output-jira/pull/7
I will try to get that merged today.

**Comment by pmobcc** [comment]
Hi,

Thank you for the information. I was able to install JIRA output plugin with logstash 5.2.0.
But still I’m getting errors when I try to add a new task to JIRA.
Below you can find the error message I got.
Please let me know if you have any solution for this.

Best
Pawel Mostek

15:46:35.270 [LogStash::Runner] FATAL logstash.runner - An unexpected error occu
rred! {:error=>#<MultiJson::ParseError: Unexpected character ('<' (code 60)): ex
pected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: [B@43859f5d; line: 1, column: 2]>, :backtrace=>["com/jrjackson/JrJa
cksonRuby.java:63:in `parse'", "D:/work/programy/logstash-5.2.0/vendor/bundle/jr
uby/1.9/gems/jrjackson-0.4.2-java/lib/jrjackson/jrjackson.rb:53:in `load'", "D:/
work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/multi_json-1.12.1/lib/
multi_json/adapters/jr_jackson.rb:11:in `load'", "D:/work/programy/logstash-5.2.
0/vendor/bundle/jruby/1.9/gems/multi_json-1.12.1/lib/multi_json/adapter.rb:21:in
`load'", "D:/work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/multi_js
on-1.12.1/lib/multi_json.rb:122:in `load'", "D:/work/programy/logstash-5.2.0/ven
dor/bundle/jruby/1.9/gems/httparty-0.11.0/lib/httparty/parser.rb:115:in `json'",
"D:/work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/httparty-0.11.0/l
ib/httparty/parser.rb:134:in `parse_supported_format'", "D:/work/programy/logsta
sh-5.2.0/vendor/bundle/jruby/1.9/gems/httparty-0.11.0/lib/httparty/parser.rb:100
:in `parse'", "D:/work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/http
arty-0.11.0/lib/httparty/parser.rb:64:in `call'", "D:/work/programy/logstash-5.2
.0/vendor/bundle/jruby/1.9/gems/httparty-0.11.0/lib/httparty/request.rb:215:in `
parse_response'", "D:/work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/
httparty-0.11.0/lib/httparty/request.rb:185:in `handle_response'", "org/jruby/Ru
byProc.java:281:in `call'", "D:/work/programy/logstash-5.2.0/vendor/bundle/jruby
/1.9/gems/httparty-0.11.0/lib/httparty/response.rb:18:in `parsed_response'", "D:
/work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/httparty-0.11.0/lib/h
ttparty/response.rb:56:in `method_missing'", "D:/work/programy/logstash-5.2.0/ve
ndor/bundle/jruby/1.9/gems/jiralicious-0.2.2/lib/jiralicious/base.rb:107:in `han
dler'", "org/jruby/RubyProc.java:281:in `call'", "D:/work/programy/logstash-5.2.
0/vendor/bundle/jruby/1.9/gems/jiralicious-0.2.2/lib/jiralicious/session.rb:32:i
n `request'", "D:/work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/jira
licious-0.2.2/lib/jiralicious/base.rb:92:in `fetch'", "D:/work/programy/logstash
-5.2.0/vendor/bundle/jruby/1.9/gems/jiralicious-0.2.2/lib/jiralicious/issue.rb:9
6:in `create'", "D:/work/programy/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/ji
ralicious-0.2.2/lib/jiralicious/issue.rb:196:in `save'", "D:/work/programy/logst
ash-5.2.0/vendor/bundle/jruby/1.9/gems/logstash-output-jira-3.0.0/lib/logstash/o
utputs/jira.rb:141:in `receive'", "D:/work/programy/logstash-5.2.0/logstash-core
/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:
1613:in `each'", "D:/work/programy/logstash-5.2.0/logstash-core/lib/logstash/out
puts/base.rb:92:in `multi_receive'", "D:/work/programy/logstash-5.2.0/logstash-c
ore/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "
D:/work/programy/logstash-5.2.0/logstash-core/lib/logstash/output_delegator.rb:4
3:in `multi_receive'", "D:/work/programy/logstash-5.2.0/logstash-core/lib/logsta
sh/pipeline.rb:336:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'",
"D:/work/programy/logstash-5.2.0/logstash-core/lib/logstash/pipeline.rb:335:in
`output_batch'", "D:/work/programy/logstash-5.2.0/logstash-core/lib/logstash/pip
eline.rb:293:in `worker_loop'", "D:/work/programy/logstash-5.2.0/logstash-core/l
ib/logstash/pipeline.rb:263:in `start_workers'"]}

**Comment by ph** [comment]
@pmobcc Can you open an issue on the jira plugin repo this seems to be a specific issue with that plugin.
