### ISSUE TITLE
Location of logstash.yml?

### ISSUE THREAD

**Issue by scheung38** [elastic/logstash#6573]
Can any show me where to put this logstash.yml file for logstash to read config from?

Old tutorials are at /etc/logstash but because I installed via

$ brew install logstash

so have no idea where to start, even though I can find a copy from 

https://github.com/elastic/logstash/blob/master/config/logstash.yml

This tutorial says /etc/logstash/logstash.yml but I could not find it, or I need to manually create it?

https://www.elastic.co/webinars/getting-started-logstash

**Comment by nealp9084** [comment]
According to the docs, the config file is located at LOGSTASH_HOME/config. You can either (1) find out the value of LOGSTASH_HOME, or (2) run logstash with strace and see which file it is trying to access.

**Comment by dmnc-net** [comment]
Hi, I have similar issue. According to the v.5.1 docs, `logstah.yml`  is located in `LOGSTASH_HOME/config`. But config file is located in `/etc/logstash`. I've installed Logstash on Debian 8.7 (TKL Core) by following the docs. In this point docs are wrong or some symlink is needed. This issue will be probably in the Elasticsearch and Kibana too.

**Comment by untergeek** [comment]
Brew has done something unique with it.  Brew tends to keep configurations in /usr/local/etc, but nothing of the sort seems to have been done for Logstash.  You can read up a bit more on the logstash formula [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/logstash.rb).

I'm honestly not sure what they're thinking with that layout, but you can find the `logstash.yml` file in `/usr/local/Cellar/logstash/5.1.2/libexec/config`

For your sake, I recommend copying the entire `config` directory to somewhere else, like `/usr/local/etc/logstash`, and running with the `--path.config` flag set to that path.

I re-iterate, this is an atypical installation, and I don't know why it is the way it is, or why it has been configured this way.  This is something to take up with the person(s) who made the brew recipe.  Marking this closed.

**Comment by swapnilbagadia** [comment]
Where is conf.d directory in this setup where I can set *.conf files?
