### ISSUE TITLE
Fix or remove protocol-free SafeURI before JRuby 9x merged

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#6576]
Valid IPv6 URLs consisting of a relative URL pointing to an IPv6 host are broken in the ruby standard library in JRuby 9k. An example would be `//[::1]`. That was a valid URI in Jruby 1.7.x, but is no longer in 9.x. This also breaks in CRuby 2.4.0.

This breaks the elasticsearch output with Jruby 9.x. 

I'm already thinking about deprecating the SafeURI class due to the danger of passwords in URIs. Maybe it was a bad idea, and plugins should generally try to avoid URLs. Either way, we need to track this before we merge JRuby 9k.

See also: #5606

**Comment by ph** [comment]
What the remaining work for this issue?

**Comment by andrewvc** [comment]
This was fixed in

https://github.com/elastic/logstash/pull/7236
and 
https://github.com/elastic/logstash/pull/7687
