### ISSUE TITLE
combine the results of 2 events into one index

### ISSUE THREAD

**Issue by kramach1980** [elastic/logstash#6586]
I am running logstash v2.1 on ubuntu 14.04. I am sending a huge log file using filebeat into logstash. In logstash, I want to be able to combine the results of 2 grok searches and define an appropriate tag or new index. 

In the same log file, I have two lines:
2017-01-20 15:48:26.906 UTC: [classname] {INFO} Test Success test_100_basic_call_line_audio_to_audio

2017-01-20 15:48:26.685 UTC: [classname] {INFO} Test Venue from Environment detected as : venue

In my logstash config, i can have grok patterns to detect both these lines. 
filter {
  if [type] == "log" {
    grok {
      match => [ "message", "%{TIMESTAMP_ISO8601:log_timestamp} %{WORD:zone}: \[%{WORD:sender}\] {%{LOGLEVEL:loglevel}} Test %{WORD:passOrFail} %{WORD:testname} \(%{NOTSPACE:testclass}\)"]
      add_tag => ["test_info"]
    }
    grok {
      match => [ "message", "%{TIMESTAMP_ISO8601:log_timestamp} %{WORD:zone}: \[%{WORD:sender}\] {%{LOGLEVEL:loglevel}} Test Venue from Environment detected as : %{GREEDYDATA:venue}"]
      add_tag => [ "venue" ]
    }
}
Now, when i try to output this to Kibana, i have to output 2 events with different indices. 

For ex:
output {
    if "test_info" in [tags]:
        send_to_elasticsearch_withIndexA
    if "venue" in [tags]:
        send_to_elasticsearch_withIndexB
}
If test_info is in tags, venue is not present and vice-versa. How can they be combined? Is it possible?

**Comment by jsvd** [comment]
not sure I understand, you want to combine (merge) two events into one?
