### ISSUE TITLE
logstash all-plugin package

### ISSUE THREAD

**Issue by AlexisAnzieu** [elastic/logstash#6587]
Hi, 

I recently had an internet proxy issue at work, so i could not download email output plugin for my logstash stack. I think it would be great if you could build an "all-plugin package" when you launch a new version, just in case. 
I saw you already did it there : https://www.elastic.co/fr/downloads/past-releases/logstash-2-3-4-all-plugins 
Was there a reason to stop ? 

Thanks!

**Comment by talevy** [comment]
Hi @AlexisAnzieu,

Unfortunately this was removed in 5.0 [BREAKING-CHANGES](https://www.elastic.co/guide/en/logstash/5.0/breaking-changes.html#_logstash_with_all_plugins_download)
