### ISSUE TITLE
quote shell script variables handling paths

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#6596]
this is a followup issue from discussion in #6290 where @jordansissel mentioned we must quote variables to handle paths with spaces in [`bin/logstash.lib.sh`](https://github.com/elastic/logstash/blob/86fad2b9073e6da8dc43d9157035223369958fa5/bin/logstash.lib.sh#L4-L24), see https://github.com/elastic/logstash/pull/6290#discussion_r97848554

/cc @untergeek who originally submitted this.

Once this is fixed we should reintroduce the symlink check back into `bin/ruby`.

**Comment by wainersm** [comment]
hi guys, I submitted a PR to fix the issue in some of Linux scripts that I found mis-quoted variables.
