### ISSUE TITLE
Clarify pipeline stats for inputs

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6597]
5.1.1

https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#pipeline-stats

>The request also returns stats for each configured input, filter, or output stage, and info about whether config reload (if configured) failed or succeeded.

But in reality, input plugins will not have detail pipeline stats until 5.3 (earliest): https://github.com/elastic/logstash/issues/5769

So for the current 5.x versions, it will always return an empty array.

```
"plugins" : {
      "inputs" : [ ],
```

Let's update our documentation accordingly.

**Comment by dedemorton** [comment]
Closed #6684 (5.1) and #6658 (5.2 and later)
