### ISSUE TITLE
Allow to completely disable thread metrics collection (slow thread dump)

### ISSUE THREAD

**Issue by micoq** [elastic/logstash#6603]
On Logstash instances with a lot of Java threads (in my case, ~160 RabbitMQ inputs for ~700 threads), the JVM metric collector can decrease a lot the throughput while performing many thread dumps: All the Java threads are stopped during approximately 5sec (workers, inputs, http server...). It's not a memory or a garbage collector problem/tuning.

We can't completely disable the metric collector (it only disable the metric storage): [The poller is always started](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/agent.rb#L220)

If we comment out this line, we can increase the throughput of 20% ! (1000 ev/s -> 1200 ev/s with an heavy grok configuration). I think it would be a good idea to be able to choose the [metric collectors](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/instrument/periodic_pollers.rb#L15).

You can see the JVM pauses (or _safepoints_) on stdout by adding the following options in `jvm.options` before starting Logstash (you can see the thread dumps safepoints with any configuration):
```
-XX:+PrintSafepointStatistics
-XX:PrintSafepointStatisticsCount=1
```

Setup:
- Logstash version: 5.1.1
- Operating System: RHEL 6

**Comment by andrewvc** [comment]
@micoq I'm on the fence with this one. I think the main culprit here is really the excessive thread creation you documented so well in https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/93 . Let's tackle that and see if we still need the patch to core.

Logstash shouldn't be creating 700 threads in any circumstance. That said, we should be sure to benchmark this feature's performance, and if it has a significant impact either decrease its collection frequency or make it possible to disable it.

**Comment by andrewvc** [comment]
@micoq you are definitely right, however, that we shouldn't start the poller if metrics are disabled. WDYT @ph?

**Comment by ph** [comment]
As of today, we didn't expose an option to completly disable the metric collection we might revisit that.

@micoq you only disabled the OS Poller? Not anything else?

**Comment by jordansissel** [comment]
I think I am missing context, so I have to ask -- What indicates that the metrics poller is causing this issue?

**Comment by ph** [comment]
@micoq Do you disable all the periodic pollers?  in 5.1.1, the os poller is a noop. https://github.com/elastic/logstash/blob/v5.1.1/logstash-core/lib/logstash/instrument/periodic_poller/os.rb

**Comment by ph** [comment]
hypothesis: this line https://github.com/elastic/logstash/blob/5.1/logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb#L72 could effectively takes some time to complete when there is a lot of threads involved.

**Comment by ph** [comment]
Yup, @jordansissel I was wrong we do use the `ManagementFactory.getThreadMXBean()` to get information on every gathering of the jvm metrics.

```
metric.gauge([:jvm, :threads], :count, threads.count)
metric.gauge([:jvm, :threads], :peak_count, @peak_threads)
```

But to get that information we use the same code as the hot threads web call, so we generate a lot more information than we actually need in this specific context. The stack trace for 700 threads and all the other information. Java implementation : https://github.com/elastic/jrmonitor/blob/630e4c83c359fbe7e476902701ddda230493004b/jruby-ext/src/main/java/com/purbon/jrmonitor/monitors/HotThreadsMonitor.java#L118

**Comment by ph** [comment]
Also there is a bug here, the threadmxbean is able to report both the current threads and the peak count. `#getThreadCount(), #getPeakThreadCount()`

**Comment by micoq** [comment]
@ph The issue came from the `threadMXBean.getThreadInfo(threadId)` call in JRMonitor : exactly [here](https://github.com/elastic/jrmonitor/blob/master/jruby-ext/src/main/java/com/purbon/jrmonitor/monitors/HotThreadsMonitor.java#L145) and called from [jvm.rb](https://github.com/elastic/logstash/blob/5.1/logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb#L73) like you said.

Actually, the bottleneck didn't came from the call itself but from it's second parameter `threadInfoMaxDepth` to retrieve the stacktrace : in this case (`threadInfoMaxDepth > 0`), the JVM must stop all its threads to create a snapshot of the whole thread's stack (for each thread !).

Here is a little java program to demonstrate this behavior. It creates 1000 sleeping threads and perform a a thread dump for each thread:

```
import java.lang.management.ThreadInfo;
import java.lang.management.ThreadMXBean;
import java.lang.management.ManagementFactory;

public class Main {
    public static void main(String[] argv) throws InterruptedException {
        int tNum = 1000;
        int stackDepth = 0;
        Thread[] threads = new Thread[tNum];
        for (int i = 0; i < tNum; ++i) {
            threads[i] = new Thread(){
                public void run(){
                    try {
                        while(true) {
                            Thread.sleep(100);
                        }
                    }
                    catch (InterruptedException ex) {}
                }
            };
            threads[i].start();
        }

        ThreadMXBean threadMXBean = ManagementFactory.getThreadMXBean();
        while(true) {
            for (long threadId : threadMXBean.getAllThreadIds()) {
                ThreadInfo info = threadMXBean.getThreadInfo(threadId,stackDepth);
                info.getStackTrace();
            }
            Thread.sleep(1000);
        }
    }
}
```
If you execute it with 'java -XX:+PrintSafepointStatistics -XX:PrintSafepointStatisticsCount=1 Main`, you'll doesn't see anything but replace the `stackDepth` value by a positive value and you will see a lot of safepoints (one for each thread) :
```
0,379: ThreadDump                       [    1009          0              0    ]      [     0     0     0     0     0    ]  0   
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
0,379: ThreadDump                       [    1009          0              0    ]      [     0     0     0     0     0    ]  0   
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
0,379: ThreadDump                       [    1009          0              1    ]      [     0     0     0     0     0    ]  0   
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
0,380: ThreadDump                       [    1009          0              1    ]      [     0     0     0     0     0    ]  0
[...]
```

**Comment by ph** [comment]
@micoq Yeah, great thanks for the snippet, I will make a PR on core, In the calling context we don't need to get that much information from the mxbean, we just need to get the number of threads and the thread peak and theses information shouldn't require  to stop all the threads to snapshot that information.

**Comment by ph** [comment]
Just to keep a bit more track, from the official doc:

https://docs.oracle.com/javase/7/docs/api/java/lang/management/ThreadMXBean.html

`This method is designed for troubleshooting use, but not for synchronization control. It might be an expensive operation.`

So we will keep using in the **hot_threads** api call since we generate that report on request.
