### ISSUE TITLE
Remove "community maintained" banners in plugin docs

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6616]
As we now have plugin maintenance delineation in the [support matrix](https://www.elastic.co/support/matrix#show_logstash_plugins), we should further clean up the "community maintained" banners in the plugin docs to reduce confusion.

For example, [5.1 and 5.2](https://www.elastic.co/guide/en/logstash/5.2/plugins-filters-translate.html) are fine, but [5.0 and prior](https://www.elastic.co/guide/en/logstash/5.0/plugins-filters-translate.html) still have it.

**Comment by suyograo** [comment]
Done.
