### ISSUE TITLE
env http_proxy setting ignored on logstash-plugin

### ISSUE THREAD

**Issue by pjanzen** [elastic/logstash#6619]
Hi,

While installing logstash-filter-elasticsearch behind a proxy I found that when I set http_proxy= it is being ignored during install and returns an error "connection refused"

After looking around @google I found that when I extend JRUBY_OPTS with -J-Dhttp.proxyHost=proxy.server -J-Dhttp.proxyPort=1234 I can install plugins from behind a proxy server.

Topic on the forum is here:
https://discuss.elastic.co/t/plugin-not-found/73472/3

- logstash 5.2.0
- Ubuntu 16.04.1 LTS
- openjdk version "1.8.0_121"

If you require any more information please let me know.

Regard,
Paul Janzen.

**Comment by ph** [comment]
We need an integration test for that, I am pretty sure it was fixed in a jar-dependencies releases that  5.2.0 includes.

**Comment by primeroz** [comment]
I am having the same problem,  reference to #6044 where this is supposed to be fixed 

* Centos 6 
* logstash 5.2 
* openjdk version "1.8.0_121"

HTTPS_PROXY environement variable is completely ignored
JRUBY_OPTS="-J-Dhttp.proxyHost=proxy -J-Dhttp.proxyPort=3128" manage to get the plugin installation started but as soon as the dependecy part start i can see it tried to connect directly to the internet on https and fail

`tcp        0      0 10.0.1.97:57734             10.0.1.254:3128             ESTABLISHED 19410/java
tcp        0      0 10.0.1.97:57736             10.0.1.254:3128             ESTABLISHED 19410/java
tcp        0      1 10.0.1.97:45970             151.101.16.215:443          SYN_SENT    20207/java
`

**Comment by disaster37** [comment]
It's not working for me with a auth http proxy. I have added <username></username> and <password></password> on settings.xml and I have added -J-Dhttp.proxyUser= and -J-Dhttp.proxyPassword=

Any idea ?

**Comment by camelx1** [comment]
primeroz, thx, it really helped me

**Comment by shqiperih** [comment]
Just to confirm this workaround does not work on RHEL 6.7 -- set .m2 file set env variables  -- set JRUBY_OPTS still same errors as #6727. I'll have to go back to an earlier installation of logstash 2.3 with all plugins included in the tar file.  Any chance we could get a similar all plugins included newer version of logstash. Possibly in RPM form so we can start as a service

**Comment by msvechla** [comment]
The workaround above does not work for me either. The installation is starting with those parameters, but I get stuck with:
`[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.10/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not e (position: START_DOCUMENT seen e... @1:1)  @ line 1, column 1`
