### ISSUE TITLE
New Kubernetes filter plugin

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6633]
New Kubernetes filter plugin that parses Kubernetes metadata.

https://github.com/phutchins/logstash-filter-kubernetes_metadata

**Comment by suyograo** [comment]
@acchen97 @phutchins created https://github.com/logstash-plugins/logstash-filter-kubernetes_metadata. Can you do an initial PR please?

**Comment by phutchins** [comment]
@suyograo Created PR. Thanks!

**Comment by acchen97** [comment]
Closed with https://github.com/logstash-plugins/logstash-filter-kubernetes_metadata/pull/1. Thanks @phutchins!
