### ISSUE TITLE
Incorrect documentation for Logstash 5.2.0 prepare-offline-pack options

### ISSUE THREAD

**Issue by OmarDarwish** [elastic/logstash#6638]
The [documentation](https://www.elastic.co/guide/en/logstash/5.2/offline-plugins.html#building-offline-packs) for Logstash 5.2.0's `prepare-offline-pack` options is slightly incorrect:

>bin/logstash-plugin prepare-offline-pack [PLUGINS] --output OUTPUT

should be 
>bin/logstash-plugin prepare-offline-pack --output OUTPUT [PLUGINS] 

If `--output [DIR]` comes after the plugin list, `logstash-plugin` will complain that it `cannot find plugin --output`.

The `--help` command for `prepare-offline-pack` is correct however.

-Steps to Reproduce:
`$ bin/logstash-plugin prepare-offline-pack <plugin> --output /path/to/output.zip`

**Comment by ph** [comment]
Good catch!

**Comment by acchen97** [comment]
Thanks @OmarDarwish.

@dedemorton minor fix here, can you please help with this one?

**Comment by dedemorton** [comment]
Fixed in #6655

**Comment by acchen97** [comment]
Thanks @dedemorton
