### ISSUE TITLE
Offline Packaging/Installation Issue, Connection reset by peer 

### ISSUE THREAD

**Issue by nikkelj** [elastic/logstash#6647]
- Version: Logstash 5.2

**- Operating System:**
**Build machine:** 
CentOS Linux release 7.3.1611 (Core)
**Target machine:**
Red Hat Enterprise Linux Server release 6.8 (Santiago)

**- Config File (if you have sensitive info, please remove it):**
(not sure which is relevant to supply here, please advise)

**- Steps to Reproduce:**
**1) On build machine:**
a) sudo yum localinstall logstash-5.2.0.rpm
b) Install plugins
sudo /usr/share/logstash/bin/logstash-plugin install  logstash-filter-elapsed
sudo /usr/share/logstash/bin/logstash-plugin install  logstash-input-jdbc
sudo /usr/share/logstash/bin/logstash-plugin install multiline
c) Prepare offline pack
sudo /usr/share/logstash/bin/logstash-plugin prepare-offline-pack logstash-input-jdbc logstash-filter-elapsed logstash-codec-multiline
d) Copy output .zip to location accessible by taret

**2) On target machine:**
a) sudo yum localinstall logstash-5.2.0.rpm
b) [root@targetmachine Installers]# sudo -u logstash /usr/share/logstash/bin/logstash-plugin install --no-verify --local ./logstash-offline-plugins-5.2.0.zip 
ERROR: Something went wrong when installing ./logstash-offline-plugins-5.2.0.zip, message: Connection reset by peer

**Comment by ph** [comment]
@nikkelj You are using the old workflow for the installing, can you try the following command, make sure you cd into the $LOGSTASH_HOME before executing the command, there is a bug in 5.2.0 for that, that will be fixed in 5.2.1.
```
bin/logstash-plugin install file:///absolute_path/logstash-offline-plugins-5.2.0.zip
```

**Comment by ph** [comment]
I will close this issue, since I am pretty sure the install command did have the correct arguments with the `file` prefix.

Feel free to reopen if it is not the case.

**Comment by nikkelj** [comment]
Sorry, I was interacting w/ support and forgot about this.  Fine with close, it was my mistake.  I recommended some doc & usage clarifications that contributed to my confusion on this.
