### ISSUE TITLE
'less/greater than or equal to' forgotten?

### ISSUE THREAD

**Issue by wols** [elastic/logstash#6652]
- Version: logstash-5.1.1
- Operating System: Gentoo Linux
- Config File:
```
if [score] >= 10 { mutate { ... } }
```
- Sample Data:
```
{"@timestamp":"2017-02-07T16:38:21.767Z","score":20.0}
```
```
# logstash-plain.log
Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>#<NoMethodError: undefined method `>=' for nil:NilClass>, ...
```

```undefined method '>='``` but I see 'equality' in documentation here
https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#conditionals
and a example here
http://stackoverflow.com/questions/35489901/logstash-compare-a-field-to-a-number

**Comment by untergeek** [comment]
This is a usage question.  Please ask in https://discuss.elastic.co/c/logstash and save the Logstash GitHub issues page for bugs and code corrections.

**Comment by wols** [comment]
See https://discuss.elastic.co/t/less-greater-than-or-equal-to-forgotten/74298
