### ISSUE TITLE
Install error : IOError: Permission denied

### ISSUE THREAD

**Issue by nengc** [elastic/logstash#6662]
![image](https://cloud.githubusercontent.com/assets/19792047/22729326/3e247796-ee1d-11e6-8c7a-4e35902c63d5.png)

[root@iZ23xp8j6lbZ elk]# sudo rpm -ivh logstash-5.2.0.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:logstash-1:5.2.0-1               ################################# [100%]
Using provided startup.options file: /etc/logstash/startup.options
IOError: Permission denied
          close at org/jruby/RubyIO.java:2120
          write at org/jruby/RubyIO.java:4058
          write at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.27/lib/pleaserun/installer.rb:32
  install_files at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.27/lib/pleaserun/installer.rb:23
           call at org/jruby/RubyProc.java:281
          yield at org/jruby/RubyYielder.java:81
          files at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.27/lib/pleaserun/platform/systemd.rb:25
           call at org/jruby/RubyProc.java:281
           each at file:/usr/share/logstash/vendor/jruby/lib/jruby.jar!/jruby/kernel/jruby/generator.rb:246
  install_files at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.27/lib/pleaserun/installer.rb:18
      run_human at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.27/lib/pleaserun/cli.rb:174
        execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.27/lib/pleaserun/cli.rb:130
            run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
            run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
         (root) at /usr/share/logstash/lib/systeminstall/pleasewrap.rb:12
{:timestamp=>"2017-02-08T16:28:12.676000+0800", :message=>"No platform selected. Autodetecting...", :platform=>"systemd", :version=>"219", :level=>:warn}
{:timestamp=>"2017-02-08T16:28:12.694000+0800", :message=>"Writing file", :destination=>"/etc/default/logstash"}
{:timestamp=>"2017-02-08T16:28:12.707000+0800", :message=>"Writing file", :destination=>"/etc/systemd/system/logstash.service"}
Unable to install system startup script for Logstash.

**Comment by nengc** [comment]
And my OS is CentOS Linux release 7.0.1406

**Comment by jsvd** [comment]
It's been a while since this issue was created, which may have been related to an upgrade.
If you find yourself here and with a similar error please create a new issue.
