### ISSUE TITLE
Add `logstash-filter-age`

### ISSUE THREAD

**Issue by joshuaspence** [elastic/logstash#6674]
I have implemented a new `age` filter as discussed in logstash-plugins/logstash-filter-drop#11. It currently lives at https://github.com/joshuaspence/logstash-filter-age but I would to keen to move it to https://github.com/logstash-plugins.

**Comment by suyograo** [comment]
Can you do an initial commit here? https://github.com/logstash-plugins/logstash-filter-age

**Comment by joshuaspence** [comment]
See logstash-plugins/logstash-filter-age#1.

**Comment by suyograo** [comment]
@joshuaspence done. Added you as maintainer. Thanks for your contribution! 

Can you please add `dev_ops@elastic.co` to the RubyGems owners list? 

```
gem owner --add dev_ops@elastic.co [logstash-plugin-name]
```

**Comment by joshuaspence** [comment]
Done
