### ISSUE TITLE
Add link to X-Pack docs in monitoring section for additional configuration? 

### ISSUE THREAD

**Issue by joshuar** [elastic/logstash#6685]
It would be handy to at the very least, link to the X-Pack docs on configuring the latter for Logstash monitoring, as a nice example of utilising the monitoring APIs. I understand the need for separate documentation for the details, but a link would go a long way for revealing the way the stack talks together, if someone so chooses to use it that way.

**Comment by suyograo** [comment]
@joshuar I don't understand the connection. Can you tell me more why someone would want to know about x-pack from here? How would it help the API user?

**Comment by joshuar** [comment]
I guess for me, I'd expected how to configure Logstash to send this monitoring data to Kibana to be in the Logstash docs.  I looked in the Kibana docs as well TBH after I couldn't find it.  Looking in the X-Pack docs (to find the details) was the last thing I thought to do.  But that's the way my brain works:  "I want to configure Logstash to show up in the Monitoring tab in Kibana, so I should consult the Logstash docs to find out how to do this".  

I'm not suggesting moving or duplicating the details in the X-Pack docs.  But maybe just a link with some text like "Looking to configure Logstash with X-Pack monitoring, go here to find out how!" or something would be useful?

**Comment by joshuar** [comment]
Discussed off ticket.  The opposite is probably the better approach here, link to the monitoring section of the Logstash docs from the X-Pack docs.  Closing this issue.
