### ISSUE TITLE
New lookup enrichment docs page

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6687]
We're working on some new lookup plugins, and it'd be awesome for discoverability to have a doc page just focused on "lookup" type things that can be done in LS. Here's a short list of plugins we could highlight here:

- geoip
- translate
- jdbc_static
- jdbc_streaming
- elasticsearch
- useragent
- dns

@jordansissel feel free to add to this if I missed anything...

**Comment by dedemorton** [comment]
We've added this content here: https://www.elastic.co/guide/en/logstash/current/lookup-enrichment.html

**Comment by jordansissel** [comment]
Shiny!
