### ISSUE TITLE
Plugin doc gen script pulls wrong text for plugin docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6692]
The script for generating the plugin docs is currently pulling in a couple of code comments instead of the description that begins at https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb#L34.

Here's what it looks like in the doc (including a screen capture because Suyog might fix the doc before you see the problem).

![image](https://cloud.githubusercontent.com/assets/14206422/22848114/dc75e968-efa6-11e6-9a9e-d52037d19a8c.png)

The script should be resilient enough to extract the text even if there's a minor formatting snafu (like an extra line).

**Comment by dedemorton** [comment]
@ph I'm seeing a similar problem here where the script takes text that's meant to be a comment: https://www.elastic.co/guide/en/logstash/5.2/plugins-inputs-http.html

![image](https://cloud.githubusercontent.com/assets/14206422/22849098/c941297c-efae-11e6-8bb9-9b530320aff4.png)

**Comment by dedemorton** [comment]
Here's another one. But in this case, there is no description of what the plugin does. "handles disconnects" comes from a code comment, tho. :-( 

![image](https://cloud.githubusercontent.com/assets/14206422/22849606/9053e08c-efb3-11e6-9953-2947fece9cb5.png)

**Comment by dedemorton** [comment]
Here's another one. 

![image](https://cloud.githubusercontent.com/assets/14206422/22849682/47173652-efb4-11e6-814d-da895a3b5a95.png)

**Comment by dedemorton** [comment]
From https://www.elastic.co/guide/en/logstash/5.2/plugins-outputs-boundary.html, not sure if this is a problem with the doc gen or the code itself:

![image](https://cloud.githubusercontent.com/assets/14206422/22849890/9647845a-efb6-11e6-8799-6920a1207282.png)

**Comment by dedemorton** [comment]
This one is pulling the license agreement and squishing it together with the description:

![image](https://cloud.githubusercontent.com/assets/14206422/22850253/37f9f7a2-efbb-11e6-8b73-220881b4e0e6.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850374/272082dc-efbd-11e6-9459-45156b65c425.png)

**Comment by dedemorton** [comment]
I'm guessing this is not the droid we're looking for:

![image](https://cloud.githubusercontent.com/assets/14206422/22850415/f0855df0-efbd-11e6-86f8-f53605b29b0e.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850456/715f636c-efbe-11e6-9514-b575b0a86884.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850515/42ea9596-efbf-11e6-8e46-bdaa9764dbba.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850574/8f15587e-efc0-11e6-9c27-defc2c5c9455.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850729/c40b21b4-efc3-11e6-9f7d-20be7e7ca573.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850764/7a7ebdac-efc4-11e6-912d-fb0c92b711c0.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850885/416c5b70-efc7-11e6-8dea-8f20f594d871.png)

**Comment by dedemorton** [comment]
![image](https://cloud.githubusercontent.com/assets/14206422/22850946/e6845f9e-efc8-11e6-8553-15f28519a83e.png)

**Comment by dedemorton** [comment]
@ph Including screen captures here for all the issues I found even tho they are likely related to the same bug. I just want to be able to verify the fix when you're done.

**Comment by dedemorton** [comment]
alvin found this one, too: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-http.html

**Comment by ph** [comment]
thanks @dedemorton checking it right now since we will push a few new artifacts.

**Comment by ph** [comment]
Got it reproduced, https://github.com/logstash-plugins/logstash-codec-msgpack/blob/master/lib/logstash/codecs/msgpack.rb#L20, It seems that on some file the parser doesn't known it should have stop reading the headers.

**Comment by ph** [comment]
Fixed: 

- logstash-input-http
- logstash-filter-geoip
- logstash-filter-msgpack
- logstash-output-http
- logstash-codec-collectd
- logstash-filter-fingerprint
- logstash-filter-elapsed -> NEED PR https://github.com/logstash-plugins/logstash-filter-elapsed/blob/master/lib/logstash/filters/elapsed.rb#L1
- logstash-output-sqs -> NEED PR https://github.com/logstash-plugins/logstash-output-sqs/blob/master/lib/logstash/outputs/sqs.rb

**Comment by acchen97** [comment]
![elastic-heart](https://cloud.githubusercontent.com/assets/13039544/22955031/da57bbcc-f2ce-11e6-9b63-4ad0e59b88c6.png)

**Comment by ph** [comment]
@dedemorton For the `license` in the file, I think the license content should go in the `LICENSE` file in the plugin repo? I think this is where it should belongs.

**Comment by ph** [comment]
@dedemorton I've merged the PRs for the plugins and published the plugins.

**Comment by acchen97** [comment]
@ph will this fix only be executed on new doc versions? Or can we also fix older versions retroactively?

**Comment by ph** [comment]
@acchen97 it depends, by looking at the list at https://github.com/elastic/logstash/issues/6692#issuecomment-279849370,  if they make no mention of a PR we could fix older versions with the same script.

**Comment by dedemorton** [comment]
@ph I think we should fix the older versions. For the topics that can't be fixed just by running the docgen tool again, I could tweak the asciidoc, but I only want to do that if we're sure we won't have to run the tool against those versions again.

**Comment by ph** [comment]
@dedemorton Exactly, I would have preferred to not have to do it manually. :(

**Comment by ph** [comment]
@dedemorton dont worry about the google plugins I have fixed it in the parser.

**Comment by ph** [comment]
@dedemorton I've merged the changes to the logstash-docgen tool so on the next generation a lot of theses issues should be fixed. 

I will assign this issue to you for the manual changes.

**Comment by dedemorton** [comment]
Closing because the manual changes have been made, where feasible, to the source files.
