### ISSUE TITLE
Error installing plugins in logstash

### ISSUE THREAD

**Issue by shqiperih** [elastic/logstash#6727]
Hello all,

I'm having a problem install the syslog output plugin to logstash 5.2.

After installing logstash using yum from a local rpm. I run this command: bin/logstash-plugin install logstash-output-syslog

However i get this output:
Validating logstash-output-syslog
Installing logstash-output-syslog
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.2.0), and Bundler cannot continue.
Make sure that gem install logstash-core-event-java -v '5.2.0' succeeds before bundling.
WARNING: SSLSocket#session= is not supported
Error Bundler::InstallError, retrying 2/10
An error occurred while installing logstash-core-event-java (5.2.0), and Bundler cannot continue.
Make sure that gem install logstash-core-event-java -v '5.2.0' succeeds before bundling.
WARNING: SSLSocket#session= is not supported
...

Until 10 tries then it dies. At this point logstash won't even start saying it cant find the syslog file.

This issue has appeared before in previous versions looking at other issue however it was said it is fixed for 5.2.

Syslog output cannot be installed manually as rubygems does not provide it as standalone.

- Version: 5.2
- Operating System: RHEL 6.7

**Comment by shqiperih** [comment]
Also to clarify the proxy variables are set for so not related to proxy issues.

**Comment by shqiperih** [comment]
some more error info from running the command with DEBUG=1:

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.9/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.9/lib/jars/gemspec_pom.rb) has 1 error
[ERROR]     Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.9/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

Errno::ENOENT: No such file or directory - /usr/share/logstash/logstash-core-event-java/deps.lst

**Comment by ph** [comment]
Still an issue there is workaround at https://github.com/elastic/logstash/issues/6619
