### ISSUE TITLE
2.4 breaking changes, link to openssl page broken

### ISSUE THREAD

**Issue by jakommo** [elastic/logstash#6734]
The 2.4 [breaking-changes / beats input](https://www.elastic.co/guide/en/logstash/2.4/breaking-changes.html#_beats_input_config_change) use [this link](https://www.openssl.org/docs/manmaster/apps/pkcs8.html) to openssl (for examples on how to convert a key to PKCS#8) but the link leads to a "page not found".
I assume it coming from the `manmaster` part in the url and that this https://www.openssl.org/docs/man1.0.2/apps/pkcs8.html is the correct link.

**Comment by dedemorton** [comment]
Closed by issue #7202
