### ISSUE TITLE
input file start_position => "beginning" doesn't work even after deleting .sincedb files

### ISSUE THREAD

**Issue by pratnimk** [elastic/logstash#6735]
Hello World

Version: ElasticSearch-5.2.1/Logstash-5.2.1/Kibana-5.2.1
OS: Windows 2008

I've just started working on the ELK Stack & am facing some problems loading data
I've got the following .json code

`input {
  file {
    path => "D:\server.log"
	start_position => beginning
  }
}
filter {  
        grok {
                match => ["message","\[%{TIMESTAMP_ISO8601:timestamp}\] %{GREEDYDATA:log_message}"]
            }
        }
output {
  elasticsearch {
    hosts => "localhost:9200"
  }
}`

I've deleted the .sincedb files

And yet when I extract log info in Kibana, I can see data starting only since I first parsed
I've got data worth 2-3 months in my log file

Please advise

Thanks
P

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
