### ISSUE TITLE
 When I active persisten connection in logstash it through out Error Logstash

### ISSUE THREAD

**Issue by DBARUNNER** [elastic/logstash#6750]
I am using logstash 5.2 tar.gz package  and have the following configuration in logstash config file

pipeline.batch.size: 2
 pipeline.batch.delay: 20 
queue.type: persisted
 queue.max_events: 0
queue.max_bytes: 2gb
queue.checkpoint.acks: 2024
queue.checkpoint.writes: 2024

when I runt the logstash the following error throught out
> Exception in thread "[main]>worker3" org.logstash.ackedqueue.QueueRuntimeException: deserialize invocation error

but when I disable the persisten que it work fine

**Comment by suyograo** [comment]
@DBARUNNER can you provide more info? What does your LS config look like? What OS is this? How do you start Logstash?

Are you running multiple LS instances in the same box?

/cc @colinsurprenant

**Comment by DBARUNNER** [comment]
here is the LS config file 
pipeline.batch.size: 2
pipeline.batch.delay: 20
queue.type: persisted
queue.max_events: 0
queue.max_bytes: 2gb
queue.checkpoint.acks: 2024
queue.checkpoint.writes: 2024

OS that I am using is ubuntu 12.4
and I am just running one LS instance in the same box

**Comment by original-brownbear** [comment]
Closing this, there were a bunch of serialization/deserialization bugs ( #8131 , #8128  etc. ) that are now fixed and as far as I can see #8239 will replace the last remaining serialization inconsistency.
