### ISSUE TITLE
New input plugin: logstash-input-okta_enterprise

### ISSUE THREAD

**Issue by p-b--** [elastic/logstash#6752]
I've worked on a plugin to pull logs from the [Okta event log](http://developer.okta.com/docs/api/resources/events.html) for use in an organization. This plugin is based on the `http_poller` plugin, however, it is modified due to the fact that the event stream does not send discrete events per poll, rather the user has to process them as they get them.

Currently the plugin favors Linux with a few features, namely retaining state between plugin launches.

https://github.com/SecurityRiskAdvisors/logstash-input-okta_enterprise

I have written some tests, however any advice on those would be very helpful, `rspec` is not my forte.

The plugin currently supports 2.4.x, as that is what I started developing on and wanted to finish the process once before updating the code to go to 5.x. As this clears review, I can start to update the code accordingly.

**Comment by suyograo** [comment]
@p-b-- Thanks for your contribution! We'll take a look shortly -- we are currently busy with our user conference for the next couple of weeks, so please be patient.

**Comment by p-b--** [comment]
Great! Thanks -- there's no rush.

**Comment by p-b--** [comment]
Closing due to deprecation.
