### ISSUE TITLE
x-pack install error through http_proxy

### ISSUE THREAD

**Issue by imweijh** [elastic/logstash#6753]
- Version:
logstash 5.2.1

- Operating System:
CentOS 6.x

- Steps to Reproduce:
```
env|grep -i proxy
http_proxy=http://127.0.0.1:3128/ 
HTTPS_PROXY=http://127.0.0.1:3128/
https_proxy=http://127.0.0.1:3128/
HTTP_PROXY=http://127.0.0.1:3128/
```

`DEBUG=1 bin/logstash-plugin install x-pack`

> DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install x-pack
Looking if package named: x-pack exists at https://artifacts.elastic.co/downloads/logstash-plugins/x-pack/x-pack-5.2.1.zip
SocketError, skipping Elastic pack, exception: initialize: name or service not known
Validating x-pack
ERROR: Installation aborted, verification failed for x-pack

**Comment by ph** [comment]
@imweijh 

`initialize: name or service not known`

This error usually mean a DNS resolution error, can you add the result of `dig artifacts.elastic.co` to this issue?

**Comment by imweijh** [comment]
@ph env http_proxy aware apps like wget yum works fine here and do not need local set /etc/resolve.conf

> [root@elk20160 ~]# wget https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-5.2.1.zip
--2017-02-24 23:00:11--  https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-5.2.1.zip                   
Connecting to 127.0.0.1:3128... connected.                                                                   
Proxy request sent, awaiting response... 200 OK                                                                 
Length: 124956667 (119M) [application/zip]                                                                      
Saving to: ‘x-pack-5.2.1.zip’

100%[=========================================================================>] 124,956,667  503KB/s   in 6m 6s

2017-02-24 23:06:18 (334 KB/s) - ‘x-pack-5.2.1.zip’ saved [124956667/124956667]

**Comment by ph** [comment]
I will take a look, ruby net http should honor any configured proxy by
default

**Comment by imweijh** [comment]
seem add  `export JRUBY_OPTS="-J-Dhttp.proxyHost=127.0.0.1 -J-Dhttp.proxyPort=3128"` works

**Comment by imweijh** [comment]
But other problem here
`
DEBUG=1 bin/logstash-plugin install logstash-filter-dissect
DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install logstash-filter-dissect
Looking if package named: logstash-filter-dissect exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-dissect/logstash-filter-dissect-5.2.2.zip
Package not found at: https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-dissect/logstash-filter-dissect-5.2.2.zip
Validating logstash-filter-dissect
ERROR: Installation aborted, verification failed for logstash-filter-dissect
`

`
wget https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-dissect/logstash-filter-dissect-5.2.2.zip
--2017-03-03 22:28:06--  https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-dissect/logstash-filter-dissect-5.2.2.zip
Connecting to 127.0.0.1:3128... connected.
Proxy request sent, awaiting response... 404 Not Found
2017-03-03 22:28:08 ERROR 404: Not Found.
`

**Comment by ph** [comment]
@imweijh is that the full log  in https://github.com/elastic/logstash/issues/6753#issuecomment-283966970 ? The current behavior of the **install** is the following:

1. check on our server if it's an elastic pack
2. fallback to rubygems.

Since 1. returned a 404 it should have switched to step 2.

**Comment by imweijh** [comment]
![logstash-plugin-install](https://cloud.githubusercontent.com/assets/23710675/23575867/095f9700-00d0-11e7-88ab-af5343d5fbb2.png)

@ph yes, it's full log.
I can install x-pack now but fail on install plugin like logstash-filter-dissect ...

**Comment by imweijh** [comment]
$LS_HOME/bin/logstash-plugin prepare-offline-pack solve my problem perfect.
