### ISSUE TITLE
Question: metricbeat & graphite

### ISSUE THREAD

**Issue by Exocomp** [elastic/logstash#6755]
I need some guidance on how to get metricbeat data into graphite.  Could someone give a highlevel or if there is a tutorial point me to it. 

If metricbeat doesn't support Graphite then would it be possible to point metricbeat to Logstash and then in Logstash filter the data and send it to Graphite ?  If that is possible then I just need a confirmation from someone and if possible a general guideline of how to do it.

Thanks,
E

**Comment by untergeek** [comment]
Please ask this question in our [community discussion forum](https://discuss.elastic.co/c/logstash), which is set up for just this sort of usage question.  GitHub issues are reserved for bugs and code submissions.
