### ISSUE TITLE
JDBC output plugin

### ISSUE THREAD

**Issue by camlizo** [elastic/logstash#6757]
I would like to use logstash to parse some log files and insert the result into an oracle database.
But when I checked the output plugins, there is no plugin for that purpose.

Is there a way to use logstash for that ?

**Comment by tac0x2a** [comment]
Hi @camlizo , this is logstash-output-jdbc plugin. 
https://github.com/theangryangel/logstash-output-jdbc

This plugin is not official plugin. However, it works on my product well.

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
