### ISSUE TITLE
Kafka input/output installation instructions for 0.8 vs 0.9 (copied from logstash-docs)

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6770]
This issue was created as https://github.com/elastic/logstash-docs/issues/256, so I'm adding it here for consideration:

It might be useful to put in the input installation instructions for Kafka input and output based on which broker the user is using.

"bin/logstash-plugin install --version 3.0.3 logstash-input-kafka" vs "bin/logstash-plugin install --version 2.0.9" logstash-input-kafka

**Comment by jordansissel** [comment]
We removed the kafka compatibility matrix (to simplify user experience and improve accuracy) -- https://github.com/logstash-plugins/logstash-output-kafka/issues/156

This issue is can be closed :)
