### ISSUE TITLE
add documentation for new queue drain option

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#6778]
queue drain support has been added in #6433 and documentation need to be updated for that new option.

**Comment by dedemorton** [comment]
@colinsurprenant It looks like this option should have been documented in 5.4, but wasn't. I want to make sure it gets added for 5.5. I'm planning to add the an entry for `queue.drain` to the table that's here: https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

I'm not sure what I should say except:  When enabled, Logstash waits until the persistent queue is drained before shutting down.  Default: false

Should I mention that setting this option to `true` might result in a slower shut down? Also, is there anything more that I can say to users to help them understand when they might want to enable this option? It sounds like "it depends" might be the answer. :-/

BTW, I expected to find a description of this setting commented out under  Queuing Settings in the logstash.yml file, but it's not mentioned. I guess I also need you to confirm that we do want to document this setting in the end user docs.

I'm also wondering if we want to say anything here: https://www.elastic.co/guide/en/logstash/current/persistent-queues.html

**Comment by colinsurprenant** [comment]
@dedemorton 

> I'm not sure what I should say except: When enabled, Logstash waits until the persistent queue is drained before shutting down. Default: false

Yes, that sounds right.

> Should I mention that setting this option to true might result in a slower shut down?

Well ... maybe. We could stress the point that depending on the amount of events accumulated it could take a while to drain the queue. Some like the time to drain the queue will be proportional to the amount of queued events? - also we could add that this setting will probably make more sense when using a small queue where even if full, draining it will take a reasonable/manageable amount of time?

> BTW, I expected to find a description of this setting commented out under Queuing Settings in the logstash.yml file, but it's not mentioned.

Yes, we also need to add it in the `logstash.yml`.

> I'm also wondering if we want to say anything here: https://www.elastic.co/guide/en/logstash/current/persistent-queues.html

Yes, I think it would be a good idea to mention this option in there also.

**Comment by dedemorton** [comment]
Fixed in #7583
