### ISSUE TITLE
Feature request: Environment variable expansion in logstash.yml

### ISSUE THREAD

**Issue by jarpy** [elastic/logstash#6785]
In some situations, it would be handy to expand environment variables in `logstash.yml`, similar to [how it's done for pipeline configuration](https://www.elastic.co/guide/en/logstash/current/environment-variables.html).

For my specific purpose, this would enable setting various options with environment variables passed by Docker to Logstash running in a container, as suggested/discussed in [this logstash-docker issue](https://github.com/elastic/logstash-docker/issues/15).

What say you, Team Logstash?

**Comment by suyograo** [comment]
Agreed.

**Comment by jarpy** [comment]
Awesome.

While I'm on a roll, I'd also like to suggest that `.` characters be allowed in environment variable names. They are [not currently allowed](https://github.com/elastic/logstash/blob/efc0a0c/logstash-core/lib/logstash/config/mixin.rb#L42) in pipeline config, but allowing them for settings would enable one-to-one mapping for things like `pipeline.workers`.

eg. `docker run -e pipeline.workers=8 docker.elastic.co/logstash/logstash:5.2.2`

**Comment by original-brownbear** [comment]
Here we go #7072  :)

**Comment by original-brownbear** [comment]
@suyograo @jarpy merged to `5.x` and `master` we can close here I guess? :)

**Comment by jarpy** [comment]
You're my hero!

**Comment by suyograo** [comment]
@original-brownbear now that we've merged the code, can we add docs that we support environment variables in settings file? We can perhaps give some examples

Doc source are at: https://github.com/elastic/logstash/blob/master/docs/static/settings-file.asciidoc

We use asciidoc. A guide is available [here](https://github.com/elastic/docs/blob/master/README.asciidoc#asciidoc-guide)

The user facing docs will then end up in https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html (there's an automated process for that)

**Comment by original-brownbear** [comment]
@suyograo sure will add an issue for that and handle it this morning :)
