### ISSUE TITLE
Is there any logstash-input-plugin to stream wikipedia in elasticsearch ? 

### ISSUE THREAD

**Issue by DBARUNNER** [elastic/logstash#6786]
there is stream2es to stream wikipedia in elasticsearch but it dont work with elasticsearch 5.2.1 
as I know there is no plugin in logstash as well is the community want to develop such a plugin ?

**Comment by suyograo** [comment]
I don't know of any such plugins. Can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? Github is mainly used for issues/enhancements. Thanks!
