### ISSUE TITLE
Unable to install x-pack into logstash as a plugin on windows

### ISSUE THREAD

**Issue by kenede** [elastic/logstash#6805]
i am starting to use ELK(Elasticsearch,logstash and kibana ) i have finished installing x-pack on both elasticsearch and kibana but i can't install the x-pack plugin on to logstash i got the following error 

Unable to find Jruby
If you are a user it is abug
If you are a developer please rub rake boostrap ,running 'rake' requires the ruby program be available. 

Please help me 
Am using windows

**Comment by suyograo** [comment]
@kenede can you use 5.2.1? we fixed a windows bug. Also, please make sure you have Java 8 installed.

For follow up debugging on this issue, can you head to our forums? (https://discuss.elastic.co/c/logstash)? Github is mainly used for issues/enhancements. Thanks!
