### ISSUE TITLE
Logstash File input plugin question- older files

### ISSUE THREAD

**Issue by iyerabhi07** [elastic/logstash#6813]
Hi, 
I had a query regarding logstash file input plugin. Scenario:
I had static files (over 100) i needed to export to ELK. I did it. But the logstash service was stopped. Now I have new files in the folders along with the old files already read into Elasticsearch. So if I start the logstash service now, would the old files be read again? Or is it going to read only the new files.

Thanks in advance.

**Comment by untergeek** [comment]
This is a usage question. Please ask usage questions at https://discuss.elastic.co/c/logstash
