### ISSUE TITLE
Feature request:  If elasticsearch output fails then catch the failure and allow a custom way to handle it

### ISSUE THREAD

**Issue by Exocomp** [elastic/logstash#6814]
Per https://discuss.elastic.co/t/logstash-drop-duplicate-elasticsearch/77807/3

Please read the discussion in the above link it will explain why this feature is necessary.

**Comment by Exocomp** [comment]
Updated title.

**Comment by untergeek** [comment]
Please move this to https://github.com/logstash-plugins/logstash-output-elasticsearch

**Comment by Exocomp** [comment]
@untergeek this feature is to be able to detect the failure at the output stage in logstash, can you please explain if you understood and why you feel it need to be moved.

**Comment by Exocomp** [comment]
@untergeek Now that I think about it, see discussion in the link, I will move it.

Thanks,
E

**Comment by Exocomp** [comment]
Closing, I don't see a way to move it, so created it here.  https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/574
