### ISSUE TITLE
./system-install error

### ISSUE THREAD

**Issue by Somebi** [elastic/logstash#6816]
Ubuntu 16.04 inside Docker
logstash 5.2.2
init daemon: supervisord

Had problems with installation. Installing via apt from your repos haven't created any init script noted from your official documentation.
Had to read manual launch documentation. 

Found this script in bin folder. It seems related to service installation, but it throws an error. 
Probably because haven't found supervisor service, because it's not supported as i suppose. 
Can be wrong ofc.

```
root@beck:/usr/share/logstash/bin# ./system-install 
NoMethodError: undefined method `tr' for nil:NilClass
   detect_upstart at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.28/lib/pleaserun/detector.rb:45
  detect_platform at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.28/lib/pleaserun/detector.rb:24
           detect at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.28/lib/pleaserun/detector.rb:18
   setup_defaults at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.28/lib/pleaserun/cli.rb:142
          execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/pleaserun-0.0.28/lib/pleaserun/cli.rb:108
              run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
              run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
           (root) at /usr/share/logstash/lib/systeminstall/pleasewrap.rb:12
Unable to install system startup script for Logstash.
root@beck:/usr/share/logstash/bin# 
```

**Comment by untergeek** [comment]
Containers are frequently going to be different. It appears yours does not contain the `tr` binary, which is causing the script to fail.

**Comment by untergeek** [comment]
You will either have to build your own service scripts, or launch logstash manually. With containers, this is frequently the chosen path anyway.

**Comment by Somebi** [comment]
what is that tr?

**Comment by untergeek** [comment]
Have you tried running it as `bin/system-install` from the `/usr/share/logstash` directory?  I don't think it will make a difference, but path detection can be weird.

At any rate, I was barely awake and responding from my phone.  That `tr` is actually [a ruby call](https://github.com/jordansissel/pleaserun/blob/master/lib/pleaserun/detector.rb#L45).  It's saying that the `out` variable is `nil`, and you can't run a `tr` against a `nil` value.

The `out` variable in the specified error suggests that it tried to run `initctl --version` and it failed.  It is supposed to `return false` if it fails, but somehow it's not trapping properly.

You may be able to force an init script, as systemd may be weird inside a container.

In any case, you should be able to manually run:
* for SysV Init: `/usr/share/logstash/bin/system-install /etc/logstash/startup.options sysv`
* for systemd: `/usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd`

And this will _force_ system-install to use the specified version.

**Comment by Somebi** [comment]
Yeah, container is completely clean. systemd isn't installed at all.

**Comment by untergeek** [comment]
Does the manual SysV install work for you?

**Comment by Somebi** [comment]
Not sure, i'm using supervisord. Well at any rate, i have already installed it long ago. Currently working with kibana and various beat servers (metricbeat/filebeat etc).

**Comment by Somebi** [comment]
solidarity feeling :D

**Comment by untergeek** [comment]
Cool.  Will chalk this up to a container thing that we already have a workaround for.

**Comment by rhaist** [comment]
This still is a problem for anyone trying to install logstash from the official repo into a docker container. The .deb package installation should not be failing because there is no systemd or sysv. I consider this a bug.

**Comment by marcintustin** [comment]
Wait, so the workaround is to complete the installation manually? I agree with @rhaist that this is a bug.

**Comment by bwhaley** [comment]
Just encountered this when install logstash in an Ubuntu image. The installer fails because the command `initctl --version` doesn't return a value. The contents of that script are simply:

```
#!/bin/sh
exit 0
```

So as an ugly hack, to work around this issue, you can update the script to just print something, e.g.

```
#!/bin/sh
echo 0.1
```

And the installer will finish by harmlessly setting up unused init scripts.
