### ISSUE TITLE
Document popular processing capabilities of Logstash

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6820]
Logstash users often have a hard time discovering what are the processing capabilities, especially when getting started. This is a bug and we should improve this experience. Let's add a new top level doc section called "Data Transformation" with 4 sub-sections "Core Operations," "Data Deserialization," "Field Extraction," and "Lookup Enrichment." Plugins to highlight in each section are below.

For each plugin / use case, we should have:
- Short summary (maybe one or two sentences) describing what the plugin does
- At least one code snippet example of how it can be used. This could warrant >1 example for multi use case plugins like mutate and grok.
- Link to the respective plugin doc page for more details

## Data Transformation (top level section)
- Core Operations
  - Mutate
  - Drop
  - Date
  - Fingerprint/Anonymize
  - Aggregate
  - Ruby
- Data Deserialization (aside from native inputs)
  - JSON codec
  - XML
  - CSV
  - Avro codec
  - Protobuf codec
  - Fluent || Msgpack codecs
- Field Extraction (Data Wrangling)
  - Grok
  - Dissect
  - KV
- Lookup Enrichment
  - GeoIP
  - UserAgent
  - DNS
  - Translate
  - Elasticsearch
  - JDBC (2 plugins: static & streaming)

**Comment by acchen97** [comment]
@dedemorton let's work on this one together. :)

**Comment by dedemorton** [comment]
Fixed in #6988
