### ISSUE TITLE
Provide curl examples for Logstash monitoring and logging api calls in doc

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6823]
There are users out there who haven't interacted with Logstash's new APIs (logging and monitoring) before.  It will be helpful to provide curl examples similar to Elasticsearch documentation.  

- Currently, our documentation provides examples using Sense/Console notation, eg. `GET /`, `GET /_node/stats/jvm`.  Providing curl examples will be more useful - esp. since the Kibana Console no longer allows configuring arbitrary URLs to send http requests to.
- For users who land [here](https://www.elastic.co/guide/en/logstash/current/logging.html#_logging_apis) directly, there is no information on where to send these logging API calls to (i.e. to the http_port that defaults to 9600).  For completeness, it will be helpful to have a similar note as the `Note` on the [monitoring api](https://www.elastic.co/guide/en/logstash/current/monitoring.html) page.

**Comment by dedemorton** [comment]
Closed by  #7208
