### ISSUE TITLE
cgroups not existing on all linux versions

### ISSUE THREAD

**Issue by ruflin** [elastic/logstash#6824]
* version: master

Running Logstash in a Docker container I get the following log message very few seconds:

```
logstash_1       | [2017-03-21T15:14:58,454][DEBUG][logstash.instrument.periodicpoller.cgroup] Error, cannot retrieve cgroups information {:exception=>"Errno::ENOENT", :message=>"No such file or directory - /sys/fs/cgroup/cpuacct/docker/17b6470608493e662e1d4e0dabcf937b0de9a9ce06197b4fe7afa6acf8f19837/cpuacct.usage"}
```

The problem is that cgroups are not available on all linux system or can also be disabled. We had a similar issue in beats: https://github.com/elastic/beats/pull/3692 I'm aware that the above is only a debug log message but I would suggest that the check if cgroup is available should happen only once on startup.

**Comment by ph** [comment]
Seems linked to #6797, I will check for that.

**Comment by ruflin** [comment]
These are 2 different things: One is `cgroups` is mounted in a different place which is #6797 . The other part is `cgroups` is disabled or does not exist on the system. Could well be that my error is because of #6797 but the second issue still exists I assume.

**Comment by ph** [comment]
@ruflin Right, I am +1 to do the check only once I will check to change that. But also this error is only logged at **debug** mode so the noise should be low in normal situation.

**Comment by jurajseffer** [comment]
This also happens on EC2 running Debian Jessie
`
[2017-05-12T12:49:06,341][DEBUG][logstash.instrument.periodicpoller.cgroup] Error, cannot retrieve cgroups information {:exception=>"Errno::ENOENT", :message=>"No such file or directory - /sys/fs/cgroup/cpuacct/cpu.cfs_period_us"}
`

**Comment by zh-h** [comment]
This also happens on Fedora WorkStation
```bash
logstash_1       | 05:41:05.517 [pool-2-thread-3] DEBUG logstash.instrument.periodicpoller.cgroup - Error, cannot retrieve cgroups information {:exce
ption=>"Errno::ENOENT", :message=>"No such file or directory - /sys/fs/cgroup/cpuacct/docker/7b1f437d0b80b70b4463a1c7c18f4b71a56eed21f2b2c66a78127e20
8fc17c5d/cpuacct.usage"}
```

**Comment by meyervp** [comment]
And my on debian jessie and docker container /sys mounted
`DEBUG logstash.instrument.periodicpoller.cgroup - Error, cannot retrieve cgroups information {:exception=>"Errno::ENOENT", :message=>"No such file or directory - /sys/fs/cgroup/cpuacct/docker/fe2c373bfa536a36fdc3f60d1885c76d58a1c7a5bd99dc54cd3df000190d1a29/cpu.cfs_period_us"`

**Comment by gnh1201** [comment]
I have same problem!

**Comment by jayunit100** [comment]
So, wait , is this simply b/c logstash is trying to 'play nice' and not use more CPU then its allocated in the CGroup ?  If so:

- Users should be able to send niceness information as a command line arg in case their OS isnt exposing properly to the containers or 
- Worst case scenario we just swallow the exception and keep moving forward.

Either way we should 

- Make sure show this  with a WARNING log.  This is a pretty significant issue it shouldnt be hidden.

**Comment by jayunit100** [comment]
cc @aclairekeum @komalsodha

**Comment by gnh1201** [comment]
2 options exists for solve this problem:
- kernel recomplile and install
- downgrade logstash to 2.4.1

If you recompile kernel with 'CONFIG_CFS_BANDWIDTH=y' option, you can enable cgroup cpuacct.
Or you can try use Logstash 2.4.1 because it not used cgroup.

**Comment by tomryanx** [comment]
Same problem here on Jessie

**Comment by markomafs** [comment]
https://unix.stackexchange.com/a/352996/54917 
This resolve my issue, on debian.

**Comment by JeMunos** [comment]
I'm having this issue on Ubuntu 18.04 and logstash 6.3.

[2018-06-18T21:43:54,865][DEBUG][logstash.instrument.periodicpoller.cgroup] Error, cannot retrieve cgroups information {:exception=>"NoMethodError", :message=>"undefined method `[]' for nil:$
[2018-06-18T21:43:55,037][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2018-06-18T21:43:55,039][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}

**Comment by aollag09** [comment]
Same error as JeMunos with Ubuntu 18.04 and logstash-6.3.0 :( :( :( !!

`
[2018-06-19T12:46:46,568][DEBUG][logstash.instrument.periodicpoller.cgroup] Error, cannot retrieve cgroups information {:exception=>"NoMethodError", :message=>"undefined method []' for nil:NilClass"}
[2018-06-19T12:46:46,664][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2018-06-19T12:46:46,665][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
`

**Comment by comnam90** [comment]
I am also on Ubuntu 18.04 LTS and Logstash 6.3.0 and seeing the same error as @aollag09  and @JeMunos

**Comment by hthemriwkf** [comment]
I am also on Ubuntu 18.04 LTS and Logstash 6.3.0 and seeing the same error as @aollag09 and @JeMunos @comnam90

**Comment by myraft** [comment]
Same here , Ubuntu 18.04 / Logstash 6.3.0. Any workarounds? Tried unzipping fresh logstash folder, did not work.

**Comment by terebentina** [comment]
I am confused: shouldn't the official logstash docker images NOT have this problem?
I am using `FROM docker.elastic.co/logstash/logstash:6.3.2` in my `Dockerfile` and yet I see this problem too.
Is there an official image that behaves in this respect, any idea?

**Comment by sp1thas** [comment]
Same error as @aollag09.
Ubuntu  18.04.1 LTS 
Logstash 6.4.0

**Comment by guyboertje** [comment]
@terebentina, @sp1thas and others

Please note: there are two errors that can occur here.
1. the first one posted by the original author where the cgroup files/directories are not where we think they should be. In one report above the sought file is `/sys/fs/cgroup/cpuacct/docker/fe2c373bfa536a36fdc3f60d1885c76d58a1c7a5bd99dc54cd3df000190d1a29/cpu.cfs_period_us`, this means that in `/proc/self/cgroup` an entry like `5:cpuacct,cpu:/docker/fe2c373bfa536a36fdc3f60d1885c76d58a1c7a5bd99dc54cd3df000190d1a29` is seen. But when we append this "offset" to `sys/fs/cgroup` to build a path to `cpuacct/cpuacct.usage`, the path does not work.
2. the other is identified by this in the log message `{:exception=>"NoMethodError", :message=>"undefined method []' for nil:NilClass"}`, meaning that the files/directories are found but  one or more files do not have the expected format. Most likely that `/proc/self/cgroup` exists but is empty.

It will be super super helpful if, when you get these errors, you did the following:
**For the missing files error**:
1. Confirm whether is cgroups is or is not disabled or does or does not exist on the system.
2. If exists, find the paths to the `cpu/cpu.stat`, `cpuacct/cpuacct.usage`, `cpuacct/cpu.cfs_period_us` and `cpuacct/cpu.cfs_quota_us` files. Logstash is expecting them to be at:
```
/proc/self/cgroup
/sys/fs/cgroup/cpu/cpu.stat
/sys/fs/cgroup/cpuacct/cpuacct.usage
/sys/fs/cgroup/cpuacct/cpu.cfs_period_us # contains an integer
/sys/fs/cgroup/cpuacct/cpu.cfs_quota_us # contains an integer

On a Google Compute RHEL7 instance this is what I get:

cat /proc/self/cgroup
11:pids:/
10:hugetlb:/
9:devices:/
8:freezer:/
7:perf_event:/
6:cpuset:/
5:cpuacct,cpu:/
4:blkio:/
3:memory:/
2:net_prio,net_cls:/
1:name=systemd:/user.slice/user-1002.slice/session-1.scope

cat /sys/fs/cgroup/cpu,cpuacct/cpu.stat
nr_periods 0
nr_throttled 0
throttled_time 0

cat /sys/fs/cgroup/cpuacct/cpuacct.usage
52976393023
cat /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
100000

cat /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
-1
```
3. Add a comment here with the paths and their contents, the Docker version, the Host OS version and any other info that you think may be relevant.

**For the unexpected format error**:
1. Confirm that the files have content similar to the listing above.
2. If `proc/self/cgroup` is empty, try to find where your Host OS has these files.
2. Add a comment here with the paths and their contents, the Docker version, the Host OS version and any other info that you think may be relevant.

**Comment by sp1thas** [comment]
@guyboertje thank you for your detailed response and analytical approach.
in my setup it occurs the second type of error:
```bash
$ cat /proc/self/cgroup 
12:blkio:/
11:rdma:/
10:hugetlb:/
9:memory:/
8:devices:/user.slice
7:perf_event:/
6:freezer:/
5:cpu,cpuacct:/
4:cpuset:/
3:pids:/user.slice/user-1000.slice/session-932.scope
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-1000.slice/session-932.scope
0::/user.slice/user-1000.slice/session-932.scope

$ cat /sys/fs/cgroup/cpu/cpu.stat
nr_periods 0
nr_throttled 0
throttled_time 0

$ cat /sys/fs/cgroup/cpuacct/cpuacct.usage
3744565630252532

$ cat /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
100000

$ cat /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
-1
```
OS: Ubuntu 18.04.1 LTS
Logstash version: 6.4.0

**Comment by guyboertje** [comment]
@sp1thas 

Thanks for this valuable feedback.

I suspect it is the last entry in `/proc/self/cgroup`...
```
0::/user.slice/user-1000.slice/session-932.scope
```
I need to verify but I think our code is expecting a string between the `::` and thereby fails.

**Comment by guyboertje** [comment]
I confirmed the the code does not anticipate the line with no text between the two colons.

Now we need to understand the first error better and we can fix this one proper like innit.

**Comment by guyboertje** [comment]
Some kernels do not create some of the needed files. Must improve the file existence checks.

**Comment by Zenexer** [comment]
Is there a temporary workaround for this?  I'm encountering the same `::` issue as @sp1thas on Ubuntu 18.04.1.

**Comment by guyboertje** [comment]
@Zenexer 
I can't think of one. I don't think removing the line is an option not is adding a space between the `::` is either.

**Comment by guyboertje** [comment]
PR up https://github.com/elastic/logstash/pull/9999

**Comment by der-eismann** [comment]
Just to take part in - I have the same second problem. I can run logstash perfectly fine from the commandline as root, but when I use the systemd service all it does is logging
```
Error, cannot retrieve cgroups information {:exception=>"NoMethodError", 
:message=>"undefined method `[]' for nil:NilClass"}
```
In case it is helpful:
OS: openSUSE Leap 15.0
Kernel: 4.12.14-lp150.12.16-default
Logstash version: 6.4.0
```
$ cat /proc/self/cgroup 
12:rdma:/
11:blkio:/
10:pids:/user.slice/user-0.slice/session-622.scope
9:hugetlb:/
8:cpu,cpuacct:/
7:perf_event:/
6:cpuset:/
5:memory:/
4:net_cls,net_prio:/
3:freezer:/
2:devices:/user.slice
1:name=systemd:/user.slice/user-0.slice/session-622.scope
0::/user.slice/user-0.slice/session-622.scope

$ cat /sys/fs/cgroup/cpu/cpu.stat
nr_periods 0
nr_throttled 0
throttled_time 0

$ cat /sys/fs/cgroup/cpuacct/cpuacct.usage
157911049320736

$ cat /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
100000

$ cat /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
-1
```

**Comment by guyboertje** [comment]
PR #9999 Merged.
