### ISSUE TITLE
Include new plugin docs for Logstash 5.3

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6844]
We have a few new plugins added in LS 5.3, let's be sure to build and add them to the index:
- JDBC Streaming filter - https://github.com/logstash-plugins/logstash-filter-jdbc_streaming
- Google PubSub input - https://github.com/logstash-plugins/logstash-input-google_pubsub
- Monasca Log API output - https://github.com/logstash-plugins/logstash-output-monasca_log_api
- Age filter - https://github.com/logstash-plugins/logstash-filter-age
- Emoji filter - https://github.com/logstash-plugins/logstash-filter-emoji

**Comment by suyograo** [comment]
I published docs for all of these except monasca. That plugin needs quite a bit of work w.r.t. its docs.
