### ISSUE TITLE
Error while trying to install Plugins [Error Bundler::InstallError]

### ISSUE THREAD

**Issue by Behkxyz** [elastic/logstash#6854]
While trying to install any of the following:
```
/usr/share/logstash/bin/logstash-plugin install logstash-filter-translate
/usr/share/logstash/bin/logstash-plugin install logstash-filter-tld
/usr/share/logstash/bin/logstash-plugin install logstash-filter-elasticsearch
/usr/share/logstash/bin/logstash-plugin install logstash-filter-rest
```

Got the Following Message:
```
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.3.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.3.0'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```

OS: Ubuntu 14.04
ELK: 5.3.0
Ruby: 1.9.3p484

**Comment by Behkxyz** [comment]
Note: I do not exit or need to exit through a Proxy

**Comment by Behkxyz** [comment]
Installing JRuby + jruby-openssl gem resolves the issue.

**Comment by svinohod** [comment]
Installing JRuby + jruby-openssl gem don't resolves the issue for me.

My workaround:

1. download necessary plugin manually, e.g. from github.com
2. Build your plugin gem by: `gem build logstash-filter-awesome.gemspec`
3. install the plugin by: `sudo bin/logstash-plugin install --local --no-verify /path/to/your/plugin/logstash-filter-awesome.gem`
