### ISSUE TITLE
Multiple pipeline and duplicates pipeline_id

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6858]
Following: @jsvd's [comment](https://github.com/elastic/logstash/pull/6632#issuecomment-290395005)

---

With the changes going on in the agent class in  #6632 and the addition of officially supporting multiple pipelines. We have to be a bit more strict with the uniqueness of the pipeline ids and to define what are the actions resulting from a conflict.

Let's look at the role of the different part as defined in #6632 

### Agent

 - Manage the lifecycle of the pipelines
 - Periodically converge the internal state

### SourceLoader:
 - Manage multiple sources of configuration
 - Aggregate the configuration from N sources.

### Proposal

I think the agent is doing enough, right now with managing the pipelines, I believe the `SourceLoader` at aggregation time should validate the uniqueness of the `pipeline_id` then we can implement one of the following scenarios.

1. The `#fetch` fails and log the error.
2. The sources can have different priorities, if a conflict happens we take the highest priority pipeline, we log the error and drop the conflicting pipeline.

I think we should to the easiest route first with 1.

**Comment by jsvd** [comment]
I'm certainly +1 on having fetch fail. If a source provides two pipelines with the same id it will certainly be due to copy paste or another kind of error, so it's great that we can stop the reload right there.

**Comment by ph** [comment]
@jsvd And we can maybe communicate that back to the source if needed or even supported?

**Comment by ph** [comment]
> I'm certainly +1 on having fetch fail. If a source provides two pipelines with the same id it will certainly be due to copy paste or another kind of error, so it's great that we can stop the reload right there.

Actually, it's legit to have multiple sources:

- Monitoring
- Config management

So the fail will happen when both of then converge.

**Comment by jsvd** [comment]
makes perfect sense 👍  in that case programatically it will be harder to call back to the source signalling an error.

**Comment by ph** [comment]
@jsvd We can make the pipeline_config keep a reference of the creator, we already do but its mostly for debugging.

**Comment by ph** [comment]
I have implemented a simple solution on my side, but after implementing it I think we should do it in both places, because new config sources can be added by a plugin and multiple sources can be running at the same. This require us to add guards on the `source_loader` at aggregation time to make sure they are unique. 

But it's also up to the **source** author to also check for that in his current domain, that way he can provides better feedback, line number, column.

**Comment by suyograo** [comment]
+1 on failing if 2 pipelines have the same ID. 

> Actually, it's legit to have multiple sources:

@ph I don't understand this scenario. The source loader is the one that always passes the config, right? Checking at that point for duplicate IDs would be enough?

**Comment by ph** [comment]
@suyograo There is a small distinction between the `SourceLoader` vs a `Source`.

A *Source* for me is where the configuration is fetched, or where I should look for pipeline configurations.

- Internal Pipeline (Like the monitoring pipeline in x-pack)
- Elasticsearch in the config management is a source
- Local configuration (either `-e` or `-f`) is a source.
- Modules can be a source of configurations.

One or more source of configuration can be active, people could also add new sources since it is a plugin system.

The *SourceLoader* is just making an abstraction over the multiple sources of configuration, for the stability of the system It need to make sure the pipeline are globally unique, So I am adding guards for that.

But some plugins author might want to handle the problem at their plugin level, depending on their format, just to provide more information. Because currently, the source loader doesn't know anything about the original format making hard to say: "You have duplicated pipeline id at line X of your configuration".


I added a comment there: https://github.com/elastic/logstash/issues/6521#issuecomment-290812737 concerning the duplicate id at the format leve.

**Comment by jsvd** [comment]
To have some closure here, can we decide that each source should do its own duplicate detections, but at the end of the day, the state resolver or another piece in core must check duplicates across all sources?

**Comment by ph** [comment]
I believe so, it might be not needed all the time depending on the format of the source.

In the context of `pipelines.yaml` a hash key could fix the duplicate problem, in the context of es, we use the `pipeline_id` is the `document_id` so we wont have duplicate too.
