### ISSUE TITLE
Equivalence of Pipelines vs the actions required to converge the agent state

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6859]
From https://github.com/elastic/logstash/pull/6632#discussion_r108890099

---

In the current context of pipeline reloading (5.x) we only look for the config changes, we don't care if the number of workers changed or not. With the changes in #6632 we will support multiple pipelines out of the box inside Logstash and multiple sources for the configuration. Making a good time to revisit when a pipeline needs to be reloaded.

### Conditions to mark a pipeline to be reloaded

- config string changes
- workers
- batch.size
- batch.delay

**Comment by jsvd** [comment]
I think it makes sense to have this set of options somewhere globally in logstash. It could be used for testing similarity of fetched PipelineConfigs but also to validate that a fetched PipelineConfig doesn't have invalid settings (like `http.port`).

We could have a subclass of LogStash::Settings called LogStash::PipelineSettings that contains only this small subset of settings + a pointer to a more generic settings Object

**Comment by ph** [comment]
@jsvd I am + 1 for having a dedicated settings object for pipelines I would make it a regular class that you can instantiate with a hash, that way it will be more easy to manipulate and would keep the validation.

**Comment by jsvd** [comment]
done in https://github.com/elastic/logstash/pull/6525
