### ISSUE TITLE
Test failure: expected 1 read of /proc/loadavg, got 2 reads.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6867]
Build failure: https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-os-compatibility/os=opensuse/437/console

Snippet:

```
:

  1) LogStash::Instrument::PeriodicPoller::LoadAverage on mocked system on Linux when it can read the file return the 3 load average from `/proc/loadavg`
     Failure/Error: expect(::File).to receive(:read).with("/proc/loadavg").and_return(proc_loadavg)
       (<File (class)>).read("/proc/loadavg")
           expected: 1 time with arguments: ("/proc/loadavg")
           received: 2 times with arguments: ("/proc/loadavg")
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/opensuse/logstash-core/spec/logstash/instrument/periodic_poller/load_average_spec.rb:17:in `(root)'
```

**Comment by ph** [comment]
I've tried to debug that before, but after a lot of runs, I was never able to reproduce it, either with or without the same seed.

I think the following is happening we have a thread in the background (Agent?), that is not completely close when this test is run. So `File.read` is called from 2 different threads, since we mock the class method this make the expectation fails.

The more I see this is mocking on the class methods is bad style, especially in our multi-threaded application. I think we could just inject the content in the method signature this would allow us to remove the mock.

**Comment by jordansissel** [comment]
https://logstash-ci.elastic.co/job/elastic+logstash+5.3+dockerubuntu-periodic/630/console

**Comment by ph** [comment]
@jordansissel Can you take a look at #6886, it fixes the issue for good. I believe we have a rogue PeriodicPoller from a previous test, I haven't been able to reproduce it locally.

**Comment by robbavey** [comment]
This looks to have reoccurred - https://github.com/elastic/logstash/issues/6867

**Comment by robbavey** [comment]
Another reoccurrence - https://logstash-ci.elastic.co/job/elastic+logstash+5.5+dockerubuntu-periodic/182/console

```
Failures:

  1) LogStash::Instrument::PeriodicPoller::JVM load average on linux when an exception occur reading the file doesn't raise an exception
     Failure/Error: expect(::File).to receive(:read).with("/proc/loadavg").and_raise("Didnt work out so well")
       (<File (class)>).read("/proc/loadavg")
           expected: 1 time with arguments: ("/proc/loadavg")
           received: 2 times with arguments: ("/proc/loadavg")
     # ./logstash-core/spec/logstash/instrument/periodic_poller/jvm_spec.rb:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

Finished in 5 minutes 35 seconds (files took 4.44 seconds to load)
1829 examples, 1 failure, 4 pending

Failed examples:

rspec ./logstash-core/spec/logstash/instrument/periodic_poller/jvm_spec.rb:50 # LogStash::Instrument::PeriodicPoller::JVM load average on linux when an exception occur reading the file doesn't raise an exception

Randomized with seed 38958
```

**Comment by robbavey** [comment]
On further investigation, these last two issues likely have the same cause as the original logged issue, but don't have the workaround @ph added in #6886, as this particular test is stubbing the File.read method to inject an failure condition. This particular test failure could likely be 'resolved' in the short term by adding an `at_least(:once)` clause to the expectation to guard against the 'rogue periodic poller' mentioned above

**Comment by jsvd** [comment]
Another instance https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-unix-compatibility/os=debian/31/console

I'm ok with adding at_least(:once). In doing it there's a very small chance that, if the test set up was incorrect, it could yield a false negative from the rogue poller, but that's extremely unlikely and would quickly show failures in subsequent runs.

**Comment by jordansissel** [comment]
I'm ok with `at_least(:once)` also. To be honest, tests which assert some method is called always feel weird to me (even when I write them also!). It's hard to articulate further than that, at least for now.

+1 on using at_least :once for this situation.
