### ISSUE TITLE
I am using s3 plugin for pulling logs from buckets and my logstash crashes after one day . This is the error I am getting : Your application used more memory than the safety cap of 1G

### ISSUE THREAD

**Issue by CelestePhutela** [elastic/logstash#6871]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by suyograo** [comment]
@CelestePhutela can you open this in https://github.com/logstash-plugins/logstash-input-s3/issues

**Comment by CelestePhutela** [comment]
Hi,
I can't find the solution in given issues . Can you guide me which
particular issue to look .
Thanks and Regards ,
Celeste
