### ISSUE TITLE
Update design/architecture recommendation docs to include persistent queue options

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6875]
https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html

PQ feature will add some additional capability when it comes to absorbing bursts of data. This area (absorbing bursts) has been somethign we typically recommend any buffering message queue (kafka, redis, rabbitmq, etc), and would no longer necessarily need.

Documenting this can help new users by showing a simpler architecture when they are needing a buffer or sponge for data.

**Comment by dedemorton** [comment]
Hiya. Info about persistent queues is added in this PR: https://github.com/elastic/logstash/pull/7005

Let me know if it's OK to close this issue now.

**Comment by acchen97** [comment]
Closed with https://github.com/elastic/logstash/pull/7005.
