### ISSUE TITLE
Disk level stats for monitoring API

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6884]
With PQs, and eventually DLQs, in place, we will need a way to track overall disk usage and performance for these components. A few items to consider adding here:
- Disk allocated for PQs
- Disk used by PQs
- Disk allocated for DLQs
- Disk used for DLQs
- Disk I/O stats

**Comment by colinsurprenant** [comment]
Discussion about PQ disk size usage APIs in #8986 where I am trying to untangle what we need.

**Comment by colinsurprenant** [comment]
If #8986 and #8936 covers the PQ side I suggest we close this and open a new DLQ specific one?

**Comment by colinsurprenant** [comment]
@acchen97 ^^ ?

**Comment by acchen97** [comment]
Closing... we can revisit the DLQ ones when we receive more demand.
