### ISSUE TITLE
Add a way to securely store secrets

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6892]
Logstash is glue between many systems. As a result, the configuration will often carry credentials for various remote systems. Currently, users write these values in plain text. This is not ideal.

Can we use environment variables? Some users will use `${FOO}` environment variables in their Logstash configs to pass secrets into a pipeline configuration. This doesn't solve the problem because environment variables are still plain text. Further, environment variables are generally *more* visible in more ways than files: `ps`, `/proc/[pid]/environ`, heap dumps, shared with child processes, etc. *Environment variables are not secret.*

Elasticsearch started work on solving this by making a [new command-line tool for managing secrets](https://github.com/elastic/elasticsearch/pull/22335). Logstash needs the same.

Long-term Proposal:

* Create a mechanism for users to securely share secrets with Logstash.
* All plugin settings using `:validate => password` will sourced only through this secrets store.
* Configuration settings (yaml) may need a way to refer to the secret store as well.

Next steps:

* [x] Review the Elasticsearch code and see what, if anything, we can share.
* [ ] Implement and document tool for managing secrets. (Keeping in mind that we also support centralized config in x-pack, and encrypted secrets could maybe live along side that)
* [ ] Design mechanism for the pipeline to feed secrets to plugins (plugins should not be able to arbitrarily query the secret store).
* [ ] Design a product path such that Logstash will eventually reject plain-text secrets.

Design assumptions:

* This secret store will be a file local to Logstash (same as Elasticsearch)

Open questions:

* How will an operator provide the decryption key for the secrets store?
* How should secrets be referenced? Explicitly in the configuration files? Implicitly based on some namespace (like 'output.elasticsearch.password') ?
* What is the user experience for this going to be like? Can we take an existing configuration help walk users through setting the credentials?

**Comment by jordansissel** [comment]
I looked at the Elasticsearch code:

* [KeyStoreWrapper](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/settings/KeyStoreWrapper.java) uses parts of Lucene and Elasticsearch. It is unlikely we can reuse this class.
* [SecureString](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/settings/SecureString.java) We can probably copy.
* [KeyStoreCli](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/settings/KeyStoreCli.java) uses parts of Elasticsearch and is unlikely we can reuse this class.

**Comment by aciokler** [comment]
We currently need a way to securely store passwords in the logstash configuration files. We could really use this feature or something similar. Any updates?

**Comment by jakelandis** [comment]
@aciokler - not much of an update other then we have had some internal discussions and this is still on our radar at or near the top of the list. 

@here
Are there specific regulations / STIGs that you are need to satisfy ?  (please be specific and link or copy the exact text please)

**Comment by jakelandis** [comment]
This work is underway and most discussions are happening over at #8353

**Comment by jordansissel** [comment]
This shipped with Logstash 6.2.0: https://www.elastic.co/guide/en/logstash/6.2/keystore.html
