### ISSUE TITLE
Test failure: Plugin pack fails due to upstream network problem

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6904]
Build failure: https://logstash-ci.elastic.co/job/elastic+logstash+5.3+dockerubuntu-periodic/625/console

```

Failures:

  1) LogStash::PluginManager::OfflinePluginPackager when the plugins exist with wildcards and normal plugins creates a pack with the plugins
     Failure/Error: subject.package(plugins_args, target)
     IOError:
       Connection reset by peer
```

**Comment by original-brownbear** [comment]
Trying this one :)

**Comment by andrewvc** [comment]
Freak accident

**Comment by andrewvc** [comment]
@colinsurprenant saw this [here](https://travis-ci.org/elastic/logstash/jobs/235874652), reopening. I've seen it a few other times as well.

I'm confused by this @ph, aren't these tests supposed to all pass offline anyway?

**Comment by ph** [comment]
@andrewvc We actually generate a package in that test, so they require to be online. I will take a stab a it right now. I've seen it too in the email.

**Comment by andrewvc** [comment]
@ph I saw three over the last 24 hours for some reason. Keep in mind, we now run the offline specs [separately](https://github.com/elastic/logstash/blob/master/ci/travis_integration_run.sh#L14)

**Comment by andrewvc** [comment]
@ph apparently I am confus

**Comment by ph** [comment]
Just to clarify, theses are the test faillings https://github.com/elastic/logstash/blob/master/spec/unit/plugin_manager/offline_plugin_packager_spec.rb#L102-L134
