### ISSUE TITLE
Enhancement - Record Last Run Meta Data Path

### ISSUE THREAD

**Issue by waynetaylor** [elastic/logstash#6922]
I love ES & Logstash.. Observation and enhancement please.

By settings value in my conf file I can record my last run and the time which is used to pick up where it left off in next run

Example:
record_last_run => true
last_run_metadata_path => "/opt/logstash-5.3.0/bin/log.txt"
schedule => "*/5 * * * *"

The above setting tells Logstash to record my last run, assume a data, put into log.txt the last run up to time & run every 5 minutes.

Use case: In the world of ephemeral infrastructure e.g. EC2 instances through an automated build pipeline this causes a challenge. Specifically, if the instance terminates the last run time is lost. This means by default when a new AMI is launched we will start again at 1970-01-01 00:00:00. 

Desired Solution: it should be possible to source last_run_metadata_path from S3 / EFS / Database Configuration Table. This will solve the ephemeral problem.

**Comment by untergeek** [comment]
This sounds like it should be plugin-specific.  If not, this sounds an awful lot like Logstash will be expected to keep state, which is something that is also handled plugin-specific.

Which plugins would need this behavior?

**Comment by waynetaylor** [comment]
@untergeek for now the biggest one i see is input-jdbc.

Thinking out loud is there any better way to handle this. I get looking at the code how this works and why, but surely not the only person that has seen or has this concern. 

Right now i'm looking at a solution that removes schedule option out and abstracts this into rundeck scheduling to do: -> run my logstash config -> once complete sync file to AWS s3

my logstash service is designed to aws s3 sync from s3 bucket in the instance of a reboot/restart/new AMI.

Seems like the only way round it

**Comment by untergeek** [comment]
It's worth considering.  Let's move this enhancement request to the [jdbc input plugin repository](https://github.com/logstash-plugins/logstash-input-jdbc), though.  This repository is for core Logstash issues, and this one seems pretty use-case specific, even if it gets replicated in some fashion between two or three plugins.

**Comment by jordansissel** [comment]
If you have ephemeral instances and Logstash records state, that state will be lost upon destruction/expiration of your ephemeral instance. You'd need an external storage system that is *not* ephemeral in order to have it survive.

If you can describe your scenario in more detail, we may be able to come up with some kind of solution.

**Comment by andrewvc** [comment]
Closing due to a lack of follow-up

**Comment by lfv89** [comment]
I'm facing this issue right at this moment.

I'm deploying logstash in an ephemeral environment, and I'm trying to figure out a way to store this state somewhere (thinking about a redis-like solution).

**Comment by waynetaylor** [comment]
@lfv89 I handled this ultimately by periodically syncing the values to s3. Now that logstash can be centrally managed surely there is a better way

**Comment by lfv89** [comment]
hey @waynetaylor, what do you mean centrally managed?

**Comment by waynetaylor** [comment]
@lfv89 i am using logstash central management in kibana a lot. This is a cool feature if your plugin allows dynamic reloadable.

**Comment by lfv89** [comment]
awesome! I don't think AWS supports x-pack plugins though :-(
