### ISSUE TITLE
logstash main process terminated with status 1

### ISSUE THREAD

**Issue by hectorqin** [elastic/logstash#6927]
I've got this error in the logs.What could be the reason and what does the status 1 means?

logstash is installed from http://packages.elasticsearch.org/logstash，version is 5.2.1

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

Any help will be appreciated
![image](https://cloud.githubusercontent.com/assets/14220132/25118565/687626f4-2449-11e7-99d4-73dd17a2539a.png)

**Comment by jsvd** [comment]
status 1 is an error, is there more information in the log files?

**Comment by hectorqin** [comment]
No more info, but the logstash still can commit events

**Comment by hectorqin** [comment]
@jsvd  No more info, but the logstash still can commit events

**Comment by jsvd** [comment]
@hectorqin can you show me the logstash logs and the logstash configuration you're using?

**Comment by hectorqin** [comment]
@jsvd   Thanks ! I finnaly find the reason. I was so stupid !  I run the script of "bin/system-install" when i install the logstash,and then i use the supervisor program to manage the logstash,so when i reboot the machine,it creates two processes and the default config from "startup.options" is wrong ,so one of the processes was terminated again and again!!
I find that the script of "bin/system-install" will create a config in dir of "/etc/init" and then the logstash will startup After boot up! But now i can't stop this process, must i delete the file of "/etc/init/logstash.conf" and reboot the machine?
