### ISSUE TITLE
input codec use cef

### ISSUE THREAD

**Issue by johnnyliao** [elastic/logstash#6932]
hello i am new logstash user when i use input codec => cef
i found output not have message(raw data)
how can i got raw data?
thx

**Comment by jsvd** [comment]
can you show your full configuration?

**Comment by johnnyliao** [comment]
hi jsvd 
thank you for reply

my logstash configuration like

input {
    stdin {
    	codec => cef 
    }
    udp {
        'port' => 8514
        codec => cef
    }
    tcp {
        'port' => 8514
        codec => cef
    }
}

filter {
  mutate {
    gsub => ['message', "\n", ""]
  }

  ruby {
    code => "
        none_values = [ '', 'N/A']
        hash = event.to_hash
        hash.each do |k,v|
                if none_values.include?(v)
                        event.remove(k)
                end
        end
    "
  }
}

output {
    elasticsearch { 
    	hosts => ["127.0.0.1:9200"]
    }

    stdout { codec => rubydebug }
}

input data is cef codec like:
Jul 10 10:39:04 alert.notice 10.66.140.59 SyslogAlertForwarder: CEF:0|McAfee|IntruShield||0x42400200|ARP: MAC Address Flip-Flop|Low|dst=N/A dpt=N/A cs2=6020338212089631144 cs2Label=Alert ID dvchost=M2950 deviceInboundInterface=7A-7B rt=2014-07-10 10:39:01 CST src=N/A spt=N/A act=Inconclusive cat=PolicyViolation app=N/A cnt=55 proto=N/A

i got stdout like
{
              "baseEventCount" => "55",
                "deviceVendor" => "McAfee",
                      "syslog" => "Jul 10 10:39:04 alert.notice 10.66.140.59 SyslogAlertForwarder:",
           "deviceReceiptTime" => "2014-07-10 10:39:01 CST",
      "deviceInboundInterface" => "7A-7B",
                    "@version" => "1",
                        "host" => "127.0.0.1",
               "deviceProduct" => "IntruShield",
              "deviceHostName" => "M2950",
    "deviceCustomString2Label" => "Alert ID",
                    "severity" => "Low",
                "deviceAction" => "Inconclusive",
         "deviceCustomString2" => "6020338212089631144",
          "deviceEventClassId" => "0x42400200",
         "deviceEventCategory" => "PolicyViolation",
                  "@timestamp" => 2017-04-19T08:33:28.264Z,
                        "port" => 40250,
                  "cefVersion" => "0",
                        "name" => "ARP: MAC Address Flip-Flop"
}

I want get raw data...but I cant find a way to got 
please help me ... thanks

**Comment by jsvd** [comment]
@johnnyliao ah, I misunderstood your question. right now the codec doesn't keep the raw data, I created an issue to track this request https://github.com/logstash-plugins/logstash-codec-cef/issues/34, please follow up there.
