### ISSUE TITLE
Cleanup asciidoc after doc extract

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#6952]
After we've finished extracting the asciidoc from the Logstash plugin source code  and moved it to separate asciidoc files (see https://github.com/elastic/logstash/issues/6846), we need to verify that the text removed in the following commits no longer appears in the asciidoc files. It's possible that this has been fixed in the docgen tool. I don't want to modify the ruby source by removing these comments because I think they are worth preserving.

If they still exist after we've extracted the doc, we can remove them.

- https://github.com/elastic/logstash-docs/pull/359/files#diff-f61fc2b56c8c487af8c729588c56474eL17
Code comments that begin “We keep the redefined method in a new http server class, this is because” (**Fixed in https://github.com/logstash-plugins/logstash-input-http/pull/65**)
- https://github.com/elastic/logstash-docs/pull/359/files#diff-4e7e66ae4e8b8593c6fae0c0000213e4L197
Description of “workers” that begins with “TODO remove this in Logstash 6.0” (appears in all output plugins) (**This will be fixed in the shared source.**)
- https://github.com/elastic/logstash-docs/pull/353/files#diff-c576c90d76578d21040e905b0fbc5c54L318
Code comment that begins with, “TODO(sissel): The timeout limitation does seem to be fixed in here:” (**Fixed in https://github.com/logstash-plugins/logstash-filter-dns/pull/33**)
- https://github.com/elastic/logstash-docs/pull/353/files#diff-2235b39ff7ff408cc934a1f7fa309f38L82
Code comment that begins with, “TODO(sissel): This should switch to use the `line` codec by default” (**Fixed in https://github.com/logstash-plugins/logstash-input-pipe/pull/17**)

**Comment by ph** [comment]
@debadair You can go ahead with making changes in the asciidoc files for each plugins, you don't need to bump the version I will do it on all of them when you are done.

**Comment by ph** [comment]
wrong user, sorry @debadair  :)

**Comment by dedemorton** [comment]
Fixed in asciidoc source files.
