### ISSUE TITLE
Get rid of Java internal API in org.logstash.ackedqueue.io.MmapPageIO

### ISSUE THREAD

**Issue by wainersm** [elastic/logstash#6961]
The org.logstash.ackedqueue.io.MmapPageIO class uses Oracle's internal classes (sun.misc.Cleaner and sun.nio.ch.DirectBuffer) to immediate cleanup of memory buffer (details about its addition is in PR #6740). It should avoid use of those classes. 

It is introduced in Java 9 a Cleaner class with similar operations (http://download.java.net/java/jdk9/docs/api/java/lang/ref/Cleaner.html).

This item is kind of reminder to investigate the replacement of those internal API in favor of the new Cleaner when Logstash move to support Java 9.

Compile warnings about internal API usage:
```
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:3: warning: Cleaner is internal proprietary API and may be removed in a future release
import sun.misc.Cleaner;
               ^
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:4: warning: DirectBuffer is internal proprietary API and may be removed in a future release
import sun.nio.ch.DirectBuffer;
                 ^
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:3: warning: Cleaner is internal proprietary API and may be removed in a future release
import sun.misc.Cleaner;
               ^
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:4: warning: DirectBuffer is internal proprietary API and may be removed in a future release
import sun.nio.ch.DirectBuffer;
                 ^
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:3: warning: Cleaner is internal proprietary API and may be removed in a future release
import sun.misc.Cleaner;
               ^
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:4: warning: DirectBuffer is internal proprietary API and may be removed in a future release
import sun.nio.ch.DirectBuffer;
                 ^
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:114: warning: Cleaner is internal proprietary API and may be removed in a future release
            Cleaner cleaner = ((DirectBuffer) this.buffer).cleaner();
            ^
/home/wainersm/projects/oss/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java:114: warning: DirectBuffer is internal proprietary API and may be removed in a future release
            Cleaner cleaner = ((DirectBuffer) this.buffer).cleaner();
                                ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 warnings
:logstash-core:processResources
:logstash-core:classes
:logstash-core:jar
:logstash-core:sourcesJar
:logstash-core:copyGemjar

BUILD SUCCESSFUL

Total time: 3 mins 42.087 secs
```

**Comment by colinsurprenant** [comment]
thanks for the headsup @wainersm - agree that moving toward Java 9 will hopefully provide a better way to achieve the correct cleaning of the memory buffers - in the mean time we still have to keep that code around as long as we support Java 8 which will be for a while. Using internal APIs should be avoided but in this case there is not much of an alternative.

**Comment by colinsurprenant** [comment]
I suggest we open 2 separate issues for this:
1- on using new cleaner class with Java 9
2- on removing the Java < 9 internal cleaner class upon Java 8 deprecation in LS.

**Comment by original-brownbear** [comment]
@colinsurprenant @suyograo Let me unsolicited opinion/comments here :)
I think the fact that we have to force a `Cleaner` here might be preventable with some refactoring.

As far as I can see most of the time the memory mapped buffers we created are simply read sequentially and it seems in 100% of cases, they are written to sequentially.

=> why even go the route of memory-mapping a buffer for writes? It seems it's just slower and more error prone with the necessary GC hacking when compared to the standard `FileChannel` + `DirectByteBuffer` approach?

=> are we sure that the occasional `java.nio.channels.SeekableByteChannel#position(long)` is worth the GC overhead the memory mapping introduces? (imo it's likely not worth it from looking at the code - especially if we drop some seemingly redundant ones)

Maybe we should just create a few quick micro-benchmarks for raw I/O logic and try out if MMapping is even worth it in our use case? (Mostly it's not for sequential IO in Java8 afaik)

**Comment by colinsurprenant** [comment]
memory mapped buffers live outside the heap so it should not add GC overhead. There *shouldn't* be any problem with the GC *hacking* - see description in #6740 - also note that Lucene also does this. The fact that Java 9 exposes it is also an indication of its utility. 

I am +1 on experimenting with other IO ideas to see if we can improve performance signature but let's not forget there are many other places where performance could also be optimized. We try to iterate in this sequence 1- let's make it work correctly and 2- let's make it work faster.

**Comment by original-brownbear** [comment]
@colinsurprenant 

> memory mapped buffers live outside the heap so it should not add GC overhead.

Well it's not Java GC, it's system paging memory management overhead. I think the fact that the benchmarks go ever slower the larger you make the page size is proof of my point (see data here https://github.com/elastic/logstash/issues/7162#issuecomment-302796372).
You're simply forcing the OS to monitor a constantly changing address space (from new page file creation), out of which you always only use a very small section when appending which comes with a lot of overhead.

> - also note that Lucene also does this. 

But Lucene uses it for a random access usage pattern right? In that case it's ok, since you're not constantly changing the address space as we do. Same goes for Cassandra doing this, it's fine for a database that requires constantly reading from/writing to some random offset, but for appending and rapidly changing files it's a problem imo.

**Comment by colinsurprenant** [comment]
can we move this discussion on using or not memory mapping elsewhere? it is a much bigger design discussion and it diverges from the original issue here which is more specific to the usage of the `Cleaner` class.

To move on with this, did my original proposal make sense?
> I suggest we open 2 separate issues for this:
> 1- on using new cleaner class with Java 9
> 2- on removing the Java < 9 internal cleaner class upon Java 8 deprecation in LS.

We can deal with these in-time as we move on with the evaluation of our mmap usage in the future and ramp up on Java 9.

**Comment by original-brownbear** [comment]
@colinsurprenant makes sense :)

**Comment by original-brownbear** [comment]
@andrewvc btw, I was just thinking ... this one is also a nice application for code gen. Just generate code using the right `Cleaner` approach depending on the detected runtime JDK version.
This way we could compile a jar that works for both JDK 8 and 9 here :)

**Comment by original-brownbear** [comment]
Seems there really is no generally accepted way other than codegen here, looking at what Lucene did https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/store/MMapDirectory.java#L338. Given that we already have Janino on the classpath, I think codegen is actually the cleaner solution (def will require a lot less code). Will look into this soon, this one seems to be the only actual code issue breaking LS Java9 support (at least in our Java code).

**Comment by original-brownbear** [comment]
Fixed in https://github.com/elastic/logstash/pull/8568 (still uses the internal APIs, but we can't change that without changing the IO strategy, but at least we're compatible with Java 9 now)
