### ISSUE TITLE
config.reload.interval need to use the `Settings::TimeValue`

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6964]
The `config.reload.interval ` settings use the `Numeric` type and we should use the new `TimeValue` type, this will allow a user to express the time in a more human way by including the unit.

**Comment by robbavey** [comment]
https://github.com/elastic/x-pack-logstash/blob/master/lib/config_management/bootstrap_check.rb#L48 should be updated post- this change too

**Comment by original-brownbear** [comment]
alright change is in,, all that's left is updating xpack

**Comment by original-brownbear** [comment]
xpack PR is in closing here
