### ISSUE TITLE
Enhancement: Add a query to the plugin manager.

### ISSUE THREAD

**Issue by KJ4IPS** [elastic/logstash#6965]
Add a 'query' sub-command to the plugin manager, to allow direct lookup of installed packages, without printing the entire list of installed plugins. This is largely inspired by `rpm -q`. 

e.g. 
```
$ logstash-plugin query some-installed-plugin
some-installed-plugin
$ logstash-plugin query --verbose some-installed-plugin
some-installed-plugin (1.2.3)
$ logstash-plugin query some-missing-plugin
$ logstash-plugin query --verbose some-missing-plugin
```

I modeled the output after the format already used by the list sub-command, but that is not necessarily the only/best way to do this.

I will likely work up a PR for this some time later this week.

**Comment by suyograo** [comment]
`logstash-plugin list foo` will return all plugins which match `foo` like `logstash-input-foo` or `logstash-output-foo`. Isn't that enough?
