### ISSUE TITLE
LS Monitoring UI docs page

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6991]
Our Logstash docs don't currently link to or mention the monitoring UI. My proposal would be to have a top level Monitoring section that encompasses a new Monitoring UI page (which can link off to the relevant x-pack docs) and the monitoring API endpoints and response payloads.

/cc @dedemorton

**Comment by dedemorton** [comment]
I'll add a topic level called "Monitoring Logstash" and nest the API info under that. Does that sound OK?

**Comment by acchen97** [comment]
Sounds good, and the monitoring UI benefits/brief will just be in that top level page then, right? In this particular context, I'd be +1 for including a snapshot of the UI.

**Comment by dedemorton** [comment]
Yup, that's right. We'll need a container for all the X-Pack monitoring docs that will be making their way into the LS docs at some point in the near future (maybe 5.5).

**Comment by dedemorton** [comment]
Closed via #7443
