### ISSUE TITLE
Very slow startup and configuration parsing (treetop)

### ISSUE THREAD

**Issue by micoq** [elastic/logstash#6999]
Currently, Logstash become very slow and consume a large amount of memory at startup when parsing big configuration files (> 128ko).
Internally, the treetop parser generate a single object `Treetop::Runtime::SyntaxNode` for each character even when it encounters white spaces or comments. This wastes a large amount of memory and slows down the parsing process.

You can easily reproduce the problem by using the embedded interpreter:
```
./logstash -i irb
g=LogStashConfigParser.new
config="input{}"+" "*1000000;nil
c=g.parse(config)
```
The last line will be very slow (and can crash Logstash if you don't have enough heap memory). The compilation process is impacted too but slightly:
```
c.compile()
```
You will never encounter an example like this in real life (~1MB of spaces !) but the problem is similar with any configuration with a lot of comments / indentations or just regular code.

However, I didn't find any option in treetop or in the configuration grammar to clean up the syntax tree. This behavior seems to be hard coded :(

With a monkey patch, it's possible to drop some unwanted `SyntaxNode`. Try to add this in config_ast.rb:
```
class LogStashConfigParser < Treetop::Runtime::CompiledParser

  protected

  def instantiate_node(node_type, input, interval, elements = nil)
    if node_type == LogStash::Config::AST::Whitespace
      elements = nil
    elsif !elements.nil?
      elements.delete_if { |n|
        n == true
      }    
      elements = nil if elements.empty?
    end
    if node_type.respond_to? :new
      node_type.new(input, interval, elements)
    else
      SyntaxNode.new(input, interval, elements).extend(node_type)
    end
  end
end
```
This code removes the content of the `Whitespace` nodes and the single character nodes (stored as `true` in memory but seems to be expanded when necessary).
It works with some examples but I can't be sure it will do the job for every configuration.

I'm sure we can't remove the `Whitespace` nodes completely because the compiler process can access to child nodes directly and need to have the right number of nodes. e.g. for the [plugin attributes](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/grammar.rb#L584).

- Version: all versions up to the last 5.3.2

**Comment by kares** [comment]
closing due EOL of 5.X ... please open a new report if this is still an issue on recent LS
