### ISSUE TITLE
Fails: LogStash::Pipeline Periodic Flush flushes the buffered contents of the filter

### ISSUE THREAD

**Issue by ph** [elastic/logstash#7024]
Job: elastic+logstash+5.4+dockerubuntu-periodic
link: https://logstash-ci.elastic.co/job/elastic+logstash+5.4+dockerubuntu-periodic/263/console

```
  1) LogStash::Pipeline Periodic Flush flushes the buffered contents of the filter
     Failure/Error: expect(event.get("message").count("\n")).to eq(99)
       
       expected: 99
            got: 98
       
       (compared using ==)
     # ./logstash-core/spec/logstash/pipeline_spec.rb:607:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:40:in `(root)'
```

```
Finished in 6 minutes 53 seconds (files took 6.24 seconds to load)
2617 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/pipeline_spec.rb:597 # LogStash::Pipeline Periodic Flush flushes the buffered contents of the filter

Randomized with seed 30079

```

**Comment by ph** [comment]
Theory, this test uses the multiline filter and look at the number of lines in the message field, this should work if the worker is set to 1. I think that depending on the order of the test sometime the worker values is set to a higher value than 1.

**Comment by suyograo** [comment]
Why do we even test ML filter since it is deprecated? Can't we delete this test?

**Comment by ph** [comment]
@suyograo I think we should keep the purpose of the test (test the periodic flush) but remove the multiline filter from the equation.

**Comment by andrewvc** [comment]
I think @suyograo is right, we should inject a dummy filter that just flushes some random thing instead of depending on timing here.

**Comment by andrewvc** [comment]
I have a fix here: https://github.com/elastic/logstash/pull/7131

**Comment by original-brownbear** [comment]
@andrewvc assigned you to reduce the bot's spamming :D
