### ISSUE TITLE
Clarify tuning options for PQ in documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#7027]
Currently, we do a pretty good job [documenting](https://www.elastic.co/guide/en/logstash/5.4/persistent-queues.html) some of the tuning settings available for PQ.
The flip side of documenting and exposing every setting is that users end up looking at a list of settings and wonder if there is something to tune here :)  In short, our general recommendation is to use all the defaults (which are sensible).

There are also settings we document, but at the same time noted that they are either internal and not intended to be changed.  For settings that don't really apply to the end users, it may be better if we leave them out of the documentation (and in the comments of logstash.yml - or least add a disclaimer to the comments to tell users not to change it) to avoid confusion.

Some suggestions for changes:

- Perhaps we can remove `queue.page_capacity` from documentation (and maybe also default comments in the logstash.yml) since we do not see a need for users to change the setting and it's already noted that it will not provide performance improvements.  There are also references to this setting various places on this page.  Maybe instead of directly using queue.page_capacity in these references, just describe it as page capacity (so users will not think about trying to change the setting to affect how durability or garbage collection work?)
- `queue.max_events`:  We are noting in the doc that "This value is used internally for the Logstash test suite."  But in the comments of the setting in the logstash yml, we suggest that there is a relationship between max_events and max_bytes that we check for when deciding which one applies to the queue capacity so it doesn't seem like this is only a setting that is used for our test suite.  Perhaps we can leave the test suite statement out?
- From talking to Jordan, there is a potential edge use case for actually setting `queue.max_bytes` to something much smaller (eg. 10mb) from the default, where users do not want much buffering, but do want the protections of the PQ.  Might be a good one to document.
- We mention both `queue.checkpoint.writes` and `queue.checkpoint.acks` settings in the durability section.  Per Jordan, if durability is important (and the user is willing to trade off performance), the only setting here we recommend is simply to set queue.checkpoint.writes to 1.  Other setting changes or setting queue.checkpoint.writes to another value is unlikely going to be productive.  We may want to clarify this.
- To be consistent with the first part of the documentation where we provide default values for the settings mentioned, when listing the settings available under durability section, eg. queue.checkpoint.writes, it will be nice to provide the default value as well (i.e. 1024)
- `queue.checkpoint.interval` is in the default logstash.yml settings file but not mentioned in the documentation.  If it's not intended to be changed, perhaps we can leave that out of the comments as well (or put a note in the comment that tells the users not to change it, etc..)

**Comment by dedemorton** [comment]
cc @suyograo

**Comment by andrewvc** [comment]
@ppf2 thanks for writing this, and apologies for the late reply, we'll need to take a look at this.

@original-brownbear @colinsurprenant @guyboertje and @jordansissel what are your thoughts?

**Comment by original-brownbear** [comment]
@ppf2 @andrewvc 

> Perhaps we can remove queue.page_capacity from documentation (and maybe also default comments in the logstash.yml) since we do not see a need for users to change the setting and it's already noted that it will not provide performance improvements. There are also references to this setting various places on this page. Maybe instead of directly using queue.page_capacity in these references, just describe it as page capacity (so users will not think about trying to change the setting to affect how durability or garbage collection work?)

I don't agree with this point. Whether or not `queue.page_capacity` has an impact on performance strongly depends on your system. The extremal cases here are (assuming no noise from slow filters etc. and this is def. not an exhaustive list):

* Old Linux kernels (old 2.6.x without unified buffering), spinning disks or OSX (it's not supported, but illustrates the point well) which will essentially see the performance of the PQ be inversely proportional to the page capacity. On OSXs HFS which seems to have a very poor implementation of `msync` it's exactly inversely proportional for example.
* Fast SSDs (on systems spare CPU cycles) or NFS setups (I know not supported either) that will probably see no effect from the setting.

> queue.max_events: We are noting in the doc that "This value is used internally for the Logstash test suite." But in the comments of the setting in the logstash yml, we suggest that there is a relationship between max_events and max_bytes that we check for when deciding which one applies to the queue capacity so it doesn't seem like this is only a setting that is used for our test suite. Perhaps we can leave the test suite statement out?

Hmm, maybe we should just leave this setting out of the documentation entirely? But I agree, in case we want to leave this documented we could def. shorten it by removing the "test suite" part :)

> From talking to Jordan, there is a potential edge use case for actually setting queue.max_bytes to something much smaller (eg. 10mb) from the default, where users do not want much buffering, but do want the protections of the PQ. Might be a good one to document.

+1. Smaller queues are much much faster than larger ones (in cases where PQ is the bottleneck), this is a very valuable tip.

> We mention both queue.checkpoint.writes and queue.checkpoint.acks settings in the durability section. Per Jordan, if durability is important (and the user is willing to trade off performance), the only setting here we recommend is simply to set queue.checkpoint.writes to 1. Other setting changes or setting queue.checkpoint.writes to another value is unlikely going to be productive. We may want to clarify this.

Agreed, this should be better explained in the docs. Maybe we should clearly state here, that the number here equals the maximum number of events (or acknowledgments) that are not guaranteed to be synced to disk?

> To be consistent with the first part of the documentation where we provide default values for the settings mentioned, when listing the settings available under durability section, eg. queue.checkpoint.writes, it will be nice to provide the default value as well (i.e. 1024)

Jup, we could simply use this as an example data point for the above explaination.

> queue.checkpoint.interval is in the default logstash.yml settings file but not mentioned in the documentation. If it's not intended to be changed, perhaps we can leave that out of the comments as well (or put a note in the comment that tells the users not to change it, etc..)

+1 this should go away. This is dead "code" since periodic acking is unimplemented.

**Comment by guyboertje** [comment]
I think @original-brownbear comment hit the nail squarely on the head. Nothing more to add from me.

**Comment by colinsurprenant** [comment]
+1

For the `queue.checkpoint.writes` and `queue.checkpoint.acks` please look at this blog post 
 https://www.elastic.co/blog/logstash-persistent-queue which tries to explain that, we could reuse some of this for the docs?

**Comment by andrewvc** [comment]
@original-brownbear  can you collaborate with @dedemorton on updating these docs in a PR?

**Comment by original-brownbear** [comment]
@andrewvc sure :)

@dedemorton ping me whenever you have a second to go over this :)

**Comment by dedemorton** [comment]
Fixed in #8927
