### ISSUE TITLE
Loop on start up - LS 5.4.0

### ISSUE THREAD

**Issue by nerddelphi** [elastic/logstash#7036]
Hi there.

After upgrade Logstash from 2.4.1 to 5.4.0 it just enters in a loop and doesn't get any input or produces output.

- Version: 5.4.0
- Operating System: Ubuntu 14.04 x64
- Config Files and Log-debug: https://pastebin.com/peDNzNaK , https://pastebin.com/MvYVVz4f , https://pastebin.com/9c23AEd5 , https://pastebin.com/jA4GwKUq

**Comment by nerddelphi** [comment]
Could be that error in Puma?

https://pastebin.com/WasVG70X

**Comment by jsvd** [comment]
this is strange, the logs that you provide in the initial post don't show the errors you linked afterwards. is logstash installed using deb package? are there any more logs you can attach here?
