### ISSUE TITLE
Gradle/Java Tests are not Run as Part of the Unit-Tests?

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7043]
Currently the rake task for the unit tests `test:core` does not execute the Java/Gradle unit-tests.
Also, the Gradle build is not documented in the Readme at all.

Shouldn't we run the Gradle UTs as part of `test:core` automatically (or if there is reasons not to do that at least document them in the Readme)?

**Comment by original-brownbear** [comment]
@suyograo what do you think about this one? The Gradle tests not running anywhere seems wrong :)

**Comment by suyograo** [comment]
@original-brownbear yes this definitely seems wrong. Let's fix it `rake test:core` to run these junit tests and also make the changes to the README about the gradle part.

**Comment by original-brownbear** [comment]
@suyograo alright, will do :)

**Comment by original-brownbear** [comment]
long fixed
