### ISSUE TITLE
Logstash 5.4 "./logstash-plugin list" throws NullPointerException

### ISSUE THREAD

**Issue by alamzeeshan** [elastic/logstash#7051]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by alamzeeshan** [comment]
Inside logstash-5.4.0/bin

`./logstash-plugin list`

**Throws:**

```
java/util/Hashtable.java:459:in `put': java.lang.NullPointerException
        from java/util/Properties.java:166:in `setProperty'
        from java/lang/System.java:796:in `setProperty'
        from java/lang/reflect/Method.java:497:in `invoke'
        from /apps/logstash-5.4.0/lib/pluginmanager/proxy_support.rb:40:in `apply_env_proxy_settings'
        from /apps/logstash-5.4.0/lib/pluginmanager/proxy_support.rb:62:in `configure_proxy'
        from /apps/logstash-5.4.0/lib/pluginmanager/main.rb:26:in `(root)'

```

**Comment by alamzeeshan** [comment]
It happens only when I set proxy in my OS environment:

```
export http_proxy=host:port
export https_proxy=host:port
```

My OS is RHEL 7

**Comment by ph** [comment]
I will close this in favor of https://github.com/elastic/logstash/issues/7045
