### ISSUE TITLE
Test failure: failure reload timestamp test

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7057]
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-os-compatibility/os=debian/477/console

Master branch.

```
Failures:

  1) LogStash::Agent metrics after config reloading when reloading a good config does not set the failure reload timestamp
     Failure/Error: expect(value).to be(nil)
       
       expected nil
            got #<LogStash::Timestamp:3815078> => 2017-05-09T16:03:32.013Z
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/debian/logstash-core/spec/logstash/agent_spec.rb:489:in `(root)'
```

**Comment by jordansissel** [comment]
https://logstash-ci.elastic.co/job/elastic+logstash+master+dockerubuntu-periodic/1994/console

**Comment by original-brownbear** [comment]
@jsvd could it be that you're already addressing this one in #7066 ? :)

**Comment by jsvd** [comment]
@original-brownbear yes it should fix this issue !

**Comment by jsvd** [comment]
this should no longer happen in master due to https://github.com/elastic/logstash/pull/7066
