### ISSUE TITLE
Contributing logstash-output-icinga

### ISSUE THREAD

**Issue by bobapple** [elastic/logstash#7061]
I would like to contribute our `logstash-output-icinga` plugin to the [logstash-plugins](https://github.com/logstash-plugins/) repository.

The plugin is currently located here: https://github.com/Icinga/logstash-output-icinga/
It includes Rspec tests, inline documentation and asciidoc documentation generated by [logstash-docgen](https://github.com/elastic/logstash/tree/master/tools/logstash-docgen)

If possible, I would like to continue my work on this plugin after it has been merged to the logstash-plugins repository.

**Comment by bobapple** [comment]
Is there anyone who can help me with this? Should I reopen the issue on [logstash-plugins](https://github.com/logstash-plugins/)?

**Comment by bobapple** [comment]
@jsvd do you have any news on this issue? Any feedback is welcome

**Comment by widhalmt** [comment]
I'd really like to see this in the Logstash package, too. So +1 from me.

**Comment by jordansissel** [comment]
Apologies for the silence on this. I think we can move this into the logstash-plugins repo.

I'll follow up shortly with next steps!

**Comment by jordansissel** [comment]
I've created https://github.com/logstash-plugins/logstash-output-icinga and have copied the git repo from https://github.com/Icinga/logstash-output-icinga/

@bobapple I've invited you as a collaborator on that repo.

I'll open some issues on the new repo to track the next steps.
