### ISSUE TITLE
Logstash-filter-grok downgraded from 3.4.0 to 3.3.1 with logstash 5.3 to 5.4 upgrade

### ISSUE THREAD

**Issue by jeffspahr** [elastic/logstash#7075]
The logstash-filter-grok was downgraded to 3.3.1 from 3.4.0 after an upgrade to logstash 5.4 from version 5.3.

This is reflected in the docs as well:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html1
https://www.elastic.co/guide/en/logstash/5.3/plugins-filters-grok.html1

This breaks the use of pattern_definitions in 5.4.

- Version: 5.4
- Operating System: CentOS 7
- Config File: N/A
- Sample Data: N/A
- Steps to Reproduce:
Install 5.3.
bin/logstash-plugin list --verbose logstash-filter-grok
Note version 3.4.0
Upgrade/Install 5.4
bin/logstash-plugin list --verbose logstash-filter-grok
Note version 3.3.1

**Comment by suyograo** [comment]
oops. this will be fixed in 5.4.1

**Comment by jeffspahr** [comment]
Thanks!

**Comment by jsvd** [comment]
logstash 5.4.1 will be released with grok plugin 3.4.0 https://github.com/elastic/logstash/blob/v5.4.1/Gemfile.jruby-1.9.lock#L206
