### ISSUE TITLE
Move Kafka Service in Integration Tests to a Dockerized Version

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7091]
@andrewvc @suyograo as discussed, let's start with Kafka and track this here:

* Dockerize whatever is is happening in `kafka-setup.sh` (and the other Kafka scripts) and plug it into the existing service infrastructure with the fixtures and such

**Comment by original-brownbear** [comment]
@suyograo @andrewvc there we go :) Will add follow up issues for the other services tomorrow.

**Comment by suyograo** [comment]
@original-brownbear +1. we should also remove the non-dockerized services as well

**Comment by original-brownbear** [comment]
closing merged to `master` and `5.x`, will link issues for the other services in a bit
