### ISSUE TITLE
`MEAN` Instrument type should be removed

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#7094]
We currently allow for a `mean` instrument type. This should, IMHO be removed. It cannot do its job accurately. I'm also not aware of it actually being used anywhere. It definitely isn't used in core.

The central problem with recording a `mean` stat is that on a non-realtime system you can't guarantee that samples were evenly spaced out. A series of timestamped gauges does a better job. This is what we can do in our x-pack monitoring extension, but not something we should do in core. The central difference is that x-pack has Elasticsearch, which can act as a time series database. I'd prefer not to build a tsdb into logstash. That would obviously involve a lot of complexity.

WDYT @suyograo @jsvd @ph ?

**Comment by ph** [comment]
+1 to remove it,.
