### ISSUE TITLE
Move Filebeat Service in ITs to Docker

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7098]
It's in the title, move the setup and teardown of the integration test Filebeat service to Docker like it was done in #7093 for Kafka.

**Comment by original-brownbear** [comment]
@andrewvc fyi :) maybe you want one of these (meaning either this one or #7097 I guess)?

**Comment by andrewvc** [comment]
@original-brownbear I'm glad to take this one! I make take a day to get to it.

**Comment by suyograo** [comment]
@wainersm this one is up for grabs as well, if you'd like :)

**Comment by wainersm** [comment]
I adopt it. :)

**Comment by wainersm** [comment]
Now that PR #7234 is merged, I will work on this one.

**Comment by original-brownbear** [comment]
@wainersm sweet thanks :)

**Comment by wainersm** [comment]
Hi @original-brownbear !  I realized that I will need to change the dockerized ci mechanism a little bit in order to adapt FileBeat tests.

I will send changes in small chunks to ease review.

Sent a first patch, that manage TLS certificates in dockerized CI....please let me hear your comments. :)

**Comment by original-brownbear** [comment]
@wainersm thanks! Can you make a PR from that first patch ? :)

**Comment by wainersm** [comment]
I'm working on helper methods to copy file contents from/to the container.

But I'm kind of stepping back for a moment to re-think the current docker design. The reason is that Filebeat tests require a work flow a bit more complex than we have implemented. For example, beyond copying files to the container (before start the service), the tests need to go for stop/start cycles in order to configure Filebeat.

**Comment by original-brownbear** [comment]
@wainersm can you give a little more detail? What do you see will turn into a problem with the current appraoch ?

**Comment by wainersm** [comment]
It's a matter of how we manage the container life cycle: currently the setup method is executed at test begin, it will creates the image, creates the container, then starts the container and the service. The teardown method is executed at test finish, it deletes the container and volumes associated.

Above is a simple life cycle that for Filebeat tests do not work. This requires to start and stop the service (not necessarily the container) with different configurations for each test context. So for Filebeat tests the setup method should just create the image, create the container, start the container (start the service with a possible default configuration). Afterwards, the test should be able to inject configuration files into the container, stop the service (not the container necessarily) and start the service. Indeed the container is seen as a "sand box".

It won't be hard to change the current management of the container life cycle to be used by Filebeat tests, and it will make more flexible at end. What do you think?

**Comment by original-brownbear** [comment]
@wainersm 

> Above is a simple life cycle that for Filebeat tests do not work. This requires to start and stop the service (not necessarily the container) with different configurations for each test context. So for Filebeat tests the setup method should just create the image, create the container, start the container (start the service with a possible default configuration). Afterwards, the test should be able to inject configuration files into the container, stop the service (not the container necessarily) and start the service. Indeed the container is seen as a "sand box".

wouldn't it be easier to simply use the `.insert_local` API that a `Docker::Image` exposes to build one image for each configuration we want to use and run the different images as new containers for each configuration.
Do you see a downside to that, to me it looks like the by far safest and easiest to implement approach?

**Comment by wainersm** [comment]
Hi @original-brownbear !  Sorry for delay to replay your message...I've been quite busy with other stuffs but I'm resuming this work now.

Yes, after think a bit about it I see the approach of customizing one image for each configuration as the right choice. My only concern so far is leaving "dirty images" into the system.

I'll play with this approach and should send a new patch soon.

**Comment by original-brownbear** [comment]
@wainersm thanks :)

>  My only concern so far is leaving "dirty images" into the system.

Don't worry about this imo. Docker is really efficient here, so each run adds like a few kb to the Docker image storage at best. Also those images don't change very often => I think we're good :)

**Comment by jakelandis** [comment]
Closing this since we have moved towards running the integration test themselves inside docker and want to avoid a docker in docker setup.
