### ISSUE TITLE
PQ Java Test Failures

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#7113]
Now that the PQ is turned on we have some java test failures like the ones seen here: https://travis-ci.org/elastic/logstash/jobs/232585006

These are breaking the build.

**Comment by original-brownbear** [comment]
link https://github.com/elastic/logstash/pull/7114 :)

**Comment by original-brownbear** [comment]
Fixed via https://github.com/elastic/logstash/pull/7114 :)

**Comment by andrewvc** [comment]
Woohoo!
