### ISSUE TITLE
Add Documentation on how to Set up Idea/Rubymine for Logstash Development? 

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7120]
Not sure if we want to do this since it's so specific to one IDE, but still given the current market it may not be the worst idea to add these two:

* Doc on how to run logstash specs from IDEA to enable debugging tests from the IDE (this one took me quite a bit of time to figure out myself :D) 
* Doc on how to make IDEA properly load ruby dependencies

WDYT?

**Comment by ph** [comment]
All for it, I am about to jump into the intellij wagon I can review it.

**Comment by jakelandis** [comment]
I received my Elastic laptop yesterday, so I took some detailed notes of getting everything running again. 

https://docs.google.com/document/d/1kqunARvYMrlfTEOgMpYHig0U-ZqCcMJfhvTtGt09iZg/edit
(please feel free to edit, my grammars is poor)

I tried to generalize the notes, but still unsure who the audience really is _(other then me the next time I need to setup from scratch)._

Documentation like this tends to rot quickly, and I have no intention of keeping this upto date. For example, I do not plan on updating this for JRuby 9k. _(unless others feel that is of great value)_

 I am abit unsure of what to do with this document. 

@dedemorton @jordansissel @suyograo  - thoughts ?

Also, please note that the instructions here deviate a bit from the formal readme in style, approach, and correctness (we need to fix some parts of the plugin readme's).

**Comment by dedemorton** [comment]
@jakelandis I'm assuming that Logstash community contributors might want to know about this setup, right? I'll defer to Jordan and/or Suyog's judgment on this one, but it seems to me that a blog entry is probably the best place for info like this. People sort of expect blog entries to get stale over time.

**Comment by suyograo** [comment]
@jakelandis this is mostly for developers (both internal and external contributors), so I would suggest adding this to CONTRIBUTING.MD in core repo. https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md

**Comment by jakelandis** [comment]
@suyograo  and @dedemorton  - thanks. 

I linked to it from our [on-boarding documentation](https://github.com/elastic/dev/blob/master/logstash/onboarding.md) (editable by anyone at elastic), and will link from the CONTRIBUTING.md to the [published version ](https://docs.google.com/document/d/1kqunARvYMrlfTEOgMpYHig0U-ZqCcMJfhvTtGt09iZg/pub)(non-editable) once I get a 👍 from on the content of the doc.

**Comment by original-brownbear** [comment]
@jakelandis you don't need anything from me here right? :) (just asking because I'm still assigned and don't wanna block this)

**Comment by jakelandis** [comment]
@original-brownbear - Nope, nothing from you specifically. I will remove you as an assignee. 

However, I would like someone to review the [published version](https://docs.google.com/document/d/1kqunARvYMrlfTEOgMpYHig0U-ZqCcMJfhvTtGt09iZg/pub) before I include into the CONTRIBUTING.md.

**Comment by jordansissel** [comment]
I am not sure I can help evaluate the changes here because the docs don't
apply to my deb environment:

- the Java instructions target OSX and I use windows and Linux (and I
basically never need to set JAVA_HOME also...)
- I use vi for editing ruby code, not Rubymine or other things

The doc you wrote looks pretty detailed and that is nice!

**Comment by ph** [comment]
I've decided to move away from my trusty vim setup to intellij full time I will take a look at your doc @jakelandis and report, looks detailed!

**Comment by ph** [comment]
@jakelandis Awesome, I was able to mostly make everything work except running the rspec suite in intellij everything else work, including the debugger. It's been a long time since I've used one of those. 

For my rspec problem, I don't see the option to run spec when I right click on the file.

**Comment by jakelandis** [comment]
@ph - Thanks for the review. 

I have update the [doc](https://docs.google.com/document/d/1kqunARvYMrlfTEOgMpYHig0U-ZqCcMJfhvTtGt09iZg/pub) with some instructions to ensure that you can run Rspec from the IDE.

Just search for "but the run/debug options do not show up" for the updated content.
