### ISSUE TITLE
Conversion tool for ingest pipelines

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#7128]
## Overview

Elasticsearch [ingest node](https://www.elastic.co/guide/en/elasticsearch/reference/master/pipeline.html) feature is a subset of Logstash functionality to transform documents before it hits ES index. Ingest node pipeline is created using JSON structure. Logstash pipeline is created using a DSL config language.

## Migrating from ingest to Logstash

Users would want to migrate to Logstash for the following reasons:

* Take advantage of the richer transformation capabilities in Logstash. Ingest processors today is a subset (plus some additional ones exclusively in ingest) of what Logstash filters provide.
* Use multiple outputs. Ingest was designed to only support ES as an output. For example, users may want to archive their incoming data to S3 as well as indexing it in ES.
* Add complex data flow logic to their ingestion. For example, users may want to use conditionals in LS.
* Use the persistent queue feature to handle spikes when ingesting data (from beats and other sources).
* Use the JDBC/web service lookup plugins in Logstash to enrich data.

## Migration Tool

Our goal is to provide a 1-way migration path from ingest node json to Logstash for the reasons mentioned above. This can be achieved using a tool that transpiles ingest DSL into the LS config equivalent.

If the tool is written in javascript, we can use it in Kibana to provide a UI. Also, this tool can be run on Java 8 using [Nashhorn](http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html). Hence with shared javascript code, we can provide a CLI tool using Java, and then a UI for easy migration.

### Pipeline-level rules:

1. Dots in field names: Ingest uses dots to access nested fields. For example: `apache2.access.remote_ip` needs to be converted to `[apache2][access][remote_ip]`.
2. `processors` map to `filters` in LS

### Filter level rules:

Each processor in ingest needs to be mapped to a filter in LS.

As a first step, we should target 1 ingest processor and convert them to LS. So create a grok pipeline in ingest and convert to LS pipeline with grok filter and no inputs and outputs.

For example:

Ingest JSON
```
{
   "description":"Pipeline for parsing apache error logs",
   "processors":[
      {
         "grok":{
            "field":"message",
            "patterns":[
               "%{IPORHOST:apache2.access.remote_ip} - %{DATA:apache2.access.user_name} \\[%{HTTPDATE:apache2.access.time}\\] \"%{WORD:apache2.access.method} %{DATA:apache2.access.url} HTTP/%{NUMBER:apache2.access.http_version}\" %{NUMBER:apache2.access.response_code} (?:%{NUMBER:apache2.access.body_sent.bytes}|-)( \"%{DATA:apache2.access.referrer}\")?( \"%{DATA:apache2.access.agent}\")?",
               "%{IPORHOST:apache2.access.remote_ip} - %{DATA:apache2.access.user_name} \\[%{HTTPDATE:apache2.access.time}\\] \"-\" %{NUMBER:apache2.access.response_code} -"
            ],
            "ignore_missing":true
         }
      }
   ]
}
```

Equivalent LS config:

```
filter {
   grok {
      match => { "message" => ["%{IPORHOST:[apache2][access][remote_ip]} - %{DATA:[apache2][access][user_name]} \[%{HTTPDATE:[apache2][access][time]}\] \"%{WORD:[apache2][access][method]} %{DATA:[apache2][access][url]} HTTP/%{NUMBER:[apache2][access][http_version]}\" %{NUMBER:[apache2][access][response_code]} (?:%{NUMBER:apache2.access.body_sent.bytes}|-)( \"%{DATA:[apache2][access][referrer]}\")?( \"%{DATA:[apache2][access][agent]}\")?",
        "%{IPORHOST:[apache2][access][remote_ip]} - %{DATA:[apache2][access][user_name]} \[%{HTTPDATE:[apache2][access][time]}\] \"-\" %{NUMBER:[apache2][access][response_code]} -" ] 
         }
     }
}


```

We can then generalize for the common filters in both ingest and LS.

**Comment by original-brownbear** [comment]
on it as discussed :)

**Comment by original-brownbear** [comment]
@suyograo good news, Nashorn makes us happy here -> executes my converter just fine :) 
see https://github.com/original-brownbear/logstash/blob/7128/logstash-core/src/main/java/org/logstash/ingest/JsonToGrok.java#L18 (ignore the dirtiness of the script inclusion, cleaning up soon)

**Comment by original-brownbear** [comment]
@suyograo I understand this is supposed to go to a frontend use case too, so we need a bit of pretty printing the output grok I guess? :)

**Comment by original-brownbear** [comment]
@suyograo is it by accident or by design that the above grok example has the second pattern double escaped while the first one is single escaped?
In the JSON both are at the same "level of escaping"/

**Comment by suyograo** [comment]
@original-brownbear yes on pretty print :)

**Comment by suyograo** [comment]
> In the JSON both are at the same "level of escaping".

hmm that does looks wrong. Let me double check

**Comment by suyograo** [comment]
@original-brownbear yep, that _is_ wrong escaping. It must be a copy-pasta :) I'll fix it now

**Comment by suyograo** [comment]
this is a different example of using a literal string:

```
filter {
  grok {
    match => {
      "message" => '%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "%{WORD:verb} %{DATA:request} HTTP/%{NUMBER:httpversion}" %{NUMBER:response:int} (?:-|%{NUMBER:bytes:int}) %{QS:referrer} %{QS:agent}'
    }
  }
}
```

**Comment by original-brownbear** [comment]
@suyograo so just to clarify:

JSON:
```json
(?:%{NUMBER:apache2.access.body_sent.bytes}|-)
```

goes to GROK:

```ruby
(?:-|%{NUMBER:apache2.access.body_sent.bytes})
```

? :)

**Comment by suyograo** [comment]
@original-brownbear just to be clear, `patterns` field in ingest JSON is still a GROK expression. It is just escaped differently in ES. For example, ES uses `\\[%{HTTPDATE:apache2.access.time}\\]` to escape the regex square brackets. LS uses `\[%{HTTPDATE:apache2.access.time}\]` to escape the regex. Everything else should be the same. So, back to your original question:

JSON:
```
(?:%{NUMBER:apache2.access.body_sent.bytes}|-)
```
is still a valid grok expression and should be directly translated to:

```
(?:%{NUMBER:apache2.access.body_sent.bytes}|-)
```

in LS.

If you were wondering what the above syntax means (in [Oniguruma](https://grokconstructor.appspot.com/RegularExpressionSyntax.txt) regex world):

`(?:subexp)` is a "not captured group" and `|` is alternation.

**Comment by original-brownbear** [comment]
@suyograo ok your answer is what I expected actually :) but the example in the initial post has the `|-` moved to the front, just an error in the example ? :)

**Comment by suyograo** [comment]
@original-brownbear argh, yeah, the original post had some bugs which I just fixed. :(

**Comment by original-brownbear** [comment]
@suyograo ok string literals now pass fine I think, at least the example above works fully :)
No time for a PR now, but feel free to test my branch again if you have some left over time :D (will likely clean it up later today though)

**Comment by suyograo** [comment]
I tested your branch and was able to generate the LS grok config. I then tested that on a real LS and 💥 works like a charm.

How about we extract the common functions to a separate file `ingest-to-logstash-pipeline.js`and import that in `ingest-to-grok.js`. We can then split the work to add `ingest-to-date.js`, `ingest-to-geoip` etc. WDYT?

**Comment by original-brownbear** [comment]
@suyograo doing that extracting as we "speak" :) Give it another 30-40 min (typing is slow at the airport :D) and we should have something nice and clean in a separate package under `/tools` :)

**Comment by suyograo** [comment]
Also, any thoughts on how we should _generalize_ this now that we have a working version? I'm thinking if we have to process a full ingest pipeline like this and convert it to its respective LS:

```
{
  "description" : "Pipeline to parse Apache logs",
  "processors" : [
    {
      "grok": {
        "field": "message",
        "pattern": "%{COMBINEDAPACHELOG}"
      },
      "date": {
        "match_field" : "timestamp",
        "target_field" : "timestamp",
        "match_formats" : ["dd/MMM/YYYY:HH:mm:ss Z"]
      },
      "convert": {
        "field" : "response",
        "type" : "integer"
      }
    }
  ]
}
```

**Comment by original-brownbear** [comment]
@suyograo on the topic of extracting `js` logic I'd be a little careful just because we don't really have much going for us in terms of `js` tooling and don't really expect that much `js` to come overall :)

Maybe we should just do this in 3 steps:

* Create the remaining two blocks of logic you mention by just copying from what we have and working in parallel
   * Create the logic for `ingest-to-date`
   * Create the logic for `ingest-to-geoip`
* Create the overall solution for the full pipeline from the 3 js files we have and dry things up once done

I think this way we'll probably not need to worry about any including of js files and whatnot and just get a single self contained js file in the end right? More importantly, we save the time we need to make a plan with what we expose and such. I mean I did my best here, but I wouldn't want to force my specific choice of `js` encapsulation on anyone ... and it probably takes longer to settle on what to extract where, than to go the `wet => done => dry` route?

**Comment by suyograo** [comment]
Makes sense to duplicate now, we can figure out what to extract later.

> Create the overall solution for the full pipeline from the 3 js files we have and dry things up once done

Just to clarify, the overall solution will be more than 3 files. It will actually be the subset of filters that ingest [implements](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest-processors.html) today. I think it's about 7.

**Comment by original-brownbear** [comment]
step 1 done in #7238
