### ISSUE TITLE
Building rake artifact:tar Pollutes the Git Index

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7129]
Currently `rake artifact:tar` pollutes the index as such:

```bash
➜  logstash git:(cleanup-queue-test) ✗ git status
On branch cleanup-queue-test
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   NOTICE.TXT

no changes added to commit (use "git add" and/or "git commit -a")
```

There is no need to modify the `NOTICE.TXT` in the project root, that build should just modify the one that goes into the tar properly and leave a clean index.

**Comment by ph** [comment]
I think the fix would be to add that file to our `./gitignore` I presume it will be still generated when we build the artifact.

**Comment by original-brownbear** [comment]
@ph can't we just generate that file to `build` instead and then move to the tar? That would be much cleaner than an ever more complicated `.gitignore` right?

**Comment by ph** [comment]
@original-brownbear We could but that would require more work on our build process, We don't have an intermediate step that generates an uncompressed LS artificat in `build/`, we just take what is needed from the current structure and generate a on the fly zip (or tar).
 https://github.com/elastic/logstash/blob/master/rakelib/artifacts.rake#L12

We have plan to move to gradle to handle theses steps, but adding `NOTICE.TXT` to the ignore list is probably the easiest way to make we don't corrupt the index.

**Comment by original-brownbear** [comment]
@ph right with the Gradle move that makes sense for now :)

**Comment by original-brownbear** [comment]
fixed in https://github.com/elastic/logstash/pull/7307
