### ISSUE TITLE
[proposal] Strict Schema For Metrics

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#7155]
Related issues:

https://github.com/elastic/logstash/issues/7227

We have a lot of test failures of the form `https://github.com/elastic/logstash/issues/7154`, we also can easily have errors when writing code due to typos in metric names. 

I think that we should revisit our metrics API and change it to make it more like our stats API where a metric must be first declared, then used.

Additionally, we have metrics scattered about all over the code. I also propose that we centralize metrics in 2 separate objects `GlobalMetric`, `PipelineMetric`, and `PluginMetric`. Plugin metric would still allow freeform metrics to be added.

I propose that when we do this refactor we try and define our metrics in only three places:

1. At Agent start (all global metrics)
2. At pipeline start (all metrics under the pipeline namespace)
3. At plugin register

These would all be done by convention. So, the current way of doing metrics involves code like:

```
class Pipeline
  def do_thing
    @metric.increment(:thing_happened, 1)
  end
end
```

would turn into

```
class Pipeline
  def initialize(metrics)
    @pipeline_metrics = PipelineMetrics.new(metrics)
  end

  def do_thing
  end
end

class PipelineMetrics
  def initialize(metrics, pipeline)
    setup_metrics(pipeline)
  end

  def setup_metrics
    @thing_happened_metric = metrics.declare(:stats, :pipelines, pipeline.id, :thing_happened)
  end

  def thing_happened
    @thing_happened_metric.increment(1)
  end
end
```

The nice thing about adding the extra class is that we can centralize the instantiation of metrics and avoid the problem of tests checking for metrics before whatever weird pipeline behavior, like a codec starting, happens. Querying for, for instance, the `queue_push_duration` metric, right now requires an input to have been started before it exists. This fixes that.

**Comment by ph** [comment]
I am all + 1 for that but I think we should use the same contract even with plugin author that they need to have declared their metric before they can use it. Also this is a good moment to javafy theses classes.


Concerning the tests, I think we should evaluate using the `json-schema` to make better assert on the results.

**Comment by ph** [comment]
@andrewvc I think we might also need to come up with a metric observer to collect from other parts of Logstash like the `read_cilent/write_client`, we monitor the time spend on pushing to the queue. 

Or we extract that time from the instrumented client and make it a concerns of the pipeline?

**Comment by andrewvc** [comment]
I like the idea of observers @ph! We should definitely not have the duplication we have in the read /  write client.

I don't think they should be everywhere, but in situations like that, they should be used.

**Comment by andrewvc** [comment]
BTW, +1 to JSON schema.

I don't know if we have the time to make the enforcement of declaration happen in time for 6.0.

I think it'd be a huge step forward to do that as a convention however.

**Comment by ph** [comment]
@andrewvc but I think we should takle it that way:

- Javafy the metric classes, theses are pretty well tested. (We will get benefit from the execution path)
- Extract into the 3 metrics wrapper.

**Comment by jsvd** [comment]
+1 to everything. also, while transforming everything to Java, are we getting rid of the usage of Symbols? Ruby's dynamic types and symbols always makes me trip, ending up with things like:

```
[2] pry(#<LogStash::Api::Commands::Node>)> pipeline_ids
=> ["main", :main]
```

**Comment by andrewvc** [comment]
After discussing implementation with @ph and @jsvd we will take the following actions:

1. Not implement this functionality as observers for v1
2. Create java interfaces for the `AgentMetrics`, and `PipelineMetrics#new(AgentMetrics)` interfaces as well as for `Gauge`, `Metric`, and `TimedExecution`.
3. `TimedExecution` will be returned directly from `PipelineMetrics` rather than using a method name like `startTimer` because a fast implementation around that would be too tricky.

**Comment by andrewvc** [comment]
These changes should also fix issues like: https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-intake/672/console

**Comment by andrewvc** [comment]
Closing this in favor of #7788
