### ISSUE TITLE
Add info around upgrading Logstash with PQs enabled

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#7158]
We should add verbiage in the "[Upgrading Logstash](https://www.elastic.co/guide/en/logstash/current/upgrading-logstash.html)" section to include info on upgrading with PQs enabled. Let's target 5.5 for this since PQs went GA in 5.4. A small note should suffice:

"Upgrading Logstash with persistent queues enabled is supported. The persistent queue directory is self-contained and can be read from a new Logstash instance running the same pipeline. You can safely shut down the original LS instance, spin up a new instance, and point to the same queue directory. You can also use a mounted drive to make this workflow easier."

**Comment by dedemorton** [comment]
Closed via #7188
