### ISSUE TITLE
Proposal: Use the pipeline configuration files to separate contexts

### ISSUE THREAD

**Issue by endersonmaia** [elastic/logstash#7165]
I'm aware of the work on multiple pipelines (#6525) for logstash 6.0.0, that solves this proposal.

But I suppose that with a simpler implementation, we could get somewhere between a complex configuration full of conditionals and the more elegant multiple pipelines solution with this proposal.

If we could make logstash consider the configuration file as a context for the input, filter and output, we could separate de logic and avoid conditionals by splitting configuration in different files.

`/opt/logstash/pipeline.conf` - should have all configuration in one place

Using separate files for different contexts:

* `/opt/logstash/pipeline.d/syslog-to-elasticsearch.conf`
* `/opt/logstash/pipeline.d/jdbc-to-rabbitmq.conf`

These files would have the input, filter and output isolated from each other.

As I said before, the multiple pipelines would solve it, but  today I'm solving it with many logstash instances in favor of complex conditional logic, but the memory consumption is not paying and I'm considering get back to a complex configuration for better resources utilization. And I don't know if waiting for logstash 6.0.0 is a solution.

I have little Ruby/Java knowledge, so I don't think I can debate implementation details, but if the maintainers think it's worth the work, I could elaborate more on this matter.

**Comment by jsvd** [comment]
@endersonmaia if I understand correctly, you'd like to have parallel "containers" of (I -> F -> O) flows within a single pipeline?

This is not possible at the moment, and would require a more complex rework of how logstash pipelines work, even more that what multiple pipelines is going to be.

There is, however, work being done by @andrewvc and @ph to construct a new execution model of pipelines that will essentially be much more flexible, allowing graph-like flows. This kind of capability does not currently have an ETA.

**Comment by endersonmaia** [comment]
@jsvd isn't there a way logstash could expose information about the configuration file context to the (I -> F -> O) and then use this to "automagically" add an `if-statement` around the each I, F O block ?

**Comment by endersonmaia** [comment]
And what about logstash 6 with multiple-pipeline support, is there an ETA already ?

**Comment by jsvd** [comment]
> @jsvd isn't there a way logstash could expose information about the configuration file context to the (I -> F -> O) and then use this to "automagically" add an if-statement around the each I, F O block ?

It's possible to explore this idea to inject context tags+conditionals. I foresee some problems in this abstraction leaking and events surprisingly showing up where they're not supposed to..

At this point, what you really want is multiple pipelines, the overhead between your proposal and MP shouldn't be significant, and MP may even perform better by allowing you to tune pipeline settings for each pipeline

**Comment by endersonmaia** [comment]
> It's possible to explore this idea to inject context tags+conditionals. I foresee some problems in this abstraction leaking and events surprisingly showing up where they're not supposed to..

Maybe some global configuration to enable pipeline context per file, and if enabled, each file would only see what's inside it, else it works as today.

> At this point, what you really want is multiple pipelines, the overhead between your proposal and MP shouldn't be significant, and MP may even perform better by allowing you to tune pipeline settings for each pipeline

As I said, I know MP solves it, but I don't know if I can wait for its release. :)

**Comment by jsvd** [comment]
I understand, but introducing such a strategy on a minor release when we have MP (that would replace that strategy) on the horizon is going to be unlikely as we have a small team. Also, the window for new features on 5.5.0 is about to close, and we're not sure if there will be another minor before 6.0
