### ISSUE TITLE
[test failure] Failed spec in hot threads API

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#7174]
seen in: https://travis-ci.org/elastic/logstash/jobs/234166103

Failures:

   `1) LogStash::Api::Modules::Node#hot threads When asking for human output and threads count should return information for <= # requested threads
     Failure/Error: get "/hot_threads?human=t&threads=2"
     NoMethodError:
       undefined method 'each' for nil:NilClass
     # ./logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb:22:in 'to_s'
     # ./logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb:19:in 'to_s'
     # ./logstash-core/lib/logstash/api/app_helpers.rb:36:in 'respond_with'
     # ./logstash-core/lib/logstash/api/modules/node.rb:20:in 'HEAD /hot_threads'
`

It appears that more resiliency is required in HotThreadsReporter when empty stack traces are encountered.

**Comment by jsvd** [comment]
another instance https://logstash-ci.elastic.co/job/elastic+logstash+5.x+dockerubuntu-periodic/2185/console
