### ISSUE TITLE
ruby syntax error in acceptance test

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7181]
the acceptance test for the generate cli command has a syntax error: `GENERATE_TYPES.each |type| do` : code here https://github.com/elastic/logstash/blob/master/qa/acceptance/spec/shared_examples/cli/logstash-plugin/generate.rb#L18

this is causing acceptance tests to fail on [5.x](https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-acceptance/label=metal,suite=redhat/167/console) and [master](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=debian/276/console)

**Comment by ph** [comment]
fixed by #7182
