### ISSUE TITLE
Logstash: How to pass value dynamically to timeout in elapsed filter

### ISSUE THREAD

**Issue by AnuroopSamrat** [elastic/logstash#7209]
-> How to pass value dynamically to timeout in elapsed filter.
-> i am trying to do using below configuration.
-> Here i am trying to get the value from db using jdbc plugin and 
->assigning that value to a global variable (@@threshold) so that value 
value can be used in continuos streaming.
->Assigning global variable @@threshold to timeout in elapsed filter is 
not accepting vairables.

input {
stdin{}
beats {
port => 5022
}

jdbc {
jdbc_driver_library => "mysql-connector-java-5.1.37.jar"
jdbc_driver_class => "com.mysql.jdbc.Driver"
jdbc_connection_string => "jdbc:mysql://localhost:3306/db"
jdbc_user => "root"
jdbc_password => "pwd"
parameters => { "id" => 3 }
schedule => "* * * * *"
statement => "SELECT * from test where id = :id"
}
}

filter {

grok {
match => [ "message", "%{DATEPATTERN2:startlogdate}%{SPACE}%{GREEDYDATA:MetricName}%{SPACE}START%{GREEDYDATA:space}%{DATEPATTERN2:salertdate}%{GREEDYDATA:alerttype}" ]
add_tag => [ "start" ]

}
grok {
match => [ "message", "%{DATEPATTERN2:endlogdate}%{SPACE}%{GREEDYDATA:MetricName}%{SPACE}END%{GREEDYDATA:space}%{DATEPATTERN2:ealertdate}%{GREEDYDATA:alerttype}" ]
add_tag => [ "end" ]
}

ruby # Here in ruby i am initializing a global variable 
{ 
init => "@@threshold =1" #setting @@threshold to '1'
code =>"if event['id'] != nil
@@threshold = event['value'] #overriding with value from db
else
end"	
}

mutate {
    convert => {"@@threshold" => "integer"} # changing type to inetger
}
elapsed {
periodic_flush => true
start_tag => "start"
end_tag => "end"
unique_id_field => "MetricName"
new_event_on_match => false
timeout => "@@threshold" #assigning global variable to timeout
}

}

output {
stdout {
codec => "rubydebug"
}
}

can anyone give a solution on this.

**Comment by andrewvc** [comment]
I'm going to close this due to it not being an actual issue. We appreciate your use of Logstash, but github issues are only for actual bugs.

Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
