### ISSUE TITLE
[test failure: 5.0, 5.1, 5.2, 5.3] bundler fails in acceptance tests

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7232]
The same bundler errors seems to repetitively reoccur inn acceptance tests in 5.0, 5.2 and 5.3. Not sure if these are transient errors but the pattern seems to indicate it's not.

https://logstash-ci.elastic.co/job/elastic+logstash+5.0+multijob-acceptance/label=metal,suite=debian/193/console
https://logstash-ci.elastic.co/job/elastic+logstash+5.0+multijob-acceptance/label=metal,suite=redhat/193/console
https://logstash-ci.elastic.co/job/elastic+logstash+5.2+multijob-acceptance/label=metal,suite=redhat/10/console
https://logstash-ci.elastic.co/job/elastic+logstash+5.2+multijob-acceptance/label=metal,suite=debian/10/console
https://logstash-ci.elastic.co/job/elastic+logstash+5.3+multijob-acceptance/label=metal,suite=redhat/30/console
https://logstash-ci.elastic.co/job/elastic+logstash+5.3+multijob-acceptance/label=metal,suite=debian/30/console

**Comment by colinsurprenant** [comment]
also found 5.1

https://logstash-ci.elastic.co/job/elastic+logstash+5.1+multijob-os-compatibility/os=ubuntu/56/console

**Comment by jakelandis** [comment]
Closing since any CI builds prior to 5.5 is only as-needed basis.
