### ISSUE TITLE
logstash-plugin list Gem::LoadError: You have already activated jar-dependencies 0.3.11, but your Gemfile requires jar-dependencies 0.3.10

### ISSUE THREAD

**Issue by dariusj18** [elastic/logstash#7237]
- Version: 5.4.0
- Operating System: CentOS 7.3.1611
- Steps to Reproduce: sudo /usr/share/logstash/bin/logstash-plugin list

> Gem::LoadError: You have already activated jar-dependencies 0.3.11, but your Gemfile requires jar-dependencies 0.3.10. Prepending `bundle exec` to your command may solve this.
>     setup at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
>      each at org/jruby/RubyArray.java:1613
>      each at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
>     setup at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
>     setup at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
>    setup! at /usr/share/logstash/lib/bootstrap/bundler.rb:64
>   execute at /usr/share/logstash/lib/pluginmanager/list.rb:17
>       run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
>   execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
>       run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
>       run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
>    (root) at /usr/share/logstash/lib/pluginmanager/main.rb:48

**Comment by jsvd** [comment]
are you still seeing this with more recent versions of logstash?

**Comment by dariusj18** [comment]
I have not upgraded.
