### ISSUE TITLE
grok logs with repeated fields

### ISSUE THREAD

**Issue by kiranmai444** [elastic/logstash#7249]
I want to grok logs with repeated fields like

[2017-05-29 02:17:18] INFO – [ActivityServiceRest:89] – [{“callId”:”kjwefkjweqkfb”},{“callId”:”nwekgwnkqgkqr”},{“callId”:”ohjiwnwbnwbrk”}]

I want to capture all the callId's into a field called call_Id

where the number of times callId appears is dynamic. Can someone please help.

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
