### ISSUE TITLE
Incorrect permissions after rpm install (CentOS)

### ISSUE THREAD

**Issue by LionelCons** [elastic/logstash#7250]
After having installed the `logstash-5.4.0.rpm` on a CentOS 7 machine, the permissions under `/usr/share/logstash` are incorrect.

"rpm -V logstash" reports many warnings like:
`.....UG.. /usr/share/logstash`

This comes from the following post-install snippet:
`chown -R logstash:logstash /usr/share/logstash`

Is there any reason why the Logstash software is not owned by root:root like all the other pieces of software on CentOS?

Already posted as https://discuss.elastic.co/t/incorrect-permissions-after-rpm-install-centos/86607 but with no reply on the forum...

**Comment by LionelCons** [comment]
FWIW, the problem is still present in the `logstash-5.4.3-1.noarch` rpm.

**Comment by LionelCons** [comment]
... and with `logstash-5.5.1-1.noarch`.

**Comment by jakelandis** [comment]
In general, _nothing specific to Logstash_, it good (common) practice to run services under a named user with limited privileges, not root. _(this includes the directories/files needed to run the service)_

If there is a mix of permissions (e.g. some root, some not root) w/r/t Logstash artifacts, or the installation does not work, we can investigate more.  However, if the issue here is that we are using a named user instead of root, that is by design, not a bug.

**Comment by LionelCons** [comment]
@jakelandis Although it is common practice to run under a named user, it is not common practice to have the _software files_ owned by this user. There is no need for this and it is a security risk since a breakin through this service would allow the attacker to modify software files.

I have just checked on a CentOS 7 system and, except log/cache/run files, all software files are owned by `root` even though:
- `httpd` runs with the `apache` user
- `sendmail` runs with the `smmsp` user
- `dbus-daemon` runs with the `dbus` user
- `chronyd` runs with the `chrony` user
- `nscd` runs with the `nscd` user
- ...

**Comment by LionelCons** [comment]
@jakelandis How would these plugins be installed? If we assume that it is by `root` running the `logstash-plugin` command then we don't need special permissions...

**Comment by joshbressers** [comment]
I'm going to dupe this into https://github.com/elastic/logstash/issues/10257, this is part of a bigger problem for RPM verify to come back clean.
