### ISSUE TITLE
JRuby 9k - Default plugins status

### ISSUE THREAD

**Issue by ph** [elastic/logstash#7252]
Plugin | Travis | 5.x/master | JRuby 9K | Issue
------ | ------ | ---------- | -------- | -----
[c-cef](https://github.com/logstash-plugins/logstash-codec-cef) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-cef.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-cef) | PASS | PASS |
[c-collectd](https://github.com/logstash-plugins/logstash-codec-collectd) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-collectd.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-collectd) | PASS | PASS |
[c-dots](https://github.com/logstash-plugins/logstash-codec-dots) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-dots.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-dots) | PASS | PASS |
[c-edn](https://github.com/logstash-plugins/logstash-codec-edn) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-edn.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-edn) | PASS | PASS
[c-edn_lines](https://github.com/logstash-plugins/logstash-codec-edn_lines) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-edn_lines.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-edn_lines) | PASS | PASS
[c-es_bulk](https://github.com/logstash-plugins/logstash-codec-es_bulk) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-es_bulk.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-es_bulk) | PASS| PASS
[c-fluent](https://github.com/logstash-plugins/logstash-codec-fluent) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-fluent.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-fluent) | PASS | PASS |
[c-graphite](https://github.com/logstash-plugins/logstash-codec-graphite) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-graphite.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-graphite) | PASS | PASS
[c-json](https://github.com/logstash-plugins/logstash-codec-json) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-json.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-json) | PASS | PASS |
[c-json_lines](https://github.com/logstash-plugins/logstash-codec-json_lines) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-json_lines.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-json_lines) | PASS | PASS |
[c-line](https://github.com/logstash-plugins/logstash-codec-line) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-line.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-line) | PASS | PASS |
[c-msgpack](https://github.com/logstash-plugins/logstash-codec-msgpack) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-msgpack.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-msgpack) | PASS | PASS |
[c-multiline](https://github.com/logstash-plugins/logstash-codec-multiline) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-multiline.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-multiline) | PASS | PASS
[c-netflow](https://github.com/logstash-plugins/logstash-codec-netflow) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-netflow.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-netflow) | PASS | PASS |
[c-plain](https://github.com/logstash-plugins/logstash-codec-plain) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-plain.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-plain) | PASS | PASS
[c-rubydebug](https://github.com/logstash-plugins/logstash-codec-rubydebug) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-rubydebug.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-rubydebug) | PASS | PASS |
[f-clone](https://github.com/logstash-plugins/logstash-filter-clone) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-clone.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-clone) | PASS | PASS |
[f-csv](https://github.com/logstash-plugins/logstash-filter-csv) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-csv.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-csv) | PASS | PASS |
[f-date](https://github.com/logstash-plugins/logstash-filter-date) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-date.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-date) | PASS | PASS |
[f-dissect](https://github.com/logstash-plugins/logstash-filter-dissect) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-dissect.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-dissect) | PASS | PASS
[f-dns](https://github.com/logstash-plugins/logstash-filter-dns) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-dns.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-dns) | PASS | PASS |
[f-drop](https://github.com/logstash-plugins/logstash-filter-drop) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-drop.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-drop) | PASS | PASS |
[f-fingerprint](https://github.com/logstash-plugins/logstash-filter-fingerprint) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-fingerprint.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-fingerprint) | PASS | PASS |
[f-geoip](https://github.com/logstash-plugins/logstash-filter-geoip) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-geoip.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-geoip) | PASS | PASS |
[f-grok](https://github.com/logstash-plugins/logstash-filter-grok) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-grok.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-grok) | PASS | PASS |
[f-json](https://github.com/logstash-plugins/logstash-filter-json) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-json.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-json) | PASS | PASS |
[f-kv](https://github.com/logstash-plugins/logstash-filter-kv) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-kv.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-kv) | PASS | PASS |
[f-metrics](https://github.com/logstash-plugins/logstash-filter-metrics) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-metrics.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-metrics) | PASS | PASS |
[f-mutate](https://github.com/logstash-plugins/logstash-filter-mutate) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-mutate.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-mutate) | PASS | PASS |
[f-ruby](https://github.com/logstash-plugins/logstash-filter-ruby) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-ruby.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-ruby) | PASS | PASS |
[f-sleep](https://github.com/logstash-plugins/logstash-filter-sleep) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-sleep.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-sleep) | PASS | PASS |
[f-split](https://github.com/logstash-plugins/logstash-filter-split) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-split.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-split) | PASS | PASS |
[f-syslog_pri](https://github.com/logstash-plugins/logstash-filter-syslog_pri) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-syslog_pri.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-syslog_pri) | PASS | PASS |
[f-throttle](https://github.com/logstash-plugins/logstash-filter-throttle) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-throttle.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-throttle) | PASS | PASS |
[f-urldecode](https://github.com/logstash-plugins/logstash-filter-urldecode) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-urldecode.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-urldecode) | PASS | PASS |
[f-useragent](https://github.com/logstash-plugins/logstash-filter-useragent) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-useragent.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-useragent) | PASS | PASS |
[f-uuid](https://github.com/logstash-plugins/logstash-filter-uuid) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-uuid.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-uuid) | PASS | PASS |
[f-xml](https://github.com/logstash-plugins/logstash-filter-xml) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-xml.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-xml) | PASS | PASS
[i-beats](https://github.com/logstash-plugins/logstash-input-beats) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-beats.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-beats) | PASS | PASS |
[i-couchdb_changes](https://github.com/logstash-plugins/logstash-input-couchdb_changes) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-couchdb_changes.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-couchdb_changes) | PASS | PASS |
[i-elasticsearch](https://github.com/logstash-plugins/logstash-input-elasticsearch) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-elasticsearch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-elasticsearch) | PASS | PASS |
[i-exec](https://github.com/logstash-plugins/logstash-input-exec) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-exec.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-exec) | PASS | PASS |
[i-file](https://github.com/logstash-plugins/logstash-input-file) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-file.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-file) | PASS | PASS |
[i-ganglia](https://github.com/logstash-plugins/logstash-input-ganglia) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-ganglia.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-ganglia) | PASS | PASS |
[i-gelf](https://github.com/logstash-plugins/logstash-input-gelf) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-gelf.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-gelf) | PASS | PASS |
[i-generator](https://github.com/logstash-plugins/logstash-input-generator) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-generator.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-generator) | PASS | PASS |
[i-graphite](https://github.com/logstash-plugins/logstash-input-graphite) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-graphite.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-graphite) | PASS | FAILED - ([1](https://travis-ci.org/logstash-plugins/logstash-input-graphite/jobs/236450664)) | [GH issue](https://github.com/logstash-plugins/logstash-input-graphite/issues/12)
[i-heartbeat](https://github.com/logstash-plugins/logstash-input-heartbeat) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-heartbeat.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-heartbeat) | PASS | PASS |
[i-http](https://github.com/logstash-plugins/logstash-input-http) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-http.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-http) | PASS | PASS |
[i-http_poller](https://github.com/logstash-plugins/logstash-input-http_poller) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-http_poller.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-http_poller) | PASS | PASS |
[i-imap](https://github.com/logstash-plugins/logstash-input-imap) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-imap.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-imap) | PASS | PASS |
[i-irc](https://github.com/logstash-plugins/logstash-input-irc) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-irc.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-irc) | PASS | PASS |
[i-jdbc](https://github.com/logstash-plugins/logstash-input-jdbc) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-jdbc.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-jdbc) | PASS | PASS |
[i-kafka](https://github.com/logstash-plugins/logstash-input-kafka) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-kafka.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-kafka) | PASS | PASS |
[i-log4j](https://github.com/logstash-plugins/logstash-input-log4j) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-log4j.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-log4j) | PASS | PASS |
[i-lumberjack](https://github.com/logstash-plugins/logstash-input-lumberjack) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-lumberjack.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-lumberjack) | PASS | PASS |
[i-pipe](https://github.com/logstash-plugins/logstash-input-pipe) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-pipe.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-pipe) | PASS | PASS |
[i-rabbitmq](https://github.com/logstash-plugins/logstash-input-rabbitmq) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-rabbitmq.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-rabbitmq) | PASS | PASS |
[i-redis](https://github.com/logstash-plugins/logstash-input-redis) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-redis.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-redis) | PASS | PASS |
[i-s3](https://github.com/logstash-plugins/logstash-input-s3) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-s3.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-s3) | PASS | PASS |
[i-snmptrap](https://github.com/logstash-plugins/logstash-input-snmptrap) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-snmptrap.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-snmptrap) | PASS | PASS |
[i-sqs](https://github.com/logstash-plugins/logstash-input-sqs) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-sqs.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-sqs) | PASS | PASS |
[i-stdin](https://github.com/logstash-plugins/logstash-input-stdin) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-stdin.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-stdin) | PASS | PASS |
[i-syslog](https://github.com/logstash-plugins/logstash-input-syslog) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-syslog.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-syslog) | PASS | PASS |
[i-tcp](https://github.com/logstash-plugins/logstash-input-tcp) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-tcp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-tcp) | PASS | PASS |
[i-twitter](https://github.com/logstash-plugins/logstash-input-twitter) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-twitter.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-twitter) | PASS | PASS |
[i-udp](https://github.com/logstash-plugins/logstash-input-udp) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-udp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-udp) | PASS | PASS |
[i-unix](https://github.com/logstash-plugins/logstash-input-unix) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-unix.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-unix) | PASS | PASS |
[i-xmpp](https://github.com/logstash-plugins/logstash-input-xmpp) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-xmpp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-xmpp) | PASS | PASS |
[o-cloudwatch](https://github.com/logstash-plugins/logstash-output-cloudwatch) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-cloudwatch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-cloudwatch) | PASS | PASS |
[o-csv](https://github.com/logstash-plugins/logstash-output-csv) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-csv.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-csv) | PASS | PASS |
[o-elasticsearch](https://github.com/logstash-plugins/logstash-output-elasticsearch) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch) | FAILED - ([1](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch/jobs/236486708)) | PASS |
[o-file](https://github.com/logstash-plugins/logstash-output-file) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-file.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-file) | PASS | PASS |
[o-graphite](https://github.com/logstash-plugins/logstash-output-graphite) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-graphite.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-graphite) | PASS | PASS |
[o-http](https://github.com/logstash-plugins/logstash-output-http) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-http.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-http) | PASS | PASS |
[o-irc](https://github.com/logstash-plugins/logstash-output-irc) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-irc.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-irc) | PASS | PASS |
[o-kafka](https://github.com/logstash-plugins/logstash-output-kafka) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-kafka.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-kafka) | PASS | PASS |
[o-nagios](https://github.com/logstash-plugins/logstash-output-nagios) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-nagios.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-nagios) | PASS | PASS |
[o-null](https://github.com/logstash-plugins/logstash-output-null) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-null.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-null) | PASS | PASS |
[o-pagerduty](https://github.com/logstash-plugins/logstash-output-pagerduty) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-pagerduty.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-pagerduty) | PASS | PASS |
[o-pipe](https://github.com/logstash-plugins/logstash-output-pipe) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-pipe.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-pipe) | PASS | PASS |
[o-rabbitmq](https://github.com/logstash-plugins/logstash-output-rabbitmq) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-rabbitmq.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-rabbitmq) | PASS | PASS |
[o-redis](https://github.com/logstash-plugins/logstash-output-redis) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-redis.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-redis) |PASS | PASS |
[o-s3](https://github.com/logstash-plugins/logstash-output-s3) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-s3.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-s3) | PASS | PASS |
[o-sns](https://github.com/logstash-plugins/logstash-output-sns) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-sns.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-sns) | PASS | PASS |
[o-sqs](https://github.com/logstash-plugins/logstash-output-sqs) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-sqs.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-sqs) | PASS | PASS |
[o-statsd](https://github.com/logstash-plugins/logstash-output-statsd) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-statsd.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-statsd) | PASS | PASS |
[o-stdout](https://github.com/logstash-plugins/logstash-output-stdout) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-stdout.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-stdout) | PASS | PASS |
[o-tcp](https://github.com/logstash-plugins/logstash-output-tcp) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-tcp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-tcp) | PASS | PASS |
[o-udp](https://github.com/logstash-plugins/logstash-output-udp) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-udp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-udp) | PASS | PASS |
[o-webhdfs](https://github.com/logstash-plugins/logstash-output-webhdfs) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-webhdfs.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-webhdfs) | PASS | PASS |
[o-xmpp](https://github.com/logstash-plugins/logstash-output-xmpp) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-xmpp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-xmpp) | PASS | PASS |

**Comment by ph** [comment]
The build scripts for the input kafka and the dissect filter where missing the execution flags, I've pushed a fix for that.

**Comment by colinsurprenant** [comment]
the is awesome work, thanks.

**Comment by ph** [comment]
This tables is now updated with the latest plugins status.

**Comment by ph** [comment]
Only remaining plugin is graphite. I haven't taken a look it, I think @colinsurprenant you were still trying to take a look?

**Comment by kares** [comment]
sounds like the work here has been complete, for some time
