### ISSUE TITLE
bin/logstash --path.plugins is broken.

### ISSUE THREAD

**Issue by wainersm** [elastic/logstash#7267]
I tried to set path to a plugin generated with ```logstash-plugin generate``` but passing ```--path.plugins``` to ```logstash``` raises an error:
```
vagrant@packer-virtualbox-iso-1490878746:~$ sudo /usr/share/logstash/bin/logstash --path.plugins ${HOME}/logstash-input-qatest-generated/lib
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
NameError: `@path.plugins' is not allowable as an instance variable name
   instance_variable_get at org/jruby/RubyKernel.java:2249
                     get at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:21
                 _append at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:41
  append_to_path.plugins at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/attribute/declaration.rb:41
                    take at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:57
           parse_options at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:32
                   parse at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:52
                     run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:66
                     run at /usr/share/logstash/logstash-core/lib/logstash/runner.rb:204
                     run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
                  (root) at /usr/share/logstash/lib/bootstrap/environment.rb:71
vagrant@packer-virtualbox-iso-1490878746:~$ sudo /usr/share/logstash/bin/logstash --version
logstash 6.0.0-alpha2
```
**ps:** I used the Ubuntu 12.04 vagrant box setup to acceptance tests. Same error happens on debian-8 box.

**Comment by wainersm** [comment]
I've found the problem, working in a fix.

**Comment by wainersm** [comment]
I made a few simple manual tests and apparently PR #7276 fixes the issue. But I'd like someone else to give it a try or suggest how could be made an automated test.

**Comment by untergeek** [comment]
@wainersm Thanks for finding this and putting a fix together.  We have been discussing removing the `--path.plugins` flag altogether for some time.  We'll take you fix under consideration, but we may ignore it and remove the feature altogether.  Building plugins as gems, and installing using the `logstash-plugin` command is still the preferred way to add new plugins.

**Comment by untergeek** [comment]
@wainersm We've officially decided to mark this feature as deprecated for v5.5, and remove it altogether for 6.0.  Thanks for all you do to make Logstash better!

**Comment by wainersm** [comment]
Hi @untergeek ! Remove ```--path.plugins``` is the best thing. The option is confusing to use and results no clear.

However, the fix in PR #7276 is still valid for any multivalued option. So into the future if we decide to include this kind of option, It will need the fix applied. Unless the Clamp hack is replaced.

**Comment by untergeek** [comment]
#7276 is not used by _any_ options currently.  We do have a multivalued option coming soon, but it doesn't need any clamp hacks because we have a separate class that handles the multivalued options due to a need to pre-parse the values and populate `@settings` differently.

We can revisit #7276 if we ever need it, otherwise it's just added complexity right now.

**Comment by peterdolan** [comment]
Just curious here -- is there a preferred way to develop a plugin without rebuilding? It's somewhat tedious to constantly rebuild before testing in development and this option seems nice!
