### ISSUE TITLE
How to fix 'Error: incompatible types: List<IRubyObject> cannot be converted to List<Queueable>'

### ISSUE THREAD

**Issue by guyuqi** [elastic/logstash#7357]
Hi 
I'm a new comer and want to build the logstash on AArch64.
The jruby supports AArch64 since the version 9.1.6.0. 
So , I tried to update the jruby to 9.1.10.0 just like [pull 6713](https://github.com/elastic/logstash/pull/6713) does. 
But the issue is faced to me: 
```
rake bootstrap 
...
.........
/home/ent-user/logstash/logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedBatchExtLibrary.java:62: error: incompatible types: List<IRubyObject> cannot be converted to List<Queueable>
            this.batch = new Batch(((RubyArray)events).getList(), ((RubyArray)seqNums).getList(), ((JrubyAckedQueueExtLibrary.RubyAckedQueue)queue).getQueue());

....
........


```
- Version:  master 
- Operating System:  ubuntu 16.04
-JDK:  openjdk version "1.8.0_131"

Any suggestions?
Thanks a lot!

**Comment by original-brownbear** [comment]
@guyuqi JRuby 9k is not yet supported by Logstash. See https://github.com/elastic/logstash/pull/7349, still working on this, but getting closer :)
I think we can close here right?

**Comment by ph** [comment]
@guyuqi If you have time, I suggest you try the PR in #7349 that will help us find any other problems. I haven't seen the error you are describing in the PR, I will close this.
