### ISSUE TITLE
6.0.0-alpha2 slow startup times

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#7379]
- Version: 6.0.0-alpha2
- Operating System: Ubuntu 14.04.5
- Config File: https://gist.github.com/ceeeekay/933ade5e28ce96198d33e85073173112
- Authlog Pattern: https://gist.github.com/ceeeekay/163e3051b02d5bef1c64286e5ef07ea4
- Steps to Reproduce: Start up Logstash 6.0.0-alpha2 with a large config

Note: this was also occurring with 6.0.0-alpha1 but I've only just got around to reporting it.

I've attempted to narrow this down to a specific part of the config but I'm unable to do this.

Tests below are made using a modified and reduced config (see gist).

**5.4.1 - 12 second startup time**
```
# dpkg -l | grep logstash
ii  logstash                                              1:5.4.1-1 

# time sudo -u logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash --path.config /etc/logstash/enabled/
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
test

real	0m12.493s
user	0m37.547s
sys	0m0.737s
```

**6.0.0-alpha2 - 39 second startup time**
```
# dpkg -l | grep logstash
ii  logstash                                              1:6.0.0~alpha2-1 

# time sudo -u logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash --path.config /etc/logstash/enabled/
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
test

real	0m39.526s
user	1m21.297s
sys	0m0.903s
```

I've tried to keep the config to a minimum for this test, however the longer the config, the larger the difference in startup times between 5.4.1 and 6.0.0-alpha2. 

Doubling the size of the test config by duplicating it in the config directory increases the 6.0.0 startup time from 40 seconds to **5 minutes**, compared to 15 seconds for 5.4.1. The full dev config I'm running (2739 lines) takes over 12 minutes to start with 6.0.0, and only 16 seconds with 5.4.1.

**Comment by jsvd** [comment]
@ceeeekay thanks for the investigation on this, can you post a thread dump taken during those 12 minutes?

**Comment by andrewvc** [comment]
Thanks for the excellent report @ceeeekay . I just coded up #7408 which should fix this.

**Comment by ceeeekay** [comment]
@andrewvc @jsvd Thanks! Do you still need the thread dump? it's going to take me a day or so to get onto this.

**Comment by andrewvc** [comment]
@ceeeekay nope! In #7408 I was easily able to repro the problem. Nothing necessary :)

**Comment by ceeeekay** [comment]
Nice - thanks :)

**Comment by suyograo** [comment]
@ceeeekay thanks for reporting this!
