### ISSUE TITLE
Incorrect coerce function with duplicate capture keys in Grok patterns

### ISSUE THREAD

**Issue by micoq** [elastic/logstash#7383]
Hello,

I'm not sure if it's the right repository to post this issue since the grok library is included in Logstash.

On any version of Logstash, if you have two or more fields (or named captures) in a grok pattern with the same name and using a coerce function (like "int" or "float"), this function si not applied all the time (even if the function is the same in each field).

Here is the complete issue with a quick fix : https://github.com/jordansissel/ruby-grok/issues/29

**Comment by jsvd** [comment]
there seems to already be an issue open on the grok filter side: https://github.com/logstash-plugins/logstash-filter-grok/issues/119, closing this
