### ISSUE TITLE
review Queue notFull signalling 

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7399]
in light of #7380 and #7382 we should review the `Queue` class `notFull` signalling to make sure a deadlock cannot occur at queue full conditions similar to what we fixed at queue empty condition.

FYI @original-brownbear

**Comment by original-brownbear** [comment]
@colinsurprenant agreed, I guess we could try and replicate the test I added for the full queue case?

**Comment by original-brownbear** [comment]
closed via #7405
