### ISSUE TITLE
logstash filter duplicate events with same document id.

### ISSUE THREAD

**Issue by yuvarajanlga** [elastic/logstash#7414]
Hi ,

I am using sensu monitoring system to monitor our infrastructure. We are sending all sensu server logs to logstash and then to elasticsearch. We recently identified in the elasticsearch has 2 same event with same document id then i check the sensu server logs and i found two logs for the same events because we are using two handler (email and hipchat) hence i can see same log 2 times in the sensu server. is there any way to remove the duplicate log before to store it in elasticsearch ?

If some one guide me on how to do this in logstash it will be very helpful. 

FYI:-

Below is the event i pulled from elasticsearch and you can noticed the document is same and it store twice.

June 12th 2017, 11:42:34.707	client.name:***_SVRXG_*****  client.address:***** client.subscriptions:client:***_SVRXG_***** client.keepalives:false client.version:0.28.5 client.timestamp:1,493,713,043 check.type:metric check.command:/usr/lib/nagios/plugins/check_ping -H ***** -w 85,30% -c 100,40% check.standalone:true check.source:LGA_SVRXG_******* check.output_format:nagios_perfdata check.handlers:influxdb, email, hipchat check.contact:sysadmin

June 12th 2017, 11:42:34.707	client.name:***_SVRXG_*****  client.address:***** client.subscriptions:client:***_SVRXG_***** client.keepalives:false client.version:0.28.5 client.timestamp:1,493,713,043 check.type:metric check.command:/usr/lib/nagios/plugins/check_ping -H ***** -w 85,30% -c 100,40% check.standalone:true check.source:LGA_SVRXG_******* check.output_format:nagios_perfdata check.handlers:influxdb, email, hipchat check.contact:sysadmin

**Comment by jsvd** [comment]
can you post your logstash pipeline?

**Comment by yuvarajanlga** [comment]
HI Jsvd,

I am able to resolve this issues  by following this link

https://www.elastic.co/blog/logstash-lessons-handling-duplicates

thank you.

**Comment by jmreymond** [comment]
the cause is kafka:
[https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/](url)
