### ISSUE TITLE
Rake Bootstrap Should Refresh Gemfile and Gemfile.jruby-1.9.lock Unconditionally

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7416]
I think I made a mistake when implementing the logic around `Gemfile.template` that allows for a clean git index across all build stages in #6985.

I made the logic only create the `Gemfile` in case it doesn't yet exist. This is wrong I think because whenever I change branches (like to `5.x`) or add/remove a dependency I need to manually delete the existing `Gemfile` and `Gemfile.jruby-1.9.lock` before running `rake bootstrap` (or some other task that has `bootstrap` as a dependency) to get a correct `Gemfile`.

I think simply turning:

(`bundler.rb`)

```ruby
      # create Gemfile from template iff it does not exist
      unless ::File.exists?(Environment::GEMFILE_PATH)
        FileUtils.copy(
          ::File.join(Environment::LOGSTASH_HOME, "Gemfile.template"), Environment::GEMFILE_PATH
        )
      end
```

into:

```ruby
      # create Gemfile from template
        FileUtils.cp_r(
          ::File.join(Environment::LOGSTASH_HOME, "Gemfile.template"), Environment::GEMFILE_PATH,
:remove_destination => true
        )
```

should fix this.

**Comment by jakelandis** [comment]
@original-brownbear - can this be closed now that we have the ability to bootstrap via Gradle ?

**Comment by original-brownbear** [comment]
@jakelandis oh yea, my bad for forgetting this one :)
