### ISSUE TITLE
documentation of pipeline.batch.delay is not correct

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7418]
Currently the [documentation of the batch delay setting](https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html) says:

>  When creating pipeline event batches, how long in milliseconds to wait before dispatching an undersized batch to filters and workers.

This suggests that, when a batch is being populated, it will be emitted if it either gets full or 5ms (default batch delay) passes.

This isn't totally accurate, as this delay is measured [during the pop operation of the queue for each event](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb#L204-L211):

```ruby
      def read_next
        @size.times do |t|
          event = @queue.poll(@wait)
          return if event.nil? # queue poll timed out

          @originals[event] = true
        end
      end
```

This means that even with a default batch delay of 5ms and batch size of 125 events, if an event arrives every 4 ms, it will take 500 miliseconds to generate a full batch, instead of cutting off the batch after 2 events.

With this in mind I think the documentation should become something like:

> When creating pipeline event batches, how long in milliseconds to wait for each event before dispatching an undersized batch to pipeline workers.

**Comment by dedemorton** [comment]
Closed via https://github.com/elastic/logstash/pull/8192
