### ISSUE TITLE
We're still referencing JRuby 1.7 in 2 Gradle Build Files

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7421]
Two small issues here:

1. The `build.gradle` for `logstash-core` as well as `logstash-core-benchmarks` both reference JRuby `1.7.x`
2. The Jruby version is duplicated between both Gradle files and differs in the patch version.

Seems to have no functional impact but should be cleaned up imo.

**Comment by ph** [comment]
I will clean them up

**Comment by jakelandis** [comment]
The main README doc also references 1.7.x  _(I can log a new issue if you like)_

**Comment by ph** [comment]
@jakelandis Thanks for finding that, I've created https://github.com/elastic/logstash/pull/7426 to fix it.
