### ISSUE TITLE
Feature Request: Plugin for lookup table

### ISSUE THREAD

**Issue by robomotic** [elastic/logstash#7432]
Hello there,
I was looking for a plugin that could do a basic whitelist/black list filtering action on a field.
Example use cases:

- filter known bad domains
- filter known bad hashes
- filter known bad commands

The list could be a simple plain file or a bloom filter (to sacrifice space vs accuracy).

A more generic approach could be to allow a filtering action based on a RESTFUL call but of course that will introduce latency in the filter.

Some food for thoughts.

**Comment by acchen97** [comment]
@robomotic can you take a look at the [Transforming Data docs](https://www.elastic.co/guide/en/logstash/current/lookup-enrichment.html) and see if the options work for you? The translate, jdbc_streaming, and elasticsearch filters could be good options.

If you're looking for a REST lookup, would this [REST filter](https://github.com/lucashenning/logstash-filter-rest) be helpful?

**Comment by robomotic** [comment]
@acchen97 that is all I needed , not sure how I couldn't find it before!
