### ISSUE TITLE
Missing require? uninitialized constant LogStash::Util::EnvironmentVariables

### ISSUE THREAD

**Issue by ph** [elastic/logstash#7449]
I've taken a look at the CI suite, I believe the error is coming from PR https://github.com/elastic/logstash/pull/7411

Job: https://logstash-ci.elastic.co/job/elastic+logstash+5.4+multijob-intake/57/console

```
NameError: uninitialized constant LogStash::Util::EnvironmentVariables
/var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-intake/logstash-core/lib/logstash/config/mixin.rb:184:in `DSL'
/var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-intake/logstash-core/lib/logstash/config/mixin.rb:182:in `Mixin'
/var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-intake/logstash-core/lib/logstash/config/mixin.rb:35:in `(root)'
```

**Comment by ph** [comment]
@original-brownbear Could you take a look?

**Comment by original-brownbear** [comment]
@ph sure looking into it :)

**Comment by suyograo** [comment]
@ph @original-brownbear will this affect runtime or just specs? If this affects runtime we need to make this a blocker and respin 5.4.2

**Comment by original-brownbear** [comment]
@suyograo runtime I'm afraid :( I can fix it in 7h feel free to take over if its more urgent, it should be just copying the missing file and adding the require (already done in my PR)

**Comment by suyograo** [comment]
@original-brownbear I can take over. Just to be sure, we copy https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/environment_variables.rb right?

**Comment by original-brownbear** [comment]
@suyograo yup :)

**Comment by suyograo** [comment]
@original-brownbear pushed directly https://github.com/elastic/logstash/commit/76c4926f4da6fa4a5d1ec9f5e5770dd85a8b1958

**Comment by original-brownbear** [comment]
@suyograo thanks :)
