### ISSUE TITLE
Combining configuration files generates a warning

### ISSUE THREAD

**Issue by t1m0t** [elastic/logstash#7475]
I'm facing something I don't understand. I have two configuration files for logstash :

- rsyslog.conf
```
    input {
      udp {
        host => "172.19.0.13"
        port => 10514
        codec => json
        type => "rsyslog"
      }
    }
    
    filter {
    }
    
    output {
      if [type] == "rsyslog" {
        elasticsearch {
          hosts => [ '172.19.0.13:9200' ]
          index => 'logstash-syslog-%{+YYY.MM.dd}'
        }
      }
    }
```

- kibana.conf
```

    input {
        udp {
                host => "172.19.0.13"
                port => 10514
                codec => json
        }
    }
    
    filter {
        if [programname] == "kibana" {
            json {
                source => "message"
            }
        }
    }
    
    output {
        if [programname] == "kibana" {
            elasticsearch {
                hosts => [ '172.19.0.13:9200' ]
                index => 'logstash-kibana-%{+YYY.MM.dd}'
            }
        }
    }

```

When I check them individually with this command, I get no warning message, eg:

> /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/kibana-logs.conf --config.reload.automatic

When I tail the logstash log file after starting logstash service, I get those warning messages over and over every approximately 1 sec :

```
[2017-06-16T16:20:38,620][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"172.19.0.13:10514"}
[2017-06-16T16:20:38,621][WARN ][logstash.inputs.udp      ] UDP listener died {:exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:82:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:56:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:443:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:436:in `start_input'"]}
[2017-06-16T16:20:43,629][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"172.19.0.13:10514"}
[2017-06-16T16:20:43,631][WARN ][logstash.inputs.udp      ] UDP listener died {:exception=>#<SocketError: bind: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:160:in `bind'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:82:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:56:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:443:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:436:in `start_input'"]}
```

Version of Logstash is: 5.4.1

Have anyone has an idea about, what it looks to me, a strange behavior ?

Thanks in advance,

Cheers

**Comment by t1m0t** [comment]
Hello,

Please find bellow debug information:
'''
Plugin: <LogStash::Inputs::Beats port=>10514, id=>"dc2eaeda9b6c18c3bfe17a9beed16a43ce791c7d-1", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_343bf9e3-2444-4c6b-999f-7414aae8722e", enable_metric=>true, charset=>"UTF-8">, host=>"0.0.0.0", ssl=>false, ssl_verify_mode=>"none", include_codec_tag=>true, ssl_handshake_timeout=>10000, congestion_threshold=>5, target_field_for_codec=>"message", tls_min_version=>1, tls_max_version=>1.2, cipher_suites=>["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"], client_inactivity_timeout=>60>
  Error: event executor terminated
  Exception: Java::JavaUtilConcurrent::RejectedExecutionException
  Stack: io.netty.util.concurrent.SingleThreadEventExecutor.reject(io/netty/util/concurrent/SingleThreadEventExecutor.java:840)
io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(io/netty/util/concurrent/SingleThreadEventExecutor.java:342)
io.netty.util.concurrent.SingleThreadEventExecutor.addTask(io/netty/util/concurrent/SingleThreadEventExecutor.java:335)
io.netty.util.concurrent.SingleThreadEventExecutor.execute(io/netty/util/concurrent/SingleThreadEventExecutor.java:765)
io.netty.channel.AbstractChannel$AbstractUnsafe.register(io/netty/channel/AbstractChannel.java:475)
io.netty.channel.SingleThreadEventLoop.register(io/netty/channel/SingleThreadEventLoop.java:80)
io.netty.channel.SingleThreadEventLoop.register(io/netty/channel/SingleThreadEventLoop.java:74)
io.netty.channel.MultithreadEventLoopGroup.register(io/netty/channel/MultithreadEventLoopGroup.java:85)
io.netty.bootstrap.AbstractBootstrap.initAndRegister(io/netty/bootstrap/AbstractBootstrap.java:330)
io.netty.bootstrap.AbstractBootstrap.doBind(io/netty/bootstrap/AbstractBootstrap.java:281)
io.netty.bootstrap.AbstractBootstrap.bind(io/netty/bootstrap/AbstractBootstrap.java:277)
io.netty.bootstrap.AbstractBootstrap.bind(io/netty/bootstrap/AbstractBootstrap.java:259)
org.logstash.beats.Server.listen(org/logstash/beats/Server.java:68)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
RUBY.run(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.21-java/lib/logstash/inputs/beats.rb:206)
RUBY.inputworker(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:443)
RUBY.start_input(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:436)
java.lang.Thread.run(java/lang/Thread.java:748)
[2017-06-29T12:32:55,819][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
'''

**Comment by untergeek** [comment]
When you have multiple Logstash configuration files, they are merged at initialization time into 1 file, effectively becoming:
```
    input {
      udp {
        host => "172.19.0.13"
        port => 10514
        codec => json
        type => "rsyslog"
      }
        udp {
                host => "172.19.0.13"
                port => 10514
                codec => json
        }
    }

    filter {
        if [programname] == "kibana" {
            json {
                source => "message"
            }
        }
    }

    output {
      if [type] == "rsyslog" {
        elasticsearch {
          hosts => [ '172.19.0.13:9200' ]
          index => 'logstash-syslog-%{+YYY.MM.dd}'
        }
      }
        if [programname] == "kibana" {
            elasticsearch {
                hosts => [ '172.19.0.13:9200' ]
                index => 'logstash-kibana-%{+YYY.MM.dd}'
            }
        }
    }
```
You have duplicate input entries on `host => "172.19.0.13"` and `port => 10514`.  Since Logstash can only bind to the same host and port one time, you're getting a collision.

As a side note, if you already have `codec => json`, then filter `json { source => message }` becomes redundant, and probably doesn't do anything.

Also, depending on which input is processed first, all events will either get `type => "rsyslog"`, or have no `type` at all, which results in the default `type` of `logs` being applied.  This could result in _only_ `[programname] == "kibana"` matching logs being output to Elasticsearch.  If you insist on having multiple configuration files, they should look something like this:

* rsyslog-input.conf

```
    input {
      udp {
        host => "172.19.0.13"
        port => 10514
        codec => json
        type => "rsyslog"
      }
```

* output.conf

```
    output {
      if [programname] == "kibana" {
        elasticsearch {
            hosts => [ '172.19.0.13:9200' ]
            index => 'logstash-kibana-%{+YYY.MM.dd}'
        }
      } else if [type] == "rsyslog" {
        elasticsearch {
          hosts => [ '172.19.0.13:9200' ]
          index => 'logstash-syslog-%{+YYY.MM.dd}'
        }
      }
    }
```
Without doing this conditional in the `output.conf` in this order, all of your logs would go to the `logstash-syslog` indices, and nothing would make it into the `logstash-kibana` indices.  This one guarantees that `[programname] == "kibana"` matching events go there first, and `[type] == "rsyslog"` events go to their respective index.  

I removed the `filter` block, since everything seems to be coming in on the same port, and would hopefully be `json` as a result.  If this is _not_ the case, then you should not be sending `kibana` data to the same port as `rsyslog` data, and should have that data come in on a different port, and be matched separately.  I'm presuming it's coming in over syslog, though, since you're looking for `[programname] == "kibana"`.

**Comment by t1m0t** [comment]
Hello,

Sorry for the late answer. You are right. The main issue from my side was to bind udp and tcp on the same port. So I solved the issue by issuing udp on a different port so that logstash will listen on a range of ports.

Thank you very much for your support and sorry for this dummy question as it is kind of basic networking knowledge!

Regards,
