### ISSUE TITLE
jvm.options does not work on Windows

### ISSUE THREAD

**Issue by todd-bowles-console** [elastic/logstash#7488]
As of my current understanding, the jvm.options file is a neat way to put all of your JVM specific settings into a file and have those settings be applied to the Logstash Java process.

The location and loading of this file appears to occur prior to Logstash being started, inside the logstash.lib.sh script file.

There is no equivalent (that I could see) for Windows (inside the logstash.bat file or the setup.bat file).

**Comment by untergeek** [comment]
That is correct. For Windows, any JVM settings currently have to go into the [`setup.bat` file, with the others](https://github.com/elastic/logstash/blob/master/bin/setup.bat#L42-L62).

**Comment by todd-bowles-console** [comment]
Intended, or an oversight/bug? It feels like both operating systems should use the same mechanism for JVM options if possible, or at the very least the documentation for settings should be amended to specify that Windows is special in regards to jvm.options.

**Comment by untergeek** [comment]
More like unintended and undesirable apathy on our part.  None of us are Windows-centric users, and so it's not high on our list to learn how to write or extend the `setup.bat` file to import and add the values from `jvm.options`.  If that's something you have the knowledge and skills to provide, that would be a wonderful and appreciated contribution.

**Comment by todd-bowles-console** [comment]
Ah no worries, I understand.

I'll see what I can do.

**Comment by jordansissel** [comment]
https://github.com/elastic/logstash/commit/79f66186477bafd20f61419ef294ae9c3b91f5f2 fixed this and was first released in v6.1.0
