### ISSUE TITLE
Allow mutate plugin to copy fields without losing the value type

### ISSUE THREAD

**Issue by micoq** [elastic/logstash#7511]
Currently, you can't copy a field without changing the value type to `string`: You can only use `add_field` or `replace` (like here #6774). In addition, it could allow to copy a whole subtree in the event.
If you have this event:
```
{
    "syslog": {
        "ip":"10.0.0.1",
        "port":514
    }
}
```
You could copy the `syslog` key:
```
mutate {
    copy => { "[syslog]" => "[source]" }
}
```
to output this:
```
{
    "syslog": {
        "ip":"10.0.0.1",
        "port":514
    },
    "source": {
        "ip":"10.0.0.1",
        "port":514
    }
}
```
Copying a field or an event part could be useful to keep raw data or to create common fields from specialized ones. In this example, `source` could exists in all events but `syslog` will be present only in syslog events.

**Comment by jsvd** [comment]
this has been implemented by https://github.com/logstash-plugins/logstash-filter-mutate/pull/84

**Comment by micoq** [comment]
Oh, I missed this commit, sorry !
