### ISSUE TITLE
5.5.0 task: Patch bump all plugins 

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7520]
In order to build the latest docs of all plugins, we need a patch release of any plugins that have not been released since we moved plugin docs into asciidoc (previously embedded as comments the Ruby code of the plugins).

This is a blocker for 5.5.0 release because the new 5.5/6.0 docs process uses different tooling to generate the documentation and version bumps of plugins are required to enable this.

Related: https://github.com/elastic/logstash/issues/7188

**Comment by jordansissel** [comment]
Related: https://github.com/elastic/logstash/pull/7521

**Comment by ph** [comment]
I've did the publish this morning.

**Comment by suyograo** [comment]
Keeping it open until we can validate the docs are getting built correctly for 5.5

**Comment by suyograo** [comment]
Some manual changes are needed for 5.5 which are in this PR: https://github.com/elastic/logstash-docs/pull/386
