### ISSUE TITLE
Doc plugin build issues

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#7522]
Issues found (in no order of importance). There were so many errors that I focused on fixing 2 of each type of plugin file. I'll need to have updated asciidoc files before I can test the entire doc build and verify that there are no other issues.

1) FIXED. There is a divider at line 88 in mutate.asciidoc that caused the build to fail:

```
Copy an existing field to another field. Existing target field will be overriden.
==========================
```

2) The files that list common options (filter.asciidoc and so on) have the ID at the top of the shared file: `[id="plugins-{type}s-common-options"]`.  When this file gets pulled into each of the plugin doc files (csv.asciidoc and so on), it results in duplicate IDs. So instead of the ID appearing at top of the shared files, it should appear at the bottom of each plugin doc file.  Also, the IDs need to contain the plugin name or they will not be unique. That's why we decided on the convention of using attributes. Otherwise, you end up with duplicate IDs. So we need to change the end of each plugin doc file to look like this:

```
[id="plugins-{type}s-{plugin}-common-options"]
include::{include_path}/{type}.asciidoc[]
```

3) The links that point to the common options also needs to be updated:
```
This plugin supports the following configuration options plus the <<plugins-{type}s-{plugin}-common-options>> described later.
.
.
.
Also see <<plugins-{type}s-{plugin}-common-options>> for a list of options supported by all
filter plugins.
```

4) codec.asciidoc (in the include folder) is blank. 

5) FIXED (just a placeholder anyhow) I had to change the include path in *all* the files because the files were not found. I changed it by adding an extra `../`.
````
:include_path: ../../../../logstash/docs/include
````

6) OK for now. I'm guessing this is intentional for right now, but these values aren't resolved:
* Plugin version: %VERSION% 
* Released on: %RELEASE_DATE% 
* %CHANGELOG_URL%[Changelog]

**Comment by ph** [comment]
codec.asciidoc (in the include folder) is blank. is intentional, we used to have commons option for codec but we don't have anymore.

**Comment by ph** [comment]
I will remove the the common file for the codec instead of having a blank file.

**Comment by dedemorton** [comment]
Plus for codecs remember to remove the sentences that point to common options (there are two links in each file that point to common options).

**Comment by ph** [comment]
This was done in a mass update.
