### ISSUE TITLE
Log message from Java code won't actually generate logs

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7526]
Due to the way we initialize the log4j logging context via Ruby, the Java logging context results in using the default context which will only log ERROR message to stdout (and/or sterr). 

This is difficult to reproduce without injecting code for testing since Java logging is already quiet unless specific errors occur. (to reproduce just inject an artificial log message in the Event class, and watch it not show up in the logs)

**Comment by jakelandis** [comment]
I believe that I have a fix for this, but still working through the details.

**Comment by jakelandis** [comment]
Submitted PR, which fixes core.  But noticed some of the plugin's are still on log4j v1, which for our use case is not compatible with v2.  I will address the Java plugin's in their respective repositories.

**Comment by saliormoon** [comment]
cmmond line: bin/logstash -f /etc/logstash/hello_es.conf

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /home/wangyufeng/logstash-5.5.2/logs which is now configured via log4j2.properties
[2017-08-29T18:39:44,022][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Expected one of #, input, filter, output at line 1, column 1 (byte 1) after "}

Anyone can tell me how to resolve it?

**Comment by jakelandis** [comment]
@saliormoon - The `ERROR StatusLogger` message is benign message and can be ignored. 5.6+ will fix that from being displayed. 

The actual error here is `Cannot create pipeline {:reason=>"Expected one of #, input, filter, output at line 1, column 1 (byte 1) after "}` which usually means some malformed configuration. https://discuss.elastic.co/c/logstash may provide some assistance in getting the configuration correct.
