### ISSUE TITLE
Update plugin docs ascidoc

### ISSUE THREAD

**Issue by ph** [elastic/logstash#7531]
Currently our plugins use the wrong defined ids at the top of the asciidoc.

```
[id="plugins-{type}-{plugin}"]
```

And it should be

```
[id="plugins-{type}s-{plugin}"]
```

**Note the s after type**

**Comment by ph** [comment]
cc @dedemorton

**Comment by dedemorton** [comment]
Closing bec this was fixed by a mass update that PH did earlier this year.
