### ISSUE TITLE
Rising thread number through SIGHUP Reload 

### ISSUE THREAD

**Issue by Shaoranlaos** [elastic/logstash#7536]
I have a problem with the reloading feature of the pipeline.
Each time i reload the pipeline configuration through the manual reload function (with signal SIGHUP) the number of threads on the maschine rises by ca. 130 Threads. These doesn't vanish until i restart logstash completely.
This is also the case in 5.2.2.

![image](https://user-images.githubusercontent.com/25054970/27173978-b833ee62-51ba-11e7-80bd-02a1017ee243.png)

Most rises in the Diagramm are from reloads in logstash.

- Version: 5.3.2
- Operating System: CentOs7

Config File:
logstash.yml (relevant Points):
    config.reload.automatic: true
    config.reload.interval: 1000000

pipeline conf.d:
90KB on config with many grok filters (ca. 120)

Steps to Reproduce:
- Start a Logstash Instance
- check the number of threads
- change the pipline config (minimal change so that a reload is triggered)
- send a SIGHUP signal to the logstash process
- check the number of threads again (should be higher as before the reload)

**Comment by jsvd** [comment]
a fix for sighup as been added recently to 5.5.x branch, which should ship with 5.5.2
I'm closing this, let me know if it still happens then
