### ISSUE TITLE
logstash service not starting on rhel7.3

### ISSUE THREAD

**Issue by dili91** [elastic/logstash#7566]
Hi all, 
I'm trying to install and start the ELK stack on a rhel7.3 machine.
I've troubles while starting logsatsh as a service:

```
[root@ip-xxx ~]# systemctl start logstash.service
Failed to start logstash.service: Unit not found.
```
I also tried 

```
[root@ip-xxx ~]# systemctl enable logstash.service
Failed to execute operation: Access denied
```

Anyone knows what's happening ?

**Comment by msteggink** [comment]
Is Logstash installed? (rpm -qa logstash)? If so, the installation does not seem to have completed succesfully, since the unit can not be found.

**Comment by dili91** [comment]
Sorry, 
I'm closing is as it was caused due to a misconfigured JAVA_HOME pointing to jre folder

**Comment by bbotte** [comment]
if you install logstash-5*.rpm first, and install jdk rpm second ,"Failed to start logstash.service: Unit not found."
1,  rpm -e logstash
2,  rpm -ivh logstash-5.4.1.rpm
3,  systemctl start logstash
it's ok

**Comment by modesolaa** [comment]
The logstash in /etc/init.d is missing. How can I resolve this?

**Comment by jakelandis** [comment]
@modesolaa - on RHEL 7 you won't have anything in /etc/init.d for service information try: 
```
systemctl status logstash
```

**Comment by GelosSnake** [comment]
Having similar problem on RHL 7.2  and centos 7.
Followed the guide from here: https://www.elastic.co/guide/en/logstash/6.2/running-logstash.html#running-logstash-systemd 
happend with both JDK and open JDK

**Comment by andyhouse90** [comment]
[root@svm59130 etc]# rpm -qa logstash
logstash-6.3.0-1.noarch
^[[A[root@svm59130 etc]# systemctl status logstash
Unit logstash.service could not be found.

**Comment by abarrios1** [comment]
@andyhouse90  Have you found a fix for this error? I recently came across this problem when running it on Ubuntu 16.04 VM...

**Comment by andyhouse90** [comment]
@abarrios1

I think it was lack of RAM during install, something was crashing out and not completing install steps.

Try again with more RAM, stop other services/processes etc, and should work fingers crossed

Andy
