### ISSUE TITLE
Plugins that cannot be installed on 5.x

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#7576]
While creating the docs for 5.5, we found that these plugins failed to install with "error occurred while installing net-ssh"

- [ ] logstash-input-heroku
- [ ] logstash-codec-cloudtrail
- [ ] logstash-codec-compress_spooler -
- [ ] logstash-output-gelf
- [ ] logstash-output-google_cloud_storage
- [ ] logstash-output-jira
- [ ] logstash-output-newrelic
- [ ] logstash-input-drupal_dblog

We should either fix these plugins, remove them from docs until they are fixed or deprecate/remove ones that are no longer used.

**Comment by dedemorton** [comment]
Updated the list to include  logstash-input-drupal_dblog. The first time I attempted to install, it did install the plugin to  v2.0.3 from March 18, 2016. However, when I ran the install command a second time, I encountered the net-ssh message, so I think it's fair to say that the latest version of the plugin cannot be installed.

**Comment by dedemorton** [comment]
Just wanted to point out that the following plugins cannot be installed either because of compatibility issues:

logstash-input-gemfire
logstash-input-rackspace
logstash-input-websocket
logstash-input-zenoss
logstash-input-zeromq
logstash-filter-cipher
logstash-filter-collate
logstash-filter-metaevent
logstash-filter-punct
logstash-filter-yaml
logstash-filter-zeromq
logstash-codec-oldlogstashjson
logstash-output-rackspace
logstash-output-zeromq

**Comment by jordansissel** [comment]
I am in favor of removing the plugins from the documentation.

**Comment by jordansissel** [comment]
The process we use to generate the plugin docs also tell us which plugins cannot be installed, and also why:

```
% cat plugins_version_docs.json | jq '.failures  | to_entries[] | .key'
"logstash-filter-punct"
"logstash-codec-oldlogstashjson"
"logstash-filter-cipher"
"logstash-filter-collate"
"logstash-input-gemfire"
"logstash-input-websocket"
"logstash-input-zenoss"
"logstash-input-zeromq"
"logstash-output-zeromq"
"logstash-output-gemfire"
"logstash-output-jira"
"logstash-filter-metaevent"
"logstash-filter-zeromq"
"logstash-codec-s3plain"
"logstash-input-fluentd"
"logstash-filter-unique"
"logstash-output-elasticsearch_java"
"logstash-codec-csv"
"logstash-output-rados"
"logstash-filter-lookup"
"logstash-output-zookeeper"
"logstash-output-monasca_log_api"
"logstash-filter-cloudfoundry"
```

(I have omitted the reasons; all of the reasons were various dependency conflicts)

**Comment by jordansissel** [comment]
So for this purpose, we could generate a patch to logstash-docs based on the output in my above comment. This patch would remove any plugins that cannot be installed from the docs.

**Comment by dedemorton** [comment]
Do we have any sense of how popular or widely-used the plugins are? Not opposed to removing hte docs, but I know that every time we do that people say "why did xyz disappear from the docs?!" Sometimes we forget the "why"....

**Comment by jordansissel** [comment]
I'm open to updating all the plugins as well. A banner can be fine, too, though it's unclear how that lifecycle would go -- should the docs sync script inject a `this plugin is broken` flag similar to how it injects the `default_plugin: 0` flag?

**Comment by dedemorton** [comment]
We've removed the plugins from 6.0. We'll do the same for 5.6 when we regenerate the docs. I've created an issue to track regenerating the plugin docs for 5.6 [here](https://github.com/elastic/logstash/issues/8571), so I am closing this issue now.
