### ISSUE TITLE
Add CIDR to default plugin and supported list

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#7577]
The [CIDR filter plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-cidr.html) has been gaining popularity in security analytics use cases. Let's bundle it by default and graduate it to a supported plugin in 6.0.

**Comment by liketic** [comment]
Can I take this?

**Comment by acchen97** [comment]
@andrewvc if not already, can we make sure to add this as a default plugin in 6.0? This should have been in 5.6 since the Netflow codec uses the CIDR filter.

**Comment by suyograo** [comment]
CIDR is already in there https://github.com/elastic/logstash/blob/6.0/Gemfile.jruby-2.3.lock.release#L187
