### ISSUE TITLE
logstash write 'logstash.shutdownwatcher' can not read read and can not write date to ealsticsearch

### ISSUE THREAD

**Issue by zhengqisong** [elastic/logstash#7584]
problem,
    data stream :  filebeat -> logstash -> elasticsearch.
    logstash run some time ,  can not write data to elasticsearch.  elasticsearch  works normally。
    I find logstash-plain.log have a lot of log “[WARN ][logstash.shutdownwatcher ] {}”。
   Follow these steps, logstash can  works normally  for some time: 
       (1) stop logstash 
       (2) rm ${path.queue} 
       (3) stop logstash 

- Version:  logstash-5.1.1
- Operating System: centos 7(Linux rizhifenxi 3.10.0-123.el7.x86_64 )
- Config File :
       (1)logstash.yml 
        queue.type: persisted
        path.queue: /home/elk/logstash-5.1.1/cache
        pipeline.workers: 15
        pipeline.output.workers: 15
        pipeline.batch.size: 10000
        pipeline.batch.delay: 10
       (2) jvm.options
        -Xms2g
        -Xmx2g
       (3)kylog.conf
          input {
    beats {
      port => 5044
    }
}

filter {
   json {
      source => message
      #skip_on_invalid_json => true
   }
   if("_jsonparsefailure" in [tags]) {
     drop {}
   }
   mutate {
      rename => {"_id" => "r_id"}
      convert => {"andUdType" => "string"}
      convert => {"html5" => "string"}
   }
}

output {
   #stdout { codec => rubydebug }
   elasticsearch {
      "hosts" => ["http://10.0.17.70:9200"]
      "index" => "kylog"
      "document_type" => "request"
      #"workers" => "2"
      #"template_overwrite" => true
      flush_size => 1000
   }
}
   
- Sample Data:
- Steps to Reproduce:
- logs:
     (1)logstash-plain.log 
       [2017-07-03T09:41:47,824][WARN ][logstash.shutdownwatcher ] {}
       [2017-07-03T09:41:52,817][WARN ][logstash.shutdownwatcher ] {}
       [2017-07-03T09:41:57,819][WARN ][logstash.shutdownwatcher ] {}
       [2017-07-03T09:42:02,823][WARN ][logstash.shutdownwatcher ] {}
       [2017-07-03T09:42:07,818][WARN ][logstash.shutdownwatcher ] {}
       [2017-07-03T09:42:12,817][WARN ][logstash.shutdownwatcher ] {}
       [2017-07-03T09:42:17,818][WARN ][logstash.shutdownwatcher ] {}
       [2017-07-03T09:42:22,828][WARN ][logstash.shutdownwatcher ] {}
     (2)/home/elk/logstash-5.1.1/cache   data file
       -rw-r--r--. 1 root root   34 Jul  1 22:13 checkpoint.989
-rw-r--r--. 1 root root   34 Jul  1 22:17 checkpoint.990
-rw-r--r--. 1 root root   34 Jul  1 22:22 checkpoint.991
-rw-r--r--. 1 root root   34 Jul  1 22:27 checkpoint.992
-rw-r--r--. 1 root root   34 Jul  1 22:30 checkpoint.993
-rw-r--r--. 1 root root   34 Jul  1 22:35 checkpoint.994
-rw-r--r--. 1 root root   34 Jul  1 22:39 checkpoint.995
-rw-r--r--. 1 root root   34 Jul  1 22:43 checkpoint.996
-rw-r--r--. 1 root root   34 Jul  1 22:48 checkpoint.997
-rw-r--r--. 1 root root   34 Jul  1 22:52 checkpoint.998
-rw-r--r--. 1 root root   34 Jul  1 22:57 checkpoint.999
-rw-r--r--. 1 root root   34 Jul  2 02:56 checkpoint.head
-rw-r--r--. 1 root root 250M Jul  2 01:18 page.1031
-rw-r--r--. 1 root root 250M Jul  2 02:56 page.1053
-rw-r--r--. 1 root root 250M Jun 30 17:33 page.329
-rw-r--r--. 1 root root 250M Jul  1 21:25 page.979

**Comment by untergeek** [comment]
A number of changes and fixes (especially related to the persistent queues) have been applied since version 5.1.1.

I recommend you test again with version 5.4.x before re-opening this ticket, and include any new details you encounter.
