### ISSUE TITLE
grok %{NUMBER:body_bytes_sent} $body_bytes_sent still string after mutate to integer?

### ISSUE THREAD

**Issue by KeithTt** [elastic/logstash#7598]
ES version: 5.4.1
Logstash version: 5.4.1
Kibana version: 5.4.1

I have mutated this section to integer in the configuration of logstash, but it always is string by default, I need to modify it to number type, who can tell me why...

here is my configuration:
```
mutate {
  convert => [ "body_bytes_sent", "integer"]
}
```

**Comment by jsvd** [comment]
can you show which data you're using and output from logstash?

**Comment by KeithTt** [comment]
It worked in another environment...I will check the environment. 

Thanks a lot! @jsvd  Close it!
