### ISSUE TITLE
Bump Jackson to newer version

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7615]
We are currently on Jackson 2.7.3.

It looks like 2.8 is out, and 2.9 is close to release:
https://github.com/FasterXML/jackson/wiki/Jackson-Releases

This change is dependent upon:
https://github.com/guyboertje/jrjackson/issues/61

We need to ensure that versions stay in sync else #6781 will re-appear.  See PR #7614 for steps on how to keep in sync.

**Comment by prathibhay** [comment]
what is the palns for upgrade and in which release are you planning to upgrade? we are also facing same issue

**Comment by jakelandis** [comment]
@prathibhay  - I can't say for certain based on timing and unknown complexity of the upgrade (hopefully it is just dependency bump).  We have re-prioritized are are targeting the next patch releases for 5.5 and 5.6, and the next release candidate for 6.0.

**Comment by jakelandis** [comment]
Changes are made initially on https://github.com/elastic/logstash/pull/8373 and will be back ported.

**Comment by aburmeis** [comment]
guyboertje/jrjackson#61 has been solved and will be included in v0.4.3

**Comment by jakelandis** [comment]
Jackson updated to 2.9.1 as far back as 5.5.x

Assuming there is release for the given pipeline (not a guarantee or commitment), it would be in:
5.5.4, 5.6.3, 5.7, 6.0.0-rc2, 6.1, 7.0.0-alpha1 

closing issue as resolved.
