### ISSUE TITLE
DLQ: Add configurable max queue size setting

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#7633]
(This is a stopgap until the DLQ retention code is merged)

Currently, the DLQ has the ability to stop writing once the queue has reached a configured limit. Currently, this queue limit is not exposed as a configurable setting, and is hardcoded to Long.MAX_VALUE. To ensure that the DLQ will not grow excessively until the retention functionality is added, this limit should be exposed as a user configurable setting

**Comment by robbavey** [comment]
@acchen97 The retention period used **dead_letter_queue.size.threshold**  as the threshold for retention - make sense to use that again?

**Comment by acchen97** [comment]
@robbavey I'd use something similar to the PQ setting, perhaps `dead_letter_queue.max_bytes` with default set to 1GB? The retention setting can be separate IMO.

**Comment by robbavey** [comment]
@acchen97 I think that makes sense
