### ISSUE TITLE
Jenkins Windows Build's show a false positive success. 

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7634]
A new build job was added today and started to fail the PR builds. 

https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-windows-compatibility/

and

https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-windows-compatibility/

**Comment by jakelandis** [comment]
I now have access to the Windows build machines and can troubleshoot the remaining failures.

**Comment by jakelandis** [comment]
Re-opening. 

It seems that I only addressed the Java side of things and we have false positive green builds. 

This issue is currently blocked by: https://github.com/elastic/infra/issues/2487

Once that is addressed we can resume getting these builds to work. 

The current state is that the Java tests are executing as part of these jobs, but the Ruby tests are failing due to long file names, and the final state is a green SUCCESS.

**Comment by jakelandis** [comment]
Once https://github.com/elastic/infra/issues/2487 is resolved, the following issue will likely arise preventing the tests from running:

```
[plugin:install-core] Installing core plugins
Installing logstash-filter-clone, logstash-filter-cidr, logstash-filter-mutate, logstash-input-generator, logstash-input-stdin, logstash-input-tcp, logstash-output-stdout, logstash-filter-multiline
Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
             getBytes at java/lang/String.java:940
               <init> at org/jruby/ast/SymbolNode.java:54
             asSymbol at org/jruby/parser/ParserSupport.java:975
              execute at org/jruby/parser/RubyParser.java:4286
              yyparse at org/jruby/parser/RubyParser.java:1677
              yyparse at org/jruby/parser/RubyParser.java:1568
                parse at org/jruby/parser/RubyParser.java:5365
                parse at org/jruby/parser/Parser.java:128
                parse at org/jruby/parser/Parser.java:77
            parseEval at org/jruby/Ruby.java:2722
            prepareIC at org/jruby/ir/interpreter/Interpreter.java:211
           evalCommon at org/jruby/ir/interpreter/Interpreter.java:167
           evalSimple at org/jruby/ir/interpreter/Interpreter.java:158
            evalUnder at org/jruby/RubyBasicObject.java:1917
         specificEval at org/jruby/RubyBasicObject.java:1842
      instance_eval19 at org/jruby/RubyBasicObject.java:1697
                 call at org/jruby/RubyBasicObject$INVOKER$i$instance_eval19.gen:-1
                 call at org/jruby/internal/runtime/methods/JavaMethod.java:328
                 call at org/jruby/runtime/callsite/CachingCallSite.java:161
          processCall at org/jruby/ir/interpreter/InterpreterEngine.java:314
            interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:73
            interpret at org/jruby/ir/interpreter/InterpreterEngine.java:83
     INTERPRET_METHOD at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:179
                 call at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:165
                 call at org/jruby/internal/runtime/methods/DynamicMethod.java:200
    .....


Bundler::GemNotFound: Could not find rake-12.0.0 in any of the sources
  block in materialize at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/spec_set.rb:92
                  map! at org/jruby/RubyArray.java:2518
           materialize at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/spec_set.rb:85
                 specs at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:132
             specs_for at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:177
       requested_specs at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:166
       requested_specs at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/environment.rb:18
                 setup at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:13
                 setup at T:/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:122
                setup! at T:/lib/bootstrap/bundler.rb:68
                <main> at T:\\lib\bootstrap\rspec.rb:3
```

If so, I tracked the error down to this line:

```dsl.instance_eval(gemfile_content)```

in LogStash::DSL in gemfile.rb. It seems that we may be hitting a bug in JRuby w.r.t Symbols in an instance_eval, but only on Windows.  The fix for this error, is to change ALL of the Symbols in Gemfile to Strings. 

For example : ```gem "logstash-core", "path" => "./logstash-core"``` 

Once all Symbols are changed to Strings, the tests will run. 

I will wait to fix/follow up on this until we have the Windows build machines will allow the long names.

**Comment by jakelandis** [comment]
Also there appears to be some additional work to get the Ruby side of the tests to pass:

```2584 examples, 24 failures, 3 pending```

**Comment by jakelandis** [comment]
https://github.com/elastic/infra/issues/2487 has been resolved. 

As expected the NullPointer + Could not find rake-12.0.0 is now present.

**Comment by suyograo** [comment]
@jakelandis we should split this work. Can you add a list of issues in a meta issue and we can then assign folks to it?

**Comment by jakelandis** [comment]
@suyograo - yup , and thanks.  I am hitting my upper limits on this Java NullPointer via Ruby meta programming. 

Closing this issue in favor of : https://github.com/elastic/logstash/issues/7767

**Comment by jakelandis** [comment]
w/r/t to the NullPointer issue, I can not figure out why it is blowing up. 

On Windows, this should be a fair replication in IRB, but it works just fine
```
irb(main):001:0> class A
irb(main):002:1> def gem(*splat)
irb(main):003:2> puts splat.to_s
irb(main):004:2> end
irb(main):005:1> end
=> :gem
irb(main):006:0> a = A.new
=> #<A:0x25fb8912>
irb(main):007:0> a.instance_eval("gem \"json-schema\", \"~> 2.6\", :group => :development")
["json-schema", "~> 2.6", {:group=>:development}]
```
Converting the Gemfile symbols to Strings is a really hacky workaround, but I am at a loss to explain this behavior. 

Also, for whom ever may tackle this issue, commenting out the Java tests saves a ton of time while debugging from ci\ci_test.bat
