### ISSUE TITLE
Add documentation for DLQ max bytes

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#7658]
@robbavey added a [new config option](https://github.com/elastic/logstash/pull/7652) for DLQ to limit the max disk usage for the DLQ to avoid out of disk scenarios. The `dead_letter_queue.max_bytes` setting is 1GB. Let's outline this in the DLQ docs page starting with the 5.6 release.

https://www.elastic.co/guide/en/logstash/current/dead-letter-queues.html

**Comment by acchen97** [comment]
As we've decided to backport this to 5.5.1, this should also go into the 5.5 docs when it releases.

**Comment by dedemorton** [comment]
Closed via #8176
