### ISSUE TITLE
About system-install, there is no /etc/init.d/logstash file after I execute this script?

### ISSUE THREAD

**Issue by KeithTt** [elastic/logstash#7660]
ES/Logstash/Kibana version: 5.4.1
OS Version: CentOS6.6

I install logstash by rpm package.

```
# bin/system-install
Successfully created system startup script for Logstash
```

There is no /etc/init.d/logstash file after I execute the `system-install` script, although it tells `Successfully created system startup script for Logstash`.

I followed the official guide here: 

https://www.elastic.co/guide/en/logstash/5.5/config-setting-files.html#_settings_files

I have a try on CentOS7, it works, there is a `logstash.service` file after execute the script. Why failed on CentOS6?

**Comment by untergeek** [comment]
You missed [this page](https://www.elastic.co/guide/en/logstash/current/running-logstash.html) where it explains that Logstash auto-detects the init-type of the system it's running on.  For CentOS 6, that's technically [upstart](https://www.elastic.co/guide/en/logstash/current/running-logstash.html#running-logstash-upstart).

However, there is a manual way to override the auto-detection and force it to make a SysV init script, if that's what you want:

```
/usr/share/logstash/bin/system-install /etc/logstash/startup.options sysv
```
