### ISSUE TITLE
Logstash::Runner error

### ISSUE THREAD

**Issue by zoubazouba** [elastic/logstash#7661]
Hi all,

I integrated a new plugin in Logstash to collect telemetry data ( https://github.com/cisco/logstash-codec-bigmuddy-network-telemetry-gpb ).
After running the logstash instance, I started facing this error (here is the full log ) : 

"Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
telemetry-logstash_1  | 09:28:55.494 [LogStash::Runner] INFO  logstash.codecs.telemetry_gpb - Registering cisco telemetry_gpb dgram codec
telemetry-logstash_1  | 09:28:55.519 [LogStash::Runner] ERROR logstash.agent - Cannot load an invalid configuration {:reason=>"uninitialized constant Kernel::BgpNbrBag"}"

Any idea what could be the issue ?

Best,

**Comment by jsvd** [comment]
this seems to be a bug in the plugin, please contact the owner to get a fix in the plugin itself
