### ISSUE TITLE
StringInterpolation cache causes OOM

### ISSUE THREAD

**Issue by IngaFeick** [elastic/logstash#7676]
We have reproducably run into OOMs due to a design issue with the StringInterpolation class. 
Specifically we run into a problem which is already described in the class: 
https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/StringInterpolation.java#L17

> // The current implementation doesn't allow the keys to expire, I think under normal usage
> // the keys will converge to a fixed number.
> // If this code make logstash goes OOM, we have the following options: ...

- Version: 5.4.3
- Operating System: debian
- Steps to Reproduce: use the influxdb output with the config option TODO set to true. Make sure that your events still have the "message" field when they reach the output plugin. 
- example config: 
```
input 
{
  kafka
  {
    ....
    codec => "line"
  }
}
filter
{
  grok
  {
    match => { "message" =>  "^(?<datacenter>[^\.]+?)\.(?<service>[^\.]+?)\.(?<host>[^\.]+?)\.(?<measurement>[^\s]+?)\s%{NUMBER:value:float}\s%{INT:time}\s*$"}
  }
}
output
{
  influxdb
  {
    host => "10.1.2.3"
    password => "password"
    user => "logstash"
    db => "collectd_test"
    measurement => "%{measurement}"
   
    send_as_tags => ["datacenter","service","host","application","instance","topic","partition","disk"]
    allow_time_override => true
    time_precision => "s"
    coerce_values =>
    {
     "value" => "float"
    }
    retention_policy => "rp"

    use_event_fields_for_data_points => true
    exclude_fields => ["@timestamp", "@version", "sequence", "message", "type", "measurement", "ip"]
  }
}
```

The last two lines of the influxdb config are most important.
We have observed that the problem seems to happen only when the option "use_event_fields_for_data_points" is set in the influx output config. 
When creating a datapoint for shipping to the database, the influxdb output plugin [calls the event.sprintf(v)](https://github.com/logstash-plugins/logstash-output-influxdb/blob/master/lib/logstash/outputs/influxdb.rb#L209) method on the name and value of each field which has been configured to go into the database. When setting the "use_event_fields_for_data_points" option to true, this happens on all fields of the event, including the "message" field generated by the kafka input. 
The event.sprintf method is then [calling](https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/Event.java#L271) the evalute() method on the StringInterpolation class. 
The StringInterpolation class [keeps a cache](https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/StringInterpolation.java#L12) of all strings passed to it, and this cache is where the memory leak happens, because values go in, but seem to never go out. 

In our tests we ended up with ConcurrentHashMaps with multiple millions of kafka message strings in them, resulting in garbage collection times of 20 seconds.

A cheap workaround for us is to drop the message field before the event reaches the output plugin, but it might be worth saving others the time and hassle to debug.

**Comment by original-brownbear** [comment]
@IngaFeick looking into this :)

**Comment by original-brownbear** [comment]
fixed performance + leaking in https://github.com/elastic/logstash/pull/7692

**Comment by IngaFeick** [comment]
Thanks @original-brownbear !
