### ISSUE TITLE
java.util.concurrent.SynchronousQueue is not a Good Choice for the In-Memory Queue

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7690]
Currently the in-memory(legacy) queue uses `java.util.concurrent.SynchronousQueue` internally.

This is a suboptimal choice when coupled with batched reads from it since it leads to either of the following two scenarios:

* Fast consumers and slow producers will see the producer thread(s) sleep more than necessary despite beeing the bottleneck
* Fast producers and slow consumers will see the consumer thread(s) sleep more than necessary

This is very visible when running the Apache dataset with `-b 1024 -w 2`:

<img width="1152" alt="screen shot 2017-07-14 at 10 03 04" src="https://user-images.githubusercontent.com/6490959/28204054-a3e2e5e8-687c-11e7-8957-7b4fcef626d5.png">

You can see the consumer threads being the obvious bottleneck here (stdin input), with the producer sleeping a lot. But still, the consumers are merely hot ~75% of the time.
This is clearly not a good scenario but entirely expected without any buffering between inputs and outputs.
A synchronous queue only makes sense in scenarios where you are expecting to most of the time have a consumer available. This is precisely not what we want, we burn most of the time in filters and outputs, having these threads blocking on the by design wastes time that could go towards processing. Worse yet, a synchronous queue requires to lock and unlock on the queue consumption for every event read from it since it doesn't have a much more efficient `drainTo` call.
We definitely want a queue with capacity here to give us `drainTo` and reduce blocking on the filter/output end. 
Any argument about this causing more events in flight could just be countered by suggesting to use a lower batch size if that is, in fact, an issue.

**Comment by original-brownbear** [comment]
@suyograo @jordansissel see #7691 and this one please, I think this is a trivial and significant performance gain (especially for high worker counts).

**Comment by suyograo** [comment]
pinging @andrewvc since I think he chose `SynchronousQueue` for the in-memory implementation.

**Comment by andrewvc** [comment]
Looks like a nice performance gain to me and the reasoning is definitely sound. Great work @original-brownbear ! Let's move this discussion over to #7691 maybe for future comments?

**Comment by original-brownbear** [comment]
fix via #7691

**Comment by amitpaz** [comment]
Hello, 
Is the Execution model documentation up to date? ( as it states usage of a synchronous queue)
https://www.elastic.co/guide/en/logstash/master/execution-model.html#execution-model

**Comment by jakelandis** [comment]
@amitpaz - yup,  with the recent 6.1 release that is is now out of date.  I have an issue to update it over here: https://github.com/elastic/logstash/issues/8488, I should get that committed.  Thanks for the reminder.
