### ISSUE TITLE
Add netflow module based on elastiflow

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#7715]
Add a new module called `netflow` based on the excellent work by @robcowart in https://github.com/robcowart/elastiflow

Tasks
- [x] Include translate and CIDR filter by default in LS core https://github.com/elastic/logstash/pull/7714
- [x] Bring in files in https://github.com/robcowart/elastiflow as module structure
- [x] Package GeoIPLite-ASN database by default https://github.com/logstash-plugins/logstash-filter-geoip/issues/126
- [x] Replace environment variables in config files in https://github.com/robcowart/elastiflow with `var.netflow.*` overrides.
- [x] For translate filter, bundle dictionaries and place them in `modules/netflow/logstash/dictionaries` folder and reference this path in pipeline config.

**Comment by untergeek** [comment]
This is complete, with modules for both 5.6 and 6.0.
