### ISSUE TITLE
Logstash 5.5.0 - log4j and syslog don't use conf. properly

### ISSUE THREAD

**Issue by randude** [elastic/logstash#7721]
For some reason, logstash does indeed send log data to my rsyslog process but it uses default settings and basically just ignores my custom settings. I've googled all other the place and I just cant get it to work properly. 
I'm using ubuntu 16.

Here are my settings:
# configure the root logger
log4j.rootLogger= syslog

# configure Syslog facility LOCAL6 appender
log4j.appender.syslog=org.apache.log4j.net.SyslogAppender
log4j.appender.syslog.threshold=WARN
log4j.appender.syslog.syslogHost=localhost
log4j.appender.syslog.facility=LOCAL6
log4j.appender.syslog.layout=org.apache.log4j.PatternLayout
log4j.appender.syslog.layout.conversionPattern=%d{MMM dd HH:mm:ss} logstash %p %m%n

**Comment by jakelandis** [comment]
You trying to send Logstash's logfile to syslog ? 

I assume that this is not what you want  https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html ?

How are you configuring the log4j2.properties file ? via the conf directory or by some other means?

**Comment by randude** [comment]
Hi, I'm editing the log4j2.properties file that tells logstash how to write it's own log.
I wrote the setting that I used in the first post.
It outputs to my syslog but it uses only default settings and ignores all of my settings.
I've played around with it and still cant get it to cooperate.

**Comment by randude** [comment]
You trying to send Logstash's logfile to syslog ? - logstash's log to syslog

**Comment by jakelandis** [comment]
We have some unreleased bug fixes w/r/t to how we configure the logging context internally. 

This specific use case had not been identified as one of those bugs, but the changes may have inadvertently fix this. 

Perhaps wait for the next release and try again (6.0.0-beta1 (not released yet) has the internal changes to logging context), build from source and try again, or use Filebeat to monitor Logstash's log and send it back into Logstash with the syslog output ?

**Comment by randude** [comment]
Syslog writes to a log file that is used as a backup. I'm trying to centerlize logs to syslog and i use logstash to output other logs to ES.

Im pretty sure my conf isnt good but i wsnt able to find any working log4j2 working syslog conf.
Didn't you guys try it ? It should be rather basic conf.

**Comment by jakelandis** [comment]
I have not tried it. 

If you believe it to be an issue specific to your configuration please raise a question over at https://discuss.elastic.co/c/logstash, you will get many more eyes on your question.  If so, do you mind If I close this github issue ?
