### ISSUE TITLE
Plugin parameter cleanup for 6.0.0 

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7740]
This issue will list the plugins that possess parameters that are:
- currently deprecated and will become obsolete
- currently obsolete and will be removed

Plugins in any of these situations will be upgraded by a major version which will be included in logstash 6.0.0.

#### For existing :obsolete configuration options

1. Remove :obsolete configuration options
2. Bump minor version of plugin
3. Add CHANGELOG.md entry noting this change
4. Create PR and add the URL to the list below

#### For existing :deprecated configuration options

1. Change all options from :deprecated to :obsolete
  a) Adjust obsolete message
2. Remove references to newly obsoleted fields in the code an tests
  a) Check that all tests still pass
3. Remove references to the newly obsoleted fields from the ascii docs file
4. Bump major version of plugin
5. Add CHANGELOG.md entry noting this change
6. Create PR and add the URL to the list below

### List of :deprecated parameters that must be converted to :obsolete

 - [x] [logstash-codec-cef#sev](https://github.com/logstash-plugins/logstash-codec-cef/blob/master/lib/logstash/codecs/cef.rb#L43) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-cef.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-cef) | https://github.com/logstash-plugins/logstash-codec-cef/pull/46
 - [x] [logstash-codec-cef#deprecated_v1_fields](https://github.com/logstash-plugins/logstash-codec-cef/blob/master/lib/logstash/codecs/cef.rb#L59) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-codec-cef.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-codec-cef) | https://github.com/logstash-plugins/logstash-codec-cef/pull/46
 - [ ] [logstash-filter-cipher#iv](https://github.com/logstash-plugins/logstash-filter-cipher/blob/master/lib/logstash/filters/cipher.rb#L103) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-cipher.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-cipher) | https://github.com/logstash-plugins/logstash-filter-cipher/pull/21
 - [x] [logstash-filter-geoip#lru_cache_size](https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb#L102) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-filter-geoip.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-filter-geoip) | https://github.com/logstash-plugins/logstash-filter-geoip/pull/129
 - [x] [logstash-input-beats#congestion_threshold](https://github.com/logstash-plugins/logstash-input-beats/blob/master/lib/logstash/inputs/beats.rb#L103) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-beats.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-beats) | https://github.com/logstash-plugins/logstash-input-beats/pull/252
 - [x] [logstash-input-beats#target_field_for_codec](https://github.com/logstash-plugins/logstash-input-beats/blob/master/lib/logstash/inputs/beats.rb#L106) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-beats.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-beats) | https://github.com/logstash-plugins/logstash-input-beats/pull/252
 - [x] [logstash-input-http_poller#interval](https://github.com/logstash-plugins/logstash-input-http_poller/blob/master/lib/logstash/inputs/http_poller.rb#L24) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-http_poller.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-http_poller) | https://github.com/logstash-plugins/logstash-input-http_poller/pull/76
 - [x] [logstash-input-kafka#ssl](https://github.com/logstash-plugins/logstash-input-kafka/blob/master/lib/logstash/inputs/kafka.rb#L163) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-kafka.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-kafka) | https://github.com/logstash-plugins/logstash-input-kafka/pull/216
 - [x] [logstash-input-tcp#data_timeout](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash/inputs/tcp.rb#L76) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-tcp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-tcp) | https://github.com/logstash-plugins/logstash-input-tcp/pull/82
 - [x] [logstash-input-tcp#ssl_cacert](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash/inputs/tcp.rb#L94) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-tcp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-tcp) | https://github.com/logstash-plugins/logstash-input-tcp/pull/82
 - [x] [logstash-mixin-http_client#ssl_certificate_validation](https://github.com/logstash-plugins/logstash-mixin-http_client/blob/master/lib/logstash/plugin_mixins/http_client.rb#L55) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-mixin-http_client.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-mixin-http_client) | https://github.com/logstash-plugins/logstash-mixin-http_client/pull/30
 - [x] [logstash-mixin-rabbitmq_connection#debug](https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/blob/master/lib/logstash/plugin_mixins/rabbitmq_connection.rb#L68) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-mixin-rabbitmq_connection.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-mixin-rabbitmq_connection) | https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/41
 - [x] [logstash-mixin-rabbitmq_connection#tls_certificate_path](https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/blob/master/lib/logstash/plugin_mixins/rabbitmq_connection.rb#L86) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-mixin-rabbitmq_connection.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-mixin-rabbitmq_connection) | https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/41
 - [x] [logstash-mixin-rabbitmq_connection#tls_certificate_password](https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/blob/master/lib/logstash/plugin_mixins/rabbitmq_connection.rb#L89) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-mixin-rabbitmq_connection.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-mixin-rabbitmq_connection) | https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/41
 - [x] [logstash-output-elasticsearch#flush_size](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common_configs.rb#L94) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch) | https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/627
 - [x] [logstash-output-elasticsearch#idle_flush_time](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common_configs.rb#L96) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch) | https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/627
 - [x] [logstash-output-elasticsearch_java#max_inflight_requests](https://github.com/logstash-plugins/logstash-output-elasticsearch_java/blob/master/lib/logstash/outputs/elasticsearch_java.rb#L101) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch_java.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch_java)
 - [x] [logstash-output-kafka#block_on_buffer_full](https://github.com/logstash-plugins/logstash-output-kafka/blob/master/lib/logstash/outputs/kafka.rb#L77) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-kafka.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-kafka) | https://github.com/logstash-plugins/logstash-output-kafka/pull/143
 - [x] [logstash-output-kafka#ssl](https://github.com/logstash-plugins/logstash-output-kafka/blob/master/lib/logstash/outputs/kafka.rb#L122) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-kafka.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-kafka) | https://github.com/logstash-plugins/logstash-output-kafka/pull/143
 - [x] [logstash-output-kafka#timeout_ms](https://github.com/logstash-plugins/logstash-output-kafka/blob/master/lib/logstash/outputs/kafka.rb#L170) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-kafka.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-kafka) | https://github.com/logstash-plugins/logstash-output-kafka/pull/143
 - [x] [logstash-output-redis#queue](https://github.com/logstash-plugins/logstash-output-redis/blob/master/lib/logstash/outputs/redis.rb#L56) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-redis.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-redis) | https://github.com/logstash-plugins/logstash-output-redis/pull/51
 - [x] [logstash-output-sqs#batch](https://github.com/logstash-plugins/logstash-output-sqs/blob/master/lib/logstash/outputs/sqs.rb#L77) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-sqs.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-sqs) | https://github.com/logstash-plugins/logstash-output-sqs/pull/25
 - [x] [logstash-output-sqs#batch_timeout](https://github.com/logstash-plugins/logstash-output-sqs/blob/master/lib/logstash/outputs/sqs.rb#L83) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-sqs.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-sqs) | https://github.com/logstash-plugins/logstash-output-sqs/pull/25
 - [x] [logstash-output-tcp#message_format](https://github.com/logstash-plugins/logstash-output-tcp/blob/master/lib/logstash/outputs/tcp.rb#L60) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-tcp.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-tcp) | https://github.com/logstash-plugins/logstash-output-tcp/pull/28

### List of :obsolete parameters that must be removed

 - [x] [logstash-input-log4j#data_timeout](https://github.com/logstash-plugins/logstash-input-log4j/blob/master/lib/logstash/inputs/log4j.rb#L120) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-input-log4j.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-input-log4j) | https://github.com/logstash-plugins/logstash-input-log4j/pull/43
 - [x] [logstash-output-elasticsearch#max_retries](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common_configs.rb#L107) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch) | https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/627
 - [x] [logstash-output-elasticsearch#retry_max_items](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common_configs.rb#L134) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch) | https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/627
 - [x] [logstash-output-file#message_format](https://github.com/logstash-plugins/logstash-output-file/blob/master/lib/logstash/outputs/file.rb#L40) | [![Build Status](https://travis-ci.org/logstash-plugins/logstash-output-file.svg?branch=master)](https://travis-ci.org/logstash-plugins/logstash-output-file) | https://github.com/logstash-plugins/logstash-output-file/pull/55

**Comment by jakelandis** [comment]
@jsvd - Would this be a good time to pin 6.x's Gemfile.template to all these new major versions ?

**Comment by jsvd** [comment]
@jakelandis I believe so, we want to make it easy for the next minor/patch releases to be safe against new major plugin versions, but we must also not block users from upgrading if they wish to do so.

**Comment by jsvd** [comment]
A note for reviewers: the breaking changes to the mixin repos `logstash-mixin-rabbitmq_connection` and `logstash-mixin-http_client` mean that the plugins used by these mixins must also receive a major version bump and a correct dependency pin to the new mixin major version.

For `logstash-mixin-http_client`: logstash-input-http_poller and logstash-output-http
For `logstash-mixin-rabbitmq_connection`: logstash-input-rabbitmq and logstash-output-rabbitmq

**Comment by jsvd** [comment]
Current status: cipher filter and tcp input are failing their specs, but not related to these PRs

PRs open:
bump major dependency on rabbitmq mixin | https://github.com/logstash-plugins/logstash-output-rabbitmq/pull/67
bump major dependency on rabbitmq mixin | https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/103
bump version on http_client mixin | https://github.com/logstash-plugins/logstash-output-http/pull/68
