### ISSUE TITLE
Logstash.pipeline - A plugin had an unrecoverable error when folder is long

### ISSUE THREAD

**Issue by alex25784** [elastic/logstash#7750]
Hello ,
I am using file input and the pipeline crashes when one of the folders in the path is too long. 

2:03:16.001 [[main]<file] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.

12:03:14.998 [[main]<file] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.
Plugin: <LogStash::Inputs::File path=>["d:/4.0/264123/AWS/12_12__08_45_AD/**/*.log"], type=>"daletlogs", start_position=>"beginning", sincedb_path=>"dev/null", max_open_files=>65000, id=>"1dfab803f936adcf610593fb6786972975d74de5-1", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_ffae9fe4-649d-4388-96bc-bbd0f3d653ee", enable_metric=>true, charset=>"UTF-8">, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, delimiter=>"\n", close_older=>3600>

Error: No such process - d:/4.0/264123/AWS/12_12__08_45_AD/Format Spec-[Interleaved 2997 asspect 4 3 Height less then 575 width more then 719] Dalet Format-2337 copy migration action-trigger miggration rule/DaletMediaThunder_InvokedBy_Sanity-MediaTranscoderAgent_1@IP-0A00023B-20.log

The issue here is with the folder length:

> Format Spec-[Interleaved 2997 asspect 4 3 Height less then 575 width more then 719] Dalet Format-2337 copy migration action-trigger miggration rule

I am using logstash5.4.0 , Any ides?
Thanks

**Comment by jakelandis** [comment]
@alex25784 
It looks like this is on Windows, and you are bumping into the 260 character file path limit. 

This is fixable via a registry edit on newer Windows 10 and Server 2016. See:
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

Closing out this issue.

**Comment by RamyaGowda397** [comment]
it looks like  more than one logstash instance running,check with something like ps axf | grep logstash
