### ISSUE TITLE
LoadError: load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/crypto/params/AsymmetricKeyParameter

### ISSUE THREAD

**Issue by nandkv** [elastic/logstash#7770]
- Version: logstash-2.4.0 and 5.5.0
- OS: macOS Sierra 10.12.5

- Steps to reproduce:
Command: bin/logstash or bin/logstash -f pipeline.conf (you don't even need to specify the filename and it blows up)

- JDK: 
ls -l /Library/Java/JavaVirtualMachines/
total 0
drwxr-xr-x  3 root  wheel  102 Sep 21  2016 jdk1.8.0_101.jdk

Issue:
LoadError: load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/crypto/params/AsymmetricKeyParameter
  require at org/jruby/RubyKernel.java:1040
   (root) at /Users/nand/Development/elk/logstash-2.4.0/vendor/jruby/lib/ruby/shared/openssl.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /Users/nand/Development/elk/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/patches/stronger_openssl_defaults.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /Users/nand/Development/elk/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/patches/stronger_openssl_defaults.rb:2
  require at org/jruby/RubyKernel.java:1040
   (root) at /Users/nand/Development/elk/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/patches.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /Users/nand/Development/elk/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/patches.rb:5
  require at org/jruby/RubyKernel.java:1040
   (root) at /Users/nand/Development/elk/logstash-2.4.0/lib/bootstrap/environment.rb:68

**Comment by original-brownbear** [comment]
@nandkv do you have any files in `/Library/Java/JavaVirtualMachines/jdk1.8.0_1001.jdk/Contents/Home/lib/ext` ? This like something on you system prevents JRuby's BouncyCastle jar to load.

**Comment by nandkv** [comment]
@original-brownbear no, but seems like it is related to to JDK instances. .profile has a $JAVA_HOME set but even after unsetting and running log stash it runs into same error. Ideally it would be good to use a bundled with idk and use that as runtime environment so that it doesn't rely on external JDK's which could be one to many on any given system.

**Comment by original-brownbear** [comment]
@nandkv 

>  no, but seems like it is related to to JDK instances. .profile has a $JAVA_HOME set but even after unsetting and running log stash it runs into same error.

what do you have set for `$JAVA_HOME` in your `.profile`? Unless you installed any custom libraries into the JDK under that path, we should be 100% portable here.
In your case `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home` should be the correct value here as far as I can tell.

> Ideally it would be good to use a bundled with idk and use that as runtime environment so that it doesn't rely on external JDK's which could be one to many on any given system.

I see the appeal of this, but I think this is somewhat unlikely to happen for licensing (but also other portability related) reasons.

**Comment by nandkv** [comment]
@original-brownbear here is what I have, which I had commented to test this out and also got rid of the .profile to see if there was any interference with the bcprov bundled as part of log stash.
#export JAVA_HOME=$(/usr/libexec/java_home)

In order to troubleshoot, I created another user and seems like that is not causing the same issue as above which leads me to believe that there is some conflict, but not sure what it is. 

I do have a complex dev setup and include Jenkins, artifactory, node, brew, apache and mysql, grails and rails setup on the user that is having this issue.

**Comment by original-brownbear** [comment]
@nandkv maybe the best solution in your case is to then simply run

```sh
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home bin/logstash
```

so that you don't have to tinker with the environment in a shared setup with multiple JVMs?

**Comment by nandkv** [comment]
@original-brownbear, are you suggesting to change this in bootstrap for log stash ?

**Comment by original-brownbear** [comment]
@nandkv not sure what you mean, but my suggestion was to simply change all scripting to prefix `bin/logstash` invocations with `JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`.
I guess you could also add this export to the `bin/logstash` script itself.

**Comment by nandkv** [comment]
@original-brownbear ah got it, not sure that would work either and seems like it doesn't.
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home bin/logstash
LoadError: load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/crypto/params/AsymmetricKeyParameter
  require at org/jruby/RubyKernel.java:1040
   (root) at /Users/nand/Development/elk/logstash-2.4.0/vendor/jruby/lib/ruby/shared/openssl.rb:1
  require at org/jruby/RubyKernel.java:1040

**Comment by original-brownbear** [comment]
@nandkv see solution here https://discuss.elastic.co/t/exception-while-starting-logstash-loaderror-load-error-jopenssl-load-java-lang-verifyerror-class-org-bouncycastle-asn1-asn1primitive-overrides-final-method-equals/51024/2 

That should do it :)

**Comment by nandkv** [comment]
Tried that too :-), in that case it is duplicate classes, but in my case it is no class def error, which is different.  You can close the issue, I will find a workaround by running this as a separate user to avoid conflicts with shared VMs.
