### ISSUE TITLE
data persistence

### ISSUE THREAD

**Issue by wudonghua** [elastic/logstash#7780]
I met a trouble,I want to take a file of data persistence in the logstash,
Such as a K-V file I want to replace in a field for each data in K-V
Have any good solution?
ruby filter plugins
For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by original-brownbear** [comment]
@wudonghua sorry, but this seems to be a general question and not a bug report. Those are better handled over at https://discuss.elastic.co/c/logstash 

Closing here.
