### ISSUE TITLE
Plugin installation behind authenticated proxy is not working in Logstash version 5.5.0

### ISSUE THREAD

**Issue by lkpatel** [elastic/logstash#7814]
I am trying to install logstash-filter-plugin behind authenticated proxy and failed to do so. So far I have used following methods
1. Setting environment variable HTTP[S]_PROXY does not work with following error
Command :  
JARS_SKIP='true' DEBUG=1 /usr/share/logstash/bin/logstash-plugin install logstash-filter-translate
Error:   
URI::InvalidURIError: bad URI(is not URI?): http://user:password@proxy.com:8080
                 split at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:176
                          parse at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:210
                          parse at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:747
                            URI at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:994
  extract_proxy_values_from_uri at /usr/share/logstash/lib/pluginmanager/proxy_support.rb:47
                configure_proxy at /usr/share/logstash/lib/pluginmanager/proxy_support.rb:69
                         (root) at /usr/share/logstash/lib/pluginmanager/main.rb:26

2a. Using Jruby J-Dhttp proxy settings is also not working
Command : 
JARS_SKIP='true' JRUBY_OPTS='-J-Dhttps.proxyHost=user:password@proxy.com -J-Dhttps.proxyPort=8080 -J-Dhttp.proxyHost=user:password:proxy.com -J-Dhttp.proxyPort=8080' DEBUG=1 /usr/share/logstash/bin/logstash-plugin install logstash-filter-translate
Error : 
DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install logstash-filter-translate
Looking if package named: logstash-filter-translate exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-translate/logstash-filter-translate-5.5.0.zip
Network error, skipping Elastic pack, exception: initialize: name or service not known
Validating logstash-filter-translate
Unable to download data from https://rubygems.org - SocketError: initialize: name or service not known (https://rubygems.org/latest_specs.4.8.gz)
ERROR: Installation aborted, verification failed for logstash-filter-translate
 
**On further diagnosis, I found that installer is sending a DNS query for "user:password@proxy.com" which is obviously failing due to malformed query.**
  
2b. Command : JARS_SKIP='true' JRUBY_OPTS='-J-Dhttps.proxyHost=proxy.com -J-Dhttps.proxyPort=8080 -J-Dhttps.proxyUser=user -J-Dhttps.proxyPassword=password -J-Dhttp.proxyHost=proxy.com -J-Dhttp.proxyPort=8080 -J-Dhttp.proxyUser=user -J-Dhttp.proxyPassword=password' DEBUG=1 /usr/share/logstash/bin/logstash-plugin install logstash-filter-translate
    Error: DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install logstash-filter-translate
Looking if package named: logstash-filter-translate exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-filter-translate/logstash-filter-translate-5.5.0.zip
Net::HTTPServerException: 407 "Proxy Authentication Required"
              error! at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2641
               value at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2650
             connect at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:796
            do_start at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:756
               start at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:745
               start at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:557
               start at /usr/share/logstash/lib/pluginmanager/utils/http_client.rb:13
  remote_file_exist? at /usr/share/logstash/lib/pluginmanager/utils/http_client.rb:31
   get_installer_for at /usr/share/logstash/lib/pluginmanager/pack_fetch_strategy/repository.rb:32
              create at /usr/share/logstash/lib/pluginmanager/install_strategy_factory.rb:18
                each at org/jruby/RubyArray.java:1613
              create at /usr/share/logstash/lib/pluginmanager/install_strategy_factory.rb:17
             execute at /usr/share/logstash/lib/pluginmanager/install.rb:30
                 run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
             execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                 run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                 run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
              (root) at /usr/share/logstash/lib/pluginmanager/main.rb:48

**Somehow, in this scenario it is not taking username and password settings.**
I tried older version too with no luck. Please guide me where I am wrong.

Regards
Lalit

**Comment by lkpatel** [comment]
I provided proxy settings directly to file [LOGSTASH_HOME]/vendor/jruby/lib/ruby/1.9/net/http.rb and problem solved

**Comment by qq351844** [comment]
Hi,

Can you tell me which setting section do you change ?
I directly to change http.rb this class
`
def HTTP.Proxy(p_addr, p_port = nil, p_user = nil, p_pass = nil)
      j_addr = ENV_JAVA['http.proxyHost']
      j_port = ENV_JAVA['http.proxyPort']
      p_addr = p_addr || j_addr
      p_port = p_port || j_port
      return self unless p_addr
      delta = ProxyDelta
      proxyclass = Class.new(self)
      proxyclass.module_eval {
        include delta
        # with proxy
        @is_proxy_class = true
        @proxy_address = 'my_proxy_addr'
        @proxy_port    = 'my_proxy_port'
        @proxy_user    = 'my_proxy_user'
        @proxy_pass    = 'my_proxy_pass'
      }
      proxyclass
    end
`
And then, I  use instruction ./logstash-plugin install logstash-codec-nmap
But I got this message
ERROR: Something went wrong when installing logstash-codec-nmap, message: certificate verify failed

**Comment by lkpatel** [comment]
I edited "vendor/jruby/lib/ruby/1.9/net/http.rb". Actually I defined proxy as env variable by using export command with username and password info(I am behind auth proxy), because in my case somehow logstash failed to acquire username and password from env proxy settings. So I provided username and password settings directly into http.rb file at line number 786( just below code is proxy ? code segment). Hope the same will work for you too.

**Comment by qq351844** [comment]
Hi, 
This is my error
```
 DEBUG=1 JARS_SKIP='true' ./logstash-plugin install logstash-codec-nmap
DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install logstash-codec-nmap
Looking if package named: logstash-codec-nmap exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-codec-nmap/logstash-codec-nmap-5.5.1.zip
proxyNet::HTTPServerException: 407 "Proxy Authentication Required"
              error! at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2643
               value at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2652
             connect at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:798
            do_start at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:756
               start at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:745
               start at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:557
               start at /usr/share/logstash/lib/pluginmanager/utils/http_client.rb:13
  remote_file_exist? at /usr/share/logstash/lib/pluginmanager/utils/http_client.rb:31
   get_installer_for at /usr/share/logstash/lib/pluginmanager/pack_fetch_strategy/repository.rb:32
              create at /usr/share/logstash/lib/pluginmanager/install_strategy_factory.rb:18
                each at org/jruby/RubyArray.java:1613
              create at /usr/share/logstash/lib/pluginmanager/install_strategy_factory.rb:17
             execute at /usr/share/logstash/lib/pluginmanager/install.rb:30
                 run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
             execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                 run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                 run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
              (root) at /usr/share/logstash/lib/pluginmanager/main.rb:48
```

I add the env variable like this:
```
JRUBY_OPTS="-J-Dhttp.proxyHost=my.proxyHost -J-Dhttp.proxyPort=my.proxyPort"
```
and the  code  at that segment:
```
if proxy_user
              print "proxy user"
              credential = ["myproxyUser:myproxyPass"].pack('m')
              credential.delete!("\r\n")
              @socket.writeline "Proxy-Authorization: Basic #{credential}"
            end
```

But I still get the message proxyNet::HTTPServerException: 407 "Proxy Authentication Required"

Thanks~

**Comment by lkpatel** [comment]
See I defined environment proxy variable using command 
export http_proxy=http://host.com:8080/
export https_proxy=http://host.com:8080/
Then I added 
proxy_user ='username'   
proxy_pass='passwd'
in file vendor/jruby/lib/ruby/1.9/net/http.rb just below line number 786
I am using logstash 5.5 also I am not using JRUBY_OPTS

**Comment by qq351844** [comment]
I try your method
And I get this message
```
 DEGUB=1 ./logstash-plugin install logstash-codec-nmap
ERROR: Something went wrong when installing logstash-codec-nmap, message: certificate verify failed

```

I think , that is my proxy problem.
Thank your for your help!!

**Comment by rahulsinghai** [comment]
ELK version: 6.2.4

Got similar issue and the reason was that my password contained `@` character.
When we set proxy settings as:
```
export HTTP_PROXY="http://proxy_user:P%40ssword@your.company.proxy.server:80"
```
, passing ASCII encoding for the special character does not work, as Ruby itself tries to encode special chars after [c355880](https://github.com/rubygems/rubygems/commit/c355880f2016597b3f0f632fbcdc688313052009) and we get `HTTPServerException: 407 "Proxy Authentication Required"`

This is what worked for me:
Instead of passing user password in HTTP_PROXY, pass it as a separate environment variable:
```
export HTTP_PROXY="http://your.company.proxy.server:80"
export HTTP_PROXY_USER="proxy_user"
export HTTP_PROXY_PASS="P@ssword"
export NO_PROXY="127.0*,[::1],localhost"
```
