### ISSUE TITLE
Accessors.java has a subtle bug as it back-fills objects when setting a deep FieldReference value.

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#7817]
Found while investigating https://github.com/logstash-plugins/logstash-filter-geoip/issues/125

Imagine a user with new Event uses `add_field` to set this `"[foo][0][bar][1]" => "baz"` - Accessors in `findCreateTarget` will not create the correct kind of parent collections for each intended element in the FieldReference path and key.

At the start of `findCreateTarget` target is the Event data Map (a ConvertedMap, mostly, except in the empty ctor)
Iterating over `"[foo]", "[0]", "[bar]", "[1]"` we do:
```
Iterate over `"[foo]", "[0]", "[bar]", "[1]"` as key
  result = fetch(target, "[foo]") // -> null
  if result is null
    result = new HashMap<String, Object>()
    if target is Map
      target.put key, result
    else if target is List
      i = parseInt(key)
      target.set(i, result)
    else
      exception
    end
  end
  target = result
end
```
Bug no. 1 - HashMap should be a ConvertedMap (I missed this when implementing BiValues)
Bug no. 2 - when result is null we need to create a ConvertedMap if the key looks like a string and a ConvertedList if the key looks like a number.

**Comment by guyboertje** [comment]
Not sure about backporting? 6.0.0|6.0.1, 5.6.0|5.5.2, 5.4.3?

**Comment by guyboertje** [comment]
Further, if the user adds a field like this `"[0]" => "foo"`, foo ends up as a value in the data Map under the String key `"0"`.
Should we allow this or throw an exception?

**Comment by original-brownbear** [comment]
@guyboertje @jsvd summing up our discussion just now:

> Bug no. 1 - HashMap should be a ConvertedMap (I missed this when implementing BiValues)

Agreed, trivial fix :)

> Bug no. 2 - when result is null we need to create a ConvertedMap if the key looks like a string and a ConvertedList if the key looks like a number.

The way I understood our discussion we're postponing this one until we have an answer to the next point.

> Further, if the user adds a field like this "[0]" => "foo", foo ends up as a value in the data Map under the String key "0".

As discussed, this will break things and we need some feedback here from @suyograo or @jordansissel before we do anything.

> Not sure about backporting? 6.0.0\|6.0.1, 5.6.0\|5.5.2, 5.4.3?

Here we also need some feedback.

**Comment by guyboertje** [comment]
About bug no. 2.
What we need to consider is:
There are two different mechanisms of creating deep structures in the Event.
1. when e.g. JSON codec creates an Event from a deep rich JSON objects or the e.g. translate filter adds a deep structure to an existing event, the intermediate objects will be Maps or Lists.
2. when a deep structure is created with add_field using `"[foo][0][bar][1]" => val` all the intermediate objects areare back filled as Maps even though there is an implicit understanding in the field reference of a mixed structure.

We need to discuss whether we want to change this so there is consistency between the two mechanisms.

**Comment by guyboertje** [comment]
As an alternative idea, what if we added a `add_json_field` function that meant that a user can create an arbitrary structure using a JSON string with or without `%{}` dynamics.

**Comment by original-brownbear** [comment]
fixed in https://github.com/elastic/logstash/pull/7823 :)
