### ISSUE TITLE
how to update nests field by filter ruby event

### ISSUE THREAD

**Issue by yangdailin** [elastic/logstash#7818]
- Version: 2.3.4
- Operating System:windows7
- Config File (if you have sensitive info, please remove it):
filter {
 	ruby {
			code => 'event[cpu][user] = 123'
        }
}
- Sample Data:
{
       cpu => {
             "user" => "xxx",
             "system" => "xxx"
       }
}
- Steps to Reproduce:
hello. as you see, how can i update cpu.user by ruby event.I found use event[cpu][user] = 123 will cause ruby exception.but use event[cpu] = 123 will right. is this version not support get/set nests fields?

**Comment by andrewvc** [comment]
Thanks for using logstash! However, This is the Logstash bug tracker, not our support forum. Please ask any support questions in our support forum here: https://discuss.elastic.co/c/logstash .
