### ISSUE TITLE
DLQ Writer `close` Shouldn't be Synchronized

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7824]
`synchronized` `close()` methods are kind of a nasty anti-pattern as explained here https://github.com/elastic/logstash/pull/7822/files#r129673727.

You simply don't want to block threads on concurrent `close()` when handling exceptions.
I think securing this by an `AtomicBoolean` (details here https://github.com/elastic/logstash/pull/7822/files#r129673727) is a much safer approach and we should refactor this.

**Comment by original-brownbear** [comment]
cc @robbavey

**Comment by liketic** [comment]
@original-brownbear Seems like this has been fixed. Should be closed?

**Comment by original-brownbear** [comment]
@liketic right thanks!
