### ISSUE TITLE
add lumberjack output to default plugins

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#7835]
We should add lumberjack output plugin back to the default plugins for LS -> LS communication before we have a formal beats output. I also need to add this back to the supported list.

@suyograo can you add this? I'll take care of the matrix.

**Comment by jordansissel** [comment]
I'd rather us write a beats output. The lumberjack output hasn't been maintained in a long time (nearly 1 year).

If you really want to do this, it needs to be tested. And if we are adding it, does this open new feature requests for the lumberjack output? Or are we going to defer everything based on a new beats output?

**Comment by acchen97** [comment]
@jordansissel we don't need to entertain new features to the lumberjack output. This will be a stopgap solution until we have a beats output.

**Comment by suyograo** [comment]
I'd rather not add Lumberjack output to the default plugins. Folks who need this can install it anyway. Also, when we have the beats output we can include it in the default plugins. That way we don't have to wait until 7.0 to remove lumberjack when we have beats output.

**Comment by acchen97** [comment]
++ ok sounds reasonable.
