### ISSUE TITLE
Metrics API response can be very slow

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7857]
Calling into any of the metrics API calls, the http response can be very slow. 5+ seconds.

This slowness is happening due to a call to ```Socket.gethostname``` for every http request.  

For example:
```
time curl -v -XGET 'localhost:9600/_node/stats/pipelines?pretty'
```
```
real	0m5.155s
user	0m0.006s
sys	0m0.006s
```

**Comment by suyograo** [comment]
Related: https://github.com/elastic/logstash/issues/6520
