### ISSUE TITLE
Metrics: Consistent serialization

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7885]
Currently the metrics are only serialized if the value is set.  This can lead to some surprising behavior if as a consumer, you expect the value to be present. 

To complicate matters, some, but not all metrics are pre-initialized creating a mix of zero/null and missing metrics in the JSON output. 

This issue is to explicitly change the serialization to ALWAYS serialize the known metrics. This is only possible with the changes over at #7788   

Part of this change should be to remove the deprecated `dirty` flag, whose sole purpose is to lazily serialize the data.

**Comment by jakelandis** [comment]
@andrewvc / @original-brownbear 
The existing PR is does does not take in account the DLQ and PQ metrics. _(They are not represented by the Witness code yet, PR coming soon)._

We discussed the zero/null vs. missing, and agree the decision to simply always show those metrics. 

However, for DLQ and PQ, since those metrics are driven by a configuration, should we continue to flex their output. 

**For DLQ and PQ should we (continue to) hide the zero/null/empty metrics when they are not enabled?**

**Comment by original-brownbear** [comment]
@jakelandis @andrewvc imo yes, we shouldn't show metrics for functionality that isn't enabled.
