### ISSUE TITLE
Environment variable `HOSTNAME` is not set

### ISSUE THREAD

**Issue by eastokes** [elastic/logstash#7901]
- Version: 5.2.0 and 5.5.1
- OS: Ubuntu 14.04

I have this in my logstash pipeline filters config:
```
mutate {
  add_field => [ "logstash_hostname", "logstash-${HOSTNAME}" ]
}
```

Which returns this:
`[ERROR][logstash.agent] Cannot create pipeline {:reason=>"Cannot evaluate `${HOSTNAME}`. Environment variable `HOSTNAME` is not set and there is no default value given."}`

`echo $HOSTNAME` returns my hostname

Logstash adds the field when I specify `${HOSTNAME:undefined}`, but obviously it fills it with `undefined`.

**Comment by andrewvc** [comment]
This is probably because you're running logstash as a service from a [non-login shell](http://www.learnlinux.org.za/courses/build/shell-scripting/ch02s02.html). You'll need to set that environment variable explicitly.

If that is not the case, and this bug occurs when running `bin/logstash` directly in your terminal, please let us know here in this ticket.

**Comment by jenskanis** [comment]
I'm running into the same issue when running `bin/logstash` directly. Logstash 5.5.1. Ubuntu 14.04.

**Comment by andrewvc** [comment]
@jenskanis if you run `echo $HOSTNAME` directly does that work?

**Comment by jenskanis** [comment]
@andrewvc that works fine.

**Comment by jenskanis** [comment]
This is how my config looks like, might that help:

`
input {
  jdbc {
    jdbc_connection_string => "jdbc:sqlite:${LOGSTASH_DATABASE}"
    jdbc_user => ""
    jdbc_driver_library => "/home/jens/Documents/drivers/sqlite-jdbc-3.20.0.jar"
    jdbc_driver_class => "org.sqlite.JDBC"
    statement => "SELECT * from '${LOGSTASH_TABLE}'"
    type => "DB ${LOGSTASH_TABLE}"
  }
}`

Of course I tested this without environment variables, which works fine.

**Comment by andrewvc** [comment]
@jenskanis I can't repro this. Can you try executing the command below and telling me what you see?

`bin/logstash -e 'input { generator { message => "Hello from ${HOSTNAME}" count => 10 } } output { stdout { codec => json_lines} }'`

For me, this works

**Comment by andrewvc** [comment]
Also, please include your logstash version.

**Comment by jenskanis** [comment]
@andrewvc I just found the solution. I was running `bin/logstash` as root (with `sudo`) instead of the user. Sorry about that. That might be your problem as well @eastokes.

**Comment by andrewvc** [comment]
@jenskanis thanks for updating the issue :) 

I'm going to close this given that there's no bug here.

**Comment by njvack** [comment]
For what it's worth, I'm banging my head against this as well. I'm on ubuntu 14.04, and installed logstash via the repository, which puts logstash (a shell script) in `/usr/share/logstash/bin`.

I instrumented it to echo `${HOSTNAME}` in several places, and found that it was always blank. Then I changed the shebang line from `#!/bin/sh` to `#!/bin/bash` and it echoed my hostname correctly. However, I still get:

```
$ echo ${HOSTNAME}
zin
$ /usr/share/logstash/bin/logstash -e 'input { generator { message => "Hello from ${HOSTNAME}" count => 10 } } output { stdout { codec => json_lines} }' --path.settings=/etc/logstash/logstash.yml
Hostname at start is zin
Hostname before setup is zin
Hostname after setup is zin
Hostname at exec is zin
WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
Could not find log4j2 configuration at path /etc/logstash/logstash.yml/log4j2.properties. Using default config which logs errors to the console
[ERROR] 2017-10-17 13:25:38.393 [LogStash::Runner] agent - Cannot create pipeline {:reason=>"Cannot evaluate `${HOSTNAME}`. Environment variable `HOSTNAME` is not set and there is no default value given."}
```

Still need to debug why it says it can't find logstash.yml when

```
$ ls -l /etc/logstash/logstash.yml
-rw-r--r-- 1 root root 5806 Oct 16 10:44 /etc/logstash/logstash.yml
```

...baby steps

Any ideas as to how the env variable might not be getting passed along into logstash? I'm 100% baffled.

**Comment by andrewvc** [comment]
How are you defining the variable? Are you aware of how [`export`](https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export) works?

**Comment by njvack** [comment]
Wowza. Now I come back and everything is working fine. Like, no problem at all. This was in a new shell.

The only thing I can imagine is that I'd sourced a script that was setting environment variables, that needed some quotes added. Maybe it somehow subtly hosed up my shell earlier.

Anyhow, please disregard my earlier message; everything looks like it's working like it should. Thanks!
