### ISSUE TITLE
"Working with Filebeat Modules" doc page enhancements

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#7914]
Let's soften the verbiage in [this section](https://www.elastic.co/guide/en/logstash/current/filebeat-modules.html#graduating-to-Logstash). I'd suggest we change this to "Introducing Logstash" or "Using Logstash Instead of Ingest Node".

Also, for 6.0+ we should find a good place here to link off to the new ingest pipeline migration tool docs that we create.

/cc @dedemorton

**Comment by dedemorton** [comment]
Closed by #8399
