### ISSUE TITLE
Pipelines plugin metrics may dissappear

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7925]
When removing and adding back an input, input plugins will disappear from the metrics.  
Use -r so that the pipelines will reload.

Start:
```
input { 
	heartbeat { interval => 30 }  
	tcp {    port => 55115	}
}
filter { } 
output { stdout { codec => rubydebug } }
```

Remove  `tcp {    port => 55115	}`:

```
input { 
	heartbeat { interval => 30 }  
}
filter { } 
output { stdout { codec => rubydebug } }
```

Let it reload.

Add it back:
```
input { 
	heartbeat { interval => 30 }  
	tcp {    port => 55115	}
}
filter { } 
output { stdout { codec => rubydebug } }
```

`curl -XGET 'localhost:9600/_node/stats/pipelines?pretty'`

Now the inputs is gone:

```
    "plugins" : {
        "inputs" : [ ],
        "filters" : [ ],
        "outputs" : [ ]
      },
```
Note the other plugin types may have this issue too, but I have not tested. 

Note - the behavior on 5.5 was correct.

**Comment by jsvd** [comment]
I confirmed this is present in a recent 6.0 branch commit https://github.com/elastic/logstash/commits/563d572, and not present in alpha2 (https://github.com/elastic/logstash/commit/db9ab809a7ceaa0929a4fa50034ce013d699bfc4)

**Comment by jsvd** [comment]
@jakelandis your guess was right, reverting commit https://github.com/elastic/logstash/commit/9b4d7c51aeba2b1e009bbf42f45df4f0afbddf66 made the issue go away

**Comment by jakelandis** [comment]
@jsvd - OK lets commit that revert, with the changes over at #7904 the changes on https://github.com/elastic/logstash/commit/9b4d7c51aeba2b1e009bbf42f45df4f0afbddf66 become much less important.  

I can push revert (to multiple code branches) with your +1.
