### ISSUE TITLE
Minor: Refactor BiValues.RUBY

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7951]
We currently cache the Ruby global runtime in a static variable inside in the `BiValues` class.

```java
public static final Ruby RUBY = Ruby.getGlobalRuntime();
```

The Ruby global runtime isn't really an attribute of the `BiValues` and should be moved to somewhere more global. It still needs to be cached statically, for performance reasons. 

I would suggest the following:

```java
package org.logstash;

public interface Ruby {
    org.jruby.Ruby RUNTIME = org.jruby.Ruby.getGlobalRuntime();

    static org.jruby.Ruby getGlobalRuntime(){
        return RUNTIME;
    }
}
```

Usually I am not a fan of mirroring names/methods, but in this case I think it makes sense. 

cc @original-brownbear

**Comment by original-brownbear** [comment]
fixed in #7957
