### ISSUE TITLE
Complete replacement of Ruby metrics / metrics namespaces in 6.1 ?

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7971]
I am currently working on the Java-fication for recording the metrics #7788. This is essentially a replacement of the Ruby metrics / metrics namespace API. 

It was always my intention to completely remove the Ruby metrics / metrics namespaces for 7.x, but use a bridge strategy ([mapping namespaces -> witness](https://github.com/jakelandis/logstash/blob/domain-metrics-bak4/logstash-core/lib/logstash/instrument/metric_type/witness_adaptor.rb)) for 6.x.  

This was out of concern for passivity w/r/t to the Ruby metrics API. However, due to lack luster performance of the bridge,  complexity of maintaining two subsystems that do the same thing, and lack of publicly documenting the Ruby metrics / metrics namespace API... I would like to solicit approval to completely remove the Ruby metrics / metrics namespaces for the 6.1 release.  

-----------
Additional relevant information:

Thus far I have:
* Replaced the underlying counters and guage state with Java objects (6.0)
* Added a `Witness` API in Java as alternative/abstraction to working directly with the underlying counters/gauges for the stats namespace. _(in review, still need to do the JVM namespace)_
* Moved the JSON serialization from Ruby to Java _(soon to be in review)_
* Created a metric namesapce -> `Witness` bridge that maps the Ruby metrics/namspace to the Java `Witness` API.  _(not reviewed yet)_

This bridge strategy has allowed me to replicate the recording of the :stats namespace with minimal (almost no) changes to the existing Ruby code (e.g. pipelines/agents/etc. still express their metrics in terms of a namespace). I even have the rspecs to passing locally with very minor changes using the bridge code. However ....**performing the conversion from a Ruby namespace to a  `Witness` regresses any performance gains made recently to the metrics subsystem.** 

So, the decision to update the Ruby code to use the new API directly (instead of going through the bridge) is easy. 

...but once I update all the Ruby code to the new API, that leaves the Ruby metrics / metrics namespaces code just sitting there in case someone's plugins leveraged it. 

This plugin strategy for metrics is TBD, but irregardless, I will need to visit each supported plugin and update _some code somewhere_ to properly support those metrics.

**Comment by suyograo** [comment]
We should go straight to the new API to reduce the complexity here. I know this breaks existing Ruby metrics API but this was never advertised as an API and it was all internal. Having a sub par API (wrt performance) is not worth it. There are only a few plugins that use this metrics API to record stats. 

We just need to make sure that the JSON output for the REST APIs doesn't change in 6.x. There are external tools which depend on the format/fields of the monitoring API.

**Comment by jakelandis** [comment]
Closing.  6.1 will not carry forward the internal namespace API, but will preserve the JSON API.
