### ISSUE TITLE
Metrics: Adopt oshi library for OS level metrics ?

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7978]
As part of the Java-fication of the metrics subsystem we should consider moving the OS level metrics into the Java space. 

I have used https://github.com/oshi/oshi in a past project and found it be quite good. A few of the API's are a bit rough around the edges, but the underlying functionality is solid.  

Thoughts ?

**Comment by jakelandis** [comment]
Possible argument for outsourcing the OS metric collection: https://github.com/elastic/logstash/issues/6824

**Comment by andrewvc** [comment]
Would getting this to produce identical output be hard?

Our current OS level metrics code may not be great, but it is stable. What are the benefits of outsourcing this?

**Comment by jordansissel** [comment]
Another option, if it is not best to keep doing what we are alreayd doing, is to copy what Elasticsearch is doing for this same problem.

**Comment by andrewvc** [comment]
They just use the MAX beans directly as we do. They used to use Sigar but
ripped it out

**Comment by suyograo** [comment]
+1 on using ES approach since we have some in-house expertise with that code. Unless the `oshi` library brings in measurable gains in performance/maintenance or others.

**Comment by jakelandis** [comment]
I am not familiar with what ES does, so I can not comment there...

However, some of the reasons to consider outsourcing OS level metrics (e.g. consume a 3rd party library):

* Better support for more operating systems, vetted by larger community.  
* Readily available additional metrics. 

While `oshi` is performance consciousness, I doubt that they are measurably faster then any custom approach we take. Under the hood they work the same way (there are only so many ways to get these numbers). 

W/R/T to the JSON output, it would not change, any library would just be used to gather the metrics, and we would continue to serialize with the same structure today. 

For example, if using `oshi` we could add any one of these [cpu metrics](http://oshi.github.io/oshi/apidocs/oshi/hardware/CentralProcessor.html) fairly easily without needing to fully understand how the underlying platform is implemented (only test that it works correctly). Open file descriptors [api](http://oshi.github.io/oshi/apidocs/oshi/json/software/os/FileSystem.html), Network IO [api](http://oshi.github.io/oshi/apidocs/oshi/hardware/NetworkIF.html)...  many [more](http://oshi.github.io/oshi/apidocs/) 

For me, it depends on the future vision for the role of OS level metrics via this API. _Some_ work in this area will need to be done to move these to metrics to Java, and want to ensure that work is properly aligned.

 I think this a good opportunity to ask, **what is the role of the OS level metrics via Logstash API ?**  (for 7.x+) _Deprecate it in favor of metric beat ? Keep the functionality as-is ? Expand it's role ?_

**Comment by jordansissel** [comment]
> Better support for more operating systems, vetted by larger community.

We only support Windows and some Linux distributions. More OS's can be better, but it is not required.

> what is the role of the OS level metrics via Logstash API 

This is a fair question. I have a longer answer, but maybe that's best answered in a separate issue if you want to file that?

**Comment by ph** [comment]
I would prefer we keep our in house solution (even not perfect) and talk directly to the MX beans, Our current need are still minimal and I don't think we would benefit from using an external libraries or dependencies.

**Comment by jakelandis** [comment]
Thanks for the comment. Closing issue.

Seems to be consensus to leave the OS level metrics in-house. 

New question posed: https://github.com/elastic/logstash/issues/8048
