### ISSUE TITLE
Exit on OutOfMemoryError's 

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7987]
http://www.oracle.com/technetwork/java/javase/8u92-relnotes-2949471.html

> ExitOnOutOfMemoryError - When you enable this option, the JVM exits on the first occurrence of an out-of-memory error. It can be used if you prefer restarting an instance of the JVM rather than handling out of memory errors.

We should default the `-XX:ExitOnOutOfMemoryError` in the config\jvm.options.  This will help prevent application code from accidentally handling this type of fatal error. Strange behavior can occur when a JVM has encountered OOM but keeps trying to run.

**Comment by colinsurprenant** [comment]
+1

also related to https://github.com/logstash-plugins/logstash-input-beats/issues/253

**Comment by original-brownbear** [comment]
fixed in #8138

**Comment by jordansissel** [comment]
This needs to be reverted until the support matrix requires Java 8u92 or newer (we currently require Java 8u60).  I opened #8254 to track.

**Comment by jakelandis** [comment]
Re-opening until we support Java 8u92 as a min. 

This change is reverted https://github.com/elastic/logstash/pull/8268.
