### ISSUE TITLE
Bump plugins to get latest documentation changes

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7993]
We've made some documentation changes in most plugins, and in order for those docs changes to ship with 5.6.0, we need to release every plugin that's had a docs change.

We didn't notice this in time for the 5.5.0 release, and on release day, we (mostly @dedemorton's hard work) do a lot of contortions in order to get the docs updated. It was manual and difficult work.

This is a blocker for 5.6.0 because I'm not going through that pain again :)

**Comment by jordansissel** [comment]
The tooling we have right now (thanks, @ph!) has certain expectations about how the plugin version is written, and there are a handful of plugins that use a different versioning system than the rest of the plugins

I'm going to try and fix that before moving forward on this. I'll keep this updated as I progress.

**Comment by jordansissel** [comment]
```
% egrep "version += +[^'\"][^0-9]" tmp/*/*gemspec  | fex /2 ':{2:}'
logstash-filter-dissect   s.version = DISSECT_VERSION
logstash-filter-useragent   s.version         = :File.read('version').split("\n").first
logstash-input-beats   s.version         = BEATS_VERSION
logstash-input-kinesis   spec.version       = Logstash:Input:Kinesis:VERSION
logstash-input-tcp   s.version       = :File.read('version').split("\n").first
```

The rest use `s.version = 'some version string'`.

**Comment by jordansissel** [comment]
https://github.com/jordansissel/logstash-mass_effect/tree/version-bumper

**Comment by jordansissel** [comment]
Patches pushed to branches, here's a sample:

* [ ] https://github.com/logstash-plugins/logstash-input-beats/pull/254
* [ ] https://github.com/logstash-plugins/logstash-codec-cef/pull/47
* [ ] https://github.com/logstash-plugins/logstash-input-file/pull/160

**Comment by jordansissel** [comment]
@jsvd Can you take a look at some of these branches in the above comment? 

I'm going to spot check a few others. All plugins should now have a `patch-test` branch that has the same changes applied (version bump + changelog). 

Next steps:

1) [ ] Get these patches merged in plugins
2)  [ ] Publish all plugins
3) [ ] Update Logstash 5.6 branch's gem lock to target new plugins

**Comment by jsvd** [comment]
@jordansissel the test PR's look good, same for your version-bumper branch.

One thing to note is that [several plugins](https://github.com/elastic/logstash/issues/7740) had their  major versions bumped, and these will only be included in Logstash 6.0

For all of these it's necessary to branch off of the latest release tag and bump that branch.

We can see the major versions of plugins used by 5.5.1 by running the command below in 
`bin/logstash -i irb` (we should be able to use `bin/ruby` but I couldn't get Bundler to set up correctly:

`Bundler.environment.specs.select {|spec| spec.metadata["logstash_plugin"] == "true" }.map {|spec| [spec.name, spec.version.segments[0] ].join(",")}`

From here we should be able to fetch the latest patch or minor release tag in each plugin repo, branch from there, and execute your bump_version

**Comment by jordansissel** [comment]
@jsvd yeah I had that thought; thank you for verifying! I'm expecting this to be a bit of a battle given the docs changes may have landed only in the new majors, but I will find out soon.

**Comment by jordansissel** [comment]
I'm pushing all the current changes to plugins now.

Next step will be to do the same patch bumps on all plugin minor versions targeted for Logstash 5.6

**Comment by jordansissel** [comment]
174 plugins published successfully. The remainder failed:

 * FAIL: logstash-filter-geoip bundle exec rake vendor

SHA1 does not match (expected '5f1d57e747b06e4c40a34db8dbb5b04651434ffd' but got '327fb6545e9fa6a632b6c791eea77f47a988a4ab')
/home/jls/.rbenv/versions/jruby-1.7.26/bin/bundle:23:in `(root)'

 * FAIL: logstash-filter-kubernetes_metadata bundle exec rake publish_gem

No permission to publish gem: https://github.com/logstash-plugins/logstash-filter-kubernetes_metadata/issues/4

 * FAIL: logstash-filter-language bundle install

Dependency compilation failure: https://github.com/logstash-plugins/logstash-filter-language/issues/2

 * FAIL: logstash-input-ganglia bundle exec rspec

Specs failing: https://github.com/logstash-plugins/logstash-input-ganglia/issues/21
 * FAIL: logstash-input-graphite bundle exec rspec
 * FAIL: logstash-input-jmx bundle exec rake publish_gem
 * FAIL: logstash-input-rabbitmq bundle exec rake publish_gem
 * FAIL: logstash-input-rackspace bundle exec rake publish_gem
 * FAIL: logstash-input-redis bundle exec rake publish_gem
 * FAIL: logstash-input-relp bundle exec rake publish_gem
 * FAIL: logstash-input-rss bundle exec rake publish_gem
 * FAIL: logstash-input-zeromq bundle exec rspec
 * FAIL: logstash-integration-zeromq bundle exec rspec
 * FAIL: logstash-mixin-zeromq bundle exec rspec
 * FAIL: logstash-output-datadog_metrics bundle exec rspec
 * FAIL: logstash-output-elasticsearch_java bundle exec rspec
 * FAIL: logstash-output-elasticsearch bundle exec rspec
 * FAIL: logstash-output-exec bundle exec rspec
 * FAIL: logstash-output-hipchat bundle exec rspec
 * FAIL: logstash-output-jms bundle exec rspec
 * FAIL: logstash-output-kafka bundle exec rspec
 * FAIL: logstash-output-lumberjack bundle exec rspec
 * FAIL: logstash-output-neo4j bundle exec rspec
 * FAIL: logstash-output-zeromq bundle exec rspec
 * FAIL: logstash-output-zookeeper bundle exec rspec

**Comment by jordansissel** [comment]
Manual corrections for things missed by automation:

* Somehow the Elasticsearch output didn't get a tag (v8.0.1). Fixed.
* logstash-codec-cef tag v5.0.1

**Comment by jordansissel** [comment]
Missing tags:

```
% grep "version *= *'"  */*gemspec| fex :1/1 \'2 | xargs -n2 sh -c 'if git -C $1 tag | grep -qF $2 ; then echo OK $1; else echo MISSING $1 $2; fi' - | less | grep MISSING
MISSING logstash-filter-geoip 5.0.1
MISSING logstash-filter-kubernetes_metadata 1.0.5
MISSING logstash-filter-language 0.1.2
MISSING logstash-input-graphite 3.0.4
MISSING logstash-input-jmx 3.0.3
MISSING logstash-input-zeromq 3.0.4
MISSING logstash-integration-zeromq 0.1.2
MISSING logstash-mixin-zeromq 3.0.3
MISSING logstash-output-datadog_metrics 3.0.2
MISSING logstash-output-elasticsearch_java 2.1.5
MISSING logstash-output-exec 3.1.2
MISSING logstash-output-hipchat 4.0.4
MISSING logstash-output-jms 3.0.2
MISSING logstash-output-kafka 7.0.1
MISSING logstash-output-lumberjack 3.1.5
MISSING logstash-output-neo4j 2.0.6
MISSING logstash-output-zeromq 3.1.2
```

**Comment by jordansissel** [comment]
* geoip filter manually published (`gem build *gemspec; gem push logstash-filter-geoip-5.0.1-java.gem`)

**Comment by jordansissel** [comment]
* elasticsearch output manually published (% gem push logstash-output-elasticsearch-8.0.1-java.gem)

**Comment by jsvd** [comment]
Here's the list of plugins that are locked in a major different than the most recent rubygems version:

| plugin | locked version | latest published major | newer compatible gem | newer compatible tag |
| -- | -- | -- | -- | -- |
| logstash-codec-cef | 4.1.3 | 5 | - | - |
| logstash-filter-geoip | 4.2.1 | 5 | 4.3.0 | v4.3.0 |
| logstash-input-beats | 3.1.23 | 5 | - | - |
| logstash-input-tcp | 4.1.2 | 5 | 4.2.2 | v4.2.2 |
| logstash-input-http_poller | 3.3.1 | 4 | - | - |
| logstash-input-kafka | 5.1.8 | 8 | - | - |
| logstash-input-rabbitmq | 5.2.4 | 6 | - | - |
| logstash-output-elasticsearch | 7.3.7 | 8 | 7.3.8 | v7.3.8 |
| logstash-output-http | 4.3.2 | 5 | - | - |
| logstash-output-kafka | 5.1.7 | 7 | - | - |
| logstash-output-rabbitmq | 4.0.9 | 5 | - | - |
| logstash-output-redis | 3.0.4 | 4 | - | - |
| logstash-output-sqs | 4.0.2 | 5 | - | - |
| logstash-output-tcp | 4.0.1 | 5 | - | - |

**Comment by jordansissel** [comment]
Published via jarvis publish command:

* https://rubygems.org/gems/logstash-codec-cef/versions/4.1.4-java
* https://rubygems.org/gems/logstash-input-beats/versions/3.1.24-java
* https://rubygems.org/gems/logstash-filter-geoip/versions/4.3.1-java

Then Jarvis' EC2 instance froze, so I started publishing manually with this script:

```sh
#!/bin/sh

set -e

plugin=$1
branch=$2

if [ ! -d "$plugin" ] ; then
  git clone "git@github.com:/logstash-plugins/$plugin"
fi

cd "$plugin"
git fetch
git checkout "$branch"
git pull --ff-only

git clean -fd
git checkout .

bundle install
bundle exec rake vendor
bundle exec rake publish_gem
```

* logstash-input-tcp-4.2.3-java.gem
* logstash-input-http_poller-3.3.2.gem
* logstash-input-kafka-5.1.10.gem
* logstash-input-rabbitmq-5.2.5.gem
* logstash-output-http-4.3.4.gem
* logstash-output-kafka-5.1.9.gem
* logstash-output-rabbitmq-4.0.10-java.gem
* logstash-output-redis-3.0.5.gem
* logstash-output-sqs-4.0.3.gem
* logstash-output-tcp-4.0.2.gem

**Comment by jordansissel** [comment]
Ok I get GC Overhead exceptions when I use Bundler 1.15.3, but if I downgrade to bundler 1.9.10, `rake generate_plugins_version` succeeds on @suyog's #8031 PR so far -- will continue testing.

**Comment by jordansissel** [comment]
docs generated for review: https://github.com/elastic/logstash-docs/compare/5.6...sample-docgen-5.6

**Comment by jordansissel** [comment]
@dedemorton @suyograo I could use your help reviewing the documentation produced by this PR -- https://github.com/elastic/logstash-docs/pull/407

**Comment by jordansissel** [comment]
Using the manual fixes from @dedemorton, the following plugins need investigation and resolution:

```
% git show | grep '^diff' | fex 3/'{2:}' | xargs -n1 sh /tmp/patch-plugins.sh |& tee /tmp/x
logstash-codec-rubydebug v3.0.3
logstash-filter-hashid v0.1.2
logstash-input-graphite v3.0.3
logstash-input-kafka v5.1.10
logstash-output-datadog_metrics v3.0.1
logstash-output-exec v3.1.1
logstash-output-hipchat v4.0.3
logstash-output-jms v3.0.1
logstash-output-kafka v5.1.9
logstash-output-lumberjack v3.1.3
logstash-output-rabbitmq v4.0.10
```

^^ all of the above plugins required manual patches in the docs by @dedemorton in order to build the docs.

Next steps:

Resolve each plugin's problem. This can be, at minimum, copying the patch by @dedemorton into the plugin repo's docs, bumping version, and releasing.

**Comment by jordansissel** [comment]
* logstash-codec-rubydebug v3.0.3

This fails because this repo was renamed (in github) to `logstash-codec-rubydebug` which causes the documentation fetcher to fetch the `pretty` codec docs instead of the `rubydebug` codec.

**Comment by jordansissel** [comment]
Fixes to rubydebug repo:

* pushed v3.0.3 of pretty codec repo to rubydebug repo (created a new repo) as master.
* deleted v1.0.1 tag (the only released pretty codec version)

**Comment by jordansissel** [comment]
* logstash-filter-hashid v0.1.2

logstash-mass_effect lists this as a plugin that is manually removed. I think this is correct and this plugin should not show up in the documentation.

* logstash-input-graphite v3.0.3

This should be v3.0.4 but somehow it didn't get published in my last run. Jarvis won't publish it because the tests are failing on what seems like a flaky test - https://travis-ci.org/logstash-plugins/logstash-input-graphite/jobs/266105322

I'm having Jarvis ignore the test failure.

https://rubygems.org/gems/logstash-input-graphite/versions/3.0.4

logstash-input-kafka v5.1.10
logstash-output-datadog_metrics v3.0.1
logstash-output-exec v3.1.1
logstash-output-hipchat v4.0.3
logstash-output-jms v3.0.1
logstash-output-kafka v5.1.9
logstash-output-lumberjack v3.1.3
logstash-output-rabbitmq v4.0.10

**Comment by jordansissel** [comment]
Next step is to remove the jms and hipchat outputs from the docs because these two plugins latest version's do not work in Logstash 5.x due to their depedencies requiring Ruby 2.x syntax.

**Comment by jordansissel** [comment]
Currently blocked on:

* https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/647
* and https://github.com/elastic/logstash/pull/8031 being updated with the latest plugin versions.

**Comment by jordansissel** [comment]
Blocked on https://github.com/logstash-plugins/logstash-codec-rubydebug/pull/1

**Comment by jordansissel** [comment]
Next steps:

* (@suyograo) Update https://github.com/elastic/logstash/pull/8031 with latest gemfile lock
* (@jordansissel) Remove jms output from docs ([for this reason](https://github.com/elastic/logstash/issues/7993#issuecomment-323802264))
* (@jordansissel) Remove hipchat output from docs ([for this reason](https://github.com/elastic/logstash/issues/7993#issuecomment-323802264))

**Comment by jordansissel** [comment]
PR to remove jms and hipchat outputs: https://github.com/elastic/logstash-docs/pull/408

**Comment by jordansissel** [comment]
I think this is resolved fully.

Some related work pending getting the docs published, but all the preparation work (version bumps, etc) in this issue is complete.
