### ISSUE TITLE
[meta] JRuby 9k stability

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8006]
This is a meta issue to track the JRuby 9k integration stability issues in LS 6. 

- [x] JRuby JIT issue jruby/jruby#4739, #7999, #8008, #8030

**Comment by colinsurprenant** [comment]
I updated the description to reflect that all issues reported were in fact related to the same JRuby JIT issue and should be solved in upcoming 9.1.13.0.

I was going to suggest we test against a 9.1.13.0 snapshot but I can't find recent nightly builds.

**Comment by headius** [comment]
Thank you for pointing out the missing 9.1.x snapshots. I believe this is simply an oversight; we're still building two HEAD builds, but it's master and jruby-1_7, not master and jruby-9.1.*. I'll remedy this.

**Comment by headius** [comment]
The JRuby CI nightlies have been reworked.

The snapshots/current and snapshots/previous dirs now hold the current development line (usually master) and previous maintained version line (currently 9.1.x).

Builds of 9.1.13.0 are available at http://ci.jruby.org/snapshots/previous/.

Builds of 9.2 (master) are available at http://ci.jruby.org/snapshots/current/.

**Comment by colinsurprenant** [comment]
Thanks @headius  - really useful!

**Comment by original-brownbear** [comment]
fixed thanks to JRuby `9.1.13.0` :)
