### ISSUE TITLE
pipeline.events.in shows 0 when there are multiple inputs where one has 0 events flowing 

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#8011]
Using latest pre-release build:

```
{
"host": "Firestorm",
"version": "5.6.0",
"http_address": "127.0.0.1:9600",
"id": "997d4528-f143-460a-ace4-838520713f3e",
"name": "Firestorm",
"build_date": "2017-08-10T02:08:35Z",
"build_sha": "e37e2d00dd80690f8bc91e0ae32a910dc64544f0",
"build_snapshot": false
}
```

pipeline.events.in works fine if there is only 1 beats input getting events.  But if there are 2 beats inputs, 1 is idle (with no events sent to it) and another one actively getting data, then the pipeline.events.in will show 0 instead of the running total based on the other active inputs.  If both beats input are receiving data, then the pipeline.events.in works also.

```
"pipeline": {
"events": {
"duration_in_millis": 162776,
"in": 0,  <-------
"out": 40023,
"filtered": 40946,
"queue_push_duration_in_millis": 18658
},
"plugins": {
"inputs": [
{
"id": "07f51f147a0e39bd6512251acc3581bd57190a8f-2",
"events": {
"out": 0,
"queue_push_duration_in_millis": 0
},
"name": "beats"
},
{
"id": "07f51f147a0e39bd6512251acc3581bd57190a8f-1",
"events": {
"out": 40946,
"queue_push_duration_in_millis": 18658
},
"current_connections": 1,
"name": "beats",
"peak_connections": 1
}
],
```

The config is simply 2 inputs writing to stdout:

```
input {
  beats {
    port=>5044
  }
    beats {
    port=>5045
  }
}
```

@jakelandis

**Comment by suyograo** [comment]
@jakelandis can you check this one out (from your Slack convo)

**Comment by jakelandis** [comment]
This may not be a regression.  After a few more tests on 5.6, it works.  I think this may be an intermittent issue for reasons not determined yet. I don't seen any directly relevant code changes between 5.5.0 and 5.6 w/r/t this metrics.

**Comment by jakelandis** [comment]
@ppf2 - Can you reproduce this reliably ? I can only reproduce intermittently (using the same version as you), it works more often then it doesn't. It seem like there may be some underlying race condition.  I will try harder to reproduce on 5.5.0 to see if this is regression or just noticed for the first time on 5.6.0

**Comment by ppf2** [comment]
Yah, it's an intermittent issue for me as well, when I filed it, i was able to reproduce it back to back.  But when I tried again today, it hasn't happened yet.  Though I have only tried it a few times back to back so far.  But glad to see that you have identified a race condition :)
