### ISSUE TITLE
Document kafka plugins' default codec change as breaking in breaking changes documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#8012]
I am filing this under the main LS repo because we don't have breaking changes section per plugin, but at the base Logstash level.

We changed the default codec for the kafka input from json to plain [here](https://github.com/logstash-plugins/logstash-input-kafka/blob/master/CHANGELOG.md#300beta2-1).  Btw, I think we meant to say "Changed default codec to plain instead of json" (and not "Changed default codec to plain instead of SSL" :) )

This can cause downstream pipelines to break because if users who expect json handling continue to use their existing pipeline, the events will end up in a plain large text body message field instead of individually parsed json fields - unless they know to explicitly set codec to json now.

Users tend to review breaking changes from the breaking changes section in the Logstash guide so it will be helpful to document it there (plus we already have other plugin breaking changes there as well).

**Comment by jsvd** [comment]
The same issue in the Kafka output already has a PR https://github.com/logstash-plugins/logstash-output-kafka/pull/144

**Comment by ppf2** [comment]
The linked Kafka output PR is related, but not the same because the output PR simply updates the documentation page to provide instructions to switch the codec to json.  This particular request is to add this product change to the breaking changes guide because it will break users' pipeline and we will want to be calling this out in breaking changes.  Though now that you mentioned it, this breaking changes request will apply to both input and output plugins :)

**Comment by jsvd** [comment]
@ppf2 we do try to pin majors of plugins between majors of logstash, and for major logstash releases we document breaking changes in plugins.
For the logstash input kafka, we had a section for 5.0.0: https://www.elastic.co/guide/en/logstash/5.0/breaking-changes.html#_kafka_input_configuration_changes

Unfortunately..that section does not document the default code change :(

**Comment by allenmchan** [comment]
@ppf2 
As the original PR says, json codec really slows down the input. (this was true back then, maybe things has changed since then? I personally have not tested). 
If it is true that json codec still slows down the input, isn't it weird for the doc to suggest to the user to set codec to json?
My config has the input as plain and first filter is the json filter. This setup has worked well for me since that PR and I get the full content of the event.

**Comment by ppf2** [comment]
@jsvd Can probably speak to this, at some point, if json encoded events are needed, it will have to take the tradeoff somewhere, either as part of the input plugin via codec processing, or the json filter.  Not sure if we have done performance comparison in house between the 2, but if we recommend json filter over json codec (or vice versa), then this is another point that will be helpful to document either as part of this doc request or another :)

**Comment by shaharmor** [comment]
So what are users supposed to do when they have newline delimited JSON strings coming from Kafka if not use the `codec => json` option? (Considering you're saying its slow)

**Comment by jordansissel** [comment]
> newline delimited JSON strings 

`codec => json_lines`

In terms of "it's slow" -- slow is not a feature, it is a bug.

**Comment by jordansissel** [comment]
> json codec really slows down the input

@allenmchan, performance is an important topic but seems unrelated to the issue described here which is a request to document the default codec change as a breaking change.

If you are concerned with the performance of kafka input when used with the json codec, please file a separate issue. If you have specific observations of slow performance, please include the resulting data and configuration in that issue.

**Comment by jordansissel** [comment]
> when they have newline delimited JSON strings coming from Kafka 

This is what the json_lines codec is for.

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-output-kafka/pull/152 is merged
