### ISSUE TITLE
Ruby exception for nil:NilClass

### ISSUE THREAD

**Issue by dangpf** [elastic/logstash#8013]
version 5.2.1
logstash config：
 filter
        ruby {
              code => "event.set('utctime', event.get('utctime').time + 8*60*60)"
                }
error：
        [ERROR][logstash.filters.ruby    ] Ruby exception occurred: undefined method `time' for nil:NilClass

**Comment by kares** [comment]
Thanks for the report Allen, seems to be working these days (tested on LS 7.5). 5.X is EOL - closing
