### ISSUE TITLE
DLQ: new files on every restart 

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8022]
When the Dead Letter Queue (DLQ) is enabled, every restart or pipeline restart of Logstash creates a new tiny file that may never be used.  

For example, I restarted the pipeline 9 times, and sent 0 events:

 ls data/dead_letter_queue/main | wc -l
`9`

The content of these files:
cat data/dead_letter_queue/main/1.log
`1`

I am not sure if there is a reaper that would eventually clean this up, but it seems unnecessary to pre-create a file for every pipeline start.

This can result in confusion, and the appearance of an error if watching the metrics. Since each file has a size, it artificially inflates the dead letter queue size. When I first saw this, i thought data was actually going into the DLQ, but that was not the case.

```
      "dead_letter_queue" : {
        "queue_size_in_bytes" : 9
      }
```

cc @robbavey

**Comment by robbavey** [comment]
@jakelandis Once I'm happy with the basic integrity of the DLQ, both are on my relatively short term radar - the reaper code is slated for 6.1, and I'd like to figure out if there is a safe way to not need to write a new segment file on startup.
