### ISSUE TITLE
GitHub status check that fails if a PR has no version labels

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#8060]
All PRs should have version labels to know which versions the PR should be merged into.

It's easy to forget to set these, so it'd be nice to have github remind you. A status check should be implemented that looks for labels with the form `v\d` or `v\d+\.\d+\.\d+.*?`.

**Comment by ph** [comment]
Just a quick tip, either you create a sinatra that only does that, or lita the library that we use for our bot also support webhooks as route.

**Comment by jsvd** [comment]
according to a previous discussion, the version labels should only be placed in a PR after it has been merged. Placing them before merging can create a disconnect between the labels and actual merged branches.
