### ISSUE TITLE
Add new output plugin Timber.io

### ISSUE THREAD

**Issue by binarylogic** [elastic/logstash#8082]
> To begin migrating your plugin to logstash-plugins, simply create a new issue in the Logstash repository.

Hi, I'm following the above quote from the ["how to write a logstash plugin" doc](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html#_acceptance_guidelines_4). We've developed an [output plugin for the Timber.io service](https://github.com/timberio/logstash-output-timber).

Is there anything else we need to do to be listed? Thanks!

**Comment by jordansissel** [comment]
I have created https://github.com/logstash-plugins/logstash-output-timber and added you as a collaborator.

**Comment by binarylogic** [comment]
Great, thank you! I've pushed up the code. Is there anything else we need to do to finalize being listed on [the output plugins documentation page](https://www.elastic.co/guide/en/logstash/current/output-plugins.html). Appreciate the help!
