### ISSUE TITLE
Review and improve documentation for cloud.id

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#8088]
Related: https://github.com/elastic/logstash/pull/8059

**Comment by tbragin** [comment]
@dedemorton @jordansissel Is there anything left to do here, once https://github.com/elastic/cloud/pull/9695#issuecomment-348627328 is merged?

**Comment by dedemorton** [comment]
@tbragin Well we don't mention in the LS reference that the cloud ID is used for monitoring and central management. Maybe we should also add the note to cloud ID topic in the LS reference.

**Comment by dedemorton** [comment]
@tbragin Just an FYI that I've also added the note to the Logstash docs here: https://github.com/elastic/logstash/pull/8828

I think we can close this issue, if @jordansissel doesn't have other additions to suggest.
