### ISSUE TITLE
Remove cloud.id documentation if Cloud is not ready by release time

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#8089]
Related: https://github.com/elastic/logstash/pull/8059

If Cloud doesn't have cloud.id feature in time for the 6.0.0 release, then we need to remove the docs for it on our side of things.

**Comment by suyograo** [comment]
@guyboertje can you test this, please. Cloud has added the cloud.id feature.

**Comment by jordansissel** [comment]
(I updated the description to say 6.0.0 not 5.6)

**Comment by guyboertje** [comment]
The Cloud ID feature is in 6.0.0-rc1+
I have tested it in Cloud Staging. There is one small update. PR pending (I have an elusive test failure when all tests are run but not the individual file - `logstash-core/spec/logstash/agent/converge_spec.rb`)

**Comment by dedemorton** [comment]
Can I close this? I think we have everything in place and tested, right?

@nrichers @jordansissel

**Comment by jordansissel** [comment]
Yep!
