### ISSUE TITLE
Define Gemfile with require RubyGem dependencies

### ISSUE THREAD

**Issue by mcandre** [elastic/logstash#8100]
Please upload a Gemfile or gemspec that specifies the RubyGem dependencies required for logstash. This helps `bundle` do its work, without requiring bootstrapping commands.

I realize this changes the structure of the project. Instead of trying to setup a special environment in `vendor/` to be deployed as-is, we can adopt more typical Ruby conventions and have the machine and human users of this project call us, so to speak.

**Comment by jordansissel** [comment]
Doing this is likely to be a lot of work in an area (the build system) that tends to be fragile. I'm not understanding what the benefits of your proposal are (compared to the current system).

`rake bootstrap` vs `bundle install` is are both one command. Also using a task tool like rake allows us to do all the other steps necessary for preparing logstash (compile java, compile grammar, fetch any dependencies, manage Logstash plugins, build releases, etc).

Maybe we can improve the [documentation in our readme](https://github.com/elastic/logstash/blob/master/README.md#building-logstash)?
