### ISSUE TITLE
Adding new Logstash modules diagram

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#8118]
Adding new Logstash modules diagram into [Working with Logstash Modules documentation section](https://www.elastic.co/guide/en/logstash/master/logstash-modules.html). I can see this sitting well somewhere before the "Running Modules" header.

https://elasticsearch.box.com/s/rclflfuh6r2z45tk4jucv3psmvlbfgil

/cc @dedemorton @suyograo

**Comment by acchen97** [comment]
Updated diagram link above with "set up" change

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/logstash/pull/8127
