### ISSUE TITLE
DRY .lock handling in DLQ

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8124]
I realized that the DLQ code in https://github.com/elastic/logstash/blob/cacc352e94a90e960492891480bc3a97d18ecd2c/logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java#L65-L69 is using its own logic to handle the exclusive locking. 

It should probably be better to reuse the existing `FileLockFactory` https://github.com/elastic/logstash/blob/d1aa2864c667d00cb6b2d3780d50f4a8360226da/logstash-core/src/main/java/org/logstash/FileLockFactory.java

/cc @robbavey

**Comment by original-brownbear** [comment]
Resolved in #8314 :)

**Comment by colinsurprenant** [comment]
Great!!
