### ISSUE TITLE
have bin/setup.bat apply the same logic as bin/logstash.lib.sh

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8126]
Under Windows, `setup.bat` is the equivalent of `bin/logstash.lib.sh` but `setup.bat` has not been updated with the enhancements such as using `config/jvm.options`. This means that under Windows, `config/jvm.options` is not taken into account when launching logstash or running the specs.

**Comment by untergeek** [comment]
Yes, indeed. This has been mentioned before.  I've apologized to users for the discrepancy, but I don't know how to make this work with windows `.bat` files.

**Comment by untergeek** [comment]
Perhaps we should ask our resident Windows experts how they do it in Elasticsearch, since they also have a `jvm.options` file.

**Comment by colinsurprenant** [comment]
@jordansissel also mentioned it could be rewritten in power shell?

**Comment by colinsurprenant** [comment]
PR in #8178
