### ISSUE TITLE
BigInteger are not Correctly Serialized

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8131]
Same as #8128 pretty much.

Trying to send a `BigInteger` through a serialize, then deserialize cycle runs into:

```java
        Event e = new Event();
        final BigInteger huge =
            new BigInteger(String.valueOf(Long.MAX_VALUE) + String.valueOf(Long.MAX_VALUE));
        e.setField("bigint", huge);
        Event er = Event.deserialize(e.serialize());
        assertEquals(huge, er.getField("bigint"));
```

```
java.lang.IllegalArgumentException: Missing Converter handling for full class name=[B, simple name=byte[]

	at org.logstash.bivalues.BiValues.newBiValue(BiValues.java:32)
	at org.logstash.Valuefier.fallbackConvert(Valuefier.java:91)
	at org.logstash.Valuefier.convert(Valuefier.java:67)
	at org.logstash.ConvertedMap.newFromMap(ConvertedMap.java:50)
	at org.logstash.Event.<init>(Event.java:60)
	at org.logstash.Event.fromSerializableMap(Event.java:193)
	at org.logstash.Event.deserialize(Event.java:392)
	at org.logstash.EventTest.toBinaryRoundtrip(EventTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

The native-Java-serialization approach using `BiValue` or similar simply doesn't work with Jackson like this. For an `Object` of arbitrary bytes, Jackson simply goes ahead and serializes the fields in the `Object`, in this case `byte[]`.

`BigInteger` needs proper custom serialization here too, like implemented for `Timestamp` in #8130.

@jordansissel FYI, this isn't just a `Timestamp` issue, I think with the exception of `RubySymbol`, `Long` and `Integer` (and their counterparts) this breaks all remaining serializations via `BiValue`.

**Comment by original-brownbear** [comment]
Seems this could also be the cause of issue like this where `byte[]` randomly breaks deserialization https://discuss.elastic.co/t/logstash-crash-with-persistent-queue-and-kafka-input/90479/2 (though with Kafka it could be something else too obviously, ... generally, JRuby will on the fly create the larger data type from `RubyFixnum` where needed though => you see this if you multiply too much :P)

**Comment by original-brownbear** [comment]
fixed in #8205

**Comment by jordansissel** [comment]
>  BigInteger are not Correctly Serialized #8131 

I ran into this while investigating #8379, and I believe it is serialized correctly?

```
% hexdump -C page.0
00000000  01 00 00 00 00 00 00 00  01 00 00 01 2b bf 64 4d  |............+.dM|
00000010  45 54 41 bf ff 64 44 41  54 41 bf 68 40 76 65 72  |ETA..dDATA.h@ver|
00000020  73 69 6f 6e 61 31 64 68  6f 73 74 69 31 32 37 2e  |siona1dhosti127.|
00000030  30 2e 30 2e 31 67 68 65  61 64 65 72 73 bf 6b 68  |0.0.1gheaders.kh|
00000040  74 74 70 5f 61 63 63 65  70 74 63 2a 2f 2a 6c 63  |ttp_acceptc*/*lc|
00000050  6f 6e 74 65 6e 74 5f 74  79 70 65 70 61 70 70 6c  |ontent_typepappl|
00000060  69 63 61 74 69 6f 6e 2f  6a 73 6f 6e 6c 72 65 71  |ication/jsonlreq|
00000070  75 65 73 74 5f 70 61 74  68 61 2f 6c 68 74 74 70  |uest_patha/lhttp|
00000080  5f 76 65 72 73 69 6f 6e  68 48 54 54 50 2f 31 2e  |_versionhHTTP/1.|
00000090  31 6e 72 65 71 75 65 73  74 5f 6d 65 74 68 6f 64  |1nrequest_method|
000000a0  64 50 4f 53 54 69 68 74  74 70 5f 68 6f 73 74 6e  |dPOSTihttp_hostn|
000000b0  31 32 37 2e 30 2e 30 2e  31 3a 38 30 38 30 6b 72  |127.0.0.1:8080kr|
000000c0  65 71 75 65 73 74 5f 75  72 69 61 2f 6e 63 6f 6e  |equest_uria/ncon|
000000d0  74 65 6e 74 5f 6c 65 6e  67 74 68 62 33 37 6f 68  |tent_lengthb37oh|
000000e0  74 74 70 5f 75 73 65 72  5f 61 67 65 6e 74 6b 63  |ttp_user_agentkc|
000000f0  75 72 6c 2f 37 2e 35 31  2e 30 ff 6a 40 74 69 6d  |url/7.51.0.j@tim|
00000100  65 73 74 61 6d 70 78 18  32 30 31 37 2d 30 39 2d  |estampx.2017-09-|
00000110  32 35 54 31 39 3a 30 36  3a 34 31 2e 30 38 37 5a  |25T19:06:41.087Z|
00000120  6a 73 6f 6d 65 5f 76 61  6c 75 65 c2 49 00 80 00  |jsome_value.I...|
00000130  00 00 00 00 00 c0 ff ff  46 bf 85 ca 00 00 00 00  |........F.......|
00000140  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
0fa00000
```

The "type" after `some_value` appears to be `C2` which is, according to the [CBOR spec](https://tools.ietf.org/html/rfc7049#section-2.4.2), a Bignum.

**Comment by original-brownbear** [comment]
@jordansissel what LS version did you test this with?
Obviously, this is fixed in `master` and `6.x` and serialized with correct type headers, in `5.6` and `6.0` the inferred type (inferred by CBOR instead of explicitly set) headers are broken and it tries to deserialize whatever comes out on the other side as a `byte[]`.

**Comment by colinsurprenant** [comment]
@original-brownbear @jordansissel  In fact, per the investigation in #8379 `BigInteger` are correctly serialized across versions,  the problem is with the deserialization: `BigInteger` CBOR **deserialization** support was only added in Jackson 2.8+ and we are using Jackson 2.7.

**Comment by colinsurprenant** [comment]
... because of the lack of deserialization support these were coming out as `byte[]`.

**Comment by colinsurprenant** [comment]
#8405 to remove custom serializers now that Jackson is updated  in #8373
