### ISSUE TITLE
@timestamp

### ISSUE THREAD

**Issue by lanmo** [elastic/logstash#8133]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

-  logstash-5.1.1:
- Operating System:
centos
- Config File (if you have sensitive info, please remove it):
 ruby {
    code=>"
         event['@timestamp'] =  event.sprintf('%{+YYYY-MM-dd HH:mm:ss:SSS}')
    "
- Steps to Reproduce:
how can I change @timestamp？

**Comment by original-brownbear** [comment]
@lanmo this doesn't look like a bug report. General questions about Logstash should be asked in https://discuss.elastic.co/c/logstash.

Thanks for understanding.
