### ISSUE TITLE
Support list configs via env variables

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#8157]
The idea here came from: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/657 , where @eisig pointed out that you can't set a list of ES output hosts via an env var. 

I'm not sure what the best approach is here, but its a good idea.

**Comment by jordansissel** [comment]
This may not be hard to add. My notes:

* Environment variable handling happens both [before validation](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/mixin.rb#L107-L116) and [during validation](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/mixin.rb#L394).
* We may need `deep_replace` to be aware of the validator -- (:validate => :array, or :list => true, for example) -- or have deep_replace return a special type wrapper that can be converted to String, Number, Array, etc, depending on the config's validator

Example behaviors for lists:

```
elasticsearch { hosts => "${ES_HOSTS}" }
```

Assuming we go with comma as the separator -- this is up for discussion, and a user specifies this environment variable:

```
ES_HOSTS=one,two,three
```

Environment variable processing needs to be aware of the config's declaration: `hosts` is `:validate => :uri, :list => true`

When looking at ES_HOSTS value, and knowing the value is a `"list of uri"`, it should behave as if they had specified this exactly in their config:

```
elasticsearch { hosts => [ "one", "two", "three" ] }
```

However, if the validation is a string, we must continue using the value as-is.

Bonus: I would like to avoid environment variable list value syntax being valid in Logstash configs literally: "foo,bar,baz" 

Examples:

Valid:
```
export ES_HOSTS="foo,bar,baz"

# Config:
output { 
  elasticsearch { hosts => "${ES_HOSTS}" }
}
```

Invalid:

```
# Config:
output {
  elasticsearch { hosts => "foo,bar,baz" }
}
```

**Comment by arn-k** [comment]
I would support the syntax noted as invalid above, if only for consistency with the Kafka input plugin, where the bootstrap_servers option accepts a string containing a comma separated list of servers.

**Comment by Erni** [comment]
Another Customer (Kaspersky Lab) asking for this feature.
Link to case: https://elastic.my.salesforce.com/5006100000Pm1OA

**Comment by Erni** [comment]
Any idea if this feature is gonna be implemented and when it will be available?
