### ISSUE TITLE
string convert to long

### ISSUE THREAD

**Issue by lanmo** [elastic/logstash#8160]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
logstash-5.1.1
- Operating System:
unbuntu 16.05
- Config File (if you have sensitive info, please remove it):
- Sample Data:
 mutate {
 50         convert => {
 51             "logSort" => "long"
 52         }
 53     }
- Steps to Reproduce:
it can not be run

**Comment by markwalkom** [comment]
Please post this question on https://discuss.elastic.co.

You need to include your complete Logstash configuration file as well.
