### ISSUE TITLE
Identify which plugins are not core in docs

### ISSUE THREAD

**Issue by markwalkom** [elastic/logstash#8179]
For non-core plugins, can we please add something to the top of the page for said plugin's documentation telling people 1) it's not core and 2) how to install it?

Currently that isn't clear when using the docs, eg [here](https://www.elastic.co/guide/en/logstash/5.5/plugins-filters-translate.html).

**Comment by jordansissel** [comment]
This will get fixed in 5.6 once the next round of docs are published.

**Comment by jordansissel** [comment]
Related:

* https://github.com/elastic/logstash/issues/7993
* https://github.com/elastic/logstash/issues/7829

Dup of https://github.com/elastic/logstash/issues/7829
