### ISSUE TITLE
Pipeline management page in Kibana does not properly paginate.

### ISSUE THREAD

**Issue by robcowart** [elastic/logstash#8194]
- Version: 6.0.0-beta2
- Operating System: CentOS 7.2
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce: Create more than 10 pipelines using the central config management page in Kibana. You will not be able to see more than 10 pipelines. There are controls to scroll to other pages, but they don't work. If you query the `.logstash` directly, the pipelines are there, but without being able to get to them in the GUI they are unmanagable.

**Comment by ycombinator** [comment]
Closing this issue in the OSS Logstash repo as it is an x-pack issue and has now been fixed.
