### ISSUE TITLE
Remove or update the CHANGELOG.md file

### ISSUE THREAD

**Issue by geekpete** [elastic/logstash#8199]
The changelog:
https://github.com/elastic/logstash/blob/master/CHANGELOG.md

appears abandoned.
It should be removed or updated regularly.

Also consider removing the older changelog file that was pre-markdown and now serves only as a pointer to the newer yet out of date changelog:
https://github.com/elastic/logstash/blob/master/CHANGELOG

**Comment by liketic** [comment]
@geekpete Please close this. 😄

**Comment by geekpete** [comment]
Thanks!
