### ISSUE TITLE
/etc/default/logstash should not be overwritten during upgrade

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#8253]
Versions: 5.5.1 -> 5.6.0
Environment: RHEL 7.4

Currently, the contents of `/etc/default/logstash` are overwritten during an upgrade, blowing away any environment variables that a user may have previously configured to use previously in Logstash

**Comment by jordansissel** [comment]
We set [`--overwrite` when invoking pleaserun](https://github.com/elastic/logstash/blob/master/bin/system-install#L68-L70) which overwrites both the service definition and the /etc/default file

We'll need to enhance [pleaserun](http://github.com/jordansissel/pleaserun) to have a way to install only the service definition, not the defaults file.
