### ISSUE TITLE
Revert 'ExitOnOutOfMemoryError' setting because it requires minimum Java 8u92

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#8254]
our support matrix targets Java 8u60, but 'ExitOnOutOfMemoryError' was only added in Java 8u92.

http://www.oracle.com/technetwork/java/javase/8u92-relnotes-2949471.html

We need to revert ExitOnOutOfMemoryError as long as we don't require 8u92 or higher.

**Comment by jordansissel** [comment]
Elasticsearch has a custom thread exception handler that basically implements exit-on-oom without the need of the 8u92 ExitOnOutOfMemoryError flag (and does a bit more, it terminates on any Error) https://github.com/elastic/elasticsearch/pull/19272/

**Comment by jordansissel** [comment]
Patch to revert: https://github.com/elastic/logstash/pull/8138

**Comment by jakelandis** [comment]
@jordansissel - Wont the flag just be ignored in older versions ?

**Comment by jasontedor** [comment]
@jakelandis An unrecognized VM option like that will prevent the VM from starting.

**Comment by jakelandis** [comment]
Setting removed: https://github.com/elastic/logstash/pull/8268

Branch | Commits
-------|--------
6.x | 5d35a8f315f22ba066757ce96fe817ca8e04ff09
master | 70dd05d88c923927a0fb2a6c17a22c2f94012c7e

**Comment by jordansissel** [comment]
Thanks jake! I only noticed this problem because I had Java 8u45 on my
workstation and master was failing to start because of it.
