### ISSUE TITLE
[discuss] unify launch scripts options support

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8261]
The new Windows launch scripts in #8178 is changing some behaviours from the Linux launch scripts:

- existing `JAVA_OPTS` env var is now ignored, [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L37-L42)
- `JAVA_TOOL_OPTIONS` env var is cleared,  [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L31-L35)
- now only `LS_JAVA_OPTS` env var is supported to append options to parsed options in the `jvm.options` file.
- dropped the support of the `USE_RUBY` and `USE_DRIP` env vars. These not used anymore I believe. 

My proposal is to also apply these changes to the Linux launch scripts. 
WDYT?

**Comment by jordansissel** [comment]
I still use USE_RUBY but only as a desparate workaround. I am OK if it is removed.

+1 on unifying (it should make user experience better, documentation easier, and maintenance simpler)

**Comment by original-brownbear** [comment]
+1 also makes #8161 much easier (replicating the current shell behaviour there turned out to be very tricky :))

**Comment by jakelandis** [comment]
+1 to unify, and +1 to make the 6.0.0 release, since this is non-passive.

**Comment by jordansissel** [comment]
@jakelandis it's a bit late in the game for 6.0.0, but if we feel confident in the change (once merged), I would be OK with it landing for 6.0.0 (assuming the ship hasn't already sailed).

**Comment by suyograo** [comment]
+1 to all your points. We should get this for 6.0 if possible.

**Comment by ph** [comment]
+1 to everything , +1 for 6.0 release.

**Comment by colinsurprenant** [comment]
ok, lets do this, quorum is met 😅

**Comment by colinsurprenant** [comment]
PR in #8285

**Comment by colinsurprenant** [comment]
#8285 new Linux launch scripts merged in master, 6.x and 6.0
