### ISSUE TITLE
jackson-databind version 2.7.4 should be updated

### ISSUE THREAD

**Issue by prathibhay** [elastic/logstash#8311]
logstash 6.0 is still using 2.7.3, we need to use logstash for our project, and need to update to at least 2.8.9.

**Comment by jakelandis** [comment]
@prathibhay - thanks for reporting this. 

A bit googling:
https://github.com/FasterXML/jackson-databind/issues/1599
https://bugzilla.redhat.com/show_bug.cgi?id=1462702

Related issues:
https://github.com/elastic/logstash/issues/8154
https://github.com/elastic/logstash/issues/7615

**Comment by jakelandis** [comment]
Closing as duplicates
https://github.com/elastic/logstash/issues/7615
https://github.com/elastic/logstash/issues/8154
