### ISSUE TITLE
 LogStash::PLUGIN_REGISTRY should have a remove method

### ISSUE THREAD

**Issue by ph** [elastic/logstash#8316]
We can add a new plugin to the plugin registry, but there is no way to remove programmatically an existing plugin from the registry. This would be useful in testing or when a plugin takes over features of another plugin. This could be necessary for the transition to the universal plugin directory structure.

**Comment by liketic** [comment]
I can take this.

**Comment by ph** [comment]
@liketic go ahead! :)

**Comment by liketic** [comment]
@ph Can we close this now?

**Comment by ph** [comment]
@kel yes, closing.
