### ISSUE TITLE
Add docs for ingest migration tool

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#8327]
6.0 introduced [ingest migration tool](https://github.com/elastic/logstash/issues/7329) which needs documentation in our LS reference. This tool should describe the CLI flags, sample input and output and then the limitations. For example, painless is not converted from ingest to LS.  See blog for content https://www.elastic.co/blog/ingest-node-to-logstash-configuration-converter

**Comment by dedemorton** [comment]
Closed by #8399
