### ISSUE TITLE
CentOS 7 logstash service broken

### ISSUE THREAD

**Issue by rt711** [elastic/logstash#8351]
Installed logstash from the provided rpm repository (provided here: https://www.elastic.co/guide/en/logstash/current/installing-logstash.html#package-repositories) on a clean machine, but environment variables are not picked up, looks like the package is broken.

- Version: 5.6.1
- Operating System: Centos 7
- Config File (if you have sensitive info, please remove it): not relevant
- Sample Data: not relevant
- Steps to Reproduce: 

1. install java and set java_home as required per docs
2. install logstash from repository on CentOS 7, 
3. add working configuration file (pipeline) to conf directory, 
4. service logstash start 
5. ps aux | grep logstash;netstat -antop

**Comment by imweijh** [comment]
CentOS 7 use 
`systemctl start logstash`

**Comment by andrewvc** [comment]
This looks solved by @imweijh 's answer (thanks!). 

Can you close this issue if that fixes it for you @rt711 ?

**Comment by rt711** [comment]
Thanks.
