### ISSUE TITLE
New rake version tool doesn't update logstash-core-plugin-api

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#8414]
The fix in #8410 looked fine (I LGTMed it!) but, after trying to do a bump, I discovered that now there's nothing around to update https://github.com/elastic/logstash/blob/master/logstash-core-plugin-api/logstash-core-plugin-api.gemspec

We'll need to fix this. For now, I can do this bump manually, but it isn't optimal.

Future patches here should test a version bump with a `rake artifact:tar`

**Comment by robbavey** [comment]
@andrewvc Sorry - I fixed the version:set_plugin_api rake task, but didn't notice that the plugin api gemspec doesn't pull it from the versions.yml like logstash and logstash-core. :(

I'll fix it over the weekend

**Comment by rdsubhas** [comment]
Hi @andrewvc @robbavey sorry for bothering you folks, but we're pretty much running everyday into the logstash queue deserialization bug now #8379 which is fixed in 5.6.3. We are eagerly looking forward to this bugfix release 😄 👍 Thanks!

**Comment by andrewvc** [comment]
You might want to build a custom logstash off the 5.6 branch using `rake
package:tar` if you need something sooner. You'll need an environment with
jruby installed to do this.

5.6.3 is still a little ways away since we synchronize with the whole
elastic stack for releases. We would accelerate this if more users hit this
bug frequently, but that doesn't seem to be the case, so we will be on our
standard release cycle.






On Oct 5, 2017 10:06 AM, "Subhas Dandapani (RDX)" <notifications@github.com>
wrote:

Hi @andrewvc <https://github.com/andrewvc> @robbavey
<https://github.com/robbavey> sorry for bothering you folks, but we're
pretty much running everyday into the logstash queue deserialization bug
now #8379 <https://github.com/elastic/logstash/issues/8379> which is fixed
in 5.6.3. We are eagerly looking forward to this bugfix release 😄 👍
Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/logstash/issues/8414#issuecomment-334390028>,
or mute the thread

**Comment by rdsubhas** [comment]
thanks @andrewvc!

**Comment by robbavey** [comment]
Fixed by #8418
