### ISSUE TITLE
Set default URL+credentials for Kibana if ES info is present

### ISSUE THREAD

**Issue by tbragin** [elastic/logstash#8422]
When loading the dashboards from Logstash modules in 5.6 and 6.0, the user needs to configure:

Elasticsearch URL
Kibana URL
Elasticsearch credentials
Kibana credentials

Beats introduced logic whereby if user supplies ES URL + credentials but no Kibana credentials, we automatically try to use ES info for both ES and Kibana: https://github.com/elastic/beats/pull/4867

This allows for getting started instructions to be simpler.

cc: @acchen97 @robbavey

**Comment by robbavey** [comment]
@tbragin @acchen97 Do we want to use the elasticsearch URL (which would need the port changing, and handling multiple es hosts) or just the credentials? 

AFAICT, the beats commit just uses the elasticsearch credentials if Kibana credentials are not set, and does not attempt to do anything with the url.

**Comment by acchen97** [comment]
@robbavey good question, it'd be ideal to have a consistent experience across both Beats and LS modules.

@monicasarbu @brandonmensing any background on why on the KB credentials are defaulted, but not the URL? It feels like it would be more complete if the URL was defaulted to ES URL too (with port changed to 5601).

**Comment by brandonmensing** [comment]
I believe it's just the creds, not the URL. We use local+port as we always had. Using the ES URL would be problematic in that there can be multiple and anyone who has multiple ES would be in production so they should be using Kibana on the ES host anyway, right?

**Comment by acchen97** [comment]
@brandonmensing yeah you're right, and plus ES hosts can likely be an array as well.

@robbavey let's go ahead and follow the same semantics as Beats. For KB, the credentials should fallback to the ES credentials and the URL to localhost:5601, if not specified.
