### ISSUE TITLE
Missing information about the data directory

### ISSUE THREAD

**Issue by ph** [elastic/logstash#8423]
The [dir-layout](https://www.elastic.co/guide/en/logstash/6.0/dir-layout.html) page is missing information about the `data` directory required for the persistent queue and also where the persistent id file is saved.

We need to update the information 
 of this file https://github.com/elastic/logstash/blob/master/docs/static/setting-up-logstash.asciidoc

# Tar/Zip
{extract.path}/data

# debian / Rpm
/var/lib/logstash

**Comment by dedemorton** [comment]
Closing because this is fixed in #8495
