### ISSUE TITLE
Multiple pipeline error

### ISSUE THREAD

**Issue by mori-ol** [elastic/logstash#8437]
I am running Centos 7.3 with Logstash v6.0. 
When running logstash without command in order to trigger pipeline, it fails with following error:

sudo /usr/share/logstash/bin/logstash
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
ERROR: Failed to read pipelines yaml file. Location: /usr/share/logstash/config/pipelines.yml
usage:
bin/logstash -f CONFIG_PATH [-t] [-r] [] [-w COUNT] [-l LOG]
bin/logstash --modules MODULE_NAME [-M "MODULE_NAME.var.PLUGIN_TYPE.PLUGIN_NAME.VARIABLE_NAME=VALUE"] [-t] [-w COUNT] [-l LOG]
bin/logstash -e CONFIG_STR [-t] [--log.level fatal|error|warn|info|debug|trace] [-w COUNT] [-l LOG]
bin/logstash -i SHELL [--log.level fatal|error|warn|info|debug|trace]
bin/logstash -V [--log.level fatal|error|warn|info|debug|trace]
bin/logstash --help

My pipelines file is as follows:
cat pipelines.yml

    pipeline.id: infl-remote
    path.config: "/etc/logstash/conf.d/logstash-influx-data.conf"
    pipeline.id: elas-remote
    path.config: "/etc/logstash/conf.d/logstash-es-data.conf"

I can run each pipeline individually successfully. Pipelines.yml has full permissions.

Error message not clear to what is wrong.

**Comment by mori-ol** [comment]
I found the error. I had only one white space before the path.config. There are two white-spaces needed, otherwise pipelines will fail.
Different error would be useful maybe.

**Comment by Kavya7** [comment]
HI mori,
even i am facing same issue
 pipeline.id: "main"

  path.config:  "/bin/first-pipeline_main.conf"

can you please help me

**Comment by pasqualecapalbo** [comment]
> I found the error. I had only one white space before the path.config. There are two white-spaces needed, otherwise pipelines will fail.
> Different error would be useful maybe.

Thanks mori-ol, same error and same solution for me!

**Comment by ktech0** [comment]
> I found the error. I had only one white space before the path.config. There are two white-spaces needed, otherwise pipelines will fail.
> Different error would be useful maybe.

Thanks, It's helpful.
