### ISSUE TITLE
Add ability to define multiple "path.config" values

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#8451]
Actually, for "path.config" option, we can define only one value :
`path:config: my-folder/*.conf`

It would be great to add the ability to define multiple values :
For example : 
``` yaml
path:config: 
- my-folder1/*.conf
- my-folder2/*.conf
```

Or :
``` yaml
path:config: "my-folder1/*.conf,my-folder2/*.conf"
```

**Comment by mostolog** [comment]
Although I tried https://www.elastic.co/guide/en/logstash/6.0/running-logstash-command-line.html#command-line-flags, I haven't been able to make logstash read configuration files from multiple locations.

**Comment by fbaligand** [comment]
Finally, I managed to define multiple values, using this glob syntax :
``` yaml
path:config: "{my-folder1/*.conf,my-folder2/*.conf}"
```

Thanks to this great doc : https://www.elastic.co/guide/en/logstash/6.0/glob-support.html

=> I close the issue.

**Comment by mostolog** [comment]
Did you tried this syntax using command line?

**Comment by fbaligand** [comment]
I just tried with command line, and it works fine :
`logstash -f {test-logstash-1.conf,test-logstash-2.conf}`

**Comment by mostolog** [comment]
Upgraded from 5.4 to 5.6 and now it seems it works.
Thanks
