### ISSUE TITLE
Add support for non blocking push operations to Queue

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#8459]
Currently the input plugins interact with a WriteClient class to perform writes to the Queue, either the [in-memory queue](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb#L228-L241) or the [persistent queue](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/wrapped_acked_queue.rb#L345-L366).

The WriteClient implements `push` (or `<<`) and `push_batch`. If the Queue is full, these operations will block, causing back pressure to the input plugin.

However, this is not always desirable. For example, for input plugins that support [acknowledgement like HTTP input, it may be desirable to implement a timeout setting](https://github.com/logstash-plugins/logstash-input-http/issues/66#issuecomment-335212075) and return a response to the client signalling the event wasn't accepted by the queue in an given amount of time.

What I propose is for the WriteClient to have `push(event, timeout = nil)` and `push_batch(events, timeout = nil)` signatures to support millisecond timeouts, but I'm not sure how easy it is to implement, specially for the persistent queue.

Can I ask for your thoughts on this @colinsurprenant ?

**Comment by original-brownbear** [comment]
@jsvd I think is is a duplicate of https://github.com/elastic/logstash/issues/8367 :)

**Comment by jsvd** [comment]
🤦‍♂️
