### ISSUE TITLE
Persistent Queues hang when 2 ES outputs are defined on same pipeline

### ISSUE THREAD

**Issue by randude** [elastic/logstash#8462]
Version: Logstash 6 rc1
Operating System: ubuntu 16.04

First of all, let me say to that I was able to find a workaround for this issue.
I've got two pipelines. Pipeline 1 gets inputs from several locations and sends some of them (after some modifications) to pipeline #2 which outputs it to the elasticsearch outputs.
However, pipeline 2 is defined in such a way that some logs are sent to index X at ES and other logs to index Y. 
It's defined in the following manner::  if [beats] elasticsearch {}   else elasticsearch {}

When I enable PQ on the ES pipeline, almost immediately logs are stopped being sent. This happens on a machine that has many logs per seconds. On machines that barely sends logs, this conf. worked ok.

The workaround:
I defined a new pipeline that does one of the elasticsearch output, i.e, I now have 2 PQ and 2 pipelines - each has its own ES output with its own template/index.
It took me several days to hunt this down since there was another issue with PQ (see https://github.com/elastic/logstash/issues/8293).

Possible solutions:
1. I'm guessing that you guys meant that only one output is to be used when PQ are enabled, if that's not the case, logstash should reject the conf and the documentation should be updated.
2. Fix the bug :)

**Comment by original-brownbear** [comment]
@randude thanks for the write up, I'll try to reproduce this locally :)

**Comment by original-brownbear** [comment]
@randude I still can't reproduce this it seems :(

But I think we're getting warmer :) Could it be that one of your outputs locks up (either index X or Y) and hence stalls the PQ which is of limited size?
You could easily check if this is the case or rule this out by using the in-memory queue on the machine that stalls and checking if both indexes continue to receive data or if one eventually stops receiving more data right?

**Comment by randude** [comment]
I'm not using that conf. anymore. You can see the stack traces from the previous bug.
From what I remember, the first pipeline continued to receive data but the elastic worker didnt do anything with it, they were sort of stuck. 
If I remember correctly, I even changed one of the ES outputs to a file output and it still didnt work. It worked only when I had 1 output.

Also, this occurs only with a machine that got many logs. It didnt reproduce on fewer logs per second.

**Comment by randude** [comment]
I was still having issues.  This is not the real issue. see https://github.com/elastic/logstash/issues/8497
