### ISSUE TITLE
not compatible with jdk1.9

### ISSUE THREAD

**Issue by cbwleft** [elastic/logstash#8463]
- Version: logstash-5.6.2，openjdk version "9-internal"
- Operating System: ubuntu16.04 LTS
- Steps to Reproduce:
I run logstash with `bin/logstash -e 'input{stdin{}}output{stdout{codec=>rubydebug}}'`，an error occurred says `LoadError: Unsupported platform: x86_64-linux`
I paste the full input and output in the following:

`~/Desktop/logstash-5.6.2$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
~/Desktop/logstash-5.6.2$ bin/logstash -e 'input{stdin{}}output{stdout{codec=>rubydebug}}'
OpenJDK 64-Bit Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
io/console on JRuby shells out to stty for most operations
Sending Logstash's logs to /home/cbwleft/Desktop/logstash-5.6.2/logs which is now configured via log4j2.properties
[2017-10-10T17:37:00,685][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/home/cbwleft/Desktop/logstash-5.6.2/modules/netflow/configuration"}
[2017-10-10T17:37:00,690][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/home/cbwleft/Desktop/logstash-5.6.2/modules/fb_apache/configuration"}
[2017-10-10T17:37:00,713][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/home/cbwleft/Desktop/logstash-5.6.2/data/queue"}
[2017-10-10T17:37:00,733][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/home/cbwleft/Desktop/logstash-5.6.2/data/dead_letter_queue"}
LoadError: Unsupported platform: x86_64-linux
          require at org/jruby/RubyKernel.java:1040
          require at /home/cbwleft/Desktop/logstash-5.6.2/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /home/cbwleft/Desktop/logstash-5.6.2/vendor/jruby/lib/ruby/shared/ffi/ffi.rb:69
          require at org/jruby/RubyKernel.java:1040
          require at /home/cbwleft/Desktop/logstash-5.6.2/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /home/cbwleft/Desktop/logstash-5.6.2/vendor/jruby/lib/ruby/shared/ffi.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /home/cbwleft/Desktop/logstash-5.6.2/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /home/cbwleft/Desktop/logstash-5.6.2/vendor/jruby/lib/ruby/shared/ffi.rb:1
           (root) at /home/cbwleft/Desktop/logstash-5.6.2/logstash-core/lib/logstash/util/prctl.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /home/cbwleft/Desktop/logstash-5.6.2/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
             LibC at /home/cbwleft/Desktop/logstash-5.6.2/logstash-core/lib/logstash/util/prctl.rb:3
           (root) at /home/cbwleft/Desktop/logstash-5.6.2/logstash-core/lib/logstash/util/prctl.rb:2
           (root) at /home/cbwleft/Desktop/logstash-5.6.2/logstash-core/lib/logstash/util.rb:1
  set_thread_name at /home/cbwleft/Desktop/logstash-5.6.2/logstash-core/lib/logstash/util.rb:20
          execute at /home/cbwleft/Desktop/logstash-5.6.2/logstash-core/lib/logstash/runner.rb:245
           (root) at /home/cbwleft/Desktop/logstash-5.6.2/lib/bootstrap/environment.rb:71

`

**Comment by jordansissel** [comment]
Indeed, Java 9 is not yet supported by Logstash.

**Comment by cbwleft** [comment]
Which confused me is，I followed the installation steps，which says Java 8 or higher is required for Logstash 5.x. so I thought java 9 won't be the problem，nothing prompted me that I should use java 8 instead.

**Comment by jordansissel** [comment]
Java 9 was released barely a month  ago. It's ok that our documentation is
not yet updated. There are only so many hours in the day :)

**Comment by CamJN** [comment]
Java 9 was released Sept 22, it is now Dec 21. Are there any updates on getting this working?

**Comment by jordansissel** [comment]
Still not supported. There is work still needing to be done. I have no ETA.

**Comment by CamJN** [comment]
Java 9 will be EOL in Mar 2018, looks like it's literally never going to be supported? With Java moving to a rapid release schedule you're going to have to move faster on supporting new versions or dump the java dep for pure ruby.

**Comment by jsvd** [comment]
Logstash now supports Java 17, see https://www.elastic.co/support/matrix#matrix_jvm for more information.
