### ISSUE TITLE
Update SynchronousQueue documentation.

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8488]
This page: https://www.elastic.co/guide/en/logstash/6.x/execution-model.html (and master/current) still refers to the the SynchronousQueue.

As of 6.1 with [this](https://github.com/elastic/logstash/pull/7691/files#diff-1eb63ed8cd2fb1ca5d896c221184d186L8) commit, the implementation been changed to an ArrayBlockingQueue, which does have a size. 

>This queue holds no events, instead transferring each pushed event to a free worker, blocking if all workers are busy.

Is no longer valid as the size of the queue is a function of the pipeline workers and batch size. However, imo, that is an implementation detail unnecessary to continue to include at this level of the documentation. 

In summary, I suggest to change:

> Each input stage in the Logstash pipeline runs in its own thread. Inputs write events to a common Java SynchronousQueue. This queue holds no events, instead transferring each pushed event to a free worker, blocking if all workers are busy. Each pipeline worker thread takes a batch of events off this queue, creating a buffer per worker, runs the batch of events through the configured filters, then runs the filtered events through any outputs.

to

> Each input stage in the Logstash pipeline runs in its own thread. Inputs write events to a central queue that is either in memory (default) or on disk.  Each pipeline worker thread takes a batch of events off this queue, creating a buffer per worker, runs the batch of events through the configured filters, then runs the filtered events through any outputs.

Also (un-related, but on same page) can we make a minor change from:

> If Logstash terminates unsafely, any events that are stored in memory will be lost. To prevent data loss, you can enable Logstash to persist in-flight events to disk. See Persistent Queues for more information.

to

> If Logstash terminates unsafely, any events that are stored in memory may be lost. To help prevent data loss, you can enable Logstash to persist in-flight events to disk. See Persistent Queues for more information.

^^ softened wording very slightly w/r/t to data loss 

cc @dedemorton @original-brownbear @jordansissel

**Comment by jordansissel** [comment]
> Each input stage in the Logstash pipeline runs in its own thread. Inputs write events to a common Java SynchronousQueue

As a guideline, I'd like us to avoid mentioning implementation details that are not necessarily useful for users. Developers may care and have understanding of "SynchronousQueue" java class, but users should not care nor should we expect them to understand. Instead, detail the behavior, not the implementation or internal naming.

That said, your proposed change follows the above guideline, and I like it for that reason.

You could strike `creating a buffer per worker` since that restates the previous phrase 'batch of events'.

**Comment by karenzone** [comment]
Work in progress

**Comment by dedemorton** [comment]
@karenzone Does #9109 close this issue? If so, go ahead and close it. :-)

**Comment by karenzone** [comment]
Yes, @dede. It does. Closing it now. Thanks for all of your help.
