### ISSUE TITLE
netflow module is not working

### ISSUE THREAD

**Issue by sergsmitienko** [elastic/logstash#8498]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: logstash 5.6.3-1, elasticsearch 5.6.3, kibana 5.6.3
- Operating System: Ubuntu 16.04
- Config File (if you have sensitive info, please remove it):
log.level: debug
modules:
  - name: netflow
    var.input.udp.port: 2055
    var.elasticsearch.hosts: "localhost:9200"
    var.kibana.host: "localhost:5601"

- Sample Data: -

- Steps to Reproduce:
bin/logstash --modules netflow --setup
systemctl restart logstash.service

/var/log/logstash/*.log:

[2017-10-18T01:38:50,900][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exceptio
n"=>"undefined method `to_hash' for []:Array", "backtrace"=>["(eval):18:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash
-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}

**Comment by noderat** [comment]
Debug log level is currently known to crash the pipeline in 5.6.3 with exactly that error message.

**Comment by sergsmitienko** [comment]
The reason why I had to enable debug, was because without debug netflow did not work also.

**Comment by kares** [comment]
closing - defunct LS 5.3 issue
