### ISSUE TITLE
Slow logger configuration is not included in packaged versions

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8499]
It appears that the packaged distributions (.rpm, .deb) do not include the slow logger configuration due to the duplication of the log4j2.properties files in the pkg directory. 

I assume that the log4j2.properties in the config directory (included as the .tar distribution) is intended to be the source of truth, and these two files have gotten out of sync. 

Ideally the fix isn't to simply copy/paste to bring the two back in sync, rather to ensure that they won't get out of sync. I believe this will be the same solution as https://github.com/elastic/logstash/issues/8427

**Comment by jakelandis** [comment]
This is a related to #9066. 

To reiterate:
> Ideally the fix isn't to simply copy/paste to bring the two back in sync, rather to ensure that they won't get out of sync.

**Comment by jordansissel** [comment]
> to ensure that they won't get out of sync

@jakelandis +1

The files in `pkg` are intended as things necessary on rpm (Red Hat) and deb (Debian, Ubuntu) platforms. Sometimes changes are made in these files in git, and sometimes they are made at [package install-time](https://github.com/elastic/logstash/blob/master/pkg/centos/after-install.sh#L4-L7)

When there are files we don't need to change at all (probably log4j2.properties?) or files we only need to change a little ([logstash.yml](https://github.com/elastic/logstash/blob/master/pkg/centos/after-install.sh#L4-L7)), maybe the right solution is to remove them from the `pkg` directory and have only a single source file -- such as config/log4j2.properties.
