### ISSUE TITLE
Trouble parsing using CSV filter

### ISSUE THREAD

**Issue by ush-2017** [elastic/logstash#8502]
#SERVER_NAME|SERVER_IPADDRESS|REQUEST_ID|EVENT_SOURCE|EVENT_TYPE|ACTION|STATE|OLD_STATE|EVENT_TIMESTAMP|EVENT_PAYLOAD
APC3.0|15.60.75.681|0929995b-f696-462b-968a-9b1b1f11ac44|TEMP_REGISTRY_LOG|||||2017-08-21T21:01:16|{"environment_label":"alp1b","openstack_release":"kilo-9.0","openstack_roles":"atp-cinder-volume,aic-controller,aic-swift-proxy","http_response_size":0,"request_id":"0929995b-f696-462b-968a-9b1b1f11ac44","python_module":"temp.registry.api.v1.images","openstack_region":"RegionOne","deployment_id":"22","severity_label":"DEBUG","programname":"glance-registry","Hostname":"extyo7","Logger":"openstack.glance","Payload":"[req-0929995b-f696-462b-968a-9b1b1f11ac44 m12915 fa9d54addad740f3818436caefaff3ea - - -] Returning detailed image list detail /usr/lib/python2.7/dist-packages/api/v1/images.py:186\n","Pid":"4360","Severity":"7","Timestamp":"2017-08-21T21:01:16","Type":"log"}

**Comment by jordansissel** [comment]
I'm not sure what the reported problem is here -- Can you move this to https://discuss.elastic.co/ and maybe the folks on the community support forum can help you?
