### ISSUE TITLE
ingres-convert apache.json generates wrong logstash config

### ISSUE THREAD

**Issue by popstas** [elastic/logstash#8507]
- Version: 5.6.3
- Operating System: Ubuntu 16.04
- Config File: https://github.com/elastic/beats/blob/v5.6.3/filebeat/module/apache2/access/ingest/default.json
- Sample Data:
Generates:
```
filter {
   grok {
      match => {
         "message" => [
            "%{IPORHOST:[apache2][access][remote_ip]} - %{DATA:[apache2][access][user_name]} \[%{HTTPDATE:[apache2][access][time]}\] \"%{WORD:[apache2][access][method]} %{DATA:[apache2][access][url]} HTTP/%{NUMBER:[apache2][access][http_version]}\" %{NUMBER:[apache2][access][response_code]} (?:%{NUMBER:apache2.access.body_sent.bytes}|-)( \"%{DATA:[apache2][access][referrer]}\")?( \"%{DATA:[apache2][access][agent]}\")?",
            "%{IPORHOST:[apache2][access][remote_ip]} - %{DATA:[apache2][access][user_name]} \[%{HTTPDATE:[apache2][access][time]}\] \"-\" %{NUMBER:[apache2][access][response_code]} -"
         ]
      }
   }

   mutate {
      rename => {
         "@timestamp" => "read_timestamp"
      }
   }
   date {
      match => [
         "[apache2][access][time]",
         "dd/MMM/YYYY:H:m:s Z"
      ]
      target => "@timestamp"
   }



   geoip {
      source => "[apache2][access][remote_ip]"
      target => "[apache2][access][geoip]"
   }
}
```

/var/log/logstash/logstash-plain.log:
```
[2017-10-22T08:34:53,059][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Expected one of #, => at line 73, column 17 (byte 1676) after filter {\n   if [fileset][module] == \"apache2\" {\n        filter {\n           grok "}
```

- Steps to Reproduce:

1. Clone elastic/beats:
```
git clone https://github.com/elastic/beats.git /tmp/beats
git checkout v5.6.3
mkdir /tmp/ingest
```

2. Generate config:
```
/usr/share/logstash/bin/ingest-convert.sh --input file:///tmp/beats/filebeat/module/apache2/access/ingest/default.json --output file:///tmp/ingest/apache.conf
```

3. Put config in logstash conf:
```
cp /tmp/ingest/apache.conf /etc/logstash/conf.d/ingest-apache.conf
```

4. Restart logstash:
```
service logstash restart
```

**Comment by original-brownbear** [comment]
@popstas the error you're seeing does not come from the config file you pasted I think.

It talks about line `73` and the field `[fileset][module]`, both of which aren't in the file generated.
Looks to me like some other config file in your path is to blame here?

**Comment by popstas** [comment]
@original-brownbear, I just wrapped all filter content in `if [fileset][module] == "apache2"{ }`, same way I applied when converted `system/syslog` and `nginx/access` ingres, they works fine, almost painless :)

Also, when I removed content of grok message section, replaced to `"message" => [ ]`, config also passed without errors.

**Comment by original-brownbear** [comment]
@popstas Not sure I understand the above, the config I'm seeing here seems correct to me. I just tested it manually and it didn't error in any way.

So the issue seems to come from an altered version of that config that has issues and not from the Ingest converter tool?

**Comment by original-brownbear** [comment]
Closing this for now as I don't see a reproducible issue here, happy to revisit this if I misunderstood anything though :)
