### ISSUE TITLE
multi_filter called for 0 events [5.6.3 regression]

### ISSUE THREAD

**Issue by praseodym** [elastic/logstash#8516]
Logstash 5.6.3 has a problem where `multi_filter` in filter plugins is called for 0 events (an empty array). Testing reveals that this is a regression from Logstash 5.6.2.

While this behaviour will not usually cause errors to be thrown, it probably has a performance impact. This impact could be significant for plugins that naively try to do work on the empty events array (e.g. call out to an external service for every batch of events, even empty batches).

I've created a straightforward test plugin that logs `multi_filter` invocations. This plugin is available at https://github.com/praseodym/logstash-filter-multitest and its output is available for these Logstash versions:
* [Logstash 5.6.2](https://github.com/praseodym/logstash-filter-multitest/blob/master/logstash-5.6.2.log) (OK)
* [Logstash 5.6.3](https://github.com/praseodym/logstash-filter-multitest/blob/master/logstash-5.6.3.log) (has regression)
* [Logstash 6.0.0-rc1](https://github.com/praseodym/logstash-filter-multitest/blob/master/logstash-6.0.0-rc1.log) (OK)

**Comment by original-brownbear** [comment]
@praseodym I'm not so sure we should ignore the `0` length batches here.

It seems to me that this a significant outlier case of plugin behavior and doesn't really justify having logic around for in core.
Shouldn't we rather fix the plugin to be smarter, than add logic for this kind of corner case to core?

**Comment by praseodym** [comment]
Just to clarify: plugins trying to do work on empty batches is the symptom, not the actual problem. What I observe is Logstash doing work on empty event batches, passing them through the pipeline including any filter plugins. This is a waste of resources and that is, in my opinion, a problem.

For a [completely idle pipeline](https://github.com/praseodym/logstash-filter-multitest/blob/65b6905ae6d9683e8cb1b66bbd00e39f08579082/pipeline-http.conf) I see 100-300 `multi_filter` invocations per second, with Logstash 5.6.3 consuming 5-40% of a CPU core doing exactly nothing.

**Comment by original-brownbear** [comment]
@praseodym I see your point, for an idle system the situation is not ideal, though (imo, could be wrong here) this really only comes with a measurable cost if the filter is doing redundant work when hit by an empty batch (which isn't the case for almost all filters that simply loop over the batch).

That said, isn't it an option to simply set `pipeline.batch.delay` to a higher value than the default `5` (ms) and reduce the overhead that way? If you increase the batch delay (== the period of time until an empty batch is created if there are no events in the pipeline) by a factor `x` then the load from this effect should go down by `x`. Setting this to `100` (which seems reasonable if the pipeline idles a lot) should turn your `100-300` redundant invocations into `5-15`.
Maybe this is a solution for your use case?

**Comment by praseodym** [comment]
The workarounds would alleviate the problem, but this doesn't answer the more fundamental question here: why is _any_ work being done on an empty batch? Why not start the `pipeline.batch.delay` timer only when the first event in a batch arrives, so that an empty batch is never yield?

I think this behaviour is already fixed in 6.x by cf2ac9f927dd01c4ed801f601fe6a2317bc7bb24. In the related PR @jordansissel made two comments about the empty batch behaviour as well (see [[1]](https://github.com/elastic/logstash/pull/7559/files#r124629913), [[2]](https://github.com/elastic/logstash/pull/7559#issuecomment-312126068)), so it might be worth revisiting those (seemingly unanswered) questions as well.

**Comment by original-brownbear** [comment]
@praseodym 

> Why not start the pipeline.batch.delay only when the first event in a batch arrives, so that an empty batch is never yielded

Yea something like that is def what we should be going for down the line. The whole reason we're operating the way we currently do comes down to details of the existing implementation (see the signal queue in `pipeline.rb` if you're interested, really just a coding detail though).

Note that we are currently in the process of reimplementing the execution engine (can already by tested and so far seems to be working flawlessly with the `6.x` and `master` branches  via the `--experimental-java-execution` flag) in Java,  so this whole code path is going to become obsolete in the near future anyways. 
Hence me pushing back on making further changes to the existing code if a workaround does the trick as well :) Better fundamentals are on the way.

**Comment by praseodym** [comment]
That makes sense. I’ve looked at `pipeline.rb` and some logic there definitely looks a bit convoluted. Also, the JRuby code in general is impossible to profile with standard JDK tooling — there’s a lot of GC activity in an idle Logstash instance, but because most activity is in Ruby code I can’t figure out whether this is entirely due to empty batch processing.

A Java execution engine thus sounds like a very good idea. For what version is this change targeted?

In the meantime, we could probably fix/work around the regression in 5.6.3 by backporting https://github.com/elastic/logstash/commit/cf2ac9f927dd01c4ed801f601fe6a2317bc7bb24 to `5.x`.

**Comment by original-brownbear** [comment]
@praseodym 

> In the meantime, we could probably fix/work around the regression in 5.6.3 by backporting cf2ac9f to 5.x.

Unfortunately cf2ac9f927dd01c4ed801f601fe6a2317bc7bb24 was unexpected issues that were fixed in subsequent commits like a0f1f3744c6ae18ed074be999c4216510fc0bc4e.
Backporting this is not something we want to do for `5.x` I think.

> A Java execution engine thus sounds like a very good idea. For what version is this change targeted?

It'll be in `6.1` available via the `--experimental-java-execution` flag.

> whether this is entirely due to empty batch processing.

If we're just talking about LS core and without a filter plugin that gets expensive on empty batches, I'd say the cost of running even a 300 empty batches per second is trivial and won't show up in a profile.

----------------------------------------------

I'll close this for now, there isn't really anything I can do here I think, sorry.
Any plugin can return to the previous performance characteristics by adding a `return [] if batch.size == 0` or similar guard in its `multi_filter` method.
As a matter of fact, the framework overhead for idle pipelines should be lower than prior to the change that brought this about (https://github.com/elastic/logstash/commit/63a05c0bfbf08f7e46b93141a258b756339bbada) in  since we only add one function call to `multi_filter` for each empty batch, but save a `Block` being instantiated (which is quite a few function calls + GC :)).
