### ISSUE TITLE
No such method of `sanitized` for String

### ISSUE THREAD

**Issue by zzt93** [elastic/logstash#8540]
- Version: 5.6.0
- Operating System: Linux ubuntu-100 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Config File (if you have sensitive info, please remove it):
```
Input {
  jdbc {
    }
  jdbc {
    }
  jdbc {
    }
  jdbc {
    }
  jdbc {
    }
 }
filter {}
output {
  elasticsearch {
    index => "%{[@metadata][table]}%{[@metadata][suffix]}"
    document_id => "%{[@metadata][id]}"
    hosts => ["192.168.1.100:9200", "192.168.1.200:9200"]
  }
}
```

- Sample Data:
```
{
    "@timestamp" => 2017-10-27T01:10:01.545Z,
     "@metadata" => {
            "id" => 9256,
        "suffix" => "-2846",
         "table" => "affair"
    },
          "name" => "string85378",
      "@version" => "1",
         "state" => 1,
       "superId" => "stringRjD00000",
      "parentId" => 9070,
          "tags" => [
        [0] ""
    ]
}
```
- Steps to Reproduce: run long enough and it produce following errors.

`[ERROR] 2017-10-27 16:01:37.640 [[.monitoring-logstash]>worker0] elasticsearch - Encountered an unexpected error submitting a bulk request! Will retry. {:error_message=>"undefined method `sanitized' for #<String:0x1e051b3c>", :class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:249:in `safe_bulk'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:222:in `safe_bulk'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:119:in `submit'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:87:in `retrying_submit'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.0-java/lib/logstash/outputs/elasticsearch/common.rb:38:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:436:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:435:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:381:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}`

**Comment by andrewvc** [comment]
This should be fixed in the latest version of this plugin. Have you tried updating it from 7.4.0?

**Comment by zzt93** [comment]
Thanks, I will give it a try when I have a chance.

**Comment by robbavey** [comment]
@zzt93 Did you get a chance to update the plugin, so we can either close or follow up on this issue?

**Comment by zzt93** [comment]
@robbavey  We haven't come across error recently, so I think you can close it now. Thanks for your response.
