### ISSUE TITLE
Jenkins Java test failure tracking issue - ProcessWitnessTest testRefreshChanges

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#8578]
What @jakelandis said in the build failure email...

The test is asserting that they are not equal.

The exact lines of the test:
```
//Add some arbitrary CPU load
....
//give the threads some time up add measurable load
Thread.sleep(3000);
long after = snitch.cpuProcessPercent();
//There is a slim chance that the stars align and the before and after are indeed equal, but should be very rare.
assertThat(before).isNotEqualTo(after);
```
Just got un-lucky.  If this keeps happening we may need to re-visit that test. 

https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility/os=oraclelinux/247/console

https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=oraclelinux/182/console

**Comment by original-brownbear** [comment]
Just for completeness sake, I already ran into this like 3 times locally in the last few days:

```sh
org.logstash.instrument.witness.process.ProcessWitnessTest > testRefreshChanges FAILED
    java.lang.AssertionError: 
    Expecting:
     <12L>
    not to be equal to:
     <12L>
        at org.logstash.instrument.witness.process.ProcessWitnessTest.testRefreshChanges(ProcessWitnessTest.java:83)
```

Maybe it would be smarter to simply do some work during those 3 seconds of waiting? (just a dumb suggestion though without knowing much about the details of this code :))
