### ISSUE TITLE
Vagrant ssh-config should check that machine is up first

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#8596]
The build error here: https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-acceptance/label=metal,suite=debian/121/console

Is due to an attempt to ssh into a vagrant host before that machine is ready. We should loop waiting for the machine, then error if it is not ready instead.

The error is occuring here: https://github.com/elastic/logstash/blob/master/qa/Rakefile#L25

**Comment by original-brownbear** [comment]
fixed in https://github.com/elastic/logstash/pull/8615
