### ISSUE TITLE
Docs cleanup for ES 6.0 doctype changes

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#8606]
There's a few other doc areas that could warrant a minor cleanup from the doctype changes in ES 6.0. The pages below seem to have "type = log" references in both the LS and/or Filebeat examples. Perhaps we can change this to "doc" instead as its now the default in 6.0 for LS and Beats.
- [Parsing Logs with Logstash](https://www.elastic.co/guide/en/logstash/6.0/advanced-pipeline.html)
- [Multiple Input and Output](https://www.elastic.co/guide/en/logstash/6.0/multiple-input-output-plugins.html)
- [Dead Letter Queue docs](https://www.elastic.co/guide/en/logstash/6.0/dead-letter-queues.html) 

/cc @dedemorton

**Comment by dedemorton** [comment]
@acchen97 I've fixed the issues that you've identified. See #8603.

However, the [Multiple Input and Output](https://www.elastic.co/guide/en/logstash/6.0/multiple-input-output-plugins.html) section looks OK to me. The first `type` field in the example is the prospector type. The second `type` field is a custom field that Filebeat adds to the event. 

As you would expect, Filebeat sets the `_type` field in the metadata document to `doc` . It's possible I'm not fully understanding how this works, but I think the examples as they are written are OK. Can you check and close this issue if you're satisfied that the topic is correct? Thanks!

**Comment by acchen97** [comment]
@dedemorton your PR LGTM, let's close this out after that's merged. :+1:

**Comment by acchen97** [comment]
Resolved with https://github.com/elastic/logstash/pull/8603.

**Comment by tbragin** [comment]
@acchen97 @andrewvc @dedemorton Looks like we missed one? Just came in via info@:
https://www.elastic.co/guide/en/logstash/current/config-examples.html

**Comment by tbragin** [comment]
Another one?
https://www.elastic.co/guide/en/logstash/current/configuration-file-structure.html

**Comment by acchen97** [comment]
@tbragin the reason this is happening is due to the bug we had in the 6.0.0 release. This will be resolved OOTB in 6.0.1.

After further clarification with @andrewvc, I don't believe this warrants any necessary documentation changes. There is no _type field in LS, so the type fields that are specified here can still be used regardless for conditionals or just simply just being another field. 

Closing this issue...
