### ISSUE TITLE
Centralized pipeline management doc enhancements

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#8618]
In the central pipeline management docs, we need to add a blurb around secure access to the [pipeline management UI](https://www.elastic.co/guide/en/logstash/6.x/logstash-centralized-pipeline-management.html#_pipeline_management_ui). With x-pack installed, we bootstrap a "logstash_admin" role which can be assigned to users that should have permissions to edit LS pipelines.

Additionally, @dedemorton should we consider renaming the parent section of this to "Managing Logstash"? It seems more consistent with the other "Configuring/Deploying/Scaling/Monitoring LS" sections.

Thanks to @ajpahl1008 for raising this.

**Comment by dedemorton** [comment]
+1 for renaming to "Managing Logstash." That was actually my first impulse, but for some reason I thought you and Suyog wanted "configuration management" to appear in in the title. :-) I am happy to make the change because I love parallelism.
