### ISSUE TITLE
Flushed events from filters doesn't respect nested "if else" statements

### ISSUE THREAD

**Issue by micoq** [elastic/logstash#8619]
Considering this configuration:
```
input {
    generator {
        type => "generator"
    }
}
filter {
    ruby {
        code => "sleep(1.000)"
    }
    if [type] == "generator" {
        if [@timestamp] {
            metrics {
                meter => "events"
                add_tag => "metric"
            }
        }
    }
    else {
        drop {
        }
    }
}
output {
    stdout {
       codec => rubydebug{}
    }
}

```
Normally, the `metrics` filter plugin should generate some events on stdout. However, you will never see any of them because these events are cancelled by the `drop` plugin in the `else` branch.

Now, let's comment out (or delete) the `if [@timestamp] {` condition:
```
    if [type] == "generator" {
        #if [@timestamp] {
            metrics {
                meter => "events"
                add_tag => "metric"
            }
        #}
    }
```
and it works !

Note: In both cases, I use a batch size of 1 to see the events immediately (`./logstash -w 1 -b 1 -f /tmp/test.conf`)

After some research, I think the problem came from the code generation in [config_ast.rb](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/config_ast.rb#L258):
in `compile_starting_here()`, the compiler detects the other branches of the `if` where the filter plugin is (called the `branch_siblings`) to avoid them when generating the code.
But when a filter plugin is enclosed in more than one `if`, the compiler can't detect the outer `if` and the 
`else` statement will be executed.

This behavior only applies to the flushed events.

The conditions in each `if` are not important. You can also add an `else` like this:
```
    if [type] == "generator" {
        if [@timestamp] {
            metrics {
                meter => "events"
                add_tag => "metric"
            }
        }
        else {
           [...]
        }
    }
```
As explained, the flushed event will not reach the code in this `else` but will be dropped/cancelled too.

Tested on RHEL 7, Logstash version: 5.6.4

**Comment by original-brownbear** [comment]
Reproduced this on `master` too, for what it's worth the Java execution doesn't have this bug ( @andrewvc maybe we should make it the default in `master`? :D) only the Ruby one is affected.

**Comment by original-brownbear** [comment]
I can also confirm using the metrics REST endpoint that the events are actually dropped.

**Comment by jordansissel** [comment]
> only the Ruby one is affected

This is a regression, so switching default implementations is not necessarily a fix, though I admit this is an appealing option for master.

**Comment by jordansissel** [comment]
@original-brownbear separately, I'm open to discussing making java execution flag enabled by default in master (not 6.x). Want to open a discussion issue?

**Comment by original-brownbear** [comment]
@jordansissel discussion issue sounds good, will add one later :)

**Comment by andrewvc** [comment]
Have we tested back to see when this is introduced? AFAIK that code hasn't changed in a very long time.

**Comment by original-brownbear** [comment]
@andrewvc tried a few versions and yes long time indeed, even in `5.1.1` (lost patience so I stopped there, probably started even before that) I can still reproduce this.

**Comment by original-brownbear** [comment]
@jordansissel @andrewvc https://github.com/elastic/logstash/issues/8623 added issue for making Java exec the default in `master`

**Comment by original-brownbear** [comment]
Uff, fixed in https://github.com/elastic/logstash/pull/8629 ... that took a while ...

**Comment by original-brownbear** [comment]
closing here, fixed in `master` and `6.x` (when using Java exec). Once Java exec becomes the default, this will be resolved for all users.
