### ISSUE TITLE
Make Java Execution the Default Execution in Master?

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8623]
It's in the title :) For `7.x` we're planning to go for the Java execution for sure => imo we should just make it the default in `master`.
I would even go as far as simply removing the Ruby execution from `master`, it's simply not part of the plan for `7.x`.

One upside of this (outside of just being correct in principle) would be fixing #8619 since the Java execution handles this case correctly.

**Comment by original-brownbear** [comment]
@andrewvc said it's fine to do this :)

**Comment by jordansissel** [comment]
I am :+1: on this as well.

**Comment by original-brownbear** [comment]
done in https://github.com/elastic/logstash/pull/8649
