### ISSUE TITLE
Documentation show wrong image version

### ISSUE THREAD

**Issue by ebuildy** [elastic/logstash#8637]
Document here (https://www.elastic.co/guide/en/logstash/current/docker.html) is talking about 5.6.5 but:

> ➜  elk git:(master) ✗ docker pull docker.elastic.co/logstash/logstash:5.6.5
> Error response from daemon: manifest for docker.elastic.co/logstash/logstash:5.6.5 not found

**Comment by robbavey** [comment]
Fixed by #8638
