### ISSUE TITLE
Migrating MySql Data Into Elasticsearch Using Logstash

### ISSUE THREAD

**Issue by mrtranquanghieu** [elastic/logstash#8643]
I use JDBC to transfer data from MySQL to Elastic Search through the Logstash
How to check if a record from MySQL migrated to exists in Elastic search?
This is logstack.conf
<pre>input {
    jdbc {
        jdbc_connection_string => "jdbc:mysql://localhost:3306/zintor"
        jdbc_user => "root"
        jdbc_password => ""
        jdbc_driver_library => "F:\ELK\mysql-connector-java-5.1.44\mysql-connector-java-5.1.44-bin.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        statement => "SELECT * FROM fb_post_page"
    }
}
output {
	stdout { codec => json_lines }
    elasticsearch {
        "hosts" => "localhost:9200"
        "index" => "zintor"
        "document_type" => "fb_post_page"
    }
}</pre>

**Comment by original-brownbear** [comment]
@mrtranquanghieu We use Github issues are only for handling bug reports. General usage questions should be directed at https://discuss.elastic.co/c/logstash.

Closing here.
