### ISSUE TITLE
duplicate documents with logstash 5.6.4

### ISSUE THREAD

**Issue by jmreymond** [elastic/logstash#8679]
We have a server with 12 CPU's. We noticed since migration from 2.3.3 a huge amount of duplicate lines so all our statistics are wrong and there is a big lag in our Kafka.
So, we upgrade to the last logstash 5.6.4 and adopt a fingerprint solution as described in [https://www.elastic.co/blog/logstash-lessons-handling-duplicates](https://www.elastic.co/blog/logstash-lessons-handling-duplicates). 
Now, we are sure that there is no duplicate but we have always 4 millions of duplicate errors per hour for 6 millions "good" lines: it is a monumental waste of CPU and it is very difficult to reduce our lag in kafka.
We understand that it is a crash of logstash which initialize again its queue message and process again all the queue  so logstash is a buggy program.
I am not sure that one day, this very old bug will be fixed so how to deal with it: 
- many logstash process  as I understand that each process has its own message queue ?
- many dockers, each one running its own logstash 
- a logstash substitution program ?
- ???

thanks for your tips,

- Version:
logstash 5.6.4
- Operating System:
Red Hat 7.2
- Config File (if you have sensitive info, please remove it):

```
# grep -v '^#' /etc/logstash/logstash.yml
path.data: /var/lib/logstash
pipeline.workers: 12
pipeline.output.workers: 6
pipeline.batch.size: 250
path.config: /etc/logstash/conf.d
config.reload.automatic: true
config.reload.interval: 120
path.logs: /pfic/logstash/logs
xpack.monitoring.elasticsearch.url: "http://up0tx755:9200"
```

- Sample Data:
- Steps to Reproduce:

**Comment by jmreymond** [comment]
After a lot of investigations, it seems that input plugin kafka 0.9 is buggy.
 It seems that is this very old and ugly bug opened since one year: 
https://github.com/logstash-plugins/logstash-input-kafka/issues/140

**Comment by jmreymond** [comment]
reading this very interesting post, the cause is our kafka 0.9
[https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/]

**Comment by original-brownbear** [comment]
@jmreymond am I correct to understand there is no issue left for us to deal with here and the problem was with the semantics of Kafka 0.9 itself?

**Comment by jmreymond** [comment]
not exactly :-) 
Kafka introduces itself duplicate records if the consumer process failed (typically, the kafka input plugin crashes). We have an massive overload of duplicate lines (average is x3, i.e. for one valid line, we have 3 fake lines; but sometimes for one line, we have 748 duplicates).
This week, we have tested with a 12 CPU server, logstash 5.6.4 and a little test program: read flat file and write fingerprint in a file: it is correct, no duplicate
Next week: same program with kafka 0.8 input and vary pipeline workers 
We understand that before kafka 11, duplicate lines exist but our numbers are so great that it is difficult to deal with it

**Comment by jmreymond** [comment]
adjusting max_partition_fetch_bytes to 100000 and session_timeout_ms to 30000 introduce a massive improvement from 350% of duplicate lines to only 14%
So, we can deal with it
next step, improve our rate since we have only 6000 lines/sec

**Comment by original-brownbear** [comment]
@jmreymond alright sounds good, I guess we can close here then? The performance issue we should handle separately. That said, generally speaking, I'd advise giving LS 6.1.x a shot here since it contains a number of performance improvements not found in `5.6.x`
