### ISSUE TITLE
KV filter not outputting data when value_split matches source data

### ISSUE THREAD

**Issue by Sjaak01** [elastic/logstash#8686]
Hi,

I'm having an issue where the value_split isn't outputting data when it matches the log data.

Example:

Log data inside "message" field is key:value and split by ":", when setting value_split to ":" logstash runs without errors but no data is generated.

Change value_split to "=" and data is sent to file/elastic however it obviously isn't processed so instead of creating separate fields all data is put inside the message field.

Seems like something is amiss with the KV filter but no errors are generated and I lack the skills to investigate further.

Config:

input {
   udp {
     port => 9910
    type => "fortilog"
  }
}

filter {
 if [type] == "fortilog" {

	grok {
			match => ["message", "%{SYSLOG5424PRI:syslog_index}%{GREEDYDATA:message}"]
			overwrite => [ "message" ]
			tag_on_failure => [ "failure_grok_fortigate" ]
		}

        kv {

    value_split => ":"
    field_split => ","
}
}
}

output {
 if [type] == "fortilog" {
 file {
   path => "/path/forti/test-%{+YYYY-MM-dd.HH}.gz"
   gzip => true
 }
}
}

**Comment by Sjaak01** [comment]
Created https://discuss.elastic.co/t/extract-data-from/107862 with log and config examples.

The problem seems to be that

    kv {

value_split => ":"
field_split => ","

Does not create field:value for each item, instead nothing is happening. 

I confirmed this by first having a kv filter with a target defined. This writes the data to that target. I then applied another kv filter with just the value_split and field_split but the outputted data doesn't change (all data is still withing the target kv field, no separate values are created).

**Comment by andrewvc** [comment]
This might depend on your actual data. Can you repro this with the generator input? For instance, this works for me:

```
 bin/logstash -e 'input { generator { message => "some:thing,is:here"} } filter { kv { field_split => "," value_split => ":" } } output { stdout { codec => json_lines } }'

#output
{"sequence":7277,"some":"thing","@timestamp":"2017-11-22T18:20:05.251Z","@version":"1","host":"avce.local","is":"here","message":"some:thing,is:here"}
```

**Comment by Neo23x0** [comment]
I have the same problem with a Fortigate log file. @Sjaak01 Did you solve that problem?

**Comment by dlewis2710** [comment]
@Neo23x0 Not sure if you got through but follow this example (it also took me time to figure it)
https://discuss.elastic.co/t/working-example-fortigate-config-for-logstash/108493

since fortigate logs have a 'type' field, that interferes with type==fortilog by overwriting it I guess, so we need to overwrite the type field we get in kv as mentioned
    rename => { "type" => "ftg_type" }
    add_field => { "type" => "forti_log" }

**Comment by guyboertje** [comment]
I'm closing this as the KV filter has seen a lot of work since this was raised.

If anyone still has problems with the KV decoding then open an issue in the KV filter plugin repo.
