### ISSUE TITLE
Discuss: implicit placeholder substitution

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8703]
Logstash allows substitution from environment entries (and soon the secret store) via the `${key.to.sub}` syntax.  This replacement syntax is used across both the configuration files and settings (`logstash.yml`), 

While implementing the secret store, the following [comment](https://github.com/elastic/logstash/issues/8353#issuecomment-345389858) was raised w/r/t to how substitution works between Elasticsearch and Logstash. 

Elasticsearch supports "implicit" keys from their yaml configuration instead of explicit substitution syntax. In a desire to allow the two product configurations to work similarity, Logstash should support some form of implicit substitution keys.

However, Logstash's configuration requirements is a bit more complicated then Elasticsearch since Logstash has 2 types of configurations such that substituted settings in `logstash.yml` should also work with Logstash's configuration language.  This means without major surgery to Logstash configuration language, we need some type of placeholder value present to satisfy the language parser. 

As a means to support implicit configuration syntax, I am proposing to introduce `${}` as a valid substitution place holder that will substitute the key's name. 

For example in `logstash.yml`:
`xpack.monitoring.elasticsearch.password: ${}` 
will be effectively equal to 
`xpack.monitoring.elasticsearch.password: ${xpack.monitoring.elasticsearch.password}`

...and in the Logstash configuration:
 `jdbc_password => "${}"`   
will effectively be equal to  
`jdbc_password => "${jdbc_password}"`

While not completely implicit like Elasticsearch, it is close, saves a few characters, and works across both the settings and configuration.

I prototyped this out on a working branch, and this (plus some yet to be writtten tests) will be the sum of the changes: https://github.com/jakelandis/logstash/commit/4b599a68fdeab59b8d3812b4511cb369f3a903d0

cc: @tylersmalley

**Comment by jordansissel** [comment]
Some parts of Logstash.yml don't have named references. Further, user configuration is inconsistent in module:

Command line calls it one thing:

```
-M "netflow.var.elasticsearch.host=es.mycloud.com"
```

And in logstash.yml it is a different notation:

```
modules:
- name: netflow
  var.elasticsearch.hosts: "es.mycloud.com"
```

Two notes here:
1) The names are totally different
2) I don't think we have any prior art (in Elastic) for array-of-hashes with dot notation. in the yaml `modules.0.var.elastic.hosts`[1] vs CLI `netflow.var.elasticsearch.host`


[1] This assumes array notation is done with numeric fields like `modules.0` means the first element of the `modules` array.

**Comment by jordansissel** [comment]
Another thought: Implicit placeholders cause an extra step if we ever decide to rename a setting.

The benefit of implict placeholder/values is syntactic sugarg:

```
foo.bar.baz: ${foo.bar.baz}
```

We save a small amount of typing, and there's some weird edge cases, like what's the implied `password` field for these:

```
output {
  elasticsearch { ... }
  elasticsearch { ... }
}
```

**Comment by ph** [comment]
I've been looking at this also on the beats side, It might worth sharing effort and syntax, related issue: https://github.com/elastic/beats/issues/3982

One of the main difference we were thinking about specifying a source when using tags. %{keystore:output.elasticsearch.password}

**Comment by jakelandis** [comment]
@jordansissel - re modules:  good point, I hadn't thought of that... however,  I am pretty sure the keys gets converted to the second form internally `netflow.var.elasticsearch.host`. We will need to mirror that before we substitute.  A quick stab at that [here](https://github.com/jakelandis/logstash/commit/5d4c682cf8c3df3fc6f6b16e30cd8952a93c79d2).

re other other thoughts : yup... those are valid concerns, and the decision here is weighing the benefits vs. those cases. 

The benefits seem to be : 
* less typing = less chance for typos
* gets a bit closer to how ES works.

**Comment by jakelandis** [comment]
@ph - can we move this discussion to https://github.com/elastic/logstash/issues/8353 ?

We decided over there to explicitly mirror the environment variable syntax. Maybe we need to revisit that ?

**Comment by jakelandis** [comment]
As discussed in a meeting, we will for now, for-go implicit substitution.  Implicit substitution may introduce some additional complexity for both the user and the product. Specifically the complexities would be found w/r/t modules and/or plugin configuration and/or exact matching implementation behaviors of other elastic products.  

For now explicit configuration will be the way forward, and can be added later if deemed necessary.
