### ISSUE TITLE
Duplicate filter for Winlogbeat and Logstash

### ISSUE THREAD

**Issue by guilhermebasalia** [elastic/logstash#8724]
- Version: 6.0
- Operating System: Centos 7
- Config File - I'm having problem to get generate a filter configuration for windows events, please help me the how to generate this filter conf.

Thanks.
Guilherme Basalia

**Comment by jordansissel** [comment]
It sounds like you need assistance using Logstash. The best place to start asking this kind of question is over on the community discussion forums: https://discuss.elastic.co/

The github issues repository is intended for feature and bug discussions.
