### ISSUE TITLE
Script to generate report of 3rd party dependencies

### ISSUE THREAD

**Issue by mgreau** [elastic/logstash#8725]
For now, the following command is used to generate a report:

```
echo 'File.write(ENV["DEPENDENCIES_REPORTS_DIR"] + "/" + ENV["DEPENDENCY_REPORT"]  , "name,version,url,license\n" + Gem::Specification.all.collect { |g| [g.name, g.version.to_s, g.homepage, g.licenses.join("|")].join(",") }.join("\n"))' | bin/logstash --interactive pry
```

Please provide a script/command to generate [a CSV file](https://tools.ietf.org/html/rfc4180) to list 3rd party dependencies:
1.   The command/script provides an option to specify the output filename and path
        - the option/property provided by the script is named **`csv`** (example: `--csv`)
1. The CSV file generated is formatted as follow:
    - the 1st line contains the header line
    - then, one record per dependency
    - if a value for a field is not found, let it empty (ie: `"…",,"…"`)
1. The CSV file contains the following fields 
   - `name`: dependency name (name that identifies the library)
     - example for Java dependency: `groupId:artifactId`
     - example for Go dependency: `repository URI`
   - `version`: dependency version
   - `revision`: VCS commit hash
       - **optional** if the `version` is defined.
   - `url`: dependency URL (website, github repository…)
   - `license`: the license SPDX short identifier (ie: MIT, Apache-2.0…) 
      - the full list is available on [spdx.org website](https://spdx.org/licenses/ )
      - in the case of [license exceptions](https://spdx.org/licenses/exceptions-index.html), use the new `WITH` operator (ie: _GPL-3.0 WITH GCC-exception-3.1_)
      - in case of multiple licenses, delimit them with `|` (example: `EPL-1.0|GPL-2.0|LGPL-2.1`)
   - `copyright` (**optional**): authorship, company...
      - extract this value from the license file content

#### Example
```
"name","version","revision","url","license","copyright"
"jruby-openssl","0.9.21",,"https://github.com/jruby/jruby-openssl",EPL-1.0|GPL-2.0|LGPL-2.1,
```

Thanks.

**Comment by jordansissel** [comment]
(notes)

We have a few groups of dependencies:

1) explicit gem dependencies via bundler/rubygems
2) explicit java dependencies via maven
3) JRuby

**Comment by jordansissel** [comment]
@mgreau I may not have URLs for maven-sourced dependencies initially.

**Comment by jordansissel** [comment]
@mgreau Some dependencies do not seem to lend themselves easily to automatic processing.

For example, some `.jar` files are bundles of several other projects.

JRuby, for example, ships `jruby.jar` with these:

```
% find META-INF -name 'pom.properties'
META-INF/maven/org.jruby/jruby-core/pom.properties
META-INF/maven/org.jruby/dirgra/pom.properties
META-INF/maven/com.github.jnr/jnr-netdb/pom.properties
META-INF/maven/com.github.jnr/jnr-enxio/pom.properties
META-INF/maven/com.github.jnr/jnr-x86asm/pom.properties
META-INF/maven/com.github.jnr/jnr-unixsocket/pom.properties
META-INF/maven/com.github.jnr/jnr-posix/pom.properties
META-INF/maven/com.github.jnr/jnr-constants/pom.properties
META-INF/maven/com.github.jnr/jnr-ffi/pom.properties
META-INF/maven/com.github.jnr/jffi/pom.properties
META-INF/maven/org.jruby.joni/joni/pom.properties
META-INF/maven/org.jruby.extras/bytelist/pom.properties
META-INF/maven/org.jruby.jcodings/jcodings/pom.properties
META-INF/maven/com.headius/invokebinder/pom.properties
META-INF/maven/com.headius/options/pom.properties
META-INF/maven/com.headius/unsafe-fences/pom.properties
META-INF/maven/com.jcraft/jzlib/pom.properties
META-INF/maven/com.martiansoftware/nailgun-server/pom.properties
META-INF/maven/joda-time/joda-time/pom.properties
META-INF/maven/me.qmx.jitescript/jitescript/pom.properties
```

The pom property files do not have your requested license and URL information.

JRuby ships a `META-INF/COPYING` file that is 2886 lines of free-form text with no obvious structure. The JRuby COPYING file appears to be [maintained by hand](https://github.com/jruby/jruby/commits/master/COPYING).

For Logstash 6.0.0, there are:

* 154 `.jar` files
* 143 contain `META-INF` directories. 
* 31 contain freeform text `META-INF/DEPENDENCIES` files. 
* 1 (JRuby) contain `META-INF/COPYING`
* 61 contain `META-INF/LICENSE`
* 10 contain `META-INF/NOTICE.txt`

I'm not really sure how to go about this other than manual maintenance the same way JRuby does it.

Producing this file, accurately, will initially require quite a bit of work to write and verify by hand.

**Comment by jordansissel** [comment]
@mgreau please advise on the level of accuracy you need for the first delivery of this tool.

I have a branch working on this: https://github.com/elastic/logstash/tree/feature/dependency-list

```
bin/dependencies-report --csv /tmp/x
```

In order for the above tool to work, you must have run `rake test:install-core` to install all dependencies

**Comment by jordansissel** [comment]
Attached a sample output

[dependencies-master.csv.txt](https://github.com/elastic/logstash/files/1508715/dependencies-master.csv.txt)

**Comment by jordansissel** [comment]
I have some options for JRuby dependency listings:

1) [hand-translate JRuby's COPYING](https://github.com/elastic/logstash/commit/747cdef5b2cfd2ae93bfdbc63b8e188e40ec9a91) to csv - this misses the `version` field.
2) [use `mvn` to show dependencies ](https://github.com/elastic/logstash/commit/0cea973ffe8d42f47a46034abfc202ef29cbcc0f)- this misses the `url` and `license` fields.

**Comment by mgreau** [comment]
@jordansissel Thanks for the work here. As we discussed on slack, for the first version we can focus on the following:

* have a script as you have started to define it ( `bin/dependencies-report --csv /tmp/x`)
* have a first header line with columns names in the CSV file
* only focus on the `explicit gem dependencies via bundler/rubygems` and try to have as more as accurate information as possible
   * for example to find licenses identifiers, we can do something similar to Beats and apm-server projects 
https://github.com/mgreau/beats/blob/2783b087ce1a060487471145f78aee1d6e1d86b6/dev-tools/generate_notice.py#L208-L230


For JRuby, what do you think if we do something like this for now:

```
jruby,9.1.14.0,https://jruby.org/,EPL1.0|GPL2|LGPL2.1|Various;https://github.com/jruby/jruby/blob/9.1.14.0/COPYING
```

Then in a second step, for java dependencies, some work has to be done on Elasticsearch project. As it should be something very close to Logstash Java dependencies, we will see how we can share the code.

**Comment by mgreau** [comment]
@jordansissel 

> the option/property provided by the script is named csv (example: --csv)

Maybe the example was confusing; the goal is to have a common name for this option/property. So it's ok to have a Gradle or Rake command with this option/property if it's easier to do.

**Comment by jordansissel** [comment]
Filed https://github.com/elastic/logstash/pull/8837
