### ISSUE TITLE
Logstash 6.0 breaks s == 'str' comparison if s is not String

### ISSUE THREAD

**Issue by vbohata** [elastic/logstash#8728]
After upgrading from LS 5.6.0 to 6.0.0 following code stopped to work:
```
      hash = event.to_hash
      hash.each do |k,v|
        if v == '-'
          event.remove(k)
        else
          if v.is_a? String
            v.strip!
            v.gsub!('`', ',')
          end
        end
      end
```
To make it work again I have to do reverse the comparison, so:
`if '-' == v`
The reason is described by guyboertje in this discussion: https://discuss.elastic.co/t/logstash-6-0-breaks-ruby-event-iteration/109084/2:

> when v is the Timestamp the v == '-' is calling the ==(other) method on the Timestamp instance and this does a naive other.time without checking whether other (the String '-') is the same Class as v.
By switching them around the `==(other) call no happens on the String class and it in not so naive - it does better equality checks.

- Version: 6.0.0
- Operating System: RHEL/Centos 7.0, docker containers

**Comment by original-brownbear** [comment]
fixed in #8730
