### ISSUE TITLE
Windows compatibilty tests are broken

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8732]
Looks like they have been broken for a while.

https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-windows-compatibility/297/console

```
13:05:03 The project name is empty. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/4.3/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
13:05:05 :clean FAILED
13:05:08 
13:05:08 FAILURE: Build failed with an exception.
13:05:08 
13:05:08 * What went wrong:
13:05:08 Execution failed for task ':clean'.
13:05:08 > Unable to delete file: B:\vendor\jruby\bin\jruby.dll
13:05:08 
13:05:08 * Try:
13:05:08 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
13:05:08 
13:05:08 * Get more help at https://help.gradle.org
13:05:08 
13:05:08 BUILD FAILED in 8s
13:05:08 1 actionable task: 1 executed
```

**Comment by original-brownbear** [comment]
@jakelandis hmmm, looks like you still have jruby running there (hence the `jruby.dll` is still loaded and can't be deleted).  Can you check in the process manager, that there's no dangling JRuby?

**Comment by jakelandis** [comment]
@original-brownbear - I didn't see any explicit JRuby process. It could be held by dllhost depending on how JRuby is implemented on Windows.  I _think_ this may have something to do with the gradle changes, but am rebooting the Windows box first to rule out lingering processes.

**Comment by jakelandis** [comment]
It looks like the windows CI script for the unit tests are still using `rake test:core` which with some recent gradle enhancements will now result in gradle assemble getting called, which in turn calls clean, which blows up since JRuby is still running via the rake command. 

Easily reproducible locally, and am testing upgrading the Windows CI to use the new gradle wrapper.
