### ISSUE TITLE
ensure secret store has stronger permissions restrictions

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#8735]
This issue is about a feature that has not landed, but the permissions discussion was deferred, so in order to not forget about this, I am filing it here.

From: https://github.com/elastic/logstash/pull/8659#discussion_r152055542

Currently using 0660, we should probably use 0600 or at least 0640. We have no specification of behavior for the keystore, so it's unclear why 0660 is a good choice, so I am lobbying to align with the behavior of other safety-conscious tools (ruby netrc, ssh-keygen, etc, will default to 0600 and refuse to work if other permissions are used).

**Comment by jakelandis** [comment]
> so it's unclear why 0660 is a good choice

[This](https://github.com/elastic/elasticsearch/commit/7a035f5f8435962072157f46031e73855fe4a875) is why Elasticsearch went with 660, I will test our package based installation and post back here with the results.

**Comment by jakelandis** [comment]
@jordansissel - I made a PR to change the permissions to `644` https://github.com/elastic/logstash/pull/9006.  This is actually counter to the original intent of this issue, but given our current defaults this is what is needed to make this work out of the box. 

I believe that saving grace here for expanding the to global read is the ability to set the password that is only accessible via root access. For example, using RHEL 6.x as test base (and assume similar will also apply to other distro's) this is how we can set/view the password environment variable only with root access.

```
set +o history
export LOGSTASH_KEYSTORE_PASS=password123
sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash create
sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash add foo
sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash list

echo 'LOGSTASH_KEYSTORE_PASS=password123' | sudo tee --append /etc/logstash/startup.options > /dev/null
sudo /usr/share/logstash/bin/system-install
```

Then in another PR (or manual instructions), I will need to ensure that  `/etc/default/logstash` is owned by root with `600` permissions.

**Comment by jakelandis** [comment]
Maybe the instructions should be to set `/etc/sysconfig/logstash` instead messing with the startup options and `system-install`.

`echo 'LOGSTASH_KEYSTORE_PASS=password123' | sudo tee --append /etc/sysconfig/logstash > /dev/null` 
and then manually change the permissions to `600`
`sudo chmod 600 /etc/sysconfig/logstash`

 .. this would avoid an upgrade over-riding the startup config. (unless please-run already handles that for us ?)

**Comment by jakelandis** [comment]
Changes applied via https://github.com/elastic/logstash/pull/9006 , we will ship with root/root `644` keystore permissions by default. We will also provide instructions for how to ensure that the keystore password is only readable by root.

**Comment by jakelandis** [comment]
@jordansissel - are you comfortable with the resolution described above ?  Are there any follow up's (besides documentation) that you would like to see ?

**Comment by jordansissel** [comment]
Yeah I'm good with this outcome. Thank you :)
