### ISSUE TITLE
Drop support for rake test:core-fail-fast (or add it to gradle wrapper)

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8742]
Currently the CI scripts support `rake test:core-fail-fast` which is basically just an alias to set the rspec `--fail-fast` flag when running the Ruby unit tests.  

Currently CI doesn't actually use this option. With the introduction of Gradle wrappers to start replacing the `rake` tasks we should either add this option to the Gradle wrappers, or drop support from our CI scripts. 

Since it is not used, I am in favor of complete removal. 

Any objections ?

**Comment by original-brownbear** [comment]
@jakelandis I'm +1 on drop it :)
