### ISSUE TITLE
Java Execution: Does not handle clone filters correctly with multiple outputs

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#8757]
Pipelines that include filters that clone events and send to multiple output plugins clone events at different rates for each of the outputs:

Using the pipeline:

```
'input { 
  stdin { 
    type => 'type1' 
  } 
} 
filter { 
  clone { 
    add_field => { 
      'cloned' =>  'cloned' 
    } 
  clones => ['type1'] 
  } 
} 
output { 
  stdout { 
    codec => rubydebug 
  } 
  stdout { 
    codec => rubydebug 
  } 
  stdout {
    codec => rubydebug
  }
}
```

Results in one output receiving 2 events for each input event, one receiving 4, and the third receiving 6:

```
$ curl -s -XGET 'localhost:9600/_node/stats' | jq "{outputs: .pipelines.main.plugins.outputs}" 
{
  "outputs": [
    {
      "id": "4bfc542c67c31103855bcf2804f70aac058d01870037c9a3749d36af3de01f8e",
      "events": {
        "duration_in_millis": 3627,
        "in": 6,
        "out": 6
      },
      "name": "stdout"
    },
    {
      "id": "6d95b9b830b60d3f515719dbfbbc0e0a50d615b76cf1f3418b2f7e0dcb3bd0f8",
      "events": {
        "duration_in_millis": 429,
        "in": 18,
        "out": 18
      },
      "name": "stdout"
    },
    {
      "id": "0220c831eeef6c8110461f884952290c92f3ff5bc03af48a146ad653f5a9c384",
      "events": {
        "duration_in_millis": 272,
        "in": 12,
        "out": 12
      },
      "name": "stdout"
    }
  ]
}
```
 
Running this pipeline with `pipeline.java_execution: false` shows each of the outputs handling the same number of events

**Comment by robbavey** [comment]
cc @original-brownbear

**Comment by original-brownbear** [comment]
@robbavey thanks, will deal with this in #8691 (probably already fixed in that branch, will add a test for it) :)

**Comment by original-brownbear** [comment]
confirmed fixed by #8691 ... hopefully will be done with cleaning that one up tomorrow, added a spec for this case there.

**Comment by original-brownbear** [comment]
Fixed by #8691

**Comment by jordansissel** [comment]
@original-brownbear @jakelandis This isn't the first (or second) time pipeline internal changes have caused the `clone` filter behave incorrectly. Can one of you own adding integration tests for this?

**Comment by original-brownbear** [comment]
@jordansissel already added one for this case in #8691 :)
