### ISSUE TITLE
logstash 6.0.0 cannot input kafka 0.10.x

### ISSUE THREAD

**Issue by jinleileiking** [elastic/logstash#8781]
My env:

Kafka 0.10.x ---> logstash 6.0.0

I use kafka input to get kafka msg, it shows:

```
Coordinator discovery failed for group live-trans-new, refreshing metadata
```

I use logstash 2.3.6, is ok.

**Comment by jinleileiking** [comment]
Group coordinator lookup for group live-trans-new failed: The coordinator is not available.¬

**Comment by mori-ol** [comment]
I have same issue. 
In my case I can join group successfully but no output comes through.

**Comment by jordansissel** [comment]
Logstash 6.0.0 ships with a kafka client version 0.11.0.0, please see the [Kafka compatibility documentation](https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix) for compatibility details.

Logstash 5.x may be what you want. See here: https://www.elastic.co/guide/en/logstash/5.6/plugins-inputs-kafka.html
