### ISSUE TITLE
error"=>{"type"=>"invalid_type_name_exception", "reason"=>"mapping type name [[\"1\", \"1\"]] should not include ',' in it"}}}}

### ISSUE THREAD

**Issue by dzhyw** [elastic/logstash#8790]
- Version:logstash-5.6.3  elasticsearch5.6.3
- Operating System:CentOS release 6.4 (Final)
- Config File (if you have sensitive info, please remove it):

gork pattern:
WCC_SERVER_NGINX %{IPORHOST:clientip} %{NGUSER:ident} %{NGUSER:auth} \[%{HTTPDATE:timestamp}\] \"%{WORD:verb} %{URIPATH:interface}\?*(?<interface_parameter>\S+)? HTTP/%{NUMBER:httpversion}" \"%{NUMBER:response}" %{NUMBER:bytes} "-"\s+%{QS:agent}\s+"(?:%{IP:http_forward}|-)"ups_addr: %{QS:ups_addr}\s+ups_status: "%{NUMBER:ups_status}"\s+ups_resp_time: "%{NUMBER:ups_resp_time}"\s+request_time: "%{NUMBER:request_time}""(?:%{WORD:grid}|-)"\s+"(?:%{WORD:imsi}|-)"\s+"(?:%{WORD:urid}|-)"\s+

~~~
[root@logstash01 conf.d]# cat server_iphone-es.conf 
input {
	redis {
        host => "192.168.199.165"
        port => "6379"
        db => "1"
        data_type => "list"
        key => "server"
	batch_count => "1"
        tags => ["iphone"]
	}
}


filter {
   if "iphone" in [tags] {
        grok {
                match => {"message" => "%{WCC_SERVER_NGINX}"}
                patterns_dir => "/usr/local/logstash/pattern"
        }

        kv {
                add_field =>{"request"=>"%{interface}?%{interface_parameter}"}
		source => "interface_parameter"
                field_split => "&?"
                value_split => "="
        }
	
	geoip {
		source => "clientip"
		target => "geoip"
                database => "/usr/local/logstash/geoip2/GeoLite2-City.mmdb"
                default_database_type => "City"
	}

        urldecode {
                all_fields => true
        }
   }
}

output {
   if "iphone" in [tags] {
       elasticsearch {
               hosts => "192.168.199.171"
               index => "logstash-server-%{+YYYY.MM.dd}"
	}
   }
} 
~~~

- Sample Data:

~~~
223.104.64.6 - - [04/Dec/2017:09:23:55 +0800] "GET /gstudy/api?dist=Apple&advon=1&buserid=912532904003548460&tokenid=&hres=750&vres=1334&dos=iOS&dosv=10.2&model=iPhone&brand=Apple&app=wochacha4&utype=iPhone7,2&buid=5108503820801603282&city_id=330&udid=4a2e5768c8a7604fb1570142ade135be6c28c5b9&openid=4a2e5768c8a7604fb1570142ade135be6c28c5b9&v=9.4.0&devicetoken=f132b43a8139d601840b640913f7e04a&token=OG-k2kpNrc1aO6XkinPF6uOTLKHV65S4O2_D91pDTP0EIDwgHnp01BeIdqrniguV9BMniDj6kKunfhcJp33wPg&source=iphone&connectnet=4g&lng=113.649182&lat=22.954947&os=iphone&his=1468300628.1510196799&device_model=iPhone&device_brand=iPhone7,2 HTTP/1.1" "200" 769 "-" "wochacha/9.4.0 (iPhone; iOS 10.2; Scale/2.00)" "-"ups_addr: "172.10.12.1:80" ups_status: "200" ups_resp_time: "0.058" request_time: "0.058""4a5fe307ed79b21d22b6eee1ec7fcae5" "4a2e5768c8a7604fb1570142ade135be6c28c5b9" "1"
~~~

- Steps to Reproduce:
logstash run error:

~~~
error"=>{"type"=>"invalid_type_name_exception", "reason"=>"mapping type name [[\"1\", \"1\"]] should not include ',' in it"}}}}
~~~

**Comment by RealLinkers** [comment]
Any solution to this? I am experiencing the same issue.

**Comment by dzhyw** [comment]
Does anyone know how to solve it?

**Comment by PMDubuc** [comment]
I'm seeing a similar error in my Logstash logs.  Any comments on the cause?

:response=>{"create"=>{"_index"=>"logstash-2019.03.22", "_type"=>"[\"log\", \"syslog\"]", "_id"=>"AWmmdT7OCZIZoibaAF7X", "status"=>400, "error"=>{"type"=>"invalid_type_name_exception", "reason"=>"mapping type name [[\"log\", \"syslog\"]] should not include ',' in it"}}}, :level=>:warn}

**Comment by rishabh-gupta2** [comment]
Facing similar issue. Do let us know of any open solution:

:response=>{"index"=>{"_index"=>"dataappanalytics-2019.03.29", "_type"=>"metric_api_event", "_id"=>"AWnP9xCgl97BCeGF97TM", "status"=>400, "error"=>{"type"=>"invalid_type_name_exception", "reason"=>"mapping type name [List View | Hotel Click | Connaught Place, Delhi] should not include ',' in it"}}}}

**Comment by yaauie** [comment]
When the Logstash Elasticsearch Output Plugin is connected to an Elasticsearch <= 5.x and configured without a `document_type` option, it stringifies the value of the event's `[type]` field; if this value is an array, the string representation contains characters that are not legal in an Elasticsearch document type name.

The easiest way around this is to specify your document type explicitly in the `elasticsearch` output plugin's configuration:

~~~
output {
  elasticsearch {
    # ...
    document_type => "your_type"
  }
}
~~~

As noted in the [`document_type` documentation](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/docs/index.asciidoc#plugins-outputs-elasticsearch-document_type), the provided Vale can be a sprintf format string referencing values on the event.
