### ISSUE TITLE
backport PQ batch maximization as a 5.6 bugfix?

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8802]
Should we backport #8702 as a bugfix in 5.6?

**Comment by jordansissel** [comment]
My thoughts: We should try to limit fixes in patch releases that resolve breakages, where a breakage is something that does not work correctly, and correctly is something along the lines of "produces the correct output". Major performance degradation I would consider also backporting.

As for this change, the rough heuristic I look at to target a patch release on a previous major:

1) The net change is +250, -143, and touches 9 files.
2) The improvement is speed-related.
3) The improvement does not change the resulting output (ie: does not correct for a computation mistake)
4) We have a new major (6.x) available

Given this data, I am -1 on backporting.

If we are doing a 5.7, I'm in favor of including this in 5.7, so maybe backport this to 5.x if we are considering a 5.7 release?

**Comment by colinsurprenant** [comment]
If we go for 5.7 and 5.7 is only a possibility, I'd say we wait for a 5.7 release decision and make the backport then because the backport will be non-trivial and it'd be a waste to do it "just in case".

**Comment by colinsurprenant** [comment]
We agreed to not backport in a 5.6 patch release and possibly backport in 5.7 if it comes up but there is no plan for a 5.7 so far. Closing.
