### ISSUE TITLE
Include Kafka client library version in plugin verbose listing

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#8809]
Not sure if it is possible to do from our plugins list command.  Given that the Logstash kafka plugins' compatibility is really based on the underlying Kafka client library versions' compatibility with Kafka broker versions, it can be helpful for admins if we can enhance the logstash plugins cli command to return (as part of the listing in verbose mode) not just the Logstash kafka plugin version, but also the underlying version of the Kafka client libraries packaged with the plugin.

**Comment by jordansissel** [comment]
We are documenting this soon in the Kafka plugin docs. Is this insufficient?

Do we need this plugin listing cli also? (It’s probably a lot of work just
to make two plugins have extra output)

**Comment by ppf2** [comment]
If it's a lot of work, then just having them documented (and updated on new versions) will be sufficient, thx!
