### ISSUE TITLE
org.logstash.config.ir.graph.GraphTest > complexConsistencyTest FAILED

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#8829]
CI Build: https://logstash-ci.elastic.co/job/elastic+logstash+6.1+multijob-unix-compatibility/os=oraclelinux/15/console

Failure:

```
20:53:46 org.logstash.config.ir.graph.GraphTest > complexConsistencyTest FAILED
20:53:46     org.junit.ComparisonFailure: expected:<[6de45043af6004f983d0b17aa80b6f98bf68dfd2591d3aa2086df9e65041dd4a]> but was:<[76d98686a05dd3786b26787b7138113152797e71e709692523aed2f5013d6a85]>
20:53:46         at org.junit.Assert.assertEquals(Assert.java:115)
20:53:46         at org.junit.Assert.assertEquals(Assert.java:144)
20:53:46         at org.logstash.config.ir.graph.GraphTest.complexConsistencyTest(GraphTest.java:89)
```

**Comment by jsvd** [comment]
Other instances of this failed spec:
- https://logstash-ci.elastic.co/job/elastic+logstash+6.1+multijob-unix-compatibility/os=oraclelinux/16/console
- https://logstash-ci.elastic.co/job/elastic+logstash+6.1+multijob-unix-compatibility/os=oraclelinux/17/console

**Comment by original-brownbear** [comment]
@andrewvc you fixed already didn't you?

**Comment by original-brownbear** [comment]
never mind, def fixed in https://github.com/elastic/logstash/pull/8836. Just realised this was created+merged after this issue was opened => all good closing here :)
