### ISSUE TITLE
fluentd input (codec) is not compatible with fluentd 0.14.X as a log shipper

### ISSUE THREAD

**Issue by muhahacz** [elastic/logstash#8834]
fluentd input (codec) is not working with fluentd 0.14.X as a log shipper unless you setup time_as_integer true in your fluentd config

- Version:
6.0.1
- Operating System:
Docker

Logstash log:
`[2017-12-12T12:42:04,902][ERROR][logstash.codecs.fluent   ] Fluent parse error, original data now in message field {:error=>#<MessagePack::UnknownExtTypeError: unexpected extension type>,`

Workaround:
```
I got MessagePack::UnknownExtTypeError error. Why?

This error happens when forwarder’s fluentd is v0.14 and receiver’s fluentd is 0.12. To avoid this problem, set time_as_integer to out_forward setting in v0.14 fluentd.
```

Source:
https://www.fluentd.org/blog/fluentd-v0.14.9-has-been-released - Section out_forward

**Comment by jordansissel** [comment]
Hi! Thank you for filing this. Can you reopen this on the fluent codec repo? https://github.com/logstash-plugins/logstash-codec-fluent/issues
