### ISSUE TITLE
X-Pack SSL documentation

### ISSUE THREAD

**Issue by msteggink** [elastic/logstash#8838]
When following the documentation instructions on 
https://www.elastic.co/guide/en/logstash/current/configuring-logstash.html, to specify the CA certificate:
```
xpack.monitoring.elasticsearch.ssl.ca: [ "/etc/logstash/ca.cer" ]
```
It produces the following error.
```
[2017-12-13T09:15:55,753][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.ssl.ca" must be a String. Received: ["/etc/logstash/ca.cer"] (Array)>
```

Should be:
```
xpack.monitoring.elasticsearch.ssl.ca: "/etc/logstash/ca.cer"
```

- Version: logstash-6.0.0-1.noarch
- Operating System: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by geekpete** [comment]
This one looks to have been resolved in the 6.0 docs and later?
https://www.elastic.co/guide/en/logstash/6.0/configuring-logstash.html

`xpack.monitoring.elasticsearch.ssl.ca: /path/to/ca.crt`
