### ISSUE TITLE
Failing to download deb file from elastic.co

### ISSUE THREAD

**Issue by mszymo** [elastic/logstash#8844]
- Version: 5.6.5 and 6.0.1, probably more
- Downloads attempted through the puppet module and through browsers (firefox and chrome). Appears to start the download but fails halfway through

**Comment by jakelandis** [comment]
I just downloaded all the artifacts from 5.6.5 and 6.0.1 all seems fine. Maybe it was a temporary issue ?

Can you try again and compare against checksum. 

Here is what I used to test:
```bash
cd /tmp
rm logstash*
export VERSION=5.6.5
DISTS=(deb rpm tar.gz rpm)
for DIST in "${DISTS[@]}"
do   
    wget https://artifacts.elastic.co/downloads/logstash/logstash-$VERSION.$DIST.sha512
    wget https://artifacts.elastic.co/downloads/logstash/logstash-$VERSION.$DIST	
done
```

**Comment by mszymo** [comment]
Yeah downloads are working now, we were just panicking because it was breaking a production enviroment. Thanks for testing, I'll close this now.
