### ISSUE TITLE
[DISCUSS] useless check in codec

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8847]
The line, plain and s3-plain codecs perform this type of check in the `encode` method:

```
 if event.is_a? LogStash::Event and @format
   ...
```

The check for `event.is_a? LogStash::Event` is useless since this was to prevent encoding the legacy *signaling* events like the *SHUTDOWN* event. Now this signals are processed OOB from the processing queue. 

I suggest we remove that check. 

Any objections?

**Comment by andrewvc** [comment]
None on my end!

**Comment by colinsurprenant** [comment]
All above PRs ready for review.

**Comment by jsvd** [comment]
When was the inbound signaling removed? I see references to the Shutdown event in releases like logstash 5.2.0, are we taking care of this restriction? I.E. if you run `bin/logstash-plugin update` on logstash 5.2.0 will things break?

**Comment by andrewvc** [comment]
@jsvd IIRC the shutdown event isn't actually passed to plugins since LS 2.2 or so ( I forget the exact version ). IIRC the ng pipeline used a poison pill, but never passed it to plugins.

**Comment by colinsurprenant** [comment]
as @andrewvc mentioned, the concept of in-band signaling using the `LogStash::SHUTDOWN` event was removed starting in 5.0. We still do have the concept of a `LogStash::SignalEvent::ShutdownEvent`  which `LogStash::SHUTDOWN` now point to but this is now used in out-of-band signalling using a separate signal queue and these are never pushed to the plugins.

**Comment by jsvd** [comment]
Thanks folks, I confirmed this too (also in 2.4.x).

**Comment by colinsurprenant** [comment]
all done.
