### ISSUE TITLE
Logstash init error

### ISSUE THREAD

**Issue by amouzigh** [elastic/logstash#8859]
Hello,
I'm using logstash 6.1.0. 
When running with this configuration: logstash.conf file
_______________________________________________________
input {
  file {
  codec =  plain{
  charset =  "UTF-8"
  }
  path =  ["C:\Users\amouzigh\Dropbox\SRC\MES\DataLake\Tests Data Lake\bin\Debug\data\file\current\*.csv"]
  sincedb_path =  "null"
  start_position =  "beginning"
 }
 }
filter {
  if [message] =~ /^"Identifier";"Value";"Timestamp";"DateAction";"Origin"/ {
  drop { }
}
csv {
  columns =  ["Identifier";"Value";"Timestamp";"DateAction";"Origin"]
  separator =  ";"
  source =  message
  #remove_field =  ["Identifier";"Value";"Timestamp";"DateAction";"Origin"]
 }
}
output {
  elasticsearch {
  host =  "localhost"
}
stdout { codec =  rubydebug }
}
__________________________________________________________________________________________________
I have an error:
[2017-12-19T12:23:08,247][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.0"}
[2017-12-19T12:23:09,143][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-12-19T12:23:09,179][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exc
eption=>"LogStash::ConfigurationError", :message=>"Expected one of #, => at line 3, column 9 (byte 26) after input {\n  file {\n  codec ", :backtrace=
>["C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:42:in `compile_imperative'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logsta
sh/compiler.rb:50:in `compile_graph'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jrub
y/RubyArray.java:2486:in `map'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "C:/appl/elk/logstash-6.
1.0/logstash-core/lib/logstash/pipeline.rb:51:in `initialize'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/pipeline.rb:171:in `initialize'
", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/lo
gstash/agent.rb:335:in `block in converge_state'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "C:/appl/
elk/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "C:/appl/elk/logs
tash-6.1.0/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:166:in `block
 in converge_state_and_update'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "C:/appl/elk/logstash-6.1.0
/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:90:in `execu
te'", "C:/appl/elk/logstash-6.1.0/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "C:/appl/elk/logstash-6.1.0/vendor/bundle/jruby/2.3
.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
Regards
Driss

**Comment by robbavey** [comment]
Hi @amouzigh 

For future reference, the [discuss forum](https://discuss.elastic.co/c/logstash) is the best place to ask these sort of configuration questions, rather than github, which is best suited for bugs and enhancement requests. 

That being said - taking a quick look at your configuration, your issue is likely that you are using `=` in your configuration files instead of `=>` - see [the Logstash configuration docs](https://www.elastic.co/guide/en/logstash/current/configuration.html) for details.
