### ISSUE TITLE
Support setting pipeline.id via CLI option

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#8867]
Currently it is possible to override the default pipeline name, `main`, by setting `pipeline.id` in `logstash.yml`. However it is not possible to perform the same operation via the CLI.

This issue is to add a `--pipeline.id` CLI option corresponding to the `pipeline.id` `logstash.yml` option. Note that either one only comes into play when either the `-f` or `-e` options are used to specify the pipeline to run.

**Comment by Shashwat986** [comment]
I'm assuming this can be closed. If not, anything I can pick up here?

**Comment by ycombinator** [comment]
Closed via #8868.
