### ISSUE TITLE
logstash is not  support use proxy connect to es cloud or other es cluster 

### ISSUE THREAD

**Issue by zqc0512** [elastic/logstash#8878]
logstash is support use proxy connect to es cloud or other es cluster ?

the packetbeat can update to es with proxy, but logstash can't support
https://discuss.elastic.co/t/how-setting-about-logstash-with-proxy-connect-to-es-cloud/112346

OS:centos 7.3
logstash:5.6.5
es cloud: 5.6.5

**Comment by zqc0512** [comment]
can close 
see:
https://discuss.elastic.co/t/how-setting-about-logstash-with-proxy-connect-to-es-cloud/112346/7

is support. i find where to configure it 
thanks.
elasticsearch {
    hosts => "https://1d482615da63165c58e0b465b58398d3.ap-southeast-1.aws.found.io:9243/"
    user => "xxx" 
    password => "xxx" 
    proxy => "xxx.xxx.xxx.xx"
    index => "apache_elastic_example"
    template => "./apache_template.json"
    template_name => "apache_elastic_example"
    template_overwrite => true
  }

**Comment by guyboertje** [comment]
Solved by originator - use proxy setting
