### ISSUE TITLE
cloning a LogStash::Timestamp results in an empty java object

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#8888]
```
2.3.0 :012 > LogStash::Timestamp.now.to_java
 => #<Java::OrgLogstash::Timestamp:0x48110259> 
2.3.0 :013 > LogStash::Timestamp.now.clone.to_java
 => nil 
```

My suspicion is that the [initialization of a LogStash::Timestamp](https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/ext/JrubyTimestampExtLibrary.java#L36-L39) requires the call to `setTimestamp` on a new instance. When doing a clone this set operation isn't called so the resulting cloned object doesn't contain the org.logstash.Timestamp instance

**Comment by original-brownbear** [comment]
Fixed all the way back to `5.6` via #8889 #8890 and #8891

**Comment by fbaligand** [comment]
Great ! 
Thanks @original-brownbear !

**Comment by rolodato** [comment]
Thanks for the quick response! Forgot to mention:

```
$ ruby --version
jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 OpenJDK 64-Bit Server VM 25.161-b14 on 1.8.0_161-b14 +jit [linux-x86_64]
```

**Comment by fbaligand** [comment]
Hi all,

I confirm I have the same issue with Logstash 6.2.2

**Comment by jsvd** [comment]
in ruby a clone is shallow:

```ruby
jruby-9.1.12.0 :001 > arr = [Object.new]
 => [#<Object:0x6c130c45>] 
jruby-9.1.12.0 :002 > arr.first.object_id
 => 2000 
jruby-9.1.12.0 :003 > arr.clone.first.object_id
 => 2000 
```

and in most situations we want to ensure that we aren't passing object references around while we're mutating the clones, so we want to do a deep clone. The only "clean" way in ruby to do a deep clone is using marshalling, which saves us from the trouble of implementing a true `deep_clone` with all the insane traversal necessary:

```
jruby-9.1.12.0 :004 > Marshal.load(Marshal.dump(arr)).first.object_id
 => 2002 
```

**Comment by original-brownbear** [comment]
@jsvd I guess the best thing we can do then, is to add a special case for `TimeStamp` to `deep_clone` when we can't marshal Java fields. (that should, in fact, be fine, since I fixed that `.clone` method here earlier and it's ok to shallow clone its immutable fields). Any reason not to do that?

**Comment by jsvd** [comment]
This could also probably be solved by implementing the [marshalling strategy](http://ruby-doc.org/core-2.2.2/Marshal.html#module-Marshal-label-marshal_dump+and+marshal_load) for this particular class.

I'm good with either solution. Eventually we'll rewrite most of the LogStash::Utils and the mutate field anyway.

**Comment by xSAVIKx** [comment]
I'm also receiving the same stack trace on `docker.elastic.co/logstash/logstash-oss:6.2.4`.

**Comment by original-brownbear** [comment]
@jsvd thanks, went for `.clone` because I already fixed the `clone` method here before :) so that was a one liner in https://github.com/elastic/logstash/pull/9405 :)

**Comment by original-brownbear** [comment]
fixed in https://github.com/elastic/logstash/pull/9405 :)

**Comment by ebuildy** [comment]
This bug also occurred if you want to copy ``@metadata`` generated by ``dead_letter_queue``:

```
input
{
  dead_letter_queue
  {
      path => "/usr/share/logstash/dead_letter_queue"
      commit_offsets => true
      pipeline_id => "main"
  }
}

filter
{
  mutate
  {
      copy => {"@metadata" => "_logstash_metadata"}
  }
}
```
