### ISSUE TITLE
xpack.monitoring.elasticsearch.url for xpack not working in v6.1.0

### ISSUE THREAD

**Issue by wilburBlog** [elastic/logstash#8895]
Upgrade v5.6.3 to v6.1.0 rencently, after installing xpack and setting logstash.yml as following, i found out xpack monitoring  not working.
 In the following log we can see that licensechecker keeps to connect es as localhost:9200,ignore the setting in logstash.yml. But the same config  works fine in v5.6.3. 
Please check  this problem, thanks a lot.

**Version:**  
v6.1.0
**Operating System:**
redhat 4

**Config File :**
#logstash.yml
xpack.monitoring.elasticsearch.url: http://192.168.0.100:9200

**Sample Data:**

[2017-12-29T11:45:40,689][INFO ][logstash.licensechecker.licensereader] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>_http://localhost:9200/_, :path=>"/"}
[2017-12-29T11:45:40,696][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}

**Comment by wilburBlog** [comment]
Turns out the setting below somehow effects the **_licensereader_** to connect to **_localhost:9200_**,instead of the right es host. It works fine after commenting this setting in logstash.yml.
#node.name: actAll

**Comment by mazadard** [comment]
I have exactly the same problem, and I don't know what to do.. @wilburBlog what am I supposed to do whith node.name ?

**Comment by wilburBlog** [comment]
Comment or remove that line should work，like this：
 #node.name: _yourNodeName_

**Comment by mazadard** [comment]
I have tried both remove, and this logstash.yml: 

node.name: "192.168.1.65"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: "http://192.168.1.65:9200"

I still got errors:

[Ruby-0-Thread-10: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:228] licensereader - Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connexion refusée (Connection refused)"}

It is searching at "http://localhost:9200", look like that'is the problem.

**Comment by ssimpo** [comment]
@mazadard Me too

The node.name was already commented out and xpack.monitoring.elasticsearch.url is set.  It still tries to connect to localhost.

@wilburBlog Any chance of reopening this?

**Comment by ssimpo** [comment]
@mazadard Thanks, actually, I had discovered the same thing myself not long after writing the message above.
