### ISSUE TITLE
DLQ Input should be able to delete read messages

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#8904]
It is commonly the case that users will have a secondary pipeline for processing DLQed messages. The DLQ input should be able to mark processed messages as 'dead', and eligible for immediate deletion.

This would enable use cases like https://discuss.elastic.co/t/why-does-logstash-not-clear-dlq-after-successful-fixes/113618

**Comment by andrewbanchich** [comment]
+1000

**Comment by reswob10** [comment]
Can you please make this an optional switch?  It can default to on, but can be set to off at the discretion of the admin.

**Comment by dannygoulder** [comment]
+1

**Comment by victor-mendes-eduardo** [comment]
+1

**Comment by keshrisohit** [comment]
+1

**Comment by alexPolisevschi** [comment]
+1

**Comment by jakub-bacic** [comment]
+1

**Comment by SuchiSmita-N** [comment]
Just curious, Is it still ongoing ? We have enabled DLQ but the processed messages are not deleted automatically.

**Comment by opiumfor** [comment]
+1

**Comment by Alsheh** [comment]
+1

**Comment by zmays** [comment]
Is there a current solution for when the DLQ fills up? I've added a pipeline for DLQ, but it filled up and stopped processing events. I was under the impression it was supposed to rotate the file automatically from docs here:

```
File Rotationedit
Dead letter queues have a built-in file rotation policy that manages the file size of the queue. When the file size reaches a preconfigured threshold, a new file is created automatically.

By default, the maximum size of each dead letter queue is set to 1024mb. To change this setting, use the dead_letter_queue.max_bytes option. Entries will be dropped if they would increase the size of the dead letter queue beyond this setting.
```

Which, upon reading now is a little confusing, it says that a new file will be automatically created, and that entries will be dropped.

**Comment by vivekkarne** [comment]
+1

**Comment by DonatasR** [comment]
+1

**Comment by delhisanjay** [comment]
Facing same issue i.e. DLQ does not clear queue content even after successful processing. Do we have fix for above issue --

**Comment by bendoerr** [comment]
Maybe it should be renamed. "Dead Letter Dump"?

**Comment by jerome83136** [comment]
+1

**Comment by naimmalek** [comment]
+1000

**Comment by arpit-ghiya** [comment]
+1

**Comment by bendoerr** [comment]
Any bets on how long this issue will stay open without comment from the maintainers?

**Comment by tom-x1** [comment]
Guys,... this is now 3 years old and still unsolved

**Comment by HamoonDBA** [comment]
+1000

**Comment by HamoonDBA** [comment]
To delete processed logs, is necessary to stop logstash?
Plus, How do we know which log files have been processed and ready to delete?

**Comment by Alsheh** [comment]
@HamoonDBA

> Plus, How do we know which log files have been processed and ready to delete?


I wrote a script that runs periodically to delete the files `*.log` in `data/dead_letter_queue/main/` based on age or when the directory reaches a certain size.

> To delete processed logs, is necessary to stop logstash?

However, with the aforementioned script, I ran into an issue where the DLQ plugin stops processing the DLQ data (see relevant logstash error logs below). The one way I was able to get it to continue processing the DLQ data is by restarting the logstash service.

```
A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:dead-letter-queue
  Plugin: <LogStash::Inputs::DeadLetterQueue pipeline_id=>"main", path=>"/usr/share/logstash/data/dead_letter_queue", id=>"1c50c536a8666c2125a7ee59d4881e891e4780485b02071e65aab109863f8ed0", commit_offsets=>true, enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_94f49a8a-437c-47ef-b9cf-c9a040f13c1a", enable_metric=>true, charset=>"UTF-8">>
  Error: invalid checksum of record
  Exception: Java::JavaLang::RuntimeException
  Stack: org.logstash.common.io.RecordIOReader.getRecord(org/logstash/common/io/RecordIOReader.java:241)
org.logstash.common.io.RecordIOReader.readEvent(org/logstash/common/io/RecordIOReader.java:257)
org.logstash.common.io.DeadLetterQueueReader.pollEntryBytes(org/logstash/common/io/DeadLetterQueueReader.java:140)
org.logstash.common.io.DeadLetterQueueReader.pollEntry(org/logstash/common/io/DeadLetterQueueReader.java:117)
org.logstash.input.DeadLetterQueueInputPlugin.run(org/logstash/input/DeadLetterQueueInputPlugin.java:82)
jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:456)
org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:317)
usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_input_minus_dead_letter_queue_minus_1_dot_1_dot_5.lib.logstash.inputs.dead_letter_queue.run(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-dead_letter_queue-1.1.5/lib/logstash/inputs/dead_letter_queue.rb:60)
usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.inputworker(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:405)
usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$inputworker$0$__VARARGS__(usr/share/logstash/logstash_minus_core/lib/logstash//usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb)
usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_input(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:396)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
java.lang.Thread.run(java/lang/Thread.java:834)
```

I hope logstash can natively remove sent DLQ data since it causing a bit of manual work to keep DLQ running at the moment .

**Comment by andsel** [comment]
Completed in phase 3 of #10493, release `8.4.0`
