### ISSUE TITLE
 could not coerce BigDecimal to class java.math.BigDecimal

### ISSUE THREAD

**Issue by Georgeqhh** [elastic/logstash#8912]
- Version:6.1.1
- Operating System:windows 10
- Config File (if you have sensitive info, please remove it):
input {
    stdin {
    }
    jdbc {
      jdbc_connection_string => "jdbc:mysql://dbmysql.h9_test:3306/h9_main?characterEncoding=utf8&useSSL=true&nullNamePatternMatchesAll=true"
      jdbc_user => "***"
      jdbc_password => "***"
      jdbc_driver_library => ".\mysql-connector-java-5.1.26-bin.jar"
      jdbc_driver_class => "com.mysql.jdbc.Driver"
	  statement => "select (select sum(money) from lottery where create_time < curdate())  as total_grant_money , (select sum(money) from withdrawals_record where create_time < curdate()) as total_withdraw_money "
	  schedule => "*/5 * * * * *"
	  type => "item_value"
	  jdbc_default_timezone => "UTC"
    }
}
output {

if [type] == "item_value" {
	jdbc {
			connection_string => "jdbc:mysql***"
			username => "***"
			password => "***"
			driver_jar_path => ".\mysql-connector-java-5.1.26-bin.jar"
			statement => [ "REPLACE INTO item_value (total_grant_money, total_withdraw_money) VALUES(?, ?) ","total_grant_money","total_withdraw_money"]
	}
	
} 
	 stdout { codec => rubydebug }
}
- Sample Data:
- Steps to Reproduce:
[ERROR][logstash.outputs.jdbc    ] JDBC - Exception. Not retrying. event: "{"total_withdraw_money":31207483.17,"@timestamp":"2018-01-05T03:00:40.368Z","type":"item_value","@version":"1","total_grant_money":10.00}". {:exception=>#<TypeError: could not coerce BigDecimal to class java.math.BigDecimal>}

**Comment by Georgeqhh** [comment]
wht get the error?

**Comment by original-brownbear** [comment]
@Georgeqhh can you reproduce this while running with --debug logging? This is really hard to track down without a stacktrace on that exception I'm afraid.

**Comment by orgertot** [comment]
i get this error too...

**Comment by kares** [comment]
should no longer be relevant, since JRuby 9.2 (LS 7.5) BigDecimals coerce to java.math.BigDecimal
