### ISSUE TITLE
Test failure: Out of memory on pq integration test

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#8918]
https://logstash-ci.elastic.co/job/elastic+logstash+6.1+multijob-integration-pq-2/42/console

```

21:57:17   1) CLI > logstash-plugin prepare-offline-pack create a pack from a wildcard successfully create a pack
21:57:17      Failure/Error: expect(unpacked.plugins.collect(&:name)).to include(*filters)
21:57:17        expected ["logstash-filter-split", "logstash-filter-geoip", "logstash-filter-aggregate", "logstash-filter-elas...ze", "logstash-filter-metrics", "logstash-filter-cidr", "logstash-filter-csv", "logstash-filter-kv"] to include "Bundler::GemspecError: There was a Errno::ENOMEM while loading logstash-filter-qatest-newer.gemspec: ", "Cannot allocate memory - git ls-files from", "  /opt/logstash/build/logstash-6.1.2-SNAPSHOT/vendor/local_gems/449e2de5/logstash-filter-qatest-0.1.1/logstash-filter-qatest-newer.gemspec:13:in `block in eval_gemspec'", <output truncated manually for readability>
```

**Comment by original-brownbear** [comment]
I think I tracked down the reason Zombie containers pile up and cause us to run OOM in https://github.com/elastic/logstash/pull/8953 to a Docker bug. Let's see if we can verify this somehow :)

**Comment by original-brownbear** [comment]
@jakelandis Do you have any update on whether or not we still see Docker zombies that cause this? :)

**Comment by jakelandis** [comment]
I checked the 3 docker hosts and no zombies! 

Interestingly there were docker instances running from a recent (~5min)  PR that was superseded by a new commit. It seems that we (Jenkins ?) is not killing the running docker container for the same PR, even though the Jenkins job is done. I vaguely remember running into this before and thought I fixed it ... will log a follow up issue.

**Comment by jakelandis** [comment]
Follow up issue https://github.com/elastic/logstash/issues/9017

Closing this issue since it appears that Zombie issue is resolved.
