### ISSUE TITLE
The logstash cant't automatically clean up sincedb file, if inode was deleted. 

### ISSUE THREAD

**Issue by lyddragon** [elastic/logstash#8929]
log file rotated and deleted,but the inode exist in the sincedb file.when new file is assigned the same inode,logstash process error reading log file.

**Example:**
log file:

> 1048593 -rw-r--r-- 1 root root 640205159 Dec  9 23:59 nginx.access.log-2017-12-09
> 1048619 -rw-r--r-- 1 root root 689935513 Dec 10 23:59 nginx.access.log-2017-12-10
> 1048685 -rw-r--r-- 1 root root 717981488 Dec 11 23:59 nginx.access.log-2017-12-11
> 1048688 -rw-r--r-- 1 root root 599901894 Dec 12 12:41 nginx.access.log

logstash sincedb file:

> 1048593 0 64785 640205159
> 1048619 0 64785 689935513
> 1048685 0 64785 717981488
> 1048688 0 64785 599901894

Now,  log file rotate, delete old log file(nginx.access.log-2017-12-09), and create new log file(**inode:1048593, same as nginx.access.log-2017-12-09**):

> 1048619 -rw-r--r-- 1 root root 689935513 Dec 10 23:59 nginx.access.log-2017-12-10
> 1048685 -rw-r--r-- 1 root root 717981488 Dec 11 23:59 nginx.access.log-2017-12-11
> 1048688 -rw-r--r-- 1 root root 498502121 Dec 12 23:59 nginx.access.log-2017-12-12
> 1048593 -rw-r--r-- 1 root root 285525556 Dec 13 12:41 nginx.access.log

Now, logstash sincedb file:

> 1048593 0 64785 640205159
> 1048619 0 64785 689935513
> 1048685 0 64785 717981488
> 1048688 0 64785 599901894

sincedb have not update。

## configuration file

> 
> $ cat /usr/local/logstash/etc/wscdn.conf
> 
> 
> input {
>     file {
>         type => "ws"
>         sincedb_path => "/usr/local/logstash/etc/sincedb/ws.sincedb"
>         path => "/data/logs/cdnlog/zs/ws/nginx.access.log-*"
>         ignore_older => 0
>         start_position => beginning
>     }
> }
> ......

> $ ls  /data/logs/cdnlog/zs/ws/*|wc -l 
> 53

## get number of inode

> $ ls -i /data/logs/cdnlog/zs/ws/nginx.access.log-2017-11-02 
> 1048649 /data/logs/cdnlog/zs/ws/nginx.access.log-2017-11-02 

## delete log file

> $ rm -f  /data/logs/cdnlog/zs/ws/nginx.access.log-2017-11-02 

## get logstash pid

> $ ps aux |grep wscdn
> root     10903 47.5  1.9 3937516 313452 pts/0  Sl   11:32   0:24 /usr/local/jdk/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Xmx1g -Xss2048k -Djffi.boot.library.path=/usr/local/logstash-2.4.1/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/logstash/heapdump.hprof -Xbootclasspath/a:/usr/local/logstash-2.4.1/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/local/logstash-2.4.1/vendor/jruby -Djruby.lib=/usr/local/logstash-2.4.1/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /usr/local/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /usr/local/logstash/etc/wscdn.conf -l /data/logs/logstash/wscdn.log
> 

## get number of files in directory

> $ ls  /data/logs/cdnlog/zs/ws/*|wc -l 
> 52

## get number of record in sincedb file

> $ wc -l ws.sincedb 
> 53 ws.sincedb

## kill logstash process

> $ kill 10903
> stopping pipeline {:id=>"main"}
> Pipeline main has been shutdown
> 
> [1]+  Done                    JAVA_HOME=/usr/local/jdk /usr/local/logstash/bin/logstash -f /usr/local/logstash/etc/wscdn.conf -l /data/logs/logstash/wscdn.log
## get number of record in sincedb

> $ wc -l ws.sincedb 
> 53 ws.sincedb

## find inode of file deleted

> $ grep 1048649  /usr/local/logstash/etc/sincedb/ws.sincedb
> 1048649 0 64785 586658237

**Comment by guyboertje** [comment]
This issue should have been opened in the file input plugin repo.

Linking there and closing here.
