### ISSUE TITLE
Document recommendation for LS to LS communication

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#9021]
Historically, we have suggested to use lumberjack output to Beats input for LS to LS communication. With enhancements being made to the HTTP output/input, we will soon be recommending the HTTP protocol for this use case moving forward.

There are a two core dependencies to making this a viable solution:
- [x] HTTP output JSON batching - https://github.com/logstash-plugins/logstash-output-http/pull/78
- [ ] HTTP output to multiple hosts (load balancing for fan-out architecture) - https://github.com/logstash-plugins/logstash-output-http/issues/83

/cc @jsvd @dedemorton @karenzone

**Comment by jordansissel** [comment]
> we will now 

"now" is pending some code landing in a release. I don't' think either of the above PRs are in a public release yet.

**Comment by acchen97** [comment]
@jordansissel changed to "soon." HTTP output v5.2.0 is published.

**Comment by karenzone** [comment]
@acchen97  I believe this is the one that you were going to look at and perhaps close because the product took a different direction.

**Comment by acchen97** [comment]
@karenzone thanks, closing...

**Comment by praseodym** [comment]
Will the recommentation change to HTTP-to-HTTP or will Lumberjack-to-Beats stay as [the recommended solution](https://www.elastic.co/guide/en/logstash/master/ls-to-ls.html)?

**Comment by acchen97** [comment]
@praseodym the documented solution will remain the recommended approach.
