### ISSUE TITLE
Cleanup for versioned plugin docgen

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#9048]
Remaining tasks:
- [ ] Cleanup of source files [also described here](https://github.com/elastic/logstash-docs/pull/463#issuecomment-360108232)
a) massively apply the data type link conversions to all plugins (example PR for 1 plugin that addresses only the data type conversions: logstash-plugins/logstash-output-elasticsearch#728)
b) fix the remaining broken docs for these 26 plugins - (already merged plugins listed in https://github.com/elastic/logstash-docs/pull/463)
c) mass release plugins with doc changes
- [x] Modify the version plugin gen script so that the include_path gets set to `:include_path: ../include/6.x`.  We'll need to search/replace until the script is fixed. NOTE that the include paths in the plugins folder (for main Logstash Ref) need to stay as-is for the LS Reference build to work.
- [x] Need a plan for running the script periodically to publish new versions of the plugins.
- [x] [DeDe] Add info about generating the plugin docs (the plugins for the Logstash Ref and the Versioned LS Plugin Reference (where the files live, what the tool does, and how generate the files and build the books). Should probably have an overall doc that talks about generating plugin docs and add a section about the versioned docs.
- [x] Automate the generation of the versioned documentation so that a new version of the docs is generated/published whenever a new version of a plugin is released.

Outstanding problems to solve:

- [ ] In the VPR, we use the `logstash-ref` attribute in the [index.asciidoc](https://raw.githubusercontent.com/elastic/logstash-docs/versioned_plugin_docs/docs/versioned-plugins/index.asciidoc) file to set the URL for links that point to the Logstash Reference (`:logstash-ref: http://www.elastic.co/guide/en/logstash`). These links will break over time as we add content. At some point, we need to use versioned links so that the VPR points to whatever version of the Logstash Reference was current when the plugin was released. To do this, the docgen script would need to add an attribute that overrides the path. So, along with the other attributes that the docgen adds, it would add something like the following to each generated file: `:logstash-ref: http://www.elastic.co/guide/en/logstash/7.0`.
- [ ] Versioning of common files. When common files change, need to create a new folder at the same level as [`include/6.x`](https://github.com/elastic/logstash-docs/tree/versioned_plugin_docs/docs/versioned-plugins/include/6.x) and have the script set the `include_path` attribute to point to the branch for any new files that it generates.

**Comment by dedemorton** [comment]
@karenzone Removing my name and adding yours. I think *a lot* of these items are already done, but wanted you to be aware of this issue.

**Comment by karenzone** [comment]
Thank you, @dedemorton!  This one had slipped by me.

**Comment by dedemorton** [comment]
@jsvd I've clarified the description ^^ here a bit because I had a little time following the details myself when I re-read it today. :-P

**Comment by dedemorton** [comment]
Closing old issue. Feel free to open another issue if you think there's still work that needs to be tracked here.
