### ISSUE TITLE
add logstash plugin

### ISSUE THREAD

**Issue by ver007** [elastic/logstash#9075]
We really like logstash and have tried writing an analysis plugin
We have an open source logstash-attackfilter plugin https://github.com/anbai-inc/AttackFilter hoping to join the list of GitHub https://github.com/logstash-plugins plug-ins.
Expect to reply  root@jeary.org

**Comment by jsvd** [comment]
Apologies for not having responded to this. I'm closing the issue as the plugin is no longer available, but we now have a process to list plugins on our docs so please open a new issue if there's ever a renewed interest.
