### ISSUE TITLE
Command line reference for bin/logstash-keystore

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#9084]
`6.2.0` will release a new tool `bin/logstash-keystore`.   There will be general documentation for working with the keystore https://github.com/elastic/logstash/pull/9044 that lightly documents this tools usage. 

However, we should have a dedicated on-line reference page for this command line tool. The reference page should document the options available and basic usage.

**Comment by jakelandis** [comment]
@karenzone - probably not needed. I wasn't sure if we provided reference documentation for every command line tool. I think the existing doc is sufficient, unless there is a standard that every command line tooling has a dedicated reference.

**Comment by karenzone** [comment]
Covered here:  https://www.elastic.co/guide/en/logstash/6.x/keystore.html#keystore-location
