### ISSUE TITLE
Logstash 6.1.3

### ISSUE THREAD

**Issue by hello4usharath** [elastic/logstash#9088]
Not able to start more than 2 processes in new logstash.

**Comment by marioluan** [comment]
What do you mean by |start processes in logstash"?
Did you mean you can't have more than X processes running on the same box?

**Comment by hello4usharath** [comment]
I have installed elastic search kibana and Logstash in one vm. Only 2 Logstash process am able to run.

**Comment by marioluan** [comment]
What happens when you try to spin the third logstash process?

**Comment by hello4usharath** [comment]
It gets exited

**Comment by marioluan** [comment]
@hello4usharath can you share your config?

**Comment by andrewvc** [comment]
Closing due to a lack of response. Thanks for helping this user out @marioluan !
