### ISSUE TITLE
Message size

### ISSUE THREAD

**Issue by Nurlan199206** [elastic/logstash#9102]
Hi everyone.

I am harvesting logs from my application. My application logging 10 strings in a row, example below, but Kibana showing only one string(screenshot). how to fix that?

![kibana](https://user-images.githubusercontent.com/22808731/35841830-6adec5e2-0b28-11e8-803d-c28b58f59ea7.jpg)

========= 2018-02-06 06:24:27 =========
IP: 172.27.34.17
COUNTRY: KZ
UID: 12910
UNAME: user.name
URL: /page/call//index.php
REFERER: http://172.27.1.40
REQUEST: 
USER_AGENT: 
Время запросов к базе: 2.3442130088806
Время выполнения: 2.3491680622101

**Comment by saravanak** [comment]
A newbie here, but can you try using the `multiline` codec? I tried it for `stdin` with the following config and it seemed to work for your example:

```
input {
  stdin{
    codec => multiline {
      # Append all lines to the 'previous' message which don't start with a === string. 
      pattern => "^==="
      negate => true
      what => "previous"
    }
  }
}
output{
  stdout{}
}

```

**Comment by Nurlan199206** [comment]
where to add this config?

> input {
  stdin{
    codec => multiline {
      # Append all lines to the 'previous' message which don't start with a === string. 
      pattern => "^==="
      negate => true
      what => "previous"
    }
  }
}
output{
  stdout{}
}
>

**Comment by saravanak** [comment]
@Nurlan199206 , That config was not supposed to work verbatim, it was an example to show that you can use the `multiline` codec. You will have to adopt this config to your setup.

**Comment by andrewvc** [comment]
Github issues are for bugs only. Can you please ask this question on our discuss forum instead? You can find it at https://discuss.elastic.co/c/logstash
