### ISSUE TITLE
Elasticsearch plugin stopped support older ES (version < 2.0) 

### ISSUE THREAD

**Issue by kzhou57** [elastic/logstash#9124]
It works with logstash 5.2 , but not  in 6.2 anymore. 

Errors suggested something to do with the scroll id changes from ES 1.x to 2.0.

**Comment by kzhou57** [comment]
Similar issue happened to ES remote reindex feature and fixed in ES 5.3 as well.

**Comment by jordansissel** [comment]
I assume this is about the elasticsearch input plugin? This is being tracked https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/89 -- let's track this over there.
