### ISSUE TITLE
Deprecated warnings may leak sensitive data to the log.

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#9138]
When a feature is deprecated, we kindly provide the full plugin configuration. If that plugin configuration contains sensitive data, it can end up in the log un-masked.

**Comment by andrewvc** [comment]
That was fixed in https://github.com/elastic/logstash/pull/8785. Is this verified in current releases?

**Comment by jakelandis** [comment]
Apologies for the noise, this was noticed in an elder version of Logstash.  I just confirmed that is resolved in the current release.
