### ISSUE TITLE
dissect filter 1.1.3 yanked from rubygems broke a bunch of builds

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#9151]
6.2, 5.6, and a few other versions of Logstash have `logstash-filter-dissect` pinned to 1.1.3 in the lockfile. This gem version was yanked this morning, and as a result, all the builds are failing.

This is an amusing consequence of a well-intended fix. Computers are neat ;)

I think it will be an easy fix:

Proposal:
* Update the lockfiles to target dissect v1.1.4

**Comment by jordansissel** [comment]
@danhermann When fixing this, can  you check all branches. I have this:

```
% echo 5.{5,6} 6.{0,1,2,x} master | xargs -n1 sh -c 'PAGER=cat git grep "logstash-filter-dissect (" origin/$1 -- "Gemfile.*.lock.release"' -
origin/5.5:Gemfile.jruby-1.9.lock.release:    logstash-filter-dissect (1.0.12)
origin/5.6:Gemfile.jruby-1.9.lock.release:    logstash-filter-dissect (1.1.3)
origin/6.0:Gemfile.jruby-2.3.lock.release:    logstash-filter-dissect (1.1.2)
origin/6.1:Gemfile.jruby-2.3.lock.release:    logstash-filter-dissect (1.1.3)
origin/6.2:Gemfile.jruby-2.3.lock.release:    logstash-filter-dissect (1.1.3)
```

5.6, 6.1, and 6.2 branches appear affected.

**Comment by guyboertje** [comment]
Dissect v1.1.3 was published (probably by me) to rubygems with the jar from
1.1.1 in it - meaning that it was effectively a downgrade from 1.1.2!

I yanked it after publishing 1.1.4.

I apologise for not doing the branch update PR before the yank. I didn't
know about that step when yanking a plugin gem.

**Comment by jordansissel** [comment]
Hey no worries - it’s amusing how sometimes a small change has unintended
effects elsewhere :)
