### ISSUE TITLE
[6.2.1] Debian package overwrites pipelines.yml

### ISSUE THREAD

**Issue by abraxxa** [elastic/logstash#9164]
- Version: 6.2.1
- Operating System: Debian 8
- Config File: edited pipelines.yml, doesn't matter which content it has
- Steps to Reproduce:
Install Logstash 6.2.0 using the Debian package
edit pipelines.yml
Update to Logstash 6.2.1 using the Debian package
check pipelines.yml, it got overwritten by the Debian package without asking

Looks to me like a packaging error because as far as I know deb's would display a question asking about overwriting of changed config files, maybe pipelines.yml isn't defined as config file.

**Comment by jakelandis** [comment]
@abraxxa -  this is a bug and fixed with `6.2.2` via https://github.com/elastic/logstash/pull/9130

**Comment by abraxxa** [comment]
Thanks!
