### ISSUE TITLE
logstash6.2.1 cannot read Kafka data

### ISSUE THREAD

**Issue by super-l** [elastic/logstash#9165]
**logstash.version：6.2.1
logstash-input-kafka (8.0.4)**

**/etc/logstash/conf.d/first.conf：**

input {
    kafka {
        bootstrap_servers=> ["118.13.32.225:9092"]
        group_id => "test"
        consumer_threads => 1
        decorate_events => true
        topics => ["test"]
    }
    tcp {
        port => 5000
        type => rsyslog
    }
    udp {
        port => 5000
        type => rsyslog
    }
}

output {
    stdout {}
}

**/var/log/logstash/logstash-plain.log:**

[2018-02-17T22:54:22,484][INFO ][org.apache.kafka.clients.consumer.ConsumerConfig] ConsumerConfig values: 
        auto.commit.interval.ms = 5000
        auto.offset.reset = latest
        bootstrap.servers = [198.13.38.255:9092]
        check.crcs = true
        client.id = logstash-0
        connections.max.idle.ms = 540000
        enable.auto.commit = true
        exclude.internal.topics = true
        fetch.max.bytes = 52428800
        fetch.max.wait.ms = 500
        fetch.min.bytes = 1
        group.id = test
        heartbeat.interval.ms = 3000
        interceptor.classes = null
        internal.leave.group.on.close = true
        isolation.level = read_uncommitted
        key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
        max.partition.fetch.bytes = 1048576
        max.poll.interval.ms = 300000
        max.poll.records = 500
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
        receive.buffer.bytes = 65536
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 305000
        retry.backoff.ms = 100
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        session.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

{:address=>"0.0.0.0:5000", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2018-02-17T22:54:22,625][INFO ][org.apache.kafka.common.utils.AppInfoParser] Kafka version : 1.0.0
[2018-02-17T22:54:22,625][INFO ][org.apache.kafka.common.utils.AppInfoParser] Kafka commitId : aaa7af6d4a11b29d

**Logstash can get data on TCP and UDP ports, but Kafka can't。And I can use Python to connect Kafka to send and consume data. It should not be a network problem.**

**Comment by super-l** [comment]
I've solved this problem because of the bug version of the kafka0.9 version。

**https://issues.apache.org/jira/browse/KAFKA-3547**


A regression in 0.9.0 causes the broker to not close a client connection when receiving an unsupported request.
Two effects of this are:
the client is not informed that the request was not supported (even though a closed connection is a blunt indication it is infact some indication), the request will (hopefully) just time out on the client after some time, stalling sub-sequent operations.
the broker leaks the connection until the connection reaper brings it down or the client closes the connection

**Comment by jordansissel** [comment]
Kafka 0.9 is unsupported

**Comment by super-l** [comment]
thanks
