### ISSUE TITLE
Logstash running out of Memory

### ISSUE THREAD

**Issue by bhanukarumudi** [elastic/logstash#9169]
Logstash is running out of memory and crashing.
Is is generating hprof file and file see that there are about 3 million 'java.util.concurrent.ConcurrentHashMap$Node' objects.
Not able to upload the dump file

it sounds similar to the issue discussed at the below url:
https://github.com/elastic/logstash/issues/8019
But I dont see a solution or version details there.

For all general issues, please provide the following details for fast resolution:

- Version: logstash 5.2.1
- Operating System: Red Hat Enterprise Linux Server release 6.7
- Config File (if you have sensitive info, please remove it):
- Sample Data: We are infact doing add_field and event.set for every event coming in.
- Steps to Reproduce:

The leak suspects are show as:
Problem Suspect 1
The class "org.jruby.util.io.ChannelDescriptor", loaded by "<system class loader>", occupies 571,290,568 (29.84%) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentHashMap$Node[]" loaded by "<system class loader>".

Keywords
java.util.concurrent.ConcurrentHashMap$Node[]
org.jruby.util.io.ChannelDescriptor

Problem Suspect 2
4,201,054 instances of "sun.nio.ch.FileChannelImpl", loaded by "<system class loader>" occupy 705,777,072 (36.86%) bytes. These instances are referenced from one instance of "java.util.concurrent.ConcurrentHashMap$Node[]", loaded by "<system class loader>"

Keywords
java.util.concurrent.ConcurrentHashMap$Node[]
sun.nio.ch.FileChannelImpl

Problem Suspect 3
4,201,057 instances of "java.io.FileOutputStream", loaded by "<system class loader>" occupy 201,650,768 (10.53%) bytes. These instances are referenced from one instance of "java.util.concurrent.ConcurrentHashMap$Node[]", loaded by "<system class loader>"

Keywords
java.util.concurrent.ConcurrentHashMap$Node[]
java.io.FileOutputStream

**Comment by andrewvc** [comment]
Can you try updating to a more recent version of Logstash? A number of memory leaks have been fixed.

Please let us know if this fixes your issue!

**Comment by bhanukarumudi** [comment]
After upgrading to logstash 6.2.3, I don’t see the issue anymore 
Thanks

Regards,
Bhanu
