### ISSUE TITLE
GeoIP Plugin - Offer Expanded MaxMind Data

### ISSUE THREAD

**Issue by ubhackn** [elastic/logstash#9202]
For really quick and easy security analysis of IP data, it would be helpful if the existing geoip plugin could include the GeoIP Anonymous IP database from MaxMind such that we don't need to purchase and maintain the license with them directly. Having a field like geoip.proxy_name would allow for highlighting of traffic from known proxy/anonymizer IPs (like TOR), which we can then use as an additional data point for threat detection.

**Comment by andrewvc** [comment]
Moved to https://github.com/logstash-plugins/logstash-filter-geoip/issues/136
