### ISSUE TITLE
`LS_OPEN_FILES` override by systemd 

### ISSUE THREAD

**Issue by atmosx** [elastic/logstash#9208]
I installed logstash-6.2 on Ubuntu 16.04 through the ES repos. Although the option `LS_OPEN_FILES` is available in `/etc/logstash/startup.options` it's not set because there is a value hardcoded in the systemd init file: 

```
root@logs:/etc/logstash# grep -i nofile /etc/systemd/system/logstash.service
LimitNOFILE=50000
root@logs:/etc/logstash# grep LS_OPEN_FILES startup.options
LS_OPEN_FILES=25000
```
It's a bit confusing. It would be nice to have a systemd file that respects all the flags set in `/etc/logstash/` dir.

**Comment by yaauie** [comment]
IIRC, `startup.options` is a _source_ file that is used to _generate_ the appropriate service configuration for your system (in your case, systemd); if you were to run the system-install again, it should regenerate:

~~~
~~~

**Comment by atmosx** [comment]
Yes, that's right, thanks for the info. I'm closing this ticket.
