### ISSUE TITLE
JVM segmentation fault in logstash 6.2.0 while building rake artifacts:rpm in Docker Container

### ISSUE THREAD

**Issue by sandeepsrkr** [elastic/logstash#9209]
Hi,

While building logstash 6.2.0 rpm artifacts using `rake artifact:rpm` I am getting segmentation fault.
I have attached error file with this.
```
openjdk version "1.8.0_151"
Linux 21f49a9ea5b4 4.1.12-61.1.18.el7uek.x86_64
jruby version 9.1.13.0
JAVA_OPTS='-Dhttp.proxyHost='$proxy' -Dhttp.proxyPort=80 -Dhttps.proxyHost='$proxy' -Dhttps.proxyPort=80'
MAVEN_OPTS=$JAVA_OPTS
RELEASE=1
```

I found this link https://github.com/jruby/jruby/issues/4506 that talks about issue with `jffi` package. I could build logstash 6.1.3 successfully with same configuration but it is failing with 6.2.0. Has there been any change with Java options which I should take care of?

[hs_err_pid3877.log](https://github.com/elastic/logstash/files/1781438/hs_err_pid3877.log)

**Comment by sandeepsrkr** [comment]
Hi @all,
Found that segmentation fault occurs when I try to build logstash source within docker container. 
How to resolve this?
Thanks

**Comment by andrewvc** [comment]
Thanks for the report @sandeepsrkr .This does indeed sound like a jffi issue. Unfortunately, we don't have enough here to repro it. Our own builds are running fine.

Can you provide a docker image where this failure is happening? That would be useful.

**Comment by sandeepsrkr** [comment]
Hi @andrewvc ,

Thanks for helping out. Regarding sharing of docker image please give me some time. Apart from this if you need any other information ? I installed jruby manually, then set USE_RUBY=1. This did not produce segmentation fault. But got failed to identify bundle gem location and always picking up path within logstash installation.
The docker image is built on Oracle Linux 7. 
```
java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

javac -version
javac 1.8.0_151
```

**Comment by kares** [comment]
calling this one a day, please report a new issue if anyone land here ...
