### ISSUE TITLE
Error: Your application used more memory than the safety cap of 6G.

### ISSUE THREAD

**Issue by tomsommer** [elastic/logstash#9210]
After upgrading to Logstash 6.2.2, from 5.X, logstash is constanly running out of memory.

pipeline settings are default. No filters. Just inputs and output to redis.

heap is capped to 10G, but error is thrown at 6G. Server has 6 CPU cores (thus workers).

https://gist.github.com/tomsommer/3fb736bd3323763334e0e798774716ea

**Comment by yaauie** [comment]
@tomsommer I'm seeing a lot of errors indicating that the jruby code being loaded was compiled with a version of java that is newer than what you've got; it may be possible that you've got the JDK for 1.8 installed, but that it's being executed with a prior version of Java:
 - https://stackoverflow.com/questions/23249331/java-unsupported-major-minor-version-52-0
 - https://stackoverflow.com/questions/28541629/unsupported-major-minor-version-52-0-in-ubuntu

Logstash 6.x requires Java 8, (also known as Java 1.8), so you'll need to make sure that you have bot the Java 8 SDK and a Java 8 runtime available and selected:
 - the following should point to a Java8-compatible SDK:
    ~~~
    echo $JAVA_HOME
    ~~~
 - the following should indicate that the first `java` on your path is Java 8:
    ~~~
    java --version
    ~~~

****

Separately, I'm also seeing a lot of exceptions in your pasted STDOUT log indicating that the server on which Logstash is running is hitting limitations with open files (e.g., `Too many open files`).

There are a couple possible reasons for this:
 - your host OS is configured with a lower than necessary file-descriptor limit; OR
 - logstash or one of the plugins you have configured in your pipeline is failing to close file handles behind itself; for this we'll need to get a better idea of what file descriptors are open, which we can do with the following in a bash-compatible shell:
    ~~~
    ls -la "/proc/${LOGSTASH_PID:?pid}/fd"
    ~~~
    and which plugins your pipeline is using, including any relevant versions which you can get with
    ~~~
   bin/logstash-plugin list --verbose $PLUGIN_NAME
    ~~~

**Comment by tomsommer** [comment]
CentOS6:
```
# java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

```

ls:

https://gist.github.com/tomsommer/142513facd7f8d55ea2c5c27dc4dcfc2

**Comment by tomsommer** [comment]
Seems this might be because of a nasty bug in `logstash-input-beats`

**Comment by cybervedaa** [comment]
> Seems this might be because of a nasty bug in logstash-input-beats

@tomsommer - What was that bug? Was it fixed on later versions? Do you have a link to it?
I am facing similar issues with my logstash hosts, running logstash 6.0.0
