### ISSUE TITLE
logstash snmp trap Received log Characters garbled

### ISSUE THREAD

**Issue by zjcnew** [elastic/logstash#9211]
![qq 20180307102600](https://user-images.githubusercontent.com/22335594/37070377-1a950944-21f2-11e8-98b2-c3bdc5fc321a.png)
![qq 20180307100241](https://user-images.githubusercontent.com/22335594/37070378-1dfb40bc-21f2-11e8-9878-19db1cd7fd79.png)

How can I solve it?

**Comment by andrewvc** [comment]
Moved to https://github.com/logstash-plugins/logstash-input-snmptrap/issues/28 , where it belongs
