### ISSUE TITLE
XML Filter Broken with Persistent Queue

### ISSUE THREAD

**Issue by wwalker0307** [elastic/logstash#9213]
When using XML Filter's xpath functions with persistent queueing enabled, the XML filter errors out.  Disabling persistent queue or removing xpath functions resolves the issue.  [See this thread for more information](https://discuss.elastic.co/t/logstash-pipeline-from-6-1-not-working-6-2-1/120548/36)

This issue is present on Windows Server 2012 R2 and Server 2016 running Elastic Stack 6.1.1 and 6.2.2 with Java 8u151, 152, 161, and 162.

I am trying to process files that range in the thousands of lines and data is being dropped because disk queueing cannot be enabled.  Please help.

**Comment by wwalker0307** [comment]
Root cause identified => https://github.com/elastic/logstash/issues/9167

**Comment by andrewvc** [comment]
Fixed as noted in #9167
