### ISSUE TITLE
META: Netty backed plugin configuration name and feature convergance

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#9244]
We will soon have 3 Netty backed plugins, Beats input (existing), TCP input (existing), and HTTP input (coming soon).

Since all 3 have similar architecture and requirements, we should ensure that the configuration options are the same where applicable. 

Specifically these input plugins need to deal with the following:
* Number of workers processing requests
* Max number of request held in memory when the Logstash pipeline is blocked (else out of memory)
* Max number of unique concurrent connections (else out of file descriptors)
* How long connections should remain open while idle (else lots of short lived connections or long lived idle connections...both are appropriate depending on use case)

I propose the following for all 3 existing plugins and future Netty backed plugins:

| Config Name | Functionality | Netty Implementation | Default value |
| --- |  ---  |  ---  |  ---  |
| executor_threads | concurrent decoding and writes to LS queue | Number of EventLoops in EventGroup doing the decoding/writing to LS queue |  LogStash::Config::CpuCoreStrategy.maximum |
| max_concurrent_connections | concurrent number of open socket connections | ChannelOption.SO_BACKLOG | 500 |
| max_pendings_requests | number of pending requests to hold in memory | size limit on taskPendingQueue + RejectionHandler closes connection | 200 |
| tcp_keep_alive (n/a to beats) | true/false to send tcp_keep_alives when in server mode | ChannelOption.SO_KEEPALIVE | false |

### executor_threads
The number of concurrent workers processing the requests. Concurrent request that exceeds this value are counted as pending request.  Increasing this value requires additional CPU and memory. 

### max_pendings_requests
The number of requests held in memory, but not currently being processed.  If the number of requests exceeds this value, the connection will rejected. Clients may start to see connection reset by peer when this value is reached.  Increasing this value requires additional memory. 

### max_concurrent_connections
The max number of unique clients that be connected at the same time. If more then this many unique clients try to connect, then the connection will not be accepted.  Note that if the tcp_keep_alive is enabled, then all connections may remain connected even while idle.  Increasing this value requires additional file descriptors. 

### tcp_keep_alive
Sends a TCP keep alive packet based on the OS settings. Turning this value on will reduces the overhead of short lived connections, but will increase the number of concurrent connections since idle connections will remain connected for much longer.  Turning on this setting can also help to keep connections from timing out if the Logstash pipeline is blocked for long periods of time. It is suggest to only turn this on if needed.

**Comment by jakelandis** [comment]
cc @jsvd @robbavey @original-brownbear

**Comment by jsvd** [comment]
I'm ++ on having similar architectures and design decisions when using netty. I'm not sure if we need to align the default values for these settings.

#### `max_pendings_requests `

> The number of requests held in memory, but not currently being processed. If the number of requests exceeds this value, the connection will rejected.

I think this is meant to say the request will be rejected?

#### `max_concurrent_connections`

this  is the one I'm less comfortable with, so_backlog essentially sets the number of connection requests that can be queued before connections are dropped, it isn't really about the number of concurrent connections we're accepting data from. it could be called something like `max_pending_connection_requests`, but it's too long..

#### `tcp_keep_alive`
 
Not sure if we should recommend turning off by default. The defaults for timing out vary immensely (OS tipically have very large timeouts, some applications have really short ones). [here's an article with some info on keep_alive](http://coryklein.com/tcp/2015/11/25/custom-configuration-of-tcp-socket-keep-alive-timeouts.html)

**Comment by jakelandis** [comment]
> I'm not sure if we need to align the default values for these settings.

++, the defaults should be use case specific (e.g. http should be batched requests, not sure about TCP)

> I think this is meant to say the request will be rejected?

Yeah.. "request" not connection. 

> it isn't really about the number of concurrent connections we're accepting data from

Doh! you are right. Maybe we should leave this out ?  If we close the connection after `max_pending_requests`, it will always take precedence (except for that short time we accept -> reject).  For HTTP since we want to send the 429 but not close the connection, this seems like a HTTP specific setting. 

> Not sure if we should recommend turning off by default.

I think it is always best to let either the client or server dictate how long the connection is open. Under normal operations they are open/closed frequently (but the OS holds open the socket for repeated connections). For not-so-normal operations we should allow the idle timeout the clients sets to be the default, not the server OS tcp keep alive settings.

**Comment by jakelandis** [comment]
Closing this issue.  After working with beats input and inspecting the http input, I am not so confident that we can get a shared set of configurations for the same behaviors.  We can discuss in each project what makes the most sense case by case.
