### ISSUE TITLE
File input read from end not working

### ISSUE THREAD

**Issue by zhangjinzhou** [elastic/logstash#9257]
- Version: 5.6.8
- Operating System: Ubuntu 16.04 LTS
- Config File

```
input {
  file {
    path => "/tmp/logfile.log"
  }
}

output {
  elasticsearch { hosts => ["elasticsearch:9200"] }
}
```
When I use this config file for a file input test, it always read the whole logfile from beginning to the end. For example, if the logfile is empty and I input message 1 to it and save, I can see message 1 in Kibana. Then, in the logfile I hit enter, input message 2 and save. The Kibana shows two new hits. As a result, you can see message 2, message 1, message 1. What could cause the problem?

I am brand new to ELK. Any info would be helpful.

**Comment by andrewvc** [comment]
Thanks for the report! 

Moved to the correct repo: https://github.com/logstash-plugins/logstash-input-file/issues/172

Please track there.
