### ISSUE TITLE
Logstash Keystore Enhancement

### ISSUE THREAD

**Issue by toddferg** [elastic/logstash#9262]
I think it may be a good idea for the logstash keystore to have a password confirmation.  Since once the password is in there, it could be difficult troubleshooting a password issue without being able to verify the password.  This could make less frustrations down the road preventing errors in input.  At least on the stdin option.

**Comment by andrewvc** [comment]
I think this makes sense.

One of our goals is to have parity with the ES password tool. We should research that tool and determine if they do the same there and coordinate.

**Comment by justinkambic** [comment]
@andrewvc the Elasticsearch keystore tool does not have a verification either, as of 6.3.0 RC1.

Should we open a companion enhancement issue in the ES repo?
