### ISSUE TITLE
drop filter with negative performance impact

### ISSUE THREAD

**Issue by GERandro** [elastic/logstash#9266]
Hi logstash people

we recently moved from logstash2 to logstash6.
There was no change in terms of front and backend architecture, meaning we consume from Kafka topics and produce to Kafka topics with several horizontal scaling logstash instances.
Our logstash is playing the role of message parsing and filtering in terms of event dropping.
After we switched to logstash6 we are facing massive performance impact and we cannot consume the messages in the same speed, as with logstash2. (This is about network capture with tshark/tstat etc. with EPS ~10k)
Initially we thought, that this negative performance impact is related to the Kafka output only and missing parallel processes. **### However after we disabled all drop {} filters within the logstash config, the logstash6 performance was as good as before with logstash2.**

I am almost certain, that this negative performance is related to drop filter.
We tuned already batch size (2000), batch delay (50ms) and JAVA HEAP size (32GB) without any performance improvement.

While monitoring the logstash pipeline in Kibana X-pack, the enabled drop filter was always the "orange" collored (high performance) process.

This is our drop logic:

`if [method] == "HTTP" {
                        drop { percentage => 99		 }
                      mutate { add_tag => [ "filterOUT" ]
                               add_field => { "eventfilter" => "HTTP filterOUT 1%" } }
                }
        }
`

Are there any best practices available, how to tune the batch size, if the drop filter is enabled?
If there are any logs required to follow up on this issue, PLS let me know.

Thanks

Andro

**Comment by GERandro** [comment]
Not sure, if this closed issue is going in the same direction 
[LINK](https://discuss.elastic.co/t/filter-drop-performance-varies-by-200x/115154)

**Comment by GERandro** [comment]
we utilize the latest logstash version 6.2.2 for the observation above

**Comment by GERandro** [comment]
as a tmp solution, we might tag events with filterOUT and create a special if condition within the output, to exclude tagged events for delivery to kafka...
However, with this tmp approach, we will loose the option, to still see 1% from the "dropped" events, which is not optimal...

**Comment by nerophon** [comment]
Hi @GERandro, thanks for raising this with us. Actually we have a separate Github org for Logstash Plugins, each plugin having its own repo. The repo for the drop filter plugin is here: https://github.com/logstash-plugins/logstash-filter-drop/. If possible, could you re-create the issue there? Thanks!

**Comment by GERandro** [comment]
[New Issue as requested](https://github.com/logstash-plugins/logstash-filter-drop/issues/14)

**Comment by nerophon** [comment]
Archiving this issue as the new issue is now in the correct location.
