### ISSUE TITLE
Logstash fails to start with /tmp mounted noexec

### ISSUE THREAD

**Issue by jorritfolmer** [elastic/logstash#9288]
Logstash 6.2.3 fails to start with /tmp/ mounted noexec. This seems a regression from version 6.1.4 which works fine with a noexec /tmp.

Mounting /tmp noexec is a security hardening practice for servers and workstations. For example the [CIS Benchmark for Red Hat 7](https://www.cisecurity.org/benchmark/red_hat_linux/) gives the following rationale for mounting /tmp noexec:

> Since the /tmp filesystem is only intended for temporary file storage, set this option to ensure that users cannot run executable binaries from /tmp .

Error in the log:

[2018-03-25T12:23:01,149][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (LoadError) Could not load FFI Provider: (NotImplementedError) FFI not available: java.lang.UnsatisfiedLinkError: /tmp/jffi5534463206038012403.so: /tmp/jffi5534463206038012403.so: failed to map segment from shared object: Operation not permitted

This happens on:
- Logstash 6.2.3
- Red Hat 7.4 Maipo, kernel 3.10.0-693.2.1.el7.x86_64
- openjdk version "1.8.0_144"
- /tmp mounted noexec (mount output: `/dev/mapper/vg-tmp on /tmp type xfs (rw,nosuid,noexec,relatime,seclabel,attr2,inode64,noquota)`

After `mount -o remount,exec /tmp` Logstash 6.2.3 proceeds to start fine.

**Comment by andrewvc** [comment]
We should have a better error message + docs to handle this. Thanks for the report @jorritfolmer

**Comment by danhermann** [comment]
@jorritfolmer, by way of explanation, certain versions of the JRuby runtime and libraries in certain plugins (e.g., the Netty network library in the TCP input) copy executable files to the temp directory which causes subsequent failures when /tmp is mounted noexec. You can specify an alternate directory with the `-Djava.io.tmpdir` setting in the `jvm.options` file if you cannot or do not wish to mount /tmp with exec. We can't change that behavior in the JRuby runtime or the libraries that rely on /tmp, but we can add a more helpful error message and/or improve Logstash documentation to note that requirement.

**Comment by jorritfolmer** [comment]
Ok thanks for the explanation. I found the fellow JRuby users over at Puppet did this:
1) 2014: document the issue and file a JRuby issue (https://tickets.puppetlabs.com/browse/SERVER-160), which doesn't look too succesful.
2) 2016: check and fail fast: (https://tickets.puppetlabs.com/browse/SERVER-1631)

**Comment by danhermann** [comment]
Thank you, @jorritfolmer. We plan to do both of those in this PR: https://github.com/elastic/logstash/pull/9293

**Comment by eins** [comment]
I noticed that the solution for this issue has been partially addressed in the logstash link [ts-temp-dir](https://www.elastic.co/guide/en/logstash/current/ts-logstash.html#ts-temp-dir). However, it seems that the information provided is incomplete.

+ Create a new directory for tmp files:
```sh
 mkdir -p /usr/share/logstash/tmp
 chown logstash:logstash /usr/share/logstash/tmp
 chmod 755 /usr/share/logstash/tmp
 semanage fcontext -a -t logstash_var_lib_t "/usr/share/logstash/tmp(/.*)?"
 restorecon -Rv /usr/share/logstash/tmp

```
+ Specify an alternate directory using the -Djava.io.tmpdir setting in the jvm.options file
```sh
-Djava.io.tmpdir=/usr/share/logstash/tmp
```
+ update  logstash service
```sh
 systemctl edit logstash
#  add:
[Service]
Environment="LS_JAVA_OPTS=-Djava.io.tmpdir=/usr/share/logstash/tmp"

# then
 systemctl daemon-reload
 systemctl restart logstash
```

done 
you should see files in /usr/share/logstash/tmp
```sh
 ls -lx /usr/share/logstash/tmp
jruby-3312
```
tested in AlmaLinux 9.4 📦
