### ISSUE TITLE
logstash  start error 

### ISSUE THREAD

**Issue by xingxing122** [elastic/logstash#9302]
- Version:  logstash  5.4.3  
-  Operating System: centos 7.2 
- Config File (if you have sensitive info, please remove it):
cat /etc/logstash/conf.d/filebeat.conf 
input {
    kafka {
        bootstrap_servers => "10.39.15.13:9092,10.39.15.15:9092,10.39.15.16:9092"
        topics => "k8s-log"
        consumer_threads => 5
        decorate_events => true
        codec => "json"
        type  => "k8s-log"
     }   

}

output {
    if [type] == "k8s-log" {
        elasticsearch {
            hosts => ["10.39.15.2:9200","10.39.15.10:9200","10.39.15.5:9200"]
	    codec => "json"
            index => "filebeat-%{+YYYY.MM.dd}"
        }
     }
}

 systemctl status  logstash 
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-03-29 18:42:02 CST; 4min 9s ago
 Main PID: 25810 (java)
   CGroup: /system.slice/logstash.service
           └─25810 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headles...

Mar 29 18:42:02 kafka-node1 systemd[1]: Started logstash.
Mar 29 18:42:02 kafka-node1 systemd[1]: Starting logstash...
Mar 29 18:42:31 kafka-node1 logstash[25810]: Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
Mar 29 18:42:32 kafka-node1 logstash[25810]: log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAuthCache).
Mar 29 18:42:32 kafka-node1 logstash[25810]: log4j:WARN Please initialize the log4j system properly.
Mar 29 18:42:32 kafka-node1 logstash[25810]: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by andrewvc** [comment]
This is an odd error. It looks like some key jars are missing. Have you modified the JVM classpath in any way?

**Comment by kares** [comment]
closing as stale
