### ISSUE TITLE
Change healthcheck_url port in logstash

### ISSUE THREAD

**Issue by pierikyp** [elastic/logstash#9323]
Hello!

I have a cluster of 3 nodes, which are related respectively to ports 9200, 9201 and 9202. My problem comes when I want to use Logstash and I switch off the node to port 9200. In fact Logstash starts an healthcheck with URL: "http: // localhost: 9200 /" and obviously fails because it finds the door free. I would like to understand how to change the healthcheck_url path so that Logstash at startup will not only check port 9200 (in this case) but also the other ports where I loaded the other active nodes.

I'm using Logsatsh 6.2.2. , Elasticsearch 6.2.2, on Centos loaded on a VM.

This is the log of the error:

[INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] (Connection refused)"}

Thank you!

**Comment by luanmuniz** [comment]
Same problem here

**Comment by andrewvc** [comment]
Thanks for the report, but this belongs in the ES output repo. I've opened an issue for you here: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/755
