### ISSUE TITLE
Syntax highlighting in grok debugger UI?

### ISSUE THREAD

**Issue by joshuar** [elastic/logstash#9353]
It would be great if there was some kind of syntax highlighting in the grok debugger. Right now, it's just all plain text:

![image](https://user-images.githubusercontent.com/7401/38590726-6dfe596a-3d76-11e8-9d8f-28e9547da11b.png)

But being able to see what parts are text and what parts are patterns would be great.  A further distinction between in-built patterns and field names the value is assigned to would be a bonus!

This might mean some custom highlighting format?

**Comment by andrewvc** [comment]
Pinging @ycombinator @justinkambic

**Comment by andrewvc** [comment]
Moved to https://github.com/elastic/kibana/issues/17857
