### ISSUE TITLE
Better box expansion/resizeable text boxed in Grok Debugger UI

### ISSUE THREAD

**Issue by joshuar** [elastic/logstash#9354]
It would be nice if the grok debugger UI had resizeable text boxes and/or the automatic resizing was more intelligent.  Here is an example of the automatic resizing failing to capture all of the entered text:

![image](https://user-images.githubusercontent.com/7401/38590832-fd8d7250-3d76-11e8-87ce-53b6b4046d9f.png)

Note the massive amount of wasted whitespace on this page.  Can we make this better to make more efficient use of the real estate, or at least, give users the option of resizing the boxes as they need themselves?

**Comment by andrewvc** [comment]
Pinging @ycombinator and @justinkambic

**Comment by andrewvc** [comment]
Moved to: https://github.com/elastic/kibana/issues/17856
