### ISSUE TITLE
Encountered a retryable error - code 405

### ISSUE THREAD

**Issue by mrebmeister** [elastic/logstash#9368]
- Version: 6.1.1
- Operating System: Linux
- Config File (if you have sensitive info, please remove it):

/etc/logstash/logstash.yml

path.data: /data_bkp/logstash/data/
path.logs: /data_bkp/logstash/logs/

config.reload.automatic: true
config.reload.interval: 10s

queue.type: persisted
queue.page_capacity: 250mb

dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1024mb

/etc/logstash/conf.d/test.conf
....
output {
	stdout {codec => rubydebug} 
	
	# Write CPDLC log messages to Elasticsearch index
	elasticsearch {
		hosts => ["${LS_XXX_ES_HOST}"]
		user => "${LS_XXX_ES_USER:}"
		password => "${LS_XXX_ES_PASSWORD:}"				
		index => "XXX-%{+YYYY.MM}"
		document_id => "%{[@metadata][uuid]}"
		template => "${LS_XXX_TEMPLATE}"
		template_name => "XXX_template"
		template_overwrite => true

- Sample Data: -

- Steps to Reproduce: the error comes when sending logs to Elaticsearch

[2018-04-12T09:19:11,570][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>405, :url=>"http://xxx.corp:9306/_bulk"}

**Comment by andrewvc** [comment]
This is either a bug with the ES output or, more likely, an issue with your usage. I'm going to close this here, but encourage you to either provide more detail in a question on our discuss forum: https://discuss.elastic.co/c/logstash or write up a bug report in https://github.com/logstash-plugins/logstash-output-elasticsearch . This is most likely, however, a bad proxy given the weird response code.

**Comment by andrewvc** [comment]
I forgot to mention, this repo is only for actual bugs in Logstash core.
