### ISSUE TITLE
Logstash-plugin command error 

### ISSUE THREAD

**Issue by upchair** [elastic/logstash#9391]
Hello,

Please I have a problem with the logstash-plugin command. I have not been able to use it at all since I installed it. As a result I have not been able to install any plugin at all.

I would like to install the PLAIN CODEC plugin but to no avail.

Anytime I run the logstash-plugin command I get the following error:

"Cannot find Java 1.5 or higher".

I have java installed yet I get the same error. I have also set the JAVA_HOME to point to the folder where I have the java executable file.

Can anybody please help me to resolve this problem as I have been on it for the past 24 hours.

Thank You

Richard

- Version: Logstash  6,2,3
- Operating System:  Windows 10
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by andrewvc** [comment]
Apologies @upchair , but we only use github for tracking bugs. https://discuss.elastic.co/c/logstash is our support forum.

I'm going to close this issue as a result.
