### ISSUE TITLE
Input plugin for returning directory contents having ".xyz" extension . 

### ISSUE THREAD

**Issue by codelionel** [elastic/logstash#9400]
I need to return the file names only, from a particular directory as soon as the file is getting created. i tried using "exec" input plugin for this. For achieveing this i wrote a shell script as below :
`(cd /home/development/DEMO/ && ls *.stdout) > /tmp/watchfile ; while true; do (cd /home/development/DEMO/ && ls *.stdout) > /tmp/watchfile2 ; diff -q /tmp/watchfile /tmp/watchfile2 > /dev/null ; if [ $? -ne 0 ] ; then echo "File list changed" ; echo `diff /tmp/watchfile /tmp/watchfile2` ; fi ; cp /tmp/watchfile2 /tmp/watchfile ; done`
Note : the second echo is under accent graves but not showing here properly !
The script is working fine through terminal, but when i try to put this in exec input plugin its throwing error.
 Please suggest how can i achieve this or is their some other plugin i can modifiy & use like the "file" input plugin. Thanks in advance

**Comment by andrewvc** [comment]
Sorry to hear about your issue!

Github issues here are only for bug reports / enhancement requests. Questions about usage should be asked on our discuss forum: https://discuss.elastic.co/c/logstash

Given that this is not the correct venue I'm going to close this issue.
