### ISSUE TITLE
Fix `rake version:set` to update README links for OSS repos

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#9424]
This rake task doesn't handle the new `-oss` artifacts in the README.

**Comment by tkbky** [comment]
@andrewvc I'm interested to help out on this issue. May I know what is the expected output? I have taken a look at the history of the task mentioned and I thought it has been taken care in this [PR](https://github.com/elastic/logstash/pull/9425) unless something I've missed.

**Comment by jsvd** [comment]
@tkbky that is correct 😞  apologies to have mislead you, I'm closing this issue now. Thanks for the heads up.
