### ISSUE TITLE
Logstash fails to create queue

### ISSUE THREAD

**Issue by quulah** [elastic/logstash#9483]
- Version:
6.2.3 and 6.2.4

- Operating System:
Ubuntu 16.04

I have a Logstash instance that keeps crashing due to this bug in a filter: logstash-plugins/logstash-filter-mutate#120.

The crashing may cause the queue to be some how corrupted, since these errors also occur:
```
[2018-04-25T09:37:31,627][ERROR][logstash.pipeline        ] Logstash failed to create queue {:pipeline_id=>"main", "exception"=>"java.io.EOFException: null", "backtrace"=>["org/logstash/com
mon/io/InputStreamStreamInput.java:19:in `readByte'", "org/logstash/common/io/BufferedChecksumStreamInput.java:28:in `readByte'", "org/logstash/common/io/StreamInput.java:42:in `readShort'"
, "org/logstash/ackedqueue/io/FileCheckpointIO.java:104:in `read'", "org/logstash/ackedqueue/io/FileCheckpointIO.java:53:in `read'", "org/logstash/ackedqueue/Queue.java:158:in `open'", "org
/logstash/ackedqueue/ext/AbstractJRubyQueue.java:88:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue$INVOKER$i$0$0$ruby_open.gen:-1:in `call'", "/usr/share/logstash/logstash-core
/lib/logstash/util/wrapped_acked_queue.rb:39:in `with_queue'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:28:in `create_file_based'", "/usr/share/logstash/l
ogstash-core/lib/logstash/queue_factory.rb:29:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:172:in `initialize'", "org/jruby/RubyClass.java:1022:in `newInstance'
", "org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/usr/share/logstash/logstash-co
re/lib/logstash/agent.rb:315:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstas
h/agent.rb:312:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/lo
gstash/agent.rb:299:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logst
ash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb
:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:348:in `block in execute'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:273:in `call19'", 
"org/jruby/RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'", "org/jruby/RubyPro
c.java:289:in `call'", "org/jruby/RubyProc.java:246:in `call'", "java/lang/Thread.java:748:in `run'"]}
```

```
[2018-04-25T09:29:32,474][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"IOError", :message=>"org.logstash.LockException: The queue failed to obtain exclusive access, cause: Lock held by this virtual machine on lock path: /var/lib/logstash/queue/main/.lock", :backtrace=>["org/logstash/ackedqueue/Queue.java:258:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue.java:88:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue$INVOKER$i$0$0$ruby_open.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:39:in `with_queue'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:28:in `create_file_based'", "/usr/share/logstash/logstash-core/lib/logstash/queue_factory.rb:29:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:172:in `initialize'", "org/jruby/RubyClass.java:1022:in `newInstance'", "org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:315:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "usr/share/logstash/logstash_minus_core/lib/logstash//usr/share/logstash/logstash-core/lib/logstash/agent.rb:-1:in `RUBY$method$with_pipelines$0$__VARARGS__'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:312:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:299:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "usr/share/logstash/logstash_minus_core/lib/logstash//usr/share/logstash/logstash-core/lib/logstash/agent.rb:-1:in `RUBY$method$with_pipelines$0$__VARARGS__'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:105:in `block in execute'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:273:in `call19'", "org/jruby/RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:18:in `interval'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:94:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:348:in `block in execute'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:273:in `call19'", "org/jruby/RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:246:in `call'", "java/lang/Thread.java:748:in `run'"]}
```
First I removed the use of the broken mutate filter. Which makes the linked issue disappear. But the error with the queue is still there.

For the queue, I first tried removing the lock file by hand and starting again. That didn't work, so I updated from 6.2.3 to 6.2.4, but the same thing occurs. After renaming the whole queue/main directory, Logstash starts properly so there's something.

There's issue #9220 which lead me to believe that something has corrupted the queued files.

This might be issue #9167 which was fixed in 6.2.4, but the older queue is from 6.2.3.

**Comment by quulah** [comment]
I added the broken float conversions back, Logstash keeps crashing. But I haven't yet seen the queue problems. So it could be that 6.2.4 has fixed this already.

**Comment by mattwwarren** [comment]
We had this problem today on 5.6.9 and were able to resolve it by removing the files from /var/lib/logstash/queue/main/

In our case, the disk filled so it seems likely that a page file became corrupt or somehow incomplete.

**Comment by andrewvc** [comment]
Apologies for this issue, we will look into this soon. We are tracking related issues in #9494

**Comment by alextxm** [comment]
Last week I upgraded from LS 5.6.5 to 5.6.9 and since the upgrade i've been hit by this bug; i've to stop LS and delete the PQ files daily.
Is there any news on a fix for the 5.6.x series ? Otherwise I'll have to roll back to 5.6.5 (as  5.6.6-5.6.8 have a nasty ruby performance bug which was triggering versios 5.6.6+ and had only been fixed in 5.6.9).

**Comment by original-brownbear** [comment]
@alextxm a fix for the `5.6.x` series is incoming here https://github.com/elastic/logstash/pull/9698. I can't give a specific timeline, but it is a priority for us to get it released as soon as possible.

**Comment by original-brownbear** [comment]
Fix for `5.6.x` series merged in https://github.com/elastic/logstash/pull/9698. `6.x` and `master` already have fixes merged => closing here :)

**Comment by ADHB** [comment]
Hi, 
I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by ADHB** [comment]
Hi, 
I use 7.7.0 and I still get corrupted queue in production everytime my container run out of heap memory or disk space. I found a workaround for solving the issue by doing the following: 

1. make a new backup directory

2. copy the content of the queue directory into the new backup directory

3. check how big the queue is with:     du -h -c queue_backup

4. delete the content of the original queue directory 

5. docker restart logstash

6. docker cp queue_backup container:/usr/share/logstash/data/

7. docker exec -u root -it container chown -R logstash:root /usr/share/logstash/data/queue

8. docker exec -u root -it container chmod -R 2755 /usr/share/logstash/data/queue

 

Tests: 

9. docker restart logstash

This will confirm that the queue is not corrupted anymore and logstash have permissions to the new queue folder.

10.  systemctl stop nginx  & du -h -c /var/tmp/logstash/queue

Empty the queue. Stop all data input in the node. Wait for 15 minuttes and check the size of the queue. It should be less that the queue_backup (pkt 2). Restart the container again when you feel the queue is stuck.

11. Check input metrics in Kibana - If you have it set up

**Comment by Andresmonty** [comment]
Hi @ADHB 

I've done the steps you mentioned before. but the docker fall down before I can get in to send the script, any suggestions, Im using docker-compose for ELK. 

thank you
Andrew
