### ISSUE TITLE
Add documentation for Azure Module

### ISSUE THREAD

**Issue by karenzone** [elastic/logstash#9499]
To do:
- Add new topic for Azure Module
- Update Modules overview topic as necessary
- Use this issue for Q/A and other info

**Comment by karenzone** [comment]
@acchen97 @jakelandis  The ArcSite module's primary focus appears to be security . 
Is the Azure module more general purpose?

If you have any random thoughts that might need to go in doc, please feel free to add them here.

**Comment by acchen97** [comment]
Good catch, and it's by design. The SQL DB nav link is for the SQL DB Overview. There's a list viz on the left hand side there that has hyperlinks that enable a user to drill down into a DB specific view. So the DB specific dashboard is effectively hidden from the top level nav. HTH.

**Comment by karenzone** [comment]
Questions:
- WHY is it easier to run module from the command line for setup, and then add the configuration to logstash.yml? Does that give you a chance to figure out how you want to configure so you don't keep changing logstash.yml?

**Comment by karenzone** [comment]
Doc for Azure Module added in #9510 
Significant updates added in #9869
