### ISSUE TITLE
Undefined method value in multipipeline spec

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#9506]
From: https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=centos/69/console

Test case: `LogStash::Pipeline Multiples pipelines should handle evaluating different config`

**Comment by andrewvc** [comment]
I suspect this to be a threadsafety issue. I suspect that the mock for the dlq enabled setting, set here: https://github.com/elastic/logstash/blob/master/logstash-core/spec/logstash/pipeline_spec.rb#L129 is not a threadsafe mock (since rspec mocks aren't threadsafe).

I think the fix here is to actually inject a different threadsafe settings object.

TBH, since this isn't a high priority bug, I'd rather wait till we refactor the Pipeline in Java.

**Comment by kares** [comment]
closing - links are already out-of-date ... so as when we see the issue again we'll open a new one
