### ISSUE TITLE
Logstash event cancellation, expected 2, got 4

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#9507]
From https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=centos/69/console

From spec: LogStash::Pipeline event cancellation should not propagate cancelled events from filter to output

**Comment by andrewvc** [comment]
This is super weird, and, TBH, I'm not sure at all how this could possibly happen.

My best guess is that the size check is not threadsafe, and that the dummy output's internal array was in some weird state. That seems unlikely however.

I cannot repro this however, so I think we should wait for this one to come back around again.

**Comment by kares** [comment]
seems this was already addressed ... at #9517
