### ISSUE TITLE
Remove logstash-output-google_cloud_storage from skip list

### ISSUE THREAD

**Issue by josephlewis42** [elastic/logstash#9511]
`logstash-output-google_cloud_storage` is currently marked as skip in `rakelib/plugins-metadata.json` which seems to mean its documentation is missing from the current Logstash library repo. The most recent published documentation is very out of date so I'd like to get it updated and pulled into the current [output pliugins](https://www.elastic.co/guide/en/logstash/current/output-plugins.html) page.

@jordansissel mentioned in #8266

> It was added to the skip list in 97352c7 (April 2016) with a commit message indicating that it failed to build (#5054). This was back when we were producing an artifact called "all plugins" which would contain all plugins, and we were rejecting plugins for this all-plugins artifact which had problems (test failures, dependency problems, etc). We no longer produce an all-plugins artifact, though.

> @josephlewis42 It's possible that it's safe to remove this plugin from the skip list. Can you open a separate issue for this?

It looks like this is no longer the case:

 * Current Build Status: [![Travis Build Status](https://travis-ci.org/logstash-plugins/logstash-output-google_cloud_storage.svg)](https://travis-ci.org/logstash-plugins/logstash-output-google_cloud_storage)
 * [Rubygems page](https://rubygems.org/gems/logstash-output-google_cloud_storage/) showing the most recent build: 3.0.4
 * Current [gemspec](https://github.com/logstash-plugins/logstash-output-google_cloud_storage/blob/master/logstash-output-google_cloud_storage.gemspec) in master showing version 3.0.4.

**Comment by karenzone** [comment]
@karenzone  Take a look at this

**Comment by karenzone** [comment]
Hi josephlewis42!   
[Google Cloud Storage](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-google_cloud_storage.html) has been in the docs for a while now.  I'm following up with some housekeeping.  

This issue was addressed by these PRs: 
* https://github.com/elastic/logstash/pull/10919
* https://github.com/elastic/logstash-docs/pull/737
