### ISSUE TITLE
Timeline of PQ data format changes

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#9522]
- String encoding changed in LS 6.2.4: https://github.com/elastic/logstash/pull/9307
  - no way to recover corrupted data for this one
- Timestamp encoding changed in LS 6.1.0: https://github.com/elastic/logstash/pull/8130
  - no way to recover Timestamps written before this fix
- BigInteger and BigDecimal encoding changed in LS 6.1.0: https://github.com/elastic/logstash/pull/8205
  - and then reverted before the LS 6.1.0 release? https://github.com/elastic/logstash/pull/8405
- BiValues removed in LS 6.1.0: https://github.com/elastic/logstash/pull/8239
  - Not yet confirmed as a data format change
- Jackson version changes (each version does not necessarily result in a data format change)
  - Jackson 2.9.5 for LS 6.2.4: https://github.com/elastic/logstash/pull/9369
  - Jackson 2.9.4 for LS 6.2.3: https://github.com/elastic/logstash/pull/9182
  - Jackson 2.9.1 for LS 5.5.4, 5.6.3, and 6.1.0: https://github.com/elastic/logstash/pull/8373
    - this one changed the data format though possibly in a way that can be handled in newer releases

**Comment by andrewvc** [comment]
Discussing this with @danhermann and @original-brownbear and @yaauie the following changes would be relevant to users performing upgrades.

## TL;DR

If users are using a version `< 6.2.4` drain your queue before upgrading, then upgrade to 6.2.4+ ONLY. We should fix this by:
  1. Incrementing the PQ version
  2. If users attempt to read pre-6.3.0 queues, display an error message asking them to drain it in the old version

## Bug Details

| Impact | Bug | Version Introduced | Version Fixed | Issue |
|--------|-----|--------------------|--------------|-------|
| Some non-ASCII strings are serialized incorrectly, and cannot be read by 6.2.4. Users should drain their queue before upgrading. These strings would be readable pre-6.2.4 but be corrupted. | String serialization corruption | TBD | 6.2.4 | https://github.com/elastic/logstash/pull/9307 |
| Timestamp values in fields other than `@timestamp` would be serialized as strings. Upgrading to 6.1.0+ will not fix previously serialized data, but will serialize new Events correctly. | Timestamp encoding fixed | 5.4.0 | 6.1.0 | https://github.com/elastic/logstash/pull/8239 |
| Versions prior to 6.1.0 would sometimes corrupt `BigDecimal`, `BigInteger`, `Timestamp`, `Boolean` and potentially other values. These queues must be drained prior to upgrading.   | BiValues | 5.4.0 | 6.1.0 |  https://github.com/elastic/logstash/pull/8239 |

**Comment by andrewvc** [comment]
Mind if we close this since the data has all been merged into #9494 ?
