### ISSUE TITLE
X-pack-integration test suite fails but returns exit code of zero

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#9527]
As an example, in the build below, the test suite failed because the download of the ES snapshot failed:

https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/35/console

**Comment by original-brownbear** [comment]
Fixed in https://github.com/elastic/logstash/pull/9567

**Comment by original-brownbear** [comment]
Same bug also applies to non-pack builds and led to at least #9566 sneaking in :(

**Comment by original-brownbear** [comment]
It still fails now, but CI is red accordingly now that https://github.com/elastic/logstash/pull/9567 is merged. Will add a new issue for the x-pack failure shortly
