### ISSUE TITLE
Can Logstash 6.2.4 run update operation in MongoDB

### ISSUE THREAD

**Issue by HedersonSantos** [elastic/logstash#9528]
I am using Logstash 6.2.4 for replicate data from a MS Sql Server table to a collection MongoDB.  Since the records are inserted in the source table, they can be updated with new information. I need to update these new information in the existing records in MongoDB. Does anyone know if it's possible to update a record in MongoDB using Logstash? How can I do it?
I am using mongodb output plugin. If someone knows other way to do it, I can try.

Thanks.

**Comment by yaauie** [comment]
The GitHub issues is not a proper forum for asking questions and getting general help; please start a thread on the [Community Logstash Forums](https://discuss.elastic.co/c/logstash).
