### ISSUE TITLE
where can i place beats-input conf files after installation from source?

### ISSUE THREAD

**Issue by prashantvidja** [elastic/logstash#9534]
Hello

i have just installaed logstash in my system and i want configure beats input plugin for take all logs from nodes in my kibana dashboard.so where can i place this files in  my system because i did not find any /etc/logstash/conf.d directory.

Thanks

**Comment by yaauie** [comment]
👋 hello.

"How-to"-type questions are best dealt with in the [Logstash Community Forums](https://discuss.elastic.co/c/logstash), so please re-ask over there.

When you do, please include:
 - (a) how you installed Logstash (e.g., via package manager like `yum` or `apt`, from source, from a tarball or zip archive downloaded from elastic.co)
 - (b) what version of Logstash
 - (c) what Operating System
