### ISSUE TITLE
private method `initialize' called for LogStash::Logging::Logger:Class

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#9535]
All plugin tests are failing currently for logstash 6.x/master as [logstash-devutils's rspec_helper calls](https://github.com/elastic/logstash-devutils/blob/master/lib/logstash/devutils/rspec/spec_helper.rb#L27):

`LogStash::Logging::Logger::initialize("file:///" + log4j2_properties)`

But it seems not be available anymore, causing the tests to fail. [Here is an example](https://travis-ci.org/logstash-plugins/logstash-filter-date/jobs/375058466#L1164-L1172):

```
Failure/Error: # encoding: utf-8
NoMethodError:
  private method `initialize' called for LogStash::Logging::Logger:Class
  Did you mean?  initialize_dup
# /home/travis/.rvm/gems/jruby-9.1.13.0/gems/logstash-devutils-1.3.6-java/lib/logstash/devutils/rspec/spec_helper.rb:27:in `<main>'
# ./spec/filters/date_spec.rb:1:in `<main>'
# ./spec/filters/date_spec.rb:3:in `(root)'
No examples found.
```

**Comment by robbavey** [comment]
Additionally, the `info?`/`isInfo` method is no longer present

**Comment by jakelandis** [comment]
It looks related to https://github.com/elastic/logstash/pull/9520/files

cc: @danhermann

**Comment by danhermann** [comment]
Fixed in https://github.com/elastic/logstash/pull/9536.
