### ISSUE TITLE
logstash  failed install on centos7.x

### ISSUE THREAD

**Issue by Hardcore-fs** [elastic/logstash#9552]
Centos 7.4 minimal + latest system patches as of 20180510 (yum update)

followed:
https://www.elastic.co/guide/en/logstash/current/installing-logstash.html

sudo yum install logstash
` Installing : 1:logstash-6.2.4-1.noarch                                                                                                                                                        1/1 
Using provided startup.options file: /etc/logstash/startup.options
Errno::ENOMEM: Cannot allocate memory - systemctl
            spawn at org/jruby/RubyProcess.java:1566
            spawn at org/jruby/RubyKernel.java:1511
        popen_run at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/open3.rb:206
           popen3 at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/open3.rb:102
          execute at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:74
   detect_systemd at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:29
  detect_platform at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:24
           detect at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:18
   setup_defaults at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:153
          execute at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:119
              run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
              run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:114
              run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
           <main> at /usr/share/logstash/lib/systeminstall/pleasewrap.rb:12
Unable to install system startup script for Logstash.
  Verifying  : 1:logstash-6.2.4-1.noarch           
`

**Comment by jorgelon** [comment]
same here. new logstash installation doesnt create the logstash.service file

**Comment by Hardcore-fs** [comment]
Ok found the issue......
The system does not clearly check the memory requirements before the install.
Taking the memory to 5GB+ a  large swap file got a full install & the files created.

I think maybe the memory requirements have increased for the initial install.. but then drop down afterwards.
