### ISSUE TITLE
Startup error Logstash (OpenSSL::X509::StoreError)

### ISSUE THREAD

**Issue by LipatovNikita** [elastic/logstash#9564]
I have installed Logstash and I try to run it with a command: sudo /usr/share/logstash/bin/logstash.
But I get a startup error:
[ERROR] 2018-05-12 20:54:15.228 [main] Logstash - java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (OpenSSL::X509::StoreError) setting default path failed: the 
trustAnchors parameter must be non-empty.

- Version: 6.2.4
- Ubuntu 18.04
- Config File:
```
input {
  kafka {
    bootstrap_servers = "localhost:9092"
    topics = ["cpu_metrics"]
    enable_auto_commit = "true"
    type = "cpu"
  }
}
output {
  if [type] == "cpu" {
    file {
      path => "/home/cpu/cpu.log"
    }
   }
}
```

**Comment by andrewvc** [comment]
Is there a stack trace alongside that error? Can you share more of the log output?

**Comment by jslirola** [comment]
Hello, I am having the same issue, with the same version and O.S.

```bash
$ ./logstash -e 'input { stdin { } } output { stdout {} }'
[ERROR] 2018-05-18 07:45:58.226 [main] Logstash - java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (OpenSSL::X509::StoreError) setting default path failed: the trustAnchors parameter must be non-empty
```

That's all, any suggestion?

**Comment by LipatovNikita** [comment]
It's unbelievable, it fixed the problem!
Thank you very much!

**Comment by mohamed-assem92** [comment]
i had the same problem i found this out:
1- find the current java version using the following command
```bash
sudo update-alternatives --display java
```
2-you should get result like that
```bash
link currently points to /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```
3-use the following command
```bash
cd  /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security
```
4- use the following command
```bash
ln -fs /System/Library/Java/Support/CoreDeploy.bundle/Contents/Home/lib/security/cacerts
```

it should work now

**Comment by invinayak** [comment]
in windows, 10 am facing the same issue what is the resolution in windows 10?
