### ISSUE TITLE
Mutex issue whith grok timeouts

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/logstash#9569]
- Version: 5.4.x / 5.x
- Operating System: Any
- Config File (if you have sensitive info, please remove it): Any using grok
- Sample Data: None
- Steps to Reproduce:

Start logstash with an expensive grok, and then checkout the logs:

Lots of timeouts for grok:

>[2018-05-14T08:20:58,507][WARN ][logstash.filters.grok    ] Timeout executing grok 'xxxx' against field 'message' with value 'xxxx'!

> [2018-05-14T08:21:53,615][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ConcurrencyError: interrupted waiting for mutex: null>, :backtrace=>["org/jruby/ext/thread/Mutex.java:94:in `lock'", "org/jruby/ext/thread/Mutex.java:147:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:58:in `fetch_or_store'", "/usr/share/logstash/logstash-core/lib/logstash/instrument/collector.rb:36:in `push'", "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric.rb:22:in `increment'", "/usr/share/logstash/logstash-core/lib/logstash/instrument/namespaced_metric.rb:24:in `increment'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-3.4.0/lib/logstash/filters/grok.rb:320:in `filter'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-3.4.0/lib/logstash/filters/grok.rb:317:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:43:in `multi_filter'", "(eval):51533:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):51530:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):4757:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:370:in `filter_batch'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:294:in `each'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:293:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:369:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:350:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"]}

The backtrace is the following:

```
"org/jruby/ext/thread/Mutex.java:94:in `lock'"
"org/jruby/ext/thread /Mutex.java:147:in `synchronize'"
"/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb: 58:in `fetch_or_store'"
"/usr/share/logstash/logstash-core/lib/logstash/instrument/collector.rb:36:in `push'" 
"/usr/share/logstash/logstash-core/lib/logstash/instrument/metric.rb:22:in `increment'"
"/usr/share/logstas h/logstash-core/lib/logstash/instrument/namespaced_metric.rb:24:in `increment'"
"/usr/share/logstash/vendor/b undle/jruby/1.9/gems/logstash-filter-grok-3.4.0/lib/logstash/filters/grok.rb:320:in `filter'"
"/usr/share/log stash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-3.4.0/lib/logstash/filters/grok.rb:317:in `filter'"
" /usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'"
"/usr/share/logstash/logst ash-core/lib/logstash/filters/base.rb:164:in `multi_filter'"
"org/jruby/RubyArray.java:1613:in `each'"
"/usr /share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'"
"/usr/share/logstash/logsta sh-core/lib/logstash/filter_delegator.rb:43:in `multi_filter'"
"(eval):51533:in `initialize'"
"org/jruby/Rub yArray.java:1613:in `each'"
"(eval):51530:in `initialize'"
"org/jruby/RubyProc.java:281:in `call'"
"(eval): 4757:in `filter_func'"
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:370:in `filter_batch'"
"o rg/jruby/RubyProc.java:281:in `call'"
"/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queu e.rb:294:in `each'"
"org/jruby/RubyHash.java:1342:in `each'"
"/usr/share/logstash/logstash-core/lib/logstash /util/wrapped_acked_queue.rb:293:in `each'"
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:369:i n `filter_batch'"
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:350:in `worker_loop'"
"/usr/sh are/logstash/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"

```

So it seems that trying to collect the metrics is failing when grok is timing out? The troublesome line is the following:

https://github.com/elastic/logstash/blob/5.4/logstash-core/lib/logstash/instrument/metric_store.rb#L58-L62

**Comment by jakelandis** [comment]
@gmoskovicz 

Since 3.4.0, there have a few major improvements in this area. 

Specifically: 
https://github.com/logstash-plugins/logstash-filter-grok/pull/125/files 
and
https://github.com/logstash-plugins/logstash-filter-grok/pull/131/files  

It looks like when 4.0.0 released it caused some issues on older version of 5.x, there has been additional fixes for 5.x since 4.0.0. I am confident that the latest version of grok works with 5.6+ (it has been tested), but not completely confident about 5.4 + the latest version of grok. You may need to remove the [version constraint](https://github.com/logstash-plugins/logstash-filter-grok/blob/master/logstash-filter-grok.gemspec#L24) to ensure it updates properly.

**Comment by andrewvc** [comment]
@gmoskovicz @jakelandis can we move this to the relevant plugin repo? I'm going to close this here since it isn't a core issue.
