### ISSUE TITLE
Early plugin registry setup breaks tests

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#9573]
We're getting a lot of test breakages in x-pack (now that the infra test runner is fixed). Git bisect traced it to: b31c0d2bed35ccb107d341fcbe4c50eda0ef670d .

Looks like that breaks lots of x-pack tests with failures about `Cannot register new settings...`

@original-brownbear thoughts on this?

**Comment by andrewvc** [comment]
I should mention `x-pack/spec/config_management/hooks_spec.rb` is a representative failing spec.

**Comment by original-brownbear** [comment]
@andrewvc handling this one now :)

**Comment by andrewvc** [comment]
Fixed in #9575
