### ISSUE TITLE
Reading Data From Kafka and use filter json fails with ParserError

### ISSUE THREAD

**Issue by ompraash** [elastic/logstash#9586]
- Version: 6.2.3
- Operating System: RHEL
- Config File :

```
input {
    kafka {
        bootstrap_servers => "127.0.0.1:9092"
        auto_offset_reset => earliest
        topics => ["test"]
        group_id => "test"
    }
}

filter {
  json {
    source => "message"
  }
}

filter {
    if ([fields][topic]=="test") {
        grok {
            match => ["message", "%{DATE:Date}\s+%{TIME:Time}\s+Caller=(%{DATA:Caller})?\s+Operator=(%{DATA:Operator})?\s+Message=(%{DATA:Message})?\s+Version=(%{DATA:Version})?\s+Service=(?<Service>(%{DATA}%{SPACE}%{DATA})|(%{DATA}))?\s+Server=(%{DATA:Server})?\s+KeyCnt=(%{NUMBER:KeyCnt:int})?\s+Key=(%{DATA:Key})?\s+(MsgId=%{DATA:MsgId}\s+)?ElapsedTime=(%{NUMBER:ElapsedTime:int})?"]
    }
  }
}

```

 
- Sample Data:

> 05/15/2018	13:21:28:464	Caller=WORK	Operator=work	Message=GetRelationship	Version=005	Service=RelationshipServer	Server=localhost	KeyCnt=1	Key=D1231231-3-2,	MsgId=6e3e3f84-3f49-496d-a287-3b277a598538	ElapsedTime=64

[2018-05-16T00:44:29,119][WARN ][logstash.filters.json    ] Error parsing json {:source=>"message", :raw=>"05/15/2018\t13:21:28:464\tCaller=WORK\tOperator=work\tMessage=GetRelationship\tVersion=005\tService=RelationshipServer\tServer=localhost\tKeyCnt=1\tKey=D1231231-3-2,\tMsgId=6e3e3f84-3f49-496d-a287-3b277a598538\tElapsedTime=64", :exception=>#<LogStash::Json::ParserError: Invalid numeric value: Leading zeroes not allowed

- Steps to Reproduce:

Filebeat reads the log files, and publishes to topic in kafka. Logstash is reading the kafka topic, and the filter is applied. During the `filter`, json throws an error.

When `kafka` is not used, and `filebeat` sends directly to `logstash` there is no failure.

Cannot go to the log/app owner and ask for correction.

How do we make logstash parse the data as string?

**Comment by andrewvc** [comment]
This repo is only for bugs, not for usage questions. Can you please ask over at https://discuss.elastic.co/c/logstash ? I'm closing this due to it not being the correct venue.
