### ISSUE TITLE
6.2.4 release broke plugin

### ISSUE THREAD

**Issue by josephlewis42** [elastic/logstash#9592]
Hi,

It looks like [this PR](https://github.com/elastic/logstash/pull/9358) in the 6.2.4 Logstash release broke the `logstash-input-google_pubsub` plugin. More info about it is in [this pubsub PR](https://github.com/logstash-plugins/logstash-input-google_pubsub/pull/36).

Reverting the version of `google-java-format` from [1.5](https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format/1.5) to [1.1](https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format/1.1) caused the guava version to drop from 22 (released in 2017) to 19 (released in 2015).

This issue is likely to come up with the four (soon to be five) other Google Logstash plugins to stop working as the Google Cloud API changes.

Is there any way to get the Guava version bumped back up to 20 or above? Or is there something we can do on our side to make sure our Guava JAR is used over the bundled one?

Thanks!

**Comment by andrewvc** [comment]
@josephlewis42 apologies. https://github.com/elastic/logstash/pull/9622 should fix this. The *real* fix is #9215 , which will include a parent last class loader policy that will let you bundle your own Guava.

**Comment by josephlewis42** [comment]
@andrewvc thank you so much!

**Comment by danhermann** [comment]
@andrewvc, can this be closed if #9622 fixes it?

**Comment by danhermann** [comment]
Fixed in #9622 and #9836.
