### ISSUE TITLE
Integrity check on file vendor\maxmind-db\reader\autoload.php

### ISSUE THREAD

**Issue by ejouvin** [elastic/logstash#9598]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: 3.5.0
- Operating System: Ubuntu
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:
Download package from http://builds.matomo.org/piwik-3.5.0.tar.gz
Install the application.
On integrity check the file vendor\maxmind-db\reader\autoload.php is marked as unexpected, even if it comes from the package.

**Comment by andrewvc** [comment]
Please post all product and debugging questions on our forum. Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
