### ISSUE TITLE
Logstash parse .rb files indie pipeline dir as configuration files

### ISSUE THREAD

**Issue by alepuccetti** [elastic/logstash#9613]
For all general issues, please provide the following details for fast resolution:

- Version: 6.2.3
- Operating System: Docker
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

I use ruby scripts and if they are inside the pipeline directory Logstash fails with this error message: `Expected one of #, input, filter, output`.  while isf they are inside a subdirectory such ass `scirpts` it works fine.
I suppose logstash it tries to parse the file as configuration file bu they extension is `.rb`.

Don't know if this is by design or a bug.

**Comment by andrewvc** [comment]
This is by design. That directory is only intended for Logstash configuration files.

**Comment by alepuccetti** [comment]
Thank you for the reply, I spent some time reading the docs but it was not clear to me.
