### ISSUE TITLE
Include path.config associated to pipeline id in logging

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#9630]
Would like to see more detailed logging for this entry.  Currently (6.2), it shows just the pipeline id.  It will be helpful to show also the path.config associated to this pipeline definition so that it is clear to the user reading the log files which specific configuration file this pipeline is reading from, instead of having the id value.

```
[2018-05-21T10:12:44,631][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"pipeline_name", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
```

**Comment by andrewvc** [comment]
I do like this idea. For users using `-e` and `config.string` we would not be able to provide this detail of course.
