### ISSUE TITLE
New Plugin: logstash-input-google_cloud_storage

### ISSUE THREAD

**Issue by josephlewis42** [elastic/logstash#9663]
Hi,

I've created a new Logstash input plugin for reading events from Google Cloud Storage to round out our suite of Google tools. The repo is here: https://github.com/josephlewis42/logstash-input-google_cloud_storage.

The plugin does rely on the Google Cloud client JAR which broke with Logstash 6.2.4, but is staged to be fixed in 6.3.0 due to Guava dependency conflicts: https://github.com/elastic/logstash/issues/9592

Based on this issue https://github.com/elastic/logstash/issues/9333 it looks like you're re-designing the plugin submission process, let us know and we'll be happy to beta-test!

Tagging: @rosbo, @erjohnso

Cheers!
\- Joseph

**Comment by josephlewis42** [comment]
@jsvd thanks for setting up the repo!

@andrewvc I opened a PR and have a gem published: https://github.com/logstash-plugins/logstash-input-google_cloud_storage/pull/1

I also added `rubygems@elastic.co` as an owner to the published gem so you all have permissions to do what you want with it.

**Comment by josephlewis42** [comment]
Thanks @jsvd! Also, thanks for being understanding, we were a little worried about someone grabbing the gem name again...

@andrewvc do you have any feeling about a timeline for getting this reviewed/merged? It's gone through internal review and I'm happy to do the leg-work with Travis CI once it's merged and whatever needs to be done to get the docs published if you can shoot me a sample PR. 

The only reason I ask is I have a user that's trying to use our cloud storage beat -> Logstash -> Elasticsearch when they could just be using the GCS Logstash Plugin and I'd like to be able to advise them better.

Thanks!

**Comment by josephlewis42** [comment]
Any update on this? It's been a couple of months and I'd love to get this merged.

I just made some updates based on comments left for #9512 so the docs should be all ready to go too.

Thanks!

**Comment by mcpate** [comment]
I'm curious where things stand here as well? This would be great to have.

**Comment by hartfordfive** [comment]
I have a use case where I need to read files from GCS to then index in elasticsearch.  I would really like to avoid having to create an application just to get data from GCS to then pass it on to Logstash.  It would be great to see this released in the very near future.
:+1:

**Comment by jamiehynds** [comment]
A new [Google Cloud Storage input ](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-gcs.html)has been added to Filebeat and Elastic Agent, for anyone interested in testing it out :)
