### ISSUE TITLE
Logstash installation on SLES12 depends on /usr/bin/java

### ISSUE THREAD

**Issue by siddharthgoel88** [elastic/logstash#9669]
- Version: 6.2.4
- Operating System: SLES12
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

1. Install and expose Java under some path, example - 
```
JAVA_HOME=/opt/myjava
PATH=$PATH:/opt/myjava/bin
export JAVA_HOME PATH
```
2. Install Logstash RPM -
```
rpm -ivh logstash-6.2.4.rpm
```

With the above steps you will find the following error -
```
Using provided startup.options file: /etc/logstash/startup.options
/usr/share/logstash/vendor/jruby/bin/jruby: line 401: /usr/bin/java: No such file or directory
Unable to install system startup script for Logstash.
```

**Comment by danhermann** [comment]
This is fixed in the 6.3.0 release of Logstash.
