### ISSUE TITLE
one log write twice to different index

### ISSUE THREAD

**Issue by cheesebar** [elastic/logstash#9703]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:6.2.4
- Operating System: centos 7.x
- Config File (if you have sensitive info, please remove it):
i have three configs
[root@localhost conf.d]# cat test.conf 

input {
  tcp {
    port => 8102
  }
}

output {
  elasticsearch {
    hosts => "localhost:9200"
    index => "demo"
   }
}

[root@localhost conf.d]# cat first-pipeline.conf 
input {
    beats {
        port => "5044"
    }
}
 filter {
    grok {
        match => { "message" => "%{COMBINEDAPACHELOG}"}
    }
    geoip {
        source => "clientip"
    }
}
output {
    elasticsearch {
        hosts => [ "localhost:9200" ]
        index => "filebeat-"
    }
}
[root@localhost conf.d]# cat noindex.conf 

input {
  tcp {
    port => 8101
  }
}

output {
  elasticsearch {
    hosts => "localhost:9200"
   }
}

- Sample Data:
when i send to port 8102 some logs, then i can see these logs also in index 'filebeat-' and 'demo', and some filebeat`s log also write to index 'demo'

- Steps to Reproduce:

**Comment by webmat** [comment]
I apologize for the inconvenience, but this is a usage question, and should be
asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
