### ISSUE TITLE
Logstash eating up cpu seldom on some AWS nodes

### ISSUE THREAD

**Issue by ehteshaam** [elastic/logstash#9713]
- Version: logstash-1.2.2-flatjar.jar
- Operating System: Linux  2.6.32-642.4.2.el6.x86_64 #1 SMP Mon Aug 15 02:06:41 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
AWS 
- Config File (if you have sensitive info, please remove it): 
- Sample Data: 
- Steps to Reproduce: It occurs seldom. Goes after restart.

**Comment by yaauie** [comment]
The Logstash 1.x series is rather old no longer maintained.

There is insufficient information in this issue to describe the problem or reproduce the issue; I am closing the issue.
