### ISSUE TITLE
Logstash pipeline started successfully BUT not loading the data

### ISSUE THREAD

**Issue by kaushikbbr** [elastic/logstash#9718]
Hello Team,

I am facing this problem since i started working with logstash.
I am trying to load a CSV as shown in the zip here;

**For once i was successfully able to stash the data**. Later i had to add a column and then stash it again.
So i tried all the following ways;

- Tried to load the data by changing the index name in the same .conf file [_which worked initially_]
- Remove the data from Elastic through Kibana Dev Tools -> Console [_Delete accural-data_].
- Tried to use the same .conf file with command logstash -f accrual-csv.conf [_which worked earlier_]

All the above steps were in vain. Please kindly help?

The below is the conf file i used;

	input {
		file {
			path => "C:\Users\M1045583\Desktop\Logs\Accrual_Data.csv"
			start_position => "beginning"
		}
	}

	filter {
		csv {
			separator => ","
			columns => ["NumberOfActivityUnits", "TransactionDate", "PartnerCode", "JPNumber", "TransactionID", "IP"]
			convert => { "NumberOfActivityUnits" => "integer" }
			skip_header => true	
		}

		geoip {
			source => "IP"
		}
		
		date {
			match => [ "TransactionDate", "dd-MMM-yyyy:HH:mm:ss" ]
			locale => en
		}
	}

	output {
		elasticsearch {
			hosts => "_My cloud instance of elasticsearch_"
			user => "elastic"
			password => "_My password_"
			index => "accural-data"
		}
	}

The zip of the CSV is here : 
[Accrual_Data.zip](https://github.com/elastic/logstash/files/2083755/Accrual_Data.zip)

Below is the screenshot of the logstash where it is stuck!
![image](https://user-images.githubusercontent.com/38374696/41149823-2bedc42a-6b2a-11e8-849b-c7e8874c29cf.png)

**Comment by yaauie** [comment]
Questions like the above are typically better suited for the [Logstash Forums](https://discuss.elastic.co/c/logstash), at least until we've been able to confirm an issue; we use the GitHub Issue tracker to track verified issues as we work toward solving them.

That said, the `file` input plugin keeps a meta-record of how far it has read in each file, called the [`sincedb`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#_tracking_of_current_position_in_watched_files), which allows it to only emit new lines that are appended by an external source. You can either delete the existing `sincedb` or specify a _new_ [`sincedb_path`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-sincedb_path) to get it to start over without record of how far it has been.

If the above doesn't help, please open a new thread in the Logstash Forums (feel free to tag me and to link back here).

**Comment by VSKMurali** [comment]
Hello,

I am also getting same issue "Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}" 

![image](https://github.com/elastic/logstash/assets/130290945/6ee2fd94-03b0-478f-b033-0b5070e6aabf)


input {
  file {
    path => "D:\elk\logs_folder\log1.json"
    start_position => "beginning"
    codec => "json"
    sincedb_path => "NUL"
  }
}

filter {
  json {
    skip_on_invalid_json => true
    source => "message"
    target => "jsonData"
    add_tag => [ "_message_json_parsed" ]
  }

}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "in_elk_test"
  }

  stdout{

  }
}

There is no new line in the log1.json file and I have tried sincedb and sincedb_path also, but still facing same issue
