### ISSUE TITLE
Limit of resources of each pipeline (queue.type MEMORY)

### ISSUE THREAD

**Issue by ranvijayj** [elastic/logstash#9726]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: 6.2.4
- Operating System: Ubuntu 14.04
- Config File (if you have sensitive info, please remove it): 
- Sample Data:
So, I got logstash running. using system-install and I have made it read pipelines file with multiple pipelines..
Earlier, I was running 3 instances of logstash for 3 different logstash.conf files as different services

I want to run the same using pipeline in 6.2.4..

I got them up and running but the heap size etc. are set on a global level and not each pipeline level. 
If any pipeline spikes up, it may bring down all the rest if there is lack of memory.

Earlier I had 3 instances/process of logstash with different Java & LS options..

Can I achieve the same here? Or just control the amount of resources available to a single pipeline?
I know probably I can put limits on persistent type but what about queue.type = memory?

- Steps to Reproduce:

**Comment by yaauie** [comment]
> Please post all product and debugging questions on our [forum]((https://discuss.elastic.co/c/logstash)). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

@ranvijayj In future, you'll find better and faster help by posting this type of question in the [community forums](https://discuss.elastic.co/c/logstash).

To answer your question though, when a pipeline's `queue.type` is `memory`, its queue capacity is limited to the number of workers (`pipeline.workers`; default one per core) _times_ the batch size (`pipeline.batch.size`; default 125); this is also known as "max in-flight".

There is no way to allocate heap per-pipeline, but with judicious use of the above knowledge you can reasonably insulate the pipelines from any individual pipeline from consuming too much heap and taking down the process.
