### ISSUE TITLE
Logstash and Sqlite

### ISSUE THREAD

**Issue by ToMas-hack** [elastic/logstash#9732]
Good, I'm starting to use logstash, and I'm finding problems to read a sqlite database .. I do not know how to configure the .conf file ... any help or example of a .conf file?

**Comment by yaauie** [comment]
For questions about basic usage, the [Logstash Forums](https://discuss.elastic.co/c/logstash) are a great place to get started. You may want to use the [JDBC input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html), which can use the [SQLite driver for JDBC](https://github.com/xerial/sqlite-jdbc).

We reserve GitHub Issues for tracking confirmed issues with Logstash itself, so I'm closing this ticket.
