### ISSUE TITLE
jRuby-OpenSSL requirement different from installed

### ISSUE THREAD

**Issue by mdrisser** [elastic/logstash#9761]
Running /usr/share/logstash/bin/logstash-plugin list results in the following error:

Gem::LoadError: You have already activated jruby-openssl 0.10.0, but your Gemfile requires jruby-openssl 0.9.21. Prepending `bundle exec` to your command may solve this.
  block in setup at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
            each at org/jruby/RubyArray.java:1734
            each at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189
           setup at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
           setup at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:122
          setup! at /usr/share/logstash/lib/bootstrap/bundler.rb:57
         execute at /usr/share/logstash/lib/pluginmanager/list.rb:17
             run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
         execute at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
             run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
             run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
          <main> at /usr/share/logstash/lib/pluginmanager/main.rb:48

- Version: logstash 6.3.0
- Operating System: Ubuntu 18.04 LTS
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce: run /usr/share/logstash/bin/logstash-plugin list

**Comment by CodingMush** [comment]
Same problem for me

**Comment by glowfall** [comment]
Just run `/usr/share/logstash/bin/logstash-plugin update` before

**Comment by mdrisser** [comment]
That did it, thank you!
