### ISSUE TITLE
how to write a grok pattern for the line  "ERROR CODE	: -1ERROR MESSAGE 	: Flow ExceptionERROR	: [FFP.0012.0004] Found no valid records"

### ISSUE THREAD

**Issue by satish16141** [elastic/logstash#9763]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by webmat** [comment]
I apologize for the inconvenience, but this is a usage question, and should be
asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.

Still, here are two Logstash filters that may help you figure this out:

* [Grok plugin](https://www.elastic.co/guide/en/logstash-versioned-plugins/current/v4.0.3-plugins-filters-grok.html). If you use grok, you can also test your grok expressions against test data right from Kibana. Go to Dev Tools / Grok Debugger.
* [Dissect plugin](https://www.elastic.co/guide/en/logstash-versioned-plugins/current/v1.1.4-plugins-filters-dissect.html)
