### ISSUE TITLE
Integration Tests Group 1 is Red in `6.3`

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#9770]
<img width="323" alt="screen shot 2018-06-20 at 15 32 20" src="https://user-images.githubusercontent.com/6490959/41662057-8244c506-74a0-11e8-997b-dc37ea4dc9f5.png">

ITs group 1 is red in `6.3` for quite a while now and has to be fixed.

**Comment by original-brownbear** [comment]
@danhermann fyi

**Comment by original-brownbear** [comment]
This is likely an issue with a plugin.
https://github.com/elastic/logstash/commit/62875dbfd1362482b32c19b7541f7f5be2f25ccc is the first commit that is red for the IT1 run and it's just a doc change.

**Comment by davidkyle** [comment]
@original-brownbear Is this still a blocker for 6.3.1?

If so could you update the release ticket elastic/dev#1012 please

**Comment by original-brownbear** [comment]
@davidkyle removed the blocker label. Sorry about that, the failure is nothing new and was in `6.3.0` already (+ it occurred randomly so it looks like more of an issue with our test infra).

**Comment by yaauie** [comment]
Resolved: we now have green builds :tada: https://logstash-ci.elastic.co/job/elastic+logstash+6.3+multijob-integration-1/73/

Related, bug in `logstash-output-file` was causing tests to stall: https://github.com/logstash-plugins/logstash-output-file/pull/70
