### ISSUE TITLE
how to test  LoggingEventAsyncDisruptorAppender is logging in asynchronously or not 

### ISSUE THREAD

**Issue by harinathbk** [elastic/logstash#9784]
I have tested one LoggingEventAsyncDisruptorAppender which will log just one java class log line in asynchronously. i see this asynchronous log  lines and main thread log lines are timestamp is same. i'm not sure how to prove LoggingEventAsyncDisruptorAppender is logging asynchronous. can you please help me.

logback.xml
========

  <appender name="ASYNC" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
        <appender name="ASYNC-LOG" class="ch.qos.logback.core.FileAppender">
            <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
                <pattern>%d %green([%thread]) %highlight(%level) %logger{30} - %msg%n</pattern>
            </encoder>
            <file>${FEIGN_LOG_FILE}</file>
        </appender>
    </appender>

  <logger name="xx.xxx.xxx" level="INFO" additivity="false">
        <appender-ref ref="ASYNC" />
    </logger>

**Comment by yaauie** [comment]
Questions on the use and configuration of Logstash are typically best handled in the [Logstash Forums](https://discuss.elastic.co/c/logstash), where our developers and the Logstash community assist each other; we use the project Issues on Github to track issues with known reproduction steps.

Or, if your question is related to a potential _contribution_ to the Logstash project, submitting a partial-progress pull-request with notes about your intent would be a good way to start the conversation.
