### ISSUE TITLE
kv filter incorrectly parse messages, which contain keys with no value

### ISSUE THREAD

**Issue by eatroshkin** [elastic/logstash#9786]
Starting from version 5.6.9 logstash incorrectly parse messages, which contains keys with no value.
Can be reproduces with config:

```
input { stdin { } }
filter {
      kv {
        source => "message"
        field_split => "\t"
        value_split => "="
        include_brackets => true
      }
}
output {
  stdout { codec => rubydebug }
}
```

Result of parsing message `a=11	b=	c=33		d=44`:

```
{
    "a" => "11",
    "b" => "c=33",
    "d" => "44",
    "message" => "a=11\tb=\tc=33\td=44"
}
```

logstash version 5.6.8 and before correctly parse the same message:

```
{
    "a" => "11",
    "c" => "33",
    "d" => "44",
    "message" => "a=11\tb=\tc=33\td=44"
}
```
 OS: Ubuntu trusty,
 Logstash installed from this repository `deb https://artifacts.elastic.co/packages/5.x/apt stable main`

**Comment by yaauie** [comment]
I've filed a ticket on the logstash-filter-kv plugin project: https://github.com/logstash-plugins/logstash-filter-kv/issues/65
