### ISSUE TITLE
Logstash with sqllite3 problem

### ISSUE THREAD

**Issue by infinitize** [elastic/logstash#9788]
Logstash version : 6.3.0
Sqlite version : 3.8.2

Hello, I am try to read data from sqlite3 in to elasticsearch with logstash. However I encountered the problem bellow which I searched around the google still could not solved. Plz help me.

[2018-06-26T15:05:43,604][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-06-26T15:05:44,247][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Sqlite path=>"/var/lib/openvas/mgr/tasks.db", type=>"users", id=>"3b53846a9a2849bb3a0332b2243253946fd6a5a8ef32fadde37c4cfd2fc5eecd", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_177a993a-688c-43ba-a447-f0545ef16e68", enable_metric=>true, charset=>"UTF-8">, batch=>5>
  Error: Missing Converter handling for full class name=org.jruby.RubyObjectVar9, simple name=RubyObjectVar9
  Exception: Java::OrgLogstash::MissingConverterException
  Stack: org.logstash.Valuefier.fallbackConvert(Valuefier.java:97)
org.logstash.Valuefier.convert(Valuefier.java:75)
org.logstash.ConvertedMap$1.visit(ConvertedMap.java:35)
org.logstash.ConvertedMap$1.visit(ConvertedMap.java:29)
org.jruby.RubyHash.visitLimited(RubyHash.java:662)
org.jruby.RubyHash.visitAll(RubyHash.java:647)
org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:69)
org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_initialize(JrubyEventExtLibrary.java:72)
org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$1$ruby_initialize.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$1$ruby_initialize.gen)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:721)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:739)
org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
home.logstash_minus_6_dot_3_dot_0.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_sqlite_minus_3_dot_0_dot_4.lib.logstash.inputs.sqlite.RUBY$block$run$2(/home/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-sqlite-3.0.4/lib/logstash/inputs/sqlite.rb:160)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
org.jruby.runtime.Block.yield(Block.java:165)
org.jruby.RubyArray.each(RubyArray.java:1734)
home.logstash_minus_6_dot_3_dot_0.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_sqlite_minus_3_dot_0_dot_4.lib.logstash.inputs.sqlite.RUBY$block$run$1(/home/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-sqlite-3.0.4/lib/logstash/inputs/sqlite.rb:159)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
org.jruby.runtime.Block.yield(Block.java:165)
org.jruby.RubyHash$12.visit(RubyHash.java:1362)
org.jruby.RubyHash$12.visit(RubyHash.java:1359)
org.jruby.RubyHash.visitLimited(RubyHash.java:662)
org.jruby.RubyHash.visitAll(RubyHash.java:647)
org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1319)
org.jruby.RubyHash.each_pairCommon(RubyHash.java:1354)
org.jruby.RubyHash.each(RubyHash.java:1343)
home.logstash_minus_6_dot_3_dot_0.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_sqlite_minus_3_dot_0_dot_4.lib.logstash.inputs.sqlite.RUBY$method$run$0(/home/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-sqlite-3.0.4/lib/logstash/inputs/sqlite.rb:153)
home.logstash_minus_6_dot_3_dot_0.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_sqlite_minus_3_dot_0_dot_4.lib.logstash.inputs.sqlite.RUBY$method$run$0$__VARARGS__(/home/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-sqlite-3.0.4/lib/logstash/inputs/sqlite.rb)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
home.logstash_minus_6_dot_3_dot_0.logstash_minus_core.lib.logstash.pipeline.RUBY$method$inputworker$0(/home/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:512)
home.logstash_minus_6_dot_3_dot_0.logstash_minus_core.lib.logstash.pipeline.RUBY$method$inputworker$0$__VARARGS__(/home/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
home.logstash_minus_6_dot_3_dot_0.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_input$1(/home/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:505)
org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)
org.jruby.runtime.Block.call(Block.java:124)
org.jruby.RubyProc.call(RubyProc.java:289)
org.jruby.RubyProc.call(RubyProc.java:246)
org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
java.lang.Thread.run(Thread.java:748)

**Comment by yaauie** [comment]
As noted clearly in our issue template, you'll have best results posting debugging questions on the [Logstash Forums](https://discuss.elastic.co/c/logstash) which has a wider audience of both developers and community:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
>
> -- https://github.com/elastic/logstash/blob/master/.github/ISSUE_TEMPLATE.md

When posting there, please be sure to include relevant information about your Logstash configuration, including:
 - the relevant portions of your pipeline configurations (notably the contents of `input { sqlite { ... } }`, scrubbed of any credentials); AND
 - which JDBC driver you supplied, and where you acquired it from; AND
 - the schema of your sqlite table; AND
 - your `logstash.yml` configuration (plus any command-line feature flags you may have specified)

**Comment by qiulang** [comment]
I saw someone asked the question at logstash forum, but it didn't get answer either. How exactly can I fix the problem ?
