### ISSUE TITLE
Event.Remove Ruby Filter Issue

### ISSUE THREAD

**Issue by aconite33** [elastic/logstash#9815]
[Forum post here.](https://discuss.elastic.co/t/ruby-filter-event-remove-inconsistent-results/138268/4)

Problem
=======

Event.Remove using the Ruby filter will result in all data removed inside the event.
------------------------------------------------------------------------------------------------------------

- Version: Logstash 6.0.0 and 6.3.0 (Docker)
- OS: Docker
- Config File:

```
input {
    jdbc {
        jdbc_validate_connection => true
        jdbc_connection_string => "jdbc:oracle:thin:@system01.com:1521/sid01"
        jdbc_user => "user01"
        jdbc_password => "supersecretpassword"
        jdbc_driver_library => "/usr/share/logstash/lib/pluginmanager/ojdbc8.jar"
        jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
        statement => "select audit_type, sessionid, os_username, userhost, dbusername, SYSTEM_PRIVILEGE_USED, SQL_TEXT, RETURN_CODE, event_timestamp from sys.unified_audit_trail where to_timestamp(event_timestamp, 'DD-MON-YY HH.MI.SS.FF AM') > :sql_last_value"
        schedule => "*/2 * * * *"
       }
}

filter {
    ruby {
        code => "
            require 'time'
            require 'date'
            event.set('[insertTime]',Time.now.to_i)
        "
    }
    date {
        match => ["insertTime", "UNIX"]
        target => "insertTime"
    }
    if [logType] == "Oracle" {
    # Set the timestamp to the one of dba_audit_trail
    mutate { convert => [ "timestamp" , "string" ]}
    date { match => ["timestamp", "ISO8601"]}
 
    if [comment_text] =~ /(?i)Authenticated by/ {
 
    grok {
    match => [ "comment_text","^.*(?i)Authenticated by: (?<authenticated_by>.*?)\;.*$" ]
     }
 
    if [comment_text] =~ /(?i)EXTERNAL NAME/ {
    grok {
    match => [ "comment_text","^.*(?i)EXTERNAL NAME: (?<external_name>.*?)\;.*$" ]
     }
     }
    }
 
    # remove temporary fields
    mutate { remove_field => ["timestamp"] } }
    ruby {
       code => '
	       event.to_hash.each {|key,value|
		      event.set("[event_data][#{key}]", value)
		      event.remove("[#{key}]")
	}
       '
    }
}

output   {
elasticsearch {
    hosts => ["elastic01:9200"]
    index => "audit_databases_oracle-%{+YYYY.MM.dd}"
}
```
- Sample Data:
```
{
    "@timestamp": "2018-07-02T20:56:26.665Z",
    "@version": "1",
    "sql_text": "select * from unified_view",
    "logType": "Oracle"
}
```

- Steps To Reproduce:

1. Pull data from Oracle DB
2. Using the above config, use a ruby filter to move root data fields into nested event_data object.
3. Confirm that 1 event.remove statement does **NOT** remove all data.
4. Confirm that 2+ event.remove statements **DO** remove all data.

Expected Output:
-----------------------
```
{
    "@timestamp": "2018-07-02T20:56:26.665Z",
    "@version": "1",
    "event_data.sql_text": "select * from unified_view",
    "event_data.logType": "Oracle"
}
```

Actual Output:
------------------

Empty Event, no data inserted into Elasticsearch

Background
----------------

I am using docker instances to run an ES stack (3 Elasticsearches, 1 Logstash).

I'm pulling in data from variety of sources, specifically what I'm having an issue with is JDBC input. I'm pulling from an Oracle DB some audit logs.

I standardize my data by putting the data into a nested object so I can search common tags across multiple sources (Windows/Linux/Oracle, etc.).

Enter my issue. I'm pulling data in from an Oracle query select statement, and then I put it through a ruby filter to extract the key/value pairs, and set new ones for my standard naming convention. When I remove the old root key/value pairs, the event seems to be deleted and nothing gets submitted to ES. When trying to narrow down my issue, I moved my event.remove statement outside of the loop, and noticed that if I do two event.remove statements, I get the result. However if only have one remove statement outside of the loop, the data is intact, with only the specific field removed.

**Comment by yaauie** [comment]
I've followed up on the forum post; this is not a bug in Logstash.
