### ISSUE TITLE
Logstash fails to run if parent folder contains whitespace

### ISSUE THREAD

**Issue by fkelbert** [elastic/logstash#9824]
Logstash 6.3.1
Java 1.8.0_172
Manjaro Linux 4.14.52-1

1. Download logstash-6.3.1.tar.gz
2. Untar into a directory containing whitespaces
3. run ./bin/logstash
4. Results in error message:
Error: Could not find or load main class org.logstash.Logstash
5. Logstash exits

**Comment by m-adams** [comment]
You beat me to it :)

**Comment by colinsurprenant** [comment]
confirmed. This https://github.com/elastic/logstash/blob/db35ced2a7a7ae35bca02735c82e67f4fa269847/bin/logstash#L61-L69 does not handle space in path correctly. Looking for the fix.

**Comment by colinsurprenant** [comment]
PR in #9832 

@fkelbert @m-adams  you should be able to test the above PR by manually patching `bin/logstash` and `bin/logstash.lib.sh`. Let me know if you do.

**Comment by fkelbert** [comment]
@colinsurprenant 
Sorry for letting you wait. #9832 fixes the problem for me. Great work!
