### ISSUE TITLE
some problems about logstash output Elasticsearch error

### ISSUE THREAD

**Issue by hualidi123** [elastic/logstash#9827]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:Elasticsearch,logstash,kibana,filebeat all is 6.3.0
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:
when logstash output,some error happen about the index of Elasticsearch,so data put into Elasticsearch failed,but I modified the configuration of ouput correctly. Previously due to index error data did not put into Elasticsearch. so I want to know how can i re-import data from the wrong place into Elasticsearch.

**Comment by danhermann** [comment]
This is a usage question rather than a bug and should be asked in the Logstash forums at https://discuss.elastic.co/c/logstash.
