### ISSUE TITLE
help !!!! how to get time from the log below?

### ISSUE THREAD

**Issue by zp672087110** [elastic/logstash#9829]
i have a log that needed to analysis,the sample as below:

[ 2018-07-03T20:05:46+08:00 ] 10.10.1.20 /api/user/profile
INFO: HTTP_CODE=200; TOTAL_TIME=0.743615;

i use the grok https://grokdebug.herokuapp.com/ to pattern the log's info
i get the regx: %{SYSLOG5424SD} %{IP} %{URIPATHPARAM}
the below is my filter in logstash's conf file：

filter {
      grok {
           match => { 
              "   message" => "%{SYSLOG5424SD:time} %{IP:hostip} %{URIPATHPARAM:url}\s*%{LOGLEVEL:loglevel}" 
                             }
               }
      date {
              #match => ["time", "yyyy-MM-dd HH:mm:ss", "ISO8601"]
              #target => "@timestamp"
              match => ["time","\[ yyyy-MM-dd'T'HH:mm:ss+08:00 \]","ISO8601"]
              target => "@timestamp"       
          }
      }
after run this ,  i get the time as this format:   [ 2018-07-03T20:05:46+08:00 ]
but i need to convert the time to timestamp ,the date{} can't work 

anyone can help me ?  tks!!!

**Comment by yaauie** [comment]
As mentioned clearly in the issue template, we use issues on GitHub to track issues with clear reproduction steps; for general help configuring Logstash and authoring pipelines, please use the [Logstash forums](https://discuss.elastic.co/c/logstash).

**Comment by zp672087110** [comment]
OK，thanks
