### ISSUE TITLE
Logstash "Failed to parse value" log output not passing JSON filter 

### ISSUE THREAD

**Issue by danielkasen** [elastic/logstash#9845]
So I'm trying to ship logstash logs to ES: Filebeat reads a logstash json file and ships it. Since the LS file is in JSON I would like to just use the JSON filter to parse the file and index it. Now this works for most logs nicely, but ironically the logs that have an incorrect mapping into ES output a json object that doesn't want to pass the JSON filter:

```
{
  "logEvent": {
    "action": [
      "index",
      {
        "_type": "doc",
        "_index": "aws"
      },
      {
        "metaClass": {
          "metaCla\nss": {
            "metaClass": {
              "response": {
                "index": {
                  "error": {
                    "caused_by": {
                      "reason": "Failed to parse value [No] as only [true] or [false] are allowed.",
                      "type": "illegal_argument_exception"
                    },
                    "reason": "failed to parse [Records.additionalEventData.MobileVersion\n]",
                    "type": "mapper_parsing_exception"
                  },
                  "status": 400,
                  "_id": "bjias2QBjkchPuoiwsLz",
                  "_type": "doc",
                  "_index": "aws-2018.07.\n19.11.15-1"
                }
              },
              "action": "[\"index\", {:_id=>nil, :_index=>\"aws\", :_type=>\"doc\", :_routing=>nil}, #<LogStash::Event:0x3018f446>]"
            }
          }
        }
      }
    ],
    "status": 400,
    "message": "Could not index event to Elasticsearch."
  },
  "thread": "Ruby-0-Thread-23@[s3-cloudtrail-logs]>worker1: /usr/share/logstash/logstash-core\n/lib/logstash/pipeline.rb:383",
  "timeMillis": 1532021622137,
  "loggerName": "logstash.outputs.elasticsearch",
  "level": "WARN"
}
```

Now I can see this in the raw log, but sadly never make it into the ES Cluster because the `action` key is an array and it's values aren't handled well (I have to remove the "index" string because it's not a true array of objects). Is there a way we could fix this log line to maybe use { 'type': 'index' } so that array is actually all objects and not a mix?

**Comment by yaauie** [comment]
The value in the `action` key is a _string_ representation of an internal tuple in the Elasticsearch Output Plugin, used for debugging, and is not to be confused with a _serialisation_ of that tuple _(JSON or otherwise)_.
