### ISSUE TITLE
Running logstash from a different Ruby environment possible?

### ISSUE THREAD

**Issue by jbwl** [elastic/logstash#9865]
Sorry if this is a newbie question or misplaced here - I have found no information on this by searching.

I have a Rails app with its own Ruby environment. From this app, I am trying to start logstash via Ruby's system() command, i.e. executing a shell command.

But logstash fails because it seems to be run in the Gem environment of the Rails app, which differs from the global Ruby env I assume logstash needs to run.

The logstash job runs fine when started from the terminal, just not from the Rails app.

What would I need to do start logstash from a different Ruby environment than the one it expects?

Thank you for any help.

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
