### ISSUE TITLE
Add support to configure port in cloud_id

### ISSUE THREAD

**Issue by zanbel** [elastic/logstash#9870]
Using cloud_id in logstash (and beat) when connecting to an ECE hosted deployment will require users to add a redirect rule to their reverse proxy, or load balancer since logstash will always use 443 if no port is specified. This is fine for ESS (where we do forward these requests to the correct port), but will break in case of ECE that listens on a different port by default.

Including the relevant port in the cloud_id will allow this integration to work seamlessly without a need to configure any redirect rules.

This will introduce a breaking change as currently logstash will append $es$kibana so we need to consider how to tackle this in a way that will continue to support the old encoding as well.

**Comment by jsvd** [comment]
solved by #9877
