### ISSUE TITLE
undefined method `multi_filter' logstash 6.3.2

### ISSUE THREAD

**Issue by lsoumille** [elastic/logstash#9871]
Hi,

I tried to migrate from version 6.2.2 to the latest version 6 (6.3.2) on Windows Server 2016.

When I'm starting logstash everythings works perfectly, my pipelines are loaded. But after few seconds logstash throws an error and stops processing.

In version 6.2.2, I'm not facing this issue.

- Version: 6.3.2
- Operating System: Windows Server 2016 / Java 8 (v181)
- I'm using persistent queues

Could you have an explanation to this error message ?

> An unexpected error occurred! {:error=>#<NoMethodError: undefined method `multi_filter' for nil:NilClass>, :backtrace=>["(eval):2596:in `block in initialize'", "org/jruby/RubyArray.java:1734:in `each'", "(eval):2593:in `block in initialize'", "(eval):2615:in `block in initialize'", "org/jruby/RubyArray.java:1734:in `each'", "(eval):2609:in `block in initialize'", "(eval):112:in `block in initialize'", "C:/Program Files/Elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:602:in `block in flush_filters'", "org/jruby/RubyArray.java:1734:in `each'", "C:/Program Files/Elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:601:in `flush_filters'", "C:/Program Files/Elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:642:in `flush_filters_to_batch'", "C:/Program Files/Elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:424:in `worker_loop'", "C:/Program Files/Elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:384:in `block in start_workers'"]}

Thanks in advance for your help,

**Comment by yaauie** [comment]
Somewhere deep in Logstash, we're expecting an object to respond to `multi_filter` (or the java equivalent `multiFilter`), but the object we send the method to is `nil`, ruby's "nothing" object. I'll add notes here about what I've dug up so far, and hopefully we'll be able to get to the root of this quickly.

Open questions:
 - Are you using the [experimental Java Execution Engine](https://www.elastic.co/blog/meet-the-new-logstash-java-execution-engine) (e.g., specifying the `--experimental-java-execution` command-line flag or the `pipeline.java_execution: true` option in your `logstash.yml`)?
 - Can you share your pipeline configuration? If you would like to share _privately_, you can encrypt with [my GPG public key](https://keybase.io/yaauie) and share your public key along with the ciphertext.

***

Let's look at the places where we send `multi_filter` (or its java-land equivalent of `multiFilter`) to any object other than _`self`_:

~~~
./logstash-core/lib/logstash/config/config_ast.rb:211:          events = @generated_objects[:#{variable_name}].multi_filter(events)
./logstash-core/lib/logstash/filter_delegator.rb:44:      new_events = @filter.multi_filter(events)
./logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java:198:            buffer(outputBuffer, filterField.call("multiFilter", inputBuffer))
./logstash-core/src/main/java/org/logstash/config/ir/compiler/FilterDelegatorExt.java:135:        final RubyArray result = (RubyArray) filter.callMethod(context, "multi_filter", batch);
~~~

 - I'm relatively certain that both implementations of "filter delagator" (Java and Ruby) guarantee that the filter they wrap is not nil; both use the passed filter object a fair bit in their initialize methods.
 - The config_ast call site hasn't seen recent change, and an initial deep-dive doesn't turn anything obvious up for me (but I've not been exhaustive yet).
 - there was [significant change](https://github.com/elastic/logstash/compare/v6.2.2...v6.3.2#diff-aa66540c4668f70bc7568433f4dac1ef) to the `DatasetCompiler` between revisions, which makes me fairly wary.

**Comment by yaauie** [comment]
@lsoumille, I paired with @danhermann on this, and the `pipeline.rb` in your backtrace indicates that you are _not_ running the Experimental Java Execution I asked about above, so our scope is limited to the ruby execution (ruling out both `DatasetCompiler` and `FilterDelegatorExt`).

There is a config setting that can be added to your `logstash.yml` that will enable us to dump the entire generated ruby code to the logs, which could be helpful in determining _why_ we're finding a `nil` object where we expect to find a filter:

~~~
config.debug: true
~~~

We must also be logging at least `DEBUG`-level in order for the generated message to be persisted:

~~~
log.level: debug
~~~

If you could share this logging output (publicly or privately), I would be glad to chase it down further.

**Comment by lsoumille** [comment]
Thanks for your reply @yaauie 

_Are you using the experimental Java Execution Engine ?_ 

- No, I gave it a try but some pipelines showed an unwanted behaviour for our use case with too much latencies (Wait 5 minutes and process all the backlog in 1 minute, wait 5 minutes and so on ... kind of batch processing)

_There_ is a config setting that can be added to your logstash.yml that will enable us to dump the entire generated ruby code to the logs, which could be helpful in determining why we're finding a nil object 

- You can find attached the dump done with the debug flags set (encrypted with your key). [debug.log](https://github.com/elastic/logstash/files/2293696/debug.log)

Let me know if you need more for investigating this.

**Comment by KoalaTea** [comment]
Hey, we are also running into this problem. Is there any movement on this ticket? 
We are not using the experimental Java Execution Engine either.

**Comment by arminabf** [comment]
I ran into the same problem with version 6.4.3. Since updating to logstash 6.8.13 I had no more crashes.

**Comment by jsvd** [comment]
Closing here as it seems to be solved. For those landing here please create a new issue if you have this problem.
