### ISSUE TITLE
Some PQ stress tests are failing

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#9878]
Some PQ stress tests which had been consistently working such as `QueueTest.reachMaxUnread` and `QueueTest.concurrentWritesTest` are now failing occasionally though none of the code under test has changed. Neither test actually "fails" but just doesn't complete within a somewhat arbitrary time limit. One possible explanation is that the move to GCP changed the performance characteristics of the machines on which these tests run.

See: https://logstash-ci.elastic.co/job/elastic+logstash+6.4+multijob-unix-compatibility/os=ubuntu/3/console

**Comment by jsvd** [comment]
Another instance of this: https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility/os=ubuntu/6/console:

```
15:32:00 org.logstash.ackedqueue.QueueTest > concurrentWritesTest FAILED
15:32:00     org.junit.runners.model.TestTimedOutException: test timed out after 50000 milliseconds
15:32:00         at sun.misc.Unsafe.park(Native Method)
15:32:00         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
15:32:00         at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
15:32:00         at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
15:32:00         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2168)
15:32:00         at org.logstash.ackedqueue.Queue.readPageBatch(Queue.java:552)
15:32:00         at org.logstash.ackedqueue.Queue.readBatch(Queue.java:525)
15:32:00         at org.logstash.ackedqueue.QueueTest.concurrentWritesTest(QueueTest.java:718)
```
