### ISSUE TITLE
The kafka consumer clientid is suffixed by 0,1,2... 

### ISSUE THREAD

**Issue by yubobo** [elastic/logstash#9934]
using kafka  input plugin, I set  client_id=d9f37fcb  and   consumer_threads => 3  

[org.apache.kafka.clients.FetchSessionHandler] [Consumer clientId=**d9f37fcb-0**, groupId=default_logstash1535012319052] Error sending fetch request (sessionId=INVALID, epoch=INITIAL) to node 99135: org.apache.kafka.common.errors.DisconnectException.

[org.apache.kafka.clients.FetchSessionHandler] [Consumer clientId=**d9f37fcb-1**, groupId=default_logstash1535012319052] Error sending fetch request (sessionId=INVALID, epoch=INITIAL) to node 99135: org.apache.kafka.common.errors.DisconnectException.

[org.apache.kafka.clients.FetchSessionHandler] [Consumer clientId=**d9f37fcb-2**, groupId=default_logstash1535012319052] Error sending fetch request (sessionId=INVALID, epoch=INITIAL) to node 99135: org.apache.kafka.common.errors.DisconnectException.

**Comment by SimplyAmuthan** [comment]
@yubobo I am experiencing the same problem with, how did you resolve this? could you please help me fix this problem

Thank you
Regards
Amuthan

**Comment by boddiguo** [comment]
Error sending fetch request (sessionId=INVALID, epoch=INITIAL) to node 3: org.apache.kafka.common.errors.DisconnectException.
I met this exception with logstash 6.5.3 too, are there any solution for it?

**Comment by SimplyAmuthan** [comment]
Actually, it is an internal error and not at all a blocker, if you notice closely it is INFO, Kafka recover it from automatically.

**Comment by carolcoral** [comment]
I have seen it too.
`Error sending fetch request (sessionId=INVALID, epoch=INITIAL) to node 2: org.apache.kafka.common.errors.DisconnectException`
When i used `consumer.commitAsync();` or `consumer.commitSync();`
How can i fix it?THX

**Comment by tianhao960** [comment]
same issue, but not automatically recover as @SimplyAmuthan said. Kafka clients will  stop consuming and need to restart

**Comment by raphaelauv** [comment]
We have the same issue , with kafka stream 2.0.0 , we do not know how to handle correctly this exception so the app fail
