### ISSUE TITLE
Logstash Input Kafka - SSL issue.

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/logstash#9946]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: 6.3.2
- Operating System: Ubuntu 16.04  4.4.0-133-generic
- Config File (if you have sensitive info, please remove it):
    ssl_truststore_location => "/etc/ssl/certs"
    ssl_truststore_type => "???"
    kerberos_config => "/es1/etc/logstash/krb5.conf"

Values from logs:
ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = /etc/ssl/certs
        ssl.truststore.password = null
        ssl.truststore.type = PKCS

- Sample Data: NA
- Steps to Reproduce: 
[2018-08-28T18:57:27,304][ERROR][logstash.inputs.kafka    ] Unable to create Kafka c
onsumer from given configuration {:kafka_error_message=>org.apache.kafka.common.Kafk
aException: Failed to construct kafka consumer, :cause=>org.apache.kafka.common.Kafk
aException: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaExc
eption: Failed to load SSL keystore /etc/ssl/certs of type PKCS}
[2018-08-28T18:57:27,313][ERROR][logstash.pipeline        ] A plugin had an unrecove
rable error. Will restart this plugin.

There is no documentation info on using ssl_truststore_type except it should be string. What value is to provided use .crt type certificates ? I want to use certificates available in /etc/ssl/certs directory.

**Comment by yaauie** [comment]
Documentation calls out two acceptable values: `jks` and `PKCS12`:

> `ssl.truststore.type`
> - The format of the truststore file. Should be either `jks` to use the Java Keystore format, or `PKCS12` to use PKCS#12 files. The default is `jks`.
>
> -- [Security Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html)

***

As noted in our issue template, GitHub issues on this project are not the place for usage or debugging questions. Our forums reach a much wider audience.

I am closing this issue. Please feel free to open an issue in the proper place (e.g., the [Kafka Input Plugin](https://github.com/logstash-plugins/logstash-input-kafka)) with clear reproduction steps if you are able to isolate a bug or have a clearly-defined feature request.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> 
> -- [ISSUE_TEMPLATE](https://github.com/elastic/logstash/blob/master/.github/ISSUE_TEMPLATE.md)
