### ISSUE TITLE
Using logstash to listen on mirrored ports (similar to Beats)

### ISSUE THREAD

**Issue by ericwentz** [elastic/logstash#9948]
I’m looking for some guidance.  I’d like to have logstash configured to listen on a “mirrored” port from another system (similar to a span port).  Let me give you some details:
System “A” is running Apache on IP address 10.223.49.62 and is sending Apache logs to a syslog server (System “B”) running on 10.223.49.77:514 – I can see logs in my syslog server.
The interface on “B” is set to mirror the traffic to the NIC on my logstash node at 10.223.49.66.
Running tcpdump on the logstash machine (tcpdump port 514 -nnvXSs 0) shows traffic:
10.223.49.62.44344 > 10.223.49.77.514: Flags [P.], cksum 0xf5bb (correct), seq 2854586422:2854586849, ack 3891561648, win 114, options [nop,nop,TS val 954299232 ecr 940318587], length 427
Which tells me that the traffic is at least hitting the NIC.

The input section of the logstash configuration file is:
input {
    tcp {
        port => 514
        codec => plain {charset => "ISO-8859-1"}
    }
  }

Problem is why am I not seeing anything with logstash? I tried setting the NIC to “promiscuous mode” but still do not see anything with logstash.  I did find some articles about using packetbeat with a mirrored interface but would prefer not to introduce an extra layer in my environment.
Has anyone had any success with this type of network monitoring configuration?

Thanks
Eric

For all general issues, please provide the following details for fast resolution:

- Version: 6.3.2
- Operating System: Centos 7.3
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by yaauie** [comment]
As noted in our issue template, GitHub issues on this project are not the place for usage or debugging questions. Our forums reach a much wider audience.

I am closing this issue. Please feel free to open an issue in the proper place (e.g., the [TCP Input Plugin](https://github.com/logstash-plugins/logstash-input-tcp)) with clear reproduction steps if you are able to isolate a bug or have a clearly-defined feature request.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> 
> -- [ISSUE_TEMPLATE](https://github.com/elastic/logstash/blob/master/.github/ISSUE_TEMPLATE.md)
